/// Otomatik üretilen çeviri haritası (am).
const Map<String, String> cevirilerAm = {
  'Aktarılacak tanınan veri bulunamadı.': 'ለማስገባት የሚታወቅ ዳታ አልተገኘም።',
  'Arama': 'ፍለጋ',
  'Aramaya başla': 'መፈለግ ጀምር',
  'Ayarlar': 'ቅንብሮች',
  'Bağla': 'አገናኝ',
  'Bio': 'ባዮ',
  'Bitirdim': 'ጨርሻለሁ',
  'Bunları da Beğenebilirsin': 'እነዚህንም ልትወዳቸው ትችላለህ',
  'Bölüm': 'ክፍል',
  'Bıraktım': 'አቁሜዋለሁ',
  'Dil': 'ቋንቋ',
  'Dil ara...': 'ቋንቋ ፈልግ...',
  'Dizi': 'ተከታታይ ድራማ',
  'Dizi ve filmlerini takip et': 'ተከታታይ ድራማዎችህን እና ፊልሞችህን ተከታተል',
  'Dizi yorumu': 'የድራማ አስተያየት',
  'Dizi, film veya kişi ara...': 'ድራማ፣ ፊልም ወይም ሰው ፈልግ...',
  'Dosya en fazla 30MB olabilir': 'ፋይሉ ቢበዛ 30MB መሆን አለበት',
  'Dosya en fazla {}MB olabilir': 'ፋይሉ ቢበዛ {}MB መሆን አለበት',
  'E-posta': 'ኢሜይል',
  'E-posta veya kullanıcı adı': 'ኢሜይል ወይም የተጠቃሚ ስም',
  'En az 2 harf yaz': 'ቢያንስ 2 ፊደላት ጻፍ',
  'Film': 'ፊልም',
  'Film yorumu': 'የፊልም አስተያየት',
  'Fotoğraf / video ekle': 'ፎቶ / ቪዲዮ ጨምር',
  'Fotoğraf veya GIF — profil ve kapak resmi': 'ፎቶ ወይም GIF — የመገለጫ እና የሽፋን ምስል',
  'Giriş Yap': 'ግባ',
  'Gönder': 'ላክ',
  'Gönderildi': 'ተልኳል',
  'Haftanın Dizileri': 'የሳምንቱ ድራማዎች',
  'Haftanın Filmleri': 'የሳምንቱ ፊልሞች',
  'Henüz izleme kaydın yok': 'እስካሁን የእይታ መዝገብ የለህም',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'እስካሁን ዝርዝር የለህም — ከመገለጫ ትር ፍጠር።',
  'Henüz yorum yok.': 'እስካሁን አስተያየት የለም።',
  'Hesabın bağlandı!': 'መለያህ ተገናኝቷል!',
  'Hesabın yok mu? Kayıt ol': 'መለያ የለህም? ተመዝገብ',
  'Hesabını Bağla': 'መለያህን አገናኝ',
  'Hesap Oluştur': 'መለያ ፍጠር',
  'Kapak resmi ekle': 'የሽፋን ምስል ጨምር',
  'Kaydet': 'አስቀምጥ',
  'Kendinden bahset...': 'ስለ ራስህ ተናገር...',
  'Keşfet': 'አስስ',
  'Kimseyi takip etmiyor': 'ማንንም አይከተልም',
  'Kişi ara': 'ሰው ፈልግ',
  'Kişi yorumu': 'የሰው አስተያየት',
  'Konuk Oyuncular': 'እንግዳ ተዋናዮች',
  'Kullanıcı adı (küçük harf)': 'የተጠቃሚ ስም (በትንንሽ ፊደላት)',
  'Kullanıcı adı ara...': 'የተጠቃሚ ስም ፈልግ...',
  'Liste adı': 'የዝርዝር ስም',
  'Listeye Ekle': 'ወደ ዝርዝር ጨምር',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'በእንግዳ መለያ ላይ ነህ — በኢሜይልህ አገናኘው፣ ዳታህን አታጣ!',
  'Misafir olarak devam et': 'እንደ እንግዳ ቀጥል',
  'Oluştur': 'ፍጠር',
  'Oyuncular': 'ተዋናዮች',
  'Profil': 'መገለጫ',
  'Profil kaydedildi': 'መገለጫ ተቀምጧል',
  'Puanla': 'ነጥብ ስጥ',
  'Puanı Sil': 'ነጥብ ሰርዝ',
  'Puanın': 'ነጥብህ',
  'Sezonlar': 'ምዕራፎች',
  'Sunucu hatası ({})': 'የአገልጋይ ስህተት ({})',
  'S{} · {}. Bölüm': 'ም{} · ክፍል {}',
  'S{}B{} yorumu': 'የም{}ክ{} አስተያየት',
  'Takibi Bırak': 'መከተል አቁም',
  'Takip': 'የሚከተላቸው',
  'Takip Edilenler': 'የሚከተላቸው',
  'Takip Et': 'ተከተል',
  'Takipçi': 'ተከታይ',
  'Takipçi yok': 'ተከታይ የለም',
  'Takipçiler': 'ተከታዮች',
  'Takvim': 'ቀን መቁጠሪያ',
  'Tamam': 'እሺ',
  'Tekrar Dene': 'እንደገና ሞክር',
  'Tekrar dene': 'እንደገና ሞክር',
  'Toplam ekran süresi': 'ጠቅላላ የእይታ ጊዜ',
  'Tüm Zamanların En İyileri': 'የሁሉም ጊዜ ምርጦች',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'ሁሉንም ዳታህን (እይታ፣ ነጥብ፣ አስተያየት፣ ዝርዝር) ከTV Time ጋር ተኳሃኝ በሆነ ZIP መልክ አውርድ ወይም ከሌላ መተግበሪያ የመጣ ZIP አስገባ።',
  'Tümünü Kaldır': 'ሁሉንም አስወግድ',
  'Tümünü İzledim': 'ሁሉንም አይቻለሁ',
  'Türk Dizileri': 'የቱርክ ድራማዎች',
  'Veri içe aktar (.zip)': 'ዳታ አስገባ (.zip)',
  'Verilerim': 'ዳታዬ',
  'Verilerimi dışa aktar (e-posta)': 'ዳታዬን አውጣ (ኢሜይል)',
  'Verilerini dışa aktar': 'ዳታህን አውጣ',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'የሚመጣ ክፍል የለም።\nከድራማው ዝርዝር ገጽ ወደ «እያየሁ ነው» ሁኔታ ቀይር፣ አዳዲስ ክፍሎችን እዚህ ተከታተል።',
  'Yapımları': 'ሥራዎቹ',
  'Yeni Diziler': 'አዳዲስ ድራማዎች',
  'Yeni Liste': 'አዲስ ዝርዝር',
  'Yeni kullanıcı adı (isteğe bağlı)': 'አዲስ የተጠቃሚ ስም (አማራጭ)',
  'Yorum': 'አስተያየት',
  'Yorumunu yaz...': 'አስተያየትህን ጻፍ...',
  'Zaten hesabın var mı? Giriş yap': 'መለያ አለህ? ግባ',
  'ort. {}': 'አማካይ {}',
  'takip': 'የሚከተላቸው',
  'takipçi': 'ተከታይ',
  '{} / {} bölüm': '{} / {} ክፍል',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} ወር',
  '{} bölüm izlendi': '{} ክፍል ታይቷል',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} ደቂቃ',
  '{} gün': '{} ቀን',
  '{} içerik': '{} ይዘት',
  '{} içerik · otomatik': '{} ይዘት · ራስ-ሰር',
  '{} kayıt atlandı (eşleşmedi).': '{} መዝገብ ተዘሏል (አልተዛመደም)።',
  '{} saat': '{} ሰዓት',
  '{} sezon': '{} ምዕራፍ',
  '{} yıl': '{} ዓመት',
  '{}. Bölüm': 'ክፍል {}',
  '{}. Sezon': 'ምዕራፍ {}',
  'Çıkış Yap': 'ውጣ',
  'Ülke': 'አገር',
  'Ülke ara...': 'አገር ፈልግ...',
  'Ülke seç': 'አገር ምረጥ',
  'İlk yorumu sen yaz!': 'የመጀመሪያውን አስተያየት አንተ ጻፍ!',
  'İncelemeler': 'ግምገማዎች',
  'İncelemen (isteğe bağlı)': 'ግምገማህ (አማራጭ)',
  'İptal': 'ይቅር',
  'İzlediklerim': 'ያየኋቸው',
  'İzledim': 'አይቻለሁ',
  'İzledin': 'አይተሃል',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'የእይታ ታሪክህ እና ዝርዝሮችህ ይጠበቃሉ፤ ከአሁን በኋላ ከየትኛውም መሣሪያ መግባት ትችላለህ።',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'የእይታ ታሪክህ፣ ነጥቦችህ፣ አስተያየቶችህ እና ዝርዝሮችህ በZIP መልክ ወደ ተመዘገበው ኢሜይል አድራሻህ ይላካሉ።',
  'İzleyeceğim': 'አያለሁ',
  'İzliyorum': 'እያየሁ ነው',
  'İçe aktarım tamamlandı': 'ማስገባት ተጠናቋል',
  'Şifre': 'የይለፍ ቃል',
  '• profil bilgisi': '• የመገለጫ መረጃ',
  '• {} dizi durumu': '• {} የድራማ ሁኔታ',
  '• {} izleme kaydı': '• {} የእይታ መዝገብ',
  '• {} liste': '• {} ዝርዝር',
  '• {} puan': '• {} ነጥብ',
  '• {} yorum': '• {} አስተያየት',
  '{}+ yapım': '{}+ ሥራዎች',
  'Yorumlar': 'አስተያየቶች',
  'Yorumlar ({})': 'አስተያየቶች ({})',
  'Yorumları ({})': 'አስተያየቶቹ ({})',
  'Listelerim': 'ዝርዝሮቼ',
  'Nereden izledin?': 'የት ተመለከትከው?',
  'Diziye git': 'ወደ ትዕይንቱ ሂድ',
  'TV / Kanal': 'ቲቪ / ቻናል',
  'Sinema': 'ሲኒማ',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'ሌላ',
  'Akış': 'ምግብ ዥረት',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'ዥረትህ ባዶ ነው።\nበምትመለከታቸው ትዕይንቶች እና ፊልሞች ላይ አስተያየት ሲሰጡ እዚህ ይታያል።',
  'Listeleri ({})': 'ዝርዝሮቻቸው ({})',
  'Liste boş.': 'ይህ ዝርዝር ባዶ ነው።',
  'Yanıtla': 'መልስ',
  '@{} kullanıcısına yanıt veriyorsun': 'ለ @{} እየመለስክ ነው',
  'İzlediğim Diziler ({})': 'የተመለከትኳቸው ትዕይንቶች ({})',
  'İzlediğim Filmler ({})': 'የተመለከትኳቸው ፊልሞች ({})',
  'Tümünü gör': 'ሁሉንም እይ',
  'Bildirimler': 'ማሳወቂያዎች',
  'Henüz bildirim yok': 'እስካሁን ማሳወቂያ የለም',
  '@{} yorumuna yanıt verdi': '@{} ለአስተያየትህ መለሰ',
  '@{} yorumunu beğendi': '@{} አስተያየትህን ወደደ',
  '@{} seni takip etti': '@{} ተከተለህ',
  '@{} sana mesaj gönderdi': '@{} መልእክት ላከልህ',
  'Mesajlar': 'መልእክቶች',
  'Mesaj': 'መልእክት',
  'Mesajını yaz...': 'መልእክት ጻፍ...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'እስካሁን ውይይት የለም።\nመገለጫ ከፍተህ መልእክት ላክ።',
  'Şifreni mi unuttun?': 'የይለፍ ቃል ረሳህ?',
  'Şifreyi Sıfırla': 'የይለፍ ቃል ዳግም አስጀምር',
  'E-postadaki kod': 'ከኢሜይል የመጣ ኮድ',
  'Yeni şifre': 'አዲስ የይለፍ ቃል',
  'Sana Özel': 'ለአንተ',
  '{} özetin': 'የ{} ማጠቃለያህ',
  'Yıllık izleme istatistiklerin': 'ዓመታዊ የእይታ ስታቲስቲክስ',
  'Rozetler': 'ባጆች',
  'Verdiğin puan': 'የሰጠሃቸው ደረጃዎች',
  'Ortalama puanın': 'አማካይ ደረጃህ',
  'En çok izlediğin diziler': 'በብዛት የተመለከትካቸው ትዕይንቶች',
  'İlk Bölüm': 'የመጀመሪያ ክፍል',
  '100 Bölüm': '100 ክፍሎች',
  '1000 Bölüm': '1000 ክፍሎች',
  'İlk Film': 'የመጀመሪያ ፊልም',
  '50 Film': '50 ፊልሞች',
  'İlk Yorum': 'የመጀመሪያ አስተያየት',
  '25 Yorum': '25 አስተያየቶች',
  '10 Puan': '10 ደረጃዎች',
  'İlk Takipçi': 'የመጀመሪያ ተከታይ',
  '10 Dizi Bitirdin': '10 ትዕይንቶች ጨርሰሃል',
  'İzlemeyi Bıraktım': 'ማየት አቆምኩ',
  'İzlediği Diziler ({})': 'የተመለከታቸው ትዕይንቶች ({})',
  'İzlediği Filmler ({})': 'የተመለከታቸው ፊልሞች ({})',
  '500 Bölüm': '500 ክፍሎች',
  '5000 Bölüm': '5000 ክፍሎች',
  '10 Film': '10 ፊልሞች',
  '100 Film': '100 ፊልሞች',
  '100 Yorum': '100 አስተያየቶች',
  '50 Puan': '50 ደረጃዎች',
  '100 Puan': '100 ደረጃዎች',
  '10 Takipçi': '10 ተከታዮች',
  '50 Takipçi': '50 ተከታዮች',
  '25 Dizi Bitirdin': '25 ትዕይንቶች ጨርሷል',
  '50 Dizi Bitirdin': '50 ትዕይንቶች ጨርሷል',
  '10 Beğeni': '10 መውደዶች',
  '100 Beğeni': '100 መውደዶች',
  'yazıyor...': 'እየጻፈ ነው...',
};
