/// Otomatik üretilen çeviri haritası (de).
const Map<String, String> cevirilerDe = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Sie haben alles gesehen, wir zeigen es Ihnen von Anfang an',
  'Aktarılacak tanınan veri bulunamadı.':
      'Keine erkannten Daten zum Importieren gefunden.',
  'Arama': 'Suche',
  'Aramaya başla': 'Starte die Suche',
  'Son aramalar': 'Letzte Suchen',
  'Ayarlar': 'Einstellungen',
  'Bağla': 'Verknüpfen',
  'Bio': 'Bio',
  'Bitirdim': 'Abgeschlossen',
  'Bunları da Beğenebilirsin': 'Das könnte dir auch gefallen',
  'Bölüm': 'Episode',
  'Bıraktım': 'Abgebrochen',
  'Dil': 'Sprache',
  'Dil ara...': 'Sprache suchen...',
  'Dizi': 'Serie',
  'Dizi ve filmlerini takip et': 'Behalte deine Serien und Filme im Blick',
  'Dizi yorumu': 'Serienkommentar',
  'Dizi, film veya kişi ara...': 'Serie, Film oder Person suchen...',
  'Dosya en fazla 30MB olabilir': 'Die Datei darf höchstens 30MB groß sein',
  'Dosya en fazla {}MB olabilir': 'Die Datei darf höchstens {}MB groß sein',
  'E-posta': 'E-Mail',
  'E-posta veya kullanıcı adı': 'E-Mail oder Benutzername',
  'En az 2 harf yaz': 'Gib mindestens 2 Buchstaben ein',
  'Film': 'Film',
  'Film yorumu': 'Filmkommentar',
  'Fotoğraf / video ekle': 'Foto / Video hinzufügen',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto oder GIF — Profil- und Titelbild',
  'Giriş Yap': 'Anmelden',
  'Gönder': 'Senden',
  'Gönderildi': 'Gesendet',
  'Haftanın Dizileri': 'Serien der Woche',
  'Haftanın Filmleri': 'Filme der Woche',
  'Henüz izleme kaydın yok': 'Du hast noch nichts angesehen',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Du hast noch keine Listen — erstelle eine im Profil-Tab.',
  'Henüz yorum yok.': 'Noch keine Kommentare.',
  'Hesabın bağlandı!': 'Dein Konto wurde verknüpft!',
  'Hesabın yok mu? Kayıt ol': 'Noch kein Konto? Registrieren',
  'Hesabını Bağla': 'Konto verknüpfen',
  'Hesap Oluştur': 'Konto erstellen',
  'Kapak resmi ekle': 'Titelbild hinzufügen',
  'Kaydet': 'Speichern',
  'Kendinden bahset...': 'Erzähl etwas über dich...',
  'Keşfet': 'Entdecken',
  'Kimseyi takip etmiyor': 'Folgt niemandem',
  'Kişi ara': 'Person suchen',
  'Kişi yorumu': 'Personenkommentar',
  'Konuk Oyuncular': 'Gastdarsteller',
  'Kullanıcı adı (küçük harf)': 'Benutzername (Kleinbuchstaben)',
  'Kullanıcı adı ara...': 'Benutzername suchen...',
  'Liste adı': 'Listenname',
  'Listeye Ekle': 'Zur Liste hinzufügen',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Du nutzt ein Gastkonto — verknüpfe deine E-Mail und verliere deine Daten nicht!',
  'Misafir olarak devam et': 'Als Gast fortfahren',
  'Oluştur': 'Erstellen',
  'Oyuncular': 'Besetzung',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil gespeichert',
  'Puanla': 'Bewerten',
  'Puanı Sil': 'Bewertung löschen',
  'Puanın': 'Deine Bewertung',
  'Sezonlar': 'Staffeln',
  'Sunucu hatası ({})': 'Serverfehler ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Kommentar zu S{}E{}',
  'Takibi Bırak': 'Entfolgen',
  'Takip': 'Folge ich',
  'Takip Edilenler': 'Gefolgte',
  'Takip Et': 'Folgen',
  'Takipçi': 'Follower',
  'Takipçi yok': 'Keine Follower',
  'Takipçiler': 'Follower',
  'Takvim': 'Kalender',
  'Tamam': 'OK',
  'Tekrar Dene': 'Erneut versuchen',
  'Tekrar dene': 'Erneut versuchen',
  'Toplam İzleme Süresi': 'Gesamte Bildschirmzeit',
  'Tüm Zamanların En İyileri': 'Die Besten aller Zeiten',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'Exportiere alle deine Daten (Verlauf, Bewertungen, Kommentare, Listen) als TV-Time-kompatibles ZIP oder importiere ein ZIP aus einer anderen App.',
  'Tümünü Kaldır': 'Alle entfernen',
  'Tümünü İzledim': 'Alle gesehen',
  'Türk Dizileri': 'Türkische Serien',
  'Veri içe aktar (.zip)': 'Daten importieren (.zip)',
  'Verilerim': 'Meine Daten',
  'Verilerimi dışa aktar (e-posta)': 'Meine Daten exportieren (E-Mail)',
  'Verilerini dışa aktar': 'Deine Daten exportieren',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Keine anstehenden Episoden.\nSetze eine Serie in der Detailansicht auf "Schaue ich" und verfolge neue Episoden hier.',
  'Yapımları': 'Filmografie',
  'Yeni Diziler': 'Neue Serien',
  'Yeni Liste': 'Neue Liste',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Neuer Benutzername (optional)',
  'Yorum': 'Kommentar',
  'Yorumunu yaz...': 'Schreib deinen Kommentar...',
  'Zaten hesabın var mı? Giriş yap': 'Hast du schon ein Konto? Anmelden',
  'ort. {}': 'Ø {}',
  'takip': 'folge ich',
  'takipçi': 'Follower',
  '{} / {} bölüm': '{} / {} Episoden',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} Mon.',
  '{} ay~tekil': '{} Mon.',
  '{} bölüm izlendi': '{} Episoden gesehen',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} Min.',
  '{} dk~tekil': '{} Min.',
  '{} gün': '{} Tg.',
  '{} gün~tekil': '{} Tg.',
  '{} içerik': '{} Titel',
  '{} içerik · otomatik': '{} Titel · automatisch',
  '{} kayıt atlandı (eşleşmedi).':
      '{} Einträge übersprungen (keine Übereinstimmung).',
  '{} saat': '{} Std.',
  '{} saat~tekil': '{} Std.',
  '{} sezon': '{} Staffeln',
  '{} yıl': '{} J.',
  '{} yıl~tekil': '{} J.',
  '{}. Bölüm': 'Episode {}',
  '{}. Sezon': 'Staffel {}',
  'Çıkış Yap': 'Abmelden',
  'Ülke': 'Land',
  'Ülke ara...': 'Land suchen...',
  'Ülke seç': 'Land auswählen',
  'İlk yorumu sen yaz!': 'Schreib den ersten Kommentar!',
  'İncelemeler': 'Rezensionen',
  'İncelemen (isteğe bağlı)': 'Deine Rezension (optional)',
  'İptal': 'Abbrechen',
  'İzlediklerim': 'Mein Verlauf',
  'İzledim': 'Gesehen',
  'İzledin': 'Gesehen',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Dein Verlauf und deine Listen bleiben erhalten; du kannst dich jetzt von jedem Gerät aus anmelden.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Dein Verlauf, deine Bewertungen, Kommentare und Listen werden als ZIP an deine hinterlegte E-Mail-Adresse gesendet.',
  'İzleyeceğim': 'Will ich sehen',
  'İzliyorum': 'Schaue ich',
  'İçe aktarım tamamlandı': 'Import abgeschlossen',
  'Şifre': 'Passwort',
  '• profil bilgisi': '• Profildaten',
  '• {} dizi durumu': '• {} Serienstatus',
  '• {} izleme kaydı': '• {} Verlaufseinträge',
  '• {} liste': '• {} Listen',
  '• {} puan': '• {} Bewertungen',
  '• {} yorum': '• {} Kommentare',
  '{}+ yapım': '{}+ Titel',
  'Yorumlar': 'Kommentare',
  'Yorumlar ({})': 'Kommentare ({})',
  'Yorumları ({})': 'Kommentare ({})',
  'Listelerim': 'Meine Listen',
  'Nereden izledin?': 'Wo hast du es gesehen?',
  'Diziye git': 'Zur Serie',
  'TV / Kanal': 'TV / Sender',
  'Sinema': 'Kino',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Sonstiges',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Dein Feed ist leer.\nWenn jemand deine Serien und Filme kommentiert, erscheint es hier.',
  'Listeleri ({})': 'Listen ({})',
  'Liste boş.': 'Diese Liste ist leer.',
  'Yanıtla': 'Antworten',
  '@{} kullanıcısına yanıt veriyorsun': 'Du antwortest @{}',
  'İzlediğim Diziler ({})': 'Gesehene Serien ({})',
  'İzlediğim Filmler ({})': 'Gesehene Filme ({})',
  'Tümünü gör': 'Alle ansehen',
  'Bildirimler': 'Benachrichtigungen',
  'Henüz bildirim yok': 'Noch keine Benachrichtigungen',
  '@{} yorumuna yanıt verdi': '@{} hat auf deinen Kommentar geantwortet',
  '@{} yorumunu beğendi': '@{} gefällt dein Kommentar',
  '@{} seni takip etti': '@{} folgt dir',
  '@{} sana mesaj gönderdi': '@{} hat dir eine Nachricht gesendet',
  'Mesajlar': 'Nachrichten',
  'Mesaj': 'Nachricht',
  'Mesaja eklenecek': 'Wird der Nachricht hinzugefugt',
  'Mesajını yaz...': 'Schreib eine Nachricht...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Noch keine Chats.\nÖffne ein Profil und sende eine Nachricht.',
  'Şifreni mi unuttun?': 'Passwort vergessen?',
  'Şifreyi Sıfırla': 'Passwort zurücksetzen',
  'E-postadaki kod': 'Code aus der E-Mail',
  'Yeni şifre': 'Neues Passwort',
  'Sana Özel': 'Für dich',
  '{} özetin': 'Dein {}-Rückblick',
  'Yıllık izleme istatistiklerin': 'Deine Jahres-Statistik',
  'Rozetler': 'Abzeichen',
  'Verdiğin puan': 'Vergebene Bewertungen',
  'Ortalama puanın': 'Deine Durchschnittswertung',
  'En çok izlediğin diziler': 'Deine meistgesehenen Serien',
  'İlk Bölüm': 'Erste Folge',
  '100 Bölüm': '100 Folgen',
  '1000 Bölüm': '1000 Folgen',
  'İlk Film': 'Erster Film',
  '50 Film': '50 Filme',
  'İlk Yorum': 'Erster Kommentar',
  '25 Yorum': '25 Kommentare',
  '10 Puan': '10 Bewertungen',
  'İlk Takipçi': 'Erster Follower',
  '10 Dizi Bitirdin': '10 Serien beendet',
  'İzlemeyi Bıraktım': 'Abgebrochen',
  'İzlediği Diziler ({})': 'Gesehene Serien ({})',
  'İzlediği Filmler ({})': 'Gesehene Filme ({})',
  '500 Bölüm': '500 Folgen',
  '5000 Bölüm': '5000 Folgen',
  '10 Film': '10 Filme',
  '100 Film': '100 Filme',
  '100 Yorum': '100 Kommentare',
  '50 Puan': '50 Bewertungen',
  '100 Puan': '100 Bewertungen',
  '10 Takipçi': '10 Follower',
  '50 Takipçi': '50 Follower',
  '25 Dizi Bitirdin': '25 Serien beendet',
  '50 Dizi Bitirdin': '50 Serien beendet',
  '10 Beğeni': '10 Likes',
  '100 Beğeni': '100 Likes',
  'yazıyor...': 'schreibt...',
  'ses kaydediyor...': 'nimmt Audio auf...',
  'Profil düzeni': 'Profil-Layout',
  'Konumla ve kırp': 'Ausrichten und zuschneiden',
  'Listeye eklendi': 'Zur Liste hinzugefügt',
  'Listeyi sil?': 'Liste löschen?',
  'Sil': 'Löschen',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Dieser Titel gilt dann als nie gesehen und wird aus deinen Listen entfernt.',
  'Gelecek bölüm bugün': 'Nächste Folge heute',
  'Gelecek bölüm {} gün sonra': 'Nächste Folge in {} Tagen',
  'Tema': 'Design',
  'Sistem': 'System',
  'Koyu': 'Dunkel',
  'Açık': 'Hell',
  'İzleyenler': 'Zuschauer',
  'Yorumunu yaz... (@ ile etiketle)':
      'Schreibe deinen Kommentar... (@ zum Markieren)',
  '@{} bir yorumda seni etiketledi': '@{} hat dich in einem Kommentar markiert',
  'Mesajı sil': 'Nachricht löschen',
  'Mesaj silinemedi': 'Nachricht konnte nicht gelöscht werden',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Link ist ungültig oder Seite nicht gefunden',
  "Keşfet'e dön": 'Zurück zu Entdecken',
  'Düzenle': 'Bearbeiten',
  'Mesajı düzenle': 'Nachricht bearbeiten',
  'Yanıtlanıyor': 'Antwortet',
  'düzenlendi': 'bearbeitet',
  'Fotoğraf': 'Foto',
  'Video': 'Video',
  'İçerik': 'Inhalt',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': 'zuletzt vor {} Min.',
  'son görülme {} saat önce': 'zuletzt vor {} Std.',
  'son görülme {} gün önce': 'zuletzt vor {} T.',
  'Yorumlar yüklenemedi': 'Kommentare konnten nicht geladen werden',
  'Favori': 'Favorit',
  'Listeye ekle': 'Zur Liste hinzufügen',
  'İçerik paylaş': 'Inhalt teilen',
  'Kapat': 'Schließen',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Alles, was du als gesehen markierst, sammelt sich hier.',
  'Henüz sohbetin yok': 'Noch keine Unterhaltungen',
  'Bir profile girip mesaj gönderebilirsin.':
      'Öffne ein Profil und sende eine Nachricht.',
  'Listeyi sil': 'Liste löschen',
  'Puan kaydedilemedi': 'Bewertung konnte nicht gespeichert werden',
  'Nerede İzlenir': 'Wo streamen',
  'Abonelik': 'Abo',
  'Kirala': 'Leihen',
  'Satın al': 'Kaufen',
  'Devam et': 'Weiter',
  'Şikayet et': 'Melden',
  'Engelle': 'Blockieren',
  'Engeli kaldır': 'Entsperren',
  'Kullanıcı engellendi': 'Benutzer blockiert',
  'Engel kaldırıldı': 'Blockierung aufgehoben',
  'Şikayet sebebi': 'Grund der Meldung',
  'Spam veya yanıltıcı': 'Spam oder irreführend',
  'Taciz veya nefret söylemi': 'Belästigung oder Hassrede',
  'Uygunsuz / cinsel içerik': 'Unangemessene / sexuelle Inhalte',
  'Şiddet veya tehlikeli içerik': 'Gewalt oder gefährliche Inhalte',
  'Telif hakkı ihlali': 'Urheberrechtsverletzung',
  'Şikayetin alındı, teşekkürler': 'Deine Meldung ist eingegangen, danke',
  'Hesabımı Sil': 'Konto löschen',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Dein Konto und alle deine Daten (Verlauf, Bewertungen, Kommentare, Listen, Nachrichten) werden dauerhaft gelöscht. Das kann nicht rückgängig gemacht werden.',
  'Şifreni gir': 'Gib dein Passwort ein',
  'Hesabımı kalıcı sil': 'Mein Konto endgültig löschen',
  'Sesli mesaj': 'Sprachnachricht',
  'Ses gönderilemedi': 'Sprachnachricht konnte nicht gesendet werden',
  'Kaydediliyor…': 'Aufnahme…',
  'Ses oynatılamadı': 'Sprachnachricht konnte nicht abgespielt werden',
  'Oynat': 'Abspielen',
  'Fragmanı oynat': 'Trailer abspielen',
  'Altyazıyı aç': 'Untertitel einschalten',
  'Altyazıyı kapat': 'Untertitel ausschalten',
  '10 saniye ileri': '10 Sekunden vorspulen',
  '10 saniye geri': '10 Sekunden zurückspulen',
  'Duraklat': 'Pause',
  'Liste görünümü': 'Listenansicht',
  'Takvim görünümü': 'Kalenderansicht',
  'Önceki ay': 'Voriger Monat',
  'Sonraki ay': 'Nächster Monat',
  'Bu gün bölüm yok': 'Keine Folgen an diesem Tag',
  'Gizlilik Politikası': 'Datenschutzerklärung',
  'Son güncelleme: {}': 'Zuletzt aktualisiert: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Diese Erklärung beschreibt, welche Daten erhoben werden, wie sie verwendet werden und welche Rechte du hast, wenn du die dizi.jpg-App und die Website dizijpg.com nutzt.',
  'Topladığımız Veriler': 'Welche Daten wir erheben',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Konto: E-Mail-Adresse, Benutzername und Passwort. Passwörter werden unumkehrbar gehasht gespeichert; Gastkonten können ohne E-Mail genutzt werden.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profil: Angaben, die du freiwillig hinzufügst, etwa Avatar, Titelbild, Bio und Land.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Nutzung: dein Verlauf, deine Bewertungen, Kommentare, Listen, Reaktionen und Favoriten.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Nachrichten: deine Text-, Bild- und Sprachnachrichten werden auf unseren Servern gespeichert. Nachrichten sind nicht Ende-zu-Ende-verschlüsselt; sie werden nur bei einer Meldung zu Moderationszwecken eingesehen.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Hochgeladene Medien: Fotos, GIF, Videos und Sprachaufnahmen, die du deinem Profil, deinen Kommentaren und Nachrichten hinzufügst.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Technisches: IP-Adresse, ungefährer Standort (Land/Stadt), Geräteplattform, App-Version und Fehlerprotokolle. Diese Daten dienen der Sicherheit und Fehlerbehebung.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Nutzungsstatistik: Gerätetyp, Betriebssystem und Browser des Zugriffs werden als grobe Kategorien zu täglichen Gesamtzählern addiert; die Browser-Kennung selbst wird nicht gespeichert und diese Zahlen lassen sich keiner Person zuordnen.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Benachrichtigungen: für Push-Benachrichtigungen speichern wir dein Geräte-Token und deine Spracheinstellung. Du kannst Benachrichtigungen jederzeit in den Geräteeinstellungen deaktivieren.',
  'Verileri Nasıl Kullanırız': 'Wie wir deine Daten verwenden',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Wir verwenden deine Daten ausschließlich, um den Dienst bereitzustellen, dein Konto zu schützen, Benachrichtigungen zu senden, Fehler zu beheben und Missbrauch zu verhindern. Wir verkaufen deine Daten nicht und geben sie nicht zu Werbezwecken weiter.',
  'Çerezler ve Yerel Depolama': 'Cookies und lokaler Speicher',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Wir nutzen lokalen Speicher nur, um dich angemeldet zu halten und Einstellungen wie Sprache und Design zu merken. Es gibt keine Werbe- oder Tracking-Cookies.',
  'Üçüncü Taraf Hizmetler': 'Dienste von Drittanbietern',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Serien- und Filmdaten stammen von TMDB, Streaming-Anbieter-Daten von JustWatch. Push-Benachrichtigungen werden über Google Firebase zugestellt, der Website-Verkehr wird von Cloudflare geschützt. Für diese Dienste gelten deren eigene Datenschutzerklärungen.',
  'Saklama ve Silme': 'Speicherung und Löschung',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Deine Daten werden gespeichert, solange dein Konto besteht. Über "Konto löschen" in den Einstellungen kannst du dein Konto dauerhaft löschen; deine Daten werden sofort gelöscht, Kopien in Backups spätestens nach 14 Tagen. Fehlerprotokolle werden nach 30 Tagen automatisch gelöscht.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'Du kannst deine Daten in den Einstellungen als ZIP exportieren; das Archiv wird an deine E-Mail-Adresse gesendet.',
  'Güvenlik': 'Sicherheit',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Daten werden über verschlüsselte Verbindungen (HTTPS) übertragen und auf Servern mit beschränktem Zugriff gespeichert.',
  'Çocukların Gizliliği': 'Datenschutz von Kindern',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg richtet sich nicht an Kinder unter 13 Jahren.',
  'Hakların': 'Deine Rechte',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Nach KVKK und GDPR hast du das Recht, auf deine Daten zuzugreifen, sie zu berichtigen, zu löschen und zu übertragen. Schreib uns dazu einfach: {}',
  'Değişiklikler': 'Änderungen',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Wenn sich diese Erklärung ändert, wird die neue Fassung auf dieser Seite veröffentlicht und das Aktualisierungsdatum erneuert.',
  'Kayıt olarak {} kabul etmiş olursun.':
      'Mit der Registrierung akzeptierst du die {}.',
  'Kullanıcılar': 'Nutzer',
  'Fotoğrafı değiştir': 'Foto ändern',
  'Yeniden konumlandır': 'Neu ausrichten',
  'Bir şeyler ters gitti': 'Etwas ist schiefgelaufen',
  'Sosyal Bağlantılar': 'Soziale Links',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'In deinem Profil werden bis zu 3 Links angezeigt.',
  'Platform seç': 'Plattform wählen',
  'Kullanıcı adın': 'Dein Benutzername',
  'Ekle': 'Hinzufügen',
  'Kaldır': 'Entfernen',
  'Kopyalandı: {}': 'Kopiert: {}',
  'Geçersiz kullanıcı adı': 'Ungültiger Benutzername',
  'Bağlantı ekle': 'Link hinzufügen',
  'Spoiler olabilir — dokun ve gör':
      'Kann Spoiler enthalten — zum Ansehen tippen',
  'Beğeni': 'Gefällt mir',
  'beğeni': 'Gefällt mir',
  'Beğen': 'Gefällt mir',
  'Görüntülenme': 'Aufrufe',
  'görüntülenme': 'Aufrufe',
  'Tam ekran': 'Vollbild',
  'Arama başarısız': 'Suche fehlgeschlagen',
  'Sonuç bulunamadı': 'Keine Ergebnisse',
  'Dizi ve Filmler': 'Serien & Filme',
  'Kişiler': 'Personen',
  'Ana Sayfa': 'Startseite',
  'Paylaş': 'Teilen',
  'Yanıtlar': 'Antworten',
  'Yaklaşan Bölümler': 'Kommende Folgen',
  'Yetişme Listesi': 'Aufholliste',
  'Şunu mu demek istedin': 'Meintest du',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — zum Anzeigen tippen',
  'uyum': 'Übereinstimmung',
  'Uyum': 'Übereinstimmung',
  '{} ortak dizi': '{} gemeinsame Serien',
  '{} ortak film': '{} gemeinsame Filme',
  'Bildirim Tercihleri': 'Benachrichtigungen',
  'Beğeniler': 'Likes',
  'Yeni takipçiler': 'Neue Follower',
  'Etiketlenmeler': 'Erwähnungen',
  'Yeniden izledim': 'Erneut gesehen',
  '{}. kez izlendi': '{}-mal gesehen',
  'Gönderi bulunamadı': 'Beitrag nicht gefunden',
  'Gözat': 'Entdecken',
  'Diziler': 'Serien',
  'Filmler': 'Filme',
  'Tümü': 'Alle',
  'Farklı bir tür seç.': 'Probier ein anderes Genre.',
  'Gizlilik': 'Privatsphäre',
  'İzlediklerimi gizle': 'Gesehenes verbergen',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Serien und Filme, die du gesehen hast, werden in deinem Profil nicht angezeigt',
  'Yorumlarımı gizle': 'Meine Kommentare verbergen',
  'Profilinde yorumların görünmez':
      'Deine Kommentare werden in deinem Profil nicht angezeigt',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Eine einzelne Serie oder einen Film kannst du mit dem Chip "In meinem Profil verbergen" auf der Inhaltsseite verbergen.',
  'Geri Bildirim': 'Feedback',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Schreib deine Meinung und Vorschläge zur App...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Danke! Dein Feedback ist angekommen.',
  'Profilimde gizle': 'In meinem Profil verbergen',
  'Yorumları': 'Kommentare',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Dieser Nutzer hat noch nichts gesehen.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Dieser Nutzer hält die Kommentare lieber privat.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Daten: JustWatch',
  'Web Sitesi': 'Website',
  'Diğer uygulamalar': 'Andere Apps',
  'Bağlantıyı kopyala': 'Link kopieren',
  'Henüz kimseyi takip etmiyorsun.': 'Du folgst noch niemandem.',
  'Çevir': 'Übersetzen',
  'Çeviri şu an yapılamadı': 'Übersetzung derzeit nicht möglich',
  'Bağlantı açılamadı': 'Link konnte nicht geöffnet werden',
  'Orijinali göster': 'Original anzeigen',
  'Çeviriyi göster': 'Übersetzung anzeigen',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Diesen Monat gibt es keine Folgen mit bekanntem Ausstrahlungsdatum. Termine werden meist wenige Wochen vorher bekannt gegeben und erscheinen dann hier.',
  'devamı': 'mehr',
  'Google ile devam et': 'Mit Google fortfahren',
  'Google girişi başarısız': 'Google-Anmeldung fehlgeschlagen',
  'Veri tasarrufu': 'Datensparmodus',
  'Wi-Fi ağında veri tasarrufu': 'Datensparmodus im WLAN',
  'Mobil veride veri tasarrufu': 'Datensparmodus bei mobilen Daten',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Wenn aktiv, werden Fotos nicht vorab geladen; nur das Bild, das du gerade ansiehst.',
  'Çocuk güvenliği': 'Kindersicherheit',
  'Türk Filmleri': 'Türkische Filme',
  'En Yüksek Puanlı Filmler': 'Bestbewertete Filme',
  'En Yüksek Puanlı Diziler': 'Bestbewertete Serien',
  'En Çok İzlenen Filmler': 'Meistgesehene Filme',
  'Popüler Diziler': 'Beliebte Serien',
  'En Çok Kazanan Filmler': 'Erfolgreichste Filme',
  'Kült Filmler': 'Kultfilme',
  'Yeni Filmler': 'Neue Filme',
  'Yorum yap': 'Kommentieren',
  'Henüz yorum yok': 'Noch keine Kommentare',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Deine Kommentare zu Serien und Filmen sammeln sich hier.',
  'GIF ekle': 'GIF hinzufügen',
  'İlk yorumu sen yaz': 'Schreibe den ersten Kommentar',
  'Video altyazıları': 'Video-Untertitel',
  'Videolarda altyazı göster': 'Untertitel für Videos anzeigen',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Der im Video gesprochene Satz wird auf den Bildschirm geschrieben. Der Text ist übersetzt: Englisch in türkischer Sprache, Türkisch in anderen Sprachen.',
  'Güncelleme gerekli': 'Update erforderlich',
  'Yeni sürüm var': 'Neue Version verfügbar',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Installiere die neue Version von dizi.jpg, um fortzufahren.',
  'Güncelle': 'Aktualisieren',
  'Daha sonra': 'Später',
  'Takvim güncelleniyor': 'Kalender wird aktualisiert',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Kalender konnte nicht aktualisiert werden, alte Liste wird angezeigt',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Einige Serien konnten nicht geladen werden, die Liste ist eventuell unvollständig',
  'Yenile': 'Aktualisieren',
  'Devam etmek için giriş yap': 'Melde dich an, um fortzufahren',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Ein kostenloses Konto reicht, um zu bewerten, zu kommentieren und deine Bibliothek aufzubauen.',
  'Şimdi değil': 'Jetzt nicht',
  'Yorum yazmak için giriş yap': 'Melde dich an, um zu kommentieren',
  'Kişilere göndermek için giriş yap':
      'Melde dich an, um an Personen zu senden',
  'Beğenenler': 'Gefallt mir',
  'Henüz beğeni yok': 'Noch keine Likes',
  'Bu gönderiyi ilk beğenen sen ol': 'Sei die erste Person, der das gefallt',
  'Bu gönderiye yanıt': 'Antwort auf diesen Beitrag',
  'Spoiler içeren gönderi': 'Beitrag mit Spoilern',
  'Görsel gönderi': 'Bildbeitrag',
  'Bu yorumu profilimde gizle': 'Diesen Kommentar in meinem Profil ausblenden',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Der Kommentar bleibt auf der Serien- und Filmseite',
  'Bu yorumu sil': 'Diesen Kommentar löschen',
  'Yorum profilinde gizlendi': 'Kommentar in deinem Profil ausgeblendet',
  'Geri al': 'Rückgängig',
  'Yorum silinsin mi?': 'Kommentar löschen?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Dieser Kommentar wird überall dauerhaft gelöscht. Das kann nicht rückgängig gemacht werden.',
  'Yorum silindi': 'Kommentar gelöscht',
  'Yorum profilinde tekrar görünüyor':
      'Der Kommentar ist wieder auf deinem Profil sichtbar',
  'Gizlenen yorumun yok': 'Keine ausgeblendeten Kommentare',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Kommentare, die du im Tab Kommentare deines Profils durch langes Drücken auf einen Beitrag ausblendest, sammeln sich hier.',
  'Gizlenen yorumlar': 'Ausgeblendete Kommentare',
  'Gönderiye git': 'Zum Beitrag',
  'Tekrar göster': 'Wieder anzeigen',
  'Yanıtlarımı gizle': 'Meine Antworten ausblenden',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Antworten, die du auf Beiträge anderer schreibst, sind nur für dich sichtbar',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Die Kommentare, die du in deinem Profil ausgeblendet hast, wieder anzeigen',
  'Sıralama': 'Sortierung',
  'Önerilen': 'Empfohlen',
  'Kronolojik': 'Chronologisch',
  'Gelen mesaj istekleri': 'Eingegangene Nachrichtenanfragen',
  'Mesaj isteğin yok': 'Keine Nachrichtenanfragen',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Nachrichten von Personen, denen du nicht folgst, erscheinen hier.',
  'Çevrimiçi durumumu gizle': 'Meinen Online-Status verbergen',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Andere sehen deinen Online-Status und deine letzte Aktivität in Nachrichten nicht',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Gehört zu unseren ersten Nutzern. Dieses Feedback hat die App zu dem gemacht, was sie heute ist.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Du gehörst zu unseren ersten Nutzern. Dein Feedback hat die App zu dem gemacht, was sie heute ist.',
  'İleri': 'Weiter',
  'Önceki': 'Vorherige',
  'Sonraki': 'Nächste',
  'Seçilen dosya okunamadı':
      'Die ausgewählte Datei konnte nicht gelesen werden',
  'Video açılamadı': 'Video konnte nicht geöffnet werden',
  'En fazla {} medya seçebilirsin': 'Du kannst höchstens {} Medien auswählen',
  'Hiçbir medya yüklenemedi': 'Es konnten keine Medien hochgeladen werden',
  'Seçimi kaldır': 'Auswahl entfernen',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'In einem Kommentar kannst du insgesamt {} MB hochladen',
  '{} dosya okunamadı': '{} Dateien konnten nicht gelesen werden',
  '{} medya eklendi, {} yüklenemedi':
      '{} Medien hinzugefügt, {} fehlgeschlagen',
  'Kırp': 'Zuschneiden',
  'Çiz': 'Zeichnen',
  'Metin': 'Text',
  'Emoji': 'Emoji',
  'Yinele': 'Wiederholen',
  'Daha fazla': 'Mehr',
  'Hazırlanıyor…': 'Wird vorbereitet…',
  'Düzenlemeden çık?': 'Bearbeitung beenden?',
  'Yaptığın değişiklikler kaybolacak.': 'Deine Änderungen gehen verloren.',
  'Çık': 'Beenden',
  'Serbest çizim': 'Freihand',
  'Ok': 'Pfeil',
  'Dikdörtgen': 'Rechteck',
  'Daire': 'Kreis',
  'Bulanıklaştır': 'Weichzeichnen',
  'Pikselleştir': 'Verpixeln',
  'Silgi': 'Radierer',
  'Çizgi kalınlığı': 'Linienstärke',
  'Saydamlık': 'Deckkraft',
  'Dolgu': 'Füllung',
  'Renk': 'Farbe',
  'Döndür': 'Drehen',
  'Yansıt': 'Spiegeln',
  'Oran': 'Verhältnis',
  'Sıfırla': 'Zurücksetzen',
  'Serbest': 'Frei',
  'Metin yaz...': 'Text eingeben...',
  'Hizala': 'Ausrichten',
  'Arka plan': 'Hintergrund',
  'Emoji ara...': 'Emoji suchen...',
  'Son kullanılanlar': 'Zuletzt verwendet',
  'İfadeler ve insanlar': 'Smileys und Menschen',
  'Hayvanlar ve doğa': 'Tiere und Natur',
  'Yiyecek ve içecek': 'Essen und Trinken',
  'Etkinlikler': 'Aktivitäten',
  'Seyahat ve yerler': 'Reisen und Orte',
  'Nesneler': 'Objekte',
  'Semboller': 'Symbole',
  'Bayraklar': 'Flaggen',
  'Görseli düzenle': 'Bild bearbeiten',
  'Düzenlendi': 'Bearbeitet',
  'Düzenlenemedi': 'Bearbeitung fehlgeschlagen',
  'Düzenlenen görsel çok büyük': 'Das bearbeitete Bild ist zu groß',
  'Videoyu düzenle': 'Video bearbeiten',
  'Sesi kapat': 'Stummschalten',
  'Sesi aç': 'Ton einschalten',
  'İptal ediliyor…': 'Wird abgebrochen…',
  'Bu biraz sürebilir': 'Das kann einen Moment dauern',
  'Video çok büyük': 'Video ist zu gross',
  'Video hazırlanamadı': 'Video konnte nicht vorbereitet werden',
  'Başlangıç': 'Start',
  'Bitiş': 'Ende',
  'En çok {} saniye seçebilirsin': 'Du kannst bis zu {} Sekunden auswaehlen',
  'Dosya en fazla {} MB olabilir': 'Die Datei darf hoechstens {} MB gross sein',
  'Medya ekle': 'Medien hinzufügen',
  'Seçili medya kalmadı': 'Keine Medien ausgewählt',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Wähle ein Foto oder Video für deinen Kommentar aus.',
  'Medya seç': 'Medien auswählen',
  'Daha fazla ekle': 'Mehr hinzufügen',
  'Medya seçilemedi': 'Medien konnten nicht ausgewählt werden',
  'Favori oyuncular': 'Lieblingsschauspieler',
  'Henüz favori oyuncun yok': 'Noch keine Lieblingsschauspieler',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Oeffne die Seite eines Schauspielers und tippe oben rechts auf das Herz.',
  '{} yapımdan {} tanesini izledin': 'Du hast {} von {} Titeln gesehen',
  'izledin': 'gesehen',
  'İzlemedin': 'Nicht gesehen',
  'Yapım bulunamadı': 'Keine Titel gefunden',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Diese Person hat keine Serien oder Filme zum Auflisten.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Dein Verlauf haengt an deinem Konto; diese Liste gehoert nur dir.',
  'Hesabın kalıcı olarak askıya alındı': 'Dein Konto wurde dauerhaft gesperrt',
  'Hesabın geçici olarak askıya alındı':
      'Dein Konto wurde vorübergehend gesperrt',
  'Hesabın askıya alındı': 'Dein Konto ist gesperrt',
  'Sebep': 'Grund',
  'Kalan süre': 'Verbleibende Zeit',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Dein Konto wird nach Ablauf der Frist automatisch wieder freigegeben',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'In dieser Zeit kannst du weiterlesen, aber keine Beiträge, Kommentare oder Nachrichten senden.',
  'Anladım': 'Verstanden',
  'Ayrıntı': 'Details',
  '{} dakika': '{} Minuten',
  'birkaç saniye': 'ein paar Sekunden',
  'Karara itiraz et': 'Entscheidung anfechten',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Erklär, warum diese Strafe aufgehoben werden sollte',
  'İtirazını gönder': 'Einspruch senden',
  'İtirazın incelemede': 'Dein Einspruch wird geprüft',
  'İtirazın reddedildi': 'Dein Einspruch wurde abgelehnt',
  'İtirazın alındı, inceleniyor':
      'Dein Einspruch ist eingegangen und wird geprüft',
  'İtiraz en az 10 karakter olmalı':
      'Der Einspruch muss mindestens 10 Zeichen lang sein',
  'Yükleniyor...': 'Wird geladen...',
  'Bu bölüme puan ver': 'Bewerte diese Folge',
  '{} kişi puanladı': '{} Personen haben bewertet',
  'Bölüm izlendi olarak işaretlendi': 'Folge als gesehen markiert',
  'Sesli ara': 'Sprachanruf',
  'Görüntülü ara': 'Videoanruf',
  'Çalıyor...': 'Es klingelt...',
  'Bağlanıyor...': 'Verbindung wird hergestellt...',
  'Cevapla': 'Annehmen',
  'Reddet': 'Ablehnen',
  'Sessize al': 'Stummschalten',
  'Hoparlör': 'Lautsprecher',
  'Kamerayı kapat': 'Kamera ausschalten',
  'Kamerayı çevir': 'Kamera wechseln',
  'Cevap yok': 'Keine Antwort',
  'Arama reddedildi': 'Anruf abgelehnt',
  'Meşgul': 'Besetzt',
  'Bağlanılamadı': 'Verbindung nicht möglich',
  'Arama iptal edildi': 'Anruf abgebrochen',
  'Arama geçmişi': 'Anrufverlauf',
  'Gelen arama': 'Eingehender Anruf',
  'Giden arama': 'Ausgehender Anruf',
  'Cevapsız arama': 'Verpasster Anruf',
  'Arama şu anda kullanılamıyor': 'Anrufe sind derzeit nicht verfügbar',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Videoanrufe sind gerade deaktiviert, du kannst einen Sprachanruf starten',
  'Bu kullanıcıyı arayamazsın': 'Du kannst diesen Nutzer nicht anrufen',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Ihr müsst euch gegenseitig folgen, um anzurufen',
  'Bu kullanıcı şu anda aranamıyor':
      'Dieser Nutzer kann gerade nicht angerufen werden',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Zu viele verpasste Anrufe. Versuch es in {} erneut',
  'Zaten bir aramadasın': 'Du bist bereits in einem Anruf',
  'Arama için mikrofon izni gerekiyor':
      'Für Anrufe wird die Mikrofonberechtigung benötigt',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'Für Videoanrufe werden Kamera- und Mikrofonberechtigung benötigt',
  'Arama başlatılamadı': 'Anruf konnte nicht gestartet werden',
  'Kullanıcı bulunamadı': 'Nutzer nicht gefunden',
  'Kendini arayamazsın': 'Du kannst dich nicht selbst anrufen',
  'Arama artık geçerli değil': 'Dieser Anruf ist nicht mehr gültig',
  'Bu aramanın tarafı değilsin': 'Du gehörst nicht zu diesem Anruf',
  'Arama bulunamadı': 'Anruf nicht gefunden',
  'Çok fazla istek, biraz bekle': 'Zu viele Anfragen, bitte kurz warten',
  'Bağlantı koptu': 'Verbindung verloren',
  'Arama süre sınırına ulaştı': 'Der Anruf hat sein Zeitlimit erreicht',
  'Arama en fazla 4 saat sürebilir':
      'Ein Anruf kann höchstens 4 Stunden dauern',
  'Arama sona erdi': 'Der Anruf ist beendet',
  'Sesli arama': 'Sprachanruf',
  'Görüntülü arama': 'Videoanruf',
  'Gelen aramalar': 'Eingehende Anrufe',
  'Sesli ve görüntülü arama bildirimleri':
      'Benachrichtigungen für Sprach- und Videoanrufe',
  '{} sa': '{} Std.',
  'Sesli ve Görüntülü Aramalar': 'Sprach- und Videoanrufe',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Anrufinhalte werden niemals aufgezeichnet. Audio und Video fließen Ende-zu-Ende-verschlüsselt (DTLS-SRTP) zwischen den Geräten; unsere Server können diesen Datenverkehr weder entschlüsseln noch mithören oder speichern.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Es werden nur Anruf-Metadaten gespeichert: mit wem, in welche Richtung, wann und wie lange. Diese Einträge werden nach 90 Tagen automatisch gelöscht.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Wenn keine direkte Verbindung möglich ist, laufen Audio und Video verschlüsselt über einen Relay-Server (TURN). Auch dieser kann die Inhalte weder entschlüsseln noch aufzeichnen.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Das Mikrofon wird nur während eines Sprach- oder Videoanrufs verwendet, die Kamera nur während eines Videoanrufs. Beide werden nach dem Anruf ausgeschaltet.',
  'Takip ettiğin {} kişi izledi':
      '{} Personen, denen du folgst, haben es gesehen',
  'Yorum yaz...': 'Schreib einen Kommentar...',
  'Sıradaki bölüm': 'Nächste Episode',
  'Doğrulanmış testçi': 'Verifizierter Tester',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Benachrichtigungen zu Follows, Likes, Antworten, Nachrichten und Markierungen',
  'Sen': 'Du',
  'Aradığınız kişide sesli arama devre dışı':
      'Sprachanrufe sind bei dieser Person deaktiviert',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Videoanrufe sind bei dieser Person deaktiviert',
  'Sesli aramalara izin ver': 'Sprachanrufe zulassen',
  'Görüntülü aramalara izin ver': 'Videoanrufe zulassen',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Wenn aus, kann dich niemand per Sprache anrufen; Anrufer sehen einen Hinweis',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Wenn aus, kann dich niemand per Video anrufen; Anrufer sehen einen Hinweis',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Sprachanrufe sind aus. Du kannst sie unter Einstellungen > Privatsphäre aktivieren.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Videoanrufe sind aus. Du kannst sie unter Einstellungen > Privatsphäre aktivieren.',
  'Sesli ve görüntülü arama': 'Sprach- und Videoanrufe',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Gastkonten können nicht anrufen. Erstelle ein Konto, um es zu nutzen.',
  'Misafir hesaplar aranamaz': 'Gastkonten können nicht angerufen werden',
  'Puan dağılımı': 'Bewertungsverteilung',
  '{} yıldız': '{} Sterne',
  'Yakında gelecek': 'Bald verfügbar',
  '{} {} yayınlandı': '{} {} ist da',
  'Yeni bölüm yayınlandı': 'Neue Episode ist da',
  'Yeni bölümler': 'Neue Episoden',
  'Geri': 'Zurück',
  'Karşılamayı kapat': 'Einführung schließen',
  'Adım {} / {}': 'Schritt {} / {}',
  'Hadi başlayalım': "Los geht's",
  'Kaydet ve devam': 'Speichern und weiter',
  '{} tanesini ekle': '{} hinzufügen',
  'Şimdilik geç': 'Vorerst überspringen',
  'Doğum tarihin ne zaman?': 'Wann bist du geboren?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Wir fragen, um dir altersgerechte Inhalte zu zeigen und deinen Geburtstag zu feiern.',
  'Gün': 'Tag',
  'Ay': 'Monat',
  'Yıl': 'Jahr',
  'Doğum yılımı paylaşmak istemiyorum':
      'Ich möchte mein Geburtsjahr nicht angeben',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'Dein Geburtsdatum wird in deinem Profil nicht öffentlich angezeigt. Es dient nur für altersgerechte Inhalte und Geburtstagsgrüße.',
  'Ocak': 'Januar',
  'Şubat': 'Februar',
  'Mart': 'März',
  'Nisan': 'April',
  'Mayıs': 'Mai',
  'Haziran': 'Juni',
  'Temmuz': 'Juli',
  'Ağustos': 'August',
  'Eylül': 'September',
  'Ekim': 'Oktober',
  'Kasım': 'November',
  'Aralık': 'Dezember',
  'Verilerini yanında getir': 'Nimm deine Daten mit',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Wenn du deine Serien und Filme in einer anderen App verfolgst, kannst du alles hierher holen. Du musst nicht bei null anfangen.',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt und Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Wähle die ZIP-Datei aus, die du exportiert hast; dein Verlauf, deine Bewertungen und deine Listen kommen mit.',
  'Aktarılıyor...': 'Wird importiert...',
  'ZIP dosyası seç': 'ZIP-Datei auswählen',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'Kein Stress: Das geht später auch unter Einstellungen > Meine Daten.',
  'Hangi filmleri izledin?': 'Welche Filme hast du gesehen?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Hier sind die meistgesehenen Titel. Tippe an, was du gesehen hast, und wir legen es in deinen Verlauf.',
  'SERİ FİLMLER': 'FILMREIHEN',
  'Serilerden {} film eklendi': '{} Filme aus Filmreihen hinzugefügt',
  'Film listesi yüklenemedi': 'Filmliste konnte nicht geladen werden',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Du kannst diesen Schritt überspringen und später hinzufügen, was du willst.',
  '{} film izlediklerine eklendi': '{} Filme zu deinem Verlauf hinzugefügt',
  'Film serileri': 'Filmreihen',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Eine Reihe komplett gesehen? Füge sie mit einem Tipp hinzu.',
  'Seri bulunamadı': 'Keine Filmreihen gefunden',
  'Daha sonra tekrar deneyebilirsin.':
      'Du kannst es später noch einmal versuchen.',
  '{} film': '{} Filme',
  'Eklendi': 'Hinzugefügt',
  'Tümünü izledim': 'Alle gesehen',
  'Peki ya diziler?': 'Und wie sieht es mit Serien aus?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Markiere, was du gesehen hast; je mehr du auswählst, desto mehr Ähnliches zeigen wir dir.',
  'Dizi listesi yüklenemedi': 'Serienliste konnte nicht geladen werden',
  'Seçtiklerine benzeyenler': 'Ähnlich wie deine Auswahl',
  'Her şey hazır': 'Alles bereit',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Wirf einen kurzen Blick darauf, was du auf dizi.jpg alles machen kannst.',
  'Profilini tamamla': 'Vervollständige dein Profil',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'In den Einstellungen kannst du eine Bio, ein Profilfoto und ein Titelbild hinzufügen.',
  'Takvimin seni bekliyor': 'Dein Kalender wartet auf dich',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'Neue Episoden deiner Serien landen im Kalender, und wir sagen dir per Benachrichtigung Bescheid.',
  'Puan ver, yorum yaz': 'Bewerten und kommentieren',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Bewerte Episode für Episode, schreibe Kommentare hinter einem Spoiler-Vorhang und erstelle Listen.',
  'Verilerin sende kalır': 'Deine Daten bleiben bei dir',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Deine Daten hängen nur an deinem Konto und werden nicht verkauft. In den Einstellungen kannst du alles herunterladen oder dein Konto vollständig löschen.',
  'Engellenen kullanıcılar': 'Blockierte Nutzer',
  'Engellediğin kişileri gör, engeli kaldır':
      'Sieh, wen du blockiert hast, und hebe die Blockierung auf',
  'Engellediğin kimse yok': 'Du hast niemanden blockiert',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Du kannst jemanden über das Drei-Punkte-Menü im Profil blockieren.',
  '@{} engellensin mi?': '@{} blockieren?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'Ihr könnt die Beiträge, Kommentare und Profile des anderen nicht mehr sehen; Nachrichten und Anrufe kommen nicht durch. Eine bestehende Follow-Verbindung wird getrennt und kehrt auch dann nicht zurück, wenn du die Blockierung aufhebst.',
  'Bu kullanıcıyı engelledin': 'Du hast diesen Nutzer blockiert',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Du siehst die Beiträge, Kommentare und Nachrichten dieser Person nicht; diese Person sieht deine ebenfalls nicht.',
  '{} yeni bir yapımda: {}': '{} ist in einer neuen Produktion zu sehen: {}',
  'Favori kişinden yeni yapım': 'Neue Produktion einer Lieblingsperson',
  '{} için bildirimler': 'Benachrichtigungen für {}',
  'Tüm bildirimler': 'Alle Benachrichtigungen',
  'Uygulamada ve telefonda': 'In der App und auf dem Handy',
  'Yalnız uygulama içi': 'Nur in der App',
  'Telefon bildirimi gönderilmez':
      'Es wird keine Handy-Benachrichtigung gesendet',
  'Kapalı': 'Aus',
  'Bu kişi için bildirim yok': 'Keine Benachrichtigungen für diese Person',
  'Favori kişilerin yeni yapımları':
      'Neue Produktionen deiner Lieblingspersonen',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Wenn aus, kann dich niemand per Sprache anrufen; Anrufer sehen den Hinweis "deaktiviert"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Wenn aus, kann dich niemand per Video anrufen; Anrufer sehen den Hinweis "deaktiviert"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'Meine Aktivitäten',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'Deine Likes, Kommentare und Ansichten an einem Ort',
  'Henüz hareketin yok': 'Noch keine Aktivität',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Alles, was du likest, kommentierst und siehst, sammelt sich hier.',
  'Bu süzgeçte hareket yok': 'Keine Aktivität in diesem Filter',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Wähle einen anderen Typ oder kehre zu „Alle“ zurück.',
  'Hepsi': 'Alle',
  'Puan': 'Bewertung',
  'Tepki': 'Reaktion',
  'İzleme': 'Gesehen',
  'Durum': 'Status',
  'Liste': 'Liste',
  'Yorum yaptın': 'Kommentiert',
  'Yorumu beğendin': 'Kommentar geliked',
  '{} puan verdin': 'Mit {} bewertet',
  'Tepki verdin': 'Reagiert',
  'Listene ekledin': 'Zur Liste hinzugefügt',
  'Takip etmeye başladın': 'Du folgst jetzt',
  '"İzleyeceğim" işaretledin': 'Als „Will ich sehen“ markiert',
  '"İzliyorum" işaretledin': 'Als „Schaue ich“ markiert',
  '"Bitirdim" işaretledin': 'Als „Abgeschlossen“ markiert',
  '"Bıraktım" işaretledin': 'Als „Abgebrochen“ markiert',
  'Silinmiş içerik': 'Gelöschter Inhalt',
  'şimdi': 'jetzt',
  '{} g': '{} Tg.',
  '{} y': '{} J.',
  'İstatistiklerim': 'Meine Statistiken',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Aufrufe und Likes deiner Beiträge',
  'Henüz gönderin yok': 'Du hast noch keine Beiträge',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Sobald du eine Serie oder einen Film kommentierst, sammeln sich hier deine Aufrufe und Likes.',
  'Tüm zamanlar': 'Gesamt',
  'Son {} gün': 'Letzte {} Tage',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'Der Aufrufverlauf hat noch nicht begonnen; die Daten des ersten Tages erscheinen morgen.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'Der Aufrufverlauf sammelt sich seit {} ({} Tage an Daten), daher ist die Zahl für {} Tage noch unvollständig.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'Der Like-Verlauf wird seit {} aufgezeichnet.',
  'Bu dönemde gösterilecek gönderi yok.':
      'Für diesen Zeitraum gibt es keine Beiträge.',
  'eksik veri': 'unvollständige Daten',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Serien und Filme, die du gesehen hast, deine Zähler, deine Bildschirmzeit und deine Übereinstimmungskarte sind für andere in deinem Profil nicht sichtbar',
  'Takipçi listemi gizle': 'Meine Follower-Liste verbergen',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Andere können nicht sehen, wer dir folgt; deine Followerzahl bleibt sichtbar',
  'Takip ettiklerimi gizle': 'Verbergen, wem ich folge',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Andere können nicht sehen, wem du folgst; deine Anzahl an Abos bleibt sichtbar',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Dieser Nutzer hält die Followerliste lieber privat.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Dieser Nutzer hält lieber privat, wem er folgt.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Beitragsstatistiken',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Du kannst nur die Statistiken deiner eigenen Beiträge sehen.',
  'Erişim': 'Reichweite',
  'Görüntüleyen': 'Betrachter',
  'Kaç farklı kişi gördü (son {} gün)':
      'Wie viele verschiedene Personen es gesehen haben (letzte {} Tage)',
  'Paylaşım': 'Geteilt',
  'Bu gönderiden sonra': 'Nach diesem Beitrag',
  'Profil ziyareti': 'Profilbesuche',
  'Yeni takip': 'Neue Follows',
  'İçeriğe tıklama': 'Klicks auf Inhalt',
  'Spoiler perdesini açan': 'Spoiler aufgedeckt',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Geteilte Beiträge, Profilbesuche, Follows, Klicks auf Inhalt, Quellenaufschlüsselung und Spoiler-Messungen sammeln sich seit {}; alles davor wurde nicht gemessen.',
  'Zamana yayılmış görüntülenme': 'Aufrufe im Zeitverlauf',
  'Görüntülenme nereden geldi': 'Woher die Aufrufe kamen',
  'Kimler gördü': 'Wer es gesehen hat',
  'Günlük veri henüz birikmeye başlamadı.':
      'Die Tagesdaten haben sich noch nicht angesammelt.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'Das Diagramm braucht Daten von mindestens zwei Tagen. Die Daten sammeln sich seit {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'Die meisten Aufrufe kamen am {}. Tag nach dem Posten: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Die täglichen Aufrufe sammeln sich seit {}; alles davor wurde nicht gemessen.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'Die Quellenaufschlüsselung wird erst seit Kurzem gemessen; dieser Beitrag hat noch keinen markierten Aufruf erhalten.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'Die Aufschlüsselung nach Followern und Entdecken wird erst seit Kurzem gemessen; es gibt noch keine Daten.',
  'Takip edenler': 'Follower',
  'Keşiften gelenler': 'Über Entdecken',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Serien-/Filmseite',
  'Paylaşılan bağlantı': 'Geteilter Link',
  'yeni ölçülüyor': 'neu gemessen',
  'Kendi ortalamanla aynı düzeyde':
      'Auf dem Niveau deines eigenen Durchschnitts',
  'Kendi ortalamanın %{} üstünde': '{} % über deinem eigenen Durchschnitt',
  'Kendi ortalamanın %{} altında': '{} % unter deinem eigenen Durchschnitt',
  'Etkileşim oranı': 'Interaktionsrate',
  '(beğeni + yorum) ÷ görüntülenme': '(Likes + Kommentare) ÷ Aufrufe',
  'Toplam görüntülenme': 'Aufrufe gesamt',
  '{} ile {} arasında toplam {} görüntülenme':
      'Zwischen {} und {}: insgesamt {} Aufrufe',
  'İstatistikleri gör': 'Statistiken ansehen',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'Für die Statistiken, die den Verfassenden eines Beitrags angezeigt werden, werden als aggregierte Zähler gespeichert: wie oft und von welcher Oberfläche (Feed, Profil, Vollbild-Feed, Serien-/Filmseite, geteilter Link) der Beitrag aufgerufen wurde, ob die betrachtende Person den Verfassenden zu diesem Zeitpunkt gefolgt ist, der Wechsel vom Beitrag zum Profil oder zum Inhalt, über den Beitrag entstandene Follows, Teilungen und das Aufdecken des Spoiler-Vorhangs. Diese Zähler enthalten keine Nutzerkennung, keine IP-Adresse und keinen Zeitstempel; wer was getan hat, lässt sich nicht abfragen.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'Um zählen zu können, wie viele verschiedene Personen einen Beitrag gesehen haben, wird pro betrachtender Person 90 Tage lang eine nicht umkehrbare Prüfsumme mit Schlüssel gespeichert (eine kryptografische Verkürzung, abgeleitet aus der Nutzerkennung oder der IP-Adresse). Den Verfassenden wird nur die Zahl angezeigt; die Identität der betrachtenden Personen wird unter keinen Umständen weitergegeben.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'Zu „Will ich sehen“ verschieben?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'Ein Titel ist entweder noch zu sehen oder schon gesehen. Wenn du fortfährst, werden deine {} Sehmarkierungen in dieser Serie gelöscht.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'Ein Titel ist entweder noch zu sehen oder schon gesehen. Wenn du fortfährst, wird deine Markierung „Gesehen“ bei diesem Film entfernt.',
  'Sil ve taşı': 'Löschen und verschieben',

  // --- Yapım ekibi / firma + seviye unvanları + doğum günü ---
  'Yapım Ekibi': 'Crew',
  'Yaratıcı': 'Idee',
  'Yönetmen': 'Regie',
  'Senaryo': 'Drehbuch',
  'Yapımcı': 'Produktion',
  'Yapım Firmaları': 'Produktionsfirmen',
  'Yapım Firması': 'Produktionsfirma',
  'Firma bulunamadı': 'Firma nicht gefunden',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'Diese Firma hat keine Titel dieser Art.',
  'Doğum günün kutlu olsun!': 'Alles Gute zum Geburtstag!',
  'İyi ki doğdun, iyi ki buradasın.':
      'Schön, dass es dich gibt, und schön, dass du hier bist.',
  'Bugün {} yaşına girdin': 'Heute wirst du {}',
  'Teşekkürler': 'Danke',
  'İki Adımlı Doğrulama': 'Bestätigung in zwei Schritten',
  'Girişte e-postana kod gönderilir':
      'Beim Anmelden wird ein Code an deine E-Mail gesendet',
  'Kod {} adresine gönderildi': 'Code an {} gesendet',
  '6 haneli kod': '6-stelliger Code',
  'Doğrula': 'Bestätigen',
  'Yeniden gönder': 'Erneut senden',
  'Vazgeç': 'Abbrechen',
  'Yeni kod gönderildi': 'Neuer Code gesendet',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'Bei der Anmeldung mit Google wird kein Code abgefragt; Google übernimmt die eigene Bestätigung.',
  'Kapatmak için de kod gerekir.':
      'Zum Deaktivieren wird ebenfalls ein Code benötigt.',
  'E-postana erişemezsen hesabına giremezsin.':
      'Ohne Zugriff auf deine E-Mail kommst du nicht mehr in dein Konto.',
  'İki adımlı doğrulama açıldı': 'Bestätigung in zwei Schritten ist aktiviert',
  'İki adımlı doğrulama kapatıldı':
      'Bestätigung in zwei Schritten ist deaktiviert',
  'Videonun ne kadarı izlendi': 'Wie viel vom Video gesehen wurde',
  'Videoyu başlatanlar': 'Video gestartet',
  'videonun %{} noktasına ulaştı': 'haben {} % des Videos erreicht',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'Die Hälfte des Publikums hat mindestens {} % des Videos gesehen.',
  'Sonuna kadar izleyen: %{}': 'Bis zum Ende gesehen: {} %',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'Für die Kurve sind mindestens {} Wiedergaben nötig; aktuell sind es {}.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'Die Kurve beruht auf {} Wiedergaben und ändert sich nicht mit dem gewählten Zeitraum.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'Die Wiedergabedauer wird seit {} gemessen; ältere Aufrufe zählen nicht mit.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} Wiedergaben. {} % haben die Hälfte erreicht, {} % das Ende.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{} %',
  'Seviye {}': 'Level {}',
  'Sonraki seviyeye {} puan kaldı': 'Noch {} Punkte bis zum nächsten Level',
  'Gönderilerin': 'Deine Beiträge',
  '{} gönderi': '{} Beiträge',
  '{} gönderi · {} görüntülenme': '{} Beiträge · {} Aufrufe',
  'önceki {} güne göre': 'vs. vorherige {} Tage',
  'önceki {} güne göre %{} arttı':
      'gegenüber den vorherigen {} Tagen um {} % gestiegen',
  'önceki {} güne göre %{} azaldı':
      'gegenüber den vorherigen {} Tagen um {} % gesunken',
  'önceki {} güne göre değişmedi':
      'gegenüber den vorherigen {} Tagen unverändert',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'Tägliche Aufrufe: Tiefstwert {}, Höchstwert {}',
  'Etkileşim oranı henüz ölçülemedi': 'Interaktionsrate noch nicht messbar',
  'Oranlar': 'Raten',
  'Beğenme oranı': 'Like-Rate',
  'Yorum oranı': 'Kommentar-Rate',
  'Paylaşma oranı': 'Teilen-Rate',
  'İçeriğe gitme oranı': 'Inhalt-Klickrate',
  'Profile gitme oranı': 'Profilbesuchsrate',
  'Ziyaretten takibe dönüşüm': 'Besuch zu Follow',
  'beğeni ÷ görüntülenme': 'Likes ÷ Aufrufe',
  'yorum ÷ görüntülenme': 'Kommentare ÷ Aufrufe',
  'paylaşım ÷ görüntülenme': 'Geteilt ÷ Aufrufe',
  'içeriğe tıklama ÷ görüntülenme': 'Klicks auf Inhalt ÷ Aufrufe',
  'profil ziyareti ÷ görüntülenme': 'Profilbesuche ÷ Aufrufe',
  'yeni takip ÷ profil ziyareti': 'neue Follows ÷ Profilbesuche',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'Für die Raten sind mindestens {} Aufrufe nötig; aktuell sind es {}.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'Die Raten stammen aus den Gesamtzahlen des Beitrags; die Tagesauswahl unten ändert sie nicht.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'Diese Zahlen sind die Gesamtwerte des Beitrags (außer Feldern mit eigener Notiz); die Tagesauswahl unten ändert nur das Diagramm.',
  'Ortalama izlenme: videonun %{} kadarı':
      'Durchschnittlich gesehen: {} % des Videos',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'Durchschnitt der 20 Abschnitte der Kurve.',
  'Dizi, film, kişi veya şirket ara...':
      'Serie, Film, Person oder Unternehmen suchen...',
  'Şirketler': 'Unternehmen',
  'Senarist': 'Drehbuchautor',
  'Bölüm puanları': 'Folgenbewertungen',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi':
      'Folgenbewertungen konnten nicht geladen werden',
  'Giriş gerekli': 'Anmeldung erforderlich',
  'Geçersiz oturum': 'Ungültige Sitzung',
  'Oturum sonlandı, tekrar giriş yap': 'Sitzung beendet, bitte neu anmelden',
  'Çok fazla istek; biraz sonra tekrar dene':
      'Zu viele Anfragen; versuch es gleich nochmal',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'Momentan kein Speicherplatz auf dem Server, versuch es gleich nochmal',
  'Devam eden yapımlar ({})': 'Laufende Produktionen ({})',
  'Diziler ({})': 'Serien ({})',
  'Filmler ({})': 'Filme ({})',
  'Tüm yapımlar': 'Alle Produktionen',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'Dein Medienspeicher ist voll; lösche alte Uploads, um Platz zu schaffen',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'E-Mail/Benutzername oder Passwort falsch',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'Diese E-Mail oder dieser Name ist schon vergeben',
  'Google doğrulaması başarısız': 'Google-Bestätigung fehlgeschlagen',
  'Kod geçersiz veya süresi dolmuş': 'Code ungültig oder abgelaufen',
  'Bu kullanıcıyla mesajlaşamazsın': 'Du kannst diesem Konto nicht schreiben',
  'Kendini takip edemezsin': 'Du kannst dir nicht selbst folgen',
  'Bu kullanıcıyı takip edemezsin': 'Du kannst diesem Konto nicht folgen',
  'Kendini engelleyemezsin': 'Du kannst dich nicht selbst blockieren',
  'Yorum 1-1000 karakter olmalı': 'Kommentar muss 1–1000 Zeichen haben',
  'Boş mesaj gönderilemez': 'Leere Nachricht geht nicht',
  'Yorum bulunamadı': 'Kommentar nicht gefunden',
  'Şifre hatalı': 'Falsches Passwort',
  'Şifre en az 6 karakter olmalı': 'Passwort mindestens 6 Zeichen',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'Nur GIF, PNG, JPEG oder WebP möglich',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'Erlaubt: GIF, PNG, JPEG, WebP, MP4, WebM, Audio',
  'Geçerli bir ZIP dosyası değil': 'Keine gültige ZIP-Datei',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'Um deine Daten per E-Mail zu bekommen, verknüpfe zuerst eine Adresse',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'Du hast bereits gesehen-Marken. Für „Will ich sehen“ müssen sie zuerst weg.',
  'Arama şu anda kapalı': 'Anrufe sind gerade aus',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'Gastkonten können Anrufe nicht anschalten; erst ein Konto anlegen',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'Server startet neu, versuch es gleich nochmal',
  'Puan 1-10 arası olmalı': 'Bewertung muss zwischen 1 und 10 liegen',
  'En fazla 10 medya eklenebilir': 'Höchstens 10 Medien möglich',
  'Bu cihazdan yeni hesap açılamıyor':
      'Von diesem Gerät kann kein Konto erstellt werden',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'Gültige E-Mail, Nutzername und ein Passwort mit mindestens 6 Zeichen sind nötig',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'Gültige E-Mail und ein Passwort mit mindestens 6 Zeichen sind nötig',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'Nutzername 3–20 Zeichen; Kleinbuchstaben, Ziffern, Punkte, Bindestriche, Unterstriche (nicht am Rand)',
  'Bu hesap zaten bağlı': 'Dieses Konto ist bereits verknüpft',
  'Hesap oluşturulamadı': 'Konto konnte nicht erstellt werden',
  'Misafir hesabı oluşturulamadı': 'Gastkonto konnte nicht erstellt werden',
  'Hesap bulunamadı': 'Konto nicht gefunden',
  'Bu hesapta e-posta yok': 'Dieses Konto hat keine E-Mail',
  'İki adımlı doğrulama zaten bu durumda':
      'Die Zwei-Schritt-Bestätigung ist schon in diesem Zustand',
  'Kod yanlış': 'Falscher Code',
  'Kodun süresi doldu': 'Code abgelaufen',
  'Kullanıcının e-postası yok (misafir hesap)':
      'Dieser Nutzer hat keine E-Mail (Gastkonto)',
  'Bio en fazla 300 karakter olabilir': 'Bio höchstens 300 Zeichen',
  'Geçersiz ülke': 'Ungültiges Land',
  'Geçersiz sosyal bağlantı': 'Ungültiger Social-Link',
  'Geçersiz doğum tarihi': 'Ungültiges Geburtsdatum',
  'Liste adı gerekli': 'Listenname ist erforderlich',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'Name höchstens 60, Beschreibung 300 Zeichen',
  'Liste bulunamadı': 'Liste nicht gefunden',
  'Değiştirilecek tercih yok': 'Nichts zu aktualisieren',
  'İnceleme en fazla 2000 karakter olabilir':
      'Rezension höchstens 2000 Zeichen',
  'Önce içeriği "bitirdim" olarak işaretle':
      'Markiere den Titel zuerst als abgeschlossen',
  'Önce kişiyi favorile': 'Setze die Person zuerst auf Favoriten',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'Für einen Folgenkommentar sind Staffel und Folge nötig',
  'Yanıtlanan yorum bulunamadı': 'Beantworteter Kommentar nicht gefunden',
  'Geri bildirim 3-2000 karakter olmalı': 'Feedback muss 3–2000 Zeichen haben',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'Titel und Text sind nötig (mindestens 2 Zeichen)',
  'Kendine mesaj gönderemezsin': 'Du kannst dir nicht selbst schreiben',
  'Mesaj en fazla 2000 karakter olabilir': 'Nachricht höchstens 2000 Zeichen',
  'Mesaj 1-2000 karakter olmalı': 'Nachricht muss 1–2000 Zeichen haben',
  'Mesaj bulunamadı': 'Nachricht nicht gefunden',
  'Mesaj bulunamadı veya düzenlenemez':
      'Nachricht nicht gefunden oder nicht bearbeitbar',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'Du kannst nur eine an dich gesendete Nachricht melden',
  'Sebep gerekli': 'Grund ist erforderlich',
  'İtiraz edilecek aktif bir ceza yok':
      'Es gibt keine aktive Strafe zum Einspruch',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'Du hast bereits einen Einspruch in Prüfung',
  'Bu ceza için itirazın zaten incelendi':
      'Dein Einspruch zu dieser Strafe wurde schon geprüft',
  'Medya bağlantısının süresi dolmuş': 'Medienlink abgelaufen',
  'Bu medya için imzalı bağlantı gerekli':
      'Für dieses Medium ist ein signierter Link nötig',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'Der Anrufdienst startet neu; versuch es gleich nochmal',
  'Puan göstergesi': 'Bewertungslegende',
  'İzleme İstatistiklerim': 'Meine Sehstatistik',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'Sobald du eine Folge oder einen Film als gesehen markierst, sammeln sich deine Statistiken hier an.',
  '{} sa {} dk': '{} Std. {} Min.',
  'Yaklaşık ekran süresi': 'Ungefähre Bildschirmzeit',
  'İzleme serisi': 'Seh-Serie',
  'Şu anki seri': 'Aktuelle Serie',
  'En uzun seri': 'Längste Serie',
  'Haftanın günleri': 'Wochentage',
  'En çok izlediklerin': 'Am meisten gesehen',
  'Bu dönemde izleme yok': 'In diesem Zeitraum nichts gesehen',
  'Tüm zamanlar: {} bölüm · {} film · ~{}':
      'Insgesamt: {} Folgen · {} Filme · ~{}',
  'Paz': 'So',
  'Pzt': 'Mo',
  'Sal': 'Di',
  'Çar': 'Mi',
  'Per': 'Do',
  'Cum': 'Fr',
  'Cmt': 'Sa',
  '{} bölüm': '{} Folgen',
  '{} bölüm~tekil': '{} Folge',
  '{} kez': '{} Mal',
  '{} kez~tekil': '{} Mal',
  'Son {} gün · günlük': 'Letzte {} Tage · täglich',
  'Son {} gün · haftalık': 'Letzte {} Tage · wöchentlich',
  'Ekran süren, serin ve en çok izlediklerin':
      'Deine Bildschirmzeit, Serie und Favoriten',
  'Daralt': 'Einklappen',
  'Listeyi düzenle': 'Liste bearbeiten',
  'Bitti': 'Fertig',
  'Sırala': 'Sortieren',
  'Herkese göster': 'Für alle anzeigen',
  'Başkalarından gizle': 'Vor anderen verbergen',
  'Listeden kaldır': 'Aus der Liste entfernen',
  'Listeden kaldırılsın mı?': 'Aus der Liste entfernen?',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'Dieser Titel wird aus der Liste genommen. Wenn du ihn nur verbergen möchtest, nutze das Augensymbol.',
  'Sıralama kaydedilemedi': 'Reihenfolge konnte nicht gespeichert werden',
  'Değişiklik kaydedilemedi': 'Änderung konnte nicht gespeichert werden',
  'Kaldırılamadı': 'Konnte nicht entfernt werden',
};
