/// Otomatik üretilen çeviri haritası (th).
const Map<String, String> cevirilerTh = {
  'Aktarılacak tanınan veri bulunamadı.': 'ไม่พบข้อมูลที่นำเข้าได้',
  'Arama': 'ค้นหา',
  'Aramaya başla': 'เริ่มค้นหาเลย',
  'Son aramalar': 'การค้นหาล่าสุด',
  'Ayarlar': 'การตั้งค่า',
  'Bağla': 'เชื่อมบัญชี',
  'Bio': 'ประวัติ',
  'Bitirdim': 'ดูจบแล้ว',
  'Bunları da Beğenebilirsin': 'คุณอาจชอบเรื่องเหล่านี้',
  'Bölüm': 'ตอน',
  'Bıraktım': 'เลิกดูแล้ว',
  'Dil': 'ภาษา',
  'Dil ara...': 'ค้นหาภาษา...',
  'Dizi': 'ซีรีส์',
  'Dizi ve filmlerini takip et': 'ติดตามซีรีส์และหนังของคุณ',
  'Dizi yorumu': 'คอมเมนต์ซีรีส์',
  'Dizi, film veya kişi ara...': 'ค้นหาซีรีส์ หนัง หรือบุคคล...',
  'Dosya en fazla 30MB olabilir': 'ไฟล์ต้องไม่เกิน 30MB',
  'Dosya en fazla {}MB olabilir': 'ไฟล์ต้องไม่เกิน {}MB',
  'E-posta': 'อีเมล',
  'E-posta veya kullanıcı adı': 'อีเมลหรือชื่อผู้ใช้',
  'En az 2 harf yaz': 'พิมพ์อย่างน้อย 2 ตัวอักษร',
  'Film': 'หนัง',
  'Film yorumu': 'คอมเมนต์หนัง',
  'Fotoğraf / video ekle': 'เพิ่มรูปภาพ / วิดีโอ',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'รูปภาพหรือ GIF — รูปโปรไฟล์และรูปปก',
  'Giriş Yap': 'เข้าสู่ระบบ',
  'Gönder': 'ส่ง',
  'Gönderildi': 'ส่งแล้ว',
  'Haftanın Dizileri': 'ซีรีส์ประจำสัปดาห์',
  'Haftanın Filmleri': 'หนังประจำสัปดาห์',
  'Henüz izleme kaydın yok': 'ยังไม่มีประวัติการดู',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'ยังไม่มีลิสต์ — สร้างได้จากแท็บโปรไฟล์',
  'Henüz yorum yok.': 'ยังไม่มีคอมเมนต์',
  'Hesabın bağlandı!': 'เชื่อมบัญชีสำเร็จแล้ว!',
  'Hesabın yok mu? Kayıt ol': 'ยังไม่มีบัญชี? สมัครสมาชิก',
  'Hesabını Bağla': 'เชื่อมบัญชีของคุณ',
  'Hesap Oluştur': 'สร้างบัญชี',
  'Kapak resmi ekle': 'เพิ่มรูปปก',
  'Kaydet': 'บันทึก',
  'Kendinden bahset...': 'เล่าเกี่ยวกับตัวคุณ...',
  'Keşfet': 'สำรวจ',
  'Kimseyi takip etmiyor': 'ยังไม่ได้ติดตามใคร',
  'Kişi ara': 'ค้นหาบุคคล',
  'Kişi yorumu': 'คอมเมนต์บุคคล',
  'Konuk Oyuncular': 'นักแสดงรับเชิญ',
  'Kullanıcı adı (küçük harf)': 'ชื่อผู้ใช้ (ตัวพิมพ์เล็ก)',
  'Kullanıcı adı ara...': 'ค้นหาชื่อผู้ใช้...',
  'Liste adı': 'ชื่อลิสต์',
  'Listeye Ekle': 'เพิ่มลงลิสต์',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'คุณกำลังใช้บัญชีผู้เยี่ยมชม — เชื่อมอีเมลไว้ จะได้ไม่เสียข้อมูล!',
  'Misafir olarak devam et': 'ดำเนินการต่อในฐานะผู้เยี่ยมชม',
  'Oluştur': 'สร้าง',
  'Oyuncular': 'นักแสดง',
  'Profil': 'โปรไฟล์',
  'Profil kaydedildi': 'บันทึกโปรไฟล์แล้ว',
  'Puanla': 'ให้คะแนน',
  'Puanı Sil': 'ลบคะแนน',
  'Puanın': 'คะแนนของคุณ',
  'Sezonlar': 'ซีซัน',
  'Sunucu hatası ({})': 'เซิร์ฟเวอร์ผิดพลาด ({})',
  'S{} · {}. Bölüm': 'S{} · ตอนที่ {}',
  'S{}B{} yorumu': 'คอมเมนต์ S{}E{}',
  'Takibi Bırak': 'เลิกติดตาม',
  'Takip': 'กำลังติดตาม',
  'Takip Edilenler': 'กำลังติดตาม',
  'Takip Et': 'ติดตาม',
  'Takipçi': 'ผู้ติดตาม',
  'Takipçi yok': 'ยังไม่มีผู้ติดตาม',
  'Takipçiler': 'ผู้ติดตาม',
  'Takvim': 'ปฏิทิน',
  'Tamam': 'ตกลง',
  'Tekrar Dene': 'ลองอีกครั้ง',
  'Tekrar dene': 'ลองอีกครั้ง',
  'Toplam ekran süresi': 'เวลาดูทั้งหมด',
  'Tüm Zamanların En İyileri': 'สุดยอดตลอดกาล',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'ส่งออกข้อมูลทั้งหมดของคุณ (การดู คะแนน คอมเมนต์ ลิสต์) เป็น ZIP ที่ใช้ได้กับ TV Time หรือนำเข้า ZIP จากแอปอื่น',
  'Tümünü Kaldır': 'เอาออกทั้งหมด',
  'Tümünü İzledim': 'ดูครบทุกตอนแล้ว',
  'Türk Dizileri': 'ซีรีส์ตุรกี',
  'Veri içe aktar (.zip)': 'นำเข้าข้อมูล (.zip)',
  'Verilerim': 'ข้อมูลของฉัน',
  'Verilerimi dışa aktar (e-posta)': 'ส่งออกข้อมูลของฉัน (อีเมล)',
  'Verilerini dışa aktar': 'ส่งออกข้อมูลของคุณ',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'ไม่มีตอนที่กำลังจะมาถึง\nไปที่หน้ารายละเอียดซีรีส์แล้วตั้งเป็น "กำลังดู" เพื่อติดตามตอนใหม่ที่นี่',
  'Yapımları': 'ผลงาน',
  'Yeni Diziler': 'ซีรีส์มาใหม่',
  'Yeni Liste': 'ลิสต์ใหม่',
  'Yeni kullanıcı adı (isteğe bağlı)': 'ชื่อผู้ใช้ใหม่ (ไม่บังคับ)',
  'Yorum': 'คอมเมนต์',
  'Yorumunu yaz...': 'เขียนคอมเมนต์ของคุณ...',
  'Zaten hesabın var mı? Giriş yap': 'มีบัญชีอยู่แล้ว? เข้าสู่ระบบ',
  'ort. {}': 'เฉลี่ย {}',
  'takip': 'กำลังติดตาม',
  'takipçi': 'ผู้ติดตาม',
  '{} / {} bölüm': '{} / {} ตอน',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} เดือน',
  '{} bölüm izlendi': 'ดูแล้ว {} ตอน',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} นาที',
  '{} gün': '{} วัน',
  '{} içerik': '{} รายการ',
  '{} içerik · otomatik': '{} รายการ · อัตโนมัติ',
  '{} kayıt atlandı (eşleşmedi).': 'ข้าม {} รายการ (ไม่ตรงกัน)',
  '{} saat': '{} ชั่วโมง',
  '{} sezon': '{} ซีซัน',
  '{} yıl': '{} ปี',
  '{}. Bölüm': 'ตอนที่ {}',
  '{}. Sezon': 'ซีซัน {}',
  'Çıkış Yap': 'ออกจากระบบ',
  'Ülke': 'ประเทศ',
  'Ülke ara...': 'ค้นหาประเทศ...',
  'Ülke seç': 'เลือกประเทศ',
  'İlk yorumu sen yaz!': 'เป็นคนแรกที่คอมเมนต์เลย!',
  'İncelemeler': 'รีวิว',
  'İncelemen (isteğe bağlı)': 'รีวิวของคุณ (ไม่บังคับ)',
  'İptal': 'ยกเลิก',
  'İzlediklerim': 'ประวัติการดู',
  'İzledim': 'ดูแล้ว',
  'İzledin': 'คุณดูแล้ว',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'ประวัติการดูและลิสต์ของคุณจะถูกเก็บไว้ และตอนนี้เข้าสู่ระบบได้จากทุกอุปกรณ์',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'ประวัติการดู คะแนน คอมเมนต์ และลิสต์ของคุณจะถูกส่งเป็นไฟล์ ZIP ไปยังอีเมลที่ลงทะเบียนไว้',
  'İzleyeceğim': 'จะดู',
  'İzliyorum': 'กำลังดู',
  'İçe aktarım tamamlandı': 'นำเข้าข้อมูลเสร็จแล้ว',
  'Şifre': 'รหัสผ่าน',
  '• profil bilgisi': '• ข้อมูลโปรไฟล์',
  '• {} dizi durumu': '• สถานะซีรีส์ {} รายการ',
  '• {} izleme kaydı': '• ประวัติการดู {} รายการ',
  '• {} liste': '• ลิสต์ {} รายการ',
  '• {} puan': '• คะแนน {} รายการ',
  '• {} yorum': '• คอมเมนต์ {} รายการ',
  '{}+ yapım': '{}+ ผลงาน',
  'Yorumlar': 'คอมเมนต์',
  'Yorumlar ({})': 'คอมเมนต์ ({})',
  'Yorumları ({})': 'คอมเมนต์ของเขา ({})',
  'Listelerim': 'ลิสต์ของฉัน',
  'Nereden izledin?': 'ดูจากที่ไหน?',
  'Diziye git': 'ไปที่ซีรีส์',
  'TV / Kanal': 'ทีวี / ช่อง',
  'Sinema': 'โรงภาพยนตร์',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'อื่น ๆ',
  'Akış': 'ฟีด',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'ฟีดของคุณว่างเปล่า\nเมื่อมีคนคอมเมนต์ซีรีส์และหนังที่คุณดู จะแสดงที่นี่',
  'Listeleri ({})': 'ลิสต์ของเขา ({})',
  'Liste boş.': 'ลิสต์นี้ว่างเปล่า',
  'Yanıtla': 'ตอบกลับ',
  '@{} kullanıcısına yanıt veriyorsun': 'กำลังตอบกลับ @{}',
  'İzlediğim Diziler ({})': 'ซีรีส์ที่ดูแล้ว ({})',
  'İzlediğim Filmler ({})': 'หนังที่ดูแล้ว ({})',
  'Tümünü gör': 'ดูทั้งหมด',
  'Bildirimler': 'การแจ้งเตือน',
  'Henüz bildirim yok': 'ยังไม่มีการแจ้งเตือน',
  '@{} yorumuna yanıt verdi': '@{} ตอบกลับคอมเมนต์ของคุณ',
  '@{} yorumunu beğendi': '@{} ถูกใจคอมเมนต์ของคุณ',
  '@{} seni takip etti': '@{} ติดตามคุณ',
  '@{} sana mesaj gönderdi': '@{} ส่งข้อความถึงคุณ',
  'Mesajlar': 'ข้อความ',
  'Mesaj': 'ข้อความ',
  'Mesajını yaz...': 'พิมพ์ข้อความ...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'ยังไม่มีแชท\nเปิดโปรไฟล์แล้วส่งข้อความเลย',
  'Şifreni mi unuttun?': 'ลืมรหัสผ่าน?',
  'Şifreyi Sıfırla': 'รีเซ็ตรหัสผ่าน',
  'E-postadaki kod': 'รหัสจากอีเมล',
  'Yeni şifre': 'รหัสผ่านใหม่',
  'Sana Özel': 'สำหรับคุณ',
  '{} özetin': 'สรุปปี {} ของคุณ',
  'Yıllık izleme istatistiklerin': 'สถิติการดูรายปี',
  'Rozetler': 'เหรียญตรา',
  'Verdiğin puan': 'คะแนนที่ให้',
  'Ortalama puanın': 'คะแนนเฉลี่ย',
  'En çok izlediğin diziler': 'ซีรีส์ที่ดูมากที่สุด',
  'İlk Bölüm': 'ตอนแรก',
  '100 Bölüm': '100 ตอน',
  '1000 Bölüm': '1000 ตอน',
  'İlk Film': 'หนังเรื่องแรก',
  '50 Film': 'หนัง 50 เรื่อง',
  'İlk Yorum': 'คอมเมนต์แรก',
  '25 Yorum': '25 คอมเมนต์',
  '10 Puan': 'ให้คะแนน 10 ครั้ง',
  'İlk Takipçi': 'ผู้ติดตามคนแรก',
  '10 Dizi Bitirdin': 'ดูจบ 10 เรื่อง',
  'İzlemeyi Bıraktım': 'เลิกดูแล้ว',
  'İzlediği Diziler ({})': 'ซีรีส์ที่เขาดู ({})',
  'İzlediği Filmler ({})': 'หนังที่เขาดู ({})',
  '500 Bölüm': '500 ตอน',
  '5000 Bölüm': '5000 ตอน',
  '10 Film': 'หนัง 10 เรื่อง',
  '100 Film': 'หนัง 100 เรื่อง',
  '100 Yorum': '100 คอมเมนต์',
  '50 Puan': 'ให้คะแนน 50 ครั้ง',
  '100 Puan': 'ให้คะแนน 100 ครั้ง',
  '10 Takipçi': 'ผู้ติดตาม 10 คน',
  '50 Takipçi': 'ผู้ติดตาม 50 คน',
  '25 Dizi Bitirdin': 'ดูจบ 25 เรื่อง',
  '50 Dizi Bitirdin': 'ดูจบ 50 เรื่อง',
  '10 Beğeni': '10 ไลก์',
  '100 Beğeni': '100 ไลก์',
  'yazıyor...': 'กำลังพิมพ์...',
  'Profil düzeni': 'เลย์เอาต์โปรไฟล์',
  'Konumla ve kırp': 'จัดตำแหน่งและครอบตัด',
  'Listeye eklendi': 'เพิ่มลงลิสต์แล้ว',
  'Listeyi sil?': 'ลบลิสต์?',
  'Sil': 'ลบ',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'เรื่องนี้จะถูกทำเครื่องหมายว่าไม่เคยดูและถูกลบออกจากลิสต์ของคุณ',
  'Gelecek bölüm bugün': 'ตอนต่อไปวันนี้',
  'Gelecek bölüm {} gün sonra': 'ตอนต่อไปในอีก {} วัน',
  'Tema': 'ธีม',
  'Sistem': 'ระบบ',
  'Koyu': 'มืด',
  'Açık': 'สว่าง',
  'İzleyenler': 'ผู้ชม',
  'Yorumunu yaz... (@ ile etiketle)': 'เขียนคอมเมนต์ของคุณ... (@ เพื่อแท็ก)',
  '@{} bir yorumda seni etiketledi': '@{} แท็กคุณในคอมเมนต์',
  'Mesajı sil': 'ลบข้อความ',
  'Mesaj silinemedi': 'ไม่สามารถลบข้อความได้',
  'Bağlantı geçersiz veya sayfa bulunamadı': 'ลิงก์ไม่ถูกต้องหรือไม่พบหน้า',
  'Keşfet\'e dön': 'กลับไปที่สำรวจ',
  'Düzenle': 'แก้ไข',
  'Mesajı düzenle': 'แก้ไขข้อความ',
  'Yanıtlanıyor': 'กำลังตอบกลับ',
  'düzenlendi': 'แก้ไขแล้ว',
  'Fotoğraf': 'รูปภาพ',
  'Video': 'วิดีโอ',
  'İçerik': 'เนื้อหา',
  'çevrimiçi': 'ออนไลน์',
  'son görülme {} dk önce': 'เห็นล่าสุด {} นาทีที่แล้ว',
  'son görülme {} saat önce': 'เห็นล่าสุด {} ชม.ที่แล้ว',
  'son görülme {} gün önce': 'เห็นล่าสุด {} วันที่แล้ว',
  'Yorumlar yüklenemedi': 'โหลดคอมเมนต์ไม่สำเร็จ',
  'Favori': 'รายการโปรด',
  'Listeye ekle': 'เพิ่มลงในลิสต์',
  'İçerik paylaş': 'แชร์เนื้อหา',
  'Kapat': 'ปิด',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'ทุกอย่างที่คุณทำเครื่องหมายว่าดูแล้วจะรวมอยู่ที่นี่',
  'Henüz sohbetin yok': 'ยังไม่มีการสนทนา',
  'Bir profile girip mesaj gönderebilirsin.': 'เปิดโปรไฟล์แล้วส่งข้อความ',
  'Listeyi sil': 'ลบลิสต์',
  'Puan kaydedilemedi': 'ไม่สามารถบันทึกคะแนนได้',
  'Nerede İzlenir': 'รับชมได้ที่ไหน',
  'Abonelik': 'สมัครสมาชิก',
  'Kirala': 'เช่า',
  'Satın al': 'ซื้อ',
  'Hoş geldin!': 'ยินดีต้อนรับ!',
  'İzlemek istediğin dizi ve filmleri seç': 'เลือกซีรีส์และหนังที่คุณอยากดู',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'รายการที่เลือกจะถูกเพิ่มในลิสต์ดูของคุณ',
  'Şimdilik atla': 'ข้ามไปก่อน',
  'Devam et': 'ดำเนินการต่อ',
  '{} ekle': 'เพิ่ม {}',
  'Şikayet et': 'รายงาน',
  'Engelle': 'บล็อก',
  'Engeli kaldır': 'เลิกบล็อก',
  'Kullanıcı engellendi': 'บล็อกผู้ใช้แล้ว',
  'Engel kaldırıldı': 'เลิกบล็อกแล้ว',
  'Şikayet sebebi': 'เหตุผลการรายงาน',
  'Spam veya yanıltıcı': 'สแปมหรือทำให้เข้าใจผิด',
  'Taciz veya nefret söylemi': 'การคุกคามหรือคำพูดสร้างความเกลียดชัง',
  'Uygunsuz / cinsel içerik': 'ไม่เหมาะสม / เนื้อหาทางเพศ',
  'Şiddet veya tehlikeli içerik': 'ความรุนแรงหรือเนื้อหาอันตราย',
  'Telif hakkı ihlali': 'การละเมิดลิขสิทธิ์',
  'Şikayetin alındı, teşekkürler': 'ได้รับรายงานของคุณแล้ว ขอบคุณ',
  'Hesabımı Sil': 'ลบบัญชีของฉัน',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'บัญชีและข้อมูลทั้งหมดของคุณ (ประวัติการดู คะแนน คอมเมนต์ ลิสต์ ข้อความ) จะถูกลบถาวร ไม่สามารถกู้คืนได้',
  'Şifreni gir': 'ใส่รหัสผ่านของคุณ',
  'Hesabımı kalıcı sil': 'ลบบัญชีของฉันถาวร',
  'Sesli mesaj': 'ข้อความเสียง',
  'Ses gönderilemedi': 'ส่งข้อความเสียงไม่สำเร็จ',
  'Kaydediliyor…': 'กำลังบันทึก…',
  'Ses oynatılamadı': 'เล่นเสียงไม่ได้',
  'Oynat': 'เล่น',
  'Duraklat': 'หยุดชั่วคราว',
  'Liste görünümü': 'มุมมองรายการ',
  'Takvim görünümü': 'มุมมองปฏิทิน',
  'Önceki ay': 'เดือนก่อนหน้า',
  'Sonraki ay': 'เดือนถัดไป',
  'Bu gün bölüm yok': 'ไม่มีตอนในวันนี้',
  'Gizlilik Politikası': 'นโยบายความเป็นส่วนตัว',
  'Son güncelleme: {}': 'อัปเดตล่าสุด: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'นโยบายนี้อธิบายว่ามีการเก็บข้อมูลอะไรบ้าง นำไปใช้อย่างไร และคุณมีสิทธิ์อะไรบ้างเมื่อใช้แอป dizi.jpg และเว็บไซต์ dizijpg.com',
  'Topladığımız Veriler': 'ข้อมูลที่เราเก็บ',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'บัญชี: ที่อยู่อีเมล ชื่อผู้ใช้ และรหัสผ่าน รหัสผ่านถูกเก็บเป็นแฮชที่ย้อนกลับไม่ได้ บัญชีผู้เยี่ยมชมใช้ได้โดยไม่ต้องมีอีเมล',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'โปรไฟล์: ข้อมูลที่คุณเลือกเพิ่มเอง เช่น อวตาร ภาพปก ประวัติย่อ และประเทศ',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'การใช้งาน: ประวัติการดู คะแนน ความคิดเห็น รายการ รีแอ็กชัน และรายการโปรดของคุณ',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'ข้อความ: ข้อความตัวอักษร รูปภาพ และเสียงของคุณถูกเก็บบนเซิร์ฟเวอร์ของเรา ข้อความไม่ได้เข้ารหัสแบบต้นทางถึงปลายทาง จะถูกตรวจดูเพื่อการดูแลเนื้อหาก็ต่อเมื่อมีการรายงานเท่านั้น',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'สื่อที่อัปโหลด: รูปภาพ GIF วิดีโอ และเสียงบันทึกที่คุณเพิ่มในโปรไฟล์ ความคิดเห็น และข้อความ',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'ข้อมูลทางเทคนิค: ที่อยู่ IP ตำแหน่งโดยประมาณ (ระดับประเทศ/เมือง) แพลตฟอร์มอุปกรณ์ เวอร์ชันแอป และบันทึกข้อผิดพลาด เก็บไว้เพื่อความปลอดภัยและการแก้ไขปัญหา',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'การแจ้งเตือน: สำหรับการแจ้งเตือนแบบพุช เราเก็บโทเคนอุปกรณ์และภาษาที่คุณเลือก คุณปิดการแจ้งเตือนได้ทุกเมื่อในการตั้งค่าอุปกรณ์',
  'Verileri Nasıl Kullanırız': 'เราใช้ข้อมูลอย่างไร',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'เราใช้ข้อมูลของคุณเพื่อให้บริการ ปกป้องบัญชี ส่งการแจ้งเตือน แก้ไขข้อผิดพลาด และป้องกันการใช้งานในทางที่ผิดเท่านั้น เราไม่ขายข้อมูลของคุณ และไม่แชร์ให้ใครเพื่อการโฆษณา',
  'Çerezler ve Yerel Depolama': 'คุกกี้และพื้นที่จัดเก็บในเครื่อง',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'เราใช้พื้นที่จัดเก็บในเครื่องเพียงเพื่อให้คุณล็อกอินค้างไว้ และจดจำการตั้งค่าอย่างภาษาและธีม ไม่มีคุกกี้โฆษณาหรือติดตามใด ๆ',
  'Üçüncü Taraf Hizmetler': 'บริการของบุคคลที่สาม',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'ข้อมูลซีรีส์และภาพยนตร์มาจาก TMDB ข้อมูลแพลตฟอร์มสตรีมมิงมาจาก JustWatch การแจ้งเตือนแบบพุชส่งผ่าน Google Firebase และทราฟฟิกของเว็บไซต์ได้รับการปกป้องโดย Cloudflare บริการเหล่านี้อยู่ภายใต้นโยบายความเป็นส่วนตัวของตนเอง',
  'Saklama ve Silme': 'การเก็บรักษาและการลบ',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'ข้อมูลของคุณถูกเก็บไว้ตราบเท่าที่บัญชียังอยู่ คุณลบบัญชีถาวรได้ด้วย "ลบบัญชีของฉัน" ในการตั้งค่า ข้อมูลถูกลบทันที ส่วนสำเนาในข้อมูลสำรองถูกลบภายใน 14 วันเป็นอย่างช้า บันทึกข้อผิดพลาดถูกลบอัตโนมัติหลัง 30 วัน',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'คุณส่งออกข้อมูลเป็น ZIP ได้จากการตั้งค่า ไฟล์เก็บถาวรจะถูกส่งไปยังที่อยู่อีเมลของคุณ',
  'Güvenlik': 'ความปลอดภัย',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'ข้อมูลถูกส่งผ่านการเชื่อมต่อที่เข้ารหัส (HTTPS) และเก็บบนเซิร์ฟเวอร์ที่จำกัดการเข้าถึง',
  'Çocukların Gizliliği': 'ความเป็นส่วนตัวของเด็ก',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg ไม่ได้มีไว้สำหรับเด็กอายุต่ำกว่า 13 ปี',
  'Hakların': 'สิทธิ์ของคุณ',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'ตาม KVKK และ GDPR คุณมีสิทธิ์เข้าถึง แก้ไข ลบ และโอนย้ายข้อมูลของคุณ ติดต่อเราได้ที่: {}',
  'Değişiklikler': 'การเปลี่ยนแปลง',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'หากนโยบายนี้เปลี่ยนแปลง เวอร์ชันใหม่จะถูกเผยแพร่ในหน้านี้และวันที่จะถูกอัปเดต',
  'Kayıt olarak {} kabul etmiş olursun.': 'เมื่อสมัครสมาชิก แสดงว่าคุณยอมรับ{}',
  'Kullanıcılar': 'ผู้ใช้',
  'Fotoğrafı değiştir': 'เปลี่ยนรูป',
  'Yeniden konumlandır': 'จัดตำแหน่งใหม่',
  'Bir şeyler ters gitti': 'มีบางอย่างผิดพลาด',
  'Sosyal Bağlantılar': 'ลิงก์โซเชียล',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'โปรไฟล์ของคุณแสดงลิงก์ได้สูงสุด 3 ลิงก์',
  'Platform seç': 'เลือกแพลตฟอร์ม',
  'Kullanıcı adın': 'ชื่อผู้ใช้ของคุณ',
  'Ekle': 'เพิ่ม',
  'Kaldır': 'ลบออก',
  'Kopyalandı: {}': 'คัดลอกแล้ว: {}',
  'Geçersiz kullanıcı adı': 'ชื่อผู้ใช้ไม่ถูกต้อง',
  'Bağlantı ekle': 'เพิ่มลิงก์',
};
