/// Otomatik üretilen çeviri haritası (en).
const Map<String, String> cevirilerEn = {
  'Aktarılacak tanınan veri bulunamadı.': 'No recognized data found to import.',
  'Arama': 'Search',
  'Aramaya başla': 'Start searching',
  'Son aramalar': 'Recent searches',
  'Ayarlar': 'Settings',
  'Bağla': 'Link',
  'Bio': 'Bio',
  'Bitirdim': 'Finished',
  'Bunları da Beğenebilirsin': 'You Might Also Like',
  'Bölüm': 'Episode',
  'Bıraktım': 'Dropped',
  'Dil': 'Language',
  'Dil ara...': 'Search language...',
  'Dizi': 'TV Show',
  'Dizi ve filmlerini takip et': 'Track your shows and movies',
  'Dizi yorumu': 'Show comment',
  'Dizi, film veya kişi ara...': 'Search shows, movies or people...',
  'Dosya en fazla 30MB olabilir': 'File can be at most 30MB',
  'Dosya en fazla {}MB olabilir': 'File can be at most {}MB',
  'E-posta': 'Email',
  'E-posta veya kullanıcı adı': 'Email or username',
  'En az 2 harf yaz': 'Type at least 2 letters',
  'Film': 'Movie',
  'Film yorumu': 'Movie comment',
  'Fotoğraf / video ekle': 'Add photo / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Photo or GIF — profile and cover image',
  'Giriş Yap': 'Log In',
  'Gönder': 'Send',
  'Gönderildi': 'Sent',
  'Haftanın Dizileri': 'Shows of the Week',
  'Haftanın Filmleri': 'Movies of the Week',
  'Henüz izleme kaydın yok': 'No watch history yet',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'No lists yet — create one from the Profile tab.',
  'Henüz yorum yok.': 'No comments yet.',
  'Hesabın bağlandı!': 'Your account is linked!',
  'Hesabın yok mu? Kayıt ol': 'Don\'t have an account? Sign up',
  'Hesabını Bağla': 'Link Your Account',
  'Hesap Oluştur': 'Create Account',
  'Kapak resmi ekle': 'Add cover image',
  'Kaydet': 'Save',
  'Kendinden bahset...': 'Tell us about yourself...',
  'Keşfet': 'Discover',
  'Kimseyi takip etmiyor': 'Not following anyone',
  'Kişi ara': 'Search people',
  'Kişi yorumu': 'Person comment',
  'Konuk Oyuncular': 'Guest Stars',
  'Kullanıcı adı (küçük harf)': 'Username (lowercase)',
  'Kullanıcı adı ara...': 'Search username...',
  'Liste adı': 'List name',
  'Listeye Ekle': 'Add to List',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'You\'re on a guest account — link your email so you don\'t lose your data!',
  'Misafir olarak devam et': 'Continue as guest',
  'Oluştur': 'Create',
  'Oyuncular': 'Cast',
  'Profil': 'Profile',
  'Profil kaydedildi': 'Profile saved',
  'Puanla': 'Rate',
  'Puanı Sil': 'Delete Rating',
  'Puanın': 'Your rating',
  'Sezonlar': 'Seasons',
  'Sunucu hatası ({})': 'Server error ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'S{}E{} comment',
  'Takibi Bırak': 'Unfollow',
  'Takip': 'Following',
  'Takip Edilenler': 'Following',
  'Takip Et': 'Follow',
  'Takipçi': 'Followers',
  'Takipçi yok': 'No followers',
  'Takipçiler': 'Followers',
  'Takvim': 'Calendar',
  'Tamam': 'OK',
  'Tekrar Dene': 'Try Again',
  'Tekrar dene': 'Try again',
  'Toplam ekran süresi': 'Total screen time',
  'Tüm Zamanların En İyileri': 'All-Time Best',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Export all your data (watches, ratings, comments, lists) as a TV Time-compatible ZIP, or import a ZIP from another app.',
  'Tümünü Kaldır': 'Remove All',
  'Tümünü İzledim': 'Watched All',
  'Türk Dizileri': 'Turkish Series',
  'Veri içe aktar (.zip)': 'Import data (.zip)',
  'Verilerim': 'My Data',
  'Verilerimi dışa aktar (e-posta)': 'Export my data (email)',
  'Verilerini dışa aktar': 'Export your data',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'No upcoming episodes.\nSet a show to "Watching" from its detail page and track new episodes here.',
  'Yapımları': 'Filmography',
  'Yeni Diziler': 'New Shows',
  'Yeni Liste': 'New List',
  'Yeni kullanıcı adı (isteğe bağlı)': 'New username (optional)',
  'Yorum': 'Comment',
  'Yorumunu yaz...': 'Write your comment...',
  'Zaten hesabın var mı? Giriş yap': 'Already have an account? Log in',
  'ort. {}': 'avg. {}',
  'takip': 'following',
  'takipçi': 'followers',
  '{} / {} bölüm': '{} / {} episodes',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} months',
  '{} bölüm izlendi': '{} episodes watched',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} gün': '{} days',
  '{} içerik': '{} titles',
  '{} içerik · otomatik': '{} titles · auto',
  '{} kayıt atlandı (eşleşmedi).': '{} records skipped (no match).',
  '{} saat': '{} hours',
  '{} sezon': '{} seasons',
  '{} yıl': '{} years',
  '{}. Bölüm': 'Episode {}',
  '{}. Sezon': 'Season {}',
  'Çıkış Yap': 'Log Out',
  'Ülke': 'Country',
  'Ülke ara...': 'Search country...',
  'Ülke seç': 'Select country',
  'İlk yorumu sen yaz!': 'Be the first to comment!',
  'İncelemeler': 'Reviews',
  'İncelemen (isteğe bağlı)': 'Your review (optional)',
  'İptal': 'Cancel',
  'İzlediklerim': 'Watch History',
  'İzledim': 'Watched',
  'İzledin': 'You watched',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Your watch history and lists are kept safe; you can now sign in from any device.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Your watch history, ratings, comments and lists will be sent as a ZIP to your registered email address.',
  'İzleyeceğim': 'Watchlist',
  'İzliyorum': 'Watching',
  'İçe aktarım tamamlandı': 'Import complete',
  'Şifre': 'Password',
  '• profil bilgisi': '• profile info',
  '• {} dizi durumu': '• {} show statuses',
  '• {} izleme kaydı': '• {} watch records',
  '• {} liste': '• {} lists',
  '• {} puan': '• {} ratings',
  '• {} yorum': '• {} comments',
  '{}+ yapım': '{}+ titles',
  'Yorumlar': 'Comments',
  'Yorumlar ({})': 'Comments ({})',
  'Yorumları ({})': 'Comments ({})',
  'Listelerim': 'My Lists',
  'Nereden izledin?': 'Where did you watch it?',
  'Diziye git': 'Go to the show',
  'TV / Kanal': 'TV / Channel',
  'Sinema': 'Cinema',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Other',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Your feed is empty.\nWhen people comment on the shows and movies you watch, it shows up here.',
  'Listeleri ({})': 'Their lists ({})',
  'Liste boş.': 'This list is empty.',
  'Yanıtla': 'Reply',
  '@{} kullanıcısına yanıt veriyorsun': 'Replying to @{}',
  'İzlediğim Diziler ({})': 'Shows I watched ({})',
  'İzlediğim Filmler ({})': 'Movies I watched ({})',
  'Tümünü gör': 'See all',
  'Bildirimler': 'Notifications',
  'Henüz bildirim yok': 'No notifications yet',
  '@{} yorumuna yanıt verdi': '@{} replied to your comment',
  '@{} yorumunu beğendi': '@{} liked your comment',
  '@{} seni takip etti': '@{} followed you',
  '@{} sana mesaj gönderdi': '@{} sent you a message',
  'Mesajlar': 'Messages',
  'Mesaj': 'Message',
  'Mesajını yaz...': 'Write a message...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'No chats yet.\nOpen a profile and send a message.',
  'Şifreni mi unuttun?': 'Forgot your password?',
  'Şifreyi Sıfırla': 'Reset Password',
  'E-postadaki kod': 'Code from email',
  'Yeni şifre': 'New password',
  'Sana Özel': 'For You',
  '{} özetin': 'Your {} recap',
  'Yıllık izleme istatistiklerin': 'Your yearly watch stats',
  'Rozetler': 'Badges',
  'Verdiğin puan': 'Ratings given',
  'Ortalama puanın': 'Your average rating',
  'En çok izlediğin diziler': 'Your most watched shows',
  'İlk Bölüm': 'First Episode',
  '100 Bölüm': '100 Episodes',
  '1000 Bölüm': '1000 Episodes',
  'İlk Film': 'First Movie',
  '50 Film': '50 Movies',
  'İlk Yorum': 'First Comment',
  '25 Yorum': '25 Comments',
  '10 Puan': '10 Ratings',
  'İlk Takipçi': 'First Follower',
  '10 Dizi Bitirdin': 'Finished 10 Shows',
  'İzlemeyi Bıraktım': 'I Stopped Watching',
  'İzlediği Diziler ({})': 'Shows they watched ({})',
  'İzlediği Filmler ({})': 'Movies they watched ({})',
  '500 Bölüm': '500 Episodes',
  '5000 Bölüm': '5000 Episodes',
  '10 Film': '10 Movies',
  '100 Film': '100 Movies',
  '100 Yorum': '100 Comments',
  '50 Puan': '50 Ratings',
  '100 Puan': '100 Ratings',
  '10 Takipçi': '10 Followers',
  '50 Takipçi': '50 Followers',
  '25 Dizi Bitirdin': 'Finished 25 Shows',
  '50 Dizi Bitirdin': 'Finished 50 Shows',
  '10 Beğeni': '10 Likes',
  '100 Beğeni': '100 Likes',
  'yazıyor...': 'typing...',
  'Profil düzeni': 'Profile layout',
  'Konumla ve kırp': 'Position and crop',
  'Listeye eklendi': 'Added to list',
  'Listeyi sil?': 'Delete list?',
  'Sil': 'Delete',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'This title will be marked as never watched and removed from your lists.',
  'Gelecek bölüm bugün': 'Next episode today',
  'Gelecek bölüm {} gün sonra': 'Next episode in {} days',
  'Tema': 'Theme',
  'Sistem': 'System',
  'Koyu': 'Dark',
  'Açık': 'Light',
  'İzleyenler': 'Watched by',
  'Yorumunu yaz... (@ ile etiketle)': 'Write your comment... (@ to tag)',
  '@{} bir yorumda seni etiketledi': '@{} tagged you in a comment',
  'Mesajı sil': 'Delete message',
  'Mesaj silinemedi': 'Message couldn\'t be deleted',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Link is invalid or page not found',
  'Keşfet\'e dön': 'Back to Discover',
  'Düzenle': 'Edit',
  'Mesajı düzenle': 'Edit message',
  'Yanıtlanıyor': 'Replying',
  'düzenlendi': 'edited',
  'Fotoğraf': 'Photo',
  'Video': 'Video',
  'İçerik': 'Content',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': 'last seen {} min ago',
  'son görülme {} saat önce': 'last seen {} h ago',
  'son görülme {} gün önce': 'last seen {} d ago',
  'Yorumlar yüklenemedi': 'Couldn\'t load comments',
  'Favori': 'Favorite',
  'Listeye ekle': 'Add to list',
  'İçerik paylaş': 'Share content',
  'Kapat': 'Close',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Everything you mark as watched is collected here.',
  'Henüz sohbetin yok': 'No conversations yet',
  'Bir profile girip mesaj gönderebilirsin.':
      'Open a profile and send a message.',
  'Listeyi sil': 'Delete list',
  'Puan kaydedilemedi': 'Rating couldn\'t be saved',
  'Nerede İzlenir': 'Where to Watch',
  'Abonelik': 'Subscription',
  'Kirala': 'Rent',
  'Satın al': 'Buy',
  'Hoş geldin!': 'Welcome!',
  'İzlemek istediğin dizi ve filmleri seç':
      'Pick shows and movies you want to watch',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Your picks are added to your Watchlist',
  'Şimdilik atla': 'Skip for now',
  'Devam et': 'Continue',
  '{} ekle': 'Add {}',
  'Şikayet et': 'Report',
  'Engelle': 'Block',
  'Engeli kaldır': 'Unblock',
  'Kullanıcı engellendi': 'User blocked',
  'Engel kaldırıldı': 'Block removed',
  'Şikayet sebebi': 'Report reason',
  'Spam veya yanıltıcı': 'Spam or misleading',
  'Taciz veya nefret söylemi': 'Harassment or hate speech',
  'Uygunsuz / cinsel içerik': 'Inappropriate / sexual content',
  'Şiddet veya tehlikeli içerik': 'Violence or dangerous content',
  'Telif hakkı ihlali': 'Copyright infringement',
  'Şikayetin alındı, teşekkürler': 'Your report was received, thanks',
  'Hesabımı Sil': 'Delete My Account',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Your account and all your data (watch history, ratings, comments, lists, messages) will be permanently deleted. This cannot be undone.',
  'Şifreni gir': 'Enter your password',
  'Hesabımı kalıcı sil': 'Permanently delete my account',
  'Sesli mesaj': 'Voice message',
  'Ses gönderilemedi': 'Voice couldn’t be sent',
  'Kaydediliyor…': 'Recording…',
  'Ses oynatılamadı': 'Voice couldn’t be played',
  'Oynat': 'Play',
  'Duraklat': 'Pause',
  'Liste görünümü': 'List view',
  'Takvim görünümü': 'Calendar view',
  'Önceki ay': 'Previous month',
  'Sonraki ay': 'Next month',
  'Bu gün bölüm yok': 'No episodes this day',
  'Gizlilik Politikası': 'Privacy Policy',
  'Son güncelleme: {}': 'Last updated: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'This policy explains what data is collected, how it is used, and what your rights are when you use the dizi.jpg app and the dizijpg.com website.',
  'Topladığımız Veriler': 'Data We Collect',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Account: email address, username, and password. Passwords are stored as irreversible hashes; guest accounts can be used without an email.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profile: information you choose to add, such as your avatar, cover image, bio, and country.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Usage: your watch history, ratings, comments, lists, reactions, and favorites.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Messages: your text, image, and voice messages are stored on our servers. Messages are not end-to-end encrypted; they are only reviewed for moderation purposes if reported.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Uploaded media: photos, GIFs, videos, and audio recordings you add to your profile, comments, and messages.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Technical: IP address, approximate location (country/city level), device platform, app version, and error logs. These are kept for security and debugging.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Notifications: your device token and language preference are stored for push notifications. You can turn off notifications anytime in your device settings.',
  'Verileri Nasıl Kullanırız': 'How We Use Your Data',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'We use your data only to provide the service, protect your account, send notifications, fix errors, and prevent abuse. We never sell your data or share it with anyone for advertising.',
  'Çerezler ve Yerel Depolama': 'Cookies and Local Storage',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'We only use local storage to keep you signed in and remember preferences like language and theme. There are no advertising or tracking cookies.',
  'Üçüncü Taraf Hizmetler': 'Third-Party Services',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'Show and movie information comes from TMDB, and streaming provider information from JustWatch. Push notifications are delivered via Google Firebase, and site traffic is protected by Cloudflare. These services are subject to their own privacy policies.',
  'Saklama ve Silme': 'Retention and Deletion',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Your data is kept for as long as your account is active. You can permanently delete your account with "Delete My Account" in Settings; your data is deleted immediately, and copies in backups within 14 days at the latest. Error logs are automatically deleted after 30 days.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'You can export your data as a ZIP from Settings; the archive is sent to your email address.',
  'Güvenlik': 'Security',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Data is transferred over an encrypted connection (HTTPS) and stored on servers with restricted access.',
  'Çocukların Gizliliği': 'Children\'s Privacy',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg is not intended for children under 13.',
  'Hakların': 'Your Rights',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Under KVKK and GDPR, you have the right to access, correct, delete, and transfer your data. To exercise these rights, you can write to us at: {}',
  'Değişiklikler': 'Changes',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'If this policy changes, the new version will be published on this page and the update date will be refreshed.',
  'Kayıt olarak {} kabul etmiş olursun.': 'By signing up, you agree to {}.',
  'Kullanıcılar': 'Users',
  'Fotoğrafı değiştir': 'Change photo',
  'Yeniden konumlandır': 'Reposition',
  'Bir şeyler ters gitti': 'Something went wrong',
  'Sosyal Bağlantılar': 'Social Links',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Up to 3 links are shown on your profile.',
  'Platform seç': 'Choose a platform',
  'Kullanıcı adın': 'Your username',
  'Ekle': 'Add',
  'Kaldır': 'Remove',
  'Kopyalandı: {}': 'Copied: {}',
  'Geçersiz kullanıcı adı': 'Invalid username',
  'Bağlantı ekle': 'Add link',
  'Spoiler olabilir — dokun ve gör': 'May contain spoilers — tap to view',
  'Beğeni': 'Likes',
  'Görüntülenme': 'Views',
  'Tam ekran': 'Fullscreen',
  'Sonuç bulunamadı': 'No results found',
  'Dizi ve Filmler': 'Shows & Movies',
  'Kişiler': 'People',
  'Ana Sayfa': 'Home',
  'Paylaş': 'Share',
  'Yanıtlar': 'Replies',
  'Yaklaşan Bölümler': 'Upcoming Episodes',
  'Yetişme Listesi': 'Catch-Up List',
  'Şunu mu demek istedin': 'Did you mean',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — tap to reveal',
  'uyum': 'match',
  'Uyum': 'Match',
  '{} ortak dizi': '{} shows in common',
  '{} ortak film': '{} movies in common',
  'Bildirim Tercihleri': 'Notification Preferences',
  'Beğeniler': 'Likes',
  'Yeni takipçiler': 'New followers',
  'Etiketlenmeler': 'Mentions',
  'Yeniden izledim': 'Watched again',
  '{}. kez izlendi': 'Watched {} times',
  'Gönderi bulunamadı': 'Post not found',
  'Gözat': 'Browse',
  'Diziler': 'Shows',
  'Filmler': 'Movies',
  'Tümü': 'All',
  'Farklı bir tür seç.': 'Try a different genre.',
  'Gizlilik': 'Privacy',
  'İzlediklerimi gizle': 'Hide what I watch',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Shows and movies you watched won\'t be shown on your profile',
  'Yorumlarımı gizle': 'Hide my comments',
  'Profilinde yorumların görünmez':
      'Your comments won\'t be shown on your profile',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'You can hide a single show or movie with the "Hide on my profile" chip on its page.',
  'Geri Bildirim': 'Feedback',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Write your thoughts and suggestions about the app...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Thanks! Your feedback has been received.',
  'Profilimde gizle': 'Hide on my profile',
  'Yorumları': 'Comments',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'This user prefers to keep their comments private.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Data: JustWatch',
  'Web Sitesi': 'Website',
  'Diğer uygulamalar': 'More apps',
  'Bağlantıyı kopyala': 'Copy link',
  'Henüz kimseyi takip etmiyorsun.': 'You\'re not following anyone yet.',
  'Çevir': 'Translate',
  'Orijinali göster': 'Show original',
};
