/// Otomatik üretilen çeviri haritası (fil).
const Map<String, String> cevirilerFil = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Nakita mo na ang lahat, ipinakita namin sa iyo mula sa simula',
  'Aktarılacak tanınan veri bulunamadı.':
      'Walang nakilalang data na maaaring i-import.',
  'Arama': 'Maghanap',
  'Aramaya başla': 'Simulan ang paghahanap',
  'Son aramalar': 'Mga kamakailang paghahanap',
  'Ayarlar': 'Mga Setting',
  'Bağla': 'I-link',
  'Bio': 'Bio',
  'Bitirdim': 'Tapos Na',
  'Bunları da Beğenebilirsin': 'Baka Magustuhan Mo Rin Ito',
  'Bölüm': 'Episode',
  'Bıraktım': 'Hininto Ko',
  'Dil': 'Wika',
  'Dil ara...': 'Maghanap ng wika...',
  'Dizi': 'Serye',
  'Dizi ve filmlerini takip et': 'Subaybayan ang mga serye at pelikula mo',
  'Dizi yorumu': 'Komento sa serye',
  'Dizi, film veya kişi ara...': 'Maghanap ng serye, pelikula, o tao...',
  'Dosya en fazla 30MB olabilir': 'Hanggang 30MB lang ang file',
  'Dosya en fazla {}MB olabilir': 'Hanggang {}MB lang ang file',
  'E-posta': 'Email',
  'E-posta veya kullanıcı adı': 'Email o username',
  'En az 2 harf yaz': 'Mag-type ng kahit 2 letra',
  'Film': 'Pelikula',
  'Film yorumu': 'Komento sa pelikula',
  'Fotoğraf / video ekle': 'Magdagdag ng larawan / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Larawan o GIF — profile at cover photo',
  'Giriş Yap': 'Mag-log In',
  'Gönder': 'Ipadala',
  'Gönderildi': 'Naipadala',
  'Haftanın Dizileri': 'Mga Serye Ngayong Linggo',
  'Haftanın Filmleri': 'Mga Pelikula Ngayong Linggo',
  'Henüz izleme kaydın yok': 'Wala ka pang watch history',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Wala ka pang listahan — gumawa mula sa Profile tab.',
  'Henüz yorum yok.': 'Wala pang komento.',
  'Hesabın bağlandı!': 'Naka-link na ang account mo!',
  'Hesabın yok mu? Kayıt ol': 'Walang account? Mag-sign up',
  'Hesabını Bağla': 'I-link ang Account Mo',
  'Hesap Oluştur': 'Gumawa ng Account',
  'Kapak resmi ekle': 'Magdagdag ng cover photo',
  'Kaydet': 'I-save',
  'Kendinden bahset...': 'Magkuwento tungkol sa sarili mo...',
  'Keşfet': 'Tuklasin',
  'Kimseyi takip etmiyor': 'Walang sinusundan',
  'Kişi ara': 'Maghanap ng tao',
  'Kişi yorumu': 'Komento sa tao',
  'Konuk Oyuncular': 'Mga Guest Star',
  'Kullanıcı adı (küçük harf)': 'Username (maliit na letra)',
  'Kullanıcı adı ara...': 'Maghanap ng username...',
  'Liste adı': 'Pangalan ng listahan',
  'Listeye Ekle': 'Idagdag sa Listahan',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Naka-guest account ka — i-link gamit ang email mo, huwag mawala ang data mo!',
  'Misafir olarak devam et': 'Magpatuloy bilang guest',
  'Oluştur': 'Gumawa',
  'Oyuncular': 'Mga Aktor',
  'Profil': 'Profile',
  'Profil kaydedildi': 'Na-save ang profile',
  'Puanla': 'Mag-rate',
  'Puanı Sil': 'Burahin ang Rating',
  'Puanın': 'Rating mo',
  'Sezonlar': 'Mga Season',
  'Sunucu hatası ({})': 'Server error ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Komento sa S{}E{}',
  'Takibi Bırak': 'I-unfollow',
  'Takip': 'Sinusundan',
  'Takip Edilenler': 'Mga Sinusundan',
  'Takip Et': 'I-follow',
  'Takipçi': 'Follower',
  'Takipçi yok': 'Walang follower',
  'Takipçiler': 'Mga Follower',
  'Takvim': 'Kalendaryo',
  'Tamam': 'OK',
  'Tekrar Dene': 'Subukan Ulit',
  'Tekrar dene': 'Subukan ulit',
  'Toplam İzleme Süresi': 'Kabuuang screen time',
  'Tüm Zamanların En İyileri': 'Pinakamahusay sa Lahat ng Panahon',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'I-export ang lahat ng data mo (panonood, rating, komento, listahan) bilang TV Time-compatible na ZIP, o mag-import ng ZIP mula sa ibang app.',
  'Tümünü Kaldır': 'Alisin Lahat',
  'Tümünü İzledim': 'Napanood Ko Lahat',
  'Türk Dizileri': 'Mga Seryeng Turkish',
  'Veri içe aktar (.zip)': 'Mag-import ng data (.zip)',
  'Verilerim': 'Data Ko',
  'Verilerimi dışa aktar (e-posta)': 'I-export ang data ko (email)',
  'Verilerini dışa aktar': 'I-export ang data mo',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Walang paparating na episode.\nGawing "Pinapanood Ko" ang serye mula sa detail page nito at subaybayan dito ang mga bagong episode.',
  'Yapımları': 'Filmography',
  'Yeni Diziler': 'Mga Bagong Serye',
  'Yeni Liste': 'Bagong Listahan',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Bagong username (opsyonal)',
  'Yorum': 'Komento',
  'Yorumunu yaz...': 'Isulat ang komento mo...',
  'Zaten hesabın var mı? Giriş yap': 'May account ka na? Mag-log in',
  'ort. {}': 'avg. {}',
  'takip': 'sinusundan',
  'takipçi': 'follower',
  '{} / {} bölüm': '{} / {} episode',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} buwan',
  '{} ay~tekil': '{} buwan',
  '{} bölüm izlendi': '{} episode ang napanood',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} dk~tekil': '{} min',
  '{} gün': '{} araw',
  '{} gün~tekil': '{} araw',
  '{} içerik': '{} nilalaman',
  '{} içerik · otomatik': '{} nilalaman · awtomatiko',
  '{} kayıt atlandı (eşleşmedi).': '{} record ang nilaktawan (walang tugma).',
  '{} saat': '{} oras',
  '{} saat~tekil': '{} oras',
  '{} sezon': '{} season',
  '{} yıl': '{} taon',
  '{} yıl~tekil': '{} taon',
  '{}. Bölüm': 'Episode {}',
  '{}. Sezon': 'Season {}',
  'Çıkış Yap': 'Mag-log Out',
  'Ülke': 'Bansa',
  'Ülke ara...': 'Maghanap ng bansa...',
  'Ülke seç': 'Pumili ng bansa',
  'İlk yorumu sen yaz!': 'Ikaw ang unang magkomento!',
  'İncelemeler': 'Mga Review',
  'İncelemen (isteğe bağlı)': 'Review mo (opsyonal)',
  'İptal': 'Kanselahin',
  'İzlediklerim': 'Mga Napanood Ko',
  'İzledim': 'Napanood Ko',
  'İzledin': 'Napanood mo',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Mananatili ang watch history at mga listahan mo; makakapag-log in ka na mula sa kahit anong device.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Ipapadala ang watch history, rating, komento, at mga listahan mo bilang ZIP sa nakarehistrong email mo.',
  'İzleyeceğim': 'Panonoorin Ko',
  'İzliyorum': 'Pinapanood Ko',
  'İçe aktarım tamamlandı': 'Tapos na ang pag-import',
  'Şifre': 'Password',
  '• profil bilgisi': '• impormasyon ng profile',
  '• {} dizi durumu': '• {} status ng serye',
  '• {} izleme kaydı': '• {} watch record',
  '• {} liste': '• {} listahan',
  '• {} puan': '• {} rating',
  '• {} yorum': '• {} komento',
  '{}+ yapım': '{}+ produksyon',
  'Yorumlar': 'Mga Komento',
  'Yorumlar ({})': 'Mga Komento ({})',
  'Yorumları ({})': 'Mga Komento Nito ({})',
  'Listelerim': 'Mga Listahan Ko',
  'Nereden izledin?': 'Saan mo pinanood?',
  'Diziye git': 'Pumunta sa show',
  'TV / Kanal': 'TV / Channel',
  'Sinema': 'Sinehan',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Iba pa',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Walang laman ang feed mo.\nKapag may nag-comment sa mga show at pelikulang pinapanood mo, lalabas ito rito.',
  'Listeleri ({})': 'Mga listahan niya ({})',
  'Liste boş.': 'Walang laman ang listahang ito.',
  'Yanıtla': 'Sumagot',
  '@{} kullanıcısına yanıt veriyorsun': 'Sumasagot kay @{}',
  'İzlediğim Diziler ({})': 'Mga show na napanood ko ({})',
  'İzlediğim Filmler ({})': 'Mga pelikulang napanood ko ({})',
  'Tümünü gör': 'Tingnan lahat',
  'Bildirimler': 'Mga Notipikasyon',
  'Henüz bildirim yok': 'Wala pang notipikasyon',
  '@{} yorumuna yanıt verdi': 'Sumagot si @{} sa komento mo',
  '@{} yorumunu beğendi': 'Nagustuhan ni @{} ang komento mo',
  '@{} seni takip etti': 'Sinundan ka ni @{}',
  '@{} sana mesaj gönderdi': 'Pinadalhan ka ni @{} ng mensahe',
  'Mesajlar': 'Mga Mensahe',
  'Mesaj': 'Mensahe',
  'Mesaja eklenecek': 'Idadagdag sa mensahe',
  'Mesajını yaz...': 'Sumulat ng mensahe...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Wala pang chat.\nBuksan ang isang profile at magpadala ng mensahe.',
  'Şifreni mi unuttun?': 'Nakalimutan ang password?',
  'Şifreyi Sıfırla': 'I-reset ang Password',
  'E-postadaki kod': 'Code mula sa email',
  'Yeni şifre': 'Bagong password',
  'Sana Özel': 'Para sa iyo',
  '{} özetin': 'Ang {} recap mo',
  'Yıllık izleme istatistiklerin': 'Taunang stats ng panonood',
  'Rozetler': 'Mga Badge',
  'Verdiğin puan': 'Mga ibinigay na rating',
  'Ortalama puanın': 'Average rating mo',
  'En çok izlediğin diziler': 'Mga seryeng pinakamadalas mong pinanood',
  'İlk Bölüm': 'Unang Episode',
  '100 Bölüm': '100 Episodes',
  '1000 Bölüm': '1000 Episodes',
  'İlk Film': 'Unang Pelikula',
  '50 Film': '50 Pelikula',
  'İlk Yorum': 'Unang Komento',
  '25 Yorum': '25 Komento',
  '10 Puan': '10 Rating',
  'İlk Takipçi': 'Unang Follower',
  '10 Dizi Bitirdin': 'Natapos ang 10 Serye',
  'İzlemeyi Bıraktım': 'Huminto na ako sa panonood',
  'İzlediği Diziler ({})': 'Mga show na pinanood niya ({})',
  'İzlediği Filmler ({})': 'Mga pelikulang pinanood niya ({})',
  '500 Bölüm': '500 Episodes',
  '5000 Bölüm': '5000 Episodes',
  '10 Film': '10 Pelikula',
  '100 Film': '100 Pelikula',
  '100 Yorum': '100 Komento',
  '50 Puan': '50 Rating',
  '100 Puan': '100 Rating',
  '10 Takipçi': '10 Followers',
  '50 Takipçi': '50 Followers',
  '25 Dizi Bitirdin': 'Natapos ang 25 Serye',
  '50 Dizi Bitirdin': 'Natapos ang 50 Serye',
  '10 Beğeni': '10 Likes',
  '100 Beğeni': '100 Likes',
  'yazıyor...': 'nagta-type...',
  'ses kaydediyor...': 'nagre-record ng audio...',
  'Profil düzeni': 'Layout ng profile',
  'Konumla ve kırp': 'Iposisyon at i-crop',
  'Listeye eklendi': 'Naidagdag sa listahan',
  'Listeyi sil?': 'Burahin ang listahan?',
  'Sil': 'Burahin',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Mamarkahan itong hindi pa napapanood at aalisin sa mga listahan mo.',
  'Gelecek bölüm bugün': 'Susunod na episode ngayon',
  'Gelecek bölüm {} gün sonra': 'Susunod na episode sa {} araw',
  'Tema': 'Tema',
  'Sistem': 'Sistema',
  'Koyu': 'Madilim',
  'Açık': 'Maliwanag',
  'İzleyenler': 'Mga nanood',
  'Yorumunu yaz... (@ ile etiketle)':
      'Isulat ang iyong komento... (@ para i-tag)',
  '@{} bir yorumda seni etiketledi': 'Ni-tag ka ni @{} sa isang komento',
  'Mesajı sil': 'Burahin ang mensahe',
  'Mesaj silinemedi': 'Hindi mabura ang mensahe',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Di-wasto ang link o hindi natagpuan ang pahina',
  "Keşfet'e dön": 'Bumalik sa Tuklasin',
  'Düzenle': 'I-edit',
  'Mesajı düzenle': 'I-edit ang mensahe',
  'Yanıtlanıyor': 'Sumasagot',
  'düzenlendi': 'na-edit',
  'Fotoğraf': 'Larawan',
  'Video': 'Video',
  'İçerik': 'Nilalaman',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': 'huling nakita {} min ang nakalipas',
  'son görülme {} saat önce': 'huling nakita {} oras ang nakalipas',
  'son görülme {} gün önce': 'huling nakita {} araw ang nakalipas',
  'Yorumlar yüklenemedi': 'Hindi ma-load ang mga komento',
  'Favori': 'Paborito',
  'Listeye ekle': 'Idagdag sa listahan',
  'İçerik paylaş': 'Ibahagi ang nilalaman',
  'Kapat': 'Isara',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Lahat ng minarkahan mong napanood ay naiipon dito.',
  'Henüz sohbetin yok': 'Wala pang usapan',
  'Bir profile girip mesaj gönderebilirsin.':
      'Magbukas ng profile at magpadala ng mensahe.',
  'Listeyi sil': 'Burahin ang listahan',
  'Puan kaydedilemedi': 'Hindi ma-save ang rating',
  'Nerede İzlenir': 'Saan Manonood',
  'Abonelik': 'Subscription',
  'Kirala': 'Umupa',
  'Satın al': 'Bumili',
  'Devam et': 'Magpatuloy',
  'Şikayet et': 'Iulat',
  'Engelle': 'I-block',
  'Engeli kaldır': 'I-unblock',
  'Kullanıcı engellendi': 'Na-block ang user',
  'Engel kaldırıldı': 'Inalis ang block',
  'Şikayet sebebi': 'Dahilan ng ulat',
  'Spam veya yanıltıcı': 'Spam o mapanlinlang',
  'Taciz veya nefret söylemi': 'Panliligalig o hate speech',
  'Uygunsuz / cinsel içerik': 'Hindi angkop / sekswal na content',
  'Şiddet veya tehlikeli içerik': 'Karahasan o mapanganib na content',
  'Telif hakkı ihlali': 'Paglabag sa copyright',
  'Şikayetin alındı, teşekkürler': 'Natanggap na ang ulat mo, salamat',
  'Hesabımı Sil': 'Burahin ang Account Ko',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Permanenteng mabubura ang account mo at lahat ng data (history, ratings, komento, lists, mensahe). Hindi na ito maibabalik.',
  'Şifreni gir': 'Ilagay ang password mo',
  'Hesabımı kalıcı sil': 'Permanenteng burahin ang account ko',
  'Sesli mesaj': 'Voice message',
  'Ses gönderilemedi': 'Hindi naipadala ang voice message',
  'Kaydediliyor…': 'Nagre-record…',
  'Ses oynatılamadı': 'Hindi ma-play ang audio',
  'Oynat': 'I-play',
  'Fragmanı oynat': 'I-play ang trailer',
  'Altyazıyı aç': 'I-on ang subtitle',
  'Altyazıyı kapat': 'I-off ang subtitle',
  '10 saniye ileri': 'Skip nang 10 segundo pasulong',
  '10 saniye geri': 'Skip nang 10 segundo paatras',
  'Duraklat': 'I-pause',
  'Liste görünümü': 'List view',
  'Takvim görünümü': 'Calendar view',
  'Önceki ay': 'Nakaraang buwan',
  'Sonraki ay': 'Susunod na buwan',
  'Bu gün bölüm yok': 'Walang episode sa araw na ito',
  'Gizlilik Politikası': 'Patakaran sa Privacy',
  'Son güncelleme: {}': 'Huling na-update: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Ipinapaliwanag ng patakarang ito kung anong data ang kinokolekta, paano ito ginagamit, at ano ang mga karapatan mo kapag ginagamit mo ang dizi.jpg app at ang site na dizijpg.com.',
  'Topladığımız Veriler': 'Data na Kinokolekta Namin',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Account: email address, username, at password. Ang mga password ay iniimbak bilang hash na hindi na maibabalik; magagamit ang guest account kahit walang email.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profile: impormasyong pinipili mong idagdag, tulad ng avatar, cover image, bio, at bansa.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Paggamit: ang history ng panonood mo, mga rating, komento, listahan, reaksyon, at paborito.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Mga mensahe: ang text, larawan, at voice message mo ay iniimbak sa aming mga server. Hindi end-to-end encrypted ang mga mensahe; sinusuri lang ang mga ito para sa moderation kapag ni-report.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Na-upload na media: mga larawan, GIF, video, at voice recording na idinaragdag mo sa profile, komento, at mensahe.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Teknikal: IP address, tinatayang lokasyon (antas ng bansa/lungsod), platform ng device, bersyon ng app, at mga error log. Iniimbak ang mga ito para sa seguridad at pag-aayos ng problema.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Istatistika ng paggamit: ang uri ng device, operating system, at browser na ginamit sa pagpasok ay idinaragdag sa pang-araw-araw na kabuuang counter bilang malalawak na kategorya; hindi iniimbak ang mismong pagkakakilanlan ng browser at hindi maiuugnay ang mga bilang na ito sa sinumang tao.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Mga notification: para sa push notification, iniimbak namin ang token ng device mo at piniling wika. Puwede mong i-off ang mga notification anumang oras sa settings ng device.',
  'Verileri Nasıl Kullanırız': 'Paano Namin Ginagamit ang Data',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Ginagamit lang namin ang data mo para maibigay ang serbisyo, protektahan ang account, magpadala ng notification, ayusin ang mga error, at pigilan ang pang-aabuso. Hindi namin ibinebenta ang data mo at hindi ibinabahagi kaninuman para sa advertising.',
  'Çerezler ve Yerel Depolama': 'Cookies at Local Storage',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Ginagamit lang ang local storage para panatilihin kang naka-login at tandaan ang mga kagustuhan tulad ng wika at tema. Walang advertising o tracking cookies.',
  'Üçüncü Taraf Hizmetler': 'Mga Serbisyo ng Third Party',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Ang data ng mga serye at pelikula ay galing sa TMDB, ang impormasyon ng streaming platform ay galing sa JustWatch. Ang push notification ay ipinapadala sa pamamagitan ng Google Firebase, at ang trapiko ng site ay pinoprotektahan ng Cloudflare. Saklaw ang mga serbisyong ito ng kani-kanilang patakaran sa privacy.',
  'Saklama ve Silme': 'Pag-iimbak at Pagbura',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Nakaimbak ang data mo hangga\'t umiiral ang account mo. Sa "Burahin ang Account Ko" sa settings, permanente mong mabubura ang account; agad na mabubura ang data, at ang mga kopya sa backup ay sa loob ng hindi lalampas sa 14 na araw. Awtomatikong nabubura ang mga error log pagkalipas ng 30 araw.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'Puwede mong i-export ang data mo bilang ZIP mula sa settings; ipapadala ang archive sa email address mo.',
  'Güvenlik': 'Seguridad',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Dumadaan ang data sa mga naka-encrypt na koneksyon (HTTPS) at nakaimbak sa mga server na limitado ang access.',
  'Çocukların Gizliliği': 'Privacy ng mga Bata',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'Ang dizi.jpg ay hindi para sa mga batang wala pang 13 taong gulang.',
  'Hakların': 'Mga Karapatan Mo',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Sa ilalim ng KVKK at GDPR, may karapatan kang i-access, itama, burahin, at ilipat ang data mo. Para dito, sumulat sa amin: {}',
  'Değişiklikler': 'Mga Pagbabago',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Kapag nagbago ang patakarang ito, ilalathala ang bagong bersyon sa pahinang ito at ia-update ang petsa.',
  'Kayıt olarak {} kabul etmiş olursun.':
      'Sa pagrerehistro, tinatanggap mo ang {}.',
  'Kullanıcılar': 'Mga user',
  'Fotoğrafı değiştir': 'Palitan ang larawan',
  'Yeniden konumlandır': 'Ayusin muli',
  'Bir şeyler ters gitti': 'May nangyaring mali',
  'Sosyal Bağlantılar': 'Mga Social Link',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Hanggang 3 link ang ipinapakita sa profile mo.',
  'Platform seç': 'Pumili ng platform',
  'Kullanıcı adın': 'Ang username mo',
  'Ekle': 'Idagdag',
  'Kaldır': 'Alisin',
  'Kopyalandı: {}': 'Nakopya: {}',
  'Geçersiz kullanıcı adı': 'Hindi wastong username',
  'Bağlantı ekle': 'Magdagdag ng link',
  'Spoiler olabilir — dokun ve gör': 'Maaaring may spoiler — i-tap para makita',
  'Beğeni': 'Mga like',
  'beğeni': 'mga like',
  'Beğen': 'I-like',
  'Görüntülenme': 'Mga view',
  'görüntülenme': 'mga view',
  'Tam ekran': 'Fullscreen',
  'Arama başarısız': 'Nabigo ang paghahanap',
  'Sonuç bulunamadı': 'Walang resulta',
  'Dizi ve Filmler': 'Mga serye at pelikula',
  'Kişiler': 'Mga tao',
  'Ana Sayfa': 'Home',
  'Paylaş': 'Ibahagi',
  'Yanıtlar': 'Mga tugon',
  'Yaklaşan Bölümler': 'Paparating na episode',
  'Yetişme Listesi': 'Listahan ng habulin',
  'Şunu mu demek istedin': 'Ibig mo bang sabihin',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — i-tap para makita',
  'uyum': 'tugma',
  'Uyum': 'Tugma',
  '{} ortak dizi': '{} serye na magkapareho',
  '{} ortak film': '{} pelikula na magkapareho',
  'Bildirim Tercihleri': 'Mga kagustuhan sa abiso',
  'Beğeniler': 'Mga like',
  'Yeni takipçiler': 'Mga bagong follower',
  'Etiketlenmeler': 'Mga banggit',
  'Yeniden izledim': 'Napanood muli',
  '{}. kez izlendi': 'Napanood ng {} beses',
  'Gönderi bulunamadı': 'Hindi natagpuan ang post',
  'Gözat': 'Mag-browse',
  'Diziler': 'Mga serye',
  'Filmler': 'Mga pelikula',
  'Tümü': 'Lahat',
  'Farklı bir tür seç.': 'Subukan ang ibang genre.',
  'Gizlilik': 'Privacy',
  'İzlediklerimi gizle': 'Itago ang mga napanood ko',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Hindi makikita sa profile mo ang mga series at pelikulang napanood mo',
  'Yorumlarımı gizle': 'Itago ang mga komento ko',
  'Profilinde yorumların görünmez':
      'Hindi makikita sa profile mo ang mga komento mo',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Puwede mong itago ang isang partikular na series o pelikula gamit ang "Itago sa profile ko" na chip sa page nito.',
  'Geri Bildirim': 'Feedback',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Isulat ang opinyon at mungkahi mo tungkol sa app...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Salamat! Natanggap na ang feedback mo.',
  'Profilimde gizle': 'Itago sa profile ko',
  'Yorumları': 'Mga Komento Nito',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Wala pang napapanood ang user na ito.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Mas gusto ng user na ito na itago ang kanyang mga komento.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Data: JustWatch',
  'Web Sitesi': 'Website',
  'Diğer uygulamalar': 'Iba pang app',
  'Bağlantıyı kopyala': 'Kopyahin ang link',
  'Henüz kimseyi takip etmiyorsun.': 'Wala ka pang sinusundan.',
  'Çevir': 'Isalin',
  'Çeviri şu an yapılamadı': 'Hindi available ang pagsasalin ngayon',
  'Bağlantı açılamadı': 'Hindi mabuksan ang link',
  'Orijinali göster': 'Ipakita ang orihinal',
  'Çeviriyi göster': 'Ipakita ang pagsasalin',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Walang episode na may anunsyadong petsa ng pagpapalabas ngayong buwan. Karaniwang inaanunsyo ang mga petsa ilang linggo bago, at lalabas dito.',
  'devamı': 'higit pa',
  'Google ile devam et': 'Magpatuloy gamit ang Google',
  'Google girişi başarısız': 'Nabigo ang pag-sign in sa Google',
  'Veri tasarrufu': 'Pagtitipid ng data',
  'Wi-Fi ağında veri tasarrufu': 'Pagtitipid ng data sa Wi-Fi',
  'Mobil veride veri tasarrufu': 'Pagtitipid ng data sa mobile data',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Kapag naka-on, hindi muna dina-download ang mga larawan; ang tinitingnan mo lang ang naglo-load.',
  'Çocuk güvenliği': 'Kaligtasan ng bata',
  'Türk Filmleri': 'Mga pelikulang Turkish',
  'En Yüksek Puanlı Filmler': 'Pinakamataas ang rating na pelikula',
  'En Yüksek Puanlı Diziler': 'Pinakamataas ang rating na serye',
  'En Çok İzlenen Filmler': 'Pinakamaraming napanood na pelikula',
  'Popüler Diziler': 'Sikat na serye',
  'En Çok Kazanan Filmler': 'Pinakamalaking kita na pelikula',
  'Kült Filmler': 'Mga cult na pelikula',
  'Yeni Filmler': 'Mga bagong pelikula',
  'Yorum yap': 'Magkomento',
  'Henüz yorum yok': 'Wala pang komento',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Ang mga komento mo sa serye at pelikula ay natitipon dito.',
  'GIF ekle': 'Magdagdag ng GIF',
  'İlk yorumu sen yaz': 'Ikaw ang mauna magkomento',
  'Video altyazıları': 'Mga subtitle ng video',
  'Videolarda altyazı göster': 'Ipakita ang mga subtitle sa mga video',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Ang pangungusap na binibigkas sa video ay nakasulat sa screen. Ang teksto ay pagsasalin: English sa Turkish speech, Turkish sa ibang mga wika.',
  'Güncelleme gerekli': 'Kailangan ng update',
  'Yeni sürüm var': 'May bagong bersyon',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'I-install ang bagong bersyon ng dizi.jpg para magpatuloy.',
  'Güncelle': 'I-update',
  'Daha sonra': 'Mamaya',
  'Takvim güncelleniyor': 'Ina-update ang kalendaryo',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Hindi na-update ang kalendaryo, ipinapakita ang lumang listahan',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'May mga seryeng hindi na-load, maaaring kulang ang listahan',
  'Yenile': 'I-refresh',
  'Devam etmek için giriş yap': 'Mag-log in para magpatuloy',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Sapat na ang libreng account para mag-rate, magkomento at buuin ang iyong library.',
  'Şimdi değil': 'Hindi muna',
  'Yorum yazmak için giriş yap': 'Mag-log in para magsulat ng komento',
  'Kişilere göndermek için giriş yap': 'Mag-log in para ipadala sa mga tao',
  'Beğenenler': 'Mga naka-like',
  'Henüz beğeni yok': 'Wala pang like',
  'Bu gönderiyi ilk beğenen sen ol': 'Maging unang mag-like ng post na ito',
  'Bu gönderiye yanıt': 'Tugon sa post na ito',
  'Spoiler içeren gönderi': 'Post na may spoiler',
  'Görsel gönderi': 'Post na may larawan',
  'Bu yorumu profilimde gizle': 'Itago ang komentong ito sa profile ko',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Mananatili ang komento sa page ng serye at pelikula',
  'Bu yorumu sil': 'Burahin ang komentong ito',
  'Yorum profilinde gizlendi': 'Naitago ang komento sa profile mo',
  'Geri al': 'I-undo',
  'Yorum silinsin mi?': 'Buburahin ba ang komento?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Permanenteng mabubura ang komentong ito sa lahat ng lugar. Hindi na ito maibabalik.',
  'Yorum silindi': 'Nabura ang komento',
  'Yorum profilinde tekrar görünüyor':
      'Nakikita na ulit ang komento sa profile mo',
  'Gizlenen yorumun yok': 'Walang nakatagong komento',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Dito napupunta ang mga komentong itinatago mo sa pamamagitan ng paghawak nang matagal sa post sa Comments tab ng profile mo.',
  'Gizlenen yorumlar': 'Mga nakatagong komento',
  'Gönderiye git': 'Pumunta sa post',
  'Tekrar göster': 'Ipakita ulit',
  'Yanıtlarımı gizle': 'Itago ang mga reply ko',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Ang mga reply na isinulat mo sa post ng iba ay ikaw lang ang makakakita',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Ipakita ulit ang mga komentong itinago mo sa profile',
  'Sıralama': 'Pagkakasunod',
  'Önerilen': 'Inirerekomenda',
  'Kronolojik': 'Ayon sa oras',
  'Gelen mesaj istekleri': 'Mga natanggap na hiling na mensahe',
  'Mesaj isteğin yok': 'Walang hiling na mensahe',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Lumalabas dito ang mga mensahe mula sa mga taong hindi mo sinusundan.',
  'Çevrimiçi durumumu gizle': 'Itago ang aking online status',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Hindi makikita ng iba ang iyong online status at huling nakita sa mga mensahe',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Isa sa aming mga unang user. Nakatulong ang kanyang feedback para maging ganito ang app ngayon.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Isa ka sa aming mga unang user. Nakatulong ang feedback mo para maging ganito ang app ngayon.',
  'İleri': 'Susunod',
  'Önceki': 'Nakaraan',
  'Sonraki': 'Susunod',
  'Seçilen dosya okunamadı': 'Hindi mabasa ang napiling file',
  'Video açılamadı': 'Hindi mabuksan ang video',
  'En fazla {} medya seçebilirsin':
      'Hanggang {} media lang ang puwedeng piliin',
  'Hiçbir medya yüklenemedi': 'Walang media na na-upload',
  'Seçimi kaldır': 'Alisin sa napili',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'Sa isang komento, hanggang {} MB lahat ang puwedeng i-upload',
  '{} dosya okunamadı': 'Hindi mabasa ang {} file',
  '{} medya eklendi, {} yüklenemedi': '{} media ang naidagdag, {} ang nabigo',
  'Kırp': 'I-crop',
  'Çiz': 'Gumuhit',
  'Metin': 'Teksto',
  'Emoji': 'Emoji',
  'Yinele': 'Ulitin',
  'Daha fazla': 'Higit pa',
  'Hazırlanıyor…': 'Inihahanda…',
  'Düzenlemeden çık?': 'Lumabas sa pag-edit?',
  'Yaptığın değişiklikler kaybolacak.': 'Mawawala ang mga pagbabago mo.',
  'Çık': 'Lumabas',
  'Serbest çizim': 'Malayang guhit',
  'Ok': 'Arrow',
  'Dikdörtgen': 'Parihaba',
  'Daire': 'Bilog',
  'Bulanıklaştır': 'I-blur',
  'Pikselleştir': 'I-pixelate',
  'Silgi': 'Pambura',
  'Çizgi kalınlığı': 'Kapal ng linya',
  'Saydamlık': 'Opacity',
  'Dolgu': 'Fill',
  'Renk': 'Kulay',
  'Döndür': 'Iikot',
  'Yansıt': 'I-flip',
  'Oran': 'Ratio',
  'Sıfırla': 'I-reset',
  'Serbest': 'Malaya',
  'Metin yaz...': 'Mag-type ng teksto...',
  'Hizala': 'Ihanay',
  'Arka plan': 'Background',
  'Emoji ara...': 'Maghanap ng emoji...',
  'Son kullanılanlar': 'Kamakailan',
  'İfadeler ve insanlar': 'Smileys at tao',
  'Hayvanlar ve doğa': 'Hayop at kalikasan',
  'Yiyecek ve içecek': 'Pagkain at inumin',
  'Etkinlikler': 'Mga aktibidad',
  'Seyahat ve yerler': 'Paglalakbay at lugar',
  'Nesneler': 'Mga bagay',
  'Semboller': 'Mga simbolo',
  'Bayraklar': 'Mga watawat',
  'Görseli düzenle': 'I-edit ang larawan',
  'Düzenlendi': 'Na-edit',
  'Düzenlenemedi': 'Hindi na-edit',
  'Düzenlenen görsel çok büyük': 'Masyadong malaki ang na-edit na larawan',
  'Videoyu düzenle': 'I-edit ang video',
  'Sesi kapat': 'I-mute',
  'Sesi aç': 'I-unmute',
  'İptal ediliyor…': 'Kinakansela…',
  'Bu biraz sürebilir': 'Maaaring tumagal ito',
  'Video çok büyük': 'Masyadong malaki ang video',
  'Video hazırlanamadı': 'Hindi naihanda ang video',
  'Başlangıç': 'Simula',
  'Bitiş': 'Katapusan',
  'En çok {} saniye seçebilirsin': 'Hanggang {} segundo lang ang puwede',
  'Dosya en fazla {} MB olabilir': 'Hanggang {} MB lang ang file',
  'Medya ekle': 'Magdagdag ng media',
  'Seçili medya kalmadı': 'Walang piniling media',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Pumili ng larawan o video na idadagdag sa iyong komento.',
  'Medya seç': 'Pumili ng media',
  'Daha fazla ekle': 'Magdagdag pa',
  'Medya seçilemedi': 'Hindi napili ang media',
  'Favori oyuncular': 'Paboritong artista',
  'Henüz favori oyuncun yok': 'Wala pang paboritong artista',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Buksan ang pahina ng artista at pindutin ang puso sa kanang itaas.',
  '{} yapımdan {} tanesini izledin': 'Napanood mo ang {} sa {}',
  'izledin': 'napanood',
  'İzlemedin': 'Hindi napanood',
  'Yapım bulunamadı': 'Walang nahanap',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Walang serye o pelikula ang taong ito.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Nakaugnay sa account mo ang panonood mo; sa iyo lang ang listahang ito.',
  'Hesabın kalıcı olarak askıya alındı':
      'Permanenteng sinuspinde ang account mo',
  'Hesabın geçici olarak askıya alındı':
      'Pansamantalang sinuspinde ang account mo',
  'Hesabın askıya alındı': 'Suspendido ang account mo',
  'Sebep': 'Dahilan',
  'Kalan süre': 'Natitirang oras',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Kusang bubukas ulit ang account mo pagkatapos ng panahong ito',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'Sa panahong ito ay puwede ka pa ring magbasa, pero hindi ka makakapag-post, makakapag-komento o makakapagpadala ng mensahe.',
  'Anladım': 'Naintindihan ko',
  'Ayrıntı': 'Detalye',
  '{} dakika': '{} minuto',
  'birkaç saniye': 'ilang segundo',
  'Karara itiraz et': 'Iapela ang desisyong ito',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Ipaliwanag kung bakit dapat alisin ang parusang ito',
  'İtirazını gönder': 'Ipadala ang apela mo',
  'İtirazın incelemede': 'Sinusuri ang apela mo',
  'İtirazın reddedildi': 'Tinanggihan ang apela mo',
  'İtirazın alındı, inceleniyor': 'Natanggap ang apela mo at sinusuri na',
  'İtiraz en az 10 karakter olmalı':
      'Dapat hindi bababa sa 10 karakter ang apela',
  'Yükleniyor...': 'Naglo-load...',
  'Bu bölüme puan ver': 'I-rate ang episode na ito',
  '{} kişi puanladı': '{} tao ang nag-rate',
  'Bölüm izlendi olarak işaretlendi': 'Namarkahan ang episode bilang napanood',
  'Sesli ara': 'Voice call',
  'Görüntülü ara': 'Video call',
  'Çalıyor...': 'Tumatawag...',
  'Bağlanıyor...': 'Kumokonekta...',
  'Cevapla': 'Sagutin',
  'Reddet': 'Tanggihan',
  'Sessize al': 'I-mute',
  'Hoparlör': 'Speaker',
  'Kamerayı kapat': 'Patayin ang camera',
  'Kamerayı çevir': 'Palitan ang camera',
  'Cevap yok': 'Walang sumasagot',
  'Arama reddedildi': 'Tinanggihan ang tawag',
  'Meşgul': 'Busy',
  'Bağlanılamadı': 'Hindi makakonekta',
  'Arama iptal edildi': 'Kinansela ang tawag',
  'Arama geçmişi': 'Kasaysayan ng tawag',
  'Gelen arama': 'Papasok na tawag',
  'Giden arama': 'Palabas na tawag',
  'Cevapsız arama': 'Hindi nasagot na tawag',
  'Arama şu anda kullanılamıyor': 'Hindi available ang pagtawag ngayon',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Naka-off ang video call ngayon, puwede kang tumawag gamit ang boses',
  'Bu kullanıcıyı arayamazsın': 'Hindi mo puwedeng tawagan ang user na ito',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Kailangan ninyong mag-follow sa isat isa para makatawag',
  'Bu kullanıcı şu anda aranamıyor':
      'Hindi puwedeng tawagan ang user na ito ngayon',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Masyadong maraming hindi nasagot na tawag. Subukan ulit pagkatapos ng {}',
  'Zaten bir aramadasın': 'Nasa tawag ka na',
  'Arama için mikrofon izni gerekiyor':
      'Kailangan ng pahintulot sa mikropono para makatawag',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'Kailangan ng pahintulot sa camera at mikropono para sa video call',
  'Arama başlatılamadı': 'Hindi masimulan ang tawag',
  'Kullanıcı bulunamadı': 'Hindi nakita ang user',
  'Kendini arayamazsın': 'Hindi mo puwedeng tawagan ang sarili mo',
  'Arama artık geçerli değil': 'Hindi na valid ang tawag na ito',
  'Bu aramanın tarafı değilsin': 'Hindi ka bahagi ng tawag na ito',
  'Arama bulunamadı': 'Hindi nakita ang tawag',
  'Çok fazla istek, biraz bekle': 'Masyadong maraming request, maghintay muna',
  'Bağlantı koptu': 'Nawala ang koneksyon',
  'Arama süre sınırına ulaştı': 'Naabot na ng tawag ang limitasyon sa oras',
  'Arama en fazla 4 saat sürebilir':
      'Ang tawag ay puwedeng tumagal nang hanggang 4 na oras',
  'Arama sona erdi': 'Tapos na ang tawag',
  'Sesli arama': 'Voice call',
  'Görüntülü arama': 'Video call',
  'Gelen aramalar': 'Mga papasok na tawag',
  'Sesli ve görüntülü arama bildirimleri':
      'Mga abiso para sa voice at video call',
  '{} sa': '{} oras',
  'Sesli ve Görüntülü Aramalar': 'Voice at Video Call',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Hindi kailanman nirerekord ang laman ng tawag. Ang audio at video ay dumadaloy nang end-to-end encrypted (DTLS-SRTP) sa pagitan ng mga device; hindi ito kayang i-decrypt, pakinggan o itago ng aming mga server.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Metadata lang ng tawag ang itinatago: kanino, anong direksyon, kailan at gaano katagal. Awtomatikong binubura ang mga talaang ito pagkatapos ng 90 araw.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Kapag hindi posible ang direktang koneksyon, dumadaan ang audio at video sa isang relay server (TURN) habang naka-encrypt. Hindi rin kayang i-decrypt o i-record ng relay ang laman.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Ginagamit ang mikropono tuwing voice o video call lang, at ang camera tuwing video call lang. Parehong nakakasara ang mga ito pagkatapos ng tawag.',
  'Takip ettiğin {} kişi izledi': '{} taong sinusundan mo ang nanood nito',
  'Yorum yaz...': 'Magsulat ng komento...',
  'Sıradaki bölüm': 'Susunod na episode',
  'Doğrulanmış testçi': 'Beripikadong tester',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Mga abiso para sa follow, like, sagot, mensahe at tag',
  'Sen': 'Ikaw',
  'Aradığınız kişide sesli arama devre dışı':
      'Naka-off ang voice call sa taong ito',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Naka-off ang video call sa taong ito',
  'Sesli aramalara izin ver': 'Payagan ang voice call',
  'Görüntülü aramalara izin ver': 'Payagan ang video call',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Kapag naka-off, walang makakatawag sa iyo gamit ang boses; may makikitang paalala ang tumatawag',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Kapag naka-off, walang makakatawag sa iyo gamit ang video; may makikitang paalala ang tumatawag',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Naka-off ang voice call. Puwede mong i-on sa Mga Setting > Privacy.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Naka-off ang video call. Puwede mong i-on sa Mga Setting > Privacy.',
  'Sesli ve görüntülü arama': 'Voice at video call',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Hindi makakatawag ang guest account. Gumawa ng account para magamit ito.',
  'Misafir hesaplar aranamaz': 'Hindi matatawagan ang guest account',
  'Puan dağılımı': 'Distribusyon ng rating',
  '{} yıldız': '{} bituin',
  'Yakında gelecek': 'Malapit nang dumating',
  '{} {} yayınlandı': 'Lumabas na ang {} {}',
  'Yeni bölüm yayınlandı': 'Lumabas na ang bagong episode',
  'Yeni bölümler': 'Mga bagong episode',
  'Geri': 'Bumalik',
  'Karşılamayı kapat': 'Isara ang panimula',
  'Adım {} / {}': 'Hakbang {} / {}',
  'Hadi başlayalım': 'Simulan na natin',
  'Kaydet ve devam': 'I-save at magpatuloy',
  '{} tanesini ekle': 'Idagdag ang napiling {}',
  'Şimdilik geç': 'Laktawan muna',
  'Doğum tarihin ne zaman?': 'Kailan ka ipinanganak?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Itinatanong namin ito para makapagpakita ng nilalamang angkop sa edad mo at para batiin ka sa kaarawan mo.',
  'Gün': 'Araw',
  'Ay': 'Buwan',
  'Yıl': 'Taon',
  'Doğum yılımı paylaşmak istemiyorum':
      'Ayaw kong ibahagi ang taon ng kapanganakan ko',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'Hindi ipinapakita nang publiko ang petsa ng kapanganakan mo sa profile mo. Ginagamit lang ito para sa nilalamang angkop sa edad at para sa pagbati sa kaarawan.',
  'Ocak': 'Enero',
  'Şubat': 'Pebrero',
  'Mart': 'Marso',
  'Nisan': 'Abril',
  'Mayıs': 'Mayo',
  'Haziran': 'Hunyo',
  'Temmuz': 'Hulyo',
  'Ağustos': 'Agosto',
  'Eylül': 'Setyembre',
  'Ekim': 'Oktubre',
  'Kasım': 'Nobyembre',
  'Aralık': 'Disyembre',
  'Verilerini yanında getir': 'Dalhin mo ang data mo',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Kung sinusubaybayan mo ang mga napapanood mo sa ibang app, puwede mong ilipat ang mga iyon dito. Hindi mo kailangang magsimula sa wala.',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Piliin ang ZIP file na na-export mo para mailipat ang mga napanood, rating at listahan mo.',
  'Aktarılıyor...': 'Ini-import...',
  'ZIP dosyası seç': 'Pumili ng ZIP file',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'Walang minamadali: puwede mo rin itong gawin mamaya sa Mga Setting > Data Ko.',
  'Hangi filmleri izledin?': 'Anong mga pelikula ang napanood mo?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Nandito ang pinakamaraming napanood. Idadagdag namin sa mga napanood mo ang mga pinindot mo.',
  'SERİ FİLMLER': 'MGA SERYE NG PELIKULA',
  'Serilerden {} film eklendi': '{} pelikula ang naidagdag mula sa mga serye',
  'Film listesi yüklenemedi': 'Hindi na-load ang listahan ng pelikula',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Puwede mong laktawan ang hakbang na ito at magdagdag ng gusto mo mamaya.',
  '{} film izlediklerine eklendi':
      '{} pelikula ang naidagdag sa mga napanood mo',
  'Film serileri': 'Mga serye ng pelikula',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Kung napanood mo ang isang serye mula simula hanggang dulo, idagdag ito sa isang pindot.',
  'Seri bulunamadı': 'Walang nakitang serye',
  'Daha sonra tekrar deneyebilirsin.': 'Puwede mong subukan ulit mamaya.',
  '{} film': '{} pelikula',
  'Eklendi': 'Naidagdag',
  'Tümünü izledim': 'Napanood ko lahat',
  'Peki ya diziler?': 'Paano naman ang mga serye?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Markahan ang mga napanood mo; habang pumipili ka, magdadala kami ng mga katulad nito.',
  'Dizi listesi yüklenemedi': 'Hindi na-load ang listahan ng serye',
  'Seçtiklerine benzeyenler': 'Katulad ng mga pinili mo',
  'Her şey hazır': 'Handa na ang lahat',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Silipin mo agad kung ano ang puwede mong gawin sa dizi.jpg.',
  'Profilini tamamla': 'Kumpletuhin ang profile mo',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'Puwede kang magdagdag ng Bio, profile photo at cover sa Mga Setting.',
  'Takvimin seni bekliyor': 'Naghihintay sa iyo ang Kalendaryo',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'Lumalabas sa kalendaryo ang mga bagong episode ng mga seryeng pinapanood mo, at ipapaalam namin sa iyo sa pamamagitan ng notipikasyon.',
  'Puan ver, yorum yaz': 'Mag-rate, magsulat ng komento',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'I-rate ang bawat episode, magsulat ng komento na may kurtinang Spoiler, at gumawa ng mga listahan.',
  'Verilerin sende kalır': 'Sa iyo nananatili ang data mo',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Nakatali lang sa account mo ang data mo at hindi ito ipinagbibili. Sa Mga Setting, puwede mong i-download ang lahat o burahin nang tuluyan ang account mo.',
  'Engellenen kullanıcılar': 'Mga na-block na user',
  'Engellediğin kişileri gör, engeli kaldır':
      'Tingnan ang mga na-block mo, alisin ang block',
  'Engellediğin kimse yok': 'Wala kang na-block na kahit sino',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Puwede mong i-block ang isang user mula sa tatlong-tuldok na menu sa profile niya.',
  '@{} engellensin mi?': 'I-block si @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      "Hindi ninyo makikita ang mga post, komento at profile ng isa't isa; hindi rin makakarating ang mensahe at tawag. Mapuputol ang pagsunod ninyo sa isa't isa kung mayroon man, at hindi na ito babalik kahit alisin mo pa ang block.",
  'Bu kullanıcıyı engelledin': 'Na-block mo ang user na ito',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Hindi mo nakikita ang mga post, komento at mensahe ng taong ito; hindi rin nakikita ng taong ito ang sa iyo.',
  '{} yeni bir yapımda: {}': '{} ay nasa bagong produksyon: {}',
  'Favori kişinden yeni yapım': 'Bagong produksyon mula sa paborito mong tao',
  '{} için bildirimler': 'Mga notipikasyon para kay {}',
  'Tüm bildirimler': 'Lahat ng notipikasyon',
  'Uygulamada ve telefonda': 'Sa app at sa telepono',
  'Yalnız uygulama içi': 'Sa loob lang ng app',
  'Telefon bildirimi gönderilmez':
      'Walang ipapadalang notipikasyon sa telepono',
  'Kapalı': 'Naka-off',
  'Bu kişi için bildirim yok': 'Walang notipikasyon para sa taong ito',
  'Favori kişilerin yeni yapımları': 'Mga bagong produksyon ng paboritong tao',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Kapag naka-off, walang makakatawag sa iyo gamit ang boses; may makikitang paalalang "naka-off" ang tumatawag',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Kapag naka-off, walang makakatawag sa iyo gamit ang video; may makikitang paalalang "naka-off" ang tumatawag',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'Aktibidad ko',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'Ang mga like, komento at napanood mo sa isang lugar',
  'Henüz hareketin yok': 'Wala pang aktibidad',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Nagtitipon dito ang lahat ng nili-like, kinokomentuhan at pinapanood mo.',
  'Bu süzgeçte hareket yok': 'Walang aktibidad sa filter na ito',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Pumili ng ibang uri o bumalik sa "Lahat".',
  'Hepsi': 'Lahat',
  'Puan': 'Rating',
  'Tepki': 'Reaksyon',
  'İzleme': 'Napanood',
  'Durum': 'Status',
  'Liste': 'Listahan',
  'Yorum yaptın': 'Nagkomento ka',
  'Yorumu beğendin': 'Nag-like ka ng komento',
  '{} puan verdin': 'Binigyan mo ng {}',
  'Tepki verdin': 'Nag-react ka',
  'Listene ekledin': 'Idinagdag mo sa listahan',
  'Takip etmeye başladın': 'Nagsimula kang sumunod',
  '"İzleyeceğim" işaretledin': 'Minarkahan bilang "Panonoorin Ko"',
  '"İzliyorum" işaretledin': 'Minarkahan bilang "Pinapanood Ko"',
  '"Bitirdim" işaretledin': 'Minarkahan bilang "Tapos Na"',
  '"Bıraktım" işaretledin': 'Minarkahan bilang "Hininto Ko"',
  'Silinmiş içerik': 'Tinanggal na content',
  'şimdi': 'ngayon',
  '{} g': '{} araw',
  '{} y': '{} taon',
  'İstatistiklerim': 'Stats ko',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Mga view at like sa mga post mo',
  'Henüz gönderin yok': 'Wala ka pang post',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Kapag nagkomento ka sa isang series o pelikula, magsisimulang mag-ipon dito ang bilang ng views at likes mo.',
  'Tüm zamanlar': 'Sa lahat ng panahon',
  'Son {} gün': 'Huling {} araw',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'Hindi pa nagsisimulang mag-ipon ang history ng views; lalabas bukas ang data ng unang araw.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'Nag-iipon ang history ng views mula {} (may {} araw na data), kaya hindi pa kumpleto ang bilang para sa {} araw.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'Naitatala ang history ng likes mula {}.',
  'Bu dönemde gösterilecek gönderi yok.':
      'Walang post na maipapakita para sa panahong ito.',
  'eksik veri': 'hindi kumpletong data',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Hindi makikita ng iba sa profile mo ang mga series at pelikulang napanood mo, ang mga counter ng panonood, screen time at match card',
  'Takipçi listemi gizle': 'Itago ang listahan ng mga follower ko',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Hindi makikita ng iba kung sino ang sumusunod sa iyo; nananatiling nakikita ang bilang ng follower mo',
  'Takip ettiklerimi gizle': 'Itago kung sino ang sinusundan ko',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Hindi makikita ng iba kung sino ang sinusundan mo; nananatiling nakikita ang bilang ng sinusundan mo',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Mas gusto ng user na ito na itago ang mga follower niya.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Mas gusto ng user na ito na itago kung sino ang sinusundan niya.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Istatistika ng post',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Makikita mo lang ang istatistika ng sarili mong mga post.',
  'Erişim': 'Abot',
  'Görüntüleyen': 'Mga nakakita',
  'Kaç farklı kişi gördü (son {} gün)':
      'Ilang magkakaibang tao ang nakakita (huling {} araw)',
  'Paylaşım': 'Mga share',
  'Bu gönderiden sonra': 'Pagkatapos ng post na ito',
  'Profil ziyareti': 'Mga pagbisita sa profile',
  'Yeni takip': 'Mga bagong follow',
  'İçeriğe tıklama': 'Mga tap sa content',
  'Spoiler perdesini açan': 'Binuksan ang spoiler',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Ang mga share, pagbisita sa profile, follow, tap sa content, breakdown ng pinagmulan at sukat ng spoiler ay naiipon mula {}; hindi sinukat ang mas maaga rito.',
  'Zamana yayılmış görüntülenme': 'Mga view sa paglipas ng panahon',
  'Görüntülenme nereden geldi': 'Saan nanggaling ang mga view',
  'Kimler gördü': 'Sino ang nakakita',
  'Günlük veri henüz birikmeye başlamadı.':
      'Hindi pa nagsisimulang maipon ang pang-araw-araw na data.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'Kailangan ng chart ng data ng hindi bababa sa dalawang araw. Naiipon ang data mula {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'Pinakamaraming view ang dumating sa ika-{} araw pagkatapos i-post: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Naiipon ang pang-araw-araw na mga view mula {}; hindi sinukat ang mas maaga rito.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'Kasisimula pa lang sukatin ang breakdown ng pinagmulan; wala pang natatanggap na naka-tag na view ang post na ito.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'Kasisimula pa lang sukatin ang breakdown ng follower/pagtuklas; wala pa ring data.',
  'Takip edenler': 'Mga follower',
  'Keşiften gelenler': 'Mula sa Tuklasin',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Pahina ng serye/pelikula',
  'Paylaşılan bağlantı': 'Na-share na link',
  'yeni ölçülüyor': 'bagong sinusukat',
  'Kendi ortalamanla aynı düzeyde': 'Katulad ng sarili mong average',
  'Kendi ortalamanın %{} üstünde': '{}% na mas mataas sa sarili mong average',
  'Kendi ortalamanın %{} altında': '{}% na mas mababa sa sarili mong average',
  'Etkileşim oranı': 'Rate ng engagement',
  '(beğeni + yorum) ÷ görüntülenme': '(mga like + komento) ÷ mga view',
  'Toplam görüntülenme': 'Kabuuang mga view',
  '{} ile {} arasında toplam {} görüntülenme':
      'Sa pagitan ng {} at {}: {} view sa kabuuan',
  'İstatistikleri gör': 'Tingnan ang istatistika',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'Para sa istatistikang ipinapakita sa may-ari ng post, iniingatan bilang pinagsama-samang counter: ilang beses at mula sa aling surface (feed, profile, full-screen na feed, pahina ng serye/pelikula, na-share na link) tiningnan ang post, kung sinusundan ba ng nanood ang may-ari ng post sa sandaling iyon, ang paglipat mula sa post papunta sa profile o content, ang mga follow na nabuo sa pamamagitan ng post, ang mga share, at ang pagbukas ng takip ng spoiler. Walang taglay na pagkakakilanlan ng user, IP address o timestamp ang mga counter na ito; hindi matutunton kung sino ang gumawa ng ano.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'Upang mabilang kung ilang magkakaibang tao ang nakakita ng isang post, isang hindi na maibabalik na keyed digest kada manonood (isang cryptographic na pagpapaikli na hango sa pagkakakilanlan ng user o sa IP address) ang iniingatan nang 90 araw. Ang bilang lamang ang ipinapakita sa may-ari ng post; hindi kailanman ibinabahagi ang pagkakakilanlan ng mga nanood sa anumang pagkakataon.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'Ilipat sa “Panonoorin Ko”?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'Ang isang pamagat ay panonoorin o napanood na. Kung magpapatuloy ka, mabubura ang {} marka ng panonood mo sa seryeng ito.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'Ang isang pamagat ay panonoorin o napanood na. Kung magpapatuloy ka, maaalis ang markang “Napanood Ko” mo sa pelikulang ito.',
  'Sil ve taşı': 'Burahin at ilipat',

  // --- Yapım ekibi / firma + seviye unvanları + doğum günü ---
  'Yapım Ekibi': 'Crew',
  'Yaratıcı': 'Tagalikha',
  'Yönetmen': 'Direktor',
  'Senaryo': 'Iskrip',
  'Yapımcı': 'Prodyuser',
  'Yapım Firmaları': 'Mga Kompanya ng Produksyon',
  'Yapım Firması': 'Kompanya ng Produksyon',
  'Firma bulunamadı': 'Hindi natagpuan ang kompanya',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'Walang ganitong uri ng pamagat ang kompanyang ito.',
  'Doğum günün kutlu olsun!': 'Maligayang kaarawan!',
  'İyi ki doğdun, iyi ki buradasın.':
      'Buti na lang isinilang ka, buti na lang nandito ka.',
  'Bugün {} yaşına girdin': 'Ngayon ay {} taong gulang ka na',
  'Teşekkürler': 'Salamat',
  'İki Adımlı Doğrulama': 'Two-Step Verification',
  'Girişte e-postana kod gönderilir':
      'Ipapadala ang code sa email mo kapag nag-sign in',
  'Kod {} adresine gönderildi': 'Ipinadala ang code sa {}',
  '6 haneli kod': '6-digit na code',
  'Doğrula': 'I-verify',
  'Yeniden gönder': 'Ipadala ulit',
  'Vazgeç': 'Kanselahin',
  'Yeni kod gönderildi': 'Naipadala ang bagong code',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'Walang hihinging code kapag nag-sign in gamit ang Google; ang Google mismo ang nagve-verify.',
  'Kapatmak için de kod gerekir.': 'Kailangan din ng code para i-off ito.',
  'E-postana erişemezsen hesabına giremezsin.':
      'Kung mawalan ka ng access sa email mo, hindi ka makakapasok sa account mo.',
  'İki adımlı doğrulama açıldı': 'Naka-on na ang two-step verification',
  'İki adımlı doğrulama kapatıldı': 'Naka-off na ang two-step verification',
  'Videonun ne kadarı izlendi': 'Gaano kalayo ang napanood',
  'Videoyu başlatanlar': 'Nagsimula ng video',
  'videonun %{} noktasına ulaştı': 'umabot sa {}% ng video',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'Napanood ng kalahati ng manonood ang hindi bababa sa {}% ng video.',
  'Sonuna kadar izleyen: %{}': 'Napanood hanggang dulo: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'Kailangan ng kurba ng hindi bababa sa {} view; {} pa lang ngayon.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'Batay ang kurba sa {} view at hindi ito naaapektuhan ng piniling panahon.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'Sinusukat ang oras ng panonood mula {}; hindi kasama ang mas lumang mga view.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} view. {}% ang umabot sa kalahati, {}% sa dulo.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'Level {}',
  'Sonraki seviyeye {} puan kaldı':
      '{} puntos na lang para sa susunod na level',
  'Gönderilerin': 'Mga post mo',
  '{} gönderi': '{} post',
  '{} gönderi · {} görüntülenme': '{} post · {} view',
  'önceki {} güne göre': 'kumpara sa nakaraang {} araw',
  'önceki {} güne göre %{} arttı':
      'kumpara sa nakaraang {} araw, tumaas nang {}%',
  'önceki {} güne göre %{} azaldı':
      'kumpara sa nakaraang {} araw, bumaba nang {}%',
  'önceki {} güne göre değişmedi':
      'walang pagbabago kumpara sa nakaraang {} araw',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'Mga view kada araw: pinakamababa {}, pinakamataas {}',
  'Etkileşim oranı henüz ölçülemedi':
      'Hindi pa masusukat ang rate ng engagement',
  'Oranlar': 'Mga rate',
  'Beğenme oranı': 'Rate ng like',
  'Yorum oranı': 'Rate ng komento',
  'Paylaşma oranı': 'Rate ng share',
  'İçeriğe gitme oranı': 'Rate ng content tap',
  'Profile gitme oranı': 'Rate ng profile visit',
  'Ziyaretten takibe dönüşüm': 'Bisita patungong follow',
  'beğeni ÷ görüntülenme': 'mga like ÷ mga view',
  'yorum ÷ görüntülenme': 'mga komento ÷ mga view',
  'paylaşım ÷ görüntülenme': 'mga share ÷ mga view',
  'içeriğe tıklama ÷ görüntülenme': 'mga tap sa content ÷ mga view',
  'profil ziyareti ÷ görüntülenme': 'mga pagbisita sa profile ÷ mga view',
  'yeni takip ÷ profil ziyareti':
      'mga bagong follow ÷ mga pagbisita sa profile',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'Kailangan ng mga rate ng hindi bababa sa {} view; {} pa lang ngayon.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'Galing ang mga rate sa kabuuang bilang ng post mula simula; hindi ito binabago ng pagpili ng araw sa ibaba.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'Kabuuang bilang ng post mula simula ang mga numerong ito (maliban sa mga kahon na may sariling paalala); ang pagpili ng araw sa ibaba ay nagbabago lang sa chart.',
  'Ortalama izlenme: videonun %{} kadarı': 'Average na napanood: {}% ng video',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'Ang average ng 20 bahagi ng kurba.',
  'Dizi, film, kişi veya şirket ara...':
      'Maghanap ng serye, pelikula, tao, o kumpanya...',
  'Şirketler': 'Mga kumpanya',
  'Senarist': 'Manunulat ng iskrip',
  'Bölüm puanları': 'Mga rating ng episode',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'Hindi ma-load ang mga rating ng episode',
  'Giriş gerekli': 'Kailangan mag-sign in',
  'Geçersiz oturum': 'Hindi wastong session',
  'Oturum sonlandı, tekrar giriş yap': 'Tapos na ang session, mag-sign in ulit',
  'Çok fazla istek; biraz sonra tekrar dene':
      'Masyadong maraming request; subukan ulit sa ilang sandali',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'Wala munang espasyo sa server, subukan ulit mamaya',
  'Devam eden yapımlar ({})': 'Kasalukuyang produksyon ({})',
  'Diziler ({})': 'Serye ({})',
  'Filmler ({})': 'Pelikula ({})',
  'Tüm yapımlar': 'Lahat ng produksyon',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'Puno na ang media storage mo; burahin ang lumang mga upload para makabawas',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'Mali ang email/username o password',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'Nakuha na ang email o username na ito',
  'Google doğrulaması başarısız': 'Nabigo ang beripikasyon ng Google',
  'Kod geçersiz veya süresi dolmuş': 'Hindi valid o expired na ang code',
  'Bu kullanıcıyla mesajlaşamazsın':
      'Hindi ka makakapag-mensahe sa user na ito',
  'Kendini takip edemezsin': 'Hindi mo puwedeng i-follow ang sarili mo',
  'Bu kullanıcıyı takip edemezsin':
      'Hindi mo puwedeng i-follow ang user na ito',
  'Kendini engelleyemezsin': 'Hindi mo puwedeng i-block ang sarili mo',
  'Yorum 1-1000 karakter olmalı': 'Ang komento ay dapat 1–1000 karakter',
  'Boş mesaj gönderilemez': 'Hindi makakapagpadala ng bakanteng mensahe',
  'Yorum bulunamadı': 'Hindi nahanap ang komento',
  'Şifre hatalı': 'Mali ang password',
  'Şifre en az 6 karakter olmalı':
      'Ang password ay dapat 6 na karakter man lang',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'GIF, PNG, JPEG, o WebP lang ang puwedeng i-upload',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'Mga suportadong uri: GIF, PNG, JPEG, WebP, MP4, WebM, audio',
  'Geçerli bir ZIP dosyası değil': 'Hindi valid na ZIP file',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'Para makuha ang data sa email, i-link muna ang email',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'May watch history ka. Para sa "Papanoodin", burahin muna ang mga marka.',
  'Arama şu anda kapalı': 'Naka-off ang tawag sa ngayon',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'Hindi mabuksan ng guest account ang tawag; gumawa ng account',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'Nagre-restart ang server, subukan ulit sa ilang saglit',
  'Puan 1-10 arası olmalı': 'Ang marka ay dapat 1 hanggang 10',
  'En fazla 10 medya eklenebilir':
      'Hanggang 10 media lang ang puwedeng idagdag',
  'Bu cihazdan yeni hesap açılamıyor':
      'Hindi makagawa ng account mula sa device na ito',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'Kailangan ng wastong email, username, at password na hindi bababa sa 6 na karakter',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'Kailangan ng wastong email at password na hindi bababa sa 6 na karakter',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'Username 3–20 karakter; maliliit na letra, numero, tuldok, gitling, underscore (hindi sa dulo)',
  'Bu hesap zaten bağlı': 'Naka-link na ang account na ito',
  'Hesap oluşturulamadı': 'Hindi nagawa ang account',
  'Misafir hesabı oluşturulamadı': 'Hindi nagawa ang guest account',
  'Hesap bulunamadı': 'Hindi nahanap ang account',
  'Bu hesapta e-posta yok': 'Walang email ang account na ito',
  'İki adımlı doğrulama zaten bu durumda':
      'Naka-ganito na ang two-step verification',
  'Kod yanlış': 'Maling code',
  'Kodun süresi doldu': 'Nag-expire na ang code',
  'Kullanıcının e-postası yok (misafir hesap)':
      'Walang email ang user na ito (guest account)',
  'Bio en fazla 300 karakter olabilir': 'Ang bio ay hanggang 300 karakter lang',
  'Geçersiz ülke': 'Hindi wastong bansa',
  'Geçersiz sosyal bağlantı': 'Hindi wastong social link',
  'Geçersiz doğum tarihi': 'Hindi wastong petsa ng kapanganakan',
  'Liste adı gerekli': 'Kailangan ang pangalan ng listahan',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'Ang pangalan ay hanggang 60, ang paglalarawan 300 karakter',
  'Liste bulunamadı': 'Hindi nahanap ang listahan',
  'Değiştirilecek tercih yok': 'Walang ia-update',
  'İnceleme en fazla 2000 karakter olabilir':
      'Ang review ay hanggang 2000 karakter lang',
  'Önce içeriği "bitirdim" olarak işaretle': 'Markahan muna bilang tapos na',
  'Önce kişiyi favorile': 'I-favorite muna ang tao',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'Kailangan ang season at episode para sa komento ng episode',
  'Yanıtlanan yorum bulunamadı': 'Hindi nahanap ang komentong sinasagot',
  'Geri bildirim 3-2000 karakter olmalı':
      'Ang feedback ay dapat 3–2000 karakter',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'Kailangan ang pamagat at teksto (hindi bababa sa 2 karakter)',
  'Kendine mesaj gönderemezsin': 'Hindi ka puwedeng magmensahe sa sarili',
  'Mesaj en fazla 2000 karakter olabilir':
      'Ang mensahe ay hanggang 2000 karakter lang',
  'Mesaj 1-2000 karakter olmalı': 'Ang mensahe ay dapat 1–2000 karakter',
  'Mesaj bulunamadı': 'Hindi nahanap ang mensahe',
  'Mesaj bulunamadı veya düzenlenemez':
      'Hindi nahanap ang mensahe o hindi ma-edit',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'Maaari mo lang i-report ang mensaheng ipinadala sa iyo',
  'Sebep gerekli': 'Kailangan ang dahilan',
  'İtiraz edilecek aktif bir ceza yok':
      'Walang aktibong parusa na maaaring iapela',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'May appeal ka nang naghihintay ng review',
  'Bu ceza için itirazın zaten incelendi':
      'Na-review na ang appeal mo para sa parusang ito',
  'Medya bağlantısının süresi dolmuş': 'Nag-expire na ang media link',
  'Bu medya için imzalı bağlantı gerekli':
      'Kailangan ng signed link para sa media na ito',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'Nagre-restart ang calling service; subukan ulit sa ilang sandali',
  'Puan göstergesi': 'Gabay sa rating',
  'İzleme İstatistiklerim': 'Aking Istatistika sa Panonood',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'Sa sandaling markahan mo ang isang episode o pelikula bilang napanood, magsisimulang mag-ipon dito ang iyong istatistika.',
  '{} sa {} dk': '{} o {} min',
  'Yaklaşık ekran süresi': 'Tinatayang oras sa screen',
  'İzleme serisi': 'Sunod-sunod na panonood',
  'Şu anki seri': 'Kasalukuyang sunod-sunod',
  'En uzun seri': 'Pinakamahabang sunod-sunod',
  'Haftanın günleri': 'Mga araw ng linggo',
  'En çok izlediklerin': 'Pinakamadalas panoorin',
  'Bu dönemde izleme yok': 'Walang panonood sa panahong ito',
  'Paz': 'Lin',
  'Pzt': 'Lun',
  'Sal': 'Mar',
  'Çar': 'Miy',
  'Per': 'Huw',
  'Cum': 'Biy',
  'Cmt': 'Sab',
  '{} bölüm': '{} episode',
  '{} bölüm~tekil': '{} episode',
  '{} kez': '{} beses',
  '{} kez~tekil': '{} beses',
  'Son {} gün · günlük': 'Huling {} araw · araw-araw',
  'Son {} gün · haftalık': 'Huling {} araw · lingguhan',
  'Ekran süren, serin ve en çok izlediklerin':
      'Ang oras mo sa screen, sunod-sunod at pinakamadalas panoorin',
  'Daralt': 'I-collapse',
  'Listeyi düzenle': 'I-edit ang listahan',
  'Bitti': 'Tapos na',
  'Sırala': 'Ayusin ang pagkakasunod',
  'Herkese göster': 'Ipakita sa lahat',
  'Başkalarından gizle': 'Itago sa iba',
  'Listeden kaldır': 'Alisin sa listahan',
  'Listeden kaldırılsın mı?': 'Alisin sa listahan?',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'Aalisin ang pamagat na ito sa listahan. Kung gusto mo lang itagong, gamitin ang icon na mata.',
  'Sıralama kaydedilemedi': 'Hindi na-save ang pagkakasunod',
  'Değişiklik kaydedilemedi': 'Hindi na-save ang pagbabago',
  'Kaldırılamadı': 'Hindi naalis',
  'Popülerlik': 'Katanyagan',
  'TMDB puanı': 'Rating sa TMDB',
  'Yapım yılı': 'Taon ng produksyon',
  'dizi.jpg puanı': 'Rating sa dizi.jpg',
  'İzlenme': 'Panonood',
  'Yorum sayısı': 'Bilang ng komento',
  'Tüm raflara uygulanır': 'Naaangkop sa lahat ng istante',
  'En popüler {} yapım arasında sıralandı':
      'Inayos sa {} pinakasikat na pamagat',
  'Altyazı görünümü': 'Hitsura ng subtitle',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık':
      'Kulay, font, laki, gilid at opacity',
  'Bu bir örnek altyazıdır.': 'Ito ay isang halimbawang subtitle.',
  'Ayar değiştikçe önizleme anında güncellenir.':
      'Agad na nag-a-update ang preview habang binabago mo ang setting.',
  'Yazı biçimi': 'Estilo ng text',
  'Yazı rengi': 'Kulay ng text',
  'Yazı opaklığı': 'Opacity ng text',
  'Yazı tipi': 'Font',
  'Yazı boyutu': 'Laki ng text',
  'Karakter ayrıtı': 'Gilid ng karakter',
  'Ayrıt türü': 'Uri ng gilid',
  'Ayrıt rengi': 'Kulay ng gilid',
  'Yok': 'Wala',
  'Dış çizgi': 'Outline',
  'Gölge': 'Drop shadow',
  'Kabartma': 'Nakaangat',
  'Oyma': 'Nakalubog',
  'Arka plan rengi': 'Kulay ng background',
  'Arka plan opaklığı': 'Opacity ng background',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      'Ang background ay ang punong bahagi sa likod mismo ng text; ang window naman ang mas malawak na ibabaw sa likod ng buong bloke ng subtitle.',
  'Pencere': 'Window',
  'Pencere rengi': 'Kulay ng window',
  'Pencere opaklığı': 'Opacity ng window',
  'Altyazı görünümü sıfırlansın mı?': 'I-reset ang hitsura ng subtitle?',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      'Babalik sa default ang mga setting ng kulay, font, laki, gilid at opacity.',
  'Altyazı görünümü varsayılana döndü':
      'Naibalik sa default ang hitsura ng subtitle',
  '{} indiriliyor…': 'Dina-download ang {}…',
  'Seçince indirilir': 'Mada-download kapag pinili',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      'Hindi na-download ang font. Ipinapakita gamit ang default na font.',
  'Beyaz': 'Puti',
  'Siyah': 'Itim',
  'Kırmızı': 'Pula',
  'Yeşil': 'Berde',
  'Mavi': 'Asul',
  'Sarı': 'Dilaw',
  'Camgöbeği': 'Cyan',
  'Macenta': 'Magenta',
  'Yapım bütçesi': 'Badyet sa produksyon',
  'Yapım bütçesi ve dünya çapında hasılat':
      'Badyet sa produksyon at kita sa buong mundo',
  'Dizinin yayın durumu': 'Status ng pagpapalabas ng serye',
  'Devam ediyor': 'Tuloy pa',
  'Sona erdi': 'Nagwakas na',
  'İptal edildi': 'Kanselado',
  'Yapımda': 'Ginagawa pa',
  'Planlandı': 'Nakaplano',
  'Pilot bölüm': 'Pilot episode',
  'Ad': 'Pangalan',
  'Adın': 'Ang pangalan mo',
  'Kullanıcı adı': 'Username',
  'Kullanıcı adını değiştir': 'Palitan ang username',
  'Kullanıcı adını 90 günde bir değiştirebilirsin':
      'Puwede mong palitan ang username mo isang beses kada 90 araw',
  'Değiştir': 'Palitan',
  '{} gün sonra değiştirebilirsin': 'Mapapalitan mo ito sa loob ng {} araw',
  'Kullanıcı adın: @{}': 'Ang username mo: @{}',
  'Bu kullanıcı adı zaten alınmış': 'Kuha na ang username na ito',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış':
      'Nakareserba muna ang username na ito para sa ibang account',
  'Bu zaten senin kullanıcı adın': 'Ito na nga ang username mo',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      'Username 3–20 karakter; maliliit na letra, numero, tuldok, gitling, underscore',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      'Lumalabas sa profile mo sa ibabaw ng username mo. Puwede mong iwanang blangko.',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      'Pagkatapos mong palitan, hindi mo na ito mababago sa loob ng 90 araw. Nakareserba pa rin sa iyo ang lumang username mo nang 90 araw — puwede kang bumalik dito, at walang ibang makakakuha nito sa panahong iyon. Hindi na bubuksan ng mga link sa lumang pangalan mo ang profile mo.',
  'Etkinliğim': 'Aktibidad',
  'Tercihler': 'Mga Kagustuhan',
  'Gizlilik ve güvenlik': 'Privacy at seguridad',
  'Destek': 'Suporta',
  'Hesap': 'Account',
  '{} dizileri': 'Mga serye: {}',
  '{} filmleri': 'Mga pelikula: {}',
  'En üste taşı': 'Ilipat sa itaas',
  'Sırayı sıfırla': 'I-reset ang pagkakasunod',
  'Listede ara': 'Maghanap sa listahan',
  'Elle sıra sıfırlansın mı?': 'I-reset ang manual na pagkakasunod?',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      'Babalik ang listahan sa default na pagkakasunod (nauuna ang huli mong minarkahan).',
  'Sıra sıfırlanamadı': 'Hindi na-reset ang pagkakasunod',
  'Listenin en üstüne taşındı': 'Inilipat sa itaas ng listahan',
  'Adlar yükleniyor…': 'Nilo-load ang mga pamagat…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      'Pindutin nang matagal ang poster para hilahin ito. Para iharap ang malayong pamagat, gamitin ang “Ilipat sa itaas”.',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      'Naka-off ang paghila kapag naghahanap; iharap ito gamit ang “Ilipat sa itaas” ({} resulta).',
  'Görünüm': 'Anyo',
  'En çok izlediğin filmler': 'Mga pelikulang pinakamadalas mong pinanood',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      'Tinatayang tagal: bawat episode ~{} min, bawat pelikula ~{} min',
  'Bu kullanıcı adı sistem tarafından ayrılmış':
      'Nakareserba ng system ang username na ito',
  'Ekran süresi': 'Oras sa screen',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir":
      'Ang mga tagal ay ang totoong tagal ng mga episode at pelikula mula sa TMDB',
  'Tüm zamanlar: {} bölüm · {} film · {}':
      'Sa kabuuan: {} episode · {} pelikula · {}',
  'Kabul et': 'Tanggapin',
  'Reddedilenler': 'Mga tinanggihan',
  'İstekler': 'Mga kahilingan',
  'Reddettiğin istek yok': 'Walang tinanggihang kahilingan',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      'Nananatili rito ang mga tinanggihang kahilingan; puwede mo itong tanggapin ulit anumang oras.',
  'Ne izlesem?': 'Ano ang papanoorin ko?',
  'Karışık': 'Halo-halo',
  'Çarkı çevir': 'Ikutin ang gulong',
  'Tekrar çevir': 'Ikutin muli',
  'Bu türde içerik yok': 'Walang nilalaman ng ganitong uri',
  'Bütçe': 'Badyet',
  'dizi.jpg AI özeti': 'Buod ng AI ng dizi.jpg',
  'Daha fazlasını gör': 'Tingnan ang higit pa',
  'Yıldız sistemi': 'Sistema ng bituin',
  '{} yıldız üzerinden': 'Sa {} bituin',
  'Önizleme': 'Preview',
  'dokununca açılır': 'bubukas kapag na-tap',
  'Bir azalt': 'Bawasan ng isa',
  'Bir artır': 'Dagdagan ng isa',
  'Ölçek kaydedilemedi': 'Hindi na-save ang scale',
  'Ölçeği değiştirmek puanlarını silmez; aynı puanlar yeni ölçekte gösterilir.':
      'Ang pagpapalit ng scale ay hindi nagbubura ng iyong mga rating; ipinapakita ang parehong rating sa bagong scale.',
  'En aşağıya gönder': 'Ipadala sa ibaba',
  'Listenin en altına taşındı': 'Inilipat sa ibaba ng listahan',
  'Oturumun sonlandı': 'Natapos na ang session mo',
  'Bu hesabın oturumları kapatıldı ya da şifresi değişti. Devam etmek için tekrar giriş yap.':
      'Na-sign out ang account na ito sa lahat ng device o nagbago ang password. Mag-sign in ulit para magpatuloy.',
  'Son izleme: {}': 'Huling napanood: {}',
  '{} tarihinde izledin': 'Napanood noong {}',
  'Geri bildirimine yanıt verdik': 'Sinagot namin ang feedback mo',
  'Bu yanıt artık görüntülenemiyor.': 'Hindi na makikita ang sagot na ito.',
  'Gönderdiğin geri bildirim': 'Ang feedback na ipinadala mo',
  'Dizi veya film seç (zorunlu)': 'Pumili ng serye o pelikula (kailangan)',
  'Bölüm seç (isteğe bağlı)': 'Pumili ng episode (opsyonal)',
  '{}. sezon {}. bölüm': 'Season {}, episode {}',
  'Ne düşünüyorsun?': 'Ano sa tingin mo?',
  '{}/{} yükleniyor': 'Ina-upload {}/{}',
  'Fotoğraf/video ekle': 'Magdagdag ng larawan o video',
  'Paylaşmak için önce bir dizi veya film seç.':
      'Pumili muna ng serye o pelikula para makapag-share.',
  'Sezon seç': 'Pumili ng season',
  '{}. sezon': 'Season {}',
  'Bölüm seçme (yalnız dizi hakkında)':
      'Walang episode (tungkol lang sa serye)',
  'Sezonlar yüklenemedi.': 'Hindi ma-load ang mga season.',
  'Bu dizide bölüm bilgisi yok.':
      'Walang impormasyon ng episode para sa seryeng ito.',
  'Bu sezonda bölüm yok.': 'Walang episode sa season na ito.',
  '{}. bölüm': 'Episode {}',
  'Dizi veya film ara...': 'Maghanap ng serye at pelikula...',
  'İzlediğin dizi ve film hakkında yorum paylaş':
      'Mag-share ng komento tungkol sa napanood mo',
  'Yapım seç (zorunlu)': 'Pumili ng pamagat (kailangan)',
  'Paylaşmak için önce bir yapım seç.':
      'Pumili muna ng pamagat para makapag-share.',
  'Kişi': 'Tao',
  'Yapım firması': 'Production company',
  'Yapım ara...': 'Maghanap ng pamagat...',
  'Çarkı çevirmek için sürükle veya dokun':
      'I-drag o i-tap para paikutin ang gulong',
  'Arşiv': 'Archive',
  'Yüklediklerim': 'Mga in-upload ko',
  'GIF ara...': 'Maghanap ng GIF...',
  'GIF yükle': 'Mag-upload ng GIF',
  'GIF etiketleri': 'Mga tag ng GIF',
  'Virgülle ayır. Aramada bu kelimelerle bulunur.':
      'Paghiwalayin ng kuwit. Sa mga salitang ito ito makikita.',
  'gülme, alkış, şaşkın': 'tawa, palakpak, gulat',
  'Yükle': 'I-upload',
  'Henüz GIF yok': 'Wala pang GIF',
  'Bu aramaya uyan GIF yok': 'Walang GIF na tumutugma sa paghahanap na ito',
  'Arşiv yeni. İlk GIF i sen yükle — sen hemen kullanırsın, onaydan sonra herkes görür.':
      'Bago ang archive. I-upload mo ang unang GIF — magagamit mo agad, makikita ng lahat pagkatapos maaprubahan.',
  'GIF yüklendi. Sen hemen kullanabilirsin; herkese açık arşive onaydan sonra girer.':
      'Na-upload ang GIF. Magagamit mo agad; papasok sa pampublikong archive pagkatapos maaprubahan.',
  'Onay bekliyor': 'Naghihintay ng pag-apruba',
  'GIF listesi yüklenemedi': 'Hindi ma-load ang listahan ng GIF',
  'GIF yüklenemedi': 'Hindi na-upload ang GIF',
  'Bu GIF i şikayet et': 'I-report ang GIF na ito',
  'Uygunsuz içerik yöneticiye bildirilir ve arşivden kaldırılabilir.':
      'Iniuulat sa moderator ang hindi angkop na nilalaman at maaaring tanggalin sa archive.',
  'Şikayetin alındı': 'Natanggap ang iyong report',
  'Şikayet gönderilemedi': 'Hindi naipadala ang report',
  'Dizinin kendisi': 'Ang serye mismo',
  'Sezon ya da bölüm seçme': 'Walang season o episode',
  'Tüm {}. sezon': 'Buong season {}',
  'Bölüm seçme': 'Walang episode',
  'En fazla {} yapım ekleyebilirsin.':
      'Puwede kang magdagdag ng hanggang {} pamagat.',
  'Bu zaten ekli.': 'Nadagdag na.',
  'Dizi, film, oyuncu ya da yönetmen etiketle — gönderin onların sayfasında da görünür.':
      'I-tag ang serye, pelikula, aktor o direktor — lalabas din ang post mo sa page nila.',
  'Etiket ekle': 'Magdagdag ng tag',
  'Dizi, film, oyuncu ya da yönetmen etiketle':
      'I-tag ang serye, pelikula, aktor o direktor',
  'Gönderiden vazgeç': 'Itapon ang post',
  'Yazdıkların kaydedilmeyecek.': 'Hindi mase-save ang isinulat mo.',
  'Yazmaya devam et': 'Magpatuloy sa pagsulat',
  'Bulunamadı. Adın yazılışını değiştirip dene.':
      'Walang nahanap. Subukan ang ibang baybay.',
  'Dizi, film, oyuncu, yönetmen ya da yapım firması ara.':
      'Maghanap ng serye, pelikula, aktor, direktor o production company.',
};
