/// Otomatik üretilen çeviri haritası (de).
const Map<String, String> cevirilerDe = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Sie haben alles gesehen, wir zeigen es Ihnen von Anfang an',
  'Aktarılacak tanınan veri bulunamadı.':
      'Keine erkannten Daten zum Importieren gefunden.',
  'Arama': 'Suche',
  'Aramaya başla': 'Starte die Suche',
  'Son aramalar': 'Letzte Suchen',
  'Ayarlar': 'Einstellungen',
  'Bağla': 'Verknüpfen',
  'Bio': 'Bio',
  'Bitirdim': 'Abgeschlossen',
  'Bunları da Beğenebilirsin': 'Das könnte dir auch gefallen',
  'Bölüm': 'Episode',
  'Bıraktım': 'Abgebrochen',
  'Dil': 'Sprache',
  'Dil ara...': 'Sprache suchen...',
  'Dizi': 'Serie',
  'Dizi ve filmlerini takip et': 'Behalte deine Serien und Filme im Blick',
  'Dizi yorumu': 'Serienkommentar',
  'Dizi, film veya kişi ara...': 'Serie, Film oder Person suchen...',
  'Dosya en fazla 30MB olabilir': 'Die Datei darf höchstens 30MB groß sein',
  'Dosya en fazla {}MB olabilir': 'Die Datei darf höchstens {}MB groß sein',
  'E-posta': 'E-Mail',
  'E-posta veya kullanıcı adı': 'E-Mail oder Benutzername',
  'En az 2 harf yaz': 'Gib mindestens 2 Buchstaben ein',
  'Film': 'Film',
  'Film yorumu': 'Filmkommentar',
  'Fotoğraf / video ekle': 'Foto / Video hinzufügen',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto oder GIF — Profil- und Titelbild',
  'Giriş Yap': 'Anmelden',
  'Gönder': 'Senden',
  'Gönderildi': 'Gesendet',
  'Haftanın Dizileri': 'Serien der Woche',
  'Haftanın Filmleri': 'Filme der Woche',
  'Henüz izleme kaydın yok': 'Du hast noch nichts angesehen',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Du hast noch keine Listen — erstelle eine im Profil-Tab.',
  'Henüz yorum yok.': 'Noch keine Kommentare.',
  'Hesabın bağlandı!': 'Dein Konto wurde verknüpft!',
  'Hesabın yok mu? Kayıt ol': 'Noch kein Konto? Registrieren',
  'Hesabını Bağla': 'Konto verknüpfen',
  'Hesap Oluştur': 'Konto erstellen',
  'Kapak resmi ekle': 'Titelbild hinzufügen',
  'Kaydet': 'Speichern',
  'Kendinden bahset...': 'Erzähl etwas über dich...',
  'Keşfet': 'Entdecken',
  'Kimseyi takip etmiyor': 'Folgt niemandem',
  'Kişi ara': 'Person suchen',
  'Kişi yorumu': 'Personenkommentar',
  'Konuk Oyuncular': 'Gastdarsteller',
  'Kullanıcı adı (küçük harf)': 'Benutzername (Kleinbuchstaben)',
  'Kullanıcı adı ara...': 'Benutzername suchen...',
  'Liste adı': 'Listenname',
  'Listeye Ekle': 'Zur Liste hinzufügen',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Du nutzt ein Gastkonto — verknüpfe deine E-Mail und verliere deine Daten nicht!',
  'Misafir olarak devam et': 'Als Gast fortfahren',
  'Oluştur': 'Erstellen',
  'Oyuncular': 'Besetzung',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil gespeichert',
  'Puanla': 'Bewerten',
  'Puanı Sil': 'Bewertung löschen',
  'Puanın': 'Deine Bewertung',
  'Sezonlar': 'Staffeln',
  'Sunucu hatası ({})': 'Serverfehler ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Kommentar zu S{}E{}',
  'Takibi Bırak': 'Entfolgen',
  'Takip': 'Folge ich',
  'Takip Edilenler': 'Gefolgte',
  'Takip Et': 'Folgen',
  'Takipçi': 'Follower',
  'Takipçi yok': 'Keine Follower',
  'Takipçiler': 'Follower',
  'Takvim': 'Kalender',
  'Tamam': 'OK',
  'Tekrar Dene': 'Erneut versuchen',
  'Tekrar dene': 'Erneut versuchen',
  'Toplam İzleme Süresi': 'Gesamte Bildschirmzeit',
  'Tüm Zamanların En İyileri': 'Die Besten aller Zeiten',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Exportiere alle deine Daten (Verlauf, Bewertungen, Kommentare, Listen) als TV-Time-kompatibles ZIP oder importiere ein ZIP aus einer anderen App.',
  'Tümünü Kaldır': 'Alle entfernen',
  'Tümünü İzledim': 'Alle gesehen',
  'Türk Dizileri': 'Türkische Serien',
  'Veri içe aktar (.zip)': 'Daten importieren (.zip)',
  'Verilerim': 'Meine Daten',
  'Verilerimi dışa aktar (e-posta)': 'Meine Daten exportieren (E-Mail)',
  'Verilerini dışa aktar': 'Deine Daten exportieren',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Keine anstehenden Episoden.\nSetze eine Serie in der Detailansicht auf "Schaue ich" und verfolge neue Episoden hier.',
  'Yapımları': 'Filmografie',
  'Yeni Diziler': 'Neue Serien',
  'Yeni Liste': 'Neue Liste',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Neuer Benutzername (optional)',
  'Yorum': 'Kommentar',
  'Yorumunu yaz...': 'Schreib deinen Kommentar...',
  'Zaten hesabın var mı? Giriş yap': 'Hast du schon ein Konto? Anmelden',
  'ort. {}': 'Ø {}',
  'takip': 'folge ich',
  'takipçi': 'Follower',
  '{} / {} bölüm': '{} / {} Episoden',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} Mon.',
  '{} bölüm izlendi': '{} Episoden gesehen',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} Min.',
  '{} gün': '{} Tg.',
  '{} içerik': '{} Titel',
  '{} içerik · otomatik': '{} Titel · automatisch',
  '{} kayıt atlandı (eşleşmedi).':
      '{} Einträge übersprungen (keine Übereinstimmung).',
  '{} saat': '{} Std.',
  '{} sezon': '{} Staffeln',
  '{} yıl': '{} J.',
  '{}. Bölüm': 'Episode {}',
  '{}. Sezon': 'Staffel {}',
  'Çıkış Yap': 'Abmelden',
  'Ülke': 'Land',
  'Ülke ara...': 'Land suchen...',
  'Ülke seç': 'Land auswählen',
  'İlk yorumu sen yaz!': 'Schreib den ersten Kommentar!',
  'İncelemeler': 'Rezensionen',
  'İncelemen (isteğe bağlı)': 'Deine Rezension (optional)',
  'İptal': 'Abbrechen',
  'İzlediklerim': 'Mein Verlauf',
  'İzledim': 'Gesehen',
  'İzledin': 'Gesehen',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Dein Verlauf und deine Listen bleiben erhalten; du kannst dich jetzt von jedem Gerät aus anmelden.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Dein Verlauf, deine Bewertungen, Kommentare und Listen werden als ZIP an deine hinterlegte E-Mail-Adresse gesendet.',
  'İzleyeceğim': 'Will ich sehen',
  'İzliyorum': 'Schaue ich',
  'İçe aktarım tamamlandı': 'Import abgeschlossen',
  'Şifre': 'Passwort',
  '• profil bilgisi': '• Profildaten',
  '• {} dizi durumu': '• {} Serienstatus',
  '• {} izleme kaydı': '• {} Verlaufseinträge',
  '• {} liste': '• {} Listen',
  '• {} puan': '• {} Bewertungen',
  '• {} yorum': '• {} Kommentare',
  '{}+ yapım': '{}+ Titel',
  'Yorumlar': 'Kommentare',
  'Yorumlar ({})': 'Kommentare ({})',
  'Yorumları ({})': 'Kommentare ({})',
  'Listelerim': 'Meine Listen',
  'Nereden izledin?': 'Wo hast du es gesehen?',
  'Diziye git': 'Zur Serie',
  'TV / Kanal': 'TV / Sender',
  'Sinema': 'Kino',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Sonstiges',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Dein Feed ist leer.\nWenn jemand deine Serien und Filme kommentiert, erscheint es hier.',
  'Listeleri ({})': 'Listen ({})',
  'Liste boş.': 'Diese Liste ist leer.',
  'Yanıtla': 'Antworten',
  '@{} kullanıcısına yanıt veriyorsun': 'Du antwortest @{}',
  'İzlediğim Diziler ({})': 'Gesehene Serien ({})',
  'İzlediğim Filmler ({})': 'Gesehene Filme ({})',
  'Tümünü gör': 'Alle ansehen',
  'Bildirimler': 'Benachrichtigungen',
  'Henüz bildirim yok': 'Noch keine Benachrichtigungen',
  '@{} yorumuna yanıt verdi': '@{} hat auf deinen Kommentar geantwortet',
  '@{} yorumunu beğendi': '@{} gefällt dein Kommentar',
  '@{} seni takip etti': '@{} folgt dir',
  '@{} sana mesaj gönderdi': '@{} hat dir eine Nachricht gesendet',
  'Mesajlar': 'Nachrichten',
  'Mesaj': 'Nachricht',
  'Mesajını yaz...': 'Schreib eine Nachricht...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Noch keine Chats.\nÖffne ein Profil und sende eine Nachricht.',
  'Şifreni mi unuttun?': 'Passwort vergessen?',
  'Şifreyi Sıfırla': 'Passwort zurücksetzen',
  'E-postadaki kod': 'Code aus der E-Mail',
  'Yeni şifre': 'Neues Passwort',
  'Sana Özel': 'Für dich',
  '{} özetin': 'Dein {}-Rückblick',
  'Yıllık izleme istatistiklerin': 'Deine Jahres-Statistik',
  'Rozetler': 'Abzeichen',
  'Verdiğin puan': 'Vergebene Bewertungen',
  'Ortalama puanın': 'Deine Durchschnittswertung',
  'En çok izlediğin diziler': 'Deine meistgesehenen Serien',
  'İlk Bölüm': 'Erste Folge',
  '100 Bölüm': '100 Folgen',
  '1000 Bölüm': '1000 Folgen',
  'İlk Film': 'Erster Film',
  '50 Film': '50 Filme',
  'İlk Yorum': 'Erster Kommentar',
  '25 Yorum': '25 Kommentare',
  '10 Puan': '10 Bewertungen',
  'İlk Takipçi': 'Erster Follower',
  '10 Dizi Bitirdin': '10 Serien beendet',
  'İzlemeyi Bıraktım': 'Abgebrochen',
  'İzlediği Diziler ({})': 'Gesehene Serien ({})',
  'İzlediği Filmler ({})': 'Gesehene Filme ({})',
  '500 Bölüm': '500 Folgen',
  '5000 Bölüm': '5000 Folgen',
  '10 Film': '10 Filme',
  '100 Film': '100 Filme',
  '100 Yorum': '100 Kommentare',
  '50 Puan': '50 Bewertungen',
  '100 Puan': '100 Bewertungen',
  '10 Takipçi': '10 Follower',
  '50 Takipçi': '50 Follower',
  '25 Dizi Bitirdin': '25 Serien beendet',
  '50 Dizi Bitirdin': '50 Serien beendet',
  '10 Beğeni': '10 Likes',
  '100 Beğeni': '100 Likes',
  'yazıyor...': 'schreibt...',
  'Profil düzeni': 'Profil-Layout',
  'Konumla ve kırp': 'Ausrichten und zuschneiden',
  'Listeye eklendi': 'Zur Liste hinzugefügt',
  'Listeyi sil?': 'Liste löschen?',
  'Sil': 'Löschen',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Dieser Titel gilt dann als nie gesehen und wird aus deinen Listen entfernt.',
  'Gelecek bölüm bugün': 'Nächste Folge heute',
  'Gelecek bölüm {} gün sonra': 'Nächste Folge in {} Tagen',
  'Tema': 'Design',
  'Sistem': 'System',
  'Koyu': 'Dunkel',
  'Açık': 'Hell',
  'İzleyenler': 'Zuschauer',
  'Yorumunu yaz... (@ ile etiketle)':
      'Schreibe deinen Kommentar... (@ zum Markieren)',
  '@{} bir yorumda seni etiketledi': '@{} hat dich in einem Kommentar markiert',
  'Mesajı sil': 'Nachricht löschen',
  'Mesaj silinemedi': 'Nachricht konnte nicht gelöscht werden',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Link ist ungültig oder Seite nicht gefunden',
  'Keşfet\'e dön': 'Zurück zu Entdecken',
  'Düzenle': 'Bearbeiten',
  'Mesajı düzenle': 'Nachricht bearbeiten',
  'Yanıtlanıyor': 'Antwortet',
  'düzenlendi': 'bearbeitet',
  'Fotoğraf': 'Foto',
  'Video': 'Video',
  'İçerik': 'Inhalt',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': 'zuletzt vor {} Min.',
  'son görülme {} saat önce': 'zuletzt vor {} Std.',
  'son görülme {} gün önce': 'zuletzt vor {} T.',
  'Yorumlar yüklenemedi': 'Kommentare konnten nicht geladen werden',
  'Favori': 'Favorit',
  'Listeye ekle': 'Zur Liste hinzufügen',
  'İçerik paylaş': 'Inhalt teilen',
  'Kapat': 'Schließen',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Alles, was du als gesehen markierst, sammelt sich hier.',
  'Henüz sohbetin yok': 'Noch keine Unterhaltungen',
  'Bir profile girip mesaj gönderebilirsin.':
      'Öffne ein Profil und sende eine Nachricht.',
  'Listeyi sil': 'Liste löschen',
  'Puan kaydedilemedi': 'Bewertung konnte nicht gespeichert werden',
  'Nerede İzlenir': 'Wo streamen',
  'Abonelik': 'Abo',
  'Kirala': 'Leihen',
  'Satın al': 'Kaufen',
  'Hoş geldin!': 'Willkommen!',
  'İzlemek istediğin dizi ve filmleri seç':
      'Wähle Serien und Filme, die du sehen möchtest',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Deine Auswahl kommt auf deine Merkliste',
  'Şimdilik atla': 'Vorerst überspringen',
  'Devam et': 'Weiter',
  '{} ekle': '{} hinzufügen',
  'Şikayet et': 'Melden',
  'Engelle': 'Blockieren',
  'Engeli kaldır': 'Entsperren',
  'Kullanıcı engellendi': 'Benutzer blockiert',
  'Engel kaldırıldı': 'Blockierung aufgehoben',
  'Şikayet sebebi': 'Grund der Meldung',
  'Spam veya yanıltıcı': 'Spam oder irreführend',
  'Taciz veya nefret söylemi': 'Belästigung oder Hassrede',
  'Uygunsuz / cinsel içerik': 'Unangemessene / sexuelle Inhalte',
  'Şiddet veya tehlikeli içerik': 'Gewalt oder gefährliche Inhalte',
  'Telif hakkı ihlali': 'Urheberrechtsverletzung',
  'Şikayetin alındı, teşekkürler': 'Deine Meldung ist eingegangen, danke',
  'Hesabımı Sil': 'Konto löschen',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Dein Konto und alle deine Daten (Verlauf, Bewertungen, Kommentare, Listen, Nachrichten) werden dauerhaft gelöscht. Das kann nicht rückgängig gemacht werden.',
  'Şifreni gir': 'Gib dein Passwort ein',
  'Hesabımı kalıcı sil': 'Mein Konto endgültig löschen',
  'Sesli mesaj': 'Sprachnachricht',
  'Ses gönderilemedi': 'Sprachnachricht konnte nicht gesendet werden',
  'Kaydediliyor…': 'Aufnahme…',
  'Ses oynatılamadı': 'Sprachnachricht konnte nicht abgespielt werden',
  'Oynat': 'Abspielen',
  'Duraklat': 'Pause',
  'Liste görünümü': 'Listenansicht',
  'Takvim görünümü': 'Kalenderansicht',
  'Önceki ay': 'Voriger Monat',
  'Sonraki ay': 'Nächster Monat',
  'Bu gün bölüm yok': 'Keine Folgen an diesem Tag',
  'Gizlilik Politikası': 'Datenschutzerklärung',
  'Son güncelleme: {}': 'Zuletzt aktualisiert: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Diese Erklärung beschreibt, welche Daten erhoben werden, wie sie verwendet werden und welche Rechte du hast, wenn du die dizi.jpg-App und die Website dizijpg.com nutzt.',
  'Topladığımız Veriler': 'Welche Daten wir erheben',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Konto: E-Mail-Adresse, Benutzername und Passwort. Passwörter werden unumkehrbar gehasht gespeichert; Gastkonten können ohne E-Mail genutzt werden.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profil: Angaben, die du freiwillig hinzufügst, etwa Avatar, Titelbild, Bio und Land.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Nutzung: dein Verlauf, deine Bewertungen, Kommentare, Listen, Reaktionen und Favoriten.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Nachrichten: deine Text-, Bild- und Sprachnachrichten werden auf unseren Servern gespeichert. Nachrichten sind nicht Ende-zu-Ende-verschlüsselt; sie werden nur bei einer Meldung zu Moderationszwecken eingesehen.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Hochgeladene Medien: Fotos, GIF, Videos und Sprachaufnahmen, die du deinem Profil, deinen Kommentaren und Nachrichten hinzufügst.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Technisches: IP-Adresse, ungefährer Standort (Land/Stadt), Geräteplattform, App-Version und Fehlerprotokolle. Diese Daten dienen der Sicherheit und Fehlerbehebung.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Benachrichtigungen: für Push-Benachrichtigungen speichern wir dein Geräte-Token und deine Spracheinstellung. Du kannst Benachrichtigungen jederzeit in den Geräteeinstellungen deaktivieren.',
  'Verileri Nasıl Kullanırız': 'Wie wir deine Daten verwenden',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Wir verwenden deine Daten ausschließlich, um den Dienst bereitzustellen, dein Konto zu schützen, Benachrichtigungen zu senden, Fehler zu beheben und Missbrauch zu verhindern. Wir verkaufen deine Daten nicht und geben sie nicht zu Werbezwecken weiter.',
  'Çerezler ve Yerel Depolama': 'Cookies und lokaler Speicher',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Wir nutzen lokalen Speicher nur, um dich angemeldet zu halten und Einstellungen wie Sprache und Design zu merken. Es gibt keine Werbe- oder Tracking-Cookies.',
  'Üçüncü Taraf Hizmetler': 'Dienste von Drittanbietern',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'Serien- und Filmdaten stammen von TMDB, Streaming-Anbieter-Daten von JustWatch. Push-Benachrichtigungen werden über Google Firebase zugestellt, der Website-Verkehr wird von Cloudflare geschützt. Für diese Dienste gelten deren eigene Datenschutzerklärungen.',
  'Saklama ve Silme': 'Speicherung und Löschung',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Deine Daten werden gespeichert, solange dein Konto besteht. Über "Konto löschen" in den Einstellungen kannst du dein Konto dauerhaft löschen; deine Daten werden sofort gelöscht, Kopien in Backups spätestens nach 14 Tagen. Fehlerprotokolle werden nach 30 Tagen automatisch gelöscht.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'Du kannst deine Daten in den Einstellungen als ZIP exportieren; das Archiv wird an deine E-Mail-Adresse gesendet.',
  'Güvenlik': 'Sicherheit',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Daten werden über verschlüsselte Verbindungen (HTTPS) übertragen und auf Servern mit beschränktem Zugriff gespeichert.',
  'Çocukların Gizliliği': 'Datenschutz von Kindern',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg richtet sich nicht an Kinder unter 13 Jahren.',
  'Hakların': 'Deine Rechte',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Nach KVKK und GDPR hast du das Recht, auf deine Daten zuzugreifen, sie zu berichtigen, zu löschen und zu übertragen. Schreib uns dazu einfach: {}',
  'Değişiklikler': 'Änderungen',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Wenn sich diese Erklärung ändert, wird die neue Fassung auf dieser Seite veröffentlicht und das Aktualisierungsdatum erneuert.',
  'Kayıt olarak {} kabul etmiş olursun.':
      'Mit der Registrierung akzeptierst du die {}.',
  'Kullanıcılar': 'Nutzer',
  'Fotoğrafı değiştir': 'Foto ändern',
  'Yeniden konumlandır': 'Neu ausrichten',
  'Bir şeyler ters gitti': 'Etwas ist schiefgelaufen',
  'Sosyal Bağlantılar': 'Soziale Links',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'In deinem Profil werden bis zu 3 Links angezeigt.',
  'Platform seç': 'Plattform wählen',
  'Kullanıcı adın': 'Dein Benutzername',
  'Ekle': 'Hinzufügen',
  'Kaldır': 'Entfernen',
  'Kopyalandı: {}': 'Kopiert: {}',
  'Geçersiz kullanıcı adı': 'Ungültiger Benutzername',
  'Bağlantı ekle': 'Link hinzufügen',
  'Spoiler olabilir — dokun ve gör':
      'Kann Spoiler enthalten — zum Ansehen tippen',
  'Beğeni': 'Gefällt mir',
  'Beğen': 'Gefällt mir',
  'Görüntülenme': 'Aufrufe',
  'Tam ekran': 'Vollbild',
  'Sonuç bulunamadı': 'Keine Ergebnisse',
  'Dizi ve Filmler': 'Serien & Filme',
  'Kişiler': 'Personen',
  'Ana Sayfa': 'Startseite',
  'Paylaş': 'Teilen',
  'Yanıtlar': 'Antworten',
  'Yaklaşan Bölümler': 'Kommende Folgen',
  'Yetişme Listesi': 'Aufholliste',
  'Şunu mu demek istedin': 'Meintest du',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — zum Anzeigen tippen',
  'uyum': 'Übereinstimmung',
  'Uyum': 'Übereinstimmung',
  '{} ortak dizi': '{} gemeinsame Serien',
  '{} ortak film': '{} gemeinsame Filme',
  'Bildirim Tercihleri': 'Benachrichtigungen',
  'Beğeniler': 'Likes',
  'Yeni takipçiler': 'Neue Follower',
  'Etiketlenmeler': 'Erwähnungen',
  'Yeniden izledim': 'Erneut gesehen',
  '{}. kez izlendi': '{}-mal gesehen',
  'Gönderi bulunamadı': 'Beitrag nicht gefunden',
  'Gözat': 'Entdecken',
  'Diziler': 'Serien',
  'Filmler': 'Filme',
  'Tümü': 'Alle',
  'Farklı bir tür seç.': 'Probier ein anderes Genre.',
  'Gizlilik': 'Privatsphäre',
  'İzlediklerimi gizle': 'Gesehenes verbergen',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Serien und Filme, die du gesehen hast, werden in deinem Profil nicht angezeigt',
  'Yorumlarımı gizle': 'Meine Kommentare verbergen',
  'Profilinde yorumların görünmez':
      'Deine Kommentare werden in deinem Profil nicht angezeigt',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Eine einzelne Serie oder einen Film kannst du mit dem Chip "In meinem Profil verbergen" auf der Inhaltsseite verbergen.',
  'Geri Bildirim': 'Feedback',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Schreib deine Meinung und Vorschläge zur App...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Danke! Dein Feedback ist angekommen.',
  'Profilimde gizle': 'In meinem Profil verbergen',
  'Yorumları': 'Kommentare',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Dieser Nutzer hat noch nichts gesehen.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Dieser Nutzer hält seine Kommentare lieber privat.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Daten: JustWatch',
  'Web Sitesi': 'Website',
  'Diğer uygulamalar': 'Andere Apps',
  'Bağlantıyı kopyala': 'Link kopieren',
  'Henüz kimseyi takip etmiyorsun.': 'Du folgst noch niemandem.',
  'Çevir': 'Übersetzen',
  'Çeviri şu an yapılamadı': 'Übersetzung derzeit nicht möglich',
  'Bağlantı açılamadı': 'Link konnte nicht geöffnet werden',
  'Orijinali göster': 'Original anzeigen',
  'Çeviriyi göster': 'Übersetzung anzeigen',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Diesen Monat gibt es keine Folgen mit bekanntem Ausstrahlungsdatum. Termine werden meist wenige Wochen vorher bekannt gegeben und erscheinen dann hier.',
  'devamı': 'mehr',
  'Google ile devam et': 'Mit Google fortfahren',
  'Google girişi başarısız': 'Google-Anmeldung fehlgeschlagen',
  'Veri tasarrufu': 'Datensparmodus',
  'Wi-Fi ağında veri tasarrufu': 'Datensparmodus im WLAN',
  'Mobil veride veri tasarrufu': 'Datensparmodus bei mobilen Daten',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Wenn aktiv, werden Fotos nicht vorab geladen; nur das Bild, das du gerade ansiehst.',
  'Çocuk güvenliği': 'Kindersicherheit',
  'Türk Filmleri': 'Türkische Filme',
  'En Yüksek Puanlı Filmler': 'Bestbewertete Filme',
  'En Yüksek Puanlı Diziler': 'Bestbewertete Serien',
  'En Çok İzlenen Filmler': 'Meistgesehene Filme',
  'Popüler Diziler': 'Beliebte Serien',
  'En Çok Kazanan Filmler': 'Erfolgreichste Filme',
  'Kült Filmler': 'Kultfilme',
  'Yeni Filmler': 'Neue Filme',
  'Yorum yap': 'Kommentieren',
  'Henüz yorum yok': 'Noch keine Kommentare',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Deine Kommentare zu Serien und Filmen sammeln sich hier.',
  'GIF ekle': 'GIF hinzufügen',
  'İlk yorumu sen yaz': 'Schreibe den ersten Kommentar',
  'Video altyazıları': 'Video-Untertitel',
  'Videolarda altyazı göster': 'Untertitel für Videos anzeigen',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Der im Video gesprochene Satz wird auf den Bildschirm geschrieben. Der Text ist übersetzt: Englisch in türkischer Sprache, Türkisch in anderen Sprachen.',
  "Güncelleme gerekli": "Update erforderlich",
  "Yeni sürüm var": "Neue Version verfügbar",
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      "Installiere die neue Version von dizi.jpg, um fortzufahren.",
  "Güncelle": "Aktualisieren",
  "Daha sonra": "Später",
  'Takvim güncelleniyor': 'Kalender wird aktualisiert',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Kalender konnte nicht aktualisiert werden, alte Liste wird angezeigt',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Einige Serien konnten nicht geladen werden, die Liste ist eventuell unvollständig',
  'Yenile': 'Aktualisieren',
  'Devam etmek için giriş yap': 'Melde dich an, um fortzufahren',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Ein kostenloses Konto reicht, um zu bewerten, zu kommentieren und deine Bibliothek aufzubauen.',
  'Şimdi değil': 'Jetzt nicht',
  'Yorum yazmak için giriş yap': 'Melde dich an, um zu kommentieren',
  'Kişilere göndermek için giriş yap':
      'Melde dich an, um an Personen zu senden',
  'Beğenenler': 'Gefallt mir',
  'Henüz beğeni yok': 'Noch keine Likes',
  'Bu gönderiyi ilk beğenen sen ol': 'Sei die erste Person, der das gefallt',
};
