/// Otomatik üretilen çeviri haritası (ta).
const Map<String, String> cevirilerTa = {
  'Hepsini gördün, baştan gösteriyoruz':
      'நீங்கள் அனைத்தையும் பார்த்தீர்கள், நாங்கள் உங்களுக்கு ஆரம்பத்தில் இருந்து காட்டுகிறோம்',
  'Aktarılacak tanınan veri bulunamadı.':
      'இறக்குமதிக்கு அடையாளம் காணக்கூடிய தரவு எதுவும் கிடைக்கவில்லை.',
  'Arama': 'தேடல்',
  'Aramaya başla': 'தேடத் தொடங்கு',
  'Son aramalar': 'சமீபத்திய தேடல்கள்',
  'Ayarlar': 'அமைப்புகள்',
  'Bağla': 'இணை',
  'Bio': 'பயோ',
  'Bitirdim': 'முடித்துவிட்டேன்',
  'Bunları da Beğenebilirsin': 'இவையும் உனக்குப் பிடிக்கலாம்',
  'Bölüm': 'எபிசோட்',
  'Bıraktım': 'விட்டுவிட்டேன்',
  'Dil': 'மொழி',
  'Dil ara...': 'மொழியைத் தேடு...',
  'Dizi': 'தொடர்',
  'Dizi ve filmlerini takip et': 'உன் தொடர்களையும் படங்களையும் டிராக் செய்',
  'Dizi yorumu': 'தொடர் கருத்து',
  'Dizi, film veya kişi ara...': 'தொடர், படம் அல்லது நபரைத் தேடு...',
  'Dosya en fazla 30MB olabilir': 'கோப்பு அதிகபட்சம் 30MB ஆக இருக்கலாம்',
  'Dosya en fazla {}MB olabilir': 'கோப்பு அதிகபட்சம் {}MB ஆக இருக்கலாம்',
  'E-posta': 'மின்னஞ்சல்',
  'E-posta veya kullanıcı adı': 'மின்னஞ்சல் அல்லது பயனர்பெயர்',
  'En az 2 harf yaz': 'குறைந்தது 2 எழுத்துகள் தட்டச்சு செய்',
  'Film': 'படம்',
  'Film yorumu': 'படக் கருத்து',
  'Fotoğraf / video ekle': 'புகைப்படம் / வீடியோ சேர்',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'புகைப்படம் அல்லது GIF — சுயவிவரம் மற்றும் அட்டைப் படம்',
  'Giriş Yap': 'உள்நுழை',
  'Gönder': 'அனுப்பு',
  'Gönderildi': 'அனுப்பப்பட்டது',
  'Haftanın Dizileri': 'இந்த வார தொடர்கள்',
  'Haftanın Filmleri': 'இந்த வார படங்கள்',
  'Henüz izleme kaydın yok': 'இன்னும் பார்த்த பதிவு எதுவும் இல்லை',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'இன்னும் பட்டியல் இல்லை — சுயவிவரம் தாவலில் உருவாக்கு.',
  'Henüz yorum yok.': 'இன்னும் கருத்து இல்லை.',
  'Hesabın bağlandı!': 'உன் கணக்கு இணைக்கப்பட்டது!',
  'Hesabın yok mu? Kayıt ol': 'கணக்கு இல்லையா? பதிவு செய்',
  'Hesabını Bağla': 'உன் கணக்கை இணை',
  'Hesap Oluştur': 'கணக்கு உருவாக்கு',
  'Kapak resmi ekle': 'அட்டைப் படம் சேர்',
  'Kaydet': 'சேமி',
  'Kendinden bahset...': 'உன்னைப் பற்றி சொல்லு...',
  'Keşfet': 'கண்டறி',
  'Kimseyi takip etmiyor': 'யாரையும் பின்தொடரவில்லை',
  'Kişi ara': 'நபரைத் தேடு',
  'Kişi yorumu': 'நபர் கருத்து',
  'Konuk Oyuncular': 'விருந்தினர் நடிகர்கள்',
  'Kullanıcı adı (küçük harf)': 'பயனர்பெயர் (சிறிய எழுத்துகள்)',
  'Kullanıcı adı ara...': 'பயனர்பெயரைத் தேடு...',
  'Liste adı': 'பட்டியல் பெயர்',
  'Listeye Ekle': 'பட்டியலில் சேர்',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'நீ விருந்தினர் கணக்கில் இருக்கிறாய் — மின்னஞ்சலுடன் இணைத்து, தரவை இழக்காதே!',
  'Misafir olarak devam et': 'விருந்தினராக தொடர்',
  'Oluştur': 'உருவாக்கு',
  'Oyuncular': 'நடிகர்கள்',
  'Profil': 'சுயவிவரம்',
  'Profil kaydedildi': 'சுயவிவரம் சேமிக்கப்பட்டது',
  'Puanla': 'மதிப்பிடு',
  'Puanı Sil': 'மதிப்பீட்டை நீக்கு',
  'Puanın': 'உன் மதிப்பீடு',
  'Sezonlar': 'சீசன்கள்',
  'Sunucu hatası ({})': 'சர்வர் பிழை ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'S{}E{} கருத்து',
  'Takibi Bırak': 'பின்தொடர்வதை நிறுத்து',
  'Takip': 'பின்தொடர்தல்',
  'Takip Edilenler': 'பின்தொடரப்படுபவர்கள்',
  'Takip Et': 'பின்தொடர்',
  'Takipçi': 'பின்தொடர்பவர்',
  'Takipçi yok': 'பின்தொடர்பவர்கள் இல்லை',
  'Takipçiler': 'பின்தொடர்பவர்கள்',
  'Takvim': 'நாட்காட்டி',
  'Tamam': 'சரி',
  'Tekrar Dene': 'மீண்டும் முயற்சி',
  'Tekrar dene': 'மீண்டும் முயற்சி செய்',
  'Toplam İzleme Süresi': 'மொத்த திரை நேரம்',
  'Tüm Zamanların En İyileri': 'எல்லா காலத்திலும் சிறந்தவை',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'உன் எல்லா தரவையும் (பார்த்தவை, மதிப்பீடுகள், கருத்துகள், பட்டியல்கள்) TV Time இணக்கமான ZIP ஆக பதிவிறக்கு அல்லது வேறு ஆப்பிலிருந்து வந்த ZIP ஐ இறக்குமதி செய்.',
  'Tümünü Kaldır': 'அனைத்தையும் நீக்கு',
  'Tümünü İzledim': 'அனைத்தையும் பார்த்துவிட்டேன்',
  'Türk Dizileri': 'துருக்கிய தொடர்கள்',
  'Veri içe aktar (.zip)': 'தரவு இறக்குமதி (.zip)',
  'Verilerim': 'என் தரவு',
  'Verilerimi dışa aktar (e-posta)': 'என் தரவை ஏற்றுமதி செய் (மின்னஞ்சல்)',
  'Verilerini dışa aktar': 'உன் தரவை ஏற்றுமதி செய்',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'வரவிருக்கும் எபிசோட் இல்லை.\nதொடர் விவரத்தில் "பார்க்கிறேன்" நிலைக்கு மாற்று, புதிய எபிசோட்களை இங்கே பின்தொடர்.',
  'Yapımları': 'படைப்புகள்',
  'Yeni Diziler': 'புதிய தொடர்கள்',
  'Yeni Liste': 'புதிய பட்டியல்',
  'Yeni kullanıcı adı (isteğe bağlı)': 'புதிய பயனர்பெயர் (விருப்பத்தேர்வு)',
  'Yorum': 'கருத்து',
  'Yorumunu yaz...': 'உன் கருத்தை எழுது...',
  'Zaten hesabın var mı? Giriş yap': 'ஏற்கனவே கணக்கு இருக்கிறதா? உள்நுழை',
  'ort. {}': 'சரா. {}',
  'takip': 'பின்தொடர்தல்',
  'takipçi': 'பின்தொடர்பவர்',
  '{} / {} bölüm': '{} / {} எபிசோட்',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} மாதம்',
  '{} bölüm izlendi': '{} எபிசோட் பார்க்கப்பட்டது',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} நிமி',
  '{} gün': '{} நாள்',
  '{} içerik': '{} உள்ளடக்கம்',
  '{} içerik · otomatik': '{} உள்ளடக்கம் · தானியங்கி',
  '{} kayıt atlandı (eşleşmedi).': '{} பதிவு தவிர்க்கப்பட்டது (பொருந்தவில்லை).',
  '{} saat': '{} மணிநேரம்',
  '{} sezon': '{} சீசன்',
  '{} yıl': '{} ஆண்டு',
  '{}. Bölüm': 'எபிசோட் {}',
  '{}. Sezon': 'சீசன் {}',
  'Çıkış Yap': 'வெளியேறு',
  'Ülke': 'நாடு',
  'Ülke ara...': 'நாட்டைத் தேடு...',
  'Ülke seç': 'நாட்டைத் தேர்ந்தெடு',
  'İlk yorumu sen yaz!': 'முதல் கருத்தை நீயே எழுது!',
  'İncelemeler': 'விமர்சனங்கள்',
  'İncelemen (isteğe bağlı)': 'உன் விமர்சனம் (விருப்பத்தேர்வு)',
  'İptal': 'ரத்து',
  'İzlediklerim': 'நான் பார்த்தவை',
  'İzledim': 'பார்த்துவிட்டேன்',
  'İzledin': 'பார்த்தாய்',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'உன் பார்வை வரலாறும் பட்டியல்களும் பாதுகாக்கப்படும்; இனி எந்த சாதனத்திலிருந்தும் உள்நுழையலாம்.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'உன் பார்வை வரலாறு, மதிப்பீடுகள், கருத்துகள் மற்றும் பட்டியல்கள் ZIP ஆக பதிவு செய்யப்பட்ட மின்னஞ்சல் முகவரிக்கு அனுப்பப்படும்.',
  'İzleyeceğim': 'பார்க்கப் போகிறேன்',
  'İzliyorum': 'பார்க்கிறேன்',
  'İçe aktarım tamamlandı': 'இறக்குமதி முடிந்தது',
  'Şifre': 'கடவுச்சொல்',
  '• profil bilgisi': '• சுயவிவரத் தகவல்',
  '• {} dizi durumu': '• {} தொடர் நிலை',
  '• {} izleme kaydı': '• {} பார்வை பதிவு',
  '• {} liste': '• {} பட்டியல்',
  '• {} puan': '• {} மதிப்பீடு',
  '• {} yorum': '• {} கருத்து',
  '{}+ yapım': '{}+ படைப்புகள்',
  'Yorumlar': 'கருத்துகள்',
  'Yorumlar ({})': 'கருத்துகள் ({})',
  'Yorumları ({})': 'கருத்துகள் ({})',
  'Listelerim': 'என் பட்டியல்கள்',
  'Nereden izledin?': 'எங்கே பார்த்தாய்?',
  'Diziye git': 'தொடருக்குச் செல்',
  'TV / Kanal': 'டிவி / சேனல்',
  'Sinema': 'திரையரங்கு',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'மற்றவை',
  'Akış': 'ஃபீட்',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'உன் ஃபீட் காலியாக உள்ளது.\nநீ பார்க்கும் தொடர்கள்/படங்களில் கருத்துகள் வந்ததும் இங்கே தோன்றும்.',
  'Listeleri ({})': 'அவர்களின் பட்டியல்கள் ({})',
  'Liste boş.': 'இந்தப் பட்டியல் காலியாக உள்ளது.',
  'Yanıtla': 'பதிலளி',
  '@{} kullanıcısına yanıt veriyorsun': '@{}க்கு பதிலளிக்கிறாய்',
  'İzlediğim Diziler ({})': 'நான் பார்த்த தொடர்கள் ({})',
  'İzlediğim Filmler ({})': 'நான் பார்த்த படங்கள் ({})',
  'Tümünü gör': 'அனைத்தையும் காண்க',
  'Bildirimler': 'அறிவிப்புகள்',
  'Henüz bildirim yok': 'இன்னும் அறிவிப்புகள் இல்லை',
  '@{} yorumuna yanıt verdi': '@{} உன் கருத்துக்கு பதிலளித்தார்',
  '@{} yorumunu beğendi': '@{} உன் கருத்தை விரும்பினார்',
  '@{} seni takip etti': '@{} உன்னை பின்தொடர்ந்தார்',
  '@{} sana mesaj gönderdi': '@{} உனக்கு செய்தி அனுப்பினார்',
  'Mesajlar': 'செய்திகள்',
  'Mesaj': 'செய்தி',
  'Mesajını yaz...': 'செய்தி எழுது...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'இன்னும் உரையாடல்கள் இல்லை.\nஒரு சுயவிவரம் திறந்து செய்தி அனுப்பு.',
  'Şifreni mi unuttun?': 'கடவுச்சொல் மறந்ததா?',
  'Şifreyi Sıfırla': 'கடவுச்சொல் மீட்டமை',
  'E-postadaki kod': 'மின்னஞ்சலில் உள்ள குறியீடு',
  'Yeni şifre': 'புதிய கடவுச்சொல்',
  'Sana Özel': 'உனக்காக',
  '{} özetin': 'உன் {} தொகுப்பு',
  'Yıllık izleme istatistiklerin': 'ஆண்டு பார்வை புள்ளிவிவரங்கள்',
  'Rozetler': 'பேட்ஜ்கள்',
  'Verdiğin puan': 'கொடுத்த மதிப்பீடுகள்',
  'Ortalama puanın': 'சராசரி மதிப்பீடு',
  'En çok izlediğin diziler': 'அதிகம் பார்த்த தொடர்கள்',
  'İlk Bölüm': 'முதல் அத்தியாயம்',
  '100 Bölüm': '100 அத்தியாயங்கள்',
  '1000 Bölüm': '1000 அத்தியாயங்கள்',
  'İlk Film': 'முதல் படம்',
  '50 Film': '50 படங்கள்',
  'İlk Yorum': 'முதல் கருத்து',
  '25 Yorum': '25 கருத்துகள்',
  '10 Puan': '10 மதிப்பீடுகள்',
  'İlk Takipçi': 'முதல் பின்தொடர்பவர்',
  '10 Dizi Bitirdin': '10 தொடர்கள் நிறைவு',
  'İzlemeyi Bıraktım': 'பார்ப்பதை நிறுத்தினேன்',
  'İzlediği Diziler ({})': 'அவர் பார்த்த தொடர்கள் ({})',
  'İzlediği Filmler ({})': 'அவர் பார்த்த படங்கள் ({})',
  '500 Bölüm': '500 அத்தியாயங்கள்',
  '5000 Bölüm': '5000 அத்தியாயங்கள்',
  '10 Film': '10 படங்கள்',
  '100 Film': '100 படங்கள்',
  '100 Yorum': '100 கருத்துகள்',
  '50 Puan': '50 மதிப்பீடுகள்',
  '100 Puan': '100 மதிப்பீடுகள்',
  '10 Takipçi': '10 பின்தொடர்பவர்கள்',
  '50 Takipçi': '50 பின்தொடர்பவர்கள்',
  '25 Dizi Bitirdin': '25 தொடர்கள் நிறைவு',
  '50 Dizi Bitirdin': '50 தொடர்கள் நிறைவு',
  '10 Beğeni': '10 விருப்பங்கள்',
  '100 Beğeni': '100 விருப்பங்கள்',
  'yazıyor...': 'தட்டச்சு செய்கிறார்...',
  'Profil düzeni': 'சுயவிவர அமைப்பு',
  'Konumla ve kırp': 'நிலைப்படுத்தி வெட்டு',
  'Listeye eklendi': 'பட்டியலில் சேர்க்கப்பட்டது',
  'Listeyi sil?': 'பட்டியலை நீக்கவா?',
  'Sil': 'நீக்கு',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'இது பார்க்கப்படாததாகக் குறிக்கப்பட்டு உன் பட்டியல்களிலிருந்து நீக்கப்படும்.',
  'Gelecek bölüm bugün': 'அடுத்த அத்தியாயம் இன்று',
  'Gelecek bölüm {} gün sonra': 'அடுத்த அத்தியாயம் {} நாட்களில்',
  'Tema': 'தீம்',
  'Sistem': 'சிஸ்டம்',
  'Koyu': 'டார்க்',
  'Açık': 'லைட்',
  'İzleyenler': 'பார்வையாளர்கள்',
  'Yorumunu yaz... (@ ile etiketle)':
      'உன் கருத்தை எழுது... (@ போட்டு டேக் செய்)',
  '@{} bir yorumda seni etiketledi': '@{} உன்னை ஒரு கருத்தில் குறியிட்டார்',
  'Mesajı sil': 'செய்தியை நீக்கு',
  'Mesaj silinemedi': 'செய்தியை நீக்க முடியவில்லை',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'இணைப்பு தவறானது அல்லது பக்கம் கிடைக்கவில்லை',
  'Keşfet\'e dön': 'கண்டறிதலுக்குத் திரும்பு',
  'Düzenle': 'திருத்து',
  'Mesajı düzenle': 'செய்தியைத் திருத்து',
  'Yanıtlanıyor': 'பதிலளிக்கிறது',
  'düzenlendi': 'திருத்தப்பட்டது',
  'Fotoğraf': 'புகைப்படம்',
  'Video': 'வீடியோ',
  'İçerik': 'உள்ளடக்கம்',
  'çevrimiçi': 'ஆன்லைன்',
  'son görülme {} dk önce': 'கடைசியாக {} நிமிடம் முன்',
  'son görülme {} saat önce': 'கடைசியாக {} மணி முன்',
  'son görülme {} gün önce': 'கடைசியாக {} நாள் முன்',
  'Yorumlar yüklenemedi': 'கருத்துகளை ஏற்ற முடியவில்லை',
  'Favori': 'பிடித்தவை',
  'Listeye ekle': 'பட்டியலில் சேர்',
  'İçerik paylaş': 'பகிர்',
  'Kapat': 'மூடு',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'பார்த்ததாகக் குறிப்பவை இங்கே சேரும்.',
  'Henüz sohbetin yok': 'இன்னும் உரையாடல்கள் இல்லை',
  'Bir profile girip mesaj gönderebilirsin.':
      'சுயவிவரத்தைத் திறந்து செய்தி அனுப்பவும்.',
  'Listeyi sil': 'பட்டியலை நீக்கு',
  'Puan kaydedilemedi': 'மதிப்பீட்டைச் சேமிக்க முடியவில்லை',
  'Nerede İzlenir': 'எங்கு பார்க்கலாம்',
  'Abonelik': 'சந்தா',
  'Kirala': 'வாடகைக்கு',
  'Satın al': 'வாங்கு',
  'Hoş geldin!': 'வரவேற்கிறோம்!',
  'İzlemek istediğin dizi ve filmleri seç':
      'நீ பார்க்க விரும்பும் தொடர்களையும் படங்களையும் தேர்ந்தெடு',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'உன் தேர்வுகள் "பார்க்கப் போகிறேன்" பட்டியலில் சேர்க்கப்படும்',
  'Şimdilik atla': 'இப்போதைக்கு தவிர்',
  'Devam et': 'தொடரவும்',
  '{} ekle': '{} சேர்',
  'Şikayet et': 'புகார் செய்',
  'Engelle': 'தடு',
  'Engeli kaldır': 'தடையை நீக்கு',
  'Kullanıcı engellendi': 'பயனர் தடுக்கப்பட்டார்',
  'Engel kaldırıldı': 'தடை நீக்கப்பட்டது',
  'Şikayet sebebi': 'புகார் காரணம்',
  'Spam veya yanıltıcı': 'ஸ்பேம் அல்லது தவறான தகவல்',
  'Taciz veya nefret söylemi': 'துன்புறுத்தல் அல்லது வெறுப்புப் பேச்சு',
  'Uygunsuz / cinsel içerik': 'பொருத்தமற்ற / பாலியல் உள்ளடக்கம்',
  'Şiddet veya tehlikeli içerik': 'வன்முறை அல்லது ஆபத்தான உள்ளடக்கம்',
  'Telif hakkı ihlali': 'பதிப்புரிமை மீறல்',
  'Şikayetin alındı, teşekkürler': 'உன் புகார் பெறப்பட்டது, நன்றி',
  'Hesabımı Sil': 'என் கணக்கை நீக்கு',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'உன் கணக்கும் எல்லா தரவும் (வரலாறு, மதிப்பீடுகள், கருத்துகள், பட்டியல்கள், செய்திகள்) நிரந்தரமாக நீக்கப்படும். இதை மீட்க முடியாது.',
  'Şifreni gir': 'உன் கடவுச்சொல்லை உள்ளிடு',
  'Hesabımı kalıcı sil': 'என் கணக்கை நிரந்தரமாக நீக்கு',
  'Sesli mesaj': 'குரல் செய்தி',
  'Ses gönderilemedi': 'குரல் செய்தியை அனுப்ப முடியவில்லை',
  'Kaydediliyor…': 'பதிவாகிறது…',
  'Ses oynatılamadı': 'ஆடியோவை இயக்க முடியவில்லை',
  'Oynat': 'இயக்கு',
  'Duraklat': 'இடைநிறுத்து',
  'Liste görünümü': 'பட்டியல் காட்சி',
  'Takvim görünümü': 'நாட்காட்டி காட்சி',
  'Önceki ay': 'முந்தைய மாதம்',
  'Sonraki ay': 'அடுத்த மாதம்',
  'Bu gün bölüm yok': 'இந்த நாளில் அத்தியாயம் இல்லை',
  'Gizlilik Politikası': 'தனியுரிமைக் கொள்கை',
  'Son güncelleme: {}': 'கடைசி புதுப்பிப்பு: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'dizi.jpg செயலியையும் dizijpg.com தளத்தையும் பயன்படுத்தும்போது என்ன தரவு சேகரிக்கப்படுகிறது, எப்படிப் பயன்படுத்தப்படுகிறது, உன் உரிமைகள் என்ன என்பதை இந்தக் கொள்கை விளக்குகிறது.',
  'Topladığımız Veriler': 'நாங்கள் சேகரிக்கும் தரவு',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'கணக்கு: மின்னஞ்சல் முகவரி, பயனர்பெயர், கடவுச்சொல். கடவுச்சொற்கள் மீட்க முடியாத ஹாஷாகச் சேமிக்கப்படுகின்றன; விருந்தினர் கணக்குகளை மின்னஞ்சல் இல்லாமல் பயன்படுத்தலாம்.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'சுயவிவரம்: அவதாரம், அட்டைப் படம், பயோ, நாடு போன்ற நீ சேர்க்கத் தேர்வு செய்யும் தகவல்கள்.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'பயன்பாடு: உன் பார்வை வரலாறு, மதிப்பீடுகள், கருத்துகள், பட்டியல்கள், ரியாக்ஷன்கள், பிடித்தவை.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'செய்திகள்: உன் உரை, படம், குரல் செய்திகள் எங்கள் சர்வர்களில் சேமிக்கப்படுகின்றன. செய்திகள் முனைக்கு-முனை என்க்ரிப்ட் செய்யப்படவில்லை; புகார் வந்தால் மட்டுமே மதிப்பாய்வுக்காகப் பார்க்கப்படும்.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'பதிவேற்றிய மீடியா: சுயவிவரம், கருத்துகள், செய்திகளில் நீ சேர்க்கும் புகைப்படங்கள், GIF, வீடியோக்கள், குரல் பதிவுகள்.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'தொழில்நுட்பம்: IP முகவரி, தோராயமான இடம் (நாடு/நகரம் அளவில்), சாதன இயங்குதளம், செயலி பதிப்பு, பிழைப் பதிவுகள். இவை பாதுகாப்புக்கும் பிழை சரிசெய்யவும் வைக்கப்படுகின்றன.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'அறிவிப்புகள்: புஷ் அறிவிப்புகளுக்காக உன் சாதன டோக்கனும் மொழித் தேர்வும் சேமிக்கப்படுகின்றன. சாதன அமைப்புகளில் எப்போது வேண்டுமானாலும் அறிவிப்புகளை அணைக்கலாம்.',
  'Verileri Nasıl Kullanırız': 'தரவை எப்படிப் பயன்படுத்துகிறோம்',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'உன் தரவை சேவை வழங்க, கணக்கைப் பாதுகாக்க, அறிவிப்பு அனுப்ப, பிழைகளைச் சரிசெய்ய, தவறான பயன்பாட்டைத் தடுக்க மட்டுமே பயன்படுத்துகிறோம். உன் தரவை விற்பதில்லை; விளம்பரத்துக்காக யாருடனும் பகிர்வதில்லை.',
  'Çerezler ve Yerel Depolama': 'குக்கீகளும் லோக்கல் ஸ்டோரேஜும்',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'உன்னை உள்நுழைந்த நிலையில் வைக்கவும் மொழி/தீம் போன்ற விருப்பங்களை நினைவில் வைக்கவும் மட்டுமே லோக்கல் ஸ்டோரேஜ் பயன்படுகிறது. விளம்பர அல்லது கண்காணிப்பு குக்கீகள் இல்லை.',
  'Üçüncü Taraf Hizmetler': 'மூன்றாம் தரப்பு சேவைகள்',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'தொடர்கள், படங்களின் தரவு TMDB-யிலிருந்தும், ஸ்ட்ரீமிங் தள விவரம் JustWatch-இலிருந்தும் வருகிறது. புஷ் அறிவிப்புகள் Google Firebase வழியாக அனுப்பப்படுகின்றன; தள ட்ராஃபிக்கை Cloudflare பாதுகாக்கிறது. இந்தச் சேவைகளுக்கு அவற்றின் சொந்த தனியுரிமைக் கொள்கைகள் பொருந்தும்.',
  'Saklama ve Silme': 'சேமிப்பும் நீக்கமும்',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'உன் கணக்கு இருக்கும் வரை உன் தரவு இருக்கும். அமைப்புகளில் உள்ள "என் கணக்கை நீக்கு" மூலம் கணக்கை நிரந்தரமாக நீக்கலாம்; தரவு உடனே அழிக்கப்படும், பேக்அப்பில் உள்ள நகல்கள் அதிகபட்சம் 14 நாட்களில் அழியும். பிழைப் பதிவுகள் 30 நாட்களுக்குப் பிறகு தானாக அழிக்கப்படும்.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'அமைப்புகளிலிருந்து உன் தரவை ZIP ஆக ஏற்றுமதி செய்யலாம்; காப்பகம் உன் மின்னஞ்சல் முகவரிக்கு அனுப்பப்படும்.',
  'Güvenlik': 'பாதுகாப்பு',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'தரவு என்க்ரிப்ட் செய்யப்பட்ட இணைப்புகள் (HTTPS) வழியாகச் செல்கிறது; வரம்புள்ள அணுகல் கொண்ட சர்வர்களில் சேமிக்கப்படுகிறது.',
  'Çocukların Gizliliği': 'குழந்தைகளின் தனியுரிமை',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg 13 வயதுக்குக் குறைவான குழந்தைகளுக்கானது அல்ல.',
  'Hakların': 'உன் உரிமைகள்',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK மற்றும் GDPR படி உன் தரவை அணுக, திருத்த, நீக்க, மாற்ற உனக்கு உரிமை உண்டு. இதற்காக எங்களுக்கு எழுது: {}',
  'Değişiklikler': 'மாற்றங்கள்',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'இந்தக் கொள்கை மாறினால் புதிய பதிப்பு இதே பக்கத்தில் வெளியிடப்பட்டு தேதி புதுப்பிக்கப்படும்.',
  'Kayıt olarak {} kabul etmiş olursun.':
      'பதிவு செய்வதன் மூலம் {} ஏற்றுக்கொள்கிறாய்.',
  'Kullanıcılar': 'பயனர்கள்',
  'Fotoğrafı değiştir': 'புகைப்படத்தை மாற்று',
  'Yeniden konumlandır': 'மீண்டும் பொருத்து',
  'Bir şeyler ters gitti': 'ஏதோ தவறு நடந்தது',
  'Sosyal Bağlantılar': 'சமூக இணைப்புகள்',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'உன் சுயவிவரத்தில் அதிகபட்சம் 3 இணைப்புகள் காட்டப்படும்.',
  'Platform seç': 'தளத்தைத் தேர்வு செய்',
  'Kullanıcı adın': 'உன் பயனர்பெயர்',
  'Ekle': 'சேர்',
  'Kaldır': 'நீக்கு',
  'Kopyalandı: {}': 'நகலெடுக்கப்பட்டது: {}',
  'Geçersiz kullanıcı adı': 'தவறான பயனர்பெயர்',
  'Bağlantı ekle': 'இணைப்பைச் சேர்',
  'Spoiler olabilir — dokun ve gör': 'ஸ்பாய்லர் இருக்கலாம் — பார்க்கத் தட்டு',
  'Beğeni': 'லைக்குகள்',
  'Görüntülenme': 'பார்வைகள்',
  'Tam ekran': 'முழுத்திரை',
  'Sonuç bulunamadı': 'முடிவுகள் இல்லை',
  'Dizi ve Filmler': 'தொடர்கள் & படங்கள்',
  'Kişiler': 'நபர்கள்',
  'Ana Sayfa': 'முகப்பு',
  'Paylaş': 'பகிர்',
  'Yanıtlar': 'பதில்கள்',
  'Yaklaşan Bölümler': 'வரவிருக்கும் எபிசோட்கள்',
  'Yetişme Listesi': 'கேட்ச்-அப் பட்டியல்',
  'Şunu mu demek istedin': 'நீங்கள் சொன்னது',
  'Spoiler': 'ஸ்பாய்லர்',
  'Spoiler — dokun ve gör': 'ஸ்பாய்லர் — பார்க்க தட்டவும்',
  'uyum': 'பொருத்தம்',
  'Uyum': 'பொருத்தம்',
  '{} ortak dizi': '{} பொதுவான தொடர்கள்',
  '{} ortak film': '{} பொதுவான படங்கள்',
  'Bildirim Tercihleri': 'அறிவிப்பு விருப்பங்கள்',
  'Beğeniler': 'விருப்பங்கள்',
  'Yeni takipçiler': 'புதிய பின்தொடர்பவர்கள்',
  'Etiketlenmeler': 'குறிப்புகள்',
  'Yeniden izledim': 'மீண்டும் பார்த்தது',
  '{}. kez izlendi': '{} முறை பார்த்தது',
  'Gönderi bulunamadı': 'இடுகை கிடைக்கவில்லை',
  'Gözat': 'உலாவு',
  'Diziler': 'தொடர்கள்',
  'Filmler': 'படங்கள்',
  'Tümü': 'அனைத்தும்',
  'Farklı bir tür seç.': 'வேறு வகையை முயற்சி செய்.',
  'Gizlilik': 'தனியுரிமை',
  'İzlediklerimi gizle': 'நான் பார்த்தவற்றை மறை',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'நீ பார்த்த தொடர்களும் படங்களும் உன் சுயவிவரத்தில் தெரியாது',
  'Yorumlarımı gizle': 'என் கருத்துகளை மறை',
  'Profilinde yorumların görünmez': 'உன் கருத்துகள் உன் சுயவிவரத்தில் தெரியாது',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'ஒரு குறிப்பிட்ட தொடரையோ படத்தையோ அதன் பக்கத்தில் உள்ள "என் சுயவிவரத்தில் மறை" சிப் மூலம் மறைக்கலாம்.',
  'Geri Bildirim': 'பின்னூட்டம்',
  'Uygulama hakkında görüş ve önerini yaz...':
      'செயலி பற்றிய உன் கருத்தையும் பரிந்துரைகளையும் எழுது...',
  'Teşekkürler! Geri bildirimin alındı.': 'நன்றி! உன் பின்னூட்டம் கிடைத்தது.',
  'Profilimde gizle': 'என் சுயவிவரத்தில் மறை',
  'Yorumları': 'கருத்துகள்',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'இந்தப் பயனர் இதுவரை எதையும் பார்க்கவில்லை.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'இந்தப் பயனர் தன் கருத்துகளை மறைத்து வைக்க விரும்புகிறார்.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'தரவு: JustWatch',
  'Web Sitesi': 'இணையதளம்',
  'Diğer uygulamalar': 'மற்ற ஆப்ஸ்',
  'Bağlantıyı kopyala': 'இணைப்பை நகலெடு',
  'Henüz kimseyi takip etmiyorsun.': 'இன்னும் யாரையும் பின்தொடரவில்லை.',
  'Çevir': 'மொழிபெயர்',
  'Çeviri şu an yapılamadı': 'இப்போது மொழிபெயர்ப்பு இயலவில்லை',
  'Bağlantı açılamadı': 'இணைப்பைத் திறக்க முடியவில்லை',
  'Orijinali göster': 'மூலத்தைக் காட்டு',
  'Çeviriyi göster': 'மொழிபெயர்ப்பைக் காட்டு',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'இந்த மாதம் ஒளிபரப்புத் தேதி அறிவிக்கப்பட்ட எபிசோடு இல்லை. தேதிகள் பொதுவாக சில வாரங்களுக்கு முன் அறிவிக்கப்படும், பிறகு இங்கே தெரியும்.',
  'devamı': 'மேலும்',
  'Google ile devam et': 'Google மூலம் தொடரவும்',
  'Google girişi başarısız': 'Google உள்நுழைவு தோல்வியடைந்தது',
  'Veri tasarrufu': 'தரவு சேமிப்பு',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi இல் தரவு சேமிப்பு',
  'Mobil veride veri tasarrufu': 'மொபைல் தரவில் தரவு சேமிப்பு',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'இயக்கத்தில் இருக்கும்போது படங்கள் முன்கூட்டியே பதிவிறக்கப்படாது, நீ பார்க்கும் படம் மட்டுமே ஏற்றப்படும்.',
  'Çocuk güvenliği': 'குழந்தைப் பாதுகாப்பு',
  'Türk Filmleri': 'துருக்கிய திரைப்படங்கள்',
  'En Yüksek Puanlı Filmler': 'அதிக மதிப்பீடு பெற்ற படங்கள்',
  'En Yüksek Puanlı Diziler': 'அதிக மதிப்பீடு பெற்ற தொடர்கள்',
  'En Çok İzlenen Filmler': 'அதிகம் பார்க்கப்பட்ட படங்கள்',
  'Popüler Diziler': 'பிரபல தொடர்கள்',
  'En Çok Kazanan Filmler': 'அதிக வருவாய் ஈட்டிய படங்கள்',
  'Kült Filmler': 'வழிபாட்டுப் படங்கள்',
  'Yeni Filmler': 'புதிய படங்கள்',
  'Yorum yap': 'கருத்து சொல்',
  'Henüz yorum yok': 'இன்னும் கருத்துகள் இல்லை',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'தொடர்கள் மற்றும் படங்களுக்கு நீ எழுதும் கருத்துகள் இங்கே சேரும்.',
  'GIF ekle': 'GIF சேர்க்கவும்',
  'İlk yorumu sen yaz': 'முதல் கருத்தை நீங்கள் எழுதுங்கள்',
  'Video altyazıları': 'வீடியோ வசனங்கள்',
  'Videolarda altyazı göster': 'வீடியோக்களில் வசனங்களைக் காட்டு',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'வீடியோவில் பேசப்படும் வாக்கியம் திரையில் எழுதப்பட்டுள்ளது. உரை மொழிபெயர்ப்பு: துருக்கிய பேச்சில் ஆங்கிலம், மற்ற மொழிகளில் துருக்கியம்.',
  "Güncelleme gerekli": "புதுப்பிப்பு தேவை",
  "Yeni sürüm var": "புதிய பதிப்பு கிடைக்கிறது",
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      "தொடர dizi.jpg இன் புதிய பதிப்பை நிறுவவும்.",
  "Güncelle": "புதுப்பிக்கவும்",
  "Daha sonra": "பிறகு",
};
