/// Otomatik üretilen çeviri haritası (da).
const Map<String, String> cevirilerDa = {
  'Aktarılacak tanınan veri bulunamadı.': 'Ingen genkendte data at importere.',
  'Arama': 'Søg',
  'Aramaya başla': 'Begynd at søge',
  'Ayarlar': 'Indstillinger',
  'Bağla': 'Tilknyt',
  'Bio': 'Bio',
  'Bitirdim': 'Set færdig',
  'Bunları da Beğenebilirsin': 'Du vil måske også kunne lide disse',
  'Bölüm': 'Afsnit',
  'Bıraktım': 'Droppet',
  'Dil': 'Sprog',
  'Dil ara...': 'Søg sprog...',
  'Dizi': 'Serie',
  'Dizi ve filmlerini takip et': 'Følg dine serier og film',
  'Dizi yorumu': 'Seriekommentar',
  'Dizi, film veya kişi ara...': 'Søg efter serie, film eller person...',
  'Dosya en fazla 30MB olabilir': 'Filen må højst være 30MB',
  'Dosya en fazla {}MB olabilir': 'Filen må højst være {}MB',
  'E-posta': 'E-mail',
  'E-posta veya kullanıcı adı': 'E-mail eller brugernavn',
  'En az 2 harf yaz': 'Skriv mindst 2 bogstaver',
  'Film': 'Film',
  'Film yorumu': 'Filmkommentar',
  'Fotoğraf / video ekle': 'Tilføj foto / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto eller GIF — profil- og coverbillede',
  'Giriş Yap': 'Log ind',
  'Gönder': 'Send',
  'Gönderildi': 'Sendt',
  'Haftanın Dizileri': 'Ugens serier',
  'Haftanın Filmleri': 'Ugens film',
  'Henüz izleme kaydın yok': 'Du har ingen visningshistorik endnu',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Du har ingen lister endnu — opret en fra Profil-fanen.',
  'Henüz yorum yok.': 'Ingen kommentarer endnu.',
  'Hesabın bağlandı!': 'Din konto er tilknyttet!',
  'Hesabın yok mu? Kayıt ol': 'Har du ikke en konto? Tilmeld dig',
  'Hesabını Bağla': 'Tilknyt din konto',
  'Hesap Oluştur': 'Opret konto',
  'Kapak resmi ekle': 'Tilføj coverbillede',
  'Kaydet': 'Gem',
  'Kendinden bahset...': 'Fortæl om dig selv...',
  'Keşfet': 'Udforsk',
  'Kimseyi takip etmiyor': 'Følger ingen',
  'Kişi ara': 'Søg person',
  'Kişi yorumu': 'Personkommentar',
  'Konuk Oyuncular': 'Gæsteskuespillere',
  'Kullanıcı adı (küçük harf)': 'Brugernavn (små bogstaver)',
  'Kullanıcı adı ara...': 'Søg brugernavn...',
  'Liste adı': 'Listenavn',
  'Listeye Ekle': 'Føj til liste',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Du bruger en gæstekonto — tilknyt din e-mail, så du ikke mister dine data!',
  'Misafir olarak devam et': 'Fortsæt som gæst',
  'Oluştur': 'Opret',
  'Oyuncular': 'Medvirkende',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil gemt',
  'Puanla': 'Bedøm',
  'Puanı Sil': 'Slet bedømmelse',
  'Puanın': 'Din bedømmelse',
  'Sezonlar': 'Sæsoner',
  'Sunucu hatası ({})': 'Serverfejl ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Kommentar til S{}E{}',
  'Takibi Bırak': 'Stop med at følge',
  'Takip': 'Følger',
  'Takip Edilenler': 'Følger',
  'Takip Et': 'Følg',
  'Takipçi': 'Følgere',
  'Takipçi yok': 'Ingen følgere',
  'Takipçiler': 'Følgere',
  'Takvim': 'Kalender',
  'Tamam': 'OK',
  'Tekrar Dene': 'Prøv igen',
  'Tekrar dene': 'Prøv igen',
  'Toplam ekran süresi': 'Samlet skærmtid',
  'Tüm Zamanların En İyileri': 'De bedste nogensinde',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Eksportér alle dine data (historik, bedømmelser, kommentarer, lister) som en TV Time-kompatibel ZIP, eller importér en ZIP fra en anden app.',
  'Tümünü Kaldır': 'Fjern alle',
  'Tümünü İzledim': 'Har set alle',
  'Türk Dizileri': 'Tyrkiske serier',
  'Veri içe aktar (.zip)': 'Importér data (.zip)',
  'Verilerim': 'Mine data',
  'Verilerimi dışa aktar (e-posta)': 'Eksportér mine data (e-mail)',
  'Verilerini dışa aktar': 'Eksportér dine data',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Ingen kommende afsnit.\nSæt en serie til "Ser" fra seriesiden, og følg nye afsnit her.',
  'Yapımları': 'Filmografi',
  'Yeni Diziler': 'Nye serier',
  'Yeni Liste': 'Ny liste',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nyt brugernavn (valgfrit)',
  'Yorum': 'Kommentar',
  'Yorumunu yaz...': 'Skriv din kommentar...',
  'Zaten hesabın var mı? Giriş yap': 'Har du allerede en konto? Log ind',
  'ort. {}': 'gns. {}',
  'takip': 'følger',
  'takipçi': 'følgere',
  '{} / {} bölüm': '{} / {} afsnit',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} mdr.',
  '{} bölüm izlendi': '{} afsnit set',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min.',
  '{} gün': '{} d.',
  '{} içerik': '{} titler',
  '{} içerik · otomatik': '{} titler · automatisk',
  '{} kayıt atlandı (eşleşmedi).': '{} poster sprunget over (intet match).',
  '{} saat': '{} t.',
  '{} sezon': '{} sæsoner',
  '{} yıl': '{} år',
  '{}. Bölüm': 'Afsnit {}',
  '{}. Sezon': 'Sæson {}',
  'Çıkış Yap': 'Log ud',
  'Ülke': 'Land',
  'Ülke ara...': 'Søg land...',
  'Ülke seç': 'Vælg land',
  'İlk yorumu sen yaz!': 'Skriv den første kommentar!',
  'İncelemeler': 'Anmeldelser',
  'İncelemen (isteğe bağlı)': 'Din anmeldelse (valgfri)',
  'İptal': 'Annuller',
  'İzlediklerim': 'Min visningshistorik',
  'İzledim': 'Set',
  'İzledin': 'Set',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Din visningshistorik og dine lister bevares; du kan nu logge ind fra alle enheder.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Din visningshistorik, dine bedømmelser, kommentarer og lister sendes som ZIP til din registrerede e-mailadresse.',
  'İzleyeceğim': 'Vil se',
  'İzliyorum': 'Ser',
  'İçe aktarım tamamlandı': 'Import fuldført',
  'Şifre': 'Adgangskode',
  '• profil bilgisi': '• profilinfo',
  '• {} dizi durumu': '• {} seriestatusser',
  '• {} izleme kaydı': '• {} visningsposter',
  '• {} liste': '• {} lister',
  '• {} puan': '• {} bedømmelser',
  '• {} yorum': '• {} kommentarer',
  '{}+ yapım': '{}+ titler',
  'Yorumlar': 'Kommentarer',
  'Yorumlar ({})': 'Kommentarer ({})',
  'Yorumları ({})': 'Kommentarer ({})',
  'Listelerim': 'Mine lister',
  'Nereden izledin?': 'Hvor så du den?',
  'Diziye git': 'Gå til serien',
  'TV / Kanal': 'TV / Kanal',
  'Sinema': 'Biograf',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Andet',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Dit feed er tomt.\nNår nogen kommenterer de serier og film, du ser, vises det her.',
  'Listeleri ({})': 'Deres lister ({})',
  'Liste boş.': 'Denne liste er tom.',
  'Yanıtla': 'Svar',
  '@{} kullanıcısına yanıt veriyorsun': 'Du svarer @{}',
  'İzlediğim Diziler ({})': 'Serier jeg har set ({})',
  'İzlediğim Filmler ({})': 'Film jeg har set ({})',
  'Tümünü gör': 'Se alle',
  'Bildirimler': 'Notifikationer',
  'Henüz bildirim yok': 'Ingen notifikationer endnu',
  '@{} yorumuna yanıt verdi': '@{} svarede på din kommentar',
  '@{} yorumunu beğendi': '@{} synes godt om din kommentar',
  '@{} seni takip etti': '@{} følger dig',
  '@{} sana mesaj gönderdi': '@{} sendte dig en besked',
  'Mesajlar': 'Beskeder',
  'Mesaj': 'Besked',
  'Mesajını yaz...': 'Skriv en besked...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Ingen chats endnu.\nÅbn en profil og send en besked.',
  'Şifreni mi unuttun?': 'Glemt adgangskode?',
  'Şifreyi Sıfırla': 'Nulstil adgangskode',
  'E-postadaki kod': 'Kode fra mailen',
  'Yeni şifre': 'Ny adgangskode',
  'Sana Özel': 'Til dig',
  '{} özetin': 'Dit {}-overblik',
  'Yıllık izleme istatistiklerin': 'Din årlige seer-statistik',
  'Rozetler': 'Badges',
  'Verdiğin puan': 'Afgivne bedømmelser',
  'Ortalama puanın': 'Din gennemsnitlige bedømmelse',
  'En çok izlediğin diziler': 'Dine mest sete serier',
  'İlk Bölüm': 'Første afsnit',
  '100 Bölüm': '100 afsnit',
  '1000 Bölüm': '1000 afsnit',
  'İlk Film': 'Første film',
  '50 Film': '50 film',
  'İlk Yorum': 'Første kommentar',
  '25 Yorum': '25 kommentarer',
  '10 Puan': '10 bedømmelser',
  'İlk Takipçi': 'Første følger',
  '10 Dizi Bitirdin': '10 serier gennemført',
  'İzlemeyi Bıraktım': 'Stoppede med at se',
  'İzlediği Diziler ({})': 'Serier de har set ({})',
  'İzlediği Filmler ({})': 'Film de har set ({})',
  '500 Bölüm': '500 afsnit',
  '5000 Bölüm': '5000 afsnit',
  '10 Film': '10 film',
  '100 Film': '100 film',
  '100 Yorum': '100 kommentarer',
  '50 Puan': '50 bedømmelser',
  '100 Puan': '100 bedømmelser',
  '10 Takipçi': '10 følgere',
  '50 Takipçi': '50 følgere',
  '25 Dizi Bitirdin': '25 serier gennemført',
  '50 Dizi Bitirdin': '50 serier gennemført',
  '10 Beğeni': '10 likes',
  '100 Beğeni': '100 likes',
  'yazıyor...': 'skriver...',
  'Profil düzeni': 'Profillayout',
  'Konumla ve kırp': 'Placer og beskær',
  'Listeye eklendi': 'Tilføjet til listen',
  'Listeyi sil?': 'Slet listen?',
};
