/// Otomatik üretilen çeviri haritası (my).
const Map<String, String> cevirilerMy = {
  'Hepsini gördün, baştan gösteriyoruz':
      'အားလုံးမြင်ပြီးပြီ၊ ငါတို့အစကတည်းက မင်းကိုပြမယ်။',
  'Aktarılacak tanınan veri bulunamadı.':
      'ထည့်သွင်းရန် သိရှိနိုင်သော ဒေတာ မတွေ့ပါ။',
  'Arama': 'ရှာဖွေရန်',
  'Aramaya başla': 'ရှာဖွေမှု စတင်လိုက်ပါ',
  'Son aramalar': 'မကြာသေးမီက ရှာဖွေမှုများ',
  'Ayarlar': 'ဆက်တင်များ',
  'Bağla': 'ချိတ်ဆက်ရန်',
  'Bio': 'ကိုယ်ရေးအကျဉ်း',
  'Bitirdim': 'ပြီးအောင် ကြည့်ပြီးပြီ',
  'Bunları da Beğenebilirsin': 'ဒါတွေလည်း ကြိုက်နိုင်တယ်',
  'Bölüm': 'အပိုင်း',
  'Bıraktım': 'ရပ်လိုက်ပြီ',
  'Dil': 'ဘာသာစကား',
  'Dil ara...': 'ဘာသာစကား ရှာရန်...',
  'Dizi': 'ဇာတ်လမ်းတွဲ',
  'Dizi ve filmlerini takip et':
      'မင်းရဲ့ ဇာတ်လမ်းတွဲတွေနဲ့ ရုပ်ရှင်တွေကို မှတ်သားလိုက်ပါ',
  'Dizi yorumu': 'ဇာတ်လမ်းတွဲ မှတ်ချက်',
  'Dizi, film veya kişi ara...':
      'ဇာတ်လမ်းတွဲ၊ ရုပ်ရှင် သို့မဟုတ် လူပုဂ္ဂိုလ် ရှာရန်...',
  'Dosya en fazla 30MB olabilir': 'ဖိုင်သည် အများဆုံး 30MB သာ ဖြစ်နိုင်သည်',
  'Dosya en fazla {}MB olabilir': 'ဖိုင်သည် အများဆုံး {}MB သာ ဖြစ်နိုင်သည်',
  'E-posta': 'အီးမေးလ်',
  'E-posta veya kullanıcı adı': 'အီးမေးလ် သို့မဟုတ် အသုံးပြုသူအမည်',
  'En az 2 harf yaz': 'အနည်းဆုံး စာလုံး ၂ လုံး ရိုက်ပါ',
  'Film': 'ရုပ်ရှင်',
  'Film yorumu': 'ရုပ်ရှင် မှတ်ချက်',
  'Fotoğraf / video ekle': 'ဓာတ်ပုံ / ဗီဒီယို ထည့်ရန်',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'ဓာတ်ပုံ သို့မဟုတ် GIF — ပရိုဖိုင်နဲ့ ကာဗာပုံ',
  'Giriş Yap': 'ဝင်ရန်',
  'Gönder': 'ပို့ရန်',
  'Gönderildi': 'ပို့ပြီးပါပြီ',
  'Haftanın Dizileri': 'ဒီအပတ်ရဲ့ ဇာတ်လမ်းတွဲများ',
  'Haftanın Filmleri': 'ဒီအပတ်ရဲ့ ရုပ်ရှင်များ',
  'Henüz izleme kaydın yok': 'ကြည့်ရှုမှတ်တမ်း မရှိသေးပါ',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'စာရင်း မရှိသေးပါ — ပရိုဖိုင် တက်ဘ်ကနေ ဖန်တီးလိုက်ပါ။',
  'Henüz yorum yok.': 'မှတ်ချက် မရှိသေးပါ။',
  'Hesabın bağlandı!': 'အကောင့် ချိတ်ဆက်ပြီးပါပြီ!',
  'Hesabın yok mu? Kayıt ol': 'အကောင့် မရှိသေးဘူးလား? စာရင်းသွင်းလိုက်ပါ',
  'Hesabını Bağla': 'အကောင့်ကို ချိတ်ဆက်ပါ',
  'Hesap Oluştur': 'အကောင့် ဖွင့်ရန်',
  'Kapak resmi ekle': 'ကာဗာပုံ ထည့်ရန်',
  'Kaydet': 'သိမ်းရန်',
  'Kendinden bahset...': 'ကိုယ့်အကြောင်း ပြောပြပါ...',
  'Keşfet': 'စူးစမ်းရန်',
  'Kimseyi takip etmiyor': 'ဘယ်သူ့ကိုမှ စောင့်ကြည့်မထားပါ',
  'Kişi ara': 'လူ ရှာရန်',
  'Kişi yorumu': 'ပုဂ္ဂိုလ် မှတ်ချက်',
  'Konuk Oyuncular': 'ဧည့်သည်သရုပ်ဆောင်များ',
  'Kullanıcı adı (küçük harf)': 'အသုံးပြုသူအမည် (စာလုံးသေး)',
  'Kullanıcı adı ara...': 'အသုံးပြုသူအမည် ရှာရန်...',
  'Liste adı': 'စာရင်းအမည်',
  'Listeye Ekle': 'စာရင်းထဲ ထည့်ရန်',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'မင်းက ဧည့်သည်အကောင့်နဲ့ သုံးနေတာ — အီးမေးလ်နဲ့ ချိတ်ဆက်ပြီး ဒေတာတွေ မဆုံးရှုံးပါစေနဲ့!',
  'Misafir olarak devam et': 'ဧည့်သည်အနေနဲ့ ဆက်သုံးမယ်',
  'Oluştur': 'ဖန်တီးရန်',
  'Oyuncular': 'သရုပ်ဆောင်များ',
  'Profil': 'ပရိုဖိုင်',
  'Profil kaydedildi': 'ပရိုဖိုင် သိမ်းပြီးပါပြီ',
  'Puanla': 'အမှတ်ပေးရန်',
  'Puanı Sil': 'အမှတ် ဖျက်ရန်',
  'Puanın': 'မင်းရဲ့ အမှတ်',
  'Sezonlar': 'ရာသီများ',
  'Sunucu hatası ({})': 'ဆာဗာ အမှား ({})',
  'S{} · {}. Bölüm': 'S{} · အပိုင်း {}',
  'S{}B{} yorumu': 'S{}E{} မှတ်ချက်',
  'Takibi Bırak': 'မစောင့်ကြည့်တော့ပါ',
  'Takip': 'စောင့်ကြည့်ထားသည်',
  'Takip Edilenler': 'စောင့်ကြည့်ထားသူများ',
  'Takip Et': 'စောင့်ကြည့်မယ်',
  'Takipçi': 'စောင့်ကြည့်သူ',
  'Takipçi yok': 'စောင့်ကြည့်သူ မရှိပါ',
  'Takipçiler': 'စောင့်ကြည့်သူများ',
  'Takvim': 'ပြက္ခဒိန်',
  'Tamam': 'အိုကေ',
  'Tekrar Dene': 'ထပ်စမ်းကြည့်ပါ',
  'Tekrar dene': 'ထပ်စမ်းကြည့်ပါ',
  'Toplam İzleme Süresi': 'စုစုပေါင်း ကြည့်ရှုချိန်',
  'Tüm Zamanların En İyileri': 'အချိန်တိုင်းရဲ့ အကောင်းဆုံးများ',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'မင်းရဲ့ ဒေတာအားလုံး (ကြည့်ရှုမှတ်တမ်း၊ အမှတ်၊ မှတ်ချက်၊ စာရင်း) ကို TV Time နဲ့ ကိုက်ညီတဲ့ ZIP အနေနဲ့ ထုတ်ယူပါ ဒါမှမဟုတ် တခြားအက်ပ်က ZIP ကို ထည့်သွင်းပါ။',
  'Tümünü Kaldır': 'အားလုံး ဖယ်ရှားရန်',
  'Tümünü İzledim': 'အားလုံး ကြည့်ပြီးပြီ',
  'Türk Dizileri': 'တူရကီ ဇာတ်လမ်းတွဲများ',
  'Veri içe aktar (.zip)': 'ဒေတာ ထည့်သွင်းရန် (.zip)',
  'Verilerim': 'ကိုယ့်ဒေတာများ',
  'Verilerimi dışa aktar (e-posta)': 'ကိုယ့်ဒေတာ ထုတ်ယူရန် (အီးမေးလ်)',
  'Verilerini dışa aktar': 'ဒေတာ ထုတ်ယူရန်',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'လာမယ့် အပိုင်း မရှိပါ။\nဇာတ်လမ်းတွဲ အသေးစိတ်စာမျက်နှာကနေ "ကြည့်နေတယ်" အခြေအနေ ပြောင်းပြီး အပိုင်းသစ်တွေကို ဒီမှာ စောင့်ကြည့်ပါ။',
  'Yapımları': 'ပါဝင်ခဲ့တဲ့ ဇာတ်ကားများ',
  'Yeni Diziler': 'ဇာတ်လမ်းတွဲ အသစ်များ',
  'Yeni Liste': 'စာရင်းသစ်',
  'Yeni kullanıcı adı (isteğe bağlı)': 'အသုံးပြုသူအမည် အသစ် (ရွေးချယ်နိုင်)',
  'Yorum': 'မှတ်ချက်',
  'Yorumunu yaz...': 'မင်းရဲ့ မှတ်ချက် ရေးပါ...',
  'Zaten hesabın var mı? Giriş yap': 'အကောင့် ရှိပြီးသားလား? ဝင်လိုက်ပါ',
  'ort. {}': 'ပျမ်းမျှ {}',
  'takip': 'စောင့်ကြည့်ထားသည်',
  'takipçi': 'စောင့်ကြည့်သူ',
  '{} / {} bölüm': '{} / {} ပိုင်း',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} လ',
  '{} ay~tekil': '{} လ',
  '{} bölüm izlendi': '{} ပိုင်း ကြည့်ပြီးပြီ',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} မိနစ်',
  '{} dk~tekil': '{} မိနစ်',
  '{} gün': '{} ရက်',
  '{} gün~tekil': '{} ရက်',
  '{} içerik': 'အကြောင်းအရာ {} ခု',
  '{} içerik · otomatik': 'အကြောင်းအရာ {} ခု · အလိုအလျောက်',
  '{} kayıt atlandı (eşleşmedi).': 'မှတ်တမ်း {} ခု ကျော်သွားသည် (မကိုက်ညီပါ)။',
  '{} saat': '{} နာရီ',
  '{} saat~tekil': '{} နာရီ',
  '{} sezon': 'ရာသီ {} ခု',
  '{} yıl': '{} နှစ်',
  '{} yıl~tekil': '{} နှစ်',
  '{}. Bölüm': 'အပိုင်း {}',
  '{}. Sezon': 'ရာသီ {}',
  'Çıkış Yap': 'ထွက်ရန်',
  'Ülke': 'နိုင်ငံ',
  'Ülke ara...': 'နိုင်ငံ ရှာရန်...',
  'Ülke seç': 'နိုင်ငံ ရွေးပါ',
  'İlk yorumu sen yaz!': 'ပထမဆုံး မှတ်ချက်ကို မင်းရေးလိုက်ပါ!',
  'İncelemeler': 'သုံးသပ်ချက်များ',
  'İncelemen (isteğe bağlı)': 'မင်းရဲ့ သုံးသပ်ချက် (ရွေးချယ်နိုင်)',
  'İptal': 'မလုပ်တော့ပါ',
  'İzlediklerim': 'ကြည့်ပြီးသားများ',
  'İzledim': 'ကြည့်ပြီးပြီ',
  'İzledin': 'မင်း ကြည့်ပြီးပြီ',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'မင်းရဲ့ ကြည့်ရှုမှတ်တမ်းနဲ့ စာရင်းတွေ ဆက်ရှိနေမယ်; အခုကစပြီး ဘယ်စက်ကမဆို ဝင်နိုင်ပြီ။',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'မင်းရဲ့ ကြည့်ရှုမှတ်တမ်း၊ အမှတ်တွေ၊ မှတ်ချက်တွေနဲ့ စာရင်းတွေကို ZIP အနေနဲ့ မှတ်ပုံတင်ထားတဲ့ အီးမေးလ်လိပ်စာဆီ ပို့ပေးပါမယ်။',
  'İzleyeceğim': 'ကြည့်မယ်',
  'İzliyorum': 'ကြည့်နေတယ်',
  'İçe aktarım tamamlandı': 'ထည့်သွင်းမှု ပြီးပါပြီ',
  'Şifre': 'စကားဝှက်',
  '• profil bilgisi': '• ပရိုဖိုင် အချက်အလက်',
  '• {} dizi durumu': '• ဇာတ်လမ်းတွဲ အခြေအနေ {} ခု',
  '• {} izleme kaydı': '• ကြည့်ရှုမှတ်တမ်း {} ခု',
  '• {} liste': '• စာရင်း {} ခု',
  '• {} puan': '• အမှတ် {} ခု',
  '• {} yorum': '• မှတ်ချက် {} ခု',
  '{}+ yapım': '{}+ ဇာတ်ကား',
  'Yorumlar': 'မှတ်ချက်များ',
  'Yorumlar ({})': 'မှတ်ချက်များ ({})',
  'Yorumları ({})': 'မှတ်ချက်များ ({})',
  'Listelerim': 'ကိုယ့်စာရင်းများ',
  'Nereden izledin?': 'ဘယ်မှာကြည့်ခဲ့လဲ။',
  'Diziye git': 'ဇာတ်လမ်းသို့ သွားရန်',
  'TV / Kanal': 'တီဗီ / ချန်နယ်',
  'Sinema': 'ရုပ်ရှင်ရုံ',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'အခြား',
  'Akış': 'ဖိဒ်',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'သင့်ဖိဒ်က ဗလာဖြစ်နေသည်။\nသင်ကြည့်နေသော ဇာတ်လမ်းများနှင့် ရုပ်ရှင်များတွင် မှတ်ချက်များ ရောက်လာလျှင် ဤနေရာတွင် ပေါ်လာမည်။',
  'Listeleri ({})': 'သူ့စာရင်းများ ({})',
  'Liste boş.': 'ဤစာရင်းသည် ဗလာဖြစ်နေသည်။',
  'Yanıtla': 'ပြန်စာ',
  '@{} kullanıcısına yanıt veriyorsun': '@{} ကို ပြန်ဖြေနေသည်',
  'İzlediğim Diziler ({})': 'ကြည့်ပြီး ဇာတ်လမ်းများ ({})',
  'İzlediğim Filmler ({})': 'ကြည့်ပြီး ရုပ်ရှင်များ ({})',
  'Tümünü gör': 'အားလုံးကြည့်ရန်',
  'Bildirimler': 'အသိပေးချက်များ',
  'Henüz bildirim yok': 'အသိပေးချက် မရှိသေးပါ',
  '@{} yorumuna yanıt verdi': '@{} က သင့်မှတ်ချက်ကို ပြန်ဖြေခဲ့သည်',
  '@{} yorumunu beğendi': '@{} က သင့်မှတ်ချက်ကို ကြိုက်ခဲ့သည်',
  '@{} seni takip etti': '@{} က သင့်ကို စောင့်ကြည့်ခဲ့သည်',
  '@{} sana mesaj gönderdi': '@{} က သင့်ထံ စာပို့ခဲ့သည်',
  'Mesajlar': 'စာများ',
  'Mesaj': 'စာ',
  'Mesaja eklenecek': 'မက်ဆေ့ချ်တွင် ထည့်သွင်းပါမည်',
  'Mesajını yaz...': 'စာရေးပါ...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'စကားပြောခန်း မရှိသေးပါ။\nပရိုဖိုင်တစ်ခုဖွင့်ပြီး စာပို့ပါ။',
  'Şifreni mi unuttun?': 'စကားဝှက် မေ့နေပါသလား။',
  'Şifreyi Sıfırla': 'စကားဝှက် ပြန်သတ်မှတ်ရန်',
  'E-postadaki kod': 'အီးမေးလ်ထဲက ကုဒ်',
  'Yeni şifre': 'စကားဝှက်အသစ်',
  'Sana Özel': 'သင့်အတွက်',
  '{} özetin': 'သင့် {} အနှစ်ချုပ်',
  'Yıllık izleme istatistiklerin': 'နှစ်စဉ် ကြည့်ရှုမှု စာရင်း',
  'Rozetler': 'တံဆိပ်များ',
  'Verdiğin puan': 'ပေးခဲ့သော အဆင့်သတ်မှတ်ချက်',
  'Ortalama puanın': 'ပျမ်းမျှ အဆင့်',
  'En çok izlediğin diziler': 'အကြည့်ဆုံး ဇာတ်လမ်းများ',
  'İlk Bölüm': 'ပထမဆုံး အပိုင်း',
  '100 Bölüm': 'အပိုင်း 100',
  '1000 Bölüm': 'အပိုင်း 1000',
  'İlk Film': 'ပထမဆုံး ရုပ်ရှင်',
  '50 Film': 'ရုပ်ရှင် 50',
  'İlk Yorum': 'ပထမဆုံး မှတ်ချက်',
  '25 Yorum': 'မှတ်ချက် 25',
  '10 Puan': 'အဆင့် 10',
  'İlk Takipçi': 'ပထမဆုံး စောင့်ကြည့်သူ',
  '10 Dizi Bitirdin': 'ဇာတ်လမ်း 10 ခု ပြီးမြောက်',
  'İzlemeyi Bıraktım': 'ကြည့်ရှုမှု ရပ်လိုက်ပြီ',
  'İzlediği Diziler ({})': 'သူကြည့်ခဲ့သော ဇာတ်လမ်းများ ({})',
  'İzlediği Filmler ({})': 'သူကြည့်ခဲ့သော ရုပ်ရှင်များ ({})',
  '500 Bölüm': 'အပိုင်း 500',
  '5000 Bölüm': 'အပိုင်း 5000',
  '10 Film': 'ရုပ်ရှင် 10',
  '100 Film': 'ရုပ်ရှင် 100',
  '100 Yorum': 'မှတ်ချက် 100',
  '50 Puan': 'အဆင့် 50',
  '100 Puan': 'အဆင့် 100',
  '10 Takipçi': 'စောင့်ကြည့်သူ 10',
  '50 Takipçi': 'စောင့်ကြည့်သူ 50',
  '25 Dizi Bitirdin': 'ဇာတ်လမ်း 25 ပြီးမြောက်',
  '50 Dizi Bitirdin': 'ဇာတ်လမ်း 50 ပြီးမြောက်',
  '10 Beğeni': 'လိုက် 10',
  '100 Beğeni': 'လိုက် 100',
  'yazıyor...': 'စာရိုက်နေသည်...',
  'ses kaydediyor...': 'အသံသွင်းနေသည်...',
  'Profil düzeni': 'ပရိုဖိုင် အပြင်အဆင်',
  'Konumla ve kırp': 'နေရာချပြီး ဖြတ်ပါ',
  'Listeye eklendi': 'စာရင်းထဲ ထည့်ပြီး',
  'Listeyi sil?': 'စာရင်းကို ဖျက်မလား။',
  'Sil': 'ဖျက်ရန်',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'ဤဇာတ်လမ်းကို မကြည့်ဖူးသလို မှတ်ပြီး သင့်စာရင်းများမှ ဖယ်ရှားပါမည်။',
  'Gelecek bölüm bugün': 'နောက်အပိုင်း ယနေ့',
  'Gelecek bölüm {} gün sonra': 'နောက်အပိုင်း {} ရက်အကြာ',
  'Tema': 'အပြင်အဆင်',
  'Sistem': 'စနစ်',
  'Koyu': 'အမှောင်',
  'Açık': 'အလင်း',
  'İzleyenler': 'ကြည့်ရှုသူများ',
  'Yorumunu yaz... (@ ile etiketle)': 'သင့်မှတ်ချက်ရေးပါ... (@ တက်ဂ်လုပ်ရန်)',
  '@{} bir yorumda seni etiketledi':
      '@{} က မှတ်ချက်တစ်ခုတွင် သင့်ကို တက်ဂ်လုပ်ခဲ့သည်',
  'Mesajı sil': 'မက်ဆေ့ဂျ်ဖျက်ရန်',
  'Mesaj silinemedi': 'မက်ဆေ့ဂျ်ကို ဖျက်၍မရပါ',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'လင့်ခ်မမှန်ကန်ပါ သို့မဟုတ် စာမျက်နှာမတွေ့ပါ',
  "Keşfet'e dön": 'ရှာဖွေရန်သို့ ပြန်သွားရန်',
  'Düzenle': 'တည်းဖြတ်',
  'Mesajı düzenle': 'မက်ဆေ့ဂျ်တည်းဖြတ်',
  'Yanıtlanıyor': 'ပြန်စာပေးနေသည်',
  'düzenlendi': 'တည်းဖြတ်ပြီး',
  'Fotoğraf': 'ဓာတ်ပုံ',
  'Video': 'ဗီဒီယို',
  'İçerik': 'အကြောင်းအရာ',
  'çevrimiçi': 'အွန်လိုင်း',
  'son görülme {} dk önce': '{} မိနစ်က တွေ့ခဲ့',
  'son görülme {} saat önce': '{} နာရီက တွေ့ခဲ့',
  'son görülme {} gün önce': '{} ရက်က တွေ့ခဲ့',
  'Yorumlar yüklenemedi': 'မှတ်ချက်များ ဖွင့်၍မရပါ',
  'Favori': 'အကြိုက်ဆုံး',
  'Listeye ekle': 'စာရင်းသို့ ထည့်ရန်',
  'İçerik paylaş': 'မျှဝေရန်',
  'Kapat': 'ပိတ်ရန်',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'ကြည့်ပြီးဟု အမှတ်အသားပြုသမျှ ဤနေရာတွင် စုစည်းသည်။',
  'Henüz sohbetin yok': 'စကားဝိုင်း မရှိသေးပါ',
  'Bir profile girip mesaj gönderebilirsin.':
      'ပရိုဖိုင်ဖွင့်၍ မက်ဆေ့ဂျ်ပို့ပါ။',
  'Listeyi sil': 'စာရင်းဖျက်ရန်',
  'Puan kaydedilemedi': 'အဆင့်သတ်မှတ်ချက် သိမ်း၍မရပါ',
  'Nerede İzlenir': 'ဘယ်မှာကြည့်ရမလဲ',
  'Abonelik': 'အသင်းဝင်ခ',
  'Kirala': 'ငှားရမ်း',
  'Satın al': 'ဝယ်ယူ',
  'Devam et': 'ဆက်လုပ်ပါ',
  'Şikayet et': 'တိုင်ကြားရန်',
  'Engelle': 'ပိတ်ဆို့ရန်',
  'Engeli kaldır': 'ပိတ်ဆို့မှုဖြုတ်ရန်',
  'Kullanıcı engellendi': 'အသုံးပြုသူကို ပိတ်ဆို့ပြီး',
  'Engel kaldırıldı': 'ပိတ်ဆို့မှု ဖြုတ်ပြီး',
  'Şikayet sebebi': 'တိုင်ကြားရသည့်အကြောင်းရင်း',
  'Spam veya yanıltıcı': 'စပမ် သို့မဟုတ် လှည့်စားမှု',
  'Taciz veya nefret söylemi': 'နှောင့်ယှက်မှု သို့မဟုတ် အမုန်းစကား',
  'Uygunsuz / cinsel içerik': 'မသင့်လျော် / လိင်ဆိုင်ရာအကြောင်းအရာ',
  'Şiddet veya tehlikeli içerik':
      'အကြမ်းဖက်မှု သို့မဟုတ် အန္တရာယ်ရှိအကြောင်းအရာ',
  'Telif hakkı ihlali': 'မူပိုင်ခွင့်ချိုးဖောက်မှု',
  'Şikayetin alındı, teşekkürler':
      'မင်းရဲ့တိုင်ကြားချက် ရရှိပါပြီ၊ ကျေးဇူးတင်ပါတယ်',
  'Hesabımı Sil': 'ကျွန်ုပ်အကောင့်ကို ဖျက်ရန်',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'မင်းရဲ့အကောင့်နဲ့ ဒေတာအားလုံး (မှတ်တမ်း၊ အဆင့်သတ်မှတ်ချက်၊ မှတ်ချက်၊ စာရင်း၊ မက်ဆေ့ချ်) အပြီးအပိုင် ဖျက်ခံရမည်။ ဒါကို ပြန်ဖျက်လို့မရပါ။',
  'Şifreni gir': 'မင်းရဲ့စကားဝှက်ကို ထည့်ပါ',
  'Hesabımı kalıcı sil': 'ကျွန်ုပ်အကောင့်ကို အပြီးအပိုင်ဖျက်ရန်',
  'Sesli mesaj': 'အသံမက်ဆေ့ချ်',
  'Ses gönderilemedi': 'အသံမက်ဆေ့ချ် ပို့၍မရပါ',
  'Kaydediliyor…': 'အသံဖမ်းနေသည်…',
  'Ses oynatılamadı': 'အသံဖွင့်၍ မရပါ',
  'Oynat': 'ဖွင့်ရန်',
  'Fragmanı oynat': 'ကြိုကြည့်ဗီဒီယို ဖွင့်ရန်',
  'Altyazıyı aç': 'စာတန်းထိုး ဖွင့်ရန်',
  'Altyazıyı kapat': 'စာတန်းထိုး ပိတ်ရန်',
  '10 saniye ileri': '၁၀ စက္ကန့် ရှေ့သို့',
  '10 saniye geri': '၁၀ စက္ကန့် နောက်သို့',
  'Duraklat': 'ခေတ္တရပ်ရန်',
  'Liste görünümü': 'စာရင်းမြင်ကွင်း',
  'Takvim görünümü': 'ပြက္ခဒိန်မြင်ကွင်း',
  'Önceki ay': 'ယခင်လ',
  'Sonraki ay': 'နောက်လ',
  'Bu gün bölüm yok': 'ဒီနေ့ ဇာတ်လမ်းအပိုင်း မရှိပါ',
  'Gizlilik Politikası': 'ကိုယ်ရေးအချက်အလက် မူဝါဒ',
  'Son güncelleme: {}': 'နောက်ဆုံးအပ်ဒိတ်- {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'dizi.jpg အက်ပ်နှင့် dizijpg.com ဆိုက်ကို အသုံးပြုစဉ် မည်သည့်ဒေတာများ စုဆောင်းသည်၊ မည်သို့အသုံးပြုသည်၊ သင့်အခွင့်အရေးများ မည်သည်တို့ဖြစ်သည်ကို ဤမူဝါဒက ရှင်းပြသည်။',
  'Topladığımız Veriler': 'ကျွန်ုပ်တို့ စုဆောင်းသောဒေတာ',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'အကောင့်- အီးမေးလ်လိပ်စာ၊ အသုံးပြုသူအမည်နှင့် စကားဝှက်။ စကားဝှက်များကို ပြန်ဖော်၍မရသော hash ပုံစံဖြင့် သိမ်းဆည်းသည်။ ဧည့်သည်အကောင့်များကို အီးမေးလ်မလိုဘဲ သုံးနိုင်သည်။',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'ပရိုဖိုင်- avatar၊ ကာဗာပုံ၊ ကိုယ်ရေးအကျဉ်းနှင့် နိုင်ငံကဲ့သို့ သင်ကိုယ်တိုင် ထည့်ရန်ရွေးချယ်သော အချက်အလက်များ။',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'အသုံးပြုမှု- သင့်ကြည့်ရှုမှုမှတ်တမ်း၊ အဆင့်သတ်မှတ်ချက်များ၊ မှတ်ချက်များ၊ စာရင်းများ၊ တုံ့ပြန်မှုများနှင့် အကြိုက်ဆုံးများ။',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'မက်ဆေ့ချ်များ- သင့်စာသား၊ ပုံနှင့် အသံမက်ဆေ့ချ်များကို ကျွန်ုပ်တို့၏ဆာဗာများပေါ်တွင် သိမ်းဆည်းသည်။ မက်ဆေ့ချ်များသည် အစွန်းမှအစွန်း စာဝှက်မထားပါ။ တိုင်ကြားခံရမှသာ စိစစ်ရေးအတွက် ကြည့်ရှုမည်။',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'တင်ထားသောမီဒီယာ- ပရိုဖိုင်၊ မှတ်ချက်နှင့် မက်ဆေ့ချ်များတွင် သင်ထည့်သော ဓာတ်ပုံ၊ GIF၊ ဗီဒီယိုနှင့် အသံသွင်းချက်များ။',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'နည်းပညာဆိုင်ရာ- IP လိပ်စာ၊ ခန့်မှန်းတည်နေရာ (နိုင်ငံ/မြို့အဆင့်)၊ စက်ပလက်ဖောင်း၊ အက်ပ်ဗားရှင်းနှင့် အမှားမှတ်တမ်းများ။ ၎င်းတို့ကို လုံခြုံရေးနှင့် ပြဿနာဖြေရှင်းရန်အတွက် သိမ်းထားသည်။',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'အသုံးပြုမှုစာရင်း- မည်သည့်စက်အမျိုးအစား၊ လည်ပတ်စနစ်နှင့် ဘရောက်ဇာဖြင့် ဝင်ရောက်သည်ကို ကြမ်းတမ်းသော အမျိုးအစားများအဖြစ် နေ့စဉ်စုစုပေါင်းရေတွက်မှုများတွင် ထည့်သွင်းသည်။ ဘရောက်ဇာ၏ သတ်မှတ်အမှတ်အသားကိုယ်တိုင်ကို မသိမ်းဆည်းဘဲ ဤကိန်းဂဏန်းများကို မည်သူတစ်ဦးတစ်ယောက်နှင့်မျှ ချိတ်ဆက်၍မရပါ။',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'အသိပေးချက်များ- push အသိပေးချက်များအတွက် သင့်စက်၏ token နှင့် ဘာသာစကားရွေးချယ်မှုကို သိမ်းထားသည်။ စက်၏ဆက်တင်များမှ အသိပေးချက်များကို အချိန်မရွေး ပိတ်နိုင်သည်။',
  'Verileri Nasıl Kullanırız': 'ဒေတာကို မည်သို့အသုံးပြုသနည်း',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'သင့်ဒေတာကို ဝန်ဆောင်မှုပေးရန်၊ အကောင့်ကာကွယ်ရန်၊ အသိပေးချက်ပို့ရန်၊ အမှားပြင်ရန်နှင့် အလွဲသုံးမှုတားဆီးရန်အတွက်သာ အသုံးပြုသည်။ သင့်ဒေတာကို မရောင်းပါ၊ ကြော်ငြာအတွက် မည်သူနှင့်မျှ မမျှဝေပါ။',
  'Çerezler ve Yerel Depolama': 'Cookie များနှင့် စက်တွင်းသိုလှောင်မှု',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'သင့်ကို လော့ဂ်အင်ဝင်ထားစေရန်နှင့် ဘာသာစကား/အပြင်အဆင်ကဲ့သို့ ရွေးချယ်မှုများကို မှတ်ထားရန်အတွက်သာ စက်တွင်းသိုလှောင်မှုကို သုံးသည်။ ကြော်ငြာ သို့မဟုတ် ခြေရာခံ cookie မရှိပါ။',
  'Üçüncü Taraf Hizmetler': 'ပြင်ပဝန်ဆောင်မှုများ',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'ဇာတ်လမ်းတွဲနှင့် ရုပ်ရှင်ဒေတာများသည် TMDB မှ၊ streaming ပလက်ဖောင်းအချက်အလက်များသည် JustWatch မှ လာသည်။ Push အသိပေးချက်များကို Google Firebase မှတစ်ဆင့် ပို့ဆောင်ပြီး ဆိုက်၏အသွားအလာကို Cloudflare က ကာကွယ်သည်။ ဤဝန်ဆောင်မှုများသည် ၎င်းတို့၏ကိုယ်ပိုင် ကိုယ်ရေးအချက်အလက်မူဝါဒများနှင့် လိုက်နာရသည်။',
  'Saklama ve Silme': 'သိမ်းဆည်းမှုနှင့် ဖျက်ခြင်း',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'သင့်အကောင့်ရှိနေသရွေ့ သင့်ဒေတာကို သိမ်းထားသည်။ ဆက်တင်များရှိ "ကျွန်ုပ်၏အကောင့်ကို ဖျက်ရန်" ဖြင့် အကောင့်ကို အပြီးတိုင်ဖျက်နိုင်သည်။ ဒေတာကို ချက်ချင်းဖျက်ပြီး အရန်ကူးယူမှုများရှိ မိတ္တူများကို အများဆုံး ၁၄ ရက်အတွင်း ဖျက်သည်။ အမှားမှတ်တမ်းများကို ရက် ၃၀ ကြာပြီးနောက် အလိုအလျောက် ဖျက်သည်။',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'ဆက်တင်များမှ သင့်ဒေတာကို ZIP အဖြစ် ထုတ်ယူနိုင်သည်။ မှတ်တမ်းဖိုင်ကို သင့်အီးမေးလ်လိပ်စာသို့ ပို့ပေးသည်။',
  'Güvenlik': 'လုံခြုံရေး',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'ဒေတာများသည် စာဝှက်ထားသောချိတ်ဆက်မှုများ (HTTPS) မှတစ်ဆင့် သွားလာပြီး ဝင်ရောက်ခွင့်ကန့်သတ်ထားသော ဆာဗာများပေါ်တွင် သိမ်းဆည်းသည်။',
  'Çocukların Gizliliği': 'ကလေးများ၏ ကိုယ်ရေးအချက်အလက်',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg သည် အသက် ၁၃ နှစ်အောက် ကလေးများအတွက် မဟုတ်ပါ။',
  'Hakların': 'သင့်အခွင့်အရေးများ',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK နှင့် GDPR အရ သင့်ဒေတာကို ဝင်ကြည့်ရန်၊ ပြင်ရန်၊ ဖျက်ရန်နှင့် ရွှေ့ပြောင်းရန် အခွင့်အရေးရှိသည်။ ဤကိစ္စများအတွက် ကျွန်ုပ်တို့ထံ စာရေးပါ- {}',
  'Değişiklikler': 'ပြောင်းလဲမှုများ',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'ဤမူဝါဒ ပြောင်းလဲပါက ဗားရှင်းအသစ်ကို ဤစာမျက်နှာတွင် ထုတ်ပြန်ပြီး ရက်စွဲကို အပ်ဒိတ်လုပ်မည်။',
  'Kayıt olarak {} kabul etmiş olursun.':
      'စာရင်းသွင်းခြင်းဖြင့် {} ကို လက်ခံပြီးဖြစ်သည်။',
  'Kullanıcılar': 'အသုံးပြုသူများ',
  'Fotoğrafı değiştir': 'ဓာတ်ပုံပြောင်းရန်',
  'Yeniden konumlandır': 'ပြန်နေရာချရန်',
  'Bir şeyler ters gitti': 'တစ်ခုခုမှားသွားသည်',
  'Sosyal Bağlantılar': 'ဆိုရှယ်လင့်ခ်များ',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'သင့်ပရိုဖိုင်တွင် လင့်ခ် ၃ ခုအထိ ပြသည်။',
  'Platform seç': 'ပလက်ဖောင်းရွေးပါ',
  'Kullanıcı adın': 'သင့်အသုံးပြုသူအမည်',
  'Ekle': 'ထည့်ရန်',
  'Kaldır': 'ဖယ်ရန်',
  'Kopyalandı: {}': 'ကူးယူပြီး- {}',
  'Geçersiz kullanıcı adı': 'အသုံးပြုသူအမည် မမှန်ပါ',
  'Bağlantı ekle': 'လင့်ခ်ထည့်ရန်',
  'Spoiler olabilir — dokun ve gör':
      'ဇာတ်လမ်းပေါက်ကြားနိုင်သည် — ကြည့်ရန် တို့ပါ',
  'Beğeni': 'ကြိုက်နှစ်သက်မှု',
  'beğeni': 'ကြိုက်နှစ်သက်မှု',
  'Beğen': 'နှစ်သက်သည်',
  'Görüntülenme': 'ကြည့်ရှုမှု',
  'görüntülenme': 'ကြည့်ရှုမှု',
  'Tam ekran': 'မျက်နှာပြင်အပြည့်',
  'Arama başarısız': 'ရှာဖွေမှု မအောင်မြင်ပါ',
  'Sonuç bulunamadı': 'ရလဒ်မတွေ့ပါ',
  'Dizi ve Filmler': 'စီးရီးနှင့် ရုပ်ရှင်များ',
  'Kişiler': 'ပုဂ္ဂိုလ်များ',
  'Ana Sayfa': 'ပင်မ',
  'Paylaş': 'မျှဝေရန်',
  'Yanıtlar': 'ပြန်စာများ',
  'Yaklaşan Bölümler': 'လာမည့်အပိုင်းများ',
  'Yetişme Listesi': 'လိုက်ကြည့်ရန်စာရင်း',
  'Şunu mu demek istedin': 'ဆိုလိုတာ',
  'Spoiler': 'စပွိုင်လာ',
  'Spoiler — dokun ve gör': 'စပွိုင်လာ — ကြည့်ရန် တို့ပါ',
  'uyum': 'ကိုက်ညီမှု',
  'Uyum': 'ကိုက်ညီမှု',
  '{} ortak dizi': 'တူညီသည့် ဇာတ်လမ်းတွဲ {} ခု',
  '{} ortak film': 'တူညီသည့် ရုပ်ရှင် {} ကား',
  'Bildirim Tercihleri': 'အကြောင်းကြားချက် နှစ်သက်မှုများ',
  'Beğeniler': 'နှစ်သက်မှုများ',
  'Yeni takipçiler': 'နောက်လိုက် အသစ်များ',
  'Etiketlenmeler': 'ဖော်ပြချက်များ',
  'Yeniden izledim': 'ပြန်ကြည့်ပြီး',
  '{}. kez izlendi': '{} ကြိမ် ကြည့်ပြီး',
  'Gönderi bulunamadı': 'ပို့စ်ကို ရှာမတွေ့ပါ',
  'Gözat': 'လှော်လှန်ကြည့်ရန်',
  'Diziler': 'ဇာတ်လမ်းတွဲများ',
  'Filmler': 'ရုပ်ရှင်များ',
  'Tümü': 'အားလုံး',
  'Farklı bir tür seç.': 'အခြားအမျိုးအစား စမ်းကြည့်ပါ။',
  'Gizlilik': 'ကိုယ်ရေးလုံခြုံမှု',
  'İzlediklerimi gizle': 'ကြည့်ထားသည်များကို ဖျောက်ရန်',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'သင်ကြည့်ထားသော စီးရီးနှင့် ရုပ်ရှင်များ သင့်ပရိုဖိုင်တွင် မပေါ်ပါ',
  'Yorumlarımı gizle': 'ကျွန်ုပ်၏ မှတ်ချက်များကို ဖျောက်ရန်',
  'Profilinde yorumların görünmez':
      'သင့်မှတ်ချက်များ သင့်ပရိုဖိုင်တွင် မပေါ်ပါ',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'စီးရီး သို့မဟုတ် ရုပ်ရှင်တစ်ခုချင်းကို ၎င်း၏စာမျက်နှာရှိ "ကျွန်ုပ်ပရိုဖိုင်တွင် ဖျောက်ရန်" ချစ်ပ်ဖြင့် ဖျောက်နိုင်သည်။',
  'Geri Bildirim': 'အကြံပြုချက်',
  'Uygulama hakkında görüş ve önerini yaz...':
      'အက်ပ်အကြောင်း သင့်ထင်မြင်ချက်နှင့် အကြံပြုချက်များ ရေးပါ...',
  'Teşekkürler! Geri bildirimin alındı.':
      'ကျေးဇူးတင်ပါသည်! သင့်အကြံပြုချက် လက်ခံရရှိပါပြီ။',
  'Profilimde gizle': 'ကျွန်ုပ်ပရိုဖိုင်တွင် ဖျောက်ရန်',
  'Yorumları': 'မှတ်ချက်များ',
  'Bu kullanıcı henüz bir şey izlememiş.': 'ဤအသုံးပြုသူသည် ဘာမျှ မကြည့်ရသေးပါ။',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'ဤအသုံးပြုသူသည် မိမိ၏မှတ်ချက်များကို လျှို့ဝှက်ထားလိုသည်။',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'ဒေတာ- JustWatch',
  'Web Sitesi': 'ဝဘ်ဆိုက်',
  'Diğer uygulamalar': 'အခြားအက်ပ်များ',
  'Bağlantıyı kopyala': 'လင့်ခ်ကူးရန်',
  'Henüz kimseyi takip etmiyorsun.': 'သင်ဘယ်သူ့ကိုမှ မလိုက်ရသေးပါ။',
  'Çevir': 'ဘာသာပြန်',
  'Çeviri şu an yapılamadı': 'ယခုအချိန်တွင် ဘာသာပြန်၍မရပါ',
  'Bağlantı açılamadı': 'လင့်ခ်ကို ဖွင့်၍မရပါ',
  'Orijinali göster': 'မူရင်းပြရန်',
  'Çeviriyi göster': 'ဘာသာပြန်ကို ပြပါ',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'ဤလတွင် ထုတ်လွှင့်မည့်ရက် ကြေညာထားသော အပိုင်းမရှိပါ။ ရက်စွဲများကို များသောအားဖြင့် ရက်သတ္တပတ်အနည်းငယ်ကြိုတင်ကြေညာပြီး ဤနေရာတွင် ပေါ်လာပါမည်။',
  'devamı': 'ထပ်ဖတ်ရန်',
  'Google ile devam et': 'Google ဖြင့် ဆက်လုပ်ပါ',
  'Google girişi başarısız': 'Google ဖြင့် ဝင်ရောက်မှု မအောင်မြင်ပါ',
  'Veri tasarrufu': 'ဒေတာချွေတာမှု',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi တွင် ဒေတာချွေတာမှု',
  'Mobil veride veri tasarrufu': 'မိုဘိုင်းဒေတာတွင် ဒေတာချွေတာမှု',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'ဖွင့်ထားချိန်တွင် ဓာတ်ပုံများကို ကြိုတင်မဒေါင်းလုဒ်ဘဲ ကြည့်နေသည့်ပုံကိုသာ တင်ပါသည်။',
  'Çocuk güvenliği': 'ကလေးလုံခြုံရေး',
  'Türk Filmleri': 'တူရကီ ရုပ်ရှင်များ',
  'En Yüksek Puanlı Filmler': 'အဆင့်သတ်မှတ်ချက် အမြင့်ဆုံး ရုပ်ရှင်များ',
  'En Yüksek Puanlı Diziler': 'အဆင့်သတ်မှတ်ချက် အမြင့်ဆုံး စီးရီးများ',
  'En Çok İzlenen Filmler': 'အကြည့်အများဆုံး ရုပ်ရှင်များ',
  'Popüler Diziler': 'ရေပန်းစား စီးရီးများ',
  'En Çok Kazanan Filmler': 'ဝင်ငွေအများဆုံး ရုပ်ရှင်များ',
  'Kült Filmler': 'ကာလ့်ရုပ်ရှင်များ',
  'Yeni Filmler': 'ရုပ်ရှင်အသစ်များ',
  'Yorum yap': 'မှတ်ချက်ပေးရန်',
  'Henüz yorum yok': 'မှတ်ချက် မရှိသေးပါ',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'စီးရီးများနှင့် ရုပ်ရှင်များအတွက် သင်ရေးသော မှတ်ချက်များ ဤနေရာတွင် စုစည်းပါသည်။',
  'GIF ekle': 'GIF ထည့်ရန်',
  'İlk yorumu sen yaz': 'ပထမဆုံး မှတ်ချက်ကို သင်ရေးပါ',
  'Video altyazıları': 'ဗီဒီယို စာတန်းထိုးများ',
  'Videolarda altyazı göster': 'ဗီဒီယိုများတွင် စာတန်းထိုးပြပါ။',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'ဗီဒီယိုတွင်ပြောသောစာကြောင်းကို စခရင်ပေါ်တွင်ရေးထားသည်။ စာသားသည် ဘာသာပြန်သည်- တူရကီစကားတွင် အင်္ဂလိပ်၊ အခြားဘာသာစကားဖြင့် တူရကီ။',
  'Güncelleme gerekli': 'အပ်ဒိတ် လိုအပ်သည်',
  'Yeni sürüm var': 'ဗားရှင်းအသစ် ရနိုင်ပါပြီ',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'ဆက်လုပ်ရန် dizi.jpg ၏ ဗားရှင်းအသစ်ကို ထည့်သွင်းပါ။',
  'Güncelle': 'အပ်ဒိတ်လုပ်ရန်',
  'Daha sonra': 'နောက်မှ',
  'Takvim güncelleniyor': 'ပြက္ခဒိန် အပ်ဒိတ်လုပ်နေသည်',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'ပြက္ခဒိန်ကို အပ်ဒိတ်မလုပ်နိုင်ပါ၊ စာရင်းအဟောင်းကို ပြသနေသည်',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'အချို့ဇာတ်လမ်းတွဲများ ဖွင့်၍မရပါ၊ စာရင်းမပြည့်စုံနိုင်ပါ',
  'Yenile': 'ပြန်လည်စတင်',
  'Devam etmek için giriş yap': 'ဆက်လုပ်ရန် အကောင့်ဝင်ပါ',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'အဆင့်သတ်မှတ်ရန်၊ မှတ်ချက်ရေးရန်နှင့် သင့်စာကြည့်တိုက်တည်ဆောက်ရန် အခမဲ့အကောင့်တစ်ခုလုံလောက်ပါသည်။',
  'Şimdi değil': 'ယခုမဟုတ်ပါ',
  'Yorum yazmak için giriş yap': 'မှတ်ချက်ရေးရန် အကောင့်ဝင်ပါ',
  'Kişilere göndermek için giriş yap': 'လူများထံပို့ရန် အကောင့်ဝင်ပါ',
  'Beğenenler': 'နှစ်သက်သူများ',
  'Henüz beğeni yok': 'နှစ်သက်မှု မရှိသေးပါ',
  'Bu gönderiyi ilk beğenen sen ol': 'ဤပို့စ်ကို ပထမဆုံး နှစ်သက်သူ ဖြစ်ပါ',
  'Bu gönderiye yanıt': 'ဤပို့စ်အတွက် စာပြန်ချက်',
  'Spoiler içeren gönderi': 'စပွိုင်လာပါဝင်သော ပို့စ်',
  'Görsel gönderi': 'ဓာတ်ပုံပို့စ်',
  'Bu yorumu profilimde gizle':
      'ဤမှတ်ချက်ကို ကျွန်ုပ်၏ပရိုဖိုင်တွင် ဖျောက်ထားပါ',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'မှတ်ချက်သည် ဇာတ်လမ်းတွဲနှင့် ရုပ်ရှင်စာမျက်နှာတွင် ဆက်ရှိနေမည်',
  'Bu yorumu sil': 'ဤမှတ်ချက်ကို ဖျက်ပါ',
  'Yorum profilinde gizlendi':
      'မှတ်ချက်ကို သင်၏ပရိုဖိုင်တွင် ဖျောက်ထားပြီးပါပြီ',
  'Geri al': 'ပြန်ပြင်ရန်',
  'Yorum silinsin mi?': 'မှတ်ချက်ကို ဖျက်မလား?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'ဤမှတ်ချက်ကို နေရာအနှံ့မှ အပြီးအပိုင် ဖျက်လိုက်ပါမည်။ ပြန်ရရှိနိုင်မည်မဟုတ်ပါ။',
  'Yorum silindi': 'မှတ်ချက် ဖျက်ပြီးပါပြီ',
  'Yorum profilinde tekrar görünüyor':
      'မှတ်ချက်ကို သင်၏ပရိုဖိုင်တွင် ပြန်လည်တွေ့မြင်ရသည်',
  'Gizlenen yorumun yok': 'ဖျောက်ထားသော မှတ်ချက် မရှိပါ',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'သင်၏ပရိုဖိုင်ရှိ မှတ်ချက်တဘ်တွင် ပို့စ်ကို ဖိထားခြင်းဖြင့် ဖျောက်ထားသော မှတ်ချက်များ ဤနေရာတွင် စုပုံလာမည်။',
  'Gizlenen yorumlar': 'ဖျောက်ထားသော မှတ်ချက်များ',
  'Gönderiye git': 'ပို့စ်သို့ သွားရန်',
  'Tekrar göster': 'ပြန်ပြရန်',
  'Yanıtlarımı gizle': 'ကျွန်ုပ်၏ပြန်စာများကို ဖျောက်ထားပါ',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'အခြားသူများ၏ ပို့စ်များတွင် သင်ရေးသော ပြန်စာများကို သင့်ကိုသာ မြင်နိုင်သည်',
  'Profilinde gizlediğin yorumları tekrar göster':
      'သင်၏ပရိုဖိုင်တွင် ဖျောက်ထားသော မှတ်ချက်များကို ပြန်ပြပါ',
  'Sıralama': 'အစီအစဉ်',
  'Önerilen': 'အကြံပြုထားသော',
  'Kronolojik': 'အချိန်အလိုက်',
  'Gelen mesaj istekleri': 'ဝင်လာသော မက်ဆေ့ခ်ျ တောင်းဆိုမှုများ',
  'Mesaj isteğin yok': 'မက်ဆေ့ခ်ျ တောင်းဆိုမှု မရှိပါ',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'သင်မလိုက်ကြည့်သူများထံမှ မက်ဆေ့ခ်ျများ ဤနေရာတွင် ပေါ်ပါမည်။',
  'Çevrimiçi durumumu gizle': 'ကျွန်ုပ်၏ အွန်လိုင်းအခြေအနေကို ဖျောက်ထားရန်',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'အခြားသူများသည် မက်ဆေ့ခ်ျများတွင် သင့်အွန်လိုင်းအခြေအနေနှင့် နောက်ဆုံးတွေ့ချိန်ကို မမြင်ရပါ',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'ကျွန်ုပ်တို့၏ ပထမဆုံး အသုံးပြုသူများထဲမှ တစ်ဦးဖြစ်သည်။ သူ၏ တုံ့ပြန်ချက်များက အက်ပ်ကို ယနေ့ပုံစံဖြစ်လာစေခဲ့သည်။',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'သင်သည် ကျွန်ုပ်တို့၏ ပထမဆုံး အသုံးပြုသူများထဲမှ တစ်ဦးဖြစ်သည်။ သင်၏ တုံ့ပြန်ချက်များက အက်ပ်ကို ယနေ့ပုံစံဖြစ်လာစေခဲ့သည်။',
  'İleri': 'ရှေ့သို့',
  'Önceki': 'ယခင်',
  'Sonraki': 'နောက်',
  'Seçilen dosya okunamadı': 'ရွေးထားသောဖိုင်ကို ဖတ်၍မရပါ',
  'Video açılamadı': 'ဗီဒီယိုကို ဖွင့်၍မရပါ',
  'En fazla {} medya seçebilirsin': 'အများဆုံး {} ခု ရွေးနိုင်သည်',
  'Hiçbir medya yüklenemedi': 'မီဒီယာ တင်၍ မရပါ',
  'Seçimi kaldır': 'ရွေးချယ်မှု ဖယ်ရှားရန်',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'မှတ်ချက်တစ်ခုတွင် စုစုပေါင်း {} MB တင်နိုင်သည်',
  '{} dosya okunamadı': 'ဖိုင် {} ခု ဖတ်၍ မရပါ',
  '{} medya eklendi, {} yüklenemedi': '{} ခု ထည့်ပြီး၊ {} ခု မအောင်မြင်ပါ',
  'Kırp': 'ဖြတ်ညှပ်',
  'Çiz': 'ရေးဆွဲ',
  'Metin': 'စာသား',
  'Emoji': 'အီမိုဂျီ',
  'Yinele': 'ပြန်လုပ်',
  'Daha fazla': 'နောက်ထပ်',
  'Hazırlanıyor…': 'ပြင်ဆင်နေသည်…',
  'Düzenlemeden çık?': 'တည်းဖြတ်မှုမှ ထွက်မလား။',
  'Yaptığın değişiklikler kaybolacak.': 'သင်ပြင်ဆင်ထားသည်များ ပျောက်သွားပါမည်။',
  'Çık': 'ထွက်ရန်',
  'Serbest çizim': 'လွတ်လပ်ရေးဆွဲ',
  'Ok': 'မြား',
  'Dikdörtgen': 'ထောင့်မှန်စတုဂံ',
  'Daire': 'စက်ဝိုင်း',
  'Bulanıklaştır': 'မှုန်ဝါးစေရန်',
  'Pikselleştir': 'ပစ်ဆယ်ပြု',
  'Silgi': 'ခဲဖျက်',
  'Çizgi kalınlığı': 'မျဉ်းအထူ',
  'Saydamlık': 'အလင်းပိတ်မှု',
  'Dolgu': 'ဖြည့်',
  'Renk': 'အရောင်',
  'Döndür': 'လှည့်',
  'Yansıt': 'လှန်',
  'Oran': 'အချိုး',
  'Sıfırla': 'ပြန်လည်သတ်မှတ်',
  'Serbest': 'လွတ်လပ်',
  'Metin yaz...': 'စာသားရိုက်ပါ...',
  'Hizala': 'ညှိ',
  'Arka plan': 'နောက်ခံ',
  'Emoji ara...': 'အီမိုဂျီ ရှာပါ...',
  'Son kullanılanlar': 'မကြာသေးမီက',
  'İfadeler ve insanlar': 'အပြုံးများနှင့် လူများ',
  'Hayvanlar ve doğa': 'တိရစ္ဆာန်များနှင့် သဘာဝ',
  'Yiyecek ve içecek': 'အစားအသောက်',
  'Etkinlikler': 'လှုပ်ရှားမှုများ',
  'Seyahat ve yerler': 'ခရီးသွားခြင်းနှင့် နေရာများ',
  'Nesneler': 'အရာဝတ္ထုများ',
  'Semboller': 'သင်္ကေတများ',
  'Bayraklar': 'အလံများ',
  'Görseli düzenle': 'ဓာတ်ပုံကို တည်းဖြတ်ရန်',
  'Düzenlendi': 'တည်းဖြတ်ပြီး',
  'Düzenlenemedi': 'တည်းဖြတ်၍မရပါ',
  'Düzenlenen görsel çok büyük': 'တည်းဖြတ်ထားသော ဓာတ်ပုံ ကြီးလွန်းသည်',
  'Videoyu düzenle': 'ဗီဒီယို တည်းဖြတ်ရန်',
  'Sesi kapat': 'အသံပိတ်ရန်',
  'Sesi aç': 'အသံဖွင့်ရန်',
  'İptal ediliyor…': 'ပယ်ဖျက်နေသည်…',
  'Bu biraz sürebilir': 'အချိန်အနည်းငယ် ကြာနိုင်သည်',
  'Video çok büyük': 'ဗီဒီယို အလွန်ကြီးသည်',
  'Video hazırlanamadı': 'ဗီဒီယို ပြင်ဆင်၍ မရပါ',
  'Başlangıç': 'အစ',
  'Bitiş': 'အဆုံး',
  'En çok {} saniye seçebilirsin': 'အများဆုံး စက္ကန့် {} ရွေးနိုင်သည်',
  'Dosya en fazla {} MB olabilir': 'ဖိုင်သည် အများဆုံး {} MB ဖြစ်နိုင်သည်',
  'Medya ekle': 'မီဒီယာ ထည့်ရန်',
  'Seçili medya kalmadı': 'ရွေးထားသော မီဒီယာ မရှိပါ',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'သင့်မှတ်ချက်တွင် ထည့်ရန် ဓာတ်ပုံ သို့မဟုတ် ဗီဒီယို ရွေးပါ။',
  'Medya seç': 'မီဒီယာ ရွေးရန်',
  'Daha fazla ekle': 'ထပ်ထည့်ရန်',
  'Medya seçilemedi': 'မီဒီယာ မရွေးနိုင်ပါ',
  'Favori oyuncular': 'အနှစ်သက်ဆုံး သရုပ်ဆောင်များ',
  'Henüz favori oyuncun yok': 'အနှစ်သက်ဆုံး သရုပ်ဆောင် မရှိသေးပါ',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'သရုပ်ဆောင်စာမျက်နှာကို ဖွင့်ပြီး ညာဘက်အပေါ်ရှိ နှလုံးကို နှိပ်ပါ။',
  '{} yapımdan {} tanesini izledin': '{} ခုအနက် {} ခု ကြည့်ပြီး',
  'izledin': 'ကြည့်ပြီး',
  'İzlemedin': 'မကြည့်ရသေးပါ',
  'Yapım bulunamadı': 'ဇာတ်လမ်း မတွေ့ပါ',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'ဤသူတွင် ပြသရန် ဇာတ်လမ်းတွဲ သို့မဟုတ် ရုပ်ရှင် မရှိပါ။',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'ကြည့်ရှုမှတ်တမ်းသည် သင့်အကောင့်နှင့် ချိတ်ဆက်ထားပြီး ဤစာရင်းသည် သင့်အတွက်သာ ဖြစ်သည်။',
  'Hesabın kalıcı olarak askıya alındı':
      'သင့်အကောင့်ကို အပြီးအပိုင် ရပ်ဆိုင်းထားသည်',
  'Hesabın geçici olarak askıya alındı': 'သင့်အကောင့်ကို ယာယီ ရပ်ဆိုင်းထားသည်',
  'Hesabın askıya alındı': 'သင့်အကောင့် ရပ်ဆိုင်းခံထားရသည်',
  'Sebep': 'အကြောင်းရင်း',
  'Kalan süre': 'ကျန်ချိန်',
  'Süre dolunca hesabın kendiliğinden açılır':
      'အချိန်ပြည့်သည်နှင့် အကောင့် အလိုအလျောက် ပြန်ဖွင့်ပါမည်',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'ဤအချိန်အတွင်း ဖတ်နိုင်သော်လည်း ပို့စ်၊ မှတ်ချက် သို့မဟုတ် စာပို့၍ မရပါ။',
  'Anladım': 'နားလည်ပါပြီ',
  'Ayrıntı': 'အသေးစိတ်',
  '{} dakika': '{} မိနစ်',
  'birkaç saniye': 'စက္ကန့်အနည်းငယ်',
  'Karara itiraz et': 'ဤဆုံးဖြတ်ချက်ကို အယူခံပါ',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'ဤပြစ်ဒဏ်ကို အဘယ်ကြောင့် ဖယ်ရှားသင့်သည်ကို ရှင်းပြပါ',
  'İtirazını gönder': 'သင့်အယူခံကို ပို့ပါ',
  'İtirazın incelemede': 'သင့်အယူခံကို စိစစ်နေသည်',
  'İtirazın reddedildi': 'သင့်အယူခံ ပယ်ချခံရသည်',
  'İtirazın alındı, inceleniyor': 'သင့်အယူခံ ရရှိပြီး စိစစ်နေသည်',
  'İtiraz en az 10 karakter olmalı':
      'အယူခံသည် အနည်းဆုံး စာလုံး ၁၀ လုံး ရှိရမည်',
  'Yükleniyor...': 'ဖွင့်နေသည်...',
  'Bu bölüme puan ver': 'ဤအပိုင်းကို အဆင့်သတ်မှတ်ပါ',
  '{} kişi puanladı': '{} ဦး အဆင့်သတ်မှတ်ပြီး',
  'Bölüm izlendi olarak işaretlendi':
      'အပိုင်းကို ကြည့်ပြီးအဖြစ် မှတ်သားလိုက်ပါပြီ',
  'Sesli ara': 'အသံခေါ်ဆိုမှု',
  'Görüntülü ara': 'ဗီဒီယိုခေါ်ဆိုမှု',
  'Çalıyor...': 'ခေါ်နေသည်...',
  'Bağlanıyor...': 'ချိတ်ဆက်နေသည်...',
  'Cevapla': 'ဖြေပါ',
  'Reddet': 'ငြင်းပယ်ပါ',
  'Sessize al': 'အသံပိတ်',
  'Hoparlör': 'စပီကာ',
  'Kamerayı kapat': 'ကင်မရာပိတ်ပါ',
  'Kamerayı çevir': 'ကင်မရာပြောင်းပါ',
  'Cevap yok': 'အဖြေမရှိပါ',
  'Arama reddedildi': 'ခေါ်ဆိုမှု ငြင်းပယ်ခံရသည်',
  'Meşgul': 'အလုပ်များနေသည်',
  'Bağlanılamadı': 'ချိတ်ဆက်၍မရပါ',
  'Arama iptal edildi': 'ခေါ်ဆိုမှု ပယ်ဖျက်ခဲ့သည်',
  'Arama geçmişi': 'ခေါ်ဆိုမှု မှတ်တမ်း',
  'Gelen arama': 'အဝင်ခေါ်ဆိုမှု',
  'Giden arama': 'အထွက်ခေါ်ဆိုမှု',
  'Cevapsız arama': 'လွတ်သွားသော ခေါ်ဆိုမှု',
  'Arama şu anda kullanılamıyor': 'ခေါ်ဆိုမှုကို ယခု မရနိုင်ပါ',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'ဗီဒီယိုခေါ်ဆိုမှု ယခု ပိတ်ထားသည်၊ အသံဖြင့် ခေါ်နိုင်သည်',
  'Bu kullanıcıyı arayamazsın': 'ဤအသုံးပြုသူကို ခေါ်၍မရပါ',
  'Aramak için karşılıklı takipleşmelisiniz':
      'ခေါ်ဆိုရန် နှစ်ဦးစလုံး အပြန်အလှန် စောင့်ကြည့်ရမည်',
  'Bu kullanıcı şu anda aranamıyor': 'ဤအသုံးပြုသူကို ယခု ခေါ်၍မရပါ',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'လွတ်သွားသော ခေါ်ဆိုမှု များလွန်းသည်။ {} အကြာတွင် ပြန်ကြိုးစားပါ',
  'Zaten bir aramadasın': 'သင် ခေါ်ဆိုမှုတစ်ခုတွင် ရှိနေပြီးဖြစ်သည်',
  'Arama için mikrofon izni gerekiyor':
      'ခေါ်ဆိုရန် မိုက်ခရိုဖုန်း ခွင့်ပြုချက် လိုအပ်သည်',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'ဗီဒီယိုခေါ်ဆိုရန် ကင်မရာနှင့် မိုက်ခရိုဖုန်း ခွင့်ပြုချက် လိုအပ်သည်',
  'Arama başlatılamadı': 'ခေါ်ဆိုမှု မစတင်နိုင်ပါ',
  'Kullanıcı bulunamadı': 'အသုံးပြုသူ မတွေ့ပါ',
  'Kendini arayamazsın': 'ကိုယ့်ကိုယ်ကို ခေါ်၍မရပါ',
  'Arama artık geçerli değil': 'ဤခေါ်ဆိုမှု အကျုံးမဝင်တော့ပါ',
  'Bu aramanın tarafı değilsin': 'သင် ဤခေါ်ဆိုမှု၏ အစိတ်အပိုင်း မဟုတ်ပါ',
  'Arama bulunamadı': 'ခေါ်ဆိုမှု မတွေ့ပါ',
  'Çok fazla istek, biraz bekle': 'တောင်းဆိုမှု များလွန်းသည်၊ ခဏစောင့်ပါ',
  'Bağlantı koptu': 'ချိတ်ဆက်မှု ပြတ်တောက်သွားသည်',
  'Arama süre sınırına ulaştı': 'ခေါ်ဆိုမှု အချိန်ကန့်သတ်ချက်သို့ ရောက်ပြီ',
  'Arama en fazla 4 saat sürebilir':
      'ခေါ်ဆိုမှုတစ်ခု အများဆုံး ၄ နာရီ ကြာနိုင်သည်',
  'Arama sona erdi': 'ခေါ်ဆိုမှု ပြီးဆုံးသွားပြီ',
  'Sesli arama': 'အသံခေါ်ဆိုမှု',
  'Görüntülü arama': 'ဗီဒီယိုခေါ်ဆိုမှု',
  'Gelen aramalar': 'အဝင်ခေါ်ဆိုမှုများ',
  'Sesli ve görüntülü arama bildirimleri':
      'အသံနှင့် ဗီဒီယိုခေါ်ဆိုမှု အသိပေးချက်များ',
  '{} sa': '{} နာရီ',
  'Sesli ve Görüntülü Aramalar': 'အသံနှင့် ဗီဒီယိုခေါ်ဆိုမှုများ',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'ခေါ်ဆိုမှု အကြောင်းအရာကို ဘယ်တော့မှ မှတ်တမ်းမတင်ပါ။ အသံနှင့် ဗီဒီယိုသည် စက်များအကြား အစအဆုံး ကုဒ်ဝှက်ထားပြီး (DTLS-SRTP) စီးဆင်းသည်။ ကျွန်ုပ်တို့၏ ဆာဗာများသည် ၎င်းကို ဖော်ထုတ်၊ နားထောင်၊ သိမ်းဆည်း၍ မရပါ။',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'ခေါ်ဆိုမှု မက်တာဒေတာသာ သိမ်းထားသည်- မည်သူနှင့်၊ မည်သည့်ဦးတည်ချက်၊ မည်သည့်အချိန်နှင့် မည်မျှကြာသည်။ ဤမှတ်တမ်းများသည် ၉၀ ရက်အကြာတွင် အလိုအလျောက် ဖျက်သွားသည်။',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'တိုက်ရိုက်ချိတ်ဆက်၍ မရပါက အသံနှင့် ဗီဒီယိုသည် ကုဒ်ဝှက်ထားသည့်အတိုင်း ထပ်ဆင့်ဆာဗာ (TURN) မှတစ်ဆင့် ဖြတ်သွားသည်။ ထပ်ဆင့်ဆာဗာကလည်း အကြောင်းအရာကို ဖော်ထုတ်၊ မှတ်တမ်းတင်၍ မရပါ။',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'မိုက်ခရိုဖုန်းကို အသံ သို့မဟုတ် ဗီဒီယိုခေါ်ဆိုစဉ်တွင်သာ၊ ကင်မရာကို ဗီဒီယိုခေါ်ဆိုစဉ်တွင်သာ အသုံးပြုသည်။ ခေါ်ဆိုမှု ပြီးလျှင် နှစ်ခုစလုံး ပိတ်သွားသည်။',
  'Takip ettiğin {} kişi izledi': 'သင်စောင့်ကြည့်နေသူ {} ဦး ကြည့်ပြီးပါပြီ',
  'Yorum yaz...': 'မှတ်ချက် ရေးပါ...',
  'Sıradaki bölüm': 'နောက်တစ်ပိုင်း',
  'Doğrulanmış testçi': 'အတည်ပြုပြီး စမ်းသပ်သူ',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'စောင့်ကြည့်ခြင်း၊ နှစ်သက်ခြင်း၊ ပြန်စာ၊ စာနှင့် တဂ် အကြောင်းကြားချက်များ',
  'Sen': 'သင်',
  'Aradığınız kişide sesli arama devre dışı':
      'ဤသူထံတွင် အသံခေါ်ဆိုမှု ပိတ်ထားသည်',
  'Aradığınız kişide görüntülü arama devre dışı':
      'ဤသူထံတွင် ဗီဒီယိုခေါ်ဆိုမှု ပိတ်ထားသည်',
  'Sesli aramalara izin ver': 'အသံခေါ်ဆိုမှုများကို ခွင့်ပြုရန်',
  'Görüntülü aramalara izin ver': 'ဗီဒီယိုခေါ်ဆိုမှုများကို ခွင့်ပြုရန်',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'ပိတ်ထားပါက မည်သူမျှ သင့်ကို အသံဖြင့် မခေါ်နိုင်ပါ။ ခေါ်သူသည် အသိပေးချက်ကို မြင်ရမည်',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'ပိတ်ထားပါက မည်သူမျှ သင့်ကို ဗီဒီယိုဖြင့် မခေါ်နိုင်ပါ။ ခေါ်သူသည် အသိပေးချက်ကို မြင်ရမည်',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'အသံခေါ်ဆိုမှု ပိတ်ထားသည်။ ဆက်တင်များ > ကိုယ်ရေးအချက်အလက် မှ ဖွင့်နိုင်သည်။',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'ဗီဒီယိုခေါ်ဆိုမှု ပိတ်ထားသည်။ ဆက်တင်များ > ကိုယ်ရေးအချက်အလက် မှ ဖွင့်နိုင်သည်။',
  'Sesli ve görüntülü arama': 'အသံနှင့် ဗီဒီယိုခေါ်ဆိုမှု',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'ဧည့်သည်အကောင့်များ ခေါ်ဆိုလို့မရပါ။ အကောင့်ဖွင့်ပါက သုံးနိုင်ပါသည်။',
  'Misafir hesaplar aranamaz': 'ဧည့်သည်အကောင့်များကို ခေါ်ဆိုလို့မရပါ',
  'Puan dağılımı': 'အမှတ် ဖြန့်ဝေမှု',
  '{} yıldız': 'ကြယ် {} ပွင့်',
  'Yakında gelecek': 'မကြာမီ လာမည်',
  '{} {} yayınlandı': '{} {} ထွက်ပြီ',
  'Yeni bölüm yayınlandı': 'အပိုင်းအသစ် ထွက်ပြီ',
  'Yeni bölümler': 'အပိုင်းအသစ်များ',
  'Geri': 'နောက်သို့',
  'Karşılamayı kapat': 'ကြိုဆိုမှုကို ပိတ်ရန်',
  'Adım {} / {}': 'အဆင့် {} / {}',
  'Hadi başlayalım': 'စတင်ကြရအောင်',
  'Kaydet ve devam': 'သိမ်းပြီး ဆက်လုပ်ပါ',
  '{} tanesini ekle': '{} ခု ထည့်ရန်',
  'Şimdilik geç': 'ယခုအတွက် ကျော်ရန်',
  'Doğum tarihin ne zaman?': 'သင့်မွေးနေ့ ဘယ်တော့လဲ?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'အသက်အရွယ်နှင့် ကိုက်ညီသော အကြောင်းအရာများ ပြသရန်နှင့် မွေးနေ့ ဆုတောင်းပေးရန် မေးခြင်းဖြစ်သည်။',
  'Gün': 'ရက်',
  'Ay': 'လ',
  'Yıl': 'နှစ်',
  'Doğum yılımı paylaşmak istemiyorum': 'မွေးသက္ကရာဇ်ကို မပြပါနှင့်',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'သင့်မွေးနေ့ကို ပရိုဖိုင်တွင် အများမြင်အောင် မပြပါ။ အသက်အရွယ်နှင့် ကိုက်ညီသော အကြောင်းအရာနှင့် မွေးနေ့ဆုတောင်းအတွက်သာ အသုံးပြုသည်။',
  'Ocak': 'ဇန်နဝါရီ',
  'Şubat': 'ဖေဖော်ဝါရီ',
  'Mart': 'မတ်',
  'Nisan': 'ဧပြီ',
  'Mayıs': 'မေ',
  'Haziran': 'ဇွန်',
  'Temmuz': 'ဇူလိုင်',
  'Ağustos': 'ဩဂုတ်',
  'Eylül': 'စက်တင်ဘာ',
  'Ekim': 'အောက်တိုဘာ',
  'Kasım': 'နိုဝင်ဘာ',
  'Aralık': 'ဒီဇင်ဘာ',
  'Verilerini yanında getir': 'သင့်ဒေတာများကို ယူဆောင်လာပါ',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'အခြားအက်ပ်တစ်ခုတွင် ကြည့်ပြီးသားများကို မှတ်သားထားလျှင် ဤနေရာသို့ ရွှေ့ယူနိုင်သည်။ အစကနေ ပြန်စရန် မလိုပါ။',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt နှင့် Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'ထုတ်ယူထားသော ZIP ဖိုင်ကို ရွေးပါ။ ကြည့်ပြီးသားများ၊ အဆင့်သတ်မှတ်ချက်များနှင့် စာရင်းများ ရောက်လာပါမည်။',
  'Aktarılıyor...': 'သွင်းယူနေသည်...',
  'ZIP dosyası seç': 'ZIP ဖိုင် ရွေးရန်',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'အလျင်စလို မလိုပါ - ဤအရာကို နောက်မှ ဆက်တင်များ > ကိုယ့်ဒေတာများ မှလည်း လုပ်နိုင်သည်။',
  'Hangi filmleri izledin?': 'ဘယ်ရုပ်ရှင်တွေ ကြည့်ဖူးလဲ?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'အကြည့်အများဆုံးများ ဒီမှာ ရှိသည်။ ထိလိုက်သည်များကို ကြည့်ပြီးသားများထဲ ထည့်လိုက်ပါမည်။',
  'SERİ FİLMLER': 'ရုပ်ရှင်စီးရီးများ',
  'Serilerden {} film eklendi': 'စီးရီးများမှ ရုပ်ရှင် {} ကား ထည့်ပြီး',
  'Film listesi yüklenemedi': 'ရုပ်ရှင်စာရင်း မဖွင့်နိုင်ပါ',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'ဤအဆင့်ကို ကျော်နိုင်သည်၊ နောက်မှ လိုသည်များ ထည့်နိုင်သည်။',
  '{} film izlediklerine eklendi':
      'ရုပ်ရှင် {} ကား ကြည့်ပြီးသားများထဲ ထည့်ပြီး',
  'Film serileri': 'ရုပ်ရှင်စီးရီးများ',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'စီးရီးတစ်ခုကို အစမှအဆုံး ကြည့်ပြီးလျှင် တစ်ချက်ထိရုံဖြင့် ထည့်ပါ။',
  'Seri bulunamadı': 'စီးရီး မတွေ့ပါ',
  'Daha sonra tekrar deneyebilirsin.': 'နောက်မှ ထပ်စမ်းကြည့်နိုင်သည်။',
  '{} film': 'ရုပ်ရှင် {} ကား',
  'Eklendi': 'ထည့်ပြီး',
  'Tümünü izledim': 'အားလုံး ကြည့်ပြီး',
  'Peki ya diziler?': 'ဇာတ်လမ်းတွဲများကော?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'ကြည့်ပြီးသားများကို မှတ်ပါ။ ရွေးလေလေ ဆင်တူသည်များ ယူလာပေးပါမည်။',
  'Dizi listesi yüklenemedi': 'ဇာတ်လမ်းတွဲစာရင်း မဖွင့်နိုင်ပါ',
  'Seçtiklerine benzeyenler': 'ရွေးထားသည်များနှင့် ဆင်တူသည်များ',
  'Her şey hazır': 'အားလုံး အဆင်သင့်',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'dizi.jpg တွင် ဘာတွေ လုပ်နိုင်သလဲ အမြန် တစ်ချက် ကြည့်လိုက်ပါ။',
  'Profilini tamamla': 'ပရိုဖိုင်ကို ပြည့်စုံအောင် လုပ်ပါ',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'ဆက်တင်များမှ ကိုယ်ရေးအကျဉ်း၊ ပရိုဖိုင်ဓာတ်ပုံနှင့် ဖုံးအုပ်ပုံ ထည့်နိုင်သည်။',
  'Takvimin seni bekliyor': 'ပြက္ခဒိန်က သင့်ကို စောင့်နေသည်',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'ကြည့်နေသော ဇာတ်လမ်းတွဲများ၏ အပိုင်းအသစ်များ ပြက္ခဒိန်ထဲ ရောက်လာမည်၊ အသိပေးချက်ဖြင့် အကြောင်းကြားပါမည်။',
  'Puan ver, yorum yaz': 'အဆင့်ပေးပါ၊ မှတ်ချက်ရေးပါ',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'အပိုင်းလိုက် အဆင့်ပေးပါ၊ စပွိုင်လာ အကာအကွယ်ဖြင့် မှတ်ချက်ရေးပါ၊ စာရင်းများ ဖန်တီးပါ။',
  'Verilerin sende kalır': 'ဒေတာများ သင့်လက်ထဲမှာပဲ ရှိသည်',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'သင့်ဒေတာများကို သင့်အကောင့်နှင့်သာ ချိတ်ဆက်ထားသည်၊ ရောင်းချခြင်း မရှိပါ။ ဆက်တင်များမှ အားလုံးကို ဒေါင်းလုဒ်လုပ်နိုင်သည် သို့မဟုတ် အကောင့်ကို လုံးဝ ဖျက်နိုင်သည်။',
  'Engellenen kullanıcılar': 'ပိတ်ဆို့ထားသော အသုံးပြုသူများ',
  'Engellediğin kişileri gör, engeli kaldır':
      'ပိတ်ဆို့ထားသူများကို ကြည့်ပါ၊ ပိတ်ဆို့မှု ဖြုတ်ပါ',
  'Engellediğin kimse yok': 'မည်သူ့ကိုမျှ ပိတ်ဆို့ထားခြင်း မရှိပါ',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'အသုံးပြုသူတစ်ဦးကို ၎င်း၏ ပရိုဖိုင်ရှိ အစက်သုံးစက် မီနူးမှ ပိတ်ဆို့နိုင်သည်။',
  '@{} engellensin mi?': '@{} ကို ပိတ်ဆို့မလား?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'တစ်ဦးနှင့်တစ်ဦး၏ ပို့စ်များ၊ မှတ်ချက်များနှင့် ပရိုဖိုင်ကို မမြင်နိုင်တော့ပါ။ စာများနှင့် ခေါ်ဆိုမှုများလည်း မရောက်တော့ပါ။ နောက်လိုက်ဆက်နွယ်မှု ရှိပါက ပြတ်တောက်သွားပြီး ပိတ်ဆို့မှု ဖြုတ်လျှင်လည်း ပြန်မလာတော့ပါ။',
  'Bu kullanıcıyı engelledin': 'ဤအသုံးပြုသူကို ပိတ်ဆို့ထားသည်',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'ထိုသူ၏ ပို့စ်များ၊ မှတ်ချက်များနှင့် စာများကို သင် မမြင်ပါ။ ထိုသူကလည်း သင့်အရာများကို မမြင်နိုင်ပါ။',
  '{} yeni bir yapımda: {}': '{} သည် ဇာတ်ကားအသစ်တွင်: {}',
  'Favori kişinden yeni yapım': 'အနှစ်သက်ဆုံးသူ၏ ဇာတ်ကားအသစ်',
  '{} için bildirimler': '{} အတွက် အသိပေးချက်များ',
  'Tüm bildirimler': 'အသိပေးချက် အားလုံး',
  'Uygulamada ve telefonda': 'အက်ပ်ထဲနှင့် ဖုန်းပေါ်တွင်',
  'Yalnız uygulama içi': 'အက်ပ်ထဲတွင်သာ',
  'Telefon bildirimi gönderilmez': 'ဖုန်းအသိပေးချက် မပို့ပါ',
  'Kapalı': 'ပိတ်',
  'Bu kişi için bildirim yok': 'ဤသူအတွက် အသိပေးချက် မရှိပါ',
  'Favori kişilerin yeni yapımları': 'အနှစ်သက်ဆုံးသူများ၏ ဇာတ်ကားအသစ်များ',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'ပိတ်ထားပါက မည်သူမျှ သင့်ကို အသံဖြင့် မခေါ်နိုင်ပါ။ ခေါ်သူသည် "ပိတ်ထားသည်" အသိပေးချက်ကို မြင်ရမည်',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'ပိတ်ထားပါက မည်သူမျှ သင့်ကို ဗီဒီယိုဖြင့် မခေါ်နိုင်ပါ။ ခေါ်သူသည် "ပိတ်ထားသည်" အသိပေးချက်ကို မြင်ရမည်',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'ကျွန်ုပ်၏ လှုပ်ရှားမှု',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'သင့် ကြိုက်မှု၊ မှတ်ချက်နှင့် ကြည့်ရှုမှုများ တစ်နေရာတည်းတွင်',
  'Henüz hareketin yok': 'လှုပ်ရှားမှု မရှိသေးပါ',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'သင် ကြိုက်သမျှ၊ မှတ်ချက်ပေးသမျှ၊ ကြည့်သမျှ ဤနေရာတွင် စုဆောင်းသည်။',
  'Bu süzgeçte hareket yok': 'ဤစစ်ထုတ်မှုတွင် လှုပ်ရှားမှု မရှိပါ',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'အခြားအမျိုးအစားကို ရွေးပါ သို့မဟုတ် "အားလုံး" သို့ ပြန်သွားပါ။',
  'Hepsi': 'အားလုံး',
  'Puan': 'အဆင့်သတ်မှတ်ချက်',
  'Tepki': 'တုံ့ပြန်မှု',
  'İzleme': 'ကြည့်ရှုမှု',
  'Durum': 'အခြေအနေ',
  'Liste': 'စာရင်း',
  'Yorum yaptın': 'မှတ်ချက် ပေးခဲ့သည်',
  'Yorumu beğendin': 'မှတ်ချက်ကို ကြိုက်ခဲ့သည်',
  '{} puan verdin': '{} အမှတ် ပေးခဲ့သည်',
  'Tepki verdin': 'တုံ့ပြန်ခဲ့သည်',
  'Listene ekledin': 'စာရင်းထဲ ထည့်ခဲ့သည်',
  'Takip etmeye başladın': 'စောင့်ကြည့်ရန် စတင်ခဲ့သည်',
  '"İzleyeceğim" işaretledin': '"ကြည့်မယ်" ဟု မှတ်သားခဲ့သည်',
  '"İzliyorum" işaretledin': '"ကြည့်နေတယ်" ဟု မှတ်သားခဲ့သည်',
  '"Bitirdim" işaretledin': '"ပြီးအောင် ကြည့်ပြီးပြီ" ဟု မှတ်သားခဲ့သည်',
  '"Bıraktım" işaretledin': '"ရပ်လိုက်ပြီ" ဟု မှတ်သားခဲ့သည်',
  'Silinmiş içerik': 'ဖျက်ပြီးသော အကြောင်းအရာ',
  'şimdi': 'ယခု',
  '{} g': '{} ရက်',
  '{} y': '{} နှစ်',
  'İstatistiklerim': 'ကျွန်ုပ်၏ စာရင်းအင်း',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'သင့်ပို့စ်များ၏ ကြည့်ရှုမှုနှင့် ကြိုက်နှစ်သက်မှု',
  'Henüz gönderin yok': 'သင့်တွင် ပို့စ် မရှိသေးပါ',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'သင် စီးရီး သို့မဟုတ် ရုပ်ရှင်တစ်ခုကို မှတ်ချက်ရေးလိုက်သည်နှင့် ကြည့်ရှုမှုနှင့် ကြိုက်နှစ်သက်မှု အရေအတွက်များ ဤနေရာတွင် စတင်စုဆောင်းပါမည်။',
  'Tüm zamanlar': 'အချိန်အားလုံး',
  'Son {} gün': 'နောက်ဆုံး {} ရက်',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'ကြည့်ရှုမှု မှတ်တမ်း စတင်စုဆောင်းခြင်း မရှိသေးပါ။ ပထမနေ့၏ ဒေတာကို မနက်ဖြန် တွေ့ရပါမည်။',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'ကြည့်ရှုမှု မှတ်တမ်းသည် {} မှစ၍ စုဆောင်းနေသည် ({} ရက်စာ ဒေတာရှိသည်)၊ ထို့ကြောင့် {} ရက်စာ ကိန်းဂဏန်းမှာ မပြည့်စုံသေးပါ။',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'ကြိုက်နှစ်သက်မှု မှတ်တမ်းကို {} မှစ၍ မှတ်တမ်းတင်ထားသည်။',
  'Bu dönemde gösterilecek gönderi yok.': 'ဤကာလအတွက် ပြသရန် ပို့စ် မရှိပါ။',
  'eksik veri': 'ဒေတာ မပြည့်စုံပါ',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'သင့်ပရိုဖိုင်ရှိ ကြည့်ထားသော စီးရီးနှင့် ရုပ်ရှင်များ၊ ကြည့်ရှုမှု ရေတွက်ချက်များ၊ မျက်နှာပြင်အချိန်နှင့် ကိုက်ညီမှုကတ်ကို အခြားသူများ မမြင်ရပါ',
  'Takipçi listemi gizle': 'ကျွန်ုပ်၏ စောင့်ကြည့်သူစာရင်းကို ဖျောက်ရန်',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'သင့်ကို မည်သူများ စောင့်ကြည့်နေသည်ကို အခြားသူများ မမြင်နိုင်ပါ။ စောင့်ကြည့်သူ အရေအတွက်မူ ဆက်လက်ပေါ်နေပါမည်',
  'Takip ettiklerimi gizle': 'ကျွန်ုပ် စောင့်ကြည့်သူများကို ဖျောက်ရန်',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'သင် မည်သူများကို စောင့်ကြည့်နေသည်ကို အခြားသူများ မမြင်နိုင်ပါ။ စောင့်ကြည့်နေသည့် အရေအတွက်မူ ဆက်လက်ပေါ်နေပါမည်',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'ဤအသုံးပြုသူသည် မိမိ၏ စောင့်ကြည့်သူများကို လျှို့ဝှက်ထားလိုသည်။',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'ဤအသုံးပြုသူသည် မိမိ စောင့်ကြည့်နေသူများကို လျှို့ဝှက်ထားလိုသည်။',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'ပို့စ် စာရင်းအင်းများ',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'ကိုယ်ပိုင်ပို့စ်များ၏ စာရင်းအင်းများကိုသာ ကြည့်နိုင်သည်။',
  'Erişim': 'ရောက်ရှိမှု',
  'Görüntüleyen': 'ကြည့်ရှုသူများ',
  'Kaç farklı kişi gördü (son {} gün)':
      'မတူညီသူ ဘယ်နှစ်ဦး မြင်ခဲ့သလဲ (နောက်ဆုံး {} ရက်)',
  'Paylaşım': 'မျှဝေမှုများ',
  'Bu gönderiden sonra': 'ဤပို့စ်ပြီးနောက်',
  'Profil ziyareti': 'ပရိုဖိုင် ဝင်ကြည့်မှု',
  'Yeni takip': 'စောင့်ကြည့်မှုအသစ်',
  'İçeriğe tıklama': 'အကြောင်းအရာ နှိပ်မှု',
  'Spoiler perdesini açan': 'စပွိုင်လာ ဖွင့်ကြည့်သူများ',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'မျှဝေမှုများ၊ ပရိုဖိုင်ဝင်ကြည့်မှု၊ စောင့်ကြည့်မှု၊ အကြောင်းအရာနှိပ်မှု၊ ရင်းမြစ်ခွဲခြမ်းမှုနှင့် စပွိုင်လာတိုင်းတာမှုများကို {} မှစ၍ စုဆောင်းနေသည်။ ထိုမတိုင်မီအရာများကို မတိုင်းတာခဲ့ပါ။',
  'Zamana yayılmış görüntülenme': 'အချိန်အလိုက် ကြည့်ရှုမှု',
  'Görüntülenme nereden geldi': 'ကြည့်ရှုမှုများ မည်သည့်နေရာမှ လာသလဲ',
  'Kimler gördü': 'မည်သူများ မြင်ခဲ့သလဲ',
  'Günlük veri henüz birikmeye başlamadı.':
      'နေ့စဉ်ဒေတာ စုဆောင်းမှု မစတင်သေးပါ။',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'ဂရပ်အတွက် အနည်းဆုံး နှစ်ရက်စာ ဒေတာလိုအပ်သည်။ ဒေတာကို {} မှစ၍ စုဆောင်းနေသည်။',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'ကြည့်ရှုမှုအများဆုံးမှာ တင်ပြီး {} ရက်မြောက်နေ့တွင် ဖြစ်သည်: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'နေ့စဉ်ကြည့်ရှုမှုများကို {} မှစ၍ စုဆောင်းနေသည်။ ထိုမတိုင်မီအရာများကို မတိုင်းတာခဲ့ပါ။',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'ရင်းမြစ်ခွဲခြမ်းမှုကို ယခုမှစ၍ တိုင်းတာနေသည်။ ဤပို့စ်သည် အမှတ်အသားပါသော ကြည့်ရှုမှု မရရှိသေးပါ။',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'စောင့်ကြည့်သူ/စူးစမ်းမှု ခွဲခြမ်းမှုကို ယခုမှစ၍ တိုင်းတာနေသည်။ ဒေတာ မရှိသေးပါ။',
  'Takip edenler': 'စောင့်ကြည့်သူများ',
  'Keşiften gelenler': 'စူးစမ်းမှုမှ',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'ဇာတ်လမ်းတွဲ/ရုပ်ရှင် စာမျက်နှာ',
  'Paylaşılan bağlantı': 'မျှဝေထားသော လင့်ခ်',
  'yeni ölçülüyor': 'အသစ်တိုင်းတာဆဲ',
  'Kendi ortalamanla aynı düzeyde': 'ကိုယ့်ပျမ်းမျှနှင့် တူညီသည်',
  'Kendi ortalamanın %{} üstünde': 'ကိုယ့်ပျမ်းမျှထက် {}% ပိုမြင့်',
  'Kendi ortalamanın %{} altında': 'ကိုယ့်ပျမ်းမျှထက် {}% ပိုနိမ့်',
  'Etkileşim oranı': 'ပါဝင်ဆက်နွှယ်မှုနှုန်း',
  '(beğeni + yorum) ÷ görüntülenme': '(နှစ်သက်မှု + မှတ်ချက်) ÷ ကြည့်ရှုမှု',
  'Toplam görüntülenme': 'စုစုပေါင်း ကြည့်ရှုမှု',
  '{} ile {} arasında toplam {} görüntülenme':
      '{} မှ {} အတွင်း စုစုပေါင်း ကြည့်ရှုမှု {} ကြိမ်',
  'İstatistikleri gör': 'စာရင်းအင်းများ ကြည့်ရန်',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'ပို့စ်ပိုင်ရှင်အား ပြသသည့် စာရင်းအင်းများအတွက် စုပေါင်းရေတွက်ကိရိယာများအဖြစ် သိမ်းဆည်းသည်— ပို့စ်ကို အကြိမ်မည်မျှ၊ မည်သည့်မျက်နှာပြင်မှ (ဖိဒ်၊ ပရိုဖိုင်၊ မျက်နှာပြင်အပြည့်ဖိဒ်၊ ဇာတ်လမ်းတွဲ/ရုပ်ရှင်စာမျက်နှာ၊ မျှဝေထားသောလင့်ခ်) ကြည့်ရှုခဲ့သည်၊ ကြည့်ရှုသူသည် ထိုအချိန်တွင် ပို့စ်ပိုင်ရှင်ကို စောင့်ကြည့်နေခဲ့သလား၊ ပို့စ်မှ ပရိုဖိုင်/အကြောင်းအရာသို့ ကူးပြောင်းမှု၊ ပို့စ်မှတစ်ဆင့် ဖြစ်ပေါ်လာသော စောင့်ကြည့်မှု၊ မျှဝေမှုနှင့် စပွိုင်လာအကာ ဖွင့်ခြင်း။ ဤရေတွက်ကိရိယာများတွင် အသုံးပြုသူ အမှတ်အသား၊ IP လိပ်စာ သို့မဟုတ် အချိန်တံဆိပ် မပါဝင်ပါ။ မည်သူက မည်သည်ကို ပြုလုပ်ခဲ့သည်ကို စုံစမ်း၍ မရပါ။',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'ပို့စ်တစ်ခုကို မတူညီသူ ဘယ်နှစ်ဦး မြင်ခဲ့သည်ကို ရေတွက်နိုင်ရန်အတွက် ကြည့်ရှုသူတစ်ဦးလျှင် ပြန်လည်ပြောင်းလဲ၍မရသော သော့ပါအကျဉ်းချုပ်တစ်ခု (အသုံးပြုသူအမှတ်အသား သို့မဟုတ် IP လိပ်စာမှ ဆင်းသက်လာသော စာဝှက်ပညာဆိုင်ရာ အကျဉ်းချုံ့မှု) ကို ရက် ၉၀ သိမ်းဆည်းသည်။ ပို့စ်ပိုင်ရှင်အား အရေအတွက်ကိုသာ ပြသသည်။ ကြည့်ရှုသူများ၏ မည်သူမည်ဝါဖြစ်ကြောင်းကို မည်သည့်အခြေအနေတွင်မျှ မမျှဝေပါ။',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': '“ကြည့်မယ်” ထဲ ရွှေ့မလား။',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'တစ်ခုသည် ကြည့်ရန်ကျန် သို့မဟုတ် ကြည့်ပြီး ဖြစ်ရမည်။ ဆက်လုပ်ပါက ဤဇာတ်လမ်းတွဲရှိ သင့်ကြည့်ရှုမှတ်သားချက် {} ခု ပျက်သွားပါမည်။',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'တစ်ခုသည် ကြည့်ရန်ကျန် သို့မဟုတ် ကြည့်ပြီး ဖြစ်ရမည်။ ဆက်လုပ်ပါက ဤရုပ်ရှင်ရှိ သင့် “ကြည့်ပြီးပြီ” မှတ်သားချက် ပျောက်သွားပါမည်။',
  'Sil ve taşı': 'ဖျက်ပြီး ရွှေ့ရန်',
  'Yapım Ekibi': 'ရိုက်ကူးရေးအဖွဲ့',
  'Yaratıcı': 'ဖန်တီးသူ',
  'Yönetmen': 'ဒါရိုက်တာ',
  'Senaryo': 'ဇာတ်ညွှန်း',
  'Yapımcı': 'ထုတ်လုပ်သူ',
  'Yapım Firmaları': 'ထုတ်လုပ်ရေးကုမ္ပဏီများ',
  'Yapım Firması': 'ထုတ်လုပ်ရေးကုမ္ပဏီ',
  'Firma bulunamadı': 'ကုမ္ပဏီ မတွေ့ပါ',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'ဤကုမ္ပဏီတွင် ဤအမျိုးအစား ဇာတ်လမ်း မရှိပါ။',
  'Doğum günün kutlu olsun!': 'မွေးနေ့မင်္ဂလာပါ!',
  'İyi ki doğdun, iyi ki buradasın.':
      'မွေးဖွားလာတာ ကောင်းလိုက်တာ၊ ဒီမှာ ရှိနေတာလည်း ကောင်းလိုက်တာ။',
  'Bugün {} yaşına girdin': 'ဒီနေ့ သင့်အသက် {} နှစ် ပြည့်ပြီ',
  'Teşekkürler': 'ကျေးဇူးတင်ပါတယ်',
  'İki Adımlı Doğrulama': 'နှစ်ဆင့် အတည်ပြုခြင်း',
  'Girişte e-postana kod gönderilir':
      'ဝင်ရောက်ချိန်တွင် အီးမေးလ်သို့ ကုဒ် ပို့ပေးပါမည်',
  'Kod {} adresine gönderildi': 'ကုဒ်ကို {} သို့ ပို့ပြီးပါပြီ',
  '6 haneli kod': '6 လုံးပါ ကုဒ်',
  'Doğrula': 'အတည်ပြုရန်',
  'Yeniden gönder': 'ပြန်ပို့ရန်',
  'Vazgeç': 'မလုပ်တော့ပါ',
  'Yeni kod gönderildi': 'ကုဒ်အသစ် ပို့ပြီးပါပြီ',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'Google ဖြင့် ဝင်ရောက်ပါက ကုဒ် မတောင်းပါ; Google က ကိုယ်တိုင် အတည်ပြုပါသည်။',
  'Kapatmak için de kod gerekir.': 'ပိတ်ရန်အတွက်လည်း ကုဒ် လိုအပ်ပါသည်။',
  'E-postana erişemezsen hesabına giremezsin.':
      'အီးမေးလ်ကို မသုံးနိုင်တော့ပါက အကောင့်သို့ ဝင်၍ မရတော့ပါ။',
  'İki adımlı doğrulama açıldı': 'နှစ်ဆင့် အတည်ပြုခြင်း ဖွင့်ပြီးပါပြီ',
  'İki adımlı doğrulama kapatıldı': 'နှစ်ဆင့် အတည်ပြုခြင်း ပိတ်ပြီးပါပြီ',

  // --- md.24 video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': 'ဗီဒီယိုကို ဘယ်လောက်ကြည့်ကြသလဲ',
  'Videoyu başlatanlar': 'ဗီဒီယိုစတင်ကြည့်သူများ',
  'videonun %{} noktasına ulaştı': 'ဗီဒီယို၏ {}% အထိ ရောက်ခဲ့သည်',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'ကြည့်သူတစ်ဝက်သည် ဗီဒီယို၏ အနည်းဆုံး {}% ကို ကြည့်ခဲ့သည်။',
  'Sonuna kadar izleyen: %{}': 'အဆုံးထိ ကြည့်သူ: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'မျဉ်းကွေးအတွက် ကြည့်ရှုမှု အနည်းဆုံး {} ကြိမ်လိုသည်။ ယခု {} ကြိမ်ရှိသည်။',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'မျဉ်းကွေးကို ကြည့်ရှုမှု {} ကြိမ်မှ ရေးဆွဲထားပြီး ရွေးထားသည့် ကာလက ၎င်းကို မပြောင်းလဲစေပါ။',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'ကြည့်ရှုချိန်ကို {} မှစ၍ တိုင်းတာသည်။ ထိုမတိုင်မီ ကြည့်ရှုမှုများ ဤအရေအတွက်တွင် မပါဝင်ပါ။',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      'ကြည့်ရှုမှု {} ကြိမ်။ ဗီဒီယိုတစ်ဝက်အထိ {}%၊ အဆုံးအထိ {}% ရောက်ခဲ့သည်။',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'အဆင့် {}',
  'Sonraki seviyeye {} puan kaldı': 'နောက်အဆင့်အထိ အမှတ် {} လိုသေးသည်',
  'Gönderilerin': 'သင့်ပို့စ်များ',
  '{} gönderi': 'ပို့စ် {} ခု',
  '{} gönderi · {} görüntülenme': 'ပို့စ် {} ခု · ကြည့်ရှုမှု {} ကြိမ်',
  'önceki {} güne göre': 'ယခင် {} ရက်နှင့် နှိုင်းယှဉ်ပါက',
  'önceki {} güne göre %{} arttı': 'ယခင် {} ရက်ထက် {}% တိုးလာသည်',
  'önceki {} güne göre %{} azaldı': 'ယခင် {} ရက်ထက် {}% ကျဆင်းသည်',
  'önceki {} güne göre değişmedi': 'ယခင် {} ရက်နှင့် မပြောင်းလဲပါ',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'နေ့စဉ် ကြည့်ရှုမှု: အနည်းဆုံး {}၊ အများဆုံး {}',
  'Etkileşim oranı henüz ölçülemedi':
      'ပါဝင်ဆက်နွှယ်မှုနှုန်းကို မတိုင်းတာနိုင်သေးပါ',
  'Oranlar': 'နှုန်းများ',
  'Beğenme oranı': 'နှစ်သက်မှုနှုန်း',
  'Yorum oranı': 'မှတ်ချက်နှုန်း',
  'Paylaşma oranı': 'မျှဝေမှုနှုန်း',
  'İçeriğe gitme oranı': 'အကြောင်းအရာ နှိပ်နှုန်း',
  'Profile gitme oranı': 'ပရိုဖိုင် ဝင်ကြည့်နှုန်း',
  'Ziyaretten takibe dönüşüm': 'ဝင်ကြည့်မှ စောင့်ကြည့်',
  'beğeni ÷ görüntülenme': 'နှစ်သက်မှု ÷ ကြည့်ရှုမှု',
  'yorum ÷ görüntülenme': 'မှတ်ချက် ÷ ကြည့်ရှုမှု',
  'paylaşım ÷ görüntülenme': 'မျှဝေမှု ÷ ကြည့်ရှုမှု',
  'içeriğe tıklama ÷ görüntülenme': 'အကြောင်းအရာ နှိပ်မှု ÷ ကြည့်ရှုမှု',
  'profil ziyareti ÷ görüntülenme': 'ပရိုဖိုင် ဝင်ကြည့်မှု ÷ ကြည့်ရှုမှု',
  'yeni takip ÷ profil ziyareti': 'စောင့်ကြည့်မှုအသစ် ÷ ပရိုဖိုင် ဝင်ကြည့်မှု',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'နှုန်းအတွက် ကြည့်ရှုမှု အနည်းဆုံး {} လိုသည်; ယခု {} ရှိသည်။',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'နှုန်းများသည် ပို့စ်၏ အချိန်အားလုံး ကိန်းဂဏန်းများမှ ထွက်သည်; အောက်ပါ ရက်ရွေးချယ်မှုက ၎င်းတို့ကို မပြောင်းလဲပါ။',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'ဤကိန်းဂဏန်းများသည် ပို့စ်၏ အချိန်အားလုံး စုစုပေါင်းဖြစ်သည် (ကိုယ်ပိုင်မှတ်စုပါသော အကွက်များမှလွဲ၍); အောက်ပါ ရက်ရွေးချယ်မှုက ဂရပ်ကိုသာ ပြောင်းသည်။',
  'Ortalama izlenme: videonun %{} kadarı': 'ပျမ်းမျှ ကြည့်ရှုမှု: ဗီဒီယို၏ {}%',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'ဆက်လက်ကြည့်ရှုမှု မျဉ်းကွေး၏ အပိုင်း 20 ခု၏ ပျမ်းမျှ။',
  'Dizi, film, kişi veya şirket ara...':
      'ဇာတ်လမ်းတွဲ၊ ရုပ်ရှင်၊ လူ သို့မဟုတ် ကုမ္ပဏီ ရှာရန်...',
  'Şirketler': 'ကုမ္ပဏီများ',
  'Senarist': 'ဇာတ်ညွှန်းရေးသူ',
  'Bölüm puanları': 'အပိုင်းအမှတ်များ',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'အပိုင်းအမှတ်များကို ဖွင့်မရပါ',
  'Giriş gerekli': 'ဝင်ရန် လိုသည်',
  'Geçersiz oturum': 'ဆက်ရှင် မမှန်',
  'Oturum sonlandı, tekrar giriş yap': 'ဆက်ရှင် ပြီးပြီ၊ ပြန်ဝင်ပါ',
  'Çok fazla istek; biraz sonra tekrar dene':
      'တောင်းဆိုမှု များလွန်းသည်၊ ခဏကြာမှ ပြန်ကြိုးစားပါ',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'ဆာဗာတွင် ယာယီနေရာမရှိပါ၊ ခဏအကြာတွင် ပြန်ကြိုးစားပါ',
  'Devam eden yapımlar ({})': 'ဆက်လက်ထုတ်လုပ်နေသော ({})',
  'Diziler ({})': 'စီးရီးများ ({})',
  'Filmler ({})': 'ရုပ်ရှင်များ ({})',
  'Tüm yapımlar': 'ထုတ်လုပ်မှုအားလုံး',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'သင့်မီဒီယာသိုလှောင်မှု ပြည့်နေပါပြီ၊ နေရာလွတ်ရန် ဟောင်းသောဖိုင်များကို ဖျက်ပါ',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'အီးမေးလ်/အသုံးပြုသူအမည် သို့မဟုတ် စကားဝှက် မှား',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'ဤအီးမေးလ် သို့မဟုတ် အမည်ကို အသုံးပြုပြီးသား',
  'Google doğrulaması başarısız': 'Google အတည်ပြုမှု မအောင်မြင်',
  'Kod geçersiz veya süresi dolmuş': 'ကုဒ် မမှန် သို့မဟုတ် သက်တမ်းကုန်',
  'Bu kullanıcıyla mesajlaşamazsın': 'ဤအသုံးပြုသူထံ မက်ဆေ့ချ် မပို့နိုင်',
  'Kendini takip edemezsin': 'ကိုယ့်ကိုယ်ကို ဖော်လို မလုပ်နိုင်',
  'Bu kullanıcıyı takip edemezsin': 'ဤအသုံးပြုသူကို ဖော်လို မလုပ်နိုင်',
  'Kendini engelleyemezsin': 'ကိုယ့်ကိုယ်ကို ပိတ်ပင်လို့ မရ',
  'Yorum 1-1000 karakter olmalı': 'မှတ်ချက်သည် စာလုံး 1–1000 ရှိရမည်',
  'Boş mesaj gönderilemez': 'အလွတ် မက်ဆေ့ချ် မပို့နိုင်',
  'Yorum bulunamadı': 'မှတ်ချက် ရှာမတွေ့',
  'Şifre hatalı': 'စကားဝှက် မှား',
  'Şifre en az 6 karakter olmalı': 'စကားဝှက် အနည်းဆုံး စာလုံး 6',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'GIF, PNG, JPEG သို့မဟုတ် WebP သာ တင်နိုင်',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'အမျိုးအစား: GIF, PNG, JPEG, WebP, MP4, WebM, အသံ',
  'Geçerli bir ZIP dosyası değil': 'မှန်ကန်သော ZIP ဖိုင် မဟုတ်',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'ဒေတာကို အီးမေးလ်နဲ့ ရရန် အကောင့်နှင့် အီးမေးလ် ချိတ်ပါ',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'ကြည့်ပြီး မှတ်သားချက် ရှိသည်။ "ကြည့်မည်" ဟု သတ်မှတ်ရန် အရင် ဖျက်ပါ။',
  'Arama şu anda kapalı': 'ဖုန်းခေါ်ဆိုမှု ယခု ပိတ်ထားသည်',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'ဧည့်သည်အကောင့်က ဖုန်းမဖွင့်နိုင်၊ အကောင့်ဖွင့်ပါ',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'ဆာဗာ ပြန်စနေသည်၊ ခဏကြာမှ ပြန်ကြိုးစားပါ',
  'Puan 1-10 arası olmalı': 'အဆင့်သည် 1 နှင့် 10 ကြား ရှိရမည်',
  'En fazla 10 medya eklenebilir': 'မီဒီယာ အများဆုံး 10 ခု',
  'Bu cihazdan yeni hesap açılamıyor': 'ဤစက်မှ အကောင့်အသစ် ဖွင့်မရ',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'မှန်ကန်သော အီးမေးလ်၊ အသုံးပြုသူအမည်နှင့် အနည်းဆုံး 6 လုံး စကားဝှက် လိုသည်',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'မှန်ကန်သော အီးမေးလ်နှင့် အနည်းဆုံး 6 လုံး စကားဝှက် လိုသည်',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'အသုံးပြုသူအမည် 3–20; စာလုံးသေး၊ ဂဏန်း၊ အစက်၊ 하이픈၊ အောက်မျဉ်း (အစ/အဆုံး မရ)',
  'Bu hesap zaten bağlı': 'ဤအကောင့် ချိတ်ပြီးသား',
  'Hesap oluşturulamadı': 'အကောင့် ဖန်တီးမရ',
  'Misafir hesabı oluşturulamadı': 'ဧည့်သည်အကောင့် ဖန်တီးမရ',
  'Hesap bulunamadı': 'အကောင့် မတွေ့',
  'Bu hesapta e-posta yok': 'ဤအကောင့်တွင် အီးမေးလ် မရှိ',
  'İki adımlı doğrulama zaten bu durumda':
      'အဆင့်နှစ်ဆင့် အတည်ပြုမှု ဤအခြေအနေ ဖြစ်ပြီးသား',
  'Kod yanlış': 'ကုဒ် မှား',
  'Kodun süresi doldu': 'ကုဒ် သက်တမ်းကုန်',
  'Kullanıcının e-postası yok (misafir hesap)':
      'ဤအသုံးပြုသူတွင် အီးမေးလ် မရှိ (ဧည့်သည်အကောင့်)',
  'Bio en fazla 300 karakter olabilir': 'ကိုယ်ရေး အများဆုံး 300 လုံး',
  'Geçersiz ülke': 'နိုင်ငံ မမှန်',
  'Geçersiz sosyal bağlantı': 'လူမှုလင့် မမှန်',
  'Geçersiz doğum tarihi': 'မွေးနေ့ မမှန်',
  'Liste adı gerekli': 'စာရင်းအမည် လိုသည်',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'အမည် အများဆုံး 60၊ ဖော်ပြချက် 300',
  'Liste bulunamadı': 'စာရင်း မတွေ့',
  'Değiştirilecek tercih yok': 'အပ်ဒိတ်ရန် မရှိ',
  'İnceleme en fazla 2000 karakter olabilir': 'သုံးသပ်ချက် အများဆုံး 2000',
  'Önce içeriği "bitirdim" olarak işaretle': 'အရင် ကြည့်ပြီးကြောင်း မှတ်ပါ',
  'Önce kişiyi favorile': 'အရင် ထိုပုဂ္ဂိုလ်ကို နှစ်သက်ပါ',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'အပိုင်းမှတ်ချက်အတွက် ရာသီနှင့် အပိုင်း နှစ်ခုလုံး လိုသည်',
  'Yanıtlanan yorum bulunamadı': 'ပြန်စာပို့သော မှတ်ချက် မတွေ့',
  'Geri bildirim 3-2000 karakter olmalı': 'တုံ့ပြန်ချက် 3–2000 လုံး ဖြစ်ရမည်',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'ခေါင်းစဉ်နှင့် စာသား လိုသည် (အနည်းဆုံး 2)',
  'Kendine mesaj gönderemezsin': 'ကိုယ့်ကိုယ်ကို မက်ဆေ့ မပို့နိုင်',
  'Mesaj en fazla 2000 karakter olabilir': 'မက်ဆေ့ အများဆုံး 2000',
  'Mesaj 1-2000 karakter olmalı': 'မက်ဆေ့ 1–2000 လုံး ဖြစ်ရမည်',
  'Mesaj bulunamadı': 'မက်ဆေ့ မတွေ့',
  'Mesaj bulunamadı veya düzenlenemez': 'မက်ဆေ့ မတွေ့ သို့မဟုတ် တည်းဖြတ်မရ',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'သင့်ထံ ပို့သော မက်ဆေ့သာ တိုင်ကြားနိုင်',
  'Sebep gerekli': 'အကြောင်းရင်း လိုသည်',
  'İtiraz edilecek aktif bir ceza yok':
      'အယူခံရန် အကျိုးသက်ရောက်နေသော ပြစ်ဒဏ် မရှိ',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'သုံးသပ်ရန် စောင့်နေသော အယူခံ ရှိပြီးသား',
  'Bu ceza için itirazın zaten incelendi': 'ဤပြစ်ဒဏ် အယူခံ သုံးသပ်ပြီးသား',
  'Medya bağlantısının süresi dolmuş': 'မီဒီယာလင့် သက်တမ်းကုန်',
  'Bu medya için imzalı bağlantı gerekli':
      'ဤမီဒီယာအတွက် လက်မှတ်ထိုးလင့် လိုသည်',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'ဖုန်းဝန်ဆောင်မှု ပြန်စနေသည်၊ ခဏနေ ပြန်ကြိုးစားပါ',
  'Puan göstergesi': 'အမှတ်အညွှန်း',
  'İzleme İstatistiklerim': 'ကျွန်ုပ်၏ ကြည့်ရှုမှုစာရင်း',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'အပိုင်းတစ်ခု သို့မဟုတ် ရုပ်ရှင်တစ်ကားကို ကြည့်ပြီးဟု အမှတ်အသားပြုလိုက်သည်နှင့် သင့်စာရင်းများ ဤနေရာတွင် စတင်စုဆောင်းပါမည်။',
  '{} sa {} dk': '{} နာရီ {} မိနစ်',
  'Yaklaşık ekran süresi': 'ခန့်မှန်း ဖန်သားပြင်အချိန်',
  'İzleme serisi': 'ကြည့်ရှုမှုစဉ်ဆက်',
  'Şu anki seri': 'လက်ရှိ စဉ်ဆက်',
  'En uzun seri': 'အရှည်ဆုံး စဉ်ဆက်',
  'Haftanın günleri': 'ရက်သတ္တပတ်နေ့များ',
  'En çok izlediklerin': 'အများဆုံးကြည့်ထားသည်',
  'Bu dönemde izleme yok': 'ဤကာလအတွင်း ကြည့်ရှုမှုမရှိပါ',
  'Tüm zamanlar: {} bölüm · {} film · ~{}':
      'စုစုပေါင်း - {} အပိုင်း · {} ရုပ်ရှင် · ~{}',
  'Paz': 'တနင်္ဂနွေ',
  'Pzt': 'တနင်္လာ',
  'Sal': 'အင်္ဂါ',
  'Çar': 'ဗုဒ္ဓဟူး',
  'Per': 'ကြာသပတေး',
  'Cum': 'သောကြာ',
  'Cmt': 'စနေ',
  '{} bölüm': '{} အပိုင်း',
  '{} bölüm~tekil': '{} အပိုင်း',
  '{} kez': '{} ကြိမ်',
  '{} kez~tekil': '{} ကြိမ်',
  'Son {} gün · günlük': 'နောက်ဆုံး {} ရက် · နေ့စဉ်',
  'Son {} gün · haftalık': 'နောက်ဆုံး {} ရက် · အပတ်စဉ်',
  'Ekran süren, serin ve en çok izlediklerin':
      'သင့်ဖန်သားပြင်အချိန်၊ စဉ်ဆက်နှင့် အများဆုံးကြည့်ထားသည်များ',
  'Daralt': 'ခေါက်သိမ်းရန်',
  'Listeyi düzenle': 'စာရင်း တည်းဖြတ်ရန်',
  'Bitti': 'ပြီးပါပြီ',
  'Sırala': 'အစီအစဉ်ပြောင်းရန်',
  'Herkese göster': 'အားလုံးကို ပြရန်',
  'Başkalarından gizle': 'အခြားသူများထံမှ ဖျောက်ရန်',
  'Listeden kaldır': 'စာရင်းမှ ဖယ်ရန်',
  'Listeden kaldırılsın mı?': 'စာရင်းမှ ဖယ်မလား။',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'ဤခေါင်းစဉ်ကို စာရင်းမှ ဖယ်ရှားပါမည်။ ဖျောက်ထားရုံသာ လိုချင်ပါက မျက်လုံးသင်္ကေတကို သုံးပါ။',
  'Sıralama kaydedilemedi': 'အစီအစဉ်ကို မသိမ်းနိုင်ပါ',
  'Değişiklik kaydedilemedi': 'ပြောင်းလဲမှုကို မသိမ်းနိုင်ပါ',
  'Kaldırılamadı': 'မဖယ်ရှားနိုင်ပါ',
  'Popülerlik': 'ရေပန်းစားမှု',
  'TMDB puanı': 'TMDB အဆင့်သတ်မှတ်ချက်',
  'Yapım yılı': 'ထုတ်လုပ်သည့်နှစ်',
  'dizi.jpg puanı': 'dizi.jpg အဆင့်သတ်မှတ်ချက်',
  'İzlenme': 'ကြည့်ရှုမှု',
  'Yorum sayısı': 'မှတ်ချက်အရေအတွက်',
  'Tüm raflara uygulanır': 'စင်အားလုံးတွင် သက်ရောက်သည်',
  'En popüler {} yapım arasında sıralandı':
      'ရေပန်းအစားဆုံး ခေါင်းစဉ် {} ခုအတွင်း စီစဉ်ထားသည်',
};
