/// Otomatik üretilen çeviri haritası (it).
const Map<String, String> cevirilerIt = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Nessun dato riconosciuto da importare.',
  'Arama': 'Ricerca',
  'Aramaya başla': 'Inizia a cercare',
  'Son aramalar': 'Ricerche recenti',
  'Ayarlar': 'Impostazioni',
  'Bağla': 'Collega',
  'Bio': 'Bio',
  'Bitirdim': 'Finita',
  'Bunları da Beğenebilirsin': 'Potrebbero piacerti anche',
  'Bölüm': 'Episodio',
  'Bıraktım': 'Abbandonata',
  'Dil': 'Lingua',
  'Dil ara...': 'Cerca lingua...',
  'Dizi': 'Serie TV',
  'Dizi ve filmlerini takip et':
      'Tieni traccia delle tue serie e dei tuoi film',
  'Dizi yorumu': 'Commento alla serie',
  'Dizi, film veya kişi ara...': 'Cerca serie, film o persone...',
  'Dosya en fazla 30MB olabilir': 'Il file può essere al massimo di 30MB',
  'Dosya en fazla {}MB olabilir': 'Il file può essere al massimo di {}MB',
  'E-posta': 'E-mail',
  'E-posta veya kullanıcı adı': 'E-mail o nome utente',
  'En az 2 harf yaz': 'Scrivi almeno 2 lettere',
  'Film': 'Film',
  'Film yorumu': 'Commento al film',
  'Fotoğraf / video ekle': 'Aggiungi foto / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto o GIF — immagine del profilo e copertina',
  'Giriş Yap': 'Accedi',
  'Gönder': 'Invia',
  'Gönderildi': 'Inviato',
  'Haftanın Dizileri': 'Serie della settimana',
  'Haftanın Filmleri': 'Film della settimana',
  'Henüz izleme kaydın yok': 'Non hai ancora una cronologia',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Non hai ancora liste — creane una dalla scheda Profilo.',
  'Henüz yorum yok.': 'Ancora nessun commento.',
  'Hesabın bağlandı!': 'Account collegato!',
  'Hesabın yok mu? Kayıt ol': 'Non hai un account? Registrati',
  'Hesabını Bağla': 'Collega il tuo account',
  'Hesap Oluştur': 'Crea account',
  'Kapak resmi ekle': 'Aggiungi copertina',
  'Kaydet': 'Salva',
  'Kendinden bahset...': 'Parlaci di te...',
  'Keşfet': 'Scopri',
  'Kimseyi takip etmiyor': 'Non segue nessuno',
  'Kişi ara': 'Cerca persone',
  'Kişi yorumu': 'Commento alla persona',
  'Konuk Oyuncular': 'Guest star',
  'Kullanıcı adı (küçük harf)': 'Nome utente (minuscolo)',
  'Kullanıcı adı ara...': 'Cerca nome utente...',
  'Liste adı': 'Nome della lista',
  'Listeye Ekle': 'Aggiungi alla lista',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Sei in un account ospite — collega la tua e-mail, non perdere i tuoi dati!',
  'Misafir olarak devam et': 'Continua come ospite',
  'Oluştur': 'Crea',
  'Oyuncular': 'Cast',
  'Profil': 'Profilo',
  'Profil kaydedildi': 'Profilo salvato',
  'Puanla': 'Valuta',
  'Puanı Sil': 'Elimina voto',
  'Puanın': 'Il tuo voto',
  'Sezonlar': 'Stagioni',
  'Sunucu hatası ({})': 'Errore del server ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Commento S{}E{}',
  'Takibi Bırak': 'Smetti di seguire',
  'Takip': 'Seguiti',
  'Takip Edilenler': 'Seguiti',
  'Takip Et': 'Segui',
  'Takipçi': 'Follower',
  'Takipçi yok': 'Nessun follower',
  'Takipçiler': 'Follower',
  'Takvim': 'Calendario',
  'Tamam': 'OK',
  'Tekrar Dene': 'Riprova',
  'Tekrar dene': 'Riprova',
  'Toplam ekran süresi': 'Tempo di visione totale',
  'Tüm Zamanların En İyileri': 'I migliori di sempre',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Esporta tutti i tuoi dati (visioni, voti, commenti, liste) come ZIP compatibile con TV Time o importa uno ZIP da un\'altra app.',
  'Tümünü Kaldır': 'Rimuovi tutto',
  'Tümünü İzledim': 'Ho visto tutto',
  'Türk Dizileri': 'Serie turche',
  'Veri içe aktar (.zip)': 'Importa dati (.zip)',
  'Verilerim': 'I miei dati',
  'Verilerimi dışa aktar (e-posta)': 'Esporta i miei dati (e-mail)',
  'Verilerini dışa aktar': 'Esporta i tuoi dati',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Nessun episodio in arrivo.\nImposta una serie su "Sto guardando" dalla sua scheda e segui qui i nuovi episodi.',
  'Yapımları': 'Filmografia',
  'Yeni Diziler': 'Nuove serie',
  'Yeni Liste': 'Nuova lista',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nuovo nome utente (facoltativo)',
  'Yorum': 'Commento',
  'Yorumunu yaz...': 'Scrivi il tuo commento...',
  'Zaten hesabın var mı? Giriş yap': 'Hai già un account? Accedi',
  'ort. {}': 'med. {}',
  'takip': 'seguiti',
  'takipçi': 'follower',
  '{} / {} bölüm': '{} / {} episodi',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} mesi',
  '{} bölüm izlendi': '{} episodi visti',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} gün': '{} giorni',
  '{} içerik': '{} titoli',
  '{} içerik · otomatik': '{} titoli · automatica',
  '{} kayıt atlandı (eşleşmedi).': '{} voci saltate (nessuna corrispondenza).',
  '{} saat': '{} ore',
  '{} sezon': '{} stagioni',
  '{} yıl': '{} anni',
  '{}. Bölüm': 'Episodio {}',
  '{}. Sezon': 'Stagione {}',
  'Çıkış Yap': 'Esci',
  'Ülke': 'Paese',
  'Ülke ara...': 'Cerca paese...',
  'Ülke seç': 'Scegli il paese',
  'İlk yorumu sen yaz!': 'Scrivi il primo commento!',
  'İncelemeler': 'Recensioni',
  'İncelemen (isteğe bağlı)': 'La tua recensione (facoltativa)',
  'İptal': 'Annulla',
  'İzlediklerim': 'La mia cronologia',
  'İzledim': 'Visto',
  'İzledin': 'Hai visto',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'La tua cronologia e le tue liste vengono conservate; ora puoi accedere da qualsiasi dispositivo.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'La tua cronologia, i tuoi voti, i tuoi commenti e le tue liste saranno inviati come ZIP alla tua e-mail registrata.',
  'İzleyeceğim': 'Da vedere',
  'İzliyorum': 'Sto guardando',
  'İçe aktarım tamamlandı': 'Importazione completata',
  'Şifre': 'Password',
  '• profil bilgisi': '• info profilo',
  '• {} dizi durumu': '• {} stati delle serie',
  '• {} izleme kaydı': '• {} visioni',
  '• {} liste': '• {} liste',
  '• {} puan': '• {} voti',
  '• {} yorum': '• {} commenti',
  '{}+ yapım': '{}+ titoli',
  'Yorumlar': 'Commenti',
  'Yorumlar ({})': 'Commenti ({})',
  'Yorumları ({})': 'Commenti ({})',
  'Listelerim': 'Le mie liste',
  'Nereden izledin?': 'Dove l\'hai visto?',
  'Diziye git': 'Vai alla serie',
  'TV / Kanal': 'TV / Canale',
  'Sinema': 'Cinema',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Altro',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Il tuo feed è vuoto.\nQuando commenteranno le serie e i film che guardi, apparirà qui.',
  'Listeleri ({})': 'Le sue liste ({})',
  'Liste boş.': 'Questa lista è vuota.',
  'Yanıtla': 'Rispondi',
  '@{} kullanıcısına yanıt veriyorsun': 'Stai rispondendo a @{}',
  'İzlediğim Diziler ({})': 'Serie viste ({})',
  'İzlediğim Filmler ({})': 'Film visti ({})',
  'Tümünü gör': 'Vedi tutto',
  'Bildirimler': 'Notifiche',
  'Henüz bildirim yok': 'Ancora nessuna notifica',
  '@{} yorumuna yanıt verdi': '@{} ha risposto al tuo commento',
  '@{} yorumunu beğendi': '@{} ha messo mi piace al tuo commento',
  '@{} seni takip etti': '@{} ha iniziato a seguirti',
  '@{} sana mesaj gönderdi': '@{} ti ha inviato un messaggio',
  'Mesajlar': 'Messaggi',
  'Mesaj': 'Messaggio',
  'Mesajını yaz...': 'Scrivi un messaggio...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Ancora nessuna chat.\nApri un profilo e invia un messaggio.',
  'Şifreni mi unuttun?': 'Password dimenticata?',
  'Şifreyi Sıfırla': 'Reimposta password',
  'E-postadaki kod': 'Codice dall\'email',
  'Yeni şifre': 'Nuova password',
  'Sana Özel': 'Per te',
  '{} özetin': 'Il tuo riepilogo {}',
  'Yıllık izleme istatistiklerin': 'Le tue statistiche annuali',
  'Rozetler': 'Badge',
  'Verdiğin puan': 'Voti dati',
  'Ortalama puanın': 'Il tuo voto medio',
  'En çok izlediğin diziler': 'Le serie più viste',
  'İlk Bölüm': 'Primo episodio',
  '100 Bölüm': '100 episodi',
  '1000 Bölüm': '1000 episodi',
  'İlk Film': 'Primo film',
  '50 Film': '50 film',
  'İlk Yorum': 'Primo commento',
  '25 Yorum': '25 commenti',
  '10 Puan': '10 voti',
  'İlk Takipçi': 'Primo follower',
  '10 Dizi Bitirdin': '10 serie completate',
  'İzlemeyi Bıraktım': 'Ho smesso di guardarla',
  'İzlediği Diziler ({})': 'Serie che ha visto ({})',
  'İzlediği Filmler ({})': 'Film che ha visto ({})',
  '500 Bölüm': '500 episodi',
  '5000 Bölüm': '5000 episodi',
  '10 Film': '10 film',
  '100 Film': '100 film',
  '100 Yorum': '100 commenti',
  '50 Puan': '50 voti',
  '100 Puan': '100 voti',
  '10 Takipçi': '10 follower',
  '50 Takipçi': '50 follower',
  '25 Dizi Bitirdin': '25 serie completate',
  '50 Dizi Bitirdin': '50 serie completate',
  '10 Beğeni': '10 mi piace',
  '100 Beğeni': '100 mi piace',
  'yazıyor...': 'sta scrivendo...',
  'Profil düzeni': 'Layout del profilo',
  'Konumla ve kırp': 'Posiziona e ritaglia',
  'Listeye eklendi': 'Aggiunto alla lista',
  'Listeyi sil?': 'Eliminare la lista?',
  'Sil': 'Elimina',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Questo titolo sarà segnato come mai visto e rimosso dalle tue liste.',
  'Gelecek bölüm bugün': 'Prossimo episodio oggi',
  'Gelecek bölüm {} gün sonra': 'Prossimo episodio tra {} giorni',
  'Tema': 'Tema',
  'Sistem': 'Sistema',
  'Koyu': 'Scuro',
  'Açık': 'Chiaro',
  'İzleyenler': 'Spettatori',
  'Yorumunu yaz... (@ ile etiketle)':
      'Scrivi il tuo commento... (@ per taggare)',
  '@{} bir yorumda seni etiketledi': '@{} ti ha taggato in un commento',
  'Mesajı sil': 'Elimina messaggio',
  'Mesaj silinemedi': 'Impossibile eliminare il messaggio',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Link non valido o pagina non trovata',
  'Keşfet\'e dön': 'Torna a Esplora',
  'Düzenle': 'Modifica',
  'Mesajı düzenle': 'Modifica messaggio',
  'Yanıtlanıyor': 'In risposta',
  'düzenlendi': 'modificato',
  'Fotoğraf': 'Foto',
  'Video': 'Video',
  'İçerik': 'Contenuto',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': 'visto {} min fa',
  'son görülme {} saat önce': 'visto {} h fa',
  'son görülme {} gün önce': 'visto {} g fa',
  'Yorumlar yüklenemedi': 'Impossibile caricare i commenti',
  'Favori': 'Preferito',
  'Listeye ekle': 'Aggiungi a lista',
  'İçerik paylaş': 'Condividi contenuto',
  'Kapat': 'Chiudi',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Tutto ciò che segni come visto si raccoglie qui.',
  'Henüz sohbetin yok': 'Ancora nessuna conversazione',
  'Bir profile girip mesaj gönderebilirsin.':
      'Apri un profilo e invia un messaggio.',
  'Listeyi sil': 'Elimina lista',
  'Puan kaydedilemedi': 'Impossibile salvare il voto',
  'Nerede İzlenir': 'Dove guardare',
  'Abonelik': 'Abbonamento',
  'Kirala': 'Noleggia',
  'Satın al': 'Acquista',
  'Hoş geldin!': 'Benvenuto!',
  'İzlemek istediğin dizi ve filmleri seç':
      'Scegli serie e film che vuoi guardare',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Le tue scelte vengono aggiunte alla tua lista',
  'Şimdilik atla': 'Salta per ora',
  'Devam et': 'Continua',
  '{} ekle': 'Aggiungi {}',
  'Şikayet et': 'Segnala',
  'Engelle': 'Blocca',
  'Engeli kaldır': 'Sblocca',
  'Kullanıcı engellendi': 'Utente bloccato',
  'Engel kaldırıldı': 'Blocco rimosso',
  'Şikayet sebebi': 'Motivo della segnalazione',
  'Spam veya yanıltıcı': 'Spam o fuorviante',
  'Taciz veya nefret söylemi': 'Molestie o incitamento all’odio',
  'Uygunsuz / cinsel içerik': 'Contenuto inappropriato / sessuale',
  'Şiddet veya tehlikeli içerik': 'Violenza o contenuti pericolosi',
  'Telif hakkı ihlali': 'Violazione del copyright',
  'Şikayetin alındı, teşekkürler':
      'La tua segnalazione è stata ricevuta, grazie',
  'Hesabımı Sil': 'Elimina il mio account',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Il tuo account e tutti i tuoi dati (cronologia, voti, commenti, liste, messaggi) verranno eliminati definitivamente. L’operazione è irreversibile.',
  'Şifreni gir': 'Inserisci la tua password',
  'Hesabımı kalıcı sil': 'Elimina definitivamente il mio account',
  'Sesli mesaj': 'Messaggio vocale',
  'Ses gönderilemedi': 'Impossibile inviare il messaggio vocale',
  'Kaydediliyor…': 'Registrazione…',
  'Ses oynatılamadı': 'Impossibile riprodurre l’audio',
  'Oynat': 'Riproduci',
  'Duraklat': 'Metti in pausa',
  'Liste görünümü': 'Vista elenco',
  'Takvim görünümü': 'Vista calendario',
  'Önceki ay': 'Mese precedente',
  'Sonraki ay': 'Mese successivo',
  'Bu gün bölüm yok': 'Nessun episodio in questo giorno',
  'Gizlilik Politikası': 'Informativa sulla Privacy',
  'Son güncelleme: {}': 'Ultimo aggiornamento: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Questa informativa spiega quali dati vengono raccolti, come vengono usati e quali sono i tuoi diritti quando usi l\'app dizi.jpg e il sito dizijpg.com.',
  'Topladığımız Veriler': 'Dati che raccogliamo',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Account: indirizzo e-mail, nome utente e password. Le password sono salvate con hash irreversibile; gli account ospite possono essere usati senza e-mail.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profilo: le informazioni che scegli di aggiungere, come avatar, immagine di copertina, bio e paese.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Utilizzo: la tua cronologia di visione, i voti, i commenti, le liste, le reazioni e i preferiti.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Messaggi: i tuoi messaggi di testo, immagine e vocali sono salvati sui nostri server. I messaggi non sono crittografati end-to-end; vengono esaminati solo in caso di segnalazione, a fini di moderazione.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Contenuti caricati: foto, GIF, video e registrazioni vocali che aggiungi al profilo, ai commenti e ai messaggi.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Dati tecnici: indirizzo IP, posizione approssimativa (paese/città), piattaforma del dispositivo, versione dell\'app e log degli errori. Sono conservati per sicurezza e per la risoluzione dei problemi.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Notifiche: per le notifiche push conserviamo il token del tuo dispositivo e la tua lingua. Puoi disattivarle in qualsiasi momento dalle impostazioni del dispositivo.',
  'Verileri Nasıl Kullanırız': 'Come usiamo i tuoi dati',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Usiamo i tuoi dati solo per fornire il servizio, proteggere il tuo account, inviare notifiche, correggere errori e prevenire abusi. Non vendiamo i tuoi dati e non li condividiamo con nessuno a fini pubblicitari.',
  'Çerezler ve Yerel Depolama': 'Cookie e archiviazione locale',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Usiamo l\'archiviazione locale solo per mantenerti connesso e ricordare preferenze come lingua e tema. Non ci sono cookie pubblicitari o di tracciamento.',
  'Üçüncü Taraf Hizmetler': 'Servizi di terze parti',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'I dati di serie e film provengono da TMDB, le informazioni sulle piattaforme di streaming da JustWatch. Le notifiche push sono recapitate tramite Google Firebase e il traffico del sito è protetto da Cloudflare. Questi servizi sono soggetti alle rispettive informative sulla privacy.',
  'Saklama ve Silme': 'Conservazione ed eliminazione',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'I tuoi dati sono conservati finché il tuo account esiste. Con "Elimina il mio account" nelle Impostazioni puoi eliminare l\'account in modo permanente; i tuoi dati vengono cancellati subito e le copie nei backup entro 14 giorni al massimo. I log degli errori vengono eliminati automaticamente dopo 30 giorni.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'Puoi esportare i tuoi dati in formato ZIP dalle Impostazioni; l\'archivio viene inviato al tuo indirizzo e-mail.',
  'Güvenlik': 'Sicurezza',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'I dati viaggiano su connessioni crittografate (HTTPS) e sono conservati su server ad accesso limitato.',
  'Çocukların Gizliliği': 'Privacy dei minori',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg non è rivolto ai minori di 13 anni.',
  'Hakların': 'I tuoi diritti',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'In base a KVKK e GDPR hai il diritto di accedere ai tuoi dati, correggerli, eliminarli e trasferirli. Per esercitarli scrivici: {}',
  'Değişiklikler': 'Modifiche',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Se questa informativa cambia, la nuova versione sarà pubblicata su questa pagina e la data sarà aggiornata.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Registrandoti accetti l\'{}.',
  'Kullanıcılar': 'Utenti',
  'Fotoğrafı değiştir': 'Cambia foto',
  'Yeniden konumlandır': 'Riposiziona',
  'Bir şeyler ters gitti': 'Qualcosa è andato storto',
  'Sosyal Bağlantılar': 'Link social',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Sul tuo profilo vengono mostrati fino a 3 link.',
  'Platform seç': 'Scegli una piattaforma',
  'Kullanıcı adın': 'Il tuo nome utente',
  'Ekle': 'Aggiungi',
  'Kaldır': 'Rimuovi',
  'Kopyalandı: {}': 'Copiato: {}',
  'Geçersiz kullanıcı adı': 'Nome utente non valido',
  'Bağlantı ekle': 'Aggiungi link',
  'Spoiler olabilir — dokun ve gör': 'Può contenere spoiler — tocca per vedere',
  'Beğeni': 'Mi piace',
  'Görüntülenme': 'Visualizzazioni',
  'Tam ekran': 'Schermo intero',
  'Sonuç bulunamadı': 'Nessun risultato',
  'Dizi ve Filmler': 'Serie e film',
  'Kişiler': 'Persone',
  'Ana Sayfa': 'Home',
  'Paylaş': 'Condividi',
  'Yanıtlar': 'Risposte',
  'Yaklaşan Bölümler': 'Prossimi episodi',
  'Yetişme Listesi': 'Lista recuperi',
  'Şunu mu demek istedin': 'Forse cercavi',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — tocca per vedere',
  'uyum': 'affinità',
  'Uyum': 'Affinità',
  '{} ortak dizi': '{} serie in comune',
  '{} ortak film': '{} film in comune',
  'Bildirim Tercihleri': 'Preferenze notifiche',
  'Beğeniler': 'Mi piace',
  'Yeni takipçiler': 'Nuovi follower',
  'Etiketlenmeler': 'Menzioni',
  'Yeniden izledim': 'Rivisto',
  '{}. kez izlendi': 'Visto {} volte',
  'Gönderi bulunamadı': 'Post non trovato',
  'Gözat': 'Sfoglia',
  'Diziler': 'Serie',
  'Filmler': 'Film',
  'Tümü': 'Tutti',
  'Farklı bir tür seç.': 'Prova un altro genere.',
  'Gizlilik': 'Privacy',
  'İzlediklerimi gizle': 'Nascondi ciò che guardo',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Le serie e i film che hai visto non appariranno sul tuo profilo',
  'Yorumlarımı gizle': 'Nascondi i miei commenti',
  'Profilinde yorumların görünmez':
      'I tuoi commenti non appariranno sul tuo profilo',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Puoi nascondere una singola serie o un film con il chip "Nascondi sul mio profilo" nella sua pagina.',
  'Geri Bildirim': 'Feedback',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Scrivi la tua opinione e i tuoi suggerimenti sull\'app...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Grazie! Il tuo feedback è stato ricevuto.',
  'Profilimde gizle': 'Nascondi sul mio profilo',
  'Yorumları': 'Commenti',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Questo utente preferisce tenere privati i propri commenti.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Dati: JustWatch',
  'Web Sitesi': 'Sito web',
  'Diğer uygulamalar': 'Altre app',
  'Bağlantıyı kopyala': 'Copia link',
  'Henüz kimseyi takip etmiyorsun.': 'Non segui ancora nessuno.',
  'Çevir': 'Traduci',
  'Orijinali göster': 'Mostra originale',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Nessun episodio con data di messa in onda annunciata questo mese. Le date escono di solito qualche settimana prima e appariranno qui.',
  'devamı': 'altro',
};
