/// Otomatik üretilen çeviri haritası (ar).
const Map<String, String> cevirilerAr = {
  'Aktarılacak tanınan veri bulunamadı.':
      'لم يتم العثور على بيانات معروفة للاستيراد.',
  'Arama': 'بحث',
  'Aramaya başla': 'ابدأ البحث',
  'Ayarlar': 'الإعدادات',
  'Bağla': 'ربط',
  'Bio': 'نبذة',
  'Bitirdim': 'أنهيته',
  'Bunları da Beğenebilirsin': 'قد تعجبك هذه أيضًا',
  'Bölüm': 'حلقة',
  'Bıraktım': 'توقفت عنه',
  'Dil': 'اللغة',
  'Dil ara...': 'ابحث عن لغة...',
  'Dizi': 'مسلسل',
  'Dizi ve filmlerini takip et': 'تابع مسلسلاتك وأفلامك',
  'Dizi yorumu': 'تعليق على المسلسل',
  'Dizi, film veya kişi ara...': 'ابحث عن مسلسل أو فيلم أو شخص...',
  'Dosya en fazla 30MB olabilir': 'الحد الأقصى لحجم الملف 30 ميغابايت',
  'Dosya en fazla {}MB olabilir': 'الحد الأقصى لحجم الملف {} ميغابايت',
  'E-posta': 'البريد الإلكتروني',
  'E-posta veya kullanıcı adı': 'البريد الإلكتروني أو اسم المستخدم',
  'En az 2 harf yaz': 'اكتب حرفين على الأقل',
  'Film': 'فيلم',
  'Film yorumu': 'تعليق على الفيلم',
  'Fotoğraf / video ekle': 'أضف صورة / فيديو',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'صورة أو GIF — صورة الملف الشخصي والغلاف',
  'Giriş Yap': 'تسجيل الدخول',
  'Gönder': 'إرسال',
  'Gönderildi': 'تم الإرسال',
  'Haftanın Dizileri': 'مسلسلات الأسبوع',
  'Haftanın Filmleri': 'أفلام الأسبوع',
  'Henüz izleme kaydın yok': 'لا يوجد سجل مشاهدة بعد',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'لا توجد لديك قوائم بعد — أنشئ واحدة من تبويب الملف الشخصي.',
  'Henüz yorum yok.': 'لا توجد تعليقات بعد.',
  'Hesabın bağlandı!': 'تم ربط حسابك!',
  'Hesabın yok mu? Kayıt ol': 'ليس لديك حساب؟ سجّل الآن',
  'Hesabını Bağla': 'اربط حسابك',
  'Hesap Oluştur': 'إنشاء حساب',
  'Kapak resmi ekle': 'أضف صورة غلاف',
  'Kaydet': 'حفظ',
  'Kendinden bahset...': 'حدّثنا عن نفسك...',
  'Keşfet': 'استكشف',
  'Kimseyi takip etmiyor': 'لا يتابع أحدًا',
  'Kişi ara': 'ابحث عن شخص',
  'Kişi yorumu': 'تعليق على الشخص',
  'Konuk Oyuncular': 'ضيوف الشرف',
  'Kullanıcı adı (küçük harf)': 'اسم المستخدم (بأحرف صغيرة)',
  'Kullanıcı adı ara...': 'ابحث عن اسم مستخدم...',
  'Liste adı': 'اسم القائمة',
  'Listeye Ekle': 'أضف إلى قائمة',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'أنت في حساب زائر — اربطه ببريدك الإلكتروني ولا تفقد بياناتك!',
  'Misafir olarak devam et': 'المتابعة كزائر',
  'Oluştur': 'إنشاء',
  'Oyuncular': 'طاقم التمثيل',
  'Profil': 'الملف الشخصي',
  'Profil kaydedildi': 'تم حفظ الملف الشخصي',
  'Puanla': 'قيّم',
  'Puanı Sil': 'حذف التقييم',
  'Puanın': 'تقييمك',
  'Sezonlar': 'المواسم',
  'Sunucu hatası ({})': 'خطأ في الخادم ({})',
  'S{} · {}. Bölüm': 'م{} · الحلقة {}',
  'S{}B{} yorumu': 'تعليق على م{}ح{}',
  'Takibi Bırak': 'إلغاء المتابعة',
  'Takip': 'يتابع',
  'Takip Edilenler': 'المتابَعون',
  'Takip Et': 'تابع',
  'Takipçi': 'متابِع',
  'Takipçi yok': 'لا يوجد متابعون',
  'Takipçiler': 'المتابِعون',
  'Takvim': 'التقويم',
  'Tamam': 'حسنًا',
  'Tekrar Dene': 'أعد المحاولة',
  'Tekrar dene': 'أعد المحاولة',
  'Toplam ekran süresi': 'إجمالي وقت المشاهدة',
  'Tüm Zamanların En İyileri': 'الأفضل على الإطلاق',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'صدّر كل بياناتك (المشاهدات والتقييمات والتعليقات والقوائم) كملف ZIP متوافق مع TV Time، أو استورد ملف ZIP قادمًا من تطبيق آخر.',
  'Tümünü Kaldır': 'إزالة الكل',
  'Tümünü İzledim': 'شاهدت الكل',
  'Türk Dizileri': 'المسلسلات التركية',
  'Veri içe aktar (.zip)': 'استيراد البيانات (.zip)',
  'Verilerim': 'بياناتي',
  'Verilerimi dışa aktar (e-posta)': 'تصدير بياناتي (بريد إلكتروني)',
  'Verilerini dışa aktar': 'صدّر بياناتك',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'لا توجد حلقات قادمة.\nحوّل مسلسلًا إلى حالة "أشاهده" من صفحة تفاصيله وتابع الحلقات الجديدة هنا.',
  'Yapımları': 'أعماله',
  'Yeni Diziler': 'مسلسلات جديدة',
  'Yeni Liste': 'قائمة جديدة',
  'Yeni kullanıcı adı (isteğe bağlı)': 'اسم مستخدم جديد (اختياري)',
  'Yorum': 'تعليق',
  'Yorumunu yaz...': 'اكتب تعليقك...',
  'Zaten hesabın var mı? Giriş yap': 'لديك حساب بالفعل؟ سجّل الدخول',
  'ort. {}': 'متوسط {}',
  'takip': 'يتابع',
  'takipçi': 'متابع',
  '{} / {} bölüm': '{} / {} حلقة',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} شهر',
  '{} bölüm izlendi': 'تمت مشاهدة {} حلقة',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} د',
  '{} gün': '{} يوم',
  '{} içerik': '{} عنصر',
  '{} içerik · otomatik': '{} عنصر · تلقائي',
  '{} kayıt atlandı (eşleşmedi).': 'تم تخطي {} سجل (بدون تطابق).',
  '{} saat': '{} ساعة',
  '{} sezon': '{} موسم',
  '{} yıl': '{} سنة',
  '{}. Bölüm': 'الحلقة {}',
  '{}. Sezon': 'الموسم {}',
  'Çıkış Yap': 'تسجيل الخروج',
  'Ülke': 'الدولة',
  'Ülke ara...': 'ابحث عن دولة...',
  'Ülke seç': 'اختر دولة',
  'İlk yorumu sen yaz!': 'كن أول من يعلّق!',
  'İncelemeler': 'المراجعات',
  'İncelemen (isteğe bağlı)': 'مراجعتك (اختياري)',
  'İptal': 'إلغاء',
  'İzlediklerim': 'مشاهداتي',
  'İzledim': 'شاهدته',
  'İzledin': 'شاهدته',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'سيتم الاحتفاظ بسجل مشاهدتك وقوائمك؛ ويمكنك الآن تسجيل الدخول من أي جهاز.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'سيتم إرسال سجل مشاهدتك وتقييماتك وتعليقاتك وقوائمك كملف ZIP إلى بريدك الإلكتروني المسجّل.',
  'İzleyeceğim': 'سأشاهده',
  'İzliyorum': 'أشاهده',
  'İçe aktarım tamamlandı': 'اكتمل الاستيراد',
  'Şifre': 'كلمة المرور',
  '• profil bilgisi': '• معلومات الملف الشخصي',
  '• {} dizi durumu': '• {} حالة مسلسل',
  '• {} izleme kaydı': '• {} سجل مشاهدة',
  '• {} liste': '• {} قائمة',
  '• {} puan': '• {} تقييم',
  '• {} yorum': '• {} تعليق',
  '{}+ yapım': '{}+ عمل',
  'Yorumlar': 'التعليقات',
  'Yorumlar ({})': 'التعليقات ({})',
  'Yorumları ({})': 'تعليقاته ({})',
  'Listelerim': 'قوائمي',
  'Nereden izledin?': 'أين شاهدته؟',
  'Diziye git': 'الذهاب إلى المسلسل',
  'TV / Kanal': 'تلفاز / قناة',
  'Sinema': 'سينما',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'أخرى',
  'Akış': 'الموجز',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'موجزك فارغ.\nعندما يعلّق الآخرون على المسلسلات والأفلام التي تشاهدها، سيظهر هنا.',
  'Listeleri ({})': 'قوائمه ({})',
  'Liste boş.': 'هذه القائمة فارغة.',
  'Yanıtla': 'رد',
  '@{} kullanıcısına yanıt veriyorsun': 'ترد على @{}',
  'İzlediğim Diziler ({})': 'مسلسلات شاهدتها ({})',
  'İzlediğim Filmler ({})': 'أفلام شاهدتها ({})',
  'Tümünü gör': 'عرض الكل',
  'Bildirimler': 'الإشعارات',
  'Henüz bildirim yok': 'لا إشعارات بعد',
  '@{} yorumuna yanıt verdi': '@{} ردّ على تعليقك',
  '@{} yorumunu beğendi': '@{} أعجب بتعليقك',
  '@{} seni takip etti': '@{} تابعك',
  '@{} sana mesaj gönderdi': '@{} أرسل لك رسالة',
  'Mesajlar': 'الرسائل',
  'Mesaj': 'رسالة',
  'Mesajını yaz...': 'اكتب رسالة...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'لا محادثات بعد.\nافتح ملفًا شخصيًا وأرسل رسالة.',
  'Şifreni mi unuttun?': 'نسيت كلمة المرور؟',
  'Şifreyi Sıfırla': 'إعادة تعيين كلمة المرور',
  'E-postadaki kod': 'الرمز من البريد',
  'Yeni şifre': 'كلمة مرور جديدة',
  'Sana Özel': 'مخصص لك',
  '{} özetin': 'ملخصك لعام {}',
  'Yıllık izleme istatistiklerin': 'إحصاءات مشاهدتك السنوية',
  'Rozetler': 'الشارات',
  'Verdiğin puan': 'التقييمات الممنوحة',
  'Ortalama puanın': 'متوسط تقييمك',
  'En çok izlediğin diziler': 'أكثر مسلسلاتك مشاهدة',
  'İlk Bölüm': 'أول حلقة',
  '100 Bölüm': '100 حلقة',
  '1000 Bölüm': '1000 حلقة',
  'İlk Film': 'أول فيلم',
  '50 Film': '50 فيلمًا',
  'İlk Yorum': 'أول تعليق',
  '25 Yorum': '25 تعليقًا',
  '10 Puan': '10 تقييمات',
  'İlk Takipçi': 'أول متابع',
  '10 Dizi Bitirdin': 'أنهيت 10 مسلسلات',
  'İzlemeyi Bıraktım': 'توقفت عن المشاهدة',
  'İzlediği Diziler ({})': 'مسلسلات شاهدها ({})',
  'İzlediği Filmler ({})': 'أفلام شاهدها ({})',
  '500 Bölüm': '500 حلقة',
  '5000 Bölüm': '5000 حلقة',
  '10 Film': '10 أفلام',
  '100 Film': '100 فيلم',
  '100 Yorum': '100 تعليق',
  '50 Puan': '50 تقييمًا',
  '100 Puan': '100 تقييم',
  '10 Takipçi': '10 متابعين',
  '50 Takipçi': '50 متابعًا',
  '25 Dizi Bitirdin': 'أنهى 25 مسلسلًا',
  '50 Dizi Bitirdin': 'أنهى 50 مسلسلًا',
  '10 Beğeni': '10 إعجابات',
  '100 Beğeni': '100 إعجاب',
  'yazıyor...': 'يكتب...',
  'Profil düzeni': 'تخطيط الملف الشخصي',
  'Konumla ve kırp': 'حدّد الموضع وقصّ',
  'Listeye eklendi': 'أضيف إلى القائمة',
  'Listeyi sil?': 'حذف القائمة؟',
  'Sil': 'حذف',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'سيُعتبر هذا العمل غير مُشاهد وسيُزال من قوائمك.',
  'Gelecek bölüm bugün': 'الحلقة القادمة اليوم',
  'Gelecek bölüm {} gün sonra': 'الحلقة القادمة بعد {} يومًا',
  'Tema': 'السمة',
  'Sistem': 'النظام',
  'Koyu': 'داكن',
  'Açık': 'فاتح',
  'İzleyenler': 'المشاهدون',
  'Yorumunu yaz... (@ ile etiketle)': 'اكتب تعليقك... (@ للإشارة)',
  '@{} bir yorumda seni etiketledi': 'أشار إليك @{} في تعليق',
  'Mesajı sil': 'حذف الرسالة',
  'Mesaj silinemedi': 'تعذّر حذف الرسالة',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'الرابط غير صالح أو الصفحة غير موجودة',
  'Keşfet\'e dön': 'العودة إلى الاستكشاف',
  'Düzenle': 'تعديل',
  'Mesajı düzenle': 'تعديل الرسالة',
  'Yanıtlanıyor': 'يرد',
  'düzenlendi': 'معدّلة',
  'Fotoğraf': 'صورة',
  'Video': 'فيديو',
  'İçerik': 'محتوى',
  'çevrimiçi': 'متصل',
  'son görülme {} dk önce': 'آخر ظهور قبل {} د',
  'son görülme {} saat önce': 'آخر ظهور قبل {} س',
  'son görülme {} gün önce': 'آخر ظهور قبل {} ي',
  'Yorumlar yüklenemedi': 'تعذّر تحميل التعليقات',
  'Favori': 'المفضلة',
  'Listeye ekle': 'إضافة إلى قائمة',
  'İçerik paylaş': 'مشاركة المحتوى',
  'Kapat': 'إغلاق',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'كل ما تحدده كمُشاهَد يُجمع هنا.',
  'Henüz sohbetin yok': 'لا محادثات بعد',
  'Bir profile girip mesaj gönderebilirsin.': 'افتح ملفًا شخصيًا وأرسل رسالة.',
  'Listeyi sil': 'حذف القائمة',
  'Puan kaydedilemedi': 'تعذّر حفظ التقييم',
};
