/// Otomatik üretilen çeviri haritası (de).
const Map<String, String> cevirilerDe = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Keine erkannten Daten zum Importieren gefunden.',
  'Arama': 'Suche',
  'Aramaya başla': 'Starte die Suche',
  'Ayarlar': 'Einstellungen',
  'Bağla': 'Verknüpfen',
  'Bio': 'Bio',
  'Bitirdim': 'Abgeschlossen',
  'Bunları da Beğenebilirsin': 'Das könnte dir auch gefallen',
  'Bölüm': 'Episode',
  'Bıraktım': 'Abgebrochen',
  'Dil': 'Sprache',
  'Dil ara...': 'Sprache suchen...',
  'Dizi': 'Serie',
  'Dizi ve filmlerini takip et': 'Behalte deine Serien und Filme im Blick',
  'Dizi yorumu': 'Serienkommentar',
  'Dizi, film veya kişi ara...': 'Serie, Film oder Person suchen...',
  'Dosya en fazla 30MB olabilir': 'Die Datei darf höchstens 30MB groß sein',
  'Dosya en fazla {}MB olabilir': 'Die Datei darf höchstens {}MB groß sein',
  'E-posta': 'E-Mail',
  'E-posta veya kullanıcı adı': 'E-Mail oder Benutzername',
  'En az 2 harf yaz': 'Gib mindestens 2 Buchstaben ein',
  'Film': 'Film',
  'Film yorumu': 'Filmkommentar',
  'Fotoğraf / video ekle': 'Foto / Video hinzufügen',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto oder GIF — Profil- und Titelbild',
  'Giriş Yap': 'Anmelden',
  'Gönder': 'Senden',
  'Gönderildi': 'Gesendet',
  'Haftanın Dizileri': 'Serien der Woche',
  'Haftanın Filmleri': 'Filme der Woche',
  'Henüz izleme kaydın yok': 'Du hast noch nichts angesehen',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Du hast noch keine Listen — erstelle eine im Profil-Tab.',
  'Henüz yorum yok.': 'Noch keine Kommentare.',
  'Hesabın bağlandı!': 'Dein Konto wurde verknüpft!',
  'Hesabın yok mu? Kayıt ol': 'Noch kein Konto? Registrieren',
  'Hesabını Bağla': 'Konto verknüpfen',
  'Hesap Oluştur': 'Konto erstellen',
  'Kapak resmi ekle': 'Titelbild hinzufügen',
  'Kaydet': 'Speichern',
  'Kendinden bahset...': 'Erzähl etwas über dich...',
  'Keşfet': 'Entdecken',
  'Kimseyi takip etmiyor': 'Folgt niemandem',
  'Kişi ara': 'Person suchen',
  'Kişi yorumu': 'Personenkommentar',
  'Konuk Oyuncular': 'Gastdarsteller',
  'Kullanıcı adı (küçük harf)': 'Benutzername (Kleinbuchstaben)',
  'Kullanıcı adı ara...': 'Benutzername suchen...',
  'Liste adı': 'Listenname',
  'Listeye Ekle': 'Zur Liste hinzufügen',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Du nutzt ein Gastkonto — verknüpfe deine E-Mail und verliere deine Daten nicht!',
  'Misafir olarak devam et': 'Als Gast fortfahren',
  'Oluştur': 'Erstellen',
  'Oyuncular': 'Besetzung',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil gespeichert',
  'Puanla': 'Bewerten',
  'Puanı Sil': 'Bewertung löschen',
  'Puanın': 'Deine Bewertung',
  'Sezonlar': 'Staffeln',
  'Sunucu hatası ({})': 'Serverfehler ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Kommentar zu S{}E{}',
  'Takibi Bırak': 'Entfolgen',
  'Takip': 'Folge ich',
  'Takip Edilenler': 'Gefolgte',
  'Takip Et': 'Folgen',
  'Takipçi': 'Follower',
  'Takipçi yok': 'Keine Follower',
  'Takipçiler': 'Follower',
  'Takvim': 'Kalender',
  'Tamam': 'OK',
  'Tekrar Dene': 'Erneut versuchen',
  'Tekrar dene': 'Erneut versuchen',
  'Toplam ekran süresi': 'Gesamte Bildschirmzeit',
  'Tüm Zamanların En İyileri': 'Die Besten aller Zeiten',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Exportiere alle deine Daten (Verlauf, Bewertungen, Kommentare, Listen) als TV-Time-kompatibles ZIP oder importiere ein ZIP aus einer anderen App.',
  'Tümünü Kaldır': 'Alle entfernen',
  'Tümünü İzledim': 'Alle gesehen',
  'Türk Dizileri': 'Türkische Serien',
  'Veri içe aktar (.zip)': 'Daten importieren (.zip)',
  'Verilerim': 'Meine Daten',
  'Verilerimi dışa aktar (e-posta)': 'Meine Daten exportieren (E-Mail)',
  'Verilerini dışa aktar': 'Deine Daten exportieren',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Keine anstehenden Episoden.\nSetze eine Serie in der Detailansicht auf "Schaue ich" und verfolge neue Episoden hier.',
  'Yapımları': 'Filmografie',
  'Yeni Diziler': 'Neue Serien',
  'Yeni Liste': 'Neue Liste',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Neuer Benutzername (optional)',
  'Yorum': 'Kommentar',
  'Yorumunu yaz...': 'Schreib deinen Kommentar...',
  'Zaten hesabın var mı? Giriş yap': 'Hast du schon ein Konto? Anmelden',
  'ort. {}': 'Ø {}',
  'takip': 'folge ich',
  'takipçi': 'Follower',
  '{} / {} bölüm': '{} / {} Episoden',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} Mon.',
  '{} bölüm izlendi': '{} Episoden gesehen',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} Min.',
  '{} gün': '{} Tg.',
  '{} içerik': '{} Titel',
  '{} içerik · otomatik': '{} Titel · automatisch',
  '{} kayıt atlandı (eşleşmedi).':
      '{} Einträge übersprungen (keine Übereinstimmung).',
  '{} saat': '{} Std.',
  '{} sezon': '{} Staffeln',
  '{} yıl': '{} J.',
  '{}. Bölüm': 'Episode {}',
  '{}. Sezon': 'Staffel {}',
  'Çıkış Yap': 'Abmelden',
  'Ülke': 'Land',
  'Ülke ara...': 'Land suchen...',
  'Ülke seç': 'Land auswählen',
  'İlk yorumu sen yaz!': 'Schreib den ersten Kommentar!',
  'İncelemeler': 'Rezensionen',
  'İncelemen (isteğe bağlı)': 'Deine Rezension (optional)',
  'İptal': 'Abbrechen',
  'İzlediklerim': 'Mein Verlauf',
  'İzledim': 'Gesehen',
  'İzledin': 'Gesehen',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Dein Verlauf und deine Listen bleiben erhalten; du kannst dich jetzt von jedem Gerät aus anmelden.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Dein Verlauf, deine Bewertungen, Kommentare und Listen werden als ZIP an deine hinterlegte E-Mail-Adresse gesendet.',
  'İzleyeceğim': 'Will ich sehen',
  'İzliyorum': 'Schaue ich',
  'İçe aktarım tamamlandı': 'Import abgeschlossen',
  'Şifre': 'Passwort',
  '• profil bilgisi': '• Profildaten',
  '• {} dizi durumu': '• {} Serienstatus',
  '• {} izleme kaydı': '• {} Verlaufseinträge',
  '• {} liste': '• {} Listen',
  '• {} puan': '• {} Bewertungen',
  '• {} yorum': '• {} Kommentare',
  '{}+ yapım': '{}+ Titel',
  'Yorumlar': 'Kommentare',
  'Yorumlar ({})': 'Kommentare ({})',
  'Yorumları ({})': 'Kommentare ({})',
  'Listelerim': 'Meine Listen',
  'Nereden izledin?': 'Wo hast du es gesehen?',
  'Diziye git': 'Zur Serie',
  'TV / Kanal': 'TV / Sender',
  'Sinema': 'Kino',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Sonstiges',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Dein Feed ist leer.\nWenn jemand deine Serien und Filme kommentiert, erscheint es hier.',
  'Listeleri ({})': 'Listen ({})',
  'Liste boş.': 'Diese Liste ist leer.',
  'Yanıtla': 'Antworten',
  '@{} kullanıcısına yanıt veriyorsun': 'Du antwortest @{}',
  'İzlediğim Diziler ({})': 'Gesehene Serien ({})',
  'İzlediğim Filmler ({})': 'Gesehene Filme ({})',
  'Tümünü gör': 'Alle ansehen',
  'Bildirimler': 'Benachrichtigungen',
  'Henüz bildirim yok': 'Noch keine Benachrichtigungen',
  '@{} yorumuna yanıt verdi': '@{} hat auf deinen Kommentar geantwortet',
  '@{} yorumunu beğendi': '@{} gefällt dein Kommentar',
  '@{} seni takip etti': '@{} folgt dir',
  '@{} sana mesaj gönderdi': '@{} hat dir eine Nachricht gesendet',
  'Mesajlar': 'Nachrichten',
  'Mesaj': 'Nachricht',
  'Mesajını yaz...': 'Schreib eine Nachricht...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Noch keine Chats.\nÖffne ein Profil und sende eine Nachricht.',
  'Şifreni mi unuttun?': 'Passwort vergessen?',
  'Şifreyi Sıfırla': 'Passwort zurücksetzen',
  'E-postadaki kod': 'Code aus der E-Mail',
  'Yeni şifre': 'Neues Passwort',
  'Sana Özel': 'Für dich',
  '{} özetin': 'Dein {}-Rückblick',
  'Yıllık izleme istatistiklerin': 'Deine Jahres-Statistik',
  'Rozetler': 'Abzeichen',
  'Verdiğin puan': 'Vergebene Bewertungen',
  'Ortalama puanın': 'Deine Durchschnittswertung',
  'En çok izlediğin diziler': 'Deine meistgesehenen Serien',
  'İlk Bölüm': 'Erste Folge',
  '100 Bölüm': '100 Folgen',
  '1000 Bölüm': '1000 Folgen',
  'İlk Film': 'Erster Film',
  '50 Film': '50 Filme',
  'İlk Yorum': 'Erster Kommentar',
  '25 Yorum': '25 Kommentare',
  '10 Puan': '10 Bewertungen',
  'İlk Takipçi': 'Erster Follower',
  '10 Dizi Bitirdin': '10 Serien beendet',
  'İzlemeyi Bıraktım': 'Abgebrochen',
  'İzlediği Diziler ({})': 'Gesehene Serien ({})',
  'İzlediği Filmler ({})': 'Gesehene Filme ({})',
  '500 Bölüm': '500 Folgen',
  '5000 Bölüm': '5000 Folgen',
  '10 Film': '10 Filme',
  '100 Film': '100 Filme',
  '100 Yorum': '100 Kommentare',
  '50 Puan': '50 Bewertungen',
  '100 Puan': '100 Bewertungen',
  '10 Takipçi': '10 Follower',
  '50 Takipçi': '50 Follower',
  '25 Dizi Bitirdin': '25 Serien beendet',
  '50 Dizi Bitirdin': '50 Serien beendet',
  '10 Beğeni': '10 Likes',
  '100 Beğeni': '100 Likes',
  'yazıyor...': 'schreibt...',
  'Profil düzeni': 'Profil-Layout',
  'Konumla ve kırp': 'Ausrichten und zuschneiden',
  'Listeye eklendi': 'Zur Liste hinzugefügt',
  'Listeyi sil?': 'Liste löschen?',
  'Sil': 'Löschen',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Dieser Titel gilt dann als nie gesehen und wird aus deinen Listen entfernt.',
  'Gelecek bölüm bugün': 'Nächste Folge heute',
  'Gelecek bölüm {} gün sonra': 'Nächste Folge in {} Tagen',
};
