/// Otomatik üretilen çeviri haritası (hi).
const Map<String, String> cevirilerHi = {
  'Hepsini gördün, baştan gösteriyoruz':
      'आपने यह सब देखा है, हम आपको शुरुआत से दिखाते हैं',
  'Aktarılacak tanınan veri bulunamadı.':
      'इंपोर्ट करने लायक कोई डेटा नहीं मिला।',
  'Arama': 'खोज',
  'Aramaya başla': 'खोजना शुरू करो',
  'Son aramalar': 'हाल की खोजें',
  'Ayarlar': 'सेटिंग्स',
  'Bağla': 'लिंक करो',
  'Bio': 'बायो',
  'Bitirdim': 'पूरा कर लिया',
  'Bunları da Beğenebilirsin': 'ये भी पसंद आ सकते हैं',
  'Bölüm': 'एपिसोड',
  'Bıraktım': 'छोड़ दिया',
  'Dil': 'भाषा',
  'Dil ara...': 'भाषा खोजो...',
  'Dizi': 'सीरीज़',
  'Dizi ve filmlerini takip et': 'अपने शो और फ़िल्में ट्रैक करो',
  'Dizi yorumu': 'सीरीज़ पर कमेंट',
  'Dizi, film veya kişi ara...': 'सीरीज़, फ़िल्म या व्यक्ति खोजो...',
  'Dosya en fazla 30MB olabilir': 'फ़ाइल ज़्यादा से ज़्यादा 30MB हो सकती है',
  'Dosya en fazla {}MB olabilir': 'फ़ाइल ज़्यादा से ज़्यादा {}MB हो सकती है',
  'E-posta': 'ईमेल',
  'E-posta veya kullanıcı adı': 'ईमेल या यूज़रनेम',
  'En az 2 harf yaz': 'कम से कम 2 अक्षर लिखो',
  'Film': 'फ़िल्म',
  'Film yorumu': 'फ़िल्म पर कमेंट',
  'Fotoğraf / video ekle': 'फ़ोटो / वीडियो जोड़ो',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'फ़ोटो या GIF — प्रोफ़ाइल और कवर इमेज',
  'Giriş Yap': 'लॉग इन करो',
  'Gönder': 'भेजो',
  'Gönderildi': 'भेज दिया गया',
  'Haftanın Dizileri': 'इस हफ़्ते के शो',
  'Haftanın Filmleri': 'इस हफ़्ते की फ़िल्में',
  'Henüz izleme kaydın yok': 'अभी तक कोई वॉच हिस्ट्री नहीं',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'अभी कोई लिस्ट नहीं — प्रोफ़ाइल टैब से बनाओ।',
  'Henüz yorum yok.': 'अभी कोई कमेंट नहीं।',
  'Hesabın bağlandı!': 'तुम्हारा अकाउंट लिंक हो गया!',
  'Hesabın yok mu? Kayıt ol': 'अकाउंट नहीं है? साइन अप करो',
  'Hesabını Bağla': 'अपना अकाउंट लिंक करो',
  'Hesap Oluştur': 'अकाउंट बनाओ',
  'Kapak resmi ekle': 'कवर इमेज जोड़ो',
  'Kaydet': 'सेव करो',
  'Kendinden bahset...': 'अपने बारे में बताओ...',
  'Keşfet': 'डिस्कवर',
  'Kimseyi takip etmiyor': 'अभी किसी को फ़ॉलो नहीं',
  'Kişi ara': 'लोग खोजो',
  'Kişi yorumu': 'व्यक्ति पर कमेंट',
  'Konuk Oyuncular': 'गेस्ट कलाकार',
  'Kullanıcı adı (küçük harf)': 'यूज़रनेम (लोअरकेस)',
  'Kullanıcı adı ara...': 'यूज़रनेम खोजो...',
  'Liste adı': 'लिस्ट का नाम',
  'Listeye Ekle': 'लिस्ट में जोड़ो',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'तुम गेस्ट अकाउंट पर हो — अपने ईमेल से लिंक करो, अपना डेटा मत खोओ!',
  'Misafir olarak devam et': 'गेस्ट के तौर पर जारी रखो',
  'Oluştur': 'बनाओ',
  'Oyuncular': 'कलाकार',
  'Profil': 'प्रोफ़ाइल',
  'Profil kaydedildi': 'प्रोफ़ाइल सेव हो गई',
  'Puanla': 'रेट करो',
  'Puanı Sil': 'रेटिंग हटाओ',
  'Puanın': 'तुम्हारी रेटिंग',
  'Sezonlar': 'सीज़न',
  'Sunucu hatası ({})': 'सर्वर एरर ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'S{}E{} पर कमेंट',
  'Takibi Bırak': 'अनफ़ॉलो करो',
  'Takip': 'फ़ॉलोइंग',
  'Takip Edilenler': 'फ़ॉलो किए गए',
  'Takip Et': 'फ़ॉलो करो',
  'Takipçi': 'फ़ॉलोअर',
  'Takipçi yok': 'कोई फ़ॉलोअर नहीं',
  'Takipçiler': 'फ़ॉलोअर्स',
  'Takvim': 'कैलेंडर',
  'Tamam': 'ठीक है',
  'Tekrar Dene': 'फिर से कोशिश करो',
  'Tekrar dene': 'फिर से कोशिश करो',
  'Toplam İzleme Süresi': 'कुल स्क्रीन टाइम',
  'Tüm Zamanların En İyileri': 'ऑल-टाइम बेस्ट',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'अपना पूरा डेटा (वॉच हिस्ट्री, रेटिंग, कमेंट, लिस्ट) TV Time-संगत ZIP के रूप में लो या दूसरे ऐप से आई ZIP इंपोर्ट करो।',
  'Tümünü Kaldır': 'सभी हटाओ',
  'Tümünü İzledim': 'सभी देख लिए',
  'Türk Dizileri': 'तुर्की सीरीज़',
  'Veri içe aktar (.zip)': 'डेटा इंपोर्ट करो (.zip)',
  'Verilerim': 'मेरा डेटा',
  'Verilerimi dışa aktar (e-posta)': 'मेरा डेटा एक्सपोर्ट करो (ईमेल)',
  'Verilerini dışa aktar': 'अपना डेटा एक्सपोर्ट करो',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'कोई आने वाला एपिसोड नहीं।\nशो के पेज से "देख रहा हूँ" स्टेटस चुनो, नए एपिसोड यहाँ ट्रैक करो।',
  'Yapımları': 'फ़िल्मोग्राफ़ी',
  'Yeni Diziler': 'नई सीरीज़',
  'Yeni Liste': 'नई लिस्ट',
  'Yeni kullanıcı adı (isteğe bağlı)': 'नया यूज़रनेम (वैकल्पिक)',
  'Yorum': 'कमेंट',
  'Yorumunu yaz...': 'अपना कमेंट लिखो...',
  'Zaten hesabın var mı? Giriş yap': 'पहले से अकाउंट है? लॉग इन करो',
  'ort. {}': 'औसत {}',
  'takip': 'फ़ॉलोइंग',
  'takipçi': 'फ़ॉलोअर',
  '{} / {} bölüm': '{} / {} एपिसोड',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} महीने',
  '{} ay~tekil': '{} महीना',
  '{} bölüm izlendi': '{} एपिसोड देखे गए',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} मिनट',
  '{} dk~tekil': '{} मिनट',
  '{} gün': '{} दिन',
  '{} gün~tekil': '{} दिन',
  '{} içerik': '{} टाइटल',
  '{} içerik · otomatik': '{} टाइटल · ऑटोमैटिक',
  '{} kayıt atlandı (eşleşmedi).': '{} रिकॉर्ड छोड़े गए (मैच नहीं हुए)।',
  '{} saat': '{} घंटे',
  '{} saat~tekil': '{} घंटा',
  '{} sezon': '{} सीज़न',
  '{} yıl': '{} साल',
  '{} yıl~tekil': '{} साल',
  '{}. Bölüm': 'एपिसोड {}',
  '{}. Sezon': 'सीज़न {}',
  'Çıkış Yap': 'लॉग आउट करो',
  'Ülke': 'देश',
  'Ülke ara...': 'देश खोजो...',
  'Ülke seç': 'देश चुनो',
  'İlk yorumu sen yaz!': 'पहला कमेंट तुम लिखो!',
  'İncelemeler': 'रिव्यू',
  'İncelemen (isteğe bağlı)': 'तुम्हारा रिव्यू (वैकल्पिक)',
  'İptal': 'रद्द करो',
  'İzlediklerim': 'मेरे देखे हुए',
  'İzledim': 'देख लिया',
  'İzledin': 'तुमने देखा',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'तुम्हारी वॉच हिस्ट्री और लिस्ट सुरक्षित रहेंगी; अब किसी भी डिवाइस से लॉग इन कर सकते हो।',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'तुम्हारी वॉच हिस्ट्री, रेटिंग, कमेंट और लिस्ट ZIP के रूप में रजिस्टर्ड ईमेल पते पर भेजी जाएँगी।',
  'İzleyeceğim': 'देखना है',
  'İzliyorum': 'देख रहा हूँ',
  'İçe aktarım tamamlandı': 'इंपोर्ट पूरा हुआ',
  'Şifre': 'पासवर्ड',
  '• profil bilgisi': '• प्रोफ़ाइल जानकारी',
  '• {} dizi durumu': '• {} शो स्टेटस',
  '• {} izleme kaydı': '• {} वॉच रिकॉर्ड',
  '• {} liste': '• {} लिस्ट',
  '• {} puan': '• {} रेटिंग',
  '• {} yorum': '• {} कमेंट',
  '{}+ yapım': '{}+ टाइटल',
  'Yorumlar': 'कमेंट्स',
  'Yorumlar ({})': 'कमेंट्स ({})',
  'Yorumları ({})': 'इस पर कमेंट्स ({})',
  'Listelerim': 'मेरी लिस्ट्स',
  'Nereden izledin?': 'कहाँ देखा?',
  'Diziye git': 'शो पर जाएँ',
  'TV / Kanal': 'टीवी / चैनल',
  'Sinema': 'सिनेमा',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'अन्य',
  'Akış': 'फ़ीड',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'तुम्हारी फ़ीड खाली है।\nतुम्हारे देखे शो और फ़िल्मों पर कमेंट आते ही यहाँ दिखेंगे।',
  'Listeleri ({})': 'इनकी लिस्ट्स ({})',
  'Liste boş.': 'यह लिस्ट खाली है।',
  'Yanıtla': 'जवाब दो',
  '@{} kullanıcısına yanıt veriyorsun': '@{} को जवाब',
  'İzlediğim Diziler ({})': 'मेरे देखे शो ({})',
  'İzlediğim Filmler ({})': 'मेरी देखी फ़िल्में ({})',
  'Tümünü gör': 'सभी देखो',
  'Bildirimler': 'सूचनाएँ',
  'Henüz bildirim yok': 'अभी कोई सूचना नहीं',
  '@{} yorumuna yanıt verdi': '@{} ने तुम्हारे कमेंट का जवाब दिया',
  '@{} yorumunu beğendi': '@{} ने तुम्हारा कमेंट पसंद किया',
  '@{} seni takip etti': '@{} ने तुम्हें फ़ॉलो किया',
  '@{} sana mesaj gönderdi': '@{} ने तुम्हें संदेश भेजा',
  'Mesajlar': 'संदेश',
  'Mesaj': 'संदेश',
  'Mesaja eklenecek': 'संदेश में जोड़ा जाएगा',
  'Mesajını yaz...': 'संदेश लिखो...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'अभी कोई चैट नहीं।\nकिसी प्रोफ़ाइल पर जाकर संदेश भेजो।',
  'Şifreni mi unuttun?': 'पासवर्ड याद नहीं?',
  'Şifreyi Sıfırla': 'पासवर्ड रीसेट करो',
  'E-postadaki kod': 'ईमेल वाला कोड',
  'Yeni şifre': 'नया पासवर्ड',
  'Sana Özel': 'तुम्हारे लिए',
  '{} özetin': 'तुम्हारा {} सार',
  'Yıllık izleme istatistiklerin': 'सालाना देखने के आँकड़े',
  'Rozetler': 'बैज',
  'Verdiğin puan': 'दी गई रेटिंग',
  'Ortalama puanın': 'औसत रेटिंग',
  'En çok izlediğin diziler': 'सबसे ज़्यादा देखे शो',
  'İlk Bölüm': 'पहला एपिसोड',
  '100 Bölüm': '100 एपिसोड',
  '1000 Bölüm': '1000 एपिसोड',
  'İlk Film': 'पहली फ़िल्म',
  '50 Film': '50 फ़िल्में',
  'İlk Yorum': 'पहला कमेंट',
  '25 Yorum': '25 कमेंट',
  '10 Puan': '10 रेटिंग',
  'İlk Takipçi': 'पहला फ़ॉलोअर',
  '10 Dizi Bitirdin': '10 शो पूरे',
  'İzlemeyi Bıraktım': 'देखना छोड़ दिया',
  'İzlediği Diziler ({})': 'इनके देखे शो ({})',
  'İzlediği Filmler ({})': 'इनकी देखी फ़िल्में ({})',
  '500 Bölüm': '500 एपिसोड',
  '5000 Bölüm': '5000 एपिसोड',
  '10 Film': '10 फ़िल्में',
  '100 Film': '100 फ़िल्में',
  '100 Yorum': '100 कमेंट',
  '50 Puan': '50 रेटिंग',
  '100 Puan': '100 रेटिंग',
  '10 Takipçi': '10 फ़ॉलोअर',
  '50 Takipçi': '50 फ़ॉलोअर',
  '25 Dizi Bitirdin': '25 शो पूरे',
  '50 Dizi Bitirdin': '50 शो पूरे',
  '10 Beğeni': '10 लाइक',
  '100 Beğeni': '100 लाइक',
  'yazıyor...': 'लिखा जा रहा है...',
  'ses kaydediyor...': 'ऑडियो रिकॉर्ड हो रहा है...',
  'Profil düzeni': 'प्रोफ़ाइल लेआउट',
  'Konumla ve kırp': 'जगह चुनो और क्रॉप करो',
  'Listeye eklendi': 'लिस्ट में जोड़ा गया',
  'Listeyi sil?': 'लिस्ट हटाओ?',
  'Sil': 'हटाओ',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'यह टाइटल कभी न देखा गया माना जाएगा और तुम्हारी लिस्ट्स से हट जाएगा।',
  'Gelecek bölüm bugün': 'अगला एपिसोड आज',
  'Gelecek bölüm {} gün sonra': 'अगला एपिसोड {} दिन बाद',
  'Tema': 'थीम',
  'Sistem': 'सिस्टम',
  'Koyu': 'डार्क',
  'Açık': 'लाइट',
  'İzleyenler': 'दर्शक',
  'Yorumunu yaz... (@ ile etiketle)': 'अपना कमेंट लिखो... (@ से टैग करो)',
  '@{} bir yorumda seni etiketledi': '@{} ने तुम्हें एक कमेंट में टैग किया',
  'Mesajı sil': 'संदेश हटाओ',
  'Mesaj silinemedi': 'संदेश नहीं हटाया जा सका',
  'Bağlantı geçersiz veya sayfa bulunamadı': 'लिंक अमान्य है या पेज नहीं मिला',
  "Keşfet'e dön": 'डिस्कवर पर वापस जाओ',
  'Düzenle': 'एडिट करो',
  'Mesajı düzenle': 'संदेश एडिट करो',
  'Yanıtlanıyor': 'जवाब दे रहे हो',
  'düzenlendi': 'संपादित',
  'Fotoğraf': 'फ़ोटो',
  'Video': 'वीडियो',
  'İçerik': 'सामग्री',
  'çevrimiçi': 'ऑनलाइन',
  'son görülme {} dk önce': '{} मिनट पहले देखा',
  'son görülme {} saat önce': '{} घंटे पहले देखा',
  'son görülme {} gün önce': '{} दिन पहले देखा',
  'Yorumlar yüklenemedi': 'कमेंट लोड नहीं हो सके',
  'Favori': 'पसंदीदा',
  'Listeye ekle': 'लिस्ट में जोड़ो',
  'İçerik paylaş': 'कंटेंट शेयर करो',
  'Kapat': 'बंद करो',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'जिन शो और फ़िल्मों को देखा हुआ मार्क करते हो, वे यहाँ जमा होती जाती हैं।',
  'Henüz sohbetin yok': 'अभी कोई बातचीत नहीं',
  'Bir profile girip mesaj gönderebilirsin.':
      'किसी प्रोफ़ाइल पर जाकर संदेश भेजो।',
  'Listeyi sil': 'लिस्ट हटाओ',
  'Puan kaydedilemedi': 'रेटिंग सेव नहीं हो सकी',
  'Nerede İzlenir': 'कहाँ देखें',
  'Abonelik': 'सदस्यता',
  'Kirala': 'किराए पर लो',
  'Satın al': 'खरीदो',
  'Devam et': 'जारी रखो',
  'Şikayet et': 'रिपोर्ट करें',
  'Engelle': 'ब्लॉक करें',
  'Engeli kaldır': 'अनब्लॉक करें',
  'Kullanıcı engellendi': 'उपयोगकर्ता ब्लॉक किया गया',
  'Engel kaldırıldı': 'ब्लॉक हटाया गया',
  'Şikayet sebebi': 'रिपोर्ट का कारण',
  'Spam veya yanıltıcı': 'स्पैम या भ्रामक',
  'Taciz veya nefret söylemi': 'उत्पीड़न या नफ़रत भरी बातें',
  'Uygunsuz / cinsel içerik': 'अनुचित / यौन सामग्री',
  'Şiddet veya tehlikeli içerik': 'हिंसा या ख़तरनाक सामग्री',
  'Telif hakkı ihlali': 'कॉपीराइट उल्लंघन',
  'Şikayetin alındı, teşekkürler': 'तुम्हारी रिपोर्ट मिल गई, शुक्रिया',
  'Hesabımı Sil': 'मेरा खाता हटाएं',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'तुम्हारा खाता और सारा डेटा (हिस्ट्री, रेटिंग, कमेंट, लिस्ट, मैसेज) हमेशा के लिए हट जाएगा। इसे वापस नहीं किया जा सकता।',
  'Şifreni gir': 'अपना पासवर्ड डालो',
  'Hesabımı kalıcı sil': 'मेरा खाता हमेशा के लिए हटाएं',
  'Sesli mesaj': 'वॉइस मैसेज',
  'Ses gönderilemedi': 'वॉइस मैसेज नहीं भेजा जा सका',
  'Kaydediliyor…': 'रिकॉर्ड हो रहा है…',
  'Ses oynatılamadı': 'ऑडियो नहीं चल सका',
  'Oynat': 'चलाओ',
  'Fragmanı oynat': 'ट्रेलर चलाएँ',
  'Altyazıyı aç': 'उपशीर्षक चालू करें',
  'Altyazıyı kapat': 'उपशीर्षक बंद करें',
  '10 saniye ileri': '10 सेकंड आगे बढ़ाएँ',
  '10 saniye geri': '10 सेकंड पीछे जाएँ',
  'Duraklat': 'रोको',
  'Liste görünümü': 'सूची दृश्य',
  'Takvim görünümü': 'कैलेंडर दृश्य',
  'Önceki ay': 'पिछला महीना',
  'Sonraki ay': 'अगला महीना',
  'Bu gün bölüm yok': 'इस दिन कोई एपिसोड नहीं',
  'Gizlilik Politikası': 'गोपनीयता नीति',
  'Son güncelleme: {}': 'आख़िरी अपडेट: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'यह नीति बताती है कि dizi.jpg ऐप और dizijpg.com साइट इस्तेमाल करते समय कौन सा डेटा इकट्ठा होता है, कैसे इस्तेमाल होता है और तुम्हारे क्या अधिकार हैं।',
  'Topladığımız Veriler': 'हम कौन सा डेटा इकट्ठा करते हैं',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'खाता: ईमेल पता, यूज़रनेम और पासवर्ड। पासवर्ड ऐसे हैश में सहेजे जाते हैं जिन्हें वापस नहीं पढ़ा जा सकता; गेस्ट खाते बिना ईमेल के भी चलते हैं।',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'प्रोफ़ाइल: वे जानकारियाँ जो तुम खुद जोड़ना चुनते हो, जैसे अवतार, कवर इमेज, बायो और देश।',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'इस्तेमाल: तुम्हारा देखने का इतिहास, रेटिंग, टिप्पणियाँ, सूचियाँ, रिएक्शन और पसंदीदा।',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'संदेश: तुम्हारे टेक्स्ट, इमेज और वॉयस संदेश हमारे सर्वर पर सहेजे जाते हैं। संदेश एंड-टू-एंड एन्क्रिप्टेड नहीं हैं; रिपोर्ट होने पर ही मॉडरेशन के लिए देखे जाते हैं।',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'अपलोड किया मीडिया: फ़ोटो, GIF, वीडियो और वॉयस रिकॉर्डिंग जो तुम प्रोफ़ाइल, टिप्पणियों और संदेशों में जोड़ते हो।',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'तकनीकी: IP पता, अनुमानित लोकेशन (देश/शहर स्तर), डिवाइस प्लैटफ़ॉर्म, ऐप वर्ज़न और एरर लॉग। ये सुरक्षा और गड़बड़ी ठीक करने के लिए रखे जाते हैं।',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'उपयोग के आँकड़े: किस तरह के डिवाइस, ऑपरेटिंग सिस्टम और ब्राउज़र से प्रवेश हुआ, यह मोटी श्रेणियों में रोज़ाना के कुल काउंटर में जोड़ा जाता है; ब्राउज़र की पहचान खुद नहीं रखी जाती और ये संख्याएँ किसी व्यक्ति से नहीं जोड़ी जा सकतीं।',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'सूचनाएँ: पुश सूचनाओं के लिए तुम्हारे डिवाइस का टोकन और भाषा पसंद सहेजी जाती है। सूचनाएँ डिवाइस की सेटिंग्स से कभी भी बंद कर सकते हो।',
  'Verileri Nasıl Kullanırız': 'हम डेटा कैसे इस्तेमाल करते हैं',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'तुम्हारा डेटा सिर्फ़ सेवा देने, खाता सुरक्षित रखने, सूचनाएँ भेजने, गड़बड़ियाँ ठीक करने और दुरुपयोग रोकने के लिए इस्तेमाल होता है। हम तुम्हारा डेटा न बेचते हैं, न विज्ञापन के लिए किसी से साझा करते हैं।',
  'Çerezler ve Yerel Depolama': 'कुकीज़ और लोकल स्टोरेज',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'लोकल स्टोरेज सिर्फ़ तुम्हें लॉग-इन रखने और भाषा/थीम जैसी पसंद याद रखने के लिए इस्तेमाल होता है। कोई विज्ञापन या ट्रैकिंग कुकी नहीं है।',
  'Üçüncü Taraf Hizmetler': 'थर्ड-पार्टी सेवाएँ',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'सीरीज़ और फ़िल्मों का डेटा TMDB से और स्ट्रीमिंग प्लैटफ़ॉर्म की जानकारी JustWatch से आती है। पुश सूचनाएँ Google Firebase से पहुँचती हैं और साइट का ट्रैफ़िक Cloudflare सुरक्षित रखता है। इन सेवाओं पर उनकी अपनी गोपनीयता नीतियाँ लागू होती हैं।',
  'Saklama ve Silme': 'संग्रहण और हटाना',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'तुम्हारा डेटा तब तक रहता है जब तक तुम्हारा खाता है। सेटिंग्स में "मेरा खाता हटाएँ" से खाता हमेशा के लिए हटा सकते हो; डेटा तुरंत और बैकअप की प्रतियाँ ज़्यादा से ज़्यादा 14 दिन में मिट जाती हैं। एरर लॉग 30 दिन बाद अपने आप मिट जाते हैं।',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'सेटिंग्स से अपना डेटा ZIP के रूप में निर्यात कर सकते हो; आर्काइव तुम्हारे ईमेल पते पर भेजा जाता है।',
  'Güvenlik': 'सुरक्षा',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'डेटा एन्क्रिप्टेड कनेक्शन (HTTPS) से जाता है और सीमित पहुँच वाले सर्वर पर रहता है।',
  'Çocukların Gizliliği': 'बच्चों की गोपनीयता',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg 13 साल से छोटे बच्चों के लिए नहीं है।',
  'Hakların': 'तुम्हारे अधिकार',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK और GDPR के तहत तुम्हें अपने डेटा तक पहुँच, सुधार, हटाने और स्थानांतरित करने का अधिकार है। इनके लिए हमें लिखो: {}',
  'Değişiklikler': 'बदलाव',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'यह नीति बदलने पर नया संस्करण इसी पेज पर प्रकाशित होगा और तारीख़ अपडेट होगी।',
  'Kayıt olarak {} kabul etmiş olursun.':
      'रजिस्टर करके तुम {} स्वीकार करते हो।',
  'Kullanıcılar': 'उपयोगकर्ता',
  'Fotoğrafı değiştir': 'फ़ोटो बदलो',
  'Yeniden konumlandır': 'फिर से सेट करो',
  'Bir şeyler ters gitti': 'कुछ गड़बड़ हो गई',
  'Sosyal Bağlantılar': 'सोशल लिंक',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'तुम्हारी प्रोफ़ाइल पर ज़्यादा से ज़्यादा 3 लिंक दिखते हैं।',
  'Platform seç': 'प्लैटफ़ॉर्म चुनो',
  'Kullanıcı adın': 'तुम्हारा यूज़रनेम',
  'Ekle': 'जोड़ो',
  'Kaldır': 'हटाओ',
  'Kopyalandı: {}': 'कॉपी हो गया: {}',
  'Geçersiz kullanıcı adı': 'गलत यूज़रनेम',
  'Bağlantı ekle': 'लिंक जोड़ो',
  'Spoiler olabilir — dokun ve gör':
      'स्पॉइलर हो सकता है — देखने के लिए टैप करो',
  'Beğeni': 'लाइक',
  'beğeni': 'लाइक',
  'Beğen': 'लाइक',
  'Görüntülenme': 'व्यू',
  'görüntülenme': 'व्यू',
  'Tam ekran': 'फ़ुल स्क्रीन',
  'Arama başarısız': 'खोज विफल रही',
  'Sonuç bulunamadı': 'कोई नतीजा नहीं मिला',
  'Dizi ve Filmler': 'सीरीज़ और फ़िल्में',
  'Kişiler': 'लोग',
  'Ana Sayfa': 'होम',
  'Paylaş': 'शेयर',
  'Yanıtlar': 'जवाब',
  'Yaklaşan Bölümler': 'आने वाले एपिसोड',
  'Yetişme Listesi': 'कैच-अप सूची',
  'Şunu mu demek istedin': 'क्या आपका मतलब था',
  'Spoiler': 'स्पॉइलर',
  'Spoiler — dokun ve gör': 'स्पॉइलर — देखने के लिए टैप करें',
  'uyum': 'मेल',
  'Uyum': 'मेल',
  '{} ortak dizi': '{} समान सीरीज़',
  '{} ortak film': '{} समान फ़िल्में',
  'Bildirim Tercihleri': 'सूचना प्राथमिकताएं',
  'Beğeniler': 'पसंद',
  'Yeni takipçiler': 'नए फ़ॉलोअर',
  'Etiketlenmeler': 'उल्लेख',
  'Yeniden izledim': 'फिर से देखा',
  '{}. kez izlendi': '{} बार देखा',
  'Gönderi bulunamadı': 'पोस्ट नहीं मिली',
  'Gözat': 'ब्राउज़ करें',
  'Diziler': 'सीरीज़',
  'Filmler': 'फ़िल्में',
  'Tümü': 'सभी',
  'Farklı bir tür seç.': 'कोई और शैली आज़माएं।',
  'Gizlilik': 'प्राइवेसी',
  'İzlediklerimi gizle': 'मैंने जो देखा उसे छिपाओ',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'तुमने जो सीरीज़ और फ़िल्में देखी हैं वे तुम्हारी प्रोफ़ाइल पर नहीं दिखेंगी',
  'Yorumlarımı gizle': 'मेरे कमेंट छिपाओ',
  'Profilinde yorumların görünmez':
      'तुम्हारे कमेंट तुम्हारी प्रोफ़ाइल पर नहीं दिखेंगे',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'किसी एक सीरीज़ या फ़िल्म को उसके पेज पर "मेरी प्रोफ़ाइल में छिपाओ" चिप से छिपा सकते हो।',
  'Geri Bildirim': 'फ़ीडबैक',
  'Uygulama hakkında görüş ve önerini yaz...':
      'ऐप के बारे में अपनी राय और सुझाव लिखो...',
  'Teşekkürler! Geri bildirimin alındı.': 'धन्यवाद! तुम्हारा फ़ीडबैक मिल गया।',
  'Profilimde gizle': 'मेरी प्रोफ़ाइल में छिपाओ',
  'Yorumları': 'इस पर कमेंट्स',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'इस उपयोगकर्ता ने अभी तक कुछ नहीं देखा है।',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'इस यूज़र के कमेंट छिपे हुए हैं।',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'डेटा: JustWatch',
  'Web Sitesi': 'वेबसाइट',
  'Diğer uygulamalar': 'अन्य ऐप',
  'Bağlantıyı kopyala': 'लिंक कॉपी करें',
  'Henüz kimseyi takip etmiyorsun.': 'तुम अभी किसी को फ़ॉलो नहीं करते।',
  'Çevir': 'अनुवाद करें',
  'Çeviri şu an yapılamadı': 'अभी अनुवाद संभव नहीं है',
  'Bağlantı açılamadı': 'लिंक नहीं खुल सका',
  'Orijinali göster': 'मूल दिखाएँ',
  'Çeviriyi göster': 'अनुवाद दिखाओ',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'इस महीने प्रसारण तिथि घोषित कोई एपिसोड नहीं है। तिथियाँ आम तौर पर कुछ हफ़्ते पहले बताई जाती हैं और फिर यहाँ दिखेंगी।',
  'devamı': 'और',
  'Google ile devam et': 'Google से जारी रखें',
  'Google girişi başarısız': 'Google से साइन इन नहीं हो सका',
  'Veri tasarrufu': 'डेटा बचत',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi पर डेटा बचत',
  'Mobil veride veri tasarrufu': 'मोबाइल डेटा पर डेटा बचत',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'चालू होने पर फ़ोटो पहले से डाउनलोड नहीं होतीं, सिर्फ़ वही तस्वीर लोड होती है जो तुम देख रहे हो।',
  'Çocuk güvenliği': 'बाल सुरक्षा',
  'Türk Filmleri': 'तुर्की फ़िल्में',
  'En Yüksek Puanlı Filmler': 'सर्वाधिक रेटेड फ़िल्में',
  'En Yüksek Puanlı Diziler': 'सर्वाधिक रेटेड सीरीज़',
  'En Çok İzlenen Filmler': 'सबसे ज़्यादा देखी गई फ़िल्में',
  'Popüler Diziler': 'लोकप्रिय सीरीज़',
  'En Çok Kazanan Filmler': 'सबसे ज़्यादा कमाई वाली फ़िल्में',
  'Kült Filmler': 'कल्ट फ़िल्में',
  'Yeni Filmler': 'नई फ़िल्में',
  'Yorum yap': 'टिप्पणी करें',
  'Henüz yorum yok': 'अभी कोई टिप्पणी नहीं',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'शो और फ़िल्मों पर लिखी तुम्हारी टिप्पणियाँ यहाँ जमा होती हैं।',
  'GIF ekle': 'GIF जोड़ें',
  'İlk yorumu sen yaz': 'पहली टिप्पणी आप करें',
  'Video altyazıları': 'वीडियो उपशीर्षक',
  'Videolarda altyazı göster': 'वीडियो पर उपशीर्षक दिखाएँ',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'वीडियो में बोला गया वाक्य स्क्रीन पर लिखा हुआ है. पाठ का अनुवाद है: तुर्की भाषण में अंग्रेजी, अन्य भाषाओं में तुर्की।',
  'Güncelleme gerekli': 'अपडेट ज़रूरी है',
  'Yeni sürüm var': 'नया वर्शन उपलब्ध है',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'जारी रखने के लिए dizi.jpg का नया वर्शन इंस्टॉल करें।',
  'Güncelle': 'अपडेट करें',
  'Daha sonra': 'बाद में',
  'Takvim güncelleniyor': 'कैलेंडर अपडेट हो रहा है',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'कैलेंडर अपडेट नहीं हो सका, पुरानी सूची दिखाई जा रही है',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'कुछ सीरीज़ लोड नहीं हो सकीं, सूची अधूरी हो सकती है',
  'Yenile': 'रिफ्रेश',
  'Devam etmek için giriş yap': 'जारी रखने के लिए लॉग इन करें',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'रेटिंग देने, टिप्पणी करने और अपनी लाइब्रेरी बनाने के लिए एक मुफ़्त खाता काफ़ी है।',
  'Şimdi değil': 'अभी नहीं',
  'Yorum yazmak için giriş yap': 'टिप्पणी लिखने के लिए लॉग इन करें',
  'Kişilere göndermek için giriş yap': 'लोगों को भेजने के लिए लॉग इन करें',
  'Beğenenler': 'पसंद करने वाले',
  'Henüz beğeni yok': 'अभी तक कोई पसंद नहीं',
  'Bu gönderiyi ilk beğenen sen ol': 'इस पोस्ट को पसंद करने वाले पहले बनें',
  'Bu gönderiye yanıt': 'इस पोस्ट का जवाब',
  'Spoiler içeren gönderi': 'स्पॉइलर वाली पोस्ट',
  'Görsel gönderi': 'फोटो पोस्ट',
  'Bu yorumu profilimde gizle': 'यह कमेंट मेरी प्रोफ़ाइल से छिपाएं',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'कमेंट शो और फ़िल्म के पेज पर बना रहता है',
  'Bu yorumu sil': 'यह कमेंट डिलीट करें',
  'Yorum profilinde gizlendi': 'कमेंट तुम्हारी प्रोफ़ाइल से छिपा दिया गया',
  'Geri al': 'वापस लाएं',
  'Yorum silinsin mi?': 'क्या कमेंट डिलीट करें?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'यह कमेंट हर जगह से हमेशा के लिए डिलीट हो जाएगा। इसे वापस नहीं लाया जा सकता।',
  'Yorum silindi': 'कमेंट डिलीट हो गया',
  'Yorum profilinde tekrar görünüyor':
      'कमेंट तुम्हारी प्रोफ़ाइल पर फिर से दिख रहा है',
  'Gizlenen yorumun yok': 'तुम्हारा कोई छिपा हुआ कमेंट नहीं है',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'जो कमेंट तुम अपनी प्रोफ़ाइल के कमेंट्स टैब में किसी पोस्ट को दबाकर छिपाते हो, वे यहां जमा होते हैं।',
  'Gizlenen yorumlar': 'छिपे हुए कमेंट्स',
  'Gönderiye git': 'पोस्ट पर जाएं',
  'Tekrar göster': 'फिर से दिखाएं',
  'Yanıtlarımı gizle': 'मेरे जवाब छिपाएं',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'दूसरों की पोस्ट पर तुम जो जवाब लिखते हो वे सिर्फ़ तुम्हें दिखते हैं',
  'Profilinde gizlediğin yorumları tekrar göster':
      'अपनी प्रोफ़ाइल पर छिपाए गए कमेंट्स फिर से दिखाएं',
  'Sıralama': 'क्रम',
  'Önerilen': 'अनुशंसित',
  'Kronolojik': 'कालानुक्रमिक',
  'Gelen mesaj istekleri': 'आने वाले संदेश अनुरोध',
  'Mesaj isteğin yok': 'कोई संदेश अनुरोध नहीं',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'जिन लोगों को आप फॉलो नहीं करते उनके संदेश यहाँ दिखते हैं।',
  'Çevrimiçi durumumu gizle': 'मेरी ऑनलाइन स्थिति छिपाएँ',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'दूसरे लोग संदेशों में आपकी ऑनलाइन स्थिति और अंतिम बार देखा गया समय नहीं देख पाएंगे',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'हमारे पहले उपयोगकर्ताओं में से एक। उनकी प्रतिक्रिया से ऐप आज जैसा है वैसा बना।',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'तुम हमारे पहले उपयोगकर्ताओं में से एक हो। तुम्हारी प्रतिक्रिया से ऐप आज जैसा है वैसा बना।',
  'İleri': 'आगे',
  'Önceki': 'पिछला',
  'Sonraki': 'अगला',
  'Seçilen dosya okunamadı': 'चुनी गई फ़ाइल पढ़ी नहीं जा सकी',
  'Video açılamadı': 'वीडियो नहीं खुल सका',
  'En fazla {} medya seçebilirsin': 'आप अधिकतम {} मीडिया चुन सकते हैं',
  'Hiçbir medya yüklenemedi': 'कोई भी मीडिया अपलोड नहीं हो सका',
  'Seçimi kaldır': 'चयन हटाएं',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'एक टिप्पणी में कुल {} MB मीडिया अपलोड कर सकते हैं',
  '{} dosya okunamadı': '{} फ़ाइलें पढ़ी नहीं जा सकीं',
  '{} medya eklendi, {} yüklenemedi': '{} मीडिया जोड़े गए, {} अपलोड नहीं हुए',
  'Kırp': 'क्रॉप',
  'Çiz': 'ड्रा',
  'Metin': 'टेक्स्ट',
  'Emoji': 'इमोजी',
  'Yinele': 'दोबारा करें',
  'Daha fazla': 'और',
  'Hazırlanıyor…': 'तैयार हो रहा है…',
  'Düzenlemeden çık?': 'संपादन से बाहर निकलें?',
  'Yaptığın değişiklikler kaybolacak.': 'आपके किए गए बदलाव खो जाएंगे.',
  'Çık': 'बाहर निकलें',
  'Serbest çizim': 'फ्रीहैंड',
  'Ok': 'तीर',
  'Dikdörtgen': 'आयत',
  'Daire': 'वृत्त',
  'Bulanıklaştır': 'धुंधला करें',
  'Pikselleştir': 'पिक्सलेट करें',
  'Silgi': 'इरेज़र',
  'Çizgi kalınlığı': 'लाइन की मोटाई',
  'Saydamlık': 'पारदर्शिता',
  'Dolgu': 'भरें',
  'Renk': 'रंग',
  'Döndür': 'घुमाएं',
  'Yansıt': 'पलटें',
  'Oran': 'अनुपात',
  'Sıfırla': 'रीसेट',
  'Serbest': 'फ्री',
  'Metin yaz...': 'टेक्स्ट लिखें...',
  'Hizala': 'संरेखित करें',
  'Arka plan': 'पृष्ठभूमि',
  'Emoji ara...': 'इमोजी खोजें...',
  'Son kullanılanlar': 'हाल के',
  'İfadeler ve insanlar': 'स्माइली और लोग',
  'Hayvanlar ve doğa': 'जानवर और प्रकृति',
  'Yiyecek ve içecek': 'खाना और पेय',
  'Etkinlikler': 'गतिविधियाँ',
  'Seyahat ve yerler': 'यात्रा और स्थान',
  'Nesneler': 'वस्तुएँ',
  'Semboller': 'प्रतीक',
  'Bayraklar': 'झंडे',
  'Görseli düzenle': 'फ़ोटो संपादित करें',
  'Düzenlendi': 'संपादित',
  'Düzenlenemedi': 'संपादित नहीं हो सका',
  'Düzenlenen görsel çok büyük': 'संपादित छवि बहुत बड़ी है',
  'Videoyu düzenle': 'वीडियो संपादित करें',
  'Sesi kapat': 'आवाज़ बंद करें',
  'Sesi aç': 'आवाज़ चालू करें',
  'İptal ediliyor…': 'रद्द किया जा रहा है…',
  'Bu biraz sürebilir': 'इसमें कुछ समय लग सकता है',
  'Video çok büyük': 'वीडियो बहुत बड़ा है',
  'Video hazırlanamadı': 'वीडियो तैयार नहीं हो सका',
  'Başlangıç': 'शुरू',
  'Bitiş': 'अंत',
  'En çok {} saniye seçebilirsin': 'आप अधिकतम {} सेकंड चुन सकते हैं',
  'Dosya en fazla {} MB olabilir': 'फ़ाइल अधिकतम {} MB हो सकती है',
  'Medya ekle': 'मीडिया जोड़ें',
  'Seçili medya kalmadı': 'कोई मीडिया चयनित नहीं',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'अपनी टिप्पणी में जोड़ने के लिए फ़ोटो या वीडियो चुनें।',
  'Medya seç': 'मीडिया चुनें',
  'Daha fazla ekle': 'और जोड़ें',
  'Medya seçilemedi': 'मीडिया नहीं चुना जा सका',
  'Favori oyuncular': 'पसंदीदा कलाकार',
  'Henüz favori oyuncun yok': 'अभी कोई पसंदीदा कलाकार नहीं',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'किसी कलाकार का पेज खोलें और ऊपर दाईं ओर दिल पर टैप करें; वे यहाँ जुड़ जाएंगे।',
  '{} yapımdan {} tanesini izledin': '{} में से {} देखे',
  'izledin': 'देखा',
  'İzlemedin': 'नहीं देखा',
  'Yapım bulunamadı': 'कोई शीर्षक नहीं मिला',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'इस व्यक्ति की कोई सीरीज या फिल्म सूचीबद्ध नहीं है।',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'आपका देखने का इतिहास आपके खाते से जुड़ा है; यह सूची केवल आपकी है।',
  'Hesabın kalıcı olarak askıya alındı':
      'आपका खाता स्थायी रूप से निलंबित कर दिया गया है',
  'Hesabın geçici olarak askıya alındı':
      'आपका खाता अस्थायी रूप से निलंबित कर दिया गया है',
  'Hesabın askıya alındı': 'आपका खाता निलंबित है',
  'Sebep': 'कारण',
  'Kalan süre': 'शेष समय',
  'Süre dolunca hesabın kendiliğinden açılır':
      'समय पूरा होने पर आपका खाता अपने आप खुल जाएगा',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'इस दौरान आप पढ़ना जारी रख सकते हैं, लेकिन पोस्ट, टिप्पणी या संदेश नहीं भेज सकते।',
  'Anladım': 'समझ गया',
  'Ayrıntı': 'विवरण',
  '{} dakika': '{} मिनट',
  'birkaç saniye': 'कुछ सेकंड',
  'Karara itiraz et': 'इस फैसले पर आपत्ति करें',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'बताइए कि यह दंड क्यों हटाया जाना चाहिए',
  'İtirazını gönder': 'अपनी आपत्ति भेजें',
  'İtirazın incelemede': 'आपकी आपत्ति समीक्षाधीन है',
  'İtirazın reddedildi': 'आपकी आपत्ति अस्वीकार कर दी गई',
  'İtirazın alındı, inceleniyor': 'आपकी आपत्ति मिल गई, समीक्षा जारी है',
  'İtiraz en az 10 karakter olmalı': 'आपत्ति कम से कम 10 अक्षर की होनी चाहिए',
  'Yükleniyor...': 'लोड हो रहा है...',
  'Bu bölüme puan ver': 'इस एपिसोड को रेट करें',
  '{} kişi puanladı': '{} लोगों ने रेट किया',
  'Bölüm izlendi olarak işaretlendi': 'एपिसोड देखा गया के रूप में चिह्नित',
  'Sesli ara': 'वॉइस कॉल',
  'Görüntülü ara': 'वीडियो कॉल',
  'Çalıyor...': 'रिंग हो रही है...',
  'Bağlanıyor...': 'कनेक्ट हो रहा है...',
  'Cevapla': 'उत्तर दें',
  'Reddet': 'अस्वीकार करें',
  'Sessize al': 'म्यूट',
  'Hoparlör': 'स्पीकर',
  'Kamerayı kapat': 'कैमरा बंद करें',
  'Kamerayı çevir': 'कैमरा बदलें',
  'Cevap yok': 'कोई जवाब नहीं',
  'Arama reddedildi': 'कॉल अस्वीकार की गई',
  'Meşgul': 'व्यस्त',
  'Bağlanılamadı': 'कनेक्ट नहीं हो सका',
  'Arama iptal edildi': 'कॉल रद्द की गई',
  'Arama geçmişi': 'कॉल इतिहास',
  'Gelen arama': 'इनकमिंग कॉल',
  'Giden arama': 'आउटगोइंग कॉल',
  'Cevapsız arama': 'मिस्ड कॉल',
  'Arama şu anda kullanılamıyor': 'कॉलिंग अभी उपलब्ध नहीं है',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'वीडियो कॉल अभी बंद है, आप वॉइस कॉल कर सकते हैं',
  'Bu kullanıcıyı arayamazsın': 'आप इस उपयोगकर्ता को कॉल नहीं कर सकते',
  'Aramak için karşılıklı takipleşmelisiniz':
      'कॉल करने के लिए आपको एक-दूसरे को फ़ॉलो करना होगा',
  'Bu kullanıcı şu anda aranamıyor':
      'इस उपयोगकर्ता को अभी कॉल नहीं किया जा सकता',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'बहुत सारी मिस्ड कॉल। {} बाद फिर कोशिश करें',
  'Zaten bir aramadasın': 'आप पहले से ही एक कॉल पर हैं',
  'Arama için mikrofon izni gerekiyor': 'कॉल के लिए माइक्रोफ़ोन अनुमति चाहिए',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'वीडियो कॉल के लिए कैमरा और माइक्रोफ़ोन अनुमति चाहिए',
  'Arama başlatılamadı': 'कॉल शुरू नहीं हो सकी',
  'Kullanıcı bulunamadı': 'उपयोगकर्ता नहीं मिला',
  'Kendini arayamazsın': 'आप खुद को कॉल नहीं कर सकते',
  'Arama artık geçerli değil': 'यह कॉल अब मान्य नहीं है',
  'Bu aramanın tarafı değilsin': 'आप इस कॉल का हिस्सा नहीं हैं',
  'Arama bulunamadı': 'कॉल नहीं मिली',
  'Çok fazla istek, biraz bekle': 'बहुत ज़्यादा अनुरोध, थोड़ा इंतज़ार करें',
  'Bağlantı koptu': 'कनेक्शन टूट गया',
  'Arama süre sınırına ulaştı': 'कॉल समय सीमा तक पहुँच गई',
  'Arama en fazla 4 saat sürebilir': 'एक कॉल अधिकतम 4 घंटे चल सकती है',
  'Arama sona erdi': 'कॉल समाप्त हो गई',
  'Sesli arama': 'वॉइस कॉल',
  'Görüntülü arama': 'वीडियो कॉल',
  'Gelen aramalar': 'इनकमिंग कॉल',
  'Sesli ve görüntülü arama bildirimleri': 'वॉइस और वीडियो कॉल सूचनाएँ',
  '{} sa': '{} घं',
  'Sesli ve Görüntülü Aramalar': 'वॉइस और वीडियो कॉल',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'कॉल की सामग्री रिकॉर्ड नहीं की जाती। ऑडियो और वीडियो डिवाइसों के बीच एंड-टू-एंड एन्क्रिप्टेड (DTLS-SRTP) चलते हैं; हमारे सर्वर इस ट्रैफ़िक को डिक्रिप्ट, सुन या संग्रहीत नहीं कर सकते।',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'केवल कॉल मेटाडेटा रखा जाता है: किसके साथ, किस दिशा में, कब और कितनी देर। ये रिकॉर्ड 90 दिन बाद अपने आप हट जाते हैं।',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'यदि सीधा कनेक्शन नहीं बन पाता, तो ऑडियो और वीडियो एन्क्रिप्टेड रूप में एक रिले सर्वर (TURN) से गुज़रते हैं। रिले सर्वर भी सामग्री को डिक्रिप्ट या रिकॉर्ड नहीं कर सकता।',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'माइक्रोफ़ोन केवल वॉइस या वीडियो कॉल के दौरान और कैमरा केवल वीडियो कॉल के दौरान उपयोग होता है। कॉल खत्म होते ही दोनों बंद हो जाते हैं।',
  'Takip ettiğin {} kişi izledi': 'आपके फ़ॉलो किए लोगों में से {} ने देखा',
  'Yorum yaz...': 'टिप्पणी लिखो...',
  'Sıradaki bölüm': 'अगला एपिसोड',
  'Doğrulanmış testçi': 'सत्यापित परीक्षक',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'फ़ॉलो, लाइक, जवाब, संदेश और टैग की सूचनाएँ',
  'Sen': 'तुम',
  'Aradığınız kişide sesli arama devre dışı':
      'इस व्यक्ति के लिए वॉइस कॉल बंद है',
  'Aradığınız kişide görüntülü arama devre dışı':
      'इस व्यक्ति के लिए वीडियो कॉल बंद है',
  'Sesli aramalara izin ver': 'वॉइस कॉल की अनुमति दें',
  'Görüntülü aramalara izin ver': 'वीडियो कॉल की अनुमति दें',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'बंद होने पर कोई आपको वॉइस कॉल नहीं कर सकता; कॉल करने वाले को सूचना दिखती है',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'बंद होने पर कोई आपको वीडियो कॉल नहीं कर सकता; कॉल करने वाले को सूचना दिखती है',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'वॉइस कॉल बंद है। आप इसे सेटिंग्स > गोपनीयता से चालू कर सकते हैं।',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'वीडियो कॉल बंद है। आप इसे सेटिंग्स > गोपनीयता से चालू कर सकते हैं।',
  'Sesli ve görüntülü arama': 'वॉइस और वीडियो कॉल',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'अतिथि खाते कॉल नहीं कर सकते। खाता बनाने पर इसका उपयोग कर सकोगे।',
  'Misafir hesaplar aranamaz': 'अतिथि खातों को कॉल नहीं किया जा सकता',
  'Puan dağılımı': 'रेटिंग वितरण',
  '{} yıldız': '{} स्टार',
  'Yakında gelecek': 'जल्द आ रहा है',
  '{} {} yayınlandı': '{} {} रिलीज़ हो गया',
  'Yeni bölüm yayınlandı': 'नया एपिसोड रिलीज़ हो गया',
  'Yeni bölümler': 'नए एपिसोड',
  'Geri': 'वापस',
  'Karşılamayı kapat': 'परिचय बंद करो',
  'Adım {} / {}': 'चरण {} / {}',
  'Hadi başlayalım': 'चलो शुरू करते हैं',
  'Kaydet ve devam': 'सेव करो और आगे बढ़ो',
  '{} tanesini ekle': '{} जोड़ो',
  'Şimdilik geç': 'अभी छोड़ो',
  'Doğum tarihin ne zaman?': 'तुम्हारी जन्मतिथि क्या है?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'उम्र के हिसाब से सामग्री दिखाने और जन्मदिन की बधाई देने के लिए पूछ रहे हैं।',
  'Gün': 'दिन',
  'Ay': 'महीना',
  'Yıl': 'साल',
  'Doğum yılımı paylaşmak istemiyorum': 'मुझे अपने जन्म का साल साझा नहीं करना',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'तुम्हारी जन्मतिथि प्रोफ़ाइल में सबको नहीं दिखाई जाती। इसका इस्तेमाल सिर्फ़ उम्र के हिसाब से सामग्री और जन्मदिन की बधाई के लिए होता है।',
  'Ocak': 'जनवरी',
  'Şubat': 'फ़रवरी',
  'Mart': 'मार्च',
  'Nisan': 'अप्रैल',
  'Mayıs': 'मई',
  'Haziran': 'जून',
  'Temmuz': 'जुलाई',
  'Ağustos': 'अगस्त',
  'Eylül': 'सितंबर',
  'Ekim': 'अक्टूबर',
  'Kasım': 'नवंबर',
  'Aralık': 'दिसंबर',
  'Verilerini yanında getir': 'अपना डेटा साथ ले आओ',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'किसी दूसरे ऐप में देखे हुए का हिसाब रखा है तो उसे यहाँ ले आओ। सब कुछ शुरू से करने की ज़रूरत नहीं।',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt और Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'वहाँ से एक्सपोर्ट की गई ZIP फ़ाइल चुनो; देखे हुए, रेटिंग और लिस्ट्स यहाँ आ जाएँगी।',
  'Aktarılıyor...': 'इंपोर्ट हो रहा है...',
  'ZIP dosyası seç': 'ZIP फ़ाइल चुनो',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'जल्दी कुछ नहीं: यह बाद में सेटिंग्स > मेरा डेटा से भी किया जा सकता है।',
  'Hangi filmleri izledin?': 'तुमने कौन-सी फ़िल्में देखीं?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'सबसे ज़्यादा देखी गई फ़िल्में यहाँ हैं। जिन पर टैप करो, वे तुम्हारे देखे हुए में जुड़ जाएँगी।',
  'SERİ FİLMLER': 'फ़िल्म सीरीज़',
  'Serilerden {} film eklendi': 'सीरीज़ से {} फ़िल्में जुड़ीं',
  'Film listesi yüklenemedi': 'फ़िल्मों की लिस्ट लोड नहीं हो सकी',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'यह चरण छोड़ा जा सकता है, बाद में जो चाहो जोड़ लेना।',
  '{} film izlediklerine eklendi': '{} फ़िल्में तुम्हारे देखे हुए में जुड़ गईं',
  'Film serileri': 'फ़िल्म सीरीज़',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'पूरी सीरीज़ शुरू से आख़िर तक देखी है तो एक टैप में जोड़ दो।',
  'Seri bulunamadı': 'कोई सीरीज़ नहीं मिली',
  'Daha sonra tekrar deneyebilirsin.': 'बाद में फिर से कोशिश करना।',
  '{} film': '{} फ़िल्में',
  'Eklendi': 'जोड़ा गया',
  'Tümünü izledim': 'सभी देखी हैं',
  'Peki ya diziler?': 'और सीरीज़ का क्या?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'देखी हुई सीरीज़ चुनो; चुनाव के हिसाब से तुम्हारे जैसे और सुझाव लाते जाएँगे।',
  'Dizi listesi yüklenemedi': 'सीरीज़ की लिस्ट लोड नहीं हो सकी',
  'Seçtiklerine benzeyenler': 'तुम्हारे चुनाव से मिलती-जुलती',
  'Her şey hazır': 'सब तैयार है',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'dizi.jpg में क्या-क्या हो सकता है, एक नज़र देख लो।',
  'Profilini tamamla': 'अपनी प्रोफ़ाइल पूरी करो',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'सेटिंग्स से बायो, प्रोफ़ाइल फ़ोटो और कवर जोड़े जा सकते हैं।',
  'Takvimin seni bekliyor': 'कैलेंडर तुम्हारा इंतज़ार कर रहा है',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'तुम्हारी सीरीज़ के नए एपिसोड कैलेंडर में आ जाते हैं और सूचना से खबर कर देते हैं।',
  'Puan ver, yorum yaz': 'रेट करो, कमेंट लिखो',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'एपिसोड-दर-एपिसोड रेट करो, स्पॉइलर परदे के साथ कमेंट लिखो, लिस्ट्स बनाओ।',
  'Verilerin sende kalır': 'डेटा तुम्हारा ही रहता है',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'तुम्हारा डेटा सिर्फ़ तुम्हारे खाते से जुड़ा रहता है, बेचा नहीं जाता। सेटिंग्स से पूरा डेटा डाउनलोड किया जा सकता है या खाता पूरी तरह मिटाया जा सकता है।',
  'Engellenen kullanıcılar': 'ब्लॉक किए गए उपयोगकर्ता',
  'Engellediğin kişileri gör, engeli kaldır':
      'ब्लॉक किए लोगों को देखो, अनब्लॉक करो',
  'Engellediğin kimse yok': 'तुमने किसी को ब्लॉक नहीं किया',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'किसी उपयोगकर्ता को उसकी प्रोफ़ाइल के तीन-बिंदु मेन्यू से ब्लॉक किया जा सकता है।',
  '@{} engellensin mi?': '@{} को ब्लॉक करें?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'एक-दूसरे की पोस्ट, कमेंट और प्रोफ़ाइल दोनों में से किसी को नहीं दिखेंगी; संदेश और कॉल भी नहीं जा सकेंगे। आपस में फ़ॉलो का रिश्ता है तो वह टूट जाएगा और ब्लॉक हटाने पर भी वापस नहीं आएगा।',
  'Bu kullanıcıyı engelledin': 'तुमने इस उपयोगकर्ता को ब्लॉक किया है',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'तुम्हें इस व्यक्ति की पोस्ट, कमेंट और संदेश नहीं दिखते; इस व्यक्ति को भी तुम्हारे नहीं दिखते।',
  '{} yeni bir yapımda: {}': '{} नए प्रोजेक्ट में: {}',
  'Favori kişinden yeni yapım': 'पसंदीदा व्यक्ति का नया प्रोजेक्ट',
  '{} için bildirimler': '{} के लिए सूचनाएँ',
  'Tüm bildirimler': 'सभी सूचनाएँ',
  'Uygulamada ve telefonda': 'ऐप में और फ़ोन पर',
  'Yalnız uygulama içi': 'सिर्फ़ ऐप में',
  'Telefon bildirimi gönderilmez': 'फ़ोन पर सूचना नहीं भेजी जाती',
  'Kapalı': 'बंद',
  'Bu kişi için bildirim yok': 'इस व्यक्ति के लिए कोई सूचना नहीं',
  'Favori kişilerin yeni yapımları': 'पसंदीदा लोगों के नए प्रोजेक्ट',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'बंद होने पर कोई तुम्हें वॉइस कॉल नहीं कर सकता; कॉल करने वाले को "बंद है" की सूचना दिखती है',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'बंद होने पर कोई तुम्हें वीडियो कॉल नहीं कर सकता; कॉल करने वाले को "बंद है" की सूचना दिखती है',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'मेरी गतिविधि',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'तुम्हारे लाइक, कमेंट और देखे गए सब एक ही जगह',
  'Henüz hareketin yok': 'अभी कोई गतिविधि नहीं',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'तुम्हारे लाइक, कमेंट और देखी गई हर चीज़ यहाँ जमा होती है।',
  'Bu süzgeçte hareket yok': 'इस फ़िल्टर में कोई गतिविधि नहीं',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'कोई दूसरा प्रकार चुनो या "सभी" पर लौटो।',
  'Hepsi': 'सभी',
  'Puan': 'रेटिंग',
  'Tepki': 'रिएक्शन',
  'İzleme': 'देखा गया',
  'Durum': 'स्टेटस',
  'Liste': 'लिस्ट',
  'Yorum yaptın': 'कमेंट किया',
  'Yorumu beğendin': 'कमेंट लाइक किया',
  '{} puan verdin': '{} रेटिंग दी',
  'Tepki verdin': 'रिएक्शन दिया',
  'Listene ekledin': 'लिस्ट में जोड़ा',
  'Takip etmeye başladın': 'फ़ॉलो करना शुरू किया',
  '"İzleyeceğim" işaretledin': 'वॉचलिस्ट में जोड़ा',
  '"İzliyorum" işaretledin': 'देखना शुरू किया',
  '"Bitirdim" işaretledin': 'देखना पूरा किया',
  '"Bıraktım" işaretledin': 'देखना छोड़ा',
  'Silinmiş içerik': 'हटाई गई सामग्री',
  'şimdi': 'अभी',
  '{} g': '{} दि',
  '{} y': '{} व',
  'İstatistiklerim': 'मेरे आँकड़े',
  'Gönderilerinin görüntülenmesi ve beğenisi': 'तुम्हारी पोस्ट के व्यू और लाइक',
  'Henüz gönderin yok': 'अभी तुम्हारी कोई पोस्ट नहीं',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'जब तुम किसी सीरीज़ या फ़िल्म पर कमेंट लिखोगे, तुम्हारे व्यू और लाइक यहाँ जमा होने लगेंगे।',
  'Tüm zamanlar': 'सर्वकालिक',
  'Son {} gün': 'पिछले {} दिन',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'व्यू का इतिहास अभी जमा होना शुरू नहीं हुआ; पहले दिन का डेटा कल दिखेगा।',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'व्यू का इतिहास {} से जमा हो रहा है ({} दिन का डेटा है), इसलिए {} दिन का आँकड़ा अभी अधूरा है।',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.': 'लाइक का इतिहास {} से दर्ज है।',
  'Bu dönemde gösterilecek gönderi yok.':
      'इस अवधि में दिखाने के लिए कोई पोस्ट नहीं।',
  'eksik veri': 'अधूरा डेटा',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'तुम्हारी प्रोफ़ाइल पर देखी गई सीरीज़ और फ़िल्में, तुम्हारे व्यू काउंटर, स्क्रीन टाइम और मैच कार्ड दूसरों को नहीं दिखेंगे',
  'Takipçi listemi gizle': 'मेरी फ़ॉलोअर सूची छिपाएँ',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'दूसरे नहीं देख पाएँगे कि तुम्हें कौन फ़ॉलो करता है; तुम्हारी फ़ॉलोअर संख्या दिखती रहेगी',
  'Takip ettiklerimi gizle': 'मैं किसे फ़ॉलो करता हूँ यह छिपाएँ',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'तुम किसे फ़ॉलो करते हो यह दूसरे नहीं देख पाएँगे; तुम्हारी फ़ॉलोइंग संख्या दिखती रहेगी',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'इस यूज़र के फ़ॉलोअर छिपे हुए हैं।',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'यह यूज़र किसे फ़ॉलो करता है यह छिपा हुआ है।',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'पोस्ट के आँकड़े',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'आप केवल अपनी पोस्ट के आँकड़े देख सकते हैं।',
  'Erişim': 'पहुँच',
  'Görüntüleyen': 'देखने वाले',
  'Kaç farklı kişi gördü (son {} gün)':
      'कितने अलग-अलग लोगों ने देखा (पिछले {} दिन)',
  'Paylaşım': 'शेयर',
  'Bu gönderiden sonra': 'इस पोस्ट के बाद',
  'Profil ziyareti': 'प्रोफ़ाइल विज़िट',
  'Yeni takip': 'नए फ़ॉलो',
  'İçeriğe tıklama': 'कंटेंट पर टैप',
  'Spoiler perdesini açan': 'स्पॉइलर परदा हटाया',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'शेयर, प्रोफ़ाइल विज़िट, फ़ॉलो, कंटेंट पर टैप, स्रोत विवरण और स्पॉइलर माप {} से जमा हो रहे हैं; उससे पहले का मापा नहीं गया।',
  'Zamana yayılmış görüntülenme': 'समय के साथ व्यू',
  'Görüntülenme nereden geldi': 'व्यू कहाँ से आए',
  'Kimler gördü': 'किसने देखा',
  'Günlük veri henüz birikmeye başlamadı.':
      'दैनिक डेटा अभी जमा होना शुरू नहीं हुआ है।',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'ग्राफ़ के लिए कम से कम दो दिन का डेटा चाहिए। डेटा {} से जमा हो रहा है।',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'सबसे ज़्यादा व्यू पोस्ट करने के {} वें दिन आए: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'दैनिक व्यू {} से जमा हो रहे हैं; उससे पहले का मापा नहीं गया।',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'स्रोत विवरण अभी मापा जाना शुरू हुआ है; इस पोस्ट को अभी तक कोई टैग किया गया व्यू नहीं मिला।',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'फ़ॉलोअर/डिस्कवर विवरण अभी मापा जाना शुरू हुआ है; अभी कोई डेटा नहीं है।',
  'Takip edenler': 'फ़ॉलोअर',
  'Keşiften gelenler': 'डिस्कवर से',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'सीरीज़/फ़िल्म पेज',
  'Paylaşılan bağlantı': 'शेयर किया गया लिंक',
  'yeni ölçülüyor': 'नया मापा जा रहा',
  'Kendi ortalamanla aynı düzeyde': 'तुम्हारे अपने औसत के बराबर',
  'Kendi ortalamanın %{} üstünde': 'तुम्हारे अपने औसत से {}% ऊपर',
  'Kendi ortalamanın %{} altında': 'तुम्हारे अपने औसत से {}% नीचे',
  'Etkileşim oranı': 'एंगेजमेंट दर',
  '(beğeni + yorum) ÷ görüntülenme': '(लाइक + कमेंट) ÷ व्यू',
  'Toplam görüntülenme': 'कुल व्यू',
  '{} ile {} arasında toplam {} görüntülenme': '{} और {} के बीच कुल {} व्यू',
  'İstatistikleri gör': 'आँकड़े देखें',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'पोस्ट के मालिक को दिखाए जाने वाले आँकड़ों के लिए, यह सामूहिक काउंटर के रूप में रखा जाता है कि पोस्ट कितनी बार और किस सतह से (फ़ीड, प्रोफ़ाइल, फ़ुल-स्क्रीन फ़ीड, सीरीज़/फ़िल्म पेज, शेयर किया गया लिंक) देखी गई, देखने वाला उस समय पोस्ट के मालिक को फ़ॉलो कर रहा था या नहीं, पोस्ट से प्रोफ़ाइल/कंटेंट पर जाना, पोस्ट के ज़रिए बना फ़ॉलो, शेयर और स्पॉइलर परदे का खुलना। इन काउंटरों में उपयोगकर्ता पहचान, IP पता या टाइमस्टैम्प नहीं होता; किसने क्या किया, यह पूछा नहीं जा सकता।',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'यह गिनने के लिए कि किसी पोस्ट को कितने अलग-अलग लोगों ने देखा, प्रति दर्शक एक अपरिवर्तनीय कुंजीबद्ध डाइजेस्ट (उपयोगकर्ता पहचान या IP पते से व्युत्पन्न क्रिप्टोग्राफ़िक संक्षेपण) 90 दिनों तक रखा जाता है। पोस्ट के मालिक को केवल संख्या दिखाई जाती है; देखने वालों की पहचान किसी भी परिस्थिति में साझा नहीं की जाती।',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': '“देखना है” में ले जाएँ?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'कोई भी टाइटल या तो देखना बाकी होता है या देखा जा चुका होता है। आगे बढ़ने पर इस सीरीज़ में तुम्हारे {} देखने के निशान हट जाएँगे।',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'कोई भी टाइटल या तो देखना बाकी होता है या देखा जा चुका होता है। आगे बढ़ने पर इस फ़िल्म पर तुम्हारा “देख लिया” निशान हट जाएगा।',
  'Sil ve taşı': 'हटाकर ले जाओ',
  'Yapım Ekibi': 'निर्माण टीम',
  'Yaratıcı': 'रचयिता',
  'Yönetmen': 'निर्देशन',
  'Senaryo': 'पटकथा',
  'Yapımcı': 'निर्माण',
  'Yapım Firmaları': 'निर्माण कंपनियाँ',
  'Yapım Firması': 'निर्माण कंपनी',
  'Firma bulunamadı': 'कंपनी नहीं मिली',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'इस कंपनी का इस तरह का कोई शीर्षक नहीं है.',
  'Doğum günün kutlu olsun!': 'जन्मदिन मुबारक हो!',
  'İyi ki doğdun, iyi ki buradasın.':
      'अच्छा हुआ कि तुम्हारा जन्म हुआ, अच्छा है कि तुम यहाँ हो.',
  'Bugün {} yaşına girdin': 'आज तुम्हारे {} साल पूरे हुए',
  'Teşekkürler': 'धन्यवाद',
  'İki Adımlı Doğrulama': '2-स्टेप वेरिफ़िकेशन',
  'Girişte e-postana kod gönderilir':
      'लॉग इन करते समय ईमेल पर कोड भेजा जाता है',
  'Kod {} adresine gönderildi': 'कोड {} पर भेजा गया',
  '6 haneli kod': '6 अंकों का कोड',
  'Doğrula': 'वेरिफ़ाई करो',
  'Yeniden gönder': 'फिर से भेजो',
  'Vazgeç': 'रद्द करो',
  'Yeni kod gönderildi': 'नया कोड भेजा गया',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'Google से लॉग इन करने पर कोड नहीं पूछा जाता; वेरिफ़िकेशन Google की तरफ़ से होता है।',
  'Kapatmak için de kod gerekir.': 'इसे बंद करने के लिए भी कोड लगेगा।',
  'E-postana erişemezsen hesabına giremezsin.':
      'ईमेल तक पहुँच न रहने पर अकाउंट में लॉग इन नहीं हो पाएगा।',
  'İki adımlı doğrulama açıldı': '2-स्टेप वेरिफ़िकेशन चालू हुआ',
  'İki adımlı doğrulama kapatıldı': '2-स्टेप वेरिफ़िकेशन बंद हुआ',

  // --- md.24 video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': 'वीडियो कितना देखा गया',
  'Videoyu başlatanlar': 'वीडियो शुरू करने वाले',
  'videonun %{} noktasına ulaştı': 'वीडियो के {}% तक पहुँचे',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'देखने वालों में से आधों ने वीडियो का कम से कम {}% हिस्सा देखा।',
  'Sonuna kadar izleyen: %{}': 'आखिर तक देखने वाले: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'कर्व के लिए कम से कम {} व्यू चाहिए; अभी {} व्यू हैं।',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'कर्व {} व्यू पर बना है और चुनी गई समय अवधि से नहीं बदलता।',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'वॉच टाइम {} से मापा जा रहा है; उससे पुराने व्यू इस गिनती में नहीं हैं।',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} व्यू। वीडियो के आधे तक {}% और आखिर तक {}% पहुँचे।',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'लेवल {}',
  'Sonraki seviyeye {} puan kaldı': 'अगले लेवल के लिए {} पॉइंट बाकी',
  'Gönderilerin': 'तुम्हारी पोस्ट',
  '{} gönderi': '{} पोस्ट',
  '{} gönderi · {} görüntülenme': '{} पोस्ट · {} व्यू',
  'önceki {} güne göre': 'पिछले {} दिन की तुलना में',
  'önceki {} güne göre %{} arttı': 'पिछले {} दिन की तुलना में {}% बढ़ा',
  'önceki {} güne göre %{} azaldı': 'पिछले {} दिन की तुलना में {}% घटा',
  'önceki {} güne göre değişmedi': 'पिछले {} दिन की तुलना में कोई बदलाव नहीं',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'रोज़ाना व्यू: सबसे कम {}, सबसे ज़्यादा {}',
  'Etkileşim oranı henüz ölçülemedi': 'एंगेजमेंट दर अभी नहीं मापी जा सकी',
  'Oranlar': 'दरें',
  'Beğenme oranı': 'लाइक दर',
  'Yorum oranı': 'कमेंट दर',
  'Paylaşma oranı': 'शेयर दर',
  'İçeriğe gitme oranı': 'कंटेंट टैप दर',
  'Profile gitme oranı': 'प्रोफ़ाइल विज़िट दर',
  'Ziyaretten takibe dönüşüm': 'विज़िट से फ़ॉलो दर',
  'beğeni ÷ görüntülenme': 'लाइक ÷ व्यू',
  'yorum ÷ görüntülenme': 'कमेंट ÷ व्यू',
  'paylaşım ÷ görüntülenme': 'शेयर ÷ व्यू',
  'içeriğe tıklama ÷ görüntülenme': 'कंटेंट पर टैप ÷ व्यू',
  'profil ziyareti ÷ görüntülenme': 'प्रोफ़ाइल विज़िट ÷ व्यू',
  'yeni takip ÷ profil ziyareti': 'नए फ़ॉलो ÷ प्रोफ़ाइल विज़िट',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'दर के लिए कम से कम {} व्यू चाहिए; अभी {} हैं।',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'दरें पोस्ट के आजीवन आँकड़ों से बनती हैं; नीचे दिया गया दिन चुनाव इन्हें नहीं बदलता।',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'ये आँकड़े पोस्ट के आजीवन कुल हैं (अपनी अलग टिप्पणी वाले बॉक्स छोड़कर); नीचे दिया गया दिन चुनाव सिर्फ़ ग्राफ़ बदलता है।',
  'Ortalama izlenme: videonun %{} kadarı': 'औसत देखा गया: वीडियो का {}%',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'रिटेंशन कर्व के 20 खंडों का औसत।',
  'Dizi, film, kişi veya şirket ara...':
      'सीरीज़, फ़िल्म, व्यक्ति या कंपनी खोजो...',
  'Şirketler': 'कंपनियाँ',
  'Senarist': 'पटकथा लेखक',
  'Bölüm puanları': 'एपिसोड रेटिंग',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'एपिसोड रेटिंग लोड नहीं हो सकी',
  'Giriş gerekli': 'साइन इन ज़रूरी है',
  'Geçersiz oturum': 'अमान्य सत्र',
  'Oturum sonlandı, tekrar giriş yap': 'सत्र खत्म, फिर साइन इन करो',
  'Çok fazla istek; biraz sonra tekrar dene':
      'बहुत ज़्यादा अनुरोध; थोड़ी देर बाद कोशिश करो',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'सर्वर पर अभी जगह नहीं है, थोड़ी देर बाद कोशिश करें',
  'Devam eden yapımlar ({})': 'जारी प्रोडक्शन ({})',
  'Diziler ({})': 'सीरीज़ ({})',
  'Filmler ({})': 'फ़िल्में ({})',
  'Tüm yapımlar': 'सभी प्रोडक्शन',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'आपका मीडिया स्टोरेज भर गया है; जगह बनाने के लिए पुराने अपलोड हटाएँ',
  'E-posta/kullanıcı adı veya şifre hatalı': 'ईमेल/यूज़रनेम या पासवर्ड गलत है',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'यह ईमेल या यूज़रनेम पहले से लिया गया है',
  'Google doğrulaması başarısız': 'Google पुष्टि असफल रही',
  'Kod geçersiz veya süresi dolmuş': 'कोड गलत है या समय खत्म',
  'Bu kullanıcıyla mesajlaşamazsın': 'इस यूज़र को संदेश नहीं भेज सकते',
  'Kendini takip edemezsin': 'खुद को फॉलो नहीं कर सकते',
  'Bu kullanıcıyı takip edemezsin': 'इस यूज़र को फॉलो नहीं कर सकते',
  'Kendini engelleyemezsin': 'खुद को ब्लॉक नहीं कर सकते',
  'Yorum 1-1000 karakter olmalı': 'टिप्पणी 1–1000 अक्षर की होनी चाहिए',
  'Boş mesaj gönderilemez': 'खाली संदेश नहीं भेज सकते',
  'Yorum bulunamadı': 'टिप्पणी नहीं मिली',
  'Şifre hatalı': 'पासवर्ड गलत है',
  'Şifre en az 6 karakter olmalı': 'पासवर्ड कम से कम 6 अक्षर का हो',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'केवल GIF, PNG, JPEG या WebP अपलोड हो सकते हैं',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'समर्थित प्रकार: GIF, PNG, JPEG, WebP, MP4, WebM, ऑडियो',
  'Geçerli bir ZIP dosyası değil': 'मान्य ZIP फ़ाइल नहीं',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'डेटा ईमेल से पाने के लिए पहले खाते से ईमेल जोड़ो',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'इस पर देखने का रिकॉर्ड है। "देखूँगा" कहने से पहले निशान हटाने होंगे।',
  'Arama şu anda kapalı': 'कॉलिंग अभी बंद है',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'मेहमान खाता कॉलिंग नहीं खोल सकता; खाता बनाओ तो चलेंगे',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'सर्वर रीस्टार्ट हो रहा है, थोड़ी देर बाद कोशिश करो',
  'Puan 1-10 arası olmalı': 'स्कोर 1 से 10 के बीच हो',
  'En fazla 10 medya eklenebilir': 'ज़्यादा से ज़्यादा 10 मीडिया जोड़ सकते हो',
  'Bu cihazdan yeni hesap açılamıyor': 'इस डिवाइस से नया खाता नहीं खोल सकते',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'मान्य ईमेल, उपयोगकर्ता नाम और कम से कम 6 अक्षर का पासवर्ड चाहिए',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'मान्य ईमेल और कम से कम 6 अक्षर का पासवर्ड चाहिए',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'उपयोगकर्ता नाम 3–20 अक्षर; छोटे अक्षर, अंक, बिंदु, हाइफ़न, अंडरस्कोर (आगे/पीछे बिंदु-हाइफ़न नहीं)',
  'Bu hesap zaten bağlı': 'यह खाता पहले से जुड़ा है',
  'Hesap oluşturulamadı': 'खाता नहीं बन सका',
  'Misafir hesabı oluşturulamadı': 'अतिथि खाता नहीं बन सका',
  'Hesap bulunamadı': 'खाता नहीं मिला',
  'Bu hesapta e-posta yok': 'इस खाते में ईमेल नहीं है',
  'İki adımlı doğrulama zaten bu durumda':
      'दो-चरण सत्यापन पहले से इसी स्थिति में है',
  'Kod yanlış': 'कोड गलत है',
  'Kodun süresi doldu': 'कोड की समय सीमा खत्म',
  'Kullanıcının e-postası yok (misafir hesap)':
      'इस उपयोगकर्ता के पास ईमेल नहीं (अतिथि खाता)',
  'Bio en fazla 300 karakter olabilir': 'बायो ज़्यादा से ज़्यादा 300 अक्षर',
  'Geçersiz ülke': 'अमान्य देश',
  'Geçersiz sosyal bağlantı': 'अमान्य सोशल लिंक',
  'Geçersiz doğum tarihi': 'अमान्य जन्म तिथि',
  'Liste adı gerekli': 'सूची का नाम ज़रूरी है',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'नाम ज़्यादा से ज़्यादा 60, विवरण 300 अक्षर',
  'Liste bulunamadı': 'सूची नहीं मिली',
  'Değiştirilecek tercih yok': 'अपडेट करने को कुछ नहीं',
  'İnceleme en fazla 2000 karakter olabilir':
      'समीक्षा ज़्यादा से ज़्यादा 2000 अक्षर',
  'Önce içeriği "bitirdim" olarak işaretle':
      'पहले इसे पूरा देखा हुआ चिह्नित करो',
  'Önce kişiyi favorile': 'पहले इस व्यक्ति को पसंदीदा करो',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'एपिसोड टिप्पणी के लिए सीज़न और एपिसोड दोनों चाहिए',
  'Yanıtlanan yorum bulunamadı': 'जिस टिप्पणी का जवाब है वह नहीं मिली',
  'Geri bildirim 3-2000 karakter olmalı': 'फ़ीडबैक 3–2000 अक्षर होना चाहिए',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'शीर्षक और पाठ ज़रूरी हैं (कम से कम 2 अक्षर)',
  'Kendine mesaj gönderemezsin': 'खुद को संदेश नहीं भेज सकते',
  'Mesaj en fazla 2000 karakter olabilir':
      'संदेश ज़्यादा से ज़्यादा 2000 अक्षर',
  'Mesaj 1-2000 karakter olmalı': 'संदेश 1–2000 अक्षर होना चाहिए',
  'Mesaj bulunamadı': 'संदेश नहीं मिला',
  'Mesaj bulunamadı veya düzenlenemez':
      'संदेश नहीं मिला या संपादित नहीं हो सकता',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'केवल तुम्हें आए संदेश की शिकायत कर सकते हो',
  'Sebep gerekli': 'कारण ज़रूरी है',
  'İtiraz edilecek aktif bir ceza yok': 'अपील करने लायक कोई सक्रिय सज़ा नहीं',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'तुम्हारी एक अपील पहले से समीक्षा की प्रतीक्षा में है',
  'Bu ceza için itirazın zaten incelendi':
      'इस सज़ा की अपील पहले ही देखी जा चुकी है',
  'Medya bağlantısının süresi dolmuş': 'मीडिया लिंक की समय सीमा खत्म',
  'Bu medya için imzalı bağlantı gerekli':
      'इस मीडिया के लिए हस्ताक्षरित लिंक ज़रूरी है',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'कॉलिंग सेवा रीस्टार्ट हो रही है; थोड़ी देर बाद कोशिश करो',
  'Puan göstergesi': 'रेटिंग लेजेंड',
  'İzleme İstatistiklerim': 'मेरे देखने के आँकड़े',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'जैसे ही आप किसी एपिसोड या फ़िल्म को देखा हुआ चिह्नित करेंगे, आपके आँकड़े यहाँ जुड़ना शुरू हो जाएँगे।',
  '{} sa {} dk': '{} घं {} मि',
  'Yaklaşık ekran süresi': 'अनुमानित स्क्रीन समय',
  'İzleme serisi': 'देखने की लय',
  'Şu anki seri': 'मौजूदा लय',
  'En uzun seri': 'सबसे लंबी लय',
  'Haftanın günleri': 'सप्ताह के दिन',
  'En çok izlediklerin': 'सबसे ज़्यादा देखे गए',
  'Bu dönemde izleme yok': 'इस अवधि में कोई देखना नहीं',
  'Paz': 'रवि',
  'Pzt': 'सोम',
  'Sal': 'मंगल',
  'Çar': 'बुध',
  'Per': 'गुरु',
  'Cum': 'शुक्र',
  'Cmt': 'शनि',
  '{} bölüm': '{} एपिसोड',
  '{} bölüm~tekil': '{} एपिसोड',
  '{} kez': '{} बार',
  '{} kez~tekil': '{} बार',
  'Son {} gün · günlük': 'पिछले {} दिन · रोज़ाना',
  'Son {} gün · haftalık': 'पिछले {} दिन · साप्ताहिक',
  'Ekran süren, serin ve en çok izlediklerin':
      'आपका स्क्रीन समय, लय और सबसे ज़्यादा देखे गए',
  'Daralt': 'छोटा करें',
  'Listeyi düzenle': 'सूची संपादित करें',
  'Bitti': 'हो गया',
  'Sırala': 'क्रम बदलें',
  'Herkese göster': 'सबको दिखाएँ',
  'Başkalarından gizle': 'दूसरों से छिपाएँ',
  'Listeden kaldır': 'सूची से हटाएँ',
  'Listeden kaldırılsın mı?': 'सूची से हटाएँ?',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'यह शीर्षक सूची से निकाल दिया जाएगा। अगर आप इसे सिर्फ़ छिपाना चाहते हैं तो आँख के चिह्न का उपयोग करें।',
  'Sıralama kaydedilemedi': 'क्रम सहेजा नहीं जा सका',
  'Değişiklik kaydedilemedi': 'बदलाव सहेजा नहीं जा सका',
  'Kaldırılamadı': 'हटाया नहीं जा सका',
  'Popülerlik': 'लोकप्रियता',
  'TMDB puanı': 'TMDB रेटिंग',
  'Yapım yılı': 'निर्माण वर्ष',
  'dizi.jpg puanı': 'dizi.jpg रेटिंग',
  'İzlenme': 'देखे गए',
  'Yorum sayısı': 'टिप्पणियों की संख्या',
  'Tüm raflara uygulanır': 'सभी शेल्फ़ पर लागू होता है',
  'En popüler {} yapım arasında sıralandı':
      '{} सबसे लोकप्रिय शीर्षकों में क्रमबद्ध',
  'Altyazı görünümü': 'उपशीर्षक का रूप',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık':
      'रंग, फ़ॉन्ट, आकार, किनारा और अपारदर्शिता',
  'Bu bir örnek altyazıdır.': 'यह एक नमूना उपशीर्षक है।',
  'Ayar değiştikçe önizleme anında güncellenir.':
      'सेटिंग बदलते ही प्रीव्यू तुरंत अपडेट होता है।',
  'Yazı biçimi': 'टेक्स्ट शैली',
  'Yazı rengi': 'टेक्स्ट का रंग',
  'Yazı opaklığı': 'टेक्स्ट की अपारदर्शिता',
  'Yazı tipi': 'फ़ॉन्ट',
  'Yazı boyutu': 'टेक्स्ट का आकार',
  'Karakter ayrıtı': 'अक्षर का किनारा',
  'Ayrıt türü': 'किनारे का प्रकार',
  'Ayrıt rengi': 'किनारे का रंग',
  'Yok': 'कोई नहीं',
  'Dış çizgi': 'आउटलाइन',
  'Gölge': 'ड्रॉप शैडो',
  'Kabartma': 'उभरा हुआ',
  'Oyma': 'धंसा हुआ',
  'Arka plan rengi': 'पृष्ठभूमि का रंग',
  'Arka plan opaklığı': 'पृष्ठभूमि की अपारदर्शिता',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      'पृष्ठभूमि टेक्स्ट के ठीक पीछे की भराई है; विंडो पूरे उपशीर्षक ब्लॉक के पीछे की बड़ी सतह है।',
  'Pencere': 'विंडो',
  'Pencere rengi': 'विंडो का रंग',
  'Pencere opaklığı': 'विंडो की अपारदर्शिता',
  'Altyazı görünümü sıfırlansın mı?': 'उपशीर्षक का रूप रीसेट करें?',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      'रंग, फ़ॉन्ट, आकार, किनारा और अपारदर्शिता सेटिंग डिफ़ॉल्ट पर लौट आएंगी।',
  'Altyazı görünümü varsayılana döndü': 'उपशीर्षक का रूप डिफ़ॉल्ट पर लौट आया',
  '{} indiriliyor…': '{} डाउनलोड हो रहा है…',
  'Seçince indirilir': 'चुनने पर डाउनलोड होगा',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      'फ़ॉन्ट डाउनलोड नहीं हो सका। डिफ़ॉल्ट फ़ॉन्ट से दिखाया जा रहा है।',
  'Beyaz': 'सफ़ेद',
  'Siyah': 'काला',
  'Kırmızı': 'लाल',
  'Yeşil': 'हरा',
  'Mavi': 'नीला',
  'Sarı': 'पीला',
  'Camgöbeği': 'सियान',
  'Macenta': 'मैजेंटा',
  'Yapım bütçesi': 'निर्माण बजट',
  'Yapım bütçesi ve dünya çapında hasılat': 'निर्माण बजट और दुनिया भर की कमाई',
  'Dizinin yayın durumu': 'शो का प्रसारण स्टेटस',
  'Devam ediyor': 'चल रहा है',
  'Sona erdi': 'खत्म हो गया',
  'İptal edildi': 'रद्द कर दिया गया',
  'Yapımda': 'निर्माणाधीन',
  'Planlandı': 'योजना में',
  'Pilot bölüm': 'पायलट एपिसोड',
  'Ad': 'नाम',
  'Adın': 'तुम्हारा नाम',
  'Kullanıcı adı': 'यूज़रनेम',
  'Kullanıcı adını değiştir': 'यूज़रनेम बदलो',
  'Kullanıcı adını 90 günde bir değiştirebilirsin':
      'यूज़रनेम 90 दिन में एक बार बदल सकते हो',
  'Değiştir': 'बदलो',
  '{} gün sonra değiştirebilirsin': '{} दिन बाद बदल सकते हो',
  'Kullanıcı adın: @{}': 'तुम्हारा यूज़रनेम: @{}',
  'Bu kullanıcı adı zaten alınmış': 'यह यूज़रनेम पहले से लिया जा चुका है',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış':
      'यह यूज़रनेम फ़िलहाल किसी दूसरे अकाउंट के लिए सुरक्षित है',
  'Bu zaten senin kullanıcı adın': 'यह पहले से ही तुम्हारा यूज़रनेम है',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      'यूज़रनेम 3–20 अक्षर; छोटे अक्षर, अंक, बिंदु, हाइफ़न, अंडरस्कोर',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      'प्रोफ़ाइल में तुम्हारे यूज़रनेम के ऊपर दिखता है। खाली भी छोड़ सकते हो।',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      'बदलने के बाद 90 दिन तक दोबारा नहीं बदल पाओगे। तुम्हारा पुराना यूज़रनेम 90 दिन तक तुम्हारे लिए सुरक्षित रहेगा — चाहो तो वापस ले सकते हो, इस दौरान कोई और नहीं ले सकता। पुराने नाम वाले लिंक अब तुम्हारी प्रोफ़ाइल नहीं खोलेंगे।',
  'Etkinliğim': 'गतिविधि',
  'Tercihler': 'प्राथमिकताएँ',
  'Gizlilik ve güvenlik': 'प्राइवेसी और सुरक्षा',
  'Destek': 'सहायता',
  'Hesap': 'अकाउंट',
  '{} dizileri': '{} की सीरीज़',
  '{} filmleri': '{} की फ़िल्में',
  'En üste taşı': 'सबसे ऊपर ले जाएँ',
  'Sırayı sıfırla': 'क्रम रीसेट करें',
  'Listede ara': 'सूची में खोजें',
  'Elle sıra sıfırlansın mı?': 'मैनुअल क्रम रीसेट करें?',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      'सूची डिफ़ॉल्ट क्रम में लौट आएगी (सबसे हाल में चिह्नित पहले)।',
  'Sıra sıfırlanamadı': 'क्रम रीसेट नहीं हो सका',
  'Listenin en üstüne taşındı': 'सूची में सबसे ऊपर ले जाया गया',
  'Adlar yükleniyor…': 'नाम लोड हो रहे हैं…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      'पोस्टर को दबाकर रखें और खींचें। दूर मौजूद किसी टाइटल को आगे लाने के लिए “सबसे ऊपर ले जाएँ” का इस्तेमाल करें।',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      'खोज में खींचना बंद है; “सबसे ऊपर ले जाएँ” से आगे लाएँ ({} नतीजे)।',
  'Görünüm': 'दृश्य',
  'En çok izlediğin filmler': 'सबसे ज़्यादा देखी फ़िल्में',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      'समय अनुमानित हैं: एपिसोड ~{} मिनट, फ़िल्म ~{} मिनट माने गए हैं',
  'Bu kullanıcı adı sistem tarafından ayrılmış':
      'यह यूज़रनेम सिस्टम द्वारा सुरक्षित है',
  'Ekran süresi': 'स्क्रीन समय',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir":
      'समय TMDB से एपिसोड और फ़िल्मों की असली अवधियाँ हैं',
  'Tüm zamanlar: {} bölüm · {} film · {}':
      'अब तक: {} एपिसोड · {} फ़िल्में · {}',
  'Kabul et': 'स्वीकार करें',
  'Reddedilenler': 'अस्वीकृत',
  'İstekler': 'अनुरोध',
  'Reddettiğin istek yok': 'कोई अस्वीकृत अनुरोध नहीं',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      'अस्वीकृत अनुरोध यहाँ रहते हैं; चाहें तो फिर से स्वीकार कर सकते हैं।',
  'Ne izlesem?': 'क्या देखूँ?',
  'Karışık': 'मिश्रित',
  'Çarkı çevir': 'पहिया घुमाएँ',
  'Tekrar çevir': 'फिर घुमाएँ',
  'Bu türde içerik yok': 'इस प्रकार की कोई सामग्री नहीं',
  'Bütçe': 'बजट',
  'dizi.jpg AI özeti': 'dizi.jpg AI सारांश',
  'Daha fazlasını gör': 'और देखें',
  'Yıldız sistemi': 'स्टार सिस्टम',
  '{} yıldız üzerinden': '{} सितारों में से',
  'Önizleme': 'पूर्वावलोकन',
  'dokununca açılır': 'टैप करने पर खुलता है',
  'Bir azalt': 'एक कम करें',
  'Bir artır': 'एक बढ़ाएं',
  'Ölçek kaydedilemedi': 'स्केल सहेजा नहीं जा सका',
  'Ölçeği değiştirmek puanlarını silmez; aynı puanlar yeni ölçekte gösterilir.':
      'स्केल बदलने से आपकी रेटिंग नहीं मिटती; वही रेटिंग नए स्केल पर दिखती है।',
  'En aşağıya gönder': 'सबसे नीचे भेजें',
  'Listenin en altına taşındı': 'सूची के सबसे नीचे ले जाया गया',
  'Oturumun sonlandı': 'आपका सत्र समाप्त हो गया',
  'Bu hesabın oturumları kapatıldı ya da şifresi değişti. Devam etmek için tekrar giriş yap.':
      'इस खाते को सभी जगह से साइन आउट किया गया या पासवर्ड बदला गया। जारी रखने के लिए फिर से साइन इन करें।',
  'Son izleme: {}': 'आखिरी बार देखा: {}',
  '{} tarihinde izledin': '{} को देखा',
  'Geri bildirimine yanıt verdik': 'हमने आपके फ़ीडबैक का जवाब दिया',
  'Bu yanıt artık görüntülenemiyor.': 'यह जवाब अब नहीं दिखाया जा सकता।',
  'Gönderdiğin geri bildirim': 'आपका भेजा गया फ़ीडबैक',
  'Dizi veya film seç (zorunlu)': 'सीरीज़ या फ़िल्म चुनें (ज़रूरी)',
  'Bölüm seç (isteğe bağlı)': 'एपिसोड चुनें (वैकल्पिक)',
  '{}. sezon {}. bölüm': 'सीज़न {}, एपिसोड {}',
  'Ne düşünüyorsun?': 'आपका क्या ख़याल है?',
  '{}/{} yükleniyor': '{}/{} अपलोड हो रहा है',
  'Fotoğraf/video ekle': 'फ़ोटो या वीडियो जोड़ें',
  'Paylaşmak için önce bir dizi veya film seç.':
      'साझा करने के लिए पहले सीरीज़ या फ़िल्म चुनें।',
  'Sezon seç': 'सीज़न चुनें',
  '{}. sezon': 'सीज़न {}',
  'Bölüm seçme (yalnız dizi hakkında)':
      'कोई एपिसोड नहीं (केवल सीरीज़ के बारे में)',
  'Sezonlar yüklenemedi.': 'सीज़न लोड नहीं हो सके।',
  'Bu dizide bölüm bilgisi yok.': 'इस सीरीज़ के एपिसोड की जानकारी नहीं है।',
  'Bu sezonda bölüm yok.': 'इस सीज़न में कोई एपिसोड नहीं है।',
  '{}. bölüm': 'एपिसोड {}',
  'Dizi veya film ara...': 'सीरीज़ और फ़िल्में खोजें...',
  'İzlediğin dizi ve film hakkında yorum paylaş':
      'आपने जो देखा उस पर टिप्पणी साझा करें',
  'Yapım seç (zorunlu)': 'टाइटल चुनें (ज़रूरी)',
  'Paylaşmak için önce bir yapım seç.': 'साझा करने के लिए पहले टाइटल चुनें।',
  'Kişi': 'व्यक्ति',
  'Yapım firması': 'प्रोडक्शन कंपनी',
  'Yapım ara...': 'टाइटल खोजें...',
  'Çarkı çevirmek için sürükle veya dokun':
      'व्हील घुमाने के लिए खींचें या टैप करें',
  'Arşiv': 'संग्रह',
  'Yüklediklerim': 'मेरे अपलोड',
  'GIF ara...': 'GIF खोजें...',
  'GIF yükle': 'GIF अपलोड करें',
  'GIF etiketleri': 'GIF टैग',
  'Virgülle ayır. Aramada bu kelimelerle bulunur.':
      'अल्पविराम से अलग करें। इन्हीं शब्दों से यह मिलेगा।',
  'gülme, alkış, şaşkın': 'हँसी, तालियाँ, हैरानी',
  'Yükle': 'अपलोड करें',
  'Henüz GIF yok': 'अभी कोई GIF नहीं',
  'Bu aramaya uyan GIF yok': 'इस खोज से मेल खाता कोई GIF नहीं',
  'Arşiv yeni. İlk GIF i sen yükle — sen hemen kullanırsın, onaydan sonra herkes görür.':
      'संग्रह नया है। पहला GIF आप अपलोड करें — आप तुरंत इस्तेमाल कर सकते हैं, मंज़ूरी के बाद सब देखेंगे।',
  'GIF yüklendi. Sen hemen kullanabilirsin; herkese açık arşive onaydan sonra girer.':
      'GIF अपलोड हो गया। आप तुरंत इस्तेमाल कर सकते हैं; सार्वजनिक संग्रह में मंज़ूरी के बाद आएगा।',
  'Onay bekliyor': 'मंज़ूरी का इंतज़ार',
  'GIF listesi yüklenemedi': 'GIF सूची लोड नहीं हो सकी',
  'GIF yüklenemedi': 'GIF अपलोड नहीं हो सका',
  'Bu GIF i şikayet et': 'इस GIF की शिकायत करें',
  'Uygunsuz içerik yöneticiye bildirilir ve arşivden kaldırılabilir.':
      'अनुचित सामग्री की सूचना मॉडरेटर को दी जाती है और उसे संग्रह से हटाया जा सकता है।',
  'Şikayetin alındı': 'आपकी शिकायत मिल गई',
  'Şikayet gönderilemedi': 'शिकायत नहीं भेजी जा सकी',
  'Dizinin kendisi': 'सीरीज़ खुद',
  'Sezon ya da bölüm seçme': 'सीज़न या एपिसोड नहीं',
  'Tüm {}. sezon': 'पूरा सीज़न {}',
  'Bölüm seçme': 'एपिसोड नहीं',
  'En fazla {} yapım ekleyebilirsin.':
      'तुम ज़्यादा से ज़्यादा {} टाइटल जोड़ सकते हो।',
  'Bu zaten ekli.': 'पहले से जुड़ा है।',
  'Dizi, film, oyuncu ya da yönetmen etiketle — gönderin onların sayfasında da görünür.':
      'किसी सीरीज़, फ़िल्म, अभिनेता या निर्देशक को टैग करो — तुम्हारी पोस्ट उनके पेज पर भी दिखेगी।',
  'Etiket ekle': 'टैग जोड़ें',
  'Dizi, film, oyuncu ya da yönetmen etiketle':
      'सीरीज़, फ़िल्म, अभिनेता या निर्देशक को टैग करो',
  'Gönderiden vazgeç': 'पोस्ट रद्द करें',
  'Yazdıkların kaydedilmeyecek.': 'जो लिखा है वह सहेजा नहीं जाएगा।',
  'Yazmaya devam et': 'लिखते रहो',
  'Bulunamadı. Adın yazılışını değiştirip dene.':
      'नहीं मिला। दूसरी वर्तनी आज़माओ।',
  'Dizi, film, oyuncu, yönetmen ya da yapım firması ara.':
      'सीरीज़, फ़िल्म, अभिनेता, निर्देशक या प्रोडक्शन कंपनी खोजो।',
};
