/// Otomatik üretilen çeviri haritası (am).
const Map<String, String> cevirilerAm = {
  'Hepsini gördün, baştan gösteriyoruz': 'ሁሉንም አይተዋል፣ ከመጀመሪያው እናሳይዎታለን።',
  'Aktarılacak tanınan veri bulunamadı.': 'ለማስገባት የሚታወቅ ዳታ አልተገኘም።',
  'Arama': 'ፍለጋ',
  'Aramaya başla': 'መፈለግ ጀምር',
  'Son aramalar': 'የቅርብ ጊዜ ፍለጋዎች',
  'Ayarlar': 'ቅንብሮች',
  'Bağla': 'አገናኝ',
  'Bio': 'ባዮ',
  'Bitirdim': 'ጨርሻለሁ',
  'Bunları da Beğenebilirsin': 'እነዚህንም ልትወዳቸው ትችላለህ',
  'Bölüm': 'ክፍል',
  'Bıraktım': 'አቁሜዋለሁ',
  'Dil': 'ቋንቋ',
  'Dil ara...': 'ቋንቋ ፈልግ...',
  'Dizi': 'ተከታታይ ድራማ',
  'Dizi ve filmlerini takip et': 'ተከታታይ ድራማዎችህን እና ፊልሞችህን ተከታተል',
  'Dizi yorumu': 'የድራማ አስተያየት',
  'Dizi, film veya kişi ara...': 'ድራማ፣ ፊልም ወይም ሰው ፈልግ...',
  'Dosya en fazla 30MB olabilir': 'ፋይሉ ቢበዛ 30MB መሆን አለበት',
  'Dosya en fazla {}MB olabilir': 'ፋይሉ ቢበዛ {}MB መሆን አለበት',
  'E-posta': 'ኢሜይል',
  'E-posta veya kullanıcı adı': 'ኢሜይል ወይም የተጠቃሚ ስም',
  'En az 2 harf yaz': 'ቢያንስ 2 ፊደላት ጻፍ',
  'Film': 'ፊልም',
  'Film yorumu': 'የፊልም አስተያየት',
  'Fotoğraf / video ekle': 'ፎቶ / ቪዲዮ ጨምር',
  'Fotoğraf veya GIF — profil ve kapak resmi': 'ፎቶ ወይም GIF — የመገለጫ እና የሽፋን ምስል',
  'Giriş Yap': 'ግባ',
  'Gönder': 'ላክ',
  'Gönderildi': 'ተልኳል',
  'Haftanın Dizileri': 'የሳምንቱ ድራማዎች',
  'Haftanın Filmleri': 'የሳምንቱ ፊልሞች',
  'Henüz izleme kaydın yok': 'እስካሁን የእይታ መዝገብ የለህም',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'እስካሁን ዝርዝር የለህም — ከመገለጫ ትር ፍጠር።',
  'Henüz yorum yok.': 'እስካሁን አስተያየት የለም።',
  'Hesabın bağlandı!': 'መለያህ ተገናኝቷል!',
  'Hesabın yok mu? Kayıt ol': 'መለያ የለህም? ተመዝገብ',
  'Hesabını Bağla': 'መለያህን አገናኝ',
  'Hesap Oluştur': 'መለያ ፍጠር',
  'Kapak resmi ekle': 'የሽፋን ምስል ጨምር',
  'Kaydet': 'አስቀምጥ',
  'Kendinden bahset...': 'ስለ ራስህ ተናገር...',
  'Keşfet': 'አስስ',
  'Kimseyi takip etmiyor': 'ማንንም አይከተሉም',
  'Kişi ara': 'ሰው ፈልግ',
  'Kişi yorumu': 'የሰው አስተያየት',
  'Konuk Oyuncular': 'እንግዳ ተዋናዮች',
  'Kullanıcı adı (küçük harf)': 'የተጠቃሚ ስም (በትንንሽ ፊደላት)',
  'Kullanıcı adı ara...': 'የተጠቃሚ ስም ፈልግ...',
  'Liste adı': 'የዝርዝር ስም',
  'Listeye Ekle': 'ወደ ዝርዝር ጨምር',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'በእንግዳ መለያ ላይ ነህ — በኢሜይልህ አገናኘው፣ ዳታህን አታጣ!',
  'Misafir olarak devam et': 'እንደ እንግዳ ቀጥል',
  'Oluştur': 'ፍጠር',
  'Oyuncular': 'ተዋናዮች',
  'Profil': 'መገለጫ',
  'Profil kaydedildi': 'መገለጫ ተቀምጧል',
  'Puanla': 'ነጥብ ስጥ',
  'Puanı Sil': 'ነጥብ ሰርዝ',
  'Puanın': 'ነጥብህ',
  'Sezonlar': 'ምዕራፎች',
  'Sunucu hatası ({})': 'የአገልጋይ ስህተት ({})',
  'S{} · {}. Bölüm': 'ም{} · ክፍል {}',
  'S{}B{} yorumu': 'የም{}ክ{} አስተያየት',
  'Takibi Bırak': 'መከተል አቁም',
  'Takip': 'የሚከተላቸው',
  'Takip Edilenler': 'የሚከተላቸው',
  'Takip Et': 'ተከተል',
  'Takipçi': 'ተከታይ',
  'Takipçi yok': 'ተከታይ የለም',
  'Takipçiler': 'ተከታዮች',
  'Takvim': 'ቀን መቁጠሪያ',
  'Tamam': 'እሺ',
  'Tekrar Dene': 'እንደገና ሞክር',
  'Tekrar dene': 'እንደገና ሞክር',
  'Toplam İzleme Süresi': 'ጠቅላላ የእይታ ጊዜ',
  'Tüm Zamanların En İyileri': 'የሁሉም ጊዜ ምርጦች',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'ሁሉንም ዳታህን (እይታ፣ ነጥብ፣ አስተያየት፣ ዝርዝር) ከTV Time ጋር ተኳሃኝ በሆነ ZIP መልክ አውርድ ወይም ከሌላ መተግበሪያ የመጣ ZIP አስገባ።',
  'Tümünü Kaldır': 'ሁሉንም አስወግድ',
  'Tümünü İzledim': 'ሁሉንም አይቻለሁ',
  'Türk Dizileri': 'የቱርክ ድራማዎች',
  'Veri içe aktar (.zip)': 'ዳታ አስገባ (.zip)',
  'Verilerim': 'ዳታዬ',
  'Verilerimi dışa aktar (e-posta)': 'ዳታዬን አውጣ (ኢሜይል)',
  'Verilerini dışa aktar': 'ዳታህን አውጣ',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'የሚመጣ ክፍል የለም።\nከድራማው ዝርዝር ገጽ ወደ «እያየሁ ነው» ሁኔታ ቀይር፣ አዳዲስ ክፍሎችን እዚህ ተከታተል።',
  'Yapımları': 'ሥራዎቹ',
  'Yeni Diziler': 'አዳዲስ ድራማዎች',
  'Yeni Liste': 'አዲስ ዝርዝር',
  'Yeni kullanıcı adı (isteğe bağlı)': 'አዲስ የተጠቃሚ ስም (አማራጭ)',
  'Yorum': 'አስተያየት',
  'Yorumunu yaz...': 'አስተያየትህን ጻፍ...',
  'Zaten hesabın var mı? Giriş yap': 'መለያ አለህ? ግባ',
  'ort. {}': 'አማካይ {}',
  'takip': 'የሚከተላቸው',
  'takipçi': 'ተከታይ',
  '{} / {} bölüm': '{} / {} ክፍል',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} ወር',
  '{} ay~tekil': '{} ወር',
  '{} bölüm izlendi': '{} ክፍል ታይቷል',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} ደቂቃ',
  '{} dk~tekil': '{} ደቂቃ',
  '{} gün': '{} ቀን',
  '{} gün~tekil': '{} ቀን',
  '{} içerik': '{} ይዘት',
  '{} içerik · otomatik': '{} ይዘት · ራስ-ሰር',
  '{} kayıt atlandı (eşleşmedi).': '{} መዝገብ ተዘሏል (አልተዛመደም)።',
  '{} saat': '{} ሰዓት',
  '{} saat~tekil': '{} ሰዓት',
  '{} sezon': '{} ምዕራፍ',
  '{} yıl': '{} ዓመት',
  '{} yıl~tekil': '{} ዓመት',
  '{}. Bölüm': 'ክፍል {}',
  '{}. Sezon': 'ምዕራፍ {}',
  'Çıkış Yap': 'ውጣ',
  'Ülke': 'አገር',
  'Ülke ara...': 'አገር ፈልግ...',
  'Ülke seç': 'አገር ምረጥ',
  'İlk yorumu sen yaz!': 'የመጀመሪያውን አስተያየት አንተ ጻፍ!',
  'İncelemeler': 'ግምገማዎች',
  'İncelemen (isteğe bağlı)': 'ግምገማህ (አማራጭ)',
  'İptal': 'ይቅር',
  'İzlediklerim': 'ያየኋቸው',
  'İzledim': 'አይቻለሁ',
  'İzledin': 'አይተዋል',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'የእይታ ታሪክህ እና ዝርዝሮችህ ይጠበቃሉ፤ ከአሁን በኋላ ከየትኛውም መሣሪያ መግባት ትችላለህ።',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'የእይታ ታሪክህ፣ ነጥቦችህ፣ አስተያየቶችህ እና ዝርዝሮችህ በZIP መልክ ወደ ተመዘገበው ኢሜይል አድራሻህ ይላካሉ።',
  'İzleyeceğim': 'አያለሁ',
  'İzliyorum': 'እያየሁ ነው',
  'İçe aktarım tamamlandı': 'ማስገባት ተጠናቋል',
  'Şifre': 'የይለፍ ቃል',
  '• profil bilgisi': '• የመገለጫ መረጃ',
  '• {} dizi durumu': '• {} የድራማ ሁኔታ',
  '• {} izleme kaydı': '• {} የእይታ መዝገብ',
  '• {} liste': '• {} ዝርዝር',
  '• {} puan': '• {} ነጥብ',
  '• {} yorum': '• {} አስተያየት',
  '{}+ yapım': '{}+ ሥራዎች',
  'Yorumlar': 'አስተያየቶች',
  'Yorumlar ({})': 'አስተያየቶች ({})',
  'Yorumları ({})': 'አስተያየቶቹ ({})',
  'Listelerim': 'ዝርዝሮቼ',
  'Nereden izledin?': 'የት ተመለከቱት?',
  'Diziye git': 'ወደ ድራማው ሂድ',
  'TV / Kanal': 'ቲቪ / ቻናል',
  'Sinema': 'ሲኒማ',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'ሌላ',
  'Akış': 'ዥረት',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'ዥረትህ ባዶ ነው።\nበምትመለከታቸው ትዕይንቶች እና ፊልሞች ላይ አስተያየት ሲሰጡ እዚህ ይታያል።',
  'Listeleri ({})': 'ዝርዝሮቻቸው ({})',
  'Liste boş.': 'ይህ ዝርዝር ባዶ ነው።',
  'Yanıtla': 'መልስ',
  '@{} kullanıcısına yanıt veriyorsun': 'ለ@{} ምላሽ',
  'İzlediğim Diziler ({})': 'የተመለከትኳቸው ድራማዎች ({})',
  'İzlediğim Filmler ({})': 'የተመለከትኳቸው ፊልሞች ({})',
  'Tümünü gör': 'ሁሉንም እይ',
  'Bildirimler': 'ማሳወቂያዎች',
  'Henüz bildirim yok': 'እስካሁን ማሳወቂያ የለም',
  '@{} yorumuna yanıt verdi': '@{} ለአስተያየትዎ መለሱ',
  '@{} yorumunu beğendi': '@{} አስተያየትዎን ወደዱት',
  '@{} seni takip etti': '@{} ተከተሉዎት',
  '@{} sana mesaj gönderdi': '@{} መልእክት ላኩልዎ',
  'Mesajlar': 'መልእክቶች',
  'Mesaj': 'መልእክት',
  'Mesaja eklenecek': 'ወደ መልእክቱ ይታከላል',
  'Mesajını yaz...': 'መልእክት ጻፍ...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'እስካሁን ውይይት የለም።\nመገለጫ ከፍተህ መልእክት ላክ።',
  'Şifreni mi unuttun?': 'የይለፍ ቃል ረሱ?',
  'Şifreyi Sıfırla': 'የይለፍ ቃል ዳግም አስጀምር',
  'E-postadaki kod': 'ከኢሜይል የመጣ ኮድ',
  'Yeni şifre': 'አዲስ የይለፍ ቃል',
  'Sana Özel': 'ለአንተ',
  '{} özetin': 'የ{} ማጠቃለያህ',
  'Yıllık izleme istatistiklerin': 'ዓመታዊ የእይታ ስታቲስቲክስ',
  'Rozetler': 'ባጆች',
  'Verdiğin puan': 'የሰጠሃቸው ደረጃዎች',
  'Ortalama puanın': 'አማካይ ደረጃህ',
  'En çok izlediğin diziler': 'በብዛት የተመለከትካቸው ድራማዎች',
  'İlk Bölüm': 'የመጀመሪያ ክፍል',
  '100 Bölüm': '100 ክፍሎች',
  '1000 Bölüm': '1000 ክፍሎች',
  'İlk Film': 'የመጀመሪያ ፊልም',
  '50 Film': '50 ፊልሞች',
  'İlk Yorum': 'የመጀመሪያ አስተያየት',
  '25 Yorum': '25 አስተያየቶች',
  '10 Puan': '10 ደረጃዎች',
  'İlk Takipçi': 'የመጀመሪያ ተከታይ',
  '10 Dizi Bitirdin': '10 ድራማዎች ጨርሰዋል',
  'İzlemeyi Bıraktım': 'ማየት አቆምኩ',
  'İzlediği Diziler ({})': 'የተመለከታቸው ድራማዎች ({})',
  'İzlediği Filmler ({})': 'የተመለከታቸው ፊልሞች ({})',
  '500 Bölüm': '500 ክፍሎች',
  '5000 Bölüm': '5000 ክፍሎች',
  '10 Film': '10 ፊልሞች',
  '100 Film': '100 ፊልሞች',
  '100 Yorum': '100 አስተያየቶች',
  '50 Puan': '50 ደረጃዎች',
  '100 Puan': '100 ደረጃዎች',
  '10 Takipçi': '10 ተከታዮች',
  '50 Takipçi': '50 ተከታዮች',
  '25 Dizi Bitirdin': '25 ድራማዎች ጨርሰዋል',
  '50 Dizi Bitirdin': '50 ድራማዎች ጨርሰዋል',
  '10 Beğeni': '10 መውደዶች',
  '100 Beğeni': '100 መውደዶች',
  'yazıyor...': 'እየጻፉ ነው...',
  'ses kaydediyor...': 'ድምጽ እየቀረጸ ነው...',
  'Profil düzeni': 'የመገለጫ አቀማመጥ',
  'Konumla ve kırp': 'አስቀምጥ እና ቁረጥ',
  'Listeye eklendi': 'ወደ ዝርዝሩ ታክሏል',
  'Listeyi sil?': 'ዝርዝሩን ልሰርዝ?',
  'Sil': 'ሰርዝ',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'ይህ በጭራሽ እንዳልታየ ተቆጥሮ ከዝርዝሮችህ ይወገዳል።',
  'Gelecek bölüm bugün': 'ቀጣዩ ክፍል ዛሬ',
  'Gelecek bölüm {} gün sonra': 'ቀጣዩ ክፍል በ{} ቀናት',
  'Tema': 'ገጽታ',
  'Sistem': 'ስርዓት',
  'Koyu': 'ጨለማ',
  'Açık': 'ብርሃን',
  'İzleyenler': 'ተመልካቾች',
  'Yorumunu yaz... (@ ile etiketle)': 'አስተያየትህን ጻፍ... (@ ለመሰየም)',
  '@{} bir yorumda seni etiketledi': '@{} በአስተያየት ውስጥ ሰይመውዎታል',
  'Mesajı sil': 'መልእክት ሰርዝ',
  'Mesaj silinemedi': 'መልእክቱ ሊሰረዝ አልቻለም',
  'Bağlantı geçersiz veya sayfa bulunamadı': 'አገናኙ ልክ ያልሆነ ወይም ገጹ አልተገኘም',
  "Keşfet'e dön": 'ወደ አስስ ተመለስ',
  'Düzenle': 'አርትዕ',
  'Mesajı düzenle': 'መልእክት አርትዕ',
  'Yanıtlanıyor': 'በመመለስ ላይ',
  'düzenlendi': 'ተስተካክሏል',
  'Fotoğraf': 'ፎቶ',
  'Video': 'ቪዲዮ',
  'İçerik': 'ይዘት',
  'çevrimiçi': 'በመስመር ላይ',
  'son görülme {} dk önce': 'ከ{} ደቂቃ በፊት ታይቷል',
  'son görülme {} saat önce': 'ከ{} ሰዓት በፊት ታይቷል',
  'son görülme {} gün önce': 'ከ{} ቀን በፊት ታይቷል',
  'Yorumlar yüklenemedi': 'አስተያየቶችን መጫን አልተቻለም',
  'Favori': 'ተወዳጅ',
  'Listeye ekle': 'ወደ ዝርዝር አክል',
  'İçerik paylaş': 'ይዘት አጋራ',
  'Kapat': 'ዝጋ',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'እንዳየኸው ምልክት ያደረግከው ሁሉ እዚህ ይሰበሰባል።',
  'Henüz sohbetin yok': 'እስካሁን ውይይት የለም',
  'Bir profile girip mesaj gönderebilirsin.': 'መገለጫ ክፈት እና መልእክት ላክ።',
  'Listeyi sil': 'ዝርዝር ሰርዝ',
  'Puan kaydedilemedi': 'ደረጃ ማስቀመጥ አልተቻለም',
  'Nerede İzlenir': 'የት እንደሚታይ',
  'Abonelik': 'የደንበኝነት ምዝገባ',
  'Kirala': 'ተከራይ',
  'Satın al': 'ግዛ',
  'Devam et': 'ቀጥል',
  'Şikayet et': 'ሪፖርት አድርግ',
  'Engelle': 'አግድ',
  'Engeli kaldır': 'እገዳ አንሳ',
  'Kullanıcı engellendi': 'ተጠቃሚው ታግዷል',
  'Engel kaldırıldı': 'እገዳ ተነስቷል',
  'Şikayet sebebi': 'የሪፖርት ምክንያት',
  'Spam veya yanıltıcı': 'አይፈለጌ ወይም አሳሳች',
  'Taciz veya nefret söylemi': 'ትንኮሳ ወይም የጥላቻ ንግግር',
  'Uygunsuz / cinsel içerik': 'ተገቢ ያልሆነ / የፆታ ይዘት',
  'Şiddet veya tehlikeli içerik': 'ጥቃት ወይም አደገኛ ይዘት',
  'Telif hakkı ihlali': 'የቅጂ መብት ጥሰት',
  'Şikayetin alındı, teşekkürler': 'ሪፖርትህ ደርሷል፣ አመሰግናለሁ',
  'Hesabımı Sil': 'መለያዬን ሰርዝ',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'መለያህ እና ሁሉም ውሂብህ (ታሪክ፣ ደረጃዎች፣ አስተያየቶች፣ ዝርዝሮች፣ መልዕክቶች) በቋሚነት ይሰረዛል። ይህ መመለስ አይቻልም።',
  'Şifreni gir': 'የይለፍ ቃልህን አስገባ',
  'Hesabımı kalıcı sil': 'መለያዬን በቋሚነት ሰርዝ',
  'Sesli mesaj': 'የድምፅ መልእክት',
  'Ses gönderilemedi': 'የድምፅ መልእክት መላክ አልተቻለም',
  'Kaydediliyor…': 'በመቅዳት ላይ…',
  'Ses oynatılamadı': 'ድምፁን ማጫወት አልተቻለም',
  'Oynat': 'አጫውት',
  'Fragmanı oynat': 'ትሬለር አጫውት',
  'Altyazıyı aç': 'ንዑስ አርእስት አብራ',
  'Altyazıyı kapat': 'ንዑስ አርእስት አጥፋ',
  '10 saniye ileri': '10 ሰከንድ ወደ ፊት',
  '10 saniye geri': '10 ሰከንድ ወደ ኋላ',
  'Duraklat': 'ለአፍታ አቁም',
  'Liste görünümü': 'የዝርዝር እይታ',
  'Takvim görünümü': 'የቀን መቁጠሪያ እይታ',
  'Önceki ay': 'ቀዳሚ ወር',
  'Sonraki ay': 'ቀጣይ ወር',
  'Bu gün bölüm yok': 'በዚህ ቀን ክፍል የለም',
  'Gizlilik Politikası': 'የግላዊነት መመሪያ',
  'Son güncelleme: {}': 'መጨረሻ የተዘመነው፦ {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'ይህ መመሪያ የ dizi.jpg መተግበሪያንና dizijpg.com ድረ-ገጽን ስትጠቀም ምን ውሂብ እንደሚሰበሰብ፣ እንዴት እንደሚውል እና መብቶችህ ምን እንደሆኑ ያብራራል።',
  'Topladığımız Veriler': 'የምንሰበስበው ውሂብ',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'መለያ፦ የኢሜይል አድራሻ፣ የተጠቃሚ ስም እና የይለፍ ቃል። የይለፍ ቃላት ወደ ኋላ በማይመለስ ሃሽ መልክ ይቀመጣሉ፤ የእንግዳ መለያዎች ያለ ኢሜይል መጠቀም ይቻላል።',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'መገለጫ፦ አቫታር፣ የሽፋን ምስል፣ ባዮ እና አገር የመሳሰሉ አንተ መጨመር የመረጥካቸው መረጃዎች።',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'አጠቃቀም፦ የእይታ ታሪክህ፣ ደረጃዎችህ፣ አስተያየቶችህ፣ ዝርዝሮችህ፣ ምላሾችህ እና ተወዳጆችህ።',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'መልዕክቶች፦ የጽሑፍ፣ የምስል እና የድምፅ መልዕክቶችህ በእኛ አገልጋዮች ላይ ይቀመጣሉ። መልዕክቶች ከጫፍ እስከ ጫፍ አልተመሰጠሩም፤ ሪፖርት ከተደረጉ ብቻ ለቁጥጥር ዓላማ ይታያሉ።',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'የተጫነ ሚዲያ፦ ወደ መገለጫህ፣ አስተያየቶችህ እና መልዕክቶችህ የምትጨምራቸው ፎቶዎች፣ GIF፣ ቪዲዮዎች እና የድምፅ ቅጂዎች።',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'ቴክኒካዊ፦ የ IP አድራሻ፣ ግምታዊ አካባቢ (በአገር/ከተማ ደረጃ)፣ የመሣሪያ መድረክ፣ የመተግበሪያ ስሪት እና የስህተት መዝገቦች። እነዚህ ለደህንነትና ችግር ለማስተካከል ይቀመጣሉ።',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'የአጠቃቀም ስታቲስቲክስ፦ በየትኛው የመሣሪያ ዓይነት፣ ኦፐሬቲንግ ሲስተምና አሳሽ እንደተገባ በጥቅል ምድቦች ተከፍሎ ወደ ዕለታዊ ጠቅላላ ቆጣሪዎች ይታከላል፤ የአሳሹ መለያ ራሱ አይቀመጥም፣ እነዚህም ቁጥሮች ከግለሰቦች ጋር ሊገናኙ አይችሉም።',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'ማሳወቂያዎች፦ ለግፊት ማሳወቂያዎች የመሣሪያህን ቶክን እና የቋንቋ ምርጫህን እናስቀምጣለን። ማሳወቂያዎችን በመሣሪያህ ቅንብሮች በማንኛውም ጊዜ ማጥፋት ትችላለህ።',
  'Verileri Nasıl Kullanırız': 'ውሂብህን እንዴት እንጠቀማለን',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'ውሂብህን አገልግሎቱን ለመስጠት፣ መለያህን ለመጠበቅ፣ ማሳወቂያ ለመላክ፣ ስህተቶችን ለማስተካከል እና አላግባብ መጠቀምን ለመከላከል ብቻ እንጠቀማለን። ውሂብህን አንሸጥም፤ ለማስታወቂያ ዓላማ ከማንም ጋር አናጋራም።',
  'Çerezler ve Yerel Depolama': 'ኩኪዎች እና አካባቢያዊ ማከማቻ',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'አካባቢያዊ ማከማቻን የምንጠቀመው አንተን ገብተህ እንድትቆይ እና እንደ ቋንቋና ገጽታ ያሉ ምርጫዎችህን ለማስታወስ ብቻ ነው። የማስታወቂያ ወይም የመከታተያ ኩኪ የለም።',
  'Üçüncü Taraf Hizmetler': 'የሶስተኛ ወገን አገልግሎቶች',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'የተከታታይ ድራማዎችና ፊልሞች ውሂብ ከ TMDB፣ የዥረት መድረኮች መረጃ ከ JustWatch ይመጣል። የግፊት ማሳወቂያዎች በ Google Firebase በኩል ይደርሳሉ፤ የድረ-ገጹን ትራፊክ Cloudflare ይጠብቃል። እነዚህ አገልግሎቶች የራሳቸው የግላዊነት መመሪያዎች አሏቸው።',
  'Saklama ve Silme': 'ማቆየትና መሰረዝ',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'ውሂብህ መለያህ እስካለ ድረስ ይቆያል። በቅንብሮች ውስጥ ባለው "መለያዬን ሰርዝ" መለያህን ለዘለቄታው መሰረዝ ትችላለህ፤ ውሂብህ ወዲያውኑ፣ በመጠባበቂያዎች ውስጥ ያሉ ቅጂዎች ደግሞ ቢበዛ በ14 ቀናት ውስጥ ይሰረዛሉ። የስህተት መዝገቦች ከ30 ቀናት በኋላ በራስ-ሰር ይሰረዛሉ።',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'ውሂብህን ከቅንብሮች እንደ ZIP ማውጣት ትችላለህ፤ ማህደሩ ወደ ኢሜይል አድራሻህ ይላካል።',
  'Güvenlik': 'ደህንነት',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'ውሂብ በተመሰጠሩ ግንኙነቶች (HTTPS) ይተላለፋል፤ የተገደበ መዳረሻ ባላቸው አገልጋዮች ላይ ይቀመጣል።',
  'Çocukların Gizliliği': 'የልጆች ግላዊነት',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg ከ13 ዓመት በታች ለሆኑ ልጆች አይደለም።',
  'Hakların': 'መብቶችህ',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'በ KVKK እና GDPR መሠረት ውሂብህን የማግኘት፣ የማስተካከል፣ የመሰረዝ እና የማዛወር መብት አለህ። ለእነዚህ ጉዳዮች ጻፍልን፦ {}',
  'Değişiklikler': 'ለውጦች',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'ይህ መመሪያ ከተለወጠ አዲሱ ስሪት በዚህ ገጽ ላይ ይታተማል፤ ቀኑም ይዘመናል።',
  'Kayıt olarak {} kabul etmiş olursun.': 'በመመዝገብ {}ን ትቀበላለህ።',
  'Kullanıcılar': 'ተጠቃሚዎች',
  'Fotoğrafı değiştir': 'ፎቶ ቀይር',
  'Yeniden konumlandır': 'እንደገና አስተካክል',
  'Bir şeyler ters gitti': 'የሆነ ስህተት ተፈጥሯል',
  'Sosyal Bağlantılar': 'የማህበራዊ አገናኞች',
  'Profilinde en fazla 3 bağlantı gösterilir.': 'በመገለጫህ ላይ እስከ 3 አገናኞች ይታያሉ።',
  'Platform seç': 'መድረክ ምረጥ',
  'Kullanıcı adın': 'የተጠቃሚ ስምህ',
  'Ekle': 'ጨምር',
  'Kaldır': 'አስወግድ',
  'Kopyalandı: {}': 'ተቀድቷል፦ {}',
  'Geçersiz kullanıcı adı': 'ልክ ያልሆነ የተጠቃሚ ስም',
  'Bağlantı ekle': 'አገናኝ ጨምር',
  'Spoiler olabilir — dokun ve gör': 'ስፖይለር ሊኖረው ይችላል — ለማየት ንካ',
  'Beğeni': 'መውደዶች',
  'beğeni': 'መውደዶች',
  'Beğen': 'ወደድኩት',
  'Görüntülenme': 'እይታዎች',
  'görüntülenme': 'እይታዎች',
  'Tam ekran': 'ሙሉ ማያ',
  'Arama başarısız': 'ፍለጋ አልተሳካም',
  'Sonuç bulunamadı': 'ውጤት አልተገኘም',
  'Dizi ve Filmler': 'ተከታታዮች እና ፊልሞች',
  'Kişiler': 'ሰዎች',
  'Ana Sayfa': 'መነሻ',
  'Paylaş': 'አጋራ',
  'Yanıtlar': 'ምላሾች',
  'Yaklaşan Bölümler': 'የሚመጡ ክፍሎች',
  'Yetişme Listesi': 'የመድረሻ ዝርዝር',
  'Şunu mu demek istedin': 'ማለትዎ ነው',
  'Spoiler': 'ስፖይለር',
  'Spoiler — dokun ve gör': 'ስፖይለር — ለማየት ንካ',
  'uyum': 'መጣጣም',
  'Uyum': 'መጣጣም',
  '{} ortak dizi': '{} የጋራ ተከታታዮች',
  '{} ortak film': '{} የጋራ ፊልሞች',
  'Bildirim Tercihleri': 'የማሳወቂያ ምርጫዎች',
  'Beğeniler': 'ውዶች',
  'Yeni takipçiler': 'አዲስ ተከታዮች',
  'Etiketlenmeler': 'መጥቀሶች',
  'Yeniden izledim': 'እንደገና ታይቷል',
  '{}. kez izlendi': '{} ጊዜ ታይቷል',
  'Gönderi bulunamadı': 'ልጥፍ አልተገኘም',
  'Gözat': 'አስስ',
  'Diziler': 'ተከታታዮች',
  'Filmler': 'ፊልሞች',
  'Tümü': 'ሁሉም',
  'Farklı bir tür seç.': 'ሌላ ዘውግ ሞክር።',
  'Gizlilik': 'ግላዊነት',
  'İzlediklerimi gizle': 'የተመለከትኩትን ደብቅ',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'የተመለከቷቸው ተከታታዮች እና ፊልሞች በመገለጫዎ ላይ አይታዩም',
  'Yorumlarımı gizle': 'አስተያየቶቼን ደብቅ',
  'Profilinde yorumların görünmez': 'አስተያየቶችህ በመገለጫህ ላይ አይታዩም',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'አንድ ተከታታይ ወይም ፊልም በገጹ ላይ ባለው «በመገለጫዬ ደብቅ» ቺፕ መደበቅ ትችላለህ።',
  'Geri Bildirim': 'ግብረመልስ',
  'Uygulama hakkında görüş ve önerini yaz...':
      'ስለ መተግበሪያው አስተያየትህን እና ጥቆማህን ጻፍ...',
  'Teşekkürler! Geri bildirimin alındı.': 'እናመሰግናለን! ግብረመልስህ ደርሷል።',
  'Profilimde gizle': 'በመገለጫዬ ደብቅ',
  'Yorumları': 'አስተያየቶቹ',
  'Bu kullanıcı henüz bir şey izlememiş.': 'ይህ ተጠቃሚ እስካሁን ምንም አልተመለከተም።',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'ይህ ተጠቃሚ አስተያየቶቻቸውን በሚስጥር መያዝ ይመርጣሉ።',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'ውሂብ: JustWatch',
  'Web Sitesi': 'ድር ጣቢያ',
  'Diğer uygulamalar': 'ሌሎች መተግበሪያዎች',
  'Bağlantıyı kopyala': 'ማገናኛ ቅዳ',
  'Henüz kimseyi takip etmiyorsun.': 'ገና ማንንም አልተከተልክም።',
  'Çevir': 'ተርጉም',
  'Çeviri şu an yapılamadı': 'ትርጉም አሁን አልተቻለም',
  'Bağlantı açılamadı': 'አገናኙን መክፈት አልተቻለም',
  'Orijinali göster': 'ዋናውን አሳይ',
  'Çeviriyi göster': 'ትርጉሙን አሳይ',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'በዚህ ወር የስርጭት ቀኑ የተገለጸ ክፍል የለም። ቀኖቹ አብዛኛውን ጊዜ ከጥቂት ሳምንታት በፊት ይገለጻሉ፤ ከዚያ እዚህ ይታያሉ።',
  'devamı': 'ተጨማሪ',
  'Google ile devam et': 'በGoogle ይቀጥሉ',
  'Google girişi başarısız': 'በGoogle መግባት አልተሳካም',
  'Veri tasarrufu': 'የውሂብ ቁጠባ',
  'Wi-Fi ağında veri tasarrufu': 'በWi-Fi ላይ የውሂብ ቁጠባ',
  'Mobil veride veri tasarrufu': 'በሞባይል ውሂብ ላይ የውሂብ ቁጠባ',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'ሲበራ ፎቶዎች አስቀድመው አይወርዱም፤ የምታየው ምስል ብቻ ይጫናል።',
  'Çocuk güvenliği': 'የልጆች ደህንነት',
  'Türk Filmleri': 'የቱርክ ፊልሞች',
  'En Yüksek Puanlı Filmler': 'ከፍተኛ ደረጃ ያላቸው ፊልሞች',
  'En Yüksek Puanlı Diziler': 'ከፍተኛ ደረጃ ያላቸው ተከታታዮች',
  'En Çok İzlenen Filmler': 'በብዛት የታዩ ፊልሞች',
  'Popüler Diziler': 'ታዋቂ ተከታታዮች',
  'En Çok Kazanan Filmler': 'ከፍተኛ ገቢ ያስገቡ ፊልሞች',
  'Kült Filmler': 'ተወዳጅ ልዩ ፊልሞች',
  'Yeni Filmler': 'አዲስ ፊልሞች',
  'Yorum yap': 'አስተያየት ስጡ',
  'Henüz yorum yok': 'እስካሁን አስተያየት የለም',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'ለተከታታዮችና ለፊልሞች የጻፍካቸው አስተያየቶች እዚህ ይሰበሰባሉ።',
  'GIF ekle': 'GIF አክል',
  'İlk yorumu sen yaz': 'መጀመሪያውን አስተያየት አንተ ጻፍ',
  'Video altyazıları': 'የቪዲዮ የትርጉም ጽሑፎች',
  'Videolarda altyazı göster': 'በቪዲዮዎች ላይ የትርጉም ጽሑፎችን አሳይ',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'በቪዲዮው ላይ የተነገረው ዓረፍተ ነገር በስክሪኑ ላይ ተጽፏል. ጽሑፉ ትርጉም ነው፡ እንግሊዝኛ በቱርክ ንግግር፣ ቱርክኛ በሌሎች ቋንቋዎች።',
  'Güncelleme gerekli': 'ማዘመን ያስፈልጋል',
  'Yeni sürüm var': 'አዲስ ስሪት አለ',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'ለመቀጠል የdizi.jpg አዲሱን ስሪት ይጫኑ።',
  'Güncelle': 'አዘምን',
  'Daha sonra': 'በኋላ',
  'Takvim güncelleniyor': 'የቀን መቁጠሪያ በመዘመን ላይ',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'የቀን መቁጠሪያውን ማዘመን አልተቻለም፣ የድሮው ዝርዝር እየታየ ነው',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'አንዳንድ ተከታታዮች አልተጫኑም፣ ዝርዝሩ ያልተሟላ ሊሆን ይችላል',
  'Yenile': 'አድስ',
  'Devam etmek için giriş yap': 'ለመቀጠል ይግቡ',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'ደረጃ ለመስጠት፣ አስተያየት ለመጻፍ እና ቤተ መጻሕፍትዎን ለመገንባት ነፃ መለያ በቂ ነው።',
  'Şimdi değil': 'አሁን አይደለም',
  'Yorum yazmak için giriş yap': 'አስተያየት ለመጻፍ ይግቡ',
  'Kişilere göndermek için giriş yap': 'ለሰዎች ለመላክ ይግቡ',
  'Beğenenler': 'የወደዱት',
  'Henüz beğeni yok': 'እስካሁን ምንም ውዴታ የለም',
  'Bu gönderiyi ilk beğenen sen ol': 'ይህን ልጥፍ በመጀመሪያ የወደደ ይሁኑ',
  'Bu gönderiye yanıt': 'ለዚህ ልጥፍ ምላሽ',
  'Spoiler içeren gönderi': 'ስፖይለር ያለበት ልጥፍ',
  'Görsel gönderi': 'የፎቶ ልጥፍ',
  'Bu yorumu profilimde gizle': 'ይህን አስተያየት በመገለጫዬ ላይ ደብቅ',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'አስተያየቱ በተከታታይና በፊልም ገጽ ላይ ይቆያል',
  'Bu yorumu sil': 'ይህን አስተያየት ሰርዝ',
  'Yorum profilinde gizlendi': 'አስተያየቱ በመገለጫህ ላይ ተደብቋል',
  'Geri al': 'ቀልብስ',
  'Yorum silinsin mi?': 'አስተያየቱ ይሰረዝ?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'ይህ አስተያየት በሁሉም ቦታ ላይ በቋሚነት ይሰረዛል። መመለስ አይቻልም።',
  'Yorum silindi': 'አስተያየቱ ተሰርዟል',
  'Yorum profilinde tekrar görünüyor': 'አስተያየቱ በመገለጫህ ላይ እንደገና ይታያል',
  'Gizlenen yorumun yok': 'የተደበቀ አስተያየት የለህም',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'በመገለጫህ የአስተያየቶች ትር ውስጥ ልጥፍን ተጭነህ በመያዝ የደበቅሃቸው አስተያየቶች እዚህ ይሰበሰባሉ።',
  'Gizlenen yorumlar': 'የተደበቁ አስተያየቶች',
  'Gönderiye git': 'ወደ ልጥፉ ሂድ',
  'Tekrar göster': 'እንደገና አሳይ',
  'Yanıtlarımı gizle': 'መልሶቼን ደብቅ',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'በሌሎች ልጥፎች ላይ የጻፍካቸው መልሶች ለአንተ ብቻ ይታያሉ',
  'Profilinde gizlediğin yorumları tekrar göster':
      'በመገለጫዎ ላይ የደበቋቸውን አስተያየቶች እንደገና ያሳዩ',
  'Sıralama': 'ቅደም ተከተል',
  'Önerilen': 'የሚመከር',
  'Kronolojik': 'በጊዜ ቅደም ተከተል',
  'Gelen mesaj istekleri': 'የገቡ የመልእክት ጥያቄዎች',
  'Mesaj isteğin yok': 'የመልእክት ጥያቄ የለም',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'የማትከታተላቸው ሰዎች መልእክቶች እዚህ ይታያሉ።',
  'Çevrimiçi durumumu gizle': 'የመስመር ላይ ሁኔታዬን ደብቅ',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'ሌሎች በመልእክቶች ውስጥ የመስመር ላይ ሁኔታህንና መጨረሻ የታየህበትን ጊዜ አያዩም',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'ከመጀመሪያዎቹ ተጠቃሚዎቻችን አንዱ። አስተያየቶቻቸው መተግበሪያው ዛሬ ያለበት ደረጃ እንዲደርስ ረድተዋል።',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'ከመጀመሪያዎቹ ተጠቃሚዎቻችን አንዱ ነዎት። አስተያየቶችዎ መተግበሪያው ዛሬ ያለበት ደረጃ እንዲደርስ ረድተዋል።',
  'İleri': 'ቀጣይ',
  'Önceki': 'ቀዳሚ',
  'Sonraki': 'ቀጣይ',
  'Seçilen dosya okunamadı': 'የተመረጠው ፋይል ማንበብ አልተቻለም',
  'Video açılamadı': 'ቪዲዮውን መክፈት አልተቻለም',
  'En fazla {} medya seçebilirsin': 'ቢበዛ {} ሚዲያ መምረጥ ይችላሉ',
  'Hiçbir medya yüklenemedi': 'ምንም ሚዲያ አልተጫነም',
  'Seçimi kaldır': 'ምርጫን አስወግድ',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'በአንድ አስተያየት በአጠቃላይ {} ሜባ መጫን ይችላሉ',
  '{} dosya okunamadı': '{} ፋይሎች ማንበብ አልተቻለም',
  '{} medya eklendi, {} yüklenemedi': '{} ሚዲያ ተጨመረ፣ {} አልተሳካም',
  'Kırp': 'ቁረጥ',
  'Çiz': 'ሳል',
  'Metin': 'ጽሑፍ',
  'Emoji': 'ኢሞጂ',
  'Yinele': 'እንደገና',
  'Daha fazla': 'ተጨማሪ',
  'Hazırlanıyor…': 'በመዘጋጀት ላይ…',
  'Düzenlemeden çık?': 'አርትዖትን ልቀቅ?',
  'Yaptığın değişiklikler kaybolacak.': 'ያደረግካቸው ለውጦች ይጠፋሉ።',
  'Çık': 'ውጣ',
  'Serbest çizim': 'ነጻ ስዕል',
  'Ok': 'ቀስት',
  'Dikdörtgen': 'አራት ማዕዘን',
  'Daire': 'ክብ',
  'Bulanıklaştır': 'አደብዝዝ',
  'Pikselleştir': 'ፒክሰል አድርግ',
  'Silgi': 'ማጥፊያ',
  'Çizgi kalınlığı': 'የመስመር ውፍረት',
  'Saydamlık': 'ግልጽነት',
  'Dolgu': 'ሙላ',
  'Renk': 'ቀለም',
  'Döndür': 'አሽከርክር',
  'Yansıt': 'ገልብጥ',
  'Oran': 'ጥምርታ',
  'Sıfırla': 'ዳግም አስጀምር',
  'Serbest': 'ነጻ',
  'Metin yaz...': 'ጽሑፍ ጻፍ...',
  'Hizala': 'አሰላልፍ',
  'Arka plan': 'ዳራ',
  'Emoji ara...': 'ኢሞጂ ፈልግ...',
  'Son kullanılanlar': 'በቅርብ ጊዜ የተጠቀሙ',
  'İfadeler ve insanlar': 'ፈገግታዎች እና ሰዎች',
  'Hayvanlar ve doğa': 'እንስሳት እና ተፈጥሮ',
  'Yiyecek ve içecek': 'ምግብ እና መጠጥ',
  'Etkinlikler': 'እንቅስቃሴዎች',
  'Seyahat ve yerler': 'ጉዞ እና ቦታዎች',
  'Nesneler': 'ዕቃዎች',
  'Semboller': 'ምልክቶች',
  'Bayraklar': 'ባንዲራዎች',
  'Görseli düzenle': 'ምስሉን አርትዕ',
  'Düzenlendi': 'ተስተካክሏል',
  'Düzenlenemedi': 'ማስተካከል አልተቻለም',
  'Düzenlenen görsel çok büyük': 'የተስተካከለው ምስል በጣም ትልቅ ነው',
  'Videoyu düzenle': 'ቪዲዮ አርትዕ',
  'Sesi kapat': 'ድምፅ አጥፋ',
  'Sesi aç': 'ድምፅ አብራ',
  'İptal ediliyor…': 'በመሰረዝ ላይ…',
  'Bu biraz sürebilir': 'ይህ ትንሽ ጊዜ ሊወስድ ይችላል',
  'Video çok büyük': 'ቪዲዮው በጣም ትልቅ ነው',
  'Video hazırlanamadı': 'ቪዲዮውን ማዘጋጀት አልተቻለም',
  'Başlangıç': 'ጅምር',
  'Bitiş': 'መጨረሻ',
  'En çok {} saniye seçebilirsin': 'ቢበዛ {} ሰከንድ መምረጥ ትችላለህ',
  'Dosya en fazla {} MB olabilir': 'ፋይሉ ቢበዛ {} MB ሊሆን ይችላል',
  'Medya ekle': 'ሚዲያ አክል',
  'Seçili medya kalmadı': 'የተመረጠ ሚዲያ የለም',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'ወደ አስተያየትህ ለመጨመር ፎቶ ወይም ቪዲዮ ምረጥ።',
  'Medya seç': 'ሚዲያ ምረጥ',
  'Daha fazla ekle': 'ተጨማሪ አክል',
  'Medya seçilemedi': 'ሚዲያ መምረጥ አልተቻለም',
  'Favori oyuncular': 'ተወዳጅ ተዋናዮች',
  'Henüz favori oyuncun yok': 'ገና ተወዳጅ ተዋናይ የለም',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'የተዋናይ ገጽ ክፈት እና በላይ በቀኝ ያለውን ልብ ንካ።',
  '{} yapımdan {} tanesini izledin': 'ከ{} {} ተመልክተዋል',
  'izledin': 'ተመልክተዋል',
  'İzlemedin': 'አልተመለከቱም',
  'Yapım bulunamadı': 'ምንም አልተገኘም',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'ይህ ሰው የሚዘረዘር ተከታታይ ወይም ፊልም የለውም።',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'የእርስዎ የመመልከቻ ታሪክ ከመለያዎ ጋር የተያያዘ ነው፤ ይህ ዝርዝር የእርስዎ ብቻ ነው።',
  'Hesabın kalıcı olarak askıya alındı': 'መለያዎ በቋሚነት ታግዷል',
  'Hesabın geçici olarak askıya alındı': 'መለያዎ ለጊዜው ታግዷል',
  'Hesabın askıya alındı': 'መለያዎ ታግዷል',
  'Sebep': 'ምክንያት',
  'Kalan süre': 'የቀረው ጊዜ',
  'Süre dolunca hesabın kendiliğinden açılır': 'ጊዜው ሲያልቅ መለያዎ በራሱ ይከፈታል',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'በዚህ ጊዜ ማንበብ ይችላሉ፣ ነገር ግን መለጠፍ፣ አስተያየት መስጠት ወይም መልእክት መላክ አይችሉም።',
  'Anladım': 'ገባኝ',
  'Ayrıntı': 'ዝርዝር',
  '{} dakika': '{} ደቂቃ',
  'birkaç saniye': 'ጥቂት ሰከንድ',
  'Karara itiraz et': 'በዚህ ውሳኔ ላይ ይግባኝ ይበሉ',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'ይህ ቅጣት ለምን መነሳት እንዳለበት ያብራሩ',
  'İtirazını gönder': 'ይግባኝዎን ይላኩ',
  'İtirazın incelemede': 'ይግባኝዎ በምርመራ ላይ ነው',
  'İtirazın reddedildi': 'ይግባኝዎ ውድቅ ተደርጓል',
  'İtirazın alındı, inceleniyor': 'ይግባኝዎ ደርሷል፣ በምርመራ ላይ ነው',
  'İtiraz en az 10 karakter olmalı': 'ይግባኝ ቢያንስ 10 ቁምፊ መሆን አለበት',
  'Yükleniyor...': 'በመጫን ላይ...',
  'Bu bölüme puan ver': 'ይህን ክፍል ደረጃ ይስጡ',
  '{} kişi puanladı': '{} ሰዎች ደረጃ ሰጥተዋል',
  'Bölüm izlendi olarak işaretlendi': 'ክፍሉ እንደታየ ተመልክቷል',
  'Sesli ara': 'የድምፅ ጥሪ',
  'Görüntülü ara': 'የቪዲዮ ጥሪ',
  'Çalıyor...': 'እየደወለ ነው...',
  'Bağlanıyor...': 'እየተገናኘ ነው...',
  'Cevapla': 'መልስ',
  'Reddet': 'አትቀበል',
  'Sessize al': 'ድምፅ አጥፋ',
  'Hoparlör': 'ስፒከር',
  'Kamerayı kapat': 'ካሜራ አጥፋ',
  'Kamerayı çevir': 'ካሜራ ቀይር',
  'Cevap yok': 'መልስ የለም',
  'Arama reddedildi': 'ጥሪው ተከልክሏል',
  'Meşgul': 'ተይዟል',
  'Bağlanılamadı': 'መገናኘት አልተቻለም',
  'Arama iptal edildi': 'ጥሪው ተሰርዟል',
  'Arama geçmişi': 'የጥሪ ታሪክ',
  'Gelen arama': 'ገቢ ጥሪ',
  'Giden arama': 'ወጪ ጥሪ',
  'Cevapsız arama': 'ያመለጠ ጥሪ',
  'Arama şu anda kullanılamıyor': 'ጥሪ አሁን አይገኝም',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'የቪዲዮ ጥሪ አሁን ጠፍቷል፤ የድምፅ ጥሪ ማድረግ ትችላለህ',
  'Bu kullanıcıyı arayamazsın': 'ይህን ተጠቃሚ መደወል አትችልም',
  'Aramak için karşılıklı takipleşmelisiniz': 'ለመደዋወል እርስ በርስ መከታተል አለባችሁ',
  'Bu kullanıcı şu anda aranamıyor': 'ይህ ተጠቃሚ አሁን ሊደወልለት አይችልም',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'በጣም ብዙ ያመለጡ ጥሪዎች። ከ{} በኋላ እንደገና ሞክር',
  'Zaten bir aramadasın': 'አስቀድመህ በጥሪ ላይ ነህ',
  'Arama için mikrofon izni gerekiyor': 'ለመደወል የማይክሮፎን ፈቃድ ያስፈልጋል',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'ለቪዲዮ ጥሪ የካሜራና የማይክሮፎን ፈቃድ ያስፈልጋል',
  'Arama başlatılamadı': 'ጥሪውን መጀመር አልተቻለም',
  'Kullanıcı bulunamadı': 'ተጠቃሚ አልተገኘም',
  'Kendini arayamazsın': 'ራስህን መደወል አትችልም',
  'Arama artık geçerli değil': 'ይህ ጥሪ ከእንግዲህ ተቀባይነት የለውም',
  'Bu aramanın tarafı değilsin': 'የዚህ ጥሪ አካል አይደለህም',
  'Arama bulunamadı': 'ጥሪ አልተገኘም',
  'Çok fazla istek, biraz bekle': 'በጣም ብዙ ጥያቄዎች፤ ትንሽ ጠብቅ',
  'Bağlantı koptu': 'ግንኙነቱ ተቋርጧል',
  'Arama süre sınırına ulaştı': 'ጥሪው የጊዜ ገደቡ ላይ ደርሷል',
  'Arama en fazla 4 saat sürebilir': 'አንድ ጥሪ ቢበዛ 4 ሰዓት ሊቆይ ይችላል',
  'Arama sona erdi': 'ጥሪው ተጠናቋል',
  'Sesli arama': 'የድምፅ ጥሪ',
  'Görüntülü arama': 'የቪዲዮ ጥሪ',
  'Gelen aramalar': 'ገቢ ጥሪዎች',
  'Sesli ve görüntülü arama bildirimleri': 'የድምፅና የቪዲዮ ጥሪ ማሳወቂያዎች',
  '{} sa': '{} ሰዓ',
  'Sesli ve Görüntülü Aramalar': 'የድምፅና የቪዲዮ ጥሪዎች',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'የጥሪ ይዘት ፈጽሞ አይቀዳም። ድምፅና ቪዲዮ በመሣሪያዎች መካከል ከጫፍ እስከ ጫፍ ተመስጥሮ (DTLS-SRTP) ይተላለፋሉ፤ አገልጋዮቻችን ይህን ትራፊክ መፍታት፣ ማዳመጥ ወይም ማከማቸት አይችሉም።',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'የሚቀመጠው የጥሪ ሜታዳታ ብቻ ነው፦ ከማን ጋር፣ በየትኛው አቅጣጫ፣ መቼና ለምን ያህል ጊዜ። እነዚህ መዝገቦች ከ90 ቀናት በኋላ በራስ-ሰር ይሰረዛሉ።',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'ቀጥተኛ ግንኙነት ካልተቻለ ድምፅና ቪዲዮ ተመስጥረው በማስተላለፊያ አገልጋይ (TURN) ያልፋሉ። ማስተላለፊያው ደግሞ ይዘቱን መፍታት ወይም መቅዳት አይችልም።',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'ማይክሮፎን የሚሠራው በድምፅ ወይም በቪዲዮ ጥሪ ወቅት ብቻ ሲሆን ካሜራ ደግሞ በቪዲዮ ጥሪ ወቅት ብቻ ነው። ጥሪው ሲያልቅ ሁለቱም ይጠፋሉ።',
  'Takip ettiğin {} kişi izledi': 'የሚከታተሏቸው {} ሰዎች ተመልክተውታል',
  'Yorum yaz...': 'አስተያየት ጻፍ...',
  'Sıradaki bölüm': 'ቀጣዩ ክፍል',
  'Doğrulanmış testçi': 'የተረጋገጠ ሞካሪ',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'የመከተል፣ የመውደድ፣ የመልስ፣ የመልእክት እና የመለያ ማሳወቂያዎች',
  'Sen': 'እርስዎ',
  'Aradığınız kişide sesli arama devre dışı': 'ለዚህ ሰው የድምፅ ጥሪ ተሰናክሏል',
  'Aradığınız kişide görüntülü arama devre dışı': 'ለዚህ ሰው የቪዲዮ ጥሪ ተሰናክሏል',
  'Sesli aramalara izin ver': 'የድምፅ ጥሪዎችን ፍቀድ',
  'Görüntülü aramalara izin ver': 'የቪዲዮ ጥሪዎችን ፍቀድ',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'ሲጠፋ ማንም በድምፅ ሊደውልልህ አይችልም፤ ደዋዩ ማሳወቂያ ያያል',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'ሲጠፋ ማንም በቪዲዮ ሊደውልልህ አይችልም፤ ደዋዩ ማሳወቂያ ያያል',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'የድምፅ ጥሪ ጠፍቷል። ከቅንብሮች > ግላዊነት ማብራት ትችላለህ።',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'የቪዲዮ ጥሪ ጠፍቷል። ከቅንብሮች > ግላዊነት ማብራት ትችላለህ።',
  'Sesli ve görüntülü arama': 'የድምፅ እና ቪዲዮ ጥሪ',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'የእንግዳ መለያዎች ጥሪ ማድረግ አይችሉም። መለያ ከፈጠርክ መጠቀም ትችላለህ።',
  'Misafir hesaplar aranamaz': 'የእንግዳ መለያዎች ሊጠሩ አይችሉም',
  'Puan dağılımı': 'የደረጃ ስርጭት',
  '{} yıldız': '{} ኮከብ',
  'Yakında gelecek': 'በቅርቡ ይመጣል',
  '{} {} yayınlandı': '{} {} ወጥቷል',
  'Yeni bölüm yayınlandı': 'አዲስ ክፍል ወጥቷል',
  'Yeni bölümler': 'አዲስ ክፍሎች',
  'Geri': 'ወደኋላ',
  'Karşılamayı kapat': 'መግቢያውን ይዝጉ',
  'Adım {} / {}': 'እርምጃ {} / {}',
  'Hadi başlayalım': 'እንጀምር',
  'Kaydet ve devam': 'ያስቀምጡና ይቀጥሉ',
  '{} tanesini ekle': 'የተመረጡትን {} ይጨምሩ',
  'Şimdilik geç': 'ለአሁኑ ይዝለሉ',
  'Doğum tarihin ne zaman?': 'የልደት ቀንዎ መቼ ነው?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'ከዕድሜዎ ጋር የሚስማማ ይዘት ለማሳየት እና ልደትዎን ለማክበር ነው የምንጠይቀው።',
  'Gün': 'ቀን',
  'Ay': 'ወር',
  'Yıl': 'ዓመት',
  'Doğum yılımı paylaşmak istemiyorum': 'የልደት ዓመቴን ማጋራት አልፈልግም',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'የልደት ቀንዎ በመገለጫዎ ላይ ለሁሉም አይታይም። ከዕድሜ ጋር ለሚስማማ ይዘት እና ለልደት መልካም ምኞት ብቻ ይውላል።',
  'Ocak': 'ጃንዋሪ',
  'Şubat': 'ፌብሩዋሪ',
  'Mart': 'ማርች',
  'Nisan': 'ኤፕሪል',
  'Mayıs': 'ሜይ',
  'Haziran': 'ጁን',
  'Temmuz': 'ጁላይ',
  'Ağustos': 'ኦገስት',
  'Eylül': 'ሴፕቴምበር',
  'Ekim': 'ኦክቶበር',
  'Kasım': 'ኖቬምበር',
  'Aralık': 'ዲሴምበር',
  'Verilerini yanında getir': 'ዳታዎን ይዘው ይምጡ',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'በሌላ መተግበሪያ ውስጥ ያዩዋቸውን የሚከታተሉ ከሆነ ወደዚህ ማዛወር ይችላሉ። ከባዶ መጀመር አያስፈልግዎትም።',
  'TV Time, Trakt ve Letterboxd': 'TV Time፣ Trakt እና Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'ወደ ውጭ የላኩትን የZIP ፋይል ይምረጡ፤ ያዩዋቸው፣ ነጥቦችዎ እና ዝርዝሮችዎ ይዛወራሉ።',
  'Aktarılıyor...': 'በማዛወር ላይ...',
  'ZIP dosyası seç': 'የZIP ፋይል ይምረጡ',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'መቸኮል አያስፈልግም፦ ይህን በኋላም ከቅንብሮች > ዳታዬ ማድረግ ይችላሉ።',
  'Hangi filmleri izledin?': 'የትኞቹን ፊልሞች አይተዋል?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'በብዛት የታዩት እዚህ አሉ። የነኩዋቸውን ወደ ያዩዋቸው እንጨምር።',
  'SERİ FİLMLER': 'ተከታታይ ፊልሞች',
  'Serilerden {} film eklendi': 'ከስብስቦች {} ፊልም ታክሏል',
  'Film listesi yüklenemedi': 'የፊልም ዝርዝር መጫን አልተቻለም',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'ይህን እርምጃ መዝለል ይችላሉ፤ በኋላ የፈለጉትን መጨመር ይችላሉ።',
  '{} film izlediklerine eklendi': '{} ፊልም ወደ ያዩዋቸው ታክሏል',
  'Film serileri': 'የፊልም ስብስቦች',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'አንድን ስብስብ ከመጀመሪያ እስከ መጨረሻ ካዩ በአንድ ንክኪ ይጨምሩት።',
  'Seri bulunamadı': 'ስብስብ አልተገኘም',
  'Daha sonra tekrar deneyebilirsin.': 'በኋላ እንደገና መሞከር ይችላሉ።',
  '{} film': '{} ፊልም',
  'Eklendi': 'ታክሏል',
  'Tümünü izledim': 'ሁሉንም አይቻለሁ',
  'Peki ya diziler?': 'ተከታታይ ድራማዎችስ?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'ያዩዋቸውን ምልክት ያድርጉ፤ በመረጡ ቁጥር ተመሳሳይ የሆኑትን እናቀርብልዎታለን።',
  'Dizi listesi yüklenemedi': 'የተከታታይ ድራማ ዝርዝር መጫን አልተቻለም',
  'Seçtiklerine benzeyenler': 'ከመረጡት ጋር ተመሳሳይ የሆኑ',
  'Her şey hazır': 'ሁሉም ነገር ዝግጁ ነው',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'በdizi.jpg ላይ ምን ማድረግ እንደሚችሉ በፍጥነት ይመልከቱ።',
  'Profilini tamamla': 'መገለጫዎን ያሟሉ',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'ከቅንብሮች ውስጥ ባዮ፣ የመገለጫ ፎቶ እና ሽፋን መጨመር ይችላሉ።',
  'Takvimin seni bekliyor': 'ቀን መቁጠሪያዎ እየጠበቀዎት ነው',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'የሚያዩዋቸው ተከታታይ ድራማዎች አዲስ ክፍሎች ወደ ቀን መቁጠሪያው ይገባሉ፤ በማሳወቂያም እናሳውቅዎታለን።',
  'Puan ver, yorum yaz': 'ደረጃ ይስጡ፣ አስተያየት ይጻፉ',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'ክፍል በክፍል ደረጃ ይስጡ፣ በስፖይለር መጋረጃ አስተያየት ይጻፉ፣ ዝርዝሮችን ይፍጠሩ።',
  'Verilerin sende kalır': 'ዳታዎ የእርስዎ ሆኖ ይቀራል',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'ዳታዎ ከመለያዎ ጋር ብቻ ተያይዞ ይቀመጣል፤ አይሸጥም። ከቅንብሮች ሁሉንም ማውረድ ወይም መለያዎን ሙሉ በሙሉ መሰረዝ ይችላሉ።',
  'Engellenen kullanıcılar': 'የታገዱ ተጠቃሚዎች',
  'Engellediğin kişileri gör, engeli kaldır': 'ያገዱዋቸውን ሰዎች ይመልከቱ፣ እገዳ ያንሱ',
  'Engellediğin kimse yok': 'ያገዱት ማንም የለም',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'አንድን ተጠቃሚ በመገለጫው ላይ ካለው የሦስት ነጥብ ምናሌ ማገድ ይችላሉ።',
  '@{} engellensin mi?': '@{} ይታገድ?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'የእርስ በርስ ልጥፎችን፣ አስተያየቶችን እና መገለጫን ማየት አትችሉም፤ መልእክትም ሆነ ጥሪ አይደርስም። ካለ የመከታተል ትስስራችሁ ይቋረጣል፤ እገዳውን ቢያነሱም ተመልሶ አይመጣም።',
  'Bu kullanıcıyı engelledin': 'ይህን ተጠቃሚ አግደዋል',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'የዚህን ሰው ልጥፎች፣ አስተያየቶች እና መልእክቶች አያዩም፤ ይህ ሰውም የእርስዎን ማየት አይችልም።',
  '{} yeni bir yapımda: {}': '{} በአዲስ ሥራ ላይ፦ {}',
  'Favori kişinden yeni yapım': 'ከተወዳጅ ሰውዎ አዲስ ሥራ',
  '{} için bildirimler': 'ለ{} ማሳወቂያዎች',
  'Tüm bildirimler': 'ሁሉም ማሳወቂያዎች',
  'Uygulamada ve telefonda': 'በመተግበሪያውና በስልክ',
  'Yalnız uygulama içi': 'በመተግበሪያ ውስጥ ብቻ',
  'Telefon bildirimi gönderilmez': 'የስልክ ማሳወቂያ አይላክም',
  'Kapalı': 'ጠፍቷል',
  'Bu kişi için bildirim yok': 'ለዚህ ሰው ማሳወቂያ የለም',
  'Favori kişilerin yeni yapımları': 'የተወዳጅ ሰዎች አዲስ ሥራዎች',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'ሲጠፋ ማንም በድምፅ ሊደውልልዎ አይችልም፤ ደዋዩ "ተሰናክሏል" የሚል ማሳወቂያ ያያል',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'ሲጠፋ ማንም በቪዲዮ ሊደውልልዎ አይችልም፤ ደዋዩ "ተሰናክሏል" የሚል ማሳወቂያ ያያል',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'የእኔ እንቅስቃሴ',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'ውዴታዎች፣ አስተያየቶችና እይታዎች በአንድ ቦታ',
  'Henüz hareketin yok': 'እስካሁን እንቅስቃሴ የለም',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'የተወደዱ፣ አስተያየት የተሰጠባቸውና የታዩ ሁሉ እዚህ ይሰበሰባሉ።',
  'Bu süzgeçte hareket yok': 'በዚህ ማጣሪያ ውስጥ እንቅስቃሴ የለም',
  'Başka bir tür seç ya da "Hepsi"ne dön.': 'ሌላ ዓይነት ይምረጡ ወይም ወደ «ሁሉም» ይመለሱ።',
  'Hepsi': 'ሁሉም',
  'Puan': 'ደረጃ',
  'Tepki': 'ምላሽ',
  'İzleme': 'እይታ',
  'Durum': 'ሁኔታ',
  'Liste': 'ዝርዝር',
  'Yorum yaptın': 'አስተያየት ተሰጥቷል',
  'Yorumu beğendin': 'አስተያየት ተወዷል',
  '{} puan verdin': '{} ነጥብ ተሰጥቷል',
  'Tepki verdin': 'ምላሽ ተሰጥቷል',
  'Listene ekledin': 'ወደ ዝርዝር ተጨምሯል',
  'Takip etmeye başladın': 'መከታተል ተጀምሯል',
  '"İzleyeceğim" işaretledin': '«አያለሁ» ተብሎ ተመልክቷል',
  '"İzliyorum" işaretledin': '«እያየሁ ነው» ተብሎ ተመልክቷል',
  '"Bitirdim" işaretledin': '«ጨርሻለሁ» ተብሎ ተመልክቷል',
  '"Bıraktım" işaretledin': '«አቁሜዋለሁ» ተብሎ ተመልክቷል',
  'Silinmiş içerik': 'የተሰረዘ ይዘት',
  'şimdi': 'አሁን',
  '{} g': '{} ቀን',
  '{} y': '{} ዓመ',
  'İstatistiklerim': 'የእኔ ስታቲስቲክስ',
  'Gönderilerinin görüntülenmesi ve beğenisi': 'የልጥፎች እይታዎችና ውዴታዎች',
  'Henüz gönderin yok': 'እስካሁን ልጥፍ የለም',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'በተከታታይ ድራማ ወይም ፊልም ላይ አስተያየት ሲጻፍ የእይታና የውዴታ ቁጥሮች እዚህ መከማቸት ይጀምራሉ።',
  'Tüm zamanlar': 'ሁሉም ጊዜ',
  'Son {} gün': 'ያለፉት {} ቀናት',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'የእይታ ታሪክ ገና መከማቸት አልጀመረም፤ የመጀመሪያው ቀን መረጃ ነገ ይታያል።',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'የእይታ ታሪክ ከ{} ጀምሮ እየተከማቸ ነው ({} ቀን መረጃ አለ)፤ ስለዚህ የ{} ቀን ቁጥር ገና ያልተሟላ ነው።',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.': 'የውዴታ ታሪክ ከ{} ጀምሮ ተመዝግቧል።',
  'Bu dönemde gösterilecek gönderi yok.': 'በዚህ ወቅት የሚታይ ልጥፍ የለም።',
  'eksik veri': 'ያልተሟላ መረጃ',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'በመገለጫው ላይ የታዩ ተከታታዮችና ፊልሞች፣ የእይታ ቆጣሪዎች፣ የስክሪን ጊዜና የተዛማጅነት ካርድ ለሌሎች አይታዩም',
  'Takipçi listemi gizle': 'የተከታዮቼን ዝርዝር ደብቅ',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'ማን እንደሚከታተል ሌሎች ማየት አይችሉም፤ የተከታዮች ቁጥር ግን መታየቱን ይቀጥላል',
  'Takip ettiklerimi gizle': 'የምከታተላቸውን ደብቅ',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'ማንን እንደሚከታተል ሌሎች ማየት አይችሉም፤ የክትትል ቁጥር ግን መታየቱን ይቀጥላል',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'ይህ ተጠቃሚ ተከታዮቻቸውን በሚስጥር መያዝ ይመርጣሉ።',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'ይህ ተጠቃሚ የሚከታተሏቸውን በሚስጥር መያዝ ይመርጣሉ።',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'የልጥፍ ስታቲስቲክስ',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'የራስህን ልጥፎች ስታቲስቲክስ ብቻ ማየት ትችላለህ።',
  'Erişim': 'ተደራሽነት',
  'Görüntüleyen': 'ተመልካቾች',
  'Kaç farklı kişi gördü (son {} gün)': 'ስንት የተለያዩ ሰዎች አዩት (ያለፉት {} ቀናት)',
  'Paylaşım': 'ማጋራቶች',
  'Bu gönderiden sonra': 'ከዚህ ልጥፍ በኋላ',
  'Profil ziyareti': 'የመገለጫ ጉብኝቶች',
  'Yeni takip': 'አዲስ ክትትሎች',
  'İçeriğe tıklama': 'የይዘት ንክኪዎች',
  'Spoiler perdesini açan': 'ስፖይለሩን የከፈቱ',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'ማጋራቶች፣ የመገለጫ ጉብኝቶች፣ ክትትሎች፣ የይዘት ንክኪዎች፣ የምንጭ ክፍፍልና የስፖይለር መለኪያዎች ከ{} ጀምሮ እየተከማቹ ናቸው፤ ከዚያ በፊት ያለው አልተለካም።',
  'Zamana yayılmış görüntülenme': 'በጊዜ ሂደት እይታዎች',
  'Görüntülenme nereden geldi': 'እይታዎቹ ከየት መጡ',
  'Kimler gördü': 'ማን አየው',
  'Günlük veri henüz birikmeye başlamadı.': 'የዕለት መረጃ ገና መከማቸት አልጀመረም።',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'ገበታው ቢያንስ የሁለት ቀን መረጃ ይፈልጋል። መረጃው ከ{} ጀምሮ እየተከማቸ ነው።',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'በጣም ብዙ እይታዎች ከተለጠፈ በኋላ በ{}ኛው ቀን መጡ፦ {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'የዕለት እይታዎች ከ{} ጀምሮ እየተከማቹ ናቸው፤ ከዚያ በፊት ያለው አልተለካም።',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'የምንጭ ክፍፍል መለካት አሁን ነው የጀመረው፤ ይህ ልጥፍ እስካሁን ምልክት የተደረገበት እይታ አላገኘም።',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'የተከታይ/ማሰስ ክፍፍል መለካት አሁን ነው የጀመረው፤ እስካሁን መረጃ የለም።',
  'Takip edenler': 'ተከታዮች',
  'Keşiften gelenler': 'ከማሰስ',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'የተከታታይ/ፊልም ገጽ',
  'Paylaşılan bağlantı': 'የተጋራ አገናኝ',
  'yeni ölçülüyor': 'አዲስ ልኬት',
  'Kendi ortalamanla aynı düzeyde': 'ከራስህ አማካይ ጋር እኩል',
  'Kendi ortalamanın %{} üstünde': 'ከራስህ አማካይ በ{}% ከፍ ያለ',
  'Kendi ortalamanın %{} altında': 'ከራስህ አማካይ በ{}% ያነሰ',
  'Etkileşim oranı': 'የተሳትፎ መጠን',
  '(beğeni + yorum) ÷ görüntülenme': '(ወዳጆች + አስተያየቶች) ÷ እይታዎች',
  'Toplam görüntülenme': 'ጠቅላላ እይታዎች',
  '{} ile {} arasında toplam {} görüntülenme': 'ከ{} እስከ {} ጠቅላላ {} እይታዎች',
  'İstatistikleri gör': 'ስታቲስቲክስ ይመልከቱ',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'ለልጥፉ ባለቤት ለሚታየው ስታቲስቲክስ እንደ ጥቅል ቆጣሪዎች ይቀመጣል፦ ልጥፉ ስንት ጊዜና ከየትኛው ገጽታ (ምግብ፣ መገለጫ፣ ሙሉ ስክሪን ምግብ፣ የተከታታይ/ፊልም ገጽ፣ የተጋራ አገናኝ) እንደታየ፣ ተመልካቹ በዚያ ወቅት የልጥፉን ባለቤት ይከታተል እንደነበር፣ ከልጥፉ ወደ መገለጫ/ይዘት መሸጋገር፣ በልጥፉ በኩል የተፈጠረ ክትትል፣ ማጋራትና የስፖይለር መጋረጃ መከፈት። በእነዚህ ቆጣሪዎች ውስጥ የተጠቃሚ መታወቂያ፣ የIP አድራሻ ወይም የጊዜ ማህተም የለም፤ ማን ምን እንዳደረገ መጠየቅ አይቻልም።',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'አንድ ልጥፍ ስንት የተለያዩ ሰዎች እንዳዩት መቁጠር እንዲቻል፣ ለእያንዳንዱ ተመልካች የማይመለስ በቁልፍ የተሰራ አጭር ማጠቃለያ (ከተጠቃሚ መታወቂያ ወይም ከIP አድራሻ የተገኘ የምስጠራ ማሳጠሪያ) ለ90 ቀናት ይቀመጣል። ለልጥፉ ባለቤት ቁጥሩ ብቻ ይታያል፤ የተመልካቾች ማንነት በምንም ሁኔታ አይጋራም።',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'ወደ «አያለሁ» ይዛወር?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'አንድ ይዘት ወይ ይታያል ወይ ታይቷል። ከቀጠሉ በዚህ ተከታታይ ድራማ ላይ ያሉ {} የእይታ ምልክቶች ይሰረዛሉ።',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'አንድ ይዘት ወይ ይታያል ወይ ታይቷል። ከቀጠሉ በዚህ ፊልም ላይ ያለው «አይቻለሁ» ምልክት ይነሳል።',
  'Sil ve taşı': 'ሰርዞ ማዛወር',

  // --- Yapım ekibi / firma + seviye unvanları + doğum günü ---
  'Yapım Ekibi': 'የፕሮዳክሽን ቡድን',
  'Yaratıcı': 'ፈጣሪ',
  'Yönetmen': 'ዳይሬክተር',
  'Senaryo': 'ስክሪፕት',
  'Yapımcı': 'ፕሮዲውሰር',
  'Yapım Firmaları': 'የፕሮዳክሽን ኩባንያዎች',
  'Yapım Firması': 'የፕሮዳክሽን ኩባንያ',
  'Firma bulunamadı': 'ኩባንያው አልተገኘም',
  'Bu firmanın bu türde listelenecek yapımı yok.': 'ይህ ኩባንያ በዚህ ዓይነት ሥራ የለውም።',
  'Doğum günün kutlu olsun!': 'መልካም ልደት!',
  'İyi ki doğdun, iyi ki buradasın.': 'መወለድዎ ደስታ ነው፣ ከእኛ ጋር መሆንዎም እንዲሁ።',
  'Bugün {} yaşına girdin': 'ዛሬ {} ዓመት ሞላዎት',
  'Teşekkürler': 'አመሰግናለሁ',
  'İki Adımlı Doğrulama': 'የሁለት ደረጃ ማረጋገጫ',
  'Girişte e-postana kod gönderilir': 'ሲገቡ ወደ ኢሜይልዎ ኮድ ይላካል',
  'Kod {} adresine gönderildi': 'ኮድ ወደ {} ተልኳል',
  '6 haneli kod': 'የ6 አኃዝ ኮድ',
  'Doğrula': 'አረጋግጡ',
  'Yeniden gönder': 'እንደገና ላኩ',
  'Vazgeç': 'ይቅር',
  'Yeni kod gönderildi': 'አዲስ ኮድ ተልኳል',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'በGoogle ሲገቡ ኮድ አይጠየቅም፤ Google የራሱን ማረጋገጫ ያከናውናል።',
  'Kapatmak için de kod gerekir.': 'ማጥፋትም ኮድ ይጠይቃል።',
  'E-postana erişemezsen hesabına giremezsin.':
      'ኢሜይልዎን ማግኘት ካልቻሉ ወደ መለያዎ መግባት አይችሉም።',
  'İki adımlı doğrulama açıldı': 'የሁለት ደረጃ ማረጋገጫ ነቅቷል',
  'İki adımlı doğrulama kapatıldı': 'የሁለት ደረጃ ማረጋገጫ ጠፍቷል',
  'Videonun ne kadarı izlendi': 'ቪዲዮው ምን ያህል ታይቷል',
  'Videoyu başlatanlar': 'ቪዲዮውን የጀመሩ',
  'videonun %{} noktasına ulaştı': 'የቪዲዮውን {}% ደርሰዋል',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'ግማሽ ተመልካቾች ቢያንስ የቪዲዮውን {}% አይተዋል።',
  'Sonuna kadar izleyen: %{}': 'እስከ መጨረሻ የተመለከቱ፦ {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'ለመስመሩ ቢያንስ {} እይታ ያስፈልጋል፤ አሁን {} እይታ አለ።',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'መስመሩ ከ{} እይታ የተሠራ ሲሆን በተመረጠው ጊዜ አይለወጥም።',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'የመመልከቻ ጊዜ ከ{} ጀምሮ ይለካል፤ ከዚያ በፊት ያሉ እይታዎች አይካተቱም።',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} እይታ። {}% ግማሹ ላይ፣ {}% መጨረሻው ላይ ደርሰዋል።',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'ደረጃ {}',
  'Sonraki seviyeye {} puan kaldı': 'ወደ ቀጣዩ ደረጃ {} ነጥብ ቀርቷል',
  'Gönderilerin': 'ልጥፎችዎ',
  '{} gönderi': '{} ልጥፍ',
  '{} gönderi · {} görüntülenme': '{} ልጥፍ · {} እይታ',
  'önceki {} güne göre': 'ካለፉት {} ቀናት አንጻር',
  'önceki {} güne göre %{} arttı': 'ካለፉት {} ቀናት አንጻር በ{}% ጨምሯል',
  'önceki {} güne göre %{} azaldı': 'ካለፉት {} ቀናት አንጻር በ{}% ቀንሷል',
  'önceki {} güne göre değişmedi': 'ካለፉት {} ቀናት አንጻር አልተለወጠም',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'ዕለታዊ እይታ፦ ዝቅተኛ {}፣ ከፍተኛ {}',
  'Etkileşim oranı henüz ölçülemedi': 'የተሳትፎ መጠን ገና አልተለካም',
  'Oranlar': 'መጠኖች',
  'Beğenme oranı': 'የመውደድ መጠን',
  'Yorum oranı': 'የአስተያየት መጠን',
  'Paylaşma oranı': 'የማጋራት መጠን',
  'İçeriğe gitme oranı': 'የይዘት ንክኪ መጠን',
  'Profile gitme oranı': 'የመገለጫ ጉብኝት መጠን',
  'Ziyaretten takibe dönüşüm': 'ከጉብኝት ወደ ክትትል',
  'beğeni ÷ görüntülenme': 'መውደዶች ÷ እይታዎች',
  'yorum ÷ görüntülenme': 'አስተያየቶች ÷ እይታዎች',
  'paylaşım ÷ görüntülenme': 'ማጋራቶች ÷ እይታዎች',
  'içeriğe tıklama ÷ görüntülenme': 'የይዘት ንክኪዎች ÷ እይታዎች',
  'profil ziyareti ÷ görüntülenme': 'የመገለጫ ጉብኝቶች ÷ እይታዎች',
  'yeni takip ÷ profil ziyareti': 'አዲስ ክትትሎች ÷ የመገለጫ ጉብኝቶች',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'ለመጠኖቹ ቢያንስ {} እይታ ያስፈልጋል፤ አሁን {} አለ።',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'መጠኖቹ የልጥፉ የዕድሜ ልክ ቁጥሮች ላይ ተመሥርተዋል፤ ከታች ያለው የቀን ምርጫ አይለውጣቸውም።',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'እነዚህ ቁጥሮች የልጥፉ የዕድሜ ልክ ድምር ናቸው (የራሳቸው ማስታወሻ ያላቸው ሳጥኖች ሳይጨመሩ)፤ ከታች ያለው የቀን ምርጫ ግራፉን ብቻ ይለውጣል።',
  'Ortalama izlenme: videonun %{} kadarı': 'አማካይ እይታ፦ የቪዲዮው {}%',
  'Elde tutma eğrisinin 20 kovasının ortalaması.': 'የመስመሩ 20 ክፍሎች አማካይ።',
  'Dizi, film, kişi veya şirket ara...': 'ድራማ፣ ፊልም፣ ሰው ወይም ኩባንያ ፈልግ...',
  'Şirketler': 'ኩባንያዎች',
  'Senarist': 'ስክሪፕት ጸሃፊ',
  'Bölüm puanları': 'የክፍል ነጥቦች',
  'S{}': 'ም{}',
  'E{}': 'ክ{}',
  'Bölüm puanları yüklenemedi': 'የክፍል ነጥቦችን መጫን አልተቻለም',
  'Giriş gerekli': 'መግባት ያስፈልጋል',
  'Geçersiz oturum': 'ልክ ያልሆነ ክፍለ ጊዜ',
  'Oturum sonlandı, tekrar giriş yap': 'ክፍለ ጊዜው አለቀ፣ እንደገና ግባ',
  'Çok fazla istek; biraz sonra tekrar dene':
      'በጣም ብዙ ጥያቄዎች፤ ትንሽ ቆይተህ እንደገና ሞክር',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'አሁን በአገልጋዩ ላይ ቦታ የለም፣ ከጥቂት ጊዜ በኋላ እንደገና ይሞክሩ',
  'Devam eden yapımlar ({})': 'በመካሄድ ላይ ያሉ ስራዎች ({})',
  'Diziler ({})': 'ተከታታዮች ({})',
  'Filmler ({})': 'ፊልሞች ({})',
  'Tüm yapımlar': 'ሁሉም ስራዎች',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'የሚዲያ ማከማቻዎ ሞልቷል፤ ቦታ ለማግኘት አሮጌ ስቀላዎችን ይሰርዙ',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'ኢሜይል/የተጠቃሚ ስም ወይም የይለፍ ቃል ስህተት ነው',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'ይህ ኢሜይል ወይም የተጠቃሚ ስም አስቀድሞ ተይዟል',
  'Google doğrulaması başarısız': 'የ Google ማረጋገጫ አልተሳካም',
  'Kod geçersiz veya süresi dolmuş': 'ኮዱ ልክ አይደለም ወይም ጊዜው አልፏል',
  'Bu kullanıcıyla mesajlaşamazsın': 'ለዚህ ተጠቃሚ መልእክት መላክ አትችልም',
  'Kendini takip edemezsin': 'ራስህን መከተል አትችልም',
  'Bu kullanıcıyı takip edemezsin': 'ይህን ተጠቃሚ መከተል አትችልም',
  'Kendini engelleyemezsin': 'ራስህን ማገድ አትችልም',
  'Yorum 1-1000 karakter olmalı': 'አስተያየቱ 1–1000 ፊደል መሆን አለበት',
  'Boş mesaj gönderilemez': 'ባዶ መልእክት መላክ አይቻልም',
  'Yorum bulunamadı': 'አስተያየት አልተገኘም',
  'Şifre hatalı': 'የይለፍ ቃል ስህተት ነው',
  'Şifre en az 6 karakter olmalı': 'የይለፍ ቃል ቢያንስ 6 ፊደል መሆን አለበት',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'GIF፣ PNG፣ JPEG ወይም WebP ብቻ መጫን ይቻላል',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'የሚደገፉ ዓይነቶች፦ GIF፣ PNG፣ JPEG፣ WebP፣ MP4፣ WebM፣ ድምፅ',
  'Geçerli bir ZIP dosyası değil': 'ትክክለኛ የ ZIP ፋይል አይደለም',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'ውሂብ በኢሜይል ለመቀበል መጀመሪያ ኢሜይል አያይዝ',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'የመመልከት ምልክት አለ። «እመለከታለሁ» ለማለት መጀመሪያ ምልክቶቹን አጥፋ።',
  'Arama şu anda kapalı': 'ጥሪ አሁን ጠፍቷል',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'የእንግዳ መለያ ጥሪ ማብራት አይችልም፤ መለያ ፍጠር',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'ሰርቨሩ እንደገና እየጀመረ ነው፤ ትንሽ ቆይተህ ሞክር',
  'Puan 1-10 arası olmalı': 'ውጤቱ ከ 1 እስከ 10 መሆን አለበት',
  'En fazla 10 medya eklenebilir': 'ቢበዛ 10 ሚዲያ መጨመር ይቻላል',
  'Bu cihazdan yeni hesap açılamıyor': 'ከዚህ መሣሪያ አዲስ መለያ መክፈት አይቻልም',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'ትክክለኛ ኢሜይል፣ የተጠቃሚ ስም እና ቢያንስ 6 ፊደል የይለፍ ቃል ያስፈልጋል',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'ትክክለኛ ኢሜይል እና ቢያንስ 6 ፊደል የይለፍ ቃል ያስፈልጋል',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'የተጠቃሚ ስም 3–20፤ ትንሽ ፊደል፣ ቁጥር፣ ነጥብ፣ ጭረት፣ የታች መስመር (ጫፍ ላይ አይሁን)',
  'Bu hesap zaten bağlı': 'ይህ መለያ አስቀድሞ ተገናኝቷል',
  'Hesap oluşturulamadı': 'መለያ መፍጠር አልተቻለም',
  'Misafir hesabı oluşturulamadı': 'የእንግዳ መለያ መፍጠር አልተቻለም',
  'Hesap bulunamadı': 'መለያ አልተገኘም',
  'Bu hesapta e-posta yok': 'ይህ መለያ ኢሜይል የለውም',
  'İki adımlı doğrulama zaten bu durumda': 'ባለ ሁለት ደረጃ ማረጋገጫ አስቀድሞ በዚህ ሁኔታ ነው',
  'Kod yanlış': 'ኮዱ ስህተት ነው',
  'Kodun süresi doldu': 'የኮዱ ጊዜ አልቋል',
  'Kullanıcının e-postası yok (misafir hesap)': 'ይህ ተጠቃሚ ኢሜይል የለውም (የእንግዳ መለያ)',
  'Bio en fazla 300 karakter olabilir': 'ባዮ ቢበዛ 300 ፊደል',
  'Geçersiz ülke': 'ልክ ያልሆነ አገር',
  'Geçersiz sosyal bağlantı': 'ልክ ያልሆነ ማህበራዊ አገናኝ',
  'Geçersiz doğum tarihi': 'ልክ ያልሆነ የልደት ቀን',
  'Liste adı gerekli': 'የዝርዝር ስም ያስፈልጋል',
  'Ad en fazla 60, açıklama 300 karakter olabilir': 'ስም ቢበዛ 60፣ መግለጫ 300 ፊደል',
  'Liste bulunamadı': 'ዝርዝር አልተገኘም',
  'Değiştirilecek tercih yok': 'የሚዘመን ነገር የለም',
  'İnceleme en fazla 2000 karakter olabilir': 'ግምገማ ቢበዛ 2000 ፊደል',
  'Önce içeriği "bitirdim" olarak işaretle': 'መጀመሪያ እንደ ተጠናቀቀ ምልክት አድርግ',
  'Önce kişiyi favorile': 'መጀመሪያ ሰውዬውን ተወዳጅ አድርግ',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'የክፍል አስተያየት ሁለቱም ወቅት እና ክፍል ያስፈልጋሉ',
  'Yanıtlanan yorum bulunamadı': 'የተመለሰው አስተያየት አልተገኘም',
  'Geri bildirim 3-2000 karakter olmalı': 'ግብረመልስ 3–2000 ፊደል መሆን አለበት',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'ርዕስ እና ጽሑፍ ያስፈልጋሉ (ቢያንስ 2 ፊደል)',
  'Kendine mesaj gönderemezsin': 'ራስህን መልእክት መላክ አትችልም',
  'Mesaj en fazla 2000 karakter olabilir': 'መልእክት ቢበዛ 2000 ፊደል',
  'Mesaj 1-2000 karakter olmalı': 'መልእክት 1–2000 ፊደል መሆን አለበት',
  'Mesaj bulunamadı': 'መልእክት አልተገኘም',
  'Mesaj bulunamadı veya düzenlenemez': 'መልእክት አልተገኘም ወይም ሊስተካከል አይችልም',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'ወደ አንተ የተላከ መልእክት ብቻ ማመልከት ትችላለህ',
  'Sebep gerekli': 'ምክንያት ያስፈልጋል',
  'İtiraz edilecek aktif bir ceza yok': 'ይግባኝ የሚቀርብበት ንቁ ቅጣት የለም',
  'Zaten incelenmeyi bekleyen bir itirazın var': 'አስቀድሞ ግምገማ የሚጠባበቅ ይግባኝ አለህ',
  'Bu ceza için itirazın zaten incelendi': 'የዚህ ቅጣት ይግባኝ አስቀድሞ ተገምግሟል',
  'Medya bağlantısının süresi dolmuş': 'የሚዲያ አገናኝ ጊዜ አልቋል',
  'Bu medya için imzalı bağlantı gerekli': 'ለዚህ ሚዲያ የተፈረመ አገናኝ ያስፈልጋል',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'የጥሪ አገልግሎት እንደገና እየተጀመረ ነው፤ ትንሽ ቆይተህ ሞክር',
  'Puan göstergesi': 'የደረጃ መግለጫ',
  'İzleme İstatistiklerim': 'የእኔ የእይታ ስታቲስቲክስ',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'አንድ ክፍል ወይም ፊልም እንደተመለከቱ ምልክት ሲያደርጉ ስታቲስቲክስዎ እዚህ መከማቸት ይጀምራል።',
  '{} sa {} dk': '{} ሰ {} ደ',
  'Yaklaşık ekran süresi': 'ግምታዊ የስክሪን ጊዜ',
  'İzleme serisi': 'የእይታ ተከታታይ',
  'Şu anki seri': 'የአሁኑ ተከታታይ',
  'En uzun seri': 'ረጅሙ ተከታታይ',
  'Haftanın günleri': 'የሳምንቱ ቀናት',
  'En çok izlediklerin': 'በብዛት የተመለከቷቸው',
  'Bu dönemde izleme yok': 'በዚህ ጊዜ ውስጥ እይታ የለም',
  'Tüm zamanlar: {} bölüm · {} film · ~{}': 'በአጠቃላይ፦ {} ክፍሎች · {} ፊልሞች · ~{}',
  'Paz': 'እሑድ',
  'Pzt': 'ሰኞ',
  'Sal': 'ማክሰ',
  'Çar': 'ረቡዕ',
  'Per': 'ሐሙስ',
  'Cum': 'ዓርብ',
  'Cmt': 'ቅዳሜ',
  '{} bölüm': '{} ክፍሎች',
  '{} bölüm~tekil': '{} ክፍል',
  '{} kez': '{} ጊዜ',
  '{} kez~tekil': '{} ጊዜ',
  'Son {} gün · günlük': 'ያለፉት {} ቀናት · በየቀኑ',
  'Son {} gün · haftalık': 'ያለፉት {} ቀናት · በየሳምንቱ',
  'Ekran süren, serin ve en çok izlediklerin':
      'የስክሪን ጊዜዎ፣ ተከታታይዎ እና በብዛት የተመለከቷቸው',
  'Daralt': 'ሰብስብ',
};
