/// Otomatik üretilen çeviri haritası (he).
const Map<String, String> cevirilerHe = {
  'Aktarılacak tanınan veri bulunamadı.': 'לא נמצאו נתונים מזוהים לייבוא.',
  'Arama': 'חיפוש',
  'Aramaya başla': 'התחל לחפש',
  'Ayarlar': 'הגדרות',
  'Bağla': 'קשר',
  'Bio': 'ביו',
  'Bitirdim': 'סיימתי',
  'Bunları da Beğenebilirsin': 'אולי תאהב גם את אלה',
  'Bölüm': 'פרק',
  'Bıraktım': 'נטשתי',
  'Dil': 'שפה',
  'Dil ara...': 'חפש שפה...',
  'Dizi': 'סדרה',
  'Dizi ve filmlerini takip et': 'עקוב אחרי הסדרות והסרטים שלך',
  'Dizi yorumu': 'תגובה על הסדרה',
  'Dizi, film veya kişi ara...': 'חפש סדרה, סרט או אדם...',
  'Dosya en fazla 30MB olabilir': 'גודל הקובץ יכול להיות עד 30MB',
  'Dosya en fazla {}MB olabilir': 'גודל הקובץ יכול להיות עד {}MB',
  'E-posta': 'אימייל',
  'E-posta veya kullanıcı adı': 'אימייל או שם משתמש',
  'En az 2 harf yaz': 'הקלד לפחות 2 אותיות',
  'Film': 'סרט',
  'Film yorumu': 'תגובה על הסרט',
  'Fotoğraf / video ekle': 'הוסף תמונה / וידאו',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'תמונה או GIF — תמונת פרופיל וקאבר',
  'Giriş Yap': 'התחברות',
  'Gönder': 'שלח',
  'Gönderildi': 'נשלח',
  'Haftanın Dizileri': 'סדרות השבוע',
  'Haftanın Filmleri': 'סרטי השבוע',
  'Henüz izleme kaydın yok': 'אין לך עדיין היסטוריית צפייה',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'אין לך עדיין רשימות — צור אחת מלשונית הפרופיל.',
  'Henüz yorum yok.': 'אין תגובות עדיין.',
  'Hesabın bağlandı!': 'החשבון שלך קושר!',
  'Hesabın yok mu? Kayıt ol': 'אין לך חשבון? הירשם',
  'Hesabını Bağla': 'קשר את החשבון שלך',
  'Hesap Oluştur': 'יצירת חשבון',
  'Kapak resmi ekle': 'הוסף תמונת קאבר',
  'Kaydet': 'שמור',
  'Kendinden bahset...': 'ספר על עצמך...',
  'Keşfet': 'גלה',
  'Kimseyi takip etmiyor': 'לא עוקב אחרי אף אחד',
  'Kişi ara': 'חפש אדם',
  'Kişi yorumu': 'תגובה על האדם',
  'Konuk Oyuncular': 'שחקנים אורחים',
  'Kullanıcı adı (küçük harf)': 'שם משתמש (אותיות קטנות)',
  'Kullanıcı adı ara...': 'חפש שם משתמש...',
  'Liste adı': 'שם הרשימה',
  'Listeye Ekle': 'הוסף לרשימה',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'אתה בחשבון אורח — קשר אותו לאימייל שלך ואל תאבד את הנתונים!',
  'Misafir olarak devam et': 'המשך כאורח',
  'Oluştur': 'צור',
  'Oyuncular': 'שחקנים',
  'Profil': 'פרופיל',
  'Profil kaydedildi': 'הפרופיל נשמר',
  'Puanla': 'דרג',
  'Puanı Sil': 'מחק דירוג',
  'Puanın': 'הדירוג שלך',
  'Sezonlar': 'עונות',
  'Sunucu hatası ({})': 'שגיאת שרת ({})',
  'S{} · {}. Bölüm': 'ע{} · פרק {}',
  'S{}B{} yorumu': 'תגובה על ע{}פ{}',
  'Takibi Bırak': 'הפסק לעקוב',
  'Takip': 'במעקב',
  'Takip Edilenler': 'נעקבים',
  'Takip Et': 'עקוב',
  'Takipçi': 'עוקב',
  'Takipçi yok': 'אין עוקבים',
  'Takipçiler': 'עוקבים',
  'Takvim': 'לוח שנה',
  'Tamam': 'אישור',
  'Tekrar Dene': 'נסה שוב',
  'Tekrar dene': 'נסה שוב',
  'Toplam ekran süresi': 'זמן מסך כולל',
  'Tüm Zamanların En İyileri': 'הטובים בכל הזמנים',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'ייצא את כל הנתונים שלך (צפיות, דירוגים, תגובות, רשימות) כקובץ ZIP תואם TV Time, או ייבא ZIP מאפליקציה אחרת.',
  'Tümünü Kaldır': 'הסר הכל',
  'Tümünü İzledim': 'צפיתי בהכל',
  'Türk Dizileri': 'סדרות טורקיות',
  'Veri içe aktar (.zip)': 'ייבוא נתונים (.zip)',
  'Verilerim': 'הנתונים שלי',
  'Verilerimi dışa aktar (e-posta)': 'ייצוא הנתונים שלי (אימייל)',
  'Verilerini dışa aktar': 'ייצא את הנתונים שלך',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'אין פרקים קרובים.\nהעבר סדרה למצב "צופה" מדף הסדרה ועקוב אחרי פרקים חדשים כאן.',
  'Yapımları': 'פילמוגרפיה',
  'Yeni Diziler': 'סדרות חדשות',
  'Yeni Liste': 'רשימה חדשה',
  'Yeni kullanıcı adı (isteğe bağlı)': 'שם משתמש חדש (אופציונלי)',
  'Yorum': 'תגובה',
  'Yorumunu yaz...': 'כתוב את התגובה שלך...',
  'Zaten hesabın var mı? Giriş yap': 'כבר יש לך חשבון? התחבר',
  'ort. {}': 'ממוצע {}',
  'takip': 'במעקב',
  'takipçi': 'עוקבים',
  '{} / {} bölüm': '{} / {} פרקים',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} חודשים',
  '{} bölüm izlendi': '{} פרקים נצפו',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} דק\'',
  '{} gün': '{} ימים',
  '{} içerik': '{} פריטים',
  '{} içerik · otomatik': '{} פריטים · אוטומטי',
  '{} kayıt atlandı (eşleşmedi).': '{} רשומות דולגו (ללא התאמה).',
  '{} saat': '{} שעות',
  '{} sezon': '{} עונות',
  '{} yıl': '{} שנים',
  '{}. Bölüm': 'פרק {}',
  '{}. Sezon': 'עונה {}',
  'Çıkış Yap': 'התנתקות',
  'Ülke': 'מדינה',
  'Ülke ara...': 'חפש מדינה...',
  'Ülke seç': 'בחר מדינה',
  'İlk yorumu sen yaz!': 'כתוב את התגובה הראשונה!',
  'İncelemeler': 'ביקורות',
  'İncelemen (isteğe bağlı)': 'הביקורת שלך (אופציונלי)',
  'İptal': 'ביטול',
  'İzlediklerim': 'הצפיות שלי',
  'İzledim': 'צפיתי',
  'İzledin': 'צפית',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'היסטוריית הצפייה והרשימות שלך נשמרות; מעכשיו תוכל להתחבר מכל מכשיר.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'היסטוריית הצפייה, הדירוגים, התגובות והרשימות שלך יישלחו כקובץ ZIP לכתובת האימייל הרשומה שלך.',
  'İzleyeceğim': 'אצפה',
  'İzliyorum': 'צופה',
  'İçe aktarım tamamlandı': 'הייבוא הושלם',
  'Şifre': 'סיסמה',
  '• profil bilgisi': '• פרטי פרופיל',
  '• {} dizi durumu': '• {} סטטוסי סדרות',
  '• {} izleme kaydı': '• {} רשומות צפייה',
  '• {} liste': '• {} רשימות',
  '• {} puan': '• {} דירוגים',
  '• {} yorum': '• {} תגובות',
  '{}+ yapım': '{}+ עבודות',
  'Yorumlar': 'תגובות',
  'Yorumlar ({})': 'תגובות ({})',
  'Yorumları ({})': 'התגובות ({})',
  'Listelerim': 'הרשימות שלי',
  'Nereden izledin?': 'איפה צפית?',
  'Diziye git': 'אל הסדרה',
  'TV / Kanal': 'טלוויזיה / ערוץ',
  'Sinema': 'קולנוע',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'אחר',
  'Akış': 'פיד',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'הפיד שלך ריק.\nכשיגיבו על הסדרות והסרטים שאתה צופה בהם, זה יופיע כאן.',
  'Listeleri ({})': 'הרשימות שלו ({})',
  'Liste boş.': 'הרשימה הזו ריקה.',
  'Yanıtla': 'השב',
  '@{} kullanıcısına yanıt veriyorsun': 'אתה מגיב ל-@{}',
  'İzlediğim Diziler ({})': 'סדרות שצפיתי ({})',
  'İzlediğim Filmler ({})': 'סרטים שצפיתי ({})',
  'Tümünü gör': 'הצג הכול',
  'Bildirimler': 'התראות',
  'Henüz bildirim yok': 'אין התראות עדיין',
  '@{} yorumuna yanıt verdi': '@{} הגיב לתגובה שלך',
  '@{} yorumunu beğendi': '@{} אהב את התגובה שלך',
  '@{} seni takip etti': '@{} עוקב אחריך',
  '@{} sana mesaj gönderdi': '@{} שלח לך הודעה',
  'Mesajlar': 'הודעות',
  'Mesaj': 'הודעה',
  'Mesajını yaz...': 'כתוב הודעה...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'אין צ\'אטים עדיין.\nפתח פרופיל ושלח הודעה.',
  'Şifreni mi unuttun?': 'שכחת סיסמה?',
  'Şifreyi Sıfırla': 'איפוס סיסמה',
  'E-postadaki kod': 'הקוד מהמייל',
  'Yeni şifre': 'סיסמה חדשה',
  'Sana Özel': 'בשבילך',
  '{} özetin': 'הסיכום שלך ל-{}',
  'Yıllık izleme istatistiklerin': 'סטטיסטיקת הצפייה השנתית',
  'Rozetler': 'תגים',
  'Verdiğin puan': 'דירוגים שנתת',
  'Ortalama puanın': 'הדירוג הממוצע שלך',
  'En çok izlediğin diziler': 'הסדרות הנצפות ביותר',
  'İlk Bölüm': 'פרק ראשון',
  '100 Bölüm': '100 פרקים',
  '1000 Bölüm': '1000 פרקים',
  'İlk Film': 'סרט ראשון',
  '50 Film': '50 סרטים',
  'İlk Yorum': 'תגובה ראשונה',
  '25 Yorum': '25 תגובות',
  '10 Puan': '10 דירוגים',
  'İlk Takipçi': 'עוקב ראשון',
  '10 Dizi Bitirdin': 'סיימת 10 סדרות',
  'İzlemeyi Bıraktım': 'הפסקתי לצפות',
  'İzlediği Diziler ({})': 'סדרות שצפה בהן ({})',
  'İzlediği Filmler ({})': 'סרטים שצפה בהם ({})',
  '500 Bölüm': '500 פרקים',
  '5000 Bölüm': '5000 פרקים',
  '10 Film': '10 סרטים',
  '100 Film': '100 סרטים',
  '100 Yorum': '100 תגובות',
  '50 Puan': '50 דירוגים',
  '100 Puan': '100 דירוגים',
  '10 Takipçi': '10 עוקבים',
  '50 Takipçi': '50 עוקבים',
  '25 Dizi Bitirdin': 'סיים 25 סדרות',
  '50 Dizi Bitirdin': 'סיים 50 סדרות',
  '10 Beğeni': '10 לייקים',
  '100 Beğeni': '100 לייקים',
  'yazıyor...': 'מקליד...',
  'Profil düzeni': 'פריסת פרופיל',
  'Konumla ve kırp': 'מקם וחתוך',
  'Listeye eklendi': 'נוסף לרשימה',
  'Listeyi sil?': 'למחוק את הרשימה?',
  'Sil': 'מחק',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'הכותר יסומן כלא נצפה ויוסר מהרשימות שלך.',
  'Gelecek bölüm bugün': 'הפרק הבא היום',
  'Gelecek bölüm {} gün sonra': 'הפרק הבא בעוד {} ימים',
  'Tema': 'ערכת נושא',
  'Sistem': 'מערכת',
  'Koyu': 'כהה',
  'Açık': 'בהיר',
  'İzleyenler': 'צופים',
  'Yorumunu yaz... (@ ile etiketle)': 'כתוב את התגובה שלך... (@ לתיוג)',
  '@{} bir yorumda seni etiketledi': '‏@{} תייג אותך בתגובה',
  'Mesajı sil': 'מחק הודעה',
  'Mesaj silinemedi': 'לא ניתן היה למחוק את ההודעה',
  'Bağlantı geçersiz veya sayfa bulunamadı': 'הקישור אינו תקין או שהדף לא נמצא',
  'Keşfet\'e dön': 'חזרה לגילוי',
};
