/// Otomatik üretilen çeviri haritası (ko).
const Map<String, String> cevirilerKo = {
  'Aktarılacak tanınan veri bulunamadı.': '가져올 수 있는 데이터를 찾지 못했어요.',
  'Arama': '검색',
  'Aramaya başla': '검색을 시작해 보세요',
  'Ayarlar': '설정',
  'Bağla': '연결',
  'Bio': '소개',
  'Bitirdim': '다 봤어요',
  'Bunları da Beğenebilirsin': '이런 작품도 좋아할 거예요',
  'Bölüm': '에피소드',
  'Bıraktım': '하차했어요',
  'Dil': '언어',
  'Dil ara...': '언어 검색...',
  'Dizi': '드라마',
  'Dizi ve filmlerini takip et': '드라마와 영화를 기록해 보세요',
  'Dizi yorumu': '드라마 댓글',
  'Dizi, film veya kişi ara...': '드라마, 영화, 인물 검색...',
  'Dosya en fazla 30MB olabilir': '파일은 최대 30MB까지 가능해요',
  'Dosya en fazla {}MB olabilir': '파일은 최대 {}MB까지 가능해요',
  'E-posta': '이메일',
  'E-posta veya kullanıcı adı': '이메일 또는 사용자 이름',
  'En az 2 harf yaz': '2자 이상 입력하세요',
  'Film': '영화',
  'Film yorumu': '영화 댓글',
  'Fotoğraf / video ekle': '사진 / 동영상 추가',
  'Fotoğraf veya GIF — profil ve kapak resmi': '사진 또는 GIF — 프로필 및 커버 이미지',
  'Giriş Yap': '로그인',
  'Gönder': '보내기',
  'Gönderildi': '전송 완료',
  'Haftanın Dizileri': '이번 주 드라마',
  'Haftanın Filmleri': '이번 주 영화',
  'Henüz izleme kaydın yok': '아직 시청 기록이 없어요',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      '아직 리스트가 없어요 — 프로필 탭에서 만들어 보세요.',
  'Henüz yorum yok.': '아직 댓글이 없어요.',
  'Hesabın bağlandı!': '계정이 연결됐어요!',
  'Hesabın yok mu? Kayıt ol': '계정이 없나요? 회원가입',
  'Hesabını Bağla': '계정 연결',
  'Hesap Oluştur': '계정 만들기',
  'Kapak resmi ekle': '커버 이미지 추가',
  'Kaydet': '저장',
  'Kendinden bahset...': '자기소개를 입력해 보세요...',
  'Keşfet': '둘러보기',
  'Kimseyi takip etmiyor': '아직 아무도 팔로우하지 않아요',
  'Kişi ara': '인물 검색',
  'Kişi yorumu': '인물 댓글',
  'Konuk Oyuncular': '게스트 출연',
  'Kullanıcı adı (küçük harf)': '사용자 이름 (소문자)',
  'Kullanıcı adı ara...': '사용자 이름 검색...',
  'Liste adı': '리스트 이름',
  'Listeye Ekle': '리스트에 추가',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      '게스트 계정을 사용 중이에요 — 이메일을 연결해서 데이터를 지키세요!',
  'Misafir olarak devam et': '게스트로 계속하기',
  'Oluştur': '만들기',
  'Oyuncular': '출연진',
  'Profil': '프로필',
  'Profil kaydedildi': '프로필이 저장됐어요',
  'Puanla': '평가하기',
  'Puanı Sil': '평점 삭제',
  'Puanın': '내 평점',
  'Sezonlar': '시즌',
  'Sunucu hatası ({})': '서버 오류 ({})',
  'S{} · {}. Bölüm': 'S{} · {}화',
  'S{}B{} yorumu': 'S{}E{} 댓글',
  'Takibi Bırak': '팔로우 취소',
  'Takip': '팔로잉',
  'Takip Edilenler': '팔로잉',
  'Takip Et': '팔로우',
  'Takipçi': '팔로워',
  'Takipçi yok': '팔로워가 없어요',
  'Takipçiler': '팔로워',
  'Takvim': '캘린더',
  'Tamam': '확인',
  'Tekrar Dene': '다시 시도',
  'Tekrar dene': '다시 시도',
  'Toplam ekran süresi': '총 시청 시간',
  'Tüm Zamanların En İyileri': '역대 최고 작품',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      '모든 데이터(시청, 평점, 댓글, 리스트)를 TV Time 호환 ZIP으로 내보내거나, 다른 앱의 ZIP을 가져올 수 있어요.',
  'Tümünü Kaldır': '전체 해제',
  'Tümünü İzledim': '전체 시청 완료',
  'Türk Dizileri': '터키 드라마',
  'Veri içe aktar (.zip)': '데이터 가져오기 (.zip)',
  'Verilerim': '내 데이터',
  'Verilerimi dışa aktar (e-posta)': '내 데이터 내보내기 (이메일)',
  'Verilerini dışa aktar': '데이터 내보내기',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      '예정된 에피소드가 없어요.\n드라마 상세에서 "보는 중"으로 설정하면 새 에피소드를 여기서 확인할 수 있어요.',
  'Yapımları': '출연 작품',
  'Yeni Diziler': '새로운 드라마',
  'Yeni Liste': '새 리스트',
  'Yeni kullanıcı adı (isteğe bağlı)': '새 사용자 이름 (선택)',
  'Yorum': '댓글',
  'Yorumunu yaz...': '댓글을 입력하세요...',
  'Zaten hesabın var mı? Giriş yap': '이미 계정이 있나요? 로그인',
  'ort. {}': '평균 {}',
  'takip': '팔로잉',
  'takipçi': '팔로워',
  '{} / {} bölüm': '{} / {} 화',
  '{} TMDB': '{} TMDB',
  '{} ay': '{}개월',
  '{} bölüm izlendi': '{}화 시청함',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{}분',
  '{} gün': '{}일',
  '{} içerik': '{}개 작품',
  '{} içerik · otomatik': '{}개 작품 · 자동',
  '{} kayıt atlandı (eşleşmedi).': '{}개 기록을 건너뛰었어요 (일치하지 않음).',
  '{} saat': '{}시간',
  '{} sezon': '시즌 {}개',
  '{} yıl': '{}년',
  '{}. Bölüm': '{}화',
  '{}. Sezon': '시즌 {}',
  'Çıkış Yap': '로그아웃',
  'Ülke': '국가',
  'Ülke ara...': '국가 검색...',
  'Ülke seç': '국가 선택',
  'İlk yorumu sen yaz!': '첫 댓글을 남겨 보세요!',
  'İncelemeler': '리뷰',
  'İncelemen (isteğe bağlı)': '리뷰 (선택)',
  'İptal': '취소',
  'İzlediklerim': '시청 기록',
  'İzledim': '봤어요',
  'İzledin': '봤어요',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      '시청 기록과 리스트는 그대로 유지되고, 이제 어떤 기기에서든 로그인할 수 있어요.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      '시청 기록, 평점, 댓글, 리스트가 ZIP 파일로 등록된 이메일 주소로 전송돼요.',
  'İzleyeceğim': '볼래요',
  'İzliyorum': '보는 중',
  'İçe aktarım tamamlandı': '가져오기 완료',
  'Şifre': '비밀번호',
  '• profil bilgisi': '• 프로필 정보',
  '• {} dizi durumu': '• 드라마 상태 {}개',
  '• {} izleme kaydı': '• 시청 기록 {}개',
  '• {} liste': '• 리스트 {}개',
  '• {} puan': '• 평점 {}개',
  '• {} yorum': '• 댓글 {}개',
  '{}+ yapım': '{}+ 작품',
  'Yorumlar': '댓글',
  'Yorumlar ({})': '댓글 ({})',
  'Yorumları ({})': '남긴 댓글 ({})',
  'Listelerim': '내 리스트',
  'Nereden izledin?': '어디서 봤어?',
  'Diziye git': '작품으로 이동',
  'TV / Kanal': 'TV / 채널',
  'Sinema': '영화관',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': '기타',
  'Akış': '피드',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      '피드가 비어 있어요.\n내가 보는 작품에 댓글이 달리면 여기에 표시돼요.',
  'Listeleri ({})': '리스트 ({})',
  'Liste boş.': '이 리스트는 비어 있어요.',
  'Yanıtla': '답글',
  '@{} kullanıcısına yanıt veriyorsun': '@{}에게 답글 작성 중',
  'İzlediğim Diziler ({})': '시청한 시리즈 ({})',
  'İzlediğim Filmler ({})': '시청한 영화 ({})',
  'Tümünü gör': '전체 보기',
  'Bildirimler': '알림',
  'Henüz bildirim yok': '아직 알림이 없어요',
  '@{} yorumuna yanıt verdi': '@{} 님이 댓글에 답글을 달았어요',
  '@{} yorumunu beğendi': '@{} 님이 댓글을 좋아해요',
  '@{} seni takip etti': '@{} 님이 나를 팔로우했어요',
  '@{} sana mesaj gönderdi': '@{} 님이 메시지를 보냈어요',
  'Mesajlar': '메시지',
  'Mesaj': '메시지',
  'Mesajını yaz...': '메시지를 입력...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      '아직 대화가 없어요.\n프로필에서 메시지를 보내보세요.',
  'Şifreni mi unuttun?': '비밀번호를 잊으셨나요?',
  'Şifreyi Sıfırla': '비밀번호 재설정',
  'E-postadaki kod': '이메일 코드',
  'Yeni şifre': '새 비밀번호',
  'Sana Özel': '맞춤 추천',
  '{} özetin': '{}년 결산',
  'Yıllık izleme istatistiklerin': '연간 시청 통계',
  'Rozetler': '배지',
  'Verdiğin puan': '남긴 평점',
  'Ortalama puanın': '평균 평점',
  'En çok izlediğin diziler': '가장 많이 본 시리즈',
  'İlk Bölüm': '첫 에피소드',
  '100 Bölüm': '100화',
  '1000 Bölüm': '1000화',
  'İlk Film': '첫 영화',
  '50 Film': '영화 50편',
  'İlk Yorum': '첫 댓글',
  '25 Yorum': '댓글 25개',
  '10 Puan': '평점 10개',
  'İlk Takipçi': '첫 팔로워',
  '10 Dizi Bitirdin': '10개 작품 완주',
  'İzlemeyi Bıraktım': '시청 중단',
  'İzlediği Diziler ({})': '시청한 시리즈 ({})',
  'İzlediği Filmler ({})': '시청한 영화 ({})',
  '500 Bölüm': '500화',
  '5000 Bölüm': '5000화',
  '10 Film': '영화 10편',
  '100 Film': '영화 100편',
  '100 Yorum': '댓글 100개',
  '50 Puan': '평점 50개',
  '100 Puan': '평점 100개',
  '10 Takipçi': '팔로워 10명',
  '50 Takipçi': '팔로워 50명',
  '25 Dizi Bitirdin': '25개 작품 완주',
  '50 Dizi Bitirdin': '50개 작품 완주',
  '10 Beğeni': '좋아요 10개',
  '100 Beğeni': '좋아요 100개',
  'yazıyor...': '입력 중...',
};
