/// Otomatik üretilen çeviri haritası (ru).
const Map<String, String> cevirilerRu = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Вы все это видели, мы покажем вам с самого начала',
  'Aktarılacak tanınan veri bulunamadı.':
      'Не найдено распознанных данных для импорта.',
  'Arama': 'Поиск',
  'Aramaya başla': 'Начни поиск',
  'Son aramalar': 'Недавние запросы',
  'Ayarlar': 'Настройки',
  'Bağla': 'Привязать',
  'Bio': 'Био',
  'Bitirdim': 'Досмотрено',
  'Bunları da Beğenebilirsin': 'Тебе может понравиться',
  'Bölüm': 'Эпизод',
  'Bıraktım': 'Брошено',
  'Dil': 'Язык',
  'Dil ara...': 'Поиск языка...',
  'Dizi': 'Сериал',
  'Dizi ve filmlerini takip et': 'Следи за своими сериалами и фильмами',
  'Dizi yorumu': 'Комментарий к сериалу',
  'Dizi, film veya kişi ara...': 'Поиск сериалов, фильмов и людей...',
  'Dosya en fazla 30MB olabilir': 'Файл не больше 30 МБ',
  'Dosya en fazla {}MB olabilir': 'Файл не больше {} МБ',
  'E-posta': 'Эл. почта',
  'E-posta veya kullanıcı adı': 'Эл. почта или имя пользователя',
  'En az 2 harf yaz': 'Введи минимум 2 буквы',
  'Film': 'Фильм',
  'Film yorumu': 'Комментарий к фильму',
  'Fotoğraf / video ekle': 'Добавить фото / видео',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Фото или GIF — аватар и обложка',
  'Giriş Yap': 'Войти',
  'Gönder': 'Отправить',
  'Gönderildi': 'Отправлено',
  'Haftanın Dizileri': 'Сериалы недели',
  'Haftanın Filmleri': 'Фильмы недели',
  'Henüz izleme kaydın yok': 'У тебя пока нет истории просмотров',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'У тебя пока нет списков — создай во вкладке «Профиль».',
  'Henüz yorum yok.': 'Пока нет комментариев.',
  'Hesabın bağlandı!': 'Аккаунт привязан!',
  'Hesabın yok mu? Kayıt ol': 'Нет аккаунта? Зарегистрируйся',
  'Hesabını Bağla': 'Привяжи аккаунт',
  'Hesap Oluştur': 'Создать аккаунт',
  'Kapak resmi ekle': 'Добавить обложку',
  'Kaydet': 'Сохранить',
  'Kendinden bahset...': 'Расскажи о себе...',
  'Keşfet': 'Обзор',
  'Kimseyi takip etmiyor': 'Нет подписок',
  'Kişi ara': 'Поиск людей',
  'Kişi yorumu': 'Комментарий о человеке',
  'Konuk Oyuncular': 'Приглашённые актёры',
  'Kullanıcı adı (küçük harf)': 'Имя пользователя (строчными)',
  'Kullanıcı adı ara...': 'Поиск по имени пользователя...',
  'Liste adı': 'Название списка',
  'Listeye Ekle': 'Добавить в список',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Ты в гостевом аккаунте — привяжи почту, не потеряй свои данные!',
  'Misafir olarak devam et': 'Продолжить как гость',
  'Oluştur': 'Создать',
  'Oyuncular': 'Актёры',
  'Profil': 'Профиль',
  'Profil kaydedildi': 'Профиль сохранён',
  'Puanla': 'Оценить',
  'Puanı Sil': 'Удалить оценку',
  'Puanın': 'Твоя оценка',
  'Sezonlar': 'Сезоны',
  'Sunucu hatası ({})': 'Ошибка сервера ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Комментарий к S{}E{}',
  'Takibi Bırak': 'Отписаться',
  'Takip': 'Подписки',
  'Takip Edilenler': 'Подписки',
  'Takip Et': 'Подписаться',
  'Takipçi': 'Подписчики',
  'Takipçi yok': 'Нет подписчиков',
  'Takipçiler': 'Подписчики',
  'Takvim': 'Календарь',
  'Tamam': 'ОК',
  'Tekrar Dene': 'Повторить',
  'Tekrar dene': 'Попробуй ещё раз',
  'Toplam İzleme Süresi': 'Общее экранное время',
  'Tüm Zamanların En İyileri': 'Лучшие за всё время',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'Скачай все свои данные (просмотры, оценки, комментарии, списки) в ZIP, совместимом с TV Time, или импортируй ZIP из другого приложения.',
  'Tümünü Kaldır': 'Убрать все',
  'Tümünü İzledim': 'Всё просмотрено',
  'Türk Dizileri': 'Турецкие сериалы',
  'Veri içe aktar (.zip)': 'Импорт данных (.zip)',
  'Verilerim': 'Мои данные',
  'Verilerimi dışa aktar (e-posta)': 'Экспорт моих данных (на почту)',
  'Verilerini dışa aktar': 'Экспорт твоих данных',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Нет предстоящих эпизодов.\nПоставь сериалу статус «Смотрю» на его странице и следи за новыми эпизодами здесь.',
  'Yapımları': 'Фильмография',
  'Yeni Diziler': 'Новые сериалы',
  'Yeni Liste': 'Новый список',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Новое имя пользователя (необязательно)',
  'Yorum': 'Комментарий',
  'Yorumunu yaz...': 'Напиши комментарий...',
  'Zaten hesabın var mı? Giriş yap': 'Уже есть аккаунт? Войди',
  'ort. {}': 'ср. {}',
  'takip': 'подписки',
  'takipçi': 'подписчики',
  '{} / {} bölüm': '{} / {} эпизодов',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} мес.',
  '{} ay~tekil': '{} мес.',
  '{} bölüm izlendi': '{} эпизодов просмотрено',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} мин',
  '{} dk~tekil': '{} мин',
  '{} gün': '{} дн.',
  '{} gün~tekil': '{} дн.',
  '{} içerik': '{} тайтлов',
  '{} içerik · otomatik': '{} тайтлов · авто',
  '{} kayıt atlandı (eşleşmedi).': '{} записей пропущено (нет совпадения).',
  '{} saat': '{} ч',
  '{} saat~tekil': '{} ч',
  '{} sezon': '{} сезонов',
  '{} yıl': '{} лет',
  '{} yıl~tekil': '{} год',
  '{}. Bölüm': 'Эпизод {}',
  '{}. Sezon': 'Сезон {}',
  'Çıkış Yap': 'Выйти',
  'Ülke': 'Страна',
  'Ülke ara...': 'Поиск страны...',
  'Ülke seç': 'Выбери страну',
  'İlk yorumu sen yaz!': 'Напиши первый комментарий!',
  'İncelemeler': 'Рецензии',
  'İncelemen (isteğe bağlı)': 'Твоя рецензия (необязательно)',
  'İptal': 'Отмена',
  'İzlediklerim': 'История просмотров',
  'İzledim': 'Просмотрено',
  'İzledin': 'Просмотрено',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'История просмотров и списки сохранятся; теперь можно входить с любого устройства.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'История просмотров, оценки, комментарии и списки будут отправлены ZIP-архивом на твою почту.',
  'İzleyeceğim': 'Буду смотреть',
  'İzliyorum': 'Смотрю',
  'İçe aktarım tamamlandı': 'Импорт завершён',
  'Şifre': 'Пароль',
  '• profil bilgisi': '• данные профиля',
  '• {} dizi durumu': '• {} статусов сериалов',
  '• {} izleme kaydı': '• {} записей просмотра',
  '• {} liste': '• {} списков',
  '• {} puan': '• {} оценок',
  '• {} yorum': '• {} комментариев',
  '{}+ yapım': '{}+ работ',
  'Yorumlar': 'Комментарии',
  'Yorumlar ({})': 'Комментарии ({})',
  'Yorumları ({})': 'Комментарии ({})',
  'Listelerim': 'Мои списки',
  'Nereden izledin?': 'Где смотрели?',
  'Diziye git': 'К сериалу',
  'TV / Kanal': 'ТВ / канал',
  'Sinema': 'Кинотеатр',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Другое',
  'Akış': 'Лента',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Твоя лента пуста.\nКогда прокомментируют сериалы и фильмы, которые ты смотришь, это появится здесь.',
  'Listeleri ({})': 'Списки ({})',
  'Liste boş.': 'Этот список пуст.',
  'Yanıtla': 'Ответить',
  '@{} kullanıcısına yanıt veriyorsun': 'Ты отвечаешь @{}',
  'İzlediğim Diziler ({})': 'Просмотренные сериалы ({})',
  'İzlediğim Filmler ({})': 'Просмотренные фильмы ({})',
  'Tümünü gör': 'Показать все',
  'Bildirimler': 'Уведомления',
  'Henüz bildirim yok': 'Пока нет уведомлений',
  '@{} yorumuna yanıt verdi': 'Новый ответ на твой комментарий: @{}',
  '@{} yorumunu beğendi': '@{} понравился твой комментарий',
  '@{} seni takip etti': 'Новый подписчик: @{}',
  '@{} sana mesaj gönderdi': 'Новое сообщение от @{}',
  'Mesajlar': 'Сообщения',
  'Mesaj': 'Сообщение',
  'Mesaja eklenecek': 'Будет добавлено к сообщению',
  'Mesajını yaz...': 'Напиши сообщение...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Пока нет чатов.\nОткрой профиль и отправь сообщение.',
  'Şifreni mi unuttun?': 'Забыли пароль?',
  'Şifreyi Sıfırla': 'Сбросить пароль',
  'E-postadaki kod': 'Код из письма',
  'Yeni şifre': 'Новый пароль',
  'Sana Özel': 'Для тебя',
  '{} özetin': 'Твои итоги {}',
  'Yıllık izleme istatistiklerin': 'Годовая статистика просмотров',
  'Rozetler': 'Значки',
  'Verdiğin puan': 'Поставлено оценок',
  'Ortalama puanın': 'Средняя оценка',
  'En çok izlediğin diziler': 'Самые просматриваемые сериалы',
  'İlk Bölüm': 'Первая серия',
  '100 Bölüm': '100 серий',
  '1000 Bölüm': '1000 серий',
  'İlk Film': 'Первый фильм',
  '50 Film': '50 фильмов',
  'İlk Yorum': 'Первый комментарий',
  '25 Yorum': '25 комментариев',
  '10 Puan': '10 оценок',
  'İlk Takipçi': 'Первый подписчик',
  '10 Dizi Bitirdin': '10 сериалов завершено',
  'İzlemeyi Bıraktım': 'Больше не смотрю',
  'İzlediği Diziler ({})': 'Просмотренные сериалы ({})',
  'İzlediği Filmler ({})': 'Просмотренные фильмы ({})',
  '500 Bölüm': '500 серий',
  '5000 Bölüm': '5000 серий',
  '10 Film': '10 фильмов',
  '100 Film': '100 фильмов',
  '100 Yorum': '100 комментариев',
  '50 Puan': '50 оценок',
  '100 Puan': '100 оценок',
  '10 Takipçi': '10 подписчиков',
  '50 Takipçi': '50 подписчиков',
  '25 Dizi Bitirdin': '25 сериалов завершено',
  '50 Dizi Bitirdin': '50 сериалов завершено',
  '10 Beğeni': '10 лайков',
  '100 Beğeni': '100 лайков',
  'yazıyor...': 'печатает...',
  'Profil düzeni': 'Порядок разделов профиля',
  'Konumla ve kırp': 'Выбери область и обрежь',
  'Listeye eklendi': 'Добавлено в список',
  'Listeyi sil?': 'Удалить список?',
  'Sil': 'Удалить',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Тайтл будет отмечен как непросмотренный и удалён из твоих списков.',
  'Gelecek bölüm bugün': 'Новая серия сегодня',
  'Gelecek bölüm {} gün sonra': 'Новая серия через {} дн.',
  'Tema': 'Тема',
  'Sistem': 'Системная',
  'Koyu': 'Тёмная',
  'Açık': 'Светлая',
  'İzleyenler': 'Зрители',
  'Yorumunu yaz... (@ ile etiketle)':
      'Напиши комментарий... (@ чтобы отметить)',
  '@{} bir yorumda seni etiketledi': 'Упоминание от @{} в комментарии',
  'Mesajı sil': 'Удалить сообщение',
  'Mesaj silinemedi': 'Не удалось удалить сообщение',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Ссылка недействительна или страница не найдена',
  "Keşfet'e dön": 'Назад к Обзору',
  'Düzenle': 'Изменить',
  'Mesajı düzenle': 'Изменить сообщение',
  'Yanıtlanıyor': 'Ответ',
  'düzenlendi': 'изменено',
  'Fotoğraf': 'Фото',
  'Video': 'Видео',
  'İçerik': 'Контент',
  'çevrimiçi': 'в сети',
  'son görülme {} dk önce': 'в сети {} мин назад',
  'son görülme {} saat önce': 'в сети {} ч назад',
  'son görülme {} gün önce': 'в сети {} дн назад',
  'Yorumlar yüklenemedi': 'Не удалось загрузить комментарии',
  'Favori': 'Избранное',
  'Listeye ekle': 'В список',
  'İçerik paylaş': 'Поделиться',
  'Kapat': 'Закрыть',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Всё, что ты отметишь просмотренным, собирается здесь.',
  'Henüz sohbetin yok': 'Пока нет переписок',
  'Bir profile girip mesaj gönderebilirsin.':
      'Открой профиль и отправь сообщение.',
  'Listeyi sil': 'Удалить список',
  'Puan kaydedilemedi': 'Не удалось сохранить оценку',
  'Nerede İzlenir': 'Где смотреть',
  'Abonelik': 'Подписка',
  'Kirala': 'Аренда',
  'Satın al': 'Купить',
  'Devam et': 'Продолжить',
  'Şikayet et': 'Пожаловаться',
  'Engelle': 'Заблокировать',
  'Engeli kaldır': 'Разблокировать',
  'Kullanıcı engellendi': 'Пользователь заблокирован',
  'Engel kaldırıldı': 'Блокировка снята',
  'Şikayet sebebi': 'Причина жалобы',
  'Spam veya yanıltıcı': 'Спам или обман',
  'Taciz veya nefret söylemi': 'Оскорбления или разжигание ненависти',
  'Uygunsuz / cinsel içerik': 'Неприемлемый / сексуальный контент',
  'Şiddet veya tehlikeli içerik': 'Насилие или опасный контент',
  'Telif hakkı ihlali': 'Нарушение авторских прав',
  'Şikayetin alındı, teşekkürler': 'Твоя жалоба принята, спасибо',
  'Hesabımı Sil': 'Удалить аккаунт',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Твой аккаунт и все данные (история, оценки, комментарии, списки, сообщения) будут удалены навсегда. Это нельзя отменить.',
  'Şifreni gir': 'Введи пароль',
  'Hesabımı kalıcı sil': 'Удалить аккаунт навсегда',
  'Sesli mesaj': 'Голосовое сообщение',
  'Ses gönderilemedi': 'Не удалось отправить голосовое сообщение',
  'Kaydediliyor…': 'Запись…',
  'Ses oynatılamadı': 'Не удалось воспроизвести аудио',
  'Oynat': 'Воспроизвести',
  'Duraklat': 'Пауза',
  'Liste görünümü': 'Список',
  'Takvim görünümü': 'Календарь',
  'Önceki ay': 'Предыдущий месяц',
  'Sonraki ay': 'Следующий месяц',
  'Bu gün bölüm yok': 'В этот день нет серий',
  'Gizlilik Politikası': 'Политика конфиденциальности',
  'Son güncelleme: {}': 'Последнее обновление: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Эта политика объясняет, какие данные собираются, как они используются и какие у тебя есть права при использовании приложения dizi.jpg и сайта dizijpg.com.',
  'Topladığımız Veriler': 'Какие данные мы собираем',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Аккаунт: адрес электронной почты, имя пользователя и пароль. Пароли хранятся в виде необратимого хеша; гостевыми аккаунтами можно пользоваться без почты.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Профиль: сведения, которые ты добавляешь по желанию, — аватар, обложка, био и страна.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Использование: твоя история просмотров, оценки, комментарии, списки, реакции и избранное.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Сообщения: твои текстовые, графические и голосовые сообщения хранятся на наших серверах. Сообщения не защищены сквозным шифрованием; их просматривают только при жалобе, в целях модерации.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Загруженные файлы: фото, GIF, видео и голосовые записи, которые ты добавляешь в профиль, комментарии и сообщения.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Технические данные: IP-адрес, приблизительное местоположение (страна/город), платформа устройства, версия приложения и журналы ошибок. Они хранятся для безопасности и отладки.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Статистика использования: тип устройства, операционная система и браузер, с которых выполнен вход, добавляются в ежедневные суммарные счётчики в виде грубых категорий; сам идентификатор браузера не сохраняется, и эти числа невозможно связать с конкретными людьми.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Уведомления: для push-уведомлений мы храним токен твоего устройства и выбранный язык. Уведомления можно в любой момент отключить в настройках устройства.',
  'Verileri Nasıl Kullanırız': 'Как мы используем твои данные',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Мы используем твои данные только для работы сервиса, защиты аккаунта, отправки уведомлений, исправления ошибок и предотвращения злоупотреблений. Мы не продаём твои данные и не передаём их никому в рекламных целях.',
  'Çerezler ve Yerel Depolama': 'Cookie и локальное хранилище',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Локальное хранилище используется только для того, чтобы не разлогинивать тебя и запоминать настройки вроде языка и темы. Рекламных и отслеживающих cookie нет.',
  'Üçüncü Taraf Hizmetler': 'Сторонние сервисы',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Данные о сериалах и фильмах поступают из TMDB, сведения о стриминговых платформах — из JustWatch. Push-уведомления доставляются через Google Firebase, трафик сайта защищает Cloudflare. На эти сервисы распространяются их собственные политики конфиденциальности.',
  'Saklama ve Silme': 'Хранение и удаление',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Твои данные хранятся, пока существует аккаунт. Через «Удалить аккаунт» в настройках можно удалить аккаунт навсегда; данные стираются сразу, а их копии в резервных копиях — не позднее чем через 14 дней. Журналы ошибок автоматически удаляются через 30 дней.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'Ты можешь выгрузить свои данные в виде ZIP из настроек; архив придёт на твою электронную почту.',
  'Güvenlik': 'Безопасность',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Данные передаются по зашифрованным соединениям (HTTPS) и хранятся на серверах с ограниченным доступом.',
  'Çocukların Gizliliği': 'Конфиденциальность детей',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg не предназначен для детей младше 13 лет.',
  'Hakların': 'Твои права',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Согласно KVKK и GDPR ты имеешь право на доступ к своим данным, их исправление, удаление и перенос. По этим вопросам напиши нам: {}',
  'Değişiklikler': 'Изменения',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Если политика изменится, новая версия будет опубликована на этой странице, а дата обновления — изменена.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Регистрируясь, ты принимаешь {}.',
  'Kullanıcılar': 'Пользователи',
  'Fotoğrafı değiştir': 'Сменить фото',
  'Yeniden konumlandır': 'Перекадрировать',
  'Bir şeyler ters gitti': 'Что-то пошло не так',
  'Sosyal Bağlantılar': 'Соцсети',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'В профиле показывается до 3 ссылок.',
  'Platform seç': 'Выбери платформу',
  'Kullanıcı adın': 'Твоё имя пользователя',
  'Ekle': 'Добавить',
  'Kaldır': 'Убрать',
  'Kopyalandı: {}': 'Скопировано: {}',
  'Geçersiz kullanıcı adı': 'Недопустимое имя пользователя',
  'Bağlantı ekle': 'Добавить ссылку',
  'Spoiler olabilir — dokun ve gör':
      'Возможны спойлеры — нажми, чтобы посмотреть',
  'Beğeni': 'Лайки',
  'Beğen': 'Нравится',
  'Görüntülenme': 'Просмотры',
  'Tam ekran': 'Во весь экран',
  'Arama başarısız': 'Поиск не удался',
  'Sonuç bulunamadı': 'Ничего не найдено',
  'Dizi ve Filmler': 'Сериалы и фильмы',
  'Kişiler': 'Люди',
  'Ana Sayfa': 'Главная',
  'Paylaş': 'Поделиться',
  'Yanıtlar': 'Ответы',
  'Yaklaşan Bölümler': 'Ближайшие серии',
  'Yetişme Listesi': 'Список к просмотру',
  'Şunu mu demek istedin': 'Возможно, вы имели в виду',
  'Spoiler': 'Спойлер',
  'Spoiler — dokun ve gör': 'Спойлер — нажми, чтобы увидеть',
  'uyum': 'совпадения',
  'Uyum': 'Совпадение',
  '{} ortak dizi': '{} общих сериалов',
  '{} ortak film': '{} общих фильмов',
  'Bildirim Tercihleri': 'Настройки уведомлений',
  'Beğeniler': 'Лайки',
  'Yeni takipçiler': 'Новые подписчики',
  'Etiketlenmeler': 'Упоминания',
  'Yeniden izledim': 'Пересмотрено',
  '{}. kez izlendi': 'Просмотрено {} раз',
  'Gönderi bulunamadı': 'Публикация не найдена',
  'Gözat': 'Обзор',
  'Diziler': 'Сериалы',
  'Filmler': 'Фильмы',
  'Tümü': 'Все',
  'Farklı bir tür seç.': 'Попробуй другой жанр.',
  'Gizlilik': 'Приватность',
  'İzlediklerimi gizle': 'Скрыть, что я смотрю',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Просмотренные сериалы и фильмы не будут видны в твоём профиле',
  'Yorumlarımı gizle': 'Скрыть мои комментарии',
  'Profilinde yorumların görünmez':
      'Твои комментарии не будут видны в твоём профиле',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Отдельный сериал или фильм можно скрыть чипом «Скрыть в моём профиле» на его странице.',
  'Geri Bildirim': 'Обратная связь',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Напиши своё мнение и предложения о приложении...',
  'Teşekkürler! Geri bildirimin alındı.': 'Спасибо! Твой отзыв получен.',
  'Profilimde gizle': 'Скрыть в моём профиле',
  'Yorumları': 'Комментарии',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Этот пользователь пока ничего не смотрел.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Этот пользователь предпочитает не показывать свои комментарии.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Данные: JustWatch',
  'Web Sitesi': 'Веб-сайт',
  'Diğer uygulamalar': 'Другие приложения',
  'Bağlantıyı kopyala': 'Копировать ссылку',
  'Henüz kimseyi takip etmiyorsun.': 'Ты пока ни на кого не подписан.',
  'Çevir': 'Перевести',
  'Çeviri şu an yapılamadı': 'Перевод сейчас недоступен',
  'Bağlantı açılamadı': 'Не удалось открыть ссылку',
  'Orijinali göster': 'Показать оригинал',
  'Çeviriyi göster': 'Показать перевод',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'В этом месяце нет серий с объявленной датой выхода. Даты обычно сообщают за несколько недель, и они появятся здесь.',
  'devamı': 'ещё',
  'Google ile devam et': 'Продолжить с Google',
  'Google girişi başarısız': 'Не удалось войти через Google',
  'Veri tasarrufu': 'Экономия трафика',
  'Wi-Fi ağında veri tasarrufu': 'Экономия трафика в Wi-Fi',
  'Mobil veride veri tasarrufu': 'Экономия трафика в мобильной сети',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Когда включено, фото не загружаются заранее — грузится только тот кадр, который ты смотришь.',
  'Çocuk güvenliği': 'Безопасность детей',
  'Türk Filmleri': 'Турецкие фильмы',
  'En Yüksek Puanlı Filmler': 'Фильмы с высшим рейтингом',
  'En Yüksek Puanlı Diziler': 'Сериалы с высшим рейтингом',
  'En Çok İzlenen Filmler': 'Самые просматриваемые фильмы',
  'Popüler Diziler': 'Популярные сериалы',
  'En Çok Kazanan Filmler': 'Самые кассовые фильмы',
  'Kült Filmler': 'Культовые фильмы',
  'Yeni Filmler': 'Новые фильмы',
  'Yorum yap': 'Комментировать',
  'Henüz yorum yok': 'Пока нет комментариев',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Твои комментарии к сериалам и фильмам собираются здесь.',
  'GIF ekle': 'Добавить GIF',
  'İlk yorumu sen yaz': 'Оставь первый комментарий',
  'Video altyazıları': 'Видео субтитры',
  'Videolarda altyazı göster': 'Показывать субтитры на видео',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Предложение, произнесенное в видео, записано на экране. Текст является переводом: английский на турецкой речи, турецкий на других языках.',
  'Güncelleme gerekli': 'Требуется обновление',
  'Yeni sürüm var': 'Доступна новая версия',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Установите новую версию dizi.jpg, чтобы продолжить.',
  'Güncelle': 'Обновить',
  'Daha sonra': 'Позже',
  'Takvim güncelleniyor': 'Календарь обновляется',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Не удалось обновить календарь, показан старый список',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Некоторые сериалы не загрузились, список может быть неполным',
  'Yenile': 'Обновить',
  'Devam etmek için giriş yap': 'Войдите, чтобы продолжить',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Бесплатного аккаунта достаточно, чтобы ставить оценки, писать комментарии и собирать свою библиотеку.',
  'Şimdi değil': 'Не сейчас',
  'Yorum yazmak için giriş yap': 'Войдите, чтобы написать комментарий',
  'Kişilere göndermek için giriş yap': 'Войдите, чтобы отправить людям',
  'Beğenenler': 'Оценили',
  'Henüz beğeni yok': 'Пока нет отметок',
  'Bu gönderiyi ilk beğenen sen ol': 'Оцените первым',
  'Bu gönderiye yanıt': 'Ответ на эту публикацию',
  'Spoiler içeren gönderi': 'Пост со спойлерами',
  'Görsel gönderi': 'Пост с фото',
  'Bu yorumu profilimde gizle': 'Скрыть этот комментарий в моём профиле',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Комментарий останется на странице сериала и фильма',
  'Bu yorumu sil': 'Удалить этот комментарий',
  'Yorum profilinde gizlendi': 'Комментарий скрыт в твоём профиле',
  'Geri al': 'Отменить',
  'Yorum silinsin mi?': 'Удалить комментарий?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Этот комментарий будет удалён навсегда везде. Отменить это будет нельзя.',
  'Yorum silindi': 'Комментарий удалён',
  'Yorum profilinde tekrar görünüyor':
      'Комментарий снова виден в твоём профиле',
  'Gizlenen yorumun yok': 'Нет скрытых комментариев',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Комментарии, которые ты скрываешь долгим нажатием на пост во вкладке Комментарии твоего профиля, собираются здесь.',
  'Gizlenen yorumlar': 'Скрытые комментарии',
  'Gönderiye git': 'Перейти к посту',
  'Tekrar göster': 'Показать снова',
  'Yanıtlarımı gizle': 'Скрыть мои ответы',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Ответы, которые ты пишешь на посты других людей, видны только тебе',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Показать снова комментарии, скрытые тобой в своём профиле',
  'Sıralama': 'Сортировка',
  'Önerilen': 'Рекомендуемое',
  'Kronolojik': 'Хронологический',
  'Gelen mesaj istekleri': 'Входящие запросы на переписку',
  'Mesaj isteğin yok': 'Нет запросов на переписку',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Здесь появляются сообщения от людей, на которых вы не подписаны.',
  'Çevrimiçi durumumu gizle': 'Скрыть мой статус в сети',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Другие не увидят ваш статус в сети и время последнего посещения в сообщениях',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Среди наших первых пользователей. Эти отзывы помогли приложению стать таким, какое оно сегодня.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Ты среди наших первых пользователей. Твои отзывы помогли приложению стать таким, какое оно сегодня.',
  'İleri': 'Далее',
  'Seçilen dosya okunamadı': 'Не удалось прочитать выбранный файл',
  'Video açılamadı': 'Не удалось открыть видео',
  'En fazla {} medya seçebilirsin': 'Можно выбрать не более {} файлов',
  'Hiçbir medya yüklenemedi': 'Не удалось загрузить ни один файл',
  'Seçimi kaldır': 'Убрать из выбора',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'В одном комментарии можно загрузить до {} МБ',
  '{} dosya okunamadı': 'Не удалось прочитать файлов: {}',
  '{} medya eklendi, {} yüklenemedi': 'Добавлено: {}, не загружено: {}',
  'Kırp': 'Обрезать',
  'Çiz': 'Рисовать',
  'Metin': 'Текст',
  'Emoji': 'Эмодзи',
  'Yinele': 'Повторить',
  'Daha fazla': 'Ещё',
  'Hazırlanıyor…': 'Подготовка…',
  'Düzenlemeden çık?': 'Выйти из редактирования?',
  'Yaptığın değişiklikler kaybolacak.': 'Внесённые изменения будут потеряны.',
  'Çık': 'Выйти',
  'Serbest çizim': 'От руки',
  'Ok': 'Стрелка',
  'Dikdörtgen': 'Прямоугольник',
  'Daire': 'Круг',
  'Bulanıklaştır': 'Размыть',
  'Pikselleştir': 'Пикселизировать',
  'Silgi': 'Ластик',
  'Çizgi kalınlığı': 'Толщина линии',
  'Saydamlık': 'Непрозрачность',
  'Dolgu': 'Заливка',
  'Renk': 'Цвет',
  'Döndür': 'Повернуть',
  'Yansıt': 'Отразить',
  'Oran': 'Пропорции',
  'Sıfırla': 'Сбросить',
  'Serbest': 'Свободно',
  'Metin yaz...': 'Введите текст...',
  'Hizala': 'Выравнивание',
  'Arka plan': 'Фон',
  'Emoji ara...': 'Поиск эмодзи...',
  'Son kullanılanlar': 'Недавние',
  'İfadeler ve insanlar': 'Смайлики и люди',
  'Hayvanlar ve doğa': 'Животные и природа',
  'Yiyecek ve içecek': 'Еда и напитки',
  'Etkinlikler': 'Занятия',
  'Seyahat ve yerler': 'Путешествия и места',
  'Nesneler': 'Объекты',
  'Semboller': 'Символы',
  'Bayraklar': 'Флаги',
  'Görseli düzenle': 'Редактировать фото',
  'Düzenlendi': 'Отредактировано',
  'Düzenlenemedi': 'Не удалось отредактировать',
  'Düzenlenen görsel çok büyük':
      'Отредактированное изображение слишком большое',
  'Videoyu düzenle': 'Редактировать видео',
  'Sesi kapat': 'Выключить звук',
  'Sesi aç': 'Включить звук',
  'İptal ediliyor…': 'Отмена…',
  'Bu biraz sürebilir': 'Это может занять некоторое время',
  'Video çok büyük': 'Видео слишком большое',
  'Video hazırlanamadı': 'Не удалось подготовить видео',
  'Başlangıç': 'Начало',
  'Bitiş': 'Конец',
  'En çok {} saniye seçebilirsin': 'Можно выбрать не более {} секунд',
  'Dosya en fazla {} MB olabilir': 'Файл может весить максимум {} МБ',
  'Medya ekle': 'Добавить медиа',
  'Seçili medya kalmadı': 'Медиа не выбрано',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Выберите фото или видео, чтобы добавить к комментарию.',
  'Medya seç': 'Выбрать медиа',
  'Daha fazla ekle': 'Добавить ещё',
  'Medya seçilemedi': 'Не удалось выбрать медиа',
  'Favori oyuncular': 'Любимые актёры',
  'Henüz favori oyuncun yok': 'Пока нет любимых актёров',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Откройте страницу актёра и коснитесь сердечка справа вверху, чтобы добавить его сюда.',
  '{} yapımdan {} tanesini izledin': 'Вы посмотрели {} из {}',
  'izledin': 'просмотрено',
  'İzlemedin': 'Не просмотрено',
  'Yapım bulunamadı': 'Ничего не найдено',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'У этого человека нет сериалов или фильмов для показа.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'История просмотров привязана к вашему аккаунту; этот список только ваш.',
  'Hesabın kalıcı olarak askıya alındı': 'Ваш аккаунт заблокирован навсегда',
  'Hesabın geçici olarak askıya alındı': 'Ваш аккаунт временно заблокирован',
  'Hesabın askıya alındı': 'Ваш аккаунт заблокирован',
  'Sebep': 'Причина',
  'Kalan süre': 'Осталось времени',
  'Süre dolunca hesabın kendiliğinden açılır':
      'По истечении срока аккаунт разблокируется автоматически',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'В это время вы можете читать, но не можете публиковать записи, комментарии и сообщения.',
  'Anladım': 'Понятно',
  'Ayrıntı': 'Подробности',
  '{} dakika': '{} минут',
  'birkaç saniye': 'несколько секунд',
  'Karara itiraz et': 'Обжаловать решение',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Объясните, почему это наказание следует отменить',
  'İtirazını gönder': 'Отправить обжалование',
  'İtirazın incelemede': 'Ваше обжалование на рассмотрении',
  'İtirazın reddedildi': 'Ваше обжалование отклонено',
  'İtirazın alındı, inceleniyor':
      'Обжалование получено и находится на рассмотрении',
  'İtiraz en az 10 karakter olmalı':
      'Обжалование должно содержать не менее 10 символов',
  'Yükleniyor...': 'Загрузка...',
  'Bu bölüme puan ver': 'Оцените эту серию',
  '{} kişi puanladı': 'Оценили: {}',
  'Bölüm izlendi olarak işaretlendi': 'Серия отмечена как просмотренная',
  'Sesli ara': 'Голосовой вызов',
  'Görüntülü ara': 'Видеозвонок',
  'Çalıyor...': 'Звоним...',
  'Bağlanıyor...': 'Соединение...',
  'Cevapla': 'Ответить',
  'Reddet': 'Отклонить',
  'Sessize al': 'Микрофон',
  'Hoparlör': 'Динамик',
  'Kamerayı kapat': 'Выключить камеру',
  'Kamerayı çevir': 'Сменить камеру',
  'Cevap yok': 'Нет ответа',
  'Arama reddedildi': 'Вызов отклонён',
  'Meşgul': 'Занято',
  'Bağlanılamadı': 'Не удалось соединиться',
  'Arama iptal edildi': 'Вызов отменён',
  'Arama geçmişi': 'История звонков',
  'Gelen arama': 'Входящий вызов',
  'Giden arama': 'Исходящий вызов',
  'Cevapsız arama': 'Пропущенный вызов',
  'Arama şu anda kullanılamıyor': 'Звонки сейчас недоступны',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Видеозвонки сейчас отключены, можно позвонить голосом',
  'Bu kullanıcıyı arayamazsın': 'Вы не можете позвонить этому пользователю',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Чтобы звонить, вы должны быть подписаны друг на друга',
  'Bu kullanıcı şu anda aranamıyor':
      'Этому пользователю сейчас нельзя позвонить',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Слишком много пропущенных вызовов. Повторите через {}',
  'Zaten bir aramadasın': 'Вы уже в разговоре',
  'Arama için mikrofon izni gerekiyor': 'Для звонка нужен доступ к микрофону',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'Для видеозвонка нужен доступ к камере и микрофону',
  'Arama başlatılamadı': 'Не удалось начать звонок',
  'Kullanıcı bulunamadı': 'Пользователь не найден',
  'Kendini arayamazsın': 'Нельзя позвонить самому себе',
  'Arama artık geçerli değil': 'Этот вызов больше не действителен',
  'Bu aramanın tarafı değilsin': 'Вы не участник этого вызова',
  'Arama bulunamadı': 'Вызов не найден',
  'Çok fazla istek, biraz bekle': 'Слишком много запросов, подождите',
  'Bağlantı koptu': 'Соединение потеряно',
  'Arama süre sınırına ulaştı': 'Достигнут предел длительности вызова',
  'Arama en fazla 4 saat sürebilir': 'Звонок может длиться не более 4 часов',
  'Arama sona erdi': 'Звонок завершён',
  'Sesli arama': 'Голосовой вызов',
  'Görüntülü arama': 'Видеозвонок',
  'Gelen aramalar': 'Входящие вызовы',
  'Sesli ve görüntülü arama bildirimleri':
      'Уведомления о голосовых и видеозвонках',
  '{} sa': '{} ч',
  'Sesli ve Görüntülü Aramalar': 'Голосовые и видеозвонки',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Содержимое звонков не записывается. Аудио и видео передаются между устройствами со сквозным шифрованием (DTLS-SRTP); наши серверы не могут расшифровать, прослушать или сохранить этот трафик.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Хранятся только метаданные звонка: с кем, в каком направлении, когда и сколько он длился. Эти записи автоматически удаляются через 90 дней.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Если прямое соединение установить не удаётся, аудио и видео проходят через ретранслирующий сервер (TURN) в зашифрованном виде. Ретранслятор тоже не может расшифровать или записать содержимое.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Микрофон используется только во время голосового или видеозвонка, а камера — только во время видеозвонка. По окончании звонка оба отключаются.',
  'Takip ettiğin {} kişi izledi': 'Посмотрели {} человек из твоих подписок',
  'Yorum yaz...': 'Напиши комментарий...',
  'Sıradaki bölüm': 'Следующий эпизод',
  'Doğrulanmış testçi': 'Проверенный тестировщик',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Уведомления о подписках, лайках, ответах, сообщениях и упоминаниях',
  'Sen': 'Ты',
  'Aradığınız kişide sesli arama devre dışı':
      'У этого пользователя голосовые звонки отключены',
  'Aradığınız kişide görüntülü arama devre dışı':
      'У этого пользователя видеозвонки отключены',
  'Sesli aramalara izin ver': 'Разрешить голосовые звонки',
  'Görüntülü aramalara izin ver': 'Разрешить видеозвонки',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Когда выключено, вам не смогут позвонить голосом; звонящий увидит уведомление',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Когда выключено, вам не смогут позвонить по видео; звонящий увидит уведомление',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Голосовые звонки выключены. Включить их можно в Настройки > Конфиденциальность.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Видеозвонки выключены. Включить их можно в Настройки > Конфиденциальность.',
  'Sesli ve görüntülü arama': 'Голосовые и видеозвонки',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Гостевые аккаунты не могут звонить. Создай аккаунт, чтобы пользоваться этим.',
  'Misafir hesaplar aranamaz': 'Гостевым аккаунтам нельзя позвонить',
  'Puan dağılımı': 'Распределение оценок',
  '{} yıldız': '{} звёзд',
  'Yakında gelecek': 'Скоро',
  '{} {} yayınlandı': '{} {} вышел',
  'Yeni bölüm yayınlandı': 'Вышел новый эпизод',
  'Yeni bölümler': 'Новые эпизоды',
  'Geri': 'Назад',
  'Karşılamayı kapat': 'Закрыть приветствие',
  'Adım {} / {}': 'Шаг {} / {}',
  'Hadi başlayalım': 'Начнём',
  'Kaydet ve devam': 'Сохранить и продолжить',
  '{} tanesini ekle': 'Добавить {}',
  'Şimdilik geç': 'Пока пропустить',
  'Doğum tarihin ne zaman?': 'Какая у тебя дата рождения?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Спрашиваем, чтобы показывать подходящее по возрасту и поздравить с днём рождения.',
  'Gün': 'День',
  'Ay': 'Месяц',
  'Yıl': 'Год',
  'Doğum yılımı paylaşmak istemiyorum': 'Не хочу показывать год рождения',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'Дата рождения не показывается в профиле публично. Она нужна только для подходящего по возрасту контента и поздравления с днём рождения.',
  'Ocak': 'Январь',
  'Şubat': 'Февраль',
  'Mart': 'Март',
  'Nisan': 'Апрель',
  'Mayıs': 'Май',
  'Haziran': 'Июнь',
  'Temmuz': 'Июль',
  'Ağustos': 'Август',
  'Eylül': 'Сентябрь',
  'Ekim': 'Октябрь',
  'Kasım': 'Ноябрь',
  'Aralık': 'Декабрь',
  'Verilerini yanında getir': 'Перенеси свои данные',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Если ведёшь историю просмотров в другом приложении, перенеси её сюда. Начинать с нуля не придётся.',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt и Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Выбери ZIP-файл из экспорта — просмотры, оценки и списки перенесутся.',
  'Aktarılıyor...': 'Перенос...',
  'ZIP dosyası seç': 'Выбрать ZIP-файл',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'Спешить некуда: это можно сделать позже в разделе Настройки > Мои данные.',
  'Hangi filmleri izledin?': 'Какие фильмы уже просмотрены?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Здесь самое популярное. Отмечай знакомые — добавим их в просмотренное.',
  'SERİ FİLMLER': 'СЕРИИ ФИЛЬМОВ',
  'Serilerden {} film eklendi': 'Из серий добавлено фильмов: {}',
  'Film listesi yüklenemedi': 'Не удалось загрузить список фильмов',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Этот шаг можно пропустить и добавить всё позже.',
  '{} film izlediklerine eklendi': 'В просмотренное добавлено фильмов: {}',
  'Film serileri': 'Серии фильмов',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Вся серия просмотрена? Добавь её одним касанием.',
  'Seri bulunamadı': 'Серии не найдены',
  'Daha sonra tekrar deneyebilirsin.': 'Можно попробовать позже.',
  '{} film': 'Фильмов: {}',
  'Eklendi': 'Добавлено',
  'Tümünü izledim': 'Всё просмотрено',
  'Peki ya diziler?': 'А что насчёт сериалов?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Отмечай просмотренное — по твоим отметкам подберём похожее.',
  'Dizi listesi yüklenemedi': 'Не удалось загрузить список сериалов',
  'Seçtiklerine benzeyenler': 'Похожее на твой выбор',
  'Her şey hazır': 'Всё готово',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Быстро посмотри, что можно делать в dizi.jpg.',
  'Profilini tamamla': 'Заполни профиль',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'В разделе Настройки можно добавить Био, фото профиля и обложку.',
  'Takvimin seni bekliyor': 'Тебя ждёт Календарь',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'Новые эпизоды твоих сериалов попадают в календарь, а мы пришлём уведомление.',
  'Puan ver, yorum yaz': 'Ставь оценки, пиши комментарии',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Оценивай эпизод за эпизодом, пиши комментарии под завесой спойлера, создавай списки.',
  'Verilerin sende kalır': 'Твои данные остаются твоими',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Данные хранятся только вместе с твоим аккаунтом и не продаются. В разделе Настройки можно скачать их целиком или полностью удалить аккаунт.',
  'Engellenen kullanıcılar': 'Заблокированные пользователи',
  'Engellediğin kişileri gör, engeli kaldır':
      'Посмотреть заблокированных и разблокировать',
  'Engellediğin kimse yok': 'Заблокированных нет',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Заблокировать пользователя можно через меню с тремя точками на странице профиля.',
  '@{} engellensin mi?': 'Заблокировать @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'Вы не сможете видеть публикации, комментарии и профиль друг друга; сообщения и звонки тоже не пройдут. Подписка между вами, если она есть, разорвётся и не вернётся даже после снятия блокировки.',
  'Bu kullanıcıyı engelledin': 'Этот пользователь заблокирован',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Ты не видишь публикации, комментарии и сообщения этого человека, а этот человек не видит твои.',
  '{} yeni bir yapımda: {}': '{} в новом проекте: {}',
  'Favori kişinden yeni yapım': 'Новый проект любимого человека',
  '{} için bildirimler': 'Уведомления: {}',
  'Tüm bildirimler': 'Все уведомления',
  'Uygulamada ve telefonda': 'В приложении и на телефоне',
  'Yalnız uygulama içi': 'Только в приложении',
  'Telefon bildirimi gönderilmez': 'Уведомления на телефон не приходят',
  'Kapalı': 'Выключено',
  'Bu kişi için bildirim yok': 'Уведомлений об этом человеке не будет',
  'Favori kişilerin yeni yapımları': 'Новые проекты любимых людей',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Когда выключено, тебе не смогут позвонить голосом; звонящий увидит уведомление "отключено"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Когда выключено, тебе не смогут позвонить по видео; звонящий увидит уведомление "отключено"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'Моя активность',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'Твои лайки, комментарии и просмотры в одной ленте',
  'Henüz hareketin yok': 'Пока нет активности',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Здесь собирается всё, что ты лайкаешь, комментируешь и смотришь.',
  'Bu süzgeçte hareket yok': 'В этом фильтре нет активности',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Выбери другой тип или вернись к «Все».',
  'Hepsi': 'Все',
  'Puan': 'Оценка',
  'Tepki': 'Реакция',
  'İzleme': 'Просмотр',
  'Durum': 'Статус',
  'Liste': 'Список',
  'Yorum yaptın': 'Комментарий добавлен',
  'Yorumu beğendin': 'Лайк комментарию',
  '{} puan verdin': 'Оценка {}',
  'Tepki verdin': 'Реакция',
  'Listene ekledin': 'Добавлено в список',
  'Takip etmeye başladın': 'Новая подписка',
  '"İzleyeceğim" işaretledin': 'Отмечено «Буду смотреть»',
  '"İzliyorum" işaretledin': 'Отмечено «Смотрю»',
  '"Bitirdim" işaretledin': 'Отмечено «Досмотрено»',
  '"Bıraktım" işaretledin': 'Отмечено «Брошено»',
  'Silinmiş içerik': 'Удалённое содержимое',
  'şimdi': 'сейчас',
  '{} g': '{} д',
  '{} y': '{} г',
  'İstatistiklerim': 'Моя статистика',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Просмотры и лайки твоих публикаций',
  'Henüz gönderin yok': 'У тебя пока нет публикаций',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Как только ты прокомментируешь сериал или фильм, здесь начнут накапливаться просмотры и лайки.',
  'Tüm zamanlar': 'За всё время',
  'Gönderi': 'Публикации',
  'Zaman kırılımı': 'Разбивка по времени',
  'Son {} gün': 'Последние {} дней',
  'En çok görüntülenen gönderilerin': 'Твои самые просматриваемые публикации',
  'En çok beğenilen gönderilerin': 'Твои самые залайканные публикации',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'История просмотров ещё не начала накапливаться; данные за первый день появятся завтра.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'История просмотров накапливается с {} (данных за {} дней), поэтому число за {} дней пока неполное.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.': 'История лайков ведётся с {}.',
  'Bu dönemde gösterilecek gönderi yok.': 'За этот период нет публикаций.',
  'eksik veri': 'неполные данные',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Просмотренные сериалы и фильмы, счётчики просмотров, экранное время и карточка совпадения не будут видны другим в твоём профиле',
  'Takipçi listemi gizle': 'Скрыть список моих подписчиков',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Другие не увидят, кто на тебя подписан; число подписчиков остаётся видимым',
  'Takip ettiklerimi gizle': 'Скрыть мои подписки',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Другие не увидят, на кого ты подписан; число подписок остаётся видимым',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Этот пользователь предпочитает не показывать своих подписчиков.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Этот пользователь предпочитает не показывать свои подписки.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Статистика публикации',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Статистика доступна только для твоих собственных публикаций.',
  'Erişim': 'Охват',
  'Görüntüleyen': 'Зрители',
  'Kaç farklı kişi gördü (son {} gün)':
      'Сколько разных людей увидели (последние {} дн.)',
  'Paylaşım': 'Репосты',
  'Bu gönderiden sonra': 'После этой публикации',
  'Profil ziyareti': 'Переходы в профиль',
  'Yeni takip': 'Новые подписки',
  'İçeriğe tıklama': 'Переходы к контенту',
  'Spoiler perdesini açan': 'Открыли спойлер',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Репосты, переходы в профиль, подписки, переходы к контенту, разбивка по источникам и данные о спойлере накапливаются с {}; более раннее не измерялось.',
  'Zamana yayılmış görüntülenme': 'Просмотры по времени',
  'Görüntülenme nereden geldi': 'Откуда пришли просмотры',
  'Kimler gördü': 'Кто увидел',
  'Günlük veri henüz birikmeye başlamadı.':
      'Ежедневные данные ещё не начали накапливаться.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'Для графика нужны данные минимум за два дня. Данные накапливаются с {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'Больше всего просмотров пришло на {}-й день после публикации: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Ежедневные просмотры накапливаются с {}; более раннее не измерялось.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'Разбивка по источникам начала измеряться только сейчас; у этой публикации ещё нет ни одного размеченного просмотра.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'Разбивка «подписчики/обзор» начала измеряться только сейчас; данных пока нет.',
  'Takip edenler': 'Подписчики',
  'Keşiften gelenler': 'Из обзора',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Страница сериала/фильма',
  'Paylaşılan bağlantı': 'Отправленная ссылка',
  'yeni ölçülüyor': 'новое измерение',
  'Kendi ortalamanla aynı düzeyde': 'На уровне твоего среднего',
  'Kendi ortalamanın %{} üstünde': 'На {}% выше твоего среднего',
  'Kendi ortalamanın %{} altında': 'На {}% ниже твоего среднего',
  'Etkileşim oranı': 'Уровень вовлечённости',
  '(beğeni + yorum) ÷ görüntülenme': '(лайки + комментарии) ÷ просмотры',
  'Toplam görüntülenme': 'Всего просмотров',
  '{} ile {} arasında toplam {} görüntülenme':
      'С {} по {}: всего {} просмотров',
  'İstatistikleri gör': 'Посмотреть статистику',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'Для статистики, которая показывается автору публикации, в виде агрегированных счётчиков хранится: сколько раз и с какой поверхности (лента, профиль, полноэкранная лента, страница сериала/фильма, отправленная ссылка) публикацию просмотрели, был ли зритель в тот момент подписан на автора, переходы из публикации в профиль или к контенту, подписки, оформленные через публикацию, репосты и раскрытие спойлерной шторки. В этих счётчиках нет ни идентификатора пользователя, ни IP-адреса, ни отметки времени; узнать, кто что сделал, невозможно.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'Чтобы можно было посчитать, сколько разных людей увидели публикацию, для каждого зрителя на 90 дней сохраняется необратимая свёртка с ключом (криптографическое сокращение, выведенное из идентификатора пользователя или IP-адреса). Автору публикации показывается только число; личность зрителей не раскрывается ни при каких обстоятельствах.',
};
