/// Otomatik üretilen çeviri haritası (sw).
const Map<String, String> cevirilerSw = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Umeona yote, tunakuonyesha tangu mwanzo',
  'Aktarılacak tanınan veri bulunamadı.':
      'Hakuna data inayotambulika ya kuhamisha.',
  'Arama': 'Tafuta',
  'Aramaya başla': 'Anza kutafuta',
  'Son aramalar': 'Utafutaji wa hivi karibuni',
  'Ayarlar': 'Mipangilio',
  'Bağla': 'Unganisha',
  'Bio': 'Bio',
  'Bitirdim': 'Nimemaliza',
  'Bunları da Beğenebilirsin': 'Huenda Ukapenda Hizi Pia',
  'Bölüm': 'Kipindi',
  'Bıraktım': 'Nimeacha',
  'Dil': 'Lugha',
  'Dil ara...': 'Tafuta lugha...',
  'Dizi': 'Mfululizo',
  'Dizi ve filmlerini takip et': 'Fuatilia mifululizo na filamu zako',
  'Dizi yorumu': 'Maoni ya mfululizo',
  'Dizi, film veya kişi ara...': 'Tafuta mfululizo, filamu au mtu...',
  'Dosya en fazla 30MB olabilir': 'Faili isizidi 30MB',
  'Dosya en fazla {}MB olabilir': 'Faili isizidi {}MB',
  'E-posta': 'Barua pepe',
  'E-posta veya kullanıcı adı': 'Barua pepe au jina la mtumiaji',
  'En az 2 harf yaz': 'Andika angalau herufi 2',
  'Film': 'Filamu',
  'Film yorumu': 'Maoni ya filamu',
  'Fotoğraf / video ekle': 'Ongeza picha / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Picha au GIF — picha ya wasifu na jalada',
  'Giriş Yap': 'Ingia',
  'Gönder': 'Tuma',
  'Gönderildi': 'Imetumwa',
  'Haftanın Dizileri': 'Mifululizo ya Wiki Hii',
  'Haftanın Filmleri': 'Filamu za Wiki Hii',
  'Henüz izleme kaydın yok': 'Bado huna historia ya kutazama',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Bado huna orodha — tengeneza kwenye kichupo cha Wasifu.',
  'Henüz yorum yok.': 'Hakuna maoni bado.',
  'Hesabın bağlandı!': 'Akaunti yako imeunganishwa!',
  'Hesabın yok mu? Kayıt ol': 'Huna akaunti? Jisajili',
  'Hesabını Bağla': 'Unganisha Akaunti Yako',
  'Hesap Oluştur': 'Fungua Akaunti',
  'Kapak resmi ekle': 'Ongeza picha ya jalada',
  'Kaydet': 'Hifadhi',
  'Kendinden bahset...': 'Jieleze kidogo...',
  'Keşfet': 'Gundua',
  'Kimseyi takip etmiyor': 'Hafuati mtu yeyote',
  'Kişi ara': 'Tafuta mtu',
  'Kişi yorumu': 'Maoni ya mtu',
  'Konuk Oyuncular': 'Waigizaji Wageni',
  'Kullanıcı adı (küçük harf)': 'Jina la mtumiaji (herufi ndogo)',
  'Kullanıcı adı ara...': 'Tafuta jina la mtumiaji...',
  'Liste adı': 'Jina la orodha',
  'Listeye Ekle': 'Ongeza kwenye Orodha',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Uko kwenye akaunti ya mgeni — unganisha na barua pepe yako, usipoteze data zako!',
  'Misafir olarak devam et': 'Endelea kama mgeni',
  'Oluştur': 'Tengeneza',
  'Oyuncular': 'Waigizaji',
  'Profil': 'Wasifu',
  'Profil kaydedildi': 'Wasifu umehifadhiwa',
  'Puanla': 'Kadiria',
  'Puanı Sil': 'Futa Alama',
  'Puanın': 'Alama Yako',
  'Sezonlar': 'Misimu',
  'Sunucu hatası ({})': 'Hitilafu ya seva ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Maoni ya S{}E{}',
  'Takibi Bırak': 'Acha Kufuata',
  'Takip': 'Anafuata',
  'Takip Edilenler': 'Wanaofuatwa',
  'Takip Et': 'Fuata',
  'Takipçi': 'Mfuasi',
  'Takipçi yok': 'Hakuna wafuasi',
  'Takipçiler': 'Wafuasi',
  'Takvim': 'Kalenda',
  'Tamam': 'Sawa',
  'Tekrar Dene': 'Jaribu Tena',
  'Tekrar dene': 'Jaribu tena',
  'Toplam İzleme Süresi': 'Jumla ya muda wa kutazama',
  'Tüm Zamanların En İyileri': 'Bora Zaidi za Wakati Wote',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da TV Time / Letterboxd ZIP'ini içe aktar.":
      'Pakua data zako zote (kutazama, alama, maoni, orodha) kama ZIP inayooana na TV Time, au leta ZIP ya TV Time / Letterboxd.',
  'Tümünü Kaldır': 'Ondoa Zote',
  'Tümünü İzledim': 'Nimetazama Zote',
  'Türk Dizileri': 'Mifululizo ya Kituruki',
  'Veri içe aktar (.zip)': 'Leta data (.zip)',
  'Verilerim': 'Data Zangu',
  'Verilerimi dışa aktar (e-posta)': 'Hamisha data zangu (barua pepe)',
  'Verilerini dışa aktar': 'Hamisha data zako',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Hakuna kipindi kijacho.\nWeka mfululizo kwenye hali ya "Ninatazama" kutoka ukurasa wake wa maelezo, kisha fuatilia vipindi vipya hapa.',
  'Yapımları': 'Kazi Zake',
  'Yeni Diziler': 'Mifululizo Mipya',
  'Yeni Liste': 'Orodha Mpya',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Jina jipya la mtumiaji (hiari)',
  'Yorum': 'Maoni',
  'Yorumunu yaz...': 'Andika maoni yako...',
  'Zaten hesabın var mı? Giriş yap': 'Tayari una akaunti? Ingia',
  'ort. {}': 'wastani {}',
  'takip': 'anafuata',
  'takipçi': 'wafuasi',
  '{} / {} bölüm': 'vipindi {} / {}',
  '{} TMDB': '{} TMDB',
  '{} ay': 'miezi {}',
  '{} ay~tekil': 'mwezi {}',
  '{} bölüm izlendi': 'vipindi {} vimetazamwa',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': 'dakika {}',
  '{} dk~tekil': 'dakika {}',
  '{} gün': 'siku {}',
  '{} gün~tekil': 'siku {}',
  '{} içerik': 'maudhui {}',
  '{} içerik · otomatik': 'maudhui {} · kiotomatiki',
  '{} kayıt atlandı (eşleşmedi).': 'Rekodi {} zimerukwa (hazikulingana).',
  '{} saat': 'saa {}',
  '{} saat~tekil': 'saa {}',
  '{} sezon': 'misimu {}',
  '{} yıl': 'miaka {}',
  '{} yıl~tekil': 'mwaka {}',
  '{}. Bölüm': 'Kipindi cha {}',
  '{}. Sezon': 'Msimu wa {}',
  'Çıkış Yap': 'Toka',
  'Ülke': 'Nchi',
  'Ülke ara...': 'Tafuta nchi...',
  'Ülke seç': 'Chagua nchi',
  'İlk yorumu sen yaz!': 'Kuwa wa kwanza kutoa maoni!',
  'İncelemeler': 'Mapitio',
  'İncelemen (isteğe bağlı)': 'Mapitio yako (hiari)',
  'İptal': 'Ghairi',
  'İzlediklerim': 'Nilizotazama',
  'İzledim': 'Nimetazama',
  'İzledin': 'Umetazama',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Historia yako ya kutazama na orodha zako zitabaki salama; sasa unaweza kuingia kutoka kifaa chochote.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Historia yako ya kutazama, alama, maoni na orodha zako zitatumwa kama ZIP kwenye barua pepe yako iliyosajiliwa.',
  'İzleyeceğim': 'Nitatazama',
  'İzliyorum': 'Ninatazama',
  'İçe aktarım tamamlandı': 'Uhamishaji umekamilika',
  'Şifre': 'Nenosiri',
  '• profil bilgisi': '• taarifa za wasifu',
  '• {} kitaplık kaydı': '• maingizo ya maktaba {}',
  '• {} favori': '• vipendwa {}',
  '• {} izleme kaydı': '• rekodi za kutazama {}',
  '• {} liste': '• orodha {}',
  '• {} puan': '• alama {}',
  '• {} yorum': '• maoni {}',
  '{}+ yapım': 'Kazi {}+',
  'Yorumlar': 'Maoni',
  'Yorumlar ({})': 'Maoni ({})',
  'Yorumları ({})': 'Maoni yake ({})',
  'Listelerim': 'Orodha Zangu',
  'Nereden izledin?': 'Ulitazama wapi?',
  'Diziye git': 'Nenda kwenye kipindi',
  'TV / Kanal': 'TV / Kituo',
  'Sinema': 'Sinema',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Nyingine',
  'Akış': 'Mlisho',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Mlisho wako ni tupu.\nWatu wakitoa maoni kwenye vipindi na filamu unazotazama, yataonekana hapa.',
  'Listeleri ({})': 'Orodha zake ({})',
  'Liste boş.': 'Orodha hii ni tupu.',
  'Yanıtla': 'Jibu',
  '@{} kullanıcısına yanıt veriyorsun': 'Unamjibu @{}',
  'İzlediğim Diziler ({})': 'Vipindi nilivyotazama ({})',
  'İzlediğim Filmler ({})': 'Filamu nilizotazama ({})',
  'Tümünü gör': 'Ona zote',
  'Bildirimler': 'Arifa',
  'Henüz bildirim yok': 'Hakuna arifa bado',
  '@{} yorumuna yanıt verdi': '@{} alijibu maoni yako',
  '@{} yorumunu beğendi': '@{} alipenda maoni yako',
  '@{} seni takip etti': '@{} alikufuata',
  '@{} sana mesaj gönderdi': '@{} alikutumia ujumbe',
  'Mesajlar': 'Jumbe',
  'Mesaj': 'Ujumbe',
  'Mesaja eklenecek': 'Itaongezwa kwenye ujumbe',
  'Mesajını yaz...': 'Andika ujumbe...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Hakuna gumzo bado.\nFungua wasifu utume ujumbe.',
  'Şifreni mi unuttun?': 'Umesahau nenosiri?',
  'Şifreyi Sıfırla': 'Weka upya nenosiri',
  'E-postadaki kod': 'Msimbo kutoka barua pepe',
  'Yeni şifre': 'Nenosiri jipya',
  'Sana Özel': 'Kwa ajili yako',
  '{} özetin': 'Muhtasari wako wa {}',
  'Yıllık izleme istatistiklerin': 'Takwimu zako za mwaka',
  'Rozetler': 'Beji',
  'Verdiğin puan': 'Ukadiriaji uliotoa',
  'Ortalama puanın': 'Wastani wa ukadiriaji',
  'En çok izlediğin diziler': 'Vipindi ulivyotazama zaidi',
  'İlk Bölüm': 'Kipindi cha Kwanza',
  '100 Bölüm': 'Vipindi 100',
  '1000 Bölüm': 'Vipindi 1000',
  'İlk Film': 'Filamu ya Kwanza',
  '50 Film': 'Filamu 50',
  'İlk Yorum': 'Maoni ya Kwanza',
  '25 Yorum': 'Maoni 25',
  '10 Puan': 'Ukadiriaji 10',
  'İlk Takipçi': 'Mfuasi wa Kwanza',
  '10 Dizi Bitirdin': 'Umemaliza Vipindi 10',
  'İzlemeyi Bıraktım': 'Nimeacha kutazama',
  'İzlediği Diziler ({})': 'Vipindi alivyotazama ({})',
  'İzlediği Filmler ({})': 'Filamu alizotazama ({})',
  '500 Bölüm': 'Vipindi 500',
  '5000 Bölüm': 'Vipindi 5000',
  '10 Film': 'Filamu 10',
  '100 Film': 'Filamu 100',
  '100 Yorum': 'Maoni 100',
  '50 Puan': 'Ukadiriaji 50',
  '100 Puan': 'Ukadiriaji 100',
  '10 Takipçi': 'Wafuasi 10',
  '50 Takipçi': 'Wafuasi 50',
  '25 Dizi Bitirdin': 'Amemaliza vipindi 25',
  '50 Dizi Bitirdin': 'Amemaliza vipindi 50',
  '10 Beğeni': 'Vipendwa 10',
  '100 Beğeni': 'Vipendwa 100',
  'yazıyor...': 'anaandika...',
  'ses kaydediyor...': 'anarekodi sauti...',
  'Profil düzeni': 'Mpangilio wa wasifu',
  'Konumla ve kırp': 'Weka mahali na ukate',
  'Listeye eklendi': 'Imeongezwa kwenye orodha',
  'Listeyi sil?': 'Ufute orodha?',
  'Sil': 'Futa',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Kichwa hiki kitawekwa kama hakijatazamwa na kuondolewa kwenye orodha zako.',
  'Gelecek bölüm bugün': 'Kipindi kijacho leo',
  'Gelecek bölüm {} gün sonra': 'Kipindi kijacho baada ya siku {}',
  'Tema': 'Mandhari',
  'Sistem': 'Mfumo',
  'Koyu': 'Giza',
  'Açık': 'Mwanga',
  'İzleyenler': 'Watazamaji',
  'Yorumunu yaz... (@ ile etiketle)': 'Andika maoni yako... (@ kutambulisha)',
  '@{} bir yorumda seni etiketledi': '@{} amekutambulisha kwenye maoni',
  'Mesajı sil': 'Futa ujumbe',
  'Mesaj silinemedi': 'Ujumbe haukuweza kufutwa',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Kiungo si sahihi au ukurasa haukupatikana',
  "Keşfet'e dön": 'Rudi kwenye Gundua',
  'Düzenle': 'Hariri',
  'Mesajı düzenle': 'Hariri ujumbe',
  'Yanıtlanıyor': 'Anajibu',
  'düzenlendi': 'imehaririwa',
  'Fotoğraf': 'Picha',
  'Video': 'Video',
  'İçerik': 'Maudhui',
  'çevrimiçi': 'mtandaoni',
  'son görülme {} dk önce': 'alionekana dakika {} zilizopita',
  'son görülme {} saat önce': 'alionekana saa {} zilizopita',
  'son görülme {} gün önce': 'alionekana siku {} zilizopita',
  'Yorumlar yüklenemedi': 'Imeshindwa kupakia maoni',
  'Favori': 'Kipendwa',
  'Listeye ekle': 'Ongeza kwenye orodha',
  'İçerik paylaş': 'Shiriki maudhui',
  'Kapat': 'Funga',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Kila unachokiweka kama kimetazamwa hukusanywa hapa.',
  'Henüz sohbetin yok': 'Bado hakuna mazungumzo',
  'Bir profile girip mesaj gönderebilirsin.': 'Fungua wasifu na tuma ujumbe.',
  'Listeyi sil': 'Futa orodha',
  'Puan kaydedilemedi': 'Ukadiriaji haukuweza kuhifadhiwa',
  'Nerede İzlenir': 'Wapi Kutazama',
  'Abonelik': 'Kujiunga',
  'Kirala': 'Kodisha',
  'Satın al': 'Nunua',
  'Devam et': 'Endelea',
  'Şikayet et': 'Ripoti',
  'Engelle': 'Zuia',
  'Engeli kaldır': 'Ondoa uzuiaji',
  'Kullanıcı engellendi': 'Mtumiaji amezuiwa',
  'Engel kaldırıldı': 'Uzuiaji umeondolewa',
  'Şikayet sebebi': 'Sababu ya ripoti',
  'Spam veya yanıltıcı': 'Barua taka au kupotosha',
  'Taciz veya nefret söylemi': 'Unyanyasaji au matamshi ya chuki',
  'Uygunsuz / cinsel içerik': 'Isiyofaa / maudhui ya ngono',
  'Şiddet veya tehlikeli içerik': 'Vurugu au maudhui hatari',
  'Telif hakkı ihlali': 'Ukiukaji wa hakimiliki',
  'Şikayetin alındı, teşekkürler': 'Ripoti yako imepokelewa, asante',
  'Hesabımı Sil': 'Futa Akaunti Yangu',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Akaunti yako na data yako yote (historia, ukadiriaji, maoni, orodha, ujumbe) itafutwa kabisa. Hii haiwezi kutenduliwa.',
  'Şifreni gir': 'Weka nywila yako',
  'Hesabımı kalıcı sil': 'Futa akaunti yangu kabisa',
  'Sesli mesaj': 'Ujumbe wa sauti',
  'Görüldü': 'Imeonwa',
  'Gönderi': 'Chapisho',
  'Ses gönderilemedi': 'Ujumbe wa sauti haukutumwa',
  'Kaydediliyor…': 'Inarekodi…',
  'Ses oynatılamadı': 'Sauti haikuweza kuchezwa',
  'Oynat': 'Cheza',
  'Fragmanı oynat': 'Cheza trela',
  'Altyazıyı aç': 'Washa manukuu',
  'Altyazıyı kapat': 'Zima manukuu',
  '10 saniye ileri': 'Sogeza mbele sekunde 10',
  '10 saniye geri': 'Rudi nyuma sekunde 10',
  'Duraklat': 'Sitisha',
  'Liste görünümü': 'Mwonekano wa orodha',
  'Takvim görünümü': 'Mwonekano wa kalenda',
  'Önceki ay': 'Mwezi uliopita',
  'Sonraki ay': 'Mwezi ujao',
  'Bu gün bölüm yok': 'Hakuna vipindi siku hii',
  'Gizlilik Politikası': 'Sera ya Faragha',
  'Son güncelleme: {}': 'Sasisho la mwisho: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Sera hii inaeleza data gani hukusanywa, jinsi inavyotumika na haki zako ni zipi unapotumia programu ya dizi.jpg na tovuti ya dizijpg.com.',
  'Topladığımız Veriler': 'Data Tunayokusanya',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Akaunti: anwani ya barua pepe, jina la mtumiaji na nenosiri. Manenosiri huhifadhiwa kama heshi isiyoweza kurejeshwa; akaunti za mgeni zinaweza kutumika bila barua pepe.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Wasifu: taarifa unazochagua kuongeza, kama avatari, picha ya jalada, wasifu mfupi na nchi.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Matumizi: historia yako ya kutazama, ukadiriaji, maoni, orodha, riaksheni na vipendwa.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Ujumbe: ujumbe wako wa maandishi, picha na sauti huhifadhiwa kwenye seva zetu. Ujumbe haujasimbwa kutoka mwanzo hadi mwisho; hukaguliwa tu kwa madhumuni ya usimamizi endapo utaripotiwa.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Media zilizopakiwa: picha, GIF, video na rekodi za sauti unazoongeza kwenye wasifu, maoni na ujumbe wako.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Kiufundi: anwani ya IP, mahali pa makadirio (kiwango cha nchi/jiji), jukwaa la kifaa, toleo la programu na kumbukumbu za hitilafu. Hizi huhifadhiwa kwa usalama na kurekebisha matatizo.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Takwimu za matumizi: aina ya kifaa, mfumo wa uendeshaji na kivinjari vinavyotumika kuingia huongezwa kwenye vihesabu vya jumla vya kila siku kama makundi mapana; kitambulisho cha kivinjari chenyewe hakihifadhiwi na idadi hizi haziwezi kuunganishwa na mtu yeyote.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Arifa: kwa arifa za papo hapo tunahifadhi tokeni ya kifaa chako na lugha uliyochagua. Unaweza kuzima arifa wakati wowote kwenye mipangilio ya kifaa.',
  'Verileri Nasıl Kullanırız': 'Jinsi Tunavyotumia Data Yako',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Tunatumia data yako tu kutoa huduma, kulinda akaunti yako, kutuma arifa, kurekebisha hitilafu na kuzuia matumizi mabaya. Hatuuzi data yako wala kuishiriki na yeyote kwa madhumuni ya matangazo.',
  'Çerezler ve Yerel Depolama': 'Vidakuzi na Hifadhi ya Ndani',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Tunatumia hifadhi ya ndani tu kukuweka umeingia na kukumbuka mapendeleo kama lugha na mandhari. Hakuna vidakuzi vya matangazo wala vya ufuatiliaji.',
  'Üçüncü Taraf Hizmetler': 'Huduma za Wahusika Wengine',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Data ya vipindi na filamu hutoka TMDB, taarifa za majukwaa ya kutiririsha kutoka JustWatch. Arifa za papo hapo huwasilishwa kupitia Google Firebase, na trafiki ya tovuti hulindwa na Cloudflare. Huduma hizi zinafuata sera zao za faragha.',
  'Saklama ve Silme': 'Uhifadhi na Ufutaji',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Data yako huhifadhiwa muda wote akaunti yako ipo. Kupitia "Futa Akaunti Yangu" kwenye mipangilio unaweza kufuta akaunti kabisa; data yako hufutwa mara moja, na nakala kwenye hifadhi rudufu ndani ya siku 14 zaidi. Kumbukumbu za hitilafu hufutwa kiotomatiki baada ya siku 30.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'Unaweza kuhamisha data yako kama ZIP kutoka kwenye mipangilio; jalada hutumwa kwa anwani yako ya barua pepe.',
  'Güvenlik': 'Usalama',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Data husafirishwa kupitia miunganisho iliyosimbwa (HTTPS) na kuhifadhiwa kwenye seva zenye ufikiaji mdogo.',
  'Çocukların Gizliliği': 'Faragha ya Watoto',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg haikusudiwi watoto walio chini ya miaka 13.',
  'Hakların': 'Haki Zako',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Chini ya KVKK na GDPR una haki ya kufikia, kusahihisha, kufuta na kuhamisha data yako. Kwa haya tuandikie: {}',
  'Değişiklikler': 'Mabadiliko',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Sera hii ikibadilika, toleo jipya litachapishwa kwenye ukurasa huu na tarehe itasasishwa.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Kwa kujisajili unakubali {}.',
  'Kullanıcılar': 'Watumiaji',
  'Fotoğrafı değiştir': 'Badilisha picha',
  'Yeniden konumlandır': 'Panga upya',
  'Bir şeyler ters gitti': 'Hitilafu imetokea',
  'Sosyal Bağlantılar': 'Viungo vya Mitandao',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Viungo 3 pekee huonyeshwa kwenye wasifu wako.',
  'Platform seç': 'Chagua jukwaa',
  'Kullanıcı adın': 'Jina lako la mtumiaji',
  'Ekle': 'Ongeza',
  'Kaldır': 'Ondoa',
  'Kopyalandı: {}': 'Imenakiliwa: {}',
  'Geçersiz kullanıcı adı': 'Jina la mtumiaji si sahihi',
  'Bağlantı ekle': 'Ongeza kiungo',
  'Spoiler olabilir — dokun ve gör': 'Inaweza kuwa na spoiler — gusa kuona',
  'Beğeni': 'Zilizopendwa',
  'beğeni': 'zilizopendwa',
  'Beğen': 'Penda',
  'Görüntülenme': 'Mionekano',
  'görüntülenme': 'mionekano',
  'Tam ekran': 'Skrini nzima',
  'Arama başarısız': 'Utafutaji umeshindwa',
  'Sonuç bulunamadı': 'Hakuna matokeo',
  'Dizi ve Filmler': 'Tamthilia na Filamu',
  'Kişiler': 'Watu',
  'Ana Sayfa': 'Mwanzo',
  'Paylaş': 'Shiriki',
  'Yanıtlar': 'Majibu',
  'Yaklaşan Bölümler': 'Vipindi Vijavyo',
  'Yetişme Listesi': 'Orodha ya Kufikia',
  'Şunu mu demek istedin': 'Ulimaanisha',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — gusa ili uone',
  'uyum': 'ulinganifu',
  'Uyum': 'Ulinganifu',
  '{} ortak dizi': 'vipindi {} sawa',
  '{} ortak film': 'filamu {} sawa',
  'Bildirim Tercihleri': 'Mapendeleo ya arifa',
  'Beğeniler': 'Mapendo',
  'Yeni takipçiler': 'Wafuasi wapya',
  'Etiketlenmeler': 'Kutajwa',
  'Yeniden izledim': 'Imetazamwa tena',
  '{}. kez izlendi': 'Imetazamwa mara {}',
  'Gönderi bulunamadı': 'Chapisho halikupatikana',
  'Gözat': 'Vinjari',
  'Diziler': 'Vipindi',
  'Filmler': 'Filamu',
  'Tümü': 'Zote',
  'Farklı bir tür seç.': 'Jaribu aina nyingine.',
  'Gizlilik': 'Faragha',
  'İzlediklerimi gizle': 'Ficha nilichotazama',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Series na filamu ulizotazama hazitaonekana kwenye wasifu wako',
  'Yorumlarımı gizle': 'Ficha maoni yangu',
  'Profilinde yorumların görünmez':
      'Maoni yako hayataonekana kwenye wasifu wako',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Unaweza kuficha series au filamu moja kwa kutumia kibonye "Ficha kwenye wasifu wangu" kwenye ukurasa wake.',
  'Geri Bildirim': 'Mrejesho',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Andika maoni na mapendekezo yako kuhusu programu...',
  'Teşekkürler! Geri bildirimin alındı.': 'Asante! Mrejesho wako umepokelewa.',
  'Profilimde gizle': 'Ficha kwenye wasifu wangu',
  'Yorumları': 'Maoni yake',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Mtumiaji huyu bado hajatazama chochote.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Mtumiaji huyu anapendelea kuficha maoni yake.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Data: JustWatch',
  'Web Sitesi': 'Tovuti',
  'Diğer uygulamalar': 'Programu nyingine',
  'Bağlantıyı kopyala': 'Nakili kiungo',
  'Henüz kimseyi takip etmiyorsun.': 'Bado hujamfuata mtu yeyote.',
  'Çevir': 'Tafsiri',
  'Çeviri şu an yapılamadı': 'Tafsiri haipatikani kwa sasa',
  'Bağlantı açılamadı': 'Kiungo hakikuweza kufunguliwa',
  'Orijinali göster': 'Onyesha asili',
  'Çeviriyi göster': 'Onyesha tafsiri',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Mwezi huu hakuna vipindi vyenye tarehe ya kurushwa iliyotangazwa. Tarehe hutangazwa wiki chache kabla na zitaonekana hapa.',
  'devamı': 'zaidi',
  'Google ile devam et': 'Endelea na Google',
  'Google girişi başarısız': 'Kuingia kwa Google hakukufaulu',
  'Veri tasarrufu': 'Kuokoa data',
  'Wi-Fi ağında veri tasarrufu': 'Kuokoa data kwenye Wi-Fi',
  'Mobil veride veri tasarrufu': 'Kuokoa data kwenye data ya simu',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Ikiwashwa, picha hazipakuliwi mapema; inapakia tu picha unayoitazama.',
  'Çocuk güvenliği': 'Usalama wa watoto',
  'Türk Filmleri': 'Filamu za Kituruki',
  'En Yüksek Puanlı Filmler': 'Filamu zenye ukadiriaji wa juu',
  'En Yüksek Puanlı Diziler': 'Misururu yenye ukadiriaji wa juu',
  'En Çok İzlenen Filmler': 'Filamu zilizotazamwa zaidi',
  'Popüler Diziler': 'Misururu maarufu',
  'En Çok Kazanan Filmler': 'Filamu zilizoingiza mapato zaidi',
  'Kült Filmler': 'Filamu za kipekee',
  'Yeni Filmler': 'Filamu mpya',
  'Yorum yap': 'Toa maoni',
  'Henüz yorum yok': 'Bado hakuna maoni',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Maoni unayoandika kuhusu misururu na filamu hukusanywa hapa.',
  'GIF ekle': 'Ongeza GIF',
  'İlk yorumu sen yaz': 'Kuwa wa kwanza kutoa maoni',
  'Video altyazıları': 'Manukuu ya video',
  'Videolarda altyazı göster': 'Onyesha manukuu kwenye video',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Sentensi inayozungumzwa kwenye video imeandikwa kwenye skrini. Nakala ni tafsiri: Kiingereza katika hotuba ya Kituruki, Kituruki kwa lugha zingine.',
  'Güncelleme gerekli': 'Sasisho linahitajika',
  'Yeni sürüm var': 'Toleo jipya linapatikana',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Sakinisha toleo jipya la dizi.jpg ili kuendelea.',
  'Güncelle': 'Sasisha',
  'Daha sonra': 'Baadaye',
  'Takvim güncelleniyor': 'Inasasisha kalenda',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Kalenda haikuweza kusasishwa, orodha ya zamani inaonyeshwa',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Baadhi ya mfululizo hazikupakiwa, orodha inaweza kuwa pungufu',
  'Yenile': 'Onyesha upya',
  'Devam etmek için giriş yap': 'Ingia ili kuendelea',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Akaunti ya bure inatosha kukadiria, kutoa maoni na kujenga maktaba yako.',
  'Şimdi değil': 'Si sasa',
  'Yorum yazmak için giriş yap': 'Ingia ili kuandika maoni',
  'Kişilere göndermek için giriş yap': 'Ingia ili kutuma kwa watu',
  'Beğenenler': 'Waliopenda',
  'Henüz beğeni yok': 'Bado hakuna anayependa',
  'Bu gönderiyi ilk beğenen sen ol': 'Kuwa wa kwanza kupenda chapisho hili',
  'Bu gönderiye yanıt': 'Jibu la chapisho hili',
  'Spoiler içeren gönderi': 'Chapisho lenye spoila',
  'Görsel gönderi': 'Chapisho la picha',
  'Bu yorumu profilimde gizle': 'Ficha maoni haya kwenye wasifu wangu',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Maoni yanabaki kwenye ukurasa wa msululu na filamu',
  'Bu yorumu sil': 'Futa maoni haya',
  'Yorum profilinde gizlendi': 'Maoni yamefichwa kwenye wasifu wako',
  'Geri al': 'Tendua',
  'Yorum silinsin mi?': 'Ufute maoni haya?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Maoni haya yatafutwa kabisa kila mahali. Haiwezi kutenduliwa.',
  'Yorum silindi': 'Maoni yamefutwa',
  'Yorum profilinde tekrar görünüyor':
      'Maoni yanaonekana tena kwenye wasifu wako',
  'Gizlenen yorumun yok': 'Huna maoni yaliyofichwa',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Maoni unayoyaficha kwa kubonyeza na kushikilia chapisho kwenye kichupo cha Maoni cha wasifu wako hukusanyika hapa.',
  'Gizlenen yorumlar': 'Maoni yaliyofichwa',
  'Gönderiye git': 'Nenda kwenye chapisho',
  'Tekrar göster': 'Onyesha tena',
  'Yanıtlarımı gizle': 'Ficha majibu yangu',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Majibu unayoandika kwenye machapisho ya wengine yanaonekana kwako pekee',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Onyesha tena maoni uliyoyaficha kwenye wasifu',
  'Sıralama': 'Panga',
  'Önerilen': 'Inapendekezwa',
  'Kronolojik': 'Kwa mpangilio',
  'Gelen mesaj istekleri': 'Maombi ya ujumbe yaliyofika',
  'Mesaj isteğin yok': 'Huna maombi ya ujumbe',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Ujumbe kutoka kwa watu usiowafuata unaonekana hapa.',
  'Çevrimiçi durumumu gizle': 'Ficha hali yangu ya mtandaoni',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Wengine hawataona hali yako ya mtandaoni wala muda wa mwisho kuonekana katika ujumbe',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Mmoja wa watumiaji wetu wa kwanza. Maoni yake yalisaidia programu kuwa ilivyo leo.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Wewe ni mmoja wa watumiaji wetu wa kwanza. Maoni yako yalisaidia programu kuwa ilivyo leo.',
  'İleri': 'Endelea',
  'Önceki': 'Iliyotangulia',
  'Sonraki': 'Ifuatayo',
  'Seçilen dosya okunamadı': 'Faili uliyochagua haikuweza kusomwa',
  'Video açılamadı': 'Video haikuweza kufunguliwa',
  'En fazla {} medya seçebilirsin': 'Unaweza kuchagua midia {} kwa juu zaidi',
  'Hiçbir medya yüklenemedi': 'Hakuna midia iliyopakiwa',
  'Seçimi kaldır': 'Ondoa uteuzi',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'Kwenye maoni moja unaweza kupakia jumla ya MB {}',
  '{} dosya okunamadı': 'Faili {} hazikusomeka',
  '{} medya eklendi, {} yüklenemedi': 'Midia {} imeongezwa, {} imeshindwa',
  'Kırp': 'Punguza',
  'Çiz': 'Chora',
  'Metin': 'Maandishi',
  'Emoji': 'Emoji',
  'Yinele': 'Rudia',
  'Daha fazla': 'Zaidi',
  'Hazırlanıyor…': 'Inaandaliwa…',
  'Düzenlemeden çık?': 'Utoke kwenye kuhariri?',
  'Yaptığın değişiklikler kaybolacak.': 'Mabadiliko uliyofanya yatapotea.',
  'Çık': 'Toka',
  'Serbest çizim': 'Chora huru',
  'Ok': 'Mshale',
  'Dikdörtgen': 'Mstatili',
  'Daire': 'Duara',
  'Bulanıklaştır': 'Fifisha',
  'Pikselleştir': 'Fanya pikseli',
  'Silgi': 'Kifutio',
  'Çizgi kalınlığı': 'Unene wa mstari',
  'Saydamlık': 'Uwazi',
  'Dolgu': 'Jaza',
  'Renk': 'Rangi',
  'Döndür': 'Zungusha',
  'Yansıt': 'Geuza',
  'Oran': 'Uwiano',
  'Sıfırla': 'Weka upya',
  'Serbest': 'Huru',
  'Metin yaz...': 'Andika maandishi...',
  'Hizala': 'Panga',
  'Arka plan': 'Mandharinyuma',
  'Emoji ara...': 'Tafuta emoji...',
  'Son kullanılanlar': 'Za hivi karibuni',
  'İfadeler ve insanlar': 'Vicheko na watu',
  'Hayvanlar ve doğa': 'Wanyama na maumbile',
  'Yiyecek ve içecek': 'Chakula na vinywaji',
  'Etkinlikler': 'Shughuli',
  'Seyahat ve yerler': 'Safari na maeneo',
  'Nesneler': 'Vitu',
  'Semboller': 'Alama',
  'Bayraklar': 'Bendera',
  'Görseli düzenle': 'Hariri picha',
  'Düzenlendi': 'Imehaririwa',
  'Düzenlenemedi': 'Haikuweza kuhaririwa',
  'Düzenlenen görsel çok büyük': 'Picha iliyohaririwa ni kubwa mno',
  'Videoyu düzenle': 'Hariri video',
  'Sesi kapat': 'Zima sauti',
  'Sesi aç': 'Washa sauti',
  'İptal ediliyor…': 'Inaghairi…',
  'Bu biraz sürebilir': 'Hii inaweza kuchukua muda',
  'Video çok büyük': 'Video ni kubwa mno',
  'Video hazırlanamadı': 'Video haikuweza kuandaliwa',
  'Başlangıç': 'Mwanzo',
  'Bitiş': 'Mwisho',
  'En çok {} saniye seçebilirsin': 'Unaweza kuchagua hadi sekunde {}',
  'Dosya en fazla {} MB olabilir': 'Faili inaweza kuwa hadi {} MB',
  'Medya ekle': 'Ongeza media',
  'Seçili medya kalmadı': 'Hakuna media iliyochaguliwa',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Chagua picha au video ya kuongeza kwenye maoni yako.',
  'Medya seç': 'Chagua media',
  'Daha fazla ekle': 'Ongeza zaidi',
  'Medya seçilemedi': 'Imeshindwa kuchagua media',
  'Favori oyuncular': 'Waigizaji pendwa',
  'Henüz favori oyuncun yok': 'Bado hakuna waigizaji pendwa',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Fungua ukurasa wa mwigizaji na ugonge moyo juu kulia ili kumuongeza hapa.',
  '{} yapımdan {} tanesini izledin': 'Umetazama {} kati ya {}',
  'izledin': 'umetazama',
  'İzlemedin': 'Hujatazama',
  'Yapım bulunamadı': 'Hakuna kazi zilizopatikana',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Mtu huyu hana mfululizo au filamu za kuorodhesha.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Historia yako imefungwa kwenye akaunti yako; orodha hii ni yako pekee.',
  'Hesabın kalıcı olarak askıya alındı': 'Akaunti yako imesimamishwa kabisa',
  'Hesabın geçici olarak askıya alındı': 'Akaunti yako imesimamishwa kwa muda',
  'Hesabın askıya alındı': 'Akaunti yako imesimamishwa',
  'Sebep': 'Sababu',
  'Kalan süre': 'Muda uliobaki',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Akaunti yako itafunguliwa yenyewe muda utakapoisha',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'Katika kipindi hiki unaweza kuendelea kusoma, lakini huwezi kuchapisha, kutoa maoni au kutuma ujumbe.',
  'Anladım': 'Nimeelewa',
  'Ayrıntı': 'Maelezo',
  '{} dakika': 'Dakika {}',
  'birkaç saniye': 'sekunde chache',
  'Karara itiraz et': 'Kata rufaa dhidi ya uamuzi',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Eleza kwa nini adhabu hii iondolewe',
  'İtirazını gönder': 'Tuma rufaa yako',
  'İtirazın incelemede': 'Rufaa yako inapitiwa',
  'İtirazın reddedildi': 'Rufaa yako imekataliwa',
  'İtirazın alındı, inceleniyor': 'Rufaa yako imepokelewa na inapitiwa',
  'İtiraz en az 10 karakter olmalı': 'Rufaa lazima iwe na angalau herufi 10',
  'Yükleniyor...': 'Inapakia...',
  'Bu bölüme puan ver': 'Kadiria kipindi hiki',
  '{} kişi puanladı': 'Watu {} wamekadiria',
  'Bölüm izlendi olarak işaretlendi':
      'Kipindi kimewekwa alama kuwa kimetazamwa',
  'Sesli ara': 'Simu ya sauti',
  'Görüntülü ara': 'Simu ya video',
  'Çalıyor...': 'Inaita...',
  'Bağlanıyor...': 'Inaunganisha...',
  'Cevapla': 'Pokea',
  'Reddet': 'Kataa',
  'Sessize al': 'Zima sauti',
  'Hoparlör': 'Spika',
  'Kamerayı kapat': 'Zima kamera',
  'Kamerayı çevir': 'Badilisha kamera',
  'Cevap yok': 'Hakuna jibu',
  'Arama reddedildi': 'Simu imekataliwa',
  'Meşgul': 'Ana shughuli',
  'Bağlanılamadı': 'Imeshindwa kuunganisha',
  'Arama iptal edildi': 'Simu imeghairiwa',
  'Arama geçmişi': 'Historia ya simu',
  'Gelen arama': 'Simu inayoingia',
  'Giden arama': 'Simu inayotoka',
  'Cevapsız arama': 'Simu isiyojibiwa',
  'Arama şu anda kullanılamıyor': 'Simu hazipatikani kwa sasa',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Simu za video zimezimwa kwa sasa, unaweza kupiga simu ya sauti',
  'Bu kullanıcıyı arayamazsın': 'Huwezi kumpigia mtumiaji huyu',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Mnahitaji kufuatana ili kupigiana simu',
  'Bu kullanıcı şu anda aranamıyor': 'Mtumiaji huyu hawezi kupigiwa kwa sasa',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Simu nyingi sana ambazo hazikujibiwa. Jaribu tena baada ya {}',
  'Zaten bir aramadasın': 'Tayari upo kwenye simu',
  'Arama için mikrofon izni gerekiyor':
      'Ruhusa ya kipaza sauti inahitajika kupiga simu',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'Ruhusa ya kamera na kipaza sauti inahitajika kwa simu za video',
  'Arama başlatılamadı': 'Imeshindwa kuanzisha simu',
  'Kullanıcı bulunamadı': 'Mtumiaji hakupatikana',
  'Kendini arayamazsın': 'Huwezi kujipigia mwenyewe',
  'Arama artık geçerli değil': 'Simu hii haifai tena',
  'Bu aramanın tarafı değilsin': 'Wewe si sehemu ya simu hii',
  'Arama bulunamadı': 'Simu haikupatikana',
  'Çok fazla istek, biraz bekle': 'Maombi mengi mno, subiri kidogo',
  'Bağlantı koptu': 'Muunganisho umekatika',
  'Arama süre sınırına ulaştı': 'Simu imefikia kikomo cha muda',
  'Arama en fazla 4 saat sürebilir': 'Simu inaweza kudumu saa 4 kwa juu zaidi',
  'Arama sona erdi': 'Simu imeisha',
  'Sesli arama': 'Simu ya sauti',
  'Görüntülü arama': 'Simu ya video',
  'Gelen aramalar': 'Simu zinazoingia',
  'Sesli ve görüntülü arama bildirimleri': 'Arifa za simu za sauti na video',
  '{} sa': 'saa {}',
  'Sesli ve Görüntülü Aramalar': 'Simu za Sauti na Video',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Maudhui ya simu hayarekodiwi kamwe. Sauti na video husafiri kati ya vifaa zikiwa zimesimbwa kwa njia ya mwisho-hadi-mwisho (DTLS-SRTP); seva zetu haziwezi kuzifungua, kuzisikiliza wala kuzihifadhi.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Metadata pekee ya simu huhifadhiwa: na nani, mwelekeo gani, lini na kwa muda gani. Kumbukumbu hizi hufutwa kiotomatiki baada ya siku 90.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Ikiwa muunganisho wa moja kwa moja hauwezekani, sauti na video hupita kwenye seva ya kupitisha (TURN) zikiwa zimesimbwa. Seva hiyo pia haiwezi kufungua wala kurekodi maudhui.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Kipaza sauti hutumika tu wakati wa simu ya sauti au video, na kamera tu wakati wa simu ya video. Vyote viwili huzimwa simu inapoisha.',
  'Takip ettiğin {} kişi izledi': 'Watu {} unaowafuata wameitazama',
  'Yorum yaz...': 'Andika maoni...',
  'Sıradaki bölüm': 'Kipindi kinachofuata',
  'Doğrulanmış testçi': 'Mjaribu aliyethibitishwa',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Arifa za kufuata, kupenda, majibu, jumbe na kutajwa',
  'Sen': 'Wewe',
  'Aradığınız kişide sesli arama devre dışı':
      'Simu za sauti zimezimwa kwa mtu huyu',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Simu za video zimezimwa kwa mtu huyu',
  'Sesli aramalara izin ver': 'Ruhusu simu za sauti',
  'Görüntülü aramalara izin ver': 'Ruhusu simu za video',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Ikizimwa, hakuna anayeweza kukupigia simu ya sauti; anayepiga ataona taarifa',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Ikizimwa, hakuna anayeweza kukupigia simu ya video; anayepiga ataona taarifa',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Simu za sauti zimezimwa. Unaweza kuziwasha katika Mipangilio > Faragha.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Simu za video zimezimwa. Unaweza kuziwasha katika Mipangilio > Faragha.',
  'Sesli ve görüntülü arama': 'Simu za sauti na video',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Akaunti za mgeni haziwezi kupiga simu. Fungua akaunti ili kutumia hii.',
  'Misafir hesaplar aranamaz': 'Akaunti za mgeni haziwezi kupigiwa simu',
  'Puan dağılımı': 'Mgawanyo wa alama',
  '{} yıldız': 'nyota {}',
  'Yakında gelecek': 'Inakuja hivi karibuni',
  '{} {} yayınlandı': '{} {} kimetoka',
  'Yeni bölüm yayınlandı': 'Kipindi kipya kimetoka',
  'Yeni bölümler': 'Vipindi vipya',
  'Geri': 'Rudi',
  'Karşılamayı kapat': 'Funga utangulizi',
  'Adım {} / {}': 'Hatua {} / {}',
  'Hadi başlayalım': 'Tuanze',
  'Kaydet ve devam': 'Hifadhi na uendelee',
  '{} tanesini ekle': 'Ongeza {}',
  'Şimdilik geç': 'Ruka kwa sasa',
  'Doğum tarihin ne zaman?': 'Ulizaliwa lini?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Tunauliza ili kuonyesha maudhui yanayolingana na umri wako na kusherehekea siku yako ya kuzaliwa.',
  'Gün': 'Siku',
  'Ay': 'Mwezi',
  'Yıl': 'Mwaka',
  'Doğum yılımı paylaşmak istemiyorum':
      'Sitaki kushiriki mwaka wangu wa kuzaliwa',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'Tarehe yako ya kuzaliwa haionyeshwi hadharani kwenye wasifu wako. Hutumika tu kwa maudhui yanayolingana na umri na kwa kusherehekea siku ya kuzaliwa.',
  'Ocak': 'Januari',
  'Şubat': 'Februari',
  'Mart': 'Machi',
  'Nisan': 'Aprili',
  'Mayıs': 'Mei',
  'Haziran': 'Juni',
  'Temmuz': 'Julai',
  'Ağustos': 'Agosti',
  'Eylül': 'Septemba',
  'Ekim': 'Oktoba',
  'Kasım': 'Novemba',
  'Aralık': 'Desemba',
  'Verilerini yanında getir': 'Leta data yako nawe',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Ikiwa unafuatilia ulichotazama kwenye programu nyingine, unaweza kukihamishia hapa. Huhitaji kuanza upya.',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Chagua faili la ZIP ulilohamisha kutoka huko; ulichotazama, alama zako na orodha zako zitahamishwa.',
  'Aktarılıyor...': 'Inahamisha...',
  'ZIP dosyası seç': 'Chagua faili la ZIP',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'Hakuna haraka: unaweza kufanya hivi baadaye pia kupitia Mipangilio > Data Zangu.',
  'Hangi filmleri izledin?': 'Umetazama filamu zipi?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Zinazotazamwa zaidi zipo hapa. Utakachogusa tutakiongeza kwenye ulichotazama.',
  'SERİ FİLMLER': 'MIFULULIZO YA FILAMU',
  'Serilerden {} film eklendi': 'Filamu {} zimeongezwa kutoka mifululizo',
  'Film listesi yüklenemedi': 'Orodha ya filamu haikupakiwa',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Unaweza kuruka hatua hii, kisha kuongeza unachotaka baadaye.',
  '{} film izlediklerine eklendi': 'Filamu {} zimeongezwa kwenye ulichotazama',
  'Film serileri': 'Mifululizo ya filamu',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Kama umetazama mfululizo mzima tangu mwanzo hadi mwisho, uongeze kwa mgusa mmoja.',
  'Seri bulunamadı': 'Hakuna mfululizo uliopatikana',
  'Daha sonra tekrar deneyebilirsin.': 'Unaweza kujaribu tena baadaye.',
  '{} film': 'Filamu {}',
  'Eklendi': 'Imeongezwa',
  'Tümünü izledim': 'Nimetazama zote',
  'Peki ya diziler?': 'Je, vipi kuhusu mifululizo?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Weka alama kwenye ulivyotazama; kadri unavyochagua, tutaleta vinavyofanana.',
  'Dizi listesi yüklenemedi': 'Orodha ya mifululizo haikupakiwa',
  'Seçtiklerine benzeyenler': 'Vinavyofanana na ulivyochagua',
  'Her şey hazır': 'Kila kitu tayari',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Angalia kwa haraka unachoweza kufanya kwenye dizi.jpg.',
  'Profilini tamamla': 'Kamilisha wasifu wako',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'Kutoka Mipangilio unaweza kuongeza Bio, picha ya wasifu na jalada.',
  'Takvimin seni bekliyor': 'Kalenda inakusubiri',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'Vipindi vipya vya mifululizo unayotazama huingia kwenye kalenda, na tunakujulisha kwa arifa.',
  'Puan ver, yorum yaz': 'Toa alama, andika maoni',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Kadiria kipindi kwa kipindi, andika maoni nyuma ya pazia la spoiler, tengeneza orodha.',
  'Verilerin sende kalır': 'Data yako inabaki kwako',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Data yako hufungamanishwa na akaunti yako pekee, na haiuzwi. Kutoka Mipangilio unaweza kupakua yote au kufuta akaunti yako kabisa.',
  'Engellenen kullanıcılar': 'Watumiaji waliozuiwa',
  'Engellediğin kişileri gör, engeli kaldır': 'Ona uliowazuia, ondoa uzuiaji',
  'Engellediğin kimse yok': 'Hujamzuia mtu yeyote',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Unaweza kumzuia mtumiaji kupitia menyu ya nukta tatu kwenye wasifu wake.',
  '@{} engellensin mi?': 'Kumzuia @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'Hamtaona machapisho, maoni wala wasifu wa kila mmoja; jumbe na simu pia hazitapita. Kama kuna ufuatiliaji kati yenu, utakatika na hautarudi hata uzuiaji ukiondolewa.',
  'Bu kullanıcıyı engelledin': 'Umemzuia mtumiaji huyu',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Huoni machapisho, maoni wala jumbe za mtu huyu; na mtu huyu haoni zako.',
  '{} yeni bir yapımda: {}': '{} kwenye kazi mpya: {}',
  'Favori kişinden yeni yapım': 'Kazi mpya kutoka kwa mtu unayempenda',
  '{} için bildirimler': 'Arifa za {}',
  'Tüm bildirimler': 'Arifa zote',
  'Uygulamada ve telefonda': 'Kwenye programu na kwenye simu',
  'Yalnız uygulama içi': 'Ndani ya programu tu',
  'Telefon bildirimi gönderilmez': 'Arifa ya simu haitumwi',
  'Kapalı': 'Imezimwa',
  'Bu kişi için bildirim yok': 'Hakuna arifa kwa mtu huyu',
  'Favori kişilerin yeni yapımları': 'Kazi mpya za watu unaowapenda',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Ikizimwa, hakuna anayeweza kukupigia simu ya sauti; anayepiga ataona taarifa kwamba simu "zimezimwa"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Ikizimwa, hakuna anayeweza kukupigia simu ya video; anayepiga ataona taarifa kwamba simu "zimezimwa"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'Shughuli zangu',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'Zilizokupendeza, maoni na ulizotazama mahali pamoja',
  'Henüz hareketin yok': 'Bado hakuna shughuli',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Kila unachopenda, unachotolea maoni na unachotazama hukusanyika hapa.',
  'Bu süzgeçte hareket yok': 'Hakuna shughuli katika kichujio hiki',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Chagua aina nyingine au rudi kwenye "Zote".',
  'Hepsi': 'Zote',
  'Puan': 'Ukadiriaji',
  'Tepki': 'Itikio',
  'İzleme': 'Kutazama',
  'Durum': 'Hali',
  'Liste': 'Orodha',
  'Yorum yaptın': 'Umetoa maoni',
  'Yorumu beğendin': 'Umependa maoni',
  '{} puan verdin': 'Umetoa alama {}',
  'Tepki verdin': 'Umeitikia',
  'Listene ekledin': 'Umeongeza kwenye orodha',
  'Takip etmeye başladın': 'Umeanza kufuata',
  '"İzleyeceğim" işaretledin': 'Umeweka alama "Nitatazama"',
  '"İzliyorum" işaretledin': 'Umeweka alama "Ninatazama"',
  '"Bitirdim" işaretledin': 'Umeweka alama "Nimemaliza"',
  '"Bıraktım" işaretledin': 'Umeweka alama "Nimeacha"',
  'Silinmiş içerik': 'Maudhui yaliyofutwa',
  'şimdi': 'sasa',
  '{} g': 'siku {}',
  '{} y': 'mwaka {}',
  'İstatistiklerim': 'Takwimu zangu',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Mionekano na zilizopendwa kwenye machapisho yako',
  'Henüz gönderin yok': 'Bado huna machapisho',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Ukiandika maoni kwenye mfululizo au filamu, idadi ya mionekano na zilizopendwa huanza kukusanyika hapa.',
  'Tüm zamanlar': 'Nyakati zote',
  'Son {} gün': 'Siku {} zilizopita',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'Historia ya mionekano bado haijaanza kukusanyika; data ya siku ya kwanza itaonekana kesho.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'Historia ya mionekano imekuwa ikikusanyika tangu {} (kuna data ya siku {}), hivyo idadi ya siku {} bado haijakamilika.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'Historia ya zilizopendwa imerekodiwa tangu {}.',
  'Bu dönemde gösterilecek gönderi yok.':
      'Hakuna machapisho ya kuonyesha kwa kipindi hiki.',
  'eksik veri': 'data pungufu',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Series na filamu ulizotazama, vihesabu vyako vya kutazama, muda wa skrini na kadi ya ulinganifu havitaonekana kwa wengine kwenye wasifu wako',
  'Takipçi listemi gizle': 'Ficha orodha ya wanaonifuata',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Wengine hawawezi kuona nani anakufuata; idadi ya wanaokufuata inabaki ikionekana',
  'Takip ettiklerimi gizle': 'Ficha ninaowafuata',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Wengine hawawezi kuona unaowafuata; idadi ya unaowafuata inabaki ikionekana',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Mtumiaji huyu anapendelea kuficha wanaomfuata.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Mtumiaji huyu anapendelea kuficha anaowafuata.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Takwimu za chapisho',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Unaweza kuona takwimu za machapisho yako pekee.',
  'Erişim': 'Ufikiaji',
  'Görüntüleyen': 'Watazamaji',
  'Kaç farklı kişi gördü (son {} gün)':
      'Watu tofauti wangapi waliona (siku {} zilizopita)',
  'Paylaşım': 'Kushirikiwa',
  'Bu gönderiden sonra': 'Baada ya chapisho hili',
  'Profil ziyareti': 'Ziara za wasifu',
  'Yeni takip': 'Wafuasi wapya',
  'İçeriğe tıklama': 'Mibofyo ya maudhui',
  'Spoiler perdesini açan': 'Walifungua spoiler',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Kushirikiwa, ziara za wasifu, wafuasi, mibofyo ya maudhui, mchanganuo wa vyanzo na vipimo vya spoiler vinakusanywa tangu {}; kabla ya hapo havikupimwa.',
  'Zamana yayılmış görüntülenme': 'Mionekano kwa muda',
  'Görüntülenme nereden geldi': 'Mionekano ilitoka wapi',
  'Kimler gördü': 'Nani aliona',
  'Günlük veri henüz birikmeye başlamadı.':
      'Data ya kila siku bado haijaanza kukusanywa.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'Chati inahitaji data ya angalau siku mbili. Data inakusanywa tangu {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'Mionekano mingi ilikuja siku ya {} baada ya kuchapisha: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Mionekano ya kila siku inakusanywa tangu {}; kabla ya hapo haikupimwa.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'Mchanganuo wa vyanzo umeanza kupimwa hivi karibuni; chapisho hili bado halijapata mwonekano uliotambulishwa.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'Mchanganuo wa wafuasi/ugunduzi umeanza kupimwa hivi karibuni; bado hakuna data.',
  'Takip edenler': 'Wafuasi',
  'Keşiften gelenler': 'Kutoka Gundua',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Ukurasa wa mfululizo/filamu',
  'Paylaşılan bağlantı': 'Kiungo kilichoshirikiwa',
  'yeni ölçülüyor': 'kipimo kipya',
  'Kendi ortalamanla aynı düzeyde': 'Sawa na wastani wako',
  'Kendi ortalamanın %{} üstünde': '{}% juu ya wastani wako',
  'Kendi ortalamanın %{} altında': '{}% chini ya wastani wako',
  'Etkileşim oranı': 'Kiwango cha mwingiliano',
  '(beğeni + yorum) ÷ görüntülenme': '(mapendekezo + maoni) ÷ mionekano',
  'Toplam görüntülenme': 'Jumla ya mionekano',
  '{} ile {} arasında toplam {} görüntülenme':
      'Kati ya {} na {}: jumla ya mionekano {}',
  'İstatistikleri gör': 'Tazama takwimu',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'Kwa takwimu zinazoonyeshwa kwa mwenye chapisho, huhifadhiwa kama vihesabu vya jumla: chapisho lilitazamwa mara ngapi na kutoka uso upi (mlisho, wasifu, mlisho wa skrini nzima, ukurasa wa mfululizo/filamu, kiungo kilichoshirikiwa), kama aliyetazama alikuwa akimfuata mwenye chapisho wakati huo, kuhama kutoka chapisho kwenda wasifu au maudhui, ufuasi ulioanzishwa kupitia chapisho, kushirikiwa, na kufunguliwa kwa pazia la spoiler. Vihesabu hivi havina kitambulisho cha mtumiaji, anwani ya IP wala alama ya wakati; haiwezekani kuuliza nani alifanya nini.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'Ili kuweza kuhesabu ni watu wangapi tofauti walioona chapisho, muhtasari wenye ufunguo usioweza kutenduliwa kwa kila mtazamaji (ufupisho wa kikriptografia unaotokana na kitambulisho cha mtumiaji au anwani ya IP) huhifadhiwa kwa siku 90. Mwenye chapisho huonyeshwa idadi pekee; utambulisho wa watazamaji hausambazwi kwa hali yoyote.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'Uhamishwe kwenye “Nitatazama”?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'Kichwa ni cha kutazamwa au kimeshatazamwa. Ukiendelea, alama {} za kutazama ulizoweka kwenye mfululizo huu zitafutwa.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'Kichwa ni cha kutazamwa au kimeshatazamwa. Ukiendelea, alama yako ya “Nimetazama” kwenye filamu hii itaondolewa.',
  'Sil ve taşı': 'Futa na uhamishe',

  // --- Yapım ekibi + yapım firmaları ---
  'Yapım Ekibi': 'Timu ya utayarishaji',
  'Yaratıcı': 'Muundaji',
  'Yönetmen': 'Mkurugenzi',
  'Senaryo': 'Mswada',
  'Yapımcı': 'Mtayarishaji',
  'Yapım Firmaları': 'Kampuni za utayarishaji',
  'Yapım Firması': 'Kampuni ya utayarishaji',
  'Firma bulunamadı': 'Kampuni haijapatikana',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'Kampuni hii haina kazi za aina hii.',
  // --- İzleyici seviyesi ve unvanları (cinsiyetsiz) ---
  // --- Doğum günü kutlama kartı ---
  'Doğum günün kutlu olsun!': 'Heri ya siku yako ya kuzaliwa!',
  'İyi ki doğdun, iyi ki buradasın.': 'Ni vizuri upo, na ni vizuri uko hapa.',
  'Bugün {} yaşına girdin': 'Leo umetimiza miaka {}',
  'Teşekkürler': 'Asante',
  // --- İki adımlı doğrulama (2FA) ---
  'İki Adımlı Doğrulama': 'Uthibitishaji wa Hatua Mbili',
  'Girişte e-postana kod gönderilir':
      'Msimbo hutumwa kwa barua pepe yako unapoingia',
  'Kod {} adresine gönderildi': 'Msimbo umetumwa kwa {}',
  '6 haneli kod': 'Msimbo wa tarakimu 6',
  'Doğrula': 'Thibitisha',
  'Yeniden gönder': 'Tuma tena',
  'Vazgeç': 'Ghairi',
  'Yeni kod gönderildi': 'Msimbo mpya umetumwa',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'Unapoingia kwa Google huulizwi msimbo; Google hufanya uthibitishaji wake.',
  'Kapatmak için de kod gerekir.': 'Kuizima pia kunahitaji msimbo.',
  'E-postana erişemezsen hesabına giremezsin.':
      'Bila ufikiaji wa barua pepe yako, huwezi kuingia kwenye akaunti.',
  'İki adımlı doğrulama açıldı': 'Uthibitishaji wa hatua mbili umewashwa',
  'İki adımlı doğrulama kapatıldı': 'Uthibitishaji wa hatua mbili umezimwa',
  // --- Video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': 'Sehemu ya video iliyotazamwa',
  'Videoyu başlatanlar': 'walianza kutazama video',
  'videonun %{} noktasına ulaştı': 'walifika {}% ya video',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'Nusu ya watazamaji walitazama angalau {}% ya video.',
  'Sonuna kadar izleyen: %{}': 'Walitazama hadi mwisho: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'Grafu inahitaji angalau mionekano {}; sasa kuna {}.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'Grafu imetokana na mionekano {} na haibadiliki na kipindi kilichochaguliwa.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'Muda wa kutazama unapimwa tangu {}; mionekano ya zamani haihesabiwi hapa.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      'Mionekano {}. {}% walifika katikati ya video, {}% hadi mwisho.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',

  // --- md.42/26 istatistikler + seviye ---
  'Seviye {}': 'Ngazi {}',
  'Sonraki seviyeye {} puan kaldı': 'Pointi {} zimebaki hadi ngazi ijayo',
  'Gönderilerin': 'Machapisho yako',
  '{} gönderi': 'Machapisho: {}',
  '{} gönderi · {} görüntülenme': 'Machapisho: {} · Mionekano: {}',
  'önceki {} güne göre': 'ikilinganishwa na siku {} zilizopita',
  'önceki {} güne göre %{} arttı':
      'ikilinganishwa na siku {} zilizopita: ongezeko la {}%',
  'önceki {} güne göre %{} azaldı':
      'ikilinganishwa na siku {} zilizopita: punguzo la {}%',
  'önceki {} güne göre değişmedi':
      'hakuna mabadiliko ikilinganishwa na siku {} zilizopita',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'Mionekano ya kila siku: chini kabisa {}, juu kabisa {}',
  'Etkileşim oranı henüz ölçülemedi':
      'Kiwango cha mwingiliano bado hakijapimika',
  'Oranlar': 'Viwango',
  'Beğenme oranı': 'Kiwango cha kupendwa',
  'Yorum oranı': 'Kiwango cha maoni',
  'Paylaşma oranı': 'Kiwango cha kushirikiwa',
  'İçeriğe gitme oranı': 'Kiwango cha mibofyo ya maudhui',
  'Profile gitme oranı': 'Kiwango cha ziara za wasifu',
  'Ziyaretten takibe dönüşüm': 'Kutoka ziara hadi kufuatwa',
  'beğeni ÷ görüntülenme': 'zilizopendwa ÷ mionekano',
  'yorum ÷ görüntülenme': 'maoni ÷ mionekano',
  'paylaşım ÷ görüntülenme': 'kushirikiwa ÷ mionekano',
  'içeriğe tıklama ÷ görüntülenme': 'mibofyo ya maudhui ÷ mionekano',
  'profil ziyareti ÷ görüntülenme': 'ziara za wasifu ÷ mionekano',
  'yeni takip ÷ profil ziyareti': 'wafuasi wapya ÷ ziara za wasifu',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'Viwango vinahitaji angalau mionekano {}; sasa kuna {}.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'Viwango hutokana na jumla ya chapisho ya muda wote; uteuzi wa siku hapa chini hauvibadilishi.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'Namba hizi ni jumla ya chapisho ya muda wote (isipokuwa visanduku vyenye dokezo lake); uteuzi wa siku hapa chini hubadilisha grafu pekee.',
  'Ortalama izlenme: videonun %{} kadarı': 'Wastani wa kutazamwa: {}% ya video',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'Wastani wa vipimo 20 vya grafu ya kubaki.',
  'Dizi, film, kişi veya şirket ara...':
      'Tafuta mfululizo, filamu, mtu au kampuni...',
  'Şirketler': 'Kampuni',
  'Senarist': 'Mwandishi wa filamu',
  'Bölüm puanları': 'Alama za vipindi',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'Alama za vipindi hazikuweza kupakiwa',
  'Giriş gerekli': 'Unahitaji kuingia',
  'Geçersiz oturum': 'Kipindi si sahihi',
  'Oturum sonlandı, tekrar giriş yap': 'Kipindi kimeisha, ingia tena',
  'Çok fazla istek; biraz sonra tekrar dene':
      'Maombi mengi mno; jaribu tena baada ya muda',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'Hakuna nafasi kwenye seva kwa sasa, jaribu tena baadaye kidogo',
  'Devam eden yapımlar ({})': 'Kazi zinazoendelea ({})',
  'Diziler ({})': 'Mfululizo ({})',
  'Filmler ({})': 'Filamu ({})',
  'Tüm yapımlar': 'Kazi zote',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'Hifadhi yako ya midia imejaa; futa vipakiwa vya zamani ili kupata nafasi',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'Barua pepe/jina la mtumiaji au nenosiri si sahihi',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'Barua pepe au jina hili tayari limetumika',
  'Google doğrulaması başarısız': 'Uthibitishaji wa Google umeshindwa',
  'Kod geçersiz veya süresi dolmuş': 'Msimbo si sahihi au umeisha',
  'Bu kullanıcıyla mesajlaşamazsın': 'Huwezi kutuma ujumbe kwa mtu huyu',
  'Kendini takip edemezsin': 'Huwezi kujifuata mwenyewe',
  'Bu kullanıcıyı takip edemezsin': 'Huwezi kumfuata mtu huyu',
  'Kendini engelleyemezsin': 'Huwezi kujizuia mwenyewe',
  'Yorum 1-1000 karakter olmalı': 'Maoni lazima yawe herufi 1–1000',
  'Boş mesaj gönderilemez': 'Huwezi kutuma ujumbe tupu',
  'Yorum bulunamadı': 'Maoni hayakupatikana',
  'Şifre hatalı': 'Nenosiri si sahihi',
  'Şifre en az 6 karakter olmalı': 'Nenosiri liwe herufi 6 au zaidi',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'Ni GIF, PNG, JPEG au WebP tu ndizo zinazokubaliwa',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'Aina zinazokubaliwa: GIF, PNG, JPEG, WebP, MP4, WebM, sauti',
  'Geçerli bir ZIP dosyası değil': 'Si faili halali la ZIP',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'Ili kupata data kwa barua pepe, unganisha barua pepe kwanza',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'Una historia ya kutazama. Ili kusema "Nitatizama", futa alama kwanza.',
  'Arama şu anda kapalı': 'Simu zimezimwa kwa sasa',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'Akaunti za mgeni haziwashi simu; unda akaunti ili utumie',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'Seva inaanza upya, jaribu tena baada ya muda',
  'Puan 1-10 arası olmalı': 'Alama iwe kati ya 1 na 10',
  'En fazla 10 medya eklenebilir': 'Unaweza kuongeza faili 10 tu',
  'Bu cihazdan yeni hesap açılamıyor':
      'Huwezi kufungua akaunti kutoka kifaa hiki',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'Unahitaji barua pepe halali, jina la mtumiaji na nenosiri la herufi 6+',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'Unahitaji barua pepe halali na nenosiri la herufi 6+',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'Jina 3–20; herufi ndogo, tarakimu, nukta, kiungo, mstari wa chini (si kwenye ncha)',
  'Bu hesap zaten bağlı': 'Akaunti hii tayari imeunganishwa',
  'Hesap oluşturulamadı': 'Akaunti haikuweza kutengenezwa',
  'Misafir hesabı oluşturulamadı': 'Akaunti ya mgeni haikuweza kutengenezwa',
  'Hesap bulunamadı': 'Akaunti haijapatikana',
  'Bu hesapta e-posta yok': 'Akaunti hii haina barua pepe',
  'İki adımlı doğrulama zaten bu durumda':
      'Uthibitishaji wa hatua mbili tayari uko hivi',
  'Kod yanlış': 'Kodi si sahihi',
  'Kodun süresi doldu': 'Muda wa kodi umeisha',
  'Kullanıcının e-postası yok (misafir hesap)':
      'Mtumiaji hana barua pepe (akaunti ya mgeni)',
  'Bio en fazla 300 karakter olabilir': 'Wasifu si zaidi ya herufi 300',
  'Geçersiz ülke': 'Nchi si sahihi',
  'Geçersiz sosyal bağlantı': 'Kiungo cha kijamii si sahihi',
  'Geçersiz doğum tarihi': 'Tarehe ya kuzaliwa si sahihi',
  'Liste adı gerekli': 'Jina la orodha linahitajika',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'Jina si zaidi ya 60, maelezo 300',
  'Liste bulunamadı': 'Orodha haijapatikana',
  'Değiştirilecek tercih yok': 'Hakuna cha kusasisha',
  'İnceleme en fazla 2000 karakter olabilir': 'Hakiki si zaidi ya herufi 2000',
  'Önce içeriği "bitirdim" olarak işaretle': 'Weka alama ya kumaliza kwanza',
  'Önce kişiyi favorile': 'Weka mtu kwenye vipendwa kwanza',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'Maoni ya kipindi yanahitaji msimu na kipindi vyote',
  'Yanıtlanan yorum bulunamadı': 'Maoni uliyojibu hayajapatikana',
  'Geri bildirim 3-2000 karakter olmalı': 'Maoni yanapaswa kuwa herufi 3–2000',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'Kichwa na maandishi vinahitajika (herufi 2+)',
  'Kendine mesaj gönderemezsin': 'Huwezi kujitumia ujumbe',
  'Mesaj en fazla 2000 karakter olabilir': 'Ujumbe si zaidi ya herufi 2000',
  'Mesaj 1-2000 karakter olmalı': 'Ujumbe unapaswa kuwa herufi 1–2000',
  'Mesaj bulunamadı': 'Ujumbe haujapatikana',
  'Mesaj bulunamadı veya düzenlenemez':
      'Ujumbe haujapatikana au hauwezi kuhaririwa',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'Unaweza kuripoti tu ujumbe uliotumiwa kwako',
  'Sebep gerekli': 'Sababu inahitajika',
  'İtiraz edilecek aktif bir ceza yok': 'Hakuna adhabu hai ya kukata rufaa',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'Tayari una rufaa inayosubiri ukaguzi',
  'Bu ceza için itirazın zaten incelendi':
      'Rufaa ya adhabu hii tayari imekaguliwa',
  'Medya bağlantısının süresi dolmuş': 'Kiungo cha media kimeisha',
  'Bu medya için imzalı bağlantı gerekli':
      'Faili hili linahitaji kiungo kilichosainiwa',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'Huduma ya simu inaanza tena; jaribu baadaye kidogo',
  'Puan göstergesi': 'Ufunguo wa alama',
  'İzleme İstatistiklerim': 'Takwimu Zangu za Kutazama',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'Ukishaweka alama kwenye kipindi au filamu kuwa umeitazama, takwimu zako zitaanza kujikusanya hapa.',
  '{} sa {} dk': 'saa {} dk {}',
  'Yaklaşık ekran süresi': 'Muda wa skrini wa kadirio',
  'İzleme serisi': 'Mfululizo wa kutazama',
  'Şu anki seri': 'Mfululizo wa sasa',
  'En uzun seri': 'Mfululizo mrefu zaidi',
  'Haftanın günleri': 'Siku za wiki',
  'En çok izlediklerin': 'Ulizotazama zaidi',
  'Bu dönemde izleme yok': 'Hakuna kutazama katika kipindi hiki',
  'Paz': 'Jpi',
  'Pzt': 'Jtt',
  'Sal': 'Jnn',
  'Çar': 'Jtn',
  'Per': 'Alh',
  'Cum': 'Iju',
  'Cmt': 'Jmo',
  '{} bölüm': 'vipindi {}',
  '{} bölüm~tekil': 'kipindi {}',
  '{} kez': 'mara {}',
  '{} kez~tekil': 'mara {}',
  'Son {} gün · günlük': 'Siku {} zilizopita · kila siku',
  'Son {} gün · haftalık': 'Siku {} zilizopita · kila wiki',
  'Ekran süren, serin ve en çok izlediklerin':
      'Muda wako wa skrini, mfululizo na ulizotazama zaidi',
  'Daralt': 'Kunja',
  'Listeyi düzenle': 'Hariri orodha',
  'Bitti': 'Imekamilika',
  'Sırala': 'Panga upya',
  'Herkese göster': 'Onyesha kwa kila mtu',
  'Başkalarından gizle': 'Ficha kwa wengine',
  'Listeden kaldır': 'Ondoa kwenye orodha',
  'Listeden kaldırılsın mı?': 'Kuondoa kwenye orodha?',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'Kichwa hiki kitatolewa kwenye orodha. Ukitaka kukificha tu, tumia aikoni ya jicho.',
  'Sıralama kaydedilemedi': 'Mpangilio haukuhifadhiwa',
  'Değişiklik kaydedilemedi': 'Mabadiliko hayakuhifadhiwa',
  'Kaldırılamadı': 'Haikuweza kuondolewa',
  'Popülerlik': 'Umaarufu',
  'TMDB puanı': 'Ukadiriaji wa TMDB',
  'Yapım yılı': 'Mwaka wa utayarishaji',
  'dizi.jpg puanı': 'Ukadiriaji wa dizi.jpg',
  'İzlenme': 'Mitazamo',
  'Yorum sayısı': 'Idadi ya maoni',
  'Tüm raflara uygulanır': 'Inatumika kwa rafu zote',
  'En popüler {} yapım arasında sıralandı':
      'Imepangwa miongoni mwa vipindi {} maarufu zaidi',
  'Altyazı görünümü': 'Muonekano wa manukuu',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık':
      'Rangi, fonti, ukubwa, ukingo na kiwango cha uwazi',
  'Bu bir örnek altyazıdır.': 'Haya ni manukuu ya mfano.',
  'Ayar değiştikçe önizleme anında güncellenir.':
      'Onyesho la kukagua husasishwa papo hapo mipangilio inapobadilika.',
  'Yazı biçimi': 'Mtindo wa maandishi',
  'Yazı rengi': 'Rangi ya maandishi',
  'Yazı opaklığı': 'Kiwango cha uwazi cha maandishi',
  'Yazı tipi': 'Fonti',
  'Yazı boyutu': 'Ukubwa wa maandishi',
  'Karakter ayrıtı': 'Ukingo wa herufi',
  'Ayrıt türü': 'Aina ya ukingo',
  'Ayrıt rengi': 'Rangi ya ukingo',
  'Yok': 'Hakuna',
  'Dış çizgi': 'Mstari wa nje',
  'Gölge': 'Kivuli',
  'Kabartma': 'Iliyoinuka',
  'Oyma': 'Iliyobonyea',
  'Arka plan rengi': 'Rangi ya mandharinyuma',
  'Arka plan opaklığı': 'Kiwango cha uwazi cha mandharinyuma',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      'Mandharinyuma ni sehemu iliyojazwa nyuma ya maandishi; dirisha ni uso mpana zaidi nyuma ya eneo lote la manukuu.',
  'Pencere': 'Dirisha',
  'Pencere rengi': 'Rangi ya dirisha',
  'Pencere opaklığı': 'Kiwango cha uwazi cha dirisha',
  'Altyazı görünümü sıfırlansın mı?': 'Uweke upya muonekano wa manukuu?',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      'Mipangilio ya rangi, fonti, ukubwa, ukingo na uwazi itarudi kwenye chaguomsingi.',
  'Altyazı görünümü varsayılana döndü':
      'Muonekano wa manukuu umerudi kwenye chaguomsingi',
  '{} indiriliyor…': 'Inapakua {}…',
  'Seçince indirilir': 'Hupakuliwa ikichaguliwa',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      'Fonti haikuweza kupakuliwa. Inaonyeshwa kwa fonti chaguomsingi.',
  'Beyaz': 'Nyeupe',
  'Siyah': 'Nyeusi',
  'Kırmızı': 'Nyekundu',
  'Yeşil': 'Kijani',
  'Mavi': 'Bluu',
  'Sarı': 'Njano',
  'Camgöbeği': 'Samawati',
  'Macenta': 'Magenta',
  'Yapım bütçesi': 'Bajeti ya utayarishaji',
  'Yapım bütçesi ve dünya çapında hasılat':
      'Bajeti ya utayarishaji na mapato ya dunia nzima',
  'Dizinin yayın durumu': 'Hali ya utangazaji wa mfululizo',
  'Devam ediyor': 'Inaendelea',
  'Sona erdi': 'Imeisha',
  'İptal edildi': 'Imeghairiwa',
  'Yapımda': 'Inatayarishwa',
  'Planlandı': 'Imepangwa',
  'Pilot bölüm': 'Kipindi cha majaribio',
  'Ad': 'Jina',
  'Adın': 'Jina lako',
  'Kullanıcı adı': 'Jina la mtumiaji',
  'Kullanıcı adını değiştir': 'Badilisha jina la mtumiaji',
  'Kullanıcı adını 90 günde bir değiştirebilirsin':
      'Unaweza kubadilisha jina la mtumiaji mara moja kila siku 90',
  'Değiştir': 'Badilisha',
  '{} gün sonra değiştirebilirsin': 'Utaweza kubadilisha baada ya siku {}',
  'Kullanıcı adın: @{}': 'Jina lako la mtumiaji: @{}',
  'Bu kullanıcı adı zaten alınmış':
      'Jina hili la mtumiaji tayari limechukuliwa',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış':
      'Jina hili la mtumiaji kwa sasa limehifadhiwa kwa akaunti nyingine',
  'Bu zaten senin kullanıcı adın': 'Hili tayari ndilo jina lako la mtumiaji',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      'Jina 3–20; herufi ndogo, tarakimu, nukta, kiungo, mstari wa chini',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      'Huonekana juu ya jina lako la mtumiaji kwenye wasifu. Unaweza kuliacha wazi.',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      'Baada ya kubadilisha huwezi kubadilisha tena kwa siku 90. Jina lako la zamani litahifadhiwa kwa ajili yako kwa siku 90 — unaweza kurudi kwake, na hakuna mtu mwingine anayeweza kulichukua kwa muda huo. Viungo vinavyoelekea jina lako la zamani havitafungua wasifu wako tena.',
  'Etkinliğim': 'Shughuli',
  'Tercihler': 'Mapendeleo',
  'Gizlilik ve güvenlik': 'Faragha na usalama',
  'Destek': 'Msaada',
  'Hesap': 'Akaunti',
  '{} dizileri': 'Vipindi vya {}',
  '{} filmleri': 'Filamu za {}',
  'En üste taşı': 'Sogeza juu kabisa',
  'Sırayı sıfırla': 'Weka upya mpangilio',
  'Listede ara': 'Tafuta kwenye orodha',
  'Elle sıra sıfırlansın mı?': 'Uweke upya mpangilio uliopanga mwenyewe?',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      'Orodha itarudi kwenye mpangilio chaguo-msingi (uliyoweka alama karibuni zaidi kwanza).',
  'Sıra sıfırlanamadı': 'Mpangilio haukuwekwa upya',
  'Listenin en üstüne taşındı': 'Imesogezwa juu kabisa kwenye orodha',
  'Adlar yükleniyor…': 'Inapakia majina…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      'Shikilia bango kisha uliburute. Ili kuleta mbele kazi iliyo mbali, tumia “Sogeza juu kabisa”.',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      'Kuburuta kumezimwa kwenye utafutaji; leta mbele kwa “Sogeza juu kabisa” (matokeo {}).',
  'Görünüm': 'Mwonekano',
  'En çok izlediğin filmler': 'Filamu ulizotazama zaidi',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      'Muda ni makadirio: kipindi huhesabiwa dakika ~{}, filamu dakika ~{}',
  'Bu kullanıcı adı sistem tarafından ayrılmış':
      'Jina hili la mtumiaji limehifadhiwa na mfumo',
  'Ekran süresi': 'Muda wa skrini',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir":
      'Muda ni urefu halisi wa vipindi na filamu kutoka TMDB',
  'Tüm zamanlar: {} bölüm · {} film · {}':
      'Muda wote: vipindi {} · filamu {} · {}',
  'Kabul et': 'Kubali',
  'Reddedilenler': 'Zilizokataliwa',
  'İstekler': 'Maombi',
  'Reddettiğin istek yok': 'Hakuna maombi yaliyokataliwa',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      'Maombi yaliyokataliwa hubaki hapa; unaweza kuyakubali tena wakati wowote.',
  'Ne izlesem?': 'Nitazame nini?',
  'Karışık': 'Mchanganyiko',
  'Çarkı çevir': 'Zungusha gurudumu',
  'Tekrar çevir': 'Zungusha tena',
  'Bu türde içerik yok': 'Hakuna maudhui ya aina hii',
  'Bütçe': 'Bajeti',
  'dizi.jpg AI özeti': 'Muhtasari wa AI wa dizi.jpg',
  'Daha fazlasını gör': 'Ona zaidi',
  'Yıldız sistemi': 'Mfumo wa nyota',
  '{} yıldız üzerinden': 'Kati ya nyota {}',
  'Önizleme': 'Hakikisho',
  'dokununca açılır': 'hufunguka ukigusa',
  'Bir azalt': 'Punguza moja',
  'Bir artır': 'Ongeza moja',
  'Ölçek kaydedilemedi': 'Kipimo hakikuhifadhiwa',
  'Ölçeği değiştirmek puanlarını silmez; aynı puanlar yeni ölçekte gösterilir.':
      'Kubadilisha kipimo hakufuti ukadiriaji wako; ukadiriaji uleule huonyeshwa kwa kipimo kipya.',
  'En aşağıya gönder': 'Peleka chini',
  'Listenin en altına taşındı': 'Imehamishwa chini ya orodha',
  'Oturumun sonlandı': 'Kipindi chako kimeisha',
  'Bu hesabın oturumları kapatıldı ya da şifresi değişti. Devam etmek için tekrar giriş yap.':
      'Akaunti hii ilitolewa kwenye vifaa vyote au nenosiri lilibadilika. Ingia tena ili kuendelea.',
  'Son izleme: {}': 'Ulitazamwa mwisho: {}',
  '{} tarihinde izledin': 'Ulitazama {}',
  'Geri bildirimine yanıt verdik': 'Tumejibu maoni yako',
  'Bu yanıt artık görüntülenemiyor.': 'Jibu hili haliwezi kuonyeshwa tena.',
  'Gönderdiğin geri bildirim': 'Maoni uliyotuma',
  'Dizi veya film seç (zorunlu)': 'Chagua mfululizo au filamu (lazima)',
  'Bölüm seç (isteğe bağlı)': 'Chagua kipindi (hiari)',
  '{}. sezon {}. bölüm': 'Msimu {}, kipindi {}',
  'Ne düşünüyorsun?': 'Unafikiri nini?',
  '{}/{} yükleniyor': 'Inapakia {}/{}',
  'Fotoğraf/video ekle': 'Ongeza picha au video',
  'Paylaşmak için önce bir dizi veya film seç.':
      'Chagua kwanza mfululizo au filamu ili kushiriki.',
  'Sezon seç': 'Chagua msimu',
  '{}. sezon': 'Msimu {}',
  'Bölüm seçme (yalnız dizi hakkında)': 'Hakuna kipindi (kuhusu mfululizo tu)',
  'Sezonlar yüklenemedi.': 'Misimu haikuweza kupakiwa.',
  'Bu dizide bölüm bilgisi yok.':
      'Hakuna taarifa za vipindi kwa mfululizo huu.',
  'Bu sezonda bölüm yok.': 'Hakuna vipindi katika msimu huu.',
  '{}. bölüm': 'Kipindi {}',
  'Dizi veya film ara...': 'Tafuta mfululizo na filamu...',
  'İzlediğin dizi ve film hakkında yorum paylaş':
      'Shiriki maoni kuhusu ulichotazama',
  'Yapım seç (zorunlu)': 'Chagua kichwa (lazima)',
  'Paylaşmak için önce bir yapım seç.': 'Chagua kwanza kichwa ili kushiriki.',
  'Kişi': 'Mtu',
  'Yapım firması': 'Kampuni ya utayarishaji',
  'Yapım ara...': 'Tafuta vichwa...',
  'Çarkı çevirmek için sürükle veya dokun':
      'Buruta au gusa ili kuzungusha gurudumu',
  'Arşiv': 'Kumbukumbu',
  'Yüklediklerim': 'Nilizopakia',
  'GIF ara...': 'Tafuta GIF...',
  'GIF yükle': 'Pakia GIF',
  'GIF etiketleri': 'Lebo za GIF',
  'Virgülle ayır. Aramada bu kelimelerle bulunur.':
      'Tenganisha kwa koma. Kwa maneno haya itapatikana.',
  'gülme, alkış, şaşkın': 'kicheko, makofi, mshangao',
  'Yükle': 'Pakia',
  'Henüz GIF yok': 'Bado hakuna GIF',
  'Bu aramaya uyan GIF yok': 'Hakuna GIF inayolingana na utafutaji huu',
  'Arşiv yeni. İlk GIF i sen yükle — sen hemen kullanırsın, onaydan sonra herkes görür.':
      'Kumbukumbu ni mpya. Pakia GIF ya kwanza — unaweza kuitumia mara moja, na wote wataiona baada ya kuidhinishwa.',
  'GIF yüklendi. Sen hemen kullanabilirsin; herkese açık arşive onaydan sonra girer.':
      'GIF imepakiwa. Unaweza kuitumia mara moja; itaingia kwenye kumbukumbu ya umma baada ya kuidhinishwa.',
  'Onay bekliyor': 'Inasubiri idhini',
  'GIF listesi yüklenemedi': 'Orodha ya GIF haikuweza kupakiwa',
  'GIF yüklenemedi': 'GIF haikuweza kupakiwa',
  'Bu GIF i şikayet et': 'Ripoti GIF hii',
  'Uygunsuz içerik yöneticiye bildirilir ve arşivden kaldırılabilir.':
      'Maudhui yasiyofaa huripotiwa kwa msimamizi na yanaweza kuondolewa kwenye kumbukumbu.',
  'Şikayetin alındı': 'Ripoti yako imepokelewa',
  'Şikayet gönderilemedi': 'Ripoti haikuweza kutumwa',
  'Dizinin kendisi': 'Msururu wenyewe',
  'Sezon ya da bölüm seçme': 'Bila msimu wala kipindi',
  'Tüm {}. sezon': 'Msimu {} mzima',
  'Bölüm seçme': 'Bila kipindi',
  'En fazla {} yapım ekleyebilirsin.': 'Unaweza kuongeza hadi vichwa {}.',
  'Bu zaten ekli.': 'Tayari imeongezwa.',
  'Dizi, film, oyuncu ya da yönetmen etiketle — gönderin onların sayfasında da görünür.':
      'Tia lebo msururu, filamu, mwigizaji au mkurugenzi — chapisho lako litaonekana pia kwenye ukurasa wao.',
  'Etiket ekle': 'Ongeza lebo',
  'Dizi, film, oyuncu ya da yönetmen etiketle':
      'Tia lebo msururu, filamu, mwigizaji au mkurugenzi',
  'Gönderiden vazgeç': 'Tupa chapisho',
  'Yazdıkların kaydedilmeyecek.': 'Ulichoandika hakitahifadhiwa.',
  'Yazmaya devam et': 'Endelea kuandika',
  'Bulunamadı. Adın yazılışını değiştirip dene.':
      'Haikupatikana. Jaribu tahajia nyingine.',
  'Dizi, film, oyuncu, yönetmen ya da yapım firması ara.':
      'Tafuta msururu, filamu, mwigizaji, mkurugenzi au kampuni ya utayarishaji.',
  'E-posta adresini değiştir': 'Badilisha anwani yako ya barua pepe',
  'E-posta bağlı değil': 'Hakuna barua pepe iliyounganishwa',
  'Geçerli bir e-posta adresi yaz': 'Andika anwani sahihi ya barua pepe',
  'Bu zaten hesabının e-posta adresi':
      'Hiyo tayari ni anwani ya barua pepe ya akaunti yako',
  'Kod gönder': 'Tuma msimbo',
  'E-posta adresin güncellendi': 'Anwani yako ya barua pepe imesasishwa',
  'Bu e-posta başka bir hesapta kayıtlı':
      'Barua pepe hii imesajiliwa kwenye akaunti nyingine',
  'Doğrulama kodu YENİ adrese gönderilir; adres ancak kodu girdikten sonra değişir. Şifre sıfırlama ve iki adımlı giriş kodları bundan sonra yeni adrese gider.':
      'Msimbo wa uthibitisho hutumwa kwenye anwani MPYA; anwani hubadilika tu baada ya kuweka msimbo. Misimbo ya kuweka upya nenosiri na ya kuingia kwa hatua mbili itakwenda kwenye anwani mpya tangu hapo.',
  'Hesabındaki e-posta adresi geçerli değil, bu yüzden e-posta teslim edilemiyor. Doğru adresi bağlamak için destekle iletişime geç.':
      'Anwani ya barua pepe kwenye akaunti yako si sahihi, kwa hivyo barua pepe haiwezi kufikishwa. Wasiliana na usaidizi ili kuunganisha anwani sahihi.',
  'Bu adrese kod gönderilemedi, adresi kontrol et':
      'Haikuwezekana kutuma msimbo kwenye anwani hii, angalia anwani',
  'ya da': 'au',
  'Google ile doğrula': 'Thibitisha kwa Google',
  'Hesabını Google ile açtıysan şifren yoktur; kimliğini Google ile doğrula.':
      'Ikiwa ulifungua akaunti yako kwa Google huna nenosiri; thibitisha utambulisho wako kwa Google.',
  'Google doğrulaması bu hesapla eşleşmedi':
      'Uthibitishaji wa Google haukulingana na akaunti hii',
  'Bu hesap Google ile açıldı; doğrulamak için Google ile giriş yap':
      'Akaunti hii ilifunguliwa kwa Google; ingia kwa Google ili kuthibitisha',
  // --- 31 Agu 2026: kitaplik paylasimi + reels ceviri + sohbet detayi ---
  'Bu liste gizli': 'Orodha hii ni ya faragha',
  'Bu kullanıcı izleme listelerini gizli tutmayı tercih ediyor.':
      'Mtumiaji huyu anapendelea kuweka orodha zake faragha.',
  'Bu listede henüz içerik yok': 'Bado hakuna vichwa kwenye orodha hii',
  'Otomatik çeviri': 'Tafsiri ya kiotomatiki',
  'Otomatik çeviri açıldı': 'Tafsiri ya kiotomatiki imewashwa',
  'Otomatik çeviri kapatıldı': 'Tafsiri ya kiotomatiki imezimwa',
  'Sohbet sessize alındı': 'Gumzo limenyamazishwa',
  'Sessize alma kaldırıldı': 'Kunyamazisha kumeondolewa',
  'Tema özelleştir': 'Badilisha mandhari',
  'Sohbette ara': 'Tafuta kwenye gumzo',
  'Mesajlarda ara...': 'Tafuta kwenye jumbe...',
  'Sonuç yok': 'Hakuna matokeo',
  'Profili gör': 'Tazama wasifu',
  'Medya ve dosyalar': 'Media na faili',
  'Henüz medya yok': 'Bado hakuna media',
  'Varsayılan': 'Chaguomsingi',
  'Mor': 'Zambarau',
  'Pembe': 'Pinki',
  'Turuncu': 'Chungwa',
  'Orijinal metin gösteriliyor': 'Inaonyesha maandishi asilia',
  'İnternet bağlantısı yok': 'Hakuna muunganisho wa intaneti',
  'Sunucu yanıt vermedi': 'Seva haikujibu',
  'Güvenli bağlantı kurulamadı': 'Imeshindwa kuanzisha muunganisho salama',
  'Sunucudan beklenmeyen bir yanıt geldi':
      'Jibu lisilotarajiwa kutoka kwa seva',
  'İzlediğim Diziler': 'Vipindi nilivyotazama',
  'İzlediğim Filmler': 'Filamu nilizotazama',
  'Satır görünümü': 'Mwonekano wa orodha',
  'Afiş görünümü': 'Mwonekano wa mabango',
  'Satır görünümünde sürükleme kapalı; "En üste taşı" ile öne al.':
      'Kuburuta kumezimwa katika mwonekano wa orodha; tumia “Sogeza juu kabisa” kuisogeza mbele.',
};
