/// Otomatik üretilen çeviri haritası (vi).
const Map<String, String> cevirilerVi = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Bạn đã thấy tất cả, chúng tôi chỉ cho bạn từ đầu',
  'Aktarılacak tanınan veri bulunamadı.':
      'Không tìm thấy dữ liệu hợp lệ để nhập.',
  'Arama': 'Tìm kiếm',
  'Aramaya başla': 'Bắt đầu tìm kiếm',
  'Son aramalar': 'Tìm kiếm gần đây',
  'Ayarlar': 'Cài đặt',
  'Bağla': 'Liên kết',
  'Bio': 'Tiểu sử',
  'Bitirdim': 'Đã xem xong',
  'Bunları da Beğenebilirsin': 'Có thể bạn cũng thích',
  'Bölüm': 'Tập',
  'Bıraktım': 'Đã bỏ dở',
  'Dil': 'Ngôn ngữ',
  'Dil ara...': 'Tìm ngôn ngữ...',
  'Dizi': 'Phim bộ',
  'Dizi ve filmlerini takip et': 'Theo dõi phim bộ và phim lẻ của bạn',
  'Dizi yorumu': 'Bình luận về phim bộ',
  'Dizi, film veya kişi ara...': 'Tìm phim bộ, phim lẻ hoặc người...',
  'Dosya en fazla 30MB olabilir': 'Tệp tối đa 30MB',
  'Dosya en fazla {}MB olabilir': 'Tệp tối đa {}MB',
  'E-posta': 'Email',
  'E-posta veya kullanıcı adı': 'Email hoặc tên người dùng',
  'En az 2 harf yaz': 'Nhập ít nhất 2 ký tự',
  'Film': 'Phim lẻ',
  'Film yorumu': 'Bình luận về phim lẻ',
  'Fotoğraf / video ekle': 'Thêm ảnh / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Ảnh hoặc GIF — ảnh đại diện và ảnh bìa',
  'Giriş Yap': 'Đăng nhập',
  'Gönder': 'Gửi',
  'Gönderildi': 'Đã gửi',
  'Haftanın Dizileri': 'Phim bộ trong tuần',
  'Haftanın Filmleri': 'Phim lẻ trong tuần',
  'Henüz izleme kaydın yok': 'Bạn chưa có lịch sử xem',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Bạn chưa có danh sách nào — tạo ngay từ tab Hồ sơ.',
  'Henüz yorum yok.': 'Chưa có bình luận nào.',
  'Hesabın bağlandı!': 'Đã liên kết tài khoản!',
  'Hesabın yok mu? Kayıt ol': 'Chưa có tài khoản? Đăng ký',
  'Hesabını Bağla': 'Liên kết tài khoản',
  'Hesap Oluştur': 'Tạo tài khoản',
  'Kapak resmi ekle': 'Thêm ảnh bìa',
  'Kaydet': 'Lưu',
  'Kendinden bahset...': 'Giới thiệu về bản thân...',
  'Keşfet': 'Khám phá',
  'Kimseyi takip etmiyor': 'Chưa theo dõi ai',
  'Kişi ara': 'Tìm người',
  'Kişi yorumu': 'Bình luận về người',
  'Konuk Oyuncular': 'Diễn viên khách mời',
  'Kullanıcı adı (küçük harf)': 'Tên người dùng (chữ thường)',
  'Kullanıcı adı ara...': 'Tìm tên người dùng...',
  'Liste adı': 'Tên danh sách',
  'Listeye Ekle': 'Thêm vào danh sách',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Bạn đang dùng tài khoản khách — liên kết email để không mất dữ liệu!',
  'Misafir olarak devam et': 'Tiếp tục với tư cách khách',
  'Oluştur': 'Tạo',
  'Oyuncular': 'Diễn viên',
  'Profil': 'Hồ sơ',
  'Profil kaydedildi': 'Đã lưu hồ sơ',
  'Puanla': 'Chấm điểm',
  'Puanı Sil': 'Xóa điểm',
  'Puanın': 'Điểm của bạn',
  'Sezonlar': 'Các mùa',
  'Sunucu hatası ({})': 'Lỗi máy chủ ({})',
  'S{} · {}. Bölüm': 'S{} · Tập {}',
  'S{}B{} yorumu': 'Bình luận S{}E{}',
  'Takibi Bırak': 'Bỏ theo dõi',
  'Takip': 'Đang theo dõi',
  'Takip Edilenler': 'Đang theo dõi',
  'Takip Et': 'Theo dõi',
  'Takipçi': 'Người theo dõi',
  'Takipçi yok': 'Chưa có người theo dõi',
  'Takipçiler': 'Người theo dõi',
  'Takvim': 'Lịch',
  'Tamam': 'OK',
  'Tekrar Dene': 'Thử lại',
  'Tekrar dene': 'Thử lại',
  'Toplam İzleme Süresi': 'Tổng thời gian xem',
  'Tüm Zamanların En İyileri': 'Hay nhất mọi thời đại',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Xuất toàn bộ dữ liệu của bạn (lượt xem, điểm, bình luận, danh sách) dưới dạng ZIP tương thích TV Time, hoặc nhập ZIP từ ứng dụng khác.',
  'Tümünü Kaldır': 'Xóa tất cả',
  'Tümünü İzledim': 'Đã xem tất cả',
  'Türk Dizileri': 'Phim bộ Thổ Nhĩ Kỳ',
  'Veri içe aktar (.zip)': 'Nhập dữ liệu (.zip)',
  'Verilerim': 'Dữ liệu của tôi',
  'Verilerimi dışa aktar (e-posta)': 'Xuất dữ liệu của tôi (email)',
  'Verilerini dışa aktar': 'Xuất dữ liệu của bạn',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Không có tập sắp phát sóng.\nVào trang chi tiết phim và chọn "Đang xem" để theo dõi tập mới tại đây.',
  'Yapımları': 'Tác phẩm',
  'Yeni Diziler': 'Phim bộ mới',
  'Yeni Liste': 'Danh sách mới',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Tên người dùng mới (không bắt buộc)',
  'Yorum': 'Bình luận',
  'Yorumunu yaz...': 'Viết bình luận của bạn...',
  'Zaten hesabın var mı? Giriş yap': 'Đã có tài khoản? Đăng nhập',
  'ort. {}': 'TB {}',
  'takip': 'đang theo dõi',
  'takipçi': 'người theo dõi',
  '{} / {} bölüm': '{} / {} tập',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} tháng',
  '{} ay~tekil': '{} tháng',
  '{} bölüm izlendi': 'Đã xem {} tập',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} phút',
  '{} dk~tekil': '{} phút',
  '{} gün': '{} ngày',
  '{} gün~tekil': '{} ngày',
  '{} içerik': '{} nội dung',
  '{} içerik · otomatik': '{} nội dung · tự động',
  '{} kayıt atlandı (eşleşmedi).': 'Đã bỏ qua {} bản ghi (không khớp).',
  '{} saat': '{} giờ',
  '{} saat~tekil': '{} giờ',
  '{} sezon': '{} mùa',
  '{} yıl': '{} năm',
  '{} yıl~tekil': '{} năm',
  '{}. Bölüm': 'Tập {}',
  '{}. Sezon': 'Mùa {}',
  'Çıkış Yap': 'Đăng xuất',
  'Ülke': 'Quốc gia',
  'Ülke ara...': 'Tìm quốc gia...',
  'Ülke seç': 'Chọn quốc gia',
  'İlk yorumu sen yaz!': 'Hãy là người bình luận đầu tiên!',
  'İncelemeler': 'Đánh giá',
  'İncelemen (isteğe bağlı)': 'Đánh giá của bạn (không bắt buộc)',
  'İptal': 'Hủy',
  'İzlediklerim': 'Lịch sử xem',
  'İzledim': 'Đã xem',
  'İzledin': 'Bạn đã xem',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Lịch sử xem và danh sách của bạn được giữ nguyên; giờ bạn có thể đăng nhập từ mọi thiết bị.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Lịch sử xem, điểm, bình luận và danh sách của bạn sẽ được gửi dưới dạng ZIP đến email đã đăng ký.',
  'İzleyeceğim': 'Sẽ xem',
  'İzliyorum': 'Đang xem',
  'İçe aktarım tamamlandı': 'Nhập dữ liệu hoàn tất',
  'Şifre': 'Mật khẩu',
  '• profil bilgisi': '• thông tin hồ sơ',
  '• {} dizi durumu': '• {} trạng thái phim',
  '• {} izleme kaydı': '• {} lượt xem',
  '• {} liste': '• {} danh sách',
  '• {} puan': '• {} điểm',
  '• {} yorum': '• {} bình luận',
  '{}+ yapım': '{}+ tác phẩm',
  'Yorumlar': 'Bình luận',
  'Yorumlar ({})': 'Bình luận ({})',
  'Yorumları ({})': 'Bình luận của họ ({})',
  'Listelerim': 'Danh sách của tôi',
  'Nereden izledin?': 'Bạn đã xem ở đâu?',
  'Diziye git': 'Đến phim',
  'TV / Kanal': 'TV / Kênh',
  'Sinema': 'Rạp chiếu phim',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Khác',
  'Akış': 'Bảng tin',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Bảng tin của bạn đang trống.\nKhi có người bình luận về phim bạn xem, nó sẽ hiện ở đây.',
  'Listeleri ({})': 'Danh sách của họ ({})',
  'Liste boş.': 'Danh sách này trống.',
  'Yanıtla': 'Trả lời',
  '@{} kullanıcısına yanıt veriyorsun': 'Đang trả lời @{}',
  'İzlediğim Diziler ({})': 'Phim bộ đã xem ({})',
  'İzlediğim Filmler ({})': 'Phim lẻ đã xem ({})',
  'Tümünü gör': 'Xem tất cả',
  'Bildirimler': 'Thông báo',
  'Henüz bildirim yok': 'Chưa có thông báo',
  '@{} yorumuna yanıt verdi': '@{} đã trả lời bình luận của bạn',
  '@{} yorumunu beğendi': '@{} đã thích bình luận của bạn',
  '@{} seni takip etti': '@{} đã theo dõi bạn',
  '@{} sana mesaj gönderdi': '@{} đã gửi tin nhắn cho bạn',
  'Mesajlar': 'Tin nhắn',
  'Mesaj': 'Nhắn tin',
  'Mesaja eklenecek': 'Se duoc them vao tin nhan',
  'Mesajını yaz...': 'Viết tin nhắn...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Chưa có cuộc trò chuyện.\nMở một trang cá nhân và gửi tin nhắn.',
  'Şifreni mi unuttun?': 'Quên mật khẩu?',
  'Şifreyi Sıfırla': 'Đặt lại mật khẩu',
  'E-postadaki kod': 'Mã từ email',
  'Yeni şifre': 'Mật khẩu mới',
  'Sana Özel': 'Dành cho bạn',
  '{} özetin': 'Tổng kết {} của bạn',
  'Yıllık izleme istatistiklerin': 'Thống kê xem hằng năm',
  'Rozetler': 'Huy hiệu',
  'Verdiğin puan': 'Số lần chấm điểm',
  'Ortalama puanın': 'Điểm trung bình',
  'En çok izlediğin diziler': 'Phim bạn xem nhiều nhất',
  'İlk Bölüm': 'Tập đầu tiên',
  '100 Bölüm': '100 tập',
  '1000 Bölüm': '1000 tập',
  'İlk Film': 'Phim đầu tiên',
  '50 Film': '50 phim',
  'İlk Yorum': 'Bình luận đầu tiên',
  '25 Yorum': '25 bình luận',
  '10 Puan': '10 lần chấm điểm',
  'İlk Takipçi': 'Người theo dõi đầu tiên',
  '10 Dizi Bitirdin': 'Hoàn thành 10 phim bộ',
  'İzlemeyi Bıraktım': 'Ngừng xem',
  'İzlediği Diziler ({})': 'Phim bộ họ đã xem ({})',
  'İzlediği Filmler ({})': 'Phim lẻ họ đã xem ({})',
  '500 Bölüm': '500 tập',
  '5000 Bölüm': '5000 tập',
  '10 Film': '10 phim',
  '100 Film': '100 phim',
  '100 Yorum': '100 bình luận',
  '50 Puan': '50 lần chấm điểm',
  '100 Puan': '100 lần chấm điểm',
  '10 Takipçi': '10 người theo dõi',
  '50 Takipçi': '50 người theo dõi',
  '25 Dizi Bitirdin': 'Hoàn thành 25 phim bộ',
  '50 Dizi Bitirdin': 'Hoàn thành 50 phim bộ',
  '10 Beğeni': '10 lượt thích',
  '100 Beğeni': '100 lượt thích',
  'yazıyor...': 'đang nhập...',
  'Profil düzeni': 'Bố cục trang cá nhân',
  'Konumla ve kırp': 'Căn chỉnh và cắt',
  'Listeye eklendi': 'Đã thêm vào danh sách',
  'Listeyi sil?': 'Xóa danh sách?',
  'Sil': 'Xóa',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Phim này sẽ được đánh dấu chưa từng xem và bị xóa khỏi danh sách của bạn.',
  'Gelecek bölüm bugün': 'Tập tiếp theo hôm nay',
  'Gelecek bölüm {} gün sonra': 'Tập tiếp theo sau {} ngày',
  'Tema': 'Chủ đề',
  'Sistem': 'Hệ thống',
  'Koyu': 'Tối',
  'Açık': 'Sáng',
  'İzleyenler': 'Người xem',
  'Yorumunu yaz... (@ ile etiketle)':
      'Viết bình luận của bạn... (@ để gắn thẻ)',
  '@{} bir yorumda seni etiketledi': '@{} đã gắn thẻ bạn trong một bình luận',
  'Mesajı sil': 'Xóa tin nhắn',
  'Mesaj silinemedi': 'Không thể xóa tin nhắn',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Liên kết không hợp lệ hoặc không tìm thấy trang',
  'Keşfet\'e dön': 'Quay lại Khám phá',
  'Düzenle': 'Sửa',
  'Mesajı düzenle': 'Sửa tin nhắn',
  'Yanıtlanıyor': 'Đang trả lời',
  'düzenlendi': 'đã sửa',
  'Fotoğraf': 'Ảnh',
  'Video': 'Video',
  'İçerik': 'Nội dung',
  'çevrimiçi': 'trực tuyến',
  'son görülme {} dk önce': 'hoạt động {} phút trước',
  'son görülme {} saat önce': 'hoạt động {} giờ trước',
  'son görülme {} gün önce': 'hoạt động {} ngày trước',
  'Yorumlar yüklenemedi': 'Không thể tải bình luận',
  'Favori': 'Yêu thích',
  'Listeye ekle': 'Thêm vào danh sách',
  'İçerik paylaş': 'Chia sẻ nội dung',
  'Kapat': 'Đóng',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Mọi thứ bạn đánh dấu đã xem sẽ gom về đây.',
  'Henüz sohbetin yok': 'Chưa có cuộc trò chuyện nào',
  'Bir profile girip mesaj gönderebilirsin.': 'Mở một hồ sơ và gửi tin nhắn.',
  'Listeyi sil': 'Xóa danh sách',
  'Puan kaydedilemedi': 'Không thể lưu đánh giá',
  'Nerede İzlenir': 'Xem ở đâu',
  'Abonelik': 'Đăng ký',
  'Kirala': 'Thuê',
  'Satın al': 'Mua',
  'Hoş geldin!': 'Chào mừng!',
  'İzlemek istediğin dizi ve filmleri seç':
      'Chọn phim bộ và phim lẻ bạn muốn xem',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Lựa chọn của bạn sẽ được thêm vào danh sách xem',
  'Şimdilik atla': 'Bỏ qua bây giờ',
  'Devam et': 'Tiếp tục',
  '{} ekle': 'Thêm {}',
  'Şikayet et': 'Báo cáo',
  'Engelle': 'Chặn',
  'Engeli kaldır': 'Bỏ chặn',
  'Kullanıcı engellendi': 'Đã chặn người dùng',
  'Engel kaldırıldı': 'Đã bỏ chặn',
  'Şikayet sebebi': 'Lý do báo cáo',
  'Spam veya yanıltıcı': 'Spam hoặc gây hiểu lầm',
  'Taciz veya nefret söylemi': 'Quấy rối hoặc phát ngôn thù ghét',
  'Uygunsuz / cinsel içerik': 'Nội dung không phù hợp / khiêu dâm',
  'Şiddet veya tehlikeli içerik': 'Bạo lực hoặc nội dung nguy hiểm',
  'Telif hakkı ihlali': 'Vi phạm bản quyền',
  'Şikayetin alındı, teşekkürler': 'Đã nhận báo cáo của bạn, cảm ơn',
  'Hesabımı Sil': 'Xóa tài khoản của tôi',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Tài khoản và toàn bộ dữ liệu của bạn (lịch sử xem, đánh giá, bình luận, danh sách, tin nhắn) sẽ bị xóa vĩnh viễn. Không thể hoàn tác.',
  'Şifreni gir': 'Nhập mật khẩu của bạn',
  'Hesabımı kalıcı sil': 'Xóa vĩnh viễn tài khoản của tôi',
  'Sesli mesaj': 'Tin nhắn thoại',
  'Ses gönderilemedi': 'Không thể gửi tin nhắn thoại',
  'Kaydediliyor…': 'Đang ghi…',
  'Ses oynatılamadı': 'Không phát được âm thanh',
  'Oynat': 'Phát',
  'Duraklat': 'Tạm dừng',
  'Liste görünümü': 'Xem danh sách',
  'Takvim görünümü': 'Xem lịch',
  'Önceki ay': 'Tháng trước',
  'Sonraki ay': 'Tháng sau',
  'Bu gün bölüm yok': 'Không có tập nào ngày này',
  'Gizlilik Politikası': 'Chính sách Quyền riêng tư',
  'Son güncelleme: {}': 'Cập nhật lần cuối: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Chính sách này giải thích dữ liệu nào được thu thập, được sử dụng ra sao và bạn có những quyền gì khi dùng ứng dụng dizi.jpg và trang dizijpg.com.',
  'Topladığımız Veriler': 'Dữ liệu chúng tôi thu thập',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Tài khoản: địa chỉ email, tên người dùng và mật khẩu. Mật khẩu được lưu dưới dạng băm không thể đảo ngược; tài khoản khách có thể dùng mà không cần email.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Hồ sơ: những thông tin bạn tự chọn thêm, như ảnh đại diện, ảnh bìa, tiểu sử và quốc gia.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Sử dụng: lịch sử xem, điểm đánh giá, bình luận, danh sách, cảm xúc và mục yêu thích của bạn.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Tin nhắn: tin nhắn văn bản, hình ảnh và thoại của bạn được lưu trên máy chủ của chúng tôi. Tin nhắn không được mã hóa đầu cuối; chỉ được xem xét cho mục đích kiểm duyệt khi bị báo cáo.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Nội dung tải lên: ảnh, GIF, video và bản ghi âm bạn thêm vào hồ sơ, bình luận và tin nhắn.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Kỹ thuật: địa chỉ IP, vị trí ước chừng (cấp quốc gia/thành phố), nền tảng thiết bị, phiên bản ứng dụng và nhật ký lỗi. Chúng được lưu để bảo mật và khắc phục sự cố.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Thông báo: để gửi thông báo đẩy, chúng tôi lưu token thiết bị và ngôn ngữ bạn chọn. Bạn có thể tắt thông báo bất cứ lúc nào trong cài đặt thiết bị.',
  'Verileri Nasıl Kullanırız': 'Cách chúng tôi dùng dữ liệu',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Chúng tôi chỉ dùng dữ liệu của bạn để cung cấp dịch vụ, bảo vệ tài khoản, gửi thông báo, sửa lỗi và ngăn lạm dụng. Chúng tôi không bán dữ liệu của bạn và không chia sẻ với ai vì mục đích quảng cáo.',
  'Çerezler ve Yerel Depolama': 'Cookie và bộ nhớ cục bộ',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Bộ nhớ cục bộ chỉ dùng để giữ bạn đăng nhập và ghi nhớ các tùy chọn như ngôn ngữ, giao diện. Không có cookie quảng cáo hay theo dõi.',
  'Üçüncü Taraf Hizmetler': 'Dịch vụ bên thứ ba',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'Dữ liệu phim và series lấy từ TMDB, thông tin nền tảng streaming từ JustWatch. Thông báo đẩy được gửi qua Google Firebase, lưu lượng trang được Cloudflare bảo vệ. Các dịch vụ này tuân theo chính sách quyền riêng tư của riêng họ.',
  'Saklama ve Silme': 'Lưu trữ và xóa',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Dữ liệu của bạn được giữ chừng nào tài khoản còn tồn tại. Với "Xóa tài khoản của tôi" trong Cài đặt, bạn có thể xóa tài khoản vĩnh viễn; dữ liệu bị xóa ngay lập tức, các bản sao trong bản sao lưu chậm nhất trong 14 ngày. Nhật ký lỗi tự động xóa sau 30 ngày.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'Bạn có thể xuất dữ liệu dưới dạng ZIP từ Cài đặt; tệp lưu trữ sẽ được gửi tới địa chỉ email của bạn.',
  'Güvenlik': 'Bảo mật',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Dữ liệu được truyền qua kết nối mã hóa (HTTPS) và lưu trên các máy chủ có quyền truy cập hạn chế.',
  'Çocukların Gizliliği': 'Quyền riêng tư của trẻ em',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg không dành cho trẻ em dưới 13 tuổi.',
  'Hakların': 'Quyền của bạn',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Theo KVKK và GDPR, bạn có quyền truy cập, sửa, xóa và chuyển dữ liệu của mình. Hãy viết cho chúng tôi về những việc này: {}',
  'Değişiklikler': 'Thay đổi',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Nếu chính sách này thay đổi, phiên bản mới sẽ được đăng trên trang này và ngày cập nhật sẽ được làm mới.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Khi đăng ký, bạn chấp nhận {}.',
  'Kullanıcılar': 'Người dùng',
  'Fotoğrafı değiştir': 'Đổi ảnh',
  'Yeniden konumlandır': 'Căn chỉnh lại',
  'Bir şeyler ters gitti': 'Đã xảy ra lỗi',
  'Sosyal Bağlantılar': 'Liên kết mạng xã hội',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Hồ sơ của bạn hiển thị tối đa 3 liên kết.',
  'Platform seç': 'Chọn nền tảng',
  'Kullanıcı adın': 'Tên người dùng của bạn',
  'Ekle': 'Thêm',
  'Kaldır': 'Gỡ',
  'Kopyalandı: {}': 'Đã sao chép: {}',
  'Geçersiz kullanıcı adı': 'Tên người dùng không hợp lệ',
  'Bağlantı ekle': 'Thêm liên kết',
  'Spoiler olabilir — dokun ve gör': 'Có thể chứa spoiler — chạm để xem',
  'Beğeni': 'Lượt thích',
  'Beğen': 'Thích',
  'Görüntülenme': 'Lượt xem',
  'Tam ekran': 'Toàn màn hình',
  'Arama başarısız': 'Tìm kiếm thất bại',
  'Sonuç bulunamadı': 'Không có kết quả',
  'Dizi ve Filmler': 'Phim bộ & phim lẻ',
  'Kişiler': 'Người',
  'Ana Sayfa': 'Trang chủ',
  'Paylaş': 'Chia sẻ',
  'Yanıtlar': 'Trả lời',
  'Yaklaşan Bölümler': 'Tập sắp phát sóng',
  'Yetişme Listesi': 'Danh sách xem bù',
  'Şunu mu demek istedin': 'Có phải bạn muốn tìm',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — chạm để xem',
  'uyum': 'tương hợp',
  'Uyum': 'Tương hợp',
  '{} ortak dizi': '{} phim bộ chung',
  '{} ortak film': '{} phim lẻ chung',
  'Bildirim Tercihleri': 'Tùy chọn thông báo',
  'Beğeniler': 'Lượt thích',
  'Yeni takipçiler': 'Người theo dõi mới',
  'Etiketlenmeler': 'Nhắc đến',
  'Yeniden izledim': 'Đã xem lại',
  '{}. kez izlendi': 'Đã xem {} lần',
  'Gönderi bulunamadı': 'Không tìm thấy bài đăng',
  'Gözat': 'Duyệt',
  'Diziler': 'Phim bộ',
  'Filmler': 'Phim lẻ',
  'Tümü': 'Tất cả',
  'Farklı bir tür seç.': 'Thử thể loại khác.',
  'Gizlilik': 'Quyền riêng tư',
  'İzlediklerimi gizle': 'Ẩn những gì tôi đã xem',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Các series và phim bạn đã xem sẽ không hiển thị trên hồ sơ của bạn',
  'Yorumlarımı gizle': 'Ẩn bình luận của tôi',
  'Profilinde yorumların görünmez':
      'Bình luận của bạn sẽ không hiển thị trên hồ sơ của bạn',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Bạn có thể ẩn một series hoặc phim cụ thể bằng nút "Ẩn trên hồ sơ của tôi" ở trang nội dung.',
  'Geri Bildirim': 'Phản hồi',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Viết ý kiến và góp ý của bạn về ứng dụng...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Cảm ơn! Đã nhận được phản hồi của bạn.',
  'Profilimde gizle': 'Ẩn trên hồ sơ của tôi',
  'Yorumları': 'Bình luận của họ',
  'Bu kullanıcı henüz bir şey izlememiş.': 'Người dùng này chưa xem gì cả.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Người dùng này muốn giữ kín bình luận của mình.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Dữ liệu: JustWatch',
  'Web Sitesi': 'Trang web',
  'Diğer uygulamalar': 'Ứng dụng khác',
  'Bağlantıyı kopyala': 'Sao chép liên kết',
  'Henüz kimseyi takip etmiyorsun.': 'Bạn chưa theo dõi ai.',
  'Çevir': 'Dịch',
  'Çeviri şu an yapılamadı': 'Hiện chưa dịch được',
  'Bağlantı açılamadı': 'Không mở được liên kết',
  'Orijinali göster': 'Xem bản gốc',
  'Çeviriyi göster': 'Xem bản dịch',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Tháng này chưa có tập nào được công bố ngày phát sóng. Ngày thường được công bố trước vài tuần và sẽ hiện ở đây.',
  'devamı': 'thêm',
  'Google ile devam et': 'Tiếp tục với Google',
  'Google girişi başarısız': 'Đăng nhập Google không thành công',
  'Veri tasarrufu': 'Tiết kiệm dữ liệu',
  'Wi-Fi ağında veri tasarrufu': 'Tiết kiệm dữ liệu khi dùng Wi-Fi',
  'Mobil veride veri tasarrufu': 'Tiết kiệm dữ liệu khi dùng mạng di động',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Khi bật, ảnh không được tải trước; chỉ tải khung hình bạn đang xem.',
  'Çocuk güvenliği': 'An toàn trẻ em',
  'Türk Filmleri': 'Phim Thổ Nhĩ Kỳ',
  'En Yüksek Puanlı Filmler': 'Phim được đánh giá cao nhất',
  'En Yüksek Puanlı Diziler': 'Phim bộ được đánh giá cao nhất',
  'En Çok İzlenen Filmler': 'Phim được xem nhiều nhất',
  'Popüler Diziler': 'Phim bộ phổ biến',
  'En Çok Kazanan Filmler': 'Phim doanh thu cao nhất',
  'Kült Filmler': 'Phim cult',
  'Yeni Filmler': 'Phim mới',
  'Yorum yap': 'Bình luận',
  'Henüz yorum yok': 'Chưa có bình luận',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Bình luận bạn viết cho phim bộ và phim lẻ sẽ gom về đây.',
  'GIF ekle': 'Thêm GIF',
  'İlk yorumu sen yaz': 'Hãy là người bình luận đầu tiên',
  'Video altyazıları': 'Phụ đề video',
  'Videolarda altyazı göster': 'Hiển thị phụ đề trên video',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Câu nói trong video được viết trên màn hình. Văn bản được dịch: tiếng Anh trong tiếng Thổ Nhĩ Kỳ, tiếng Thổ Nhĩ Kỳ bằng các ngôn ngữ khác.',
  "Güncelleme gerekli": "Cần cập nhật",
  "Yeni sürüm var": "Đã có phiên bản mới",
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      "Cài đặt phiên bản mới của dizi.jpg để tiếp tục.",
  "Güncelle": "Cập nhật",
  "Daha sonra": "Để sau",
  'Takvim güncelleniyor': 'Đang cập nhật lịch',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Không thể cập nhật lịch, đang hiển thị danh sách cũ',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Một số phim không tải được, danh sách có thể chưa đầy đủ',
  'Yenile': 'Làm mới',
  'Devam etmek için giriş yap': 'Đăng nhập để tiếp tục',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Một tài khoản miễn phí là đủ để chấm điểm, bình luận và xây dựng thư viện của bạn.',
  'Şimdi değil': 'Để sau',
  'Yorum yazmak için giriş yap': 'Đăng nhập để viết bình luận',
  'Kişilere göndermek için giriş yap': 'Đăng nhập để gửi cho mọi người',
  'Beğenenler': 'Luot thich',
  'Henüz beğeni yok': 'Chua co luot thich nao',
  'Bu gönderiyi ilk beğenen sen ol': 'Hay la nguoi dau tien thich bai nay',
  'Bu gönderiye yanıt': 'Tra loi bai dang nay',
  'Spoiler içeren gönderi': 'Bài viết có tiết lộ nội dung',
  'Görsel gönderi': 'Bài viết hình ảnh',
  'Bu yorumu profilimde gizle': 'Ẩn bình luận này trên hồ sơ của tôi',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Bình luận vẫn còn trên trang phim bộ và phim',
  'Bu yorumu sil': 'Xóa bình luận này',
  'Yorum profilinde gizlendi': 'Đã ẩn bình luận trên hồ sơ của bạn',
  'Geri al': 'Hoàn tác',
  'Yorum silinsin mi?': 'Xóa bình luận này chứ?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Bình luận này sẽ bị xóa vĩnh viễn ở mọi nơi. Không thể hoàn tác.',
  'Yorum silindi': 'Đã xóa bình luận',
  'Yorum profilinde tekrar görünüyor':
      'Bình luận hiển thị lại trên hồ sơ của bạn',
  'Gizlenen yorumun yok': 'Không có bình luận nào bị ẩn',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Các bình luận bạn ẩn bằng cách nhấn giữ một bài viết trong tab Bình luận trên hồ sơ sẽ được lưu tại đây.',
  'Gizlenen yorumlar': 'Bình luận đã ẩn',
  'Gönderiye git': 'Đi đến bài viết',
  'Tekrar göster': 'Hiện lại',
  'Yanıtlarımı gizle': 'Ẩn câu trả lời của tôi',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Câu trả lời bạn viết trên bài viết của người khác chỉ mình bạn nhìn thấy',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Hiện lại các bình luận bạn đã ẩn trên hồ sơ',
  'Sıralama': 'Sắp xếp',
  'Önerilen': 'Đề xuất',
  'Kronolojik': 'Theo thời gian',
  'Gelen mesaj istekleri': 'Yêu cầu tin nhắn đến',
  'Mesaj isteğin yok': 'Không có yêu cầu tin nhắn',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Tin nhắn từ những người bạn không theo dõi sẽ xuất hiện ở đây.',
  'Çevrimiçi durumumu gizle': 'Ẩn trạng thái trực tuyến của tôi',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Người khác sẽ không thấy trạng thái trực tuyến và lần cuối hoạt động của bạn trong tin nhắn',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Một trong những người dùng đầu tiên của chúng tôi. Phản hồi của họ đã giúp ứng dụng trở thành như hôm nay.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Bạn là một trong những người dùng đầu tiên của chúng tôi. Phản hồi của bạn đã giúp ứng dụng trở thành như hôm nay.',
  'İleri': 'Tiếp',
  'Seçilen dosya okunamadı': 'Không thể đọc tệp đã chọn',
  'Video açılamadı': 'Không thể mở video',
  'En fazla {} medya seçebilirsin': 'Bạn có thể chọn tối đa {} mục',
  'Hiçbir medya yüklenemedi': 'Không tải lên được media nào',
  'Seçimi kaldır': 'Bỏ chọn',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'Mỗi bình luận có thể tải lên tổng cộng {} MB',
  '{} dosya okunamadı': 'Không đọc được {} tệp',
  '{} medya eklendi, {} yüklenemedi': 'Đã thêm {} mục, {} thất bại',
  'Kırp': 'Cắt',
  'Çiz': 'Vẽ',
  'Metin': 'Văn bản',
  'Emoji': 'Biểu tượng',
  'Yinele': 'Làm lại',
  'Daha fazla': 'Thêm',
  'Hazırlanıyor…': 'Đang chuẩn bị…',
  'Düzenlemeden çık?': 'Thoát khỏi chỉnh sửa?',
  'Yaptığın değişiklikler kaybolacak.': 'Các thay đổi của bạn sẽ bị mất.',
  'Çık': 'Thoát',
  'Serbest çizim': 'Vẽ tay',
  'Ok': 'Mũi tên',
  'Dikdörtgen': 'Hình chữ nhật',
  'Daire': 'Hình tròn',
  'Bulanıklaştır': 'Làm mờ',
  'Pikselleştir': 'Làm vỡ hình',
  'Silgi': 'Tẩy',
  'Çizgi kalınlığı': 'Độ dày nét',
  'Saydamlık': 'Độ mờ',
  'Dolgu': 'Tô màu',
  'Renk': 'Màu',
  'Döndür': 'Xoay',
  'Yansıt': 'Lật',
  'Oran': 'Tỉ lệ',
  'Sıfırla': 'Đặt lại',
  'Serbest': 'Tự do',
  'Metin yaz...': 'Nhập văn bản...',
  'Hizala': 'Căn chỉnh',
  'Arka plan': 'Nền',
  'Emoji ara...': 'Tìm biểu tượng...',
  'Son kullanılanlar': 'Gần đây',
  'İfadeler ve insanlar': 'Mặt cười và người',
  'Hayvanlar ve doğa': 'Động vật và thiên nhiên',
  'Yiyecek ve içecek': 'Đồ ăn và thức uống',
  'Etkinlikler': 'Hoạt động',
  'Seyahat ve yerler': 'Du lịch và địa điểm',
  'Nesneler': 'Đồ vật',
  'Semboller': 'Ký hiệu',
  'Bayraklar': 'Cờ',
  'Görseli düzenle': 'Chỉnh sửa ảnh',
  'Düzenlendi': 'Đã chỉnh sửa',
  'Düzenlenemedi': 'Không thể chỉnh sửa',
  'Düzenlenen görsel çok büyük': 'Ảnh đã chỉnh sửa quá lớn',
  'Videoyu düzenle': 'Chỉnh sửa video',
  'Sesi kapat': 'Tắt tiếng',
  'Sesi aç': 'Bật tiếng',
  'İptal ediliyor…': 'Đang hủy…',
  'Bu biraz sürebilir': 'Việc này có thể mất một lúc',
  'Video çok büyük': 'Video quá lớn',
  'Video hazırlanamadı': 'Không thể chuẩn bị video',
  'Başlangıç': 'Bắt đầu',
  'Bitiş': 'Kết thúc',
  'En çok {} saniye seçebilirsin': 'Bạn có thể chọn tối đa {} giây',
  'Dosya en fazla {} MB olabilir': 'Tệp tối đa {} MB',
  'Medya ekle': 'Thêm phương tiện',
  'Seçili medya kalmadı': 'Chưa chọn phương tiện nào',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Chọn ảnh hoặc video để thêm vào bình luận của bạn.',
  'Medya seç': 'Chọn phương tiện',
  'Daha fazla ekle': 'Thêm nữa',
  'Medya seçilemedi': 'Không thể chọn phương tiện',
  'Favori oyuncular': 'Diễn viên yêu thích',
  'Henüz favori oyuncun yok': 'Chưa có diễn viên yêu thích',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Mở trang diễn viên và chạm vào trái tim ở góc trên bên phải để thêm vào đây.',
  '{} yapımdan {} tanesini izledin': 'Bạn đã xem {} trong {} tựa',
  'izledin': 'đã xem',
  'İzlemedin': 'Chưa xem',
  'Yapım bulunamadı': 'Không tìm thấy tựa nào',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Người này không có phim hay series nào để liệt kê.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Lịch sử xem gắn với tài khoản của bạn; danh sách này chỉ của bạn.',
  'Hesabın kalıcı olarak askıya alındı':
      'Tài khoản của bạn đã bị khóa vĩnh viễn',
  'Hesabın geçici olarak askıya alındı':
      'Tài khoản của bạn đã bị khóa tạm thời',
  'Hesabın askıya alındı': 'Tài khoản của bạn đang bị khóa',
  'Sebep': 'Lý do',
  'Kalan süre': 'Thời gian còn lại',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Tài khoản sẽ tự mở lại khi hết thời gian',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'Trong thời gian này bạn vẫn có thể đọc, nhưng không thể đăng bài, bình luận hay gửi tin nhắn.',
  'Anladım': 'Đã hiểu',
  'Ayrıntı': 'Chi tiết',
  '{} dakika': '{} phút',
  'birkaç saniye': 'vài giây',
  'Karara itiraz et': 'Khiếu nại quyết định này',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Giải thích vì sao nên gỡ bỏ hình phạt này',
  'İtirazını gönder': 'Gửi khiếu nại',
  'İtirazın incelemede': 'Khiếu nại của bạn đang được xem xét',
  'İtirazın reddedildi': 'Khiếu nại của bạn đã bị từ chối',
  'İtirazın alındı, inceleniyor': 'Đã nhận khiếu nại của bạn và đang xem xét',
  'İtiraz en az 10 karakter olmalı': 'Khiếu nại phải có ít nhất 10 ký tự',
  'Yükleniyor...': 'Đang tải...',
  'Bu bölüme puan ver': 'Đánh giá tập này',
  '{} kişi puanladı': '{} người đã đánh giá',
  'Bölüm izlendi olarak işaretlendi': 'Đã đánh dấu tập này là đã xem',
  'Sesli ara': 'Cuộc gọi thoại',
  'Görüntülü ara': 'Cuộc gọi video',
  'Çalıyor...': 'Đang đổ chuông...',
  'Bağlanıyor...': 'Đang kết nối...',
  'Cevapla': 'Trả lời',
  'Reddet': 'Từ chối',
  'Sessize al': 'Tắt tiếng',
  'Hoparlör': 'Loa ngoài',
  'Kamerayı kapat': 'Tắt camera',
  'Kamerayı çevir': 'Đổi camera',
  'Cevap yok': 'Không có phản hồi',
  'Arama reddedildi': 'Cuộc gọi bị từ chối',
  'Meşgul': 'Đang bận',
  'Bağlanılamadı': 'Không thể kết nối',
  'Arama iptal edildi': 'Cuộc gọi đã bị hủy',
  'Arama geçmişi': 'Lịch sử cuộc gọi',
  'Gelen arama': 'Cuộc gọi đến',
  'Giden arama': 'Cuộc gọi đi',
  'Cevapsız arama': 'Cuộc gọi nhỡ',
  'Arama şu anda kullanılamıyor': 'Hiện chưa thể gọi',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Cuộc gọi video đang tắt, bạn có thể gọi thoại',
  'Bu kullanıcıyı arayamazsın': 'Bạn không thể gọi người dùng này',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Hai bạn phải theo dõi lẫn nhau mới gọi được',
  'Bu kullanıcı şu anda aranamıyor': 'Hiện không thể gọi người dùng này',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Quá nhiều cuộc gọi nhỡ. Thử lại sau {}',
  'Zaten bir aramadasın': 'Bạn đang trong một cuộc gọi',
  'Arama için mikrofon izni gerekiyor': 'Cần quyền micrô để gọi',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'Cần quyền camera và micrô cho cuộc gọi video',
  'Arama başlatılamadı': 'Không thể bắt đầu cuộc gọi',
  'Kullanıcı bulunamadı': 'Không tìm thấy người dùng',
  'Kendini arayamazsın': 'Bạn không thể tự gọi cho mình',
  'Arama artık geçerli değil': 'Cuộc gọi này không còn hiệu lực',
  'Bu aramanın tarafı değilsin': 'Bạn không thuộc cuộc gọi này',
  'Arama bulunamadı': 'Không tìm thấy cuộc gọi',
  'Çok fazla istek, biraz bekle': 'Quá nhiều yêu cầu, hãy đợi một chút',
  'Bağlantı koptu': 'Mất kết nối',
  'Arama süre sınırına ulaştı': 'Cuộc gọi đã đạt giới hạn thời gian',
  'Arama en fazla 4 saat sürebilir': 'Một cuộc gọi kéo dài tối đa 4 giờ',
  'Arama sona erdi': 'Cuộc gọi đã kết thúc',
  'Sesli arama': 'Cuộc gọi thoại',
  'Görüntülü arama': 'Cuộc gọi video',
  'Gelen aramalar': 'Cuộc gọi đến',
  'Sesli ve görüntülü arama bildirimleri': 'Thông báo cuộc gọi thoại và video',
  '{} sa': '{} giờ',
  'Sesli ve Görüntülü Aramalar': 'Cuộc gọi thoại và video',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Nội dung cuộc gọi không bao giờ được ghi lại. Âm thanh và hình ảnh được mã hóa đầu cuối (DTLS-SRTP) giữa các thiết bị; máy chủ của chúng tôi không thể giải mã, nghe lén hay lưu trữ luồng dữ liệu này.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Chỉ siêu dữ liệu cuộc gọi được lưu: với ai, theo chiều nào, khi nào và kéo dài bao lâu. Các bản ghi này tự động bị xóa sau 90 ngày.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Nếu không thể kết nối trực tiếp, âm thanh và hình ảnh sẽ đi qua máy chủ chuyển tiếp (TURN) ở dạng đã mã hóa. Máy chủ chuyển tiếp cũng không thể giải mã hay ghi lại nội dung.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Micrô chỉ được dùng trong cuộc gọi thoại hoặc video, còn camera chỉ dùng trong cuộc gọi video. Cả hai đều tắt khi cuộc gọi kết thúc.',
  'Takip ettiğin {} kişi izledi': '{} người bạn theo dõi đã xem',
  'Yorum yaz...': 'Viết bình luận...',
  'Sıradaki bölüm': 'Tập tiếp theo',
  'Doğrulanmış testçi': 'Người thử nghiệm đã xác minh',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Thông báo theo dõi, thích, trả lời, tin nhắn và gắn thẻ',
  'Sen': 'Bạn',
  'Aradığınız kişide sesli arama devre dışı': 'Người này đã tắt cuộc gọi thoại',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Người này đã tắt cuộc gọi video',
  'Sesli aramalara izin ver': 'Cho phép cuộc gọi thoại',
  'Görüntülü aramalara izin ver': 'Cho phép cuộc gọi video',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Khi tắt, không ai có thể gọi thoại cho bạn; người gọi sẽ thấy thông báo',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Khi tắt, không ai có thể gọi video cho bạn; người gọi sẽ thấy thông báo',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Cuộc gọi thoại đang tắt. Bạn có thể bật trong Cài đặt > Quyền riêng tư.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Cuộc gọi video đang tắt. Bạn có thể bật trong Cài đặt > Quyền riêng tư.',
  'Sesli ve görüntülü arama': 'Cuộc gọi thoại và video',
};
