/// Otomatik üretilen çeviri haritası (th).
const Map<String, String> cevirilerTh = {
  'Hepsini gördün, baştan gösteriyoruz':
      'คุณได้เห็นมาหมดแล้ว เราแสดงให้คุณเห็นตั้งแต่ต้น',
  'Aktarılacak tanınan veri bulunamadı.': 'ไม่พบข้อมูลที่นำเข้าได้',
  'Arama': 'ค้นหา',
  'Aramaya başla': 'เริ่มค้นหาเลย',
  'Son aramalar': 'การค้นหาล่าสุด',
  'Ayarlar': 'การตั้งค่า',
  'Bağla': 'เชื่อมบัญชี',
  'Bio': 'ประวัติ',
  'Bitirdim': 'ดูจบแล้ว',
  'Bunları da Beğenebilirsin': 'คุณอาจชอบเรื่องเหล่านี้',
  'Bölüm': 'ตอน',
  'Bıraktım': 'เลิกดูแล้ว',
  'Dil': 'ภาษา',
  'Dil ara...': 'ค้นหาภาษา...',
  'Dizi': 'ซีรีส์',
  'Dizi ve filmlerini takip et': 'ติดตามซีรีส์และหนังของคุณ',
  'Dizi yorumu': 'คอมเมนต์ซีรีส์',
  'Dizi, film veya kişi ara...': 'ค้นหาซีรีส์ หนัง หรือบุคคล...',
  'Dosya en fazla 30MB olabilir': 'ไฟล์ต้องไม่เกิน 30MB',
  'Dosya en fazla {}MB olabilir': 'ไฟล์ต้องไม่เกิน {}MB',
  'E-posta': 'อีเมล',
  'E-posta veya kullanıcı adı': 'อีเมลหรือชื่อผู้ใช้',
  'En az 2 harf yaz': 'พิมพ์อย่างน้อย 2 ตัวอักษร',
  'Film': 'หนัง',
  'Film yorumu': 'คอมเมนต์หนัง',
  'Fotoğraf / video ekle': 'เพิ่มรูปภาพ / วิดีโอ',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'รูปภาพหรือ GIF — รูปโปรไฟล์และรูปปก',
  'Giriş Yap': 'เข้าสู่ระบบ',
  'Gönder': 'ส่ง',
  'Gönderildi': 'ส่งแล้ว',
  'Haftanın Dizileri': 'ซีรีส์ประจำสัปดาห์',
  'Haftanın Filmleri': 'หนังประจำสัปดาห์',
  'Henüz izleme kaydın yok': 'ยังไม่มีประวัติการดู',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'ยังไม่มีลิสต์ — สร้างได้จากแท็บโปรไฟล์',
  'Henüz yorum yok.': 'ยังไม่มีคอมเมนต์',
  'Hesabın bağlandı!': 'เชื่อมบัญชีสำเร็จแล้ว!',
  'Hesabın yok mu? Kayıt ol': 'ยังไม่มีบัญชี? สมัครสมาชิก',
  'Hesabını Bağla': 'เชื่อมบัญชีของคุณ',
  'Hesap Oluştur': 'สร้างบัญชี',
  'Kapak resmi ekle': 'เพิ่มรูปปก',
  'Kaydet': 'บันทึก',
  'Kendinden bahset...': 'เล่าเกี่ยวกับตัวคุณ...',
  'Keşfet': 'สำรวจ',
  'Kimseyi takip etmiyor': 'ยังไม่ได้ติดตามใคร',
  'Kişi ara': 'ค้นหาบุคคล',
  'Kişi yorumu': 'คอมเมนต์บุคคล',
  'Konuk Oyuncular': 'นักแสดงรับเชิญ',
  'Kullanıcı adı (küçük harf)': 'ชื่อผู้ใช้ (ตัวพิมพ์เล็ก)',
  'Kullanıcı adı ara...': 'ค้นหาชื่อผู้ใช้...',
  'Liste adı': 'ชื่อลิสต์',
  'Listeye Ekle': 'เพิ่มลงลิสต์',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'คุณกำลังใช้บัญชีผู้เยี่ยมชม — เชื่อมอีเมลไว้ จะได้ไม่เสียข้อมูล!',
  'Misafir olarak devam et': 'ดำเนินการต่อในฐานะผู้เยี่ยมชม',
  'Oluştur': 'สร้าง',
  'Oyuncular': 'นักแสดง',
  'Profil': 'โปรไฟล์',
  'Profil kaydedildi': 'บันทึกโปรไฟล์แล้ว',
  'Puanla': 'ให้คะแนน',
  'Puanı Sil': 'ลบคะแนน',
  'Puanın': 'คะแนนของคุณ',
  'Sezonlar': 'ซีซัน',
  'Sunucu hatası ({})': 'เซิร์ฟเวอร์ผิดพลาด ({})',
  'S{} · {}. Bölüm': 'S{} · ตอนที่ {}',
  'S{}B{} yorumu': 'คอมเมนต์ S{}E{}',
  'Takibi Bırak': 'เลิกติดตาม',
  'Takip': 'กำลังติดตาม',
  'Takip Edilenler': 'กำลังติดตาม',
  'Takip Et': 'ติดตาม',
  'Takipçi': 'ผู้ติดตาม',
  'Takipçi yok': 'ยังไม่มีผู้ติดตาม',
  'Takipçiler': 'ผู้ติดตาม',
  'Takvim': 'ปฏิทิน',
  'Tamam': 'ตกลง',
  'Tekrar Dene': 'ลองอีกครั้ง',
  'Tekrar dene': 'ลองอีกครั้ง',
  'Toplam İzleme Süresi': 'เวลาดูทั้งหมด',
  'Tüm Zamanların En İyileri': 'สุดยอดตลอดกาล',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'ส่งออกข้อมูลทั้งหมดของคุณ (การดู คะแนน คอมเมนต์ ลิสต์) เป็น ZIP ที่ใช้ได้กับ TV Time หรือนำเข้า ZIP จากแอปอื่น',
  'Tümünü Kaldır': 'เอาออกทั้งหมด',
  'Tümünü İzledim': 'ดูครบทุกตอนแล้ว',
  'Türk Dizileri': 'ซีรีส์ตุรกี',
  'Veri içe aktar (.zip)': 'นำเข้าข้อมูล (.zip)',
  'Verilerim': 'ข้อมูลของฉัน',
  'Verilerimi dışa aktar (e-posta)': 'ส่งออกข้อมูลของฉัน (อีเมล)',
  'Verilerini dışa aktar': 'ส่งออกข้อมูลของคุณ',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'ไม่มีตอนที่กำลังจะมาถึง\nไปที่หน้ารายละเอียดซีรีส์แล้วตั้งเป็น "กำลังดู" เพื่อติดตามตอนใหม่ที่นี่',
  'Yapımları': 'ผลงาน',
  'Yeni Diziler': 'ซีรีส์มาใหม่',
  'Yeni Liste': 'ลิสต์ใหม่',
  'Yeni kullanıcı adı (isteğe bağlı)': 'ชื่อผู้ใช้ใหม่ (ไม่บังคับ)',
  'Yorum': 'คอมเมนต์',
  'Yorumunu yaz...': 'เขียนคอมเมนต์ของคุณ...',
  'Zaten hesabın var mı? Giriş yap': 'มีบัญชีอยู่แล้ว? เข้าสู่ระบบ',
  'ort. {}': 'เฉลี่ย {}',
  'takip': 'กำลังติดตาม',
  'takipçi': 'ผู้ติดตาม',
  '{} / {} bölüm': '{} / {} ตอน',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} เดือน',
  '{} ay~tekil': '{} เดือน',
  '{} bölüm izlendi': 'ดูแล้ว {} ตอน',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} นาที',
  '{} dk~tekil': '{} นาที',
  '{} gün': '{} วัน',
  '{} gün~tekil': '{} วัน',
  '{} içerik': '{} รายการ',
  '{} içerik · otomatik': '{} รายการ · อัตโนมัติ',
  '{} kayıt atlandı (eşleşmedi).': 'ข้าม {} รายการ (ไม่ตรงกัน)',
  '{} saat': '{} ชั่วโมง',
  '{} saat~tekil': '{} ชั่วโมง',
  '{} sezon': '{} ซีซัน',
  '{} yıl': '{} ปี',
  '{} yıl~tekil': '{} ปี',
  '{}. Bölüm': 'ตอนที่ {}',
  '{}. Sezon': 'ซีซัน {}',
  'Çıkış Yap': 'ออกจากระบบ',
  'Ülke': 'ประเทศ',
  'Ülke ara...': 'ค้นหาประเทศ...',
  'Ülke seç': 'เลือกประเทศ',
  'İlk yorumu sen yaz!': 'เป็นคนแรกที่คอมเมนต์เลย!',
  'İncelemeler': 'รีวิว',
  'İncelemen (isteğe bağlı)': 'รีวิวของคุณ (ไม่บังคับ)',
  'İptal': 'ยกเลิก',
  'İzlediklerim': 'ประวัติการดู',
  'İzledim': 'ดูแล้ว',
  'İzledin': 'คุณดูแล้ว',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'ประวัติการดูและลิสต์ของคุณจะถูกเก็บไว้ และตอนนี้เข้าสู่ระบบได้จากทุกอุปกรณ์',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'ประวัติการดู คะแนน คอมเมนต์ และลิสต์ของคุณจะถูกส่งเป็นไฟล์ ZIP ไปยังอีเมลที่ลงทะเบียนไว้',
  'İzleyeceğim': 'จะดู',
  'İzliyorum': 'กำลังดู',
  'İçe aktarım tamamlandı': 'นำเข้าข้อมูลเสร็จแล้ว',
  'Şifre': 'รหัสผ่าน',
  '• profil bilgisi': '• ข้อมูลโปรไฟล์',
  '• {} dizi durumu': '• สถานะซีรีส์ {} รายการ',
  '• {} izleme kaydı': '• ประวัติการดู {} รายการ',
  '• {} liste': '• ลิสต์ {} รายการ',
  '• {} puan': '• คะแนน {} รายการ',
  '• {} yorum': '• คอมเมนต์ {} รายการ',
  '{}+ yapım': '{}+ ผลงาน',
  'Yorumlar': 'คอมเมนต์',
  'Yorumlar ({})': 'คอมเมนต์ ({})',
  'Yorumları ({})': 'คอมเมนต์ของเขา ({})',
  'Listelerim': 'ลิสต์ของฉัน',
  'Nereden izledin?': 'ดูจากที่ไหน?',
  'Diziye git': 'ไปที่ซีรีส์',
  'TV / Kanal': 'ทีวี / ช่อง',
  'Sinema': 'โรงภาพยนตร์',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'อื่น ๆ',
  'Akış': 'ฟีด',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'ฟีดของคุณว่างเปล่า\nเมื่อมีคนคอมเมนต์ซีรีส์และหนังที่คุณดู จะแสดงที่นี่',
  'Listeleri ({})': 'ลิสต์ ({})',
  'Liste boş.': 'ลิสต์นี้ว่างเปล่า',
  'Yanıtla': 'ตอบกลับ',
  '@{} kullanıcısına yanıt veriyorsun': 'กำลังตอบกลับ @{}',
  'İzlediğim Diziler ({})': 'ซีรีส์ที่ดูแล้ว ({})',
  'İzlediğim Filmler ({})': 'หนังที่ดูแล้ว ({})',
  'Tümünü gör': 'ดูทั้งหมด',
  'Bildirimler': 'การแจ้งเตือน',
  'Henüz bildirim yok': 'ยังไม่มีการแจ้งเตือน',
  '@{} yorumuna yanıt verdi': '@{} ตอบกลับคอมเมนต์ของคุณ',
  '@{} yorumunu beğendi': '@{} ถูกใจคอมเมนต์ของคุณ',
  '@{} seni takip etti': '@{} ติดตามคุณ',
  '@{} sana mesaj gönderdi': '@{} ส่งข้อความถึงคุณ',
  'Mesajlar': 'ข้อความ',
  'Mesaj': 'ข้อความ',
  'Mesaja eklenecek': 'จะถูกเพิ่มในข้อความ',
  'Mesajını yaz...': 'พิมพ์ข้อความ...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'ยังไม่มีแชท\nเปิดโปรไฟล์แล้วส่งข้อความเลย',
  'Şifreni mi unuttun?': 'ลืมรหัสผ่าน?',
  'Şifreyi Sıfırla': 'รีเซ็ตรหัสผ่าน',
  'E-postadaki kod': 'รหัสจากอีเมล',
  'Yeni şifre': 'รหัสผ่านใหม่',
  'Sana Özel': 'สำหรับคุณ',
  '{} özetin': 'สรุปปี {} ของคุณ',
  'Yıllık izleme istatistiklerin': 'สถิติการดูรายปี',
  'Rozetler': 'เหรียญตรา',
  'Verdiğin puan': 'คะแนนที่ให้',
  'Ortalama puanın': 'คะแนนเฉลี่ย',
  'En çok izlediğin diziler': 'ซีรีส์ที่ดูมากที่สุด',
  'İlk Bölüm': 'ตอนแรก',
  '100 Bölüm': '100 ตอน',
  '1000 Bölüm': '1000 ตอน',
  'İlk Film': 'หนังเรื่องแรก',
  '50 Film': 'หนัง 50 เรื่อง',
  'İlk Yorum': 'คอมเมนต์แรก',
  '25 Yorum': '25 คอมเมนต์',
  '10 Puan': 'ให้คะแนน 10 ครั้ง',
  'İlk Takipçi': 'ผู้ติดตามคนแรก',
  '10 Dizi Bitirdin': 'ดูจบ 10 เรื่อง',
  'İzlemeyi Bıraktım': 'เลิกดูแล้ว',
  'İzlediği Diziler ({})': 'ซีรีส์ที่ดูแล้ว ({})',
  'İzlediği Filmler ({})': 'หนังที่ดูแล้ว ({})',
  '500 Bölüm': '500 ตอน',
  '5000 Bölüm': '5000 ตอน',
  '10 Film': 'หนัง 10 เรื่อง',
  '100 Film': 'หนัง 100 เรื่อง',
  '100 Yorum': '100 คอมเมนต์',
  '50 Puan': 'ให้คะแนน 50 ครั้ง',
  '100 Puan': 'ให้คะแนน 100 ครั้ง',
  '10 Takipçi': 'ผู้ติดตาม 10 คน',
  '50 Takipçi': 'ผู้ติดตาม 50 คน',
  '25 Dizi Bitirdin': 'ดูจบ 25 เรื่อง',
  '50 Dizi Bitirdin': 'ดูจบ 50 เรื่อง',
  '10 Beğeni': '10 ไลก์',
  '100 Beğeni': '100 ไลก์',
  'yazıyor...': 'กำลังพิมพ์...',
  'ses kaydediyor...': 'กำลังอัดเสียง...',
  'Profil düzeni': 'เลย์เอาต์โปรไฟล์',
  'Konumla ve kırp': 'จัดตำแหน่งและครอบตัด',
  'Listeye eklendi': 'เพิ่มลงลิสต์แล้ว',
  'Listeyi sil?': 'ลบลิสต์?',
  'Sil': 'ลบ',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'เรื่องนี้จะถูกทำเครื่องหมายว่าไม่เคยดูและถูกลบออกจากลิสต์ของคุณ',
  'Gelecek bölüm bugün': 'ตอนต่อไปวันนี้',
  'Gelecek bölüm {} gün sonra': 'ตอนต่อไปในอีก {} วัน',
  'Tema': 'ธีม',
  'Sistem': 'ระบบ',
  'Koyu': 'มืด',
  'Açık': 'สว่าง',
  'İzleyenler': 'ผู้ชม',
  'Yorumunu yaz... (@ ile etiketle)': 'เขียนคอมเมนต์ของคุณ... (@ เพื่อแท็ก)',
  '@{} bir yorumda seni etiketledi': '@{} แท็กคุณในคอมเมนต์',
  'Mesajı sil': 'ลบข้อความ',
  'Mesaj silinemedi': 'ไม่สามารถลบข้อความได้',
  'Bağlantı geçersiz veya sayfa bulunamadı': 'ลิงก์ไม่ถูกต้องหรือไม่พบหน้า',
  "Keşfet'e dön": 'กลับไปที่สำรวจ',
  'Düzenle': 'แก้ไข',
  'Mesajı düzenle': 'แก้ไขข้อความ',
  'Yanıtlanıyor': 'กำลังตอบกลับ',
  'düzenlendi': 'แก้ไขแล้ว',
  'Fotoğraf': 'รูปภาพ',
  'Video': 'วิดีโอ',
  'İçerik': 'เนื้อหา',
  'çevrimiçi': 'ออนไลน์',
  'son görülme {} dk önce': 'เห็นล่าสุด {} นาทีที่แล้ว',
  'son görülme {} saat önce': 'เห็นล่าสุด {} ชม.ที่แล้ว',
  'son görülme {} gün önce': 'เห็นล่าสุด {} วันที่แล้ว',
  'Yorumlar yüklenemedi': 'โหลดคอมเมนต์ไม่สำเร็จ',
  'Favori': 'รายการโปรด',
  'Listeye ekle': 'เพิ่มลงในลิสต์',
  'İçerik paylaş': 'แชร์เนื้อหา',
  'Kapat': 'ปิด',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'ทุกอย่างที่คุณทำเครื่องหมายว่าดูแล้วจะรวมอยู่ที่นี่',
  'Henüz sohbetin yok': 'ยังไม่มีการสนทนา',
  'Bir profile girip mesaj gönderebilirsin.': 'เปิดโปรไฟล์แล้วส่งข้อความ',
  'Listeyi sil': 'ลบลิสต์',
  'Puan kaydedilemedi': 'ไม่สามารถบันทึกคะแนนได้',
  'Nerede İzlenir': 'รับชมได้ที่ไหน',
  'Abonelik': 'สมัครสมาชิก',
  'Kirala': 'เช่า',
  'Satın al': 'ซื้อ',
  'Devam et': 'ดำเนินการต่อ',
  'Şikayet et': 'รายงาน',
  'Engelle': 'บล็อก',
  'Engeli kaldır': 'เลิกบล็อก',
  'Kullanıcı engellendi': 'บล็อกผู้ใช้แล้ว',
  'Engel kaldırıldı': 'เลิกบล็อกแล้ว',
  'Şikayet sebebi': 'เหตุผลการรายงาน',
  'Spam veya yanıltıcı': 'สแปมหรือทำให้เข้าใจผิด',
  'Taciz veya nefret söylemi': 'การคุกคามหรือคำพูดสร้างความเกลียดชัง',
  'Uygunsuz / cinsel içerik': 'ไม่เหมาะสม / เนื้อหาทางเพศ',
  'Şiddet veya tehlikeli içerik': 'ความรุนแรงหรือเนื้อหาอันตราย',
  'Telif hakkı ihlali': 'การละเมิดลิขสิทธิ์',
  'Şikayetin alındı, teşekkürler': 'ได้รับรายงานของคุณแล้ว ขอบคุณ',
  'Hesabımı Sil': 'ลบบัญชีของฉัน',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'บัญชีและข้อมูลทั้งหมดของคุณ (ประวัติการดู คะแนน คอมเมนต์ ลิสต์ ข้อความ) จะถูกลบถาวร ไม่สามารถกู้คืนได้',
  'Şifreni gir': 'ใส่รหัสผ่านของคุณ',
  'Hesabımı kalıcı sil': 'ลบบัญชีของฉันถาวร',
  'Sesli mesaj': 'ข้อความเสียง',
  'Ses gönderilemedi': 'ส่งข้อความเสียงไม่สำเร็จ',
  'Kaydediliyor…': 'กำลังบันทึก…',
  'Ses oynatılamadı': 'เล่นเสียงไม่ได้',
  'Oynat': 'เล่น',
  'Fragmanı oynat': 'เล่นตัวอย่าง',
  'Altyazıyı aç': 'เปิดคำบรรยาย',
  'Altyazıyı kapat': 'ปิดคำบรรยาย',
  '10 saniye ileri': 'ข้ามไปข้างหน้า 10 วินาที',
  '10 saniye geri': 'ถอยหลัง 10 วินาที',
  'Duraklat': 'หยุดชั่วคราว',
  'Liste görünümü': 'มุมมองรายการ',
  'Takvim görünümü': 'มุมมองปฏิทิน',
  'Önceki ay': 'เดือนก่อนหน้า',
  'Sonraki ay': 'เดือนถัดไป',
  'Bu gün bölüm yok': 'ไม่มีตอนในวันนี้',
  'Gizlilik Politikası': 'นโยบายความเป็นส่วนตัว',
  'Son güncelleme: {}': 'อัปเดตล่าสุด: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'นโยบายนี้อธิบายว่ามีการเก็บข้อมูลอะไรบ้าง นำไปใช้อย่างไร และคุณมีสิทธิ์อะไรบ้างเมื่อใช้แอป dizi.jpg และเว็บไซต์ dizijpg.com',
  'Topladığımız Veriler': 'ข้อมูลที่เราเก็บ',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'บัญชี: ที่อยู่อีเมล ชื่อผู้ใช้ และรหัสผ่าน รหัสผ่านถูกเก็บเป็นแฮชที่ย้อนกลับไม่ได้ บัญชีผู้เยี่ยมชมใช้ได้โดยไม่ต้องมีอีเมล',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'โปรไฟล์: ข้อมูลที่คุณเลือกเพิ่มเอง เช่น อวตาร ภาพปก ประวัติย่อ และประเทศ',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'การใช้งาน: ประวัติการดู คะแนน ความคิดเห็น รายการ รีแอ็กชัน และรายการโปรดของคุณ',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'ข้อความ: ข้อความตัวอักษร รูปภาพ และเสียงของคุณถูกเก็บบนเซิร์ฟเวอร์ของเรา ข้อความไม่ได้เข้ารหัสแบบต้นทางถึงปลายทาง จะถูกตรวจดูเพื่อการดูแลเนื้อหาก็ต่อเมื่อมีการรายงานเท่านั้น',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'สื่อที่อัปโหลด: รูปภาพ GIF วิดีโอ และเสียงบันทึกที่คุณเพิ่มในโปรไฟล์ ความคิดเห็น และข้อความ',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'ข้อมูลทางเทคนิค: ที่อยู่ IP ตำแหน่งโดยประมาณ (ระดับประเทศ/เมือง) แพลตฟอร์มอุปกรณ์ เวอร์ชันแอป และบันทึกข้อผิดพลาด เก็บไว้เพื่อความปลอดภัยและการแก้ไขปัญหา',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'สถิติการใช้งาน: ประเภทอุปกรณ์ ระบบปฏิบัติการ และเบราว์เซอร์ที่ใช้เข้าใช้งานจะถูกนับรวมเป็นหมวดหมู่กว้าง ๆ ในตัวนับยอดรวมรายวัน ตัวระบุเบราว์เซอร์เองไม่ถูกเก็บไว้ และตัวเลขเหล่านี้เชื่อมโยงกับบุคคลใดไม่ได้',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'การแจ้งเตือน: สำหรับการแจ้งเตือนแบบพุช เราเก็บโทเคนอุปกรณ์และภาษาที่คุณเลือก คุณปิดการแจ้งเตือนได้ทุกเมื่อในการตั้งค่าอุปกรณ์',
  'Verileri Nasıl Kullanırız': 'เราใช้ข้อมูลอย่างไร',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'เราใช้ข้อมูลของคุณเพื่อให้บริการ ปกป้องบัญชี ส่งการแจ้งเตือน แก้ไขข้อผิดพลาด และป้องกันการใช้งานในทางที่ผิดเท่านั้น เราไม่ขายข้อมูลของคุณ และไม่แชร์ให้ใครเพื่อการโฆษณา',
  'Çerezler ve Yerel Depolama': 'คุกกี้และพื้นที่จัดเก็บในเครื่อง',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'เราใช้พื้นที่จัดเก็บในเครื่องเพียงเพื่อให้คุณล็อกอินค้างไว้ และจดจำการตั้งค่าอย่างภาษาและธีม ไม่มีคุกกี้โฆษณาหรือติดตามใด ๆ',
  'Üçüncü Taraf Hizmetler': 'บริการของบุคคลที่สาม',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'ข้อมูลซีรีส์และภาพยนตร์มาจาก TMDB ข้อมูลแพลตฟอร์มสตรีมมิงมาจาก JustWatch การแจ้งเตือนแบบพุชส่งผ่าน Google Firebase และทราฟฟิกของเว็บไซต์ได้รับการปกป้องโดย Cloudflare บริการเหล่านี้อยู่ภายใต้นโยบายความเป็นส่วนตัวของตนเอง',
  'Saklama ve Silme': 'การเก็บรักษาและการลบ',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'ข้อมูลของคุณถูกเก็บไว้ตราบเท่าที่บัญชียังอยู่ คุณลบบัญชีถาวรได้ด้วย "ลบบัญชีของฉัน" ในการตั้งค่า ข้อมูลถูกลบทันที ส่วนสำเนาในข้อมูลสำรองถูกลบภายใน 14 วันเป็นอย่างช้า บันทึกข้อผิดพลาดถูกลบอัตโนมัติหลัง 30 วัน',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'คุณส่งออกข้อมูลเป็น ZIP ได้จากการตั้งค่า ไฟล์เก็บถาวรจะถูกส่งไปยังที่อยู่อีเมลของคุณ',
  'Güvenlik': 'ความปลอดภัย',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'ข้อมูลถูกส่งผ่านการเชื่อมต่อที่เข้ารหัส (HTTPS) และเก็บบนเซิร์ฟเวอร์ที่จำกัดการเข้าถึง',
  'Çocukların Gizliliği': 'ความเป็นส่วนตัวของเด็ก',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg ไม่ได้มีไว้สำหรับเด็กอายุต่ำกว่า 13 ปี',
  'Hakların': 'สิทธิ์ของคุณ',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'ตาม KVKK และ GDPR คุณมีสิทธิ์เข้าถึง แก้ไข ลบ และโอนย้ายข้อมูลของคุณ ติดต่อเราได้ที่: {}',
  'Değişiklikler': 'การเปลี่ยนแปลง',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'หากนโยบายนี้เปลี่ยนแปลง เวอร์ชันใหม่จะถูกเผยแพร่ในหน้านี้และวันที่จะถูกอัปเดต',
  'Kayıt olarak {} kabul etmiş olursun.': 'เมื่อสมัครสมาชิก แสดงว่าคุณยอมรับ{}',
  'Kullanıcılar': 'ผู้ใช้',
  'Fotoğrafı değiştir': 'เปลี่ยนรูป',
  'Yeniden konumlandır': 'จัดตำแหน่งใหม่',
  'Bir şeyler ters gitti': 'มีบางอย่างผิดพลาด',
  'Sosyal Bağlantılar': 'ลิงก์โซเชียล',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'โปรไฟล์ของคุณแสดงลิงก์ได้สูงสุด 3 ลิงก์',
  'Platform seç': 'เลือกแพลตฟอร์ม',
  'Kullanıcı adın': 'ชื่อผู้ใช้ของคุณ',
  'Ekle': 'เพิ่ม',
  'Kaldır': 'ลบออก',
  'Kopyalandı: {}': 'คัดลอกแล้ว: {}',
  'Geçersiz kullanıcı adı': 'ชื่อผู้ใช้ไม่ถูกต้อง',
  'Bağlantı ekle': 'เพิ่มลิงก์',
  'Spoiler olabilir — dokun ve gör': 'อาจมีสปอยล์ — แตะเพื่อดู',
  'Beğeni': 'ถูกใจ',
  'beğeni': 'ถูกใจ',
  'Beğen': 'ถูกใจ',
  'Görüntülenme': 'ยอดดู',
  'görüntülenme': 'ยอดดู',
  'Tam ekran': 'เต็มจอ',
  'Arama başarısız': 'การค้นหาล้มเหลว',
  'Sonuç bulunamadı': 'ไม่พบผลลัพธ์',
  'Dizi ve Filmler': 'ซีรีส์และภาพยนตร์',
  'Kişiler': 'บุคคล',
  'Ana Sayfa': 'หน้าแรก',
  'Paylaş': 'แชร์',
  'Yanıtlar': 'การตอบกลับ',
  'Yaklaşan Bölümler': 'ตอนที่กำลังจะมาถึง',
  'Yetişme Listesi': 'รายการดูย้อนหลัง',
  'Şunu mu demek istedin': 'คุณหมายถึง',
  'Spoiler': 'สปอยล์',
  'Spoiler — dokun ve gör': 'สปอยล์ — แตะเพื่อดู',
  'uyum': 'ความเข้ากัน',
  'Uyum': 'ความเข้ากัน',
  '{} ortak dizi': 'ซีรีส์ร่วมกัน {} เรื่อง',
  '{} ortak film': 'หนังร่วมกัน {} เรื่อง',
  'Bildirim Tercihleri': 'การตั้งค่าการแจ้งเตือน',
  'Beğeniler': 'ถูกใจ',
  'Yeni takipçiler': 'ผู้ติดตามใหม่',
  'Etiketlenmeler': 'การกล่าวถึง',
  'Yeniden izledim': 'ดูอีกครั้ง',
  '{}. kez izlendi': 'ดูแล้ว {} ครั้ง',
  'Gönderi bulunamadı': 'ไม่พบโพสต์',
  'Gözat': 'เรียกดู',
  'Diziler': 'ซีรีส์',
  'Filmler': 'หนัง',
  'Tümü': 'ทั้งหมด',
  'Farklı bir tür seç.': 'ลองแนวอื่นดู',
  'Gizlilik': 'ความเป็นส่วนตัว',
  'İzlediklerimi gizle': 'ซ่อนสิ่งที่ฉันดู',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'ซีรีส์และหนังที่คุณดูจะไม่แสดงบนโปรไฟล์ของคุณ',
  'Yorumlarımı gizle': 'ซ่อนความคิดเห็นของฉัน',
  'Profilinde yorumların görünmez': 'ความคิดเห็นของคุณจะไม่แสดงบนโปรไฟล์ของคุณ',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'ซ่อนซีรีส์หรือหนังเรื่องใดเรื่องหนึ่งได้ด้วยชิป "ซ่อนบนโปรไฟล์ของฉัน" ในหน้าของเรื่องนั้น',
  'Geri Bildirim': 'ข้อเสนอแนะ',
  'Uygulama hakkında görüş ve önerini yaz...':
      'เขียนความคิดเห็นและข้อเสนอแนะเกี่ยวกับแอป...',
  'Teşekkürler! Geri bildirimin alındı.': 'ขอบคุณ! ได้รับข้อเสนอแนะของคุณแล้ว',
  'Profilimde gizle': 'ซ่อนบนโปรไฟล์ของฉัน',
  'Yorumları': 'คอมเมนต์ของเขา',
  'Bu kullanıcı henüz bir şey izlememiş.': 'ผู้ใช้รายนี้ยังไม่ได้ดูอะไรเลย',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'ผู้ใช้รายนี้เลือกที่จะซ่อนความคิดเห็นของตน',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'ข้อมูล: JustWatch',
  'Web Sitesi': 'เว็บไซต์',
  'Diğer uygulamalar': 'แอปอื่น',
  'Bağlantıyı kopyala': 'คัดลอกลิงก์',
  'Henüz kimseyi takip etmiyorsun.': 'คุณยังไม่ได้ติดตามใคร',
  'Çevir': 'แปล',
  'Çeviri şu an yapılamadı': 'ขณะนี้ยังแปลไม่ได้',
  'Bağlantı açılamadı': 'เปิดลิงก์ไม่ได้',
  'Orijinali göster': 'ดูต้นฉบับ',
  'Çeviriyi göster': 'ดูคำแปล',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'เดือนนี้ยังไม่มีตอนที่ประกาศวันออกอากาศ วันที่มักประกาศล่วงหน้าไม่กี่สัปดาห์ และจะแสดงที่นี่',
  'devamı': 'เพิ่มเติม',
  'Google ile devam et': 'ดำเนินการต่อด้วย Google',
  'Google girişi başarısız': 'การลงชื่อเข้าใช้ Google ล้มเหลว',
  'Veri tasarrufu': 'ประหยัดข้อมูล',
  'Wi-Fi ağında veri tasarrufu': 'ประหยัดข้อมูลเมื่อใช้ Wi-Fi',
  'Mobil veride veri tasarrufu': 'ประหยัดข้อมูลเมื่อใช้เน็ตมือถือ',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'เมื่อเปิดอยู่ รูปจะไม่ถูกดาวน์โหลดล่วงหน้า จะโหลดเฉพาะรูปที่คุณกำลังดู',
  'Çocuk güvenliği': 'ความปลอดภัยของเด็ก',
  'Türk Filmleri': 'ภาพยนตร์ตุรกี',
  'En Yüksek Puanlı Filmler': 'ภาพยนตร์คะแนนสูงสุด',
  'En Yüksek Puanlı Diziler': 'ซีรีส์คะแนนสูงสุด',
  'En Çok İzlenen Filmler': 'ภาพยนตร์ที่มีผู้ชมมากที่สุด',
  'Popüler Diziler': 'ซีรีส์ยอดนิยม',
  'En Çok Kazanan Filmler': 'ภาพยนตร์ทำเงินสูงสุด',
  'Kült Filmler': 'ภาพยนตร์คัลต์',
  'Yeni Filmler': 'ภาพยนตร์ใหม่',
  'Yorum yap': 'แสดงความคิดเห็น',
  'Henüz yorum yok': 'ยังไม่มีความคิดเห็น',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'ความคิดเห็นที่คุณเขียนถึงซีรีส์และภาพยนตร์จะรวมอยู่ที่นี่',
  'GIF ekle': 'เพิ่ม GIF',
  'İlk yorumu sen yaz': 'มาเป็นคนแรกที่แสดงความคิดเห็น',
  'Video altyazıları': 'คำบรรยายวิดีโอ',
  'Videolarda altyazı göster': 'แสดงคำบรรยายในวิดีโอ',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'ประโยคที่พูดในวิดีโอถูกเขียนบนหน้าจอ ข้อความมีการแปล: ภาษาอังกฤษเป็นภาษาตุรกี ภาษาตุรกีในภาษาอื่นๆ',
  'Güncelleme gerekli': 'ต้องอัปเดต',
  'Yeni sürüm var': 'มีเวอร์ชันใหม่',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'ติดตั้ง dizi.jpg เวอร์ชันใหม่เพื่อดำเนินการต่อ',
  'Güncelle': 'อัปเดต',
  'Daha sonra': 'ภายหลัง',
  'Takvim güncelleniyor': 'กำลังอัปเดตปฏิทิน',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'ไม่สามารถอัปเดตปฏิทินได้ กำลังแสดงรายการเดิม',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'บางซีรีส์โหลดไม่สำเร็จ รายการอาจไม่ครบ',
  'Yenile': 'รีเฟรช',
  'Devam etmek için giriş yap': 'เข้าสู่ระบบเพื่อดำเนินการต่อ',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'บัญชีฟรีก็เพียงพอสำหรับการให้คะแนน แสดงความคิดเห็น และสร้างคลังของคุณ',
  'Şimdi değil': 'ไว้ทีหลัง',
  'Yorum yazmak için giriş yap': 'เข้าสู่ระบบเพื่อเขียนความคิดเห็น',
  'Kişilere göndermek için giriş yap': 'เข้าสู่ระบบเพื่อส่งให้ผู้อื่น',
  'Beğenenler': 'คนที่ถูกใจ',
  'Henüz beğeni yok': 'ยังไม่มีใครถูกใจ',
  'Bu gönderiyi ilk beğenen sen ol': 'เป็นคนแรกที่ถูกใจโพสต์นี้',
  'Bu gönderiye yanıt': 'ตอบกลับโพสต์นี้',
  'Spoiler içeren gönderi': 'โพสต์ที่มีสปอยล์',
  'Görsel gönderi': 'โพสต์รูปภาพ',
  'Bu yorumu profilimde gizle': 'ซ่อนความคิดเห็นนี้บนโปรไฟล์ของฉัน',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'ความคิดเห็นยังคงอยู่ในหน้าซีรีส์และภาพยนตร์',
  'Bu yorumu sil': 'ลบความคิดเห็นนี้',
  'Yorum profilinde gizlendi': 'ซ่อนความคิดเห็นบนโปรไฟล์แล้ว',
  'Geri al': 'เลิกทำ',
  'Yorum silinsin mi?': 'ลบความคิดเห็นนี้ใช่ไหม',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'ความคิดเห็นนี้จะถูกลบอย่างถาวรจากทุกที่ ไม่สามารถย้อนกลับได้',
  'Yorum silindi': 'ลบความคิดเห็นแล้ว',
  'Yorum profilinde tekrar görünüyor': 'ความคิดเห็นแสดงบนโปรไฟล์ของคุณอีกครั้ง',
  'Gizlenen yorumun yok': 'ไม่มีความคิดเห็นที่ซ่อนไว้',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'ความคิดเห็นที่คุณซ่อนโดยการกดค้างที่โพสต์ในแท็บความคิดเห็นบนโปรไฟล์จะรวมอยู่ที่นี่',
  'Gizlenen yorumlar': 'ความคิดเห็นที่ซ่อนไว้',
  'Gönderiye git': 'ไปที่โพสต์',
  'Tekrar göster': 'แสดงอีกครั้ง',
  'Yanıtlarımı gizle': 'ซ่อนการตอบกลับของฉัน',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'การตอบกลับที่คุณเขียนในโพสต์ของผู้อื่นจะมองเห็นได้เฉพาะคุณเท่านั้น',
  'Profilinde gizlediğin yorumları tekrar göster':
      'แสดงความคิดเห็นที่คุณซ่อนไว้บนโปรไฟล์อีกครั้ง',
  'Sıralama': 'การเรียง',
  'Önerilen': 'แนะนำ',
  'Kronolojik': 'ตามเวลา',
  'Gelen mesaj istekleri': 'คำขอข้อความที่เข้ามา',
  'Mesaj isteğin yok': 'ไม่มีคำขอข้อความ',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'ข้อความจากคนที่คุณไม่ได้ติดตามจะแสดงที่นี่',
  'Çevrimiçi durumumu gizle': 'ซ่อนสถานะออนไลน์ของฉัน',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'คนอื่นจะไม่เห็นสถานะออนไลน์และเวลาที่เห็นล่าสุดของคุณในข้อความ',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'หนึ่งในผู้ใช้กลุ่มแรกของเรา ความคิดเห็นเหล่านั้นช่วยให้แอปเป็นอย่างที่เป็นอยู่ทุกวันนี้',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'คุณคือหนึ่งในผู้ใช้กลุ่มแรกของเรา ความคิดเห็นของคุณช่วยให้แอปเป็นอย่างที่เป็นอยู่ทุกวันนี้',
  'İleri': 'ถัดไป',
  'Önceki': 'ก่อนหน้า',
  'Sonraki': 'ถัดไป',
  'Seçilen dosya okunamadı': 'อ่านไฟล์ที่เลือกไม่สำเร็จ',
  'Video açılamadı': 'เปิดวิดีโอไม่สำเร็จ',
  'En fazla {} medya seçebilirsin': 'เลือกได้สูงสุด {} รายการ',
  'Hiçbir medya yüklenemedi': 'อัปโหลดสื่อไม่สำเร็จ',
  'Seçimi kaldır': 'เอาออกจากการเลือก',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'ในหนึ่งความคิดเห็นอัปโหลดได้รวม {} MB',
  '{} dosya okunamadı': 'อ่านไฟล์ {} รายการไม่ได้',
  '{} medya eklendi, {} yüklenemedi': 'เพิ่มแล้ว {} รายการ ไม่สำเร็จ {} รายการ',
  'Kırp': 'ครอบตัด',
  'Çiz': 'วาด',
  'Metin': 'ข้อความ',
  'Emoji': 'อิโมจิ',
  'Yinele': 'ทำซ้ำ',
  'Daha fazla': 'เพิ่มเติม',
  'Hazırlanıyor…': 'กำลังเตรียม…',
  'Düzenlemeden çık?': 'ออกจากการแก้ไข?',
  'Yaptığın değişiklikler kaybolacak.': 'การเปลี่ยนแปลงของคุณจะหายไป',
  'Çık': 'ออก',
  'Serbest çizim': 'วาดอิสระ',
  'Ok': 'ลูกศร',
  'Dikdörtgen': 'สี่เหลี่ยมผืนผ้า',
  'Daire': 'วงกลม',
  'Bulanıklaştır': 'เบลอ',
  'Pikselleştir': 'พิกเซล',
  'Silgi': 'ยางลบ',
  'Çizgi kalınlığı': 'ความหนาเส้น',
  'Saydamlık': 'ความทึบ',
  'Dolgu': 'เติมสี',
  'Renk': 'สี',
  'Döndür': 'หมุน',
  'Yansıt': 'พลิก',
  'Oran': 'อัตราส่วน',
  'Sıfırla': 'รีเซ็ต',
  'Serbest': 'อิสระ',
  'Metin yaz...': 'พิมพ์ข้อความ...',
  'Hizala': 'จัดแนว',
  'Arka plan': 'พื้นหลัง',
  'Emoji ara...': 'ค้นหาอิโมจิ...',
  'Son kullanılanlar': 'ล่าสุด',
  'İfadeler ve insanlar': 'หน้ายิ้มและผู้คน',
  'Hayvanlar ve doğa': 'สัตว์และธรรมชาติ',
  'Yiyecek ve içecek': 'อาหารและเครื่องดื่ม',
  'Etkinlikler': 'กิจกรรม',
  'Seyahat ve yerler': 'การเดินทางและสถานที่',
  'Nesneler': 'วัตถุ',
  'Semboller': 'สัญลักษณ์',
  'Bayraklar': 'ธง',
  'Görseli düzenle': 'แก้ไขรูปภาพ',
  'Düzenlendi': 'แก้ไขแล้ว',
  'Düzenlenemedi': 'แก้ไขไม่สำเร็จ',
  'Düzenlenen görsel çok büyük': 'รูปภาพที่แก้ไขมีขนาดใหญ่เกินไป',
  'Videoyu düzenle': 'แก้ไขวิดีโอ',
  'Sesi kapat': 'ปิดเสียง',
  'Sesi aç': 'เปิดเสียง',
  'İptal ediliyor…': 'กำลังยกเลิก…',
  'Bu biraz sürebilir': 'อาจใช้เวลาสักครู่',
  'Video çok büyük': 'วิดีโอใหญ่เกินไป',
  'Video hazırlanamadı': 'เตรียมวิดีโอไม่สำเร็จ',
  'Başlangıç': 'เริ่ม',
  'Bitiş': 'สิ้นสุด',
  'En çok {} saniye seçebilirsin': 'เลือกได้สูงสุด {} วินาที',
  'Dosya en fazla {} MB olabilir': 'ไฟล์มีขนาดได้สูงสุด {} MB',
  'Medya ekle': 'เพิ่มสื่อ',
  'Seçili medya kalmadı': 'ยังไม่ได้เลือกสื่อ',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'เลือกรูปภาพหรือวิดีโอเพื่อเพิ่มในความคิดเห็นของคุณ',
  'Medya seç': 'เลือกสื่อ',
  'Daha fazla ekle': 'เพิ่มอีก',
  'Medya seçilemedi': 'ไม่สามารถเลือกสื่อได้',
  'Favori oyuncular': 'นักแสดงที่ชื่นชอบ',
  'Henüz favori oyuncun yok': 'ยังไม่มีนักแสดงที่ชื่นชอบ',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'เปิดหน้านักแสดงแล้วแตะรูปหัวใจมุมขวาบนเพื่อเพิ่มที่นี่',
  '{} yapımdan {} tanesini izledin': 'คุณดูแล้ว {} จาก {} เรื่อง',
  'izledin': 'ดูแล้ว',
  'İzlemedin': 'ยังไม่ได้ดู',
  'Yapım bulunamadı': 'ไม่พบผลงาน',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'บุคคลนี้ไม่มีซีรีส์หรือภาพยนตร์ที่จะแสดง',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'ประวัติการดูผูกกับบัญชีของคุณ รายการนี้เป็นของคุณเท่านั้น',
  'Hesabın kalıcı olarak askıya alındı': 'บัญชีของคุณถูกระงับถาวร',
  'Hesabın geçici olarak askıya alındı': 'บัญชีของคุณถูกระงับชั่วคราว',
  'Hesabın askıya alındı': 'บัญชีของคุณถูกระงับ',
  'Sebep': 'เหตุผล',
  'Kalan süre': 'เวลาที่เหลือ',
  'Süre dolunca hesabın kendiliğinden açılır':
      'บัญชีจะเปิดใช้งานอัตโนมัติเมื่อครบกำหนด',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'ในช่วงนี้คุณยังอ่านได้ แต่โพสต์ แสดงความคิดเห็น หรือส่งข้อความไม่ได้',
  'Anladım': 'เข้าใจแล้ว',
  'Ayrıntı': 'รายละเอียด',
  '{} dakika': '{} นาที',
  'birkaç saniye': 'ไม่กี่วินาที',
  'Karara itiraz et': 'อุทธรณ์คำตัดสินนี้',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'อธิบายว่าทำไมควรยกเลิกบทลงโทษนี้',
  'İtirazını gönder': 'ส่งคำอุทธรณ์',
  'İtirazın incelemede': 'คำอุทธรณ์ของคุณอยู่ระหว่างพิจารณา',
  'İtirazın reddedildi': 'คำอุทธรณ์ของคุณถูกปฏิเสธ',
  'İtirazın alındı, inceleniyor':
      'ได้รับคำอุทธรณ์ของคุณแล้ว อยู่ระหว่างพิจารณา',
  'İtiraz en az 10 karakter olmalı': 'คำอุทธรณ์ต้องมีอย่างน้อย 10 ตัวอักษร',
  'Yükleniyor...': 'กำลังโหลด...',
  'Bu bölüme puan ver': 'ให้คะแนนตอนนี้',
  '{} kişi puanladı': '{} คนให้คะแนน',
  'Bölüm izlendi olarak işaretlendi': 'ทำเครื่องหมายตอนนี้ว่าดูแล้ว',
  'Sesli ara': 'สายเสียง',
  'Görüntülü ara': 'สายวิดีโอ',
  'Çalıyor...': 'กำลังเรียก...',
  'Bağlanıyor...': 'กำลังเชื่อมต่อ...',
  'Cevapla': 'รับสาย',
  'Reddet': 'ปฏิเสธ',
  'Sessize al': 'ปิดไมค์',
  'Hoparlör': 'ลำโพง',
  'Kamerayı kapat': 'ปิดกล้อง',
  'Kamerayı çevir': 'สลับกล้อง',
  'Cevap yok': 'ไม่มีผู้รับสาย',
  'Arama reddedildi': 'สายถูกปฏิเสธ',
  'Meşgul': 'ไม่ว่าง',
  'Bağlanılamadı': 'เชื่อมต่อไม่ได้',
  'Arama iptal edildi': 'ยกเลิกสายแล้ว',
  'Arama geçmişi': 'ประวัติการโทร',
  'Gelen arama': 'สายเรียกเข้า',
  'Giden arama': 'สายโทรออก',
  'Cevapsız arama': 'สายที่ไม่ได้รับ',
  'Arama şu anda kullanılamıyor': 'ขณะนี้ยังใช้การโทรไม่ได้',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'สายวิดีโอปิดอยู่ตอนนี้ คุณโทรด้วยเสียงได้',
  'Bu kullanıcıyı arayamazsın': 'คุณโทรหาผู้ใช้นี้ไม่ได้',
  'Aramak için karşılıklı takipleşmelisiniz':
      'ต้องติดตามกันทั้งสองฝ่ายจึงจะโทรได้',
  'Bu kullanıcı şu anda aranamıyor': 'ตอนนี้โทรหาผู้ใช้นี้ไม่ได้',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'สายที่ไม่ได้รับมากเกินไป ลองใหม่ในอีก {}',
  'Zaten bir aramadasın': 'คุณอยู่ในสายอยู่แล้ว',
  'Arama için mikrofon izni gerekiyor': 'ต้องอนุญาตไมโครโฟนเพื่อโทร',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'สายวิดีโอต้องอนุญาตกล้องและไมโครโฟน',
  'Arama başlatılamadı': 'เริ่มการโทรไม่ได้',
  'Kullanıcı bulunamadı': 'ไม่พบผู้ใช้',
  'Kendini arayamazsın': 'คุณโทรหาตัวเองไม่ได้',
  'Arama artık geçerli değil': 'สายนี้ใช้ไม่ได้แล้ว',
  'Bu aramanın tarafı değilsin': 'คุณไม่ได้อยู่ในสายนี้',
  'Arama bulunamadı': 'ไม่พบสาย',
  'Çok fazla istek, biraz bekle': 'คำขอมากเกินไป โปรดรอสักครู่',
  'Bağlantı koptu': 'การเชื่อมต่อหลุด',
  'Arama süre sınırına ulaştı': 'สายถึงขีดจำกัดเวลาแล้ว',
  'Arama en fazla 4 saat sürebilir': 'การโทรใช้เวลาได้สูงสุด 4 ชั่วโมง',
  'Arama sona erdi': 'สายสิ้นสุดแล้ว',
  'Sesli arama': 'สายเสียง',
  'Görüntülü arama': 'สายวิดีโอ',
  'Gelen aramalar': 'สายเรียกเข้า',
  'Sesli ve görüntülü arama bildirimleri': 'การแจ้งเตือนสายเสียงและวิดีโอ',
  '{} sa': '{} ชม.',
  'Sesli ve Görüntülü Aramalar': 'สายเสียงและสายวิดีโอ',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'เนื้อหาการสนทนาไม่ถูกบันทึกเลย เสียงและวิดีโอถูกเข้ารหัสแบบต้นทางถึงปลายทาง (DTLS-SRTP) ระหว่างอุปกรณ์ เซิร์ฟเวอร์ของเราถอดรหัส ดักฟัง หรือจัดเก็บข้อมูลนี้ไม่ได้',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'เก็บเฉพาะข้อมูลกำกับการโทรเท่านั้น ได้แก่ คู่สนทนา ทิศทาง เวลา และระยะเวลา บันทึกเหล่านี้จะถูกลบอัตโนมัติหลัง 90 วัน',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'หากเชื่อมต่อโดยตรงไม่ได้ เสียงและวิดีโอจะผ่านเซิร์ฟเวอร์รีเลย์ (TURN) ในสถานะที่เข้ารหัสไว้ เซิร์ฟเวอร์รีเลย์ก็ถอดรหัสหรือบันทึกเนื้อหาไม่ได้เช่นกัน',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'ไมโครโฟนถูกใช้เฉพาะระหว่างสายเสียงหรือสายวิดีโอ และกล้องเฉพาะระหว่างสายวิดีโอ ทั้งคู่จะถูกปิดเมื่อวางสาย',
  'Takip ettiğin {} kişi izledi': 'มี {} คนที่คุณติดตามดูแล้ว',
  'Yorum yaz...': 'เขียนความคิดเห็น...',
  'Sıradaki bölüm': 'ตอนถัดไป',
  'Doğrulanmış testçi': 'ผู้ทดสอบที่ยืนยันแล้ว',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'การแจ้งเตือนการติดตาม ถูกใจ ตอบกลับ ข้อความ และการแท็ก',
  'Sen': 'คุณ',
  'Aradığınız kişide sesli arama devre dışı': 'บุคคลนี้ปิดการโทรด้วยเสียงไว้',
  'Aradığınız kişide görüntülü arama devre dışı': 'บุคคลนี้ปิดการโทรวิดีโอไว้',
  'Sesli aramalara izin ver': 'อนุญาตการโทรด้วยเสียง',
  'Görüntülü aramalara izin ver': 'อนุญาตการโทรวิดีโอ',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'เมื่อปิดอยู่ จะไม่มีใครโทรหาคุณด้วยเสียงได้ ผู้โทรจะเห็นข้อความแจ้ง',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'เมื่อปิดอยู่ จะไม่มีใครโทรวิดีโอหาคุณได้ ผู้โทรจะเห็นข้อความแจ้ง',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'การโทรด้วยเสียงปิดอยู่ เปิดได้ที่ การตั้งค่า > ความเป็นส่วนตัว',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'การโทรวิดีโอปิดอยู่ เปิดได้ที่ การตั้งค่า > ความเป็นส่วนตัว',
  'Sesli ve görüntülü arama': 'การโทรด้วยเสียงและวิดีโอ',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'บัญชีผู้เยี่ยมชมโทรออกไม่ได้ สร้างบัญชีเพื่อใช้งาน',
  'Misafir hesaplar aranamaz': 'โทรหาบัญชีผู้เยี่ยมชมไม่ได้',
  'Puan dağılımı': 'การกระจายคะแนน',
  '{} yıldız': '{} ดาว',
  'Yakında gelecek': 'เร็ว ๆ นี้',
  '{} {} yayınlandı': '{} {} มาแล้ว',
  'Yeni bölüm yayınlandı': 'ตอนใหม่มาแล้ว',
  'Yeni bölümler': 'ตอนใหม่',
  'Geri': 'ย้อนกลับ',
  'Karşılamayı kapat': 'ปิดหน้าเริ่มต้นใช้งาน',
  'Adım {} / {}': 'ขั้นที่ {} จาก {}',
  'Hadi başlayalım': 'เริ่มกันเลย',
  'Kaydet ve devam': 'บันทึกและไปต่อ',
  '{} tanesini ekle': 'เพิ่ม {} เรื่องที่เลือก',
  'Şimdilik geç': 'ข้ามไปก่อน',
  'Doğum tarihin ne zaman?': 'วันเกิดของคุณคือวันไหน?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'เราถามเพื่อแสดงเนื้อหาที่เหมาะกับวัยและอวยพรวันเกิดให้คุณ',
  'Gün': 'วัน',
  'Ay': 'เดือน',
  'Yıl': 'ปี',
  'Doğum yılımı paylaşmak istemiyorum': 'ฉันไม่ต้องการเปิดเผยปีเกิด',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'วันเกิดของคุณจะไม่แสดงต่อสาธารณะบนโปรไฟล์ ใช้เพียงเพื่อเนื้อหาที่เหมาะกับวัยและการอวยพรวันเกิดเท่านั้น',
  'Ocak': 'มกราคม',
  'Şubat': 'กุมภาพันธ์',
  'Mart': 'มีนาคม',
  'Nisan': 'เมษายน',
  'Mayıs': 'พฤษภาคม',
  'Haziran': 'มิถุนายน',
  'Temmuz': 'กรกฎาคม',
  'Ağustos': 'สิงหาคม',
  'Eylül': 'กันยายน',
  'Ekim': 'ตุลาคม',
  'Kasım': 'พฤศจิกายน',
  'Aralık': 'ธันวาคม',
  'Verilerini yanında getir': 'ย้ายข้อมูลของคุณมาด้วย',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'ถ้าคุณบันทึกสิ่งที่ดูไว้ในแอปอื่น ย้ายมาที่นี่ได้เลย ไม่ต้องเริ่มใหม่จากศูนย์',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt และ Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'เลือกไฟล์ ZIP ที่คุณส่งออกไว้ แล้วประวัติการดู คะแนน และลิสต์ของคุณจะถูกนำเข้ามา',
  'Aktarılıyor...': 'กำลังนำเข้า...',
  'ZIP dosyası seç': 'เลือกไฟล์ ZIP',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'ไม่ต้องรีบ: ทำภายหลังได้ที่ การตั้งค่า > ข้อมูลของฉัน',
  'Hangi filmleri izledin?': 'คุณดูหนังเรื่องไหนมาบ้าง?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'นี่คือเรื่องที่คนดูมากที่สุด แตะเรื่องไหน เราจะเพิ่มลงประวัติการดูให้',
  'SERİ FİLMLER': 'หนังชุด',
  'Serilerden {} film eklendi': 'เพิ่มหนังจากหนังชุดแล้ว {} เรื่อง',
  'Film listesi yüklenemedi': 'โหลดรายการหนังไม่สำเร็จ',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'ข้ามขั้นนี้ไปก่อนได้ แล้วค่อยเพิ่มเรื่องที่อยากได้ทีหลัง',
  '{} film izlediklerine eklendi': 'เพิ่มหนัง {} เรื่องลงประวัติการดูแล้ว',
  'Film serileri': 'ชุดภาพยนตร์',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'ถ้าคุณดูหนังชุดไหนครบทุกภาคแล้ว แตะครั้งเดียวเพิ่มได้เลย',
  'Seri bulunamadı': 'ไม่พบหนังชุด',
  'Daha sonra tekrar deneyebilirsin.': 'คุณลองใหม่อีกครั้งภายหลังได้',
  '{} film': 'หนัง {} เรื่อง',
  'Eklendi': 'เพิ่มแล้ว',
  'Tümünü izledim': 'ดูครบทุกเรื่องแล้ว',
  'Peki ya diziler?': 'แล้วซีรีส์ล่ะ?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'ทำเครื่องหมายเรื่องที่คุณดูแล้ว ยิ่งเลือก เราก็ยิ่งหาเรื่องที่คล้ายกันมาให้',
  'Dizi listesi yüklenemedi': 'โหลดรายการซีรีส์ไม่สำเร็จ',
  'Seçtiklerine benzeyenler': 'เรื่องที่คล้ายกับที่คุณเลือก',
  'Her şey hazır': 'พร้อมแล้ว',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'มาดูอย่างรวดเร็วว่าคุณทำอะไรได้บ้างใน dizi.jpg',
  'Profilini tamamla': 'เติมโปรไฟล์ให้ครบ',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'คุณเพิ่มประวัติ รูปโปรไฟล์ และรูปปกได้จากการตั้งค่า',
  'Takvimin seni bekliyor': 'ปฏิทินรอคุณอยู่',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'ตอนใหม่ของซีรีส์ที่คุณดูจะขึ้นในปฏิทิน และเราจะแจ้งเตือนให้รู้',
  'Puan ver, yorum yaz': 'ให้คะแนน เขียนคอมเมนต์',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'ให้คะแนนทีละตอน เขียนคอมเมนต์โดยมีม่านสปอยล์ปิดไว้ และสร้างลิสต์ของคุณเอง',
  'Verilerin sende kalır': 'ข้อมูลยังเป็นของคุณ',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'ข้อมูลของคุณผูกกับบัญชีของคุณเท่านั้นและไม่ถูกนำไปขาย คุณดาวน์โหลดทั้งหมดหรือลบบัญชีทิ้งทั้งหมดได้จากการตั้งค่า',
  'Engellenen kullanıcılar': 'ผู้ใช้ที่ถูกบล็อก',
  'Engellediğin kişileri gör, engeli kaldır': 'ดูคนที่คุณบล็อกไว้ และเลิกบล็อก',
  'Engellediğin kimse yok': 'คุณยังไม่ได้บล็อกใคร',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'คุณบล็อกผู้ใช้ได้จากเมนูสามจุดในหน้าโปรไฟล์ของผู้ใช้รายนั้น',
  '@{} engellensin mi?': 'บล็อก @{} ไหม?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'คุณทั้งสองฝ่ายจะไม่เห็นโพสต์ คอมเมนต์ และโปรไฟล์ของกันและกัน ส่งข้อความและโทรหากันก็ไม่ได้ หากติดตามกันอยู่ การติดตามจะถูกตัดขาดและจะไม่กลับคืนมา แม้คุณจะเลิกบล็อกในภายหลังก็ตาม',
  'Bu kullanıcıyı engelledin': 'คุณบล็อกผู้ใช้รายนี้ไว้',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'คุณไม่เห็นโพสต์ คอมเมนต์ และข้อความของผู้ใช้รายนี้ และผู้ใช้รายนี้ก็ไม่เห็นของคุณเช่นกัน',
  '{} yeni bir yapımda: {}': '{} มีผลงานใหม่: {}',
  'Favori kişinden yeni yapım': 'ผลงานใหม่จากคนที่คุณชื่นชอบ',
  '{} için bildirimler': 'การแจ้งเตือนสำหรับ {}',
  'Tüm bildirimler': 'การแจ้งเตือนทั้งหมด',
  'Uygulamada ve telefonda': 'ทั้งในแอปและบนโทรศัพท์',
  'Yalnız uygulama içi': 'ในแอปเท่านั้น',
  'Telefon bildirimi gönderilmez': 'ไม่ส่งการแจ้งเตือนไปที่โทรศัพท์',
  'Kapalı': 'ปิด',
  'Bu kişi için bildirim yok': 'ไม่มีการแจ้งเตือนสำหรับคนนี้',
  'Favori kişilerin yeni yapımları': 'ผลงานใหม่ของคนที่ชื่นชอบ',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'เมื่อปิดอยู่ จะไม่มีใครโทรหาคุณด้วยเสียงได้ ผู้โทรจะเห็นข้อความแจ้งว่า "ปิดอยู่"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'เมื่อปิดอยู่ จะไม่มีใครโทรวิดีโอหาคุณได้ ผู้โทรจะเห็นข้อความแจ้งว่า "ปิดอยู่"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'กิจกรรมของฉัน',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'ถูกใจ คอมเมนต์ และการดูของคุณในที่เดียว',
  'Henüz hareketin yok': 'ยังไม่มีกิจกรรม',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'ทุกอย่างที่คุณถูกใจ คอมเมนต์ และดู จะถูกรวบรวมไว้ที่นี่',
  'Bu süzgeçte hareket yok': 'ไม่มีกิจกรรมในตัวกรองนี้',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'เลือกประเภทอื่น หรือกลับไปที่ "ทั้งหมด"',
  'Hepsi': 'ทั้งหมด',
  'Puan': 'คะแนน',
  'Tepki': 'รีแอ็กชัน',
  'İzleme': 'การดู',
  'Durum': 'สถานะ',
  'Liste': 'รายการ',
  'Yorum yaptın': 'คุณคอมเมนต์',
  'Yorumu beğendin': 'คุณถูกใจคอมเมนต์',
  '{} puan verdin': 'คุณให้ {} คะแนน',
  'Tepki verdin': 'คุณแสดงรีแอ็กชัน',
  'Listene ekledin': 'คุณเพิ่มลงรายการ',
  'Takip etmeye başladın': 'คุณเริ่มติดตาม',
  '"İzleyeceğim" işaretledin': 'ทำเครื่องหมาย "จะดู"',
  '"İzliyorum" işaretledin': 'ทำเครื่องหมาย "กำลังดู"',
  '"Bitirdim" işaretledin': 'ทำเครื่องหมาย "ดูจบแล้ว"',
  '"Bıraktım" işaretledin': 'ทำเครื่องหมาย "เลิกดูแล้ว"',
  'Silinmiş içerik': 'เนื้อหาที่ถูกลบ',
  'şimdi': 'เมื่อกี้',
  '{} g': '{} วัน',
  '{} y': '{} ปี',
  'İstatistiklerim': 'สถิติของฉัน',
  'Gönderilerinin görüntülenmesi ve beğenisi': 'ยอดดูและถูกใจของโพสต์คุณ',
  'Henüz gönderin yok': 'คุณยังไม่มีโพสต์',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'เมื่อคุณคอมเมนต์ซีรีส์หรือหนัง ยอดดูและถูกใจของคุณจะเริ่มสะสมที่นี่',
  'Tüm zamanlar': 'ตลอดเวลา',
  'Son {} gün': '{} วันล่าสุด',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'ประวัติยอดดูยังไม่เริ่มสะสม ข้อมูลวันแรกจะปรากฏพรุ่งนี้',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'ประวัติยอดดูสะสมมาตั้งแต่ {} (มีข้อมูล {} วัน) ตัวเลข {} วันจึงยังไม่ครบ',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'ประวัติถูกใจถูกบันทึกตั้งแต่ {}',
  'Bu dönemde gösterilecek gönderi yok.': 'ไม่มีโพสต์ให้แสดงในช่วงเวลานี้',
  'eksik veri': 'ข้อมูลไม่ครบ',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'ซีรีส์และหนังที่คุณดู ตัวนับการดู เวลาหน้าจอ และการ์ดความเข้ากันบนโปรไฟล์ของคุณจะไม่แสดงให้คนอื่นเห็น',
  'Takipçi listemi gizle': 'ซ่อนรายชื่อผู้ติดตามของฉัน',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'คนอื่นจะไม่เห็นว่าใครติดตามคุณ แต่จำนวนผู้ติดตามยังแสดงอยู่',
  'Takip ettiklerimi gizle': 'ซ่อนคนที่ฉันติดตาม',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'คนอื่นจะไม่เห็นว่าคุณติดตามใคร แต่จำนวนที่คุณติดตามยังแสดงอยู่',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'ผู้ใช้รายนี้เลือกที่จะซ่อนผู้ติดตามของตน',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'ผู้ใช้รายนี้เลือกที่จะซ่อนคนที่ตนติดตาม',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'สถิติโพสต์',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'คุณดูสถิติได้เฉพาะโพสต์ของตัวเองเท่านั้น',
  'Erişim': 'การเข้าถึง',
  'Görüntüleyen': 'ผู้ชม',
  'Kaç farklı kişi gördü (son {} gün)':
      'มีคนต่างกันกี่คนที่เห็น ({} วันล่าสุด)',
  'Paylaşım': 'การแชร์',
  'Bu gönderiden sonra': 'หลังจากโพสต์นี้',
  'Profil ziyareti': 'การเข้าชมโปรไฟล์',
  'Yeni takip': 'การติดตามใหม่',
  'İçeriğe tıklama': 'การแตะเนื้อหา',
  'Spoiler perdesini açan': 'เปิดดูสปอยล์',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'การแชร์ การเข้าชมโปรไฟล์ การติดตาม การแตะเนื้อหา สัดส่วนแหล่งที่มา และการวัดสปอยล์ สะสมมาตั้งแต่ {} ส่วนก่อนหน้านั้นไม่ได้วัดไว้',
  'Zamana yayılmış görüntülenme': 'ยอดดูตามช่วงเวลา',
  'Görüntülenme nereden geldi': 'ยอดดูมาจากที่ใด',
  'Kimler gördü': 'ใครเห็นบ้าง',
  'Günlük veri henüz birikmeye başlamadı.': 'ข้อมูลรายวันยังไม่เริ่มสะสม',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'กราฟต้องใช้ข้อมูลอย่างน้อยสองวัน ข้อมูลสะสมมาตั้งแต่ {}',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'ยอดดูสูงสุดมาในวันที่ {} หลังโพสต์: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'ยอดดูรายวันสะสมมาตั้งแต่ {} ส่วนก่อนหน้านั้นไม่ได้วัดไว้',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'เพิ่งเริ่มวัดสัดส่วนแหล่งที่มา โพสต์นี้ยังไม่ได้รับยอดดูที่ระบุแหล่งที่มา',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'เพิ่งเริ่มวัดสัดส่วนผู้ติดตาม/การสำรวจ ยังไม่มีข้อมูล',
  'Takip edenler': 'ผู้ติดตาม',
  'Keşiften gelenler': 'จากสำรวจ',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'หน้าซีรีส์/ภาพยนตร์',
  'Paylaşılan bağlantı': 'ลิงก์ที่แชร์',
  'yeni ölçülüyor': 'เพิ่งเริ่มวัด',
  'Kendi ortalamanla aynı düzeyde': 'เท่ากับค่าเฉลี่ยของคุณเอง',
  'Kendi ortalamanın %{} üstünde': 'สูงกว่าค่าเฉลี่ยของคุณเอง {}%',
  'Kendi ortalamanın %{} altında': 'ต่ำกว่าค่าเฉลี่ยของคุณเอง {}%',
  'Etkileşim oranı': 'อัตราการมีส่วนร่วม',
  '(beğeni + yorum) ÷ görüntülenme': '(ถูกใจ + ความคิดเห็น) ÷ ยอดดู',
  'Toplam görüntülenme': 'ยอดดูทั้งหมด',
  '{} ile {} arasında toplam {} görüntülenme': 'ระหว่าง {} ถึง {} รวม {} ยอดดู',
  'İstatistikleri gör': 'ดูสถิติ',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'สำหรับสถิติที่แสดงแก่เจ้าของโพสต์ ระบบเก็บเป็นตัวนับรวมว่า โพสต์ถูกดูกี่ครั้งและจากพื้นผิวใด (ฟีด โปรไฟล์ ฟีดเต็มจอ หน้าซีรีส์/ภาพยนตร์ ลิงก์ที่แชร์) ผู้ดูกำลังติดตามเจ้าของโพสต์อยู่ในขณะนั้นหรือไม่ การย้ายจากโพสต์ไปยังโปรไฟล์หรือเนื้อหา การติดตามที่เกิดขึ้นผ่านโพสต์ การแชร์ และการเปิดม่านสปอยล์ ตัวนับเหล่านี้ไม่มีอัตลักษณ์ผู้ใช้ ที่อยู่ IP หรือประทับเวลา จึงไม่สามารถสืบค้นได้ว่าใครทำอะไร',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'เพื่อให้นับได้ว่ามีคนต่างกันกี่คนที่เห็นโพสต์หนึ่ง ระบบจะเก็บค่าย่อยแบบมีกุญแจที่ย้อนกลับไม่ได้สำหรับผู้ชมแต่ละคน (ค่าย่อทางวิทยาการเข้ารหัสลับที่ได้จากอัตลักษณ์ผู้ใช้หรือที่อยู่ IP) ไว้ 90 วัน เจ้าของโพสต์จะเห็นเพียงตัวเลขเท่านั้น ตัวตนของผู้ชมจะไม่ถูกเปิดเผยไม่ว่ากรณีใด',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'ย้ายไป “จะดู” ไหม',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'เรื่องหนึ่งจะอยู่ในสถานะจะดูหรือดูแล้วอย่างใดอย่างหนึ่ง ถ้าไปต่อ เครื่องหมายการดู {} รายการของคุณในซีรีส์นี้จะถูกลบ',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'เรื่องหนึ่งจะอยู่ในสถานะจะดูหรือดูแล้วอย่างใดอย่างหนึ่ง ถ้าไปต่อ เครื่องหมาย “ดูแล้ว” ของคุณในหนังเรื่องนี้จะถูกเอาออก',
  'Sil ve taşı': 'ลบและย้าย',

  // --- Yapım ekibi + yapım firmaları ---
  'Yapım Ekibi': 'ทีมงาน',
  'Yaratıcı': 'ผู้สร้าง',
  'Yönetmen': 'ผู้กำกับ',
  'Senaryo': 'เขียนบท',
  'Yapımcı': 'โปรดิวเซอร์',
  'Yapım Firmaları': 'บริษัทผู้สร้าง',
  'Yapım Firması': 'บริษัทผู้สร้าง',
  'Firma bulunamadı': 'ไม่พบบริษัท',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'บริษัทนี้ไม่มีผลงานประเภทนี้',
  // --- İzleyici seviyesi ve unvanları (cinsiyetsiz) ---
  // --- Doğum günü kutlama kartı ---
  'Doğum günün kutlu olsun!': 'สุขสันต์วันเกิด!',
  'İyi ki doğdun, iyi ki buradasın.':
      'ดีใจที่มีคุณอยู่ และดีใจที่คุณอยู่ตรงนี้',
  'Bugün {} yaşına girdin': 'วันนี้คุณอายุครบ {} ปีแล้ว',
  'Teşekkürler': 'ขอบคุณ',
  // --- İki adımlı doğrulama (2FA) ---
  'İki Adımlı Doğrulama': 'การยืนยันแบบ 2 ขั้นตอน',
  'Girişte e-postana kod gönderilir':
      'ระบบจะส่งรหัสไปยังอีเมลของคุณเมื่อลงชื่อเข้าใช้',
  'Kod {} adresine gönderildi': 'ส่งรหัสไปที่ {} แล้ว',
  '6 haneli kod': 'รหัส 6 หลัก',
  'Doğrula': 'ยืนยัน',
  'Yeniden gönder': 'ส่งอีกครั้ง',
  'Vazgeç': 'ยกเลิก',
  'Yeni kod gönderildi': 'ส่งรหัสใหม่แล้ว',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'เมื่อลงชื่อเข้าใช้ด้วย Google จะไม่มีการขอรหัส เพราะ Google ยืนยันตัวตนด้วยตัวเอง',
  'Kapatmak için de kod gerekir.': 'การปิดใช้งานก็ต้องใช้รหัสเช่นกัน',
  'E-postana erişemezsen hesabına giremezsin.':
      'หากเข้าถึงอีเมลไม่ได้ จะลงชื่อเข้าใช้บัญชีไม่ได้',
  'İki adımlı doğrulama açıldı': 'เปิดการยืนยันแบบ 2 ขั้นตอนแล้ว',
  'İki adımlı doğrulama kapatıldı': 'ปิดการยืนยันแบบ 2 ขั้นตอนแล้ว',
  // --- Video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': 'ดูวิดีโอไปได้ถึงไหน',
  'Videoyu başlatanlar': 'เริ่มดูวิดีโอ',
  'videonun %{} noktasına ulaştı': 'ดูถึง {}% ของวิดีโอ',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'ครึ่งหนึ่งของผู้ชมดูอย่างน้อย {}% ของวิดีโอ',
  'Sonuna kadar izleyen: %{}': 'ดูจนจบ: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'กราฟต้องมียอดดูอย่างน้อย {} ครั้ง ตอนนี้มี {} ครั้ง',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'กราฟคำนวณจากยอดดู {} ครั้ง และไม่เปลี่ยนตามช่วงเวลาที่เลือก',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'เวลาที่ดูวัดตั้งแต่ {} เป็นต้นมา การดูก่อนหน้านั้นไม่นับรวม',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      'ยอดดู {} ครั้ง {}% ดูถึงครึ่งวิดีโอ {}% ดูจนจบ',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',

  // --- md.42/26 istatistikler + seviye ---
  'Seviye {}': 'ระดับ {}',
  'Sonraki seviyeye {} puan kaldı': 'อีก {} คะแนนถึงระดับถัดไป',
  'Gönderilerin': 'โพสต์ของคุณ',
  '{} gönderi': 'โพสต์ {}',
  '{} gönderi · {} görüntülenme': 'โพสต์ {} · ยอดดู {}',
  'önceki {} güne göre': 'เทียบกับ {} วันก่อนหน้า',
  'önceki {} güne göre %{} arttı': 'เทียบกับ {} วันก่อนหน้า เพิ่มขึ้น {}%',
  'önceki {} güne göre %{} azaldı': 'เทียบกับ {} วันก่อนหน้า ลดลง {}%',
  'önceki {} güne göre değişmedi': 'ไม่เปลี่ยนแปลงเทียบกับ {} วันก่อนหน้า',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'ยอดดูรายวัน: ต่ำสุด {} สูงสุด {}',
  'Etkileşim oranı henüz ölçülemedi': 'ยังวัดอัตราการมีส่วนร่วมไม่ได้',
  'Oranlar': 'อัตราส่วน',
  'Beğenme oranı': 'อัตราการถูกใจ',
  'Yorum oranı': 'อัตราความคิดเห็น',
  'Paylaşma oranı': 'อัตราการแชร์',
  'İçeriğe gitme oranı': 'อัตราการแตะเนื้อหา',
  'Profile gitme oranı': 'อัตราการเข้าชมโปรไฟล์',
  'Ziyaretten takibe dönüşüm': 'จากเข้าชมเป็นผู้ติดตาม',
  'beğeni ÷ görüntülenme': 'ถูกใจ ÷ ยอดดู',
  'yorum ÷ görüntülenme': 'ความคิดเห็น ÷ ยอดดู',
  'paylaşım ÷ görüntülenme': 'การแชร์ ÷ ยอดดู',
  'içeriğe tıklama ÷ görüntülenme': 'การแตะเนื้อหา ÷ ยอดดู',
  'profil ziyareti ÷ görüntülenme': 'การเข้าชมโปรไฟล์ ÷ ยอดดู',
  'yeni takip ÷ profil ziyareti': 'การติดตามใหม่ ÷ การเข้าชมโปรไฟล์',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'อัตราส่วนต้องมียอดดูอย่างน้อย {} ครั้ง ตอนนี้มี {} ครั้ง',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'อัตราส่วนคำนวณจากยอดรวมตลอดอายุโพสต์ การเลือกวันด้านล่างไม่เปลี่ยนค่าเหล่านี้',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'ตัวเลขเหล่านี้คือยอดรวมตลอดอายุโพสต์ (ยกเว้นกล่องที่มีหมายเหตุของตัวเอง) การเลือกวันด้านล่างเปลี่ยนเฉพาะกราฟ',
  'Ortalama izlenme: videonun %{} kadarı': 'ดูเฉลี่ย: {}% ของวิดีโอ',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'ค่าเฉลี่ยของ 20 ช่วงในกราฟการคงอยู่',
  'Dizi, film, kişi veya şirket ara...': 'ค้นหาซีรีส์ หนัง บุคคล หรือบริษัท...',
  'Şirketler': 'บริษัท',
  'Senarist': 'นักเขียนบท',
  'Bölüm puanları': 'คะแนนตอน',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'โหลดคะแนนตอนไม่ได้',
  'Giriş gerekli': 'ต้องเข้าสู่ระบบ',
  'Geçersiz oturum': 'เซสชันไม่ถูกต้อง',
  'Oturum sonlandı, tekrar giriş yap': 'เซสชันสิ้นสุด เข้าสู่ระบบอีกครั้ง',
  'Çok fazla istek; biraz sonra tekrar dene': 'คำขอมากเกินไป ลองใหม่สักครู่',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'ตอนนี้เซิร์ฟเวอร์ไม่มีพื้นที่ว่าง ลองใหม่อีกสักครู่',
  'Devam eden yapımlar ({})': 'ผลงานที่กำลังฉาย ({})',
  'Diziler ({})': 'ซีรีส์ ({})',
  'Filmler ({})': 'ภาพยนตร์ ({})',
  'Tüm yapımlar': 'ผลงานทั้งหมด',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'พื้นที่สื่อของคุณเต็มแล้ว ลบไฟล์เก่าเพื่อเพิ่มพื้นที่',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'อีเมล/ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı': 'อีเมลหรือชื่อนี้ถูกใช้แล้ว',
  'Google doğrulaması başarısız': 'การยืนยัน Google ล้มเหลว',
  'Kod geçersiz veya süresi dolmuş': 'รหัสไม่ถูกต้องหรือหมดอายุ',
  'Bu kullanıcıyla mesajlaşamazsın': 'ส่งข้อความถึงผู้ใช้นี้ไม่ได้',
  'Kendini takip edemezsin': 'ติดตามตัวเองไม่ได้',
  'Bu kullanıcıyı takip edemezsin': 'ติดตามผู้ใช้นี้ไม่ได้',
  'Kendini engelleyemezsin': 'บล็อกตัวเองไม่ได้',
  'Yorum 1-1000 karakter olmalı': 'ความคิดเห็นต้องมี 1–1000 ตัวอักษร',
  'Boş mesaj gönderilemez': 'ส่งข้อความว่างไม่ได้',
  'Yorum bulunamadı': 'ไม่พบความคิดเห็น',
  'Şifre hatalı': 'รหัสผ่านไม่ถูกต้อง',
  'Şifre en az 6 karakter olmalı': 'รหัสผ่านอย่างน้อย 6 ตัวอักษร',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'อัปโหลดได้เฉพาะ GIF PNG JPEG หรือ WebP',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'ชนิดที่รองรับ: GIF PNG JPEG WebP MP4 WebM เสียง',
  'Geçerli bir ZIP dosyası değil': 'ไม่ใช่ไฟล์ ZIP ที่ถูกต้อง',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'ถ้าจะรับข้อมูลทางอีเมล ให้ผูกอีเมลกับบัญชีก่อน',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'มีประวัติการดูแล้ว ถ้าจะตั้งเป็น "จะดู" ต้องลบเครื่องหมายก่อน',
  'Arama şu anda kapalı': 'การโทรปิดอยู่ตอนนี้',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'บัญชีผู้เยี่ยมชมเปิดการโทรไม่ได้ สร้างบัญชีก่อน',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'เซิร์ฟเวอร์กำลังรีสตาร์ท ลองใหม่สักครู่',
  'Puan 1-10 arası olmalı': 'คะแนนต้องอยู่ระหว่าง 1 ถึง 10',
  'En fazla 10 medya eklenebilir': 'เพิ่มสื่อได้ไม่เกิน 10 ไฟล์',
  'Bu cihazdan yeni hesap açılamıyor': 'สร้างบัญชีใหม่จากอุปกรณ์นี้ไม่ได้',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'ต้องมีอีเมลที่ใช้ได้ ชื่อผู้ใช้ และรหัสผ่านอย่างน้อย 6 ตัว',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'ต้องมีอีเมลที่ใช้ได้และรหัสผ่านอย่างน้อย 6 ตัว',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'ชื่อผู้ใช้ 3–20 ตัว; ตัวพิมพ์เล็ก ตัวเลข จุด ยัติภังค์ ขีดล่าง (ห้ามหัวท้าย)',
  'Bu hesap zaten bağlı': 'บัญชีนี้เชื่อมแล้ว',
  'Hesap oluşturulamadı': 'สร้างบัญชีไม่ได้',
  'Misafir hesabı oluşturulamadı': 'สร้างบัญชีผู้เยี่ยมชมไม่ได้',
  'Hesap bulunamadı': 'ไม่พบบัญชี',
  'Bu hesapta e-posta yok': 'บัญชีนี้ไม่มีอีเมล',
  'İki adımlı doğrulama zaten bu durumda':
      'การยืนยันสองขั้นเป็นสถานะนี้อยู่แล้ว',
  'Kod yanlış': 'รหัสผิด',
  'Kodun süresi doldu': 'รหัสหมดอายุ',
  'Kullanıcının e-postası yok (misafir hesap)':
      'ผู้ใช้นี้ไม่มีอีเมล (บัญชีผู้เยี่ยมชม)',
  'Bio en fazla 300 karakter olabilir': 'ประวัติได้ไม่เกิน 300 ตัวอักษร',
  'Geçersiz ülke': 'ประเทศไม่ถูกต้อง',
  'Geçersiz sosyal bağlantı': 'ลิงก์โซเชียลไม่ถูกต้อง',
  'Geçersiz doğum tarihi': 'วันเกิดไม่ถูกต้อง',
  'Liste adı gerekli': 'ต้องมีชื่อรายการ',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'ชื่อได้ไม่เกิน 60 คำอธิบาย 300 ตัวอักษร',
  'Liste bulunamadı': 'ไม่พบรายการ',
  'Değiştirilecek tercih yok': 'ไม่มีอะไรให้อัปเดต',
  'İnceleme en fazla 2000 karakter olabilir': 'รีวิวได้ไม่เกิน 2000 ตัวอักษร',
  'Önce içeriği "bitirdim" olarak işaretle': 'ทำเครื่องหมายว่าดูจบก่อน',
  'Önce kişiyi favorile': 'เพิ่มบุคคลนี้ในรายการโปรดก่อน',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'คอมเมนต์ตอนต้องมีทั้งซีซันและตอน',
  'Yanıtlanan yorum bulunamadı': 'ไม่พบคอมเมนต์ที่ตอบกลับ',
  'Geri bildirim 3-2000 karakter olmalı': 'ความคิดเห็นต้องมี 3–2000 ตัวอักษร',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'ต้องมีหัวข้อและข้อความ (อย่างน้อย 2 ตัวอักษร)',
  'Kendine mesaj gönderemezsin': 'ส่งข้อความถึงตัวเองไม่ได้',
  'Mesaj en fazla 2000 karakter olabilir': 'ข้อความได้ไม่เกิน 2000 ตัวอักษร',
  'Mesaj 1-2000 karakter olmalı': 'ข้อความต้องมี 1–2000 ตัวอักษร',
  'Mesaj bulunamadı': 'ไม่พบข้อความ',
  'Mesaj bulunamadı veya düzenlenemez': 'ไม่พบข้อความหรือแก้ไขไม่ได้',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'รายงานได้เฉพาะข้อความที่ส่งมาหาคุณ',
  'Sebep gerekli': 'ต้องมีเหตุผล',
  'İtiraz edilecek aktif bir ceza yok': 'ไม่มีโทษที่ใช้อยู่ให้ยื่นอุทธรณ์',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'คุณมีคำอุทธรณ์รอตรวจสอบอยู่แล้ว',
  'Bu ceza için itirazın zaten incelendi':
      'คำอุทธรณ์โทษนี้ได้รับการตรวจสอบแล้ว',
  'Medya bağlantısının süresi dolmuş': 'ลิงก์สื่อหมดอายุ',
  'Bu medya için imzalı bağlantı gerekli': 'สื่อนี้ต้องใช้ลิงก์ที่มีลายเซ็น',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'บริการโทรกำลังรีสตาร์ต ลองใหม่สักครู่',
  'Puan göstergesi': 'คำอธิบายสัญลักษณ์คะแนน',
  'İzleme İstatistiklerim': 'สถิติการดูของฉัน',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'เมื่อคุณทำเครื่องหมายว่าดูตอนหรือภาพยนตร์แล้ว สถิติของคุณจะเริ่มสะสมที่นี่',
  '{} sa {} dk': '{} ชม. {} นาที',
  'Yaklaşık ekran süresi': 'เวลาหน้าจอโดยประมาณ',
  'İzleme serisi': 'สตรีคการดู',
  'Şu anki seri': 'สตรีคปัจจุบัน',
  'En uzun seri': 'สตรีคยาวที่สุด',
  'Haftanın günleri': 'วันในสัปดาห์',
  'En çok izlediklerin': 'ดูมากที่สุด',
  'Bu dönemde izleme yok': 'ไม่มีการดูในช่วงนี้',
  'Paz': 'อา.',
  'Pzt': 'จ.',
  'Sal': 'อ.',
  'Çar': 'พ.',
  'Per': 'พฤ.',
  'Cum': 'ศ.',
  'Cmt': 'ส.',
  '{} bölüm': '{} ตอน',
  '{} bölüm~tekil': '{} ตอน',
  '{} kez': '{} ครั้ง',
  '{} kez~tekil': '{} ครั้ง',
  'Son {} gün · günlük': '{} วันล่าสุด · รายวัน',
  'Son {} gün · haftalık': '{} วันล่าสุด · รายสัปดาห์',
  'Ekran süren, serin ve en çok izlediklerin':
      'เวลาหน้าจอ สตรีค และรายการที่ดูมากที่สุดของคุณ',
  'Daralt': 'ย่อ',
  'Listeyi düzenle': 'แก้ไขรายการ',
  'Bitti': 'เสร็จสิ้น',
  'Sırala': 'จัดลำดับ',
  'Herkese göster': 'แสดงให้ทุกคนเห็น',
  'Başkalarından gizle': 'ซ่อนจากผู้อื่น',
  'Listeden kaldır': 'นำออกจากรายการ',
  'Listeden kaldırılsın mı?': 'นำออกจากรายการไหม',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'เรื่องนี้จะถูกนำออกจากรายการ หากต้องการเพียงซ่อน ให้ใช้ไอคอนรูปดวงตา',
  'Sıralama kaydedilemedi': 'บันทึกลำดับไม่สำเร็จ',
  'Değişiklik kaydedilemedi': 'บันทึกการเปลี่ยนแปลงไม่สำเร็จ',
  'Kaldırılamadı': 'นำออกไม่สำเร็จ',
  'Popülerlik': 'ความนิยม',
  'TMDB puanı': 'คะแนน TMDB',
  'Yapım yılı': 'ปีที่ผลิต',
  'dizi.jpg puanı': 'คะแนน dizi.jpg',
  'İzlenme': 'ยอดรับชม',
  'Yorum sayısı': 'จำนวนความคิดเห็น',
  'Tüm raflara uygulanır': 'ใช้กับทุกชั้น',
  'En popüler {} yapım arasında sıralandı':
      'จัดเรียงจาก {} เรื่องที่นิยมที่สุด',
  'Altyazı görünümü': 'ลักษณะคำบรรยาย',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık': 'สี แบบอักษร ขนาด ขอบ และความทึบ',
  'Bu bir örnek altyazıdır.': 'นี่คือคำบรรยายตัวอย่าง',
  'Ayar değiştikçe önizleme anında güncellenir.':
      'ตัวอย่างจะอัปเดตทันทีเมื่อเปลี่ยนการตั้งค่า',
  'Yazı biçimi': 'รูปแบบข้อความ',
  'Yazı rengi': 'สีข้อความ',
  'Yazı opaklığı': 'ความทึบของข้อความ',
  'Yazı tipi': 'แบบอักษร',
  'Yazı boyutu': 'ขนาดข้อความ',
  'Karakter ayrıtı': 'ขอบตัวอักษร',
  'Ayrıt türü': 'ประเภทขอบ',
  'Ayrıt rengi': 'สีขอบ',
  'Yok': 'ไม่มี',
  'Dış çizgi': 'เส้นขอบ',
  'Gölge': 'เงา',
  'Kabartma': 'นูน',
  'Oyma': 'บุ๋ม',
  'Arka plan rengi': 'สีพื้นหลัง',
  'Arka plan opaklığı': 'ความทึบของพื้นหลัง',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      'พื้นหลังคือพื้นที่ทึบด้านหลังข้อความโดยตรง ส่วนหน้าต่างคือพื้นผิวที่กว้างกว่าซึ่งอยู่หลังบล็อกคำบรรยายทั้งหมด',
  'Pencere': 'หน้าต่าง',
  'Pencere rengi': 'สีหน้าต่าง',
  'Pencere opaklığı': 'ความทึบของหน้าต่าง',
  'Altyazı görünümü sıfırlansın mı?': 'รีเซ็ตลักษณะคำบรรยายไหม',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      'การตั้งค่าสี แบบอักษร ขนาด ขอบ และความทึบจะกลับเป็นค่าเริ่มต้น',
  'Altyazı görünümü varsayılana döndü':
      'รีเซ็ตลักษณะคำบรรยายเป็นค่าเริ่มต้นแล้ว',
  '{} indiriliyor…': 'กำลังดาวน์โหลด {}…',
  'Seçince indirilir': 'ดาวน์โหลดเมื่อเลือก',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      'ดาวน์โหลดแบบอักษรไม่สำเร็จ กำลังแสดงด้วยแบบอักษรเริ่มต้น',
  'Beyaz': 'ขาว',
  'Siyah': 'ดำ',
  'Kırmızı': 'แดง',
  'Yeşil': 'เขียว',
  'Mavi': 'น้ำเงิน',
  'Sarı': 'เหลือง',
  'Camgöbeği': 'ฟ้าอมเขียว',
  'Macenta': 'บานเย็น',
  'Yapım bütçesi': 'งบสร้าง',
  'Yapım bütçesi ve dünya çapında hasılat': 'งบสร้างและรายได้ทั่วโลก',
  'Dizinin yayın durumu': 'สถานะการออกอากาศของซีรีส์',
  'Devam ediyor': 'กำลังฉาย',
  'Sona erdi': 'จบแล้ว',
  'İptal edildi': 'ถูกยกเลิก',
  'Yapımda': 'อยู่ระหว่างสร้าง',
  'Planlandı': 'วางแผนไว้',
  'Pilot bölüm': 'ตอนนำร่อง',
  'Ad': 'ชื่อ',
  'Adın': 'ชื่อของคุณ',
  'Kullanıcı adı': 'ชื่อผู้ใช้',
  'Kullanıcı adını değiştir': 'เปลี่ยนชื่อผู้ใช้',
  'Kullanıcı adını 90 günde bir değiştirebilirsin':
      'เปลี่ยนชื่อผู้ใช้ได้ทุก 90 วัน',
  'Değiştir': 'เปลี่ยน',
  '{} gün sonra değiştirebilirsin': 'เปลี่ยนได้ในอีก {} วัน',
  'Kullanıcı adın: @{}': 'ชื่อผู้ใช้ของคุณ: @{}',
  'Bu kullanıcı adı zaten alınmış': 'ชื่อผู้ใช้นี้ถูกใช้ไปแล้ว',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış':
      'ชื่อผู้ใช้นี้ถูกสงวนไว้ให้บัญชีอื่นอยู่ในขณะนี้',
  'Bu zaten senin kullanıcı adın': 'นี่เป็นชื่อผู้ใช้ของคุณอยู่แล้ว',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      'ชื่อผู้ใช้ 3–20 ตัว; ตัวพิมพ์เล็ก ตัวเลข จุด ยัติภังค์ ขีดล่าง',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      'แสดงเหนือชื่อผู้ใช้ในโปรไฟล์ เว้นว่างไว้ก็ได้',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      'หลังเปลี่ยนแล้วจะเปลี่ยนอีกไม่ได้เป็นเวลา 90 วัน ชื่อผู้ใช้เดิมจะถูกสงวนไว้ให้คุณ 90 วัน — กลับไปใช้ได้ถ้าต้องการ และช่วงนั้นไม่มีใครเอาไปได้ ลิงก์ที่ชี้ไปยังชื่อเดิมจะไม่เปิดโปรไฟล์ของคุณอีกต่อไป',
  'Etkinliğim': 'กิจกรรม',
  'Tercihler': 'ค่ากำหนด',
  'Gizlilik ve güvenlik': 'ความเป็นส่วนตัวและความปลอดภัย',
  'Destek': 'ความช่วยเหลือ',
  'Hesap': 'บัญชี',
  '{} dizileri': 'ซีรีส์ของ {}',
  '{} filmleri': 'หนังของ {}',
  'En üste taşı': 'ย้ายขึ้นบนสุด',
  'Sırayı sıfırla': 'รีเซ็ตลำดับ',
  'Listede ara': 'ค้นหาในรายการ',
  'Elle sıra sıfırlansın mı?': 'รีเซ็ตลำดับที่จัดเองไหม',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      'รายการจะกลับไปเป็นลำดับเริ่มต้น (รายการที่ทำเครื่องหมายล่าสุดขึ้นก่อน)',
  'Sıra sıfırlanamadı': 'รีเซ็ตลำดับไม่สำเร็จ',
  'Listenin en üstüne taşındı': 'ย้ายขึ้นบนสุดของรายการแล้ว',
  'Adlar yükleniyor…': 'กำลังโหลดชื่อ…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      'กดค้างที่โปสเตอร์เพื่อลาก หากต้องการดึงเรื่องที่อยู่ไกลขึ้นมาข้างหน้า ให้ใช้ “ย้ายขึ้นบนสุด”',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      'ลากไม่ได้ขณะค้นหา ใช้ “ย้ายขึ้นบนสุด” เพื่อดึงขึ้นมาข้างหน้า ({} ผลลัพธ์)',
  'Görünüm': 'มุมมอง',
  'En çok izlediğin filmler': 'หนังที่ดูมากที่สุด',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      'เวลาเป็นค่าประมาณ: ตอนละ ~{} นาที หนังละ ~{} นาที',
  'Bu kullanıcı adı sistem tarafından ayrılmış':
      'ชื่อผู้ใช้นี้ถูกสงวนไว้โดยระบบ',
  'Ekran süresi': 'เวลาหน้าจอ',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir":
      'เวลาเป็นความยาวจริงของตอนและหนังจาก TMDB',
  'Tüm zamanlar: {} bölüm · {} film · {}': 'ตลอดกาล: {} ตอน · {} เรื่อง · {}',
  'Kabul et':
      'ยอมรับ',
  'Reddedilenler':
      'ที่ปฏิเสธแล้ว',
  'İstekler':
      'คำขอ',
  'Reddettiğin istek yok':
      'ไม่มีคำขอที่ปฏิเสธ',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      'คำขอที่ปฏิเสธจะอยู่ที่นี่ คุณยอมรับอีกครั้งได้ทุกเมื่อ',
  'Ne izlesem?': 'ดูอะไรดี?',
  'Karışık': 'คละกัน',
  'Çarkı çevir': 'หมุนวงล้อ',
  'Tekrar çevir': 'หมุนอีกครั้ง',
  'Bu türde içerik yok': 'ไม่มีเนื้อหาประเภทนี้',
  'Bütçe': 'งบประมาณ',
};
