/// Otomatik üretilen çeviri haritası (te).
const Map<String, String> cevirilerTe = {
  'Hepsini gördün, baştan gösteriyoruz':
      'మీరు అన్నింటినీ చూశారు, మేము మీకు మొదటి నుండి చూపిస్తాము',
  'Aktarılacak tanınan veri bulunamadı.':
      'దిగుమతికి గుర్తించదగిన డేటా ఏదీ దొరకలేదు.',
  'Arama': 'శోధన',
  'Aramaya başla': 'వెతకడం మొదలుపెట్టు',
  'Son aramalar': 'ఇటీవలి శోధనలు',
  'Ayarlar': 'సెట్టింగ్స్',
  'Bağla': 'లింక్ చేయి',
  'Bio': 'బయో',
  'Bitirdim': 'పూర్తి చేశాను',
  'Bunları da Beğenebilirsin': 'ఇవి కూడా నచ్చొచ్చు',
  'Bölüm': 'ఎపిసోడ్',
  'Bıraktım': 'వదిలేశాను',
  'Dil': 'భాష',
  'Dil ara...': 'భాషను వెతుకు...',
  'Dizi': 'సిరీస్',
  'Dizi ve filmlerini takip et': 'నీ సిరీస్‌లు, సినిమాలను ట్రాక్ చేయి',
  'Dizi yorumu': 'సిరీస్ కామెంట్',
  'Dizi, film veya kişi ara...': 'సిరీస్, సినిమా లేదా వ్యక్తిని వెతుకు...',
  'Dosya en fazla 30MB olabilir': 'ఫైల్ గరిష్టంగా 30MB ఉండాలి',
  'Dosya en fazla {}MB olabilir': 'ఫైల్ గరిష్టంగా {}MB ఉండాలి',
  'E-posta': 'ఇమెయిల్',
  'E-posta veya kullanıcı adı': 'ఇమెయిల్ లేదా యూజర్‌నేమ్',
  'En az 2 harf yaz': 'కనీసం 2 అక్షరాలు టైప్ చేయి',
  'Film': 'సినిమా',
  'Film yorumu': 'సినిమా కామెంట్',
  'Fotoğraf / video ekle': 'ఫోటో / వీడియో జోడించు',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'ఫోటో లేదా GIF — ప్రొఫైల్ మరియు కవర్ ఫోటో',
  'Giriş Yap': 'లాగిన్',
  'Gönder': 'పంపు',
  'Gönderildi': 'పంపబడింది',
  'Haftanın Dizileri': 'ఈ వారం సిరీస్‌లు',
  'Haftanın Filmleri': 'ఈ వారం సినిమాలు',
  'Henüz izleme kaydın yok': 'ఇంకా వీక్షణ రికార్డు లేదు',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'ఇంకా లిస్ట్ లేదు — ప్రొఫైల్ ట్యాబ్ నుండి సృష్టించు.',
  'Henüz yorum yok.': 'ఇంకా కామెంట్లు లేవు.',
  'Hesabın bağlandı!': 'నీ ఖాతా లింక్ అయింది!',
  'Hesabın yok mu? Kayıt ol': 'ఖాతా లేదా? సైన్ అప్ చేయి',
  'Hesabını Bağla': 'నీ ఖాతాను లింక్ చేయి',
  'Hesap Oluştur': 'ఖాతా సృష్టించు',
  'Kapak resmi ekle': 'కవర్ ఫోటో జోడించు',
  'Kaydet': 'సేవ్ చేయి',
  'Kendinden bahset...': 'నీ గురించి చెప్పు...',
  'Keşfet': 'అన్వేషించు',
  'Kimseyi takip etmiyor': 'ఎవరినీ ఫాలో అవడం లేదు',
  'Kişi ara': 'వ్యక్తిని వెతుకు',
  'Kişi yorumu': 'వ్యక్తి కామెంట్',
  'Konuk Oyuncular': 'అతిథి నటులు',
  'Kullanıcı adı (küçük harf)': 'యూజర్‌నేమ్ (చిన్న అక్షరాలు)',
  'Kullanıcı adı ara...': 'యూజర్‌నేమ్ వెతుకు...',
  'Liste adı': 'లిస్ట్ పేరు',
  'Listeye Ekle': 'లిస్ట్‌కి జోడించు',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'నువ్వు గెస్ట్ ఖాతాలో ఉన్నావు — ఇమెయిల్‌తో లింక్ చేసి, డేటాను కోల్పోకు!',
  'Misafir olarak devam et': 'గెస్ట్‌గా కొనసాగు',
  'Oluştur': 'సృష్టించు',
  'Oyuncular': 'నటులు',
  'Profil': 'ప్రొఫైల్',
  'Profil kaydedildi': 'ప్రొఫైల్ సేవ్ అయింది',
  'Puanla': 'రేట్ చేయి',
  'Puanı Sil': 'రేటింగ్ తొలగించు',
  'Puanın': 'నీ రేటింగ్',
  'Sezonlar': 'సీజన్లు',
  'Sunucu hatası ({})': 'సర్వర్ లోపం ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'S{}E{} కామెంట్',
  'Takibi Bırak': 'అన్‌ఫాలో',
  'Takip': 'ఫాలోయింగ్',
  'Takip Edilenler': 'ఫాలో అవుతున్నవారు',
  'Takip Et': 'ఫాలో అవ్వు',
  'Takipçi': 'ఫాలోవర్',
  'Takipçi yok': 'ఫాలోవర్లు లేరు',
  'Takipçiler': 'ఫాలోవర్లు',
  'Takvim': 'క్యాలెండర్',
  'Tamam': 'సరే',
  'Tekrar Dene': 'మళ్ళీ ప్రయత్నించు',
  'Tekrar dene': 'మళ్ళీ ప్రయత్నించు',
  'Toplam İzleme Süresi': 'మొత్తం స్క్రీన్ సమయం',
  'Tüm Zamanların En İyileri': 'అన్ని కాలాల్లో అత్యుత్తమమైనవి',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'నీ మొత్తం డేటాను (వీక్షణలు, రేటింగ్‌లు, కామెంట్లు, లిస్టులు) TV Time అనుకూల ZIP గా పొందు లేదా వేరే యాప్ నుండి వచ్చిన ZIP ను దిగుమతి చేయి.',
  'Tümünü Kaldır': 'అన్నీ తొలగించు',
  'Tümünü İzledim': 'అన్నీ చూశాను',
  'Türk Dizileri': 'టర్కిష్ సిరీస్‌లు',
  'Veri içe aktar (.zip)': 'డేటా దిగుమతి (.zip)',
  'Verilerim': 'నా డేటా',
  'Verilerimi dışa aktar (e-posta)': 'నా డేటాను ఎగుమతి చేయి (ఇమెయిల్)',
  'Verilerini dışa aktar': 'నీ డేటాను ఎగుమతి చేయి',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'రాబోయే ఎపిసోడ్ లేదు.\nసిరీస్ వివరాల్లో "చూస్తున్నాను" స్థితికి మార్చి, కొత్త ఎపిసోడ్లను ఇక్కడ ఫాలో అవ్వు.',
  'Yapımları': 'ఫిల్మోగ్రఫీ',
  'Yeni Diziler': 'కొత్త సిరీస్‌లు',
  'Yeni Liste': 'కొత్త లిస్ట్',
  'Yeni kullanıcı adı (isteğe bağlı)': 'కొత్త యూజర్‌నేమ్ (ఐచ్ఛికం)',
  'Yorum': 'కామెంట్',
  'Yorumunu yaz...': 'నీ కామెంట్ రాయి...',
  'Zaten hesabın var mı? Giriş yap': 'ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వు',
  'ort. {}': 'సగటు {}',
  'takip': 'ఫాలోయింగ్',
  'takipçi': 'ఫాలోవర్లు',
  '{} / {} bölüm': '{} / {} ఎపిసోడ్లు',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} నెలలు',
  '{} ay~tekil': '{} నెల',
  '{} bölüm izlendi': '{} ఎపిసోడ్లు చూశావు',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} నిమి',
  '{} dk~tekil': '{} నిమి',
  '{} gün': '{} రోజులు',
  '{} gün~tekil': '{} రోజు',
  '{} içerik': '{} కంటెంట్',
  '{} içerik · otomatik': '{} కంటెంట్ · ఆటోమేటిక్',
  '{} kayıt atlandı (eşleşmedi).': '{} రికార్డులు దాటవేయబడ్డాయి (సరిపోలలేదు).',
  '{} saat': '{} గంటలు',
  '{} saat~tekil': '{} గంట',
  '{} sezon': '{} సీజన్లు',
  '{} yıl': '{} సంవత్సరాలు',
  '{} yıl~tekil': '{} సంవత్సరం',
  '{}. Bölüm': 'ఎపిసోడ్ {}',
  '{}. Sezon': 'సీజన్ {}',
  'Çıkış Yap': 'లాగ్ అవుట్',
  'Ülke': 'దేశం',
  'Ülke ara...': 'దేశాన్ని వెతుకు...',
  'Ülke seç': 'దేశాన్ని ఎంచుకో',
  'İlk yorumu sen yaz!': 'మొదటి కామెంట్ నువ్వే రాయి!',
  'İncelemeler': 'సమీక్షలు',
  'İncelemen (isteğe bağlı)': 'నీ సమీక్ష (ఐచ్ఛికం)',
  'İptal': 'రద్దు',
  'İzlediklerim': 'నేను చూసినవి',
  'İzledim': 'చూశాను',
  'İzledin': 'చూశావు',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'నీ వీక్షణ చరిత్ర, లిస్టులు భద్రంగా ఉంటాయి; ఇక ఏ పరికరం నుండైనా లాగిన్ అవ్వొచ్చు.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'నీ వీక్షణ చరిత్ర, రేటింగ్‌లు, కామెంట్లు, లిస్టులు ZIP గా నమోదిత ఇమెయిల్ చిరునామాకు పంపబడతాయి.',
  'İzleyeceğim': 'చూస్తాను',
  'İzliyorum': 'చూస్తున్నాను',
  'İçe aktarım tamamlandı': 'దిగుమతి పూర్తయింది',
  'Şifre': 'పాస్‌వర్డ్',
  '• profil bilgisi': '• ప్రొఫైల్ సమాచారం',
  '• {} dizi durumu': '• {} సిరీస్ స్థితి',
  '• {} izleme kaydı': '• {} వీక్షణ రికార్డు',
  '• {} liste': '• {} లిస్ట్',
  '• {} puan': '• {} రేటింగ్',
  '• {} yorum': '• {} కామెంట్',
  '{}+ yapım': '{}+ చిత్రాలు',
  'Yorumlar': 'కామెంట్లు',
  'Yorumlar ({})': 'కామెంట్లు ({})',
  'Yorumları ({})': 'కామెంట్లు ({})',
  'Listelerim': 'నా లిస్టులు',
  'Nereden izledin?': 'ఎక్కడ చూశావు?',
  'Diziye git': 'షోకి వెళ్లు',
  'TV / Kanal': 'టీవీ / ఛానెల్',
  'Sinema': 'సినిమా హాల్',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'ఇతర',
  'Akış': 'ఫీడ్',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'నీ ఫీడ్ ఖాళీగా ఉంది.\nనువ్వు చూసే షోలు, సినిమాలపై కామెంట్లు వస్తే ఇక్కడ కనిపిస్తాయి.',
  'Listeleri ({})': 'వారి జాబితాలు ({})',
  'Liste boş.': 'ఈ జాబితా ఖాళీగా ఉంది.',
  'Yanıtla': 'బదులివ్వు',
  '@{} kullanıcısına yanıt veriyorsun': '@{}కి బదులిస్తున్నావు',
  'İzlediğim Diziler ({})': 'నేను చూసిన షోలు ({})',
  'İzlediğim Filmler ({})': 'నేను చూసిన సినిమాలు ({})',
  'Tümünü gör': 'అన్నీ చూడు',
  'Bildirimler': 'నోటిఫికేషన్లు',
  'Henüz bildirim yok': 'ఇంకా నోటిఫికేషన్లు లేవు',
  '@{} yorumuna yanıt verdi': '@{} నీ కామెంట్‌కు బదులిచ్చారు',
  '@{} yorumunu beğendi': '@{} నీ కామెంట్‌ను ఇష్టపడ్డారు',
  '@{} seni takip etti': '@{} నిన్ను ఫాలో చేశారు',
  '@{} sana mesaj gönderdi': '@{} నీకు సందేశం పంపారు',
  'Mesajlar': 'సందేశాలు',
  'Mesaj': 'సందేశం',
  'Mesaja eklenecek': 'సందేశంలో జోడించబడుతుంది',
  'Mesajını yaz...': 'సందేశం రాయి...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'ఇంకా చాట్‌లు లేవు.\nప్రొఫైల్ తెరిచి సందేశం పంపు.',
  'Şifreni mi unuttun?': 'పాస్‌వర్డ్ మర్చిపోయావా?',
  'Şifreyi Sıfırla': 'పాస్‌వర్డ్ రీసెట్',
  'E-postadaki kod': 'ఇమెయిల్‌లోని కోడ్',
  'Yeni şifre': 'కొత్త పాస్‌వర్డ్',
  'Sana Özel': 'నీ కోసం',
  '{} özetin': 'నీ {} సారాంశం',
  'Yıllık izleme istatistiklerin': 'వార్షిక వీక్షణ గణాంకాలు',
  'Rozetler': 'బ్యాడ్జీలు',
  'Verdiğin puan': 'ఇచ్చిన రేటింగ్‌లు',
  'Ortalama puanın': 'సగటు రేటింగ్',
  'En çok izlediğin diziler': 'ఎక్కువగా చూసిన షోలు',
  'İlk Bölüm': 'మొదటి ఎపిసోడ్',
  '100 Bölüm': '100 ఎపిసోడ్లు',
  '1000 Bölüm': '1000 ఎపిసోడ్లు',
  'İlk Film': 'మొదటి సినిమా',
  '50 Film': '50 సినిమాలు',
  'İlk Yorum': 'మొదటి కామెంట్',
  '25 Yorum': '25 కామెంట్లు',
  '10 Puan': '10 రేటింగ్‌లు',
  'İlk Takipçi': 'మొదటి ఫాలోవర్',
  '10 Dizi Bitirdin': '10 షోలు పూర్తి',
  'İzlemeyi Bıraktım': 'చూడటం మానేశాను',
  'İzlediği Diziler ({})': 'వారు చూసిన షోలు ({})',
  'İzlediği Filmler ({})': 'వారు చూసిన సినిమాలు ({})',
  '500 Bölüm': '500 ఎపిసోడ్లు',
  '5000 Bölüm': '5000 ఎపిసోడ్లు',
  '10 Film': '10 సినిమాలు',
  '100 Film': '100 సినిమాలు',
  '100 Yorum': '100 కామెంట్లు',
  '50 Puan': '50 రేటింగ్‌లు',
  '100 Puan': '100 రేటింగ్‌లు',
  '10 Takipçi': '10 ఫాలోవర్లు',
  '50 Takipçi': '50 ఫాలోవర్లు',
  '25 Dizi Bitirdin': '25 షోలు పూర్తి',
  '50 Dizi Bitirdin': '50 షోలు పూర్తి',
  '10 Beğeni': '10 లైక్‌లు',
  '100 Beğeni': '100 లైక్‌లు',
  'yazıyor...': 'టైప్ చేస్తున్నారు...',
  'Profil düzeni': 'ప్రొఫైల్ లేఅవుట్',
  'Konumla ve kırp': 'స్థానం సర్దుబాటు చేసి కత్తిరించు',
  'Listeye eklendi': 'జాబితాకు జోడించబడింది',
  'Listeyi sil?': 'జాబితాను తొలగించాలా?',
  'Sil': 'తొలగించు',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'ఇది ఎప్పుడూ చూడనిదిగా గుర్తించబడి నీ జాబితాల నుండి తీసివేయబడుతుంది.',
  'Gelecek bölüm bugün': 'తదుపరి ఎపిసోడ్ ఈరోజు',
  'Gelecek bölüm {} gün sonra': 'తదుపరి ఎపిసోడ్ {} రోజుల్లో',
  'Tema': 'థీమ్',
  'Sistem': 'సిస్టమ్',
  'Koyu': 'డార్క్',
  'Açık': 'లైట్',
  'İzleyenler': 'వీక్షకులు',
  'Yorumunu yaz... (@ ile etiketle)': 'నీ కామెంట్ రాయి... (@ తో ట్యాగ్ చెయ్యి)',
  '@{} bir yorumda seni etiketledi': '@{} నిన్ను ఒక కామెంట్‌లో ట్యాగ్ చేశారు',
  'Mesajı sil': 'సందేశాన్ని తొలగించు',
  'Mesaj silinemedi': 'సందేశాన్ని తొలగించలేకపోయాం',
  'Bağlantı geçersiz veya sayfa bulunamadı': 'లింక్ చెల్లదు లేదా పేజీ దొరకలేదు',
  'Keşfet\'e dön': 'అన్వేషణకు తిరిగి వెళ్లు',
  'Düzenle': 'సవరించు',
  'Mesajı düzenle': 'సందేశం సవరించు',
  'Yanıtlanıyor': 'ప్రత్యుత్తరం ఇస్తోంది',
  'düzenlendi': 'సవరించబడింది',
  'Fotoğraf': 'ఫోటో',
  'Video': 'వీడియో',
  'İçerik': 'కంటెంట్',
  'çevrimiçi': 'ఆన్‌లైన్',
  'son görülme {} dk önce': 'చివరిగా {} నిమి క్రితం',
  'son görülme {} saat önce': 'చివరిగా {} గం క్రితం',
  'son görülme {} gün önce': 'చివరిగా {} రోజు క్రితం',
  'Yorumlar yüklenemedi': 'కామెంట్‌లను లోడ్ చేయలేకపోయాం',
  'Favori': 'ఇష్టమైనవి',
  'Listeye ekle': 'జాబితాకు జోడించు',
  'İçerik paylaş': 'షేర్ చేయి',
  'Kapat': 'మూసివేయి',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'నువ్వు చూసినట్లు గుర్తించినవన్నీ ఇక్కడ చేరతాయి.',
  'Henüz sohbetin yok': 'ఇంకా సంభాషణలు లేవు',
  'Bir profile girip mesaj gönderebilirsin.': 'ప్రొఫైల్ తెరిచి సందేశం పంపు.',
  'Listeyi sil': 'జాబితాను తొలగించు',
  'Puan kaydedilemedi': 'రేటింగ్‌ను సేవ్ చేయలేకపోయాం',
  'Nerede İzlenir': 'ఎక్కడ చూడాలి',
  'Abonelik': 'సబ్‌స్క్రిప్షన్',
  'Kirala': 'అద్దెకు తీసుకోండి',
  'Satın al': 'కొనండి',
  'Hoş geldin!': 'స్వాగతం!',
  'İzlemek istediğin dizi ve filmleri seç':
      'నువ్వు చూడాలనుకునే సిరీస్‌లు, సినిమాలను ఎంచుకో',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'నీ ఎంపికలు "చూస్తాను" లిస్ట్‌కు జోడించబడతాయి',
  'Şimdilik atla': 'ప్రస్తుతానికి దాటవేయి',
  'Devam et': 'కొనసాగించు',
  '{} ekle': '{} జోడించు',
  'Şikayet et': 'ఫిర్యాదు చెయ్యి',
  'Engelle': 'బ్లాక్ చెయ్యి',
  'Engeli kaldır': 'అన్‌బ్లాక్ చెయ్యి',
  'Kullanıcı engellendi': 'వినియోగదారు బ్లాక్ అయ్యారు',
  'Engel kaldırıldı': 'బ్లాక్ తీసివేయబడింది',
  'Şikayet sebebi': 'ఫిర్యాదు కారణం',
  'Spam veya yanıltıcı': 'స్పామ్ లేదా తప్పుదోవ పట్టించేది',
  'Taciz veya nefret söylemi': 'వేధింపు లేదా ద్వేషపూరిత ప్రసంగం',
  'Uygunsuz / cinsel içerik': 'అనుచిత / లైంగిక కంటెంట్',
  'Şiddet veya tehlikeli içerik': 'హింస లేదా ప్రమాదకర కంటెంట్',
  'Telif hakkı ihlali': 'కాపీరైట్ ఉల్లంఘన',
  'Şikayetin alındı, teşekkürler': 'నీ ఫిర్యాదు అందింది, ధన్యవాదాలు',
  'Hesabımı Sil': 'నా ఖాతాను తొలగించు',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'నీ ఖాతా, అన్ని డేటా (చరిత్ర, రేటింగ్‌లు, కామెంట్‌లు, జాబితాలు, సందేశాలు) శాశ్వతంగా తొలగించబడతాయి. దీన్ని రద్దు చేయలేం.',
  'Şifreni gir': 'నీ పాస్‌వర్డ్ ఎంటర్ చెయ్యి',
  'Hesabımı kalıcı sil': 'నా ఖాతాను శాశ్వతంగా తొలగించు',
  'Sesli mesaj': 'వాయిస్ మెసేజ్',
  'Ses gönderilemedi': 'వాయిస్ మెసేజ్ పంపడం సాధ్యపడలేదు',
  'Kaydediliyor…': 'రికార్డ్ అవుతోంది…',
  'Ses oynatılamadı': 'ఆడియో ప్లే చేయలేకపోయాం',
  'Oynat': 'ప్లే చేయి',
  'Duraklat': 'పాజ్ చేయి',
  'Liste görünümü': 'జాబితా వీక్షణ',
  'Takvim görünümü': 'క్యాలెండర్ వీక్షణ',
  'Önceki ay': 'మునుపటి నెల',
  'Sonraki ay': 'తదుపరి నెల',
  'Bu gün bölüm yok': 'ఈ రోజు ఎపిసోడ్‌లు లేవు',
  'Gizlilik Politikası': 'గోప్యతా విధానం',
  'Son güncelleme: {}': 'చివరి అప్‌డేట్: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'dizi.jpg యాప్ మరియు dizijpg.com సైట్ వాడేటప్పుడు ఏ డేటా సేకరిస్తారో, ఎలా వాడతారో, నీ హక్కులు ఏమిటో ఈ విధానం వివరిస్తుంది.',
  'Topladığımız Veriler': 'మేము సేకరించే డేటా',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'ఖాతా: ఇమెయిల్ చిరునామా, యూజర్‌నేమ్, పాస్‌వర్డ్. పాస్‌వర్డ్‌లు తిరిగి చదవలేని హ్యాష్ రూపంలో నిల్వ అవుతాయి; గెస్ట్ ఖాతాలను ఇమెయిల్ లేకుండా వాడుకోవచ్చు.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'ప్రొఫైల్: అవతార్, కవర్ ఫోటో, బయో, దేశం వంటి నువ్వు జోడించాలనుకున్న వివరాలు.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'వాడకం: నీ వీక్షణ చరిత్ర, రేటింగ్‌లు, వ్యాఖ్యలు, జాబితాలు, రియాక్షన్‌లు, ఇష్టమైనవి.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'సందేశాలు: నీ టెక్స్ట్, ఫోటో, వాయిస్ సందేశాలు మా సర్వర్లలో నిల్వ అవుతాయి. సందేశాలకు ఎండ్-టు-ఎండ్ ఎన్‌క్రిప్షన్ లేదు; రిపోర్ట్ అయితేనే మోడరేషన్ కోసం చూస్తారు.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'అప్‌లోడ్ చేసిన మీడియా: ప్రొఫైల్, వ్యాఖ్యలు, సందేశాల్లో నువ్వు జోడించే ఫోటోలు, GIF, వీడియోలు, వాయిస్ రికార్డింగ్‌లు.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'సాంకేతికం: IP చిరునామా, సుమారు ప్రాంతం (దేశం/నగరం స్థాయి), పరికర ప్లాట్‌ఫారమ్, యాప్ వెర్షన్, ఎర్రర్ లాగ్‌లు. ఇవి భద్రత, లోపాల సరిదిద్దటం కోసం ఉంచుతాం.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'నోటిఫికేషన్లు: పుష్ నోటిఫికేషన్ల కోసం నీ పరికర టోకెన్, భాషా ఎంపిక నిల్వ అవుతాయి. పరికర సెట్టింగ్స్ నుంచి ఎప్పుడైనా నోటిఫికేషన్లు ఆపేయవచ్చు.',
  'Verileri Nasıl Kullanırız': 'డేటాను ఎలా వాడతాం',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'నీ డేటాను సేవ అందించడానికి, ఖాతా రక్షణకు, నోటిఫికేషన్లు పంపడానికి, లోపాలు సరిచేయడానికి, దుర్వినియోగం ఆపడానికి మాత్రమే వాడతాం. నీ డేటాను అమ్మము; ప్రకటనల కోసం ఎవరితోనూ పంచుకోము.',
  'Çerezler ve Yerel Depolama': 'కుకీలు మరియు లోకల్ స్టోరేజ్',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'నిన్ను లాగిన్‌లో ఉంచడానికి, భాష/థీమ్ వంటి ఎంపికలను గుర్తుంచుకోవడానికి మాత్రమే లోకల్ స్టోరేజ్ వాడతాం. ప్రకటన లేదా ట్రాకింగ్ కుకీలు లేవు.',
  'Üçüncü Taraf Hizmetler': 'మూడో పక్ష సేవలు',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'సిరీస్, సినిమాల డేటా TMDB నుంచి, స్ట్రీమింగ్ ప్లాట్‌ఫారమ్ సమాచారం JustWatch నుంచి వస్తాయి. పుష్ నోటిఫికేషన్లు Google Firebase ద్వారా చేరతాయి; సైట్ ట్రాఫిక్‌ను Cloudflare కాపాడుతుంది. ఈ సేవలకు వాటి సొంత గోప్యతా విధానాలు వర్తిస్తాయి.',
  'Saklama ve Silme': 'నిల్వ మరియు తొలగింపు',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'నీ ఖాతా ఉన్నంతవరకు నీ డేటా ఉంటుంది. సెట్టింగ్స్‌లోని "నా ఖాతాను తొలగించు" ద్వారా ఖాతాను శాశ్వతంగా తొలగించవచ్చు; డేటా వెంటనే, బ్యాకప్‌లలోని కాపీలు గరిష్ఠంగా 14 రోజుల్లో తొలగుతాయి. ఎర్రర్ లాగ్‌లు 30 రోజుల తర్వాత ఆటోమేటిక్‌గా తొలగుతాయి.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'సెట్టింగ్స్ నుంచి నీ డేటాను ZIP రూపంలో ఎగుమతి చేసుకోవచ్చు; ఆర్కైవ్ నీ ఇమెయిల్ చిరునామాకు పంపబడుతుంది.',
  'Güvenlik': 'భద్రత',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'డేటా ఎన్‌క్రిప్టెడ్ కనెక్షన్ల (HTTPS) ద్వారా వెళ్తుంది; పరిమిత యాక్సెస్ ఉన్న సర్వర్లలో నిల్వ అవుతుంది.',
  'Çocukların Gizliliği': 'పిల్లల గోప్యత',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg 13 ఏళ్లలోపు పిల్లల కోసం కాదు.',
  'Hakların': 'నీ హక్కులు',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK మరియు GDPR ప్రకారం నీ డేటాను చూడటానికి, సరిచేయడానికి, తొలగించడానికి, బదిలీ చేయడానికి నీకు హక్కు ఉంది. వీటి కోసం మాకు రాయి: {}',
  'Değişiklikler': 'మార్పులు',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'ఈ విధానం మారితే కొత్త వెర్షన్ ఇదే పేజీలో ప్రచురించబడి తేదీ అప్‌డేట్ అవుతుంది.',
  'Kayıt olarak {} kabul etmiş olursun.':
      'నమోదు చేసుకోవడం ద్వారా నువ్వు {} అంగీకరిస్తున్నావు.',
  'Kullanıcılar': 'వినియోగదారులు',
  'Fotoğrafı değiştir': 'ఫోటో మార్చు',
  'Yeniden konumlandır': 'మళ్లీ సర్దు',
  'Bir şeyler ters gitti': 'ఏదో తప్పు జరిగింది',
  'Sosyal Bağlantılar': 'సోషల్ లింక్‌లు',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'నీ ప్రొఫైల్‌లో గరిష్ఠంగా 3 లింక్‌లు కనిపిస్తాయి.',
  'Platform seç': 'ప్లాట్‌ఫారమ్ ఎంచుకో',
  'Kullanıcı adın': 'నీ యూజర్‌నేమ్',
  'Ekle': 'జోడించు',
  'Kaldır': 'తీసేయి',
  'Kopyalandı: {}': 'కాపీ అయింది: {}',
  'Geçersiz kullanıcı adı': 'చెల్లని యూజర్‌నేమ్',
  'Bağlantı ekle': 'లింక్ జోడించు',
  'Spoiler olabilir — dokun ve gör':
      'స్పాయిలర్ ఉండవచ్చు — చూడటానికి ట్యాప్ చేయి',
  'Beğeni': 'లైక్‌లు',
  'Beğen': 'ఇష్టం',
  'Görüntülenme': 'వీక్షణలు',
  'Tam ekran': 'పూర్తి స్క్రీన్',
  'Arama başarısız': 'శోధన విఫలమైంది',
  'Sonuç bulunamadı': 'ఫలితాలు లేవు',
  'Dizi ve Filmler': 'సిరీస్ & సినిమాలు',
  'Kişiler': 'వ్యక్తులు',
  'Ana Sayfa': 'హోమ్',
  'Paylaş': 'షేర్',
  'Yanıtlar': 'జవాబులు',
  'Yaklaşan Bölümler': 'రాబోయే ఎపిసోడ్‌లు',
  'Yetişme Listesi': 'క్యాచ్-అప్ జాబితా',
  'Şunu mu demek istedin': 'మీ ఉద్దేశం ఇదేనా',
  'Spoiler': 'స్పాయిలర్',
  'Spoiler — dokun ve gör': 'స్పాయిలర్ — చూడటానికి నొక్కండి',
  'uyum': 'సరిపోలిక',
  'Uyum': 'సరిపోలిక',
  '{} ortak dizi': '{} ఉమ్మడి సిరీస్‌లు',
  '{} ortak film': '{} ఉమ్మడి సినిమాలు',
  'Bildirim Tercihleri': 'నోటిఫికేషన్ ప్రాధాన్యతలు',
  'Beğeniler': 'ఇష్టాలు',
  'Yeni takipçiler': 'కొత్త అనుచరులు',
  'Etiketlenmeler': 'ప్రస్తావనలు',
  'Yeniden izledim': 'మళ్లీ చూశారు',
  '{}. kez izlendi': '{} సార్లు చూశారు',
  'Gönderi bulunamadı': 'పోస్ట్ కనబడలేదు',
  'Gözat': 'బ్రౌజ్',
  'Diziler': 'సిరీస్‌లు',
  'Filmler': 'సినిమాలు',
  'Tümü': 'అన్నీ',
  'Farklı bir tür seç.': 'వేరే శైలిని ప్రయత్నించండి.',
  'Gizlilik': 'గోప్యత',
  'İzlediklerimi gizle': 'నేను చూసినవి దాచు',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'నువ్వు చూసిన సిరీస్‌లు, సినిమాలు నీ ప్రొఫైల్‌లో కనిపించవు',
  'Yorumlarımı gizle': 'నా కామెంట్లు దాచు',
  'Profilinde yorumların görünmez': 'నీ కామెంట్లు నీ ప్రొఫైల్‌లో కనిపించవు',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'ఒక నిర్దిష్ట సిరీస్ లేదా సినిమాను దాని పేజీలోని "నా ప్రొఫైల్‌లో దాచు" చిప్‌తో దాచవచ్చు.',
  'Geri Bildirim': 'ఫీడ్‌బ్యాక్',
  'Uygulama hakkında görüş ve önerini yaz...':
      'యాప్ గురించి నీ అభిప్రాయం, సూచనలు రాయి...',
  'Teşekkürler! Geri bildirimin alındı.': 'ధన్యవాదాలు! నీ ఫీడ్‌బ్యాక్ అందింది.',
  'Profilimde gizle': 'నా ప్రొఫైల్‌లో దాచు',
  'Yorumları': 'కామెంట్లు',
  'Bu kullanıcı henüz bir şey izlememiş.': 'ఈ వినియోగదారు ఇంకా ఏమీ చూడలేదు.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'ఈ వినియోగదారు తన కామెంట్లను గోప్యంగా ఉంచడాన్ని ఇష్టపడతారు.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'డేటా: JustWatch',
  'Web Sitesi': 'వెబ్‌సైట్',
  'Diğer uygulamalar': 'ఇతర యాప్‌లు',
  'Bağlantıyı kopyala': 'లింక్ కాపీ చేయి',
  'Henüz kimseyi takip etmiyorsun.': 'నువ్వు ఇంకా ఎవరినీ ఫాలో అవ్వలేదు.',
  'Çevir': 'అనువదించు',
  'Çeviri şu an yapılamadı': 'ప్రస్తుతం అనువాదం సాధ్యం కాదు',
  'Bağlantı açılamadı': 'లింక్ తెరవలేకపోయాం',
  'Orijinali göster': 'అసలుది చూపు',
  'Çeviriyi göster': 'అనువాదం చూపించు',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'ఈ నెలలో ప్రసార తేదీ ప్రకటించిన ఎపిసోడ్ లేదు. తేదీలు సాధారణంగా కొన్ని వారాల ముందు ప్రకటిస్తారు, అప్పుడు ఇక్కడ కనిపిస్తాయి.',
  'devamı': 'మరిన్ని',
  'Google ile devam et': 'Googleతో కొనసాగించండి',
  'Google girişi başarısız': 'Google సైన్ ఇన్ విఫలమైంది',
  'Veri tasarrufu': 'డేటా ఆదా',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi లో డేటా ఆదా',
  'Mobil veride veri tasarrufu': 'మొబైల్ డేటాలో డేటా ఆదా',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'ఆన్‌లో ఉన్నప్పుడు ఫోటోలు ముందుగా డౌన్‌లోడ్ కావు, నువ్వు చూస్తున్న చిత్రం మాత్రమే లోడ్ అవుతుంది.',
  'Çocuk güvenliği': 'పిల్లల భద్రత',
  'Türk Filmleri': 'టర్కిష్ సినిమాలు',
  'En Yüksek Puanlı Filmler': 'అత్యధిక రేటింగ్ ఉన్న సినిమాలు',
  'En Yüksek Puanlı Diziler': 'అత్యధిక రేటింగ్ ఉన్న సిరీస్',
  'En Çok İzlenen Filmler': 'అత్యధికంగా చూసిన సినిమాలు',
  'Popüler Diziler': 'జనాదరణ పొందిన సిరీస్',
  'En Çok Kazanan Filmler': 'అత్యధిక వసూళ్ల సినిమాలు',
  'Kült Filmler': 'కల్ట్ సినిమాలు',
  'Yeni Filmler': 'కొత్త సినిమాలు',
  'Yorum yap': 'వ్యాఖ్యానించు',
  'Henüz yorum yok': 'ఇంకా వ్యాఖ్యలు లేవు',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'సిరీస్ మరియు సినిమాలపై నీ వ్యాఖ్యలు ఇక్కడ చేరతాయి.',
  'GIF ekle': 'GIF జోడించండి',
  'İlk yorumu sen yaz': 'మొదటి వ్యాఖ్య మీరు రాయండి',
  'Video altyazıları': 'వీడియో ఉపశీర్షికలు',
  'Videolarda altyazı göster': 'వీడియోలలో ఉపశీర్షికలను చూపండి',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'వీడియోలో మాట్లాడిన వాక్యం స్క్రీన్‌పై వ్రాయబడింది. టెక్స్ట్ అనువాదం: టర్కిష్ ప్రసంగంలో ఇంగ్లీష్, ఇతర భాషలలో టర్కిష్.',
  "Güncelleme gerekli": "అప్‌డేట్ అవసరం",
  "Yeni sürüm var": "కొత్త వెర్షన్ అందుబాటులో ఉంది",
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      "కొనసాగించడానికి dizi.jpg కొత్త వెర్షన్‌ను ఇన్‌స్టాల్ చేయండి.",
  "Güncelle": "అప్‌డేట్ చేయండి",
  "Daha sonra": "తర్వాత",
  'Takvim güncelleniyor': 'క్యాలెండర్ నవీకరించబడుతోంది',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'క్యాలెండర్ నవీకరించలేకపోయాము, పాత జాబితా చూపబడుతోంది',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'కొన్ని సిరీస్ లోడ్ కాలేదు, జాబితా అసంపూర్ణంగా ఉండవచ్చు',
  'Yenile': 'రిఫ్రెష్',
  'Devam etmek için giriş yap': 'కొనసాగించడానికి లాగిన్ చేయండి',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'రేటింగ్ ఇవ్వడానికి, వ్యాఖ్య రాయడానికి మరియు మీ లైబ్రరీని నిర్మించడానికి ఉచిత ఖాతా చాలు.',
  'Şimdi değil': 'ఇప్పుడు కాదు',
  'Yorum yazmak için giriş yap': 'వ్యాఖ్య రాయడానికి లాగిన్ చేయండి',
  'Kişilere göndermek için giriş yap': 'వ్యక్తులకు పంపడానికి లాగిన్ చేయండి',
  'Beğenenler': 'ఇష్టపడినవారు',
  'Henüz beğeni yok': 'ఇంకా లైక్‌లు లేవు',
  'Bu gönderiyi ilk beğenen sen ol': 'ఈ పోస్ట్‌ను మొదట ఇష్టపడండి',
  'Bu gönderiye yanıt': 'ఈ పోస్ట్‌కు ప్రత్యుత్తరం',
  'Spoiler içeren gönderi': 'స్పాయిలర్ ఉన్న పోస్ట్',
  'Görsel gönderi': 'ఫోటో పోస్ట్',
  'Bu yorumu profilimde gizle': 'ఈ కామెంట్‌ని నా ప్రొఫైల్ నుండి దాచు',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'కామెంట్ షో మరియు సినిమా పేజీలో అలాగే ఉంటుంది',
  'Bu yorumu sil': 'ఈ కామెంట్‌ని తొలగించు',
  'Yorum profilinde gizlendi': 'కామెంట్ నీ ప్రొఫైల్ నుండి దాచబడింది',
  'Geri al': 'వెనక్కి తీసుకో',
  'Yorum silinsin mi?': 'కామెంట్‌ని తొలగించాలా?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'ఈ కామెంట్ ప్రతిచోటా శాశ్వతంగా తొలగించబడుతుంది. దీన్ని వెనక్కి తీసుకోలేరు.',
  'Yorum silindi': 'కామెంట్ తొలగించబడింది',
  'Yorum profilinde tekrar görünüyor':
      'కామెంట్ నీ ప్రొఫైల్‌లో మళ్ళీ కనిపిస్తోంది',
  'Gizlenen yorumun yok': 'నీకు దాచిన కామెంట్లు లేవు',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'నీ ప్రొఫైల్‌లోని కామెంట్స్ ట్యాబ్‌లో ఒక పోస్ట్‌ని నొక్కి పట్టుకుని నువ్వు దాచే కామెంట్లు ఇక్కడ చేరతాయి.',
  'Gizlenen yorumlar': 'దాచిన కామెంట్లు',
  'Gönderiye git': 'పోస్ట్‌కి వెళ్ళు',
  'Tekrar göster': 'మళ్ళీ చూపించు',
  'Yanıtlarımı gizle': 'నా రిప్లైలను దాచు',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'ఇతరుల పోస్ట్‌లకు నువ్వు రాసే రిప్లైలు నీకు మాత్రమే కనిపిస్తాయి',
  'Profilinde gizlediğin yorumları tekrar göster':
      'నీ ప్రొఫైల్‌లో దాచిన కామెంట్లను మళ్ళీ చూపించు',
  'Sıralama': 'క్రమం',
  'Önerilen': 'సిఫార్సు చేయబడినది',
  'Kronolojik': 'కాలక్రమానుసారం',
  'Gelen mesaj istekleri': 'వచ్చిన సందేశ అభ్యర్థనలు',
  'Mesaj isteğin yok': 'సందేశ అభ్యర్థనలు లేవు',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'మీరు అనుసరించని వ్యక్తుల సందేశాలు ఇక్కడ కనిపిస్తాయి.',
  'Çevrimiçi durumumu gizle': 'నా ఆన్‌లైన్ స్థితిని దాచు',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'ఇతరులు సందేశాలలో మీ ఆన్‌లైన్ స్థితిని మరియు చివరిగా చూసిన సమయాన్ని చూడలేరు',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'మా మొదటి వినియోగదారులలో ఒకరు. వారి అభిప్రాయాలు యాప్ ఈరోజు ఉన్నట్టుగా మారడానికి సహాయపడ్డాయి.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'నువ్వు మా మొదటి వినియోగదారులలో ఒకరు. నీ అభిప్రాయాలు యాప్ ఈరోజు ఉన్నట్టుగా మారడానికి సహాయపడ్డాయి.',
  'İleri': 'తదుపరి',
  'Seçilen dosya okunamadı': 'ఎంచుకున్న ఫైల్‌ను చదవలేకపోయాం',
  'Video açılamadı': 'వీడియోను తెరవలేకపోయాం',
  'En fazla {} medya seçebilirsin': 'మీరు గరిష్ఠంగా {} మీడియా ఎంచుకోవచ్చు',
  'Hiçbir medya yüklenemedi': 'ఏ మీడియా అప్‌లోడ్ కాలేదు',
  'Seçimi kaldır': 'ఎంపిక తీసివేయండి',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'ఒక వ్యాఖ్యలో మొత్తం {} MB మీడియా అప్‌లోడ్ చేయవచ్చు',
  '{} dosya okunamadı': '{} ఫైళ్లు చదవలేకపోయాం',
  '{} medya eklendi, {} yüklenemedi': '{} మీడియా జోడించబడింది, {} విఫలమైంది',
  'Kırp': 'కత్తిరించు',
  'Çiz': 'గీయండి',
  'Metin': 'వచనం',
  'Emoji': 'ఎమోజీ',
  'Yinele': 'మళ్ళీ చేయి',
  'Daha fazla': 'మరిన్ని',
  'Hazırlanıyor…': 'సిద్ధమవుతోంది…',
  'Düzenlemeden çık?': 'సవరణ నుండి నిష్క్రమించాలా?',
  'Yaptığın değişiklikler kaybolacak.': 'మీరు చేసిన మార్పులు పోతాయి.',
  'Çık': 'నిష్క్రమించు',
  'Serbest çizim': 'స్వేచ్ఛా గీత',
  'Ok': 'బాణం',
  'Dikdörtgen': 'దీర్ఘచతురస్రం',
  'Daire': 'వృత్తం',
  'Bulanıklaştır': 'మసకబరచు',
  'Pikselleştir': 'పిక్సలేట్',
  'Silgi': 'చెరిపివేత',
  'Çizgi kalınlığı': 'గీత మందం',
  'Saydamlık': 'అపారదర్శకత',
  'Dolgu': 'నింపు',
  'Renk': 'రంగు',
  'Döndür': 'తిప్పు',
  'Yansıt': 'తిరగవేయి',
  'Oran': 'నిష్పత్తి',
  'Sıfırla': 'రీసెట్',
  'Serbest': 'స్వేచ్ఛ',
  'Metin yaz...': 'వచనం రాయండి...',
  'Hizala': 'సర్దుబాటు',
  'Arka plan': 'నేపథ్యం',
  'Emoji ara...': 'ఎమోజీ వెతకండి...',
  'Son kullanılanlar': 'ఇటీవలివి',
  'İfadeler ve insanlar': 'స్మైలీలు మరియు వ్యక్తులు',
  'Hayvanlar ve doğa': 'జంతువులు మరియు ప్రకృతి',
  'Yiyecek ve içecek': 'ఆహారం మరియు పానీయాలు',
  'Etkinlikler': 'కార్యకలాపాలు',
  'Seyahat ve yerler': 'ప్రయాణం మరియు ప్రదేశాలు',
  'Nesneler': 'వస్తువులు',
  'Semboller': 'చిహ్నాలు',
  'Bayraklar': 'జెండాలు',
  'Görseli düzenle': 'చిత్రాన్ని సవరించు',
  'Düzenlendi': 'సవరించబడింది',
  'Düzenlenemedi': 'సవరించలేకపోయాం',
  'Düzenlenen görsel çok büyük': 'సవరించిన చిత్రం చాలా పెద్దది',
  'Videoyu düzenle': 'వీడియోను సవరించండి',
  'Sesi kapat': 'మ్యూట్ చేయి',
  'Sesi aç': 'మ్యూట్ తీసివేయి',
  'İptal ediliyor…': 'రద్దు చేస్తోంది…',
  'Bu biraz sürebilir': 'దీనికి కొంత సమయం పట్టవచ్చు',
  'Video çok büyük': 'వీడియో చాలా పెద్దది',
  'Video hazırlanamadı': 'వీడియోను సిద్ధం చేయలేకపోయాము',
  'Başlangıç': 'ప్రారంభం',
  'Bitiş': 'ముగింపు',
  'En çok {} saniye seçebilirsin': 'మీరు గరిష్టంగా {} సెకన్లు ఎంచుకోవచ్చు',
  'Dosya en fazla {} MB olabilir': 'ఫైల్ గరిష్టంగా {} MB ఉండవచ్చు',
  'Medya ekle': 'మీడియా జోడించండి',
  'Seçili medya kalmadı': 'మీడియా ఏదీ ఎంచుకోలేదు',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'మీ వ్యాఖ్యకు జోడించడానికి ఫోటో లేదా వీడియోను ఎంచుకోండి.',
  'Medya seç': 'మీడియా ఎంచుకోండి',
  'Daha fazla ekle': 'మరిన్ని జోడించండి',
  'Medya seçilemedi': 'మీడియాను ఎంచుకోలేకపోయాము',
  'Favori oyuncular': 'ఇష్టమైన నటులు',
  'Henüz favori oyuncun yok': 'ఇంకా ఇష్టమైన నటులు లేరు',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'ఒక నటుడి పేజీ తెరిచి కుడి పైన ఉన్న గుండె గుర్తుపై నొక్కండి.',
  '{} yapımdan {} tanesini izledin': '{} లో {} చూశారు',
  'izledin': 'చూశారు',
  'İzlemedin': 'చూడలేదు',
  'Yapım bulunamadı': 'ఏమీ కనబడలేదు',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'ఈ వ్యక్తికి చూపించడానికి సిరీస్ లేదా సినిమాలు లేవు.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'మీ చరిత్ర మీ ఖాతాతో ముడిపడి ఉంది; ఈ జాబితా మీది మాత్రమే.',
  'Hesabın kalıcı olarak askıya alındı': 'మీ ఖాతా శాశ్వతంగా నిలిపివేయబడింది',
  'Hesabın geçici olarak askıya alındı': 'మీ ఖాతా తాత్కాలికంగా నిలిపివేయబడింది',
  'Hesabın askıya alındı': 'మీ ఖాతా నిలిపివేయబడింది',
  'Sebep': 'కారణం',
  'Kalan süre': 'మిగిలిన సమయం',
  'Süre dolunca hesabın kendiliğinden açılır':
      'గడువు ముగిసిన వెంటనే మీ ఖాతా దానంతట అదే తెరుచుకుంటుంది',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'ఈ సమయంలో మీరు చదవగలరు, కానీ పోస్ట్, వ్యాఖ్య లేదా సందేశం పంపలేరు.',
  'Anladım': 'అర్థమైంది',
  'Ayrıntı': 'వివరాలు',
  '{} dakika': '{} నిమిషాలు',
  'birkaç saniye': 'కొన్ని సెకన్లు',
  'Karara itiraz et': 'ఈ నిర్ణయంపై అప్పీలు చేయండి',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'ఈ శిక్ష ఎందుకు తొలగించాలో వివరించండి',
  'İtirazını gönder': 'మీ అప్పీలు పంపండి',
  'İtirazın incelemede': 'మీ అప్పీలు పరిశీలనలో ఉంది',
  'İtirazın reddedildi': 'మీ అప్పీలు తిరస్కరించబడింది',
  'İtirazın alındı, inceleniyor': 'మీ అప్పీలు అందింది, పరిశీలనలో ఉంది',
  'İtiraz en az 10 karakter olmalı': 'అప్పీలు కనీసం 10 అక్షరాలు ఉండాలి',
  'Yükleniyor...': 'లోడ్ అవుతోంది...',
  'Bu bölüme puan ver': 'ఈ ఎపిసోడ్‌ను రేట్ చేయండి',
  '{} kişi puanladı': '{} మంది రేట్ చేశారు',
  'Bölüm izlendi olarak işaretlendi': 'ఎపిసోడ్ చూసినట్లు గుర్తించబడింది',
};
