/// Otomatik üretilen çeviri haritası (bg).
const Map<String, String> cevirilerBg = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Вие сте видели всичко, ние ви показваме от самото начало',
  'Aktarılacak tanınan veri bulunamadı.':
      'Не бяха намерени разпознати данни за импортиране.',
  'Arama': 'Търсене',
  'Aramaya başla': 'Започни да търсиш',
  'Son aramalar': 'Скорошни търсения',
  'Ayarlar': 'Настройки',
  'Bağla': 'Свържи',
  'Bio': 'Био',
  'Bitirdim': 'Завършено',
  'Bunları da Beğenebilirsin': 'Може да ти харесат и тези',
  'Bölüm': 'Епизод',
  'Bıraktım': 'Зарязано',
  'Dil': 'Език',
  'Dil ara...': 'Търси език...',
  'Dizi': 'Сериал',
  'Dizi ve filmlerini takip et': 'Следи сериалите и филмите си',
  'Dizi yorumu': 'Коментар за сериал',
  'Dizi, film veya kişi ara...': 'Търси сериал, филм или човек...',
  'Dosya en fazla 30MB olabilir': 'Файлът може да е най-много 30 МБ',
  'Dosya en fazla {}MB olabilir': 'Файлът може да е най-много {} МБ',
  'E-posta': 'Имейл',
  'E-posta veya kullanıcı adı': 'Имейл или потребителско име',
  'En az 2 harf yaz': 'Въведи поне 2 букви',
  'Film': 'Филм',
  'Film yorumu': 'Коментар за филм',
  'Fotoğraf / video ekle': 'Добави снимка / видео',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Снимка или GIF — аватар и корица',
  'Giriş Yap': 'Вход',
  'Gönder': 'Изпрати',
  'Gönderildi': 'Изпратено',
  'Haftanın Dizileri': 'Сериалите на седмицата',
  'Haftanın Filmleri': 'Филмите на седмицата',
  'Henüz izleme kaydın yok': 'Още нямаш история на гледане',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Още нямаш списъци — създай от раздел „Профил“.',
  'Henüz yorum yok.': 'Още няма коментари.',
  'Hesabın bağlandı!': 'Акаунтът ти е свързан!',
  'Hesabın yok mu? Kayıt ol': 'Нямаш акаунт? Регистрирай се',
  'Hesabını Bağla': 'Свържи акаунта си',
  'Hesap Oluştur': 'Създай акаунт',
  'Kapak resmi ekle': 'Добави корица',
  'Kaydet': 'Запази',
  'Kendinden bahset...': 'Разкажи за себе си...',
  'Keşfet': 'Открий',
  'Kimseyi takip etmiyor': 'Не следва никого',
  'Kişi ara': 'Търси хора',
  'Kişi yorumu': 'Коментар за човек',
  'Konuk Oyuncular': 'Гост-актьори',
  'Kullanıcı adı (küçük harf)': 'Потребителско име (малки букви)',
  'Kullanıcı adı ara...': 'Търси потребителско име...',
  'Liste adı': 'Име на списъка',
  'Listeye Ekle': 'Добави в списък',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'В гост акаунт си — свържи го с имейла си, не губи данните си!',
  'Misafir olarak devam et': 'Продължи като гост',
  'Oluştur': 'Създай',
  'Oyuncular': 'Актьори',
  'Profil': 'Профил',
  'Profil kaydedildi': 'Профилът е запазен',
  'Puanla': 'Оцени',
  'Puanı Sil': 'Изтрий оценката',
  'Puanın': 'Твоята оценка',
  'Sezonlar': 'Сезони',
  'Sunucu hatası ({})': 'Сървърна грешка ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Коментар за S{}E{}',
  'Takibi Bırak': 'Спри да следваш',
  'Takip': 'Следвани',
  'Takip Edilenler': 'Следвани',
  'Takip Et': 'Последвай',
  'Takipçi': 'Последователи',
  'Takipçi yok': 'Няма последователи',
  'Takipçiler': 'Последователи',
  'Takvim': 'Календар',
  'Tamam': 'ОК',
  'Tekrar Dene': 'Опитай пак',
  'Tekrar dene': 'Опитай отново',
  'Toplam İzleme Süresi': 'Общо екранно време',
  'Tüm Zamanların En İyileri': 'Най-добрите за всички времена',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'Изтегли всичките си данни (гледания, оценки, коментари, списъци) като ZIP, съвместим с TV Time, или импортирай ZIP от друго приложение.',
  'Tümünü Kaldır': 'Премахни всички',
  'Tümünü İzledim': 'Всичко е изгледано',
  'Türk Dizileri': 'Турски сериали',
  'Veri içe aktar (.zip)': 'Импорт на данни (.zip)',
  'Verilerim': 'Моите данни',
  'Verilerimi dışa aktar (e-posta)': 'Експорт на моите данни (имейл)',
  'Verilerini dışa aktar': 'Експортирай данните си',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Няма предстоящи епизоди.\nСложи на сериала статус „Гледам“ от страницата му и следи новите епизоди тук.',
  'Yapımları': 'Филмография',
  'Yeni Diziler': 'Нови сериали',
  'Yeni Liste': 'Нов списък',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Ново потребителско име (по избор)',
  'Yorum': 'Коментар',
  'Yorumunu yaz...': 'Напиши коментар...',
  'Zaten hesabın var mı? Giriş yap': 'Вече имаш акаунт? Влез',
  'ort. {}': 'ср. {}',
  'takip': 'следвани',
  'takipçi': 'последователи',
  '{} / {} bölüm': '{} / {} епизода',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} мес.',
  '{} ay~tekil': '{} мес.',
  '{} bölüm izlendi': '{} изгледани епизода',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} мин',
  '{} dk~tekil': '{} мин',
  '{} gün': '{} дни',
  '{} gün~tekil': '{} ден',
  '{} içerik': '{} заглавия',
  '{} içerik · otomatik': '{} заглавия · автоматично',
  '{} kayıt atlandı (eşleşmedi).': '{} записа са пропуснати (няма съвпадение).',
  '{} saat': '{} часа',
  '{} saat~tekil': '{} час',
  '{} sezon': '{} сезона',
  '{} yıl': '{} години',
  '{} yıl~tekil': '{} година',
  '{}. Bölüm': 'Епизод {}',
  '{}. Sezon': 'Сезон {}',
  'Çıkış Yap': 'Изход',
  'Ülke': 'Държава',
  'Ülke ara...': 'Търси държава...',
  'Ülke seç': 'Избери държава',
  'İlk yorumu sen yaz!': 'Напиши първия коментар!',
  'İncelemeler': 'Ревюта',
  'İncelemen (isteğe bağlı)': 'Твоето ревю (по избор)',
  'İptal': 'Отказ',
  'İzlediklerim': 'История на гледане',
  'İzledim': 'Изгледано',
  'İzledin': 'Изгледано',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Историята на гледане и списъците ти се запазват; вече можеш да влизаш от всяко устройство.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Историята на гледане, оценките, коментарите и списъците ти ще бъдат изпратени като ZIP на регистрирания ти имейл.',
  'İzleyeceğim': 'Ще гледам',
  'İzliyorum': 'Гледам',
  'İçe aktarım tamamlandı': 'Импортът е завършен',
  'Şifre': 'Парола',
  '• profil bilgisi': '• информация за профила',
  '• {} dizi durumu': '• {} статуса на сериали',
  '• {} izleme kaydı': '• {} записа на гледане',
  '• {} liste': '• {} списъка',
  '• {} puan': '• {} оценки',
  '• {} yorum': '• {} коментара',
  '{}+ yapım': '{}+ продукции',
  'Yorumlar': 'Коментари',
  'Yorumlar ({})': 'Коментари ({})',
  'Yorumları ({})': 'Коментари ({})',
  'Listelerim': 'Моите списъци',
  'Nereden izledin?': 'Къде го гледа?',
  'Diziye git': 'Към сериала',
  'TV / Kanal': 'ТВ / канал',
  'Sinema': 'Кино',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Друго',
  'Akış': 'Емисия',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Емисията ти е празна.\nКогато коментират сериалите и филмите, които гледаш, ще се появи тук.',
  'Listeleri ({})': 'Списъци ({})',
  'Liste boş.': 'Този списък е празен.',
  'Yanıtla': 'Отговори',
  '@{} kullanıcısına yanıt veriyorsun': 'Отговаряш на @{}',
  'İzlediğim Diziler ({})': 'Изгледани сериали ({})',
  'İzlediğim Filmler ({})': 'Изгледани филми ({})',
  'Tümünü gör': 'Виж всички',
  'Bildirimler': 'Известия',
  'Henüz bildirim yok': 'Още няма известия',
  '@{} yorumuna yanıt verdi': '@{} отговори на коментара ти',
  '@{} yorumunu beğendi': '@{} хареса коментара ти',
  '@{} seni takip etti': '@{} те последва',
  '@{} sana mesaj gönderdi': '@{} ти изпрати съобщение',
  'Mesajlar': 'Съобщения',
  'Mesaj': 'Съобщение',
  'Mesaja eklenecek': 'Ще бъде добавено към съобщението',
  'Mesajını yaz...': 'Напиши съобщение...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Още няма чатове.\nОтвори профил и изпрати съобщение.',
  'Şifreni mi unuttun?': 'Забравена парола?',
  'Şifreyi Sıfırla': 'Нулиране на паролата',
  'E-postadaki kod': 'Кодът от имейла',
  'Yeni şifre': 'Нова парола',
  'Sana Özel': 'За теб',
  '{} özetin': 'Твоето обобщение за {}',
  'Yıllık izleme istatistiklerin': 'Годишна статистика',
  'Rozetler': 'Значки',
  'Verdiğin puan': 'Дадени оценки',
  'Ortalama puanın': 'Средната ти оценка',
  'En çok izlediğin diziler': 'Най-гледаните ти сериали',
  'İlk Bölüm': 'Първи епизод',
  '100 Bölüm': '100 епизода',
  '1000 Bölüm': '1000 епизода',
  'İlk Film': 'Първи филм',
  '50 Film': '50 филма',
  'İlk Yorum': 'Първи коментар',
  '25 Yorum': '25 коментара',
  '10 Puan': '10 оценки',
  'İlk Takipçi': 'Първи последовател',
  '10 Dizi Bitirdin': 'Завърши 10 сериала',
  'İzlemeyi Bıraktım': 'Спрях да гледам',
  'İzlediği Diziler ({})': 'Изгледани сериали ({})',
  'İzlediği Filmler ({})': 'Изгледани филми ({})',
  '500 Bölüm': '500 епизода',
  '5000 Bölüm': '5000 епизода',
  '10 Film': '10 филма',
  '100 Film': '100 филма',
  '100 Yorum': '100 коментара',
  '50 Puan': '50 оценки',
  '100 Puan': '100 оценки',
  '10 Takipçi': '10 последователи',
  '50 Takipçi': '50 последователи',
  '25 Dizi Bitirdin': 'Завърши 25 сериала',
  '50 Dizi Bitirdin': 'Завърши 50 сериала',
  '10 Beğeni': '10 харесвания',
  '100 Beğeni': '100 харесвания',
  'yazıyor...': 'пише...',
  'ses kaydediyor...': 'записва аудио...',
  'Profil düzeni': 'Подредба на профила',
  'Konumla ve kırp': 'Позиционирай и изрежи',
  'Listeye eklendi': 'Добавено в списъка',
  'Listeyi sil?': 'Изтриване на списъка?',
  'Sil': 'Изтрий',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Ще бъде отбелязано като негледано и премахнато от списъците ти.',
  'Gelecek bölüm bugün': 'Следващият епизод днес',
  'Gelecek bölüm {} gün sonra': 'Следващият епизод след {} дни',
  'Tema': 'Тема',
  'Sistem': 'Системна',
  'Koyu': 'Тъмна',
  'Açık': 'Светла',
  'İzleyenler': 'Зрители',
  'Yorumunu yaz... (@ ile etiketle)':
      'Напиши коментара си... (@ за отбелязване)',
  '@{} bir yorumda seni etiketledi': '@{} те отбеляза в коментар',
  'Mesajı sil': 'Изтрий съобщението',
  'Mesaj silinemedi': 'Съобщението не можа да бъде изтрито',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Връзката е невалидна или страницата не е намерена',
  "Keşfet'e dön": 'Обратно към Открий',
  'Düzenle': 'Редакция',
  'Mesajı düzenle': 'Редактирай съобщението',
  'Yanıtlanıyor': 'Отговаряне',
  'düzenlendi': 'редактирано',
  'Fotoğraf': 'Снимка',
  'Video': 'Видео',
  'İçerik': 'Съдържание',
  'çevrimiçi': 'на линия',
  'son görülme {} dk önce': 'онлайн преди {} мин',
  'son görülme {} saat önce': 'онлайн преди {} ч',
  'son görülme {} gün önce': 'онлайн преди {} д',
  'Yorumlar yüklenemedi': 'Коментарите не можаха да се заредят',
  'Favori': 'Любимо',
  'Listeye ekle': 'Добави в списък',
  'İçerik paylaş': 'Сподели',
  'Kapat': 'Затвори',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Всичко, което отбележиш като гледано, се събира тук.',
  'Henüz sohbetin yok': 'Все още няма разговори',
  'Bir profile girip mesaj gönderebilirsin.':
      'Отвори профил и изпрати съобщение.',
  'Listeyi sil': 'Изтрий списъка',
  'Puan kaydedilemedi': 'Оценката не можа да се запази',
  'Nerede İzlenir': 'Къде да гледате',
  'Abonelik': 'Абонамент',
  'Kirala': 'Наем',
  'Satın al': 'Купуване',
  'Devam et': 'Продължи',
  'Şikayet et': 'Докладвай',
  'Engelle': 'Блокирай',
  'Engeli kaldır': 'Разблокирай',
  'Kullanıcı engellendi': 'Потребителят е блокиран',
  'Engel kaldırıldı': 'Блокирането е премахнато',
  'Şikayet sebebi': 'Причина за доклада',
  'Spam veya yanıltıcı': 'Спам или подвеждащо',
  'Taciz veya nefret söylemi': 'Тормоз или изказвания на омраза',
  'Uygunsuz / cinsel içerik': 'Неподходящо / сексуално съдържание',
  'Şiddet veya tehlikeli içerik': 'Насилие или опасно съдържание',
  'Telif hakkı ihlali': 'Нарушение на авторски права',
  'Şikayetin alındı, teşekkürler': 'Докладът ти е получен, благодарим',
  'Hesabımı Sil': 'Изтрий акаунта ми',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Акаунтът ти и всички данни (история, оценки, коментари, списъци, съобщения) ще бъдат изтрити завинаги. Това не може да бъде отменено.',
  'Şifreni gir': 'Въведи паролата си',
  'Hesabımı kalıcı sil': 'Изтрий акаунта ми завинаги',
  'Sesli mesaj': 'Гласово съобщение',
  'Ses gönderilemedi': 'Гласовото съобщение не можа да бъде изпратено',
  'Kaydediliyor…': 'Записване…',
  'Ses oynatılamadı': 'Аудиото не можа да се възпроизведе',
  'Oynat': 'Възпроизвеждане',
  'Fragmanı oynat': 'Пусни трейлъра',
  'Altyazıyı aç': 'Включи субтитрите',
  'Altyazıyı kapat': 'Изключи субтитрите',
  '10 saniye ileri': 'Напред 10 секунди',
  '10 saniye geri': 'Назад 10 секунди',
  'Duraklat': 'Пауза',
  'Liste görünümü': 'Изглед списък',
  'Takvim görünümü': 'Изглед календар',
  'Önceki ay': 'Предишен месец',
  'Sonraki ay': 'Следващ месец',
  'Bu gün bölüm yok': 'Няма епизоди този ден',
  'Gizlilik Politikası': 'Политика за поверителност',
  'Son güncelleme: {}': 'Последна актуализация: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Тази политика обяснява какви данни се събират, как се използват и какви права имаш, когато използваш приложението dizi.jpg и сайта dizijpg.com.',
  'Topladığımız Veriler': 'Какви данни събираме',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Акаунт: имейл адрес, потребителско име и парола. Паролите се съхраняват като необратим хеш; гост акаунтите могат да се използват без имейл.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Профил: данните, които сам избираш да добавиш — аватар, корица, био и държава.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Използване: твоята история на гледане, оценки, коментари, списъци, реакции и любими.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Съобщения: твоите текстови, снимкови и гласови съобщения се съхраняват на нашите сървъри. Съобщенията не са криптирани от край до край; преглеждат се само при подаден сигнал, с цел модерация.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Качени файлове: снимки, GIF, видеа и гласови записи, които добавяш към профила, коментарите и съобщенията си.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Технически данни: IP адрес, приблизително местоположение (държава/град), платформа на устройството, версия на приложението и записи за грешки. Пазят се за сигурност и отстраняване на проблеми.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Статистика за ползването: с какъв тип устройство, операционна система и браузър е осъществен достъпът се добавя в груби категории към дневни общи броячи; самият идентификатор на браузъра не се запазва и тези числа не могат да бъдат свързани с конкретни лица.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Известия: за push известията пазим токена на устройството ти и избрания език. Можеш да изключиш известията по всяко време от настройките на устройството.',
  'Verileri Nasıl Kullanırız': 'Как използваме данните ти',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Използваме данните ти единствено за да предоставяме услугата, да пазим акаунта ти, да изпращаме известия, да поправяме грешки и да предотвратяваме злоупотреби. Не продаваме данните ти и не ги споделяме с никого с рекламна цел.',
  'Çerezler ve Yerel Depolama': 'Бисквитки и локално хранилище',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Използваме локално хранилище само за да останеш вписан и да помним предпочитания като език и тема. Няма рекламни или проследяващи бисквитки.',
  'Üçüncü Taraf Hizmetler': 'Услуги на трети страни',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Данните за сериали и филми идват от TMDB, информацията за стрийминг платформите — от JustWatch. Push известията се доставят чрез Google Firebase, а трафикът на сайта се защитава от Cloudflare. За тези услуги важат собствените им политики за поверителност.',
  'Saklama ve Silme': 'Съхранение и изтриване',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Данните ти се пазят, докато акаунтът ти съществува. Чрез „Изтрий акаунта ми" в настройките можеш да изтриеш акаунта завинаги; данните се изтриват веднага, а копията им в резервните копия — най-късно до 14 дни. Записите за грешки се изтриват автоматично след 30 дни.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'Можеш да експортираш данните си като ZIP от настройките; архивът се изпраща на имейл адреса ти.',
  'Güvenlik': 'Сигурност',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Данните се пренасят по криптирани връзки (HTTPS) и се съхраняват на сървъри с ограничен достъп.',
  'Çocukların Gizliliği': 'Поверителност на децата',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg не е предназначен за деца под 13 години.',
  'Hakların': 'Твоите права',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Съгласно KVKK и GDPR имаш право на достъп до данните си, коригиране, изтриване и прехвърляне. За тези въпроси ни пиши: {}',
  'Değişiklikler': 'Промени',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Ако тази политика се промени, новата версия ще бъде публикувана на тази страница и датата ще бъде обновена.',
  'Kayıt olarak {} kabul etmiş olursun.': 'С регистрацията си приемаш {}.',
  'Kullanıcılar': 'Потребители',
  'Fotoğrafı değiştir': 'Смени снимката',
  'Yeniden konumlandır': 'Прекадрирай',
  'Bir şeyler ters gitti': 'Нещо се обърка',
  'Sosyal Bağlantılar': 'Социални връзки',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'В профила се показват до 3 връзки.',
  'Platform seç': 'Избери платформа',
  'Kullanıcı adın': 'Твоето потребителско име',
  'Ekle': 'Добави',
  'Kaldır': 'Премахни',
  'Kopyalandı: {}': 'Копирано: {}',
  'Geçersiz kullanıcı adı': 'Невалидно потребителско име',
  'Bağlantı ekle': 'Добави връзка',
  'Spoiler olabilir — dokun ve gör':
      'Може да съдържа спойлери — докосни, за да видиш',
  'Beğeni': 'Харесвания',
  'beğeni': 'харесвания',
  'Beğen': 'Харесай',
  'Görüntülenme': 'Показвания',
  'görüntülenme': 'показвания',
  'Tam ekran': 'Цял екран',
  'Arama başarısız': 'Търсенето е неуспешно',
  'Sonuç bulunamadı': 'Няма резултати',
  'Dizi ve Filmler': 'Сериали и филми',
  'Kişiler': 'Хора',
  'Ana Sayfa': 'Начало',
  'Paylaş': 'Сподели',
  'Yanıtlar': 'Отговори',
  'Yaklaşan Bölümler': 'Предстоящи епизоди',
  'Yetişme Listesi': 'Списък за наваксване',
  'Şunu mu demek istedin': 'Може би имахте предвид',
  'Spoiler': 'Спойлер',
  'Spoiler — dokun ve gör': 'Спойлер — докосни, за да видиш',
  'uyum': 'съвпадение',
  'Uyum': 'Съвпадение',
  '{} ortak dizi': '{} общи сериала',
  '{} ortak film': '{} общи филма',
  'Bildirim Tercihleri': 'Настройки за известия',
  'Beğeniler': 'Харесвания',
  'Yeni takipçiler': 'Нови последователи',
  'Etiketlenmeler': 'Споменавания',
  'Yeniden izledim': 'Гледано отново',
  '{}. kez izlendi': 'Гледано {} пъти',
  'Gönderi bulunamadı': 'Публикацията не е намерена',
  'Gözat': 'Разглеждане',
  'Diziler': 'Сериали',
  'Filmler': 'Филми',
  'Tümü': 'Всички',
  'Farklı bir tür seç.': 'Опитай друг жанр.',
  'Gizlilik': 'Поверителност',
  'İzlediklerimi gizle': 'Скрий какво гледам',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Гледаните сериали и филми няма да се виждат в профила ти',
  'Yorumlarımı gizle': 'Скрий коментарите ми',
  'Profilinde yorumların görünmez':
      'Коментарите ти няма да се виждат в профила ти',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Можеш да скриеш отделен сериал или филм с чипа „Скрий в профила ми” на неговата страница.',
  'Geri Bildirim': 'Обратна връзка',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Напиши мнението и предложенията си за приложението...',
  'Teşekkürler! Geri bildirimin alındı.': 'Благодарим! Отзивът ти е получен.',
  'Profilimde gizle': 'Скрий в профила ми',
  'Yorumları': 'Коментари',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Този потребител още не е гледал нищо.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Този потребител предпочита да пази коментарите си скрити.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Данни: JustWatch',
  'Web Sitesi': 'Уебсайт',
  'Diğer uygulamalar': 'Други приложения',
  'Bağlantıyı kopyala': 'Копирай връзката',
  'Henüz kimseyi takip etmiyorsun.': 'Още не следваш никого.',
  'Çevir': 'Преведи',
  'Çeviri şu an yapılamadı': 'Преводът не е възможен в момента',
  'Bağlantı açılamadı': 'Връзката не можа да се отвори',
  'Orijinali göster': 'Покажи оригинала',
  'Çeviriyi göster': 'Покажи превода',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Този месец няма епизоди с обявена дата на излъчване. Датите обикновено се съобщават няколко седмици предварително и ще се появят тук.',
  'devamı': 'още',
  'Google ile devam et': 'Продължаване с Google',
  'Google girişi başarısız': 'Входът с Google не бе успешен',
  'Veri tasarrufu': 'Икономия на данни',
  'Wi-Fi ağında veri tasarrufu': 'Икономия на данни при Wi-Fi',
  'Mobil veride veri tasarrufu': 'Икономия на данни при мобилни данни',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Когато е включено, снимките не се изтеглят предварително — зарежда се само кадърът, който гледаш.',
  'Çocuk güvenliği': 'Безопасност на децата',
  'Türk Filmleri': 'Турски филми',
  'En Yüksek Puanlı Filmler': 'Най-високо оценени филми',
  'En Yüksek Puanlı Diziler': 'Най-високо оценени сериали',
  'En Çok İzlenen Filmler': 'Най-гледани филми',
  'Popüler Diziler': 'Популярни сериали',
  'En Çok Kazanan Filmler': 'Най-касови филми',
  'Kült Filmler': 'Култови филми',
  'Yeni Filmler': 'Нови филми',
  'Yorum yap': 'Коментирай',
  'Henüz yorum yok': 'Още няма коментари',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Коментарите ти за сериали и филми се събират тук.',
  'GIF ekle': 'Добавяне на GIF',
  'İlk yorumu sen yaz': 'Бъди първият с коментар',
  'Video altyazıları': 'Видео субтитри',
  'Videolarda altyazı göster': 'Показване на субтитри на видеоклипове',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Изреченото във видеото изречение е изписано на екрана. Текстът е превод: английски на турски език, турски на други езици.',
  'Güncelleme gerekli': 'Изисква се актуализация',
  'Yeni sürüm var': 'Има нова версия',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Инсталирай новата версия на dizi.jpg, за да продължиш.',
  'Güncelle': 'Актуализирай',
  'Daha sonra': 'По-късно',
  'Takvim güncelleniyor': 'Календарът се обновява',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Календарът не можа да се обнови, показва се старият списък',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Някои сериали не се заредиха, списъкът може да е непълен',
  'Yenile': 'Обнови',
  'Devam etmek için giriş yap': 'Влезте, за да продължите',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Безплатен профил е достатъчен, за да оценявате, коментирате и създадете своята библиотека.',
  'Şimdi değil': 'Не сега',
  'Yorum yazmak için giriş yap': 'Влезте, за да напишете коментар',
  'Kişilere göndermek için giriş yap': 'Влезте, за да изпратите на хора',
  'Beğenenler': 'Харесвания',
  'Henüz beğeni yok': 'Все още няма харесвания',
  'Bu gönderiyi ilk beğenen sen ol': 'Дай първото харесване на тази публикация',
  'Bu gönderiye yanıt': 'Отговор на тази публикация',
  'Spoiler içeren gönderi': 'Публикация със спойлери',
  'Görsel gönderi': 'Публикация със снимка',
  'Bu yorumu profilimde gizle': 'Скрий този коментар от профила ми',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Коментарът остава на страницата на сериала или филма',
  'Bu yorumu sil': 'Изтрий този коментар',
  'Yorum profilinde gizlendi': 'Коментарът е скрит от профила ти',
  'Geri al': 'Отмени',
  'Yorum silinsin mi?': 'Да се изтрие ли коментарът?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Този коментар ще бъде изтрит завинаги навсякъде. Не може да бъде възстановен.',
  'Yorum silindi': 'Коментарът е изтрит',
  'Yorum profilinde tekrar görünüyor':
      'Коментарът отново се вижда в профила ти',
  'Gizlenen yorumun yok': 'Нямаш скрити коментари',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Коментарите, които скриваш чрез задържане върху публикация в раздел Коментари на профила ти, се събират тук.',
  'Gizlenen yorumlar': 'Скрити коментари',
  'Gönderiye git': 'Отиди към публикацията',
  'Tekrar göster': 'Покажи отново',
  'Yanıtlarımı gizle': 'Скрий отговорите ми',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Отговорите, които пишеш на чужди публикации, се виждат само от теб',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Покажи отново коментарите, скрити в профила ти',
  'Sıralama': 'Подреждане',
  'Önerilen': 'Препоръчано',
  'Kronolojik': 'Хронологично',
  'Gelen mesaj istekleri': 'Входящи заявки за съобщение',
  'Mesaj isteğin yok': 'Нямаш заявки за съобщение',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Съобщенията от хора, които не следваш, се показват тук.',
  'Çevrimiçi durumumu gizle': 'Скрий моя статус онлайн',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Другите няма да виждат статуса ти онлайн и последното ти влизане в съобщенията',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Сред първите ни потребители. Обратната им връзка помогна на приложението да стане това, което е днес.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Ти си сред първите ни потребители. Твоята обратна връзка помогна на приложението да стане това, което е днес.',
  'İleri': 'Напред',
  'Önceki': 'Предишен',
  'Sonraki': 'Следващ',
  'Seçilen dosya okunamadı': 'Избраният файл не можа да бъде прочетен',
  'Video açılamadı': 'Видеото не можа да се отвори',
  'En fazla {} medya seçebilirsin': 'Можете да изберете най-много {} файла',
  'Hiçbir medya yüklenemedi': 'Нито един файл не беше качен',
  'Seçimi kaldır': 'Премахване от избора',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'В един коментар можете да качите общо {} MB',
  '{} dosya okunamadı': '{} файла не можаха да бъдат прочетени',
  '{} medya eklendi, {} yüklenemedi': 'Добавени: {}, неуспешни: {}',
  'Kırp': 'Изрязване',
  'Çiz': 'Рисуване',
  'Metin': 'Текст',
  'Emoji': 'Емоджи',
  'Yinele': 'Повтори',
  'Daha fazla': 'Още',
  'Hazırlanıyor…': 'Подготвя се…',
  'Düzenlemeden çık?': 'Изход от редактирането?',
  'Yaptığın değişiklikler kaybolacak.': 'Промените ви ще бъдат загубени.',
  'Çık': 'Изход',
  'Serbest çizim': 'Свободно рисуване',
  'Ok': 'Стрелка',
  'Dikdörtgen': 'Правоъгълник',
  'Daire': 'Кръг',
  'Bulanıklaştır': 'Размазване',
  'Pikselleştir': 'Пикселиране',
  'Silgi': 'Гума',
  'Çizgi kalınlığı': 'Дебелина на линията',
  'Saydamlık': 'Прозрачност',
  'Dolgu': 'Запълване',
  'Renk': 'Цвят',
  'Döndür': 'Завъртане',
  'Yansıt': 'Огледално',
  'Oran': 'Съотношение',
  'Sıfırla': 'Нулиране',
  'Serbest': 'Свободно',
  'Metin yaz...': 'Напишете текст...',
  'Hizala': 'Подравняване',
  'Arka plan': 'Фон',
  'Emoji ara...': 'Търсене на емоджи...',
  'Son kullanılanlar': 'Скорошни',
  'İfadeler ve insanlar': 'Усмивки и хора',
  'Hayvanlar ve doğa': 'Животни и природа',
  'Yiyecek ve içecek': 'Храна и напитки',
  'Etkinlikler': 'Дейности',
  'Seyahat ve yerler': 'Пътувания и места',
  'Nesneler': 'Обекти',
  'Semboller': 'Символи',
  'Bayraklar': 'Знамена',
  'Görseli düzenle': 'Редактиране на снимката',
  'Düzenlendi': 'Редактирано',
  'Düzenlenemedi': 'Редактирането не бе успешно',
  'Düzenlenen görsel çok büyük': 'Редактираното изображение е твърде голямо',
  'Videoyu düzenle': 'Редактиране на видео',
  'Sesi kapat': 'Изключване на звука',
  'Sesi aç': 'Включване на звука',
  'İptal ediliyor…': 'Отменя се…',
  'Bu biraz sürebilir': 'Това може да отнеме малко време',
  'Video çok büyük': 'Видеото е твърде голямо',
  'Video hazırlanamadı': 'Видеото не можа да бъде подготвено',
  'Başlangıç': 'Начало',
  'Bitiş': 'Край',
  'En çok {} saniye seçebilirsin': 'Можеш да избереш най-много {} секунди',
  'Dosya en fazla {} MB olabilir': 'Файлът може да е най-много {} MB',
  'Medya ekle': 'Добавяне на медия',
  'Seçili medya kalmadı': 'Няма избрана медия',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Изберете снимка или видео, за да го добавите към коментара си.',
  'Medya seç': 'Избор на медия',
  'Daha fazla ekle': 'Добавяне на още',
  'Medya seçilemedi': 'Медията не можа да бъде избрана',
  'Favori oyuncular': 'Любими актьори',
  'Henüz favori oyuncun yok': 'Все още няма любими актьори',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Отвори страницата на актьор и докосни сърцето горе вдясно.',
  '{} yapımdan {} tanesini izledin': 'Гледали сте {} от {}',
  'izledin': 'гледани',
  'İzlemedin': 'Не е гледано',
  'Yapım bulunamadı': 'Не са намерени заглавия',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Този човек няма сериали или филми за показване.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Историята ти е свързана с профила ти; този списък е само твой.',
  'Hesabın kalıcı olarak askıya alındı': 'Вашият профил е спрян завинаги',
  'Hesabın geçici olarak askıya alındı': 'Вашият профил е спрян временно',
  'Hesabın askıya alındı': 'Вашият профил е спрян',
  'Sebep': 'Причина',
  'Kalan süre': 'Оставащо време',
  'Süre dolunca hesabın kendiliğinden açılır':
      'След изтичане на срока профилът се отключва автоматично',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'През това време можете да четете, но не можете да публикувате, коментирате или изпращате съобщения.',
  'Anladım': 'Разбрах',
  'Ayrıntı': 'Подробности',
  '{} dakika': '{} минути',
  'birkaç saniye': 'няколко секунди',
  'Karara itiraz et': 'Обжалване на решението',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Обяснете защо това наказание трябва да отпадне',
  'İtirazını gönder': 'Изпратете обжалването',
  'İtirazın incelemede': 'Обжалването ви се разглежда',
  'İtirazın reddedildi': 'Обжалването ви беше отхвърлено',
  'İtirazın alındı, inceleniyor': 'Получихме обжалването ви и то се разглежда',
  'İtiraz en az 10 karakter olmalı': 'Обжалването трябва да е поне 10 знака',
  'Yükleniyor...': 'Зареждане...',
  'Bu bölüme puan ver': 'Оценете този епизод',
  '{} kişi puanladı': '{} души оцениха',
  'Bölüm izlendi olarak işaretlendi': 'Епизодът е отбелязан като гледан',
  'Sesli ara': 'Гласово обаждане',
  'Görüntülü ara': 'Видеообаждане',
  'Çalıyor...': 'Звъни...',
  'Bağlanıyor...': 'Свързване...',
  'Cevapla': 'Отговори',
  'Reddet': 'Отхвърли',
  'Sessize al': 'Заглуши',
  'Hoparlör': 'Високоговорител',
  'Kamerayı kapat': 'Изключи камерата',
  'Kamerayı çevir': 'Смени камерата',
  'Cevap yok': 'Няма отговор',
  'Arama reddedildi': 'Обаждането е отхвърлено',
  'Meşgul': 'Заето',
  'Bağlanılamadı': 'Свързването не бе успешно',
  'Arama iptal edildi': 'Обаждането е отменено',
  'Arama geçmişi': 'История на обажданията',
  'Gelen arama': 'Входящо обаждане',
  'Giden arama': 'Изходящо обаждане',
  'Cevapsız arama': 'Пропуснато обаждане',
  'Arama şu anda kullanılamıyor': 'Обажданията в момента не са налични',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Видеообажданията са изключени, можеш да се обадиш гласово',
  'Bu kullanıcıyı arayamazsın': 'Не можеш да се обадиш на този потребител',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Трябва да се следвате взаимно, за да се обаждате',
  'Bu kullanıcı şu anda aranamıyor':
      'На този потребител не може да се звъни в момента',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Твърде много пропуснати обаждания. Опитай отново след {}',
  'Zaten bir aramadasın': 'Вече си в разговор',
  'Arama için mikrofon izni gerekiyor':
      'За обаждане е нужно разрешение за микрофона',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'За видеообаждане са нужни разрешения за камерата и микрофона',
  'Arama başlatılamadı': 'Обаждането не можа да започне',
  'Kullanıcı bulunamadı': 'Потребителят не е намерен',
  'Kendini arayamazsın': 'Не можеш да се обадиш на себе си',
  'Arama artık geçerli değil': 'Това обаждане вече не е валидно',
  'Bu aramanın tarafı değilsin': 'Не си участник в това обаждане',
  'Arama bulunamadı': 'Обаждането не е намерено',
  'Çok fazla istek, biraz bekle': 'Твърде много заявки, изчакай малко',
  'Bağlantı koptu': 'Връзката прекъсна',
  'Arama süre sınırına ulaştı': 'Обаждането достигна времевото ограничение',
  'Arama en fazla 4 saat sürebilir':
      'Едно обаждане може да продължи най-много 4 часа',
  'Arama sona erdi': 'Обаждането приключи',
  'Sesli arama': 'Гласово обаждане',
  'Görüntülü arama': 'Видеообаждане',
  'Gelen aramalar': 'Входящи обаждания',
  'Sesli ve görüntülü arama bildirimleri':
      'Известия за гласови и видеообаждания',
  '{} sa': '{} ч',
  'Sesli ve Görüntülü Aramalar': 'Гласови и видеообаждания',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Съдържанието на разговорите никога не се записва. Звукът и видеото се предават между устройствата с шифроване от край до край (DTLS-SRTP); нашите сървъри не могат да ги дешифрират, подслушват или съхраняват.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Съхраняват се само метаданните на обаждането: с кого, в каква посока, кога и колко е продължило. Тези записи се изтриват автоматично след 90 дни.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Ако не може да се установи пряка връзка, звукът и видеото преминават шифровани през ретранслиращ сървър (TURN). И той не може да дешифрира или запише съдържанието.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Микрофонът се използва само по време на гласово или видеообаждане, а камерата само по време на видеообаждане. И двете се изключват след края на разговора.',
  'Takip ettiğin {} kişi izledi': '{} души, които следваш, го гледаха',
  'Yorum yaz...': 'Напиши коментар...',
  'Sıradaki bölüm': 'Следващ епизод',
  'Doğrulanmış testçi': 'Потвърден тестер',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Известия за следване, харесване, отговор, съобщение и споменаване',
  'Sen': 'Ти',
  'Aradığınız kişide sesli arama devre dışı':
      'Гласовите обаждания са изключени при този човек',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Видеообажданията са изключени при този човек',
  'Sesli aramalara izin ver': 'Разреши гласови обаждания',
  'Görüntülü aramalara izin ver': 'Разреши видеообаждания',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Когато е изключено, никой не може да ти се обади гласово; обаждащият се вижда съобщение',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Когато е изключено, никой не може да ти се обади с видео; обаждащият се вижда съобщение',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Гласовите обаждания са изключени. Можеш да ги включиш от Настройки > Поверителност.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Видеообажданията са изключени. Можеш да ги включиш от Настройки > Поверителност.',
  'Sesli ve görüntülü arama': 'Гласови и видеообаждания',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Гостуващите профили не могат да се обаждат. Създай профил, за да ги ползваш.',
  'Misafir hesaplar aranamaz': 'На гостуващи профили не може да се звъни',
  'Puan dağılımı': 'Разпределение на оценките',
  '{} yıldız': '{} звезди',
  'Yakında gelecek': 'Очаквайте скоро',
  '{} {} yayınlandı': '{} {} излезе',
  'Yeni bölüm yayınlandı': 'Излезе нов епизод',
  'Yeni bölümler': 'Нови епизоди',
  'Geri': 'Назад',
  'Karşılamayı kapat': 'Затвори въведението',
  'Adım {} / {}': 'Стъпка {} / {}',
  'Hadi başlayalım': 'Да започваме',
  'Kaydet ve devam': 'Запази и продължи',
  '{} tanesini ekle': 'Добави {}',
  'Şimdilik geç': 'Пропусни засега',
  'Doğum tarihin ne zaman?': 'Каква е датата ти на раждане?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Питаме, за да показваме съдържание, подходящо за възрастта ти, и да те поздравим за рождения ден.',
  'Gün': 'Ден',
  'Ay': 'Месец',
  'Yıl': 'Година',
  'Doğum yılımı paylaşmak istemiyorum':
      'Не искам да показвам годината си на раждане',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'Датата на раждане не се показва публично в профила ти. Използва се само за съдържание, подходящо за възрастта, и за поздрав за рождения ден.',
  'Ocak': 'Януари',
  'Şubat': 'Февруари',
  'Mart': 'Март',
  'Nisan': 'Април',
  'Mayıs': 'Май',
  'Haziran': 'Юни',
  'Temmuz': 'Юли',
  'Ağustos': 'Август',
  'Eylül': 'Септември',
  'Ekim': 'Октомври',
  'Kasım': 'Ноември',
  'Aralık': 'Декември',
  'Verilerini yanında getir': 'Донеси данните си със себе си',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Ако следиш какво гледаш в друго приложение, можеш да го прехвърлиш тук. Не е нужно да започваш от нулата.',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt и Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Избери ZIP файла от експорта — гледаното, оценките и списъците ти ще се прехвърлят.',
  'Aktarılıyor...': 'Прехвърляне...',
  'ZIP dosyası seç': 'Избери ZIP файл',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'Няма бързане: това може да стане и по-късно от раздела Настройки > Моите данни.',
  'Hangi filmleri izledin?': 'Кои филми вече са изгледани?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Тук са най-гледаните. Докосни познатите и ще ги добавим към гледаното.',
  'SERİ FİLMLER': 'ФИЛМОВИ ПОРЕДИЦИ',
  'Serilerden {} film eklendi': 'От поредици са добавени филми: {}',
  'Film listesi yüklenemedi': 'Списъкът с филми не можа да се зареди',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Можеш да пропуснеш тази стъпка и да добавиш каквото искаш по-късно.',
  '{} film izlediklerine eklendi': 'Към гледаното са добавени филми: {}',
  'Film serileri': 'Филмови поредици',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Изгледана ли е цялата поредица? Добави я с едно докосване.',
  'Seri bulunamadı': 'Не са намерени поредици',
  'Daha sonra tekrar deneyebilirsin.': 'Можеш да опиташ отново по-късно.',
  '{} film': 'Филми: {}',
  'Eklendi': 'Добавено',
  'Tümünü izledim': 'Всичко изгледано',
  'Peki ya diziler?': 'А сериалите?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Отбележи изгледаното — по отметките ти ще подберем подобни.',
  'Dizi listesi yüklenemedi': 'Списъкът със сериали не можа да се зареди',
  'Seçtiklerine benzeyenler': 'Подобни на избраното от теб',
  'Her şey hazır': 'Всичко е готово',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Хвърли бърз поглед какво можеш да правиш в dizi.jpg.',
  'Profilini tamamla': 'Попълни профила си',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'От раздела Настройки можеш да добавиш Био, профилна снимка и корица.',
  'Takvimin seni bekliyor': 'Календарът те чака',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'Новите епизоди на сериалите, които гледаш, влизат в календара, а ние ти казваме с известие.',
  'Puan ver, yorum yaz': 'Оцени, напиши коментар',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Оценявай епизод по епизод, пиши коментари зад спойлер завеса, създавай списъци.',
  'Verilerin sende kalır': 'Данните ти остават твои',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Данните ти се пазят само свързани с профила ти и не се продават. От раздела Настройки можеш да ги изтеглиш всички или да изтриеш профила си напълно.',
  'Engellenen kullanıcılar': 'Блокирани потребители',
  'Engellediğin kişileri gör, engeli kaldır':
      'Виж блокираните и ги разблокирай',
  'Engellediğin kimse yok': 'Няма блокирани',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Можеш да блокираш потребител от менюто с три точки в страницата на профила.',
  '@{} engellensin mi?': 'Да се блокира ли @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'Няма да виждате взаимно публикациите, коментарите и профилите си; съобщения и обаждания също няма да минават. Ако има следване между вас, то се прекъсва и не се връща дори ако премахнеш блокирането.',
  'Bu kullanıcıyı engelledin': 'Този потребител е блокиран',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Не виждаш публикациите, коментарите и съобщенията на този човек, а и този човек не вижда твоите.',
  '{} yeni bir yapımda: {}': '{} в нов проект: {}',
  'Favori kişinden yeni yapım': 'Нов проект от любим човек',
  '{} için bildirimler': 'Известия за {}',
  'Tüm bildirimler': 'Всички известия',
  'Uygulamada ve telefonda': 'В приложението и на телефона',
  'Yalnız uygulama içi': 'Само в приложението',
  'Telefon bildirimi gönderilmez': 'Не се изпраща известие на телефона',
  'Kapalı': 'Изключено',
  'Bu kişi için bildirim yok': 'Няма известия за този човек',
  'Favori kişilerin yeni yapımları': 'Нови проекти на любими хора',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Когато е изключено, никой не може да ти се обади гласово; обаждащият се вижда съобщение "изключено"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Когато е изключено, никой не може да ти се обади с видео; обаждащият се вижда съобщение "изключено"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'Моята активност',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'Твоите харесвания, коментари и гледания на едно място',
  'Henüz hareketin yok': 'Още няма активност',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Всичко, което харесваш, коментираш и гледаш, се събира тук.',
  'Bu süzgeçte hareket yok': 'Няма активност в този филтър',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Избери друг тип или се върни към „Всички“.',
  'Hepsi': 'Всички',
  'Puan': 'Оценка',
  'Tepki': 'Реакция',
  'İzleme': 'Гледане',
  'Durum': 'Статус',
  'Liste': 'Списък',
  'Yorum yaptın': 'Добавен коментар',
  'Yorumu beğendin': 'Харесан коментар',
  '{} puan verdin': 'Оценка {}',
  'Tepki verdin': 'Реакция',
  'Listene ekledin': 'Добавено в списък',
  'Takip etmeye başladın': 'Ново следване',
  '"İzleyeceğim" işaretledin': 'Отбелязано „Ще гледам“',
  '"İzliyorum" işaretledin': 'Отбелязано „Гледам“',
  '"Bitirdim" işaretledin': 'Отбелязано „Завършено“',
  '"Bıraktım" işaretledin': 'Отбелязано „Зарязано“',
  'Silinmiş içerik': 'Изтрито съдържание',
  'şimdi': 'сега',
  '{} g': '{} д',
  '{} y': '{} г',
  'İstatistiklerim': 'Моята статистика',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Показвания и харесвания на публикациите ти',
  'Henüz gönderin yok': 'Още нямаш публикации',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Щом коментираш сериал или филм, показванията и харесванията ти започват да се събират тук.',
  'Tüm zamanlar': 'За всички времена',
  'Son {} gün': 'Последните {} дни',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'Историята на показванията още не е започнала да се събира; данните за първия ден се появяват утре.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'Историята на показванията се събира от {} (има данни за {} дни), затова числото за {} дни все още е непълно.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'Историята на харесванията се записва от {}.',
  'Bu dönemde gösterilecek gönderi yok.':
      'Няма публикации за показване за този период.',
  'eksik veri': 'непълни данни',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Гледаните сериали и филми, броячите ти за гледане, времето пред екрана и картата за съвпадение няма да се виждат от другите в профила ти',
  'Takipçi listemi gizle': 'Скрий списъка с последователите ми',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Другите не могат да видят кой те следва; броят на последователите ти остава видим',
  'Takip ettiklerimi gizle': 'Скрий кого следвам',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Другите не могат да видят кого следваш; броят на следваните остава видим',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Този потребител предпочита да пази последователите си скрити.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Този потребител предпочита да пази скрито кого следва.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Статистика на публикацията',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Статистиката е достъпна само за твоите собствени публикации.',
  'Erişim': 'Обхват',
  'Görüntüleyen': 'Зрители',
  'Kaç farklı kişi gördü (son {} gün)':
      'Колко различни хора са видели (последните {} дни)',
  'Paylaşım': 'Споделяния',
  'Bu gönderiden sonra': 'След тази публикация',
  'Profil ziyareti': 'Посещения на профила',
  'Yeni takip': 'Нови последвания',
  'İçeriğe tıklama': 'Докосвания на съдържанието',
  'Spoiler perdesini açan': 'Разкриха спойлера',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Споделянията, посещенията на профила, последванията, докосванията на съдържанието, разбивката по източници и измерванията за спойлер се натрупват от {}; по-ранното не е измервано.',
  'Zamana yayılmış görüntülenme': 'Показвания във времето',
  'Görüntülenme nereden geldi': 'Откъде дойдоха показванията',
  'Kimler gördü': 'Кой го е видял',
  'Günlük veri henüz birikmeye başlamadı.':
      'Дневните данни още не са започнали да се натрупват.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'Графиката се нуждае от данни поне за два дни. Данните се натрупват от {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'Най-много показвания дойдоха на {}-ия ден след публикуването: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Дневните показвания се натрупват от {}; по-ранното не е измервано.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'Разбивката по източници едва започна да се измерва; тази публикация още не е получила отбелязано показване.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'Разбивката последователи/откриване едва започна да се измерва; още няма данни.',
  'Takip edenler': 'Последователи',
  'Keşiften gelenler': 'От Открий',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Страница на сериал/филм',
  'Paylaşılan bağlantı': 'Споделен линк',
  'yeni ölçülüyor': 'ново измерване',
  'Kendi ortalamanla aynı düzeyde': 'На нивото на твоята средна стойност',
  'Kendi ortalamanın %{} üstünde': 'С {}% над твоята средна стойност',
  'Kendi ortalamanın %{} altında': 'С {}% под твоята средна стойност',
  'Etkileşim oranı': 'Ниво на взаимодействие',
  '(beğeni + yorum) ÷ görüntülenme': '(харесвания + коментари) ÷ показвания',
  'Toplam görüntülenme': 'Общо показвания',
  '{} ile {} arasında toplam {} görüntülenme':
      'Между {} и {}: общо {} показвания',
  'İstatistikleri gör': 'Виж статистиката',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'За статистиката, показвана на автора на публикацията, се пазят като обобщени броячи: колко пъти и от коя повърхност (емисия, профил, емисия на цял екран, страница на сериал/филм, споделен линк) е разгледана публикацията, дали разглеждащият е следвал автора в този момент, преминаването от публикацията към профил или съдържание, последванията, започнали през публикацията, споделянията и отварянето на спойлер завесата. Тези броячи не съдържат идентичност на потребител, IP адрес или времеви печат; не може да се провери кой какво е направил.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'За да може да се преброи колко различни хора са видели дадена публикация, за всеки разглеждащ се пази 90 дни необратима извадка с ключ (криптографско съкращение, изведено от идентичността на потребителя или от IP адреса). На автора на публикацията се показва само числото; самоличността на разглеждащите не се споделя при никакви обстоятелства.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'Да се премести ли в „Ще гледам“?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'Едно заглавие или предстои да се гледа, или вече е изгледано. Ако продължиш, отметките ти за гледане в този сериал ({}) ще бъдат изтрити.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'Едно заглавие или предстои да се гледа, или вече е изгледано. Ако продължиш, отметката ти „Изгледано“ за този филм ще бъде премахната.',
  'Sil ve taşı': 'Изтрий и премести',

  // --- Yapım ekibi / firma + seviye unvanları + doğum günü ---
  'Yapım Ekibi': 'Екип',
  'Yaratıcı': 'Идея',
  'Yönetmen': 'Режисура',
  'Senaryo': 'Сценарий',
  'Yapımcı': 'Продукция',
  'Yapım Firmaları': 'Продуцентски компании',
  'Yapım Firması': 'Продуцентска компания',
  'Firma bulunamadı': 'Компанията не е намерена',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'Тази компания няма заглавия от този тип.',
  'Doğum günün kutlu olsun!': 'Честит рожден ден!',
  'İyi ki doğdun, iyi ki buradasın.':
      'Хубаво, че се роди, и хубаво, че си тук.',
  'Bugün {} yaşına girdin': 'Днес навършваш {} години',
  'Teşekkürler': 'Благодаря',
  'İki Adımlı Doğrulama': 'Потвърждаване в две стъпки',
  'Girişte e-postana kod gönderilir': 'При влизане на имейла ти се изпраща код',
  'Kod {} adresine gönderildi': 'Кодът е изпратен до {}',
  '6 haneli kod': '6-цифрен код',
  'Doğrula': 'Потвърди',
  'Yeniden gönder': 'Изпрати отново',
  'Vazgeç': 'Отказ',
  'Yeni kod gönderildi': 'Изпратен е нов код',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'При влизане с Google не се иска код; Google прави собствена проверка.',
  'Kapatmak için de kod gerekir.': 'За изключване също се изисква код.',
  'E-postana erişemezsen hesabına giremezsin.':
      'Ако изгубиш достъп до имейла си, няма да можеш да влезеш в акаунта си.',
  'İki adımlı doğrulama açıldı': 'Потвърждаването в две стъпки е включено',
  'İki adımlı doğrulama kapatıldı': 'Потвърждаването в две стъпки е изключено',
  'Videonun ne kadarı izlendi': 'Докъде е гледано видеото',
  'Videoyu başlatanlar': 'Пуснали видеото',
  'videonun %{} noktasına ulaştı': 'са стигнали до {}% от видеото',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'Половината от публиката е гледала поне {}% от видеото.',
  'Sonuna kadar izleyen: %{}': 'Гледали до края: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'Кривата изисква поне {} гледания; сега има {}.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'Кривата се основава на {} гледания и не зависи от избрания период.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'Времето на гледане се измерва от {}; по-старите показвания не се броят.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} гледания. {}% са стигнали до средата, {}% до края.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'Ниво {}',
  'Sonraki seviyeye {} puan kaldı': 'Още {} точки до следващото ниво',
  'Gönderilerin': 'Твоите публикации',
  '{} gönderi': '{} публикации',
  '{} gönderi · {} görüntülenme': '{} публикации · {} показвания',
  'önceki {} güne göre': 'спрямо предходните {} дни',
  'önceki {} güne göre %{} arttı': 'спрямо предходните {} дни, ръст с {}%',
  'önceki {} güne göre %{} azaldı': 'спрямо предходните {} дни, спад с {}%',
  'önceki {} güne göre değişmedi': 'без промяна спрямо предходните {} дни',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'Дневни показвания: най-малко {}, най-много {}',
  'Etkileşim oranı henüz ölçülemedi':
      'Нивото на взаимодействие още не може да се измери',
  'Oranlar': 'Проценти',
  'Beğenme oranı': 'Процент харесвания',
  'Yorum oranı': 'Процент коментари',
  'Paylaşma oranı': 'Процент споделяния',
  'İçeriğe gitme oranı': 'Процент към съдържанието',
  'Profile gitme oranı': 'Процент посещения',
  'Ziyaretten takibe dönüşüm': 'Посещение към последване',
  'beğeni ÷ görüntülenme': 'харесвания ÷ показвания',
  'yorum ÷ görüntülenme': 'коментари ÷ показвания',
  'paylaşım ÷ görüntülenme': 'споделяния ÷ показвания',
  'içeriğe tıklama ÷ görüntülenme': 'докосвания на съдържанието ÷ показвания',
  'profil ziyareti ÷ görüntülenme': 'посещения на профила ÷ показвания',
  'yeni takip ÷ profil ziyareti': 'нови последвания ÷ посещения на профила',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'Процентите изискват поне {} показвания; сега има {}.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'Процентите се изчисляват от общите числа на публикацията за целия ѝ период; изборът на дни по-долу не ги променя.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'Тези числа са общо за целия период на публикацията (без кутиите със собствена бележка); изборът на дни по-долу променя само графиката.',
  'Ortalama izlenme: videonun %{} kadarı': 'Средно изгледано: {}% от видеото',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'Средното от 20-те части на кривата.',
  'Dizi, film, kişi veya şirket ara...':
      'Търси сериал, филм, човек или компания...',
  'Şirketler': 'Компании',
  'Senarist': 'Сценарист',
  'Bölüm puanları': 'Оценки на епизоди',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'Оценките на епизодите не можаха да се заредят',
  'Giriş gerekli': 'Необходим е вход',
  'Geçersiz oturum': 'Невалидна сесия',
  'Oturum sonlandı, tekrar giriş yap': 'Сесията приключи, влез отново',
  'Çok fazla istek; biraz sonra tekrar dene':
      'Твърде много заявки; опитай пак след малко',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'В момента няма място на сървъра, опитай отново след малко',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'Грешен имейл/потребител или парола',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'Този имейл или потребител вече е зает',
  'Google doğrulaması başarısız': 'Проверката на Google не успя',
  'Kod geçersiz veya süresi dolmuş': 'Кодът е невалиден или е изтекъл',
  'Bu kullanıcıyla mesajlaşamazsın': 'Не можеш да пишеш на този потребител',
  'Kendini takip edemezsin': 'Не можеш да следваш себе си',
  'Bu kullanıcıyı takip edemezsin': 'Не можеш да следваш този потребител',
  'Kendini engelleyemezsin': 'Не можеш да блокираш себе си',
  'Yorum 1-1000 karakter olmalı': 'Коментарът трябва да е 1–1000 знака',
  'Boş mesaj gönderilemez': 'Не може да се изпрати празно съобщение',
  'Yorum bulunamadı': 'Коментарът не е намерен',
  'Şifre hatalı': 'Грешна парола',
  'Şifre en az 6 karakter olmalı': 'Паролата трябва да е поне 6 знака',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'Може да се качва само GIF, PNG, JPEG или WebP',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'Поддържани типове: GIF, PNG, JPEG, WebP, MP4, WebM, аудио',
  'Geçerli bir ZIP dosyası değil': 'Това не е валиден ZIP файл',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'За да получиш данните по имейл, първо свържи адрес',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'Имаш записи за гледане. За „Ще гледам“ първо ги изтрий.',
  'Arama şu anda kapalı': 'Обажданията са изключени в момента',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'Гост акаунт не може да включи обаждания; създай акаунт',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'Сървърът се рестартира, опитай пак след малко',
  'Puan 1-10 arası olmalı': 'Оценката трябва да е между 1 и 10',
  'En fazla 10 medya eklenebilir': 'Може да се добавят най-много 10 файла',
  'Bu cihazdan yeni hesap açılamıyor':
      'От това устройство не може да се създаде акаунт',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'Нужен е валиден имейл, потребителско име и парола от поне 6 знака',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'Нужен е валиден имейл и парола от поне 6 знака',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'Потребителското име е 3–20 знака; малки букви, цифри, точки, тирета и долни черти (не в краищата)',
  'Bu hesap zaten bağlı': 'Този акаунт вече е свързан',
  'Hesap oluşturulamadı': 'Акаунтът не можа да бъде създаден',
  'Misafir hesabı oluşturulamadı': 'Гост акаунтът не можа да бъде създаден',
  'Hesap bulunamadı': 'Акаунтът не е намерен',
  'Bu hesapta e-posta yok': 'Този акаунт няма имейл',
  'İki adımlı doğrulama zaten bu durumda':
      'Двустъпковата проверка вече е в това състояние',
  'Kod yanlış': 'Грешен код',
  'Kodun süresi doldu': 'Кодът е изтекъл',
  'Kullanıcının e-postası yok (misafir hesap)':
      'Този потребител няма имейл (гост акаунт)',
  'Bio en fazla 300 karakter olabilir': 'Биото може да е най-много 300 знака',
  'Geçersiz ülke': 'Невалидна държава',
  'Geçersiz sosyal bağlantı': 'Невалидна социална връзка',
  'Geçersiz doğum tarihi': 'Невалидна рождена дата',
  'Liste adı gerekli': 'Името на списъка е задължително',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'Името може да е най-много 60, описанието 300 знака',
  'Liste bulunamadı': 'Списъкът не е намерен',
  'Değiştirilecek tercih yok': 'Няма какво да се обнови',
  'İnceleme en fazla 2000 karakter olabilir':
      'Рецензията може да е най-много 2000 знака',
  'Önce içeriği "bitirdim" olarak işaretle':
      'Първо маркирай заглавието като гледано',
  'Önce kişiyi favorile': 'Първо добави човека в любими',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'За коментар към епизод са нужни и сезон, и епизод',
  'Yanıtlanan yorum bulunamadı': 'Коментарът, на който отговаряш, не е намерен',
  'Geri bildirim 3-2000 karakter olmalı':
      'Обратната връзка трябва да е 3–2000 знака',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'Заглавие и текст са задължителни (поне 2 знака)',
  'Kendine mesaj gönderemezsin': 'Не можеш да пишеш на себе си',
  'Mesaj en fazla 2000 karakter olabilir':
      'Съобщението може да е най-много 2000 знака',
  'Mesaj 1-2000 karakter olmalı': 'Съобщението трябва да е 1–2000 знака',
  'Mesaj bulunamadı': 'Съобщението не е намерено',
  'Mesaj bulunamadı veya düzenlenemez':
      'Съобщението не е намерено или не може да се редактира',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'Можеш да докладваш само съобщение, изпратено до теб',
  'Sebep gerekli': 'Причината е задължителна',
  'İtiraz edilecek aktif bir ceza yok': 'Няма активно наказание за обжалване',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'Вече имаш жалба, чакаща преглед',
  'Bu ceza için itirazın zaten incelendi':
      'Жалбата за това наказание вече е прегледана',
  'Medya bağlantısının süresi dolmuş': 'Медийният линк е изтекъл',
  'Bu medya için imzalı bağlantı gerekli':
      'За тази медия е нужен подписан линк',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'Услугата за обаждания се рестартира; опитай след малко',
  'Puan göstergesi': 'Легенда на оценките',
};
