/// Otomatik üretilen çeviri haritası (sr).
const Map<String, String> cevirilerSr = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Није пронађен препознатљив податак за увоз.',
  'Arama': 'Претрага',
  'Aramaya başla': 'Почни да претражујеш',
  'Son aramalar': 'Недавне претраге',
  'Ayarlar': 'Подешавања',
  'Bağla': 'Повежи',
  'Bio': 'Био',
  'Bitirdim': 'Завршено',
  'Bunları da Beğenebilirsin': 'Можда ти се свиде и ови',
  'Bölüm': 'Епизода',
  'Bıraktım': 'Напуштено',
  'Dil': 'Језик',
  'Dil ara...': 'Претражи језике...',
  'Dizi': 'Серија',
  'Dizi ve filmlerini takip et': 'Прати своје серије и филмове',
  'Dizi yorumu': 'Коментар о серији',
  'Dizi, film veya kişi ara...': 'Претражи серије, филмове или особе...',
  'Dosya en fazla 30MB olabilir': 'Фајл може бити највише 30MB',
  'Dosya en fazla {}MB olabilir': 'Фајл може бити највише {}MB',
  'E-posta': 'Имејл',
  'E-posta veya kullanıcı adı': 'Имејл или корисничко име',
  'En az 2 harf yaz': 'Укуцај бар 2 слова',
  'Film': 'Филм',
  'Film yorumu': 'Коментар о филму',
  'Fotoğraf / video ekle': 'Додај фотографију / видео',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Фотографија или GIF — профилна и насловна слика',
  'Giriş Yap': 'Пријави се',
  'Gönder': 'Пошаљи',
  'Gönderildi': 'Послато',
  'Haftanın Dizileri': 'Серије недеље',
  'Haftanın Filmleri': 'Филмови недеље',
  'Henüz izleme kaydın yok': 'Још немаш историју гледања',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Још немаш листу — направи је у картици Профил.',
  'Henüz yorum yok.': 'Још нема коментара.',
  'Hesabın bağlandı!': 'Налог је повезан!',
  'Hesabın yok mu? Kayıt ol': 'Немаш налог? Региструј се',
  'Hesabını Bağla': 'Повежи свој налог',
  'Hesap Oluştur': 'Направи налог',
  'Kapak resmi ekle': 'Додај насловну слику',
  'Kaydet': 'Сачувај',
  'Kendinden bahset...': 'Реци нешто о себи...',
  'Keşfet': 'Откриј',
  'Kimseyi takip etmiyor': 'Не прати никога',
  'Kişi ara': 'Претражи особе',
  'Kişi yorumu': 'Коментар о особи',
  'Konuk Oyuncular': 'Гостујуће улоге',
  'Kullanıcı adı (küçük harf)': 'Корисничко име (мала слова)',
  'Kullanıcı adı ara...': 'Претражи корисничка имена...',
  'Liste adı': 'Назив листе',
  'Listeye Ekle': 'Додај на листу',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Користиш налог за госте — повежи га са имејлом да не изгубиш податке!',
  'Misafir olarak devam et': 'Настави као гост',
  'Oluştur': 'Направи',
  'Oyuncular': 'Глумци',
  'Profil': 'Профил',
  'Profil kaydedildi': 'Профил је сачуван',
  'Puanla': 'Оцени',
  'Puanı Sil': 'Обриши оцену',
  'Puanın': 'Твоја оцена',
  'Sezonlar': 'Сезоне',
  'Sunucu hatası ({})': 'Грешка сервера ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Коментар за S{}E{}',
  'Takibi Bırak': 'Отпрати',
  'Takip': 'Праћење',
  'Takip Edilenler': 'Праћени',
  'Takip Et': 'Запрати',
  'Takipçi': 'Пратилац',
  'Takipçi yok': 'Нема пратилаца',
  'Takipçiler': 'Пратиоци',
  'Takvim': 'Календар',
  'Tamam': 'У реду',
  'Tekrar Dene': 'Покушај поново',
  'Tekrar dene': 'Покушај поново',
  'Toplam ekran süresi': 'Укупно време гледања',
  'Tüm Zamanların En İyileri': 'Најбоље свих времена',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Преузми све своје податке (гледања, оцене, коментаре, листе) као ZIP компатибилан са TV Time или увези ZIP из друге апликације.',
  'Tümünü Kaldır': 'Уклони све',
  'Tümünü İzledim': 'Све одгледано',
  'Türk Dizileri': 'Турске серије',
  'Veri içe aktar (.zip)': 'Увоз података (.zip)',
  'Verilerim': 'Моји подаци',
  'Verilerimi dışa aktar (e-posta)': 'Извези моје податке (имејл)',
  'Verilerini dışa aktar': 'Извези своје податке',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Нема предстојећих епизода.\nУ детаљима серије пребаци је на "Гледам" и прати нове епизоде овде.',
  'Yapımları': 'Филмографија',
  'Yeni Diziler': 'Нове серије',
  'Yeni Liste': 'Нова листа',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Ново корисничко име (опционо)',
  'Yorum': 'Коментар',
  'Yorumunu yaz...': 'Напиши свој коментар...',
  'Zaten hesabın var mı? Giriş yap': 'Већ имаш налог? Пријави се',
  'ort. {}': 'прос. {}',
  'takip': 'праћења',
  'takipçi': 'пратилаца',
  '{} / {} bölüm': '{} / {} епизода',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} мес.',
  '{} bölüm izlendi': '{} епизода одгледано',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} мин',
  '{} gün': '{} дана',
  '{} içerik': '{} наслова',
  '{} içerik · otomatik': '{} наслова · аутоматски',
  '{} kayıt atlandı (eşleşmedi).': '{} записа прескочено (без поклапања).',
  '{} saat': '{} сати',
  '{} sezon': '{} сезона',
  '{} yıl': '{} година',
  '{}. Bölüm': '{}. епизода',
  '{}. Sezon': '{}. сезона',
  'Çıkış Yap': 'Одјави се',
  'Ülke': 'Земља',
  'Ülke ara...': 'Претражи земље...',
  'Ülke seç': 'Изабери земљу',
  'İlk yorumu sen yaz!': 'Напиши први коментар!',
  'İncelemeler': 'Рецензије',
  'İncelemen (isteğe bağlı)': 'Твоја рецензија (опционо)',
  'İptal': 'Откажи',
  'İzlediklerim': 'Историја гледања',
  'İzledim': 'Одгледано',
  'İzledin': 'Одгледао/ла си',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Историја гледања и листе остају сачуване; од сада можеш да се пријавиш са било ког уређаја.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Историја гледања, оцене, коментари и листе биће послати као ZIP на регистровану имејл адресу.',
  'İzleyeceğim': 'Гледаћу',
  'İzliyorum': 'Гледам',
  'İçe aktarım tamamlandı': 'Увоз је завршен',
  'Şifre': 'Лозинка',
  '• profil bilgisi': '• подаци о профилу',
  '• {} dizi durumu': '• {} статуса серија',
  '• {} izleme kaydı': '• {} записа гледања',
  '• {} liste': '• {} листа',
  '• {} puan': '• {} оцена',
  '• {} yorum': '• {} коментара',
  '{}+ yapım': '{}+ наслова',
  'Yorumlar': 'Коментари',
  'Yorumlar ({})': 'Коментари ({})',
  'Yorumları ({})': 'Коментари ({})',
  'Listelerim': 'Моје листе',
  'Nereden izledin?': 'Где си гледао?',
  'Diziye git': 'Иди на серију',
  'TV / Kanal': 'ТВ / канал',
  'Sinema': 'Биоскоп',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Друго',
  'Akış': 'Фид',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Твој фид је празан.\nКад неко коментарише серије и филмове које гледаш, појавиће се овде.',
  'Listeleri ({})': 'Његове листе ({})',
  'Liste boş.': 'Ова листа је празна.',
  'Yanıtla': 'Одговори',
  '@{} kullanıcısına yanıt veriyorsun': 'Одговараш кориснику @{}',
  'İzlediğim Diziler ({})': 'Одгледане серије ({})',
  'İzlediğim Filmler ({})': 'Одгледани филмови ({})',
  'Tümünü gör': 'Прикажи све',
  'Bildirimler': 'Обавештења',
  'Henüz bildirim yok': 'Још нема обавештења',
  '@{} yorumuna yanıt verdi': '@{} је одговорио на твој коментар',
  '@{} yorumunu beğendi': '@{} се свиђа твој коментар',
  '@{} seni takip etti': '@{} те прати',
  '@{} sana mesaj gönderdi': '@{} ти је послао поруку',
  'Mesajlar': 'Поруке',
  'Mesaj': 'Порука',
  'Mesajını yaz...': 'Напиши поруку...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Још нема ћаскања.\nОтвори профил и пошаљи поруку.',
  'Şifreni mi unuttun?': 'Заборавио си лозинку?',
  'Şifreyi Sıfırla': 'Ресетуј лозинку',
  'E-postadaki kod': 'Код из мејла',
  'Yeni şifre': 'Нова лозинка',
  'Sana Özel': 'За тебе',
  '{} özetin': 'Твој преглед {}.',
  'Yıllık izleme istatistiklerin': 'Годишња статистика гледања',
  'Rozetler': 'Беџеви',
  'Verdiğin puan': 'Дате оцене',
  'Ortalama puanın': 'Просечна оцена',
  'En çok izlediğin diziler': 'Најгледаније серије',
  'İlk Bölüm': 'Прва епизода',
  '100 Bölüm': '100 епизода',
  '1000 Bölüm': '1000 епизода',
  'İlk Film': 'Први филм',
  '50 Film': '50 филмова',
  'İlk Yorum': 'Први коментар',
  '25 Yorum': '25 коментара',
  '10 Puan': '10 оцена',
  'İlk Takipçi': 'Први пратилац',
  '10 Dizi Bitirdin': 'Завршио си 10 серија',
  'İzlemeyi Bıraktım': 'Престао сам да гледам',
  'İzlediği Diziler ({})': 'Одгледане серије ({})',
  'İzlediği Filmler ({})': 'Одгледани филмови ({})',
  '500 Bölüm': '500 епизода',
  '5000 Bölüm': '5000 епизода',
  '10 Film': '10 филмова',
  '100 Film': '100 филмова',
  '100 Yorum': '100 коментара',
  '50 Puan': '50 оцена',
  '100 Puan': '100 оцена',
  '10 Takipçi': '10 пратилаца',
  '50 Takipçi': '50 пратилаца',
  '25 Dizi Bitirdin': 'Завршио 25 серија',
  '50 Dizi Bitirdin': 'Завршио 50 серија',
  '10 Beğeni': '10 лајкова',
  '100 Beğeni': '100 лајкова',
  'yazıyor...': 'куца...',
  'Profil düzeni': 'Распоред профила',
  'Konumla ve kırp': 'Намести и исеци',
  'Listeye eklendi': 'Додато у листу',
  'Listeyi sil?': 'Обрисати листу?',
  'Sil': 'Обриши',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Биће означено као никад гледано и уклоњено са твојих листа.',
  'Gelecek bölüm bugün': 'Следећа епизода данас',
  'Gelecek bölüm {} gün sonra': 'Следећа епизода за {} дана',
  'Tema': 'Тема',
  'Sistem': 'Систем',
  'Koyu': 'Тамна',
  'Açık': 'Светла',
  'İzleyenler': 'Гледаоци',
  'Yorumunu yaz... (@ ile etiketle)': 'Напиши коментар... (@ за означавање)',
  '@{} bir yorumda seni etiketledi': '@{} те је означио у коментару',
  'Mesajı sil': 'Обриши поруку',
  'Mesaj silinemedi': 'Порука није могла бити обрисана',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Веза је неисправна или страница није пронађена',
  'Keşfet\'e dön': 'Назад на Откриј',
  'Düzenle': 'Измени',
  'Mesajı düzenle': 'Измени поруку',
  'Yanıtlanıyor': 'Одговара',
  'düzenlendi': 'измењено',
  'Fotoğraf': 'Фотографија',
  'Video': 'Видео',
  'İçerik': 'Садржај',
  'çevrimiçi': 'на вези',
  'son görülme {} dk önce': 'виђен пре {} мин',
  'son görülme {} saat önce': 'виђен пре {} ч',
  'son görülme {} gün önce': 'виђен пре {} д',
  'Yorumlar yüklenemedi': 'Коментари нису могли да се учитају',
  'Favori': 'Омиљено',
  'Listeye ekle': 'Додај на листу',
  'İçerik paylaş': 'Подели садржај',
  'Kapat': 'Затвори',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Све што означиш као погледано скупља се овде.',
  'Henüz sohbetin yok': 'Још нема разговора',
  'Bir profile girip mesaj gönderebilirsin.': 'Отвори профил и пошаљи поруку.',
  'Listeyi sil': 'Обриши листу',
  'Puan kaydedilemedi': 'Оцена није могла да се сачува',
  'Nerede İzlenir': 'Где гледати',
  'Abonelik': 'Претплата',
  'Kirala': 'Изнајми',
  'Satın al': 'Купи',
  'Hoş geldin!': 'Добро дошли!',
  'İzlemek istediğin dizi ve filmleri seç':
      'Изабери серије и филмове које желиш да гледаш',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Твој избор се додаје у листу за гледање',
  'Şimdilik atla': 'Прескочи за сада',
  'Devam et': 'Настави',
  '{} ekle': 'Додај {}',
  'Şikayet et': 'Пријави',
  'Engelle': 'Блокирај',
  'Engeli kaldır': 'Одблокирај',
  'Kullanıcı engellendi': 'Корисник је блокиран',
  'Engel kaldırıldı': 'Блокирање уклоњено',
  'Şikayet sebebi': 'Разлог пријаве',
  'Spam veya yanıltıcı': 'Спам или обмањујуће',
  'Taciz veya nefret söylemi': 'Узнемиравање или говор мржње',
  'Uygunsuz / cinsel içerik': 'Неприкладан / сексуални садржај',
  'Şiddet veya tehlikeli içerik': 'Насиље или опасан садржај',
  'Telif hakkı ihlali': 'Кршење ауторских права',
  'Şikayetin alındı, teşekkürler': 'Твоја пријава је примљена, хвала',
  'Hesabımı Sil': 'Обриши налог',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Твој налог и сви подаци (историја, оцене, коментари, листе, поруке) биће трајно обрисани. Ово се не може опозвати.',
  'Şifreni gir': 'Унеси лозинку',
  'Hesabımı kalıcı sil': 'Трајно обриши налог',
  'Sesli mesaj': 'Гласовна порука',
  'Ses gönderilemedi': 'Гласовна порука није послата',
  'Kaydediliyor…': 'Снимање…',
  'Ses oynatılamadı': 'Није могуће репродуковати аудио',
  'Oynat': 'Пусти',
  'Duraklat': 'Пауза',
  'Liste görünümü': 'Приказ листе',
  'Takvim görünümü': 'Приказ календара',
  'Önceki ay': 'Претходни месец',
  'Sonraki ay': 'Следећи месец',
  'Bu gün bölüm yok': 'Нема епизода овог дана',
  'Gizlilik Politikası': 'Политика приватности',
  'Son güncelleme: {}': 'Последње ажурирање: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Ова политика објашњава који се подаци прикупљају, како се користе и која су твоја права када користиш апликацију dizi.jpg и сајт dizijpg.com.',
  'Topladığımız Veriler': 'Подаци које прикупљамо',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Налог: имејл адреса, корисничко име и лозинка. Лозинке се чувају као неповратни хеш; гостујући налози могу се користити без имејла.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Профил: подаци које сам одлучиш да додаш, попут аватара, насловне слике, биографије и земље.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Коришћење: твоја историја гледања, оцене, коментари, листе, реакције и омиљено.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Поруке: твоје текстуалне, сликовне и гласовне поруке чувају се на нашим серверима. Поруке нису шифроване с краја на крај; прегледају се само ако буду пријављене, ради модерације.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Отпремљени медији: фотографије, GIF-ови, видео-снимци и гласовни снимци које додајеш профилу, коментарима и порукама.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Техничко: IP адреса, приближна локација (на нивоу земље/града), платформа уређаја, верзија апликације и евиденције грешака. Чувају се ради безбедности и отклањања грешака.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Обавештења: за пуш обавештења чувамо токен твог уређаја и изабрани језик. Обавештења можеш било кад искључити у подешавањима уређаја.',
  'Verileri Nasıl Kullanırız': 'Како користимо твоје податке',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Твоје податке користимо искључиво за пружање услуге, заштиту налога, слање обавештења, исправљање грешака и спречавање злоупотребе. Не продајемо твоје податке и не делимо их ни са ким у рекламне сврхе.',
  'Çerezler ve Yerel Depolama': 'Колачићи и локално складиште',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Локално складиште користимо само да останеш пријављен и да запамтимо изборе попут језика и теме. Нема рекламних ни колачића за праћење.',
  'Üçüncü Taraf Hizmetler': 'Услуге трећих страна',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'Подаци о серијама и филмовима долазе са TMDB, информације о стриминг платформама са JustWatch. Пуш обавештења испоручује Google Firebase, а саобраћај сајта штити Cloudflare. На ове услуге примењују се њихове сопствене политике приватности.',
  'Saklama ve Silme': 'Чување и брисање',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Твоји подаци се чувају док твој налог постоји. Преко „Обриши мој налог" у подешавањима можеш трајно обрисати налог; подаци се бришу одмах, а њихове копије у резервним копијама најкасније за 14 дана. Евиденције грешака аутоматски се бришу после 30 дана.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'Своје податке можеш извести као ZIP из подешавања; архива се шаље на твоју имејл адресу.',
  'Güvenlik': 'Безбедност',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Подаци путују шифрованим везама (HTTPS) и чувају се на серверима са ограниченим приступом.',
  'Çocukların Gizliliği': 'Приватност деце',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg није намењен деци млађој од 13 година.',
  'Hakların': 'Твоја права',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Према KVKK и GDPR имаш право на приступ својим подацима, исправку, брисање и пренос. За то нам пиши: {}',
  'Değişiklikler': 'Измене',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Ако се ова политика промени, нова верзија биће објављена на овој страници, а датум ажуриран.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Регистрацијом прихваташ {}.',
  'Kullanıcılar': 'Корисници',
  'Fotoğrafı değiştir': 'Промени фотографију',
  'Yeniden konumlandır': 'Поново кадрирај',
  'Bir şeyler ters gitti': 'Нешто је пошло наопако',
  'Sosyal Bağlantılar': 'Друштвене везе',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'На профилу се приказује до 3 везе.',
  'Platform seç': 'Изабери платформу',
  'Kullanıcı adın': 'Твоје корисничко име',
  'Ekle': 'Додај',
  'Kaldır': 'Уклони',
  'Kopyalandı: {}': 'Копирано: {}',
  'Geçersiz kullanıcı adı': 'Неисправно корисничко име',
  'Bağlantı ekle': 'Додај везу',
  'Spoiler olabilir — dokun ve gör':
      'Може садржати спојлере — додирни да видиш',
  'Beğeni': 'Свиђања',
  'Görüntülenme': 'Прегледи',
  'Tam ekran': 'Цео екран',
  'Sonuç bulunamadı': 'Нема резултата',
  'Dizi ve Filmler': 'Серије и филмови',
  'Kişiler': 'Особе',
  'Ana Sayfa': 'Почетна',
  'Paylaş': 'Подели',
  'Yanıtlar': 'Одговори',
};
