/// Otomatik üretilen çeviri haritası (it).
const Map<String, String> cevirilerIt = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Hai visto tutto, te lo mostriamo dall’inizio',
  'Aktarılacak tanınan veri bulunamadı.':
      'Nessun dato riconosciuto da importare.',
  'Arama': 'Ricerca',
  'Aramaya başla': 'Inizia a cercare',
  'Son aramalar': 'Ricerche recenti',
  'Ayarlar': 'Impostazioni',
  'Bağla': 'Collega',
  'Bio': 'Bio',
  'Bitirdim': 'Finita',
  'Bunları da Beğenebilirsin': 'Potrebbero piacerti anche',
  'Bölüm': 'Episodio',
  'Bıraktım': 'Abbandonata',
  'Dil': 'Lingua',
  'Dil ara...': 'Cerca lingua...',
  'Dizi': 'Serie TV',
  'Dizi ve filmlerini takip et':
      'Tieni traccia delle tue serie e dei tuoi film',
  'Dizi yorumu': 'Commento alla serie',
  'Dizi, film veya kişi ara...': 'Cerca serie, film o persone...',
  'Dosya en fazla 30MB olabilir': 'Il file può essere al massimo di 30MB',
  'Dosya en fazla {}MB olabilir': 'Il file può essere al massimo di {}MB',
  'E-posta': 'E-mail',
  'E-posta veya kullanıcı adı': 'E-mail o nome utente',
  'En az 2 harf yaz': 'Scrivi almeno 2 lettere',
  'Film': 'Film',
  'Film yorumu': 'Commento al film',
  'Fotoğraf / video ekle': 'Aggiungi foto / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto o GIF — immagine del profilo e copertina',
  'Giriş Yap': 'Accedi',
  'Gönder': 'Invia',
  'Gönderildi': 'Inviato',
  'Haftanın Dizileri': 'Serie della settimana',
  'Haftanın Filmleri': 'Film della settimana',
  'Henüz izleme kaydın yok': 'Non hai ancora una cronologia',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Non hai ancora liste — creane una dalla scheda Profilo.',
  'Henüz yorum yok.': 'Ancora nessun commento.',
  'Hesabın bağlandı!': 'Account collegato!',
  'Hesabın yok mu? Kayıt ol': 'Non hai un account? Registrati',
  'Hesabını Bağla': 'Collega il tuo account',
  'Hesap Oluştur': 'Crea account',
  'Kapak resmi ekle': 'Aggiungi copertina',
  'Kaydet': 'Salva',
  'Kendinden bahset...': 'Parlaci di te...',
  'Keşfet': 'Scopri',
  'Kimseyi takip etmiyor': 'Non segue nessuno',
  'Kişi ara': 'Cerca persone',
  'Kişi yorumu': 'Commento alla persona',
  'Konuk Oyuncular': 'Guest star',
  'Kullanıcı adı (küçük harf)': 'Nome utente (minuscolo)',
  'Kullanıcı adı ara...': 'Cerca nome utente...',
  'Liste adı': 'Nome della lista',
  'Listeye Ekle': 'Aggiungi alla lista',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Sei in un account ospite — collega la tua e-mail, non perdere i tuoi dati!',
  'Misafir olarak devam et': 'Continua come ospite',
  'Oluştur': 'Crea',
  'Oyuncular': 'Cast',
  'Profil': 'Profilo',
  'Profil kaydedildi': 'Profilo salvato',
  'Puanla': 'Valuta',
  'Puanı Sil': 'Elimina voto',
  'Puanın': 'Il tuo voto',
  'Sezonlar': 'Stagioni',
  'Sunucu hatası ({})': 'Errore del server ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Commento S{}E{}',
  'Takibi Bırak': 'Smetti di seguire',
  'Takip': 'Seguiti',
  'Takip Edilenler': 'Seguiti',
  'Takip Et': 'Segui',
  'Takipçi': 'Follower',
  'Takipçi yok': 'Nessun follower',
  'Takipçiler': 'Follower',
  'Takvim': 'Calendario',
  'Tamam': 'OK',
  'Tekrar Dene': 'Riprova',
  'Tekrar dene': 'Riprova',
  'Toplam İzleme Süresi': 'Tempo di visione totale',
  'Tüm Zamanların En İyileri': 'I migliori di sempre',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da TV Time / Letterboxd ZIP'ini içe aktar.":
      'Esporta tutti i tuoi dati (visioni, voti, commenti, liste) come ZIP compatibile con TV Time o importa uno ZIP di TV Time / Letterboxd.',
  'Tümünü Kaldır': 'Rimuovi tutto',
  'Tümünü İzledim': 'Ho visto tutto',
  'Türk Dizileri': 'Serie turche',
  'Veri içe aktar (.zip)': 'Importa dati (.zip)',
  'Verilerim': 'I miei dati',
  'Verilerimi dışa aktar (e-posta)': 'Esporta i miei dati (e-mail)',
  'Verilerini dışa aktar': 'Esporta i tuoi dati',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Nessun episodio in arrivo.\nImposta una serie su "Sto guardando" dalla sua scheda e segui qui i nuovi episodi.',
  'Yapımları': 'Filmografia',
  'Yeni Diziler': 'Nuove serie',
  'Yeni Liste': 'Nuova lista',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nuovo nome utente (facoltativo)',
  'Yorum': 'Commento',
  'Yorumunu yaz...': 'Scrivi il tuo commento...',
  'Zaten hesabın var mı? Giriş yap': 'Hai già un account? Accedi',
  'ort. {}': 'med. {}',
  'takip': 'seguiti',
  'takipçi': 'follower',
  '{} / {} bölüm': '{} / {} episodi',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} mesi',
  '{} ay~tekil': '{} mese',
  '{} bölüm izlendi': '{} episodi visti',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} dk~tekil': '{} min',
  '{} gün': '{} giorni',
  '{} gün~tekil': '{} giorno',
  '{} içerik': '{} titoli',
  '{} içerik · otomatik': '{} titoli · automatica',
  '{} kayıt atlandı (eşleşmedi).': '{} voci saltate (nessuna corrispondenza).',
  '{} saat': '{} ore',
  '{} saat~tekil': '{} ora',
  '{} sezon': '{} stagioni',
  '{} yıl': '{} anni',
  '{} yıl~tekil': '{} anno',
  '{}. Bölüm': 'Episodio {}',
  '{}. Sezon': 'Stagione {}',
  'Çıkış Yap': 'Esci',
  'Ülke': 'Paese',
  'Ülke ara...': 'Cerca paese...',
  'Ülke seç': 'Scegli il paese',
  'İlk yorumu sen yaz!': 'Scrivi il primo commento!',
  'İncelemeler': 'Recensioni',
  'İncelemen (isteğe bağlı)': 'La tua recensione (facoltativa)',
  'İptal': 'Annulla',
  'İzlediklerim': 'La mia cronologia',
  'İzledim': 'Visto',
  'İzledin': 'Hai visto',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'La tua cronologia e le tue liste vengono conservate; ora puoi accedere da qualsiasi dispositivo.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'La tua cronologia, i tuoi voti, i tuoi commenti e le tue liste saranno inviati come ZIP alla tua e-mail registrata.',
  'İzleyeceğim': 'Da vedere',
  'İzliyorum': 'Sto guardando',
  'İçe aktarım tamamlandı': 'Importazione completata',
  'Şifre': 'Password',
  '• profil bilgisi': '• info profilo',
  '• {} kitaplık kaydı': '• {} voci in libreria',
  '• {} favori': '• {} preferiti',
  '• {} izleme kaydı': '• {} visioni',
  '• {} liste': '• {} liste',
  '• {} puan': '• {} voti',
  '• {} yorum': '• {} commenti',
  '{}+ yapım': '{}+ titoli',
  'Yorumlar': 'Commenti',
  'Yorumlar ({})': 'Commenti ({})',
  'Yorumları ({})': 'Commenti ({})',
  'Listelerim': 'Le mie liste',
  'Nereden izledin?': "Dove l'hai visto?",
  'Diziye git': 'Vai alla serie',
  'TV / Kanal': 'TV / Canale',
  'Sinema': 'Cinema',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Altro',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Il tuo feed è vuoto.\nQuando commenteranno le serie e i film che guardi, apparirà qui.',
  'Listeleri ({})': 'Le sue liste ({})',
  'Liste boş.': 'Questa lista è vuota.',
  'Yanıtla': 'Rispondi',
  '@{} kullanıcısına yanıt veriyorsun': 'Stai rispondendo a @{}',
  'İzlediğim Diziler ({})': 'Serie viste ({})',
  'İzlediğim Filmler ({})': 'Film visti ({})',
  'Tümünü gör': 'Vedi tutto',
  'Bildirimler': 'Notifiche',
  'Henüz bildirim yok': 'Ancora nessuna notifica',
  '@{} yorumuna yanıt verdi': '@{} ha risposto al tuo commento',
  '@{} yorumunu beğendi': '@{} ha messo mi piace al tuo commento',
  '{} ve {} yorumunu beğendi': 'A {} e {} piace il tuo commento',
  '{} ve {} kişi yorumunu beğendi': 'A {} e ad altri {} piace il tuo commento',
  '@{} seni takip etti': '@{} ha iniziato a seguirti',
  '@{} sana mesaj gönderdi': '@{} ti ha inviato un messaggio',
  'Mesajlar': 'Messaggi',
  'Mesaj': 'Messaggio',
  'Mesaja eklenecek': 'Sara aggiunto al messaggio',
  'Mesajını yaz...': 'Scrivi un messaggio...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Ancora nessuna chat.\nApri un profilo e invia un messaggio.',
  'Şifreni mi unuttun?': 'Password dimenticata?',
  'Şifreyi Sıfırla': 'Reimposta password',
  'E-postadaki kod': "Codice dall'email",
  'Yeni şifre': 'Nuova password',
  'Sana Özel': 'Per te',
  '{} özetin': 'Il tuo riepilogo {}',
  'Yıllık izleme istatistiklerin': 'Le tue statistiche annuali',
  'Rozetler': 'Badge',
  'Verdiğin puan': 'Voti dati',
  'Ortalama puanın': 'Il tuo voto medio',
  'En çok izlediğin diziler': 'Le serie più viste',
  'İlk Bölüm': 'Primo episodio',
  '100 Bölüm': '100 episodi',
  '1000 Bölüm': '1000 episodi',
  'İlk Film': 'Primo film',
  '50 Film': '50 film',
  'İlk Yorum': 'Primo commento',
  '25 Yorum': '25 commenti',
  '10 Puan': '10 voti',
  'İlk Takipçi': 'Primo follower',
  '10 Dizi Bitirdin': '10 serie completate',
  'İzlemeyi Bıraktım': 'Ho smesso di guardarla',
  'İzlediği Diziler ({})': 'Serie che ha visto ({})',
  'İzlediği Filmler ({})': 'Film che ha visto ({})',
  '500 Bölüm': '500 episodi',
  '5000 Bölüm': '5000 episodi',
  '10 Film': '10 film',
  '100 Film': '100 film',
  '100 Yorum': '100 commenti',
  '50 Puan': '50 voti',
  '100 Puan': '100 voti',
  '10 Takipçi': '10 follower',
  '50 Takipçi': '50 follower',
  '25 Dizi Bitirdin': '25 serie completate',
  '50 Dizi Bitirdin': '50 serie completate',
  '10 Beğeni': '10 mi piace',
  '100 Beğeni': '100 mi piace',
  'yazıyor...': 'sta scrivendo...',
  'ses kaydediyor...': 'sta registrando audio...',
  'Profil düzeni': 'Layout del profilo',
  'Konumla ve kırp': 'Posiziona e ritaglia',
  'Listeye eklendi': 'Aggiunto alla lista',
  'Listeyi sil?': 'Eliminare la lista?',
  'Sil': 'Elimina',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Questo titolo sarà segnato come mai visto e rimosso dalle tue liste.',
  'Gelecek bölüm bugün': 'Prossimo episodio oggi',
  'Gelecek bölüm {} gün sonra': 'Prossimo episodio tra {} giorni',
  'Tema': 'Tema',
  'Sistem': 'Sistema',
  'Koyu': 'Scuro',
  'Açık': 'Chiaro',
  'İzleyenler': 'Spettatori',
  'Yorumunu yaz... (@ ile etiketle)':
      'Scrivi il tuo commento... (@ per taggare)',
  '@{} bir yorumda seni etiketledi': 'Menzione da @{} in un commento',
  'Mesajı sil': 'Elimina messaggio',
  'Mesaj silinemedi': 'Impossibile eliminare il messaggio',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Link non valido o pagina non trovata',
  "Keşfet'e dön": 'Torna a Esplora',
  'Düzenle': 'Modifica',
  'Mesajı düzenle': 'Modifica messaggio',
  'Yanıtlanıyor': 'In risposta',
  'düzenlendi': 'modificato',
  'Fotoğraf': 'Foto',
  'Video': 'Video',
  'İçerik': 'Contenuto',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': 'online {} min fa',
  'son görülme {} saat önce': 'online {} h fa',
  'son görülme {} gün önce': 'online {} g fa',
  'Yorumlar yüklenemedi': 'Impossibile caricare i commenti',
  'Favori': 'Preferito',
  'Listeye ekle': 'Aggiungi a lista',
  'İçerik paylaş': 'Condividi contenuto',
  'Kapat': 'Chiudi',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Tutto ciò che segni come visto si raccoglie qui.',
  'Henüz sohbetin yok': 'Ancora nessuna conversazione',
  'Bir profile girip mesaj gönderebilirsin.':
      'Apri un profilo e invia un messaggio.',
  'Listeyi sil': 'Elimina lista',
  'Puan kaydedilemedi': 'Impossibile salvare il voto',
  'Nerede İzlenir': 'Dove guardare',
  'Abonelik': 'Abbonamento',
  'Kirala': 'Noleggia',
  'Satın al': 'Acquista',
  'Devam et': 'Continua',
  'Şikayet et': 'Segnala',
  'Engelle': 'Blocca',
  'Engeli kaldır': 'Sblocca',
  'Kullanıcı engellendi': 'Utente bloccato',
  'Engel kaldırıldı': 'Blocco rimosso',
  'Şikayet sebebi': 'Motivo della segnalazione',
  'Spam veya yanıltıcı': 'Spam o fuorviante',
  'Taciz veya nefret söylemi': 'Molestie o incitamento all’odio',
  'Uygunsuz / cinsel içerik': 'Contenuto inappropriato / sessuale',
  'Şiddet veya tehlikeli içerik': 'Violenza o contenuti pericolosi',
  'Telif hakkı ihlali': 'Violazione del copyright',
  'Şikayetin alındı, teşekkürler':
      'La tua segnalazione è stata ricevuta, grazie',
  'Hesabımı Sil': 'Elimina il mio account',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Il tuo account e tutti i tuoi dati (cronologia, voti, commenti, liste, messaggi) verranno eliminati definitivamente. L’operazione è irreversibile.',
  'Şifreni gir': 'Inserisci la tua password',
  'Hesabımı kalıcı sil': 'Elimina definitivamente il mio account',
  'Sesli mesaj': 'Messaggio vocale',
  'Görüldü': 'Visualizzato',
  'Gönderi': 'Post',
  'Ses gönderilemedi': 'Impossibile inviare il messaggio vocale',
  'Kaydediliyor…': 'Registrazione…',
  'Ses oynatılamadı': 'Impossibile riprodurre l’audio',
  'Oynat': 'Riproduci',
  'Fragmanı oynat': 'Riproduci trailer',
  'Altyazıyı aç': 'Attiva i sottotitoli',
  'Altyazıyı kapat': 'Disattiva i sottotitoli',
  '10 saniye ileri': 'Avanti di 10 secondi',
  '10 saniye geri': 'Indietro di 10 secondi',
  'Duraklat': 'Metti in pausa',
  'Liste görünümü': 'Vista elenco',
  'Takvim görünümü': 'Vista calendario',
  'Önceki ay': 'Mese precedente',
  'Sonraki ay': 'Mese successivo',
  'Bu gün bölüm yok': 'Nessun episodio in questo giorno',
  'Gizlilik Politikası': 'Informativa sulla Privacy',
  'Son güncelleme: {}': 'Ultimo aggiornamento: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      "Questa informativa spiega quali dati vengono raccolti, come vengono usati e quali sono i tuoi diritti quando usi l'app dizi.jpg e il sito dizijpg.com.",
  'Topladığımız Veriler': 'Dati che raccogliamo',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Account: indirizzo e-mail, nome utente e password. Le password sono salvate con hash irreversibile; gli account ospite possono essere usati senza e-mail.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profilo: le informazioni che scegli di aggiungere, come avatar, immagine di copertina, bio e paese.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Utilizzo: la tua cronologia di visione, i voti, i commenti, le liste, le reazioni e i preferiti.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Messaggi: i tuoi messaggi di testo, immagine e vocali sono salvati sui nostri server. I messaggi non sono crittografati end-to-end; vengono esaminati solo in caso di segnalazione, a fini di moderazione.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Contenuti caricati: foto, GIF, video e registrazioni vocali che aggiungi al profilo, ai commenti e ai messaggi.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      "Dati tecnici: indirizzo IP, posizione approssimativa (paese/città), piattaforma del dispositivo, versione dell'app e log degli errori. Sono conservati per sicurezza e per la risoluzione dei problemi.",
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Statistiche d’uso: il tipo di dispositivo, il sistema operativo e il browser con cui si accede vengono sommati a contatori giornalieri complessivi come categorie generiche; l’identificativo del browser non viene conservato e questi numeri non sono collegabili a nessuna persona.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Notifiche: per le notifiche push conserviamo il token del tuo dispositivo e la tua lingua. Puoi disattivarle in qualsiasi momento dalle impostazioni del dispositivo.',
  'Verileri Nasıl Kullanırız': 'Come usiamo i tuoi dati',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Usiamo i tuoi dati solo per fornire il servizio, proteggere il tuo account, inviare notifiche, correggere errori e prevenire abusi. Non vendiamo i tuoi dati e non li condividiamo con nessuno a fini pubblicitari.',
  'Çerezler ve Yerel Depolama': 'Cookie e archiviazione locale',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      "Usiamo l'archiviazione locale solo per mantenerti connesso e ricordare preferenze come lingua e tema. Non ci sono cookie pubblicitari o di tracciamento.",
  'Üçüncü Taraf Hizmetler': 'Servizi di terze parti',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'I dati di serie e film provengono da TMDB, le informazioni sulle piattaforme di streaming da JustWatch. Le notifiche push sono recapitate tramite Google Firebase e il traffico del sito è protetto da Cloudflare. Questi servizi sono soggetti alle rispettive informative sulla privacy.',
  'Saklama ve Silme': 'Conservazione ed eliminazione',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'I tuoi dati sono conservati finché il tuo account esiste. Con "Elimina il mio account" nelle Impostazioni puoi eliminare l\'account in modo permanente; i tuoi dati vengono cancellati subito e le copie nei backup entro 14 giorni al massimo. I log degli errori vengono eliminati automaticamente dopo 30 giorni.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      "Puoi esportare i tuoi dati in formato ZIP dalle Impostazioni; l'archivio viene inviato al tuo indirizzo e-mail.",
  'Güvenlik': 'Sicurezza',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'I dati viaggiano su connessioni crittografate (HTTPS) e sono conservati su server ad accesso limitato.',
  'Çocukların Gizliliği': 'Privacy dei minori',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg non è rivolto ai minori di 13 anni.',
  'Hakların': 'I tuoi diritti',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'In base a KVKK e GDPR hai il diritto di accedere ai tuoi dati, correggerli, eliminarli e trasferirli. Per esercitarli scrivici: {}',
  'Değişiklikler': 'Modifiche',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Se questa informativa cambia, la nuova versione sarà pubblicata su questa pagina e la data sarà aggiornata.',
  'Kayıt olarak {} kabul etmiş olursun.': "Registrandoti accetti l'{}.",
  'Kullanıcılar': 'Utenti',
  'Fotoğrafı değiştir': 'Cambia foto',
  'Yeniden konumlandır': 'Riposiziona',
  'Bir şeyler ters gitti': 'Qualcosa è andato storto',
  'Sosyal Bağlantılar': 'Link social',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Sul tuo profilo vengono mostrati fino a 3 link.',
  'Platform seç': 'Scegli una piattaforma',
  'Kullanıcı adın': 'Il tuo nome utente',
  'Ekle': 'Aggiungi',
  'Kaldır': 'Rimuovi',
  'Kopyalandı: {}': 'Copiato: {}',
  'Geçersiz kullanıcı adı': 'Nome utente non valido',
  'Bağlantı ekle': 'Aggiungi link',
  'Spoiler olabilir — dokun ve gör': 'Può contenere spoiler — tocca per vedere',
  'Beğeni': 'Mi piace',
  'beğeni': 'mi piace',
  'Beğen': 'Mi piace',
  'Görüntülenme': 'Visualizzazioni',
  'görüntülenme': 'visualizzazioni',
  'Tam ekran': 'Schermo intero',
  'Arama başarısız': 'Ricerca non riuscita',
  'Sonuç bulunamadı': 'Nessun risultato',
  'Dizi ve Filmler': 'Serie e film',
  'Kişiler': 'Persone',
  'Ana Sayfa': 'Home',
  'Paylaş': 'Condividi',
  'Yanıtlar': 'Risposte',
  'Yaklaşan Bölümler': 'Prossimi episodi',
  'Yetişme Listesi': 'Lista recuperi',
  'Şunu mu demek istedin': 'Forse cercavi',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — tocca per vedere',
  'uyum': 'affinità',
  'Uyum': 'Affinità',
  '{} ortak dizi': '{} serie in comune',
  '{} ortak film': '{} film in comune',
  'Bildirim Tercihleri': 'Preferenze notifiche',
  'Beğeniler': 'Mi piace',
  'Yeni takipçiler': 'Nuovi follower',
  'Etiketlenmeler': 'Menzioni',
  'Yeniden izledim': 'Rivisto',
  '{}. kez izlendi': 'Visto {} volte',
  'Gönderi bulunamadı': 'Post non trovato',
  'Gözat': 'Sfoglia',
  'Diziler': 'Serie',
  'Filmler': 'Film',
  'Tümü': 'Tutti',
  'Farklı bir tür seç.': 'Prova un altro genere.',
  'Gizlilik': 'Privacy',
  'İzlediklerimi gizle': 'Nascondi ciò che guardo',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Le serie e i film che hai visto non appariranno sul tuo profilo',
  'Yorumlarımı gizle': 'Nascondi i miei commenti',
  'Profilinde yorumların görünmez':
      'I tuoi commenti non appariranno sul tuo profilo',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Puoi nascondere una singola serie o un film con il chip "Nascondi sul mio profilo" nella sua pagina.',
  'Geri Bildirim': 'Feedback',
  'Uygulama hakkında görüş ve önerini yaz...':
      "Scrivi la tua opinione e i tuoi suggerimenti sull'app...",
  'Teşekkürler! Geri bildirimin alındı.':
      'Grazie! Il tuo feedback è stato ricevuto.',
  'Profilimde gizle': 'Nascondi sul mio profilo',
  'Yorumları': 'Commenti',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Questo utente non ha ancora guardato nulla.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Questo utente preferisce tenere privati i propri commenti.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Dati: JustWatch',
  'Web Sitesi': 'Sito web',
  'Diğer uygulamalar': 'Altre app',
  'Bağlantıyı kopyala': 'Copia link',
  'Henüz kimseyi takip etmiyorsun.': 'Non segui ancora nessuno.',
  'Çevir': 'Traduci',
  'Çeviri şu an yapılamadı': 'Traduzione non disponibile al momento',
  'Bağlantı açılamadı': 'Impossibile aprire il link',
  'Orijinali göster': 'Mostra originale',
  'Çeviriyi göster': 'Mostra traduzione',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Nessun episodio con data di messa in onda annunciata questo mese. Le date escono di solito qualche settimana prima e appariranno qui.',
  'devamı': 'altro',
  'Google ile devam et': 'Continua con Google',
  'Google girişi başarısız': 'Accesso con Google non riuscito',
  'Veri tasarrufu': 'Risparmio dati',
  'Wi-Fi ağında veri tasarrufu': 'Risparmio dati su Wi-Fi',
  'Mobil veride veri tasarrufu': 'Risparmio dati su rete mobile',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Quando è attivo, le foto non vengono scaricate in anticipo: si carica solo il fotogramma che stai guardando.',
  'Çocuk güvenliği': 'Sicurezza dei minori',
  'Türk Filmleri': 'Film turchi',
  'En Yüksek Puanlı Filmler': 'Film con voto più alto',
  'En Yüksek Puanlı Diziler': 'Serie con voto più alto',
  'En Çok İzlenen Filmler': 'Film più visti',
  'Popüler Diziler': 'Serie popolari',
  'En Çok Kazanan Filmler': 'Film con maggiori incassi',
  'Kült Filmler': 'Film di culto',
  'Yeni Filmler': 'Nuovi film',
  'Yorum yap': 'Commenta',
  'Henüz yorum yok': 'Ancora nessun commento',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'I tuoi commenti su serie e film si raccolgono qui.',
  'GIF ekle': 'Aggiungi GIF',
  'İlk yorumu sen yaz': 'Scrivi tu il primo commento',
  'Video altyazıları': 'Sottotitoli video',
  'Videolarda altyazı göster': 'Mostra i sottotitoli sui video',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'La frase pronunciata nel video è scritta sullo schermo. Il testo è la traduzione: inglese in turco, turco in altre lingue.',
  'Güncelleme gerekli': 'Aggiornamento necessario',
  'Yeni sürüm var': 'Nuova versione disponibile',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Installa la nuova versione di dizi.jpg per continuare.',
  'Güncelle': 'Aggiorna',
  'Daha sonra': 'Più tardi',
  'Takvim güncelleniyor': 'Aggiornamento del calendario',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Impossibile aggiornare il calendario, viene mostrato il vecchio elenco',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Alcune serie non sono state caricate, la lista potrebbe essere incompleta',
  'Yenile': 'Aggiorna',
  'Devam etmek için giriş yap': 'Accedi per continuare',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Un account gratuito basta per votare, commentare e creare la tua libreria.',
  'Şimdi değil': 'Non ora',
  'Yorum yazmak için giriş yap': 'Accedi per scrivere un commento',
  'Kişilere göndermek için giriş yap': 'Accedi per inviare alle persone',
  'Beğenenler': 'Mi piace',
  'Henüz beğeni yok': 'Ancora nessun mi piace',
  'Bu gönderiyi ilk beğenen sen ol': 'Sii la prima persona a mettere mi piace',
  'Bu gönderiye yanıt': 'Risposta a questo post',
  'Spoiler içeren gönderi': 'Post con spoiler',
  'Görsel gönderi': 'Post con foto',
  'Bu yorumu profilimde gizle': 'Nascondi questo commento sul mio profilo',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Il commento resta nella pagina della serie e del film',
  'Bu yorumu sil': 'Elimina questo commento',
  'Yorum profilinde gizlendi': 'Commento nascosto sul tuo profilo',
  'Geri al': 'Annulla',
  'Yorum silinsin mi?': 'Eliminare il commento?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Questo commento verrà eliminato definitivamente ovunque. Non può essere annullato.',
  'Yorum silindi': 'Commento eliminato',
  'Yorum profilinde tekrar görünüyor':
      'Il commento è di nuovo visibile sul tuo profilo',
  'Gizlenen yorumun yok': 'Nessun commento nascosto',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'I commenti che nascondi tenendo premuto un post nella scheda Commenti del tuo profilo si accumulano qui.',
  'Gizlenen yorumlar': 'Commenti nascosti',
  'Gönderiye git': 'Vai al post',
  'Tekrar göster': 'Mostra di nuovo',
  'Yanıtlarımı gizle': 'Nascondi le mie risposte',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Le risposte che scrivi ai post di altri sono visibili solo a te',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Mostra di nuovo i commenti che hai nascosto sul tuo profilo',
  'Sıralama': 'Ordinamento',
  'Önerilen': 'Consigliato',
  'Kronolojik': 'Cronologico',
  'Gelen mesaj istekleri': 'Richieste di messaggio ricevute',
  'Mesaj isteğin yok': 'Nessuna richiesta di messaggio',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'I messaggi delle persone che non segui compaiono qui.',
  'Çevrimiçi durumumu gizle': 'Nascondi il mio stato online',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Gli altri non vedranno il tuo stato online né il tuo ultimo accesso nei messaggi',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Tra i nostri primi utenti. I suoi commenti hanno reso questa applicazione quella che è oggi.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Sei tra i nostri primi utenti. I tuoi commenti hanno reso questa applicazione quella che è oggi.',
  'İleri': 'Avanti',
  'Önceki': 'Precedente',
  'Sonraki': 'Successivo',
  'Seçilen dosya okunamadı': 'Impossibile leggere il file selezionato',
  'Video açılamadı': 'Impossibile aprire il video',
  'En fazla {} medya seçebilirsin': 'Puoi selezionare al massimo {} elementi',
  'Hiçbir medya yüklenemedi': 'Nessun elemento è stato caricato',
  'Seçimi kaldır': 'Rimuovi dalla selezione',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'In un commento puoi caricare in totale {} MB',
  '{} dosya okunamadı': '{} file non sono leggibili',
  '{} medya eklendi, {} yüklenemedi': '{} elementi aggiunti, {} non riusciti',
  'Kırp': 'Ritaglia',
  'Çiz': 'Disegna',
  'Metin': 'Testo',
  'Emoji': 'Emoji',
  'Yinele': 'Ripeti',
  'Daha fazla': 'Altro',
  'Hazırlanıyor…': 'Preparazione…',
  'Düzenlemeden çık?': 'Uscire dalla modifica?',
  'Yaptığın değişiklikler kaybolacak.': 'Le modifiche andranno perse.',
  'Çık': 'Esci',
  'Serbest çizim': 'Mano libera',
  'Ok': 'Freccia',
  'Dikdörtgen': 'Rettangolo',
  'Daire': 'Cerchio',
  'Bulanıklaştır': 'Sfoca',
  'Pikselleştir': 'Pixel',
  'Silgi': 'Gomma',
  'Çizgi kalınlığı': 'Spessore linea',
  'Saydamlık': 'Opacità',
  'Dolgu': 'Riempimento',
  'Renk': 'Colore',
  'Döndür': 'Ruota',
  'Yansıt': 'Capovolgi',
  'Oran': 'Proporzioni',
  'Sıfırla': 'Reimposta',
  'Serbest': 'Libero',
  'Metin yaz...': 'Scrivi un testo...',
  'Hizala': 'Allinea',
  'Arka plan': 'Sfondo',
  'Emoji ara...': 'Cerca emoji...',
  'Son kullanılanlar': 'Recenti',
  'İfadeler ve insanlar': 'Faccine e persone',
  'Hayvanlar ve doğa': 'Animali e natura',
  'Yiyecek ve içecek': 'Cibo e bevande',
  'Etkinlikler': 'Attività',
  'Seyahat ve yerler': 'Viaggi e luoghi',
  'Nesneler': 'Oggetti',
  'Semboller': 'Simboli',
  'Bayraklar': 'Bandiere',
  'Görseli düzenle': 'Modifica immagine',
  'Düzenlendi': 'Modificata',
  'Düzenlenemedi': 'Modifica non riuscita',
  'Düzenlenen görsel çok büyük': 'Immagine modificata troppo grande',
  'Videoyu düzenle': 'Modifica video',
  'Sesi kapat': 'Disattiva audio',
  'Sesi aç': 'Attiva audio',
  'İptal ediliyor…': 'Annullamento…',
  'Bu biraz sürebilir': 'Potrebbe richiedere un po di tempo',
  'Video çok büyük': 'Il video e troppo grande',
  'Video hazırlanamadı': 'Impossibile preparare il video',
  'Başlangıç': 'Inizio',
  'Bitiş': 'Fine',
  'En çok {} saniye seçebilirsin': 'Puoi selezionare al massimo {} secondi',
  'Dosya en fazla {} MB olabilir': 'Il file puo essere al massimo di {} MB',
  'Medya ekle': 'Aggiungi contenuti',
  'Seçili medya kalmadı': 'Nessun contenuto selezionato',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Scegli una foto o un video da aggiungere al tuo commento.',
  'Medya seç': 'Seleziona contenuti',
  'Daha fazla ekle': 'Aggiungi altri',
  'Medya seçilemedi': 'Impossibile selezionare i contenuti',
  'Favori oyuncular': 'Attori preferiti',
  'Henüz favori oyuncun yok': 'Nessun attore preferito ancora',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Apri la pagina di un attore e tocca il cuore in alto a destra per aggiungerlo qui.',
  '{} yapımdan {} tanesini izledin': 'Hai visto {} di {} titoli',
  'izledin': 'visti',
  'İzlemedin': 'Non visto',
  'Yapım bulunamadı': 'Nessun titolo trovato',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Questa persona non ha serie o film da elencare.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'La tua cronologia e legata al tuo account; questa lista e solo tua.',
  'Hesabın kalıcı olarak askıya alındı':
      'Il tuo account è stato sospeso in modo permanente',
  'Hesabın geçici olarak askıya alındı':
      'Il tuo account è stato sospeso temporaneamente',
  'Hesabın askıya alındı': 'Il tuo account è sospeso',
  'Sebep': 'Motivo',
  'Kalan süre': 'Tempo rimanente',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Il tuo account si riattiva da solo allo scadere del tempo',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'In questo periodo puoi continuare a leggere, ma non puoi pubblicare, commentare o inviare messaggi.',
  'Anladım': 'Ho capito',
  'Ayrıntı': 'Dettagli',
  '{} dakika': '{} minuti',
  'birkaç saniye': 'pochi secondi',
  'Karara itiraz et': 'Contesta questa decisione',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Spiega perché questa sanzione dovrebbe essere revocata',
  'İtirazını gönder': 'Invia il tuo ricorso',
  'İtirazın incelemede': 'Il tuo ricorso è in esame',
  'İtirazın reddedildi': 'Il tuo ricorso è stato respinto',
  'İtirazın alındı, inceleniyor':
      'Abbiamo ricevuto il tuo ricorso ed è in esame',
  'İtiraz en az 10 karakter olmalı':
      'Il ricorso deve contenere almeno 10 caratteri',
  'Yükleniyor...': 'Caricamento...',
  'Bu bölüme puan ver': 'Vota questo episodio',
  '{} kişi puanladı': '{} persone hanno votato',
  'Bölüm izlendi olarak işaretlendi': 'Episodio segnato come visto',
  'Sesli ara': 'Chiamata vocale',
  'Görüntülü ara': 'Videochiamata',
  'Çalıyor...': 'Sta squillando...',
  'Bağlanıyor...': 'Connessione...',
  'Cevapla': 'Rispondi',
  'Reddet': 'Rifiuta',
  'Sessize al': 'Disattiva microfono',
  'Hoparlör': 'Altoparlante',
  'Kamerayı kapat': 'Spegni fotocamera',
  'Kamerayı çevir': 'Cambia fotocamera',
  'Cevap yok': 'Nessuna risposta',
  'Arama reddedildi': 'Chiamata rifiutata',
  'Meşgul': 'Occupato',
  'Bağlanılamadı': 'Impossibile connettersi',
  'Arama iptal edildi': 'Chiamata annullata',
  'Arama geçmişi': 'Cronologia chiamate',
  'Gelen arama': 'Chiamata in arrivo',
  'Giden arama': 'Chiamata in uscita',
  'Cevapsız arama': 'Chiamata persa',
  'Arama şu anda kullanılamıyor': 'Le chiamate non sono disponibili al momento',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Le videochiamate sono disattivate, puoi fare una chiamata vocale',
  'Bu kullanıcıyı arayamazsın': 'Non puoi chiamare questo utente',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Dovete seguirvi a vicenda per chiamarvi',
  'Bu kullanıcı şu anda aranamıyor':
      'Questo utente non può essere chiamato ora',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Troppe chiamate perse. Riprova tra {}',
  'Zaten bir aramadasın': 'Sei già in una chiamata',
  'Arama için mikrofon izni gerekiyor':
      'Per chiamare serve il permesso del microfono',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'Per le videochiamate servono i permessi di fotocamera e microfono',
  'Arama başlatılamadı': 'Impossibile avviare la chiamata',
  'Kullanıcı bulunamadı': 'Utente non trovato',
  'Kendini arayamazsın': 'Non puoi chiamare te stesso',
  'Arama artık geçerli değil': 'Questa chiamata non è più valida',
  'Bu aramanın tarafı değilsin': 'Non fai parte di questa chiamata',
  'Arama bulunamadı': 'Chiamata non trovata',
  'Çok fazla istek, biraz bekle': 'Troppe richieste, attendi un momento',
  'Bağlantı koptu': 'Connessione persa',
  'Arama süre sınırına ulaştı': 'La chiamata ha raggiunto il limite di tempo',
  'Arama en fazla 4 saat sürebilir': 'Una chiamata può durare al massimo 4 ore',
  'Arama sona erdi': 'La chiamata è terminata',
  'Sesli arama': 'Chiamata vocale',
  'Görüntülü arama': 'Videochiamata',
  'Gelen aramalar': 'Chiamate in arrivo',
  'Sesli ve görüntülü arama bildirimleri':
      'Notifiche di chiamate vocali e video',
  '{} sa': '{} h',
  'Sesli ve Görüntülü Aramalar': 'Chiamate vocali e video',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Il contenuto delle chiamate non viene mai registrato. Audio e video viaggiano cifrati end-to-end (DTLS-SRTP) tra i dispositivi; i nostri server non possono decifrare, ascoltare o conservare questo traffico.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Vengono conservati solo i metadati della chiamata: con chi, in quale direzione, quando e quanto è durata. Questi dati vengono eliminati automaticamente dopo 90 giorni.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Se non è possibile stabilire una connessione diretta, audio e video passano cifrati attraverso un server di inoltro (TURN). Nemmeno quel server può decifrare o registrare il contenuto.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Il microfono viene usato solo durante una chiamata vocale o video, la fotocamera solo durante una videochiamata. Entrambi vengono spenti al termine della chiamata.',
  'Takip ettiğin {} kişi izledi': "{} persone che segui l'hanno visto",
  'Yorum yaz...': 'Scrivi un commento...',
  'Sıradaki bölüm': 'Episodio successivo',
  'Doğrulanmış testçi': 'Tester verificato',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Notifiche di follow, mi piace, risposte, messaggi e menzioni',
  'Sen': 'Tu',
  'Aradığınız kişide sesli arama devre dışı':
      'Le chiamate vocali sono disattivate per questa persona',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Le videochiamate sono disattivate per questa persona',
  'Sesli aramalara izin ver': 'Consenti chiamate vocali',
  'Görüntülü aramalara izin ver': 'Consenti videochiamate',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Se disattivato, nessuno può chiamarti in voce; chi chiama vede un avviso',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Se disattivato, nessuno può videochiamarti; chi chiama vede un avviso',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Le chiamate vocali sono disattivate. Puoi attivarle in Impostazioni > Privacy.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Le videochiamate sono disattivate. Puoi attivarle in Impostazioni > Privacy.',
  'Sesli ve görüntülü arama': 'Chiamate vocali e video',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Gli account ospite non possono chiamare. Crea un account per usarlo.',
  'Misafir hesaplar aranamaz': 'Non puoi chiamare un account ospite',
  'Puan dağılımı': 'Distribuzione dei voti',
  '{} yıldız': '{} stelle',
  'Yakında gelecek': 'Prossimamente',
  '{} {} yayınlandı': '{} {} è disponibile',
  'Yeni bölüm yayınlandı': 'Nuovo episodio disponibile',
  'Yeni bölümler': 'Nuovi episodi',
  'Geri': 'Indietro',
  'Karşılamayı kapat': "Chiudi l'introduzione",
  'Adım {} / {}': 'Passo {} / {}',
  'Hadi başlayalım': 'Iniziamo',
  'Kaydet ve devam': 'Salva e continua',
  '{} tanesini ekle': 'Aggiungi {}',
  'Şimdilik geç': 'Non ora',
  'Doğum tarihin ne zaman?': 'Qual è la tua data di nascita?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Te lo chiediamo per mostrarti contenuti adatti alla tua età e per farti gli auguri di compleanno.',
  'Gün': 'Giorno',
  'Ay': 'Mese',
  'Yıl': 'Anno',
  'Doğum yılımı paylaşmak istemiyorum':
      'Non voglio condividere il mio anno di nascita',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      "La tua data di nascita non viene mostrata pubblicamente sul profilo. Serve solo per i contenuti adatti all'età e per gli auguri di compleanno.",
  'Ocak': 'gennaio',
  'Şubat': 'febbraio',
  'Mart': 'marzo',
  'Nisan': 'aprile',
  'Mayıs': 'maggio',
  'Haziran': 'giugno',
  'Temmuz': 'luglio',
  'Ağustos': 'agosto',
  'Eylül': 'settembre',
  'Ekim': 'ottobre',
  'Kasım': 'novembre',
  'Aralık': 'dicembre',
  'Verilerini yanında getir': 'Porta con te i tuoi dati',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      "Se tieni traccia di ciò che guardi in un'altra app, puoi portare tutto qui. Non devi ricominciare da zero.",
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Scegli il file ZIP che hai esportato: le tue visualizzazioni, i tuoi voti e le tue liste verranno importati.',
  'Aktarılıyor...': 'Importazione in corso...',
  'ZIP dosyası seç': 'Scegli file ZIP',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      "Non c'è fretta: puoi farlo anche più tardi da Impostazioni > I miei dati.",
  'Hangi filmleri izledin?': 'Quali film hai visto?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Ecco i più visti. Tocca quelli che hai visto e li aggiungiamo alla tua cronologia.',
  'SERİ FİLMLER': 'SAGHE',
  'Serilerden {} film eklendi': '{} film aggiunti dalle saghe',
  'Film listesi yüklenemedi': 'Impossibile caricare la lista dei film',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Puoi saltare questo passo e aggiungere ciò che vuoi più tardi.',
  '{} film izlediklerine eklendi': '{} film aggiunti alla tua cronologia',
  'Film serileri': 'Saghe di film',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      "Se hai visto una saga dall'inizio alla fine, aggiungila con un solo tocco.",
  'Seri bulunamadı': 'Nessuna saga trovata',
  'Daha sonra tekrar deneyebilirsin.': 'Puoi riprovare più tardi.',
  '{} film': '{} film',
  'Eklendi': 'Aggiunto',
  'Tümünü izledim': 'Li ho visti tutti',
  'Peki ya diziler?': 'E le serie TV?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Segna ciò che hai visto: man mano che scegli, ti proponiamo serie simili.',
  'Dizi listesi yüklenemedi': 'Impossibile caricare la lista delle serie',
  'Seçtiklerine benzeyenler': 'Simili alle tue scelte',
  'Her şey hazır': 'Tutto pronto',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      "Dai un'occhiata veloce a ciò che puoi fare su dizi.jpg.",
  'Profilini tamamla': 'Completa il tuo profilo',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'Dalle Impostazioni puoi aggiungere una bio, una foto profilo e una copertina.',
  'Takvimin seni bekliyor': 'Il tuo calendario ti aspetta',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'I nuovi episodi delle serie che guardi finiscono nel calendario e te lo diciamo con una notifica.',
  'Puan ver, yorum yaz': 'Vota e commenta',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Vota episodio per episodio, commenta dietro un velo spoiler e crea liste.',
  'Verilerin sende kalır': 'I tuoi dati restano tuoi',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'I tuoi dati restano collegati solo al tuo account e non vengono venduti. Dalle Impostazioni puoi scaricarli tutti oppure eliminare del tutto il tuo account.',
  'Engellenen kullanıcılar': 'Persone bloccate',
  'Engellediğin kişileri gör, engeli kaldır':
      'Guarda chi hai bloccato e togli il blocco',
  'Engellediğin kimse yok': 'Non hai bloccato nessuno',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Puoi bloccare una persona dal menu a tre puntini sul suo profilo.',
  '@{} engellensin mi?': 'Bloccare @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      "Nessuna delle due parti vedrà i post, i commenti o il profilo dell'altra; non sarà possibile nemmeno inviare messaggi o chiamare. Se esiste un legame di follow, viene interrotto e non torna nemmeno se togli il blocco.",
  'Bu kullanıcıyı engelledin': 'Hai bloccato questa persona',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Non vedi i post, i commenti e i messaggi di questa persona; nemmeno lei vede i tuoi.',
  '{} yeni bir yapımda: {}': '{} è in una nuova produzione: {}',
  'Favori kişinden yeni yapım': 'Nuova produzione di una persona preferita',
  '{} için bildirimler': 'Notifiche per {}',
  'Tüm bildirimler': 'Tutte le notifiche',
  'Uygulamada ve telefonda': "Nell'app e sul telefono",
  'Yalnız uygulama içi': "Solo nell'app",
  'Telefon bildirimi gönderilmez': 'Nessuna notifica sul telefono',
  'Kapalı': 'Disattivato',
  'Bu kişi için bildirim yok': 'Nessuna notifica per questa persona',
  'Favori kişilerin yeni yapımları': 'Nuove produzioni delle persone preferite',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Se disattivato, nessuno può chiamarti in voce; chi chiama vede l\'avviso "disattivate"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Se disattivato, nessuno può videochiamarti; chi chiama vede l\'avviso "disattivate"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'La mia attività',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'I tuoi mi piace, commenti e visioni in un unico flusso',
  'Henüz hareketin yok': 'Ancora nessuna attività',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Tutto ciò che ti piace, commenti e guardi si raccoglie qui.',
  'Bu süzgeçte hareket yok': 'Nessuna attività in questo filtro',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Scegli un altro tipo o torna a "Tutti".',
  'Hepsi': 'Tutti',
  'Puan': 'Voto',
  'Tepki': 'Reazione',
  'İzleme': 'Visione',
  'Durum': 'Stato',
  'Liste': 'Lista',
  'Yorum yaptın': 'Hai commentato',
  'Yorumu beğendin': 'Ti è piaciuto un commento',
  '{} puan verdin': 'Hai votato {}',
  'Tepki verdin': 'Hai reagito',
  'Listene ekledin': 'Hai aggiunto a una lista',
  'Takip etmeye başladın': 'Hai iniziato a seguire',
  '"İzleyeceğim" işaretledin': 'Segnato come "Da vedere"',
  '"İzliyorum" işaretledin': 'Segnato come "Sto guardando"',
  '"Bitirdim" işaretledin': 'Segnato come "Finita"',
  '"Bıraktım" işaretledin': 'Segnato come "Abbandonata"',
  'Silinmiş içerik': 'Contenuto eliminato',
  'şimdi': 'ora',
  '{} g': '{} g',
  '{} y': '{} a',
  'İstatistiklerim': 'Le mie statistiche',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Visualizzazioni e mi piace dei tuoi post',
  'Henüz gönderin yok': 'Non hai ancora post',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Quando commenti una serie o un film, le tue visualizzazioni e i mi piace iniziano ad accumularsi qui.',
  'Tüm zamanlar': 'Da sempre',
  'Son {} gün': 'Ultimi {} giorni',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'La cronologia delle visualizzazioni non ha ancora iniziato ad accumularsi; i dati del primo giorno appaiono domani.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'La cronologia delle visualizzazioni si accumula dal {} ({} giorni di dati), quindi il conteggio di {} giorni è ancora incompleto.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'La cronologia dei mi piace è registrata dal {}.',
  'Bu dönemde gösterilecek gönderi yok.':
      'Nessun post da mostrare per questo periodo.',
  'eksik veri': 'dati incompleti',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Le serie e i film che hai visto, i tuoi contatori di visione, il tempo di visione e la scheda di affinità non saranno visibili agli altri sul tuo profilo',
  'Takipçi listemi gizle': 'Nascondi la mia lista di follower',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Gli altri non possono vedere chi ti segue; il numero dei tuoi follower resta visibile',
  'Takip ettiklerimi gizle': 'Nascondi chi seguo',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Gli altri non possono vedere chi segui; il numero dei tuoi seguiti resta visibile',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Questo utente preferisce tenere privati i propri follower.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Questo utente preferisce tenere privati i profili che segue.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Statistiche del post',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Puoi vedere le statistiche solo dei tuoi post.',
  'Erişim': 'Copertura',
  'Görüntüleyen': 'Visualizzatori',
  'Kaç farklı kişi gördü (son {} gün)':
      'Quante persone diverse l’hanno visto (ultimi {} giorni)',
  'Paylaşım': 'Condivisioni',
  'Bu gönderiden sonra': 'Dopo questo post',
  'Profil ziyareti': 'Visite al profilo',
  'Yeni takip': 'Nuovi follower',
  'İçeriğe tıklama': 'Tocchi sul contenuto',
  'Spoiler perdesini açan': 'Hanno rivelato lo spoiler',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Condivisioni, visite al profilo, follower, tocchi sul contenuto, ripartizione per origine e misure sullo spoiler si accumulano dal {}; quanto precede non è stato misurato.',
  'Zamana yayılmış görüntülenme': 'Visualizzazioni nel tempo',
  'Görüntülenme nereden geldi': 'Da dove arrivano le visualizzazioni',
  'Kimler gördü': 'Chi l’ha visto',
  'Günlük veri henüz birikmeye başlamadı.':
      'I dati giornalieri non hanno ancora iniziato ad accumularsi.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'Il grafico richiede almeno due giorni di dati. I dati si accumulano dal {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'La maggior parte delle visualizzazioni è arrivata il {}° giorno dopo la pubblicazione: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Le visualizzazioni giornaliere si accumulano dal {}; quanto precede non è stato misurato.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'La ripartizione per origine ha appena iniziato a essere misurata; questo post non ha ancora ricevuto una visualizzazione etichettata.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'La ripartizione tra follower e scoperta ha appena iniziato a essere misurata; non ci sono ancora dati.',
  'Takip edenler': 'Follower',
  'Keşiften gelenler': 'Da Scopri',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Pagina serie/film',
  'Paylaşılan bağlantı': 'Link condiviso',
  'yeni ölçülüyor': 'misura recente',
  'Kendi ortalamanla aynı düzeyde': 'In linea con la tua media',
  'Kendi ortalamanın %{} üstünde': '{}% sopra la tua media',
  'Kendi ortalamanın %{} altında': '{}% sotto la tua media',
  'Etkileşim oranı': 'Tasso di interazione',
  '(beğeni + yorum) ÷ görüntülenme': '(mi piace + commenti) ÷ visualizzazioni',
  'Toplam görüntülenme': 'Visualizzazioni totali',
  '{} ile {} arasında toplam {} görüntülenme':
      'Tra il {} e il {}: {} visualizzazioni in totale',
  'İstatistikleri gör': 'Vedi statistiche',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'Per le statistiche mostrate a chi ha pubblicato, vengono conservati come contatori aggregati: quante volte e da quale superficie (feed, profilo, feed a schermo intero, pagina serie/film, link condiviso) il post è stato visualizzato, se chi lo ha visto seguiva in quel momento chi ha pubblicato, il passaggio dal post al profilo o al contenuto, i follow nati dal post, le condivisioni e l’apertura del velo dello spoiler. Questi contatori non contengono identità utente, indirizzo IP né marca temporale; non è possibile sapere chi ha fatto cosa.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'Per poter contare quante persone diverse hanno visto un post, per ogni persona che lo ha visto viene conservata per 90 giorni una sintesi con chiave non reversibile (una riduzione crittografica derivata dall’identità utente o dall’indirizzo IP). A chi ha pubblicato viene mostrato solo il numero; l’identità di chi ha visto il post non viene condivisa in nessun caso.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'Spostare in «Da vedere»?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'Un titolo o è da vedere o è visto. Se continui, i tuoi {} segni di visione su questa serie verranno eliminati.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'Un titolo o è da vedere o è visto. Se continui, il tuo segno «Visto» su questo film verrà rimosso.',
  'Sil ve taşı': 'Elimina e sposta',
  'Yapım Ekibi': 'Troupe',
  'Yaratıcı': 'Ideazione',
  'Yönetmen': 'Regia',
  'Senaryo': 'Sceneggiatura',
  'Yapımcı': 'Produzione',
  'Yapım Firmaları': 'Case di produzione',
  'Yapım Firması': 'Casa di produzione',
  'Firma bulunamadı': 'Casa di produzione non trovata',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'Questa casa di produzione non ha titoli di questo tipo.',
  'Doğum günün kutlu olsun!': 'Buon compleanno!',
  'İyi ki doğdun, iyi ki buradasın.':
      'Che bello che tu esista, che bello averti qui.',
  'Bugün {} yaşına girdin': 'Oggi compi {} anni',
  'Teşekkürler': 'Grazie',
  'İki Adımlı Doğrulama': 'Verifica in due passaggi',
  'Girişte e-postana kod gönderilir': "All'accesso ricevi un codice via e-mail",
  'Kod {} adresine gönderildi': 'Codice inviato a {}',
  '6 haneli kod': 'Codice a 6 cifre',
  'Doğrula': 'Verifica',
  'Yeniden gönder': 'Invia di nuovo',
  'Vazgeç': 'Annulla',
  'Yeni kod gönderildi': 'Nuovo codice inviato',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      "Con l'accesso tramite Google il codice non viene richiesto; Google esegue la propria verifica.",
  'Kapatmak için de kod gerekir.': 'Anche per disattivarla serve un codice.',
  'E-postana erişemezsen hesabına giremezsin.':
      "Se perdi l'accesso alla tua e-mail, non potrai più accedere all'account.",
  'İki adımlı doğrulama açıldı': 'Verifica in due passaggi attiva',
  'İki adımlı doğrulama kapatıldı': 'Verifica in due passaggi disattivata',

  // --- md.24 video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': 'Quanto viene visto il video',
  'Videoyu başlatanlar': 'Ha avviato il video',
  'videonun %{} noktasına ulaştı': 'ha raggiunto il {}% del video',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'Metà di chi guarda ha visto almeno il {}% del video.',
  'Sonuna kadar izleyen: %{}': 'Visto fino alla fine: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'La curva richiede almeno {} visualizzazioni; ora ce ne sono {}.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'La curva si basa su {} visualizzazioni e non dipende dal periodo selezionato.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'Il tempo di visualizzazione è misurato dal {}; le visualizzazioni precedenti non rientrano in questo numero.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} visualizzazioni. Il {}% ha raggiunto metà video, il {}% la fine.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'Livello {}',
  'Sonraki seviyeye {} puan kaldı': '{} punti al livello successivo',
  'Gönderilerin': 'I tuoi post',
  '{} gönderi': '{} post',
  '{} gönderi · {} görüntülenme': '{} post · {} visualizzazioni',
  'önceki {} güne göre': 'rispetto ai {} giorni precedenti',
  'önceki {} güne göre %{} arttı':
      'rispetto ai {} giorni precedenti: aumento del {}%',
  'önceki {} güne göre %{} azaldı':
      'rispetto ai {} giorni precedenti: calo del {}%',
  'önceki {} güne göre değişmedi': 'invariato rispetto ai {} giorni precedenti',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'Visualizzazioni giornaliere: minimo {}, massimo {}',
  'Etkileşim oranı henüz ölçülemedi':
      'Tasso di interazione non ancora misurabile',
  'Oranlar': 'Tassi',
  'Beğenme oranı': 'Tasso di mi piace',
  'Yorum oranı': 'Tasso di commenti',
  'Paylaşma oranı': 'Tasso di condivisioni',
  'İçeriğe gitme oranı': 'Tasso tocchi contenuto',
  'Profile gitme oranı': 'Tasso visite al profilo',
  'Ziyaretten takibe dönüşüm': 'Da visita a follower',
  'beğeni ÷ görüntülenme': 'mi piace ÷ visualizzazioni',
  'yorum ÷ görüntülenme': 'commenti ÷ visualizzazioni',
  'paylaşım ÷ görüntülenme': 'condivisioni ÷ visualizzazioni',
  'içeriğe tıklama ÷ görüntülenme': 'tocchi sul contenuto ÷ visualizzazioni',
  'profil ziyareti ÷ görüntülenme': 'visite al profilo ÷ visualizzazioni',
  'yeni takip ÷ profil ziyareti': 'nuovi follower ÷ visite al profilo',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'Per i tassi servono almeno {} visualizzazioni; al momento ce ne sono {}.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'I tassi derivano dai totali di sempre del post; la selezione dei giorni qui sotto non li cambia.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'Questi numeri sono i totali di sempre del post (tranne i riquadri con una nota propria); la selezione dei giorni qui sotto cambia solo il grafico.',
  'Ortalama izlenme: videonun %{} kadarı': 'Visione media: il {}% del video',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'La media dei 20 segmenti della curva di visione.',
  'Dizi, film, kişi veya şirket ara...':
      'Cerca serie, film, persone o società...',
  'Şirketler': 'Società',
  'Senarist': 'Sceneggiatore',
  'Bölüm puanları': 'Voti degli episodi',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'Impossibile caricare i voti',
  'Giriş gerekli': 'Accesso richiesto',
  'Geçersiz oturum': 'Sessione non valida',
  'Oturum sonlandı, tekrar giriş yap': 'Sessione terminata, accedi di nuovo',
  'Çok fazla istek; biraz sonra tekrar dene':
      'Troppe richieste; riprova tra poco',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'Al momento non c’è spazio sul server, riprova tra poco',
  'Devam eden yapımlar ({})': 'Produzioni in corso ({})',
  'Diziler ({})': 'Serie ({})',
  'Filmler ({})': 'Film ({})',
  'Tüm yapımlar': 'Tutte le produzioni',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'Il tuo spazio multimediale è pieno; elimina i caricamenti vecchi per liberare spazio',
  'E-posta/kullanıcı adı veya şifre hatalı': 'Email/utente o password errati',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'Questa email o questo nome è già registrato',
  'Google doğrulaması başarısız': 'Verifica Google non riuscita',
  'Kod geçersiz veya süresi dolmuş': 'Codice non valido o scaduto',
  'Bu kullanıcıyla mesajlaşamazsın': 'Non puoi scrivere a questo utente',
  'Kendini takip edemezsin': 'Non puoi seguirti da solo',
  'Bu kullanıcıyı takip edemezsin': 'Non puoi seguire questo utente',
  'Kendini engelleyemezsin': 'Non puoi bloccarti da solo',
  'Yorum 1-1000 karakter olmalı': 'Il commento deve essere di 1–1000 caratteri',
  'Boş mesaj gönderilemez': 'Non puoi inviare un messaggio vuoto',
  'Yorum bulunamadı': 'Commento non trovato',
  'Şifre hatalı': 'Password errata',
  'Şifre en az 6 karakter olmalı': 'La password deve avere almeno 6 caratteri',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'Puoi caricare solo GIF, PNG, JPEG o WebP',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'Tipi supportati: GIF, PNG, JPEG, WebP, MP4, WebM, audio',
  'Geçerli bir ZIP dosyası değil': 'Non è uno ZIP valido',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'Per ricevere i dati via email, collega prima un indirizzo',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'Hai già dei segni di visione. Per «Lo guarderò» vanno cancellati prima.',
  'Arama şu anda kapalı': 'Le chiamate sono disattivate ora',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'Gli account ospite non possono attivare le chiamate; crea un account',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'Il server si sta riavviando, riprova tra poco',
  'Puan 1-10 arası olmalı': 'Il voto deve essere tra 1 e 10',
  'En fazla 10 medya eklenebilir': 'Puoi aggiungere al massimo 10 file',
  'Bu cihazdan yeni hesap açılamıyor':
      'Impossibile creare un account da questo dispositivo',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'Servono email valida, nome utente e password di almeno 6 caratteri',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'Servono email valida e password di almeno 6 caratteri',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'Il nome deve essere 3–20 caratteri; minuscole, cifre, punti, trattini e underscore (non agli estremi)',
  'Bu hesap zaten bağlı': 'Questo account è già collegato',
  'Hesap oluşturulamadı': 'Impossibile creare l\'account',
  'Misafir hesabı oluşturulamadı': 'Impossibile creare un account ospite',
  'Hesap bulunamadı': 'Account non trovato',
  'Bu hesapta e-posta yok': 'Questo account non ha un\'email',
  'İki adımlı doğrulama zaten bu durumda':
      'La verifica in due passaggi è già in questo stato',
  'Kod yanlış': 'Codice errato',
  'Kodun süresi doldu': 'Codice scaduto',
  'Kullanıcının e-postası yok (misafir hesap)':
      'Questo utente non ha email (account ospite)',
  'Bio en fazla 300 karakter olabilir':
      'La bio può avere al massimo 300 caratteri',
  'Geçersiz ülke': 'Paese non valido',
  'Geçersiz sosyal bağlantı': 'Link social non valido',
  'Geçersiz doğum tarihi': 'Data di nascita non valida',
  'Liste adı gerekli': 'Il nome dell\'elenco è obbligatorio',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'Il nome può avere 60 caratteri, la descrizione 300',
  'Liste bulunamadı': 'Elenco non trovato',
  'Değiştirilecek tercih yok': 'Niente da aggiornare',
  'İnceleme en fazla 2000 karakter olabilir':
      'La recensione può avere al massimo 2000 caratteri',
  'Önce içeriği "bitirdim" olarak işaretle':
      'Segna prima il titolo come finito',
  'Önce kişiyi favorile': 'Metti prima la persona tra i preferiti',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'Per un commento all\'episodio servono sia stagione sia episodio',
  'Yanıtlanan yorum bulunamadı': 'Commento a cui rispondi non trovato',
  'Geri bildirim 3-2000 karakter olmalı':
      'Il feedback deve essere 3–2000 caratteri',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'Titolo e testo sono obbligatori (almeno 2 caratteri)',
  'Kendine mesaj gönderemezsin': 'Non puoi messaggiare te stesso',
  'Mesaj en fazla 2000 karakter olabilir':
      'Il messaggio può avere al massimo 2000 caratteri',
  'Mesaj 1-2000 karakter olmalı': 'Il messaggio deve essere 1–2000 caratteri',
  'Mesaj bulunamadı': 'Messaggio non trovato',
  'Mesaj bulunamadı veya düzenlenemez':
      'Messaggio non trovato o non modificabile',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'Puoi segnalare solo un messaggio inviato a te',
  'Sebep gerekli': 'Il motivo è obbligatorio',
  'İtiraz edilecek aktif bir ceza yok':
      'Non c\'è una sanzione attiva da contestare',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'Hai già un ricorso in attesa di esame',
  'Bu ceza için itirazın zaten incelendi':
      'Il ricorso per questa sanzione è già stato esaminato',
  'Medya bağlantısının süresi dolmuş': 'Link media scaduto',
  'Bu medya için imzalı bağlantı gerekli':
      'Per questo media serve un link firmato',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'Il servizio chiamate si sta riavviando; riprova tra poco',
  'Puan göstergesi': 'Legenda dei voti',
  'İzleme İstatistiklerim': 'Le mie statistiche di visione',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'Appena segni un episodio o un film come visto, le tue statistiche iniziano ad accumularsi qui.',
  '{} sa {} dk': '{} h {} min',
  'Yaklaşık ekran süresi': 'Tempo di visione approssimativo',
  'İzleme serisi': 'Serie di visione',
  'Şu anki seri': 'Serie attuale',
  'En uzun seri': 'Serie più lunga',
  'Haftanın günleri': 'Giorni della settimana',
  'En çok izlediklerin': 'I più visti',
  'Bu dönemde izleme yok': 'Nessuna visione in questo periodo',
  'Paz': 'Dom',
  'Pzt': 'Lun',
  'Sal': 'Mar',
  'Çar': 'Mer',
  'Per': 'Gio',
  'Cum': 'Ven',
  'Cmt': 'Sab',
  '{} bölüm': '{} episodi',
  '{} bölüm~tekil': '{} episodio',
  '{} kez': '{} volte',
  '{} kez~tekil': '{} volta',
  'Son {} gün · günlük': 'Ultimi {} giorni · giornaliero',
  'Son {} gün · haftalık': 'Ultimi {} giorni · settimanale',
  'Ekran süren, serin ve en çok izlediklerin':
      'Il tuo tempo di visione, la serie e i più visti',
  'Daralt': 'Comprimi',
  'Listeyi düzenle': 'Modifica elenco',
  'Bitti': 'Fatto',
  'Sırala': 'Riordina',
  'Herkese göster': 'Mostra a tutti',
  'Başkalarından gizle': 'Nascondi agli altri',
  'Listeden kaldır': 'Rimuovi dall’elenco',
  'Listeden kaldırılsın mı?': 'Rimuovere dall’elenco?',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'Questo titolo verrà tolto dall’elenco. Se vuoi solo nasconderlo, usa l’icona a forma di occhio.',
  'Sıralama kaydedilemedi': 'Impossibile salvare l’ordine',
  'Değişiklik kaydedilemedi': 'Impossibile salvare la modifica',
  'Kaldırılamadı': 'Impossibile rimuovere',
  'Popülerlik': 'Popolarità',
  'TMDB puanı': 'Voto TMDB',
  'Yapım yılı': 'Anno di produzione',
  'dizi.jpg puanı': 'Voto dizi.jpg',
  'İzlenme': 'Visualizzazioni',
  'Yorum sayısı': 'Numero di commenti',
  'Tüm raflara uygulanır': 'Si applica a tutti gli scaffali',
  'En popüler {} yapım arasında sıralandı':
      'Ordinato tra i {} titoli più popolari',
  'Altyazı görünümü': 'Aspetto dei sottotitoli',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık':
      'Colore, carattere, dimensione, bordo e opacità',
  'Bu bir örnek altyazıdır.': 'Questo è un sottotitolo di esempio.',
  'Ayar değiştikçe önizleme anında güncellenir.':
      'L\'anteprima si aggiorna subito a ogni modifica.',
  'Yazı biçimi': 'Stile del testo',
  'Yazı rengi': 'Colore del testo',
  'Yazı opaklığı': 'Opacità del testo',
  'Yazı tipi': 'Carattere',
  'Yazı boyutu': 'Dimensione del testo',
  'Karakter ayrıtı': 'Bordo dei caratteri',
  'Ayrıt türü': 'Tipo di bordo',
  'Ayrıt rengi': 'Colore del bordo',
  'Yok': 'Nessuno',
  'Dış çizgi': 'Contorno',
  'Gölge': 'Ombreggiatura',
  'Kabartma': 'In rilievo',
  'Oyma': 'Incassato',
  'Arka plan rengi': 'Colore dello sfondo',
  'Arka plan opaklığı': 'Opacità dello sfondo',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      'Lo sfondo è il riempimento subito dietro il testo; la finestra è la superficie più ampia dietro l\'intero blocco di sottotitoli.',
  'Pencere': 'Finestra',
  'Pencere rengi': 'Colore della finestra',
  'Pencere opaklığı': 'Opacità della finestra',
  'Altyazı görünümü sıfırlansın mı?': 'Reimpostare l\'aspetto dei sottotitoli?',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      'Le impostazioni di colore, carattere, dimensione, bordo e opacità torneranno ai valori predefiniti.',
  'Altyazı görünümü varsayılana döndü': 'Aspetto dei sottotitoli reimpostato',
  '{} indiriliyor…': 'Download di {} in corso…',
  'Seçince indirilir': 'Si scarica alla selezione',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      'Impossibile scaricare il carattere. Visualizzazione con il carattere predefinito.',
  'Beyaz': 'Bianco',
  'Siyah': 'Nero',
  'Kırmızı': 'Rosso',
  'Yeşil': 'Verde',
  'Mavi': 'Blu',
  'Sarı': 'Giallo',
  'Camgöbeği': 'Ciano',
  'Macenta': 'Magenta',
  'Yapım bütçesi': 'Budget di produzione',
  'Yapım bütçesi ve dünya çapında hasılat':
      'Budget di produzione e incassi mondiali',
  'Dizinin yayın durumu': 'Stato di trasmissione della serie',
  'Devam ediyor': 'In corso',
  'Sona erdi': 'Conclusa',
  'İptal edildi': 'Cancellata',
  'Yapımda': 'In produzione',
  'Planlandı': 'Pianificata',
  'Pilot bölüm': 'Episodio pilota',
  'Ad': 'Nome',
  'Adın': 'Il tuo nome',
  'Kullanıcı adı': 'Nome utente',
  'Kullanıcı adını değiştir': 'Cambia nome utente',
  'Kullanıcı adını 90 günde bir değiştirebilirsin':
      'Puoi cambiare il nome utente una volta ogni 90 giorni',
  'Değiştir': 'Cambia',
  '{} gün sonra değiştirebilirsin': 'Potrai cambiarlo tra {} giorni',
  'Kullanıcı adın: @{}': 'Il tuo nome utente: @{}',
  'Bu kullanıcı adı zaten alınmış': 'Questo nome utente è già in uso',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış':
      'Questo nome utente è al momento riservato a un altro account',
  'Bu zaten senin kullanıcı adın': 'Questo è già il tuo nome utente',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      'Il nome deve essere 3–20 caratteri; minuscole, cifre, punti, trattini e underscore',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      'Appare sopra il tuo nome utente nel profilo. Puoi lasciarlo vuoto.',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      'Dopo il cambio non potrai cambiarlo di nuovo per 90 giorni. Il vecchio nome utente resta riservato a te per 90 giorni — puoi tornarci e nessun altro può prenderlo in quel periodo. I link al vecchio nome non apriranno più il tuo profilo.',
  'Etkinliğim': 'Attività',
  'Tercihler': 'Preferenze',
  'Gizlilik ve güvenlik': 'Privacy e sicurezza',
  'Destek': 'Assistenza',
  'Hesap': 'Account',
  '{} dizileri': 'Serie di {}',
  '{} filmleri': 'Film di {}',
  'En üste taşı': 'Sposta in cima',
  'Sırayı sıfırla': 'Reimposta l’ordine',
  'Listede ara': 'Cerca nella lista',
  'Elle sıra sıfırlansın mı?': 'Reimpostare l’ordine manuale?',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      'La lista torna all’ordine predefinito (prima ciò che hai segnato più di recente).',
  'Sıra sıfırlanamadı': 'Impossibile reimpostare l’ordine',
  'Listenin en üstüne taşındı': 'Spostato in cima alla lista',
  'Adlar yükleniyor…': 'Caricamento dei titoli…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      'Tieni premuto un poster per trascinarlo. Per portare avanti un titolo lontano, usa «Sposta in cima».',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      'Il trascinamento è disattivato nella ricerca; portalo avanti con «Sposta in cima» ({} risultati).',
  'Görünüm': 'Visualizzazione',
  'En çok izlediğin filmler': 'I film più visti',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      'I tempi sono stimati: un episodio vale ~{} min, un film ~{} min',
  'Bu kullanıcı adı sistem tarafından ayrılmış':
      'Questo nome utente è riservato dal sistema',
  'Ekran süresi': 'Tempo di visione',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir":
      'I tempi sono le durate reali di episodi e film su TMDB',
  'Tüm zamanlar: {} bölüm · {} film · {}':
      'Da sempre: {} episodi · {} film · {}',
  'Kabul et': 'Accetta',
  'Reddedilenler': 'Rifiutate',
  'İstekler': 'Richieste',
  'Reddettiğin istek yok': 'Nessuna richiesta rifiutata',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      'Le richieste rifiutate restano qui; puoi accettarle di nuovo quando vuoi.',
  'Ne izlesem?': 'Cosa guardo?',
  'Karışık': 'Misto',
  'Çarkı çevir': 'Gira la ruota',
  'Tekrar çevir': 'Gira di nuovo',
  'Bu türde içerik yok': 'Nessun titolo di questo tipo',
  'Bütçe': 'Budget',
  'dizi.jpg AI özeti': 'Riassunto IA di dizi.jpg',
  'Daha fazlasını gör': 'Vedi altro',
  'Yıldız sistemi': 'Sistema a stelle',
  '{} yıldız üzerinden': 'Su {} stelle',
  'Önizleme': 'Anteprima',
  'dokununca açılır': 'si apre al tocco',
  'Bir azalt': 'Riduci di uno',
  'Bir artır': 'Aumenta di uno',
  'Ölçek kaydedilemedi': 'Impossibile salvare la scala',
  'Ölçeği değiştirmek puanlarını silmez; aynı puanlar yeni ölçekte gösterilir.':
      'Cambiare scala non elimina i tuoi voti; gli stessi voti sono mostrati nella nuova scala.',
  'En aşağıya gönder': 'Sposta in fondo',
  'Listenin en altına taşındı': 'Spostato in fondo alla lista',
  'Oturumun sonlandı': 'La tua sessione è terminata',
  'Bu hesabın oturumları kapatıldı ya da şifresi değişti. Devam etmek için tekrar giriş yap.':
      'Questo account è stato disconnesso ovunque o la password è cambiata. Accedi di nuovo per continuare.',
  'Son izleme: {}': 'Visto l\'ultima volta: {}',
  '{} tarihinde izledin': 'Visto il {}',
  'Geri bildirimine yanıt verdik': 'Abbiamo risposto al tuo feedback',
  'Bu yanıt artık görüntülenemiyor.': 'Questa risposta non è più disponibile.',
  'Gönderdiğin geri bildirim': 'Il feedback che hai inviato',
  'Dizi veya film seç (zorunlu)': 'Scegli una serie o un film (obbligatorio)',
  'Bölüm seç (isteğe bağlı)': 'Scegli un episodio (facoltativo)',
  '{}. sezon {}. bölüm': 'Stagione {}, episodio {}',
  'Ne düşünüyorsun?': 'Cosa ne pensi?',
  '{}/{} yükleniyor': 'Caricamento {}/{}',
  'Fotoğraf/video ekle': 'Aggiungi foto o video',
  'Paylaşmak için önce bir dizi veya film seç.':
      'Scegli prima una serie o un film da condividere.',
  'Sezon seç': 'Scegli una stagione',
  '{}. sezon': 'Stagione {}',
  'Bölüm seçme (yalnız dizi hakkında)': 'Nessun episodio (solo sulla serie)',
  'Sezonlar yüklenemedi.': 'Impossibile caricare le stagioni.',
  'Bu dizide bölüm bilgisi yok.':
      'Nessuna informazione sugli episodi per questa serie.',
  'Bu sezonda bölüm yok.': 'Nessun episodio in questa stagione.',
  '{}. bölüm': 'Episodio {}',
  'Dizi veya film ara...': 'Cerca serie e film...',
  'İzlediğin dizi ve film hakkında yorum paylaş':
      'Condividi un commento su ciò che hai visto',
  'Yapım seç (zorunlu)': 'Scegli un titolo (obbligatorio)',
  'Paylaşmak için önce bir yapım seç.':
      'Scegli prima un titolo da condividere.',
  'Kişi': 'Persona',
  'Yapım firması': 'Casa di produzione',
  'Yapım ara...': 'Cerca titoli...',
  'Çarkı çevirmek için sürükle veya dokun':
      'Trascina o tocca per girare la ruota',
  'Arşiv': 'Archivio',
  'Yüklediklerim': 'I miei caricamenti',
  'GIF ara...': 'Cerca GIF...',
  'GIF yükle': 'Carica GIF',
  'GIF etiketleri': 'Tag della GIF',
  'Virgülle ayır. Aramada bu kelimelerle bulunur.':
      'Separa con virgole. La GIF si trova con queste parole.',
  'gülme, alkış, şaşkın': 'risata, applausi, sorpresa',
  'Yükle': 'Carica',
  'Henüz GIF yok': 'Ancora nessuna GIF',
  'Bu aramaya uyan GIF yok': 'Nessuna GIF corrisponde a questa ricerca',
  'Arşiv yeni. İlk GIF i sen yükle — sen hemen kullanırsın, onaydan sonra herkes görür.':
      'L\'archivio è nuovo. Carica la prima GIF: puoi usarla subito, tutti la vedranno dopo l\'approvazione.',
  'GIF yüklendi. Sen hemen kullanabilirsin; herkese açık arşive onaydan sonra girer.':
      'GIF caricata. Puoi usarla subito; entra nell\'archivio pubblico dopo l\'approvazione.',
  'Onay bekliyor': 'In attesa di approvazione',
  'GIF listesi yüklenemedi': 'Impossibile caricare l\'elenco delle GIF',
  'GIF yüklenemedi': 'Impossibile caricare la GIF',
  'Bu GIF i şikayet et': 'Segnala questa GIF',
  'Uygunsuz içerik yöneticiye bildirilir ve arşivden kaldırılabilir.':
      'I contenuti inappropriati vengono segnalati a un moderatore e possono essere rimossi dall\'archivio.',
  'Şikayetin alındı': 'La tua segnalazione è stata ricevuta',
  'Şikayet gönderilemedi': 'Impossibile inviare la segnalazione',
  'Dizinin kendisi': 'La serie stessa',
  'Sezon ya da bölüm seçme': 'Nessuna stagione o episodio',
  'Tüm {}. sezon': 'Tutta la stagione {}',
  'Bölüm seçme': 'Nessun episodio',
  'En fazla {} yapım ekleyebilirsin.': 'Puoi aggiungere fino a {} titoli.',
  'Bu zaten ekli.': 'Già aggiunto.',
  'Dizi, film, oyuncu ya da yönetmen etiketle — gönderin onların sayfasında da görünür.':
      'Tagga una serie, un film, un attore o un regista: il tuo post apparirà anche sulla loro pagina.',
  'Etiket ekle': 'Aggiungi tag',
  'Dizi, film, oyuncu ya da yönetmen etiketle':
      'Tagga una serie, un film, un attore o un regista',
  'Gönderiden vazgeç': 'Elimina il post',
  'Yazdıkların kaydedilmeyecek.': 'Quello che hai scritto non verrà salvato.',
  'Yazmaya devam et': 'Continua a scrivere',
  'Bulunamadı. Adın yazılışını değiştirip dene.':
      'Non trovato. Prova con un’altra grafia.',
  'Dizi, film, oyuncu, yönetmen ya da yapım firması ara.':
      'Cerca una serie, un film, un attore, un regista o una casa di produzione.',
  'E-posta adresini değiştir': 'Cambia il tuo indirizzo email',
  'E-posta bağlı değil': 'Nessuna email collegata',
  'Geçerli bir e-posta adresi yaz': 'Scrivi un indirizzo email valido',
  'Bu zaten hesabının e-posta adresi':
      'È già l\'indirizzo email del tuo account',
  'Kod gönder': 'Invia codice',
  'E-posta adresin güncellendi': 'Il tuo indirizzo email è stato aggiornato',
  'Bu e-posta başka bir hesapta kayıtlı':
      'Questa email è registrata su un altro account',
  'Doğrulama kodu YENİ adrese gönderilir; adres ancak kodu girdikten sonra değişir. Şifre sıfırlama ve iki adımlı giriş kodları bundan sonra yeni adrese gider.':
      'Il codice di verifica viene inviato al NUOVO indirizzo; l\'indirizzo cambia solo dopo che inserisci il codice. I codici di reimpostazione password e di accesso in due passaggi andranno poi al nuovo indirizzo.',
  'Hesabındaki e-posta adresi geçerli değil, bu yüzden e-posta teslim edilemiyor. Doğru adresi bağlamak için destekle iletişime geç.':
      'L\'indirizzo email del tuo account non è valido, quindi l\'email non può essere consegnata. Contatta il supporto per collegare l\'indirizzo corretto.',
  'Bu adrese kod gönderilemedi, adresi kontrol et':
      'Non è stato possibile inviare un codice a questo indirizzo, controllalo',
  'ya da': 'oppure',
  'Google ile doğrula': 'Verifica con Google',
  'Hesabını Google ile açtıysan şifren yoktur; kimliğini Google ile doğrula.':
      'Se hai creato il tuo account con Google non hai una password; verifica la tua identità con Google.',
  'Google doğrulaması bu hesapla eşleşmedi':
      'La verifica Google non corrisponde a questo account',
  'Bu hesap Google ile açıldı; doğrulamak için Google ile giriş yap':
      'Questo account è stato creato con Google; accedi con Google per verificare',
  // --- 31 Agu 2026: kitaplik paylasimi + reels ceviri + sohbet detayi ---
  'Bu liste gizli': 'Questa lista è privata',
  'Bu kullanıcı izleme listelerini gizli tutmayı tercih ediyor.':
      'Questo utente preferisce tenere private le sue liste.',
  'Bu listede henüz içerik yok': 'Ancora nessun titolo in questa lista',
  'Otomatik çeviri': 'Traduzione automatica',
  'Otomatik çeviri açıldı': 'Traduzione automatica attivata',
  'Otomatik çeviri kapatıldı': 'Traduzione automatica disattivata',
  'Sohbet sessize alındı': 'Chat silenziata',
  'Sessize alma kaldırıldı': 'Silenzioso disattivato',
  'Tema özelleştir': 'Personalizza tema',
  'Sohbette ara': 'Cerca nella chat',
  'Mesajlarda ara...': 'Cerca nei messaggi...',
  'Sonuç yok': 'Nessun risultato',
  'Profili gör': 'Vedi profilo',
  'Medya ve dosyalar': 'Media e file',
  'Henüz medya yok': 'Ancora nessun media',
  'Varsayılan': 'Predefinito',
  'Mor': 'Viola',
  'Pembe': 'Rosa',
  'Turuncu': 'Arancione',
  'Orijinal metin gösteriliyor': 'Testo originale mostrato',
  'İnternet bağlantısı yok': 'Nessuna connessione a Internet',
  'Sunucu yanıt vermedi': 'Il server non ha risposto',
  'Güvenli bağlantı kurulamadı': 'Impossibile stabilire una connessione sicura',
  'Sunucudan beklenmeyen bir yanıt geldi': 'Risposta inattesa dal server',
  'İzlediğim Diziler': 'Serie viste',
  'İzlediğim Filmler': 'Film visti',
  'Satır görünümü': 'Vista elenco',
  'Afiş görünümü': 'Vista poster',
  'Satır görünümünde sürükleme kapalı; "En üste taşı" ile öne al.':
      'Nella vista elenco il trascinamento è disattivato; usa «Sposta in cima» per portarlo avanti.',
  'Spoiler uyarısını göster': 'Mostra avviso spoiler',
  'Kapalıyken spoiler işaretli gönderiler perdesiz, doğrudan gösterilir.':
      'Se disattivato, i post contrassegnati come spoiler vengono mostrati direttamente, senza copertura.',
  'Etiketler': 'Tag',
  'Galeri': 'Galleria',
  'Kamera': 'Fotocamera',
  'Dosya': 'File',
  'GIF': 'GIF',
  'Dizi / Film': 'Serie / Film',
  'Sesli mesaj (basılı tut)': 'Messaggio vocale (tieni premuto)',
  'Kaydetmek için basılı tut': 'Tieni premuto per registrare',
  'Kaydırarak iptal': 'Scorri per annullare',
  'Kamera açılamadı': 'Impossibile aprire la fotocamera',
  'Dosya seçilemedi': 'Impossibile selezionare il file',
  'Dosya gönderilemedi': 'Impossibile inviare il file',
  'En yeni mesaja in': 'Vai all’ultimo messaggio',
  'Gönderilemedi · tekrar dene': 'Non inviato · riprova',
  'Dosya açılamadı': 'Impossibile aprire il file',
};
