/// Otomatik üretilen çeviri haritası (uk).
const Map<String, String> cevirilerUk = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Не знайдено розпізнаних даних для імпорту.',
  'Arama': 'Пошук',
  'Aramaya başla': 'Почни пошук',
  'Ayarlar': 'Налаштування',
  'Bağla': 'Прив’язати',
  'Bio': 'Біо',
  'Bitirdim': 'Завершено',
  'Bunları da Beğenebilirsin': 'Тобі може сподобатися',
  'Bölüm': 'Епізод',
  'Bıraktım': 'Покинуто',
  'Dil': 'Мова',
  'Dil ara...': 'Пошук мови...',
  'Dizi': 'Серіал',
  'Dizi ve filmlerini takip et': 'Стеж за своїми серіалами й фільмами',
  'Dizi yorumu': 'Коментар до серіалу',
  'Dizi, film veya kişi ara...': 'Пошук серіалів, фільмів і людей...',
  'Dosya en fazla 30MB olabilir': 'Файл не більше 30 МБ',
  'Dosya en fazla {}MB olabilir': 'Файл не більше {} МБ',
  'E-posta': 'Ел. пошта',
  'E-posta veya kullanıcı adı': 'Ел. пошта або ім’я користувача',
  'En az 2 harf yaz': 'Введи щонайменше 2 літери',
  'Film': 'Фільм',
  'Film yorumu': 'Коментар до фільму',
  'Fotoğraf / video ekle': 'Додати фото / відео',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Фото або GIF — аватар і обкладинка',
  'Giriş Yap': 'Увійти',
  'Gönder': 'Надіслати',
  'Gönderildi': 'Надіслано',
  'Haftanın Dizileri': 'Серіали тижня',
  'Haftanın Filmleri': 'Фільми тижня',
  'Henüz izleme kaydın yok': 'У тебе поки немає історії переглядів',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'У тебе поки немає списків — створи у вкладці «Профіль».',
  'Henüz yorum yok.': 'Поки немає коментарів.',
  'Hesabın bağlandı!': 'Акаунт прив’язано!',
  'Hesabın yok mu? Kayıt ol': 'Немає акаунта? Зареєструйся',
  'Hesabını Bağla': 'Прив’яжи акаунт',
  'Hesap Oluştur': 'Створити акаунт',
  'Kapak resmi ekle': 'Додати обкладинку',
  'Kaydet': 'Зберегти',
  'Kendinden bahset...': 'Розкажи про себе...',
  'Keşfet': 'Огляд',
  'Kimseyi takip etmiyor': 'Немає підписок',
  'Kişi ara': 'Пошук людей',
  'Kişi yorumu': 'Коментар про людину',
  'Konuk Oyuncular': 'Запрошені актори',
  'Kullanıcı adı (küçük harf)': 'Ім’я користувача (малими літерами)',
  'Kullanıcı adı ara...': 'Пошук за ім’ям користувача...',
  'Liste adı': 'Назва списку',
  'Listeye Ekle': 'Додати до списку',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Ти в гостьовому акаунті — прив’яжи пошту, не втрать свої дані!',
  'Misafir olarak devam et': 'Продовжити як гість',
  'Oluştur': 'Створити',
  'Oyuncular': 'Актори',
  'Profil': 'Профіль',
  'Profil kaydedildi': 'Профіль збережено',
  'Puanla': 'Оцінити',
  'Puanı Sil': 'Видалити оцінку',
  'Puanın': 'Твоя оцінка',
  'Sezonlar': 'Сезони',
  'Sunucu hatası ({})': 'Помилка сервера ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Коментар до S{}E{}',
  'Takibi Bırak': 'Відписатися',
  'Takip': 'Підписки',
  'Takip Edilenler': 'Підписки',
  'Takip Et': 'Підписатися',
  'Takipçi': 'Підписники',
  'Takipçi yok': 'Немає підписників',
  'Takipçiler': 'Підписники',
  'Takvim': 'Календар',
  'Tamam': 'Гаразд',
  'Tekrar Dene': 'Повторити',
  'Tekrar dene': 'Спробуй ще раз',
  'Toplam ekran süresi': 'Загальний екранний час',
  'Tüm Zamanların En İyileri': 'Найкращі за весь час',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Завантаж усі свої дані (перегляди, оцінки, коментарі, списки) у ZIP, сумісному з TV Time, або імпортуй ZIP з іншого застосунку.',
  'Tümünü Kaldır': 'Прибрати все',
  'Tümünü İzledim': 'Все переглянуто',
  'Türk Dizileri': 'Турецькі серіали',
  'Veri içe aktar (.zip)': 'Імпорт даних (.zip)',
  'Verilerim': 'Мої дані',
  'Verilerimi dışa aktar (e-posta)': 'Експорт моїх даних (на пошту)',
  'Verilerini dışa aktar': 'Експорт твоїх даних',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Немає майбутніх епізодів.\nПостав серіалу статус «Дивлюся» на його сторінці й стеж за новими епізодами тут.',
  'Yapımları': 'Фільмографія',
  'Yeni Diziler': 'Нові серіали',
  'Yeni Liste': 'Новий список',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Нове ім’я користувача (необов’язково)',
  'Yorum': 'Коментар',
  'Yorumunu yaz...': 'Напиши коментар...',
  'Zaten hesabın var mı? Giriş yap': 'Уже є акаунт? Увійди',
  'ort. {}': 'сер. {}',
  'takip': 'підписки',
  'takipçi': 'підписники',
  '{} / {} bölüm': '{} / {} епізодів',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} міс.',
  '{} bölüm izlendi': '{} епізодів переглянуто',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} хв',
  '{} gün': '{} дн.',
  '{} içerik': '{} тайтлів',
  '{} içerik · otomatik': '{} тайтлів · авто',
  '{} kayıt atlandı (eşleşmedi).': '{} записів пропущено (немає збігу).',
  '{} saat': '{} год',
  '{} sezon': '{} сезонів',
  '{} yıl': '{} років',
  '{}. Bölüm': 'Епізод {}',
  '{}. Sezon': 'Сезон {}',
  'Çıkış Yap': 'Вийти',
  'Ülke': 'Країна',
  'Ülke ara...': 'Пошук країни...',
  'Ülke seç': 'Вибери країну',
  'İlk yorumu sen yaz!': 'Напиши перший коментар!',
  'İncelemeler': 'Рецензії',
  'İncelemen (isteğe bağlı)': 'Твоя рецензія (необов’язково)',
  'İptal': 'Скасувати',
  'İzlediklerim': 'Історія переглядів',
  'İzledim': 'Переглянуто',
  'İzledin': 'Переглянуто',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Історія переглядів і списки збережуться; тепер можна входити з будь-якого пристрою.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Історію переглядів, оцінки, коментарі та списки буде надіслано ZIP-архівом на твою пошту.',
  'İzleyeceğim': 'Буду дивитися',
  'İzliyorum': 'Дивлюся',
  'İçe aktarım tamamlandı': 'Імпорт завершено',
  'Şifre': 'Пароль',
  '• profil bilgisi': '• дані профілю',
  '• {} dizi durumu': '• {} статусів серіалів',
  '• {} izleme kaydı': '• {} записів перегляду',
  '• {} liste': '• {} списків',
  '• {} puan': '• {} оцінок',
  '• {} yorum': '• {} коментарів',
  '{}+ yapım': '{}+ робіт',
  'Yorumlar': 'Коментарі',
  'Yorumlar ({})': 'Коментарі ({})',
  'Yorumları ({})': 'Коментарі ({})',
  'Listelerim': 'Мої списки',
  'Nereden izledin?': 'Де ти дивився?',
  'Diziye git': 'До серіалу',
  'TV / Kanal': 'ТБ / канал',
  'Sinema': 'Кінотеатр',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Інше',
  'Akış': 'Стрічка',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Твоя стрічка порожня.\nКоли коментуватимуть серіали й фільми, які ти дивишся, це з\'явиться тут.',
  'Listeleri ({})': 'Списки ({})',
  'Liste boş.': 'Цей список порожній.',
  'Yanıtla': 'Відповісти',
  '@{} kullanıcısına yanıt veriyorsun': 'Ти відповідаєш @{}',
  'İzlediğim Diziler ({})': 'Переглянуті серіали ({})',
  'İzlediğim Filmler ({})': 'Переглянуті фільми ({})',
  'Tümünü gör': 'Показати всі',
  'Bildirimler': 'Сповіщення',
  'Henüz bildirim yok': 'Поки немає сповіщень',
  '@{} yorumuna yanıt verdi': '@{} відповів на твій коментар',
  '@{} yorumunu beğendi': '@{} вподобав твій коментар',
  '@{} seni takip etti': '@{} підписався на тебе',
  '@{} sana mesaj gönderdi': '@{} надіслав тобі повідомлення',
  'Mesajlar': 'Повідомлення',
  'Mesaj': 'Повідомлення',
  'Mesajını yaz...': 'Напиши повідомлення...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Поки немає чатів.\nВідкрий профіль і надішли повідомлення.',
  'Şifreni mi unuttun?': 'Забув пароль?',
  'Şifreyi Sıfırla': 'Скинути пароль',
  'E-postadaki kod': 'Код із листа',
  'Yeni şifre': 'Новий пароль',
  'Sana Özel': 'Для тебе',
  '{} özetin': 'Твої підсумки {}',
  'Yıllık izleme istatistiklerin': 'Річна статистика переглядів',
  'Rozetler': 'Значки',
  'Verdiğin puan': 'Поставлені оцінки',
  'Ortalama puanın': 'Середня оцінка',
  'En çok izlediğin diziler': 'Найбільш переглянуті серіали',
  'İlk Bölüm': 'Перша серія',
  '100 Bölüm': '100 серій',
  '1000 Bölüm': '1000 серій',
  'İlk Film': 'Перший фільм',
  '50 Film': '50 фільмів',
  'İlk Yorum': 'Перший коментар',
  '25 Yorum': '25 коментарів',
  '10 Puan': '10 оцінок',
  'İlk Takipçi': 'Перший підписник',
  '10 Dizi Bitirdin': 'Завершено 10 серіалів',
  'İzlemeyi Bıraktım': 'Я покинув перегляд',
  'İzlediği Diziler ({})': 'Переглянуті серіали ({})',
  'İzlediği Filmler ({})': 'Переглянуті фільми ({})',
  '500 Bölüm': '500 серій',
  '5000 Bölüm': '5000 серій',
  '10 Film': '10 фільмів',
  '100 Film': '100 фільмів',
  '100 Yorum': '100 коментарів',
  '50 Puan': '50 оцінок',
  '100 Puan': '100 оцінок',
  '10 Takipçi': '10 підписників',
  '50 Takipçi': '50 підписників',
  '25 Dizi Bitirdin': 'Завершено 25 серіалів',
  '50 Dizi Bitirdin': 'Завершено 50 серіалів',
  '10 Beğeni': '10 вподобань',
  '100 Beğeni': '100 вподобань',
  'yazıyor...': 'друкує...',
  'Profil düzeni': 'Порядок розділів профілю',
  'Konumla ve kırp': 'Розташуйте та обріжте',
  'Listeye eklendi': 'Додано до списку',
  'Listeyi sil?': 'Видалити список?',
  'Sil': 'Видалити',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Тайтл буде позначено як непереглянутий і вилучено з твоїх списків.',
  'Gelecek bölüm bugün': 'Наступна серія сьогодні',
  'Gelecek bölüm {} gün sonra': 'Наступна серія через {} дн.',
  'Tema': 'Тема',
  'Sistem': 'Системна',
  'Koyu': 'Темна',
  'Açık': 'Світла',
  'İzleyenler': 'Глядачі',
  'Yorumunu yaz... (@ ile etiketle)': 'Напишіть коментар... (@ щоб позначити)',
  '@{} bir yorumda seni etiketledi': '@{} згадав вас у коментарі',
  'Mesajı sil': 'Видалити повідомлення',
  'Mesaj silinemedi': 'Не вдалося видалити повідомлення',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Посилання недійсне або сторінку не знайдено',
  'Keşfet\'e dön': 'Назад до Огляду',
  'Düzenle': 'Редагувати',
  'Mesajı düzenle': 'Редагувати повідомлення',
  'Yanıtlanıyor': 'Відповідь',
  'düzenlendi': 'змінено',
  'Fotoğraf': 'Фото',
  'Video': 'Відео',
  'İçerik': 'Контент',
  'çevrimiçi': 'онлайн',
  'son görülme {} dk önce': 'бачили {} хв тому',
  'son görülme {} saat önce': 'бачили {} год тому',
  'son görülme {} gün önce': 'бачили {} дн тому',
  'Yorumlar yüklenemedi': 'Не вдалося завантажити коментарі',
  'Favori': 'Обране',
  'Listeye ekle': 'Додати до списку',
  'İçerik paylaş': 'Поділитися',
  'Kapat': 'Закрити',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Усе, що ви позначите переглянутим, збирається тут.',
  'Henüz sohbetin yok': 'Ще немає розмов',
  'Bir profile girip mesaj gönderebilirsin.':
      'Відкрийте профіль і надішліть повідомлення.',
};
