/// Otomatik üretilen çeviri haritası (sv).
const Map<String, String> cevirilerSv = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Inga igenkända data att importera hittades.',
  'Arama': 'Sök',
  'Aramaya başla': 'Börja söka',
  'Ayarlar': 'Inställningar',
  'Bağla': 'Koppla',
  'Bio': 'Bio',
  'Bitirdim': 'Sett klart',
  'Bunları da Beğenebilirsin': 'Du kanske också gillar dessa',
  'Bölüm': 'Avsnitt',
  'Bıraktım': 'Slutat titta',
  'Dil': 'Språk',
  'Dil ara...': 'Sök språk...',
  'Dizi': 'Serie',
  'Dizi ve filmlerini takip et': 'Håll koll på dina serier och filmer',
  'Dizi yorumu': 'Seriekommentar',
  'Dizi, film veya kişi ara...': 'Sök serie, film eller person...',
  'Dosya en fazla 30MB olabilir': 'Filen får vara högst 30MB',
  'Dosya en fazla {}MB olabilir': 'Filen får vara högst {}MB',
  'E-posta': 'E-post',
  'E-posta veya kullanıcı adı': 'E-post eller användarnamn',
  'En az 2 harf yaz': 'Skriv minst 2 bokstäver',
  'Film': 'Film',
  'Film yorumu': 'Filmkommentar',
  'Fotoğraf / video ekle': 'Lägg till foto / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto eller GIF — profil- och omslagsbild',
  'Giriş Yap': 'Logga in',
  'Gönder': 'Skicka',
  'Gönderildi': 'Skickat',
  'Haftanın Dizileri': 'Veckans serier',
  'Haftanın Filmleri': 'Veckans filmer',
  'Henüz izleme kaydın yok': 'Du har ingen tittarhistorik än',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Du har inga listor än — skapa en från Profil-fliken.',
  'Henüz yorum yok.': 'Inga kommentarer än.',
  'Hesabın bağlandı!': 'Ditt konto är kopplat!',
  'Hesabın yok mu? Kayıt ol': 'Har du inget konto? Registrera dig',
  'Hesabını Bağla': 'Koppla ditt konto',
  'Hesap Oluştur': 'Skapa konto',
  'Kapak resmi ekle': 'Lägg till omslagsbild',
  'Kaydet': 'Spara',
  'Kendinden bahset...': 'Berätta om dig själv...',
  'Keşfet': 'Utforska',
  'Kimseyi takip etmiyor': 'Följer ingen',
  'Kişi ara': 'Sök person',
  'Kişi yorumu': 'Personkommentar',
  'Konuk Oyuncular': 'Gästskådespelare',
  'Kullanıcı adı (küçük harf)': 'Användarnamn (små bokstäver)',
  'Kullanıcı adı ara...': 'Sök användarnamn...',
  'Liste adı': 'Listnamn',
  'Listeye Ekle': 'Lägg till i lista',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Du använder ett gästkonto — koppla din e-post så du inte förlorar dina data!',
  'Misafir olarak devam et': 'Fortsätt som gäst',
  'Oluştur': 'Skapa',
  'Oyuncular': 'Skådespelare',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profilen sparad',
  'Puanla': 'Betygsätt',
  'Puanı Sil': 'Ta bort betyg',
  'Puanın': 'Ditt betyg',
  'Sezonlar': 'Säsonger',
  'Sunucu hatası ({})': 'Serverfel ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Kommentar till S{}E{}',
  'Takibi Bırak': 'Sluta följa',
  'Takip': 'Följer',
  'Takip Edilenler': 'Följer',
  'Takip Et': 'Följ',
  'Takipçi': 'Följare',
  'Takipçi yok': 'Inga följare',
  'Takipçiler': 'Följare',
  'Takvim': 'Kalender',
  'Tamam': 'OK',
  'Tekrar Dene': 'Försök igen',
  'Tekrar dene': 'Försök igen',
  'Toplam ekran süresi': 'Total skärmtid',
  'Tüm Zamanların En İyileri': 'Bästa genom tiderna',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Exportera alla dina data (historik, betyg, kommentarer, listor) som en TV Time-kompatibel ZIP eller importera en ZIP från en annan app.',
  'Tümünü Kaldır': 'Ta bort alla',
  'Tümünü İzledim': 'Har sett alla',
  'Türk Dizileri': 'Turkiska serier',
  'Veri içe aktar (.zip)': 'Importera data (.zip)',
  'Verilerim': 'Mina data',
  'Verilerimi dışa aktar (e-posta)': 'Exportera mina data (e-post)',
  'Verilerini dışa aktar': 'Exportera dina data',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Inga kommande avsnitt.\nSätt en serie till "Tittar" från seriesidan och följ nya avsnitt här.',
  'Yapımları': 'Filmografi',
  'Yeni Diziler': 'Nya serier',
  'Yeni Liste': 'Ny lista',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nytt användarnamn (valfritt)',
  'Yorum': 'Kommentar',
  'Yorumunu yaz...': 'Skriv din kommentar...',
  'Zaten hesabın var mı? Giriş yap': 'Har du redan ett konto? Logga in',
  'ort. {}': 'snitt {}',
  'takip': 'följer',
  'takipçi': 'följare',
  '{} / {} bölüm': '{} / {} avsnitt',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} mån',
  '{} bölüm izlendi': '{} avsnitt sedda',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} gün': '{} d',
  '{} içerik': '{} titlar',
  '{} içerik · otomatik': '{} titlar · automatisk',
  '{} kayıt atlandı (eşleşmedi).': '{} poster hoppades över (ingen matchning).',
  '{} saat': '{} tim',
  '{} sezon': '{} säsonger',
  '{} yıl': '{} år',
  '{}. Bölüm': 'Avsnitt {}',
  '{}. Sezon': 'Säsong {}',
  'Çıkış Yap': 'Logga ut',
  'Ülke': 'Land',
  'Ülke ara...': 'Sök land...',
  'Ülke seç': 'Välj land',
  'İlk yorumu sen yaz!': 'Skriv den första kommentaren!',
  'İncelemeler': 'Recensioner',
  'İncelemen (isteğe bağlı)': 'Din recension (valfritt)',
  'İptal': 'Avbryt',
  'İzlediklerim': 'Min tittarhistorik',
  'İzledim': 'Sett',
  'İzledin': 'Sett',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Din tittarhistorik och dina listor sparas; nu kan du logga in från vilken enhet som helst.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Din tittarhistorik, dina betyg, kommentarer och listor skickas som ZIP till din registrerade e-postadress.',
  'İzleyeceğim': 'Vill se',
  'İzliyorum': 'Tittar',
  'İçe aktarım tamamlandı': 'Importen är klar',
  'Şifre': 'Lösenord',
  '• profil bilgisi': '• profilinfo',
  '• {} dizi durumu': '• {} seriestatusar',
  '• {} izleme kaydı': '• {} tittarposter',
  '• {} liste': '• {} listor',
  '• {} puan': '• {} betyg',
  '• {} yorum': '• {} kommentarer',
  '{}+ yapım': '{}+ titlar',
  'Yorumlar': 'Kommentarer',
  'Yorumlar ({})': 'Kommentarer ({})',
  'Yorumları ({})': 'Kommentarer ({})',
  'Listelerim': 'Mina listor',
  'Nereden izledin?': 'Var såg du den?',
  'Diziye git': 'Gå till serien',
  'TV / Kanal': 'TV / Kanal',
  'Sinema': 'Bio',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Annat',
  'Akış': 'Flöde',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Ditt flöde är tomt.\nNär någon kommenterar serierna och filmerna du tittar på visas det här.',
  'Listeleri ({})': 'Deras listor ({})',
  'Liste boş.': 'Den här listan är tom.',
  'Yanıtla': 'Svara',
  '@{} kullanıcısına yanıt veriyorsun': 'Du svarar @{}',
  'İzlediğim Diziler ({})': 'Serier jag sett ({})',
  'İzlediğim Filmler ({})': 'Filmer jag sett ({})',
  'Tümünü gör': 'Visa alla',
  'Bildirimler': 'Aviseringar',
  'Henüz bildirim yok': 'Inga aviseringar än',
  '@{} yorumuna yanıt verdi': '@{} svarade på din kommentar',
  '@{} yorumunu beğendi': '@{} gillade din kommentar',
  '@{} seni takip etti': '@{} följde dig',
  '@{} sana mesaj gönderdi': '@{} skickade ett meddelande',
  'Mesajlar': 'Meddelanden',
  'Mesaj': 'Meddelande',
  'Mesajını yaz...': 'Skriv ett meddelande...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Inga chattar än.\nÖppna en profil och skicka ett meddelande.',
  'Şifreni mi unuttun?': 'Glömt lösenordet?',
  'Şifreyi Sıfırla': 'Återställ lösenord',
  'E-postadaki kod': 'Kod från mejlet',
  'Yeni şifre': 'Nytt lösenord',
  'Sana Özel': 'För dig',
  '{} özetin': 'Din {}-summering',
  'Yıllık izleme istatistiklerin': 'Din årliga tittarstatistik',
  'Rozetler': 'Utmärkelser',
  'Verdiğin puan': 'Betyg satta',
  'Ortalama puanın': 'Ditt snittbetyg',
  'En çok izlediğin diziler': 'Dina mest sedda serier',
  'İlk Bölüm': 'Första avsnittet',
  '100 Bölüm': '100 avsnitt',
  '1000 Bölüm': '1000 avsnitt',
  'İlk Film': 'Första filmen',
  '50 Film': '50 filmer',
  'İlk Yorum': 'Första kommentaren',
  '25 Yorum': '25 kommentarer',
  '10 Puan': '10 betyg',
  'İlk Takipçi': 'Första följaren',
  '10 Dizi Bitirdin': '10 avklarade serier',
  'İzlemeyi Bıraktım': 'Slutade titta',
  'İzlediği Diziler ({})': 'Serier hen sett ({})',
  'İzlediği Filmler ({})': 'Filmer hen sett ({})',
  '500 Bölüm': '500 avsnitt',
  '5000 Bölüm': '5000 avsnitt',
  '10 Film': '10 filmer',
  '100 Film': '100 filmer',
  '100 Yorum': '100 kommentarer',
  '50 Puan': '50 betyg',
  '100 Puan': '100 betyg',
  '10 Takipçi': '10 följare',
  '50 Takipçi': '50 följare',
  '25 Dizi Bitirdin': '25 avklarade serier',
  '50 Dizi Bitirdin': '50 avklarade serier',
  '10 Beğeni': '10 gilla',
  '100 Beğeni': '100 gilla',
  'yazıyor...': 'skriver...',
  'Profil düzeni': 'Profillayout',
};
