/// Otomatik üretilen çeviri haritası (pa).
const Map<String, String> cevirilerPa = {
  'Aktarılacak tanınan veri bulunamadı.':
      'ਇੰਪੋਰਟ ਕਰਨ ਲਈ ਕੋਈ ਪਛਾਣਿਆ ਡੇਟਾ ਨਹੀਂ ਮਿਲਿਆ।',
  'Arama': 'ਖੋਜ',
  'Aramaya başla': 'ਖੋਜਣਾ ਸ਼ੁਰੂ ਕਰੋ',
  'Son aramalar': 'ਹਾਲੀਆ ਖੋਜਾਂ',
  'Ayarlar': 'ਸੈਟਿੰਗਾਂ',
  'Bağla': 'ਲਿੰਕ ਕਰੋ',
  'Bio': 'ਬਾਇਓ',
  'Bitirdim': 'ਪੂਰਾ ਕਰ ਲਿਆ',
  'Bunları da Beğenebilirsin': 'ਇਹ ਵੀ ਪਸੰਦ ਆ ਸਕਦੇ ਹਨ',
  'Bölüm': 'ਐਪੀਸੋਡ',
  'Bıraktım': 'ਛੱਡ ਦਿੱਤਾ',
  'Dil': 'ਭਾਸ਼ਾ',
  'Dil ara...': 'ਭਾਸ਼ਾ ਖੋਜੋ...',
  'Dizi': 'ਸੀਰੀਜ਼',
  'Dizi ve filmlerini takip et': 'ਆਪਣੇ ਸ਼ੋਅ ਤੇ ਫ਼ਿਲਮਾਂ ਟ੍ਰੈਕ ਕਰੋ',
  'Dizi yorumu': 'ਸੀਰੀਜ਼ ਬਾਰੇ ਕਮੈਂਟ',
  'Dizi, film veya kişi ara...': 'ਸੀਰੀਜ਼, ਫ਼ਿਲਮ ਜਾਂ ਵਿਅਕਤੀ ਖੋਜੋ...',
  'Dosya en fazla 30MB olabilir': 'ਫ਼ਾਈਲ ਵੱਧ ਤੋਂ ਵੱਧ 30MB ਹੋ ਸਕਦੀ ਹੈ',
  'Dosya en fazla {}MB olabilir': 'ਫ਼ਾਈਲ ਵੱਧ ਤੋਂ ਵੱਧ {}MB ਹੋ ਸਕਦੀ ਹੈ',
  'E-posta': 'ਈਮੇਲ',
  'E-posta veya kullanıcı adı': 'ਈਮੇਲ ਜਾਂ ਯੂਜ਼ਰਨੇਮ',
  'En az 2 harf yaz': 'ਘੱਟੋ-ਘੱਟ 2 ਅੱਖਰ ਲਿਖੋ',
  'Film': 'ਫ਼ਿਲਮ',
  'Film yorumu': 'ਫ਼ਿਲਮ ਬਾਰੇ ਕਮੈਂਟ',
  'Fotoğraf / video ekle': 'ਫੋਟੋ / ਵੀਡੀਓ ਸ਼ਾਮਲ ਕਰੋ',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'ਫੋਟੋ ਜਾਂ GIF — ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਕਵਰ ਤਸਵੀਰ',
  'Giriş Yap': 'ਲੌਗ ਇਨ ਕਰੋ',
  'Gönder': 'ਭੇਜੋ',
  'Gönderildi': 'ਭੇਜ ਦਿੱਤਾ ਗਿਆ',
  'Haftanın Dizileri': 'ਇਸ ਹਫ਼ਤੇ ਦੇ ਸ਼ੋਅ',
  'Haftanın Filmleri': 'ਇਸ ਹਫ਼ਤੇ ਦੀਆਂ ਫ਼ਿਲਮਾਂ',
  'Henüz izleme kaydın yok': 'ਹਾਲੇ ਕੋਈ ਵਾਚ ਹਿਸਟਰੀ ਨਹੀਂ',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'ਹਾਲੇ ਕੋਈ ਲਿਸਟ ਨਹੀਂ — ਪ੍ਰੋਫਾਈਲ ਟੈਬ ਤੋਂ ਬਣਾਓ।',
  'Henüz yorum yok.': 'ਹਾਲੇ ਕੋਈ ਕਮੈਂਟ ਨਹੀਂ।',
  'Hesabın bağlandı!': 'ਤੁਹਾਡਾ ਅਕਾਊਂਟ ਲਿੰਕ ਹੋ ਗਿਆ!',
  'Hesabın yok mu? Kayıt ol': 'ਅਕਾਊਂਟ ਨਹੀਂ ਹੈ? ਸਾਈਨ ਅੱਪ ਕਰੋ',
  'Hesabını Bağla': 'ਆਪਣਾ ਅਕਾਊਂਟ ਲਿੰਕ ਕਰੋ',
  'Hesap Oluştur': 'ਅਕਾਊਂਟ ਬਣਾਓ',
  'Kapak resmi ekle': 'ਕਵਰ ਤਸਵੀਰ ਸ਼ਾਮਲ ਕਰੋ',
  'Kaydet': 'ਸੇਵ ਕਰੋ',
  'Kendinden bahset...': 'ਆਪਣੇ ਬਾਰੇ ਦੱਸੋ...',
  'Keşfet': 'ਡਿਸਕਵਰ',
  'Kimseyi takip etmiyor': 'ਕਿਸੇ ਨੂੰ ਫਾਲੋ ਨਹੀਂ ਕਰਦੇ',
  'Kişi ara': 'ਲੋਕ ਖੋਜੋ',
  'Kişi yorumu': 'ਵਿਅਕਤੀ ਬਾਰੇ ਕਮੈਂਟ',
  'Konuk Oyuncular': 'ਮਹਿਮਾਨ ਕਲਾਕਾਰ',
  'Kullanıcı adı (küçük harf)': 'ਯੂਜ਼ਰਨੇਮ (ਲੋਅਰਕੇਸ)',
  'Kullanıcı adı ara...': 'ਯੂਜ਼ਰਨੇਮ ਖੋਜੋ...',
  'Liste adı': 'ਲਿਸਟ ਦਾ ਨਾਮ',
  'Listeye Ekle': 'ਲਿਸਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'ਤੁਸੀਂ ਗੈਸਟ ਅਕਾਊਂਟ ਤੇ ਹੋ — ਆਪਣੀ ਈਮੇਲ ਨਾਲ ਲਿੰਕ ਕਰੋ, ਆਪਣਾ ਡੇਟਾ ਨਾ ਗੁਆਓ!',
  'Misafir olarak devam et': 'ਗੈਸਟ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ',
  'Oluştur': 'ਬਣਾਓ',
  'Oyuncular': 'ਕਲਾਕਾਰ',
  'Profil': 'ਪ੍ਰੋਫਾਈਲ',
  'Profil kaydedildi': 'ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਹੋ ਗਿਆ',
  'Puanla': 'ਰੇਟ ਕਰੋ',
  'Puanı Sil': 'ਰੇਟਿੰਗ ਹਟਾਓ',
  'Puanın': 'ਤੁਹਾਡੀ ਰੇਟਿੰਗ',
  'Sezonlar': 'ਸੀਜ਼ਨ',
  'Sunucu hatası ({})': 'ਸਰਵਰ ਐਰਰ ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'S{}E{} ਬਾਰੇ ਕਮੈਂਟ',
  'Takibi Bırak': 'ਅਨਫਾਲੋ ਕਰੋ',
  'Takip': 'ਫਾਲੋਇੰਗ',
  'Takip Edilenler': 'ਫਾਲੋ ਕੀਤੇ ਗਏ',
  'Takip Et': 'ਫਾਲੋ ਕਰੋ',
  'Takipçi': 'ਫਾਲੋਅਰ',
  'Takipçi yok': 'ਕੋਈ ਫਾਲੋਅਰ ਨਹੀਂ',
  'Takipçiler': 'ਫਾਲੋਅਰਜ਼',
  'Takvim': 'ਕੈਲੰਡਰ',
  'Tamam': 'ਠੀਕ ਹੈ',
  'Tekrar Dene': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
  'Tekrar dene': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
  'Toplam İzleme Süresi': 'ਕੁੱਲ ਸਕ੍ਰੀਨ ਟਾਈਮ',
  'Tüm Zamanların En İyileri': 'ਆਲ-ਟਾਈਮ ਬੈਸਟ',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'ਆਪਣਾ ਸਾਰਾ ਡੇਟਾ (ਵਾਚ ਹਿਸਟਰੀ, ਰੇਟਿੰਗ, ਕਮੈਂਟ, ਲਿਸਟ) TV Time-ਅਨੁਕੂਲ ZIP ਵਜੋਂ ਲਓ ਜਾਂ ਕਿਸੇ ਹੋਰ ਐਪ ਤੋਂ ਆਈ ZIP ਇੰਪੋਰਟ ਕਰੋ।',
  'Tümünü Kaldır': 'ਸਭ ਹਟਾਓ',
  'Tümünü İzledim': 'ਸਭ ਦੇਖ ਲਏ',
  'Türk Dizileri': 'ਤੁਰਕੀ ਸੀਰੀਜ਼',
  'Veri içe aktar (.zip)': 'ਡੇਟਾ ਇੰਪੋਰਟ ਕਰੋ (.zip)',
  'Verilerim': 'ਮੇਰਾ ਡੇਟਾ',
  'Verilerimi dışa aktar (e-posta)': 'ਮੇਰਾ ਡੇਟਾ ਐਕਸਪੋਰਟ ਕਰੋ (ਈਮੇਲ)',
  'Verilerini dışa aktar': 'ਆਪਣਾ ਡੇਟਾ ਐਕਸਪੋਰਟ ਕਰੋ',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'ਕੋਈ ਆਉਣ ਵਾਲਾ ਐਪੀਸੋਡ ਨਹੀਂ।\nਸੀਰੀਜ਼ ਦੇ ਪੇਜ ਤੋਂ "ਦੇਖ ਰਿਹਾ ਹਾਂ" ਸਟੇਟਸ ਚੁਣੋ, ਨਵੇਂ ਐਪੀਸੋਡ ਇੱਥੇ ਟ੍ਰੈਕ ਕਰੋ।',
  'Yapımları': 'ਫ਼ਿਲਮੋਗ੍ਰਾਫੀ',
  'Yeni Diziler': 'ਨਵੀਆਂ ਸੀਰੀਜ਼',
  'Yeni Liste': 'ਨਵੀਂ ਲਿਸਟ',
  'Yeni kullanıcı adı (isteğe bağlı)': 'ਨਵਾਂ ਯੂਜ਼ਰਨੇਮ (ਵਿਕਲਪਿਕ)',
  'Yorum': 'ਕਮੈਂਟ',
  'Yorumunu yaz...': 'ਆਪਣਾ ਕਮੈਂਟ ਲਿਖੋ...',
  'Zaten hesabın var mı? Giriş yap': 'ਪਹਿਲਾਂ ਤੋਂ ਅਕਾਊਂਟ ਹੈ? ਲੌਗ ਇਨ ਕਰੋ',
  'ort. {}': 'ਔਸਤ {}',
  'takip': 'ਫਾਲੋਇੰਗ',
  'takipçi': 'ਫਾਲੋਅਰ',
  '{} / {} bölüm': '{} / {} ਐਪੀਸੋਡ',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} ਮਹੀਨੇ',
  '{} bölüm izlendi': '{} ਐਪੀਸੋਡ ਦੇਖੇ ਗਏ',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} ਮਿੰਟ',
  '{} gün': '{} ਦਿਨ',
  '{} içerik': '{} ਟਾਈਟਲ',
  '{} içerik · otomatik': '{} ਟਾਈਟਲ · ਆਟੋਮੈਟਿਕ',
  '{} kayıt atlandı (eşleşmedi).': '{} ਰਿਕਾਰਡ ਛੱਡੇ ਗਏ (ਮੇਲ ਨਹੀਂ ਖਾਧਾ)।',
  '{} saat': '{} ਘੰਟੇ',
  '{} sezon': '{} ਸੀਜ਼ਨ',
  '{} yıl': '{} ਸਾਲ',
  '{}. Bölüm': 'ਐਪੀਸੋਡ {}',
  '{}. Sezon': 'ਸੀਜ਼ਨ {}',
  'Çıkış Yap': 'ਲੌਗ ਆਊਟ ਕਰੋ',
  'Ülke': 'ਦੇਸ਼',
  'Ülke ara...': 'ਦੇਸ਼ ਖੋਜੋ...',
  'Ülke seç': 'ਦੇਸ਼ ਚੁਣੋ',
  'İlk yorumu sen yaz!': 'ਪਹਿਲਾ ਕਮੈਂਟ ਤੁਸੀਂ ਲਿਖੋ!',
  'İncelemeler': 'ਰਿਵਿਊ',
  'İncelemen (isteğe bağlı)': 'ਤੁਹਾਡਾ ਰਿਵਿਊ (ਵਿਕਲਪਿਕ)',
  'İptal': 'ਰੱਦ ਕਰੋ',
  'İzlediklerim': 'ਮੇਰੇ ਦੇਖੇ ਹੋਏ',
  'İzledim': 'ਦੇਖ ਲਿਆ',
  'İzledin': 'ਤੁਸੀਂ ਦੇਖਿਆ',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'ਤੁਹਾਡੀ ਵਾਚ ਹਿਸਟਰੀ ਅਤੇ ਲਿਸਟਾਂ ਸੁਰੱਖਿਅਤ ਰਹਿਣਗੀਆਂ; ਹੁਣ ਕਿਸੇ ਵੀ ਡਿਵਾਈਸ ਤੋਂ ਲੌਗ ਇਨ ਕਰ ਸਕਦੇ ਹੋ।',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'ਤੁਹਾਡੀ ਵਾਚ ਹਿਸਟਰੀ, ਰੇਟਿੰਗ, ਕਮੈਂਟ ਅਤੇ ਲਿਸਟਾਂ ZIP ਵਜੋਂ ਰਜਿਸਟਰਡ ਈਮੇਲ ਪਤੇ ਤੇ ਭੇਜੀਆਂ ਜਾਣਗੀਆਂ।',
  'İzleyeceğim': 'ਦੇਖਣਾ ਹੈ',
  'İzliyorum': 'ਦੇਖ ਰਿਹਾ ਹਾਂ',
  'İçe aktarım tamamlandı': 'ਇੰਪੋਰਟ ਪੂਰਾ ਹੋਇਆ',
  'Şifre': 'ਪਾਸਵਰਡ',
  '• profil bilgisi': '• ਪ੍ਰੋਫਾਈਲ ਜਾਣਕਾਰੀ',
  '• {} dizi durumu': '• {} ਸੀਰੀਜ਼ ਸਟੇਟਸ',
  '• {} izleme kaydı': '• {} ਵਾਚ ਰਿਕਾਰਡ',
  '• {} liste': '• {} ਲਿਸਟ',
  '• {} puan': '• {} ਰੇਟਿੰਗ',
  '• {} yorum': '• {} ਕਮੈਂਟ',
  '{}+ yapım': '{}+ ਟਾਈਟਲ',
  'Yorumlar': 'ਕਮੈਂਟ',
  'Yorumlar ({})': 'ਕਮੈਂਟ ({})',
  'Yorumları ({})': 'ਇਸ ਬਾਰੇ ਕਮੈਂਟ ({})',
  'Listelerim': 'ਮੇਰੀਆਂ ਲਿਸਟਾਂ',
  'Nereden izledin?': 'ਕਿੱਥੇ ਦੇਖਿਆ?',
  'Diziye git': 'ਸ਼ੋਅ \'ਤੇ ਜਾਓ',
  'TV / Kanal': 'ਟੀਵੀ / ਚੈਨਲ',
  'Sinema': 'ਸਿਨੇਮਾ',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'ਹੋਰ',
  'Akış': 'ਫੀਡ',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'ਤੇਰੀ ਫੀਡ ਖਾਲੀ ਹੈ।\nਤੇਰੇ ਦੇਖੇ ਸ਼ੋਅ ਅਤੇ ਫ਼ਿਲਮਾਂ \'ਤੇ ਟਿੱਪਣੀਆਂ ਆਉਣਗੀਆਂ ਤਾਂ ਇੱਥੇ ਦਿਖਣਗੀਆਂ।',
  'Listeleri ({})': 'ਉਹਨਾਂ ਦੀਆਂ ਸੂਚੀਆਂ ({})',
  'Liste boş.': 'ਇਹ ਸੂਚੀ ਖਾਲੀ ਹੈ।',
  'Yanıtla': 'ਜਵਾਬ ਦਿਓ',
  '@{} kullanıcısına yanıt veriyorsun': '@{} ਨੂੰ ਜਵਾਬ ਦੇ ਰਹੇ ਹੋ',
  'İzlediğim Diziler ({})': 'ਮੇਰੇ ਦੇਖੇ ਸ਼ੋਅ ({})',
  'İzlediğim Filmler ({})': 'ਮੇਰੀਆਂ ਦੇਖੀਆਂ ਫ਼ਿਲਮਾਂ ({})',
  'Tümünü gör': 'ਸਭ ਦੇਖੋ',
  'Bildirimler': 'ਸੂਚਨਾਵਾਂ',
  'Henüz bildirim yok': 'ਹਾਲੇ ਕੋਈ ਸੂਚਨਾ ਨਹੀਂ',
  '@{} yorumuna yanıt verdi': '@{} ਨੇ ਤੇਰੀ ਟਿੱਪਣੀ ਦਾ ਜਵਾਬ ਦਿੱਤਾ',
  '@{} yorumunu beğendi': '@{} ਨੂੰ ਤੇਰੀ ਟਿੱਪਣੀ ਪਸੰਦ ਆਈ',
  '@{} seni takip etti': '@{} ਨੇ ਤੈਨੂੰ ਫਾਲੋ ਕੀਤਾ',
  '@{} sana mesaj gönderdi': '@{} ਨੇ ਤੈਨੂੰ ਸੁਨੇਹਾ ਭੇਜਿਆ',
  'Mesajlar': 'ਸੁਨੇਹੇ',
  'Mesaj': 'ਸੁਨੇਹਾ',
  'Mesajını yaz...': 'ਸੁਨੇਹਾ ਲਿਖੋ...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'ਹਾਲੇ ਕੋਈ ਗੱਲਬਾਤ ਨਹੀਂ।\nਪ੍ਰੋਫਾਈਲ ਖੋਲ੍ਹ ਕੇ ਸੁਨੇਹਾ ਭੇਜੋ।',
  'Şifreni mi unuttun?': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
  'Şifreyi Sıfırla': 'ਪਾਸਵਰਡ ਰੀਸੈੱਟ ਕਰੋ',
  'E-postadaki kod': 'ਈਮੇਲ ਵਾਲਾ ਕੋਡ',
  'Yeni şifre': 'ਨਵਾਂ ਪਾਸਵਰਡ',
  'Sana Özel': 'ਤੇਰੇ ਲਈ',
  '{} özetin': 'ਤੇਰਾ {} ਸਾਰ',
  'Yıllık izleme istatistiklerin': 'ਸਾਲਾਨਾ ਦੇਖਣ ਦੇ ਅੰਕੜੇ',
  'Rozetler': 'ਬੈਜ',
  'Verdiğin puan': 'ਦਿੱਤੀਆਂ ਰੇਟਿੰਗਾਂ',
  'Ortalama puanın': 'ਔਸਤ ਰੇਟਿੰਗ',
  'En çok izlediğin diziler': 'ਸਭ ਤੋਂ ਵੱਧ ਦੇਖੇ ਸ਼ੋਅ',
  'İlk Bölüm': 'ਪਹਿਲਾ ਐਪੀਸੋਡ',
  '100 Bölüm': '100 ਐਪੀਸੋਡ',
  '1000 Bölüm': '1000 ਐਪੀਸੋਡ',
  'İlk Film': 'ਪਹਿਲੀ ਫ਼ਿਲਮ',
  '50 Film': '50 ਫ਼ਿਲਮਾਂ',
  'İlk Yorum': 'ਪਹਿਲੀ ਟਿੱਪਣੀ',
  '25 Yorum': '25 ਟਿੱਪਣੀਆਂ',
  '10 Puan': '10 ਰੇਟਿੰਗਾਂ',
  'İlk Takipçi': 'ਪਹਿਲਾ ਫਾਲੋਅਰ',
  '10 Dizi Bitirdin': '10 ਸ਼ੋਅ ਪੂਰੇ',
  'İzlemeyi Bıraktım': 'ਦੇਖਣਾ ਛੱਡ ਦਿੱਤਾ',
  'İzlediği Diziler ({})': 'ਉਹਨਾਂ ਦੇ ਦੇਖੇ ਸ਼ੋਅ ({})',
  'İzlediği Filmler ({})': 'ਉਹਨਾਂ ਦੀਆਂ ਦੇਖੀਆਂ ਫ਼ਿਲਮਾਂ ({})',
  '500 Bölüm': '500 ਐਪੀਸੋਡ',
  '5000 Bölüm': '5000 ਐਪੀਸੋਡ',
  '10 Film': '10 ਫ਼ਿਲਮਾਂ',
  '100 Film': '100 ਫ਼ਿਲਮਾਂ',
  '100 Yorum': '100 ਟਿੱਪਣੀਆਂ',
  '50 Puan': '50 ਰੇਟਿੰਗਾਂ',
  '100 Puan': '100 ਰੇਟਿੰਗਾਂ',
  '10 Takipçi': '10 ਫਾਲੋਅਰ',
  '50 Takipçi': '50 ਫਾਲੋਅਰ',
  '25 Dizi Bitirdin': '25 ਸ਼ੋਅ ਪੂਰੇ',
  '50 Dizi Bitirdin': '50 ਸ਼ੋਅ ਪੂਰੇ',
  '10 Beğeni': '10 ਲਾਈਕ',
  '100 Beğeni': '100 ਲਾਈਕ',
  'yazıyor...': 'ਲਿਖ ਰਹੇ ਹਨ...',
  'Profil düzeni': 'ਪ੍ਰੋਫਾਈਲ ਲੇਆਉਟ',
  'Konumla ve kırp': 'ਸਥਿਤੀ ਸੈੱਟ ਕਰੋ ਅਤੇ ਕੱਟੋ',
  'Listeye eklendi': 'ਸੂਚੀ ਵਿੱਚ ਜੋੜਿਆ ਗਿਆ',
  'Listeyi sil?': 'ਸੂਚੀ ਮਿਟਾਉਣੀ?',
  'Sil': 'ਮਿਟਾਓ',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'ਇਹ ਕਦੇ ਨਾ ਦੇਖਿਆ ਮੰਨਿਆ ਜਾਵੇਗਾ ਅਤੇ ਤੇਰੀਆਂ ਸੂਚੀਆਂ ਵਿੱਚੋਂ ਹਟ ਜਾਵੇਗਾ।',
  'Gelecek bölüm bugün': 'ਅਗਲਾ ਐਪੀਸੋਡ ਅੱਜ',
  'Gelecek bölüm {} gün sonra': 'ਅਗਲਾ ਐਪੀਸੋਡ {} ਦਿਨ ਬਾਅਦ',
  'Tema': 'ਥੀਮ',
  'Sistem': 'ਸਿਸਟਮ',
  'Koyu': 'ਡਾਰਕ',
  'Açık': 'ਲਾਈਟ',
  'İzleyenler': 'ਦਰਸ਼ਕ',
  'Yorumunu yaz... (@ ile etiketle)': 'ਆਪਣੀ ਟਿੱਪਣੀ ਲਿਖੋ... (@ ਟੈਗ ਕਰਨ ਲਈ)',
  '@{} bir yorumda seni etiketledi': '@{} ਨੇ ਤੁਹਾਨੂੰ ਇੱਕ ਟਿੱਪਣੀ ਵਿੱਚ ਟੈਗ ਕੀਤਾ',
  'Mesajı sil': 'ਸੁਨੇਹਾ ਮਿਟਾਓ',
  'Mesaj silinemedi': 'ਸੁਨੇਹਾ ਮਿਟਾਇਆ ਨਹੀਂ ਜਾ ਸਕਿਆ',
  'Bağlantı geçersiz veya sayfa bulunamadı': 'ਲਿੰਕ ਗਲਤ ਹੈ ਜਾਂ ਪੰਨਾ ਨਹੀਂ ਮਿਲਿਆ',
  'Keşfet\'e dön': 'ਡਿਸਕਵਰ \'ਤੇ ਵਾਪਸ ਜਾਓ',
  'Düzenle': 'ਸੋਧੋ',
  'Mesajı düzenle': 'ਸੁਨੇਹਾ ਸੋਧੋ',
  'Yanıtlanıyor': 'ਜਵਾਬ ਦੇ ਰਿਹਾ',
  'düzenlendi': 'ਸੋਧਿਆ',
  'Fotoğraf': 'ਫੋਟੋ',
  'Video': 'ਵੀਡੀਓ',
  'İçerik': 'ਸਮੱਗਰੀ',
  'çevrimiçi': 'ਆਨਲਾਈਨ',
  'son görülme {} dk önce': '{} ਮਿੰਟ ਪਹਿਲਾਂ ਵੇਖਿਆ',
  'son görülme {} saat önce': '{} ਘੰਟੇ ਪਹਿਲਾਂ ਵੇਖਿਆ',
  'son görülme {} gün önce': '{} ਦਿਨ ਪਹਿਲਾਂ ਵੇਖਿਆ',
  'Yorumlar yüklenemedi': 'ਟਿੱਪਣੀਆਂ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀਆਂ',
  'Favori': 'ਪਸੰਦੀਦਾ',
  'Listeye ekle': 'ਸੂਚੀ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
  'İçerik paylaş': 'ਸਾਂਝਾ ਕਰੋ',
  'Kapat': 'ਬੰਦ ਕਰੋ',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'ਜੋ ਤੁਸੀਂ ਵੇਖਿਆ ਵਜੋਂ ਨਿਸ਼ਾਨ ਲਗਾਉਂਦੇ ਹੋ ਇੱਥੇ ਇਕੱਠਾ ਹੁੰਦਾ ਹੈ।',
  'Henüz sohbetin yok': 'ਹਾਲੇ ਕੋਈ ਗੱਲਬਾਤ ਨਹੀਂ',
  'Bir profile girip mesaj gönderebilirsin.':
      'ਪ੍ਰੋਫਾਈਲ ਖੋਲ੍ਹੋ ਅਤੇ ਸੁਨੇਹਾ ਭੇਜੋ।',
  'Listeyi sil': 'ਸੂਚੀ ਮਿਟਾਓ',
  'Puan kaydedilemedi': 'ਰੇਟਿੰਗ ਸੰਭਾਲੀ ਨਹੀਂ ਜਾ ਸਕੀ',
  'Nerede İzlenir': 'ਕਿੱਥੇ ਵੇਖੋ',
  'Abonelik': 'ਗਾਹਕੀ',
  'Kirala': 'ਕਿਰਾਏ \'ਤੇ',
  'Satın al': 'ਖਰੀਦੋ',
  'Hoş geldin!': 'ਜੀ ਆਇਆਂ ਨੂੰ!',
  'İzlemek istediğin dizi ve filmleri seç':
      'ਉਹ ਸ਼ੋਅ ਅਤੇ ਫ਼ਿਲਮਾਂ ਚੁਣੋ ਜੋ ਤੁਸੀਂ ਦੇਖਣਾ ਚਾਹੁੰਦੇ ਹੋ',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'ਤੁਹਾਡੀਆਂ ਚੋਣਾਂ ਤੁਹਾਡੀ ਵਾਚਲਿਸਟ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਣਗੀਆਂ',
  'Şimdilik atla': 'ਹੁਣੇ ਛੱਡੋ',
  'Devam et': 'ਜਾਰੀ ਰੱਖੋ',
  '{} ekle': '{} ਸ਼ਾਮਲ ਕਰੋ',
  'Şikayet et': 'ਰਿਪੋਰਟ ਕਰੋ',
  'Engelle': 'ਬਲਾਕ ਕਰੋ',
  'Engeli kaldır': 'ਅਨਬਲਾਕ ਕਰੋ',
  'Kullanıcı engellendi': 'ਵਰਤੋਂਕਾਰ ਬਲਾਕ ਕੀਤਾ',
  'Engel kaldırıldı': 'ਬਲਾਕ ਹਟਾਇਆ',
  'Şikayet sebebi': 'ਰਿਪੋਰਟ ਦਾ ਕਾਰਨ',
  'Spam veya yanıltıcı': 'ਸਪੈਮ ਜਾਂ ਗੁੰਮਰਾਹਕੁੰਨ',
  'Taciz veya nefret söylemi': 'ਪਰੇਸ਼ਾਨੀ ਜਾਂ ਨਫ਼ਰਤੀ ਭਾਸ਼ਣ',
  'Uygunsuz / cinsel içerik': 'ਅਣਉਚਿਤ / ਜਿਨਸੀ ਸਮੱਗਰੀ',
  'Şiddet veya tehlikeli içerik': 'ਹਿੰਸਾ ਜਾਂ ਖ਼ਤਰਨਾਕ ਸਮੱਗਰੀ',
  'Telif hakkı ihlali': 'ਕਾਪੀਰਾਈਟ ਉਲੰਘਣਾ',
  'Şikayetin alındı, teşekkürler': 'ਤੇਰੀ ਰਿਪੋਰਟ ਮਿਲ ਗਈ, ਧੰਨਵਾਦ',
  'Hesabımı Sil': 'ਮੇਰਾ ਖਾਤਾ ਮਿਟਾਓ',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'ਤੇਰਾ ਖਾਤਾ ਅਤੇ ਸਾਰਾ ਡਾਟਾ (ਇਤਿਹਾਸ, ਰੇਟਿੰਗ, ਟਿੱਪਣੀਆਂ, ਸੂਚੀਆਂ, ਸੁਨੇਹੇ) ਪੱਕੇ ਤੌਰ ਤੇ ਮਿਟ ਜਾਵੇਗਾ। ਇਸਨੂੰ ਵਾਪਸ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ।',
  'Şifreni gir': 'ਆਪਣਾ ਪਾਸਵਰਡ ਭਰੋ',
  'Hesabımı kalıcı sil': 'ਮੇਰਾ ਖਾਤਾ ਪੱਕੇ ਤੌਰ ਤੇ ਮਿਟਾਓ',
  'Sesli mesaj': 'ਵੌਇਸ ਸੁਨੇਹਾ',
  'Ses gönderilemedi': 'ਵੌਇਸ ਸੁਨੇਹਾ ਨਹੀਂ ਭੇਜਿਆ ਜਾ ਸਕਿਆ',
  'Kaydediliyor…': 'ਰਿਕਾਰਡ ਹੋ ਰਿਹਾ ਹੈ…',
  'Ses oynatılamadı': 'ਆਡੀਓ ਚਲਾਇਆ ਨਹੀਂ ਜਾ ਸਕਿਆ',
  'Oynat': 'ਚਲਾਓ',
  'Duraklat': 'ਰੋਕੋ',
  'Liste görünümü': 'ਸੂਚੀ ਦ੍ਰਿਸ਼',
  'Takvim görünümü': 'ਕੈਲੰਡਰ ਦ੍ਰਿਸ਼',
  'Önceki ay': 'ਪਿਛਲਾ ਮਹੀਨਾ',
  'Sonraki ay': 'ਅਗਲਾ ਮਹੀਨਾ',
  'Bu gün bölüm yok': 'ਇਸ ਦਿਨ ਕੋਈ ਕਿਸ਼ਤ ਨਹੀਂ',
  'Gizlilik Politikası': 'ਪਰਦੇਦਾਰੀ ਨੀਤੀ',
  'Son güncelleme: {}': 'ਆਖਰੀ ਅੱਪਡੇਟ: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'ਇਹ ਨੀਤੀ ਦੱਸਦੀ ਹੈ ਕਿ dizi.jpg ਐਪ ਅਤੇ dizijpg.com ਸਾਈਟ ਵਰਤਣ ਵੇਲੇ ਕਿਹੜਾ ਡਾਟਾ ਇਕੱਠਾ ਹੁੰਦਾ ਹੈ, ਕਿਵੇਂ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ ਅਤੇ ਤੇਰੇ ਹੱਕ ਕੀ ਹਨ।',
  'Topladığımız Veriler': 'ਅਸੀਂ ਇਕੱਠਾ ਕਰਦੇ ਡਾਟਾ',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'ਖਾਤਾ: ਈਮੇਲ ਪਤਾ, ਯੂਜ਼ਰਨੇਮ ਅਤੇ ਪਾਸਵਰਡ। ਪਾਸਵਰਡ ਵਾਪਸ ਨਾ ਪੜ੍ਹੇ ਜਾ ਸਕਣ ਵਾਲੇ ਹੈਸ਼ ਰੂਪ ਵਿੱਚ ਰੱਖੇ ਜਾਂਦੇ ਹਨ; ਮਹਿਮਾਨ ਖਾਤੇ ਬਿਨਾਂ ਈਮੇਲ ਵੀ ਵਰਤੇ ਜਾ ਸਕਦੇ ਹਨ।',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'ਪ੍ਰੋਫਾਈਲ: ਅਵਤਾਰ, ਕਵਰ ਤਸਵੀਰ, ਬਾਇਓ ਅਤੇ ਦੇਸ਼ ਵਰਗੀ ਜਾਣਕਾਰੀ ਜੋ ਤੂੰ ਖੁਦ ਜੋੜਨੀ ਚੁਣੇਂ।',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'ਵਰਤੋਂ: ਤੇਰਾ ਦੇਖਣ ਦਾ ਇਤਿਹਾਸ, ਰੇਟਿੰਗ, ਟਿੱਪਣੀਆਂ, ਸੂਚੀਆਂ, ਰਿਐਕਸ਼ਨ ਅਤੇ ਮਨਪਸੰਦ।',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'ਸੁਨੇਹੇ: ਤੇਰੇ ਲਿਖਤੀ, ਤਸਵੀਰੀ ਅਤੇ ਆਵਾਜ਼ੀ ਸੁਨੇਹੇ ਸਾਡੇ ਸਰਵਰਾਂ \'ਤੇ ਰੱਖੇ ਜਾਂਦੇ ਹਨ। ਸੁਨੇਹੇ ਐਂਡ-ਟੂ-ਐਂਡ ਇਨਕ੍ਰਿਪਟਡ ਨਹੀਂ ਹਨ; ਸਿਰਫ਼ ਰਿਪੋਰਟ ਹੋਣ \'ਤੇ ਮੋਡਰੇਸ਼ਨ ਲਈ ਵੇਖੇ ਜਾਂਦੇ ਹਨ।',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'ਅੱਪਲੋਡ ਕੀਤਾ ਮੀਡੀਆ: ਪ੍ਰੋਫਾਈਲ, ਟਿੱਪਣੀਆਂ ਅਤੇ ਸੁਨੇਹਿਆਂ ਵਿੱਚ ਜੋੜੀਆਂ ਫੋਟੋਆਂ, GIF, ਵੀਡੀਓ ਅਤੇ ਆਵਾਜ਼ੀ ਰਿਕਾਰਡਿੰਗਾਂ।',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'ਤਕਨੀਕੀ: IP ਪਤਾ, ਅੰਦਾਜ਼ਨ ਟਿਕਾਣਾ (ਦੇਸ਼/ਸ਼ਹਿਰ ਪੱਧਰ), ਡਿਵਾਈਸ ਪਲੇਟਫਾਰਮ, ਐਪ ਵਰਜ਼ਨ ਅਤੇ ਐਰਰ ਲਾਗ। ਇਹ ਸੁਰੱਖਿਆ ਅਤੇ ਖਾਮੀਆਂ ਠੀਕ ਕਰਨ ਲਈ ਰੱਖੇ ਜਾਂਦੇ ਹਨ।',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'ਸੂਚਨਾਵਾਂ: ਪੁਸ਼ ਸੂਚਨਾਵਾਂ ਲਈ ਤੇਰੇ ਡਿਵਾਈਸ ਦਾ ਟੋਕਨ ਅਤੇ ਭਾਸ਼ਾ ਦੀ ਪਸੰਦ ਰੱਖੀ ਜਾਂਦੀ ਹੈ। ਡਿਵਾਈਸ ਦੀਆਂ ਸੈਟਿੰਗਾਂ ਵਿੱਚੋਂ ਕਦੇ ਵੀ ਸੂਚਨਾਵਾਂ ਬੰਦ ਕਰ ਸਕਦਾ ਹੈਂ।',
  'Verileri Nasıl Kullanırız': 'ਅਸੀਂ ਡਾਟਾ ਕਿਵੇਂ ਵਰਤਦੇ ਹਾਂ',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'ਤੇਰਾ ਡਾਟਾ ਸਿਰਫ਼ ਸੇਵਾ ਦੇਣ, ਖਾਤਾ ਸੁਰੱਖਿਅਤ ਰੱਖਣ, ਸੂਚਨਾਵਾਂ ਭੇਜਣ, ਖਾਮੀਆਂ ਠੀਕ ਕਰਨ ਅਤੇ ਦੁਰਵਰਤੋਂ ਰੋਕਣ ਲਈ ਵਰਤਦੇ ਹਾਂ। ਅਸੀਂ ਤੇਰਾ ਡਾਟਾ ਨਾ ਵੇਚਦੇ ਹਾਂ, ਨਾ ਇਸ਼ਤਿਹਾਰਬਾਜ਼ੀ ਲਈ ਕਿਸੇ ਨਾਲ ਸਾਂਝਾ ਕਰਦੇ ਹਾਂ।',
  'Çerezler ve Yerel Depolama': 'ਕੂਕੀਜ਼ ਅਤੇ ਲੋਕਲ ਸਟੋਰੇਜ',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'ਲੋਕਲ ਸਟੋਰੇਜ ਸਿਰਫ਼ ਤੈਨੂੰ ਲਾਗਇਨ ਰੱਖਣ ਅਤੇ ਭਾਸ਼ਾ/ਥੀਮ ਵਰਗੀਆਂ ਪਸੰਦਾਂ ਯਾਦ ਰੱਖਣ ਲਈ ਵਰਤੀ ਜਾਂਦੀ ਹੈ। ਕੋਈ ਇਸ਼ਤਿਹਾਰੀ ਜਾਂ ਟ੍ਰੈਕਿੰਗ ਕੂਕੀ ਨਹੀਂ ਹੈ।',
  'Üçüncü Taraf Hizmetler': 'ਤੀਜੀ-ਧਿਰ ਸੇਵਾਵਾਂ',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'ਸੀਰੀਜ਼ ਅਤੇ ਫਿਲਮਾਂ ਦਾ ਡਾਟਾ TMDB ਤੋਂ ਅਤੇ ਸਟ੍ਰੀਮਿੰਗ ਪਲੇਟਫਾਰਮਾਂ ਦੀ ਜਾਣਕਾਰੀ JustWatch ਤੋਂ ਆਉਂਦੀ ਹੈ। ਪੁਸ਼ ਸੂਚਨਾਵਾਂ Google Firebase ਰਾਹੀਂ ਪਹੁੰਚਦੀਆਂ ਹਨ ਅਤੇ ਸਾਈਟ ਦੇ ਟ੍ਰੈਫਿਕ ਦੀ ਰਾਖੀ Cloudflare ਕਰਦਾ ਹੈ। ਇਨ੍ਹਾਂ ਸੇਵਾਵਾਂ \'ਤੇ ਉਨ੍ਹਾਂ ਦੀਆਂ ਆਪਣੀਆਂ ਪਰਦੇਦਾਰੀ ਨੀਤੀਆਂ ਲਾਗੂ ਹੁੰਦੀਆਂ ਹਨ।',
  'Saklama ve Silme': 'ਸੰਭਾਲ ਅਤੇ ਮਿਟਾਉਣਾ',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'ਤੇਰਾ ਡਾਟਾ ਓਨਾ ਚਿਰ ਰਹਿੰਦਾ ਹੈ ਜਿੰਨਾ ਚਿਰ ਤੇਰਾ ਖਾਤਾ ਹੈ। ਸੈਟਿੰਗਾਂ ਵਿੱਚ "ਮੇਰਾ ਖਾਤਾ ਮਿਟਾਓ" ਨਾਲ ਖਾਤਾ ਹਮੇਸ਼ਾ ਲਈ ਮਿਟਾ ਸਕਦਾ ਹੈਂ; ਡਾਟਾ ਤੁਰੰਤ ਅਤੇ ਬੈਕਅੱਪ ਦੀਆਂ ਕਾਪੀਆਂ ਵੱਧ ਤੋਂ ਵੱਧ 14 ਦਿਨਾਂ ਵਿੱਚ ਮਿਟ ਜਾਂਦੀਆਂ ਹਨ। ਐਰਰ ਲਾਗ 30 ਦਿਨਾਂ ਬਾਅਦ ਆਪੇ ਮਿਟ ਜਾਂਦੇ ਹਨ।',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'ਸੈਟਿੰਗਾਂ ਵਿੱਚੋਂ ਆਪਣਾ ਡਾਟਾ ZIP ਰੂਪ ਵਿੱਚ ਨਿਰਯਾਤ ਕਰ ਸਕਦਾ ਹੈਂ; ਆਰਕਾਈਵ ਤੇਰੇ ਈਮੇਲ ਪਤੇ \'ਤੇ ਭੇਜਿਆ ਜਾਂਦਾ ਹੈ।',
  'Güvenlik': 'ਸੁਰੱਖਿਆ',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'ਡਾਟਾ ਇਨਕ੍ਰਿਪਟਡ ਕਨੈਕਸ਼ਨਾਂ (HTTPS) ਰਾਹੀਂ ਜਾਂਦਾ ਹੈ ਅਤੇ ਸੀਮਤ ਪਹੁੰਚ ਵਾਲੇ ਸਰਵਰਾਂ \'ਤੇ ਰੱਖਿਆ ਜਾਂਦਾ ਹੈ।',
  'Çocukların Gizliliği': 'ਬੱਚਿਆਂ ਦੀ ਪਰਦੇਦਾਰੀ',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg 13 ਸਾਲ ਤੋਂ ਛੋਟੇ ਬੱਚਿਆਂ ਲਈ ਨਹੀਂ ਹੈ।',
  'Hakların': 'ਤੇਰੇ ਹੱਕ',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK ਅਤੇ GDPR ਤਹਿਤ ਤੈਨੂੰ ਆਪਣੇ ਡਾਟੇ ਤੱਕ ਪਹੁੰਚ, ਸੁਧਾਰ, ਮਿਟਾਉਣ ਅਤੇ ਤਬਦੀਲ ਕਰਨ ਦਾ ਹੱਕ ਹੈ। ਇਸ ਲਈ ਸਾਨੂੰ ਲਿਖ: {}',
  'Değişiklikler': 'ਤਬਦੀਲੀਆਂ',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'ਇਹ ਨੀਤੀ ਬਦਲੇ ਤਾਂ ਨਵਾਂ ਰੂਪ ਇਸੇ ਪੰਨੇ \'ਤੇ ਪ੍ਰਕਾਸ਼ਿਤ ਹੋਵੇਗਾ ਅਤੇ ਤਾਰੀਖ ਅੱਪਡੇਟ ਹੋਵੇਗੀ।',
  'Kayıt olarak {} kabul etmiş olursun.': 'ਰਜਿਸਟਰ ਕਰਕੇ ਤੂੰ {} ਸਵੀਕਾਰ ਕਰਦਾ ਹੈਂ।',
  'Kullanıcılar': 'ਵਰਤੋਂਕਾਰ',
  'Fotoğrafı değiştir': 'ਫੋਟੋ ਬਦਲੋ',
  'Yeniden konumlandır': 'ਮੁੜ ਸੈੱਟ ਕਰੋ',
  'Bir şeyler ters gitti': 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ',
  'Sosyal Bağlantılar': 'ਸੋਸ਼ਲ ਲਿੰਕ',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'ਤੇਰੀ ਪ੍ਰੋਫਾਈਲ \'ਤੇ ਵੱਧ ਤੋਂ ਵੱਧ 3 ਲਿੰਕ ਦਿਖਦੇ ਹਨ।',
  'Platform seç': 'ਪਲੇਟਫਾਰਮ ਚੁਣ',
  'Kullanıcı adın': 'ਤੇਰਾ ਯੂਜ਼ਰਨੇਮ',
  'Ekle': 'ਜੋੜੋ',
  'Kaldır': 'ਹਟਾਓ',
  'Kopyalandı: {}': 'ਕਾਪੀ ਹੋ ਗਿਆ: {}',
  'Geçersiz kullanıcı adı': 'ਗਲਤ ਯੂਜ਼ਰਨੇਮ',
  'Bağlantı ekle': 'ਲਿੰਕ ਜੋੜੋ',
  'Spoiler olabilir — dokun ve gör': 'ਸਪੌਇਲਰ ਹੋ ਸਕਦਾ ਹੈ — ਦੇਖਣ ਲਈ ਟੈਪ ਕਰੋ',
  'Beğeni': 'ਲਾਈਕ',
  'Görüntülenme': 'ਵਿਊ',
  'Tam ekran': 'ਫੁੱਲ ਸਕ੍ਰੀਨ',
  'Sonuç bulunamadı': 'ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ ਮਿਲਿਆ',
  'Dizi ve Filmler': 'ਸੀਰੀਜ਼ ਅਤੇ ਫਿਲਮਾਂ',
  'Kişiler': 'ਵਿਅਕਤੀ',
  'Ana Sayfa': 'ਹੋਮ',
  'Paylaş': 'ਸਾਂਝਾ ਕਰੋ',
  'Yanıtlar': 'ਜਵਾਬ',
  'Yaklaşan Bölümler': 'ਆਉਣ ਵਾਲੇ ਐਪੀਸੋਡ',
  'Yetişme Listesi': 'ਕੈਚ-ਅੱਪ ਸੂਚੀ',
  'Şunu mu demek istedin': 'ਕੀ ਤੁਹਾਡਾ ਮਤਲਬ ਸੀ',
  'Spoiler': 'ਸਪੌਇਲਰ',
  'Spoiler — dokun ve gör': 'ਸਪੌਇਲਰ — ਵੇਖਣ ਲਈ ਟੈਪ ਕਰੋ',
  'uyum': 'ਮੇਲ',
  'Uyum': 'ਮੇਲ',
  '{} ortak dizi': '{} ਸਾਂਝੀਆਂ ਸੀਰੀਜ਼',
  '{} ortak film': '{} ਸਾਂਝੀਆਂ ਫ਼ਿਲਮਾਂ',
  'Bildirim Tercihleri': 'ਸੂਚਨਾ ਤਰਜੀਹਾਂ',
  'Beğeniler': 'ਪਸੰਦਾਂ',
  'Yeni takipçiler': 'ਨਵੇਂ ਫਾਲੋਅਰ',
  'Etiketlenmeler': 'ਜ਼ਿਕਰ',
  'Yeniden izledim': 'ਦੁਬਾਰਾ ਦੇਖਿਆ',
  '{}. kez izlendi': '{} ਵਾਰ ਦੇਖਿਆ',
  'Gönderi bulunamadı': 'ਪੋਸਟ ਨਹੀਂ ਮਿਲੀ',
  'Gözat': 'ਬ੍ਰਾਊਜ਼ ਕਰੋ',
  'Diziler': 'ਸੀਰੀਜ਼',
  'Filmler': 'ਫ਼ਿਲਮਾਂ',
  'Tümü': 'ਸਭ',
  'Farklı bir tür seç.': 'ਹੋਰ ਸ਼ੈਲੀ ਅਜ਼ਮਾਓ।',
  'Gizlilik': 'ਪਰਦੇਦਾਰੀ',
  'İzlediklerimi gizle': 'ਮੇਰਾ ਦੇਖਿਆ ਲੁਕਾਓ',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'ਤੇਰੀਆਂ ਦੇਖੀਆਂ ਸੀਰੀਜ਼ ਅਤੇ ਫ਼ਿਲਮਾਂ ਤੇਰੀ ਪ੍ਰੋਫ਼ਾਈਲ \'ਤੇ ਨਹੀਂ ਦਿਸਣਗੀਆਂ',
  'Yorumlarımı gizle': 'ਮੇਰੀਆਂ ਟਿੱਪਣੀਆਂ ਲੁਕਾਓ',
  'Profilinde yorumların görünmez':
      'ਤੇਰੀਆਂ ਟਿੱਪਣੀਆਂ ਤੇਰੀ ਪ੍ਰੋਫ਼ਾਈਲ \'ਤੇ ਨਹੀਂ ਦਿਸਣਗੀਆਂ',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'ਕਿਸੇ ਇੱਕ ਸੀਰੀਜ਼ ਜਾਂ ਫ਼ਿਲਮ ਨੂੰ ਉਸਦੇ ਪੇਜ \'ਤੇ "ਮੇਰੀ ਪ੍ਰੋਫ਼ਾਈਲ ਵਿੱਚ ਲੁਕਾਓ" ਚਿੱਪ ਨਾਲ ਲੁਕਾ ਸਕਦੇ ਹੋ।',
  'Geri Bildirim': 'ਫੀਡਬੈਕ',
  'Uygulama hakkında görüş ve önerini yaz...':
      'ਐਪ ਬਾਰੇ ਆਪਣੀ ਰਾਏ ਅਤੇ ਸੁਝਾਅ ਲਿਖੋ...',
  'Teşekkürler! Geri bildirimin alındı.': 'ਧੰਨਵਾਦ! ਤੇਰਾ ਫੀਡਬੈਕ ਮਿਲ ਗਿਆ।',
  'Profilimde gizle': 'ਮੇਰੀ ਪ੍ਰੋਫ਼ਾਈਲ ਵਿੱਚ ਲੁਕਾਓ',
  'Yorumları': 'ਇਸ ਬਾਰੇ ਕਮੈਂਟ',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'ਇਸ ਵਰਤੋਂਕਾਰ ਨੇ ਹਾਲੇ ਕੁਝ ਨਹੀਂ ਦੇਖਿਆ।',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'ਇਹ ਵਰਤੋਂਕਾਰ ਆਪਣੀਆਂ ਟਿੱਪਣੀਆਂ ਲੁਕਾ ਕੇ ਰੱਖਣਾ ਪਸੰਦ ਕਰਦਾ ਹੈ।',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'ਡੇਟਾ: JustWatch',
  'Web Sitesi': 'ਵੈੱਬਸਾਈਟ',
  'Diğer uygulamalar': 'ਹੋਰ ਐਪਸ',
  'Bağlantıyı kopyala': 'ਲਿੰਕ ਕਾਪੀ ਕਰੋ',
  'Henüz kimseyi takip etmiyorsun.': 'ਤੂੰ ਹਾਲੇ ਕਿਸੇ ਨੂੰ ਫਾਲੋ ਨਹੀਂ ਕਰਦਾ।',
  'Çevir': 'ਅਨੁਵਾਦ ਕਰੋ',
  'Orijinali göster': 'ਅਸਲ ਦਿਖਾਓ',
  'Çeviriyi göster': 'ਅਨੁਵਾਦ ਦਿਖਾਓ',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'ਇਸ ਮਹੀਨੇ ਪ੍ਰਸਾਰਣ ਤਾਰੀਖ਼ ਐਲਾਨੀ ਗਈ ਕੋਈ ਕੜੀ ਨਹੀਂ। ਤਾਰੀਖ਼ਾਂ ਆਮ ਤੌਰ \'ਤੇ ਕੁਝ ਹਫ਼ਤੇ ਪਹਿਲਾਂ ਦੱਸੀਆਂ ਜਾਂਦੀਆਂ ਹਨ ਅਤੇ ਫਿਰ ਇੱਥੇ ਦਿਸਣਗੀਆਂ।',
  'devamı': 'ਹੋਰ',
  'Google ile devam et': 'Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
  'Google girişi başarısız': 'Google ਸਾਈਨ-ਇਨ ਅਸਫਲ ਰਿਹਾ',
  'Veri tasarrufu': 'ਡਾਟਾ ਬਚਤ',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi ਤੇ ਡਾਟਾ ਬਚਤ',
  'Mobil veride veri tasarrufu': 'ਮੋਬਾਈਲ ਡਾਟੇ ਤੇ ਡਾਟਾ ਬਚਤ',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'ਚਾਲੂ ਹੋਣ ਤੇ ਫੋਟੋਆਂ ਪਹਿਲਾਂ ਤੋਂ ਡਾਊਨਲੋਡ ਨਹੀਂ ਹੁੰਦੀਆਂ, ਸਿਰਫ਼ ਉਹੀ ਤਸਵੀਰ ਲੋਡ ਹੁੰਦੀ ਹੈ ਜੋ ਤੂੰ ਵੇਖ ਰਿਹਾ ਹੈਂ।',
  'Çocuk güvenliği': 'ਬੱਚਿਆਂ ਦੀ ਸੁਰੱਖਿਆ',
  'Türk Filmleri': 'ਤੁਰਕੀ ਫਿਲਮਾਂ',
  'En Yüksek Puanlı Filmler': 'ਸਭ ਤੋਂ ਵੱਧ ਰੇਟਿੰਗ ਵਾਲੀਆਂ ਫਿਲਮਾਂ',
  'En Yüksek Puanlı Diziler': 'ਸਭ ਤੋਂ ਵੱਧ ਰੇਟਿੰਗ ਵਾਲੀਆਂ ਸੀਰੀਜ਼',
  'En Çok İzlenen Filmler': 'ਸਭ ਤੋਂ ਵੱਧ ਵੇਖੀਆਂ ਫਿਲਮਾਂ',
  'Popüler Diziler': 'ਪ੍ਰਸਿੱਧ ਸੀਰੀਜ਼',
  'En Çok Kazanan Filmler': 'ਸਭ ਤੋਂ ਵੱਧ ਕਮਾਈ ਵਾਲੀਆਂ ਫਿਲਮਾਂ',
  'Kült Filmler': 'ਕਲਟ ਫਿਲਮਾਂ',
  'Yeni Filmler': 'ਨਵੀਆਂ ਫਿਲਮਾਂ',
  'Yorum yap': 'ਟਿੱਪਣੀ ਕਰੋ',
  'Henüz yorum yok': 'ਹਾਲੇ ਕੋਈ ਟਿੱਪਣੀ ਨਹੀਂ',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'ਸੀਰੀਜ਼ ਅਤੇ ਫਿਲਮਾਂ ਉੱਤੇ ਤੇਰੀਆਂ ਟਿੱਪਣੀਆਂ ਇੱਥੇ ਇਕੱਠੀਆਂ ਹੁੰਦੀਆਂ ਹਨ।',
};
