/// Otomatik üretilen çeviri haritası (pl).
const Map<String, String> cevirilerPl = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Nie znaleziono rozpoznanych danych do importu.',
  'Arama': 'Szukaj',
  'Aramaya başla': 'Zacznij szukać',
  'Ayarlar': 'Ustawienia',
  'Bağla': 'Połącz',
  'Bio': 'Bio',
  'Bitirdim': 'Ukończone',
  'Bunları da Beğenebilirsin': 'To też może ci się spodobać',
  'Bölüm': 'Odcinek',
  'Bıraktım': 'Porzucone',
  'Dil': 'Język',
  'Dil ara...': 'Szukaj języka...',
  'Dizi': 'Serial',
  'Dizi ve filmlerini takip et': 'Śledź swoje seriale i filmy',
  'Dizi yorumu': 'Komentarz do serialu',
  'Dizi, film veya kişi ara...': 'Szukaj serialu, filmu lub osoby...',
  'Dosya en fazla 30MB olabilir': 'Plik może mieć maks. 30 MB',
  'Dosya en fazla {}MB olabilir': 'Plik może mieć maks. {} MB',
  'E-posta': 'E-mail',
  'E-posta veya kullanıcı adı': 'E-mail lub nazwa użytkownika',
  'En az 2 harf yaz': 'Wpisz co najmniej 2 litery',
  'Film': 'Film',
  'Film yorumu': 'Komentarz do filmu',
  'Fotoğraf / video ekle': 'Dodaj zdjęcie / wideo',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Zdjęcie lub GIF — awatar i okładka',
  'Giriş Yap': 'Zaloguj się',
  'Gönder': 'Wyślij',
  'Gönderildi': 'Wysłano',
  'Haftanın Dizileri': 'Seriale tygodnia',
  'Haftanın Filmleri': 'Filmy tygodnia',
  'Henüz izleme kaydın yok': 'Nie masz jeszcze historii oglądania',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Nie masz jeszcze list — utwórz w zakładce Profil.',
  'Henüz yorum yok.': 'Brak komentarzy.',
  'Hesabın bağlandı!': 'Konto połączone!',
  'Hesabın yok mu? Kayıt ol': 'Nie masz konta? Zarejestruj się',
  'Hesabını Bağla': 'Połącz konto',
  'Hesap Oluştur': 'Utwórz konto',
  'Kapak resmi ekle': 'Dodaj okładkę',
  'Kaydet': 'Zapisz',
  'Kendinden bahset...': 'Opowiedz coś o sobie...',
  'Keşfet': 'Odkrywaj',
  'Kimseyi takip etmiyor': 'Nie obserwuje nikogo',
  'Kişi ara': 'Szukaj osób',
  'Kişi yorumu': 'Komentarz o osobie',
  'Konuk Oyuncular': 'Aktorzy gościnni',
  'Kullanıcı adı (küçük harf)': 'Nazwa użytkownika (małe litery)',
  'Kullanıcı adı ara...': 'Szukaj nazwy użytkownika...',
  'Liste adı': 'Nazwa listy',
  'Listeye Ekle': 'Dodaj do listy',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Jesteś na koncie gościa — połącz je z e-mailem, nie strać swoich danych!',
  'Misafir olarak devam et': 'Kontynuuj jako gość',
  'Oluştur': 'Utwórz',
  'Oyuncular': 'Obsada',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil zapisany',
  'Puanla': 'Oceń',
  'Puanı Sil': 'Usuń ocenę',
  'Puanın': 'Twoja ocena',
  'Sezonlar': 'Sezony',
  'Sunucu hatası ({})': 'Błąd serwera ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Komentarz do S{}E{}',
  'Takibi Bırak': 'Przestań obserwować',
  'Takip': 'Obserwowani',
  'Takip Edilenler': 'Obserwowani',
  'Takip Et': 'Obserwuj',
  'Takipçi': 'Obserwujący',
  'Takipçi yok': 'Brak obserwujących',
  'Takipçiler': 'Obserwujący',
  'Takvim': 'Kalendarz',
  'Tamam': 'OK',
  'Tekrar Dene': 'Spróbuj ponownie',
  'Tekrar dene': 'Spróbuj jeszcze raz',
  'Toplam ekran süresi': 'Łączny czas przed ekranem',
  'Tüm Zamanların En İyileri': 'Najlepsze wszech czasów',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Pobierz wszystkie swoje dane (obejrzane, oceny, komentarze, listy) jako ZIP zgodny z TV Time albo zaimportuj ZIP z innej aplikacji.',
  'Tümünü Kaldır': 'Usuń wszystkie',
  'Tümünü İzledim': 'Wszystkie obejrzane',
  'Türk Dizileri': 'Tureckie seriale',
  'Veri içe aktar (.zip)': 'Importuj dane (.zip)',
  'Verilerim': 'Moje dane',
  'Verilerimi dışa aktar (e-posta)': 'Eksportuj moje dane (e-mail)',
  'Verilerini dışa aktar': 'Eksportuj swoje dane',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Brak nadchodzących odcinków.\nUstaw serialowi status „Oglądam” na jego stronie i śledź nowe odcinki tutaj.',
  'Yapımları': 'Filmografia',
  'Yeni Diziler': 'Nowe seriale',
  'Yeni Liste': 'Nowa lista',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nowa nazwa użytkownika (opcjonalnie)',
  'Yorum': 'Komentarz',
  'Yorumunu yaz...': 'Napisz komentarz...',
  'Zaten hesabın var mı? Giriş yap': 'Masz już konto? Zaloguj się',
  'ort. {}': 'śr. {}',
  'takip': 'obserwowani',
  'takipçi': 'obserwujący',
  '{} / {} bölüm': '{} / {} odcinków',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} mies.',
  '{} bölüm izlendi': '{} obejrzanych odcinków',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} gün': '{} dni',
  '{} içerik': '{} pozycji',
  '{} içerik · otomatik': '{} pozycji · automatyczna',
  '{} kayıt atlandı (eşleşmedi).': 'Pominięto {} wpisów (brak dopasowania).',
  '{} saat': '{} godz.',
  '{} sezon': '{} sezonów',
  '{} yıl': '{} lat',
  '{}. Bölüm': 'Odcinek {}',
  '{}. Sezon': 'Sezon {}',
  'Çıkış Yap': 'Wyloguj się',
  'Ülke': 'Kraj',
  'Ülke ara...': 'Szukaj kraju...',
  'Ülke seç': 'Wybierz kraj',
  'İlk yorumu sen yaz!': 'Napisz pierwszy komentarz!',
  'İncelemeler': 'Recenzje',
  'İncelemen (isteğe bağlı)': 'Twoja recenzja (opcjonalnie)',
  'İptal': 'Anuluj',
  'İzlediklerim': 'Historia oglądania',
  'İzledim': 'Obejrzane',
  'İzledin': 'Obejrzane',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Twoja historia oglądania i listy zostaną zachowane; teraz możesz logować się z każdego urządzenia.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Twoja historia oglądania, oceny, komentarze i listy zostaną wysłane jako ZIP na zapisany adres e-mail.',
  'İzleyeceğim': 'Obejrzę',
  'İzliyorum': 'Oglądam',
  'İçe aktarım tamamlandı': 'Import zakończony',
  'Şifre': 'Hasło',
  '• profil bilgisi': '• dane profilu',
  '• {} dizi durumu': '• {} statusów seriali',
  '• {} izleme kaydı': '• {} wpisów oglądania',
  '• {} liste': '• {} list',
  '• {} puan': '• {} ocen',
  '• {} yorum': '• {} komentarzy',
  '{}+ yapım': '{}+ produkcji',
  'Yorumlar': 'Komentarze',
  'Yorumlar ({})': 'Komentarze ({})',
  'Yorumları ({})': 'Komentarze ({})',
  'Listelerim': 'Moje listy',
  'Nereden izledin?': 'Gdzie to oglądałeś?',
  'Diziye git': 'Przejdź do serialu',
  'TV / Kanal': 'TV / Kanał',
  'Sinema': 'Kino',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Inne',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Twój feed jest pusty.\nGdy ktoś skomentuje seriale i filmy, które oglądasz, pojawi się tutaj.',
  'Listeleri ({})': 'Listy użytkownika ({})',
  'Liste boş.': 'Ta lista jest pusta.',
  'Yanıtla': 'Odpowiedz',
  '@{} kullanıcısına yanıt veriyorsun': 'Odpowiadasz @{}',
  'İzlediğim Diziler ({})': 'Obejrzane seriale ({})',
  'İzlediğim Filmler ({})': 'Obejrzane filmy ({})',
  'Tümünü gör': 'Zobacz wszystko',
  'Bildirimler': 'Powiadomienia',
  'Henüz bildirim yok': 'Brak powiadomień',
  '@{} yorumuna yanıt verdi': '@{} odpowiedział na twój komentarz',
  '@{} yorumunu beğendi': '@{} polubił twój komentarz',
  '@{} seni takip etti': '@{} zaczął cię obserwować',
  '@{} sana mesaj gönderdi': '@{} wysłał ci wiadomość',
  'Mesajlar': 'Wiadomości',
  'Mesaj': 'Wiadomość',
  'Mesajını yaz...': 'Napisz wiadomość...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Brak czatów.\nOtwórz profil i wyślij wiadomość.',
  'Şifreni mi unuttun?': 'Nie pamiętasz hasła?',
  'Şifreyi Sıfırla': 'Zresetuj hasło',
  'E-postadaki kod': 'Kod z e-maila',
  'Yeni şifre': 'Nowe hasło',
  'Sana Özel': 'Dla ciebie',
  '{} özetin': 'Twoje podsumowanie {}',
  'Yıllık izleme istatistiklerin': 'Twoje roczne statystyki',
  'Rozetler': 'Odznaki',
  'Verdiğin puan': 'Wystawione oceny',
  'Ortalama puanın': 'Twoja średnia ocena',
  'En çok izlediğin diziler': 'Najczęściej oglądane seriale',
  'İlk Bölüm': 'Pierwszy odcinek',
  '100 Bölüm': '100 odcinków',
  '1000 Bölüm': '1000 odcinków',
  'İlk Film': 'Pierwszy film',
  '50 Film': '50 filmów',
  'İlk Yorum': 'Pierwszy komentarz',
  '25 Yorum': '25 komentarzy',
  '10 Puan': '10 ocen',
  'İlk Takipçi': 'Pierwszy obserwujący',
  '10 Dizi Bitirdin': '10 ukończonych seriali',
  'İzlemeyi Bıraktım': 'Przestałem oglądać',
  'İzlediği Diziler ({})': 'Obejrzane seriale ({})',
  'İzlediği Filmler ({})': 'Obejrzane filmy ({})',
  '500 Bölüm': '500 odcinków',
  '5000 Bölüm': '5000 odcinków',
  '10 Film': '10 filmów',
  '100 Film': '100 filmów',
  '100 Yorum': '100 komentarzy',
  '50 Puan': '50 ocen',
  '100 Puan': '100 ocen',
  '10 Takipçi': '10 obserwujących',
  '50 Takipçi': '50 obserwujących',
  '25 Dizi Bitirdin': '25 ukończonych seriali',
  '50 Dizi Bitirdin': '50 ukończonych seriali',
  '10 Beğeni': '10 polubień',
  '100 Beğeni': '100 polubień',
  'yazıyor...': 'pisze...',
  'Profil düzeni': 'Układ profilu',
  'Konumla ve kırp': 'Ustaw i przytnij',
  'Listeye eklendi': 'Dodano do listy',
  'Listeyi sil?': 'Usunąć listę?',
  'Sil': 'Usuń',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Ten tytuł zostanie oznaczony jako nieobejrzany i usunięty z twoich list.',
  'Gelecek bölüm bugün': 'Następny odcinek dzisiaj',
  'Gelecek bölüm {} gün sonra': 'Następny odcinek za {} dni',
};
