/// Otomatik üretilen çeviri haritası (bn).
const Map<String, String> cevirilerBn = {
  'Hepsini gördün, baştan gösteriyoruz':
      'আপনি এটি সব দেখেছেন, আমরা আপনাকে শুরু থেকে দেখাই',
  'Aktarılacak tanınan veri bulunamadı.':
      'ইমপোর্ট করার মতো কোনো ডেটা পাওয়া যায়নি।',
  'Arama': 'সার্চ',
  'Aramaya başla': 'খোঁজা শুরু করো',
  'Son aramalar': 'সাম্প্রতিক অনুসন্ধান',
  'Ayarlar': 'সেটিংস',
  'Bağla': 'লিংক করো',
  'Bio': 'বায়ো',
  'Bitirdim': 'শেষ করেছি',
  'Bunları da Beğenebilirsin': 'এগুলোও ভালো লাগতে পারে',
  'Bölüm': 'এপিসোড',
  'Bıraktım': 'ছেড়ে দিয়েছি',
  'Dil': 'ভাষা',
  'Dil ara...': 'ভাষা খোঁজো...',
  'Dizi': 'সিরিজ',
  'Dizi ve filmlerini takip et': 'তোমার সিরিজ আর সিনেমা ট্র্যাক করো',
  'Dizi yorumu': 'সিরিজ নিয়ে কমেন্ট',
  'Dizi, film veya kişi ara...': 'সিরিজ, সিনেমা বা ব্যক্তি খোঁজো...',
  'Dosya en fazla 30MB olabilir': 'ফাইল সর্বোচ্চ 30MB হতে পারে',
  'Dosya en fazla {}MB olabilir': 'ফাইল সর্বোচ্চ {}MB হতে পারে',
  'E-posta': 'ইমেইল',
  'E-posta veya kullanıcı adı': 'ইমেইল বা ইউজারনেম',
  'En az 2 harf yaz': 'অন্তত 2টা অক্ষর লেখো',
  'Film': 'সিনেমা',
  'Film yorumu': 'সিনেমা নিয়ে কমেন্ট',
  'Fotoğraf / video ekle': 'ছবি / ভিডিও যোগ করো',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'ছবি বা GIF — প্রোফাইল ও কভার ছবি',
  'Giriş Yap': 'লগ ইন করো',
  'Gönder': 'পাঠাও',
  'Gönderildi': 'পাঠানো হয়েছে',
  'Haftanın Dizileri': 'এই সপ্তাহের সিরিজ',
  'Haftanın Filmleri': 'এই সপ্তাহের সিনেমা',
  'Henüz izleme kaydın yok': 'এখনও কোনো দেখার রেকর্ড নেই',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'এখনও কোনো লিস্ট নেই — প্রোফাইল ট্যাব থেকে বানাও।',
  'Henüz yorum yok.': 'এখনও কোনো কমেন্ট নেই।',
  'Hesabın bağlandı!': 'তোমার অ্যাকাউন্ট লিংক হয়ে গেছে!',
  'Hesabın yok mu? Kayıt ol': 'অ্যাকাউন্ট নেই? সাইন আপ করো',
  'Hesabını Bağla': 'তোমার অ্যাকাউন্ট লিংক করো',
  'Hesap Oluştur': 'অ্যাকাউন্ট বানাও',
  'Kapak resmi ekle': 'কভার ছবি যোগ করো',
  'Kaydet': 'সেভ করো',
  'Kendinden bahset...': 'নিজের সম্পর্কে লেখো...',
  'Keşfet': 'ডিসকভার',
  'Kimseyi takip etmiyor': 'কাউকে ফলো করে না',
  'Kişi ara': 'মানুষ খোঁজো',
  'Kişi yorumu': 'ব্যক্তি নিয়ে কমেন্ট',
  'Konuk Oyuncular': 'অতিথি শিল্পী',
  'Kullanıcı adı (küçük harf)': 'ইউজারনেম (ছোট হাতের অক্ষর)',
  'Kullanıcı adı ara...': 'ইউজারনেম খোঁজো...',
  'Liste adı': 'লিস্টের নাম',
  'Listeye Ekle': 'লিস্টে যোগ করো',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'তুমি গেস্ট অ্যাকাউন্টে আছ — ইমেইল দিয়ে লিংক করো, তোমার ডেটা হারিয়ো না!',
  'Misafir olarak devam et': 'গেস্ট হিসেবে চালিয়ে যাও',
  'Oluştur': 'বানাও',
  'Oyuncular': 'কাস্ট',
  'Profil': 'প্রোফাইল',
  'Profil kaydedildi': 'প্রোফাইল সেভ হয়েছে',
  'Puanla': 'রেট করো',
  'Puanı Sil': 'রেটিং মুছে ফেলো',
  'Puanın': 'তোমার রেটিং',
  'Sezonlar': 'সিজন',
  'Sunucu hatası ({})': 'সার্ভার এরর ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'S{}E{} নিয়ে কমেন্ট',
  'Takibi Bırak': 'আনফলো করো',
  'Takip': 'ফলোয়িং',
  'Takip Edilenler': 'ফলো করা হচ্ছে',
  'Takip Et': 'ফলো করো',
  'Takipçi': 'ফলোয়ার',
  'Takipçi yok': 'কোনো ফলোয়ার নেই',
  'Takipçiler': 'ফলোয়াররা',
  'Takvim': 'ক্যালেন্ডার',
  'Tamam': 'ঠিক আছে',
  'Tekrar Dene': 'আবার চেষ্টা করো',
  'Tekrar dene': 'আবার চেষ্টা করো',
  'Toplam İzleme Süresi': 'মোট স্ক্রিন টাইম',
  'Tüm Zamanların En İyileri': 'সর্বকালের সেরা',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'তোমার সব ডেটা (দেখা, রেটিং, কমেন্ট, লিস্ট) TV Time-সামঞ্জস্যপূর্ণ ZIP হিসেবে নাও, অথবা অন্য অ্যাপ থেকে আসা ZIP ইমপোর্ট করো।',
  'Tümünü Kaldır': 'সব সরাও',
  'Tümünü İzledim': 'সব দেখেছি',
  'Türk Dizileri': 'তুর্কি সিরিজ',
  'Veri içe aktar (.zip)': 'ডেটা ইমপোর্ট করো (.zip)',
  'Verilerim': 'আমার ডেটা',
  'Verilerimi dışa aktar (e-posta)': 'আমার ডেটা এক্সপোর্ট করো (ইমেইল)',
  'Verilerini dışa aktar': 'তোমার ডেটা এক্সপোর্ট করো',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'কোনো আসন্ন এপিসোড নেই।\nসিরিজের পেজ থেকে "দেখছি" স্ট্যাটাস দাও, নতুন এপিসোডগুলো এখানে ট্র্যাক করো।',
  'Yapımları': 'ফিল্মোগ্রাফি',
  'Yeni Diziler': 'নতুন সিরিজ',
  'Yeni Liste': 'নতুন লিস্ট',
  'Yeni kullanıcı adı (isteğe bağlı)': 'নতুন ইউজারনেম (ঐচ্ছিক)',
  'Yorum': 'কমেন্ট',
  'Yorumunu yaz...': 'তোমার কমেন্ট লেখো...',
  'Zaten hesabın var mı? Giriş yap': 'আগে থেকেই অ্যাকাউন্ট আছে? লগ ইন করো',
  'ort. {}': 'গড় {}',
  'takip': 'ফলোয়িং',
  'takipçi': 'ফলোয়ার',
  '{} / {} bölüm': '{} / {} এপিসোড',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} মাস',
  '{} ay~tekil': '{} মাস',
  '{} bölüm izlendi': '{}টা এপিসোড দেখা হয়েছে',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} মিনিট',
  '{} dk~tekil': '{} মিনিট',
  '{} gün': '{} দিন',
  '{} gün~tekil': '{} দিন',
  '{} içerik': '{}টা টাইটেল',
  '{} içerik · otomatik': '{}টা টাইটেল · অটোমেটিক',
  '{} kayıt atlandı (eşleşmedi).': '{}টা রেকর্ড বাদ গেছে (মেলেনি)।',
  '{} saat': '{} ঘণ্টা',
  '{} saat~tekil': '{} ঘণ্টা',
  '{} sezon': '{}টা সিজন',
  '{} yıl': '{} বছর',
  '{} yıl~tekil': '{} বছর',
  '{}. Bölüm': 'এপিসোড {}',
  '{}. Sezon': 'সিজন {}',
  'Çıkış Yap': 'লগ আউট করো',
  'Ülke': 'দেশ',
  'Ülke ara...': 'দেশ খোঁজো...',
  'Ülke seç': 'দেশ বেছে নাও',
  'İlk yorumu sen yaz!': 'প্রথম কমেন্টটা তুমিই লেখো!',
  'İncelemeler': 'রিভিউ',
  'İncelemen (isteğe bağlı)': 'তোমার রিভিউ (ঐচ্ছিক)',
  'İptal': 'বাতিল',
  'İzlediklerim': 'আমার দেখা',
  'İzledim': 'দেখেছি',
  'İzledin': 'তুমি দেখেছ',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'তোমার দেখার হিস্ট্রি আর লিস্টগুলো সুরক্ষিত থাকবে; এখন যেকোনো ডিভাইস থেকে ঢুকতে পারবে।',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'তোমার দেখার হিস্ট্রি, রেটিং, কমেন্ট আর লিস্টগুলো ZIP হিসেবে নিবন্ধিত ইমেইল ঠিকানায় পাঠানো হবে।',
  'İzleyeceğim': 'দেখব',
  'İzliyorum': 'দেখছি',
  'İçe aktarım tamamlandı': 'ইমপোর্ট সম্পন্ন হয়েছে',
  'Şifre': 'পাসওয়ার্ড',
  '• profil bilgisi': '• প্রোফাইল তথ্য',
  '• {} dizi durumu': '• {}টা সিরিজ স্ট্যাটাস',
  '• {} izleme kaydı': '• {}টা দেখার রেকর্ড',
  '• {} liste': '• {}টা লিস্ট',
  '• {} puan': '• {}টা রেটিং',
  '• {} yorum': '• {}টা কমেন্ট',
  '{}+ yapım': '{}+ টাইটেল',
  'Yorumlar': 'কমেন্ট',
  'Yorumlar ({})': 'কমেন্ট ({})',
  'Yorumları ({})': 'এটা নিয়ে কমেন্ট ({})',
  'Listelerim': 'আমার লিস্ট',
  'Nereden izledin?': 'কোথায় দেখেছ?',
  'Diziye git': 'শোতে যাও',
  'TV / Kanal': 'টিভি / চ্যানেল',
  'Sinema': 'সিনেমা',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'অন্যান্য',
  'Akış': 'ফিড',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'তোমার ফিড খালি।\nতোমার দেখা শো ও সিনেমায় কেউ কমেন্ট করলে এখানে দেখাবে।',
  'Listeleri ({})': 'তার লিস্ট ({})',
  'Liste boş.': 'এই লিস্টটা খালি।',
  'Yanıtla': 'উত্তর দাও',
  '@{} kullanıcısına yanıt veriyorsun': '@{}-কে উত্তর দিচ্ছ',
  'İzlediğim Diziler ({})': 'আমার দেখা শো ({})',
  'İzlediğim Filmler ({})': 'আমার দেখা সিনেমা ({})',
  'Tümünü gör': 'সব দেখো',
  'Bildirimler': 'বিজ্ঞপ্তি',
  'Henüz bildirim yok': 'এখনো কোনো বিজ্ঞপ্তি নেই',
  '@{} yorumuna yanıt verdi': '@{} তোমার মন্তব্যের উত্তর দিয়েছে',
  '@{} yorumunu beğendi': '@{} তোমার মন্তব্য পছন্দ করেছে',
  '@{} seni takip etti': '@{} তোমাকে অনুসরণ করেছে',
  '@{} sana mesaj gönderdi': '@{} তোমাকে বার্তা পাঠিয়েছে',
  'Mesajlar': 'বার্তা',
  'Mesaj': 'বার্তা',
  'Mesaja eklenecek': 'বার্তায় যোগ করা হবে',
  'Mesajını yaz...': 'বার্তা লেখো...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'এখনো কোনো চ্যাট নেই।\nকোনো প্রোফাইলে গিয়ে বার্তা পাঠাও।',
  'Şifreni mi unuttun?': 'পাসওয়ার্ড ভুলে গেছ?',
  'Şifreyi Sıfırla': 'পাসওয়ার্ড রিসেট',
  'E-postadaki kod': 'ইমেইলের কোড',
  'Yeni şifre': 'নতুন পাসওয়ার্ড',
  'Sana Özel': 'তোমার জন্য',
  '{} özetin': 'তোমার {} সারাংশ',
  'Yıllık izleme istatistiklerin': 'বার্ষিক দেখার পরিসংখ্যান',
  'Rozetler': 'ব্যাজ',
  'Verdiğin puan': 'দেওয়া রেটিং',
  'Ortalama puanın': 'গড় রেটিং',
  'En çok izlediğin diziler': 'সবচেয়ে বেশি দেখা শো',
  'İlk Bölüm': 'প্রথম পর্ব',
  '100 Bölüm': '১০০ পর্ব',
  '1000 Bölüm': '১০০০ পর্ব',
  'İlk Film': 'প্রথম সিনেমা',
  '50 Film': '৫০ সিনেমা',
  'İlk Yorum': 'প্রথম কমেন্ট',
  '25 Yorum': '২৫ কমেন্ট',
  '10 Puan': '১০ রেটিং',
  'İlk Takipçi': 'প্রথম অনুসারী',
  '10 Dizi Bitirdin': '১০টি শো শেষ',
  'İzlemeyi Bıraktım': 'দেখা ছেড়ে দিয়েছি',
  'İzlediği Diziler ({})': 'তার দেখা শো ({})',
  'İzlediği Filmler ({})': 'তার দেখা সিনেমা ({})',
  '500 Bölüm': '৫০০ পর্ব',
  '5000 Bölüm': '৫০০০ পর্ব',
  '10 Film': '১০ সিনেমা',
  '100 Film': '১০০ সিনেমা',
  '100 Yorum': '১০০ কমেন্ট',
  '50 Puan': '৫০ রেটিং',
  '100 Puan': '১০০ রেটিং',
  '10 Takipçi': '১০ অনুসারী',
  '50 Takipçi': '৫০ অনুসারী',
  '25 Dizi Bitirdin': '২৫টি শো শেষ',
  '50 Dizi Bitirdin': '৫০টি শো শেষ',
  '10 Beğeni': '১০ লাইক',
  '100 Beğeni': '১০০ লাইক',
  'yazıyor...': 'লিখছে...',
  'ses kaydediyor...': 'অডিও রেকর্ড করছে...',
  'Profil düzeni': 'প্রোফাইল লেআউট',
  'Konumla ve kırp': 'অবস্থান ঠিক করে ক্রপ করো',
  'Listeye eklendi': 'লিস্টে যোগ হয়েছে',
  'Listeyi sil?': 'লিস্ট মুছবে?',
  'Sil': 'মুছে ফেলো',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'এটি কখনো দেখা হয়নি বলে চিহ্নিত হবে এবং তোমার লিস্ট থেকে সরবে।',
  'Gelecek bölüm bugün': 'পরের পর্ব আজ',
  'Gelecek bölüm {} gün sonra': 'পরের পর্ব {} দিন পরে',
  'Tema': 'থিম',
  'Sistem': 'সিস্টেম',
  'Koyu': 'ডার্ক',
  'Açık': 'লাইট',
  'İzleyenler': 'দর্শকরা',
  'Yorumunu yaz... (@ ile etiketle)':
      'তোমার কমেন্ট লেখো... (@ দিয়ে ট্যাগ করো)',
  '@{} bir yorumda seni etiketledi': '@{} তোমাকে একটা কমেন্টে ট্যাগ করেছে',
  'Mesajı sil': 'বার্তা মুছে ফেলো',
  'Mesaj silinemedi': 'বার্তা মোছা যায়নি',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'লিঙ্কটি অবৈধ বা পৃষ্ঠা পাওয়া যায়নি',
  "Keşfet'e dön": 'ডিসকভারে ফিরে যাও',
  'Düzenle': 'এডিট',
  'Mesajı düzenle': 'বার্তা এডিট',
  'Yanıtlanıyor': 'উত্তর দেওয়া হচ্ছে',
  'düzenlendi': 'সম্পাদিত',
  'Fotoğraf': 'ছবি',
  'Video': 'ভিডিও',
  'İçerik': 'কনটেন্ট',
  'çevrimiçi': 'অনলাইন',
  'son görülme {} dk önce': '{} মিনিট আগে দেখা',
  'son görülme {} saat önce': '{} ঘণ্টা আগে দেখা',
  'son görülme {} gün önce': '{} দিন আগে দেখা',
  'Yorumlar yüklenemedi': 'কমেন্ট লোড করা যায়নি',
  'Favori': 'প্রিয়',
  'Listeye ekle': 'লিস্টে যোগ করো',
  'İçerik paylaş': 'কনটেন্ট শেয়ার করো',
  'Kapat': 'বন্ধ করো',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'তুমি যা দেখা হিসেবে চিহ্নিত করো, তা এখানে জমতে থাকে।',
  'Henüz sohbetin yok': 'এখনও কোনো কথোপকথন নেই',
  'Bir profile girip mesaj gönderebilirsin.':
      'কোনো প্রোফাইলে গিয়ে বার্তা পাঠাও।',
  'Listeyi sil': 'লিস্ট মুছে ফেলো',
  'Puan kaydedilemedi': 'রেটিং সেভ করা যায়নি',
  'Nerede İzlenir': 'কোথায় দেখবে',
  'Abonelik': 'সাবস্ক্রিপশন',
  'Kirala': 'ভাড়া নাও',
  'Satın al': 'কিনে নাও',
  'Devam et': 'চালিয়ে যাও',
  'Şikayet et': 'রিপোর্ট করো',
  'Engelle': 'ব্লক করো',
  'Engeli kaldır': 'আনব্লক করো',
  'Kullanıcı engellendi': 'ব্যবহারকারী ব্লক করা হয়েছে',
  'Engel kaldırıldı': 'ব্লক সরানো হয়েছে',
  'Şikayet sebebi': 'রিপোর্টের কারণ',
  'Spam veya yanıltıcı': 'স্প্যাম বা বিভ্রান্তিকর',
  'Taciz veya nefret söylemi': 'হয়রানি বা বিদ্বেষমূলক বক্তব্য',
  'Uygunsuz / cinsel içerik': 'অনুপযুক্ত / যৌন কনটেন্ট',
  'Şiddet veya tehlikeli içerik': 'সহিংসতা বা বিপজ্জনক কনটেন্ট',
  'Telif hakkı ihlali': 'কপিরাইট লঙ্ঘন',
  'Şikayetin alındı, teşekkürler': 'তোমার রিপোর্ট পেয়েছি, ধন্যবাদ',
  'Hesabımı Sil': 'আমার অ্যাকাউন্ট মুছুন',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'তোমার অ্যাকাউন্ট এবং সব ডেটা (হিস্ট্রি, রেটিং, কমেন্ট, লিস্ট, মেসেজ) স্থায়ীভাবে মুছে যাবে। এটি ফেরানো যাবে না।',
  'Şifreni gir': 'তোমার পাসওয়ার্ড দাও',
  'Hesabımı kalıcı sil': 'আমার অ্যাকাউন্ট স্থায়ীভাবে মুছুন',
  'Sesli mesaj': 'ভয়েস মেসেজ',
  'Ses gönderilemedi': 'ভয়েস মেসেজ পাঠানো যায়নি',
  'Kaydediliyor…': 'রেকর্ড হচ্ছে…',
  'Ses oynatılamadı': 'অডিও চালানো যায়নি',
  'Oynat': 'চালাও',
  'Fragmanı oynat': 'ট্রেলার চালান',
  'Altyazıyı aç': 'সাবটাইটেল চালু করুন',
  'Altyazıyı kapat': 'সাবটাইটেল বন্ধ করুন',
  '10 saniye ileri': '১০ সেকেন্ড এগিয়ে যান',
  '10 saniye geri': '১০ সেকেন্ড পেছনে যান',
  'Duraklat': 'থামাও',
  'Liste görünümü': 'তালিকা ভিউ',
  'Takvim görünümü': 'ক্যালেন্ডার ভিউ',
  'Önceki ay': 'আগের মাস',
  'Sonraki ay': 'পরের মাস',
  'Bu gün bölüm yok': 'এই দিনে কোনো পর্ব নেই',
  'Gizlilik Politikası': 'গোপনীয়তা নীতি',
  'Son güncelleme: {}': 'সর্বশেষ আপডেট: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'এই নীতিতে ব্যাখ্যা করা হয়েছে dizi.jpg অ্যাপ ও dizijpg.com সাইট ব্যবহারের সময় কোন ডেটা সংগ্রহ করা হয়, কীভাবে ব্যবহার হয় এবং তোমার অধিকারগুলো কী।',
  'Topladığımız Veriler': 'আমরা যে ডেটা সংগ্রহ করি',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'অ্যাকাউন্ট: ইমেইল ঠিকানা, ইউজারনেম ও পাসওয়ার্ড। পাসওয়ার্ড অপরিবর্তনীয় হ্যাশ আকারে রাখা হয়; গেস্ট অ্যাকাউন্ট ইমেইল ছাড়াই ব্যবহার করা যায়।',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'প্রোফাইল: অবতার, কভার ছবি, বায়ো ও দেশের মতো যেসব তথ্য তুমি নিজে যোগ করতে চাও।',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'ব্যবহার: তোমার দেখার ইতিহাস, রেটিং, মন্তব্য, তালিকা, রিঅ্যাকশন ও পছন্দের তালিকা।',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'বার্তা: তোমার লেখা, ছবি ও ভয়েস বার্তা আমাদের সার্ভারে সংরক্ষিত থাকে। বার্তা এন্ড-টু-এন্ড এনক্রিপ্টেড নয়; শুধু রিপোর্ট হলে মডারেশনের জন্য দেখা হয়।',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'আপলোড করা মিডিয়া: প্রোফাইল, মন্তব্য ও বার্তায় যোগ করা ছবি, GIF, ভিডিও ও ভয়েস রেকর্ডিং।',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'প্রযুক্তিগত: IP ঠিকানা, আনুমানিক অবস্থান (দেশ/শহর পর্যায়ে), ডিভাইস প্ল্যাটফর্ম, অ্যাপ সংস্করণ ও এরর লগ। এগুলো নিরাপত্তা ও ত্রুটি সারানোর জন্য রাখা হয়।',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'ব্যবহারের পরিসংখ্যান: কোন ধরনের ডিভাইস, অপারেটিং সিস্টেম ও ব্রাউজার দিয়ে প্রবেশ করা হয়েছে তা মোটা দাগের শ্রেণিতে ভাগ করে দৈনিক মোট গণনায় যোগ করা হয়; ব্রাউজারের পরিচয় নিজে সংরক্ষণ করা হয় না এবং এই সংখ্যাগুলো কোনো ব্যক্তির সঙ্গে যুক্ত করা যায় না।',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'নোটিফিকেশন: পুশ নোটিফিকেশনের জন্য তোমার ডিভাইস টোকেন ও ভাষার পছন্দ রাখা হয়। ডিভাইসের সেটিংস থেকে যেকোনো সময় নোটিফিকেশন বন্ধ করতে পারো।',
  'Verileri Nasıl Kullanırız': 'ডেটা আমরা কীভাবে ব্যবহার করি',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'তোমার ডেটা শুধু সেবা দেওয়া, অ্যাকাউন্ট সুরক্ষা, নোটিফিকেশন পাঠানো, ত্রুটি সারানো ও অপব্যবহার ঠেকানোর জন্য ব্যবহার করি। তোমার ডেটা বিক্রি করি না, বিজ্ঞাপনের জন্য কারও সঙ্গে শেয়ারও করি না।',
  'Çerezler ve Yerel Depolama': 'কুকি ও লোকাল স্টোরেজ',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'লোকাল স্টোরেজ শুধু তোমাকে লগইন রাখা এবং ভাষা/থিমের মতো পছন্দ মনে রাখার জন্য ব্যবহার হয়। কোনো বিজ্ঞাপনী বা ট্র্যাকিং কুকি নেই।',
  'Üçüncü Taraf Hizmetler': 'তৃতীয় পক্ষের সেবা',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'সিরিজ ও সিনেমার ডেটা আসে TMDB থেকে, স্ট্রিমিং প্ল্যাটফর্মের তথ্য JustWatch থেকে। পুশ নোটিফিকেশন Google Firebase-এর মাধ্যমে পৌঁছায় আর সাইটের ট্রাফিক Cloudflare সুরক্ষিত রাখে। এসব সেবার নিজস্ব গোপনীয়তা নীতি প্রযোজ্য।',
  'Saklama ve Silme': 'সংরক্ষণ ও মুছে ফেলা',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'তোমার অ্যাকাউন্ট যতদিন আছে, ডেটাও ততদিন থাকে। সেটিংসের "আমার অ্যাকাউন্ট মুছুন" দিয়ে অ্যাকাউন্ট স্থায়ীভাবে মুছতে পারো; ডেটা সঙ্গে সঙ্গে আর ব্যাকআপের কপি সর্বোচ্চ ১৪ দিনের মধ্যে মুছে যায়। এরর লগ ৩০ দিন পর স্বয়ংক্রিয়ভাবে মুছে যায়।',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'সেটিংস থেকে তোমার ডেটা ZIP আকারে এক্সপোর্ট করতে পারো; আর্কাইভ তোমার ইমেইল ঠিকানায় পাঠানো হয়।',
  'Güvenlik': 'নিরাপত্তা',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'ডেটা এনক্রিপ্টেড সংযোগে (HTTPS) যায় এবং সীমিত প্রবেশাধিকারের সার্ভারে রাখা হয়।',
  'Çocukların Gizliliği': 'শিশুদের গোপনীয়তা',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg ১৩ বছরের কম বয়সী শিশুদের জন্য নয়।',
  'Hakların': 'তোমার অধিকার',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK ও GDPR অনুযায়ী তোমার ডেটায় প্রবেশ, সংশোধন, মুছে ফেলা ও স্থানান্তরের অধিকার আছে। এসবের জন্য আমাদের লেখো: {}',
  'Değişiklikler': 'পরিবর্তন',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'এই নীতি বদলালে নতুন সংস্করণ এই পাতায় প্রকাশ হবে এবং তারিখ আপডেট হবে।',
  'Kayıt olarak {} kabul etmiş olursun.': 'নিবন্ধন করে তুমি {} মেনে নিচ্ছ।',
  'Kullanıcılar': 'ব্যবহারকারী',
  'Fotoğrafı değiştir': 'ছবি বদলাও',
  'Yeniden konumlandır': 'আবার সাজাও',
  'Bir şeyler ters gitti': 'কিছু একটা ভুল হয়েছে',
  'Sosyal Bağlantılar': 'সোশ্যাল লিংক',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'তোমার প্রোফাইলে সর্বোচ্চ ৩টি লিংক দেখা যায়।',
  'Platform seç': 'প্ল্যাটফর্ম বেছে নাও',
  'Kullanıcı adın': 'তোমার ইউজারনেম',
  'Ekle': 'যোগ করো',
  'Kaldır': 'সরাও',
  'Kopyalandı: {}': 'কপি হয়েছে: {}',
  'Geçersiz kullanıcı adı': 'ভুল ইউজারনেম',
  'Bağlantı ekle': 'লিংক যোগ করো',
  'Spoiler olabilir — dokun ve gör': 'স্পয়লার থাকতে পারে — দেখতে ট্যাপ করো',
  'Beğeni': 'লাইক',
  'beğeni': 'লাইক',
  'Beğen': 'লাইক',
  'Görüntülenme': 'ভিউ',
  'görüntülenme': 'ভিউ',
  'Tam ekran': 'ফুলস্ক্রিন',
  'Arama başarısız': 'অনুসন্ধান ব্যর্থ হয়েছে',
  'Sonuç bulunamadı': 'কোনো ফলাফল নেই',
  'Dizi ve Filmler': 'সিরিজ ও সিনেমা',
  'Kişiler': 'ব্যক্তি',
  'Ana Sayfa': 'হোম',
  'Paylaş': 'শেয়ার',
  'Yanıtlar': 'জবাব',
  'Yaklaşan Bölümler': 'আসন্ন পর্ব',
  'Yetişme Listesi': 'ক্যাচ-আপ তালিকা',
  'Şunu mu demek istedin': 'আপনি কি বোঝাতে চেয়েছেন',
  'Spoiler': 'স্পয়লার',
  'Spoiler — dokun ve gör': 'স্পয়লার — দেখতে ট্যাপ করুন',
  'uyum': 'মিল',
  'Uyum': 'মিল',
  '{} ortak dizi': '{}টি সাধারণ সিরিজ',
  '{} ortak film': '{}টি সাধারণ সিনেমা',
  'Bildirim Tercihleri': 'বিজ্ঞপ্তির পছন্দ',
  'Beğeniler': 'লাইক',
  'Yeni takipçiler': 'নতুন অনুসরণকারী',
  'Etiketlenmeler': 'উল্লেখ',
  'Yeniden izledim': 'আবার দেখা হয়েছে',
  '{}. kez izlendi': '{} বার দেখা হয়েছে',
  'Gönderi bulunamadı': 'পোস্ট পাওয়া যায়নি',
  'Gözat': 'ব্রাউজ',
  'Diziler': 'সিরিজ',
  'Filmler': 'সিনেমা',
  'Tümü': 'সব',
  'Farklı bir tür seç.': 'অন্য ধরন চেষ্টা করুন।',
  'Gizlilik': 'গোপনীয়তা',
  'İzlediklerimi gizle': 'আমি যা দেখেছি তা লুকাও',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'তুমি যে সিরিজ ও সিনেমা দেখেছ তা তোমার প্রোফাইলে দেখা যাবে না',
  'Yorumlarımı gizle': 'আমার কমেন্ট লুকাও',
  'Profilinde yorumların görünmez': 'তোমার কমেন্ট তোমার প্রোফাইলে দেখা যাবে না',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'কোনো নির্দিষ্ট সিরিজ বা সিনেমা তার পেজের "আমার প্রোফাইলে লুকাও" চিপ দিয়ে লুকাতে পারো।',
  'Geri Bildirim': 'ফিডব্যাক',
  'Uygulama hakkında görüş ve önerini yaz...':
      'অ্যাপ নিয়ে তোমার মতামত ও পরামর্শ লেখো...',
  'Teşekkürler! Geri bildirimin alındı.':
      'ধন্যবাদ! তোমার ফিডব্যাক পাওয়া গেছে।',
  'Profilimde gizle': 'আমার প্রোফাইলে লুকাও',
  'Yorumları': 'এটা নিয়ে কমেন্ট',
  'Bu kullanıcı henüz bir şey izlememiş.': 'এই ব্যবহারকারী এখনও কিছু দেখেননি।',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'এই ব্যবহারকারী তার কমেন্ট গোপন রাখতে পছন্দ করেন।',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'ডেটা: JustWatch',
  'Web Sitesi': 'ওয়েবসাইট',
  'Diğer uygulamalar': 'অন্যান্য অ্যাপ',
  'Bağlantıyı kopyala': 'লিঙ্ক কপি করুন',
  'Henüz kimseyi takip etmiyorsun.': 'তুমি এখনও কাউকে ফলো করছ না।',
  'Çevir': 'অনুবাদ করুন',
  'Çeviri şu an yapılamadı': 'এখন অনুবাদ করা যাচ্ছে না',
  'Bağlantı açılamadı': 'লিঙ্কটি খোলা যায়নি',
  'Orijinali göster': 'মূলটি দেখাও',
  'Çeviriyi göster': 'অনুবাদ দেখাও',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'এই মাসে ঘোষিত সম্প্রচার তারিখসহ কোনো পর্ব নেই। তারিখ সাধারণত কয়েক সপ্তাহ আগে জানানো হয় এবং তখন এখানে দেখা যাবে।',
  'devamı': 'আরও',
  'Google ile devam et': 'Google দিয়ে চালিয়ে যান',
  'Google girişi başarısız': 'Google সাইন-ইন ব্যর্থ হয়েছে',
  'Veri tasarrufu': 'ডেটা সাশ্রয়',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi তে ডেটা সাশ্রয়',
  'Mobil veride veri tasarrufu': 'মোবাইল ডেটায় ডেটা সাশ্রয়',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'চালু থাকলে ছবি আগে থেকে ডাউনলোড হয় না, শুধু তুমি যেটা দেখছ সেটাই লোড হয়।',
  'Çocuk güvenliği': 'শিশু নিরাপত্তা',
  'Türk Filmleri': 'তুর্কি সিনেমা',
  'En Yüksek Puanlı Filmler': 'সর্বোচ্চ রেটিং পাওয়া সিনেমা',
  'En Yüksek Puanlı Diziler': 'সর্বোচ্চ রেটিং পাওয়া সিরিজ',
  'En Çok İzlenen Filmler': 'সবচেয়ে বেশি দেখা সিনেমা',
  'Popüler Diziler': 'জনপ্রিয় সিরিজ',
  'En Çok Kazanan Filmler': 'সর্বোচ্চ আয় করা সিনেমা',
  'Kült Filmler': 'কাল্ট সিনেমা',
  'Yeni Filmler': 'নতুন সিনেমা',
  'Yorum yap': 'মন্তব্য করুন',
  'Henüz yorum yok': 'এখনো কোনো মন্তব্য নেই',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'সিরিজ ও সিনেমায় লেখা তোমার মন্তব্য এখানে জমা হয়।',
  'GIF ekle': 'GIF যোগ করুন',
  'İlk yorumu sen yaz': 'প্রথম মন্তব্যটি আপনি করুন',
  'Video altyazıları': 'ভিডিও সাবটাইটেল',
  'Videolarda altyazı göster': 'ভিডিওতে সাবটাইটেল দেখান',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'ভিডিওতে বলা বাক্যটি স্ক্রিনে লেখা আছে। পাঠ্যটি অনুবাদ: তুর্কি বক্তৃতায় ইংরেজি, অন্যান্য ভাষায় তুর্কি।',
  'Güncelleme gerekli': 'আপডেট প্রয়োজন',
  'Yeni sürüm var': 'নতুন সংস্করণ এসেছে',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'চালিয়ে যেতে dizi.jpg-এর নতুন সংস্করণ ইনস্টল করুন।',
  'Güncelle': 'আপডেট করুন',
  'Daha sonra': 'পরে',
  'Takvim güncelleniyor': 'ক্যালেন্ডার আপডেট হচ্ছে',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'ক্যালেন্ডার আপডেট করা যায়নি, পুরনো তালিকা দেখানো হচ্ছে',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'কিছু সিরিজ লোড হয়নি, তালিকা অসম্পূর্ণ হতে পারে',
  'Yenile': 'রিফ্রেশ',
  'Devam etmek için giriş yap': 'চালিয়ে যেতে লগ ইন করুন',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'রেটিং দিতে, মন্তব্য করতে এবং নিজের লাইব্রেরি গড়তে একটি ফ্রি অ্যাকাউন্টই যথেষ্ট।',
  'Şimdi değil': 'এখন নয়',
  'Yorum yazmak için giriş yap': 'মন্তব্য লিখতে লগ ইন করুন',
  'Kişilere göndermek için giriş yap': 'মানুষকে পাঠাতে লগ ইন করুন',
  'Beğenenler': 'যারা পছন্দ করেছেন',
  'Henüz beğeni yok': 'এখনো কোনো লাইক নেই',
  'Bu gönderiyi ilk beğenen sen ol': 'এই পোস্টে প্রথম লাইক দিন',
  'Bu gönderiye yanıt': 'এই পোস্টের উত্তর',
  'Spoiler içeren gönderi': 'স্পয়লারযুক্ত পোস্ট',
  'Görsel gönderi': 'ছবি পোস্ট',
  'Bu yorumu profilimde gizle': 'আমার প্রোফাইল থেকে এই কমেন্ট লুকাও',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'কমেন্ট শো এবং সিনেমার পেজে থেকে যায়',
  'Bu yorumu sil': 'এই কমেন্ট মুছে ফেলুন',
  'Yorum profilinde gizlendi': 'কমেন্ট তোমার প্রোফাইল থেকে লুকানো হয়েছে',
  'Geri al': 'পূর্বাবস্থায় ফেরাও',
  'Yorum silinsin mi?': 'কমেন্ট মুছে ফেলবেন?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'এই কমেন্ট সব জায়গা থেকে চিরতরে মুছে যাবে। এটি ফেরানো যাবে না।',
  'Yorum silindi': 'কমেন্ট মুছে ফেলা হয়েছে',
  'Yorum profilinde tekrar görünüyor':
      'কমেন্ট তোমার প্রোফাইলে আবার দেখা যাচ্ছে',
  'Gizlenen yorumun yok': 'তোমার কোনো লুকানো কমেন্ট নেই',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'তোমার প্রোফাইলের কমেন্টস ট্যাবে কোনো পোস্টে চেপে ধরে যেসব কমেন্ট লুকাও, সেগুলো এখানে জমা হয়।',
  'Gizlenen yorumlar': 'লুকানো কমেন্ট',
  'Gönderiye git': 'পোস্টে যাও',
  'Tekrar göster': 'আবার দেখাও',
  'Yanıtlarımı gizle': 'আমার রিপ্লাই লুকাও',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'অন্যদের পোস্টে তুমি যেসব রিপ্লাই লেখো তা শুধু তোমাকেই দেখা যায়',
  'Profilinde gizlediğin yorumları tekrar göster':
      'তোমার প্রোফাইলে লুকানো কমেন্টগুলো আবার দেখাও',
  'Sıralama': 'সাজানো',
  'Önerilen': 'প্রস্তাবিত',
  'Kronolojik': 'কালানুক্রমিক',
  'Gelen mesaj istekleri': 'আসা বার্তা অনুরোধ',
  'Mesaj isteğin yok': 'কোনো বার্তা অনুরোধ নেই',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'আপনি যাদের অনুসরণ করেন না তাদের বার্তা এখানে দেখা যায়।',
  'Çevrimiçi durumumu gizle': 'আমার অনলাইন অবস্থা লুকান',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'অন্যরা বার্তায় আপনার অনলাইন অবস্থা ও শেষ দেখার সময় দেখতে পাবে না',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'আমাদের প্রথম ব্যবহারকারীদের একজন। তার মতামত অ্যাপটিকে আজকের রূপ দিতে সাহায্য করেছে।',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'তুমি আমাদের প্রথম ব্যবহারকারীদের একজন। তোমার মতামত অ্যাপটিকে আজকের রূপ দিতে সাহায্য করেছে।',
  'İleri': 'পরবর্তী',
  'Önceki': 'পূর্ববর্তী',
  'Sonraki': 'পরবর্তী',
  'Seçilen dosya okunamadı': 'নির্বাচিত ফাইল পড়া যায়নি',
  'Video açılamadı': 'ভিডিও খোলা যায়নি',
  'En fazla {} medya seçebilirsin':
      'আপনি সর্বোচ্চ {} মিডিয়া নির্বাচন করতে পারেন',
  'Hiçbir medya yüklenemedi': 'কোনো মিডিয়া আপলোড করা যায়নি',
  'Seçimi kaldır': 'নির্বাচন সরান',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'একটি মন্তব্যে সর্বমোট {} MB মিডিয়া আপলোড করতে পারেন',
  '{} dosya okunamadı': '{} ফাইল পড়া যায়নি',
  '{} medya eklendi, {} yüklenemedi': '{} মিডিয়া যোগ হয়েছে, {} ব্যর্থ',
  'Kırp': 'ক্রপ',
  'Çiz': 'আঁকুন',
  'Metin': 'টেক্সট',
  'Emoji': 'ইমোজি',
  'Yinele': 'রিডু',
  'Daha fazla': 'আরও',
  'Hazırlanıyor…': 'প্রস্তুত হচ্ছে…',
  'Düzenlemeden çık?': 'সম্পাদনা থেকে বেরোবেন?',
  'Yaptığın değişiklikler kaybolacak.': 'আপনার করা পরিবর্তনগুলি হারিয়ে যাবে।',
  'Çık': 'বেরোন',
  'Serbest çizim': 'ফ্রিহ্যান্ড',
  'Ok': 'তীর',
  'Dikdörtgen': 'আয়তক্ষেত্র',
  'Daire': 'বৃত্ত',
  'Bulanıklaştır': 'ব্লার',
  'Pikselleştir': 'পিক্সেলেট',
  'Silgi': 'ইরেজার',
  'Çizgi kalınlığı': 'রেখার পুরুত্ব',
  'Saydamlık': 'অস্বচ্ছতা',
  'Dolgu': 'ফিল',
  'Renk': 'রঙ',
  'Döndür': 'ঘোরান',
  'Yansıt': 'ফ্লিপ',
  'Oran': 'অনুপাত',
  'Sıfırla': 'রিসেট',
  'Serbest': 'ফ্রি',
  'Metin yaz...': 'টেক্সট লিখুন...',
  'Hizala': 'সারিবদ্ধ করুন',
  'Arka plan': 'পটভূমি',
  'Emoji ara...': 'ইমোজি খুঁজুন...',
  'Son kullanılanlar': 'সাম্প্রতিক',
  'İfadeler ve insanlar': 'স্মাইলি ও মানুষ',
  'Hayvanlar ve doğa': 'প্রাণী ও প্রকৃতি',
  'Yiyecek ve içecek': 'খাবার ও পানীয়',
  'Etkinlikler': 'কার্যকলাপ',
  'Seyahat ve yerler': 'ভ্রমণ ও স্থান',
  'Nesneler': 'বস্তু',
  'Semboller': 'প্রতীক',
  'Bayraklar': 'পতাকা',
  'Görseli düzenle': 'ছবি সম্পাদনা করুন',
  'Düzenlendi': 'সম্পাদিত',
  'Düzenlenemedi': 'সম্পাদনা করা যায়নি',
  'Düzenlenen görsel çok büyük': 'সম্পাদিত ছবিটি খুব বড়',
  'Videoyu düzenle': 'ভিডিও সম্পাদনা করুন',
  'Sesi kapat': 'শব্দ বন্ধ করুন',
  'Sesi aç': 'শব্দ চালু করুন',
  'İptal ediliyor…': 'বাতিল করা হচ্ছে…',
  'Bu biraz sürebilir': 'এতে কিছু সময় লাগতে পারে',
  'Video çok büyük': 'ভিডিওটি খুব বড়',
  'Video hazırlanamadı': 'ভিডিও প্রস্তুত করা যায়নি',
  'Başlangıç': 'শুরু',
  'Bitiş': 'শেষ',
  'En çok {} saniye seçebilirsin': 'আপনি সর্বোচ্চ {} সেকেন্ড বেছে নিতে পারেন',
  'Dosya en fazla {} MB olabilir': 'ফাইল সর্বোচ্চ {} MB হতে পারে',
  'Medya ekle': 'মিডিয়া যোগ করুন',
  'Seçili medya kalmadı': 'কোনো মিডিয়া নির্বাচিত নেই',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'আপনার মন্তব্যে যোগ করতে একটি ছবি বা ভিডিও নির্বাচন করুন।',
  'Medya seç': 'মিডিয়া নির্বাচন করুন',
  'Daha fazla ekle': 'আরও যোগ করুন',
  'Medya seçilemedi': 'মিডিয়া নির্বাচন করা যায়নি',
  'Favori oyuncular': 'প্রিয় অভিনেতা',
  'Henüz favori oyuncun yok': 'এখনও কোনো প্রিয় অভিনেতা নেই',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'একজন অভিনেতার পাতা খুলুন এবং উপরে ডানদিকের হৃদয়ে ট্যাপ করুন; এখানে যোগ হবে।',
  '{} yapımdan {} tanesini izledin': '{} টির মধ্যে {} টি দেখেছেন',
  'izledin': 'দেখা হয়েছে',
  'İzlemedin': 'দেখা হয়নি',
  'Yapım bulunamadı': 'কোনো শিরোনাম পাওয়া যায়নি',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'এই ব্যক্তির তালিকাভুক্ত করার মতো সিরিজ বা সিনেমা নেই।',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'আপনার দেখার ইতিহাস আপনার অ্যাকাউন্টের সাথে যুক্ত; এই তালিকা কেবল আপনার।',
  'Hesabın kalıcı olarak askıya alındı':
      'আপনার অ্যাকাউন্ট স্থায়ীভাবে স্থগিত করা হয়েছে',
  'Hesabın geçici olarak askıya alındı':
      'আপনার অ্যাকাউন্ট সাময়িকভাবে স্থগিত করা হয়েছে',
  'Hesabın askıya alındı': 'আপনার অ্যাকাউন্ট স্থগিত',
  'Sebep': 'কারণ',
  'Kalan süre': 'বাকি সময়',
  'Süre dolunca hesabın kendiliğinden açılır':
      'সময় শেষ হলে আপনার অ্যাকাউন্ট নিজে থেকেই খুলে যাবে',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'এই সময়ে আপনি পড়তে পারবেন, তবে পোস্ট, মন্তব্য বা বার্তা পাঠাতে পারবেন না।',
  'Anladım': 'বুঝেছি',
  'Ayrıntı': 'বিস্তারিত',
  '{} dakika': '{} মিনিট',
  'birkaç saniye': 'কয়েক সেকেন্ড',
  'Karara itiraz et': 'এই সিদ্ধান্তে আপিল করুন',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'কেন এই শাস্তি তুলে নেওয়া উচিত তা লিখুন',
  'İtirazını gönder': 'আপনার আপিল পাঠান',
  'İtirazın incelemede': 'আপনার আপিল পর্যালোচনাধীন',
  'İtirazın reddedildi': 'আপনার আপিল বাতিল হয়েছে',
  'İtirazın alındı, inceleniyor': 'আপনার আপিল পাওয়া গেছে, পর্যালোচনা চলছে',
  'İtiraz en az 10 karakter olmalı': 'আপিল কমপক্ষে 10 অক্ষরের হতে হবে',
  'Yükleniyor...': 'লোড হচ্ছে...',
  'Bu bölüme puan ver': 'এই পর্বটি রেট করুন',
  '{} kişi puanladı': '{} জন রেট করেছেন',
  'Bölüm izlendi olarak işaretlendi': 'পর্বটি দেখা হয়েছে হিসেবে চিহ্নিত',
  'Sesli ara': 'ভয়েস কল',
  'Görüntülü ara': 'ভিডিও কল',
  'Çalıyor...': 'রিং হচ্ছে...',
  'Bağlanıyor...': 'সংযোগ হচ্ছে...',
  'Cevapla': 'উত্তর দিন',
  'Reddet': 'প্রত্যাখ্যান',
  'Sessize al': 'মিউট',
  'Hoparlör': 'স্পিকার',
  'Kamerayı kapat': 'ক্যামেরা বন্ধ করুন',
  'Kamerayı çevir': 'ক্যামেরা বদলান',
  'Cevap yok': 'কোনো উত্তর নেই',
  'Arama reddedildi': 'কল প্রত্যাখ্যান করা হয়েছে',
  'Meşgul': 'ব্যস্ত',
  'Bağlanılamadı': 'সংযোগ করা যায়নি',
  'Arama iptal edildi': 'কল বাতিল হয়েছে',
  'Arama geçmişi': 'কল ইতিহাস',
  'Gelen arama': 'ইনকামিং কল',
  'Giden arama': 'আউটগোয়িং কল',
  'Cevapsız arama': 'মিসড কল',
  'Arama şu anda kullanılamıyor': 'কল এখন উপলব্ধ নয়',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'ভিডিও কল এখন বন্ধ, আপনি ভয়েস কল করতে পারেন',
  'Bu kullanıcıyı arayamazsın': 'আপনি এই ব্যবহারকারীকে কল করতে পারবেন না',
  'Aramak için karşılıklı takipleşmelisiniz':
      'কল করতে হলে দুজনকেই একে অপরকে ফলো করতে হবে',
  'Bu kullanıcı şu anda aranamıyor': 'এই ব্যবহারকারীকে এখন কল করা যাচ্ছে না',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'অনেক মিসড কল। {} পরে আবার চেষ্টা করুন',
  'Zaten bir aramadasın': 'আপনি ইতিমধ্যে একটি কলে আছেন',
  'Arama için mikrofon izni gerekiyor': 'কল করতে মাইক্রোফোন অনুমতি প্রয়োজন',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'ভিডিও কলের জন্য ক্যামেরা ও মাইক্রোফোন অনুমতি প্রয়োজন',
  'Arama başlatılamadı': 'কল শুরু করা যায়নি',
  'Kullanıcı bulunamadı': 'ব্যবহারকারী পাওয়া যায়নি',
  'Kendini arayamazsın': 'আপনি নিজেকে কল করতে পারবেন না',
  'Arama artık geçerli değil': 'এই কলটি আর বৈধ নয়',
  'Bu aramanın tarafı değilsin': 'আপনি এই কলের অংশ নন',
  'Arama bulunamadı': 'কল পাওয়া যায়নি',
  'Çok fazla istek, biraz bekle': 'অনেক বেশি অনুরোধ, একটু অপেক্ষা করুন',
  'Bağlantı koptu': 'সংযোগ বিচ্ছিন্ন হয়েছে',
  'Arama süre sınırına ulaştı': 'কল সময়সীমায় পৌঁছেছে',
  'Arama en fazla 4 saat sürebilir': 'একটি কল সর্বোচ্চ 4 ঘণ্টা চলতে পারে',
  'Arama sona erdi': 'কল শেষ হয়েছে',
  'Sesli arama': 'ভয়েস কল',
  'Görüntülü arama': 'ভিডিও কল',
  'Gelen aramalar': 'ইনকামিং কল',
  'Sesli ve görüntülü arama bildirimleri': 'ভয়েস ও ভিডিও কল বিজ্ঞপ্তি',
  '{} sa': '{} ঘ',
  'Sesli ve Görüntülü Aramalar': 'ভয়েস ও ভিডিও কল',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'কলের বিষয়বস্তু কখনও রেকর্ড করা হয় না। অডিও ও ভিডিও ডিভাইসের মধ্যে এন্ড-টু-এন্ড এনক্রিপ্টেড (DTLS-SRTP) অবস্থায় চলে; আমাদের সার্ভার এই ট্রাফিক ডিক্রিপ্ট, শুনতে বা সংরক্ষণ করতে পারে না।',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'শুধু কল মেটাডেটা রাখা হয়: কার সাথে, কোন দিকে, কখন এবং কত সময় ধরে। এই রেকর্ডগুলো 90 দিন পরে স্বয়ংক্রিয়ভাবে মুছে যায়।',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'সরাসরি সংযোগ সম্ভব না হলে অডিও ও ভিডিও এনক্রিপ্টেড অবস্থায় একটি রিলে সার্ভারের (TURN) মধ্য দিয়ে যায়। রিলে সার্ভারও বিষয়বস্তু ডিক্রিপ্ট বা রেকর্ড করতে পারে না।',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'মাইক্রোফোন শুধু ভয়েস বা ভিডিও কলের সময় এবং ক্যামেরা শুধু ভিডিও কলের সময় ব্যবহার হয়। কল শেষ হলে দুটোই বন্ধ হয়ে যায়।',
  'Takip ettiğin {} kişi izledi': 'তুমি যাদের ফলো করো তাদের {} জন দেখেছে',
  'Yorum yaz...': 'মন্তব্য লেখো...',
  'Sıradaki bölüm': 'পরবর্তী এপিসোড',
  'Doğrulanmış testçi': 'যাচাই করা টেস্টার',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'ফলো, লাইক, উত্তর, বার্তা ও ট্যাগের বিজ্ঞপ্তি',
  'Sen': 'তুমি',
  'Aradığınız kişide sesli arama devre dışı':
      'এই ব্যক্তির জন্য ভয়েস কল বন্ধ আছে',
  'Aradığınız kişide görüntülü arama devre dışı':
      'এই ব্যক্তির জন্য ভিডিও কল বন্ধ আছে',
  'Sesli aramalara izin ver': 'ভয়েস কলের অনুমতি দিন',
  'Görüntülü aramalara izin ver': 'ভিডিও কলের অনুমতি দিন',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'বন্ধ থাকলে কেউ আপনাকে ভয়েস কল করতে পারবে না; কলকারী একটি বার্তা দেখবে',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'বন্ধ থাকলে কেউ আপনাকে ভিডিও কল করতে পারবে না; কলকারী একটি বার্তা দেখবে',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'ভয়েস কল বন্ধ আছে। সেটিংস > গোপনীয়তা থেকে চালু করতে পারেন।',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'ভিডিও কল বন্ধ আছে। সেটিংস > গোপনীয়তা থেকে চালু করতে পারেন।',
  'Sesli ve görüntülü arama': 'ভয়েস ও ভিডিও কল',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'অতিথি অ্যাকাউন্ট কল করতে পারে না। অ্যাকাউন্ট তৈরি করলে ব্যবহার করতে পারবে।',
  'Misafir hesaplar aranamaz': 'অতিথি অ্যাকাউন্টে কল করা যায় না',
  'Puan dağılımı': 'রেটিং বণ্টন',
  '{} yıldız': '{}টা তারা',
  'Yakında gelecek': 'শীঘ্রই আসছে',
  '{} {} yayınlandı': '{} {} প্রকাশিত হয়েছে',
  'Yeni bölüm yayınlandı': 'নতুন এপিসোড প্রকাশিত হয়েছে',
  'Yeni bölümler': 'নতুন এপিসোড',
  'Geri': 'পেছনে',
  'Karşılamayı kapat': 'পরিচিতি বন্ধ করো',
  'Adım {} / {}': 'ধাপ {} / {}',
  'Hadi başlayalım': 'চলো শুরু করি',
  'Kaydet ve devam': 'সেভ করে এগিয়ে যাও',
  '{} tanesini ekle': '{}টি যোগ করো',
  'Şimdilik geç': 'আপাতত থাক',
  'Doğum tarihin ne zaman?': 'তোমার জন্মতারিখ কবে?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'বয়স অনুযায়ী কনটেন্ট দেখাতে আর জন্মদিনের শুভেচ্ছা জানাতে জিজ্ঞেস করছি।',
  'Gün': 'দিন',
  'Ay': 'মাস',
  'Yıl': 'বছর',
  'Doğum yılımı paylaşmak istemiyorum': 'জন্মের বছর শেয়ার করতে চাই না',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'তোমার জন্মতারিখ প্রোফাইলে সবাইকে দেখানো হয় না। এটি শুধু বয়স অনুযায়ী কনটেন্ট আর জন্মদিনের শুভেচ্ছার জন্য ব্যবহার হয়।',
  'Ocak': 'জানুয়ারি',
  'Şubat': 'ফেব্রুয়ারি',
  'Mart': 'মার্চ',
  'Nisan': 'এপ্রিল',
  'Mayıs': 'মে',
  'Haziran': 'জুন',
  'Temmuz': 'জুলাই',
  'Ağustos': 'আগস্ট',
  'Eylül': 'সেপ্টেম্বর',
  'Ekim': 'অক্টোবর',
  'Kasım': 'নভেম্বর',
  'Aralık': 'ডিসেম্বর',
  'Verilerini yanında getir': 'নিজের ডেটা সঙ্গে নিয়ে এসো',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'অন্য কোনো অ্যাপে দেখা জিনিস ট্র্যাক করলে সেগুলো এখানে নিয়ে আসতে পারো। শূন্য থেকে শুরু করার দরকার নেই।',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt ও Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'সেখান থেকে এক্সপোর্ট করা ZIP ফাইল বেছে নাও; তোমার দেখা, রেটিং আর লিস্ট চলে আসবে।',
  'Aktarılıyor...': 'ইম্পোর্ট হচ্ছে...',
  'ZIP dosyası seç': 'ZIP ফাইল বেছে নাও',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'তাড়া নেই: এটা পরে সেটিংস > আমার ডেটা থেকেও করা যায়।',
  'Hangi filmleri izledin?': 'কোন সিনেমাগুলো দেখেছ?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'সবচেয়ে বেশি দেখা সিনেমা এখানে। যেগুলোয় ট্যাপ করবে, সেগুলো তোমার দেখায় যোগ হবে।',
  'SERİ FİLMLER': 'সিনেমা সিরিজ',
  'Serilerden {} film eklendi': 'সিরিজ থেকে {}টি সিনেমা যোগ হয়েছে',
  'Film listesi yüklenemedi': 'সিনেমার লিস্ট লোড করা যায়নি',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'এই ধাপটা এড়িয়ে যেতে পারো, পরে যা ইচ্ছে যোগ করে নিয়ো।',
  '{} film izlediklerine eklendi': '{}টি সিনেমা তোমার দেখায় যোগ হয়েছে',
  'Film serileri': 'সিনেমা সিরিজ',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'পুরো একটা সিরিজ শুরু থেকে শেষ পর্যন্ত দেখা থাকলে এক ট্যাপে যোগ করো।',
  'Seri bulunamadı': 'কোনো সিরিজ পাওয়া যায়নি',
  'Daha sonra tekrar deneyebilirsin.': 'পরে আবার চেষ্টা করে দেখো।',
  '{} film': '{}টি সিনেমা',
  'Eklendi': 'যোগ হয়েছে',
  'Tümünü izledim': 'সবগুলো দেখেছি',
  'Peki ya diziler?': 'আর সিরিজ?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'দেখা সিরিজগুলো চিহ্নিত করো; যত বাছবে, তত তোমার মতো সাজেশন আসবে।',
  'Dizi listesi yüklenemedi': 'সিরিজের লিস্ট লোড করা যায়নি',
  'Seçtiklerine benzeyenler': 'তোমার বাছাইয়ের মতো',
  'Her şey hazır': 'সব তৈরি',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'dizi.jpg-এ কী কী করা যায়, একবার চোখ বুলিয়ে নাও।',
  'Profilini tamamla': 'প্রোফাইল পূরণ করো',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'সেটিংস থেকে বায়ো, প্রোফাইল ছবি আর কভার যোগ করতে পারো।',
  'Takvimin seni bekliyor': 'ক্যালেন্ডার তোমার অপেক্ষায়',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'তুমি যে সিরিজ দেখো তার নতুন এপিসোড ক্যালেন্ডারে চলে আসে, বিজ্ঞপ্তি দিয়ে জানিয়ে দিই।',
  'Puan ver, yorum yaz': 'রেট করো, কমেন্ট লেখো',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'এপিসোড ধরে ধরে রেট করো, স্পয়লার পর্দা দিয়ে কমেন্ট লেখো, লিস্ট বানাও।',
  'Verilerin sende kalır': 'ডেটা তোমারই থাকে',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'তোমার ডেটা শুধু তোমার অ্যাকাউন্টের সঙ্গেই থাকে, বিক্রি হয় না। সেটিংস থেকে সবটা ডাউনলোড করতে পারো বা অ্যাকাউন্ট পুরোপুরি মুছে ফেলতে পারো।',
  'Engellenen kullanıcılar': 'ব্লক করা ব্যবহারকারী',
  'Engellediğin kişileri gör, engeli kaldır':
      'ব্লক করা মানুষদের দেখো, আনব্লক করো',
  'Engellediğin kimse yok': 'কাউকে ব্লক করোনি',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'কোনো ব্যবহারকারীকে তার প্রোফাইলের তিন-বিন্দু মেনু থেকে ব্লক করা যায়।',
  '@{} engellensin mi?': '@{}-কে ব্লক করবে?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'একে অপরের পোস্ট, কমেন্ট ও প্রোফাইল কেউই দেখতে পাবে না; বার্তা বা কলও যাবে না। ফলোর সম্পর্ক থাকলে তা ছিঁড়ে যাবে এবং ব্লক তুলে নিলেও ফিরে আসবে না।',
  'Bu kullanıcıyı engelledin': 'এই ব্যবহারকারীকে ব্লক করেছ',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'এই ব্যক্তির পোস্ট, কমেন্ট ও বার্তা তুমি দেখতে পাও না; এই ব্যক্তিও তোমারগুলো দেখতে পায় না।',
  '{} yeni bir yapımda: {}': '{} নতুন প্রজেক্টে: {}',
  'Favori kişinden yeni yapım': 'প্রিয় ব্যক্তির নতুন প্রজেক্ট',
  '{} için bildirimler': '{}-এর জন্য বিজ্ঞপ্তি',
  'Tüm bildirimler': 'সব বিজ্ঞপ্তি',
  'Uygulamada ve telefonda': 'অ্যাপে ও ফোনে',
  'Yalnız uygulama içi': 'শুধু অ্যাপে',
  'Telefon bildirimi gönderilmez': 'ফোনে বিজ্ঞপ্তি পাঠানো হয় না',
  'Kapalı': 'বন্ধ',
  'Bu kişi için bildirim yok': 'এই ব্যক্তির জন্য কোনো বিজ্ঞপ্তি নেই',
  'Favori kişilerin yeni yapımları': 'প্রিয় ব্যক্তিদের নতুন প্রজেক্ট',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'বন্ধ থাকলে কেউ তোমাকে ভয়েস কল করতে পারবে না; কলকারী "বন্ধ আছে" বার্তা দেখবে',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'বন্ধ থাকলে কেউ তোমাকে ভিডিও কল করতে পারবে না; কলকারী "বন্ধ আছে" বার্তা দেখবে',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'আমার কার্যকলাপ',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'তোমার লাইক, কমেন্ট আর দেখা সব এক জায়গায়',
  'Henüz hareketin yok': 'এখনও কোনো কার্যকলাপ নেই',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'তুমি যা লাইক করো, কমেন্ট করো আর দেখো সব এখানে জমা হয়।',
  'Bu süzgeçte hareket yok': 'এই ফিল্টারে কোনো কার্যকলাপ নেই',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'অন্য একটি ধরন বেছে নাও বা "সব"-এ ফিরে যাও।',
  'Hepsi': 'সব',
  'Puan': 'রেটিং',
  'Tepki': 'রিঅ্যাকশন',
  'İzleme': 'দেখা',
  'Durum': 'স্ট্যাটাস',
  'Liste': 'লিস্ট',
  'Yorum yaptın': 'কমেন্ট করেছ',
  'Yorumu beğendin': 'একটি কমেন্ট লাইক করেছ',
  '{} puan verdin': '{} রেটিং দিয়েছ',
  'Tepki verdin': 'রিঅ্যাক্ট করেছ',
  'Listene ekledin': 'লিস্টে যোগ করেছ',
  'Takip etmeye başladın': 'ফলো করা শুরু করেছ',
  '"İzleyeceğim" işaretledin': '"দেখব" চিহ্নিত করেছ',
  '"İzliyorum" işaretledin': '"দেখছি" চিহ্নিত করেছ',
  '"Bitirdim" işaretledin': '"শেষ করেছি" চিহ্নিত করেছ',
  '"Bıraktım" işaretledin': '"ছেড়ে দিয়েছি" চিহ্নিত করেছ',
  'Silinmiş içerik': 'মুছে ফেলা কনটেন্ট',
  'şimdi': 'এখন',
  '{} g': '{} দি',
  '{} y': '{} ব',
  'İstatistiklerim': 'আমার পরিসংখ্যান',
  'Gönderilerinin görüntülenmesi ve beğenisi': 'তোমার পোস্টের ভিউ ও লাইক',
  'Henüz gönderin yok': 'এখনও তোমার কোনো পোস্ট নেই',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'কোনো সিরিজ বা সিনেমায় কমেন্ট লিখলে তোমার ভিউ ও লাইকের সংখ্যা এখানে জমতে শুরু করবে।',
  'Tüm zamanlar': 'সর্বকালীন',
  'Son {} gün': 'শেষ {} দিন',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'ভিউয়ের ইতিহাস এখনও জমতে শুরু করেনি; প্রথম দিনের ডেটা কাল দেখা যাবে।',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'ভিউয়ের ইতিহাস {} থেকে জমছে ({} দিনের ডেটা আছে), তাই {} দিনের সংখ্যা এখনও অসম্পূর্ণ।',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'লাইকের ইতিহাস {} থেকে রেকর্ড করা আছে।',
  'Bu dönemde gösterilecek gönderi yok.':
      'এই সময়ে দেখানোর মতো কোনো পোস্ট নেই।',
  'eksik veri': 'অসম্পূর্ণ ডেটা',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'তোমার প্রোফাইলে দেখা সিরিজ ও সিনেমা, দেখার সংখ্যা, স্ক্রিন টাইম আর মিল কার্ড অন্যরা দেখতে পাবে না',
  'Takipçi listemi gizle': 'আমার ফলোয়ার তালিকা লুকান',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'কে তোমাকে ফলো করে তা অন্যরা দেখতে পাবে না; তোমার ফলোয়ার সংখ্যা দেখা যেতে থাকবে',
  'Takip ettiklerimi gizle': 'আমি কাদের ফলো করি তা লুকান',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'তুমি কাদের ফলো করো তা অন্যরা দেখতে পাবে না; তোমার ফলোয়িং সংখ্যা দেখা যেতে থাকবে',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'এই ব্যবহারকারী তার ফলোয়ার গোপন রাখতে পছন্দ করেন।',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'এই ব্যবহারকারী কাদের ফলো করেন তা গোপন রাখতে পছন্দ করেন।',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'পোস্টের পরিসংখ্যান',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'আপনি কেবল নিজের পোস্টের পরিসংখ্যান দেখতে পারেন।',
  'Erişim': 'নাগাল',
  'Görüntüleyen': 'দর্শক',
  'Kaç farklı kişi gördü (son {} gün)': 'কতজন আলাদা মানুষ দেখেছেন (গত {} দিন)',
  'Paylaşım': 'শেয়ার',
  'Bu gönderiden sonra': 'এই পোস্টের পরে',
  'Profil ziyareti': 'প্রোফাইল ভিজিট',
  'Yeni takip': 'নতুন ফলো',
  'İçeriğe tıklama': 'কনটেন্টে ট্যাপ',
  'Spoiler perdesini açan': 'স্পয়লার খুলেছেন',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'শেয়ার, প্রোফাইল ভিজিট, ফলো, কনটেন্টে ট্যাপ, উৎসের বিভাজন আর স্পয়লারের হিসাব {} থেকে জমছে; এর আগেরটা মাপা হয়নি।',
  'Zamana yayılmış görüntülenme': 'সময়ের সাথে ভিউ',
  'Görüntülenme nereden geldi': 'ভিউ কোথা থেকে এল',
  'Kimler gördü': 'কারা দেখেছে',
  'Günlük veri henüz birikmeye başlamadı.':
      'দৈনিক ডেটা এখনও জমা হতে শুরু করেনি।',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'গ্রাফের জন্য অন্তত দুই দিনের ডেটা দরকার। ডেটা {} থেকে জমছে।',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'সবচেয়ে বেশি ভিউ এসেছে পোস্টের {} তম দিনে: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'দৈনিক ভিউ {} থেকে জমছে; এর আগেরটা মাপা হয়নি।',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'উৎসের বিভাজন সবে মাপা শুরু হয়েছে; এই পোস্ট এখনও কোনো ট্যাগ করা ভিউ পায়নি।',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'ফলোয়ার/ডিসকভার বিভাজন সবে মাপা শুরু হয়েছে; এখনও কোনো ডেটা নেই।',
  'Takip edenler': 'ফলোয়ার',
  'Keşiften gelenler': 'ডিসকভার থেকে',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'সিরিজ/সিনেমা পেজ',
  'Paylaşılan bağlantı': 'শেয়ার করা লিঙ্ক',
  'yeni ölçülüyor': 'নতুন মাপা হচ্ছে',
  'Kendi ortalamanla aynı düzeyde': 'তোমার নিজের গড়ের সমান',
  'Kendi ortalamanın %{} üstünde': 'তোমার নিজের গড়ের চেয়ে {}% বেশি',
  'Kendi ortalamanın %{} altında': 'তোমার নিজের গড়ের চেয়ে {}% কম',
  'Etkileşim oranı': 'এনগেজমেন্ট হার',
  '(beğeni + yorum) ÷ görüntülenme': '(লাইক + কমেন্ট) ÷ ভিউ',
  'Toplam görüntülenme': 'মোট ভিউ',
  '{} ile {} arasında toplam {} görüntülenme': '{} থেকে {} এর মধ্যে মোট {} ভিউ',
  'İstatistikleri gör': 'পরিসংখ্যান দেখুন',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'পোস্টের মালিককে দেখানো পরিসংখ্যানের জন্য সমষ্টিগত কাউন্টার হিসেবে রাখা হয়: পোস্টটি কতবার এবং কোন পৃষ্ঠ থেকে (ফিড, প্রোফাইল, ফুল-স্ক্রিন ফিড, সিরিজ/সিনেমা পেজ, শেয়ার করা লিঙ্ক) দেখা হয়েছে, দেখার সময় দর্শক পোস্টের মালিককে ফলো করছিলেন কি না, পোস্ট থেকে প্রোফাইল/কনটেন্টে যাওয়া, পোস্টের মাধ্যমে হওয়া ফলো, শেয়ার এবং স্পয়লার পর্দা খোলা। এই কাউন্টারে ব্যবহারকারীর পরিচয়, IP ঠিকানা বা টাইমস্ট্যাম্প থাকে না; কে কী করেছে তা জিজ্ঞেস করা যায় না।',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'একটি পোস্ট কতজন আলাদা মানুষ দেখেছেন তা গুনতে পারার জন্য, প্রতি দর্শকের জন্য একটি অপরিবর্তনীয় কি-যুক্ত ডাইজেস্ট (ব্যবহারকারীর পরিচয় বা IP ঠিকানা থেকে উদ্ভূত ক্রিপ্টোগ্রাফিক সংক্ষেপ) ৯০ দিন রাখা হয়। পোস্টের মালিককে কেবল সংখ্যাটি দেখানো হয়; দর্শকদের পরিচয় কোনো অবস্থাতেই শেয়ার করা হয় না।',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': '“দেখব”-তে সরানো হবে?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'একটি কনটেন্ট হয় দেখা হবে, নয়তো দেখা হয়ে গেছে। চালিয়ে গেলে এই সিরিজে তোমার {}টি দেখার চিহ্ন মুছে যাবে।',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'একটি কনটেন্ট হয় দেখা হবে, নয়তো দেখা হয়ে গেছে। চালিয়ে গেলে এই সিনেমায় তোমার “দেখেছি” চিহ্ন উঠে যাবে।',
  'Sil ve taşı': 'মুছে সরাও',

  // --- Yapım ekibi / firma + seviye unvanları + doğum günü ---
  'Yapım Ekibi': 'কলাকুশলী',
  'Yaratıcı': 'স্রষ্টা',
  'Yönetmen': 'পরিচালক',
  'Senaryo': 'চিত্রনাট্য',
  'Yapımcı': 'প্রযোজক',
  'Yapım Firmaları': 'প্রযোজনা সংস্থাগুলো',
  'Yapım Firması': 'প্রযোজনা সংস্থা',
  'Firma bulunamadı': 'সংস্থা পাওয়া যায়নি',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'এই সংস্থার এই ধরনের কোনো কাজ নেই।',
  'Doğum günün kutlu olsun!': 'শুভ জন্মদিন!',
  'İyi ki doğdun, iyi ki buradasın.':
      'ভালো হয়েছে তুমি জন্মেছ, ভালো হয়েছে তুমি এখানে আছ।',
  'Bugün {} yaşına girdin': 'আজ তুমি {} বছরে পা দিলে',
  'Teşekkürler': 'ধন্যবাদ',
  'İki Adımlı Doğrulama': 'দুই ধাপে যাচাইকরণ',
  'Girişte e-postana kod gönderilir':
      'সাইন ইন করলে তোমার ইমেইলে কোড পাঠানো হয়',
  'Kod {} adresine gönderildi': '{} ঠিকানায় কোড পাঠানো হয়েছে',
  '6 haneli kod': '6 সংখ্যার কোড',
  'Doğrula': 'যাচাই করো',
  'Yeniden gönder': 'আবার পাঠাও',
  'Vazgeç': 'বাতিল',
  'Yeni kod gönderildi': 'নতুন কোড পাঠানো হয়েছে',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'Google দিয়ে সাইন ইন করলে কোড চাওয়া হয় না; Google নিজেই যাচাই করে।',
  'Kapatmak için de kod gerekir.': 'বন্ধ করতেও কোড লাগবে।',
  'E-postana erişemezsen hesabına giremezsin.':
      'ইমেইলে ঢুকতে না পারলে অ্যাকাউন্টেও ঢোকা যাবে না।',
  'İki adımlı doğrulama açıldı': 'দুই ধাপে যাচাইকরণ চালু হয়েছে',
  'İki adımlı doğrulama kapatıldı': 'দুই ধাপে যাচাইকরণ বন্ধ হয়েছে',
  'Videonun ne kadarı izlendi': 'ভিডিওর কতটা দেখা হয়েছে',
  'Videoyu başlatanlar': 'ভিডিও শুরু করেছে',
  'videonun %{} noktasına ulaştı': 'ভিডিওর {}% পর্যন্ত পৌঁছেছে',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'অর্ধেক দর্শক ভিডিওর অন্তত {}% দেখেছে।',
  'Sonuna kadar izleyen: %{}': 'শেষ পর্যন্ত দেখেছে: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'কার্ভের জন্য অন্তত {} ভিউ দরকার; এখন আছে {} ভিউ।',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'কার্ভটি {} ভিউ থেকে তৈরি এবং নির্বাচিত সময়সীমা এতে প্রভাব ফেলে না।',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'দেখার সময় {} থেকে মাপা হচ্ছে; এর আগের ভিউ এতে ধরা হয় না।',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} ভিউ। {}% অর্ধেক পর্যন্ত, {}% শেষ পর্যন্ত পৌঁছেছে।',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'লেভেল {}',
  'Sonraki seviyeye {} puan kaldı': 'পরের লেভেলে {} পয়েন্ট বাকি',
  'Gönderilerin': 'তোমার পোস্ট',
  '{} gönderi': '{} পোস্ট',
  '{} gönderi · {} görüntülenme': '{} পোস্ট · {} ভিউ',
  'önceki {} güne göre': 'আগের {} দিনের তুলনায়',
  'önceki {} güne göre %{} arttı': 'আগের {} দিনের তুলনায় {}% বেড়েছে',
  'önceki {} güne göre %{} azaldı': 'আগের {} দিনের তুলনায় {}% কমেছে',
  'önceki {} güne göre değişmedi': 'আগের {} দিনের তুলনায় অপরিবর্তিত',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'দৈনিক ভিউ: সর্বনিম্ন {}, সর্বোচ্চ {}',
  'Etkileşim oranı henüz ölçülemedi': 'এনগেজমেন্ট হার এখনও মাপা যাচ্ছে না',
  'Oranlar': 'হার',
  'Beğenme oranı': 'লাইকের হার',
  'Yorum oranı': 'কমেন্টের হার',
  'Paylaşma oranı': 'শেয়ারের হার',
  'İçeriğe gitme oranı': 'কনটেন্টে ট্যাপের হার',
  'Profile gitme oranı': 'প্রোফাইল ভিজিটের হার',
  'Ziyaretten takibe dönüşüm': 'ভিজিট থেকে ফলো',
  'beğeni ÷ görüntülenme': 'লাইক ÷ ভিউ',
  'yorum ÷ görüntülenme': 'কমেন্ট ÷ ভিউ',
  'paylaşım ÷ görüntülenme': 'শেয়ার ÷ ভিউ',
  'içeriğe tıklama ÷ görüntülenme': 'কনটেন্টে ট্যাপ ÷ ভিউ',
  'profil ziyareti ÷ görüntülenme': 'প্রোফাইল ভিজিট ÷ ভিউ',
  'yeni takip ÷ profil ziyareti': 'নতুন ফলো ÷ প্রোফাইল ভিজিট',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'হারের জন্য অন্তত {} ভিউ দরকার; এখন আছে {}।',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'হারগুলো পোস্টের সর্বকালীন সংখ্যা থেকে হিসাব হয়; নিচের দিন নির্বাচন এগুলো বদলায় না।',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'এই সংখ্যাগুলো পোস্টের সর্বকালীন মোট (যেসব বাক্সের নিজস্ব নোট আছে সেগুলো ছাড়া); নিচের দিন নির্বাচন কেবল গ্রাফ বদলায়।',
  'Ortalama izlenme: videonun %{} kadarı': 'গড় দেখা: ভিডিওর {}%',
  'Elde tutma eğrisinin 20 kovasının ortalaması.': 'কার্ভের 20টি ভাগের গড়।',
  'Dizi, film, kişi veya şirket ara...':
      'সিরিজ, সিনেমা, ব্যক্তি বা কোম্পানি খোঁজো...',
  'Şirketler': 'কোম্পানি',
  'Senarist': 'চিত্রনাট্যকার',
  'Bölüm puanları': 'এপিসোড রেটিং',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'এপিসোড রেটিং লোড করা যায়নি',
  'Giriş gerekli': 'সাইন ইন প্রয়োজন',
  'Geçersiz oturum': 'অবৈধ সেশন',
  'Oturum sonlandı, tekrar giriş yap': 'সেশন শেষ, আবার সাইন ইন করো',
  'Çok fazla istek; biraz sonra tekrar dene':
      'অনেক বেশি অনুরোধ; একটু পরে চেষ্টা করো',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'সার্ভারে এখন জায়গা নেই, একটু পরে আবার চেষ্টা করুন',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'আপনার মিডিয়া স্টোরেজ পূর্ণ; জায়গা খালি করতে পুরোনো আপলোড মুছুন',
  'E-posta/kullanıcı adı veya şifre hatalı': 'ইমেল/ইউজারনেম বা পাসওয়ার্ড ভুল',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'এই ইমেল বা ইউজারনেম আগেই নেওয়া',
  'Google doğrulaması başarısız': 'Google যাচাই ব্যর্থ',
  'Kod geçersiz veya süresi dolmuş': 'কোড ভুল বা মেয়াদ শেষ',
  'Bu kullanıcıyla mesajlaşamazsın': 'এই ব্যবহারকারীকে মেসেজ করা যাবে না',
  'Kendini takip edemezsin': 'নিজেকে ফলো করা যায় না',
  'Bu kullanıcıyı takip edemezsin': 'এই ব্যবহারকারীকে ফলো করা যাবে না',
  'Kendini engelleyemezsin': 'নিজেকে ব্লক করা যায় না',
  'Yorum 1-1000 karakter olmalı': 'মন্তব্য 1–1000 অক্ষরের হতে হবে',
  'Boş mesaj gönderilemez': 'খালি মেসেজ পাঠানো যায় না',
  'Yorum bulunamadı': 'মন্তব্য পাওয়া যায়নি',
  'Şifre hatalı': 'পাসওয়ার্ড ভুল',
  'Şifre en az 6 karakter olmalı': 'পাসওয়ার্ড কমপক্ষে 6 অক্ষরের হতে হবে',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'শুধু GIF, PNG, JPEG বা WebP আপলোড করা যায়',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'সমর্থিত ধরন: GIF, PNG, JPEG, WebP, MP4, WebM, অডিও',
  'Geçerli bir ZIP dosyası değil': 'এটি বৈধ ZIP ফাইল নয়',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'ডেটা ইমেলে পেতে আগে অ্যাকাউন্টে ইমেল যোগ করো',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'এতে দেখার রেকর্ড আছে। "দেখব" বলতে আগে চিহ্ন মুছতে হবে।',
  'Arama şu anda kapalı': 'কল এখন বন্ধ',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'গেস্ট অ্যাকাউন্ট কল চালু করতে পারে না; অ্যাকাউন্ট খুললে চলবে',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'সার্ভার রিস্টার্ট হচ্ছে, একটু পরে চেষ্টা করো',
  'Puan 1-10 arası olmalı': 'স্কোর 1 থেকে 10 এর মধ্যে হতে হবে',
  'En fazla 10 medya eklenebilir': 'সর্বোচ্চ 10টি মিডিয়া যোগ করা যায়',
  'Bu cihazdan yeni hesap açılamıyor':
      'এই ডিভাইস থেকে নতুন অ্যাকাউন্ট খোলা যায় না',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'সঠিক ইমেইল, ব্যবহারকারীর নাম ও অন্তত ৬ অক্ষরের পাসওয়ার্ড লাগে',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'সঠিক ইমেইল ও অন্তত ৬ অক্ষরের পাসওয়ার্ড লাগে',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'ব্যবহারকারীর নাম ৩–২০ অক্ষর; ছোট হাতের অক্ষর, সংখ্যা, বিন্দু, হাইফেন, আন্ডারস্কোর (শুরু/শেষে নয়)',
  'Bu hesap zaten bağlı': 'এই অ্যাকাউন্ট ইতিমধ্যেই সংযুক্ত',
  'Hesap oluşturulamadı': 'অ্যাকাউন্ট তৈরি করা যায়নি',
  'Misafir hesabı oluşturulamadı': 'গেস্ট অ্যাকাউন্ট তৈরি করা যায়নি',
  'Hesap bulunamadı': 'অ্যাকাউন্ট পাওয়া যায়নি',
  'Bu hesapta e-posta yok': 'এই অ্যাকাউন্টে ইমেইল নেই',
  'İki adımlı doğrulama zaten bu durumda':
      'দুই ধাপের যাচাই ইতিমধ্যেই এই অবস্থায়',
  'Kod yanlış': 'কোড ভুল',
  'Kodun süresi doldu': 'কোডের মেয়াদ শেষ',
  'Kullanıcının e-postası yok (misafir hesap)':
      'এই ব্যবহারকারীর ইমেইল নেই (গেস্ট অ্যাকাউন্ট)',
  'Bio en fazla 300 karakter olabilir': 'বায়ো সর্বোচ্চ ৩০০ অক্ষর',
  'Geçersiz ülke': 'অবৈধ দেশ',
  'Geçersiz sosyal bağlantı': 'অবৈধ সামাজিক লিঙ্ক',
  'Geçersiz doğum tarihi': 'অবৈধ জন্ম তারিখ',
  'Liste adı gerekli': 'তালিকার নাম লাগে',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'নাম সর্বোচ্চ ৬০, বিবরণ ৩০০ অক্ষর',
  'Liste bulunamadı': 'তালিকা পাওয়া যায়নি',
  'Değiştirilecek tercih yok': 'আপডেট করার কিছু নেই',
  'İnceleme en fazla 2000 karakter olabilir': 'রিভিউ সর্বোচ্চ ২০০০ অক্ষর',
  'Önce içeriği "bitirdim" olarak işaretle':
      'আগে এটিকে শেষ দেখা হিসেবে চিহ্নিত করো',
  'Önce kişiyi favorile': 'আগে এই ব্যক্তিকে ফেভারিট করো',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'পর্বের মন্তব্যে সিজন ও পর্ব দুটোই লাগে',
  'Yanıtlanan yorum bulunamadı': 'যে মন্তব্যে উত্তর দিচ্ছ তা পাওয়া যায়নি',
  'Geri bildirim 3-2000 karakter olmalı': 'ফিডব্যাক ৩–২০০০ অক্ষর হতে হবে',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'শিরোনাম ও লেখা লাগে (কমপক্ষে ২ অক্ষর)',
  'Kendine mesaj gönderemezsin': 'নিজেকে বার্তা পাঠানো যায় না',
  'Mesaj en fazla 2000 karakter olabilir': 'বার্তা সর্বোচ্চ ২০০০ অক্ষর',
  'Mesaj 1-2000 karakter olmalı': 'বার্তা ১–২০০০ অক্ষর হতে হবে',
  'Mesaj bulunamadı': 'বার্তা পাওয়া যায়নি',
  'Mesaj bulunamadı veya düzenlenemez':
      'বার্তা পাওয়া যায়নি বা সম্পাদন করা যায় না',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'শুধু তোমার কাছে আসা বার্তার অভিযোগ করা যায়',
  'Sebep gerekli': 'কারণ লাগে',
  'İtiraz edilecek aktif bir ceza yok': 'আপিল করার মতো কোনো সক্রিয় শাস্তি নেই',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'তোমার ইতিমধ্যেই পর্যালোচনার অপেক্ষায় একটি আপিল আছে',
  'Bu ceza için itirazın zaten incelendi':
      'এই শাস্তির আপিল ইতিমধ্যেই পর্যালোচিত',
  'Medya bağlantısının süresi dolmuş': 'মিডিয়া লিঙ্কের মেয়াদ শেষ',
  'Bu medya için imzalı bağlantı gerekli':
      'এই মিডিয়ার জন্য স্বাক্ষরিত লিঙ্ক লাগে',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'কল সেবা রিস্টার্ট হচ্ছে; কিছুক্ষণ পর চেষ্টা করো',
  'Puan göstergesi': 'রেটিং লেজেন্ড',
};
