/// Otomatik üretilen çeviri haritası (fr).
const Map<String, String> cevirilerFr = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Vous avez tout vu, nous vous montrons depuis le début',
  'Aktarılacak tanınan veri bulunamadı.': 'Aucune donnée reconnue à importer.',
  'Arama': 'Recherche',
  'Aramaya başla': 'Lance une recherche',
  'Son aramalar': 'Recherches récentes',
  'Ayarlar': 'Paramètres',
  'Bağla': 'Associer',
  'Bio': 'Bio',
  'Bitirdim': 'Terminé',
  'Bunları da Beğenebilirsin': 'Tu pourrais aussi aimer',
  'Bölüm': 'Épisode',
  'Bıraktım': 'Abandonné',
  'Dil': 'Langue',
  'Dil ara...': 'Rechercher une langue...',
  'Dizi': 'Série',
  'Dizi ve filmlerini takip et': 'Suis tes séries et tes films',
  'Dizi yorumu': 'Commentaire de série',
  'Dizi, film veya kişi ara...':
      'Cherche une série, un film ou une personne...',
  'Dosya en fazla 30MB olabilir': 'Le fichier ne peut pas dépasser 30 Mo',
  'Dosya en fazla {}MB olabilir': 'Le fichier ne peut pas dépasser {} Mo',
  'E-posta': 'E-mail',
  'E-posta veya kullanıcı adı': "E-mail ou nom d'utilisateur",
  'En az 2 harf yaz': 'Écris au moins 2 lettres',
  'Film': 'Film',
  'Film yorumu': 'Commentaire de film',
  'Fotoğraf / video ekle': 'Ajouter une photo / vidéo',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Photo ou GIF — photo de profil et de couverture',
  'Giriş Yap': 'Se connecter',
  'Gönder': 'Envoyer',
  'Gönderildi': 'Envoyé',
  'Haftanın Dizileri': 'Séries de la semaine',
  'Haftanın Filmleri': 'Films de la semaine',
  'Henüz izleme kaydın yok': "Tu n'as pas encore d'historique",
  'Henüz listen yok — Profil sekmesinden oluştur.':
      "Tu n'as pas encore de liste — crée-en une depuis l'onglet Profil.",
  'Henüz yorum yok.': 'Pas encore de commentaires.',
  'Hesabın bağlandı!': 'Ton compte est associé !',
  'Hesabın yok mu? Kayıt ol': 'Pas de compte ? Inscris-toi',
  'Hesabını Bağla': 'Associe ton compte',
  'Hesap Oluştur': 'Créer un compte',
  'Kapak resmi ekle': 'Ajouter une couverture',
  'Kaydet': 'Enregistrer',
  'Kendinden bahset...': 'Parle-nous de toi...',
  'Keşfet': 'Découvrir',
  'Kimseyi takip etmiyor': 'Ne suit personne',
  'Kişi ara': 'Rechercher des personnes',
  'Kişi yorumu': 'Commentaire de personne',
  'Konuk Oyuncular': 'Acteurs invités',
  'Kullanıcı adı (küçük harf)': "Nom d'utilisateur (minuscules)",
  'Kullanıcı adı ara...': "Rechercher un nom d'utilisateur...",
  'Liste adı': 'Nom de la liste',
  'Listeye Ekle': 'Ajouter à une liste',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Tu es sur un compte invité — associe ton e-mail pour ne pas perdre tes données !',
  'Misafir olarak devam et': 'Continuer en invité',
  'Oluştur': 'Créer',
  'Oyuncular': 'Casting',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil enregistré',
  'Puanla': 'Noter',
  'Puanı Sil': 'Supprimer la note',
  'Puanın': 'Ta note',
  'Sezonlar': 'Saisons',
  'Sunucu hatası ({})': 'Erreur serveur ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Commentaire S{}E{}',
  'Takibi Bırak': 'Ne plus suivre',
  'Takip': 'Abonnements',
  'Takip Edilenler': 'Abonnements',
  'Takip Et': 'Suivre',
  'Takipçi': 'Abonnés',
  'Takipçi yok': 'Aucun abonné',
  'Takipçiler': 'Abonnés',
  'Takvim': 'Calendrier',
  'Tamam': 'OK',
  'Tekrar Dene': 'Réessayer',
  'Tekrar dene': 'Réessaie',
  'Toplam İzleme Süresi': "Temps d'écran total",
  'Tüm Zamanların En İyileri': 'Les meilleurs de tous les temps',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      "Exporte toutes tes données (visionnages, notes, commentaires, listes) en ZIP compatible TV Time, ou importe un ZIP venant d'une autre appli.",
  'Tümünü Kaldır': 'Tout retirer',
  'Tümünü İzledim': "J'ai tout vu",
  'Türk Dizileri': 'Séries turques',
  'Veri içe aktar (.zip)': 'Importer des données (.zip)',
  'Verilerim': 'Mes données',
  'Verilerimi dışa aktar (e-posta)': 'Exporter mes données (e-mail)',
  'Verilerini dışa aktar': 'Exporte tes données',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Aucun épisode à venir.\nPasse une série en "Je regarde" depuis sa fiche et suis les nouveaux épisodes ici.',
  'Yapımları': 'Filmographie',
  'Yeni Diziler': 'Nouvelles séries',
  'Yeni Liste': 'Nouvelle liste',
  'Yeni kullanıcı adı (isteğe bağlı)': "Nouveau nom d'utilisateur (facultatif)",
  'Yorum': 'Commentaire',
  'Yorumunu yaz...': 'Écris ton commentaire...',
  'Zaten hesabın var mı? Giriş yap': 'Déjà un compte ? Connecte-toi',
  'ort. {}': 'moy. {}',
  'takip': 'abonnements',
  'takipçi': 'abonnés',
  '{} / {} bölüm': '{} / {} épisodes',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} mois',
  '{} ay~tekil': '{} mois',
  '{} bölüm izlendi': '{} épisodes vus',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} dk~tekil': '{} min',
  '{} gün': '{} jours',
  '{} gün~tekil': '{} jour',
  '{} içerik': '{} titres',
  '{} içerik · otomatik': '{} titres · automatique',
  '{} kayıt atlandı (eşleşmedi).':
      '{} entrées ignorées (aucune correspondance).',
  '{} saat': '{} heures',
  '{} saat~tekil': '{} heure',
  '{} sezon': '{} saisons',
  '{} yıl': '{} ans',
  '{} yıl~tekil': '{} an',
  '{}. Bölüm': 'Épisode {}',
  '{}. Sezon': 'Saison {}',
  'Çıkış Yap': 'Se déconnecter',
  'Ülke': 'Pays',
  'Ülke ara...': 'Rechercher un pays...',
  'Ülke seç': 'Choisis un pays',
  'İlk yorumu sen yaz!': 'Écris le premier commentaire !',
  'İncelemeler': 'Critiques',
  'İncelemen (isteğe bağlı)': 'Ta critique (facultatif)',
  'İptal': 'Annuler',
  'İzlediklerim': 'Mon historique',
  'İzledim': 'Vu',
  'İzledin': 'Tu as vu',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      "Ton historique et tes listes sont conservés ; tu peux maintenant te connecter depuis n'importe quel appareil.",
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Ton historique, tes notes, tes commentaires et tes listes seront envoyés en ZIP à ton adresse e-mail enregistrée.',
  'İzleyeceğim': 'À voir',
  'İzliyorum': 'Je regarde',
  'İçe aktarım tamamlandı': 'Import terminé',
  'Şifre': 'Mot de passe',
  '• profil bilgisi': '• infos de profil',
  '• {} dizi durumu': '• {} statuts de séries',
  '• {} izleme kaydı': '• {} visionnages',
  '• {} liste': '• {} listes',
  '• {} puan': '• {} notes',
  '• {} yorum': '• {} commentaires',
  '{}+ yapım': '{}+ titres',
  'Yorumlar': 'Commentaires',
  'Yorumlar ({})': 'Commentaires ({})',
  'Yorumları ({})': 'Commentaires ({})',
  'Listelerim': 'Mes listes',
  'Nereden izledin?': "Où l'as-tu regardé ?",
  'Diziye git': 'Voir la série',
  'TV / Kanal': 'TV / Chaîne',
  'Sinema': 'Cinéma',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Autre',
  'Akış': 'Fil',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Ton fil est vide.\nQuand on commentera les séries et films que tu regardes, ça apparaîtra ici.',
  'Listeleri ({})': 'Ses listes ({})',
  'Liste boş.': 'Cette liste est vide.',
  'Yanıtla': 'Répondre',
  '@{} kullanıcısına yanıt veriyorsun': 'Tu réponds à @{}',
  'İzlediğim Diziler ({})': 'Séries vues ({})',
  'İzlediğim Filmler ({})': 'Films vus ({})',
  'Tümünü gör': 'Tout voir',
  'Bildirimler': 'Notifications',
  'Henüz bildirim yok': 'Pas encore de notifications',
  '@{} yorumuna yanıt verdi': '@{} a répondu à ton commentaire',
  '@{} yorumunu beğendi': '@{} a aimé ton commentaire',
  '@{} seni takip etti': '@{} te suit maintenant',
  '@{} sana mesaj gönderdi': "@{} t'a envoyé un message",
  'Mesajlar': 'Messages',
  'Mesaj': 'Message',
  'Mesaja eklenecek': 'Sera ajoute au message',
  'Mesajını yaz...': 'Écris un message...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Pas encore de discussions.\nOuvre un profil et envoie un message.',
  'Şifreni mi unuttun?': 'Mot de passe oublié ?',
  'Şifreyi Sıfırla': 'Réinitialiser le mot de passe',
  'E-postadaki kod': 'Code reçu par e-mail',
  'Yeni şifre': 'Nouveau mot de passe',
  'Sana Özel': 'Pour toi',
  '{} özetin': 'Ton bilan {}',
  'Yıllık izleme istatistiklerin': 'Tes stats annuelles',
  'Rozetler': 'Badges',
  'Verdiğin puan': 'Notes données',
  'Ortalama puanın': 'Ta note moyenne',
  'En çok izlediğin diziler': 'Tes séries les plus vues',
  'İlk Bölüm': 'Premier épisode',
  '100 Bölüm': '100 épisodes',
  '1000 Bölüm': '1000 épisodes',
  'İlk Film': 'Premier film',
  '50 Film': '50 films',
  'İlk Yorum': 'Premier commentaire',
  '25 Yorum': '25 commentaires',
  '10 Puan': '10 notes',
  'İlk Takipçi': 'Premier abonné',
  '10 Dizi Bitirdin': '10 séries terminées',
  'İzlemeyi Bıraktım': "J'ai arrêté de regarder",
  'İzlediği Diziler ({})': 'Séries vues ({})',
  'İzlediği Filmler ({})': 'Films vus ({})',
  '500 Bölüm': '500 épisodes',
  '5000 Bölüm': '5000 épisodes',
  '10 Film': '10 films',
  '100 Film': '100 films',
  '100 Yorum': '100 commentaires',
  '50 Puan': '50 notes',
  '100 Puan': '100 notes',
  '10 Takipçi': '10 abonnés',
  '50 Takipçi': '50 abonnés',
  '25 Dizi Bitirdin': '25 séries terminées',
  '50 Dizi Bitirdin': '50 séries terminées',
  '10 Beğeni': "10 j'aime",
  '100 Beğeni': "100 j'aime",
  'yazıyor...': 'écrit...',
  'Profil düzeni': 'Disposition du profil',
  'Konumla ve kırp': 'Positionner et rogner',
  'Listeye eklendi': 'Ajouté à la liste',
  'Listeyi sil?': 'Supprimer la liste ?',
  'Sil': 'Supprimer',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Ce titre sera marqué comme jamais vu et retiré de tes listes.',
  'Gelecek bölüm bugün': "Prochain épisode aujourd'hui",
  'Gelecek bölüm {} gün sonra': 'Prochain épisode dans {} jours',
  'Tema': 'Thème',
  'Sistem': 'Système',
  'Koyu': 'Sombre',
  'Açık': 'Clair',
  'İzleyenler': 'Spectateurs',
  'Yorumunu yaz... (@ ile etiketle)':
      'Écris ton commentaire... (@ pour identifier)',
  '@{} bir yorumda seni etiketledi': 'Mention de @{} dans un commentaire',
  'Mesajı sil': 'Supprimer le message',
  'Mesaj silinemedi': 'Impossible de supprimer le message',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Lien invalide ou page introuvable',
  "Keşfet'e dön": 'Retour à Découvrir',
  'Düzenle': 'Modifier',
  'Mesajı düzenle': 'Modifier le message',
  'Yanıtlanıyor': 'Réponse',
  'düzenlendi': 'modifié',
  'Fotoğraf': 'Photo',
  'Video': 'Vidéo',
  'İçerik': 'Contenu',
  'çevrimiçi': 'en ligne',
  'son görülme {} dk önce': 'en ligne il y a {} min',
  'son görülme {} saat önce': 'en ligne il y a {} h',
  'son görülme {} gün önce': 'en ligne il y a {} j',
  'Yorumlar yüklenemedi': 'Impossible de charger les commentaires',
  'Favori': 'Favori',
  'Listeye ekle': 'Ajouter à la liste',
  'İçerik paylaş': 'Partager le contenu',
  'Kapat': 'Fermer',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Tout ce que tu marques comme vu se retrouve ici.',
  'Henüz sohbetin yok': "Aucune conversation pour l'instant",
  'Bir profile girip mesaj gönderebilirsin.':
      'Ouvre un profil et envoie un message.',
  'Listeyi sil': 'Supprimer la liste',
  'Puan kaydedilemedi': "Impossible d'enregistrer la note",
  'Nerede İzlenir': 'Où regarder',
  'Abonelik': 'Abonnement',
  'Kirala': 'Louer',
  'Satın al': 'Acheter',
  'Devam et': 'Continuer',
  'Şikayet et': 'Signaler',
  'Engelle': 'Bloquer',
  'Engeli kaldır': 'Débloquer',
  'Kullanıcı engellendi': 'Utilisateur bloqué',
  'Engel kaldırıldı': 'Blocage retiré',
  'Şikayet sebebi': 'Motif du signalement',
  'Spam veya yanıltıcı': 'Spam ou trompeur',
  'Taciz veya nefret söylemi': 'Harcèlement ou incitation à la haine',
  'Uygunsuz / cinsel içerik': 'Contenu inapproprié / sexuel',
  'Şiddet veya tehlikeli içerik': 'Violence ou contenu dangereux',
  'Telif hakkı ihlali': 'Violation de droits d’auteur',
  'Şikayetin alındı, teşekkürler': 'Ton signalement a été reçu, merci',
  'Hesabımı Sil': 'Supprimer mon compte',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Ton compte et toutes tes données (historique, notes, commentaires, listes, messages) seront définitivement supprimés. Cette action est irréversible.',
  'Şifreni gir': 'Saisis ton mot de passe',
  'Hesabımı kalıcı sil': 'Supprimer définitivement mon compte',
  'Sesli mesaj': 'Message vocal',
  'Ses gönderilemedi': 'Impossible d’envoyer le message vocal',
  'Kaydediliyor…': 'Enregistrement…',
  'Ses oynatılamadı': 'Impossible de lire l’audio',
  'Oynat': 'Lire',
  'Duraklat': 'Pause',
  'Liste görünümü': 'Vue liste',
  'Takvim görünümü': 'Vue calendrier',
  'Önceki ay': 'Mois précédent',
  'Sonraki ay': 'Mois suivant',
  'Bu gün bölüm yok': 'Aucun épisode ce jour',
  'Gizlilik Politikası': 'Politique de Confidentialité',
  'Son güncelleme: {}': 'Dernière mise à jour : {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      "Cette politique explique quelles données sont collectées, comment elles sont utilisées et quels sont tes droits lorsque tu utilises l'application dizi.jpg et le site dizijpg.com.",
  'Topladığımız Veriler': 'Données que nous collectons',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      "Compte : adresse e-mail, nom d'utilisateur et mot de passe. Les mots de passe sont stockés sous forme de hachage irréversible ; les comptes invités peuvent être utilisés sans e-mail.",
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      "Profil : les informations que tu choisis d'ajouter, comme l'avatar, l'image de couverture, la bio et le pays.",
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Utilisation : ton historique de visionnage, tes notes, commentaires, listes, réactions et favoris.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      "Messages : tes messages texte, image et vocaux sont stockés sur nos serveurs. Les messages ne sont pas chiffrés de bout en bout ; ils ne sont consultés qu'en cas de signalement, à des fins de modération.",
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Médias envoyés : photos, GIF, vidéos et enregistrements vocaux que tu ajoutes à ton profil, tes commentaires et tes messages.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      "Données techniques : adresse IP, localisation approximative (pays/ville), plateforme de l'appareil, version de l'application et journaux d'erreurs. Elles sont conservées pour la sécurité et le débogage.",
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Statistiques d’usage : le type d’appareil, le système d’exploitation et le navigateur utilisés pour se connecter sont ajoutés à des compteurs quotidiens globaux sous forme de catégories approximatives ; l’identifiant du navigateur lui-même n’est pas conservé et ces chiffres ne peuvent être rattachés à personne.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      "Notifications : pour les notifications push, nous conservons le jeton de ton appareil et ta langue. Tu peux les désactiver à tout moment dans les réglages de l'appareil.",
  'Verileri Nasıl Kullanırız': 'Comment nous utilisons tes données',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Nous utilisons tes données uniquement pour fournir le service, protéger ton compte, envoyer des notifications, corriger les erreurs et prévenir les abus. Nous ne vendons pas tes données et ne les partageons avec personne à des fins publicitaires.',
  'Çerezler ve Yerel Depolama': 'Cookies et stockage local',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      "Nous utilisons le stockage local uniquement pour garder ta session ouverte et mémoriser tes préférences comme la langue et le thème. Il n'y a aucun cookie publicitaire ni de suivi.",
  'Üçüncü Taraf Hizmetler': 'Services tiers',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Les données des séries et films proviennent de TMDB, les informations sur les plateformes de streaming de JustWatch. Les notifications push sont acheminées par Google Firebase et le trafic du site est protégé par Cloudflare. Ces services sont soumis à leurs propres politiques de confidentialité.',
  'Saklama ve Silme': 'Conservation et suppression',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      "Tes données sont conservées tant que ton compte existe. Avec « Supprimer mon compte » dans les Réglages, tu peux supprimer ton compte définitivement ; tes données sont effacées immédiatement et leurs copies dans les sauvegardes sous 14 jours au plus tard. Les journaux d'erreurs sont supprimés automatiquement après 30 jours.",
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      "Tu peux exporter tes données au format ZIP depuis les Réglages ; l'archive est envoyée à ton adresse e-mail.",
  'Güvenlik': 'Sécurité',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Les données transitent par des connexions chiffrées (HTTPS) et sont stockées sur des serveurs à accès restreint.',
  'Çocukların Gizliliği': 'Confidentialité des enfants',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      "dizi.jpg ne s'adresse pas aux enfants de moins de 13 ans.",
  'Hakların': 'Tes droits',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      "En vertu de la KVKK et du GDPR, tu as le droit d'accéder à tes données, de les corriger, de les supprimer et de les transférer. Pour cela, écris-nous : {}",
  'Değişiklikler': 'Modifications',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Si cette politique change, la nouvelle version sera publiée sur cette page et la date sera mise à jour.',
  'Kayıt olarak {} kabul etmiş olursun.': "En t'inscrivant, tu acceptes la {}.",
  'Kullanıcılar': 'Utilisateurs',
  'Fotoğrafı değiştir': 'Changer la photo',
  'Yeniden konumlandır': 'Repositionner',
  'Bir şeyler ters gitti': 'Un problème est survenu',
  'Sosyal Bağlantılar': 'Liens sociaux',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      "Jusqu'à 3 liens s'affichent sur ton profil.",
  'Platform seç': 'Choisis une plateforme',
  'Kullanıcı adın': "Ton nom d'utilisateur",
  'Ekle': 'Ajouter',
  'Kaldır': 'Retirer',
  'Kopyalandı: {}': 'Copié : {}',
  'Geçersiz kullanıcı adı': "Nom d'utilisateur invalide",
  'Bağlantı ekle': 'Ajouter un lien',
  'Spoiler olabilir — dokun ve gör':
      'Peut contenir des spoilers — touche pour voir',
  'Beğeni': "J'aime",
  'Beğen': 'Jaime',
  'Görüntülenme': 'Vues',
  'Tam ekran': 'Plein écran',
  'Arama başarısız': 'Échec de la recherche',
  'Sonuç bulunamadı': 'Aucun résultat',
  'Dizi ve Filmler': 'Séries et films',
  'Kişiler': 'Personnes',
  'Ana Sayfa': 'Accueil',
  'Paylaş': 'Partager',
  'Yanıtlar': 'Réponses',
  'Yaklaşan Bölümler': 'Épisodes à venir',
  'Yetişme Listesi': 'Liste de rattrapage',
  'Şunu mu demek istedin': 'Vouliez-vous dire',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — appuie pour voir',
  'uyum': "d'affinité",
  'Uyum': 'Affinité',
  '{} ortak dizi': '{} séries en commun',
  '{} ortak film': '{} films en commun',
  'Bildirim Tercihleri': 'Préférences de notification',
  'Beğeniler': "J'aime",
  'Yeni takipçiler': 'Nouveaux abonnés',
  'Etiketlenmeler': 'Mentions',
  'Yeniden izledim': 'Revu',
  '{}. kez izlendi': 'Vu {} fois',
  'Gönderi bulunamadı': 'Publication introuvable',
  'Gözat': 'Parcourir',
  'Diziler': 'Séries',
  'Filmler': 'Films',
  'Tümü': 'Tout',
  'Farklı bir tür seç.': 'Essaie un autre genre.',
  'Gizlilik': 'Confidentialité',
  'İzlediklerimi gizle': 'Masquer ce que je regarde',
  'Profilinde izlediğin dizi ve filmler görünmez':
      "Les séries et films que tu as vus n'apparaîtront pas sur ton profil",
  'Yorumlarımı gizle': 'Masquer mes commentaires',
  'Profilinde yorumların görünmez':
      "Tes commentaires n'apparaîtront pas sur ton profil",
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Tu peux masquer une série ou un film précis avec la puce « Masquer sur mon profil » sur sa page.',
  'Geri Bildirim': 'Ton avis',
  'Uygulama hakkında görüş ve önerini yaz...':
      "Écris ton avis et tes suggestions sur l'appli...",
  'Teşekkürler! Geri bildirimin alındı.': 'Merci ! Ton avis a bien été reçu.',
  'Profilimde gizle': 'Masquer sur mon profil',
  'Yorumları': 'Commentaires',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Aucun contenu regardé pour le moment.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Cet utilisateur préfère garder ses commentaires privés.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Données : JustWatch',
  'Web Sitesi': 'Site web',
  'Diğer uygulamalar': 'Autres applis',
  'Bağlantıyı kopyala': 'Copier le lien',
  'Henüz kimseyi takip etmiyorsun.': 'Tu ne suis encore personne.',
  'Çevir': 'Traduire',
  'Çeviri şu an yapılamadı': 'Traduction impossible pour le moment',
  'Bağlantı açılamadı': 'Ouverture du lien impossible',
  'Orijinali göster': "Voir l'original",
  'Çeviriyi göster': 'Afficher la traduction',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      "Aucun épisode avec une date de diffusion annoncée ce mois-ci. Les dates sont généralement révélées quelques semaines à l'avance et apparaîtront ici.",
  'devamı': 'plus',
  'Google ile devam et': 'Continuer avec Google',
  'Google girişi başarısız': 'Échec de la connexion Google',
  'Veri tasarrufu': 'Économiseur de données',
  'Wi-Fi ağında veri tasarrufu': 'Économiseur de données en Wi-Fi',
  'Mobil veride veri tasarrufu': 'Économiseur de données en données mobiles',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Quand il est activé, les photos ne sont pas téléchargées à lavance ; seule limage que tu regardes se charge.',
  'Çocuk güvenliği': 'Sécurité des enfants',
  'Türk Filmleri': 'Films turcs',
  'En Yüksek Puanlı Filmler': 'Films les mieux notés',
  'En Yüksek Puanlı Diziler': 'Séries les mieux notées',
  'En Çok İzlenen Filmler': 'Films les plus vus',
  'Popüler Diziler': 'Séries populaires',
  'En Çok Kazanan Filmler': 'Films les plus rentables',
  'Kült Filmler': 'Films cultes',
  'Yeni Filmler': 'Nouveaux films',
  'Yorum yap': 'Commenter',
  'Henüz yorum yok': 'Pas encore de commentaires',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Tes commentaires sur les séries et films sont réunis ici.',
  'GIF ekle': 'Ajouter un GIF',
  'İlk yorumu sen yaz': 'Sois le premier à commenter',
  'Video altyazıları': 'Sous-titres vidéo',
  'Videolarda altyazı göster': 'Afficher les sous-titres sur les vidéos',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'La phrase prononcée dans la vidéo est écrite à l’écran. Le texte est une traduction : anglais dans la langue turque, turc dans d’autres langues.',
  'Güncelleme gerekli': 'Mise à jour requise',
  'Yeni sürüm var': 'Nouvelle version disponible',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Installe la nouvelle version de dizi.jpg pour continuer.',
  'Güncelle': 'Mettre à jour',
  'Daha sonra': 'Plus tard',
  'Takvim güncelleniyor': 'Mise à jour du calendrier',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Impossible de mettre à jour le calendrier, ancienne liste affichée',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Certaines séries ne se sont pas chargées, la liste peut être incomplète',
  'Yenile': 'Actualiser',
  'Devam etmek için giriş yap': 'Connecte-toi pour continuer',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Un compte gratuit suffit pour noter, commenter et créer ta bibliothèque.',
  'Şimdi değil': 'Pas maintenant',
  'Yorum yazmak için giriş yap': 'Connecte-toi pour écrire un commentaire',
  'Kişilere göndermek için giriş yap':
      'Connecte-toi pour envoyer à des personnes',
  'Beğenenler': 'Mentions Jaime',
  'Henüz beğeni yok': 'Pas encore de mentions Jaime',
  'Bu gönderiyi ilk beğenen sen ol':
      'Sois la premiere personne a aimer ce post',
  'Bu gönderiye yanıt': 'Reponse a cette publication',
  'Spoiler içeren gönderi': 'Publication avec spoilers',
  'Görsel gönderi': 'Publication avec photo',
  'Bu yorumu profilimde gizle': 'Masquer ce commentaire sur mon profil',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Le commentaire reste sur la page de la série et du film',
  'Bu yorumu sil': 'Supprimer ce commentaire',
  'Yorum profilinde gizlendi': 'Commentaire masqué sur ton profil',
  'Geri al': 'Annuler',
  'Yorum silinsin mi?': 'Supprimer le commentaire ?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Ce commentaire sera supprimé définitivement partout. Impossible d’annuler.',
  'Yorum silindi': 'Commentaire supprimé',
  'Yorum profilinde tekrar görünüyor':
      'Le commentaire est de nouveau visible sur ton profil',
  'Gizlenen yorumun yok': 'Aucun commentaire masqué',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Les commentaires que tu masques en appuyant longuement sur une publication dans l’onglet Commentaires de ton profil s’accumulent ici.',
  'Gizlenen yorumlar': 'Commentaires masqués',
  'Gönderiye git': 'Aller à la publication',
  'Tekrar göster': 'Afficher à nouveau',
  'Yanıtlarımı gizle': 'Masquer mes réponses',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Les réponses que tu écris aux publications des autres ne sont visibles que par toi',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Afficher à nouveau les commentaires que tu as masqués sur ton profil',
  'Sıralama': 'Tri',
  'Önerilen': 'Recommandé',
  'Kronolojik': 'Chronologique',
  'Gelen mesaj istekleri': 'Demandes de message reçues',
  'Mesaj isteğin yok': 'Aucune demande de message',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Les messages des personnes que vous ne suivez pas apparaissent ici.',
  'Çevrimiçi durumumu gizle': 'Masquer mon statut en ligne',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Les autres ne verront pas votre statut en ligne ni votre dernière connexion dans les messages',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Fait partie de nos premiers utilisateurs. Ses retours ont aidé cette application à devenir ce que nous avons maintenant.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Tu fais partie de nos premiers utilisateurs. Tes retours ont aidé cette application à devenir ce que nous avons maintenant.',
  'İleri': 'Suivant',
  'Seçilen dosya okunamadı': 'Impossible de lire le fichier sélectionné',
  'Video açılamadı': 'Impossible d’ouvrir la vidéo',
  'En fazla {} medya seçebilirsin':
      'Vous pouvez sélectionner au maximum {} médias',
  'Hiçbir medya yüklenemedi': 'Aucun média envoyé',
  'Seçimi kaldır': 'Retirer de la sélection',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'Limite totale par commentaire : {} MB',
  '{} dosya okunamadı': '{} fichiers illisibles',
  '{} medya eklendi, {} yüklenemedi': '{} médias ajoutés, {} en échec',
  'Kırp': 'Recadrer',
  'Çiz': 'Dessiner',
  'Metin': 'Texte',
  'Emoji': 'Emoji',
  'Yinele': 'Rétablir',
  'Daha fazla': 'Plus',
  'Hazırlanıyor…': 'Préparation…',
  'Düzenlemeden çık?': 'Quitter la retouche ?',
  'Yaptığın değişiklikler kaybolacak.': 'Vos modifications seront perdues.',
  'Çık': 'Quitter',
  'Serbest çizim': 'Main levée',
  'Ok': 'Flèche',
  'Dikdörtgen': 'Rectangle',
  'Daire': 'Cercle',
  'Bulanıklaştır': 'Flouter',
  'Pikselleştir': 'Pixelliser',
  'Silgi': 'Gomme',
  'Çizgi kalınlığı': 'Épaisseur du trait',
  'Saydamlık': 'Opacité',
  'Dolgu': 'Remplissage',
  'Renk': 'Couleur',
  'Döndür': 'Pivoter',
  'Yansıt': 'Retourner',
  'Oran': 'Format',
  'Sıfırla': 'Réinitialiser',
  'Serbest': 'Libre',
  'Metin yaz...': 'Saisir du texte...',
  'Hizala': 'Aligner',
  'Arka plan': 'Arrière-plan',
  'Emoji ara...': 'Rechercher un emoji...',
  'Son kullanılanlar': 'Récents',
  'İfadeler ve insanlar': 'Smileys et personnes',
  'Hayvanlar ve doğa': 'Animaux et nature',
  'Yiyecek ve içecek': 'Nourriture et boissons',
  'Etkinlikler': 'Activités',
  'Seyahat ve yerler': 'Voyages et lieux',
  'Nesneler': 'Objets',
  'Semboller': 'Symboles',
  'Bayraklar': 'Drapeaux',
  'Görseli düzenle': 'Modifier la photo',
  'Düzenlendi': 'Modifiée',
  'Düzenlenemedi': 'Modification impossible',
  'Düzenlenen görsel çok büyük': 'Image modifiée trop volumineuse',
  'Videoyu düzenle': 'Modifier la video',
  'Sesi kapat': 'Couper le son',
  'Sesi aç': 'Activer le son',
  'İptal ediliyor…': 'Annulation…',
  'Bu biraz sürebilir': 'Cela peut prendre un moment',
  'Video çok büyük': 'La video est trop volumineuse',
  'Video hazırlanamadı': 'Impossible de preparer la video',
  'Başlangıç': 'Debut',
  'Bitiş': 'Fin',
  'En çok {} saniye seçebilirsin':
      'Vous pouvez selectionner jusqu a {} secondes',
  'Dosya en fazla {} MB olabilir': 'Le fichier peut faire au maximum {} MB',
  'Medya ekle': 'Ajouter un média',
  'Seçili medya kalmadı': 'Aucun média sélectionné',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Choisis une photo ou une vidéo à ajouter à ton commentaire.',
  'Medya seç': 'Sélectionner un média',
  'Daha fazla ekle': 'En ajouter d’autres',
  'Medya seçilemedi': 'Impossible de sélectionner le média',
  'Favori oyuncular': 'Acteurs favoris',
  'Henüz favori oyuncun yok': 'Pas encore d acteurs favoris',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Ouvre la page d un acteur et touche le coeur en haut a droite pour l ajouter ici.',
  '{} yapımdan {} tanesini izledin': 'Tu as vu {} sur {} titres',
  'izledin': 'vus',
  'İzlemedin': 'Non vu',
  'Yapım bulunamadı': 'Aucun titre trouve',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Cette personne n a aucune serie ni film a lister.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Ton historique est lie a ton compte ; cette liste n appartient qu a toi.',
  'Hesabın kalıcı olarak askıya alındı':
      'Ton compte a été suspendu définitivement',
  'Hesabın geçici olarak askıya alındı':
      'Ton compte a été suspendu temporairement',
  'Hesabın askıya alındı': 'Ton compte est suspendu',
  'Sebep': 'Motif',
  'Kalan süre': 'Temps restant',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Ton compte sera rouvert automatiquement à la fin du délai',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'Tu peux continuer à lire pendant ce temps, mais tu ne peux pas publier, commenter ni envoyer de messages.',
  'Anladım': 'Compris',
  'Ayrıntı': 'Détails',
  '{} dakika': '{} minutes',
  'birkaç saniye': 'quelques secondes',
  'Karara itiraz et': 'Contester cette décision',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Explique pourquoi cette sanction devrait être levée',
  'İtirazını gönder': 'Envoyer ta contestation',
  'İtirazın incelemede': 'Ta contestation est en cours dexamen',
  'İtirazın reddedildi': 'Ta contestation a été rejetée',
  'İtirazın alındı, inceleniyor':
      'Ta contestation a bien été reçue et est en cours dexamen',
  'İtiraz en az 10 karakter olmalı':
      'La contestation doit faire au moins 10 caractères',
  'Yükleniyor...': 'Chargement...',
  'Bu bölüme puan ver': 'Notez cet épisode',
  '{} kişi puanladı': '{} personnes ont noté',
  'Bölüm izlendi olarak işaretlendi': 'Épisode marqué comme vu',
  'Sesli ara': 'Appel audio',
  'Görüntülü ara': 'Appel vidéo',
  'Çalıyor...': 'Sonnerie...',
  'Bağlanıyor...': 'Connexion...',
  'Cevapla': 'Répondre',
  'Reddet': 'Refuser',
  'Sessize al': 'Couper le micro',
  'Hoparlör': 'Haut-parleur',
  'Kamerayı kapat': 'Couper la caméra',
  'Kamerayı çevir': 'Changer de caméra',
  'Cevap yok': 'Pas de réponse',
  'Arama reddedildi': 'Appel refusé',
  'Meşgul': 'Occupé',
  'Bağlanılamadı': 'Connexion impossible',
  'Arama iptal edildi': 'Appel annulé',
  'Arama geçmişi': 'Historique des appels',
  'Gelen arama': 'Appel entrant',
  'Giden arama': 'Appel sortant',
  'Cevapsız arama': 'Appel manqué',
  'Arama şu anda kullanılamıyor':
      'Les appels sont indisponibles pour le moment',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Les appels vidéo sont désactivés, tu peux passer un appel audio',
  'Bu kullanıcıyı arayamazsın': 'Tu ne peux pas appeler cet utilisateur',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Vous devez vous suivre mutuellement pour vous appeler',
  'Bu kullanıcı şu anda aranamıyor':
      'Cet utilisateur ne peut pas être appelé pour le moment',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Trop d’appels manqués. Réessaie dans {}',
  'Zaten bir aramadasın': 'Tu es déjà en appel',
  'Arama için mikrofon izni gerekiyor':
      'L’autorisation du microphone est nécessaire pour appeler',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'L’autorisation de la caméra et du microphone est nécessaire pour les appels vidéo',
  'Arama başlatılamadı': 'Impossible de démarrer l’appel',
  'Kullanıcı bulunamadı': 'Utilisateur introuvable',
  'Kendini arayamazsın': 'Tu ne peux pas t’appeler toi-même',
  'Arama artık geçerli değil': 'Cet appel n’est plus valide',
  'Bu aramanın tarafı değilsin': 'Tu ne fais pas partie de cet appel',
  'Arama bulunamadı': 'Appel introuvable',
  'Çok fazla istek, biraz bekle': 'Trop de requêtes, patiente un peu',
  'Bağlantı koptu': 'Connexion perdue',
  'Arama süre sınırına ulaştı': 'L’appel a atteint sa limite de durée',
  'Arama en fazla 4 saat sürebilir': 'Un appel peut durer au maximum 4 heures',
  'Arama sona erdi': 'L’appel est terminé',
  'Sesli arama': 'Appel audio',
  'Görüntülü arama': 'Appel vidéo',
  'Gelen aramalar': 'Appels entrants',
  'Sesli ve görüntülü arama bildirimleri':
      'Notifications d’appels audio et vidéo',
  '{} sa': '{} h',
  'Sesli ve Görüntülü Aramalar': 'Appels audio et vidéo',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Le contenu des appels n’est jamais enregistré. L’audio et la vidéo circulent chiffrés de bout en bout (DTLS-SRTP) entre les appareils ; nos serveurs ne peuvent ni déchiffrer, ni écouter, ni conserver ce trafic.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Seules les métadonnées de l’appel sont conservées : avec qui, dans quel sens, quand et pendant combien de temps. Ces enregistrements sont supprimés automatiquement au bout de 90 jours.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Si une connexion directe est impossible, l’audio et la vidéo transitent chiffrés par un serveur relais (TURN). Ce relais ne peut pas non plus déchiffrer ni enregistrer le contenu.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Le microphone n’est utilisé que pendant un appel audio ou vidéo, et la caméra uniquement pendant un appel vidéo. Les deux sont coupés à la fin de l’appel.',
  'Takip ettiğin {} kişi izledi': "{} personnes que tu suis l'ont regardé",
  'Yorum yaz...': 'Écris un commentaire...',
  'Sıradaki bölüm': 'Épisode suivant',
  'Doğrulanmış testçi': 'Testeur vérifié',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      "Notifications de suivis, j'aime, réponses, messages et mentions",
  'Sen': 'Toi',
  'Aradığınız kişide sesli arama devre dışı':
      'Les appels vocaux sont désactivés pour cette personne',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Les appels vidéo sont désactivés pour cette personne',
  'Sesli aramalara izin ver': 'Autoriser les appels vocaux',
  'Görüntülü aramalara izin ver': 'Autoriser les appels vidéo',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      "Si désactivé, personne ne peut t'appeler en vocal ; l'appelant voit un avis",
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      "Si désactivé, personne ne peut t'appeler en vidéo ; l'appelant voit un avis",
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Les appels vocaux sont désactivés. Tu peux les activer dans Paramètres > Confidentialité.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Les appels vidéo sont désactivés. Tu peux les activer dans Paramètres > Confidentialité.',
  'Sesli ve görüntülü arama': 'Appels vocaux et vidéo',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Les comptes invités ne peuvent pas appeler. Crée un compte pour l’utiliser.',
  'Misafir hesaplar aranamaz': 'Impossible d’appeler un compte invité',
  'Puan dağılımı': 'Répartition des notes',
  '{} yıldız': '{} étoiles',
  'Yakında gelecek': 'Bientôt disponible',
  '{} {} yayınlandı': '{} {} est disponible',
  'Yeni bölüm yayınlandı': 'Nouvel épisode disponible',
  'Yeni bölümler': 'Nouveaux épisodes',
  'Geri': 'Retour',
  'Karşılamayı kapat': "Fermer l'introduction",
  'Adım {} / {}': 'Étape {} / {}',
  'Hadi başlayalım': "C'est parti",
  'Kaydet ve devam': 'Enregistrer et continuer',
  '{} tanesini ekle': 'Ajouter {}',
  'Şimdilik geç': 'Plus tard',
  'Doğum tarihin ne zaman?': 'Quelle est ta date de naissance ?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      "On te le demande pour t'afficher des contenus adaptés à ton âge et pour te souhaiter ton anniversaire.",
  'Gün': 'Jour',
  'Ay': 'Mois',
  'Yıl': 'Année',
  'Doğum yılımı paylaşmak istemiyorum':
      'Je ne veux pas partager mon année de naissance',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      "Ta date de naissance n'est pas affichée publiquement sur ton profil. Elle sert uniquement aux contenus adaptés à l'âge et aux vœux d'anniversaire.",
  'Ocak': 'janvier',
  'Şubat': 'février',
  'Mart': 'mars',
  'Nisan': 'avril',
  'Mayıs': 'mai',
  'Haziran': 'juin',
  'Temmuz': 'juillet',
  'Ağustos': 'août',
  'Eylül': 'septembre',
  'Ekim': 'octobre',
  'Kasım': 'novembre',
  'Aralık': 'décembre',
  'Verilerini yanında getir': 'Emporte tes données avec toi',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Si tu suis ce que tu regardes dans une autre appli, tu peux tout transférer ici. Pas besoin de repartir de zéro.',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt et Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Choisis le fichier ZIP que tu as exporté : ce que tu as regardé, tes notes et tes listes seront importés.',
  'Aktarılıyor...': 'Import en cours...',
  'ZIP dosyası seç': 'Choisir un fichier ZIP',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'Rien ne presse : tu peux aussi le faire plus tard dans Paramètres > Mes données.',
  'Hangi filmleri izledin?': 'Quels films as-tu vus ?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Voici les plus regardés. Touche ceux que tu as vus et on les ajoute à ton historique.',
  'SERİ FİLMLER': 'SAGAS',
  'Serilerden {} film eklendi': '{} films ajoutés depuis les sagas',
  'Film listesi yüklenemedi': 'Impossible de charger la liste des films',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Tu peux passer cette étape et ajouter ce que tu veux plus tard.',
  '{} film izlediklerine eklendi': '{} films ajoutés à ton historique',
  'Film serileri': 'Sagas de films',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Si tu as vu une saga du début à la fin, ajoute-la en une seule touche.',
  'Seri bulunamadı': 'Aucune saga trouvée',
  'Daha sonra tekrar deneyebilirsin.': 'Tu peux réessayer plus tard.',
  '{} film': '{} films',
  'Eklendi': 'Ajouté',
  'Tümünü izledim': 'Je les ai tous vus',
  'Peki ya diziler?': 'Et les séries ?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Coche ce que tu as vu : au fil de tes choix, on te propose des séries similaires.',
  'Dizi listesi yüklenemedi': 'Impossible de charger la liste des séries',
  'Seçtiklerine benzeyenler': 'Similaires à tes choix',
  'Her şey hazır': 'Tout est prêt',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Jette un œil rapide à ce que tu peux faire sur dizi.jpg.',
  'Profilini tamamla': 'Complète ton profil',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'Depuis Paramètres, tu peux ajouter une bio, une photo de profil et une couverture.',
  'Takvimin seni bekliyor': "Ton calendrier t'attend",
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      "Les nouveaux épisodes de tes séries s'ajoutent au calendrier et on te prévient par notification.",
  'Puan ver, yorum yaz': 'Note et commente',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Note épisode par épisode, commente derrière un voile spoiler et crée des listes.',
  'Verilerin sende kalır': 'Tes données restent les tiennes',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Tes données sont conservées uniquement liées à ton compte et ne sont pas vendues. Depuis Paramètres, tu peux toutes les télécharger ou supprimer complètement ton compte.',
  'Engellenen kullanıcılar': 'Personnes bloquées',
  'Engellediğin kişileri gör, engeli kaldır':
      'Vois qui tu as bloqué et retire le blocage',
  'Engellediğin kimse yok': "Tu n'as bloqué personne",
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Tu peux bloquer une personne depuis le menu à trois points de son profil.',
  '@{} engellensin mi?': 'Bloquer @{} ?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      "Aucune des deux parties ne verra les publications, les commentaires ni le profil de l'autre ; les messages et les appels seront également impossibles. S'il existe un lien d'abonnement, il est rompu et ne revient pas, même si tu retires le blocage.",
  'Bu kullanıcıyı engelledin': 'Tu as bloqué cette personne',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Tu ne vois pas les publications, les commentaires ni les messages de cette personne ; elle ne voit pas les tiens non plus.',
  '{} yeni bir yapımda: {}': '{} est dans une nouvelle production : {}',
  'Favori kişinden yeni yapım': "Nouvelle production d'une personne favorite",
  '{} için bildirimler': 'Notifications pour {}',
  'Tüm bildirimler': 'Toutes les notifications',
  'Uygulamada ve telefonda': "Dans l'appli et sur le téléphone",
  'Yalnız uygulama içi': "Dans l'appli uniquement",
  'Telefon bildirimi gönderilmez':
      "Aucune notification n'est envoyée sur le téléphone",
  'Kapalı': 'Désactivé',
  'Bu kişi için bildirim yok': 'Aucune notification pour cette personne',
  'Favori kişilerin yeni yapımları':
      'Nouvelles productions de tes personnes favorites',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Si désactivé, personne ne peut t\'appeler en vocal ; l\'appelant voit l\'avis "désactivés"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Si désactivé, personne ne peut t\'appeler en vidéo ; l\'appelant voit l\'avis "désactivés"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'Mon activité',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'Tes j’aime, commentaires et visionnages au même endroit',
  'Henüz hareketin yok': 'Pas encore d’activité',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Tout ce que tu aimes, commentes et regardes s’accumule ici.',
  'Bu süzgeçte hareket yok': 'Aucune activité dans ce filtre',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Choisis un autre type ou reviens à « Tout ».',
  'Hepsi': 'Tout',
  'Puan': 'Note',
  'Tepki': 'Réaction',
  'İzleme': 'Visionnage',
  'Durum': 'Statut',
  'Liste': 'Liste',
  'Yorum yaptın': 'Tu as commenté',
  'Yorumu beğendin': 'Tu as aimé un commentaire',
  '{} puan verdin': 'Tu as noté {}',
  'Tepki verdin': 'Tu as réagi',
  'Listene ekledin': 'Tu as ajouté à une liste',
  'Takip etmeye başladın': 'Tu as commencé à suivre',
  '"İzleyeceğim" işaretledin': 'Marqué « À voir »',
  '"İzliyorum" işaretledin': 'Marqué « Je regarde »',
  '"Bitirdim" işaretledin': 'Marqué « Terminé »',
  '"Bıraktım" işaretledin': 'Marqué « Abandonné »',
  'Silinmiş içerik': 'Contenu supprimé',
  'şimdi': 'à l’instant',
  '{} g': '{} j',
  '{} y': '{} a',
  'İstatistiklerim': 'Mes statistiques',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Vues et j’aime de tes publications',
  'Henüz gönderin yok': 'Tu n’as pas encore de publication',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Dès que tu commentes une série ou un film, tes vues et j’aime commencent à s’accumuler ici.',
  'Tüm zamanlar': 'Depuis toujours',
  'Son {} gün': '{} derniers jours',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'L’historique des vues n’a pas encore commencé à s’accumuler ; les données du premier jour apparaîtront demain.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'L’historique des vues s’accumule depuis le {} ({} jours de données), donc le total sur {} jours est encore incomplet.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'L’historique des j’aime est enregistré depuis le {}.',
  'Bu dönemde gösterilecek gönderi yok.':
      'Aucune publication à afficher pour cette période.',
  'eksik veri': 'données incomplètes',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Les séries et films que tu as vus, tes compteurs de visionnage, ton temps d’écran et ta carte d’affinité ne seront pas visibles par les autres sur ton profil',
  'Takipçi listemi gizle': 'Masquer ma liste d’abonnés',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Les autres ne peuvent pas voir qui te suit ; ton nombre d’abonnés reste visible',
  'Takip ettiklerimi gizle': 'Masquer les personnes que je suis',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Les autres ne peuvent pas voir qui tu suis ; ton nombre d’abonnements reste visible',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Cet utilisateur préfère garder ses abonnés privés.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Cet utilisateur préfère garder privées les personnes qu’il suit.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Statistiques de la publication',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Tu ne peux voir que les statistiques de tes propres publications.',
  'Erişim': 'Portée',
  'Görüntüleyen': 'Spectateurs',
  'Kaç farklı kişi gördü (son {} gün)':
      'Combien de personnes différentes l’ont vu (derniers {} jours)',
  'Paylaşım': 'Partages',
  'Bu gönderiden sonra': 'Après cette publication',
  'Profil ziyareti': 'Visites du profil',
  'Yeni takip': 'Nouveaux abonnements',
  'İçeriğe tıklama': 'Clics sur le contenu',
  'Spoiler perdesini açan': 'Ont révélé le spoiler',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Les partages, visites du profil, abonnements, clics sur le contenu, la répartition par source et les mesures de spoiler s’accumulent depuis le {} ; ce qui précède n’a pas été mesuré.',
  'Zamana yayılmış görüntülenme': 'Vues dans le temps',
  'Görüntülenme nereden geldi': 'D’où viennent les vues',
  'Kimler gördü': 'Qui l’a vu',
  'Günlük veri henüz birikmeye başlamadı.':
      'Les données quotidiennes n’ont pas encore commencé à s’accumuler.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'Le graphique nécessite au moins deux jours de données. Les données s’accumulent depuis le {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'Le plus de vues est arrivé le {}ᵉ jour après la publication : {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Les vues quotidiennes s’accumulent depuis le {} ; ce qui précède n’a pas été mesuré.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'La répartition par source vient tout juste d’être mesurée ; cette publication n’a pas encore reçu de vue étiquetée.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'La répartition entre abonnés et découverte vient tout juste d’être mesurée ; il n’y a pas encore de données.',
  'Takip edenler': 'Abonnés',
  'Keşiften gelenler': 'Depuis Découvrir',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Page série/film',
  'Paylaşılan bağlantı': 'Lien partagé',
  'yeni ölçülüyor': 'mesure récente',
  'Kendi ortalamanla aynı düzeyde': 'Au niveau de ta propre moyenne',
  'Kendi ortalamanın %{} üstünde': '{} % au-dessus de ta propre moyenne',
  'Kendi ortalamanın %{} altında': '{} % en dessous de ta propre moyenne',
  'Etkileşim oranı': 'Taux d’engagement',
  '(beğeni + yorum) ÷ görüntülenme': '(j’aime + commentaires) ÷ vues',
  'Toplam görüntülenme': 'Vues totales',
  '{} ile {} arasında toplam {} görüntülenme':
      'Entre le {} et le {} : {} vues au total',
  'İstatistikleri gör': 'Voir les statistiques',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'Pour les statistiques présentées à la personne propriétaire d’une publication, sont conservés sous forme de compteurs agrégés : combien de fois et depuis quelle surface (fil, profil, fil en plein écran, page série/film, lien partagé) la publication a été vue, si la personne qui l’a vue suivait alors la personne propriétaire, le passage de la publication au profil ou au contenu, les abonnements créés depuis la publication, les partages et l’ouverture du voile de spoiler. Ces compteurs ne contiennent ni identité d’utilisateur, ni adresse IP, ni horodatage ; il est impossible de savoir qui a fait quoi.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'Afin de pouvoir compter combien de personnes différentes ont vu une publication, un condensé à clé irréversible par personne l’ayant vue (une réduction cryptographique dérivée de l’identité d’utilisateur ou de l’adresse IP) est conservé pendant 90 jours. Seul le nombre est présenté à la personne propriétaire de la publication ; l’identité de celles qui l’ont vue n’est en aucun cas partagée.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'Déplacer vers « À voir » ?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'Un titre est soit à voir, soit vu. Si tu continues, tes {} marques de visionnage sur cette série seront supprimées.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'Un titre est soit à voir, soit vu. Si tu continues, ta marque « Vu » sur ce film sera retirée.',
  'Sil ve taşı': 'Supprimer et déplacer',

  // --- Yapım ekibi / firma + seviye unvanları + doğum günü ---
  'Yapım Ekibi': 'Équipe technique',
  'Yaratıcı': 'Création',
  'Yönetmen': 'Réalisation',
  'Senaryo': 'Scénario',
  'Yapımcı': 'Production',
  'Yapım Firmaları': 'Sociétés de production',
  'Yapım Firması': 'Société de production',
  'Firma bulunamadı': 'Société introuvable',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'Cette société n’a aucun titre de ce type.',
  'Doğum günün kutlu olsun!': 'Joyeux anniversaire !',
  'İyi ki doğdun, iyi ki buradasın.':
      'Ta naissance, c’était une bonne idée. Ta présence ici aussi.',
  'Bugün {} yaşına girdin': 'Aujourd’hui, tu as {} ans',
  'Teşekkürler': 'Merci',
  'İki Adımlı Doğrulama': 'Validation en deux étapes',
  'Girişte e-postana kod gönderilir':
      'Un code est envoyé à ton e-mail lors de la connexion',
  'Kod {} adresine gönderildi': 'Code envoyé à {}',
  '6 haneli kod': 'Code à 6 chiffres',
  'Doğrula': 'Vérifier',
  'Yeniden gönder': 'Renvoyer',
  'Vazgeç': 'Annuler',
  'Yeni kod gönderildi': 'Nouveau code envoyé',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      "Aucun code n'est demandé lors de la connexion avec Google ; Google effectue sa propre vérification.",
  'Kapatmak için de kod gerekir.': 'La désactivation demande aussi un code.',
  'E-postana erişemezsen hesabına giremezsin.':
      'Sans accès à ton e-mail, tu ne peux plus te connecter à ton compte.',
  'İki adımlı doğrulama açıldı': 'Validation en deux étapes activée',
  'İki adımlı doğrulama kapatıldı': 'Validation en deux étapes désactivée',
  'Videonun ne kadarı izlendi': 'Jusqu’où la vidéo est regardée',
  'Videoyu başlatanlar': 'Ont lancé la vidéo',
  'videonun %{} noktasına ulaştı': 'ont atteint {} % de la vidéo',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'La moitié du public a vu au moins {} % de la vidéo.',
  'Sonuna kadar izleyen: %{}': 'Vu jusqu’à la fin : {} %',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'La courbe nécessite au moins {} lectures ; il y en a {} pour le moment.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'La courbe est basée sur {} lectures et ne dépend pas de la période choisie.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'La durée de visionnage est mesurée depuis le {} ; les vues plus anciennes ne comptent pas.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} lectures. {} % ont atteint la moitié, {} % la fin.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{} %',
  'Seviye {}': 'Niveau {}',
  'Sonraki seviyeye {} puan kaldı': '{} points avant le niveau suivant',
  'Gönderilerin': 'Tes publications',
  '{} gönderi': '{} publications',
  '{} gönderi · {} görüntülenme': '{} publications · {} vues',
  'önceki {} güne göre': 'vs {} jours précédents',
  'önceki {} güne göre %{} arttı':
      'par rapport aux {} jours précédents, hausse de {} %',
  'önceki {} güne göre %{} azaldı':
      'par rapport aux {} jours précédents, baisse de {} %',
  'önceki {} güne göre değişmedi':
      'sans changement par rapport aux {} jours précédents',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'Vues quotidiennes : minimum {}, maximum {}',
  'Etkileşim oranı henüz ölçülemedi': 'Taux d’engagement pas encore mesurable',
  'Oranlar': 'Taux',
  'Beğenme oranı': 'Taux de j’aime',
  'Yorum oranı': 'Taux de commentaires',
  'Paylaşma oranı': 'Taux de partages',
  'İçeriğe gitme oranı': 'Taux de clics contenu',
  'Profile gitme oranı': 'Taux de visites profil',
  'Ziyaretten takibe dönüşüm': 'Visite vers abonnement',
  'beğeni ÷ görüntülenme': 'j’aime ÷ vues',
  'yorum ÷ görüntülenme': 'commentaires ÷ vues',
  'paylaşım ÷ görüntülenme': 'partages ÷ vues',
  'içeriğe tıklama ÷ görüntülenme': 'clics sur le contenu ÷ vues',
  'profil ziyareti ÷ görüntülenme': 'visites du profil ÷ vues',
  'yeni takip ÷ profil ziyareti': 'nouveaux abonnements ÷ visites du profil',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'Les taux nécessitent au moins {} vues ; il y en a {} pour le moment.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'Les taux proviennent des totaux depuis la publication ; le choix des jours ci-dessous ne les modifie pas.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'Ces chiffres sont les totaux depuis la publication (sauf les blocs qui ont leur propre note) ; le choix des jours ci-dessous ne modifie que le graphique.',
  'Ortalama izlenme: videonun %{} kadarı':
      'Visionnage moyen : {} % de la vidéo',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'La moyenne des 20 segments de la courbe.',
  'Dizi, film, kişi veya şirket ara...':
      'Cherche une série, un film, une personne ou une société...',
  'Şirketler': 'Sociétés',
  'Senarist': 'Scénariste',
  'Bölüm puanları': 'Notes des épisodes',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'Impossible de charger les notes',
};
