/// Otomatik üretilen çeviri haritası (fi).
const Map<String, String> cevirilerFi = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Olet nähnyt kaiken, näytämme sinulle alusta alkaen',
  'Aktarılacak tanınan veri bulunamadı.':
      'Tuotavaa tunnistettua dataa ei löytynyt.',
  'Arama': 'Haku',
  'Aramaya başla': 'Aloita haku',
  'Son aramalar': 'Viimeisimmät haut',
  'Ayarlar': 'Asetukset',
  'Bağla': 'Yhdistä',
  'Bio': 'Bio',
  'Bitirdim': 'Katsoin loppuun',
  'Bunları da Beğenebilirsin': 'Saattaisit pitää myös näistä',
  'Bölüm': 'Jakso',
  'Bıraktım': 'Jätin kesken',
  'Dil': 'Kieli',
  'Dil ara...': 'Hae kieltä...',
  'Dizi': 'Sarja',
  'Dizi ve filmlerini takip et': 'Seuraa sarjojasi ja elokuviasi',
  'Dizi yorumu': 'Sarjan kommentti',
  'Dizi, film veya kişi ara...': 'Hae sarjaa, elokuvaa tai henkilöä...',
  'Dosya en fazla 30MB olabilir': 'Tiedosto saa olla enintään 30 MB',
  'Dosya en fazla {}MB olabilir': 'Tiedosto saa olla enintään {} MB',
  'E-posta': 'Sähköposti',
  'E-posta veya kullanıcı adı': 'Sähköposti tai käyttäjänimi',
  'En az 2 harf yaz': 'Kirjoita vähintään 2 kirjainta',
  'Film': 'Elokuva',
  'Film yorumu': 'Elokuvan kommentti',
  'Fotoğraf / video ekle': 'Lisää kuva / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Kuva tai GIF — profiili- ja kansikuva',
  'Giriş Yap': 'Kirjaudu sisään',
  'Gönder': 'Lähetä',
  'Gönderildi': 'Lähetetty',
  'Haftanın Dizileri': 'Viikon sarjat',
  'Haftanın Filmleri': 'Viikon elokuvat',
  'Henüz izleme kaydın yok': 'Sinulla ei ole vielä katseluhistoriaa',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Sinulla ei ole vielä listoja — luo yksi Profiili-välilehdellä.',
  'Henüz yorum yok.': 'Ei vielä kommentteja.',
  'Hesabın bağlandı!': 'Tilisi on yhdistetty!',
  'Hesabın yok mu? Kayıt ol': 'Eikö sinulla ole tiliä? Rekisteröidy',
  'Hesabını Bağla': 'Yhdistä tilisi',
  'Hesap Oluştur': 'Luo tili',
  'Kapak resmi ekle': 'Lisää kansikuva',
  'Kaydet': 'Tallenna',
  'Kendinden bahset...': 'Kerro itsestäsi...',
  'Keşfet': 'Löydä',
  'Kimseyi takip etmiyor': 'Ei seuraa ketään',
  'Kişi ara': 'Hae henkilöä',
  'Kişi yorumu': 'Henkilön kommentti',
  'Konuk Oyuncular': 'Vierailevat tähdet',
  'Kullanıcı adı (küçük harf)': 'Käyttäjänimi (pienin kirjaimin)',
  'Kullanıcı adı ara...': 'Hae käyttäjänimeä...',
  'Liste adı': 'Listan nimi',
  'Listeye Ekle': 'Lisää listaan',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Käytät vierastiliä — yhdistä se sähköpostiisi, ettet menetä tietojasi!',
  'Misafir olarak devam et': 'Jatka vieraana',
  'Oluştur': 'Luo',
  'Oyuncular': 'Näyttelijät',
  'Profil': 'Profiili',
  'Profil kaydedildi': 'Profiili tallennettu',
  'Puanla': 'Anna arvosana',
  'Puanı Sil': 'Poista arvosana',
  'Puanın': 'Arvosanasi',
  'Sezonlar': 'Kaudet',
  'Sunucu hatası ({})': 'Palvelinvirhe ({})',
  'S{} · {}. Bölüm': 'K{} · J{}',
  'S{}B{} yorumu': 'K{}J{}-kommentti',
  'Takibi Bırak': 'Lopeta seuraaminen',
  'Takip': 'Seuratut',
  'Takip Edilenler': 'Seuratut',
  'Takip Et': 'Seuraa',
  'Takipçi': 'Seuraaja',
  'Takipçi yok': 'Ei seuraajia',
  'Takipçiler': 'Seuraajat',
  'Takvim': 'Kalenteri',
  'Tamam': 'OK',
  'Tekrar Dene': 'Yritä uudelleen',
  'Tekrar dene': 'Yritä uudelleen',
  'Toplam İzleme Süresi': 'Ruutuaika yhteensä',
  'Tüm Zamanların En İyileri': 'Kaikkien aikojen parhaat',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Lataa kaikki tietosi (katselut, arvosanat, kommentit, listat) TV Time -yhteensopivana ZIP-tiedostona tai tuo ZIP toisesta sovelluksesta.',
  'Tümünü Kaldır': 'Poista kaikki',
  'Tümünü İzledim': 'Katsoin kaikki',
  'Türk Dizileri': 'Turkkilaiset sarjat',
  'Veri içe aktar (.zip)': 'Tuo tiedot (.zip)',
  'Verilerim': 'Omat tiedot',
  'Verilerimi dışa aktar (e-posta)': 'Vie tietoni (sähköposti)',
  'Verilerini dışa aktar': 'Vie tietosi',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Ei tulevia jaksoja.\nMerkitse sarja tilaan ”Katson nyt” sen tiedoista ja seuraa uusia jaksoja täällä.',
  'Yapımları': 'Tuotannot',
  'Yeni Diziler': 'Uudet sarjat',
  'Yeni Liste': 'Uusi lista',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Uusi käyttäjänimi (valinnainen)',
  'Yorum': 'Kommentti',
  'Yorumunu yaz...': 'Kirjoita kommenttisi...',
  'Zaten hesabın var mı? Giriş yap': 'Onko sinulla jo tili? Kirjaudu sisään',
  'ort. {}': 'ka. {}',
  'takip': 'seurattua',
  'takipçi': 'seuraajaa',
  '{} / {} bölüm': '{} / {} jaksoa',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} kk',
  '{} bölüm izlendi': '{} jaksoa katsottu',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} gün': '{} pv',
  '{} içerik': '{} nimikettä',
  '{} içerik · otomatik': '{} nimikettä · automaattinen',
  '{} kayıt atlandı (eşleşmedi).': '{} merkintää ohitettiin (ei osumaa).',
  '{} saat': '{} h',
  '{} sezon': '{} kautta',
  '{} yıl': '{} v',
  '{}. Bölüm': '{}. jakso',
  '{}. Sezon': '{}. kausi',
  'Çıkış Yap': 'Kirjaudu ulos',
  'Ülke': 'Maa',
  'Ülke ara...': 'Hae maata...',
  'Ülke seç': 'Valitse maa',
  'İlk yorumu sen yaz!': 'Kirjoita ensimmäinen kommentti!',
  'İncelemeler': 'Arvostelut',
  'İncelemen (isteğe bağlı)': 'Arvostelusi (valinnainen)',
  'İptal': 'Peruuta',
  'İzlediklerim': 'Katseluhistoria',
  'İzledim': 'Katsottu',
  'İzledin': 'Katsoit',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Katseluhistoriasi ja listasi säilyvät; voit jatkossa kirjautua sisään millä tahansa laitteella.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Katseluhistoriasi, arvosanasi, kommenttisi ja listasi lähetetään ZIP-tiedostona rekisteröityyn sähköpostiosoitteeseesi.',
  'İzleyeceğim': 'Aion katsoa',
  'İzliyorum': 'Katson nyt',
  'İçe aktarım tamamlandı': 'Tuonti valmis',
  'Şifre': 'Salasana',
  '• profil bilgisi': '• profiilitiedot',
  '• {} dizi durumu': '• {} sarjan tilaa',
  '• {} izleme kaydı': '• {} katselumerkintää',
  '• {} liste': '• {} listaa',
  '• {} puan': '• {} arvosanaa',
  '• {} yorum': '• {} kommenttia',
  '{}+ yapım': '{}+ tuotantoa',
  'Yorumlar': 'Kommentit',
  'Yorumlar ({})': 'Kommentit ({})',
  'Yorumları ({})': 'Kommentit ({})',
  'Listelerim': 'Omat listat',
  'Nereden izledin?': 'Missä katsoit sen?',
  'Diziye git': 'Siirry sarjaan',
  'TV / Kanal': 'TV / Kanava',
  'Sinema': 'Elokuvateatteri',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Muu',
  'Akış': 'Syöte',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Syötteesi on tyhjä.\nKun katsomiasi sarjoja ja elokuvia kommentoidaan, se näkyy täällä.',
  'Listeleri ({})': 'Hänen listansa ({})',
  'Liste boş.': 'Tämä lista on tyhjä.',
  'Yanıtla': 'Vastaa',
  '@{} kullanıcısına yanıt veriyorsun': 'Vastaat käyttäjälle @{}',
  'İzlediğim Diziler ({})': 'Katsomani sarjat ({})',
  'İzlediğim Filmler ({})': 'Katsomani elokuvat ({})',
  'Tümünü gör': 'Näytä kaikki',
  'Bildirimler': 'Ilmoitukset',
  'Henüz bildirim yok': 'Ei ilmoituksia vielä',
  '@{} yorumuna yanıt verdi': '@{} vastasi kommenttiisi',
  '@{} yorumunu beğendi': '@{} tykkäsi kommentistasi',
  '@{} seni takip etti': '@{} seurasi sinua',
  '@{} sana mesaj gönderdi': '@{} lähetti sinulle viestin',
  'Mesajlar': 'Viestit',
  'Mesaj': 'Viesti',
  'Mesajını yaz...': 'Kirjoita viesti...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Ei keskusteluja vielä.\nAvaa profiili ja lähetä viesti.',
  'Şifreni mi unuttun?': 'Unohditko salasanan?',
  'Şifreyi Sıfırla': 'Nollaa salasana',
  'E-postadaki kod': 'Koodi sähköpostista',
  'Yeni şifre': 'Uusi salasana',
  'Sana Özel': 'Sinulle',
  '{} özetin': '{}-koosteesi',
  'Yıllık izleme istatistiklerin': 'Vuotuiset katselutilastosi',
  'Rozetler': 'Merkit',
  'Verdiğin puan': 'Annetut arvosanat',
  'Ortalama puanın': 'Keskiarvosanasi',
  'En çok izlediğin diziler': 'Katsotuimmat sarjasi',
  'İlk Bölüm': 'Ensimmäinen jakso',
  '100 Bölüm': '100 jaksoa',
  '1000 Bölüm': '1000 jaksoa',
  'İlk Film': 'Ensimmäinen elokuva',
  '50 Film': '50 elokuvaa',
  'İlk Yorum': 'Ensimmäinen kommentti',
  '25 Yorum': '25 kommenttia',
  '10 Puan': '10 arvosanaa',
  'İlk Takipçi': 'Ensimmäinen seuraaja',
  '10 Dizi Bitirdin': '10 sarjaa katsottu loppuun',
  'İzlemeyi Bıraktım': 'Lopetin katsomisen',
  'İzlediği Diziler ({})': 'Katsotut sarjat ({})',
  'İzlediği Filmler ({})': 'Katsotut elokuvat ({})',
  '500 Bölüm': '500 jaksoa',
  '5000 Bölüm': '5000 jaksoa',
  '10 Film': '10 elokuvaa',
  '100 Film': '100 elokuvaa',
  '100 Yorum': '100 kommenttia',
  '50 Puan': '50 arvosanaa',
  '100 Puan': '100 arvosanaa',
  '10 Takipçi': '10 seuraajaa',
  '50 Takipçi': '50 seuraajaa',
  '25 Dizi Bitirdin': '25 sarjaa katsottu loppuun',
  '50 Dizi Bitirdin': '50 sarjaa katsottu loppuun',
  '10 Beğeni': '10 tykkäystä',
  '100 Beğeni': '100 tykkäystä',
  'yazıyor...': 'kirjoittaa...',
  'Profil düzeni': 'Profiilin asettelu',
  'Konumla ve kırp': 'Asettele ja rajaa',
  'Listeye eklendi': 'Lisätty listaan',
  'Listeyi sil?': 'Poistetaanko lista?',
  'Sil': 'Poista',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Tämä merkitään katsomattomaksi ja poistetaan listoiltasi.',
  'Gelecek bölüm bugün': 'Seuraava jakso tänään',
  'Gelecek bölüm {} gün sonra': 'Seuraava jakso {} päivän päästä',
  'Tema': 'Teema',
  'Sistem': 'Järjestelmä',
  'Koyu': 'Tumma',
  'Açık': 'Vaalea',
  'İzleyenler': 'Katsojat',
  'Yorumunu yaz... (@ ile etiketle)':
      'Kirjoita kommenttisi... (@ merkitäksesi)',
  '@{} bir yorumda seni etiketledi': '@{} merkitsi sinut kommenttiin',
  'Mesajı sil': 'Poista viesti',
  'Mesaj silinemedi': 'Viestiä ei voitu poistaa',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Linkki on virheellinen tai sivua ei löytynyt',
  'Keşfet\'e dön': 'Takaisin Löydä-sivulle',
  'Düzenle': 'Muokkaa',
  'Mesajı düzenle': 'Muokkaa viestiä',
  'Yanıtlanıyor': 'Vastataan',
  'düzenlendi': 'muokattu',
  'Fotoğraf': 'Kuva',
  'Video': 'Video',
  'İçerik': 'Sisältö',
  'çevrimiçi': 'paikalla',
  'son görülme {} dk önce': 'nähty {} min sitten',
  'son görülme {} saat önce': 'nähty {} t sitten',
  'son görülme {} gün önce': 'nähty {} pv sitten',
  'Yorumlar yüklenemedi': 'Kommenttien lataus epäonnistui',
  'Favori': 'Suosikki',
  'Listeye ekle': 'Lisää listaan',
  'İçerik paylaş': 'Jaa sisältö',
  'Kapat': 'Sulje',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Kaikki katsotuksi merkitsemäsi kerääntyy tänne.',
  'Henüz sohbetin yok': 'Ei keskusteluja vielä',
  'Bir profile girip mesaj gönderebilirsin.': 'Avaa profiili ja lähetä viesti.',
  'Listeyi sil': 'Poista lista',
  'Puan kaydedilemedi': 'Arvosanan tallennus epäonnistui',
  'Nerede İzlenir': 'Missä katsoa',
  'Abonelik': 'Tilaus',
  'Kirala': 'Vuokraa',
  'Satın al': 'Osta',
  'Hoş geldin!': 'Tervetuloa!',
  'İzlemek istediğin dizi ve filmleri seç':
      'Valitse sarjat ja elokuvat, joita haluat katsoa',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Valintasi lisätään katselulistallesi',
  'Şimdilik atla': 'Ohita nyt',
  'Devam et': 'Jatka',
  '{} ekle': 'Lisää {}',
  'Şikayet et': 'Ilmoita',
  'Engelle': 'Estä',
  'Engeli kaldır': 'Poista esto',
  'Kullanıcı engellendi': 'Käyttäjä estetty',
  'Engel kaldırıldı': 'Esto poistettu',
  'Şikayet sebebi': 'Ilmoituksen syy',
  'Spam veya yanıltıcı': 'Roskaposti tai harhaanjohtava',
  'Taciz veya nefret söylemi': 'Häirintä tai vihapuhe',
  'Uygunsuz / cinsel içerik': 'Sopimaton / seksuaalinen sisältö',
  'Şiddet veya tehlikeli içerik': 'Väkivalta tai vaarallinen sisältö',
  'Telif hakkı ihlali': 'Tekijänoikeusrikkomus',
  'Şikayetin alındı, teşekkürler': 'Ilmoituksesi vastaanotettiin, kiitos',
  'Hesabımı Sil': 'Poista tilini',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Tilisi ja kaikki tietosi (katseluhistoria, arvosanat, kommentit, listat, viestit) poistetaan pysyvästi. Tätä ei voi kumota.',
  'Şifreni gir': 'Anna salasanasi',
  'Hesabımı kalıcı sil': 'Poista tilini pysyvästi',
  'Sesli mesaj': 'Ääniviesti',
  'Ses gönderilemedi': 'Ääniviestiä ei voitu lähettää',
  'Kaydediliyor…': 'Tallennetaan…',
  'Ses oynatılamadı': 'Ääniviestiä ei voitu toistaa',
  'Oynat': 'Toista',
  'Duraklat': 'Keskeytä',
  'Liste görünümü': 'Luettelonäkymä',
  'Takvim görünümü': 'Kalenterinäkymä',
  'Önceki ay': 'Edellinen kuukausi',
  'Sonraki ay': 'Seuraava kuukausi',
  'Bu gün bölüm yok': 'Ei jaksoja tänä päivänä',
  'Gizlilik Politikası': 'Tietosuojakäytäntö',
  'Son güncelleme: {}': 'Viimeksi päivitetty: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Tämä käytäntö kertoo, mitä tietoja kerätään, miten niitä käytetään ja mitkä ovat oikeutesi, kun käytät dizi.jpg-sovellusta ja dizijpg.com-sivustoa.',
  'Topladığımız Veriler': 'Keräämämme tiedot',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Tili: sähköpostiosoite, käyttäjänimi ja salasana. Salasanat tallennetaan peruuttamattomana tiivisteenä; vierastilejä voi käyttää ilman sähköpostia.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profiili: tiedot, jotka itse päätät lisätä, kuten avatar, kansikuva, bio ja maa.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Käyttö: katseluhistoriasi, arviosi, kommenttisi, listasi, reaktiosi ja suosikkisi.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Viestit: teksti-, kuva- ja ääniviestisi tallennetaan palvelimillemme. Viestejä ei ole salattu päästä päähän; niitä tarkastellaan vain moderointia varten, jos niistä tehdään ilmoitus.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Ladattu media: valokuvat, GIFit, videot ja ääninauhoitteet, joita lisäät profiiliisi, kommentteihisi ja viesteihisi.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Tekniset: IP-osoite, likimääräinen sijainti (maa-/kaupunkitasolla), laitealusta, sovellusversio ja virhelokit. Näitä säilytetään turvallisuutta ja vianetsintää varten.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Ilmoitukset: push-ilmoituksia varten tallennamme laitteesi tokenin ja kielivalintasi. Voit poistaa ilmoitukset käytöstä milloin tahansa laitteen asetuksista.',
  'Verileri Nasıl Kullanırız': 'Miten käytämme tietojasi',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Käytämme tietojasi vain palvelun tarjoamiseen, tilisi suojaamiseen, ilmoitusten lähettämiseen, virheiden korjaamiseen ja väärinkäytön estämiseen. Emme myy tietojasi emmekä jaa niitä kenellekään mainostarkoituksiin.',
  'Çerezler ve Yerel Depolama': 'Evästeet ja paikallinen tallennustila',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Käytämme paikallista tallennustilaa vain pitääksemme sinut kirjautuneena ja muistaaksemme asetukset, kuten kielen ja teeman. Mainos- tai seurantaevästeitä ei ole.',
  'Üçüncü Taraf Hizmetler': 'Kolmansien osapuolten palvelut',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'Sarja- ja elokuvatiedot tulevat TMDB:stä, suoratoistoalustojen tiedot JustWatchista. Push-ilmoitukset toimitetaan Google Firebasen kautta, ja sivuston liikennettä suojaa Cloudflare. Näihin palveluihin sovelletaan niiden omia tietosuojakäytäntöjä.',
  'Saklama ve Silme': 'Säilytys ja poistaminen',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Tietosi säilytetään niin kauan kuin tilisi on olemassa. Asetusten "Poista tilini" -toiminnolla voit poistaa tilisi pysyvästi; tietosi poistetaan heti ja varmuuskopioissa olevat kopiot viimeistään 14 päivässä. Virhelokit poistuvat automaattisesti 30 päivän kuluttua.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'Voit viedä tietosi ZIP-muodossa asetuksista; arkisto lähetetään sähköpostiosoitteeseesi.',
  'Güvenlik': 'Turvallisuus',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Tiedot siirretään salattujen yhteyksien (HTTPS) kautta ja tallennetaan palvelimille, joihin on rajoitettu pääsy.',
  'Çocukların Gizliliği': 'Lasten yksityisyys',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg ei ole tarkoitettu alle 13-vuotiaille lapsille.',
  'Hakların': 'Oikeutesi',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK:n ja GDPR:n nojalla sinulla on oikeus päästä tietoihisi sekä korjata, poistaa ja siirtää niitä. Kirjoita meille näistä asioista: {}',
  'Değişiklikler': 'Muutokset',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Jos tämä käytäntö muuttuu, uusi versio julkaistaan tällä sivulla ja päivämäärä päivitetään.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Rekisteröitymällä hyväksyt: {}.',
  'Kullanıcılar': 'Käyttäjät',
  'Fotoğrafı değiştir': 'Vaihda kuva',
  'Yeniden konumlandır': 'Rajaa uudelleen',
  'Bir şeyler ters gitti': 'Jokin meni pieleen',
  'Sosyal Bağlantılar': 'Somelinkit',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Profiilissasi näytetään enintään 3 linkkiä.',
  'Platform seç': 'Valitse alusta',
  'Kullanıcı adın': 'Käyttäjänimesi',
  'Ekle': 'Lisää',
  'Kaldır': 'Poista',
  'Kopyalandı: {}': 'Kopioitu: {}',
  'Geçersiz kullanıcı adı': 'Virheellinen käyttäjänimi',
  'Bağlantı ekle': 'Lisää linkki',
  'Spoiler olabilir — dokun ve gör':
      'Voi sisältää juonipaljastuksia — napauta nähdäksesi',
  'Beğeni': 'Tykkäykset',
  'Beğen': 'Tykkää',
  'Görüntülenme': 'Katselukerrat',
  'Tam ekran': 'Koko näyttö',
  'Arama başarısız': 'Haku epäonnistui',
  'Sonuç bulunamadı': 'Ei tuloksia',
  'Dizi ve Filmler': 'Sarjat ja elokuvat',
  'Kişiler': 'Henkilöt',
  'Ana Sayfa': 'Etusivu',
  'Paylaş': 'Jaa',
  'Yanıtlar': 'Vastaukset',
  'Yaklaşan Bölümler': 'Tulevat jaksot',
  'Yetişme Listesi': 'Kiinniottolista',
  'Şunu mu demek istedin': 'Tarkoititko',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — napauta näyttääksesi',
  'uyum': 'yhteensopivuus',
  'Uyum': 'Yhteensopivuus',
  '{} ortak dizi': '{} yhteistä sarjaa',
  '{} ortak film': '{} yhteistä elokuvaa',
  'Bildirim Tercihleri': 'Ilmoitusasetukset',
  'Beğeniler': 'Tykkäykset',
  'Yeni takipçiler': 'Uudet seuraajat',
  'Etiketlenmeler': 'Maininnat',
  'Yeniden izledim': 'Katsottu uudelleen',
  '{}. kez izlendi': 'Katsottu {} kertaa',
  'Gönderi bulunamadı': 'Julkaisua ei löytynyt',
  'Gözat': 'Selaa',
  'Diziler': 'Sarjat',
  'Filmler': 'Elokuvat',
  'Tümü': 'Kaikki',
  'Farklı bir tür seç.': 'Kokeile toista lajityyppiä.',
  'Gizlilik': 'Yksityisyys',
  'İzlediklerimi gizle': 'Piilota katsomani',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Katsomasi sarjat ja elokuvat eivät näy profiilissasi',
  'Yorumlarımı gizle': 'Piilota kommenttini',
  'Profilinde yorumların görünmez': 'Kommenttisi eivät näy profiilissasi',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Voit piilottaa yksittäisen sarjan tai elokuvan sen sivulla olevalla "Piilota profiilistani" -sirulla.',
  'Geri Bildirim': 'Palaute',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Kirjoita mielipiteesi ja ehdotuksesi sovelluksesta...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Kiitos! Palautteesi on vastaanotettu.',
  'Profilimde gizle': 'Piilota profiilistani',
  'Yorumları': 'Kommentit',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Tämä käyttäjä ei ole katsonut vielä mitään.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Tämä käyttäjä haluaa pitää kommenttinsa yksityisinä.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Tiedot: JustWatch',
  'Web Sitesi': 'Verkkosivusto',
  'Diğer uygulamalar': 'Muut sovellukset',
  'Bağlantıyı kopyala': 'Kopioi linkki',
  'Henüz kimseyi takip etmiyorsun.': 'Et seuraa vielä ketään.',
  'Çevir': 'Käännä',
  'Çeviri şu an yapılamadı': 'Käännös ei ole nyt mahdollinen',
  'Bağlantı açılamadı': 'Linkkiä ei voitu avata',
  'Orijinali göster': 'Näytä alkuperäinen',
  'Çeviriyi göster': 'Näytä käännös',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Tässä kuussa ei ole jaksoja, joiden esityspäivä olisi julkistettu. Päivät ilmoitetaan yleensä paria viikkoa aiemmin ja näkyvät sitten täällä.',
  'devamı': 'lisää',
  'Google ile devam et': 'Jatka Google-tilillä',
  'Google girişi başarısız': 'Google-kirjautuminen epäonnistui',
  'Veri tasarrufu': 'Datansäästö',
  'Wi-Fi ağında veri tasarrufu': 'Datansäästö Wi-Fi-verkossa',
  'Mobil veride veri tasarrufu': 'Datansäästö mobiilidatalla',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Kun tämä on päällä, kuvia ei ladata etukäteen, vain se kuva jota katsot.',
  'Çocuk güvenliği': 'Lasten turvallisuus',
  'Türk Filmleri': 'Turkkilaiset elokuvat',
  'En Yüksek Puanlı Filmler': 'Parhaiten arvioidut elokuvat',
  'En Yüksek Puanlı Diziler': 'Parhaiten arvioidut sarjat',
  'En Çok İzlenen Filmler': 'Katsotuimmat elokuvat',
  'Popüler Diziler': 'Suositut sarjat',
  'En Çok Kazanan Filmler': 'Tuottoisimmat elokuvat',
  'Kült Filmler': 'Kulttielokuvat',
  'Yeni Filmler': 'Uudet elokuvat',
  'Yorum yap': 'Kommentoi',
  'Henüz yorum yok': 'Ei vielä kommentteja',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Sarjoista ja elokuvista kirjoittamasi kommentit kootaan tänne.',
  'GIF ekle': 'Lisää GIF',
  'İlk yorumu sen yaz': 'Kirjoita ensimmäinen kommentti',
  'Video altyazıları': 'Videon tekstitykset',
  'Videolarda altyazı göster': 'Näytä tekstitykset videoissa',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Videolla puhuttu lause kirjoitetaan näytölle. Teksti on käännetty: Englanti turkin puheessa, turkki muilla kielillä.',
  "Güncelleme gerekli": "Päivitys vaaditaan",
  "Yeni sürüm var": "Uusi versio saatavilla",
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      "Asenna dizi.jpg:n uusi versio jatkaaksesi.",
  "Güncelle": "Päivitä",
  "Daha sonra": "Myöhemmin",
  'Takvim güncelleniyor': 'Kalenteria päivitetään',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Kalenteria ei voitu päivittää, näytetään vanha lista',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Joitakin sarjoja ei voitu ladata, lista voi olla puutteellinen',
  'Yenile': 'Päivitä',
  'Devam etmek için giriş yap': 'Kirjaudu sisään jatkaaksesi',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Ilmainen tili riittää arviointiin, kommentointiin ja oman kirjaston rakentamiseen.',
  'Şimdi değil': 'Ei nyt',
  'Yorum yazmak için giriş yap': 'Kirjaudu sisään kirjoittaaksesi kommentin',
  'Kişilere göndermek için giriş yap':
      'Kirjaudu sisään lähettääksesi ihmisille',
  'Beğenenler': 'Tykkaykset',
  'Henüz beğeni yok': 'Ei viela tykkayksia',
  'Bu gönderiyi ilk beğenen sen ol': 'Ole ensimmainen tykkaaja',
  'Bu gönderiye yanıt': 'Vastaus tahan julkaisuun',
  'Spoiler içeren gönderi': 'Viesti, jossa on spoilereita',
  'Görsel gönderi': 'Kuvaviesti',
  'Bu yorumu profilimde gizle': 'Piilota tämä kommentti profiilissani',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Kommentti pysyy sarjan ja elokuvan sivulla',
  'Bu yorumu sil': 'Poista tämä kommentti',
  'Yorum profilinde gizlendi': 'Kommentti piilotettu profiilissasi',
  'Geri al': 'Kumoa',
  'Yorum silinsin mi?': 'Poistetaanko kommentti?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Tämä kommentti poistetaan pysyvästi kaikkialta. Toimintoa ei voi kumota.',
  'Yorum silindi': 'Kommentti poistettu',
  'Yorum profilinde tekrar görünüyor': 'Kommentti näkyy taas profiilissasi',
  'Gizlenen yorumun yok': 'Ei piilotettuja kommentteja',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Kommentit, jotka piilotat pitämällä sormea viestin päällä profiilisi Kommentit-välilehdellä, kertyvät tänne.',
  'Gizlenen yorumlar': 'Piilotetut kommentit',
  'Gönderiye git': 'Siirry viestiin',
  'Tekrar göster': 'Näytä uudelleen',
  'Yanıtlarımı gizle': 'Piilota vastaukseni',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Vastaukset, joita kirjoitat muiden viesteihin, näkyvät vain sinulle',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Näytä taas profiilissasi piilottamasi kommentit',
  'Sıralama': 'Järjestys',
  'Önerilen': 'Suositellut',
  'Kronolojik': 'Aikajärjestys',
  'Dizi jpg aile üyesi': 'Dizi jpg -perheenjäsen',
};
