/// Otomatik üretilen çeviri haritası (sw).
const Map<String, String> cevirilerSw = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Umeona yote, tunakuonyesha tangu mwanzo',
  'Aktarılacak tanınan veri bulunamadı.':
      'Hakuna data inayotambulika ya kuhamisha.',
  'Arama': 'Tafuta',
  'Aramaya başla': 'Anza kutafuta',
  'Son aramalar': 'Utafutaji wa hivi karibuni',
  'Ayarlar': 'Mipangilio',
  'Bağla': 'Unganisha',
  'Bio': 'Bio',
  'Bitirdim': 'Nimemaliza',
  'Bunları da Beğenebilirsin': 'Huenda Ukapenda Hizi Pia',
  'Bölüm': 'Kipindi',
  'Bıraktım': 'Nimeacha',
  'Dil': 'Lugha',
  'Dil ara...': 'Tafuta lugha...',
  'Dizi': 'Mfululizo',
  'Dizi ve filmlerini takip et': 'Fuatilia mifululizo na filamu zako',
  'Dizi yorumu': 'Maoni ya mfululizo',
  'Dizi, film veya kişi ara...': 'Tafuta mfululizo, filamu au mtu...',
  'Dosya en fazla 30MB olabilir': 'Faili isizidi 30MB',
  'Dosya en fazla {}MB olabilir': 'Faili isizidi {}MB',
  'E-posta': 'Barua pepe',
  'E-posta veya kullanıcı adı': 'Barua pepe au jina la mtumiaji',
  'En az 2 harf yaz': 'Andika angalau herufi 2',
  'Film': 'Filamu',
  'Film yorumu': 'Maoni ya filamu',
  'Fotoğraf / video ekle': 'Ongeza picha / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Picha au GIF — picha ya wasifu na jalada',
  'Giriş Yap': 'Ingia',
  'Gönder': 'Tuma',
  'Gönderildi': 'Imetumwa',
  'Haftanın Dizileri': 'Mifululizo ya Wiki Hii',
  'Haftanın Filmleri': 'Filamu za Wiki Hii',
  'Henüz izleme kaydın yok': 'Bado huna historia ya kutazama',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Bado huna orodha — tengeneza kwenye kichupo cha Wasifu.',
  'Henüz yorum yok.': 'Hakuna maoni bado.',
  'Hesabın bağlandı!': 'Akaunti yako imeunganishwa!',
  'Hesabın yok mu? Kayıt ol': 'Huna akaunti? Jisajili',
  'Hesabını Bağla': 'Unganisha Akaunti Yako',
  'Hesap Oluştur': 'Fungua Akaunti',
  'Kapak resmi ekle': 'Ongeza picha ya jalada',
  'Kaydet': 'Hifadhi',
  'Kendinden bahset...': 'Jieleze kidogo...',
  'Keşfet': 'Gundua',
  'Kimseyi takip etmiyor': 'Hafuati mtu yeyote',
  'Kişi ara': 'Tafuta mtu',
  'Kişi yorumu': 'Maoni ya mtu',
  'Konuk Oyuncular': 'Waigizaji Wageni',
  'Kullanıcı adı (küçük harf)': 'Jina la mtumiaji (herufi ndogo)',
  'Kullanıcı adı ara...': 'Tafuta jina la mtumiaji...',
  'Liste adı': 'Jina la orodha',
  'Listeye Ekle': 'Ongeza kwenye Orodha',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Uko kwenye akaunti ya mgeni — unganisha na barua pepe yako, usipoteze data zako!',
  'Misafir olarak devam et': 'Endelea kama mgeni',
  'Oluştur': 'Tengeneza',
  'Oyuncular': 'Waigizaji',
  'Profil': 'Wasifu',
  'Profil kaydedildi': 'Wasifu umehifadhiwa',
  'Puanla': 'Kadiria',
  'Puanı Sil': 'Futa Alama',
  'Puanın': 'Alama Yako',
  'Sezonlar': 'Misimu',
  'Sunucu hatası ({})': 'Hitilafu ya seva ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Maoni ya S{}E{}',
  'Takibi Bırak': 'Acha Kufuata',
  'Takip': 'Anafuata',
  'Takip Edilenler': 'Wanaofuatwa',
  'Takip Et': 'Fuata',
  'Takipçi': 'Mfuasi',
  'Takipçi yok': 'Hakuna wafuasi',
  'Takipçiler': 'Wafuasi',
  'Takvim': 'Kalenda',
  'Tamam': 'Sawa',
  'Tekrar Dene': 'Jaribu Tena',
  'Tekrar dene': 'Jaribu tena',
  'Toplam İzleme Süresi': 'Jumla ya muda wa kutazama',
  'Tüm Zamanların En İyileri': 'Bora Zaidi za Wakati Wote',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Pakua data zako zote (kutazama, alama, maoni, orodha) kama ZIP inayooana na TV Time, au leta ZIP kutoka programu nyingine.',
  'Tümünü Kaldır': 'Ondoa Zote',
  'Tümünü İzledim': 'Nimetazama Zote',
  'Türk Dizileri': 'Mifululizo ya Kituruki',
  'Veri içe aktar (.zip)': 'Leta data (.zip)',
  'Verilerim': 'Data Zangu',
  'Verilerimi dışa aktar (e-posta)': 'Hamisha data zangu (barua pepe)',
  'Verilerini dışa aktar': 'Hamisha data zako',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Hakuna kipindi kijacho.\nWeka mfululizo kwenye hali ya "Ninatazama" kutoka ukurasa wake wa maelezo, kisha fuatilia vipindi vipya hapa.',
  'Yapımları': 'Kazi Zake',
  'Yeni Diziler': 'Mifululizo Mipya',
  'Yeni Liste': 'Orodha Mpya',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Jina jipya la mtumiaji (hiari)',
  'Yorum': 'Maoni',
  'Yorumunu yaz...': 'Andika maoni yako...',
  'Zaten hesabın var mı? Giriş yap': 'Tayari una akaunti? Ingia',
  'ort. {}': 'wastani {}',
  'takip': 'anafuata',
  'takipçi': 'wafuasi',
  '{} / {} bölüm': 'vipindi {} / {}',
  '{} TMDB': '{} TMDB',
  '{} ay': 'miezi {}',
  '{} bölüm izlendi': 'vipindi {} vimetazamwa',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': 'dakika {}',
  '{} gün': 'siku {}',
  '{} içerik': 'maudhui {}',
  '{} içerik · otomatik': 'maudhui {} · kiotomatiki',
  '{} kayıt atlandı (eşleşmedi).': 'Rekodi {} zimerukwa (hazikulingana).',
  '{} saat': 'saa {}',
  '{} sezon': 'misimu {}',
  '{} yıl': 'miaka {}',
  '{}. Bölüm': 'Kipindi cha {}',
  '{}. Sezon': 'Msimu wa {}',
  'Çıkış Yap': 'Toka',
  'Ülke': 'Nchi',
  'Ülke ara...': 'Tafuta nchi...',
  'Ülke seç': 'Chagua nchi',
  'İlk yorumu sen yaz!': 'Kuwa wa kwanza kutoa maoni!',
  'İncelemeler': 'Mapitio',
  'İncelemen (isteğe bağlı)': 'Mapitio yako (hiari)',
  'İptal': 'Ghairi',
  'İzlediklerim': 'Nilizotazama',
  'İzledim': 'Nimetazama',
  'İzledin': 'Umetazama',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Historia yako ya kutazama na orodha zako zitabaki salama; sasa unaweza kuingia kutoka kifaa chochote.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Historia yako ya kutazama, alama, maoni na orodha zako zitatumwa kama ZIP kwenye barua pepe yako iliyosajiliwa.',
  'İzleyeceğim': 'Nitatazama',
  'İzliyorum': 'Ninatazama',
  'İçe aktarım tamamlandı': 'Uhamishaji umekamilika',
  'Şifre': 'Nenosiri',
  '• profil bilgisi': '• taarifa za wasifu',
  '• {} dizi durumu': '• hali za mifululizo {}',
  '• {} izleme kaydı': '• rekodi za kutazama {}',
  '• {} liste': '• orodha {}',
  '• {} puan': '• alama {}',
  '• {} yorum': '• maoni {}',
  '{}+ yapım': 'Kazi {}+',
  'Yorumlar': 'Maoni',
  'Yorumlar ({})': 'Maoni ({})',
  'Yorumları ({})': 'Maoni yake ({})',
  'Listelerim': 'Orodha Zangu',
  'Nereden izledin?': 'Ulitazama wapi?',
  'Diziye git': 'Nenda kwenye kipindi',
  'TV / Kanal': 'TV / Kituo',
  'Sinema': 'Sinema',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Nyingine',
  'Akış': 'Mlisho',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Mlisho wako ni tupu.\nWatu wakitoa maoni kwenye vipindi na filamu unazotazama, yataonekana hapa.',
  'Listeleri ({})': 'Orodha zake ({})',
  'Liste boş.': 'Orodha hii ni tupu.',
  'Yanıtla': 'Jibu',
  '@{} kullanıcısına yanıt veriyorsun': 'Unamjibu @{}',
  'İzlediğim Diziler ({})': 'Vipindi nilivyotazama ({})',
  'İzlediğim Filmler ({})': 'Filamu nilizotazama ({})',
  'Tümünü gör': 'Ona zote',
  'Bildirimler': 'Arifa',
  'Henüz bildirim yok': 'Hakuna arifa bado',
  '@{} yorumuna yanıt verdi': '@{} alijibu maoni yako',
  '@{} yorumunu beğendi': '@{} alipenda maoni yako',
  '@{} seni takip etti': '@{} alikufuata',
  '@{} sana mesaj gönderdi': '@{} alikutumia ujumbe',
  'Mesajlar': 'Jumbe',
  'Mesaj': 'Ujumbe',
  'Mesajını yaz...': 'Andika ujumbe...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Hakuna gumzo bado.\nFungua wasifu utume ujumbe.',
  'Şifreni mi unuttun?': 'Umesahau nenosiri?',
  'Şifreyi Sıfırla': 'Weka upya nenosiri',
  'E-postadaki kod': 'Msimbo kutoka barua pepe',
  'Yeni şifre': 'Nenosiri jipya',
  'Sana Özel': 'Kwa ajili yako',
  '{} özetin': 'Muhtasari wako wa {}',
  'Yıllık izleme istatistiklerin': 'Takwimu zako za mwaka',
  'Rozetler': 'Beji',
  'Verdiğin puan': 'Ukadiriaji uliotoa',
  'Ortalama puanın': 'Wastani wa ukadiriaji',
  'En çok izlediğin diziler': 'Vipindi ulivyotazama zaidi',
  'İlk Bölüm': 'Kipindi cha Kwanza',
  '100 Bölüm': 'Vipindi 100',
  '1000 Bölüm': 'Vipindi 1000',
  'İlk Film': 'Filamu ya Kwanza',
  '50 Film': 'Filamu 50',
  'İlk Yorum': 'Maoni ya Kwanza',
  '25 Yorum': 'Maoni 25',
  '10 Puan': 'Ukadiriaji 10',
  'İlk Takipçi': 'Mfuasi wa Kwanza',
  '10 Dizi Bitirdin': 'Umemaliza Vipindi 10',
  'İzlemeyi Bıraktım': 'Nimeacha kutazama',
  'İzlediği Diziler ({})': 'Vipindi alivyotazama ({})',
  'İzlediği Filmler ({})': 'Filamu alizotazama ({})',
  '500 Bölüm': 'Vipindi 500',
  '5000 Bölüm': 'Vipindi 5000',
  '10 Film': 'Filamu 10',
  '100 Film': 'Filamu 100',
  '100 Yorum': 'Maoni 100',
  '50 Puan': 'Ukadiriaji 50',
  '100 Puan': 'Ukadiriaji 100',
  '10 Takipçi': 'Wafuasi 10',
  '50 Takipçi': 'Wafuasi 50',
  '25 Dizi Bitirdin': 'Amemaliza vipindi 25',
  '50 Dizi Bitirdin': 'Amemaliza vipindi 50',
  '10 Beğeni': 'Vipendwa 10',
  '100 Beğeni': 'Vipendwa 100',
  'yazıyor...': 'anaandika...',
  'Profil düzeni': 'Mpangilio wa wasifu',
  'Konumla ve kırp': 'Weka mahali na ukate',
  'Listeye eklendi': 'Imeongezwa kwenye orodha',
  'Listeyi sil?': 'Ufute orodha?',
  'Sil': 'Futa',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Kichwa hiki kitawekwa kama hakijatazamwa na kuondolewa kwenye orodha zako.',
  'Gelecek bölüm bugün': 'Kipindi kijacho leo',
  'Gelecek bölüm {} gün sonra': 'Kipindi kijacho baada ya siku {}',
  'Tema': 'Mandhari',
  'Sistem': 'Mfumo',
  'Koyu': 'Giza',
  'Açık': 'Mwanga',
  'İzleyenler': 'Watazamaji',
  'Yorumunu yaz... (@ ile etiketle)': 'Andika maoni yako... (@ kutambulisha)',
  '@{} bir yorumda seni etiketledi': '@{} amekutambulisha kwenye maoni',
  'Mesajı sil': 'Futa ujumbe',
  'Mesaj silinemedi': 'Ujumbe haukuweza kufutwa',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Kiungo si sahihi au ukurasa haukupatikana',
  'Keşfet\'e dön': 'Rudi kwenye Gundua',
  'Düzenle': 'Hariri',
  'Mesajı düzenle': 'Hariri ujumbe',
  'Yanıtlanıyor': 'Anajibu',
  'düzenlendi': 'imehaririwa',
  'Fotoğraf': 'Picha',
  'Video': 'Video',
  'İçerik': 'Maudhui',
  'çevrimiçi': 'mtandaoni',
  'son görülme {} dk önce': 'alionekana dakika {} zilizopita',
  'son görülme {} saat önce': 'alionekana saa {} zilizopita',
  'son görülme {} gün önce': 'alionekana siku {} zilizopita',
  'Yorumlar yüklenemedi': 'Imeshindwa kupakia maoni',
  'Favori': 'Kipendwa',
  'Listeye ekle': 'Ongeza kwenye orodha',
  'İçerik paylaş': 'Shiriki maudhui',
  'Kapat': 'Funga',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Kila unachokiweka kama kimetazamwa hukusanywa hapa.',
  'Henüz sohbetin yok': 'Bado hakuna mazungumzo',
  'Bir profile girip mesaj gönderebilirsin.': 'Fungua wasifu na tuma ujumbe.',
  'Listeyi sil': 'Futa orodha',
  'Puan kaydedilemedi': 'Ukadiriaji haukuweza kuhifadhiwa',
  'Nerede İzlenir': 'Wapi Kutazama',
  'Abonelik': 'Kujiunga',
  'Kirala': 'Kodisha',
  'Satın al': 'Nunua',
  'Hoş geldin!': 'Karibu!',
  'İzlemek istediğin dizi ve filmleri seç':
      'Chagua vipindi na filamu unazotaka kutazama',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Chaguo lako litaongezwa kwenye orodha yako',
  'Şimdilik atla': 'Ruka kwa sasa',
  'Devam et': 'Endelea',
  '{} ekle': 'Ongeza {}',
  'Şikayet et': 'Ripoti',
  'Engelle': 'Zuia',
  'Engeli kaldır': 'Ondoa uzuiaji',
  'Kullanıcı engellendi': 'Mtumiaji amezuiwa',
  'Engel kaldırıldı': 'Uzuiaji umeondolewa',
  'Şikayet sebebi': 'Sababu ya ripoti',
  'Spam veya yanıltıcı': 'Barua taka au kupotosha',
  'Taciz veya nefret söylemi': 'Unyanyasaji au matamshi ya chuki',
  'Uygunsuz / cinsel içerik': 'Isiyofaa / maudhui ya ngono',
  'Şiddet veya tehlikeli içerik': 'Vurugu au maudhui hatari',
  'Telif hakkı ihlali': 'Ukiukaji wa hakimiliki',
  'Şikayetin alındı, teşekkürler': 'Ripoti yako imepokelewa, asante',
  'Hesabımı Sil': 'Futa Akaunti Yangu',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Akaunti yako na data yako yote (historia, ukadiriaji, maoni, orodha, ujumbe) itafutwa kabisa. Hii haiwezi kutenduliwa.',
  'Şifreni gir': 'Weka nywila yako',
  'Hesabımı kalıcı sil': 'Futa akaunti yangu kabisa',
  'Sesli mesaj': 'Ujumbe wa sauti',
  'Ses gönderilemedi': 'Ujumbe wa sauti haukutumwa',
  'Kaydediliyor…': 'Inarekodi…',
  'Ses oynatılamadı': 'Sauti haikuweza kuchezwa',
  'Oynat': 'Cheza',
  'Duraklat': 'Sitisha',
  'Liste görünümü': 'Mwonekano wa orodha',
  'Takvim görünümü': 'Mwonekano wa kalenda',
  'Önceki ay': 'Mwezi uliopita',
  'Sonraki ay': 'Mwezi ujao',
  'Bu gün bölüm yok': 'Hakuna vipindi siku hii',
  'Gizlilik Politikası': 'Sera ya Faragha',
  'Son güncelleme: {}': 'Sasisho la mwisho: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Sera hii inaeleza data gani hukusanywa, jinsi inavyotumika na haki zako ni zipi unapotumia programu ya dizi.jpg na tovuti ya dizijpg.com.',
  'Topladığımız Veriler': 'Data Tunayokusanya',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Akaunti: anwani ya barua pepe, jina la mtumiaji na nenosiri. Manenosiri huhifadhiwa kama heshi isiyoweza kurejeshwa; akaunti za mgeni zinaweza kutumika bila barua pepe.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Wasifu: taarifa unazochagua kuongeza, kama avatari, picha ya jalada, wasifu mfupi na nchi.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Matumizi: historia yako ya kutazama, ukadiriaji, maoni, orodha, riaksheni na vipendwa.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Ujumbe: ujumbe wako wa maandishi, picha na sauti huhifadhiwa kwenye seva zetu. Ujumbe haujasimbwa kutoka mwanzo hadi mwisho; hukaguliwa tu kwa madhumuni ya usimamizi endapo utaripotiwa.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Media zilizopakiwa: picha, GIF, video na rekodi za sauti unazoongeza kwenye wasifu, maoni na ujumbe wako.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Kiufundi: anwani ya IP, mahali pa makadirio (kiwango cha nchi/jiji), jukwaa la kifaa, toleo la programu na kumbukumbu za hitilafu. Hizi huhifadhiwa kwa usalama na kurekebisha matatizo.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Arifa: kwa arifa za papo hapo tunahifadhi tokeni ya kifaa chako na lugha uliyochagua. Unaweza kuzima arifa wakati wowote kwenye mipangilio ya kifaa.',
  'Verileri Nasıl Kullanırız': 'Jinsi Tunavyotumia Data Yako',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Tunatumia data yako tu kutoa huduma, kulinda akaunti yako, kutuma arifa, kurekebisha hitilafu na kuzuia matumizi mabaya. Hatuuzi data yako wala kuishiriki na yeyote kwa madhumuni ya matangazo.',
  'Çerezler ve Yerel Depolama': 'Vidakuzi na Hifadhi ya Ndani',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Tunatumia hifadhi ya ndani tu kukuweka umeingia na kukumbuka mapendeleo kama lugha na mandhari. Hakuna vidakuzi vya matangazo wala vya ufuatiliaji.',
  'Üçüncü Taraf Hizmetler': 'Huduma za Wahusika Wengine',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'Data ya vipindi na filamu hutoka TMDB, taarifa za majukwaa ya kutiririsha kutoka JustWatch. Arifa za papo hapo huwasilishwa kupitia Google Firebase, na trafiki ya tovuti hulindwa na Cloudflare. Huduma hizi zinafuata sera zao za faragha.',
  'Saklama ve Silme': 'Uhifadhi na Ufutaji',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Data yako huhifadhiwa muda wote akaunti yako ipo. Kupitia "Futa Akaunti Yangu" kwenye mipangilio unaweza kufuta akaunti kabisa; data yako hufutwa mara moja, na nakala kwenye hifadhi rudufu ndani ya siku 14 zaidi. Kumbukumbu za hitilafu hufutwa kiotomatiki baada ya siku 30.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'Unaweza kuhamisha data yako kama ZIP kutoka kwenye mipangilio; jalada hutumwa kwa anwani yako ya barua pepe.',
  'Güvenlik': 'Usalama',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Data husafirishwa kupitia miunganisho iliyosimbwa (HTTPS) na kuhifadhiwa kwenye seva zenye ufikiaji mdogo.',
  'Çocukların Gizliliği': 'Faragha ya Watoto',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg haikusudiwi watoto walio chini ya miaka 13.',
  'Hakların': 'Haki Zako',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Chini ya KVKK na GDPR una haki ya kufikia, kusahihisha, kufuta na kuhamisha data yako. Kwa haya tuandikie: {}',
  'Değişiklikler': 'Mabadiliko',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Sera hii ikibadilika, toleo jipya litachapishwa kwenye ukurasa huu na tarehe itasasishwa.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Kwa kujisajili unakubali {}.',
  'Kullanıcılar': 'Watumiaji',
  'Fotoğrafı değiştir': 'Badilisha picha',
  'Yeniden konumlandır': 'Panga upya',
  'Bir şeyler ters gitti': 'Hitilafu imetokea',
  'Sosyal Bağlantılar': 'Viungo vya Mitandao',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Viungo 3 pekee huonyeshwa kwenye wasifu wako.',
  'Platform seç': 'Chagua jukwaa',
  'Kullanıcı adın': 'Jina lako la mtumiaji',
  'Ekle': 'Ongeza',
  'Kaldır': 'Ondoa',
  'Kopyalandı: {}': 'Imenakiliwa: {}',
  'Geçersiz kullanıcı adı': 'Jina la mtumiaji si sahihi',
  'Bağlantı ekle': 'Ongeza kiungo',
  'Spoiler olabilir — dokun ve gör': 'Inaweza kuwa na spoiler — gusa kuona',
  'Beğeni': 'Zilizopendwa',
  'Görüntülenme': 'Mionekano',
  'Tam ekran': 'Skrini nzima',
  'Sonuç bulunamadı': 'Hakuna matokeo',
  'Dizi ve Filmler': 'Tamthilia na Filamu',
  'Kişiler': 'Watu',
  'Ana Sayfa': 'Mwanzo',
  'Paylaş': 'Shiriki',
  'Yanıtlar': 'Majibu',
  'Yaklaşan Bölümler': 'Vipindi Vijavyo',
  'Yetişme Listesi': 'Orodha ya Kufikia',
  'Şunu mu demek istedin': 'Ulimaanisha',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — gusa ili uone',
  'uyum': 'ulinganifu',
  'Uyum': 'Ulinganifu',
  '{} ortak dizi': 'vipindi {} sawa',
  '{} ortak film': 'filamu {} sawa',
  'Bildirim Tercihleri': 'Mapendeleo ya arifa',
  'Beğeniler': 'Mapendo',
  'Yeni takipçiler': 'Wafuasi wapya',
  'Etiketlenmeler': 'Kutajwa',
  'Yeniden izledim': 'Imetazamwa tena',
  '{}. kez izlendi': 'Imetazamwa mara {}',
  'Gönderi bulunamadı': 'Chapisho halikupatikana',
  'Gözat': 'Vinjari',
  'Diziler': 'Vipindi',
  'Filmler': 'Filamu',
  'Tümü': 'Zote',
  'Farklı bir tür seç.': 'Jaribu aina nyingine.',
  'Gizlilik': 'Faragha',
  'İzlediklerimi gizle': 'Ficha nilichotazama',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Series na filamu ulizotazama hazitaonekana kwenye wasifu wako',
  'Yorumlarımı gizle': 'Ficha maoni yangu',
  'Profilinde yorumların görünmez':
      'Maoni yako hayataonekana kwenye wasifu wako',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Unaweza kuficha series au filamu moja kwa kutumia kibonye "Ficha kwenye wasifu wangu" kwenye ukurasa wake.',
  'Geri Bildirim': 'Mrejesho',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Andika maoni na mapendekezo yako kuhusu programu...',
  'Teşekkürler! Geri bildirimin alındı.': 'Asante! Mrejesho wako umepokelewa.',
  'Profilimde gizle': 'Ficha kwenye wasifu wangu',
  'Yorumları': 'Maoni yake',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Mtumiaji huyu bado hajatazama chochote.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Mtumiaji huyu anapendelea kuficha maoni yake.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Data: JustWatch',
  'Web Sitesi': 'Tovuti',
  'Diğer uygulamalar': 'Programu nyingine',
  'Bağlantıyı kopyala': 'Nakili kiungo',
  'Henüz kimseyi takip etmiyorsun.': 'Bado hujamfuata mtu yeyote.',
  'Çevir': 'Tafsiri',
  'Çeviri şu an yapılamadı': 'Tafsiri haipatikani kwa sasa',
  'Bağlantı açılamadı': 'Kiungo hakikuweza kufunguliwa',
  'Orijinali göster': 'Onyesha asili',
  'Çeviriyi göster': 'Onyesha tafsiri',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Mwezi huu hakuna vipindi vyenye tarehe ya kurushwa iliyotangazwa. Tarehe hutangazwa wiki chache kabla na zitaonekana hapa.',
  'devamı': 'zaidi',
  'Google ile devam et': 'Endelea na Google',
  'Google girişi başarısız': 'Kuingia kwa Google hakukufaulu',
  'Veri tasarrufu': 'Kuokoa data',
  'Wi-Fi ağında veri tasarrufu': 'Kuokoa data kwenye Wi-Fi',
  'Mobil veride veri tasarrufu': 'Kuokoa data kwenye data ya simu',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Ikiwashwa, picha hazipakuliwi mapema; inapakia tu picha unayoitazama.',
  'Çocuk güvenliği': 'Usalama wa watoto',
  'Türk Filmleri': 'Filamu za Kituruki',
  'En Yüksek Puanlı Filmler': 'Filamu zenye ukadiriaji wa juu',
  'En Yüksek Puanlı Diziler': 'Misururu yenye ukadiriaji wa juu',
  'En Çok İzlenen Filmler': 'Filamu zilizotazamwa zaidi',
  'Popüler Diziler': 'Misururu maarufu',
  'En Çok Kazanan Filmler': 'Filamu zilizoingiza mapato zaidi',
  'Kült Filmler': 'Filamu za kipekee',
  'Yeni Filmler': 'Filamu mpya',
  'Yorum yap': 'Toa maoni',
  'Henüz yorum yok': 'Bado hakuna maoni',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Maoni unayoandika kuhusu misururu na filamu hukusanywa hapa.',
};
