/// Otomatik üretilen çeviri haritası (pt).
const Map<String, String> cevirilerPt = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Você já viu de tudo, nós mostramos desde o início',
  'Aktarılacak tanınan veri bulunamadı.':
      'Nenhum dado reconhecido para importar.',
  'Arama': 'Busca',
  'Aramaya başla': 'Comece a buscar',
  'Son aramalar': 'Pesquisas recentes',
  'Ayarlar': 'Configurações',
  'Bağla': 'Vincular',
  'Bio': 'Bio',
  'Bitirdim': 'Terminei',
  'Bunları da Beğenebilirsin': 'Você também pode gostar',
  'Bölüm': 'Episódio',
  'Bıraktım': 'Abandonei',
  'Dil': 'Idioma',
  'Dil ara...': 'Buscar idioma...',
  'Dizi': 'Série',
  'Dizi ve filmlerini takip et': 'Acompanhe suas séries e filmes',
  'Dizi yorumu': 'Comentário de série',
  'Dizi, film veya kişi ara...': 'Busque séries, filmes ou pessoas...',
  'Dosya en fazla 30MB olabilir': 'O arquivo pode ter no máximo 30MB',
  'Dosya en fazla {}MB olabilir': 'O arquivo pode ter no máximo {}MB',
  'E-posta': 'E-mail',
  'E-posta veya kullanıcı adı': 'E-mail ou nome de usuário',
  'En az 2 harf yaz': 'Digite pelo menos 2 letras',
  'Film': 'Filme',
  'Film yorumu': 'Comentário de filme',
  'Fotoğraf / video ekle': 'Adicionar foto / vídeo',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto ou GIF — foto de perfil e capa',
  'Giriş Yap': 'Entrar',
  'Gönder': 'Enviar',
  'Gönderildi': 'Enviado',
  'Haftanın Dizileri': 'Séries da Semana',
  'Haftanın Filmleri': 'Filmes da Semana',
  'Henüz izleme kaydın yok': 'Você ainda não tem histórico',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Você ainda não tem listas — crie uma na aba Perfil.',
  'Henüz yorum yok.': 'Ainda não há comentários.',
  'Hesabın bağlandı!': 'Sua conta foi vinculada!',
  'Hesabın yok mu? Kayıt ol': 'Não tem conta? Cadastre-se',
  'Hesabını Bağla': 'Vincule sua conta',
  'Hesap Oluştur': 'Criar conta',
  'Kapak resmi ekle': 'Adicionar capa',
  'Kaydet': 'Salvar',
  'Kendinden bahset...': 'Fale sobre você...',
  'Keşfet': 'Descobrir',
  'Kimseyi takip etmiyor': 'Não segue ninguém',
  'Kişi ara': 'Buscar pessoas',
  'Kişi yorumu': 'Comentário de pessoa',
  'Konuk Oyuncular': 'Participações especiais',
  'Kullanıcı adı (küçük harf)': 'Nome de usuário (minúsculas)',
  'Kullanıcı adı ara...': 'Buscar nome de usuário...',
  'Liste adı': 'Nome da lista',
  'Listeye Ekle': 'Adicionar à lista',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Você está em uma conta de convidado — vincule seu e-mail e não perca seus dados!',
  'Misafir olarak devam et': 'Continuar como convidado',
  'Oluştur': 'Criar',
  'Oyuncular': 'Elenco',
  'Profil': 'Perfil',
  'Profil kaydedildi': 'Perfil salvo',
  'Puanla': 'Avaliar',
  'Puanı Sil': 'Excluir nota',
  'Puanın': 'Sua nota',
  'Sezonlar': 'Temporadas',
  'Sunucu hatası ({})': 'Erro do servidor ({})',
  'S{} · {}. Bölüm': 'T{} · E{}',
  'S{}B{} yorumu': 'Comentário de T{}E{}',
  'Takibi Bırak': 'Deixar de seguir',
  'Takip': 'Seguindo',
  'Takip Edilenler': 'Seguindo',
  'Takip Et': 'Seguir',
  'Takipçi': 'Seguidores',
  'Takipçi yok': 'Nenhum seguidor',
  'Takipçiler': 'Seguidores',
  'Takvim': 'Calendário',
  'Tamam': 'OK',
  'Tekrar Dene': 'Tentar novamente',
  'Tekrar dene': 'Tente novamente',
  'Toplam İzleme Süresi': 'Tempo total de tela',
  'Tüm Zamanların En İyileri': 'Melhores de Todos os Tempos',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'Exporte todos os seus dados (histórico, notas, comentários, listas) como um ZIP compatível com o TV Time ou importe um ZIP de outro app.',
  'Tümünü Kaldır': 'Remover tudo',
  'Tümünü İzledim': 'Assisti a tudo',
  'Türk Dizileri': 'Séries Turcas',
  'Veri içe aktar (.zip)': 'Importar dados (.zip)',
  'Verilerim': 'Meus dados',
  'Verilerimi dışa aktar (e-posta)': 'Exportar meus dados (e-mail)',
  'Verilerini dışa aktar': 'Exporte seus dados',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Nenhum episódio a caminho.\nColoque uma série em "Assistindo" na tela de detalhes e acompanhe os novos episódios aqui.',
  'Yapımları': 'Filmografia',
  'Yeni Diziler': 'Novas Séries',
  'Yeni Liste': 'Nova lista',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Novo nome de usuário (opcional)',
  'Yorum': 'Comentário',
  'Yorumunu yaz...': 'Escreva seu comentário...',
  'Zaten hesabın var mı? Giriş yap': 'Já tem conta? Entre',
  'ort. {}': 'méd. {}',
  'takip': 'seguindo',
  'takipçi': 'seguidores',
  '{} / {} bölüm': '{} / {} episódios',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} meses',
  '{} ay~tekil': '{} mês',
  '{} bölüm izlendi': '{} episódios assistidos',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} dk~tekil': '{} min',
  '{} gün': '{} dias',
  '{} gün~tekil': '{} dia',
  '{} içerik': '{} títulos',
  '{} içerik · otomatik': '{} títulos · automática',
  '{} kayıt atlandı (eşleşmedi).':
      '{} registros ignorados (sem correspondência).',
  '{} saat': '{} horas',
  '{} saat~tekil': '{} hora',
  '{} sezon': '{} temporadas',
  '{} yıl': '{} anos',
  '{} yıl~tekil': '{} ano',
  '{}. Bölüm': 'Episódio {}',
  '{}. Sezon': 'Temporada {}',
  'Çıkış Yap': 'Sair',
  'Ülke': 'País',
  'Ülke ara...': 'Buscar país...',
  'Ülke seç': 'Escolha o país',
  'İlk yorumu sen yaz!': 'Seja o primeiro a comentar!',
  'İncelemeler': 'Resenhas',
  'İncelemen (isteğe bağlı)': 'Sua resenha (opcional)',
  'İptal': 'Cancelar',
  'İzlediklerim': 'Meu histórico',
  'İzledim': 'Assisti',
  'İzledin': 'Você assistiu',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Seu histórico e suas listas ficam salvos; agora você pode entrar de qualquer dispositivo.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Seu histórico, notas, comentários e listas serão enviados como ZIP para o e-mail cadastrado.',
  'İzleyeceğim': 'Vou assistir',
  'İzliyorum': 'Assistindo',
  'İçe aktarım tamamlandı': 'Importação concluída',
  'Şifre': 'Senha',
  '• profil bilgisi': '• dados do perfil',
  '• {} dizi durumu': '• {} status de séries',
  '• {} izleme kaydı': '• {} registros de exibição',
  '• {} liste': '• {} listas',
  '• {} puan': '• {} notas',
  '• {} yorum': '• {} comentários',
  '{}+ yapım': '{}+ títulos',
  'Yorumlar': 'Comentários',
  'Yorumlar ({})': 'Comentários ({})',
  'Yorumları ({})': 'Comentários ({})',
  'Listelerim': 'Minhas listas',
  'Nereden izledin?': 'Onde você assistiu?',
  'Diziye git': 'Ir para a série',
  'TV / Kanal': 'TV / Canal',
  'Sinema': 'Cinema',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Outro',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Seu feed está vazio.\nQuando comentarem nas séries e filmes que você assiste, aparecerá aqui.',
  'Listeleri ({})': 'Listas ({})',
  'Liste boş.': 'Esta lista está vazia.',
  'Yanıtla': 'Responder',
  '@{} kullanıcısına yanıt veriyorsun': 'Respondendo a @{}',
  'İzlediğim Diziler ({})': 'Séries que assisti ({})',
  'İzlediğim Filmler ({})': 'Filmes que assisti ({})',
  'Tümünü gör': 'Ver tudo',
  'Bildirimler': 'Notificações',
  'Henüz bildirim yok': 'Nenhuma notificação ainda',
  '@{} yorumuna yanıt verdi': '@{} respondeu seu comentário',
  '@{} yorumunu beğendi': '@{} curtiu seu comentário',
  '@{} seni takip etti': '@{} seguiu você',
  '@{} sana mesaj gönderdi': '@{} te enviou uma mensagem',
  'Mesajlar': 'Mensagens',
  'Mesaj': 'Mensagem',
  'Mesaja eklenecek': 'Sera adicionado a mensagem',
  'Mesajını yaz...': 'Escreva uma mensagem...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Nenhuma conversa ainda.\nAbra um perfil e envie uma mensagem.',
  'Şifreni mi unuttun?': 'Esqueceu a senha?',
  'Şifreyi Sıfırla': 'Redefinir senha',
  'E-postadaki kod': 'Código do e-mail',
  'Yeni şifre': 'Nova senha',
  'Sana Özel': 'Para você',
  '{} özetin': 'Sua retrospectiva de {}',
  'Yıllık izleme istatistiklerin': 'Suas estatísticas anuais',
  'Rozetler': 'Conquistas',
  'Verdiğin puan': 'Notas dadas',
  'Ortalama puanın': 'Sua nota média',
  'En çok izlediğin diziler': 'Suas séries mais assistidas',
  'İlk Bölüm': 'Primeiro episódio',
  '100 Bölüm': '100 episódios',
  '1000 Bölüm': '1000 episódios',
  'İlk Film': 'Primeiro filme',
  '50 Film': '50 filmes',
  'İlk Yorum': 'Primeiro comentário',
  '25 Yorum': '25 comentários',
  '10 Puan': '10 notas',
  'İlk Takipçi': 'Primeiro seguidor',
  '10 Dizi Bitirdin': '10 séries concluídas',
  'İzlemeyi Bıraktım': 'Parei de assistir',
  'İzlediği Diziler ({})': 'Séries que assistiu ({})',
  'İzlediği Filmler ({})': 'Filmes que assistiu ({})',
  '500 Bölüm': '500 episódios',
  '5000 Bölüm': '5000 episódios',
  '10 Film': '10 filmes',
  '100 Film': '100 filmes',
  '100 Yorum': '100 comentários',
  '50 Puan': '50 notas',
  '100 Puan': '100 notas',
  '10 Takipçi': '10 seguidores',
  '50 Takipçi': '50 seguidores',
  '25 Dizi Bitirdin': '25 séries concluídas',
  '50 Dizi Bitirdin': '50 séries concluídas',
  '10 Beğeni': '10 curtidas',
  '100 Beğeni': '100 curtidas',
  'yazıyor...': 'digitando...',
  'Profil düzeni': 'Layout do perfil',
  'Konumla ve kırp': 'Posicione e recorte',
  'Listeye eklendi': 'Adicionado à lista',
  'Listeyi sil?': 'Excluir a lista?',
  'Sil': 'Excluir',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Este título será marcado como nunca assistido e removido das suas listas.',
  'Gelecek bölüm bugün': 'Próximo episódio hoje',
  'Gelecek bölüm {} gün sonra': 'Próximo episódio em {} dias',
  'Tema': 'Tema',
  'Sistem': 'Sistema',
  'Koyu': 'Escuro',
  'Açık': 'Claro',
  'İzleyenler': 'Espectadores',
  'Yorumunu yaz... (@ ile etiketle)':
      'Escreva seu comentário... (@ para marcar)',
  '@{} bir yorumda seni etiketledi': '@{} marcou você em um comentário',
  'Mesajı sil': 'Excluir mensagem',
  'Mesaj silinemedi': 'Não foi possível excluir a mensagem',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Link inválido ou página não encontrada',
  "Keşfet'e dön": 'Voltar a Descobrir',
  'Düzenle': 'Editar',
  'Mesajı düzenle': 'Editar mensagem',
  'Yanıtlanıyor': 'Respondendo',
  'düzenlendi': 'editado',
  'Fotoğraf': 'Foto',
  'Video': 'Vídeo',
  'İçerik': 'Conteúdo',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': 'online há {} min',
  'son görülme {} saat önce': 'online há {} h',
  'son görülme {} gün önce': 'online há {} d',
  'Yorumlar yüklenemedi': 'Não foi possível carregar os comentários',
  'Favori': 'Favorito',
  'Listeye ekle': 'Adicionar à lista',
  'İçerik paylaş': 'Compartilhar conteúdo',
  'Kapat': 'Fechar',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Tudo o que você marcar como visto se junta aqui.',
  'Henüz sohbetin yok': 'Ainda sem conversas',
  'Bir profile girip mesaj gönderebilirsin.':
      'Abra um perfil e envie uma mensagem.',
  'Listeyi sil': 'Excluir lista',
  'Puan kaydedilemedi': 'Não foi possível salvar a nota',
  'Nerede İzlenir': 'Onde assistir',
  'Abonelik': 'Assinatura',
  'Kirala': 'Alugar',
  'Satın al': 'Comprar',
  'Devam et': 'Continuar',
  'Şikayet et': 'Denunciar',
  'Engelle': 'Bloquear',
  'Engeli kaldır': 'Desbloquear',
  'Kullanıcı engellendi': 'Usuário bloqueado',
  'Engel kaldırıldı': 'Bloqueio removido',
  'Şikayet sebebi': 'Motivo da denúncia',
  'Spam veya yanıltıcı': 'Spam ou enganoso',
  'Taciz veya nefret söylemi': 'Assédio ou discurso de ódio',
  'Uygunsuz / cinsel içerik': 'Conteúdo impróprio / sexual',
  'Şiddet veya tehlikeli içerik': 'Violência ou conteúdo perigoso',
  'Telif hakkı ihlali': 'Violação de direitos autorais',
  'Şikayetin alındı, teşekkürler': 'Sua denúncia foi recebida, obrigado',
  'Hesabımı Sil': 'Excluir minha conta',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Sua conta e todos os seus dados (histórico, avaliações, comentários, listas, mensagens) serão excluídos permanentemente. Isso não pode ser desfeito.',
  'Şifreni gir': 'Digite sua senha',
  'Hesabımı kalıcı sil': 'Excluir minha conta permanentemente',
  'Sesli mesaj': 'Mensagem de voz',
  'Ses gönderilemedi': 'Não foi possível enviar o áudio',
  'Kaydediliyor…': 'Gravando…',
  'Ses oynatılamadı': 'Não foi possível reproduzir o áudio',
  'Oynat': 'Reproduzir',
  'Duraklat': 'Pausar',
  'Liste görünümü': 'Visualização em lista',
  'Takvim görünümü': 'Visualização em calendário',
  'Önceki ay': 'Mês anterior',
  'Sonraki ay': 'Próximo mês',
  'Bu gün bölüm yok': 'Nenhum episódio neste dia',
  'Gizlilik Politikası': 'Política de Privacidade',
  'Son güncelleme: {}': 'Última atualização: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Esta política explica quais dados são coletados, como são usados e quais são os seus direitos ao usar o aplicativo dizi.jpg e o site dizijpg.com.',
  'Topladığımız Veriler': 'Dados que coletamos',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Conta: endereço de e-mail, nome de usuário e senha. As senhas são armazenadas com hash irreversível; contas de convidado podem ser usadas sem e-mail.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Perfil: informações que você escolhe adicionar, como avatar, imagem de capa, bio e país.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Uso: seu histórico de exibição, notas, comentários, listas, reações e favoritos.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Mensagens: suas mensagens de texto, imagem e voz ficam armazenadas em nossos servidores. As mensagens não têm criptografia de ponta a ponta; elas só são analisadas, para fins de moderação, se forem denunciadas.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Mídia enviada: fotos, GIF, vídeos e gravações de voz que você adiciona ao seu perfil, comentários e mensagens.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Dados técnicos: endereço IP, localização aproximada (país/cidade), plataforma do dispositivo, versão do aplicativo e registros de erros. São mantidos por segurança e para correção de falhas.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Estatísticas de uso: o tipo de dispositivo, o sistema operacional e o navegador usados no acesso são somados a contadores diários totais em categorias amplas; o identificador do navegador em si não é guardado e esses números não podem ser ligados a pessoas.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Notificações: para notificações push, guardamos o token do seu dispositivo e seu idioma. Você pode desativá-las quando quiser nas configurações do dispositivo.',
  'Verileri Nasıl Kullanırız': 'Como usamos seus dados',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Usamos seus dados apenas para fornecer o serviço, proteger sua conta, enviar notificações, corrigir erros e prevenir abusos. Não vendemos seus dados nem os compartilhamos com ninguém para fins publicitários.',
  'Çerezler ve Yerel Depolama': 'Cookies e armazenamento local',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Usamos armazenamento local apenas para manter você conectado e lembrar preferências como idioma e tema. Não há cookies de publicidade nem de rastreamento.',
  'Üçüncü Taraf Hizmetler': 'Serviços de terceiros',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Os dados de séries e filmes vêm do TMDB e as informações de plataformas de streaming, do JustWatch. As notificações push são entregues pelo Google Firebase e o tráfego do site é protegido pela Cloudflare. Esses serviços seguem suas próprias políticas de privacidade.',
  'Saklama ve Silme': 'Retenção e exclusão',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Seus dados são mantidos enquanto sua conta existir. Com "Excluir minha conta" nas Configurações, você pode excluir sua conta permanentemente; seus dados são apagados na hora e as cópias em backups, em até 14 dias. Os registros de erros são apagados automaticamente após 30 dias.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'Você pode exportar seus dados como ZIP nas Configurações; o arquivo é enviado para o seu e-mail.',
  'Güvenlik': 'Segurança',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Os dados trafegam por conexões criptografadas (HTTPS) e ficam em servidores com acesso restrito.',
  'Çocukların Gizliliği': 'Privacidade de crianças',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'O dizi.jpg não é destinado a menores de 13 anos.',
  'Hakların': 'Seus direitos',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'De acordo com a KVKK e o GDPR, você tem direito de acessar, corrigir, excluir e transferir seus dados. Para isso, escreva para: {}',
  'Değişiklikler': 'Alterações',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Se esta política mudar, a nova versão será publicada nesta página e a data será atualizada.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Ao se cadastrar, você aceita a {}.',
  'Kullanıcılar': 'Usuários',
  'Fotoğrafı değiştir': 'Trocar foto',
  'Yeniden konumlandır': 'Reposicionar',
  'Bir şeyler ters gitti': 'Algo deu errado',
  'Sosyal Bağlantılar': 'Redes sociais',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Até 3 links aparecem no seu perfil.',
  'Platform seç': 'Escolha uma plataforma',
  'Kullanıcı adın': 'Seu nome de usuário',
  'Ekle': 'Adicionar',
  'Kaldır': 'Remover',
  'Kopyalandı: {}': 'Copiado: {}',
  'Geçersiz kullanıcı adı': 'Nome de usuário inválido',
  'Bağlantı ekle': 'Adicionar link',
  'Spoiler olabilir — dokun ve gör': 'Pode conter spoilers — toque para ver',
  'Beğeni': 'Curtidas',
  'Beğen': 'Curtir',
  'Görüntülenme': 'Visualizações',
  'Tam ekran': 'Tela cheia',
  'Arama başarısız': 'Falha na pesquisa',
  'Sonuç bulunamadı': 'Nenhum resultado',
  'Dizi ve Filmler': 'Séries e filmes',
  'Kişiler': 'Pessoas',
  'Ana Sayfa': 'Início',
  'Paylaş': 'Compartilhar',
  'Yanıtlar': 'Respostas',
  'Yaklaşan Bölümler': 'Próximos episódios',
  'Yetişme Listesi': 'Lista para colocar em dia',
  'Şunu mu demek istedin': 'Você quis dizer',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — toque para ver',
  'uyum': 'de compatibilidade',
  'Uyum': 'Compatibilidade',
  '{} ortak dizi': '{} séries em comum',
  '{} ortak film': '{} filmes em comum',
  'Bildirim Tercihleri': 'Preferências de notificação',
  'Beğeniler': 'Curtidas',
  'Yeni takipçiler': 'Novos seguidores',
  'Etiketlenmeler': 'Menções',
  'Yeniden izledim': 'Revisto',
  '{}. kez izlendi': 'Visto {} vezes',
  'Gönderi bulunamadı': 'Publicação não encontrada',
  'Gözat': 'Explorar',
  'Diziler': 'Séries',
  'Filmler': 'Filmes',
  'Tümü': 'Tudo',
  'Farklı bir tür seç.': 'Tente outro gênero.',
  'Gizlilik': 'Privacidade',
  'İzlediklerimi gizle': 'Ocultar o que assisti',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'As séries e filmes que você assistiu não aparecem no seu perfil',
  'Yorumlarımı gizle': 'Ocultar meus comentários',
  'Profilinde yorumların görünmez':
      'Seus comentários não aparecem no seu perfil',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Você pode ocultar uma série ou filme específico com o chip "Ocultar no meu perfil" na página do conteúdo.',
  'Geri Bildirim': 'Feedback',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Escreva sua opinião e sugestões sobre o app...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Obrigado! Seu feedback foi recebido.',
  'Profilimde gizle': 'Ocultar no meu perfil',
  'Yorumları': 'Comentários',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Este usuário ainda não assistiu nada.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Este usuário prefere manter seus comentários privados.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Dados: JustWatch',
  'Web Sitesi': 'Site',
  'Diğer uygulamalar': 'Outros apps',
  'Bağlantıyı kopyala': 'Copiar link',
  'Henüz kimseyi takip etmiyorsun.': 'Você ainda não segue ninguém.',
  'Çevir': 'Traduzir',
  'Çeviri şu an yapılamadı': 'Tradução indisponível no momento',
  'Bağlantı açılamadı': 'Não foi possível abrir o link',
  'Orijinali göster': 'Ver original',
  'Çeviriyi göster': 'Mostrar tradução',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Nenhum episódio com data de exibição anunciada neste mês. As datas costumam sair algumas semanas antes e aparecerão aqui.',
  'devamı': 'mais',
  'Google ile devam et': 'Continuar com o Google',
  'Google girişi başarısız': 'Falha ao iniciar sessão com o Google',
  'Veri tasarrufu': 'Poupança de dados',
  'Wi-Fi ağında veri tasarrufu': 'Poupança de dados no Wi-Fi',
  'Mobil veride veri tasarrufu': 'Poupança de dados nos dados móveis',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Quando está ativa, as fotos não são transferidas antecipadamente; só carrega a imagem que estás a ver.',
  'Çocuk güvenliği': 'Segurança infantil',
  'Türk Filmleri': 'Filmes turcos',
  'En Yüksek Puanlı Filmler': 'Filmes mais bem avaliados',
  'En Yüksek Puanlı Diziler': 'Séries mais bem avaliadas',
  'En Çok İzlenen Filmler': 'Filmes mais vistos',
  'Popüler Diziler': 'Séries populares',
  'En Çok Kazanan Filmler': 'Filmes de maior bilheteira',
  'Kült Filmler': 'Filmes de culto',
  'Yeni Filmler': 'Filmes novos',
  'Yorum yap': 'Comentar',
  'Henüz yorum yok': 'Ainda sem comentários',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Os teus comentários sobre séries e filmes juntam-se aqui.',
  'GIF ekle': 'Adicionar GIF',
  'İlk yorumu sen yaz': 'Seja o primeiro a comentar',
  'Video altyazıları': 'Legendas de vídeo',
  'Videolarda altyazı göster': 'Mostrar legendas em vídeos',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'A frase falada no vídeo está escrita na tela. O texto é traduzido: inglês na língua turca, turco em outras línguas.',
  'Güncelleme gerekli': 'Atualização necessária',
  'Yeni sürüm var': 'Nova versão disponível',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Instale a nova versão do dizi.jpg para continuar.',
  'Güncelle': 'Atualizar',
  'Daha sonra': 'Mais tarde',
  'Takvim güncelleniyor': 'Atualizando o calendário',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Não foi possível atualizar o calendário, exibindo a lista antiga',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Algumas séries não puderam ser carregadas, a lista pode estar incompleta',
  'Yenile': 'Atualizar',
  'Devam etmek için giriş yap': 'Entra para continuar',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Uma conta gratuita basta para avaliar, comentar e criar a tua biblioteca.',
  'Şimdi değil': 'Agora não',
  'Yorum yazmak için giriş yap': 'Entra para escrever um comentário',
  'Kişilere göndermek için giriş yap': 'Entra para enviar a pessoas',
  'Beğenenler': 'Curtidas',
  'Henüz beğeni yok': 'Ainda sem curtidas',
  'Bu gönderiyi ilk beğenen sen ol': 'Seja a primeira pessoa a curtir',
  'Bu gönderiye yanıt': 'Resposta a esta publicacao',
  'Spoiler içeren gönderi': 'Publicação com spoiler',
  'Görsel gönderi': 'Publicação com foto',
  'Bu yorumu profilimde gizle': 'Ocultar este comentário no meu perfil',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'O comentário continua na página da série e do filme',
  'Bu yorumu sil': 'Excluir este comentário',
  'Yorum profilinde gizlendi': 'Comentário ocultado no seu perfil',
  'Geri al': 'Desfazer',
  'Yorum silinsin mi?': 'Excluir comentário?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Este comentário será excluído permanentemente em todos os lugares. Não pode ser desfeito.',
  'Yorum silindi': 'Comentário excluído',
  'Yorum profilinde tekrar görünüyor':
      'O comentário está visível novamente no seu perfil',
  'Gizlenen yorumun yok': 'Nenhum comentário ocultado',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Os comentários que você oculta ao manter pressionada uma publicação na aba Comentários do seu perfil se acumulam aqui.',
  'Gizlenen yorumlar': 'Comentários ocultados',
  'Gönderiye git': 'Ir para a publicação',
  'Tekrar göster': 'Mostrar novamente',
  'Yanıtlarımı gizle': 'Ocultar minhas respostas',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'As respostas que você escreve em publicações de outras pessoas são visíveis só para você',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Mostrar novamente os comentários que você ocultou no seu perfil',
  'Sıralama': 'Ordem',
  'Önerilen': 'Recomendado',
  'Kronolojik': 'Cronológico',
  'Gelen mesaj istekleri': 'Pedidos de mensagem recebidos',
  'Mesaj isteğin yok': 'Nenhum pedido de mensagem',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'As mensagens de pessoas que você não segue aparecem aqui.',
  'Çevrimiçi durumumu gizle': 'Ocultar meu status online',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Os outros não verão seu status online nem sua última visualização nas mensagens',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Entre os nossos primeiros usuários. Os comentários ajudaram o aplicativo a se tornar o que é hoje.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Você está entre os nossos primeiros usuários. Seus comentários ajudaram o aplicativo a se tornar o que é hoje.',
  'İleri': 'Avançar',
  'Seçilen dosya okunamadı': 'Não foi possível ler o arquivo selecionado',
  'Video açılamadı': 'Não foi possível abrir o vídeo',
  'En fazla {} medya seçebilirsin': 'Você pode selecionar no máximo {} mídias',
  'Hiçbir medya yüklenemedi': 'Nenhuma mídia foi enviada',
  'Seçimi kaldır': 'Remover da seleção',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'Em um comentário você pode enviar {} MB no total',
  '{} dosya okunamadı': '{} arquivos não puderam ser lidos',
  '{} medya eklendi, {} yüklenemedi': '{} mídias adicionadas, {} falharam',
  'Kırp': 'Recortar',
  'Çiz': 'Desenhar',
  'Metin': 'Texto',
  'Emoji': 'Emoji',
  'Yinele': 'Refazer',
  'Daha fazla': 'Mais',
  'Hazırlanıyor…': 'Preparando…',
  'Düzenlemeden çık?': 'Sair da edição?',
  'Yaptığın değişiklikler kaybolacak.':
      'As alterações que você fez serão perdidas.',
  'Çık': 'Sair',
  'Serbest çizim': 'Mão livre',
  'Ok': 'Seta',
  'Dikdörtgen': 'Retângulo',
  'Daire': 'Círculo',
  'Bulanıklaştır': 'Desfocar',
  'Pikselleştir': 'Pixelizar',
  'Silgi': 'Borracha',
  'Çizgi kalınlığı': 'Espessura da linha',
  'Saydamlık': 'Opacidade',
  'Dolgu': 'Preenchimento',
  'Renk': 'Cor',
  'Döndür': 'Girar',
  'Yansıt': 'Inverter',
  'Oran': 'Proporção',
  'Sıfırla': 'Redefinir',
  'Serbest': 'Livre',
  'Metin yaz...': 'Digite um texto...',
  'Hizala': 'Alinhar',
  'Arka plan': 'Fundo',
  'Emoji ara...': 'Pesquisar emoji...',
  'Son kullanılanlar': 'Recentes',
  'İfadeler ve insanlar': 'Rostos e pessoas',
  'Hayvanlar ve doğa': 'Animais e natureza',
  'Yiyecek ve içecek': 'Comida e bebida',
  'Etkinlikler': 'Atividades',
  'Seyahat ve yerler': 'Viagens e lugares',
  'Nesneler': 'Objetos',
  'Semboller': 'Símbolos',
  'Bayraklar': 'Bandeiras',
  'Görseli düzenle': 'Editar imagem',
  'Düzenlendi': 'Editada',
  'Düzenlenemedi': 'Não foi possível editar',
  'Düzenlenen görsel çok büyük': 'A imagem editada é muito grande',
  'Videoyu düzenle': 'Editar video',
  'Sesi kapat': 'Silenciar',
  'Sesi aç': 'Ativar som',
  'İptal ediliyor…': 'Cancelando…',
  'Bu biraz sürebilir': 'Isso pode demorar um pouco',
  'Video çok büyük': 'O video e muito grande',
  'Video hazırlanamadı': 'Nao foi possivel preparar o video',
  'Başlangıç': 'Inicio',
  'Bitiş': 'Fim',
  'En çok {} saniye seçebilirsin': 'Voce pode selecionar ate {} segundos',
  'Dosya en fazla {} MB olabilir': 'O arquivo pode ter no maximo {} MB',
  'Medya ekle': 'Adicionar mídia',
  'Seçili medya kalmadı': 'Nenhuma mídia selecionada',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Escolha uma foto ou vídeo para adicionar ao seu comentário.',
  'Medya seç': 'Selecionar mídia',
  'Daha fazla ekle': 'Adicionar mais',
  'Medya seçilemedi': 'Não foi possível selecionar a mídia',
  'Favori oyuncular': 'Atores favoritos',
  'Henüz favori oyuncun yok': 'Ainda sem atores favoritos',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Abra a pagina de um ator e toque no coracao no topo direito para adiciona-lo aqui.',
  '{} yapımdan {} tanesini izledin': 'Voce viu {} de {} titulos',
  'izledin': 'vistos',
  'İzlemedin': 'Nao visto',
  'Yapım bulunamadı': 'Nenhum titulo encontrado',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Esta pessoa nao tem series ou filmes para listar.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Seu historico esta ligado a sua conta; esta lista e so sua.',
  'Hesabın kalıcı olarak askıya alındı':
      'A tua conta foi suspensa permanentemente',
  'Hesabın geçici olarak askıya alındı':
      'A tua conta foi suspensa temporariamente',
  'Hesabın askıya alındı': 'A tua conta está suspensa',
  'Sebep': 'Motivo',
  'Kalan süre': 'Tempo restante',
  'Süre dolunca hesabın kendiliğinden açılır':
      'A tua conta reabre automaticamente quando o prazo terminar',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'Durante este período podes continuar a ler, mas não podes publicar, comentar nem enviar mensagens.',
  'Anladım': 'Entendi',
  'Ayrıntı': 'Detalhes',
  '{} dakika': '{} minutos',
  'birkaç saniye': 'alguns segundos',
  'Karara itiraz et': 'Contestar esta decisão',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Explica por que esta penalização deve ser retirada',
  'İtirazını gönder': 'Enviar a tua contestação',
  'İtirazın incelemede': 'A tua contestação está em análise',
  'İtirazın reddedildi': 'A tua contestação foi recusada',
  'İtirazın alındı, inceleniyor':
      'Recebemos a tua contestação e está em análise',
  'İtiraz en az 10 karakter olmalı':
      'A contestação deve ter pelo menos 10 caracteres',
  'Yükleniyor...': 'A carregar...',
  'Bu bölüme puan ver': 'Avalie este episódio',
  '{} kişi puanladı': '{} pessoas avaliaram',
  'Bölüm izlendi olarak işaretlendi': 'Episódio marcado como visto',
  'Sesli ara': 'Chamada de voz',
  'Görüntülü ara': 'Videochamada',
  'Çalıyor...': 'Chamando...',
  'Bağlanıyor...': 'Conectando...',
  'Cevapla': 'Atender',
  'Reddet': 'Recusar',
  'Sessize al': 'Silenciar',
  'Hoparlör': 'Alto-falante',
  'Kamerayı kapat': 'Desligar câmera',
  'Kamerayı çevir': 'Virar câmera',
  'Cevap yok': 'Sem resposta',
  'Arama reddedildi': 'Chamada recusada',
  'Meşgul': 'Ocupado',
  'Bağlanılamadı': 'Não foi possível conectar',
  'Arama iptal edildi': 'Chamada cancelada',
  'Arama geçmişi': 'Histórico de chamadas',
  'Gelen arama': 'Chamada recebida',
  'Giden arama': 'Chamada realizada',
  'Cevapsız arama': 'Chamada perdida',
  'Arama şu anda kullanılamıyor': 'As chamadas estão indisponíveis no momento',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'As videochamadas estão desativadas, você pode fazer uma chamada de voz',
  'Bu kullanıcıyı arayamazsın': 'Você não pode ligar para este usuário',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Vocês precisam seguir um ao outro para ligar',
  'Bu kullanıcı şu anda aranamıyor':
      'Não é possível ligar para este usuário agora',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Muitas chamadas perdidas. Tente novamente em {}',
  'Zaten bir aramadasın': 'Você já está em uma chamada',
  'Arama için mikrofon izni gerekiyor':
      'É necessária permissão de microfone para ligar',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'É necessária permissão de câmera e microfone para videochamadas',
  'Arama başlatılamadı': 'Não foi possível iniciar a chamada',
  'Kullanıcı bulunamadı': 'Usuário não encontrado',
  'Kendini arayamazsın': 'Você não pode ligar para si mesmo',
  'Arama artık geçerli değil': 'Esta chamada não é mais válida',
  'Bu aramanın tarafı değilsin': 'Você não faz parte desta chamada',
  'Arama bulunamadı': 'Chamada não encontrada',
  'Çok fazla istek, biraz bekle': 'Muitas solicitações, aguarde um pouco',
  'Bağlantı koptu': 'Conexão perdida',
  'Arama süre sınırına ulaştı': 'A chamada atingiu o limite de tempo',
  'Arama en fazla 4 saat sürebilir': 'Uma chamada pode durar no máximo 4 horas',
  'Arama sona erdi': 'A chamada terminou',
  'Sesli arama': 'Chamada de voz',
  'Görüntülü arama': 'Videochamada',
  'Gelen aramalar': 'Chamadas recebidas',
  'Sesli ve görüntülü arama bildirimleri':
      'Notificações de chamadas de voz e vídeo',
  '{} sa': '{} h',
  'Sesli ve Görüntülü Aramalar': 'Chamadas de voz e vídeo',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'O conteúdo das chamadas nunca é gravado. Áudio e vídeo trafegam com criptografia de ponta a ponta (DTLS-SRTP) entre os dispositivos; nossos servidores não conseguem descriptografar, ouvir ou armazenar esse tráfego.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Somente os metadados da chamada são guardados: com quem, em qual direção, quando e quanto durou. Esses registros são apagados automaticamente após 90 dias.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Se não for possível estabelecer uma conexão direta, áudio e vídeo passam criptografados por um servidor de retransmissão (TURN). Esse servidor também não consegue descriptografar nem gravar o conteúdo.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'O microfone é usado apenas durante uma chamada de voz ou vídeo, e a câmera apenas durante uma videochamada. Ambos são desligados quando a chamada termina.',
  'Takip ettiğin {} kişi izledi': '{} pessoas que você segue assistiram',
  'Yorum yaz...': 'Escreva um comentário...',
  'Sıradaki bölüm': 'Próximo episódio',
  'Doğrulanmış testçi': 'Testador verificado',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Notificações de seguidores, curtidas, respostas, mensagens e menções',
  'Sen': 'Você',
  'Aradığınız kişide sesli arama devre dışı':
      'As chamadas de voz estão desativadas para esta pessoa',
  'Aradığınız kişide görüntülü arama devre dışı':
      'As chamadas de vídeo estão desativadas para esta pessoa',
  'Sesli aramalara izin ver': 'Permitir chamadas de voz',
  'Görüntülü aramalara izin ver': 'Permitir chamadas de vídeo',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Quando desativado, ninguém pode te ligar por voz; quem ligar verá um aviso',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Quando desativado, ninguém pode te chamar em vídeo; quem ligar verá um aviso',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'As chamadas de voz estão desativadas. Você pode ativá-las em Configurações > Privacidade.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'As chamadas de vídeo estão desativadas. Você pode ativá-las em Configurações > Privacidade.',
  'Sesli ve görüntülü arama': 'Chamadas de voz e vídeo',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Contas de convidado não podem ligar. Cria uma conta para usar isto.',
  'Misafir hesaplar aranamaz': 'Não é possível ligar para contas de convidado',
  'Puan dağılımı': 'Distribuição das notas',
  '{} yıldız': '{} estrelas',
  'Yakında gelecek': 'Em breve',
  '{} {} yayınlandı': '{} {} já saiu',
  'Yeni bölüm yayınlandı': 'Novo episódio já saiu',
  'Yeni bölümler': 'Novos episódios',
  'Geri': 'Voltar',
  'Karşılamayı kapat': 'Fechar a introdução',
  'Adım {} / {}': 'Etapa {} / {}',
  'Hadi başlayalım': 'Vamos começar',
  'Kaydet ve devam': 'Salvar e continuar',
  '{} tanesini ekle': 'Adicionar {}',
  'Şimdilik geç': 'Agora não',
  'Doğum tarihin ne zaman?': 'Qual é a sua data de nascimento?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Perguntamos para mostrar conteúdo adequado à sua idade e para te parabenizar no aniversário.',
  'Gün': 'Dia',
  'Ay': 'Mês',
  'Yıl': 'Ano',
  'Doğum yılımı paylaşmak istemiyorum':
      'Não quero compartilhar meu ano de nascimento',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'Sua data de nascimento não aparece publicamente no seu perfil. Ela é usada apenas para o conteúdo adequado à idade e para a mensagem de aniversário.',
  'Ocak': 'janeiro',
  'Şubat': 'fevereiro',
  'Mart': 'março',
  'Nisan': 'abril',
  'Mayıs': 'maio',
  'Haziran': 'junho',
  'Temmuz': 'julho',
  'Ağustos': 'agosto',
  'Eylül': 'setembro',
  'Ekim': 'outubro',
  'Kasım': 'novembro',
  'Aralık': 'dezembro',
  'Verilerini yanında getir': 'Traga seus dados com você',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Se você acompanha o que assiste em outro app, pode trazer tudo para cá. Não precisa começar do zero.',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt e Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Escolha o arquivo ZIP que você exportou; o que você assistiu, suas notas e suas listas serão importados.',
  'Aktarılıyor...': 'Importando...',
  'ZIP dosyası seç': 'Escolher arquivo ZIP',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'Sem pressa: você também pode fazer isso depois em Configurações > Meus dados.',
  'Hangi filmleri izledin?': 'Quais filmes você já assistiu?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Aqui estão os mais assistidos. Toque nos que você viu e adicionamos ao seu histórico.',
  'SERİ FİLMLER': 'SAGAS',
  'Serilerden {} film eklendi': '{} filmes adicionados a partir das sagas',
  'Film listesi yüklenemedi': 'Não foi possível carregar a lista de filmes',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Você pode pular esta etapa e adicionar o que quiser depois.',
  '{} film izlediklerine eklendi': '{} filmes adicionados ao seu histórico',
  'Film serileri': 'Sagas de filmes',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Se você assistiu a uma saga inteira, adicione com um único toque.',
  'Seri bulunamadı': 'Nenhuma saga encontrada',
  'Daha sonra tekrar deneyebilirsin.': 'Você pode tentar de novo mais tarde.',
  '{} film': '{} filmes',
  'Eklendi': 'Adicionado',
  'Tümünü izledim': 'Vi todos',
  'Peki ya diziler?': 'E as séries?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Marque o que você já assistiu; conforme escolhe, trazemos séries parecidas.',
  'Dizi listesi yüklenemedi': 'Não foi possível carregar a lista de séries',
  'Seçtiklerine benzeyenler': 'Parecidas com o que você escolheu',
  'Her şey hazır': 'Tudo pronto',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Dê uma olhada rápida no que dá para fazer no dizi.jpg.',
  'Profilini tamamla': 'Complete seu perfil',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'Em Configurações você pode adicionar uma bio, uma foto de perfil e uma capa.',
  'Takvimin seni bekliyor': 'Seu calendário está te esperando',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'Os novos episódios das séries que você assiste entram no calendário e avisamos por notificação.',
  'Puan ver, yorum yaz': 'Dê nota e comente',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Dê nota episódio a episódio, comente com cortina de spoiler e crie listas.',
  'Verilerin sende kalır': 'Seus dados continuam seus',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Seus dados ficam ligados apenas à sua conta e não são vendidos. Em Configurações você pode baixar tudo ou excluir sua conta por completo.',
  'Engellenen kullanıcılar': 'Pessoas bloqueadas',
  'Engellediğin kişileri gör, engeli kaldır':
      'Veja quem você bloqueou e desbloqueie',
  'Engellediğin kimse yok': 'Você não bloqueou ninguém',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Você pode bloquear uma pessoa pelo menu de três pontos no perfil dela.',
  '@{} engellensin mi?': 'Bloquear @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'Nenhuma das duas partes verá as publicações, os comentários nem o perfil da outra; também não será possível enviar mensagens nem fazer chamadas. Se houver um vínculo de seguir, ele é rompido e não volta nem se você remover o bloqueio.',
  'Bu kullanıcıyı engelledin': 'Você bloqueou essa pessoa',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Você não vê as publicações, os comentários nem as mensagens dessa pessoa; ela também não vê os seus.',
  '{} yeni bir yapımda: {}': '{} está em uma nova produção: {}',
  'Favori kişinden yeni yapım': 'Nova produção de uma pessoa favorita',
  '{} için bildirimler': 'Notificações de {}',
  'Tüm bildirimler': 'Todas as notificações',
  'Uygulamada ve telefonda': 'No app e no celular',
  'Yalnız uygulama içi': 'Somente no app',
  'Telefon bildirimi gönderilmez': 'Nenhuma notificação é enviada ao celular',
  'Kapalı': 'Desativado',
  'Bu kişi için bildirim yok': 'Sem notificações desta pessoa',
  'Favori kişilerin yeni yapımları':
      'Novas produções das suas pessoas favoritas',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Quando desativado, ninguém pode te ligar por voz; quem ligar verá o aviso "desativadas"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Quando desativado, ninguém pode te chamar em vídeo; quem ligar verá o aviso "desativadas"',
};
