/// Otomatik üretilen çeviri haritası (he).
const Map<String, String> cevirilerHe = {
  'Aktarılacak tanınan veri bulunamadı.': 'לא נמצאו נתונים מזוהים לייבוא.',
  'Arama': 'חיפוש',
  'Aramaya başla': 'התחל לחפש',
  'Son aramalar': 'חיפושים אחרונים',
  'Ayarlar': 'הגדרות',
  'Bağla': 'קשר',
  'Bio': 'ביו',
  'Bitirdim': 'סיימתי',
  'Bunları da Beğenebilirsin': 'אולי תאהב גם את אלה',
  'Bölüm': 'פרק',
  'Bıraktım': 'נטשתי',
  'Dil': 'שפה',
  'Dil ara...': 'חפש שפה...',
  'Dizi': 'סדרה',
  'Dizi ve filmlerini takip et': 'עקוב אחרי הסדרות והסרטים שלך',
  'Dizi yorumu': 'תגובה על הסדרה',
  'Dizi, film veya kişi ara...': 'חפש סדרה, סרט או אדם...',
  'Dosya en fazla 30MB olabilir': 'גודל הקובץ יכול להיות עד 30MB',
  'Dosya en fazla {}MB olabilir': 'גודל הקובץ יכול להיות עד {}MB',
  'E-posta': 'אימייל',
  'E-posta veya kullanıcı adı': 'אימייל או שם משתמש',
  'En az 2 harf yaz': 'הקלד לפחות 2 אותיות',
  'Film': 'סרט',
  'Film yorumu': 'תגובה על הסרט',
  'Fotoğraf / video ekle': 'הוסף תמונה / וידאו',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'תמונה או GIF — תמונת פרופיל וקאבר',
  'Giriş Yap': 'התחברות',
  'Gönder': 'שלח',
  'Gönderildi': 'נשלח',
  'Haftanın Dizileri': 'סדרות השבוע',
  'Haftanın Filmleri': 'סרטי השבוע',
  'Henüz izleme kaydın yok': 'אין לך עדיין היסטוריית צפייה',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'אין לך עדיין רשימות — צור אחת מלשונית הפרופיל.',
  'Henüz yorum yok.': 'אין תגובות עדיין.',
  'Hesabın bağlandı!': 'החשבון שלך קושר!',
  'Hesabın yok mu? Kayıt ol': 'אין לך חשבון? הירשם',
  'Hesabını Bağla': 'קשר את החשבון שלך',
  'Hesap Oluştur': 'יצירת חשבון',
  'Kapak resmi ekle': 'הוסף תמונת קאבר',
  'Kaydet': 'שמור',
  'Kendinden bahset...': 'ספר על עצמך...',
  'Keşfet': 'גלה',
  'Kimseyi takip etmiyor': 'לא עוקב אחרי אף אחד',
  'Kişi ara': 'חפש אדם',
  'Kişi yorumu': 'תגובה על האדם',
  'Konuk Oyuncular': 'שחקנים אורחים',
  'Kullanıcı adı (küçük harf)': 'שם משתמש (אותיות קטנות)',
  'Kullanıcı adı ara...': 'חפש שם משתמש...',
  'Liste adı': 'שם הרשימה',
  'Listeye Ekle': 'הוסף לרשימה',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'אתה בחשבון אורח — קשר אותו לאימייל שלך ואל תאבד את הנתונים!',
  'Misafir olarak devam et': 'המשך כאורח',
  'Oluştur': 'צור',
  'Oyuncular': 'שחקנים',
  'Profil': 'פרופיל',
  'Profil kaydedildi': 'הפרופיל נשמר',
  'Puanla': 'דרג',
  'Puanı Sil': 'מחק דירוג',
  'Puanın': 'הדירוג שלך',
  'Sezonlar': 'עונות',
  'Sunucu hatası ({})': 'שגיאת שרת ({})',
  'S{} · {}. Bölüm': 'ע{} · פרק {}',
  'S{}B{} yorumu': 'תגובה על ע{}פ{}',
  'Takibi Bırak': 'הפסק לעקוב',
  'Takip': 'במעקב',
  'Takip Edilenler': 'נעקבים',
  'Takip Et': 'עקוב',
  'Takipçi': 'עוקב',
  'Takipçi yok': 'אין עוקבים',
  'Takipçiler': 'עוקבים',
  'Takvim': 'לוח שנה',
  'Tamam': 'אישור',
  'Tekrar Dene': 'נסה שוב',
  'Tekrar dene': 'נסה שוב',
  'Toplam ekran süresi': 'זמן מסך כולל',
  'Tüm Zamanların En İyileri': 'הטובים בכל הזמנים',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'ייצא את כל הנתונים שלך (צפיות, דירוגים, תגובות, רשימות) כקובץ ZIP תואם TV Time, או ייבא ZIP מאפליקציה אחרת.',
  'Tümünü Kaldır': 'הסר הכל',
  'Tümünü İzledim': 'צפיתי בהכל',
  'Türk Dizileri': 'סדרות טורקיות',
  'Veri içe aktar (.zip)': 'ייבוא נתונים (.zip)',
  'Verilerim': 'הנתונים שלי',
  'Verilerimi dışa aktar (e-posta)': 'ייצוא הנתונים שלי (אימייל)',
  'Verilerini dışa aktar': 'ייצא את הנתונים שלך',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'אין פרקים קרובים.\nהעבר סדרה למצב "צופה" מדף הסדרה ועקוב אחרי פרקים חדשים כאן.',
  'Yapımları': 'פילמוגרפיה',
  'Yeni Diziler': 'סדרות חדשות',
  'Yeni Liste': 'רשימה חדשה',
  'Yeni kullanıcı adı (isteğe bağlı)': 'שם משתמש חדש (אופציונלי)',
  'Yorum': 'תגובה',
  'Yorumunu yaz...': 'כתוב את התגובה שלך...',
  'Zaten hesabın var mı? Giriş yap': 'כבר יש לך חשבון? התחבר',
  'ort. {}': 'ממוצע {}',
  'takip': 'במעקב',
  'takipçi': 'עוקבים',
  '{} / {} bölüm': '{} / {} פרקים',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} חודשים',
  '{} bölüm izlendi': '{} פרקים נצפו',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} דק\'',
  '{} gün': '{} ימים',
  '{} içerik': '{} פריטים',
  '{} içerik · otomatik': '{} פריטים · אוטומטי',
  '{} kayıt atlandı (eşleşmedi).': '{} רשומות דולגו (ללא התאמה).',
  '{} saat': '{} שעות',
  '{} sezon': '{} עונות',
  '{} yıl': '{} שנים',
  '{}. Bölüm': 'פרק {}',
  '{}. Sezon': 'עונה {}',
  'Çıkış Yap': 'התנתקות',
  'Ülke': 'מדינה',
  'Ülke ara...': 'חפש מדינה...',
  'Ülke seç': 'בחר מדינה',
  'İlk yorumu sen yaz!': 'כתוב את התגובה הראשונה!',
  'İncelemeler': 'ביקורות',
  'İncelemen (isteğe bağlı)': 'הביקורת שלך (אופציונלי)',
  'İptal': 'ביטול',
  'İzlediklerim': 'הצפיות שלי',
  'İzledim': 'צפיתי',
  'İzledin': 'צפית',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'היסטוריית הצפייה והרשימות שלך נשמרות; מעכשיו תוכל להתחבר מכל מכשיר.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'היסטוריית הצפייה, הדירוגים, התגובות והרשימות שלך יישלחו כקובץ ZIP לכתובת האימייל הרשומה שלך.',
  'İzleyeceğim': 'אצפה',
  'İzliyorum': 'צופה',
  'İçe aktarım tamamlandı': 'הייבוא הושלם',
  'Şifre': 'סיסמה',
  '• profil bilgisi': '• פרטי פרופיל',
  '• {} dizi durumu': '• {} סטטוסי סדרות',
  '• {} izleme kaydı': '• {} רשומות צפייה',
  '• {} liste': '• {} רשימות',
  '• {} puan': '• {} דירוגים',
  '• {} yorum': '• {} תגובות',
  '{}+ yapım': '{}+ עבודות',
  'Yorumlar': 'תגובות',
  'Yorumlar ({})': 'תגובות ({})',
  'Yorumları ({})': 'התגובות ({})',
  'Listelerim': 'הרשימות שלי',
  'Nereden izledin?': 'איפה צפית?',
  'Diziye git': 'אל הסדרה',
  'TV / Kanal': 'טלוויזיה / ערוץ',
  'Sinema': 'קולנוע',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'אחר',
  'Akış': 'פיד',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'הפיד שלך ריק.\nכשיגיבו על הסדרות והסרטים שאתה צופה בהם, זה יופיע כאן.',
  'Listeleri ({})': 'הרשימות שלו ({})',
  'Liste boş.': 'הרשימה הזו ריקה.',
  'Yanıtla': 'השב',
  '@{} kullanıcısına yanıt veriyorsun': 'אתה מגיב ל-@{}',
  'İzlediğim Diziler ({})': 'סדרות שצפיתי ({})',
  'İzlediğim Filmler ({})': 'סרטים שצפיתי ({})',
  'Tümünü gör': 'הצג הכול',
  'Bildirimler': 'התראות',
  'Henüz bildirim yok': 'אין התראות עדיין',
  '@{} yorumuna yanıt verdi': '@{} הגיב לתגובה שלך',
  '@{} yorumunu beğendi': '@{} אהב את התגובה שלך',
  '@{} seni takip etti': '@{} עוקב אחריך',
  '@{} sana mesaj gönderdi': '@{} שלח לך הודעה',
  'Mesajlar': 'הודעות',
  'Mesaj': 'הודעה',
  'Mesajını yaz...': 'כתוב הודעה...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'אין צ\'אטים עדיין.\nפתח פרופיל ושלח הודעה.',
  'Şifreni mi unuttun?': 'שכחת סיסמה?',
  'Şifreyi Sıfırla': 'איפוס סיסמה',
  'E-postadaki kod': 'הקוד מהמייל',
  'Yeni şifre': 'סיסמה חדשה',
  'Sana Özel': 'בשבילך',
  '{} özetin': 'הסיכום שלך ל-{}',
  'Yıllık izleme istatistiklerin': 'סטטיסטיקת הצפייה השנתית',
  'Rozetler': 'תגים',
  'Verdiğin puan': 'דירוגים שנתת',
  'Ortalama puanın': 'הדירוג הממוצע שלך',
  'En çok izlediğin diziler': 'הסדרות הנצפות ביותר',
  'İlk Bölüm': 'פרק ראשון',
  '100 Bölüm': '100 פרקים',
  '1000 Bölüm': '1000 פרקים',
  'İlk Film': 'סרט ראשון',
  '50 Film': '50 סרטים',
  'İlk Yorum': 'תגובה ראשונה',
  '25 Yorum': '25 תגובות',
  '10 Puan': '10 דירוגים',
  'İlk Takipçi': 'עוקב ראשון',
  '10 Dizi Bitirdin': 'סיימת 10 סדרות',
  'İzlemeyi Bıraktım': 'הפסקתי לצפות',
  'İzlediği Diziler ({})': 'סדרות שצפה בהן ({})',
  'İzlediği Filmler ({})': 'סרטים שצפה בהם ({})',
  '500 Bölüm': '500 פרקים',
  '5000 Bölüm': '5000 פרקים',
  '10 Film': '10 סרטים',
  '100 Film': '100 סרטים',
  '100 Yorum': '100 תגובות',
  '50 Puan': '50 דירוגים',
  '100 Puan': '100 דירוגים',
  '10 Takipçi': '10 עוקבים',
  '50 Takipçi': '50 עוקבים',
  '25 Dizi Bitirdin': 'סיים 25 סדרות',
  '50 Dizi Bitirdin': 'סיים 50 סדרות',
  '10 Beğeni': '10 לייקים',
  '100 Beğeni': '100 לייקים',
  'yazıyor...': 'מקליד...',
  'Profil düzeni': 'פריסת פרופיל',
  'Konumla ve kırp': 'מקם וחתוך',
  'Listeye eklendi': 'נוסף לרשימה',
  'Listeyi sil?': 'למחוק את הרשימה?',
  'Sil': 'מחק',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'הכותר יסומן כלא נצפה ויוסר מהרשימות שלך.',
  'Gelecek bölüm bugün': 'הפרק הבא היום',
  'Gelecek bölüm {} gün sonra': 'הפרק הבא בעוד {} ימים',
  'Tema': 'ערכת נושא',
  'Sistem': 'מערכת',
  'Koyu': 'כהה',
  'Açık': 'בהיר',
  'İzleyenler': 'צופים',
  'Yorumunu yaz... (@ ile etiketle)': 'כתוב את התגובה שלך... (@ לתיוג)',
  '@{} bir yorumda seni etiketledi': '‏@{} תייג אותך בתגובה',
  'Mesajı sil': 'מחק הודעה',
  'Mesaj silinemedi': 'לא ניתן היה למחוק את ההודעה',
  'Bağlantı geçersiz veya sayfa bulunamadı': 'הקישור אינו תקין או שהדף לא נמצא',
  'Keşfet\'e dön': 'חזרה לגילוי',
  'Düzenle': 'ערוך',
  'Mesajı düzenle': 'ערוך הודעה',
  'Yanıtlanıyor': 'משיב',
  'düzenlendi': 'נערך',
  'Fotoğraf': 'תמונה',
  'Video': 'וידאו',
  'İçerik': 'תוכן',
  'çevrimiçi': 'מחובר',
  'son görülme {} dk önce': 'נראה לפני {} דק\'',
  'son görülme {} saat önce': 'נראה לפני {} ש\'',
  'son görülme {} gün önce': 'נראה לפני {} י\'',
  'Yorumlar yüklenemedi': 'לא ניתן היה לטעון תגובות',
  'Favori': 'מועדף',
  'Listeye ekle': 'הוסף לרשימה',
  'İçerik paylaş': 'שתף תוכן',
  'Kapat': 'סגור',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'כל מה שתסמן כנצפה נאסף כאן.',
  'Henüz sohbetin yok': 'אין שיחות עדיין',
  'Bir profile girip mesaj gönderebilirsin.': 'פתח פרופיל ושלח הודעה.',
  'Listeyi sil': 'מחק רשימה',
  'Puan kaydedilemedi': 'לא ניתן היה לשמור את הדירוג',
  'Nerede İzlenir': 'איפה לצפות',
  'Abonelik': 'מנוי',
  'Kirala': 'השכרה',
  'Satın al': 'קנייה',
  'Hoş geldin!': 'ברוך הבא!',
  'İzlemek istediğin dizi ve filmleri seç': 'בחר סדרות וסרטים שאתה רוצה לראות',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'הבחירות שלך יתווספו לרשימת הצפייה',
  'Şimdilik atla': 'דלג בינתיים',
  'Devam et': 'המשך',
  '{} ekle': 'הוסף {}',
  'Şikayet et': 'דיווח',
  'Engelle': 'חסימה',
  'Engeli kaldır': 'ביטול חסימה',
  'Kullanıcı engellendi': 'המשתמש נחסם',
  'Engel kaldırıldı': 'החסימה הוסרה',
  'Şikayet sebebi': 'סיבת הדיווח',
  'Spam veya yanıltıcı': 'ספאם או מטעה',
  'Taciz veya nefret söylemi': 'הטרדה או דברי שנאה',
  'Uygunsuz / cinsel içerik': 'תוכן לא הולם / מיני',
  'Şiddet veya tehlikeli içerik': 'אלימות או תוכן מסוכן',
  'Telif hakkı ihlali': 'הפרת זכויות יוצרים',
  'Şikayetin alındı, teşekkürler': 'הדיווח שלך התקבל, תודה',
  'Hesabımı Sil': 'מחיקת החשבון שלי',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'החשבון שלך וכל הנתונים שלך (היסטוריה, דירוגים, תגובות, רשימות, הודעות) יימחקו לצמיתות. לא ניתן לבטל זאת.',
  'Şifreni gir': 'הזן את הסיסמה שלך',
  'Hesabımı kalıcı sil': 'מחק את החשבון שלי לצמיתות',
  'Sesli mesaj': 'הודעה קולית',
  'Ses gönderilemedi': 'לא ניתן היה לשלוח את ההודעה הקולית',
  'Kaydediliyor…': 'מקליט…',
  'Ses oynatılamadı': 'לא ניתן להפעיל את ההודעה הקולית',
  'Oynat': 'הפעל',
  'Duraklat': 'השהה',
  'Liste görünümü': 'תצוגת רשימה',
  'Takvim görünümü': 'תצוגת לוח שנה',
  'Önceki ay': 'חודש קודם',
  'Sonraki ay': 'חודש הבא',
  'Bu gün bölüm yok': 'אין פרקים ביום זה',
  'Gizlilik Politikası': 'מדיניות פרטיות',
  'Son güncelleme: {}': 'עדכון אחרון: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'מדיניות זו מסבירה אילו נתונים נאספים, כיצד הם משמשים ומהן הזכויות שלך כשאתה משתמש באפליקציית dizi.jpg ובאתר dizijpg.com.',
  'Topladığımız Veriler': 'אילו נתונים אנחנו אוספים',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'חשבון: כתובת אימייל, שם משתמש וסיסמה. הסיסמאות נשמרות כגיבוב בלתי הפיך; בחשבונות אורח אפשר להשתמש בלי אימייל.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'פרופיל: מידע שאתה בוחר להוסיף, כמו אווטאר, תמונת רקע, ביו ומדינה.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'שימוש: היסטוריית הצפייה, הדירוגים, התגובות, הרשימות, הריאקציות והמועדפים שלך.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'הודעות: הודעות הטקסט, התמונה והקול שלך נשמרות בשרתים שלנו. ההודעות אינן מוצפנות מקצה לקצה; הן נבדקות רק אם הוגש עליהן דיווח, לצורכי פיקוח.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'מדיה שהועלתה: תמונות, קובצי GIF, סרטונים והקלטות קול שאתה מוסיף לפרופיל, לתגובות ולהודעות.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'נתונים טכניים: כתובת IP, מיקום משוער (מדינה/עיר), פלטפורמת המכשיר, גרסת האפליקציה ויומני שגיאות. אלה נשמרים לצורכי אבטחה ותיקון תקלות.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'התראות: לצורך התראות פוש אנחנו שומרים את אסימון המכשיר ואת שפת ההעדפה שלך. אפשר לכבות התראות בכל עת בהגדרות המכשיר.',
  'Verileri Nasıl Kullanırız': 'איך אנחנו משתמשים בנתונים שלך',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'אנחנו משתמשים בנתונים שלך אך ורק כדי לספק את השירות, להגן על החשבון, לשלוח התראות, לתקן תקלות ולמנוע שימוש לרעה. אנחנו לא מוכרים את הנתונים שלך ולא משתפים אותם עם איש למטרות פרסום.',
  'Çerezler ve Yerel Depolama': 'עוגיות ואחסון מקומי',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'אנחנו משתמשים באחסון מקומי רק כדי לשמור אותך מחובר ולזכור העדפות כמו שפה וערכת נושא. אין עוגיות פרסום או מעקב.',
  'Üçüncü Taraf Hizmetler': 'שירותי צד שלישי',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'נתוני הסדרות והסרטים מגיעים מ-TMDB, ומידע על פלטפורמות סטרימינג מ-JustWatch. התראות פוש נשלחות דרך Google Firebase, ותעבורת האתר מוגנת על ידי Cloudflare. שירותים אלה כפופים למדיניות הפרטיות שלהם.',
  'Saklama ve Silme': 'שמירה ומחיקה',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'הנתונים שלך נשמרים כל עוד החשבון קיים. באמצעות "מחק את החשבון שלי" בהגדרות אפשר למחוק את החשבון לצמיתות; הנתונים נמחקים מיד, והעותקים בגיבויים בתוך 14 יום לכל היותר. יומני שגיאות נמחקים אוטומטית אחרי 30 יום.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'אפשר לייצא את הנתונים שלך כקובץ ZIP מההגדרות; הארכיון נשלח לכתובת האימייל שלך.',
  'Güvenlik': 'אבטחה',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'הנתונים עוברים בחיבורים מוצפנים (HTTPS) ונשמרים בשרתים עם גישה מוגבלת.',
  'Çocukların Gizliliği': 'פרטיות ילדים',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      '‏dizi.jpg אינו מיועד לילדים מתחת לגיל 13.',
  'Hakların': 'הזכויות שלך',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'לפי KVKK ו-GDPR יש לך זכות לגשת לנתונים שלך, לתקן אותם, למחוק אותם ולהעביר אותם. בנושאים אלה כתוב לנו: {}',
  'Değişiklikler': 'שינויים',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'אם המדיניות תשתנה, הגרסה החדשה תפורסם בעמוד זה והתאריך יעודכן.',
  'Kayıt olarak {} kabul etmiş olursun.': 'בהרשמה אתה מקבל את {}.',
  'Kullanıcılar': 'משתמשים',
  'Fotoğrafı değiştir': 'החלפת תמונה',
  'Yeniden konumlandır': 'מיקום מחדש',
  'Bir şeyler ters gitti': 'משהו השתבש',
  'Sosyal Bağlantılar': 'קישורים חברתיים',
  'Profilinde en fazla 3 bağlantı gösterilir.': 'בפרופיל מוצגים עד 3 קישורים.',
  'Platform seç': 'בחר פלטפורמה',
  'Kullanıcı adın': 'שם המשתמש שלך',
  'Ekle': 'הוספה',
  'Kaldır': 'הסרה',
  'Kopyalandı: {}': 'הועתק: {}',
  'Geçersiz kullanıcı adı': 'שם משתמש לא תקין',
  'Bağlantı ekle': 'הוספת קישור',
  'Spoiler olabilir — dokun ve gör': 'עשוי להכיל ספוילרים — הקש כדי לצפות',
  'Beğeni': 'לייקים',
  'Görüntülenme': 'צפיות',
  'Tam ekran': 'מסך מלא',
  'Sonuç bulunamadı': 'אין תוצאות',
  'Dizi ve Filmler': 'סדרות וסרטים',
  'Kişiler': 'אנשים',
  'Ana Sayfa': 'בית',
  'Paylaş': 'שיתוף',
  'Yanıtlar': 'תגובות',
  'Yaklaşan Bölümler': 'פרקים קרובים',
  'Yetişme Listesi': 'רשימת השלמות',
  'Şunu mu demek istedin': 'האם התכוונת ל',
  'Spoiler': 'ספוילר',
  'Spoiler — dokun ve gör': 'ספוילר — הקש כדי לראות',
  'uyum': 'התאמה',
  'Uyum': 'התאמה',
  '{} ortak dizi': '{} סדרות משותפות',
  '{} ortak film': '{} סרטים משותפים',
  'Bildirim Tercihleri': 'העדפות התראות',
  'Beğeniler': 'לייקים',
  'Yeni takipçiler': 'עוקבים חדשים',
  'Etiketlenmeler': 'אזכורים',
  'Yeniden izledim': 'נצפה שוב',
  '{}. kez izlendi': 'נצפה {} פעמים',
  'Gönderi bulunamadı': 'הפוסט לא נמצא',
};
