/// Otomatik üretilen çeviri haritası (pl).
const Map<String, String> cevirilerPl = {
  'Yorumun bu sayfada görünecek': 'Twój komentarz pojawi się na tej stronie',
  'Hepsini gördün, baştan gösteriyoruz':
      'To już wszystko, pokażemy Ci od początku',
  'Aktarılacak tanınan veri bulunamadı.':
      'Nie znaleziono rozpoznanych danych do importu.',
  'Arama': 'Szukaj',
  'Aramaya başla': 'Zacznij szukać',
  'Son aramalar': 'Ostatnie wyszukiwania',
  'Ayarlar': 'Ustawienia',
  'Bağla': 'Połącz',
  'Bio': 'Bio',
  'Bitirdim': 'Ukończone',
  'Bunları da Beğenebilirsin': 'To też może ci się spodobać',
  'Bölüm': 'Odcinek',
  'Bıraktım': 'Porzucone',
  'Dil': 'Język',
  'Dil ara...': 'Szukaj języka...',
  'Dizi': 'Serial',
  'Dizi ve filmlerini takip et': 'Śledź swoje seriale i filmy',
  'Dizi yorumu': 'Komentarz do serialu',
  'Dizi, film veya kişi ara...': 'Szukaj serialu, filmu lub osoby...',
  'Dosya en fazla 30MB olabilir': 'Plik może mieć maks. 30 MB',
  'Dosya en fazla {}MB olabilir': 'Plik może mieć maks. {} MB',
  'E-posta': 'E-mail',
  'E-posta veya kullanıcı adı': 'E-mail lub nazwa użytkownika',
  'En az 2 harf yaz': 'Wpisz co najmniej 2 litery',
  'Film': 'Film',
  'Film yorumu': 'Komentarz do filmu',
  'Fotoğraf / video ekle': 'Dodaj zdjęcie / wideo',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Zdjęcie lub GIF — awatar i okładka',
  'Giriş Yap': 'Zaloguj się',
  'Gönder': 'Wyślij',
  'Gönderildi': 'Wysłano',
  'Haftanın Dizileri': 'Seriale tygodnia',
  'Haftanın Filmleri': 'Filmy tygodnia',
  'Henüz izleme kaydın yok': 'Nie masz jeszcze historii oglądania',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Nie masz jeszcze list — utwórz w zakładce Profil.',
  'Henüz yorum yok.': 'Brak komentarzy.',
  'Hesabın bağlandı!': 'Konto połączone!',
  'Hesabın yok mu? Kayıt ol': 'Nie masz konta? Zarejestruj się',
  'Hesabını Bağla': 'Połącz konto',
  'Hesap Oluştur': 'Utwórz konto',
  'Kapak resmi ekle': 'Dodaj okładkę',
  'Kaydet': 'Zapisz',
  'Kendinden bahset...': 'Opowiedz coś o sobie...',
  'Keşfet': 'Odkrywaj',
  'Kimseyi takip etmiyor': 'Nie obserwuje nikogo',
  'Kişi ara': 'Szukaj osób',
  'Kişi yorumu': 'Komentarz o osobie',
  'Konuk Oyuncular': 'Aktorzy gościnni',
  'Kullanıcı adı (küçük harf)': 'Nazwa użytkownika (małe litery)',
  'Kullanıcı adı ara...': 'Szukaj nazwy użytkownika...',
  'Liste adı': 'Nazwa listy',
  'Listeye Ekle': 'Dodaj do listy',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Jesteś na koncie gościa — połącz je z e-mailem, nie strać swoich danych!',
  'Misafir olarak devam et': 'Kontynuuj jako gość',
  'Oluştur': 'Utwórz',
  'Oyuncular': 'Obsada',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil zapisany',
  'Puanla': 'Oceń',
  'Puanı Sil': 'Usuń ocenę',
  'Puanın': 'Twoja ocena',
  'Sezonlar': 'Sezony',
  'Sunucu hatası ({})': 'Błąd serwera ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Komentarz do S{}E{}',
  'Takibi Bırak': 'Przestań obserwować',
  'Takip': 'Obserwowani',
  'Takip Edilenler': 'Obserwowani',
  'Takip Et': 'Obserwuj',
  'Takipçi': 'Obserwujący',
  'Takipçi yok': 'Brak obserwujących',
  'Takipçiler': 'Obserwujący',
  'Takvim': 'Kalendarz',
  'Tamam': 'OK',
  'Tekrar Dene': 'Spróbuj ponownie',
  'Tekrar dene': 'Spróbuj jeszcze raz',
  'Toplam İzleme Süresi': 'Łączny czas przed ekranem',
  'Tüm Zamanların En İyileri': 'Najlepsze wszech czasów',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da TV Time / Letterboxd ZIP'ini içe aktar.":
      'Pobierz wszystkie swoje dane (obejrzane, oceny, komentarze, listy) jako ZIP zgodny z TV Time albo zaimportuj ZIP z TV Time / Letterboxd.',
  'Tümünü Kaldır': 'Usuń wszystkie',
  'Tümünü İzledim': 'Wszystkie obejrzane',
  'Türk Dizileri': 'Tureckie seriale',
  'Veri içe aktar (.zip)': 'Importuj dane (.zip)',
  'Verilerim': 'Moje dane',
  'Verilerimi dışa aktar (e-posta)': 'Eksportuj moje dane (e-mail)',
  'Verilerini dışa aktar': 'Eksportuj swoje dane',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Brak nadchodzących odcinków.\nUstaw serialowi status „Oglądam” na jego stronie i śledź nowe odcinki tutaj.',
  'Yapımları': 'Filmografia',
  'Yeni Diziler': 'Nowe seriale',
  'Yeni Liste': 'Nowa lista',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nowa nazwa użytkownika (opcjonalnie)',
  'Yorum': 'Komentarz',
  'Yorumunu yaz...': 'Napisz komentarz...',
  'Zaten hesabın var mı? Giriş yap': 'Masz już konto? Zaloguj się',
  'ort. {}': 'śr. {}',
  'takip': 'obserwowani',
  'takipçi': 'obserwujący',
  '{} / {} bölüm': '{} / {} odcinków',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} mies.',
  '{} ay~tekil': '{} mies.',
  '{} bölüm izlendi': '{} obejrzanych odcinków',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} dk~tekil': '{} min',
  '{} gün': '{} dni',
  '{} gün~tekil': '{} dzień',
  '{} içerik': '{} pozycji',
  '{} içerik · otomatik': '{} pozycji · automatyczna',
  '{} kayıt atlandı (eşleşmedi).': 'Pominięto {} wpisów (brak dopasowania).',
  '{} saat': '{} godz.',
  '{} saat~tekil': '{} godz.',
  '{} sezon': '{} sezonów',
  '{} yıl': '{} lat',
  '{} yıl~tekil': '{} rok',
  '{}. Bölüm': 'Odcinek {}',
  '{}. Sezon': 'Sezon {}',
  'Çıkış Yap': 'Wyloguj się',
  'Ülke': 'Kraj',
  'Ülke ara...': 'Szukaj kraju...',
  'Ülke seç': 'Wybierz kraj',
  'İlk yorumu sen yaz!': 'Napisz pierwszy komentarz!',
  'İncelemeler': 'Recenzje',
  'İncelemen (isteğe bağlı)': 'Twoja recenzja (opcjonalnie)',
  'İptal': 'Anuluj',
  'İzlediklerim': 'Historia oglądania',
  'İzledim': 'Obejrzane',
  'İzledin': 'Obejrzane',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Twoja historia oglądania i listy zostaną zachowane; teraz możesz logować się z każdego urządzenia.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Twoja historia oglądania, oceny, komentarze i listy zostaną wysłane jako ZIP na zapisany adres e-mail.',
  'İzleyeceğim': 'Obejrzę',
  'İzliyorum': 'Oglądam',
  'İçe aktarım tamamlandı': 'Import zakończony',
  'Şifre': 'Hasło',
  '• profil bilgisi': '• dane profilu',
  '• {} kitaplık kaydı': '• {} wpisów w bibliotece',
  '• {} favori': '• {} ulubionych',
  '• {} izleme kaydı': '• {} wpisów oglądania',
  '• {} liste': '• {} list',
  '• {} puan': '• {} ocen',
  '• {} yorum': '• {} komentarzy',
  '{}+ yapım': '{}+ produkcji',
  'Yorumlar': 'Komentarze',
  'Yorumlar ({})': 'Komentarze ({})',
  'Yorumları ({})': 'Komentarze ({})',
  'Listelerim': 'Moje listy',
  'Nereden izledin?': 'Gdzie to oglądano?',
  'Diziye git': 'Przejdź do serialu',
  'TV / Kanal': 'TV / Kanał',
  'Sinema': 'Kino',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Inne',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Twój feed jest pusty.\nGdy ktoś skomentuje seriale i filmy, które oglądasz, pojawi się tutaj.',
  'Listeleri ({})': 'Listy ({})',
  'Liste boş.': 'Ta lista jest pusta.',
  'Yanıtla': 'Odpowiedz',
  '@{} kullanıcısına yanıt veriyorsun': 'Odpowiadasz @{}',
  'İzlediğim Diziler ({})': 'Obejrzane seriale ({})',
  'İzlediğim Filmler ({})': 'Obejrzane filmy ({})',
  'Tümünü gör': 'Zobacz wszystko',
  'Bildirimler': 'Powiadomienia',
  'Henüz bildirim yok': 'Brak powiadomień',
  '@{} yorumuna yanıt verdi': 'Nowa odpowiedź na twój komentarz: @{}',
  '@{} yorumunu beğendi': '@{} lubi twój komentarz',
  '{} ve {} yorumunu beğendi': '{} i {} lubią twój komentarz',
  '{} ve {} kişi yorumunu beğendi': '{} i {} innych lubi twój komentarz',
  '@{} seni takip etti': '@{} obserwuje cię teraz',
  '@{} sana mesaj gönderdi': 'Nowa wiadomość od @{}',
  'Mesajlar': 'Wiadomości',
  'Mesaj': 'Wiadomość',
  'Mesaja eklenecek': 'Zostanie dodane do wiadomosci',
  'Mesajını yaz...': 'Napisz wiadomość...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Brak czatów.\nOtwórz profil i wyślij wiadomość.',
  'Şifreni mi unuttun?': 'Nie pamiętasz hasła?',
  'Şifreyi Sıfırla': 'Zresetuj hasło',
  'E-postadaki kod': 'Kod z e-maila',
  'Yeni şifre': 'Nowe hasło',
  'Sana Özel': 'Dla ciebie',
  '{} özetin': 'Twoje podsumowanie roku {}',
  'Yıllık izleme istatistiklerin': 'Twoje roczne statystyki',
  'Rozetler': 'Odznaki',
  'Verdiğin puan': 'Wystawione oceny',
  'Ortalama puanın': 'Twoja średnia ocena',
  'En çok izlediğin diziler': 'Twoje najczęściej oglądane seriale',
  'İlk Bölüm': 'Pierwszy odcinek',
  '100 Bölüm': '100 odcinków',
  '1000 Bölüm': '1000 odcinków',
  'İlk Film': 'Pierwszy film',
  '50 Film': '50 filmów',
  'İlk Yorum': 'Pierwszy komentarz',
  '25 Yorum': '25 komentarzy',
  '10 Puan': '10 ocen',
  'İlk Takipçi': 'Pierwszy obserwujący',
  '10 Dizi Bitirdin': '10 ukończonych seriali',
  'İzlemeyi Bıraktım': 'Już nie oglądam',
  'İzlediği Diziler ({})': 'Obejrzane seriale ({})',
  'İzlediği Filmler ({})': 'Obejrzane filmy ({})',
  '500 Bölüm': '500 odcinków',
  '5000 Bölüm': '5000 odcinków',
  '10 Film': '10 filmów',
  '100 Film': '100 filmów',
  '100 Yorum': '100 komentarzy',
  '50 Puan': '50 ocen',
  '100 Puan': '100 ocen',
  '10 Takipçi': '10 obserwujących',
  '50 Takipçi': '50 obserwujących',
  '25 Dizi Bitirdin': '25 ukończonych seriali',
  '50 Dizi Bitirdin': '50 ukończonych seriali',
  '10 Beğeni': '10 polubień',
  '100 Beğeni': '100 polubień',
  'yazıyor...': 'pisze...',
  'ses kaydediyor...': 'nagrywa audio...',
  'Profil düzeni': 'Układ profilu',
  'Konumla ve kırp': 'Ustaw i przytnij',
  'Listeye eklendi': 'Dodano do listy',
  'Listeyi sil?': 'Usunąć listę?',
  'Sil': 'Usuń',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Ten tytuł zostanie oznaczony jako nieobejrzany i usunięty z twoich list.',
  'Gelecek bölüm bugün': 'Następny odcinek dzisiaj',
  'Gelecek bölüm {} gün sonra': 'Następny odcinek za {} dni',
  'Tema': 'Motyw',
  'Sistem': 'Systemowy',
  'Koyu': 'Ciemny',
  'Açık': 'Jasny',
  'İzleyenler': 'Widzowie',
  'Yorumunu yaz... (@ ile etiketle)': 'Napisz komentarz... (@ aby oznaczyć)',
  '@{} bir yorumda seni etiketledi': 'Wzmianka od @{} w komentarzu',
  'Mesajı sil': 'Usuń wiadomość',
  'Mesaj silinemedi': 'Nie udało się usunąć wiadomości',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Link jest nieprawidłowy lub nie znaleziono strony',
  "Keşfet'e dön": 'Wróć do Odkrywaj',
  'Düzenle': 'Edytuj',
  'Mesajı düzenle': 'Edytuj wiadomość',
  'Yanıtlanıyor': 'Odpowiadanie',
  'düzenlendi': 'edytowano',
  'Fotoğraf': 'Zdjęcie',
  'Video': 'Wideo',
  'İçerik': 'Treść',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': 'ostatnio {} min temu',
  'son görülme {} saat önce': 'ostatnio {} godz temu',
  'son görülme {} gün önce': 'ostatnio {} dni temu',
  'Yorumlar yüklenemedi': 'Nie można załadować komentarzy',
  'Favori': 'Ulubione',
  'Listeye ekle': 'Dodaj do listy',
  'İçerik paylaş': 'Udostępnij',
  'Kapat': 'Zamknij',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Wszystko, co oznaczysz jako obejrzane, zbiera się tutaj.',
  'Henüz sohbetin yok': 'Brak rozmów',
  'Bir profile girip mesaj gönderebilirsin.':
      'Otwórz profil i wyślij wiadomość.',
  'Listeyi sil': 'Usuń listę',
  'Puan kaydedilemedi': 'Nie udało się zapisać oceny',
  'Nerede İzlenir': 'Gdzie oglądać',
  'Abonelik': 'Subskrypcja',
  'Kirala': 'Wypożycz',
  'Satın al': 'Kup',
  'Devam et': 'Kontynuuj',
  'Şikayet et': 'Zgłoś',
  'Engelle': 'Zablokuj',
  'Engeli kaldır': 'Odblokuj',
  'Kullanıcı engellendi': 'Użytkownik zablokowany',
  'Engel kaldırıldı': 'Blokada usunięta',
  'Şikayet sebebi': 'Powód zgłoszenia',
  'Spam veya yanıltıcı': 'Spam lub wprowadzanie w błąd',
  'Taciz veya nefret söylemi': 'Nękanie lub mowa nienawiści',
  'Uygunsuz / cinsel içerik': 'Nieodpowiednie / treści seksualne',
  'Şiddet veya tehlikeli içerik': 'Przemoc lub niebezpieczne treści',
  'Telif hakkı ihlali': 'Naruszenie praw autorskich',
  'Şikayetin alındı, teşekkürler':
      'Twoje zgłoszenie zostało przyjęte, dziękujemy',
  'Hesabımı Sil': 'Usuń moje konto',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Twoje konto i wszystkie dane (historia, oceny, komentarze, listy, wiadomości) zostaną trwale usunięte. Tego nie można cofnąć.',
  'Şifreni gir': 'Wpisz hasło',
  'Hesabımı kalıcı sil': 'Trwale usuń moje konto',
  'Sesli mesaj': 'Wiadomość głosowa',
  'Görüldü': 'Wyświetlono',
  'Gönderi': 'Post',
  'Ses gönderilemedi': 'Nie udało się wysłać wiadomości głosowej',
  'Kaydediliyor…': 'Nagrywanie…',
  'Ses oynatılamadı': 'Nie udało się odtworzyć dźwięku',
  'Oynat': 'Odtwórz',
  'Fragmanı oynat': 'Odtwórz zwiastun',
  'Altyazıyı aç': 'Włącz napisy',
  'Altyazıyı kapat': 'Wyłącz napisy',
  '10 saniye ileri': 'Do przodu o 10 sekund',
  '10 saniye geri': 'Do tyłu o 10 sekund',
  'Duraklat': 'Wstrzymaj',
  'Liste görünümü': 'Widok listy',
  'Takvim görünümü': 'Widok kalendarza',
  'Önceki ay': 'Poprzedni miesiąc',
  'Sonraki ay': 'Następny miesiąc',
  'Bu gün bölüm yok': 'Brak odcinków tego dnia',
  'Gizlilik Politikası': 'Polityka Prywatności',
  'Son güncelleme: {}': 'Ostatnia aktualizacja: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Ta polityka wyjaśnia, jakie dane są zbierane, jak są wykorzystywane i jakie masz prawa, gdy korzystasz z aplikacji dizi.jpg i strony dizijpg.com.',
  'Topladığımız Veriler': 'Jakie dane zbieramy',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Konto: adres e-mail, nazwa użytkownika i hasło. Hasła są przechowywane w postaci nieodwracalnego skrótu; z kont gościnnych można korzystać bez e-maila.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profil: informacje, które sam(a) dodajesz, np. awatar, zdjęcie w tle, bio i kraj.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Korzystanie: twoja historia oglądania, oceny, komentarze, listy, reakcje i ulubione.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Wiadomości: twoje wiadomości tekstowe, graficzne i głosowe są przechowywane na naszych serwerach. Wiadomości nie są szyfrowane end-to-end; są przeglądane wyłącznie po zgłoszeniu, w celach moderacji.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Przesłane media: zdjęcia, GIF-y, filmy i nagrania głosowe, które dodajesz do profilu, komentarzy i wiadomości.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Dane techniczne: adres IP, przybliżona lokalizacja (kraj/miasto), platforma urządzenia, wersja aplikacji i dzienniki błędów. Przechowujemy je dla bezpieczeństwa i usuwania usterek.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Statystyki użycia: rodzaj urządzenia, system operacyjny i przeglądarka, z których następuje wejście, są dodawane do dziennych liczników zbiorczych jako ogólne kategorie; sam identyfikator przeglądarki nie jest przechowywany, a tych liczb nie da się powiązać z konkretnymi osobami.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Powiadomienia: dla powiadomień push przechowujemy token twojego urządzenia i wybrany język. Powiadomienia możesz w każdej chwili wyłączyć w ustawieniach urządzenia.',
  'Verileri Nasıl Kullanırız': 'Jak wykorzystujemy twoje dane',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Twoje dane wykorzystujemy wyłącznie do świadczenia usługi, ochrony konta, wysyłania powiadomień, naprawiania błędów i zapobiegania nadużyciom. Nie sprzedajemy twoich danych i nie udostępniamy ich nikomu w celach reklamowych.',
  'Çerezler ve Yerel Depolama': 'Pliki cookie i pamięć lokalna',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Pamięci lokalnej używamy tylko po to, aby utrzymać cię zalogowanym i zapamiętać preferencje, takie jak język i motyw. Nie ma żadnych reklamowych ani śledzących plików cookie.',
  'Üçüncü Taraf Hizmetler': 'Usługi zewnętrzne',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Dane o serialach i filmach pochodzą z TMDB, informacje o platformach streamingowych z JustWatch. Powiadomienia push są dostarczane przez Google Firebase, a ruch na stronie chroni Cloudflare. Te usługi podlegają własnym politykom prywatności.',
  'Saklama ve Silme': 'Przechowywanie i usuwanie',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Twoje dane są przechowywane, dopóki istnieje twoje konto. Przez „Usuń moje konto" w ustawieniach możesz trwale usunąć konto; dane są kasowane od razu, a ich kopie w backupach najpóźniej w ciągu 14 dni. Dzienniki błędów są automatycznie usuwane po 30 dniach.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'Możesz wyeksportować swoje dane jako ZIP z ustawień; archiwum zostanie wysłane na twój adres e-mail.',
  'Güvenlik': 'Bezpieczeństwo',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Dane są przesyłane szyfrowanymi połączeniami (HTTPS) i przechowywane na serwerach z ograniczonym dostępem.',
  'Çocukların Gizliliği': 'Prywatność dzieci',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg nie jest przeznaczony dla dzieci poniżej 13 lat.',
  'Hakların': 'Twoje prawa',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Zgodnie z KVKK i GDPR masz prawo do dostępu do swoich danych, ich poprawiania, usunięcia i przeniesienia. W tych sprawach napisz do nas: {}',
  'Değişiklikler': 'Zmiany',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Jeśli ta polityka się zmieni, nowa wersja zostanie opublikowana na tej stronie, a data zaktualizowana.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Rejestrując się, akceptujesz {}.',
  'Kullanıcılar': 'Użytkownicy',
  'Fotoğrafı değiştir': 'Zmień zdjęcie',
  'Yeniden konumlandır': 'Wykadruj ponownie',
  'Bir şeyler ters gitti': 'Coś poszło nie tak',
  'Sosyal Bağlantılar': 'Linki społecznościowe',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'W profilu wyświetlane są maksymalnie 3 linki.',
  'Platform seç': 'Wybierz platformę',
  'Kullanıcı adın': 'Twoja nazwa użytkownika',
  'Ekle': 'Dodaj',
  'Kaldır': 'Usuń',
  'Kopyalandı: {}': 'Skopiowano: {}',
  'Geçersiz kullanıcı adı': 'Nieprawidłowa nazwa użytkownika',
  'Bağlantı ekle': 'Dodaj link',
  'Spoiler olabilir — dokun ve gör':
      'Może zawierać spoilery — dotknij, aby zobaczyć',
  'Beğeni': 'Polubienia',
  'beğeni': 'polubienia',
  'Beğen': 'Lubię to',
  'Görüntülenme': 'Wyświetlenia',
  'görüntülenme': 'wyświetlenia',
  'Tam ekran': 'Pełny ekran',
  'Arama başarısız': 'Wyszukiwanie nie powiodło się',
  'Sonuç bulunamadı': 'Brak wyników',
  'Dizi ve Filmler': 'Seriale i filmy',
  'Kişiler': 'Osoby',
  'Ana Sayfa': 'Główna',
  'Paylaş': 'Udostępnij',
  'Yanıtlar': 'Odpowiedzi',
  'Yaklaşan Bölümler': 'Nadchodzące odcinki',
  'Yetişme Listesi': 'Lista zaległości',
  'Şunu mu demek istedin': 'Czy chodziło ci o',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — dotknij, aby zobaczyć',
  'uyum': 'dopasowania',
  'Uyum': 'Dopasowanie',
  '{} ortak dizi': '{} wspólnych seriali',
  '{} ortak film': '{} wspólnych filmów',
  'Bildirim Tercihleri': 'Ustawienia powiadomień',
  'Beğeniler': 'Polubienia',
  'Yeni takipçiler': 'Nowi obserwujący',
  'Etiketlenmeler': 'Wzmianki',
  'Yeniden izledim': 'Obejrzano ponownie',
  '{}. kez izlendi': 'Obejrzano {} razy',
  'Gönderi bulunamadı': 'Nie znaleziono posta',
  'Gözat': 'Przeglądaj',
  'Diziler': 'Seriale',
  'Filmler': 'Filmy',
  'Tümü': 'Wszystko',
  'Farklı bir tür seç.': 'Wypróbuj inny gatunek.',
  'Gizlilik': 'Prywatność',
  'İzlediklerimi gizle': 'Ukryj, co oglądam',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Obejrzane seriale i filmy nie będą widoczne na twoim profilu',
  'Yorumlarımı gizle': 'Ukryj moje komentarze',
  'Profilinde yorumların görünmez':
      'Twoje komentarze nie będą widoczne na twoim profilu',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Pojedynczy serial lub film możesz ukryć chipem „Ukryj na moim profilu” na jego stronie.',
  'Geri Bildirim': 'Opinie',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Napisz swoją opinię i sugestie o aplikacji...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Dzięki! Twoja opinia została przyjęta.',
  'Profilimde gizle': 'Ukryj na moim profilu',
  'Yorumları': 'Komentarze',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Ten użytkownik nie obejrzał jeszcze niczego.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Ten użytkownik woli, by komentarze pozostały prywatne.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Dane: JustWatch',
  'Web Sitesi': 'Strona internetowa',
  'Diğer uygulamalar': 'Inne aplikacje',
  'Bağlantıyı kopyala': 'Kopiuj link',
  'Henüz kimseyi takip etmiyorsun.': 'Nikogo jeszcze nie obserwujesz.',
  'Çevir': 'Przetłumacz',
  'Çeviri şu an yapılamadı': 'Tłumaczenie jest teraz niedostępne',
  'Bağlantı açılamadı': 'Nie udało się otworzyć linku',
  'Orijinali göster': 'Pokaż oryginał',
  'Çeviriyi göster': 'Pokaż tłumaczenie',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'W tym miesiącu nie ma odcinków z ogłoszoną datą emisji. Daty zwykle podaje się kilka tygodni wcześniej i wtedy pojawią się tutaj.',
  'devamı': 'więcej',
  'Google ile devam et': 'Kontynuuj przez Google',
  'Google girişi başarısız': 'Logowanie przez Google nie powiodło się',
  'Veri tasarrufu': 'Oszczędzanie danych',
  'Wi-Fi ağında veri tasarrufu': 'Oszczędzanie danych przez Wi-Fi',
  'Mobil veride veri tasarrufu': 'Oszczędzanie danych w sieci komórkowej',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Gdy jest włączone, zdjęcia nie są pobierane z wyprzedzeniem — ładuje się tylko oglądany kadr.',
  'Çocuk güvenliği': 'Bezpieczeństwo dzieci',
  'Türk Filmleri': 'Filmy tureckie',
  'En Yüksek Puanlı Filmler': 'Najwyżej oceniane filmy',
  'En Yüksek Puanlı Diziler': 'Najwyżej oceniane seriale',
  'En Çok İzlenen Filmler': 'Najczęściej oglądane filmy',
  'Popüler Diziler': 'Popularne seriale',
  'En Çok Kazanan Filmler': 'Filmy z najwyższymi wpływami',
  'Kült Filmler': 'Filmy kultowe',
  'Yeni Filmler': 'Nowe filmy',
  'Yorum yap': 'Skomentuj',
  'Henüz yorum yok': 'Brak komentarzy',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Twoje komentarze o serialach i filmach zbierają się tutaj.',
  'GIF ekle': 'Dodaj GIF',
  'İlk yorumu sen yaz': 'Skomentuj jako pierwszy',
  'Video altyazıları': 'Napisy wideo',
  'Videolarda altyazı göster': 'Wyświetlaj napisy w filmach',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Zdanie wypowiedziane w filmie jest zapisane na ekranie. Tekst jest tłumaczeniem: angielski w mowie tureckiej, turecki w innych językach.',
  'Güncelleme gerekli': 'Wymagana aktualizacja',
  'Yeni sürüm var': 'Dostępna nowa wersja',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Zainstaluj nową wersję dizi.jpg, aby kontynuować.',
  'Güncelle': 'Aktualizuj',
  'Daha sonra': 'Później',
  'Takvim güncelleniyor': 'Aktualizowanie kalendarza',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Nie udało się zaktualizować kalendarza, pokazywana jest stara lista',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Niektóre seriale nie zostały wczytane, lista może być niepełna',
  'Yenile': 'Odśwież',
  'Devam etmek için giriş yap': 'Zaloguj się, aby kontynuować',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Darmowe konto wystarczy, aby oceniać, komentować i tworzyć swoją bibliotekę.',
  'Şimdi değil': 'Nie teraz',
  'Yorum yazmak için giriş yap': 'Zaloguj się, aby napisać komentarz',
  'Kişilere göndermek için giriş yap': 'Zaloguj się, aby wysłać do osób',
  'Beğenenler': 'Polubienia',
  'Henüz beğeni yok': 'Brak polubien',
  'Bu gönderiyi ilk beğenen sen ol': 'Polub ten post jako pierwsza osoba',
  'Bu gönderiye yanıt': 'Odpowiedz na ten post',
  'Spoiler içeren gönderi': 'Post ze spoilerami',
  'Görsel gönderi': 'Post ze zdjęciem',
  'Bu yorumu profilimde gizle': 'Ukryj ten komentarz na moim profilu',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Komentarz pozostaje na stronie serialu i filmu',
  'Bu yorumu sil': 'Usuń ten komentarz',
  'Yorum profilinde gizlendi': 'Komentarz ukryty na Twoim profilu',
  'Geri al': 'Cofnij',
  'Yorum silinsin mi?': 'Usunąć komentarz?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Ten komentarz zostanie trwale usunięty wszędzie. Nie można tego cofnąć.',
  'Yorum silindi': 'Komentarz usunięty',
  'Yorum profilinde tekrar görünüyor':
      'Komentarz znów jest widoczny na Twoim profilu',
  'Gizlenen yorumun yok': 'Brak ukrytych komentarzy',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Komentarze, które ukrywasz, przytrzymując post w zakładce Komentarze na Twoim profilu, zbierają się tutaj.',
  'Gizlenen yorumlar': 'Ukryte komentarze',
  'Gönderiye git': 'Przejdź do posta',
  'Tekrar göster': 'Pokaż ponownie',
  'Yanıtlarımı gizle': 'Ukryj moje odpowiedzi',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Odpowiedzi, które piszesz pod postami innych osób, widzisz tylko Ty',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Pokaż ponownie komentarze ukryte na twoim profilu',
  'Sıralama': 'Sortowanie',
  'Önerilen': 'Polecane',
  'Kronolojik': 'Chronologicznie',
  'Gelen mesaj istekleri': 'Otrzymane prośby o wiadomość',
  'Mesaj isteğin yok': 'Brak próśb o wiadomość',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Wiadomości od osób, których nie obserwujesz, pojawiają się tutaj.',
  'Çevrimiçi durumumu gizle': 'Ukryj mój status online',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Inni nie zobaczą Twojego statusu online ani ostatniej aktywności w wiadomościach',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Należy do naszych pierwszych użytkowników. Te opinie pomogły aplikacji stać się tym, czym jest dzisiaj.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Należysz do naszych pierwszych użytkowników. Twoje opinie pomogły aplikacji stać się tym, czym jest dzisiaj.',
  'İleri': 'Dalej',
  'Önceki': 'Poprzedni',
  'Sonraki': 'Następny',
  'Seçilen dosya okunamadı': 'Nie udało się odczytać wybranego pliku',
  'Video açılamadı': 'Nie udało się otworzyć filmu',
  'En fazla {} medya seçebilirsin': 'Możesz wybrać maksymalnie {} elementów',
  'Hiçbir medya yüklenemedi': 'Nie udało się przesłać żadnego pliku',
  'Seçimi kaldır': 'Usuń z wyboru',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'W jednym komentarzu możesz przesłać łącznie {} MB',
  '{} dosya okunamadı': 'Nie udało się odczytać plików: {}',
  '{} medya eklendi, {} yüklenemedi': 'Dodano: {}, nie przesłano: {}',
  'Kırp': 'Przytnij',
  'Çiz': 'Rysuj',
  'Metin': 'Tekst',
  'Emoji': 'Emoji',
  'Yinele': 'Ponów',
  'Daha fazla': 'Więcej',
  'Hazırlanıyor…': 'Przygotowywanie…',
  'Düzenlemeden çık?': 'Zakończyć edycję?',
  'Yaptığın değişiklikler kaybolacak.': 'Wprowadzone zmiany zostaną utracone.',
  'Çık': 'Zakończ',
  'Serbest çizim': 'Odręcznie',
  'Ok': 'Strzałka',
  'Dikdörtgen': 'Prostokąt',
  'Daire': 'Koło',
  'Bulanıklaştır': 'Rozmyj',
  'Pikselleştir': 'Pikselizuj',
  'Silgi': 'Gumka',
  'Çizgi kalınlığı': 'Grubość linii',
  'Saydamlık': 'Krycie',
  'Dolgu': 'Wypełnienie',
  'Renk': 'Kolor',
  'Döndür': 'Obróć',
  'Yansıt': 'Odbij',
  'Oran': 'Proporcje',
  'Sıfırla': 'Resetuj',
  'Serbest': 'Dowolny',
  'Metin yaz...': 'Wpisz tekst...',
  'Hizala': 'Wyrównaj',
  'Arka plan': 'Tło',
  'Emoji ara...': 'Szukaj emoji...',
  'Son kullanılanlar': 'Ostatnie',
  'İfadeler ve insanlar': 'Buźki i ludzie',
  'Hayvanlar ve doğa': 'Zwierzęta i natura',
  'Yiyecek ve içecek': 'Jedzenie i napoje',
  'Etkinlikler': 'Aktywności',
  'Seyahat ve yerler': 'Podróże i miejsca',
  'Nesneler': 'Obiekty',
  'Semboller': 'Symbole',
  'Bayraklar': 'Flagi',
  'Görseli düzenle': 'Edytuj zdjęcie',
  'Düzenlendi': 'Edytowane',
  'Düzenlenemedi': 'Nie udało się edytować',
  'Düzenlenen görsel çok büyük': 'Edytowany obraz jest za duży',
  'Videoyu düzenle': 'Edytuj wideo',
  'Sesi kapat': 'Wycisz',
  'Sesi aç': 'Włącz dźwięk',
  'İptal ediliyor…': 'Anulowanie…',
  'Bu biraz sürebilir': 'To może chwilę potrwać',
  'Video çok büyük': 'Wideo jest za duże',
  'Video hazırlanamadı': 'Nie udało się przygotować wideo',
  'Başlangıç': 'Początek',
  'Bitiş': 'Koniec',
  'En çok {} saniye seçebilirsin': 'Możesz wybrać maksymalnie {} sekund',
  'Dosya en fazla {} MB olabilir': 'Plik może mieć maksymalnie {} MB',
  'Medya ekle': 'Dodaj multimedia',
  'Seçili medya kalmadı': 'Nie wybrano multimediów',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Wybierz zdjęcie lub film, aby dodać je do komentarza.',
  'Medya seç': 'Wybierz multimedia',
  'Daha fazla ekle': 'Dodaj więcej',
  'Medya seçilemedi': 'Nie udało się wybrać multimediów',
  'Favori oyuncular': 'Ulubieni aktorzy',
  'Henüz favori oyuncun yok': 'Brak ulubionych aktorow',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Otworz strone aktora i dotknij serca w prawym gornym rogu, aby go tu dodac.',
  '{} yapımdan {} tanesini izledin': 'Obejrzano {} z {} tytułów',
  'izledin': 'obejrzane',
  'İzlemedin': 'Nieobejrzane',
  'Yapım bulunamadı': 'Nie znaleziono tytulow',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Ta osoba nie ma seriali ani filmow do wyswietlenia.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Twoja historia jest powiazana z kontem; ta lista jest tylko twoja.',
  'Hesabın kalıcı olarak askıya alındı':
      'Twoje konto zostało trwale zawieszone',
  'Hesabın geçici olarak askıya alındı':
      'Twoje konto zostało tymczasowo zawieszone',
  'Hesabın askıya alındı': 'Twoje konto jest zawieszone',
  'Sebep': 'Powód',
  'Kalan süre': 'Pozostały czas',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Po upływie tego czasu konto odblokuje się samo',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'W tym czasie możesz czytać, ale nie możesz publikować, komentować ani wysyłać wiadomości.',
  'Anladım': 'Rozumiem',
  'Ayrıntı': 'Szczegóły',
  '{} dakika': '{} minut',
  'birkaç saniye': 'kilka sekund',
  'Karara itiraz et': 'Odwołaj się od tej decyzji',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Wyjaśnij, dlaczego ta kara powinna zostać zniesiona',
  'İtirazını gönder': 'Wyślij odwołanie',
  'İtirazın incelemede': 'Twoje odwołanie jest rozpatrywane',
  'İtirazın reddedildi': 'Twoje odwołanie zostało odrzucone',
  'İtirazın alındı, inceleniyor':
      'Otrzymaliśmy Twoje odwołanie i jest rozpatrywane',
  'İtiraz en az 10 karakter olmalı':
      'Odwołanie musi mieć co najmniej 10 znaków',
  'Yükleniyor...': 'Wczytywanie...',
  'Bu bölüme puan ver': 'Oceń ten odcinek',
  '{} kişi puanladı': 'Oceniło {} osób',
  'Bölüm izlendi olarak işaretlendi': 'Odcinek oznaczony jako obejrzany',
  'Sesli ara': 'Połączenie głosowe',
  'Görüntülü ara': 'Połączenie wideo',
  'Çalıyor...': 'Dzwoni...',
  'Bağlanıyor...': 'Łączenie...',
  'Cevapla': 'Odbierz',
  'Reddet': 'Odrzuć',
  'Sessize al': 'Wycisz',
  'Hoparlör': 'Głośnik',
  'Kamerayı kapat': 'Wyłącz kamerę',
  'Kamerayı çevir': 'Przełącz kamerę',
  'Cevap yok': 'Brak odpowiedzi',
  'Arama reddedildi': 'Połączenie odrzucone',
  'Meşgul': 'Zajęte',
  'Bağlanılamadı': 'Nie udało się połączyć',
  'Arama iptal edildi': 'Połączenie anulowane',
  'Arama geçmişi': 'Historia połączeń',
  'Gelen arama': 'Połączenie przychodzące',
  'Giden arama': 'Połączenie wychodzące',
  'Cevapsız arama': 'Nieodebrane połączenie',
  'Arama şu anda kullanılamıyor': 'Połączenia są chwilowo niedostępne',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Połączenia wideo są teraz wyłączone, możesz zadzwonić głosowo',
  'Bu kullanıcıyı arayamazsın': 'Nie możesz zadzwonić do tego użytkownika',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Aby dzwonić, musicie obserwować się nawzajem',
  'Bu kullanıcı şu anda aranamıyor':
      'Do tego użytkownika nie można teraz zadzwonić',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Zbyt wiele nieodebranych połączeń. Spróbuj ponownie za {}',
  'Zaten bir aramadasın': 'Jesteś już w trakcie połączenia',
  'Arama için mikrofon izni gerekiyor':
      'Do dzwonienia potrzebne jest pozwolenie na mikrofon',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'Do połączeń wideo potrzebne są pozwolenia na kamerę i mikrofon',
  'Arama başlatılamadı': 'Nie udało się rozpocząć połączenia',
  'Kullanıcı bulunamadı': 'Nie znaleziono użytkownika',
  'Kendini arayamazsın': 'Nie możesz zadzwonić do siebie',
  'Arama artık geçerli değil': 'To połączenie nie jest już aktualne',
  'Bu aramanın tarafı değilsin': 'Nie jesteś uczestnikiem tego połączenia',
  'Arama bulunamadı': 'Nie znaleziono połączenia',
  'Çok fazla istek, biraz bekle': 'Zbyt wiele żądań, poczekaj chwilę',
  'Bağlantı koptu': 'Utracono połączenie',
  'Arama süre sınırına ulaştı': 'Rozmowa osiągnęła limit czasu',
  'Arama en fazla 4 saat sürebilir': 'Rozmowa może trwać maksymalnie 4 godziny',
  'Arama sona erdi': 'Połączenie zakończone',
  'Sesli arama': 'Połączenie głosowe',
  'Görüntülü arama': 'Połączenie wideo',
  'Gelen aramalar': 'Połączenia przychodzące',
  'Sesli ve görüntülü arama bildirimleri':
      'Powiadomienia o połączeniach głosowych i wideo',
  '{} sa': '{} godz.',
  'Sesli ve Görüntülü Aramalar': 'Połączenia głosowe i wideo',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Treść rozmów nigdy nie jest nagrywana. Dźwięk i obraz płyną między urządzeniami z szyfrowaniem end-to-end (DTLS-SRTP); nasze serwery nie mogą tego ruchu odszyfrować, podsłuchać ani przechować.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Przechowywane są wyłącznie metadane połączenia: z kim, w którą stronę, kiedy i jak długo trwało. Te zapisy są automatycznie usuwane po 90 dniach.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Jeśli bezpośrednie połączenie nie jest możliwe, dźwięk i obraz przechodzą w postaci zaszyfrowanej przez serwer przekaźnikowy (TURN). On również nie może odszyfrować ani nagrać treści.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Mikrofon jest używany tylko podczas rozmowy głosowej lub wideo, a kamera tylko podczas rozmowy wideo. Po zakończeniu rozmowy oba są wyłączane.',
  'Takip ettiğin {} kişi izledi': 'Obejrzało to {} osób, które obserwujesz',
  'Yorum yaz...': 'Napisz komentarz...',
  'Sıradaki bölüm': 'Następny odcinek',
  'Doğrulanmış testçi': 'Zweryfikowany tester',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Powiadomienia o obserwacjach, polubieniach, odpowiedziach, wiadomościach i oznaczeniach',
  'Sen': 'Ty',
  'Aradığınız kişide sesli arama devre dışı':
      'Połączenia głosowe są wyłączone u tej osoby',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Połączenia wideo są wyłączone u tej osoby',
  'Sesli aramalara izin ver': 'Zezwalaj na połączenia głosowe',
  'Görüntülü aramalara izin ver': 'Zezwalaj na połączenia wideo',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Gdy wyłączone, nikt nie może do ciebie zadzwonić; dzwoniący zobaczy powiadomienie',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Gdy wyłączone, nikt nie może zadzwonić do ciebie z wideo; dzwoniący zobaczy powiadomienie',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Połączenia głosowe są wyłączone. Możesz je włączyć w Ustawienia > Prywatność.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Połączenia wideo są wyłączone. Możesz je włączyć w Ustawienia > Prywatność.',
  'Sesli ve görüntülü arama': 'Połączenia głosowe i wideo',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Konta gościa nie mogą dzwonić. Załóż konto, aby z tego korzystać.',
  'Misafir hesaplar aranamaz': 'Do kont gościa nie można zadzwonić',
  'Puan dağılımı': 'Rozkład ocen',
  '{} yıldız': '{} gwiazdek',
  'Yakında gelecek': 'Wkrótce',
  '{} {} yayınlandı': '{} {} już dostępny',
  'Yeni bölüm yayınlandı': 'Nowy odcinek już dostępny',
  'Yeni bölümler': 'Nowe odcinki',
  'Geri': 'Wstecz',
  'Karşılamayı kapat': 'Zamknij wprowadzenie',
  'Adım {} / {}': 'Krok {} / {}',
  'Hadi başlayalım': 'Zaczynajmy',
  'Kaydet ve devam': 'Zapisz i kontynuuj',
  '{} tanesini ekle': 'Dodaj wybrane ({})',
  'Şimdilik geç': 'Pomiń na razie',
  'Doğum tarihin ne zaman?': 'Jaka jest twoja data urodzenia?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Pytamy o to, żeby pokazywać treści odpowiednie do wieku i złożyć ci życzenia urodzinowe.',
  'Gün': 'Dzień',
  'Ay': 'Miesiąc',
  'Yıl': 'Rok',
  'Doğum yılımı paylaşmak istemiyorum': 'Nie chcę udostępniać roku urodzenia',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'Data urodzenia nie jest pokazywana publicznie w twoim profilu. Służy tylko do treści odpowiednich do wieku i do życzeń urodzinowych.',
  'Ocak': 'Styczeń',
  'Şubat': 'Luty',
  'Mart': 'Marzec',
  'Nisan': 'Kwiecień',
  'Mayıs': 'Maj',
  'Haziran': 'Czerwiec',
  'Temmuz': 'Lipiec',
  'Ağustos': 'Sierpień',
  'Eylül': 'Wrzesień',
  'Ekim': 'Październik',
  'Kasım': 'Listopad',
  'Aralık': 'Grudzień',
  'Verilerini yanında getir': 'Zabierz swoje dane ze sobą',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Jeśli w innej aplikacji prowadzisz historię oglądania, możesz ją tu przenieść. Nie musisz zaczynać od zera.',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Wybierz wyeksportowany plik ZIP, a przeniesiemy twoją historię oglądania, oceny i listy.',
  'Aktarılıyor...': 'Importowanie...',
  'ZIP dosyası seç': 'Wybierz plik ZIP',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'Nie ma pośpiechu: możesz to zrobić później w Ustawienia > Moje dane.',
  'Hangi filmleri izledin?': 'Które filmy masz już obejrzane?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Oto najczęściej oglądane. To, w co stukniesz, dodamy do twojej historii oglądania.',
  'SERİ FİLMLER': 'SERIE FILMOWE',
  'Serilerden {} film eklendi': 'Dodano filmów z serii: {}',
  'Film listesi yüklenemedi': 'Nie udało się wczytać listy filmów',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Możesz pominąć ten krok i dodać wszystko później.',
  '{} film izlediklerine eklendi': 'Dodano filmów do historii oglądania: {}',
  'Film serileri': 'Serie filmowe',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Jeśli masz całą serię obejrzaną od początku do końca, dodaj ją jednym stuknięciem.',
  'Seri bulunamadı': 'Nie znaleziono serii',
  'Daha sonra tekrar deneyebilirsin.': 'Możesz spróbować ponownie później.',
  '{} film': 'Filmów: {}',
  'Eklendi': 'Dodano',
  'Tümünü izledim': 'Wszystkie obejrzane',
  'Peki ya diziler?': 'A seriale?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Zaznacz, co masz obejrzane – im więcej wybierzesz, tym trafniejsze podobne pokażemy.',
  'Dizi listesi yüklenemedi': 'Nie udało się wczytać listy seriali',
  'Seçtiklerine benzeyenler': 'Podobne do twoich wyborów',
  'Her şey hazır': 'Wszystko gotowe',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Zobacz szybko, co możesz robić w dizi.jpg.',
  'Profilini tamamla': 'Uzupełnij swój profil',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'W Ustawieniach dodasz bio, zdjęcie profilowe i okładkę.',
  'Takvimin seni bekliyor': 'Kalendarz na ciebie czeka',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'Nowe odcinki seriali, które oglądasz, trafiają do kalendarza, a my dajemy znać powiadomieniem.',
  'Puan ver, yorum yaz': 'Oceniaj i komentuj',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Oceniaj odcinek po odcinku, pisz komentarze pod zasłoną spoilerów i twórz listy.',
  'Verilerin sende kalır': 'Twoje dane zostają u ciebie',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Twoje dane są powiązane tylko z twoim kontem i nie są sprzedawane. W Ustawieniach pobierzesz je wszystkie albo całkowicie usuniesz konto.',
  'Engellenen kullanıcılar': 'Zablokowani użytkownicy',
  'Engellediğin kişileri gör, engeli kaldır':
      'Zobacz zablokowane osoby i cofnij blokadę',
  'Engellediğin kimse yok': 'Nie masz zablokowanych osób',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Użytkownika zablokujesz w menu z trzema kropkami na profilu danej osoby.',
  '@{} engellensin mi?': 'Zablokować @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'Nie zobaczycie nawzajem swoich postów, komentarzy ani profilu; nie przejdą też wiadomości i połączenia. Ewentualna obserwacja między wami zostaje zerwana i nie wróci, nawet gdy cofniesz blokadę.',
  'Bu kullanıcıyı engelledin': 'Ten użytkownik jest przez ciebie zablokowany',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Nie widzisz postów, komentarzy ani wiadomości tej osoby, a ta osoba nie widzi twoich.',
  '{} yeni bir yapımda: {}': '{} w nowej produkcji: {}',
  'Favori kişinden yeni yapım': 'Nowa produkcja ulubionej osoby',
  '{} için bildirimler': 'Powiadomienia: {}',
  'Tüm bildirimler': 'Wszystkie powiadomienia',
  'Uygulamada ve telefonda': 'W aplikacji i na telefonie',
  'Yalnız uygulama içi': 'Tylko w aplikacji',
  'Telefon bildirimi gönderilmez': 'Powiadomienia na telefon nie są wysyłane',
  'Kapalı': 'Wyłączone',
  'Bu kişi için bildirim yok': 'Brak powiadomień o tej osobie',
  'Favori kişilerin yeni yapımları': 'Nowe produkcje ulubionych osób',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Gdy wyłączone, nikt nie może do ciebie zadzwonić; dzwoniący zobaczy, że połączenia głosowe są "wyłączone"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Gdy wyłączone, nikt nie może zadzwonić do ciebie z wideo; dzwoniący zobaczy, że połączenia wideo są "wyłączone"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'Moja aktywność',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'Twoje polubienia, komentarze i seanse w jednym miejscu',
  'Henüz hareketin yok': 'Brak aktywności',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Wszystko, co lubisz, komentujesz i oglądasz, zbiera się tutaj.',
  'Bu süzgeçte hareket yok': 'Brak aktywności w tym filtrze',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Wybierz inny typ albo wróć do „Wszystko”.',
  'Hepsi': 'Wszystko',
  'Puan': 'Ocena',
  'Tepki': 'Reakcja',
  'İzleme': 'Seans',
  'Durum': 'Status',
  'Liste': 'Lista',
  'Yorum yaptın': 'Komentarz dodany',
  'Yorumu beğendin': 'Polubienie komentarza',
  '{} puan verdin': 'Ocena {}',
  'Tepki verdin': 'Reakcja',
  'Listene ekledin': 'Dodano do listy',
  'Takip etmeye başladın': 'Nowa obserwacja',
  '"İzleyeceğim" işaretledin': 'Oznaczono „Obejrzę”',
  '"İzliyorum" işaretledin': 'Oznaczono „Oglądam”',
  '"Bitirdim" işaretledin': 'Oznaczono „Ukończone”',
  '"Bıraktım" işaretledin': 'Oznaczono „Porzucone”',
  'Silinmiş içerik': 'Usunięta treść',
  'şimdi': 'teraz',
  '{} g': '{} dn.',
  '{} y': '{} l.',
  'İstatistiklerim': 'Moje statystyki',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Wyświetlenia i polubienia twoich postów',
  'Henüz gönderin yok': 'Nie masz jeszcze postów',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Gdy skomentujesz serial lub film, twoje wyświetlenia i polubienia zaczną się tu gromadzić.',
  'Tüm zamanlar': 'Od początku',
  'Son {} gün': 'Ostatnie {} dni',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'Historia wyświetleń jeszcze się nie zaczęła gromadzić; dane z pierwszego dnia pojawią się jutro.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'Historia wyświetleń gromadzi się od {} (jest {} dni danych), więc liczba za {} dni jest jeszcze niepełna.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'Historia polubień jest zapisywana od {}.',
  'Bu dönemde gösterilecek gönderi yok.':
      'Brak postów do pokazania w tym okresie.',
  'eksik veri': 'niepełne dane',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Obejrzane seriale i filmy, liczniki seansów, czas oglądania i karta dopasowania nie będą widoczne dla innych na twoim profilu',
  'Takipçi listemi gizle': 'Ukryj listę moich obserwujących',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Inni nie zobaczą, kto cię obserwuje; liczba obserwujących pozostaje widoczna',
  'Takip ettiklerimi gizle': 'Ukryj, kogo obserwuję',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Inni nie zobaczą, kogo obserwujesz; liczba obserwowanych pozostaje widoczna',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Ten użytkownik woli, by lista obserwujących pozostała prywatna.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Ten użytkownik woli, by lista obserwowanych pozostała prywatna.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Statystyki posta',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Statystyki są widoczne tylko dla twoich własnych postów.',
  'Erişim': 'Zasięg',
  'Görüntüleyen': 'Oglądający',
  'Kaç farklı kişi gördü (son {} gün)':
      'Ile różnych osób to zobaczyło (ostatnie {} dni)',
  'Paylaşım': 'Udostępnienia',
  'Bu gönderiden sonra': 'Po tym poście',
  'Profil ziyareti': 'Wizyty w profilu',
  'Yeni takip': 'Nowe obserwacje',
  'İçeriğe tıklama': 'Kliknięcia treści',
  'Spoiler perdesini açan': 'Odkryli spoiler',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Udostępnienia, wizyty w profilu, obserwacje, kliknięcia treści, podział na źródła i pomiary spoilera gromadzą się od {}; wcześniejsze nie były mierzone.',
  'Zamana yayılmış görüntülenme': 'Wyświetlenia w czasie',
  'Görüntülenme nereden geldi': 'Skąd pochodzą wyświetlenia',
  'Kimler gördü': 'Kto to zobaczył',
  'Günlük veri henüz birikmeye başlamadı.':
      'Dane dzienne jeszcze się nie zaczęły gromadzić.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'Wykres wymaga danych z co najmniej dwóch dni. Dane gromadzą się od {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'Najwięcej wyświetleń przyszło {}. dnia po opublikowaniu: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Dzienne wyświetlenia gromadzą się od {}; wcześniejsze nie były mierzone.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'Podział na źródła dopiero zaczął być mierzony; ten post nie otrzymał jeszcze oznaczonego wyświetlenia.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'Podział na obserwujących i odkrywanie dopiero zaczął być mierzony; nie ma jeszcze danych.',
  'Takip edenler': 'Obserwujący',
  'Keşiften gelenler': 'Z odkrywania',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Strona serialu/filmu',
  'Paylaşılan bağlantı': 'Udostępniony link',
  'yeni ölçülüyor': 'nowy pomiar',
  'Kendi ortalamanla aynı düzeyde': 'Na poziomie twojej średniej',
  'Kendi ortalamanın %{} üstünde': '{}% powyżej twojej średniej',
  'Kendi ortalamanın %{} altında': '{}% poniżej twojej średniej',
  'Etkileşim oranı': 'Wskaźnik zaangażowania',
  '(beğeni + yorum) ÷ görüntülenme': '(polubienia + komentarze) ÷ wyświetlenia',
  'Toplam görüntülenme': 'Łączne wyświetlenia',
  '{} ile {} arasında toplam {} görüntülenme':
      'Od {} do {}: łącznie {} wyświetleń',
  'İstatistikleri gör': 'Zobacz statystyki',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'Na potrzeby statystyk pokazywanych osobie, która opublikowała post, przechowywane są jako zbiorcze liczniki: ile razy i z jakiej powierzchni (kanał, profil, kanał pełnoekranowy, strona serialu/filmu, udostępniony link) post został wyświetlony, czy osoba oglądająca obserwowała w tym momencie autora posta, przejścia z posta do profilu lub treści, obserwacje rozpoczęte przez post, udostępnienia oraz odsłonięcia kurtyny spoilera. Te liczniki nie zawierają identyfikatora użytkownika, adresu IP ani znacznika czasu; nie da się sprawdzić, kto co zrobił.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'Aby móc policzyć, ile różnych osób zobaczyło post, dla każdej osoby oglądającej przechowywany jest przez 90 dni nieodwracalny skrót z kluczem (kryptograficzne skrócenie wyprowadzone z identyfikatora użytkownika lub adresu IP). Autorowi posta pokazywana jest wyłącznie liczba; tożsamość osób oglądających nie jest udostępniana w żadnych okolicznościach.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'Przenieść do „Obejrzę”?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'Tytuł jest albo do obejrzenia, albo obejrzany. Jeśli przejdziesz dalej, twoje oznaczenia obejrzenia w tym serialu ({}) zostaną usunięte.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'Tytuł jest albo do obejrzenia, albo obejrzany. Jeśli przejdziesz dalej, twoje oznaczenie „Obejrzane” przy tym filmie zostanie usunięte.',
  'Sil ve taşı': 'Usuń i przenieś',

  // --- Yapım ekibi + yapım firmaları ---
  'Yapım Ekibi': 'Ekipa',
  'Yaratıcı': 'Twórca',
  'Yönetmen': 'Reżyseria',
  'Senaryo': 'Scenariusz',
  'Yapımcı': 'Produkcja',
  'Yapım Firmaları': 'Firmy producenckie',
  'Yapım Firması': 'Firma producencka',
  'Firma bulunamadı': 'Nie znaleziono firmy',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'Ta firma nie ma tytułów tego rodzaju.',
  // --- İzleyici seviyesi ve unvanları (cinsiyetsiz) ---
  // --- Doğum günü kutlama kartı ---
  'Doğum günün kutlu olsun!': 'Wszystkiego najlepszego!',
  'İyi ki doğdun, iyi ki buradasın.':
      'Jak dobrze, że jesteś i że jesteś tutaj.',
  'Bugün {} yaşına girdin': 'Dziś kończysz {} lat',
  'Teşekkürler': 'Dziękuję',
  // --- İki adımlı doğrulama (2FA) ---
  'İki Adımlı Doğrulama': 'Weryfikacja dwuetapowa',
  'Girişte e-postana kod gönderilir':
      'Kod jest wysyłany na e-mail przy logowaniu',
  'Kod {} adresine gönderildi': 'Kod wysłany na {}',
  '6 haneli kod': '6-cyfrowy kod',
  'Doğrula': 'Zweryfikuj',
  'Yeniden gönder': 'Wyślij ponownie',
  'Vazgeç': 'Anuluj',
  'Yeni kod gönderildi': 'Wysłano nowy kod',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'Przy logowaniu przez Google kod nie jest wymagany; Google prowadzi własną weryfikację.',
  'Kapatmak için de kod gerekir.': 'Wyłączenie też wymaga kodu.',
  'E-postana erişemezsen hesabına giremezsin.':
      'Bez dostępu do e-maila logowanie nie będzie możliwe.',
  'İki adımlı doğrulama açıldı': 'Weryfikacja dwuetapowa włączona',
  'İki adımlı doğrulama kapatıldı': 'Weryfikacja dwuetapowa wyłączona',
  // --- Video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': 'Obejrzana część wideo',
  'Videoyu başlatanlar': 'zaczęło oglądać wideo',
  'videonun %{} noktasına ulaştı': 'dotarło do {}% wideo',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'Połowa widzów obejrzała co najmniej {}% wideo.',
  'Sonuna kadar izleyen: %{}': 'Dotarło do końca: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'Krzywa wymaga co najmniej {} wyświetleń; teraz jest ich {}.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'Krzywa uwzględnia wszystkie wyświetlenia ({}) i nie zależy od wybranego okresu.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'Czas oglądania jest mierzony od {}; starsze wyświetlenia nie są liczone.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      'Wyświetlenia: {}. Do połowy wideo dotarło {}%, do końca {}%.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',

  // --- md.42/26 istatistikler + seviye ---
  'Seviye {}': 'Poziom {}',
  'Sonraki seviyeye {} puan kaldı': 'Punkty do następnego poziomu: {}',
  'Gönderilerin': 'Twoje posty',
  '{} gönderi': 'Posty: {}',
  '{} gönderi · {} görüntülenme': 'Posty: {} · Wyświetlenia: {}',
  'önceki {} güne göre': 'wobec poprzednich {} dni',
  'önceki {} güne göre %{} arttı': 'wobec poprzednich {} dni wzrost o {}%',
  'önceki {} güne göre %{} azaldı': 'wobec poprzednich {} dni spadek o {}%',
  'önceki {} güne göre değişmedi': 'bez zmian wobec poprzednich {} dni',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'Dzienne wyświetlenia: najmniej {}, najwięcej {}',
  'Etkileşim oranı henüz ölçülemedi':
      'Wskaźnika zaangażowania nie da się jeszcze zmierzyć',
  'Oranlar': 'Wskaźniki',
  'Beğenme oranı': 'Wskaźnik polubień',
  'Yorum oranı': 'Wskaźnik komentarzy',
  'Paylaşma oranı': 'Wskaźnik udostępnień',
  'İçeriğe gitme oranı': 'Wskaźnik kliknięć treści',
  'Profile gitme oranı': 'Wskaźnik wizyt w profilu',
  'Ziyaretten takibe dönüşüm': 'Z wizyty w obserwację',
  'beğeni ÷ görüntülenme': 'polubienia ÷ wyświetlenia',
  'yorum ÷ görüntülenme': 'komentarze ÷ wyświetlenia',
  'paylaşım ÷ görüntülenme': 'udostępnienia ÷ wyświetlenia',
  'içeriğe tıklama ÷ görüntülenme': 'kliknięcia treści ÷ wyświetlenia',
  'profil ziyareti ÷ görüntülenme': 'wizyty w profilu ÷ wyświetlenia',
  'yeni takip ÷ profil ziyareti': 'nowe obserwacje ÷ wizyty w profilu',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'Wskaźniki wymagają co najmniej {} wyświetleń; teraz jest ich {}.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'Wskaźniki wynikają z sum posta z całego okresu; wybór dni poniżej ich nie zmienia.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'To są sumy posta z całego okresu (poza polami z własną notką); wybór dni poniżej zmienia tylko wykres.',
  'Ortalama izlenme: videonun %{} kadarı': 'Średnio obejrzano: {}% wideo',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'Średnia z 20 przedziałów krzywej utrzymania.',
  'Dizi, film, kişi veya şirket ara...':
      'Szukaj serialu, filmu, osoby lub firmy...',
  'Şirketler': 'Firmy',
  'Senarist': 'Scenarzysta',
  'Bölüm puanları': 'Oceny odcinków',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'Nie udało się wczytać ocen odcinków',
  'Giriş gerekli': 'Wymagane logowanie',
  'Geçersiz oturum': 'Nieprawidłowa sesja',
  'Oturum sonlandı, tekrar giriş yap': 'Sesja zakończona, zaloguj się ponownie',
  'Çok fazla istek; biraz sonra tekrar dene':
      'Za dużo żądań; spróbuj za chwilę',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'Na serwerze chwilowo brak miejsca, spróbuj za chwilę',
  'Devam eden yapımlar ({})': 'Trwające produkcje ({})',
  'Diziler ({})': 'Seriale ({})',
  'Filmler ({})': 'Filmy ({})',
  'Tüm yapımlar': 'Wszystkie produkcje',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'Twoja przestrzeń na media jest pełna; usuń stare pliki, aby zwolnić miejsce',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'E-mail/login lub hasło jest błędne',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'Ten e-mail lub login jest już zajęty',
  'Google doğrulaması başarısız': 'Weryfikacja Google nie powiodła się',
  'Kod geçersiz veya süresi dolmuş': 'Kod jest nieprawidłowy lub wygasł',
  'Bu kullanıcıyla mesajlaşamazsın': 'Nie możesz napisać do tego użytkownika',
  'Kendini takip edemezsin': 'Nie możesz obserwować samego siebie',
  'Bu kullanıcıyı takip edemezsin': 'Nie możesz obserwować tego użytkownika',
  'Kendini engelleyemezsin': 'Nie możesz zablokować samego siebie',
  'Yorum 1-1000 karakter olmalı': 'Komentarz musi mieć 1–1000 znaków',
  'Boş mesaj gönderilemez': 'Nie można wysłać pustej wiadomości',
  'Yorum bulunamadı': 'Nie znaleziono komentarza',
  'Şifre hatalı': 'Błędne hasło',
  'Şifre en az 6 karakter olmalı': 'Hasło musi mieć co najmniej 6 znaków',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'Można wgrać tylko GIF, PNG, JPEG lub WebP',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'Obsługiwane: GIF, PNG, JPEG, WebP, MP4, WebM, dźwięk',
  'Geçerli bir ZIP dosyası değil': 'To nie jest prawidłowy plik ZIP',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'Aby dostać dane mailem, najpierw powiąż adres',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'Masz już oznaczenia obejrzenia. Żeby dać „Zamierzam obejrzeć”, najpierw je usuń.',
  'Arama şu anda kapalı': 'Dzwonienie jest teraz wyłączone',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'Konta gościa nie włączą dzwonienia; załóż konto',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'Serwer się restartuje, spróbuj za chwilę',
  'Puan 1-10 arası olmalı': 'Ocena musi być między 1 a 10',
  'En fazla 10 medya eklenebilir': 'Można dodać najwyżej 10 plików',
  'Bu cihazdan yeni hesap açılamıyor':
      'Nie można założyć konta z tego urządzenia',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'Potrzebny jest poprawny e-mail, nazwa użytkownika i hasło min. 6 znaków',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'Potrzebny jest poprawny e-mail i hasło min. 6 znaków',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'Nazwa 3–20 znaków; małe litery, cyfry, kropki, myślniki i podkreślenia (nie na brzegach)',
  'Bu hesap zaten bağlı': 'To konto jest już połączone',
  'Hesap oluşturulamadı': 'Nie udało się utworzyć konta',
  'Misafir hesabı oluşturulamadı': 'Nie udało się utworzyć konta gościa',
  'Hesap bulunamadı': 'Nie znaleziono konta',
  'Bu hesapta e-posta yok': 'To konto nie ma e-maila',
  'İki adımlı doğrulama zaten bu durumda':
      'Weryfikacja dwuetapowa jest już w tym stanie',
  'Kod yanlış': 'Błędny kod',
  'Kodun süresi doldu': 'Kod wygasł',
  'Kullanıcının e-postası yok (misafir hesap)':
      'Ten użytkownik nie ma e-maila (konto gościa)',
  'Bio en fazla 300 karakter olabilir': 'Bio może mieć najwyżej 300 znaków',
  'Geçersiz ülke': 'Nieprawidłowy kraj',
  'Geçersiz sosyal bağlantı': 'Nieprawidłowy link społecznościowy',
  'Geçersiz doğum tarihi': 'Nieprawidłowa data urodzenia',
  'Liste adı gerekli': 'Nazwa listy jest wymagana',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'Nazwa najwyżej 60, opis 300 znaków',
  'Liste bulunamadı': 'Nie znaleziono listy',
  'Değiştirilecek tercih yok': 'Nie ma nic do aktualizacji',
  'İnceleme en fazla 2000 karakter olabilir':
      'Recenzja może mieć najwyżej 2000 znaków',
  'Önce içeriği "bitirdim" olarak işaretle':
      'Najpierw oznacz tytuł jako dokończony',
  'Önce kişiyi favorile': 'Najpierw dodaj osobę do ulubionych',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'Do komentarza odcinka potrzebne są sezon i odcinek',
  'Yanıtlanan yorum bulunamadı':
      'Nie znaleziono komentarza, na który odpowiadasz',
  'Geri bildirim 3-2000 karakter olmalı': 'Opinia musi mieć 3–2000 znaków',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'Tytuł i treść są wymagane (min. 2 znaki)',
  'Kendine mesaj gönderemezsin': 'Nie możesz wysłać wiadomości do siebie',
  'Mesaj en fazla 2000 karakter olabilir':
      'Wiadomość może mieć najwyżej 2000 znaków',
  'Mesaj 1-2000 karakter olmalı': 'Wiadomość musi mieć 1–2000 znaków',
  'Mesaj bulunamadı': 'Nie znaleziono wiadomości',
  'Mesaj bulunamadı veya düzenlenemez':
      'Nie znaleziono wiadomości albo nie można jej edytować',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'Możesz zgłosić tylko wiadomość wysłaną do ciebie',
  'Sebep gerekli': 'Powód jest wymagany',
  'İtiraz edilecek aktif bir ceza yok': 'Nie ma aktywnej kary do odwołania',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'Masz już odwołanie oczekujące na rozpatrzenie',
  'Bu ceza için itirazın zaten incelendi':
      'Twoje odwołanie od tej kary zostało już rozpatrzone',
  'Medya bağlantısının süresi dolmuş': 'Link do mediów wygasł',
  'Bu medya için imzalı bağlantı gerekli':
      'Do tego pliku potrzebny jest podpisany link',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'Usługa połączeń się restartuje; spróbuj za chwilę',
  'Puan göstergesi': 'Legenda ocen',
  'İzleme İstatistiklerim': 'Moje statystyki oglądania',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'Gdy oznaczysz odcinek lub film jako obejrzany, Twoje statystyki zaczną się tu gromadzić.',
  '{} sa {} dk': '{} godz. {} min',
  'Yaklaşık ekran süresi': 'Przybliżony czas przed ekranem',
  'İzleme serisi': 'Passa oglądania',
  'Şu anki seri': 'Obecna passa',
  'En uzun seri': 'Najdłuższa passa',
  'Haftanın günleri': 'Dni tygodnia',
  'En çok izlediklerin': 'Najczęściej oglądane',
  'Bu dönemde izleme yok': 'Brak oglądania w tym okresie',
  'Paz': 'nd',
  'Pzt': 'pn',
  'Sal': 'wt',
  'Çar': 'śr',
  'Per': 'czw',
  'Cum': 'pt',
  'Cmt': 'sob',
  '{} bölüm': '{} odcinków',
  '{} bölüm~tekil': '{} odcinek',
  '{} kez': '{} razy',
  '{} kez~tekil': '{} raz',
  'Son {} gün · günlük': 'Ostatnie {} dni · dziennie',
  'Son {} gün · haftalık': 'Ostatnie {} dni · tygodniowo',
  'Ekran süren, serin ve en çok izlediklerin':
      'Twój czas przed ekranem, passa i ulubione',
  'Daralt': 'Zwiń',
  'Listeyi düzenle': 'Edytuj listę',
  'Bitti': 'Gotowe',
  'Sırala': 'Zmień kolejność',
  'Herkese göster': 'Pokaż wszystkim',
  'Başkalarından gizle': 'Ukryj przed innymi',
  'Listeden kaldır': 'Usuń z listy',
  'Listeden kaldırılsın mı?': 'Usunąć z listy?',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'Ten tytuł zostanie usunięty z listy. Jeśli chcesz go tylko ukryć, użyj ikony oka.',
  'Sıralama kaydedilemedi': 'Nie udało się zapisać kolejności',
  'Değişiklik kaydedilemedi': 'Nie udało się zapisać zmiany',
  'Kaldırılamadı': 'Nie udało się usunąć',
  'Popülerlik': 'Popularność',
  'TMDB puanı': 'Ocena TMDB',
  'Yapım yılı': 'Rok produkcji',
  'dizi.jpg puanı': 'Ocena dizi.jpg',
  'İzlenme': 'Wyświetlenia',
  'Yorum sayısı': 'Liczba komentarzy',
  'Tüm raflara uygulanır': 'Dotyczy wszystkich półek',
  'En popüler {} yapım arasında sıralandı':
      'Posortowano wśród {} najpopularniejszych tytułów',
  'Altyazı görünümü': 'Wygląd napisów',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık':
      'Kolor, czcionka, rozmiar, krawędź i nieprzezroczystość',
  'Bu bir örnek altyazıdır.': 'To jest przykładowy napis.',
  'Ayar değiştikçe önizleme anında güncellenir.':
      'Podgląd aktualizuje się natychmiast po zmianie ustawień.',
  'Yazı biçimi': 'Styl tekstu',
  'Yazı rengi': 'Kolor tekstu',
  'Yazı opaklığı': 'Nieprzezroczystość tekstu',
  'Yazı tipi': 'Czcionka',
  'Yazı boyutu': 'Rozmiar tekstu',
  'Karakter ayrıtı': 'Krawędź znaków',
  'Ayrıt türü': 'Typ krawędzi',
  'Ayrıt rengi': 'Kolor krawędzi',
  'Yok': 'Brak',
  'Dış çizgi': 'Kontur',
  'Gölge': 'Cień',
  'Kabartma': 'Wypukła',
  'Oyma': 'Wklęsła',
  'Arka plan rengi': 'Kolor tła',
  'Arka plan opaklığı': 'Nieprzezroczystość tła',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      'Tło to wypełnienie tuż za tekstem, a okno to szersza powierzchnia za całym blokiem napisów.',
  'Pencere': 'Okno',
  'Pencere rengi': 'Kolor okna',
  'Pencere opaklığı': 'Nieprzezroczystość okna',
  'Altyazı görünümü sıfırlansın mı?': 'Zresetować wygląd napisów?',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      'Ustawienia koloru, czcionki, rozmiaru, krawędzi i nieprzezroczystości wrócą do wartości domyślnych.',
  'Altyazı görünümü varsayılana döndü':
      'Wygląd napisów przywrócony do domyślnego',
  '{} indiriliyor…': 'Pobieranie {}…',
  'Seçince indirilir': 'Pobierze się po wybraniu',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      'Nie udało się pobrać czcionki. Wyświetlanie czcionką domyślną.',
  'Beyaz': 'Biały',
  'Siyah': 'Czarny',
  'Kırmızı': 'Czerwony',
  'Yeşil': 'Zielony',
  'Mavi': 'Niebieski',
  'Sarı': 'Żółty',
  'Camgöbeği': 'Cyjan',
  'Macenta': 'Magenta',
  'Yapım bütçesi': 'Budżet produkcji',
  'Yapım bütçesi ve dünya çapında hasılat':
      'Budżet produkcji i wpływy na świecie',
  'Dizinin yayın durumu': 'Status emisji serialu',
  'Devam ediyor': 'W trakcie emisji',
  'Sona erdi': 'Zakończony',
  'İptal edildi': 'Anulowany',
  'Yapımda': 'W produkcji',
  'Planlandı': 'Zaplanowany',
  'Pilot bölüm': 'Odcinek pilotażowy',
  'Ad': 'Nazwa wyświetlana',
  'Adın': 'Twoja nazwa wyświetlana',
  'Kullanıcı adı': 'Nazwa użytkownika',
  'Kullanıcı adını değiştir': 'Zmień nazwę użytkownika',
  'Kullanıcı adını 90 günde bir değiştirebilirsin':
      'Nazwę użytkownika możesz zmieniać raz na 90 dni',
  'Değiştir': 'Zmień',
  '{} gün sonra değiştirebilirsin': 'Zmienisz ją za {} dni',
  'Kullanıcı adın: @{}': 'Twoja nazwa użytkownika: @{}',
  'Bu kullanıcı adı zaten alınmış': 'Ta nazwa użytkownika jest już zajęta',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış':
      'Ta nazwa użytkownika jest teraz zarezerwowana dla innego konta',
  'Bu zaten senin kullanıcı adın': 'To już jest twoja nazwa użytkownika',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      'Nazwa 3–20 znaków; małe litery, cyfry, kropki, myślniki i podkreślenia',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      'Widoczna w profilu nad nazwą użytkownika. Możesz zostawić puste.',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      'Po zmianie przez 90 dni nie zmienisz jej ponownie. Stara nazwa użytkownika zostaje zarezerwowana dla ciebie na 90 dni — możesz do niej wrócić, a nikt inny w tym czasie jej nie zajmie. Linki do starej nazwy nie otworzą już twojego profilu.',
  'Etkinliğim': 'Aktywność',
  'Tercihler': 'Preferencje',
  'Gizlilik ve güvenlik': 'Prywatność i bezpieczeństwo',
  'Destek': 'Pomoc',
  'Hesap': 'Konto',
  '{} dizileri': 'Seriale: {}',
  '{} filmleri': 'Filmy: {}',
  'En üste taşı': 'Przenieś na górę',
  'Sırayı sıfırla': 'Zresetuj kolejność',
  'Listede ara': 'Szukaj na liście',
  'Elle sıra sıfırlansın mı?': 'Zresetować ręczną kolejność?',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      'Lista wróci do domyślnej kolejności (ostatnio oznaczone na początku).',
  'Sıra sıfırlanamadı': 'Nie udało się zresetować kolejności',
  'Listenin en üstüne taşındı': 'Przeniesiono na górę listy',
  'Adlar yükleniyor…': 'Wczytywanie tytułów…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      'Przytrzymaj plakat, aby go przeciągnąć. Aby przenieść odległy tytuł do przodu, użyj „Przenieś na górę”.',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      'Przeciąganie jest wyłączone w wyszukiwaniu; przenieś do przodu przez „Przenieś na górę” ({} wyników).',
  'Görünüm': 'Widok',
  'En çok izlediğin filmler': 'Twoje najczęściej oglądane filmy',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      'Czasy są szacunkowe: odcinek liczy się jako ~{} min, film jako ~{} min',
  'Bu kullanıcı adı sistem tarafından ayrılmış':
      'Ta nazwa użytkownika jest zarezerwowana przez system',
  'Ekran süresi': 'Czas przed ekranem',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir":
      'Czasy to rzeczywiste długości odcinków i filmów z TMDB',
  'Tüm zamanlar: {} bölüm · {} film · {}':
      'Od zawsze: {} odcinków · {} filmów · {}',
  'Kabul et': 'Akceptuj',
  'Reddedilenler': 'Odrzucone',
  'İstekler': 'Prośby',
  'Reddettiğin istek yok': 'Brak odrzuconych próśb',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      'Odrzucone prośby zostają tutaj; możesz je w każdej chwili znów zaakceptować.',
  'Ne izlesem?': 'Co obejrzeć?',
  'Karışık': 'Mieszane',
  'Çarkı çevir': 'Zakręć kołem',
  'Tekrar çevir': 'Zakręć ponownie',
  'Bu türde içerik yok': 'Brak tytułów tego typu',
  'Bütçe': 'Budżet',
  'dizi.jpg AI özeti': 'Streszczenie AI dizi.jpg',
  'Daha fazlasını gör': 'Zobacz więcej',
  'Yıldız sistemi': 'System gwiazdek',
  '{} yıldız üzerinden': 'Na {} gwiazdek',
  'Önizleme': 'Podgląd',
  'dokununca açılır': 'otwiera się po dotknięciu',
  'Bir azalt': 'Zmniejsz o jeden',
  'Bir artır': 'Zwiększ o jeden',
  'Ölçek kaydedilemedi': 'Nie udało się zapisać skali',
  'Ölçeği değiştirmek puanlarını silmez; aynı puanlar yeni ölçekte gösterilir.':
      'Zmiana skali nie usuwa Twoich ocen; te same oceny są pokazywane w nowej skali.',
  'En aşağıya gönder': 'Przenieś na dół',
  'Listenin en altına taşındı': 'Przeniesiono na dół listy',
  'Oturumun sonlandı': 'Twoja sesja zakończyła się',
  'Bu hesabın oturumları kapatıldı ya da şifresi değişti. Devam etmek için tekrar giriş yap.':
      'To konto zostało wylogowane wszędzie lub zmieniono jego hasło. Zaloguj się ponownie, aby kontynuować.',
  'Son izleme: {}': 'Ostatnio oglądane: {}',
  '{} tarihinde izledin': 'Obejrzane {}',
  'Geri bildirimine yanıt verdik': 'Odpowiedzieliśmy na Twoją opinię',
  'Bu yanıt artık görüntülenemiyor.': 'Ta odpowiedź nie jest już dostępna.',
  'Gönderdiğin geri bildirim': 'Wysłana przez Ciebie opinia',
  'Dizi veya film seç (zorunlu)': 'Wybierz serial lub film (wymagane)',
  'Bölüm seç (isteğe bağlı)': 'Wybierz odcinek (opcjonalnie)',
  '{}. sezon {}. bölüm': 'Sezon {}, odcinek {}',
  'Ne düşünüyorsun?': 'Co o tym myślisz?',
  '{}/{} yükleniyor': 'Przesyłanie {}/{}',
  'Fotoğraf/video ekle': 'Dodaj zdjęcie lub wideo',
  'Paylaşmak için önce bir dizi veya film seç.':
      'Najpierw wybierz serial lub film, aby udostępnić.',
  'Sezon seç': 'Wybierz sezon',
  '{}. sezon': 'Sezon {}',
  'Bölüm seçme (yalnız dizi hakkında)': 'Bez odcinka (tylko o serialu)',
  'Sezonlar yüklenemedi.': 'Nie udało się wczytać sezonów.',
  'Bu dizide bölüm bilgisi yok.': 'Brak informacji o odcinkach tego serialu.',
  'Bu sezonda bölüm yok.': 'Brak odcinków w tym sezonie.',
  '{}. bölüm': 'Odcinek {}',
  'Dizi veya film ara...': 'Szukaj seriali i filmów...',
  'İzlediğin dizi ve film hakkında yorum paylaş':
      'Podziel się komentarzem o tym, co obejrzałeś',
  'Yapım seç (zorunlu)': 'Wybierz tytuł (wymagane)',
  'Paylaşmak için önce bir yapım seç.':
      'Najpierw wybierz tytuł, aby udostępnić.',
  'Kişi': 'Osoba',
  'Yapım firması': 'Firma produkcyjna',
  'Yapım ara...': 'Szukaj tytułów...',
  'Çarkı çevirmek için sürükle veya dokun':
      'Przeciągnij lub dotknij, aby zakręcić kołem',
  'Arşiv': 'Archiwum',
  'Yüklediklerim': 'Moje przesłane',
  'GIF ara...': 'Szukaj GIF-ów...',
  'GIF yükle': 'Prześlij GIF',
  'GIF etiketleri': 'Tagi GIF-a',
  'Virgülle ayır. Aramada bu kelimelerle bulunur.':
      'Oddziel przecinkami. Po tych słowach będzie wyszukiwany.',
  'gülme, alkış, şaşkın': 'śmiech, brawa, zaskoczenie',
  'Yükle': 'Prześlij',
  'Henüz GIF yok': 'Nie ma jeszcze GIF-ów',
  'Bu aramaya uyan GIF yok': 'Brak GIF-ów pasujących do tego wyszukiwania',
  'Arşiv yeni. İlk GIF i sen yükle — sen hemen kullanırsın, onaydan sonra herkes görür.':
      'Archiwum jest nowe. Prześlij pierwszy GIF — użyjesz go od razu, a wszyscy zobaczą go po zatwierdzeniu.',
  'GIF yüklendi. Sen hemen kullanabilirsin; herkese açık arşive onaydan sonra girer.':
      'GIF przesłany. Możesz go użyć od razu; do publicznego archiwum trafi po zatwierdzeniu.',
  'Onay bekliyor': 'Czeka na zatwierdzenie',
  'GIF listesi yüklenemedi': 'Nie udało się wczytać listy GIF-ów',
  'GIF yüklenemedi': 'Nie udało się przesłać GIF-a',
  'Bu GIF i şikayet et': 'Zgłoś ten GIF',
  'Uygunsuz içerik yöneticiye bildirilir ve arşivden kaldırılabilir.':
      'Nieodpowiednie treści są zgłaszane moderatorowi i mogą zostać usunięte z archiwum.',
  'Şikayetin alındı': 'Twoje zgłoszenie zostało przyjęte',
  'Şikayet gönderilemedi': 'Nie udało się wysłać zgłoszenia',
  'Dizinin kendisi': 'Sam serial',
  'Sezon ya da bölüm seçme': 'Bez sezonu ani odcinka',
  'Tüm {}. sezon': 'Cały sezon {}',
  'Bölüm seçme': 'Bez odcinka',
  'En fazla {} yapım ekleyebilirsin.': 'Możesz dodać maksymalnie {} tytułów.',
  'Bu zaten ekli.': 'Już dodano.',
  'Dizi, film, oyuncu ya da yönetmen etiketle — gönderin onların sayfasında da görünür.':
      'Oznacz serial, film, aktora lub reżysera — twój post pojawi się też na ich stronie.',
  'Etiket ekle': 'Dodaj tag',
  'Dizi, film, oyuncu ya da yönetmen etiketle':
      'Oznacz serial, film, aktora lub reżysera',
  'Gönderiden vazgeç': 'Odrzuć post',
  'Yazdıkların kaydedilmeyecek.': 'To, co napisałeś, nie zostanie zapisane.',
  'Yazmaya devam et': 'Pisz dalej',
  'Bulunamadı. Adın yazılışını değiştirip dene.':
      'Nie znaleziono. Spróbuj innej pisowni.',
  'Dizi, film, oyuncu, yönetmen ya da yapım firması ara.':
      'Szukaj serialu, filmu, aktora, reżysera lub studia.',
  'E-posta adresini değiştir': 'Zmień swój adres e-mail',
  'E-posta bağlı değil': 'Brak powiązanego adresu e-mail',
  'Geçerli bir e-posta adresi yaz': 'Wpisz prawidłowy adres e-mail',
  'Bu zaten hesabının e-posta adresi': 'To już jest adres e-mail twojego konta',
  'Kod gönder': 'Wyślij kod',
  'E-posta adresin güncellendi': 'Twój adres e-mail został zaktualizowany',
  'Bu e-posta başka bir hesapta kayıtlı':
      'Ten e-mail jest zarejestrowany na innym koncie',
  'Doğrulama kodu YENİ adrese gönderilir; adres ancak kodu girdikten sonra değişir. Şifre sıfırlama ve iki adımlı giriş kodları bundan sonra yeni adrese gider.':
      'Kod weryfikacyjny trafia na NOWY adres; adres zmienia się dopiero po wpisaniu kodu. Kody resetowania hasła i logowania dwuetapowego będą od tej pory przychodzić na nowy adres.',
  'Hesabındaki e-posta adresi geçerli değil, bu yüzden e-posta teslim edilemiyor. Doğru adresi bağlamak için destekle iletişime geç.':
      'Adres e-mail na twoim koncie jest nieprawidłowy, więc nie da się dostarczyć wiadomości. Skontaktuj się z pomocą, aby powiązać właściwy adres.',
  'Bu adrese kod gönderilemedi, adresi kontrol et':
      'Nie udało się wysłać kodu na ten adres, sprawdź go',
  'ya da': 'lub',
  'Google ile doğrula': 'Zweryfikuj przez Google',
  'Hesabını Google ile açtıysan şifren yoktur; kimliğini Google ile doğrula.':
      'Jeśli założyłeś konto przez Google, nie masz hasła; potwierdź tożsamość przez Google.',
  'Google doğrulaması bu hesapla eşleşmedi':
      'Weryfikacja Google nie pasuje do tego konta',
  'Bu hesap Google ile açıldı; doğrulamak için Google ile giriş yap':
      'To konto założono przez Google; zaloguj się przez Google, aby potwierdzić',
  // --- 31 Agu 2026: kitaplik paylasimi + reels ceviri + sohbet detayi ---
  'Bu liste gizli': 'Ta lista jest prywatna',
  'Bu kullanıcı izleme listelerini gizli tutmayı tercih ediyor.':
      'Ten użytkownik woli zachować swoje listy jako prywatne.',
  'Bu listede henüz içerik yok': 'W tej liście nie ma jeszcze tytułów',
  'Otomatik çeviri': 'Automatyczne tłumaczenie',
  'Otomatik çeviri açıldı': 'Automatyczne tłumaczenie włączone',
  'Otomatik çeviri kapatıldı': 'Automatyczne tłumaczenie wyłączone',
  'Sohbet sessize alındı': 'Czat wyciszony',
  'Sessize alma kaldırıldı': 'Wyciszenie wyłączone',
  'Tema özelleştir': 'Dostosuj motyw',
  'Sohbette ara': 'Szukaj w czacie',
  'Mesajlarda ara...': 'Szukaj w wiadomościach...',
  'Sonuç yok': 'Brak wyników',
  'Profili gör': 'Zobacz profil',
  'Medya ve dosyalar': 'Multimedia i pliki',
  'Henüz medya yok': 'Brak multimediów',
  'Varsayılan': 'Domyślny',
  'Mor': 'Fioletowy',
  'Pembe': 'Różowy',
  'Turuncu': 'Pomarańczowy',
  'Orijinal metin gösteriliyor': 'Wyświetlany jest oryginalny tekst',
  'İnternet bağlantısı yok': 'Brak połączenia z internetem',
  'Sunucu yanıt vermedi': 'Serwer nie odpowiedział',
  'Güvenli bağlantı kurulamadı':
      'Nie udało się nawiązać bezpiecznego połączenia',
  'Sunucudan beklenmeyen bir yanıt geldi': 'Nieoczekiwana odpowiedź serwera',
  'İzlediğim Diziler': 'Obejrzane seriale',
  'İzlediğim Filmler': 'Obejrzane filmy',
  'Satır görünümü': 'Widok listy',
  'Afiş görünümü': 'Widok plakatów',
  'Satır görünümünde sürükleme kapalı; "En üste taşı" ile öne al.':
      'W widoku listy przeciąganie jest wyłączone; przesuń na przód przez „Przenieś na górę”.',
  'Spoiler uyarısını göster': 'Pokazuj ostrzeżenie o spoilerach',
  'Kapalıyken spoiler işaretli gönderiler perdesiz, doğrudan gösterilir.':
      'Gdy wyłączone, wpisy oznaczone jako spoiler są pokazywane od razu, bez zasłony.',
  'Etiketler': 'Oznaczenia',
  'Galeri': 'Galeria',
  'Kamera': 'Aparat',
  'Dosya': 'Plik',
  'GIF': 'GIF',
  'Dizi / Film': 'Serial / Film',
  'Sesli mesaj (basılı tut)': 'Wiadomość głosowa (przytrzymaj)',
  'Kaydetmek için basılı tut': 'Przytrzymaj, aby nagrać',
  'Kaydırarak iptal': 'Przesuń, aby anulować',
  'Kamera açılamadı': 'Nie udało się otworzyć aparatu',
  'Dosya seçilemedi': 'Nie udało się wybrać pliku',
  'Dosya gönderilemedi': 'Nie udało się wysłać pliku',
  'En yeni mesaja in': 'Do najnowszej wiadomości',
  'Gönderilemedi · tekrar dene': 'Nie wysłano · ponów',
  'Dosya açılamadı': 'Nie udało się otworzyć pliku',
  'Temizle': 'Wyczyść',
  'Oyuncu': 'Aktor',
  'Böyle bir oda yok': 'Nie ma takiego pokoju',
  'Bu oda kapandı': 'Ten pokój został zamknięty',
  'Bu odaya girmek için davet ya da oda kodu gerekli':
      'Potrzebujesz zaproszenia albo kodu pokoju',
  'Oda dolu': 'Pokój jest pełny',
  'Bu odaya giremezsin': 'Nie możesz wejść do tego pokoju',
  'Bu odanın üyesi değilsin': 'Nie należysz do tego pokoju',
  'Bunu yalnız oda sahibi yapabilir': 'Może to zrobić tylko gospodarz pokoju',
  'Oda sahibi odayı kapatmalı': 'Pokój musi zamknąć gospodarz',
  'Zaten açık bir odan var': 'Masz już otwarty pokój',
  'Oda kodu 6 karakter olmalı': 'Kod pokoju musi mieć 6 znaków',
  'Misafir hesaplar izleme odası açamaz. Hesap oluşturursan açabilirsin.':
      'Konta gościa nie mogą otwierać pokoi. Załóż konto, aby otworzyć pokój.',
  'Yalnız karşılıklı takipleştiğin kişileri davet edebilirsin':
      'Możesz zapraszać tylko osoby, które też Cię obserwują',
  'Video en fazla {} GB olabilir': 'Film może mieć najwyżej {} GB',
  'Yalnızca MP4 veya WebM izlenebilir': 'Można odtwarzać tylko MP4 lub WebM',
  '{} odaya katıldı': '{} dołączył(a) do pokoju',
  '{} odadan ayrıldı': '{} opuścił(a) pokój',
  '{} bir video yükledi': '{} wgrał(a) film',
  'bitti': 'koniec',
  '{} sn': '{} s',
  'Birlikte izle': 'Oglądajcie razem',
  'Bir video yükle, arkadaşlarını davet et, aynı anda izleyin.':
      'Wgraj film, zaproś znajomych i oglądajcie w tym samym czasie.',
  'Henüz bir odan ya da davetin yok.':
      'Nie masz jeszcze pokoju ani zaproszenia.',
  'Odaya katıl': 'Dołącz do pokoju',
  'Oda kodu': 'Kod pokoju',
  'Katıl': 'Dołącz',
  'Oda oluştur': 'Utwórz pokój',
  'Odalar 12 saat sonra kendiliğinden kapanır ve video silinir.':
      'Pokoje zamykają się same po 12 godzinach, a film zostaje usunięty.',
  'Odam': 'Mój pokój',
  '@{} odası': 'Pokój @{}',
  'Seni davet etti': 'Zaprosił(a) Cię',
  '{} kişi': '{} osób',
  'Video yok': 'Brak filmu',
  '{} kaldı': 'Zostało {}',
  'Davet': 'Zaproszenie',
  '@{} davet edildi': 'Zaproszono @{}',
  'Oda kodu kopyalandı': 'Skopiowano kod pokoju',
  'Odayı kapat': 'Zamknij pokój',
  'Odadan ayrıl': 'Opuść pokój',
  'Oda kapanacak ve video silinecek. Bu geri alınamaz.':
      'Pokój zostanie zamknięty, a film usunięty. Tego nie da się cofnąć.',
  'Odadan çıkacaksın. Kodla ya da davetle geri dönebilirsin.':
      'Opuścisz pokój. Możesz wrócić z kodem albo zaproszeniem.',
  'Ayrıl': 'Opuść',
  'İzleme odası': 'Pokój oglądania',
  'Odalar 12 saat sonra kendiliğinden kapanır.':
      'Pokoje zamykają się same po 12 godzinach.',
  '{} kişi · {} kaldı': '{} osób · zostało {}',
  'Davet et': 'Zaproś',
  'Bir video yükle, izlemeye başlayın': 'Wgraj film i zacznijcie oglądać',
  'Oda sahibi henüz video yüklemedi': 'Gospodarz nie wgrał jeszcze filmu',
  'Video yükle': 'Wgraj film',
  'En fazla {} GB · MP4 veya WebM': 'Do {} GB · MP4 lub WebM',
  'Kaldığı yerden yükleniyor · {}/{} MB': 'Wznawianie wysyłania · {}/{} MB',
  'Yükleniyor · {}/{} MB': 'Wysyłanie · {}/{} MB',
  'Videoyu değiştir': 'Zmień film',
  'Oda sahibiyle eşleniyor': 'Synchronizacja z gospodarzem',
  'Sohbet boş': 'Czat jest pusty',
  'İzlerken buradan konuşabilirsiniz.':
      'Tutaj możecie rozmawiać podczas oglądania.',
  'oda sahibi': 'gospodarz',
  'davet bekliyor': 'oczekuje na zaproszenie',
  'çevrimdışı': 'offline',
  'Mesaj yaz...': 'Napisz wiadomość...',
  'Oda kodunu kopyala': 'Kopiuj kod pokoju',
  'Oda kodu {} — kopyala': 'Kod pokoju {} — kopiuj',
  'Arkadaşını davet et': 'Zaproś znajomego',
  'kullanıcı adı': 'nazwa użytkownika',
  'Yalnız karşılıklı takipleştiğin kişileri davet edebilirsin.':
      'Możesz zapraszać tylko osoby, które też Cię obserwują.',
  'Oda açılamadı': 'Nie udało się otworzyć pokoju',
  'Tam ekrandan çık': 'Zamknij pełny ekran',
  'Sohbeti gizle': 'Ukryj czat',
  'Sohbeti göster': 'Pokaż czat',
  'Fragman': 'Zwiastun',
  'Tekrar oynat': 'Odtwórz ponownie',
  '@{} seni izleme odasına davet etti':
      '@{} zaprosił(a) Cię do pokoju wspólnego oglądania',
  '{} · {} davet bekliyor': '{} · oczekujące zaproszenia: {}',
  'Sırada bekliyor': 'W kolejce',
  'Hazırlanıyor · %{}': 'Przygotowywanie · {}%',
  'Video, her cihazda oynayacak biçime çevriliyor.':
      'Wideo jest konwertowane, żeby odtwarzało się na każdym urządzeniu.',
  'Başka video yükle': 'Wgraj inne wideo',
  'Bu videoyu tarayıcı oynatamıyor. Telefondan aç.':
      'Twoja przeglądarka nie odtworzy tego wideo. Otwórz je na telefonie.',
  'Bu videoyu iPhone oynatamıyor.': 'iPhone nie odtworzy tego wideo.',
  'Tarayıcı için hazırla': 'Przygotuj dla przeglądarki',
  'Başlat': 'Zacznij',
  'Bu videonun görüntü biçimi oynatılamıyor. MP4 (H.264) olarak çevirip yeniden dene.':
      'Formatu tego wideo nie da się odtworzyć. Przekonwertuj je na MP4 (H.264) i spróbuj ponownie.',
  'Bu dosyada görüntü yok': 'W tym pliku nie ma wideo',
  'Video okunamadı, dosya bozuk olabilir':
      'Nie udało się odczytać wideo, plik może być uszkodzony',
  'Sunucuda yer kalmadı, biraz sonra tekrar dene':
      'Na serwerze skończyło się miejsce, spróbuj za chwilę',
  'Video bulunamadı': 'Nie znaleziono wideo',
  'Yetkili': 'Moderator',
  'Kontrolü ver': 'Przekaż sterowanie',
  'Kontrolü al': 'Odbierz sterowanie',
  'Videoyu oynatıp durdurabilir ve değiştirebilir.':
      'Może odtwarzać, wstrzymywać i zmieniać film.',
  'Artık videoyu yönetemez.': 'Nie może już zarządzać filmem.',
  'Bunu oda sahibi ve yetki verdiği kişiler yapabilir':
      'Może to zrobić tylko gospodarz i osoby, którym ufa',
  'Kendi yetkini değiştiremezsin': 'Nie możesz zmienić własnych uprawnień',
  'Geçersiz yetki': 'Nieprawidłowe uprawnienie',
  '{} artık videoyu yönetebilir': '{} może teraz zarządzać filmem',
  '{} kontrolü bıraktı': '{} nie ma już sterowania',
  'Kişi ara...': 'Szukaj osób...',
  'Karşılıklı takipleştiğin kimse yok':
      'Nikt Cię jeszcze nie obserwuje wzajemnie',
  'Böyle bir kullanıcı yok': 'Nie ma takiego użytkownika',
  'Oda kodunu paylaşarak da davet edebilirsin.':
      'Możesz też zaprosić, udostępniając kod pokoju.',
  'Karşılıklı takipleşmiyorsunuz': 'Nie obserwujecie się wzajemnie',
  'Odada': 'W pokoju',
  'Davet edildi': 'Zaproszono',
  'Aşk': 'Miłość',
  'Arkadaşlar': 'Przyjaciele',
  'Gece': 'Noc',
  'Okyanus': 'Ocean',
  'Gün batımı': 'Zachód słońca',
  'Orman': 'Las',
  'Neon': 'Neon',
  'Temalar': 'Motywy',
  'Renkler': 'Kolory',
  'Sık kullanılanlar': 'Często używane',
  'Klavye': 'Klawiatura',
};
