/// Otomatik üretilen çeviri haritası (es).
const Map<String, String> cevirilerEs = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Lo has visto todo, te lo mostramos desde el principio.',
  'Aktarılacak tanınan veri bulunamadı.':
      'No se encontraron datos reconocidos para importar.',
  'Arama': 'Búsqueda',
  'Aramaya başla': 'Empieza a buscar',
  'Son aramalar': 'Búsquedas recientes',
  'Ayarlar': 'Ajustes',
  'Bağla': 'Vincular',
  'Bio': 'Bio',
  'Bitirdim': 'Terminada',
  'Bunları da Beğenebilirsin': 'También te pueden gustar',
  'Bölüm': 'Episodio',
  'Bıraktım': 'Abandonada',
  'Dil': 'Idioma',
  'Dil ara...': 'Buscar idioma...',
  'Dizi': 'Serie',
  'Dizi ve filmlerini takip et': 'Sigue tus series y películas',
  'Dizi yorumu': 'Comentario de serie',
  'Dizi, film veya kişi ara...': 'Busca series, películas o personas...',
  'Dosya en fazla 30MB olabilir': 'El archivo no puede superar los 30MB',
  'Dosya en fazla {}MB olabilir': 'El archivo no puede superar los {}MB',
  'E-posta': 'Correo electrónico',
  'E-posta veya kullanıcı adı': 'Correo o nombre de usuario',
  'En az 2 harf yaz': 'Escribe al menos 2 letras',
  'Film': 'Película',
  'Film yorumu': 'Comentario de película',
  'Fotoğraf / video ekle': 'Añadir foto / vídeo',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto o GIF — imagen de perfil y portada',
  'Giriş Yap': 'Iniciar sesión',
  'Gönder': 'Enviar',
  'Gönderildi': 'Enviado',
  'Haftanın Dizileri': 'Series de la semana',
  'Haftanın Filmleri': 'Películas de la semana',
  'Henüz izleme kaydın yok': 'Aún no tienes historial de visionado',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Aún no tienes listas — crea una desde la pestaña Perfil.',
  'Henüz yorum yok.': 'Aún no hay comentarios.',
  'Hesabın bağlandı!': '¡Tu cuenta está vinculada!',
  'Hesabın yok mu? Kayıt ol': '¿No tienes cuenta? Regístrate',
  'Hesabını Bağla': 'Vincula tu cuenta',
  'Hesap Oluştur': 'Crear cuenta',
  'Kapak resmi ekle': 'Añadir portada',
  'Kaydet': 'Guardar',
  'Kendinden bahset...': 'Cuéntanos sobre ti...',
  'Keşfet': 'Descubrir',
  'Kimseyi takip etmiyor': 'No sigue a nadie',
  'Kişi ara': 'Buscar personas',
  'Kişi yorumu': 'Comentario de persona',
  'Konuk Oyuncular': 'Estrellas invitadas',
  'Kullanıcı adı (küçük harf)': 'Nombre de usuario (minúsculas)',
  'Kullanıcı adı ara...': 'Buscar nombre de usuario...',
  'Liste adı': 'Nombre de la lista',
  'Listeye Ekle': 'Añadir a lista',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Estás en una cuenta de invitado — vincula tu correo, ¡no pierdas tus datos!',
  'Misafir olarak devam et': 'Continuar como invitado',
  'Oluştur': 'Crear',
  'Oyuncular': 'Reparto',
  'Profil': 'Perfil',
  'Profil kaydedildi': 'Perfil guardado',
  'Puanla': 'Puntuar',
  'Puanı Sil': 'Eliminar puntuación',
  'Puanın': 'Tu puntuación',
  'Sezonlar': 'Temporadas',
  'Sunucu hatası ({})': 'Error del servidor ({})',
  'S{} · {}. Bölüm': 'T{} · E{}',
  'S{}B{} yorumu': 'Comentario de T{}E{}',
  'Takibi Bırak': 'Dejar de seguir',
  'Takip': 'Siguiendo',
  'Takip Edilenler': 'Seguidos',
  'Takip Et': 'Seguir',
  'Takipçi': 'Seguidores',
  'Takipçi yok': 'Sin seguidores',
  'Takipçiler': 'Seguidores',
  'Takvim': 'Calendario',
  'Tamam': 'Aceptar',
  'Tekrar Dene': 'Reintentar',
  'Tekrar dene': 'Inténtalo de nuevo',
  'Toplam İzleme Süresi': 'Tiempo total de pantalla',
  'Tüm Zamanların En İyileri': 'Los mejores de todos los tiempos',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'Exporta todos tus datos (visionados, puntuaciones, comentarios, listas) como un ZIP compatible con TV Time o importa un ZIP de otra app.',
  'Tümünü Kaldır': 'Quitar todo',
  'Tümünü İzledim': 'Lo he visto todo',
  'Türk Dizileri': 'Series turcas',
  'Veri içe aktar (.zip)': 'Importar datos (.zip)',
  'Verilerim': 'Mis datos',
  'Verilerimi dışa aktar (e-posta)': 'Exportar mis datos (correo)',
  'Verilerini dışa aktar': 'Exporta tus datos',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'No hay episodios próximos.\nPon una serie en "Viendo" desde su ficha y sigue aquí los nuevos episodios.',
  'Yapımları': 'Filmografía',
  'Yeni Diziler': 'Series nuevas',
  'Yeni Liste': 'Nueva lista',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nuevo nombre de usuario (opcional)',
  'Yorum': 'Comentario',
  'Yorumunu yaz...': 'Escribe tu comentario...',
  'Zaten hesabın var mı? Giriş yap': '¿Ya tienes cuenta? Inicia sesión',
  'ort. {}': 'med. {}',
  'takip': 'siguiendo',
  'takipçi': 'seguidores',
  '{} / {} bölüm': '{} / {} episodios',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} meses',
  '{} ay~tekil': '{} mes',
  '{} bölüm izlendi': '{} episodios vistos',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} dk~tekil': '{} min',
  '{} gün': '{} días',
  '{} gün~tekil': '{} día',
  '{} içerik': '{} títulos',
  '{} içerik · otomatik': '{} títulos · automática',
  '{} kayıt atlandı (eşleşmedi).': '{} registros omitidos (sin coincidencia).',
  '{} saat': '{} horas',
  '{} saat~tekil': '{} hora',
  '{} sezon': '{} temporadas',
  '{} yıl': '{} años',
  '{} yıl~tekil': '{} año',
  '{}. Bölüm': 'Episodio {}',
  '{}. Sezon': 'Temporada {}',
  'Çıkış Yap': 'Cerrar sesión',
  'Ülke': 'País',
  'Ülke ara...': 'Buscar país...',
  'Ülke seç': 'Elige un país',
  'İlk yorumu sen yaz!': '¡Escribe el primer comentario!',
  'İncelemeler': 'Reseñas',
  'İncelemen (isteğe bağlı)': 'Tu reseña (opcional)',
  'İptal': 'Cancelar',
  'İzlediklerim': 'Mi historial',
  'İzledim': 'Visto',
  'İzledin': 'Has visto',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Tu historial y tus listas se conservan; ahora puedes entrar desde cualquier dispositivo.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Tu historial, puntuaciones, comentarios y listas se enviarán como ZIP a tu correo registrado.',
  'İzleyeceğim': 'Pendiente',
  'İzliyorum': 'Viendo',
  'İçe aktarım tamamlandı': 'Importación completada',
  'Şifre': 'Contraseña',
  '• profil bilgisi': '• información de perfil',
  '• {} dizi durumu': '• {} estados de series',
  '• {} izleme kaydı': '• {} registros de visionado',
  '• {} liste': '• {} listas',
  '• {} puan': '• {} puntuaciones',
  '• {} yorum': '• {} comentarios',
  '{}+ yapım': '{}+ títulos',
  'Yorumlar': 'Comentarios',
  'Yorumlar ({})': 'Comentarios ({})',
  'Yorumları ({})': 'Comentarios ({})',
  'Listelerim': 'Mis listas',
  'Nereden izledin?': '¿Dónde lo viste?',
  'Diziye git': 'Ir a la serie',
  'TV / Kanal': 'TV / Canal',
  'Sinema': 'Cine',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Otro',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Tu feed está vacío.\nCuando comenten las series y películas que ves, aparecerá aquí.',
  'Listeleri ({})': 'Sus listas ({})',
  'Liste boş.': 'Esta lista está vacía.',
  'Yanıtla': 'Responder',
  '@{} kullanıcısına yanıt veriyorsun': 'Respondiendo a @{}',
  'İzlediğim Diziler ({})': 'Series que vi ({})',
  'İzlediğim Filmler ({})': 'Películas que vi ({})',
  'Tümünü gör': 'Ver todo',
  'Bildirimler': 'Notificaciones',
  'Henüz bildirim yok': 'Aún no hay notificaciones',
  '@{} yorumuna yanıt verdi': '@{} respondió a tu comentario',
  '@{} yorumunu beğendi': '@{} le gustó tu comentario',
  '@{} seni takip etti': '@{} te siguió',
  '@{} sana mesaj gönderdi': '@{} te envió un mensaje',
  'Mesajlar': 'Mensajes',
  'Mesaj': 'Mensaje',
  'Mesaja eklenecek': 'Se anadira al mensaje',
  'Mesajını yaz...': 'Escribe un mensaje...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Aún no hay chats.\nEntra a un perfil y envía un mensaje.',
  'Şifreni mi unuttun?': '¿Olvidaste tu contraseña?',
  'Şifreyi Sıfırla': 'Restablecer contraseña',
  'E-postadaki kod': 'Código del correo',
  'Yeni şifre': 'Nueva contraseña',
  'Sana Özel': 'Para ti',
  '{} özetin': 'Tu resumen de {}',
  'Yıllık izleme istatistiklerin': 'Tus estadísticas anuales',
  'Rozetler': 'Insignias',
  'Verdiğin puan': 'Puntuaciones dadas',
  'Ortalama puanın': 'Tu puntuación media',
  'En çok izlediğin diziler': 'Tus series más vistas',
  'İlk Bölüm': 'Primer episodio',
  '100 Bölüm': '100 episodios',
  '1000 Bölüm': '1000 episodios',
  'İlk Film': 'Primera película',
  '50 Film': '50 películas',
  'İlk Yorum': 'Primer comentario',
  '25 Yorum': '25 comentarios',
  '10 Puan': '10 puntuaciones',
  'İlk Takipçi': 'Primer seguidor',
  '10 Dizi Bitirdin': '10 series terminadas',
  'İzlemeyi Bıraktım': 'Dejé de verla',
  'İzlediği Diziler ({})': 'Series que vio ({})',
  'İzlediği Filmler ({})': 'Películas que vio ({})',
  '500 Bölüm': '500 episodios',
  '5000 Bölüm': '5000 episodios',
  '10 Film': '10 películas',
  '100 Film': '100 películas',
  '100 Yorum': '100 comentarios',
  '50 Puan': '50 puntuaciones',
  '100 Puan': '100 puntuaciones',
  '10 Takipçi': '10 seguidores',
  '50 Takipçi': '50 seguidores',
  '25 Dizi Bitirdin': '25 series terminadas',
  '50 Dizi Bitirdin': '50 series terminadas',
  '10 Beğeni': '10 me gusta',
  '100 Beğeni': '100 me gusta',
  'yazıyor...': 'escribiendo...',
  'ses kaydediyor...': 'grabando audio...',
  'Profil düzeni': 'Diseño del perfil',
  'Konumla ve kırp': 'Ajusta y recorta',
  'Listeye eklendi': 'Añadido a la lista',
  'Listeyi sil?': '¿Eliminar la lista?',
  'Sil': 'Eliminar',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Este título se marcará como nunca visto y se quitará de tus listas.',
  'Gelecek bölüm bugün': 'Próximo episodio hoy',
  'Gelecek bölüm {} gün sonra': 'Próximo episodio en {} días',
  'Tema': 'Tema',
  'Sistem': 'Sistema',
  'Koyu': 'Oscuro',
  'Açık': 'Claro',
  'İzleyenler': 'Espectadores',
  'Yorumunu yaz... (@ ile etiketle)':
      'Escribe tu comentario... (@ para etiquetar)',
  '@{} bir yorumda seni etiketledi': '@{} te etiquetó en un comentario',
  'Mesajı sil': 'Eliminar mensaje',
  'Mesaj silinemedi': 'No se pudo eliminar el mensaje',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'El enlace no es válido o la página no existe',
  "Keşfet'e dön": 'Volver a Descubrir',
  'Düzenle': 'Editar',
  'Mesajı düzenle': 'Editar mensaje',
  'Yanıtlanıyor': 'Respondiendo',
  'düzenlendi': 'editado',
  'Fotoğraf': 'Foto',
  'Video': 'Video',
  'İçerik': 'Contenido',
  'çevrimiçi': 'en línea',
  'son görülme {} dk önce': 'en línea hace {} min',
  'son görülme {} saat önce': 'en línea hace {} h',
  'son görülme {} gün önce': 'en línea hace {} d',
  'Yorumlar yüklenemedi': 'No se pudieron cargar los comentarios',
  'Favori': 'Favorito',
  'Listeye ekle': 'Añadir a lista',
  'İçerik paylaş': 'Compartir contenido',
  'Kapat': 'Cerrar',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Todo lo que marques como visto se junta aquí.',
  'Henüz sohbetin yok': 'Aún no hay conversaciones',
  'Bir profile girip mesaj gönderebilirsin.':
      'Abre un perfil y envía un mensaje.',
  'Listeyi sil': 'Eliminar lista',
  'Puan kaydedilemedi': 'No se pudo guardar la puntuación',
  'Nerede İzlenir': 'Dónde ver',
  'Abonelik': 'Suscripción',
  'Kirala': 'Alquilar',
  'Satın al': 'Comprar',
  'Devam et': 'Continuar',
  'Şikayet et': 'Denunciar',
  'Engelle': 'Bloquear',
  'Engeli kaldır': 'Desbloquear',
  'Kullanıcı engellendi': 'Usuario bloqueado',
  'Engel kaldırıldı': 'Bloqueo eliminado',
  'Şikayet sebebi': 'Motivo de la denuncia',
  'Spam veya yanıltıcı': 'Spam o engañoso',
  'Taciz veya nefret söylemi': 'Acoso o discurso de odio',
  'Uygunsuz / cinsel içerik': 'Contenido inapropiado / sexual',
  'Şiddet veya tehlikeli içerik': 'Violencia o contenido peligroso',
  'Telif hakkı ihlali': 'Infracción de derechos de autor',
  'Şikayetin alındı, teşekkürler': 'Tu denuncia se recibió, gracias',
  'Hesabımı Sil': 'Eliminar mi cuenta',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Tu cuenta y todos tus datos (historial, valoraciones, comentarios, listas, mensajes) se eliminarán permanentemente. Esto no se puede deshacer.',
  'Şifreni gir': 'Ingresa tu contraseña',
  'Hesabımı kalıcı sil': 'Eliminar mi cuenta para siempre',
  'Sesli mesaj': 'Mensaje de voz',
  'Ses gönderilemedi': 'No se pudo enviar el audio',
  'Kaydediliyor…': 'Grabando…',
  'Ses oynatılamadı': 'No se pudo reproducir el audio',
  'Oynat': 'Reproducir',
  'Fragmanı oynat': 'Reproducir tráiler',
  'Altyazıyı aç': 'Activar subtítulos',
  'Altyazıyı kapat': 'Desactivar subtítulos',
  '10 saniye ileri': 'Avanzar 10 segundos',
  '10 saniye geri': 'Retroceder 10 segundos',
  'Duraklat': 'Pausar',
  'Liste görünümü': 'Vista de lista',
  'Takvim görünümü': 'Vista de calendario',
  'Önceki ay': 'Mes anterior',
  'Sonraki ay': 'Mes siguiente',
  'Bu gün bölüm yok': 'No hay episodios este día',
  'Gizlilik Politikası': 'Política de Privacidad',
  'Son güncelleme: {}': 'Última actualización: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Esta política explica qué datos se recopilan, cómo se usan y cuáles son tus derechos cuando usas la aplicación dizi.jpg y el sitio dizijpg.com.',
  'Topladığımız Veriler': 'Datos que recopilamos',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Cuenta: dirección de correo, nombre de usuario y contraseña. Las contraseñas se guardan con un hash irreversible; las cuentas de invitado pueden usarse sin correo.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Perfil: la información que eliges añadir, como avatar, imagen de portada, bio y país.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Uso: tu historial de visualización, puntuaciones, comentarios, listas, reacciones y favoritos.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Mensajes: tus mensajes de texto, imagen y voz se guardan en nuestros servidores. Los mensajes no están cifrados de extremo a extremo; solo se revisan con fines de moderación si alguien los denuncia.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Contenido subido: fotos, GIF, vídeos y grabaciones de voz que añades a tu perfil, comentarios y mensajes.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Datos técnicos: dirección IP, ubicación aproximada (país/ciudad), plataforma del dispositivo, versión de la app y registros de errores. Se conservan por seguridad y para corregir fallos.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Estadísticas de uso: el tipo de dispositivo, el sistema operativo y el navegador con los que se entra se suman a contadores diarios totales en categorías generales; el identificador del navegador en sí no se guarda y esas cifras no pueden vincularse a ninguna persona.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Notificaciones: para las notificaciones push guardamos el token de tu dispositivo y tu idioma. Puedes desactivarlas cuando quieras en los ajustes del dispositivo.',
  'Verileri Nasıl Kullanırız': 'Cómo usamos tus datos',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Usamos tus datos únicamente para prestar el servicio, proteger tu cuenta, enviar notificaciones, corregir errores y prevenir abusos. No vendemos tus datos ni los compartimos con nadie con fines publicitarios.',
  'Çerezler ve Yerel Depolama': 'Cookies y almacenamiento local',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Solo usamos almacenamiento local para mantener tu sesión abierta y recordar preferencias como idioma y tema. No hay cookies de publicidad ni de rastreo.',
  'Üçüncü Taraf Hizmetler': 'Servicios de terceros',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Los datos de series y películas provienen de TMDB y la información de plataformas de streaming, de JustWatch. Las notificaciones push se envían mediante Google Firebase y el tráfico del sitio está protegido por Cloudflare. Estos servicios se rigen por sus propias políticas de privacidad.',
  'Saklama ve Silme': 'Conservación y eliminación',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Tus datos se conservan mientras tu cuenta esté activa. Con "Eliminar mi cuenta" en Configuración puedes borrar tu cuenta de forma permanente; tus datos se eliminan al instante y las copias de seguridad, como máximo en 14 días. Los registros de errores se borran automáticamente a los 30 días.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'Puedes exportar tus datos como ZIP desde Configuración; el archivo se envía a tu dirección de correo.',
  'Güvenlik': 'Seguridad',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Los datos se transmiten por conexiones cifradas (HTTPS) y se almacenan en servidores con acceso restringido.',
  'Çocukların Gizliliği': 'Privacidad de los menores',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg no está dirigido a menores de 13 años.',
  'Hakların': 'Tus derechos',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Según KVKK y GDPR, tienes derecho a acceder a tus datos, corregirlos, eliminarlos y transferirlos. Para ejercerlos, escríbenos: {}',
  'Değişiklikler': 'Cambios',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Si esta política cambia, la nueva versión se publicará en esta página y se actualizará la fecha.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Al registrarte aceptas la {}.',
  'Kullanıcılar': 'Usuarios',
  'Fotoğrafı değiştir': 'Cambiar foto',
  'Yeniden konumlandır': 'Reposicionar',
  'Bir şeyler ters gitti': 'Algo salió mal',
  'Sosyal Bağlantılar': 'Enlaces sociales',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Se muestran hasta 3 enlaces en tu perfil.',
  'Platform seç': 'Elige una plataforma',
  'Kullanıcı adın': 'Tu nombre de usuario',
  'Ekle': 'Añadir',
  'Kaldır': 'Quitar',
  'Kopyalandı: {}': 'Copiado: {}',
  'Geçersiz kullanıcı adı': 'Nombre de usuario no válido',
  'Bağlantı ekle': 'Añadir enlace',
  'Spoiler olabilir — dokun ve gör': 'Puede contener spoilers — toca para ver',
  'Beğeni': 'Me gusta',
  'beğeni': 'me gusta',
  'Beğen': 'Me gusta',
  'Görüntülenme': 'Visualizaciones',
  'görüntülenme': 'visualizaciones',
  'Tam ekran': 'Pantalla completa',
  'Arama başarısız': 'Error en la búsqueda',
  'Sonuç bulunamadı': 'Sin resultados',
  'Dizi ve Filmler': 'Series y películas',
  'Kişiler': 'Personas',
  'Ana Sayfa': 'Inicio',
  'Paylaş': 'Compartir',
  'Yanıtlar': 'Respuestas',
  'Yaklaşan Bölümler': 'Próximos episodios',
  'Yetişme Listesi': 'Lista para ponerte al día',
  'Şunu mu demek istedin': 'Quizás quisiste decir',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — toca para ver',
  'uyum': 'afinidad',
  'Uyum': 'Afinidad',
  '{} ortak dizi': '{} series en común',
  '{} ortak film': '{} películas en común',
  'Bildirim Tercihleri': 'Preferencias de notificaciones',
  'Beğeniler': 'Me gusta',
  'Yeni takipçiler': 'Nuevos seguidores',
  'Etiketlenmeler': 'Menciones',
  'Yeniden izledim': 'Visto de nuevo',
  '{}. kez izlendi': 'Visto {} veces',
  'Gönderi bulunamadı': 'Publicación no encontrada',
  'Gözat': 'Explorar',
  'Diziler': 'Series',
  'Filmler': 'Películas',
  'Tümü': 'Todo',
  'Farklı bir tür seç.': 'Prueba otro género.',
  'Gizlilik': 'Privacidad',
  'İzlediklerimi gizle': 'Ocultar lo que veo',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Las series y películas que viste no se mostrarán en tu perfil',
  'Yorumlarımı gizle': 'Ocultar mis comentarios',
  'Profilinde yorumların görünmez':
      'Tus comentarios no se mostrarán en tu perfil',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Puedes ocultar una serie o película concreta con el chip "Ocultar en mi perfil" en su página.',
  'Geri Bildirim': 'Tu opinión',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Escribe tu opinión y sugerencias sobre la app...',
  'Teşekkürler! Geri bildirimin alındı.':
      '¡Gracias! Hemos recibido tu opinión.',
  'Profilimde gizle': 'Ocultar en mi perfil',
  'Yorumları': 'Comentarios',
  'Bu kullanıcı henüz bir şey izlememiş.': 'Este usuario aún no ha visto nada.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Este usuario prefiere mantener sus comentarios en privado.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Datos: JustWatch',
  'Web Sitesi': 'Sitio web',
  'Diğer uygulamalar': 'Otras apps',
  'Bağlantıyı kopyala': 'Copiar enlace',
  'Henüz kimseyi takip etmiyorsun.': 'Todavía no sigues a nadie.',
  'Çevir': 'Traducir',
  'Çeviri şu an yapılamadı': 'La traducción no está disponible ahora',
  'Bağlantı açılamadı': 'No se pudo abrir el enlace',
  'Orijinali göster': 'Ver original',
  'Çeviriyi göster': 'Mostrar traducción',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Este mes no hay episodios con fecha de emisión anunciada. Las fechas suelen anunciarse unas semanas antes y aparecerán aquí.',
  'devamı': 'más',
  'Google ile devam et': 'Continuar con Google',
  'Google girişi başarısız': 'No se pudo iniciar sesión con Google',
  'Veri tasarrufu': 'Ahorro de datos',
  'Wi-Fi ağında veri tasarrufu': 'Ahorro de datos en Wi-Fi',
  'Mobil veride veri tasarrufu': 'Ahorro de datos en datos móviles',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Cuando está activo, las fotos no se descargan por adelantado; solo se carga la imagen que estás viendo.',
  'Çocuk güvenliği': 'Seguridad infantil',
  'Türk Filmleri': 'Películas turcas',
  'En Yüksek Puanlı Filmler': 'Películas mejor valoradas',
  'En Yüksek Puanlı Diziler': 'Series mejor valoradas',
  'En Çok İzlenen Filmler': 'Películas más vistas',
  'Popüler Diziler': 'Series populares',
  'En Çok Kazanan Filmler': 'Películas más taquilleras',
  'Kült Filmler': 'Películas de culto',
  'Yeni Filmler': 'Películas nuevas',
  'Yorum yap': 'Comentar',
  'Henüz yorum yok': 'Aún no hay comentarios',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Tus comentarios sobre series y películas se reúnen aquí.',
  'GIF ekle': 'Añadir GIF',
  'İlk yorumu sen yaz': 'Sé el primero en comentar',
  'Video altyazıları': 'Subtítulos de vídeo',
  'Videolarda altyazı göster': 'Mostrar subtítulos en vídeos',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'La frase pronunciada en el vídeo está escrita en la pantalla. El texto está traducido: inglés en turco, turco en otros idiomas.',
  'Güncelleme gerekli': 'Actualización necesaria',
  'Yeni sürüm var': 'Nueva versión disponible',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Instala la nueva versión de dizi.jpg para continuar.',
  'Güncelle': 'Actualizar',
  'Daha sonra': 'Más tarde',
  'Takvim güncelleniyor': 'Actualizando el calendario',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'No se pudo actualizar el calendario, se muestra la lista anterior',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Algunas series no se pudieron cargar, la lista puede estar incompleta',
  'Yenile': 'Actualizar',
  'Devam etmek için giriş yap': 'Inicia sesión para continuar',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Con una cuenta gratuita puedes puntuar, comentar y crear tu biblioteca.',
  'Şimdi değil': 'Ahora no',
  'Yorum yazmak için giriş yap': 'Inicia sesión para comentar',
  'Kişilere göndermek için giriş yap':
      'Inicia sesión para enviar a otras personas',
  'Beğenenler': 'Me gusta',
  'Henüz beğeni yok': 'Aun no hay me gusta',
  'Bu gönderiyi ilk beğenen sen ol': 'Se la primera persona en darle me gusta',
  'Bu gönderiye yanıt': 'Respuesta a esta publicacion',
  'Spoiler içeren gönderi': 'Publicación con spoilers',
  'Görsel gönderi': 'Publicación con foto',
  'Bu yorumu profilimde gizle': 'Ocultar este comentario en mi perfil',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'El comentario permanece en la página de la serie y la película',
  'Bu yorumu sil': 'Eliminar este comentario',
  'Yorum profilinde gizlendi': 'Comentario oculto en tu perfil',
  'Geri al': 'Deshacer',
  'Yorum silinsin mi?': '¿Eliminar comentario?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Este comentario se eliminará permanentemente en todas partes. No se puede deshacer.',
  'Yorum silindi': 'Comentario eliminado',
  'Yorum profilinde tekrar görünüyor':
      'El comentario vuelve a ser visible en tu perfil',
  'Gizlenen yorumun yok': 'No tienes comentarios ocultos',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Los comentarios que ocultas al mantener pulsada una publicación en la pestaña Comentarios de tu perfil se acumulan aquí.',
  'Gizlenen yorumlar': 'Comentarios ocultos',
  'Gönderiye git': 'Ir a la publicación',
  'Tekrar göster': 'Mostrar de nuevo',
  'Yanıtlarımı gizle': 'Ocultar mis respuestas',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Las respuestas que escribes en publicaciones de otros solo son visibles para ti',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Mostrar de nuevo los comentarios que ocultaste en tu perfil',
  'Sıralama': 'Orden',
  'Önerilen': 'Recomendado',
  'Kronolojik': 'Cronológico',
  'Gelen mesaj istekleri': 'Solicitudes de mensaje recibidas',
  'Mesaj isteğin yok': 'No tienes solicitudes de mensaje',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Los mensajes de personas que no sigues aparecen aquí.',
  'Çevrimiçi durumumu gizle': 'Ocultar mi estado en línea',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Los demás no verán tu estado en línea ni tu última conexión en los mensajes',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'De nuestros primeros usuarios. Sus comentarios ayudaron a que la aplicación sea lo que es hoy.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Estás entre nuestros primeros usuarios. Tus comentarios ayudaron a que la aplicación sea lo que es hoy.',
  'İleri': 'Siguiente',
  'Önceki': 'Anterior',
  'Sonraki': 'Siguiente',
  'Seçilen dosya okunamadı': 'No se pudo leer el archivo seleccionado',
  'Video açılamadı': 'No se pudo abrir el vídeo',
  'En fazla {} medya seçebilirsin':
      'Puedes seleccionar un máximo de {} elementos',
  'Hiçbir medya yüklenemedi': 'No se pudo subir ningún archivo',
  'Seçimi kaldır': 'Quitar de la selección',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'En un comentario puedes subir {} MB en total',
  '{} dosya okunamadı': 'No se pudieron leer {} archivos',
  '{} medya eklendi, {} yüklenemedi': '{} elementos agregados, {} fallaron',
  'Kırp': 'Recortar',
  'Çiz': 'Dibujar',
  'Metin': 'Texto',
  'Emoji': 'Emoji',
  'Yinele': 'Rehacer',
  'Daha fazla': 'Más',
  'Hazırlanıyor…': 'Preparando…',
  'Düzenlemeden çık?': '¿Salir de la edición?',
  'Yaptığın değişiklikler kaybolacak.': 'Se perderán los cambios que hiciste.',
  'Çık': 'Salir',
  'Serbest çizim': 'Mano alzada',
  'Ok': 'Flecha',
  'Dikdörtgen': 'Rectángulo',
  'Daire': 'Círculo',
  'Bulanıklaştır': 'Difuminar',
  'Pikselleştir': 'Pixelar',
  'Silgi': 'Borrador',
  'Çizgi kalınlığı': 'Grosor de línea',
  'Saydamlık': 'Opacidad',
  'Dolgu': 'Relleno',
  'Renk': 'Color',
  'Döndür': 'Girar',
  'Yansıt': 'Voltear',
  'Oran': 'Proporción',
  'Sıfırla': 'Restablecer',
  'Serbest': 'Libre',
  'Metin yaz...': 'Escribe un texto...',
  'Hizala': 'Alinear',
  'Arka plan': 'Fondo',
  'Emoji ara...': 'Buscar emoji...',
  'Son kullanılanlar': 'Recientes',
  'İfadeler ve insanlar': 'Caritas y personas',
  'Hayvanlar ve doğa': 'Animales y naturaleza',
  'Yiyecek ve içecek': 'Comida y bebida',
  'Etkinlikler': 'Actividades',
  'Seyahat ve yerler': 'Viajes y lugares',
  'Nesneler': 'Objetos',
  'Semboller': 'Símbolos',
  'Bayraklar': 'Banderas',
  'Görseli düzenle': 'Editar imagen',
  'Düzenlendi': 'Editada',
  'Düzenlenemedi': 'No se pudo editar',
  'Düzenlenen görsel çok büyük': 'La imagen editada es demasiado grande',
  'Videoyu düzenle': 'Editar video',
  'Sesi kapat': 'Silenciar',
  'Sesi aç': 'Activar sonido',
  'İptal ediliyor…': 'Cancelando…',
  'Bu biraz sürebilir': 'Esto puede tardar un poco',
  'Video çok büyük': 'El video es demasiado grande',
  'Video hazırlanamadı': 'No se pudo preparar el video',
  'Başlangıç': 'Inicio',
  'Bitiş': 'Fin',
  'En çok {} saniye seçebilirsin': 'Puedes seleccionar hasta {} segundos',
  'Dosya en fazla {} MB olabilir': 'El archivo puede pesar como máximo {} MB',
  'Medya ekle': 'Añadir contenido',
  'Seçili medya kalmadı': 'No hay contenido seleccionado',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Elige una foto o un vídeo para añadirlo a tu comentario.',
  'Medya seç': 'Seleccionar contenido',
  'Daha fazla ekle': 'Añadir más',
  'Medya seçilemedi': 'No se pudo seleccionar el contenido',
  'Favori oyuncular': 'Actores favoritos',
  'Henüz favori oyuncun yok': 'Aún no tienes actores favoritos',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Abre la pagina de un actor y toca el corazon arriba a la derecha para anadirlo aqui.',
  '{} yapımdan {} tanesini izledin': 'Viste {} de {} titulos',
  'izledin': 'vistos',
  'İzlemedin': 'No visto',
  'Yapım bulunamadı': 'No se encontraron titulos',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Esta persona no tiene series ni peliculas para listar.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Tu historial esta ligado a tu cuenta; esta lista es solo tuya.',
  'Hesabın kalıcı olarak askıya alındı':
      'Tu cuenta ha sido suspendida permanentemente',
  'Hesabın geçici olarak askıya alındı':
      'Tu cuenta ha sido suspendida temporalmente',
  'Hesabın askıya alındı': 'Tu cuenta está suspendida',
  'Sebep': 'Motivo',
  'Kalan süre': 'Tiempo restante',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Tu cuenta se reactivará automáticamente cuando termine el plazo',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'Durante este tiempo puedes seguir leyendo, pero no publicar, comentar ni enviar mensajes.',
  'Anladım': 'Entendido',
  'Ayrıntı': 'Detalles',
  '{} dakika': '{} minutos',
  'birkaç saniye': 'unos segundos',
  'Karara itiraz et': 'Apelar esta decisión',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Explica por qué debería retirarse esta sanción',
  'İtirazını gönder': 'Enviar tu apelación',
  'İtirazın incelemede': 'Tu apelación está en revisión',
  'İtirazın reddedildi': 'Tu apelación fue rechazada',
  'İtirazın alındı, inceleniyor': 'Recibimos tu apelación y está en revisión',
  'İtiraz en az 10 karakter olmalı':
      'La apelación debe tener al menos 10 caracteres',
  'Yükleniyor...': 'Cargando...',
  'Bu bölüme puan ver': 'Puntúa este episodio',
  '{} kişi puanladı': '{} personas puntuaron',
  'Bölüm izlendi olarak işaretlendi': 'Episodio marcado como visto',
  'Sesli ara': 'Llamada de voz',
  'Görüntülü ara': 'Videollamada',
  'Çalıyor...': 'Llamando...',
  'Bağlanıyor...': 'Conectando...',
  'Cevapla': 'Responder',
  'Reddet': 'Rechazar',
  'Sessize al': 'Silenciar',
  'Hoparlör': 'Altavoz',
  'Kamerayı kapat': 'Apagar cámara',
  'Kamerayı çevir': 'Cambiar cámara',
  'Cevap yok': 'Sin respuesta',
  'Arama reddedildi': 'Llamada rechazada',
  'Meşgul': 'Ocupado',
  'Bağlanılamadı': 'No se pudo conectar',
  'Arama iptal edildi': 'Llamada cancelada',
  'Arama geçmişi': 'Historial de llamadas',
  'Gelen arama': 'Llamada entrante',
  'Giden arama': 'Llamada saliente',
  'Cevapsız arama': 'Llamada perdida',
  'Arama şu anda kullanılamıyor': 'Las llamadas no están disponibles ahora',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Las videollamadas están desactivadas, puedes hacer una llamada de voz',
  'Bu kullanıcıyı arayamazsın': 'No puedes llamar a este usuario',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Debéis seguiros mutuamente para llamar',
  'Bu kullanıcı şu anda aranamıyor': 'No se puede llamar a este usuario ahora',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Demasiadas llamadas perdidas. Inténtalo de nuevo en {}',
  'Zaten bir aramadasın': 'Ya estás en una llamada',
  'Arama için mikrofon izni gerekiyor':
      'Se necesita permiso de micrófono para llamar',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'Se necesita permiso de cámara y micrófono para videollamadas',
  'Arama başlatılamadı': 'No se pudo iniciar la llamada',
  'Kullanıcı bulunamadı': 'Usuario no encontrado',
  'Kendini arayamazsın': 'No puedes llamarte a ti mismo',
  'Arama artık geçerli değil': 'Esta llamada ya no es válida',
  'Bu aramanın tarafı değilsin': 'No formas parte de esta llamada',
  'Arama bulunamadı': 'Llamada no encontrada',
  'Çok fazla istek, biraz bekle': 'Demasiadas solicitudes, espera un momento',
  'Bağlantı koptu': 'Se perdió la conexión',
  'Arama süre sınırına ulaştı': 'La llamada alcanzó su límite de tiempo',
  'Arama en fazla 4 saat sürebilir':
      'Una llamada puede durar como máximo 4 horas',
  'Arama sona erdi': 'La llamada ha terminado',
  'Sesli arama': 'Llamada de voz',
  'Görüntülü arama': 'Videollamada',
  'Gelen aramalar': 'Llamadas entrantes',
  'Sesli ve görüntülü arama bildirimleri':
      'Notificaciones de llamadas de voz y vídeo',
  '{} sa': '{} h',
  'Sesli ve Görüntülü Aramalar': 'Llamadas de voz y vídeo',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'El contenido de las llamadas nunca se graba. El audio y el vídeo viajan cifrados de extremo a extremo (DTLS-SRTP) entre los dispositivos; nuestros servidores no pueden descifrar, escuchar ni almacenar ese tráfico.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Solo se guardan los metadatos de la llamada: con quién, en qué dirección, cuándo y cuánto duró. Estos registros se eliminan automáticamente a los 90 días.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Si no se puede establecer una conexión directa, el audio y el vídeo pasan cifrados por un servidor de retransmisión (TURN). Ese servidor tampoco puede descifrar ni grabar el contenido.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'El micrófono solo se usa durante una llamada de voz o vídeo, y la cámara solo durante una videollamada. Ambos se apagan al terminar la llamada.',
  'Takip ettiğin {} kişi izledi': '{} personas que sigues lo vieron',
  'Yorum yaz...': 'Escribe un comentario...',
  'Sıradaki bölüm': 'Siguiente episodio',
  'Doğrulanmış testçi': 'Probador verificado',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Notificaciones de seguidores, me gusta, respuestas, mensajes y menciones',
  'Sen': 'Tú',
  'Aradığınız kişide sesli arama devre dışı':
      'Las llamadas de voz están desactivadas para esta persona',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Las videollamadas están desactivadas para esta persona',
  'Sesli aramalara izin ver': 'Permitir llamadas de voz',
  'Görüntülü aramalara izin ver': 'Permitir videollamadas',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Si está desactivado, nadie puede llamarte por voz; quien llame verá un aviso',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Si está desactivado, nadie puede hacerte videollamadas; quien llame verá un aviso',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Las llamadas de voz están desactivadas. Puedes activarlas en Ajustes > Privacidad.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Las videollamadas están desactivadas. Puedes activarlas en Ajustes > Privacidad.',
  'Sesli ve görüntülü arama': 'Llamadas de voz y vídeo',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Las cuentas de invitado no pueden llamar. Crea una cuenta para usarlo.',
  'Misafir hesaplar aranamaz': 'No se puede llamar a cuentas de invitado',
  'Puan dağılımı': 'Distribución de puntuaciones',
  '{} yıldız': '{} estrellas',
  'Yakında gelecek': 'Próximamente',
  '{} {} yayınlandı': '{} {} ya está disponible',
  'Yeni bölüm yayınlandı': 'Nuevo episodio disponible',
  'Yeni bölümler': 'Nuevos episodios',
  'Geri': 'Atrás',
  'Karşılamayı kapat': 'Cerrar la introducción',
  'Adım {} / {}': 'Paso {} / {}',
  'Hadi başlayalım': 'Empecemos',
  'Kaydet ve devam': 'Guardar y continuar',
  '{} tanesini ekle': 'Añadir {}',
  'Şimdilik geç': 'Ahora no',
  'Doğum tarihin ne zaman?': '¿Cuál es tu fecha de nacimiento?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Lo preguntamos para mostrarte contenido acorde a tu edad y para felicitarte en tu cumpleaños.',
  'Gün': 'Día',
  'Ay': 'Mes',
  'Yıl': 'Año',
  'Doğum yılımı paylaşmak istemiyorum':
      'No quiero compartir mi año de nacimiento',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'Tu fecha de nacimiento no se muestra públicamente en tu perfil. Solo se usa para ofrecer contenido acorde a la edad y para la felicitación de cumpleaños.',
  'Ocak': 'enero',
  'Şubat': 'febrero',
  'Mart': 'marzo',
  'Nisan': 'abril',
  'Mayıs': 'mayo',
  'Haziran': 'junio',
  'Temmuz': 'julio',
  'Ağustos': 'agosto',
  'Eylül': 'septiembre',
  'Ekim': 'octubre',
  'Kasım': 'noviembre',
  'Aralık': 'diciembre',
  'Verilerini yanında getir': 'Trae tus datos contigo',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Si llevas el registro de lo que ves en otra app, puedes traerlo aquí. No hace falta empezar de cero.',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt y Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Elige el archivo ZIP que exportaste; lo que has visto, tus puntuaciones y tus listas se importarán.',
  'Aktarılıyor...': 'Importando...',
  'ZIP dosyası seç': 'Elegir archivo ZIP',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'No hay prisa: también puedes hacerlo más tarde en Ajustes > Mis datos.',
  'Hangi filmleri izledin?': '¿Qué películas has visto?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Aquí están las más vistas. Toca las que hayas visto y las añadimos a tu historial.',
  'SERİ FİLMLER': 'SAGAS',
  'Serilerden {} film eklendi': '{} películas añadidas desde las sagas',
  'Film listesi yüklenemedi': 'No se pudo cargar la lista de películas',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Puedes saltarte este paso y añadir lo que quieras más tarde.',
  '{} film izlediklerine eklendi': '{} películas añadidas a tu historial',
  'Film serileri': 'Sagas de películas',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Si has visto una saga entera, añádela con un solo toque.',
  'Seri bulunamadı': 'No se encontraron sagas',
  'Daha sonra tekrar deneyebilirsin.': 'Puedes intentarlo de nuevo más tarde.',
  '{} film': '{} películas',
  'Eklendi': 'Añadido',
  'Tümünü izledim': 'Las he visto todas',
  'Peki ya diziler?': '¿Y las series?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Marca lo que has visto; a medida que elijas, te traeremos series parecidas.',
  'Dizi listesi yüklenemedi': 'No se pudo cargar la lista de series',
  'Seçtiklerine benzeyenler': 'Parecidas a tu selección',
  'Her şey hazır': 'Todo listo',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Echa un vistazo rápido a lo que puedes hacer en dizi.jpg.',
  'Profilini tamamla': 'Completa tu perfil',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'Desde Ajustes puedes añadir una bio, una foto de perfil y una portada.',
  'Takvimin seni bekliyor': 'Tu calendario te espera',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'Los nuevos episodios de tus series aparecen en el calendario y te avisamos con una notificación.',
  'Puan ver, yorum yaz': 'Puntúa y comenta',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Puntúa episodio a episodio, comenta tras una cortina de spoiler y crea listas.',
  'Verilerin sende kalır': 'Tus datos son tuyos',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Tus datos se guardan vinculados solo a tu cuenta y no se venden. Desde Ajustes puedes descargarlos todos o eliminar tu cuenta por completo.',
  'Engellenen kullanıcılar': 'Personas bloqueadas',
  'Engellediğin kişileri gör, engeli kaldır':
      'Mira a quién has bloqueado y quita el bloqueo',
  'Engellediğin kimse yok': 'No has bloqueado a nadie',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Puedes bloquear a una persona desde el menú de tres puntos de su perfil.',
  '@{} engellensin mi?': '¿Bloquear a @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'Ninguna de las dos partes verá las publicaciones, los comentarios ni el perfil de la otra; tampoco se podrán enviar mensajes ni llamadas. Si existe un vínculo de seguimiento, se romperá y no volverá aunque quites el bloqueo.',
  'Bu kullanıcıyı engelledin': 'Has bloqueado a esta persona',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'No ves sus publicaciones, comentarios ni mensajes; esa persona tampoco ve los tuyos.',
  '{} yeni bir yapımda: {}': '{} aparece en una nueva producción: {}',
  'Favori kişinden yeni yapım': 'Nueva producción de una persona favorita',
  '{} için bildirimler': 'Notificaciones de {}',
  'Tüm bildirimler': 'Todas las notificaciones',
  'Uygulamada ve telefonda': 'En la app y en el teléfono',
  'Yalnız uygulama içi': 'Solo en la app',
  'Telefon bildirimi gönderilmez': 'No se envían notificaciones al teléfono',
  'Kapalı': 'Desactivado',
  'Bu kişi için bildirim yok': 'Sin notificaciones de esta persona',
  'Favori kişilerin yeni yapımları':
      'Nuevas producciones de tus personas favoritas',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Si está desactivado, nadie puede llamarte por voz; quien llame verá el aviso "desactivadas"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Si está desactivado, nadie puede hacerte videollamadas; quien llame verá el aviso "desactivadas"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'Mi actividad',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'Tus me gusta, comentarios y visualizaciones en un solo lugar',
  'Henüz hareketin yok': 'Aún no hay actividad',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Todo lo que te gusta, comentas y ves se acumula aquí.',
  'Bu süzgeçte hareket yok': 'No hay actividad en este filtro',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Elige otro tipo o vuelve a "Todo".',
  'Hepsi': 'Todo',
  'Puan': 'Puntuación',
  'Tepki': 'Reacción',
  'İzleme': 'Visto',
  'Durum': 'Estado',
  'Liste': 'Lista',
  'Yorum yaptın': 'Comentaste',
  'Yorumu beğendin': 'Te gustó un comentario',
  '{} puan verdin': 'Puntuaste con {}',
  'Tepki verdin': 'Reaccionaste',
  'Listene ekledin': 'Añadiste a una lista',
  'Takip etmeye başladın': 'Empezaste a seguir',
  '"İzleyeceğim" işaretledin': 'Marcado como "Pendiente"',
  '"İzliyorum" işaretledin': 'Marcado como "Viendo"',
  '"Bitirdim" işaretledin': 'Marcado como "Terminada"',
  '"Bıraktım" işaretledin': 'Marcado como "Abandonada"',
  'Silinmiş içerik': 'Contenido eliminado',
  'şimdi': 'ahora',
  '{} g': '{} d',
  '{} y': '{} a',
  'İstatistiklerim': 'Mis estadísticas',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Visualizaciones y me gusta de tus publicaciones',
  'Henüz gönderin yok': 'Aún no tienes publicaciones',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Cuando comentes una serie o película, tus visualizaciones y me gusta empezarán a acumularse aquí.',
  'Tüm zamanlar': 'Desde siempre',
  'Son {} gün': 'Últimos {} días',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'El historial de visualizaciones aún no empezó a acumularse; los datos del primer día aparecen mañana.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'El historial de visualizaciones se acumula desde el {} (hay {} días de datos), así que el recuento de {} días aún está incompleto.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'El historial de me gusta está registrado desde el {}.',
  'Bu dönemde gösterilecek gönderi yok.':
      'No hay publicaciones para mostrar en este período.',
  'eksik veri': 'datos incompletos',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Las series y películas que viste, tus contadores de visualización, tu tiempo de pantalla y tu tarjeta de afinidad no serán visibles para otros en tu perfil',
  'Takipçi listemi gizle': 'Ocultar mi lista de seguidores',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Los demás no pueden ver quién te sigue; tu número de seguidores sigue visible',
  'Takip ettiklerimi gizle': 'Ocultar a quién sigo',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Los demás no pueden ver a quién sigues; tu número de seguidos sigue visible',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Este usuario prefiere mantener sus seguidores en privado.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Este usuario prefiere mantener en privado a quién sigue.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Estadísticas de la publicación',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Solo puedes ver las estadísticas de tus propias publicaciones.',
  'Erişim': 'Alcance',
  'Görüntüleyen': 'Espectadores',
  'Kaç farklı kişi gördü (son {} gün)':
      'Cuántas personas distintas lo vieron (últimos {} días)',
  'Paylaşım': 'Compartidos',
  'Bu gönderiden sonra': 'Después de esta publicación',
  'Profil ziyareti': 'Visitas al perfil',
  'Yeni takip': 'Nuevos seguidores',
  'İçeriğe tıklama': 'Toques en el contenido',
  'Spoiler perdesini açan': 'Revelaron el spoiler',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Los compartidos, las visitas al perfil, los seguidores, los toques en el contenido, el desglose por origen y las medidas de spoiler se acumulan desde el {}; lo anterior no se midió.',
  'Zamana yayılmış görüntülenme': 'Visualizaciones a lo largo del tiempo',
  'Görüntülenme nereden geldi': 'De dónde vinieron las visualizaciones',
  'Kimler gördü': 'Quién lo vio',
  'Günlük veri henüz birikmeye başlamadı.':
      'Los datos diarios aún no han empezado a acumularse.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'El gráfico necesita al menos dos días de datos. Los datos se acumulan desde el {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'La mayoría de las visualizaciones llegaron el día {} tras publicar: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Las visualizaciones diarias se acumulan desde el {}; lo anterior no se midió.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'El desglose por origen acaba de empezar a medirse; esta publicación aún no ha recibido ninguna visualización etiquetada.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'El desglose entre seguidores y descubrimiento acaba de empezar a medirse; todavía no hay datos.',
  'Takip edenler': 'Seguidores',
  'Keşiften gelenler': 'Desde Descubrir',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Página de serie/película',
  'Paylaşılan bağlantı': 'Enlace compartido',
  'yeni ölçülüyor': 'medición reciente',
  'Kendi ortalamanla aynı düzeyde': 'Al nivel de tu propio promedio',
  'Kendi ortalamanın %{} üstünde': 'Un {}% por encima de tu propio promedio',
  'Kendi ortalamanın %{} altında': 'Un {}% por debajo de tu propio promedio',
  'Etkileşim oranı': 'Tasa de interacción',
  '(beğeni + yorum) ÷ görüntülenme':
      '(me gusta + comentarios) ÷ visualizaciones',
  'Toplam görüntülenme': 'Visualizaciones totales',
  '{} ile {} arasında toplam {} görüntülenme':
      'Entre el {} y el {}: {} visualizaciones en total',
  'İstatistikleri gör': 'Ver estadísticas',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'Para las estadísticas que se muestran a la persona propietaria de una publicación, se guardan como contadores agregados: cuántas veces y desde qué superficie (feed, perfil, feed a pantalla completa, página de serie/película, enlace compartido) se vio la publicación, si quien la vio seguía en ese momento a la persona propietaria, el paso de la publicación al perfil o al contenido, los seguimientos iniciados desde la publicación, los compartidos y la apertura del velo de spoiler. Estos contadores no contienen identidad de usuario, dirección IP ni marca de tiempo; no se puede consultar quién hizo qué.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'Para poder contar cuántas personas distintas vieron una publicación, se conserva durante 90 días un resumen con clave irreversible por cada persona que la vio (una condensación criptográfica derivada de la identidad de usuario o de la dirección IP). A la persona propietaria de la publicación solo se le muestra el número; la identidad de quienes la vieron no se comparte bajo ninguna circunstancia.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': '¿Mover a «Pendiente»?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'Un título o está pendiente o ya está visto. Si continúas, se eliminarán tus {} marcas de visto en esta serie.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'Un título o está pendiente o ya está visto. Si continúas, se quitará tu marca «Visto» en esta película.',
  'Sil ve taşı': 'Eliminar y mover',

  // --- Yapım ekibi / firma + seviye unvanları + doğum günü ---
  'Yapım Ekibi': 'Equipo técnico',
  'Yaratıcı': 'Creación',
  'Yönetmen': 'Dirección',
  'Senaryo': 'Guion',
  'Yapımcı': 'Producción',
  'Yapım Firmaları': 'Productoras',
  'Yapım Firması': 'Productora',
  'Firma bulunamadı': 'Productora no encontrada',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'Esta productora no tiene títulos de este tipo.',
  'Doğum günün kutlu olsun!': '¡Feliz cumpleaños!',
  'İyi ki doğdun, iyi ki buradasın.':
      'Qué bueno que naciste y qué bueno que estés aquí.',
  'Bugün {} yaşına girdin': 'Hoy cumples {} años',
  'Teşekkürler': 'Gracias',
  'İki Adımlı Doğrulama': 'Verificación en dos pasos',
  'Girişte e-postana kod gönderilir':
      'Al iniciar sesión se envía un código a tu correo',
  'Kod {} adresine gönderildi': 'Código enviado a {}',
  '6 haneli kod': 'Código de 6 dígitos',
  'Doğrula': 'Verificar',
  'Yeniden gönder': 'Reenviar',
  'Vazgeç': 'Cancelar',
  'Yeni kod gönderildi': 'Nuevo código enviado',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'Al iniciar sesión con Google no se pide código; Google hace su propia verificación.',
  'Kapatmak için de kod gerekir.': 'Desactivarla también requiere un código.',
  'E-postana erişemezsen hesabına giremezsin.':
      'Si pierdes el acceso a tu correo, no podrás entrar en tu cuenta.',
  'İki adımlı doğrulama açıldı': 'Verificación en dos pasos activada',
  'İki adımlı doğrulama kapatıldı': 'Verificación en dos pasos desactivada',
  'Videonun ne kadarı izlendi': 'Cuánto se vio del video',
  'Videoyu başlatanlar': 'Empezaron el video',
  'videonun %{} noktasına ulaştı': 'llegaron al {}% del video',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'La mitad del público vio al menos el {}% del video.',
  'Sonuna kadar izleyen: %{}': 'Vieron hasta el final: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'La curva necesita al menos {} reproducciones; ahora hay {}.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'La curva se basa en {} reproducciones y no cambia con el periodo seleccionado.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'El tiempo de reproducción se mide desde el {}; las visualizaciones anteriores no cuentan.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} reproducciones. El {}% llegó a la mitad y el {}% al final.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'Nivel {}',
  'Sonraki seviyeye {} puan kaldı': '{} puntos para el siguiente nivel',
  'Gönderilerin': 'Tus publicaciones',
  '{} gönderi': '{} publicaciones',
  '{} gönderi · {} görüntülenme': '{} publicaciones · {} visualizaciones',
  'önceki {} güne göre': 'frente a los {} días anteriores',
  'önceki {} güne göre %{} arttı': 'frente a los {} días anteriores, {}% más',
  'önceki {} güne göre %{} azaldı':
      'frente a los {} días anteriores, {}% menos',
  'önceki {} güne göre değişmedi':
      'sin cambios frente a los {} días anteriores',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'Visualizaciones diarias: mínimo {}, máximo {}',
  'Etkileşim oranı henüz ölçülemedi':
      'La tasa de interacción aún no se puede medir',
  'Oranlar': 'Tasas',
  'Beğenme oranı': 'Tasa de me gusta',
  'Yorum oranı': 'Tasa de comentarios',
  'Paylaşma oranı': 'Tasa de compartidos',
  'İçeriğe gitme oranı': 'Tasa de toques',
  'Profile gitme oranı': 'Tasa de visitas',
  'Ziyaretten takibe dönüşüm': 'De visita a seguidor',
  'beğeni ÷ görüntülenme': 'me gusta ÷ visualizaciones',
  'yorum ÷ görüntülenme': 'comentarios ÷ visualizaciones',
  'paylaşım ÷ görüntülenme': 'compartidos ÷ visualizaciones',
  'içeriğe tıklama ÷ görüntülenme': 'toques en el contenido ÷ visualizaciones',
  'profil ziyareti ÷ görüntülenme': 'visitas al perfil ÷ visualizaciones',
  'yeni takip ÷ profil ziyareti': 'nuevos seguidores ÷ visitas al perfil',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'Las tasas necesitan al menos {} visualizaciones; ahora hay {}.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'Las tasas salen de los totales de la publicación desde su inicio; la selección de días de abajo no las cambia.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'Estos números son los totales de la publicación desde su inicio (salvo los recuadros con su propia nota); la selección de días de abajo solo cambia el gráfico.',
  'Ortalama izlenme: videonun %{} kadarı': 'Reproducción media: {}% del video',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'El promedio de los 20 tramos de la curva.',
  'Dizi, film, kişi veya şirket ara...':
      'Busca series, películas, personas o compañías...',
  'Şirketler': 'Compañías',
  'Senarist': 'Guionista',
  'Bölüm puanları': 'Puntuaciones de episodios',
  'S{}': 'T{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'No se pudieron cargar las puntuaciones',
  'Giriş gerekli': 'Tienes que iniciar sesión',
  'Geçersiz oturum': 'Sesión no válida',
  'Oturum sonlandı, tekrar giriş yap': 'La sesión terminó, vuelve a entrar',
  'Çok fazla istek; biraz sonra tekrar dene':
      'Demasiadas solicitudes; prueba en un rato',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'No hay espacio en el servidor ahora mismo, inténtalo en un momento',
  'Devam eden yapımlar ({})': 'Producciones en curso ({})',
  'Diziler ({})': 'Series ({})',
  'Filmler ({})': 'Películas ({})',
  'Tüm yapımlar': 'Todas las producciones',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'Tu espacio para medios está lleno; borra subidas antiguas para liberar espacio',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'Correo/usuario o contraseña incorrectos',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'Este correo o usuario ya está registrado',
  'Google doğrulaması başarısız': 'Falló la verificación de Google',
  'Kod geçersiz veya süresi dolmuş': 'El código no vale o caducó',
  'Bu kullanıcıyla mesajlaşamazsın': 'No puedes escribirle a este usuario',
  'Kendini takip edemezsin': 'No puedes seguirte a ti',
  'Bu kullanıcıyı takip edemezsin': 'No puedes seguir a este usuario',
  'Kendini engelleyemezsin': 'No puedes bloquearte a ti',
  'Yorum 1-1000 karakter olmalı': 'El comentario debe tener 1–1000 caracteres',
  'Boş mesaj gönderilemez': 'No puedes enviar un mensaje vacío',
  'Yorum bulunamadı': 'Comentario no encontrado',
  'Şifre hatalı': 'Contraseña incorrecta',
  'Şifre en az 6 karakter olmalı':
      'La contraseña debe tener al menos 6 caracteres',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'Solo se pueden subir GIF, PNG, JPEG o WebP',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'Tipos admitidos: GIF, PNG, JPEG, WebP, MP4, WebM, audio',
  'Geçerli bir ZIP dosyası değil': 'No es un ZIP válido',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'Para recibir tus datos por correo, vincula un e-mail primero',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'Tienes marcas de visto. Para ponerlo en "Pendientes" hay que borrarlas primero.',
  'Arama şu anda kapalı': 'Las llamadas están desactivadas ahora',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'Las cuentas invitado no pueden activar llamadas; crea una cuenta',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'El servidor se está reiniciando; prueba en un momento',
  'Puan 1-10 arası olmalı': 'La nota debe estar entre 1 y 10',
  'En fazla 10 medya eklenebilir': 'Puedes añadir 10 archivos como máximo',
  'Bu cihazdan yeni hesap açılamıyor':
      'No se puede crear una cuenta desde este dispositivo',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'Hace falta un correo válido, un nombre de usuario y una contraseña de al menos 6 caracteres',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'Hace falta un correo válido y una contraseña de al menos 6 caracteres',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'El nombre debe tener 3–20 caracteres; minúsculas, dígitos, puntos, guiones y guiones bajos (no al inicio ni al final)',
  'Bu hesap zaten bağlı': 'Esta cuenta ya está vinculada',
  'Hesap oluşturulamadı': 'No se pudo crear la cuenta',
  'Misafir hesabı oluşturulamadı': 'No se pudo crear una cuenta de invitado',
  'Hesap bulunamadı': 'Cuenta no encontrada',
  'Bu hesapta e-posta yok': 'Esta cuenta no tiene correo',
  'İki adımlı doğrulama zaten bu durumda':
      'La verificación en dos pasos ya está así',
  'Kod yanlış': 'Código incorrecto',
  'Kodun süresi doldu': 'El código caducó',
  'Kullanıcının e-postası yok (misafir hesap)':
      'Este usuario no tiene correo (cuenta invitado)',
  'Bio en fazla 300 karakter olabilir':
      'La bio puede tener 300 caracteres como máximo',
  'Geçersiz ülke': 'País no válido',
  'Geçersiz sosyal bağlantı': 'Enlace social no válido',
  'Geçersiz doğum tarihi': 'Fecha de nacimiento no válida',
  'Liste adı gerekli': 'El nombre de la lista es obligatorio',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'El nombre puede tener 60 caracteres, la descripción 300',
  'Liste bulunamadı': 'Lista no encontrada',
  'Değiştirilecek tercih yok': 'No hay nada que actualizar',
  'İnceleme en fazla 2000 karakter olabilir':
      'La reseña puede tener 2000 caracteres como máximo',
  'Önce içeriği "bitirdim" olarak işaretle':
      'Marca el título como terminado primero',
  'Önce kişiyi favorile': 'Marca a la persona como favorita primero',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'Para un comentario de episodio hacen falta temporada y episodio',
  'Yanıtlanan yorum bulunamadı':
      'No se encontró el comentario al que respondes',
  'Geri bildirim 3-2000 karakter olmalı':
      'Los comentarios deben tener 3–2000 caracteres',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'Hacen falta título y texto (al menos 2 caracteres)',
  'Kendine mesaj gönderemezsin': 'No puedes enviarte un mensaje a ti',
  'Mesaj en fazla 2000 karakter olabilir':
      'El mensaje puede tener 2000 caracteres como máximo',
  'Mesaj 1-2000 karakter olmalı': 'El mensaje debe tener 1–2000 caracteres',
  'Mesaj bulunamadı': 'Mensaje no encontrado',
  'Mesaj bulunamadı veya düzenlenemez':
      'Mensaje no encontrado o no se puede editar',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'Solo puedes denunciar un mensaje que te hayan enviado',
  'Sebep gerekli': 'El motivo es obligatorio',
  'İtiraz edilecek aktif bir ceza yok': 'No hay una sanción activa que apelar',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'Ya tienes una apelación pendiente de revisión',
  'Bu ceza için itirazın zaten incelendi':
      'Tu apelación por esta sanción ya fue revisada',
  'Medya bağlantısının süresi dolmuş': 'El enlace de media caducó',
  'Bu medya için imzalı bağlantı gerekli':
      'Hace falta un enlace firmado para este archivo',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'El servicio de llamadas se está reiniciando; prueba en un rato',
  'Puan göstergesi': 'Leyenda de puntuación',
  'İzleme İstatistiklerim': 'Mis estadísticas de visionado',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'Cuando marques un episodio o una película como visto, tus estadísticas empezarán a acumularse aquí.',
  '{} sa {} dk': '{} h {} min',
  'Yaklaşık ekran süresi': 'Tiempo de pantalla aproximado',
  'İzleme serisi': 'Racha de visionado',
  'Şu anki seri': 'Racha actual',
  'En uzun seri': 'Racha más larga',
  'Haftanın günleri': 'Días de la semana',
  'En çok izlediklerin': 'Lo más visto',
  'Bu dönemde izleme yok': 'No hay visionados en este periodo',
  'Tüm zamanlar: {} bölüm · {} film · ~{}':
      'Histórico: {} episodios · {} películas · ~{}',
  'Paz': 'Dom',
  'Pzt': 'Lun',
  'Sal': 'Mar',
  'Çar': 'Mié',
  'Per': 'Jue',
  'Cum': 'Vie',
  'Cmt': 'Sáb',
  '{} bölüm': '{} episodios',
  '{} bölüm~tekil': '{} episodio',
  '{} kez': '{} veces',
  '{} kez~tekil': '{} vez',
  'Son {} gün · günlük': 'Últimos {} días · diario',
  'Son {} gün · haftalık': 'Últimos {} días · semanal',
  'Ekran süren, serin ve en çok izlediklerin':
      'Tu tiempo de pantalla, racha y lo más visto',
  'Daralt': 'Contraer',
  'Listeyi düzenle': 'Editar lista',
  'Bitti': 'Listo',
  'Sırala': 'Reordenar',
  'Herkese göster': 'Mostrar a todos',
  'Başkalarından gizle': 'Ocultar a los demás',
  'Listeden kaldır': 'Quitar de la lista',
  'Listeden kaldırılsın mı?': '¿Quitar de la lista?',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'Este título saldrá de la lista. Si solo quieres ocultarlo, usa el icono del ojo.',
  'Sıralama kaydedilemedi': 'No se pudo guardar el orden',
  'Değişiklik kaydedilemedi': 'No se pudo guardar el cambio',
  'Kaldırılamadı': 'No se pudo quitar',
  'Popülerlik': 'Popularidad',
  'TMDB puanı': 'Puntuación de TMDB',
  'Yapım yılı': 'Año de estreno',
  'dizi.jpg puanı': 'Puntuación de dizi.jpg',
  'İzlenme': 'Visualizaciones',
  'Yorum sayısı': 'Número de comentarios',
  'Tüm raflara uygulanır': 'Se aplica a todos los estantes',
  'En popüler {} yapım arasında sıralandı':
      'Ordenado entre los {} títulos más populares',
};
