/// Otomatik üretilen çeviri haritası (mr).
const Map<String, String> cevirilerMr = {
  'Hepsini gördün, baştan gösteriyoruz':
      'तुम्ही हे सर्व पाहिले आहे, आम्ही तुम्हाला सुरुवातीपासून दाखवतो',
  'Aktarılacak tanınan veri bulunamadı.':
      'इंपोर्ट करण्यासारखा कोणताही डेटा सापडला नाही.',
  'Arama': 'शोध',
  'Aramaya başla': 'शोधायला सुरुवात करा',
  'Son aramalar': 'अलीकडील शोध',
  'Ayarlar': 'सेटिंग्ज',
  'Bağla': 'लिंक करा',
  'Bio': 'बायो',
  'Bitirdim': 'पूर्ण केलं',
  'Bunları da Beğenebilirsin': 'हेही आवडू शकतील',
  'Bölüm': 'एपिसोड',
  'Bıraktım': 'सोडून दिलं',
  'Dil': 'भाषा',
  'Dil ara...': 'भाषा शोधा...',
  'Dizi': 'सीरीज',
  'Dizi ve filmlerini takip et': 'तुमचे शो आणि सिनेमे ट्रॅक करा',
  'Dizi yorumu': 'सीरीजवरील कमेंट',
  'Dizi, film veya kişi ara...': 'सीरीज, सिनेमा किंवा व्यक्ती शोधा...',
  'Dosya en fazla 30MB olabilir': 'फाइल जास्तीत जास्त 30MB असू शकते',
  'Dosya en fazla {}MB olabilir': 'फाइल जास्तीत जास्त {}MB असू शकते',
  'E-posta': 'ईमेल',
  'E-posta veya kullanıcı adı': 'ईमेल किंवा युजरनेम',
  'En az 2 harf yaz': 'किमान 2 अक्षरं लिहा',
  'Film': 'सिनेमा',
  'Film yorumu': 'सिनेमावरील कमेंट',
  'Fotoğraf / video ekle': 'फोटो / व्हिडिओ जोडा',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'फोटो किंवा GIF — प्रोफाइल आणि कव्हर इमेज',
  'Giriş Yap': 'लॉग इन करा',
  'Gönder': 'पाठवा',
  'Gönderildi': 'पाठवलं',
  'Haftanın Dizileri': 'या आठवड्याच्या सीरीज',
  'Haftanın Filmleri': 'या आठवड्याचे सिनेमे',
  'Henüz izleme kaydın yok': 'अजून कोणतीही वॉच हिस्टरी नाही',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'अजून कोणतीही लिस्ट नाही — प्रोफाइल टॅबमधून बनवा.',
  'Henüz yorum yok.': 'अजून कोणतीही कमेंट नाही.',
  'Hesabın bağlandı!': 'तुमचं अकाउंट लिंक झालं!',
  'Hesabın yok mu? Kayıt ol': 'अकाउंट नाही? साइन अप करा',
  'Hesabını Bağla': 'तुमचं अकाउंट लिंक करा',
  'Hesap Oluştur': 'अकाउंट बनवा',
  'Kapak resmi ekle': 'कव्हर इमेज जोडा',
  'Kaydet': 'सेव्ह करा',
  'Kendinden bahset...': 'स्वतःबद्दल सांगा...',
  'Keşfet': 'डिस्कव्हर',
  'Kimseyi takip etmiyor': 'कोणालाही फॉलो करत नाही',
  'Kişi ara': 'व्यक्ती शोधा',
  'Kişi yorumu': 'व्यक्तीवरील कमेंट',
  'Konuk Oyuncular': 'पाहुणे कलाकार',
  'Kullanıcı adı (küçük harf)': 'युजरनेम (लोअरकेस)',
  'Kullanıcı adı ara...': 'युजरनेम शोधा...',
  'Liste adı': 'लिस्टचं नाव',
  'Listeye Ekle': 'लिस्टमध्ये जोडा',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'तुम्ही गेस्ट अकाउंटवर आहात — ईमेलने लिंक करा, तुमचा डेटा गमावू नका!',
  'Misafir olarak devam et': 'गेस्ट म्हणून पुढे जा',
  'Oluştur': 'बनवा',
  'Oyuncular': 'कलाकार',
  'Profil': 'प्रोफाइल',
  'Profil kaydedildi': 'प्रोफाइल सेव्ह झालं',
  'Puanla': 'रेट करा',
  'Puanı Sil': 'रेटिंग काढून टाका',
  'Puanın': 'तुमचं रेटिंग',
  'Sezonlar': 'सीझन',
  'Sunucu hatası ({})': 'सर्व्हर एरर ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'S{}E{} कमेंट',
  'Takibi Bırak': 'अनफॉलो करा',
  'Takip': 'फॉलोइंग',
  'Takip Edilenler': 'फॉलो केलेले',
  'Takip Et': 'फॉलो करा',
  'Takipçi': 'फॉलोअर',
  'Takipçi yok': 'फॉलोअर नाहीत',
  'Takipçiler': 'फॉलोअर्स',
  'Takvim': 'कॅलेंडर',
  'Tamam': 'ठीक आहे',
  'Tekrar Dene': 'पुन्हा प्रयत्न करा',
  'Tekrar dene': 'पुन्हा प्रयत्न करा',
  'Toplam İzleme Süresi': 'एकूण स्क्रीन टाइम',
  'Tüm Zamanların En İyileri': 'सर्वकालीन सर्वोत्तम',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'तुमचा सगळा डेटा (वॉच हिस्टरी, रेटिंग, कमेंट, लिस्ट) TV Time-सुसंगत ZIP म्हणून घ्या किंवा दुसऱ्या ॲपमधून आलेली ZIP इंपोर्ट करा.',
  'Tümünü Kaldır': 'सगळं काढून टाका',
  'Tümünü İzledim': 'सगळं पाहिलं',
  'Türk Dizileri': 'तुर्की सीरीज',
  'Veri içe aktar (.zip)': 'डेटा इंपोर्ट करा (.zip)',
  'Verilerim': 'माझा डेटा',
  'Verilerimi dışa aktar (e-posta)': 'माझा डेटा एक्स्पोर्ट करा (ईमेल)',
  'Verilerini dışa aktar': 'तुमचा डेटा एक्स्पोर्ट करा',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'आगामी एपिसोड नाही.\nसीरीजच्या पेजवरून "पाहत आहे" स्टेटस निवडा, नवे एपिसोड इथे ट्रॅक करा.',
  'Yapımları': 'फिल्मोग्राफी',
  'Yeni Diziler': 'नव्या सीरीज',
  'Yeni Liste': 'नवी लिस्ट',
  'Yeni kullanıcı adı (isteğe bağlı)': 'नवा युजरनेम (ऐच्छिक)',
  'Yorum': 'कमेंट',
  'Yorumunu yaz...': 'तुमची कमेंट लिहा...',
  'Zaten hesabın var mı? Giriş yap': 'आधीच अकाउंट आहे? लॉग इन करा',
  'ort. {}': 'सरासरी {}',
  'takip': 'फॉलोइंग',
  'takipçi': 'फॉलोअर',
  '{} / {} bölüm': '{} / {} एपिसोड',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} महिने',
  '{} ay~tekil': '{} महिना',
  '{} bölüm izlendi': '{} एपिसोड पाहिले',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} मिनिटं',
  '{} dk~tekil': '{} मिनिट',
  '{} gün': '{} दिवस',
  '{} gün~tekil': '{} दिवस',
  '{} içerik': '{} टायटल',
  '{} içerik · otomatik': '{} टायटल · ऑटोमॅटिक',
  '{} kayıt atlandı (eşleşmedi).': '{} रेकॉर्ड वगळले (जुळले नाहीत).',
  '{} saat': '{} तास',
  '{} saat~tekil': '{} तास',
  '{} sezon': '{} सीझन',
  '{} yıl': '{} वर्षं',
  '{} yıl~tekil': '{} वर्ष',
  '{}. Bölüm': 'एपिसोड {}',
  '{}. Sezon': 'सीझन {}',
  'Çıkış Yap': 'लॉग आउट करा',
  'Ülke': 'देश',
  'Ülke ara...': 'देश शोधा...',
  'Ülke seç': 'देश निवडा',
  'İlk yorumu sen yaz!': 'पहिली कमेंट तुम्हीच लिहा!',
  'İncelemeler': 'रिव्ह्यू',
  'İncelemen (isteğe bağlı)': 'तुमचा रिव्ह्यू (ऐच्छिक)',
  'İptal': 'रद्द करा',
  'İzlediklerim': 'मी पाहिलेले',
  'İzledim': 'पाहिलं',
  'İzledin': 'तुम्ही पाहिलं',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'तुमची वॉच हिस्टरी आणि लिस्ट सुरक्षित राहतील; आता कोणत्याही डिव्हाइसवरून लॉग इन करू शकता.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'तुमची वॉच हिस्टरी, रेटिंग, कमेंट आणि लिस्ट ZIP स्वरूपात नोंदणीकृत ईमेल पत्त्यावर पाठवल्या जातील.',
  'İzleyeceğim': 'बघायचं आहे',
  'İzliyorum': 'पाहत आहे',
  'İçe aktarım tamamlandı': 'इंपोर्ट पूर्ण झालं',
  'Şifre': 'पासवर्ड',
  '• profil bilgisi': '• प्रोफाइल माहिती',
  '• {} dizi durumu': '• {} सीरीज स्टेटस',
  '• {} izleme kaydı': '• {} वॉच रेकॉर्ड',
  '• {} liste': '• {} लिस्ट',
  '• {} puan': '• {} रेटिंग',
  '• {} yorum': '• {} कमेंट',
  '{}+ yapım': '{}+ टायटल',
  'Yorumlar': 'कमेंट्स',
  'Yorumlar ({})': 'कमेंट्स ({})',
  'Yorumları ({})': 'यावरील कमेंट्स ({})',
  'Listelerim': 'माझ्या लिस्ट',
  'Nereden izledin?': 'कुठे पाहिले?',
  'Diziye git': 'शोवर जा',
  'TV / Kanal': 'टीव्ही / चॅनेल',
  'Sinema': 'सिनेमा',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'इतर',
  'Akış': 'फीड',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'तुझी फीड रिकामी आहे.\nतू पाहत असलेल्या शो व चित्रपटांवर कमेंट आल्या की इथे दिसतील.',
  'Listeleri ({})': 'त्यांच्या याद्या ({})',
  'Liste boş.': 'ही यादी रिकामी आहे.',
  'Yanıtla': 'उत्तर द्या',
  '@{} kullanıcısına yanıt veriyorsun': '@{} ला उत्तर देत आहेस',
  'İzlediğim Diziler ({})': 'मी पाहिलेले शो ({})',
  'İzlediğim Filmler ({})': 'मी पाहिलेले चित्रपट ({})',
  'Tümünü gör': 'सर्व पाहा',
  'Bildirimler': 'सूचना',
  'Henüz bildirim yok': 'अजून सूचना नाहीत',
  '@{} yorumuna yanıt verdi': '@{} ने तुझ्या कमेंटला उत्तर दिले',
  '@{} yorumunu beğendi': '@{} ला तुझी कमेंट आवडली',
  '@{} seni takip etti': '@{} ने तुला फॉलो केले',
  '@{} sana mesaj gönderdi': '@{} ने तुला संदेश पाठवला',
  'Mesajlar': 'संदेश',
  'Mesaj': 'संदेश',
  'Mesaja eklenecek': 'संदेशात जोडले जाईल',
  'Mesajını yaz...': 'संदेश लिही...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'अजून चॅट नाहीत.\nप्रोफाइलवर जाऊन संदेश पाठव.',
  'Şifreni mi unuttun?': 'पासवर्ड विसरलास?',
  'Şifreyi Sıfırla': 'पासवर्ड रीसेट करा',
  'E-postadaki kod': 'ईमेलमधील कोड',
  'Yeni şifre': 'नवा पासवर्ड',
  'Sana Özel': 'तुझ्यासाठी',
  '{} özetin': 'तुझा {} आढावा',
  'Yıllık izleme istatistiklerin': 'वार्षिक पाहण्याची आकडेवारी',
  'Rozetler': 'बॅज',
  'Verdiğin puan': 'दिलेली रेटिंग',
  'Ortalama puanın': 'सरासरी रेटिंग',
  'En çok izlediğin diziler': 'सर्वाधिक पाहिलेले शो',
  'İlk Bölüm': 'पहिला भाग',
  '100 Bölüm': '100 भाग',
  '1000 Bölüm': '1000 भाग',
  'İlk Film': 'पहिला चित्रपट',
  '50 Film': '50 चित्रपट',
  'İlk Yorum': 'पहिली कमेंट',
  '25 Yorum': '25 कमेंट',
  '10 Puan': '10 रेटिंग',
  'İlk Takipçi': 'पहिला फॉलोअर',
  '10 Dizi Bitirdin': '10 शो पूर्ण',
  'İzlemeyi Bıraktım': 'पाहणे सोडले',
  'İzlediği Diziler ({})': 'त्यांनी पाहिलेले शो ({})',
  'İzlediği Filmler ({})': 'त्यांनी पाहिलेले चित्रपट ({})',
  '500 Bölüm': '500 भाग',
  '5000 Bölüm': '5000 भाग',
  '10 Film': '10 चित्रपट',
  '100 Film': '100 चित्रपट',
  '100 Yorum': '100 कमेंट',
  '50 Puan': '50 रेटिंग',
  '100 Puan': '100 रेटिंग',
  '10 Takipçi': '10 फॉलोअर',
  '50 Takipçi': '50 फॉलोअर',
  '25 Dizi Bitirdin': '25 शो पूर्ण',
  '50 Dizi Bitirdin': '50 शो पूर्ण',
  '10 Beğeni': '10 लाइक',
  '100 Beğeni': '100 लाइक',
  'yazıyor...': 'टाइप करत आहे...',
  'Profil düzeni': 'प्रोफाइल मांडणी',
  'Konumla ve kırp': 'स्थिती ठरवा आणि क्रॉप करा',
  'Listeye eklendi': 'यादीत जोडले',
  'Listeyi sil?': 'यादी हटवायची?',
  'Sil': 'हटवा',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'हे कधीही न पाहिलेले म्हणून चिन्हांकित होईल आणि तुझ्या याद्यांतून निघेल.',
  'Gelecek bölüm bugün': 'पुढील भाग आज',
  'Gelecek bölüm {} gün sonra': 'पुढील भाग {} दिवसांनी',
  'Tema': 'थीम',
  'Sistem': 'सिस्टम',
  'Koyu': 'डार्क',
  'Açık': 'लाइट',
  'İzleyenler': 'प्रेक्षक',
  'Yorumunu yaz... (@ ile etiketle)':
      'तुमची टिप्पणी लिहा... (@ टॅग करण्यासाठी)',
  '@{} bir yorumda seni etiketledi': '@{} ने तुम्हाला एका टिप्पणीत टॅग केले',
  'Mesajı sil': 'संदेश हटवा',
  'Mesaj silinemedi': 'संदेश हटवता आला नाही',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'दुवा अवैध आहे किंवा पृष्ठ सापडले नाही',
  'Keşfet\'e dön': 'डिस्कव्हरकडे परत जा',
  'Düzenle': 'संपादित करा',
  'Mesajı düzenle': 'संदेश संपादित करा',
  'Yanıtlanıyor': 'उत्तर देत आहे',
  'düzenlendi': 'संपादित',
  'Fotoğraf': 'फोटो',
  'Video': 'व्हिडिओ',
  'İçerik': 'आशय',
  'çevrimiçi': 'ऑनलाइन',
  'son görülme {} dk önce': '{} मिनिटांपूर्वी पाहिले',
  'son görülme {} saat önce': '{} तासांपूर्वी पाहिले',
  'son görülme {} gün önce': '{} दिवसांपूर्वी पाहिले',
  'Yorumlar yüklenemedi': 'टिप्पण्या लोड करता आल्या नाहीत',
  'Favori': 'आवडते',
  'Listeye ekle': 'सूचीत जोडा',
  'İçerik paylaş': 'सामायिक करा',
  'Kapat': 'बंद करा',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'तुम्ही पाहिले म्हणून चिन्हांकित करता ते इथे जमा होते.',
  'Henüz sohbetin yok': 'अजून संभाषणे नाहीत',
  'Bir profile girip mesaj gönderebilirsin.': 'प्रोफाइल उघडा आणि संदेश पाठवा.',
  'Listeyi sil': 'सूची हटवा',
  'Puan kaydedilemedi': 'रेटिंग जतन करता आली नाही',
  'Nerede İzlenir': 'कुठे पाहावे',
  'Abonelik': 'सदस्यता',
  'Kirala': 'भाड्याने घ्या',
  'Satın al': 'खरेदी करा',
  'Hoş geldin!': 'स्वागत आहे!',
  'İzlemek istediğin dizi ve filmleri seç':
      'तुम्हाला पाहायचे असलेले शो आणि चित्रपट निवडा',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'तुमच्या निवडी तुमच्या वॉचलिस्टमध्ये जोडल्या जातील',
  'Şimdilik atla': 'आत्ता वगळा',
  'Devam et': 'सुरू ठेवा',
  '{} ekle': '{} जोडा',
  'Şikayet et': 'तक्रार करा',
  'Engelle': 'ब्लॉक करा',
  'Engeli kaldır': 'अनब्लॉक करा',
  'Kullanıcı engellendi': 'वापरकर्ता ब्लॉक केला',
  'Engel kaldırıldı': 'ब्लॉक काढला',
  'Şikayet sebebi': 'तक्रारीचे कारण',
  'Spam veya yanıltıcı': 'स्पॅम किंवा दिशाभूल करणारे',
  'Taciz veya nefret söylemi': 'छळ किंवा द्वेषपूर्ण भाषण',
  'Uygunsuz / cinsel içerik': 'अयोग्य / लैंगिक आशय',
  'Şiddet veya tehlikeli içerik': 'हिंसा किंवा धोकादायक आशय',
  'Telif hakkı ihlali': 'कॉपीराइट उल्लंघन',
  'Şikayetin alındı, teşekkürler': 'तुझी तक्रार मिळाली, धन्यवाद',
  'Hesabımı Sil': 'माझे खाते हटवा',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'तुझे खाते आणि सर्व डेटा (इतिहास, रेटिंग, कमेंट, याद्या, संदेश) कायमचा हटवला जाईल. हे परत करता येणार नाही.',
  'Şifreni gir': 'तुझा पासवर्ड टाक',
  'Hesabımı kalıcı sil': 'माझे खाते कायमचे हटवा',
  'Sesli mesaj': 'व्हॉइस मेसेज',
  'Ses gönderilemedi': 'व्हॉइस मेसेज पाठवता आला नाही',
  'Kaydediliyor…': 'रेकॉर्ड होत आहे…',
  'Ses oynatılamadı': 'ऑडिओ प्ले होऊ शकला नाही',
  'Oynat': 'प्ले कर',
  'Duraklat': 'थांबव',
  'Liste görünümü': 'सूची दृश्य',
  'Takvim görünümü': 'कॅलेंडर दृश्य',
  'Önceki ay': 'मागील महिना',
  'Sonraki ay': 'पुढील महिना',
  'Bu gün bölüm yok': 'या दिवशी कोणताही भाग नाही',
  'Gizlilik Politikası': 'गोपनीयता धोरण',
  'Son güncelleme: {}': 'शेवटचे अपडेट: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'dizi.jpg अ‍ॅप आणि dizijpg.com साइट वापरताना कोणता डेटा गोळा होतो, तो कसा वापरला जातो आणि तुझे हक्क काय आहेत, हे हे धोरण सांगते.',
  'Topladığımız Veriler': 'आम्ही गोळा करतो तो डेटा',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'खाते: ईमेल पत्ता, यूजरनेम आणि पासवर्ड. पासवर्ड परत वाचता न येणाऱ्या हॅश स्वरूपात ठेवले जातात; गेस्ट खाती ईमेलशिवायही वापरता येतात.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'प्रोफाइल: अवतार, कव्हर इमेज, बायो आणि देश यांसारखी तू स्वतः जोडलेली माहिती.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'वापर: तुझा पाहण्याचा इतिहास, रेटिंग, टिप्पण्या, याद्या, रिअ‍ॅक्शन आणि आवडते.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'संदेश: तुझे मजकूर, इमेज आणि व्हॉइस संदेश आमच्या सर्व्हरवर साठवले जातात. संदेश एंड-टू-एंड एनक्रिप्टेड नाहीत; तक्रार आल्यासच मॉडरेशनसाठी पाहिले जातात.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'अपलोड केलेला मीडिया: प्रोफाइल, टिप्पण्या आणि संदेशांत जोडलेले फोटो, GIF, व्हिडिओ आणि व्हॉइस रेकॉर्डिंग.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'तांत्रिक: IP पत्ता, अंदाजे स्थान (देश/शहर पातळी), डिव्हाइस प्लॅटफॉर्म, अ‍ॅप आवृत्ती आणि एरर लॉग. हे सुरक्षा आणि दोष दुरुस्तीसाठी ठेवले जातात.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'सूचना: पुश सूचनांसाठी तुझ्या डिव्हाइसचा टोकन आणि भाषेची निवड साठवली जाते. डिव्हाइसच्या सेटिंग्जमधून सूचना कधीही बंद करू शकतोस.',
  'Verileri Nasıl Kullanırız': 'आम्ही डेटा कसा वापरतो',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'तुझा डेटा फक्त सेवा देणे, खाते सुरक्षित ठेवणे, सूचना पाठवणे, दोष दुरुस्त करणे आणि गैरवापर रोखणे यासाठीच वापरतो. आम्ही तुझा डेटा विकत नाही आणि जाहिरातीसाठी कोणाशीही शेअर करत नाही.',
  'Çerezler ve Yerel Depolama': 'कुकीज आणि लोकल स्टोरेज',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'लोकल स्टोरेज फक्त तुला लॉग-इन ठेवण्यासाठी आणि भाषा/थीमसारख्या आवडी लक्षात ठेवण्यासाठी वापरले जाते. जाहिरात किंवा ट्रॅकिंग कुकीज नाहीत.',
  'Üçüncü Taraf Hizmetler': 'तृतीय-पक्ष सेवा',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'मालिका आणि चित्रपटांचा डेटा TMDB कडून, स्ट्रीमिंग प्लॅटफॉर्मची माहिती JustWatch कडून येते. पुश सूचना Google Firebase मार्फत पोहोचतात आणि साइटची वाहतूक Cloudflare सुरक्षित ठेवते. या सेवांना त्यांची स्वतःची गोपनीयता धोरणे लागू होतात.',
  'Saklama ve Silme': 'साठवण आणि हटवणे',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'तुझे खाते असेपर्यंत तुझा डेटा राहतो. सेटिंग्जमधील "माझे खाते हटवा" ने खाते कायमचे हटवू शकतोस; डेटा लगेच आणि बॅकअपमधील प्रती जास्तीत जास्त १४ दिवसांत हटतात. एरर लॉग ३० दिवसांनी आपोआप हटतात.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'सेटिंग्जमधून तुझा डेटा ZIP स्वरूपात निर्यात करू शकतोस; संग्रह तुझ्या ईमेल पत्त्यावर पाठवला जातो.',
  'Güvenlik': 'सुरक्षा',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'डेटा एनक्रिप्टेड कनेक्शनने (HTTPS) जातो आणि मर्यादित प्रवेश असलेल्या सर्व्हरवर साठवला जातो.',
  'Çocukların Gizliliği': 'मुलांची गोपनीयता',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg हे १३ वर्षांखालील मुलांसाठी नाही.',
  'Hakların': 'तुझे हक्क',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK आणि GDPR अंतर्गत तुला तुझ्या डेटामध्ये प्रवेश, दुरुस्ती, हटवणे आणि हस्तांतरणाचा हक्क आहे. यासाठी आम्हाला लिही: {}',
  'Değişiklikler': 'बदल',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'हे धोरण बदलल्यास नवी आवृत्ती याच पानावर प्रसिद्ध होईल आणि तारीख अपडेट होईल.',
  'Kayıt olarak {} kabul etmiş olursun.': 'नोंदणी करून तू {} स्वीकारतोस.',
  'Kullanıcılar': 'वापरकर्ते',
  'Fotoğrafı değiştir': 'फोटो बदल',
  'Yeniden konumlandır': 'पुन्हा जुळव',
  'Bir şeyler ters gitti': 'काहीतरी चुकले',
  'Sosyal Bağlantılar': 'सोशल लिंक',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'तुझ्या प्रोफाइलवर जास्तीत जास्त ३ लिंक दिसतात.',
  'Platform seç': 'प्लॅटफॉर्म निवड',
  'Kullanıcı adın': 'तुझे यूजरनेम',
  'Ekle': 'जोड',
  'Kaldır': 'काढ',
  'Kopyalandı: {}': 'कॉपी झाले: {}',
  'Geçersiz kullanıcı adı': 'चुकीचे यूजरनेम',
  'Bağlantı ekle': 'लिंक जोड',
  'Spoiler olabilir — dokun ve gör': 'स्पॉयलर असू शकतो — पाहण्यासाठी टॅप कर',
  'Beğeni': 'लाइक',
  'Beğen': 'लाईक',
  'Görüntülenme': 'व्ह्यू',
  'Tam ekran': 'फुल स्क्रीन',
  'Arama başarısız': 'शोध अयशस्वी झाला',
  'Sonuç bulunamadı': 'निकाल सापडला नाही',
  'Dizi ve Filmler': 'मालिका आणि चित्रपट',
  'Kişiler': 'व्यक्ती',
  'Ana Sayfa': 'होम',
  'Paylaş': 'शेअर',
  'Yanıtlar': 'उत्तरे',
  'Yaklaşan Bölümler': 'आगामी भाग',
  'Yetişme Listesi': 'कॅच-अप यादी',
  'Şunu mu demek istedin': 'तुम्हाला हे म्हणायचे होते का',
  'Spoiler': 'स्पॉयलर',
  'Spoiler — dokun ve gör': 'स्पॉयलर — पाहण्यासाठी टॅप करा',
  'uyum': 'जुळणी',
  'Uyum': 'जुळणी',
  '{} ortak dizi': '{} समान मालिका',
  '{} ortak film': '{} समान चित्रपट',
  'Bildirim Tercihleri': 'सूचना प्राधान्ये',
  'Beğeniler': 'आवडी',
  'Yeni takipçiler': 'नवीन अनुयायी',
  'Etiketlenmeler': 'उल्लेख',
  'Yeniden izledim': 'पुन्हा पाहिले',
  '{}. kez izlendi': '{} वेळा पाहिले',
  'Gönderi bulunamadı': 'पोस्ट सापडली नाही',
  'Gözat': 'ब्राउझ करा',
  'Diziler': 'मालिका',
  'Filmler': 'चित्रपट',
  'Tümü': 'सर्व',
  'Farklı bir tür seç.': 'दुसरा प्रकार वापरून पहा.',
  'Gizlilik': 'गोपनीयता',
  'İzlediklerimi gizle': 'मी पाहिलेले लपवा',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'तू पाहिलेल्या मालिका आणि चित्रपट तुझ्या प्रोफाइलवर दिसणार नाहीत',
  'Yorumlarımı gizle': 'माझ्या कमेंट लपवा',
  'Profilinde yorumların görünmez':
      'तुझ्या कमेंट तुझ्या प्रोफाइलवर दिसणार नाहीत',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'एखादी मालिका किंवा चित्रपट त्याच्या पेजवरील "माझ्या प्रोफाइलवर लपवा" चिपने लपवता येतो.',
  'Geri Bildirim': 'फीडबॅक',
  'Uygulama hakkında görüş ve önerini yaz...':
      'अ‍ॅपबद्दल तुझे मत आणि सूचना लिही...',
  'Teşekkürler! Geri bildirimin alındı.': 'धन्यवाद! तुझा फीडबॅक मिळाला.',
  'Profilimde gizle': 'माझ्या प्रोफाइलवर लपवा',
  'Yorumları': 'यावरील कमेंट्स',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'या वापरकर्त्याने अद्याप काहीही पाहिलेले नाही.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'हा वापरकर्ता आपल्या कमेंट खाजगी ठेवणे पसंत करतो.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'डेटा: JustWatch',
  'Web Sitesi': 'वेबसाइट',
  'Diğer uygulamalar': 'इतर अ‍ॅप्स',
  'Bağlantıyı kopyala': 'लिंक कॉपी करा',
  'Henüz kimseyi takip etmiyorsun.': 'तू अजून कुणालाही फॉलो करत नाहीस.',
  'Çevir': 'भाषांतर करा',
  'Çeviri şu an yapılamadı': 'सध्या भाषांतर शक्य नाही',
  'Bağlantı açılamadı': 'दुवा उघडता आला नाही',
  'Orijinali göster': 'मूळ दाखवा',
  'Çeviriyi göster': 'भाषांतर दाखवा',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'या महिन्यात प्रसारण तारीख जाहीर झालेला कोणताही भाग नाही. तारखा साधारणतः काही आठवडे आधी जाहीर होतात आणि नंतर इथे दिसतील.',
  'devamı': 'अधिक',
  'Google ile devam et': 'Google सह सुरू ठेवा',
  'Google girişi başarısız': 'Google साइन-इन अयशस्वी झाले',
  'Veri tasarrufu': 'डेटा बचत',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi वर डेटा बचत',
  'Mobil veride veri tasarrufu': 'मोबाइल डेटावर डेटा बचत',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'चालू असताना फोटो आधीच डाउनलोड होत नाहीत, फक्त तू बघत असलेली प्रतिमा लोड होते.',
  'Çocuk güvenliği': 'बाल सुरक्षा',
  'Türk Filmleri': 'तुर्की चित्रपट',
  'En Yüksek Puanlı Filmler': 'सर्वाधिक रेटिंग असलेले चित्रपट',
  'En Yüksek Puanlı Diziler': 'सर्वाधिक रेटिंग असलेल्या मालिका',
  'En Çok İzlenen Filmler': 'सर्वाधिक पाहिलेले चित्रपट',
  'Popüler Diziler': 'लोकप्रिय मालिका',
  'En Çok Kazanan Filmler': 'सर्वाधिक कमाई करणारे चित्रपट',
  'Kült Filmler': 'कल्ट चित्रपट',
  'Yeni Filmler': 'नवीन चित्रपट',
  'Yorum yap': 'टिप्पणी करा',
  'Henüz yorum yok': 'अजून टिप्पणी नाही',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'मालिका आणि चित्रपटांवरील तुझ्या टिप्पण्या इथे जमा होतात.',
  'GIF ekle': 'GIF जोडा',
  'İlk yorumu sen yaz': 'पहिली टिप्पणी तुम्ही लिहा',
  'Video altyazıları': 'व्हिडिओ उपशीर्षके',
  'Videolarda altyazı göster': 'व्हिडिओंवर सबटायटल्स दाखवा',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'व्हिडिओमध्ये बोललेले वाक्य स्क्रीनवर लिहिलेले आहे. मजकूर अनुवाद आहे: तुर्की भाषणात इंग्रजी, इतर भाषांमध्ये तुर्की.',
  "Güncelleme gerekli": "अपडेट आवश्यक आहे",
  "Yeni sürüm var": "नवीन आवृत्ती उपलब्ध आहे",
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      "सुरू ठेवण्यासाठी dizi.jpg ची नवीन आवृत्ती इंस्टॉल करा.",
  "Güncelle": "अपडेट करा",
  "Daha sonra": "नंतर",
  'Takvim güncelleniyor': 'कॅलेंडर अपडेट होत आहे',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'कॅलेंडर अपडेट होऊ शकले नाही, जुनी यादी दाखवली जात आहे',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'काही मालिका लोड होऊ शकल्या नाहीत, यादी अपूर्ण असू शकते',
  'Yenile': 'रिफ्रेश',
  'Devam etmek için giriş yap': 'सुरू ठेवण्यासाठी लॉग इन करा',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'गुण देण्यासाठी, टिप्पणी लिहिण्यासाठी आणि तुमची लायब्ररी बनवण्यासाठी मोफत खाते पुरेसे आहे.',
  'Şimdi değil': 'आता नको',
  'Yorum yazmak için giriş yap': 'टिप्पणी लिहिण्यासाठी लॉग इन करा',
  'Kişilere göndermek için giriş yap': 'लोकांना पाठवण्यासाठी लॉग इन करा',
  'Beğenenler': 'आवडलेले',
  'Henüz beğeni yok': 'अद्याप कोणतीही पसंती नाही',
  'Bu gönderiyi ilk beğenen sen ol': 'ही पोस्ट पसंत करणारे पहिले व्हा',
  'Bu gönderiye yanıt': 'या पोस्टला उत्तर',
  'Spoiler içeren gönderi': 'स्पॉयलर असलेली पोस्ट',
  'Görsel gönderi': 'फोटो पोस्ट',
  'Bu yorumu profilimde gizle': 'ही कमेंट माझ्या प्रोफाइलवरून लपवा',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'कमेंट शो आणि चित्रपटाच्या पेजवर राहते',
  'Bu yorumu sil': 'ही कमेंट डिलीट करा',
  'Yorum profilinde gizlendi': 'कमेंट तुझ्या प्रोफाइलवरून लपवली गेली',
  'Geri al': 'पूर्ववत करा',
  'Yorum silinsin mi?': 'कमेंट डिलीट करायची का?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'ही कमेंट सगळीकडून कायमची डिलीट होईल. ती परत आणता येणार नाही.',
  'Yorum silindi': 'कमेंट डिलीट झाली',
  'Yorum profilinde tekrar görünüyor':
      'कमेंट तुझ्या प्रोफाइलवर पुन्हा दिसत आहे',
  'Gizlenen yorumun yok': 'तुझी कोणतीही लपवलेली कमेंट नाही',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'तुझ्या प्रोफाइलच्या कमेंट्स टॅबमध्ये एखाद्या पोस्टवर दाबून धरून तू ज्या कमेंट्स लपवतोस, त्या इथे जमा होतात.',
  'Gizlenen yorumlar': 'लपवलेल्या कमेंट्स',
  'Gönderiye git': 'पोस्टवर जा',
  'Tekrar göster': 'पुन्हा दाखवा',
  'Yanıtlarımı gizle': 'माझी उत्तरे लपवा',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'इतरांच्या पोस्टवर तू लिहिलेली उत्तरे फक्त तुलाच दिसतात',
  'Profilinde gizlediğin yorumları tekrar göster':
      'तुझ्या प्रोफाइलवर लपवलेल्या कमेंट्स पुन्हा दाखवा',
  'Sıralama': 'क्रमवारी',
  'Önerilen': 'शिफारस केलेले',
  'Kronolojik': 'कालक्रमानुसार',
  'Gelen mesaj istekleri': 'आलेल्या संदेश विनंत्या',
  'Mesaj isteğin yok': 'संदेश विनंती नाही',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'तुम्ही फॉलो न करणाऱ्या लोकांचे संदेश येथे दिसतात.',
  'Çevrimiçi durumumu gizle': 'माझी ऑनलाइन स्थिती लपवा',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'इतरांना संदेशांमध्ये तुमची ऑनलाइन स्थिती आणि शेवटचे पाहिले वेळ दिसणार नाही',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'आमच्या पहिल्या वापरकर्त्यांपैकी एक. त्यांच्या अभिप्रायामुळे अ‍ॅप आज जसे आहे तसे झाले.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'तू आमच्या पहिल्या वापरकर्त्यांपैकी एक आहेस. तुझ्या अभिप्रायामुळे अ‍ॅप आज जसे आहे तसे झाले.',
  'İleri': 'पुढे',
  'Seçilen dosya okunamadı': 'निवडलेली फाइल वाचता आली नाही',
  'Video açılamadı': 'व्हिडिओ उघडता आला नाही',
  'En fazla {} medya seçebilirsin': 'तुम्ही जास्तीत जास्त {} मीडिया निवडू शकता',
  'Hiçbir medya yüklenemedi': 'कोणतीही मीडिया अपलोड होऊ शकली नाही',
  'Seçimi kaldır': 'निवड काढा',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'एका टिप्पणीत एकूण {} MB मीडिया अपलोड करू शकता',
  '{} dosya okunamadı': '{} फाइल वाचता आल्या नाहीत',
  '{} medya eklendi, {} yüklenemedi': '{} मीडिया जोडली, {} अयशस्वी',
  'Kırp': 'क्रॉप',
  'Çiz': 'काढा',
  'Metin': 'मजकूर',
  'Emoji': 'इमोजी',
  'Yinele': 'पुन्हा करा',
  'Daha fazla': 'अधिक',
  'Hazırlanıyor…': 'तयार करत आहे…',
  'Düzenlemeden çık?': 'संपादन सोडायचे?',
  'Yaptığın değişiklikler kaybolacak.': 'तुम्ही केलेले बदल हरवतील.',
  'Çık': 'बाहेर पडा',
  'Serbest çizim': 'मुक्त रेखाटन',
  'Ok': 'बाण',
  'Dikdörtgen': 'आयत',
  'Daire': 'वर्तुळ',
  'Bulanıklaştır': 'अस्पष्ट करा',
  'Pikselleştir': 'पिक्सेल करा',
  'Silgi': 'खोडरबर',
  'Çizgi kalınlığı': 'रेषेची जाडी',
  'Saydamlık': 'पारदर्शकता',
  'Dolgu': 'भरा',
  'Renk': 'रंग',
  'Döndür': 'फिरवा',
  'Yansıt': 'उलटा करा',
  'Oran': 'गुणोत्तर',
  'Sıfırla': 'रीसेट करा',
  'Serbest': 'मुक्त',
  'Metin yaz...': 'मजकूर लिहा...',
  'Hizala': 'संरेखित करा',
  'Arka plan': 'पार्श्वभूमी',
  'Emoji ara...': 'इमोजी शोधा...',
  'Son kullanılanlar': 'अलीकडील',
  'İfadeler ve insanlar': 'स्माइली आणि लोक',
  'Hayvanlar ve doğa': 'प्राणी आणि निसर्ग',
  'Yiyecek ve içecek': 'अन्न आणि पेय',
  'Etkinlikler': 'क्रियाकलाप',
  'Seyahat ve yerler': 'प्रवास आणि ठिकाणे',
  'Nesneler': 'वस्तू',
  'Semboller': 'चिन्हे',
  'Bayraklar': 'ध्वज',
  'Görseli düzenle': 'प्रतिमा संपादित करा',
  'Düzenlendi': 'संपादित',
  'Düzenlenemedi': 'संपादित करता आले नाही',
  'Düzenlenen görsel çok büyük': 'संपादित प्रतिमा खूप मोठी आहे',
  'Videoyu düzenle': 'व्हिडिओ संपादित करा',
  'Sesi kapat': 'आवाज बंद करा',
  'Sesi aç': 'आवाज सुरू करा',
  'İptal ediliyor…': 'रद्द करत आहे…',
  'Bu biraz sürebilir': 'याला थोडा वेळ लागू शकतो',
  'Video çok büyük': 'व्हिडिओ खूप मोठा आहे',
  'Video hazırlanamadı': 'व्हिडिओ तयार करता आला नाही',
  'Başlangıç': 'सुरुवात',
  'Bitiş': 'शेवट',
  'En çok {} saniye seçebilirsin': 'तुम्ही जास्तीत जास्त {} सेकंद निवडू शकता',
  'Dosya en fazla {} MB olabilir': 'फाइल जास्तीत जास्त {} MB असू शकते',
  'Medya ekle': 'मीडिया जोडा',
  'Seçili medya kalmadı': 'कोणतेही मीडिया निवडलेले नाही',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'तुमच्या टिप्पणीत जोडण्यासाठी फोटो किंवा व्हिडिओ निवडा.',
  'Medya seç': 'मीडिया निवडा',
  'Daha fazla ekle': 'आणखी जोडा',
  'Medya seçilemedi': 'मीडिया निवडता आले नाही',
  'Favori oyuncular': 'आवडते कलाकार',
  'Henüz favori oyuncun yok': 'अजून आवडते कलाकार नाहीत',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'कलाकाराचे पान उघडा आणि वरच्या उजव्या कोपऱ्यातील हृदयावर टॅप करा.',
  '{} yapımdan {} tanesini izledin': '{} पैकी {} पाहिले',
  'izledin': 'पाहिले',
  'İzlemedin': 'पाहिले नाही',
  'Yapım bulunamadı': 'कोणतेही शीर्षक सापडले नाही',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'या व्यक्तीच्या मालिका किंवा चित्रपट नाहीत.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'तुमचा इतिहास तुमच्या खात्याशी जोडलेला आहे; ही यादी फक्त तुमची आहे.',
  'Hesabın kalıcı olarak askıya alındı':
      'तुमचे खाते कायमचे निलंबित करण्यात आले आहे',
  'Hesabın geçici olarak askıya alındı':
      'तुमचे खाते तात्पुरते निलंबित करण्यात आले आहे',
  'Hesabın askıya alındı': 'तुमचे खाते निलंबित आहे',
  'Sebep': 'कारण',
  'Kalan süre': 'उरलेला वेळ',
  'Süre dolunca hesabın kendiliğinden açılır':
      'मुदत संपल्यावर तुमचे खाते आपोआप सुरू होईल',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'या काळात तुम्ही वाचू शकता, पण पोस्ट, टिप्पणी किंवा संदेश पाठवू शकत नाही.',
  'Anladım': 'समजले',
  'Ayrıntı': 'तपशील',
  '{} dakika': '{} मिनिटे',
  'birkaç saniye': 'काही सेकंद',
  'Karara itiraz et': 'या निर्णयाविरुद्ध अपील करा',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'ही शिक्षा का हटवावी ते सांगा',
  'İtirazını gönder': 'तुमचे अपील पाठवा',
  'İtirazın incelemede': 'तुमचे अपील तपासले जात आहे',
  'İtirazın reddedildi': 'तुमचे अपील नाकारले गेले',
  'İtirazın alındı, inceleniyor': 'तुमचे अपील मिळाले, तपासणी सुरू आहे',
  'İtiraz en az 10 karakter olmalı': 'अपील किमान 10 अक्षरांचे असावे',
  'Yükleniyor...': 'लोड होत आहे...',
  'Bu bölüme puan ver': 'या भागाला रेटिंग द्या',
  '{} kişi puanladı': '{} लोकांनी रेटिंग दिले',
  'Bölüm izlendi olarak işaretlendi': 'भाग पाहिला म्हणून चिन्हांकित',
};
