/// Otomatik üretilen çeviri haritası (ur).
const Map<String, String> cevirilerUr = {
  'Hepsini gördün, baştan gösteriyoruz':
      'آپ نے یہ سب دیکھا ہے، ہم آپ کو شروع سے دکھاتے ہیں۔',
  'Aktarılacak tanınan veri bulunamadı.':
      'منتقلی کے لیے کوئی قابلِ شناخت ڈیٹا نہیں ملا۔',
  'Arama': 'تلاش',
  'Aramaya başla': 'تلاش شروع کریں',
  'Son aramalar': 'حالیہ تلاشیں',
  'Ayarlar': 'ترتیبات',
  'Bağla': 'منسلک کریں',
  'Bio': 'تعارف',
  'Bitirdim': 'مکمل کر لیا',
  'Bunları da Beğenebilirsin': 'یہ بھی آپ کو پسند آ سکتے ہیں',
  'Bölüm': 'قسط',
  'Bıraktım': 'چھوڑ دیا',
  'Dil': 'زبان',
  'Dil ara...': 'زبان تلاش کریں...',
  'Dizi': 'سیریز',
  'Dizi ve filmlerini takip et': 'اپنی سیریز اور فلمیں ٹریک کریں',
  'Dizi yorumu': 'سیریز پر تبصرہ',
  'Dizi, film veya kişi ara...': 'سیریز، فلم یا شخصیت تلاش کریں...',
  'Dosya en fazla 30MB olabilir': 'فائل زیادہ سے زیادہ 30MB ہو سکتی ہے',
  'Dosya en fazla {}MB olabilir': 'فائل زیادہ سے زیادہ {}MB ہو سکتی ہے',
  'E-posta': 'ای میل',
  'E-posta veya kullanıcı adı': 'ای میل یا صارف نام',
  'En az 2 harf yaz': 'کم از کم 2 حروف لکھیں',
  'Film': 'فلم',
  'Film yorumu': 'فلم پر تبصرہ',
  'Fotoğraf / video ekle': 'تصویر / ویڈیو شامل کریں',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'تصویر یا GIF — پروفائل اور کور تصویر',
  'Giriş Yap': 'لاگ ان',
  'Gönder': 'بھیجیں',
  'Gönderildi': 'بھیج دیا گیا',
  'Haftanın Dizileri': 'ہفتے کی سیریز',
  'Haftanın Filmleri': 'ہفتے کی فلمیں',
  'Henüz izleme kaydın yok': 'ابھی تک کوئی واچ ہسٹری نہیں',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'ابھی کوئی لسٹ نہیں — پروفائل ٹیب سے بنائیں۔',
  'Henüz yorum yok.': 'ابھی کوئی تبصرہ نہیں۔',
  'Hesabın bağlandı!': 'آپ کا اکاؤنٹ منسلک ہو گیا!',
  'Hesabın yok mu? Kayıt ol': 'اکاؤنٹ نہیں ہے؟ رجسٹر کریں',
  'Hesabını Bağla': 'اپنا اکاؤنٹ منسلک کریں',
  'Hesap Oluştur': 'اکاؤنٹ بنائیں',
  'Kapak resmi ekle': 'کور تصویر شامل کریں',
  'Kaydet': 'محفوظ کریں',
  'Kendinden bahset...': 'اپنے بارے میں بتائیں...',
  'Keşfet': 'دریافت',
  'Kimseyi takip etmiyor': 'کسی کو فالو نہیں',
  'Kişi ara': 'شخصیت تلاش کریں',
  'Kişi yorumu': 'شخصیت پر تبصرہ',
  'Konuk Oyuncular': 'مہمان اداکار',
  'Kullanıcı adı (küçük harf)': 'صارف نام (چھوٹے حروف)',
  'Kullanıcı adı ara...': 'صارف نام تلاش کریں...',
  'Liste adı': 'لسٹ کا نام',
  'Listeye Ekle': 'لسٹ میں شامل کریں',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'آپ مہمان اکاؤنٹ پر ہیں — اپنی ای میل سے منسلک کریں، اپنا ڈیٹا ضائع نہ کریں!',
  'Misafir olarak devam et': 'مہمان کے طور پر جاری رکھیں',
  'Oluştur': 'بنائیں',
  'Oyuncular': 'اداکار',
  'Profil': 'پروفائل',
  'Profil kaydedildi': 'پروفائل محفوظ ہو گیا',
  'Puanla': 'ریٹنگ دیں',
  'Puanı Sil': 'ریٹنگ حذف کریں',
  'Puanın': 'آپ کی ریٹنگ',
  'Sezonlar': 'سیزن',
  'Sunucu hatası ({})': 'سرور کی خرابی ({})',
  'S{} · {}. Bölüm': 'سیزن {} · قسط {}',
  'S{}B{} yorumu': 'سیزن {} قسط {} پر تبصرہ',
  'Takibi Bırak': 'ان فالو کریں',
  'Takip': 'فالوونگ',
  'Takip Edilenler': 'فالو کیے گئے',
  'Takip Et': 'فالو کریں',
  'Takipçi': 'فالوور',
  'Takipçi yok': 'کوئی فالوور نہیں',
  'Takipçiler': 'فالوورز',
  'Takvim': 'کیلنڈر',
  'Tamam': 'ٹھیک ہے',
  'Tekrar Dene': 'دوبارہ کوشش کریں',
  'Tekrar dene': 'دوبارہ کوشش کریں',
  'Toplam İzleme Süresi': 'کل اسکرین ٹائم',
  'Tüm Zamanların En İyileri': 'ہر دور کی بہترین',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'اپنا سارا ڈیٹا (واچ، ریٹنگ، تبصرے، لسٹیں) TV Time سے ہم آہنگ ZIP کے طور پر حاصل کریں یا کسی اور ایپ سے آنے والی ZIP درآمد کریں۔',
  'Tümünü Kaldır': 'سب ہٹائیں',
  'Tümünü İzledim': 'سب دیکھ لیے',
  'Türk Dizileri': 'ترک ڈرامے',
  'Veri içe aktar (.zip)': 'ڈیٹا درآمد کریں (.zip)',
  'Verilerim': 'میرا ڈیٹا',
  'Verilerimi dışa aktar (e-posta)': 'میرا ڈیٹا برآمد کریں (ای میل)',
  'Verilerini dışa aktar': 'اپنا ڈیٹا برآمد کریں',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'کوئی آنے والی قسط نہیں۔\nسیریز کی تفصیل سے اسے "دیکھ رہا ہوں" پر سیٹ کریں اور نئی قسطیں یہاں ٹریک کریں۔',
  'Yapımları': 'ان کے کام',
  'Yeni Diziler': 'نئی سیریز',
  'Yeni Liste': 'نئی لسٹ',
  'Yeni kullanıcı adı (isteğe bağlı)': 'نیا صارف نام (اختیاری)',
  'Yorum': 'تبصرہ',
  'Yorumunu yaz...': 'اپنا تبصرہ لکھیں...',
  'Zaten hesabın var mı? Giriş yap': 'پہلے سے اکاؤنٹ ہے؟ لاگ ان کریں',
  'ort. {}': 'اوسط {}',
  'takip': 'فالوونگ',
  'takipçi': 'فالوورز',
  '{} / {} bölüm': '{} / {} قسطیں',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} ماہ',
  '{} ay~tekil': '{} ماہ',
  '{} bölüm izlendi': '{} قسطیں دیکھی گئیں',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} منٹ',
  '{} dk~tekil': '{} منٹ',
  '{} gün': '{} دن',
  '{} gün~tekil': '{} دن',
  '{} içerik': '{} عنوانات',
  '{} içerik · otomatik': '{} عنوانات · خودکار',
  '{} kayıt atlandı (eşleşmedi).': '{} اندراجات چھوڑ دیے گئے (مماثل نہیں)۔',
  '{} saat': '{} گھنٹے',
  '{} saat~tekil': '{} گھنٹہ',
  '{} sezon': '{} سیزن',
  '{} yıl': '{} سال',
  '{} yıl~tekil': '{} سال',
  '{}. Bölüm': 'قسط {}',
  '{}. Sezon': 'سیزن {}',
  'Çıkış Yap': 'لاگ آؤٹ',
  'Ülke': 'ملک',
  'Ülke ara...': 'ملک تلاش کریں...',
  'Ülke seç': 'ملک منتخب کریں',
  'İlk yorumu sen yaz!': 'پہلا تبصرہ آپ لکھیں!',
  'İncelemeler': 'جائزے',
  'İncelemen (isteğe bağlı)': 'آپ کا جائزہ (اختیاری)',
  'İptal': 'منسوخ',
  'İzlediklerim': 'واچ ہسٹری',
  'İzledim': 'دیکھ لیا',
  'İzledin': 'آپ نے دیکھا',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'آپ کی واچ ہسٹری اور لسٹیں محفوظ رہیں گی؛ اب آپ کسی بھی ڈیوائس سے لاگ ان کر سکتے ہیں۔',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'آپ کی واچ ہسٹری، ریٹنگز، تبصرے اور لسٹیں ZIP کے طور پر آپ کی رجسٹرڈ ای میل پر بھیج دی جائیں گی۔',
  'İzleyeceğim': 'دیکھوں گا',
  'İzliyorum': 'دیکھ رہا ہوں',
  'İçe aktarım tamamlandı': 'درآمد مکمل ہو گئی',
  'Şifre': 'پاس ورڈ',
  '• profil bilgisi': '• پروفائل معلومات',
  '• {} dizi durumu': '• {} سیریز اسٹیٹس',
  '• {} izleme kaydı': '• {} واچ اندراجات',
  '• {} liste': '• {} لسٹیں',
  '• {} puan': '• {} ریٹنگز',
  '• {} yorum': '• {} تبصرے',
  '{}+ yapım': '{}+ کام',
  'Yorumlar': 'تبصرے',
  'Yorumlar ({})': 'تبصرے ({})',
  'Yorumları ({})': 'اس پر تبصرے ({})',
  'Listelerim': 'میری لسٹیں',
  'Nereden izledin?': 'کہاں دیکھا؟',
  'Diziye git': 'سیریز پر جائیں',
  'TV / Kanal': 'ٹی وی / چینل',
  'Sinema': 'سینما',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'دیگر',
  'Akış': 'فیڈ',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'تمہاری فیڈ خالی ہے۔\nتمہارے دیکھے ہوئے شوز اور فلموں پر تبصرے آئیں گے تو یہاں نظر آئیں گے۔',
  'Listeleri ({})': 'ان کی فہرستیں ({})',
  'Liste boş.': 'یہ فہرست خالی ہے۔',
  'Yanıtla': 'جواب دیں',
  '@{} kullanıcısına yanıt veriyorsun': '@{} کو جواب',
  'İzlediğim Diziler ({})': 'میرے دیکھے شوز ({})',
  'İzlediğim Filmler ({})': 'میری دیکھی فلمیں ({})',
  'Tümünü gör': 'سب دیکھیں',
  'Bildirimler': 'اطلاعات',
  'Henüz bildirim yok': 'ابھی کوئی اطلاع نہیں',
  '@{} yorumuna yanıt verdi': '@{} نے تمہارے تبصرے کا جواب دیا',
  '@{} yorumunu beğendi': '@{} نے تمہارا تبصرہ پسند کیا',
  '@{} seni takip etti': '@{} نے تمہیں فالو کیا',
  '@{} sana mesaj gönderdi': '@{} نے تمہیں پیغام بھیجا',
  'Mesajlar': 'پیغامات',
  'Mesaj': 'پیغام',
  'Mesaja eklenecek': 'پیغام میں شامل کیا جائے گا',
  'Mesajını yaz...': 'پیغام لکھیں...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'ابھی کوئی چیٹ نہیں۔\nکسی پروفائل پر جا کر پیغام بھیجیں۔',
  'Şifreni mi unuttun?': 'پاس ورڈ یاد نہیں؟',
  'Şifreyi Sıfırla': 'پاس ورڈ ری سیٹ کریں',
  'E-postadaki kod': 'ای میل والا کوڈ',
  'Yeni şifre': 'نیا پاس ورڈ',
  'Sana Özel': 'تمہارے لیے',
  '{} özetin': 'تمہارا {} خلاصہ',
  'Yıllık izleme istatistiklerin': 'سالانہ دیکھنے کے اعداد و شمار',
  'Rozetler': 'بیجز',
  'Verdiğin puan': 'دی گئی ریٹنگز',
  'Ortalama puanın': 'اوسط ریٹنگ',
  'En çok izlediğin diziler': 'سب سے زیادہ دیکھے شوز',
  'İlk Bölüm': 'پہلی قسط',
  '100 Bölüm': '100 اقساط',
  '1000 Bölüm': '1000 اقساط',
  'İlk Film': 'پہلی فلم',
  '50 Film': '50 فلمیں',
  'İlk Yorum': 'پہلا تبصرہ',
  '25 Yorum': '25 تبصرے',
  '10 Puan': '10 ریٹنگز',
  'İlk Takipçi': 'پہلا فالوور',
  '10 Dizi Bitirdin': '10 شوز مکمل',
  'İzlemeyi Bıraktım': 'دیکھنا چھوڑ دیا',
  'İzlediği Diziler ({})': 'ان کے دیکھے شوز ({})',
  'İzlediği Filmler ({})': 'ان کی دیکھی فلمیں ({})',
  '500 Bölüm': '500 اقساط',
  '5000 Bölüm': '5000 اقساط',
  '10 Film': '10 فلمیں',
  '100 Film': '100 فلمیں',
  '100 Yorum': '100 تبصرے',
  '50 Puan': '50 ریٹنگز',
  '100 Puan': '100 ریٹنگز',
  '10 Takipçi': '10 فالوورز',
  '50 Takipçi': '50 فالوورز',
  '25 Dizi Bitirdin': '25 شوز مکمل',
  '50 Dizi Bitirdin': '50 شوز مکمل',
  '10 Beğeni': '10 لائیکس',
  '100 Beğeni': '100 لائیکس',
  'yazıyor...': 'لکھا جا رہا ہے...',
  'Profil düzeni': 'پروفائل ترتیب',
  'Konumla ve kırp': 'پوزیشن سیٹ کریں اور کراپ کریں',
  'Listeye eklendi': 'فہرست میں شامل ہو گیا',
  'Listeyi sil?': 'فہرست حذف کریں؟',
  'Sil': 'حذف کریں',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'یہ کبھی نہ دیکھا ہوا شمار ہوگا اور آپ کی فہرستوں سے ہٹ جائے گا۔',
  'Gelecek bölüm bugün': 'اگلی قسط آج',
  'Gelecek bölüm {} gün sonra': 'اگلی قسط {} دن بعد',
  'Tema': 'تھیم',
  'Sistem': 'سسٹم',
  'Koyu': 'ڈارک',
  'Açık': 'لائٹ',
  'İzleyenler': 'ناظرین',
  'Yorumunu yaz... (@ ile etiketle)': 'اپنا تبصرہ لکھیں... (@ ٹیگ کرنے کے لیے)',
  '@{} bir yorumda seni etiketledi': '‏@{} نے آپ کو ایک تبصرے میں ٹیگ کیا',
  'Mesajı sil': 'پیغام حذف کریں',
  'Mesaj silinemedi': 'پیغام حذف نہیں ہو سکا',
  'Bağlantı geçersiz veya sayfa bulunamadı': 'لنک غلط ہے یا صفحہ نہیں ملا',
  "Keşfet'e dön": 'دریافت پر واپس جائیں',
  'Düzenle': 'ترمیم',
  'Mesajı düzenle': 'پیغام ترمیم کریں',
  'Yanıtlanıyor': 'جواب دیا جا رہا ہے',
  'düzenlendi': 'ترمیم شدہ',
  'Fotoğraf': 'تصویر',
  'Video': 'ویڈیو',
  'İçerik': 'مواد',
  'çevrimiçi': 'آن لائن',
  'son görülme {} dk önce': 'آخری بار {} منٹ پہلے',
  'son görülme {} saat önce': 'آخری بار {} گھنٹے پہلے',
  'son görülme {} gün önce': 'آخری بار {} دن پہلے',
  'Yorumlar yüklenemedi': 'تبصرے لوڈ نہیں ہو سکے',
  'Favori': 'پسندیدہ',
  'Listeye ekle': 'فہرست میں شامل کریں',
  'İçerik paylaş': 'مواد شیئر کریں',
  'Kapat': 'بند کریں',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'جو کچھ آپ دیکھا ہوا نشان زد کرتے ہیں یہاں جمع ہوتا ہے۔',
  'Henüz sohbetin yok': 'ابھی کوئی گفتگو نہیں',
  'Bir profile girip mesaj gönderebilirsin.':
      'کوئی پروفائل کھولیں اور پیغام بھیجیں۔',
  'Listeyi sil': 'فہرست حذف کریں',
  'Puan kaydedilemedi': 'ریٹنگ محفوظ نہ ہو سکی',
  'Nerede İzlenir': 'کہاں دیکھیں',
  'Abonelik': 'سبسکرپشن',
  'Kirala': 'کرائے پر لیں',
  'Satın al': 'خریدیں',
  'Devam et': 'جاری رکھیں',
  'Şikayet et': 'رپورٹ کریں',
  'Engelle': 'بلاک کریں',
  'Engeli kaldır': 'بلاک ہٹائیں',
  'Kullanıcı engellendi': 'صارف بلاک ہو گیا',
  'Engel kaldırıldı': 'بلاک ہٹا دیا گیا',
  'Şikayet sebebi': 'رپورٹ کی وجہ',
  'Spam veya yanıltıcı': 'اسپام یا گمراہ کن',
  'Taciz veya nefret söylemi': 'ہراسانی یا نفرت انگیز تقریر',
  'Uygunsuz / cinsel içerik': 'نامناسب / جنسی مواد',
  'Şiddet veya tehlikeli içerik': 'تشدد یا خطرناک مواد',
  'Telif hakkı ihlali': 'کاپی رائٹ کی خلاف ورزی',
  'Şikayetin alındı, teşekkürler': 'تمہاری رپورٹ موصول ہو گئی، شکریہ',
  'Hesabımı Sil': 'میرا اکاؤنٹ حذف کریں',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'تمہارا اکاؤنٹ اور تمام ڈیٹا (ہسٹری، ریٹنگز، تبصرے، فہرستیں، پیغامات) مستقل طور پر حذف ہو جائے گا۔ اسے واپس نہیں کیا جا سکتا۔',
  'Şifreni gir': 'اپنا پاس ورڈ درج کریں',
  'Hesabımı kalıcı sil': 'میرا اکاؤنٹ مستقل طور پر حذف کریں',
  'Sesli mesaj': 'صوتی پیغام',
  'Ses gönderilemedi': 'صوتی پیغام نہیں بھیجا جا سکا',
  'Kaydediliyor…': 'ریکارڈنگ…',
  'Ses oynatılamadı': 'آواز نہیں چلائی جا سکی',
  'Oynat': 'چلائیں',
  'Duraklat': 'وقفہ',
  'Liste görünümü': 'فہرست منظر',
  'Takvim görünümü': 'کیلنڈر منظر',
  'Önceki ay': 'پچھلا مہینہ',
  'Sonraki ay': 'اگلا مہینہ',
  'Bu gün bölüm yok': 'اس دن کوئی قسط نہیں',
  'Gizlilik Politikası': 'رازداری کی پالیسی',
  'Son güncelleme: {}': 'آخری اپڈیٹ: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'یہ پالیسی بتاتی ہے کہ dizi.jpg ایپ اور dizijpg.com سائٹ استعمال کرتے وقت کون سا ڈیٹا جمع کیا جاتا ہے، کیسے استعمال ہوتا ہے اور تمہارے کیا حقوق ہیں۔',
  'Topladığımız Veriler': 'ہم کون سا ڈیٹا جمع کرتے ہیں',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'اکاؤنٹ: ای میل ایڈریس، صارف نام اور پاس ورڈ۔ پاس ورڈ ناقابلِ واپسی ہیش کی صورت میں محفوظ ہوتے ہیں؛ مہمان اکاؤنٹ بغیر ای میل کے استعمال کیے جا سکتے ہیں۔',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'پروفائل: وہ معلومات جو تم خود شامل کرنا چاہو، جیسے اوتار، کور تصویر، بایو اور ملک۔',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'استعمال: تمہاری دیکھنے کی ہسٹری، ریٹنگز، تبصرے، فہرستیں، ری ایکشنز اور پسندیدہ۔',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'پیغامات: تمہارے تحریری، تصویری اور صوتی پیغامات ہمارے سرورز پر محفوظ ہوتے ہیں۔ پیغامات اینڈ ٹو اینڈ انکرپٹڈ نہیں ہیں؛ صرف رپورٹ ہونے پر ماڈریشن کے لیے دیکھے جاتے ہیں۔',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'اپ لوڈ کردہ میڈیا: تصاویر، GIF، ویڈیوز اور صوتی ریکارڈنگز جو تم پروفائل، تبصروں اور پیغامات میں شامل کرتے ہو۔',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'تکنیکی ڈیٹا: IP ایڈریس، تخمینی مقام (ملک/شہر)، ڈیوائس پلیٹ فارم، ایپ ورژن اور ایرر لاگز۔ یہ سکیورٹی اور خرابیاں دور کرنے کے لیے رکھے جاتے ہیں۔',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'استعمال کے اعدادوشمار: کس قسم کے ڈیوائس، آپریٹنگ سسٹم اور براؤزر سے داخل ہوا گیا، یہ موٹے زمروں کی صورت میں روزانہ کے مجموعی شماروں میں شامل کیا جاتا ہے؛ براؤزر کی شناخت خود محفوظ نہیں کی جاتی اور یہ اعداد کسی شخص سے منسوب نہیں کیے جا سکتے۔',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'اطلاعات: پش اطلاعات کے لیے ہم تمہاری ڈیوائس کا ٹوکن اور زبان کی ترجیح محفوظ رکھتے ہیں۔ تم جب چاہو ڈیوائس کی سیٹنگز سے اطلاعات بند کر سکتے ہو۔',
  'Verileri Nasıl Kullanırız': 'ہم تمہارا ڈیٹا کیسے استعمال کرتے ہیں',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'ہم تمہارا ڈیٹا صرف سروس فراہم کرنے، اکاؤنٹ محفوظ رکھنے، اطلاعات بھیجنے، خرابیاں دور کرنے اور غلط استعمال روکنے کے لیے استعمال کرتے ہیں۔ ہم تمہارا ڈیٹا نہ بیچتے ہیں اور نہ اشتہاری مقاصد کے لیے کسی سے شیئر کرتے ہیں۔',
  'Çerezler ve Yerel Depolama': 'کوکیز اور لوکل اسٹوریج',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'لوکل اسٹوریج صرف تمہیں لاگ ان رکھنے اور زبان و تھیم جیسی ترجیحات یاد رکھنے کے لیے استعمال ہوتی ہے۔ کوئی اشتہاری یا ٹریکنگ کوکی نہیں ہے۔',
  'Üçüncü Taraf Hizmetler': 'تیسرے فریق کی سروسز',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'سیریز اور فلموں کا ڈیٹا TMDB سے اور اسٹریمنگ پلیٹ فارمز کی معلومات JustWatch سے آتی ہیں۔ پش اطلاعات Google Firebase کے ذریعے پہنچائی جاتی ہیں اور سائٹ کی ٹریفک کو Cloudflare محفوظ رکھتا ہے۔ یہ سروسز اپنی اپنی رازداری پالیسیوں کے تابع ہیں۔',
  'Saklama ve Silme': 'ذخیرہ اور حذف',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'تمہارا ڈیٹا اس وقت تک محفوظ رہتا ہے جب تک تمہارا اکاؤنٹ موجود ہے۔ سیٹنگز میں "میرا اکاؤنٹ حذف کریں" سے اکاؤنٹ مستقل طور پر حذف کر سکتے ہو؛ ڈیٹا فوراً اور بیک اپ میں موجود نقول زیادہ سے زیادہ 14 دن میں حذف ہو جاتی ہیں۔ ایرر لاگز 30 دن بعد خودکار طور پر حذف ہو جاتے ہیں۔',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'تم سیٹنگز سے اپنا ڈیٹا ZIP کی صورت میں ایکسپورٹ کر سکتے ہو؛ آرکائیو تمہارے ای میل ایڈریس پر بھیجا جاتا ہے۔',
  'Güvenlik': 'سکیورٹی',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'ڈیٹا انکرپٹڈ کنکشنز (HTTPS) کے ذریعے منتقل ہوتا ہے اور محدود رسائی والے سرورز پر محفوظ رہتا ہے۔',
  'Çocukların Gizliliği': 'بچوں کی رازداری',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      '‏dizi.jpg تیرہ (13) سال سے کم عمر بچوں کے لیے نہیں ہے۔',
  'Hakların': 'تمہارے حقوق',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK اور GDPR کے تحت تمہیں اپنے ڈیٹا تک رسائی، درستی، حذف اور منتقلی کا حق حاصل ہے۔ ان امور کے لیے ہمیں لکھو: {}',
  'Değişiklikler': 'تبدیلیاں',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'اگر یہ پالیسی تبدیل ہو تو نیا ورژن اسی صفحے پر شائع ہوگا اور تاریخ اپڈیٹ کر دی جائے گی۔',
  'Kayıt olarak {} kabul etmiş olursun.': 'رجسٹر ہو کر تم {} قبول کرتے ہو۔',
  'Kullanıcılar': 'صارفین',
  'Fotoğrafı değiştir': 'تصویر بدلیں',
  'Yeniden konumlandır': 'دوبارہ ترتیب دیں',
  'Bir şeyler ters gitti': 'کچھ غلط ہو گیا',
  'Sosyal Bağlantılar': 'سوشل لنکس',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'تمہاری پروفائل پر زیادہ سے زیادہ 3 لنکس دکھتے ہیں۔',
  'Platform seç': 'پلیٹ فارم چنو',
  'Kullanıcı adın': 'تمہارا صارف نام',
  'Ekle': 'شامل کرو',
  'Kaldır': 'ہٹاؤ',
  'Kopyalandı: {}': 'کاپی ہو گیا: {}',
  'Geçersiz kullanıcı adı': 'غلط صارف نام',
  'Bağlantı ekle': 'لنک شامل کرو',
  'Spoiler olabilir — dokun ve gör':
      'اسپائلر ہو سکتا ہے — دیکھنے کے لیے چھوئیں',
  'Beğeni': 'پسندیدگیاں',
  'Beğen': 'پسند',
  'Görüntülenme': 'ملاحظات',
  'Tam ekran': 'فل اسکرین',
  'Arama başarısız': 'تلاش ناکام ہو گئی',
  'Sonuç bulunamadı': 'کوئی نتیجہ نہیں ملا',
  'Dizi ve Filmler': 'سیریز اور فلمیں',
  'Kişiler': 'افراد',
  'Ana Sayfa': 'ہوم',
  'Paylaş': 'شیئر',
  'Yanıtlar': 'جوابات',
  'Yaklaşan Bölümler': 'آنے والی اقساط',
  'Yetişme Listesi': 'کیچ اپ فہرست',
  'Şunu mu demek istedin': 'کیا آپ کا مطلب تھا',
  'Spoiler': 'اسپائلر',
  'Spoiler — dokun ve gör': 'اسپائلر — دیکھنے کے لیے چھوئیں',
  'uyum': 'مماثلت',
  'Uyum': 'مماثلت',
  '{} ortak dizi': '{} مشترکہ سیریز',
  '{} ortak film': '{} مشترکہ فلمیں',
  'Bildirim Tercihleri': 'اطلاع کی ترجیحات',
  'Beğeniler': 'پسندیدگیاں',
  'Yeni takipçiler': 'نئے فالوورز',
  'Etiketlenmeler': 'تذکرے',
  'Yeniden izledim': 'دوبارہ دیکھا',
  '{}. kez izlendi': '{} بار دیکھا',
  'Gönderi bulunamadı': 'پوسٹ نہیں ملی',
  'Gözat': 'براؤز کریں',
  'Diziler': 'سیریز',
  'Filmler': 'فلمیں',
  'Tümü': 'سب',
  'Farklı bir tür seç.': 'کوئی اور صنف آزمائیں۔',
  'Gizlilik': 'رازداری',
  'İzlediklerimi gizle': 'میری دیکھی ہوئی چیزیں چھپائیں',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'تمہاری دیکھی ہوئی سیریز اور فلمیں تمہارے پروفائل پر نظر نہیں آئیں گی',
  'Yorumlarımı gizle': 'میرے تبصرے چھپائیں',
  'Profilinde yorumların görünmez':
      'تمہارے تبصرے تمہارے پروفائل پر نظر نہیں آئیں گے',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'کسی ایک سیریز یا فلم کو اس کے صفحے پر «میرے پروفائل میں چھپائیں» چپ سے چھپا سکتے ہو۔',
  'Geri Bildirim': 'رائے',
  'Uygulama hakkında görüş ve önerini yaz...':
      'ایپ کے بارے میں اپنی رائے اور تجاویز لکھو...',
  'Teşekkürler! Geri bildirimin alındı.': 'شکریہ! تمہاری رائے موصول ہو گئی۔',
  'Profilimde gizle': 'میرے پروفائل میں چھپائیں',
  'Yorumları': 'اس پر تبصرے',
  'Bu kullanıcı henüz bir şey izlememiş.': 'اس صارف نے ابھی تک کچھ نہیں دیکھا۔',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'اس صارف کے تبصرے چھپے ہوئے ہیں۔',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'ڈیٹا: JustWatch',
  'Web Sitesi': 'ویب سائٹ',
  'Diğer uygulamalar': 'دیگر ایپس',
  'Bağlantıyı kopyala': 'لنک کاپی کریں',
  'Henüz kimseyi takip etmiyorsun.': 'ابھی تم کسی کو فالو نہیں کرتے۔',
  'Çevir': 'ترجمہ کریں',
  'Çeviri şu an yapılamadı': 'ابھی ترجمہ ممکن نہیں',
  'Bağlantı açılamadı': 'لنک نہیں کھل سکا',
  'Orijinali göster': 'اصل دکھائیں',
  'Çeviriyi göster': 'ترجمہ دکھائیں',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'اس مہینے نشریات کی اعلان کردہ تاریخ والی کوئی قسط نہیں۔ تاریخیں عموماً چند ہفتے پہلے بتائی جاتی ہیں اور پھر یہاں نظر آئیں گی۔',
  'devamı': 'مزید',
  'Google ile devam et': 'Google کے ساتھ جاری رکھیں',
  'Google girişi başarısız': 'Google لاگ ان ناکام رہا',
  'Veri tasarrufu': 'ڈیٹا کی بچت',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi پر ڈیٹا کی بچت',
  'Mobil veride veri tasarrufu': 'موبائل ڈیٹا پر ڈیٹا کی بچت',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'آن ہونے پر تصاویر پہلے سے ڈاؤن لوڈ نہیں ہوتیں، صرف وہی تصویر لوڈ ہوتی ہے جو تم دیکھ رہے ہو۔',
  'Çocuk güvenliği': 'بچوں کی حفاظت',
  'Türk Filmleri': 'ترک فلمیں',
  'En Yüksek Puanlı Filmler': 'سب سے زیادہ ریٹنگ والی فلمیں',
  'En Yüksek Puanlı Diziler': 'سب سے زیادہ ریٹنگ والی سیریز',
  'En Çok İzlenen Filmler': 'سب سے زیادہ دیکھی جانے والی فلمیں',
  'Popüler Diziler': 'مقبول سیریز',
  'En Çok Kazanan Filmler': 'سب سے زیادہ کمانے والی فلمیں',
  'Kült Filmler': 'کلٹ فلمیں',
  'Yeni Filmler': 'نئی فلمیں',
  'Yorum yap': 'تبصرہ کریں',
  'Henüz yorum yok': 'ابھی کوئی تبصرہ نہیں',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'سیریز اور فلموں پر تمہارے تبصرے یہاں جمع ہوتے ہیں۔',
  'GIF ekle': 'GIF شامل کریں',
  'İlk yorumu sen yaz': 'پہلا تبصرہ آپ لکھیں',
  'Video altyazıları': 'ویڈیو سب ٹائٹلز',
  'Videolarda altyazı göster': 'ویڈیوز پر سب ٹائٹلز دکھائیں۔',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'ویڈیو میں بولا گیا جملہ سکرین پر لکھا ہوا ہے۔ متن کا ترجمہ ہے: ترکی تقریر میں انگریزی، دوسری زبانوں میں ترکی۔',
  'Güncelleme gerekli': 'اپ ڈیٹ ضروری ہے',
  'Yeni sürüm var': 'نیا ورژن دستیاب ہے',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'جاری رکھنے کے لیے dizi.jpg کا نیا ورژن انسٹال کریں۔',
  'Güncelle': 'اپ ڈیٹ کریں',
  'Daha sonra': 'بعد میں',
  'Takvim güncelleniyor': 'کیلنڈر اپ ڈیٹ ہو رہا ہے',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'کیلنڈر اپ ڈیٹ نہیں ہو سکا، پرانی فہرست دکھائی جا رہی ہے',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'کچھ سیریز لوڈ نہیں ہو سکیں، فہرست نامکمل ہو سکتی ہے',
  'Yenile': 'ریفریش',
  'Devam etmek için giriş yap': 'جاری رکھنے کے لیے لاگ ان کریں',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'درجہ بندی کرنے، تبصرہ لکھنے اور اپنی لائبریری بنانے کے لیے ایک مفت اکاؤنٹ کافی ہے۔',
  'Şimdi değil': 'ابھی نہیں',
  'Yorum yazmak için giriş yap': 'تبصرہ لکھنے کے لیے لاگ ان کریں',
  'Kişilere göndermek için giriş yap': 'لوگوں کو بھیجنے کے لیے لاگ ان کریں',
  'Beğenenler': 'پسند کرنے والے',
  'Henüz beğeni yok': 'ابھی کوئی پسند نہیں',
  'Bu gönderiyi ilk beğenen sen ol': 'اس پوسٹ کو پسند کرنے والے پہلے بنیں',
  'Bu gönderiye yanıt': 'اس پوسٹ کا جواب',
  'Spoiler içeren gönderi': 'اسپائلر والی پوسٹ',
  'Görsel gönderi': 'تصویری پوسٹ',
  'Bu yorumu profilimde gizle': 'یہ تبصرہ میری پروفائل سے چھپائیں',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'تبصرہ ڈرامہ اور فلم کے صفحے پر موجود رہتا ہے',
  'Bu yorumu sil': 'یہ تبصرہ حذف کریں',
  'Yorum profilinde gizlendi': 'تبصرہ تمہاری پروفائل سے چھپا دیا گیا',
  'Geri al': 'واپس لائیں',
  'Yorum silinsin mi?': 'کیا تبصرہ حذف کیا جائے؟',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'یہ تبصرہ ہر جگہ سے مستقل طور پر حذف ہو جائے گا۔ اسے واپس نہیں لایا جا سکتا۔',
  'Yorum silindi': 'تبصرہ حذف کر دیا گیا',
  'Yorum profilinde tekrar görünüyor':
      'تبصرہ دوبارہ تمہاری پروفائل پر نظر آ رہا ہے',
  'Gizlenen yorumun yok': 'تمہارا کوئی چھپا ہوا تبصرہ نہیں ہے',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'وہ تبصرے جو تم اپنی پروفائل کے تبصرے ٹیب میں کسی پوسٹ کو دبا کر چھپاتے ہو یہاں جمع ہوتے ہیں۔',
  'Gizlenen yorumlar': 'چھپے ہوئے تبصرے',
  'Gönderiye git': 'پوسٹ پر جائیں',
  'Tekrar göster': 'دوبارہ دکھائیں',
  'Yanıtlarımı gizle': 'اپنے جوابات چھپائیں',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'تم دوسروں کی پوسٹس پر جو جوابات لکھتے ہو وہ صرف تمہیں نظر آتے ہیں',
  'Profilinde gizlediğin yorumları tekrar göster':
      'اپنی پروفائل پر چھپائے گئے تبصرے دوبارہ دکھائیں',
  'Sıralama': 'ترتیب',
  'Önerilen': 'تجویز کردہ',
  'Kronolojik': 'تاریخ وار',
  'Gelen mesaj istekleri': 'موصولہ پیغام درخواستیں',
  'Mesaj isteğin yok': 'کوئی پیغام درخواست نہیں',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'جن لوگوں کو آپ فالو نہیں کرتے ان کے پیغامات یہاں دکھائی دیتے ہیں۔',
  'Çevrimiçi durumumu gizle': 'میری آن لائن حالت چھپائیں',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'دوسرے لوگ پیغامات میں آپ کی آن لائن حالت اور آخری بار دیکھے جانے کا وقت نہیں دیکھ سکیں گے',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'ہمارے پہلے صارفین میں سے ایک۔ ان کی رائے نے ایپ کو آج کی شکل دی۔',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'تم ہمارے پہلے صارفین میں سے ایک ہو۔ تمہاری رائے نے ایپ کو آج کی شکل دی۔',
  'İleri': 'آگے',
  'Seçilen dosya okunamadı': 'منتخب فائل نہیں پڑھی جا سکی',
  'Video açılamadı': 'ویڈیو نہیں کھل سکی',
  'En fazla {} medya seçebilirsin':
      'آپ زیادہ سے زیادہ {} میڈیا منتخب کر سکتے ہیں',
  'Hiçbir medya yüklenemedi': 'کوئی میڈیا اپ لوڈ نہیں ہو سکا',
  'Seçimi kaldır': 'انتخاب ہٹائیں',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'ایک تبصرے میں کل {} MB میڈیا اپ لوڈ کر سکتے ہیں',
  '{} dosya okunamadı': '{} فائلیں پڑھی نہیں جا سکیں',
  '{} medya eklendi, {} yüklenemedi': '{} میڈیا شامل، {} ناکام',
  'Kırp': 'کراپ',
  'Çiz': 'ڈرا',
  'Metin': 'متن',
  'Emoji': 'ایموجی',
  'Yinele': 'دوبارہ کریں',
  'Daha fazla': 'مزید',
  'Hazırlanıyor…': 'تیار ہو رہا ہے…',
  'Düzenlemeden çık?': 'ترمیم سے باہر نکلیں؟',
  'Yaptığın değişiklikler kaybolacak.': 'آپ کی تبدیلیاں ضائع ہو جائیں گی۔',
  'Çık': 'باہر نکلیں',
  'Serbest çizim': 'آزاد ڈرائنگ',
  'Ok': 'تیر',
  'Dikdörtgen': 'مستطیل',
  'Daire': 'دائرہ',
  'Bulanıklaştır': 'دھندلا کریں',
  'Pikselleştir': 'پکسلیٹ کریں',
  'Silgi': 'ربر',
  'Çizgi kalınlığı': 'لکیر کی موٹائی',
  'Saydamlık': 'دھندلاپن',
  'Dolgu': 'بھریں',
  'Renk': 'رنگ',
  'Döndür': 'گھمائیں',
  'Yansıt': 'پلٹیں',
  'Oran': 'تناسب',
  'Sıfırla': 'ری سیٹ',
  'Serbest': 'آزاد',
  'Metin yaz...': 'متن لکھیں...',
  'Hizala': 'سیدھ کریں',
  'Arka plan': 'پس منظر',
  'Emoji ara...': 'ایموجی تلاش کریں...',
  'Son kullanılanlar': 'حالیہ',
  'İfadeler ve insanlar': 'مسکراہٹیں اور لوگ',
  'Hayvanlar ve doğa': 'جانور اور فطرت',
  'Yiyecek ve içecek': 'کھانا اور مشروبات',
  'Etkinlikler': 'سرگرمیاں',
  'Seyahat ve yerler': 'سفر اور مقامات',
  'Nesneler': 'اشیاء',
  'Semboller': 'علامات',
  'Bayraklar': 'جھنڈے',
  'Görseli düzenle': 'تصویر میں ترمیم کریں',
  'Düzenlendi': 'ترمیم شدہ',
  'Düzenlenemedi': 'ترمیم نہیں ہو سکی',
  'Düzenlenen görsel çok büyük': 'ترمیم شدہ تصویر بہت بڑی ہے',
  'Videoyu düzenle': 'ویڈیو میں ترمیم کریں',
  'Sesi kapat': 'آواز بند کریں',
  'Sesi aç': 'آواز چالو کریں',
  'İptal ediliyor…': 'منسوخ کیا جا رہا ہے…',
  'Bu biraz sürebilir': 'اس میں کچھ وقت لگ سکتا ہے',
  'Video çok büyük': 'ویڈیو بہت بڑی ہے',
  'Video hazırlanamadı': 'ویڈیو تیار نہیں ہو سکی',
  'Başlangıç': 'آغاز',
  'Bitiş': 'اختتام',
  'En çok {} saniye seçebilirsin':
      'آپ زیادہ سے زیادہ {} سیکنڈ منتخب کر سکتے ہیں',
  'Dosya en fazla {} MB olabilir': 'فائل زیادہ سے زیادہ {} MB ہو سکتی ہے',
  'Medya ekle': 'میڈیا شامل کریں',
  'Seçili medya kalmadı': 'کوئی میڈیا منتخب نہیں',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'اپنے تبصرے میں شامل کرنے کے لیے تصویر یا ویڈیو منتخب کریں۔',
  'Medya seç': 'میڈیا منتخب کریں',
  'Daha fazla ekle': 'مزید شامل کریں',
  'Medya seçilemedi': 'میڈیا منتخب نہیں ہو سکا',
  'Favori oyuncular': 'پسندیدہ اداکار',
  'Henüz favori oyuncun yok': 'ابھی کوئی پسندیدہ اداکار نہیں',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'کسی اداکار کا صفحہ کھولیں اور اوپر دائیں دل کو دبائیں؛ یہاں شامل ہو جائے گا۔',
  '{} yapımdan {} tanesini izledin': '{} میں سے {} دیکھے',
  'izledin': 'دیکھے',
  'İzlemedin': 'نہیں دیکھا',
  'Yapım bulunamadı': 'کوئی عنوان نہیں ملا',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'اس شخص کی کوئی سیریز یا فلم موجود نہیں۔',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'آپ کی تاریخ آپ کے اکاؤنٹ سے منسلک ہے؛ یہ فہرست صرف آپ کی ہے۔',
  'Hesabın kalıcı olarak askıya alındı':
      'آپ کا اکاؤنٹ مستقل طور پر معطل کر دیا گیا ہے',
  'Hesabın geçici olarak askıya alındı':
      'آپ کا اکاؤنٹ عارضی طور پر معطل کر دیا گیا ہے',
  'Hesabın askıya alındı': 'آپ کا اکاؤنٹ معطل ہے',
  'Sebep': 'وجہ',
  'Kalan süre': 'باقی وقت',
  'Süre dolunca hesabın kendiliğinden açılır':
      'مدت ختم ہوتے ہی آپ کا اکاؤنٹ خود بخود کھل جائے گا',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'اس دوران آپ پڑھ سکتے ہیں، لیکن پوسٹ، تبصرہ یا پیغام نہیں بھیج سکتے۔',
  'Anladım': 'سمجھ گیا',
  'Ayrıntı': 'تفصیل',
  '{} dakika': '{} منٹ',
  'birkaç saniye': 'چند سیکنڈ',
  'Karara itiraz et': 'فیصلے کے خلاف اپیل کریں',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'بتائیں کہ یہ سزا کیوں ختم ہونی چاہیے',
  'İtirazını gönder': 'اپنی اپیل بھیجیں',
  'İtirazın incelemede': 'آپ کی اپیل زیر غور ہے',
  'İtirazın reddedildi': 'آپ کی اپیل مسترد کر دی گئی',
  'İtirazın alındı, inceleniyor': 'آپ کی اپیل موصول ہو گئی، جائزہ جاری ہے',
  'İtiraz en az 10 karakter olmalı': 'اپیل کم از کم 10 حروف کی ہونی چاہیے',
  'Yükleniyor...': 'لوڈ ہو رہا ہے...',
  'Bu bölüme puan ver': 'اس قسط کو ریٹ کریں',
  '{} kişi puanladı': '{} افراد نے ریٹ کیا',
  'Bölüm izlendi olarak işaretlendi': 'قسط دیکھی گئی کے طور پر نشان زد',
  'Sesli ara': 'وائس کال',
  'Görüntülü ara': 'ویڈیو کال',
  'Çalıyor...': 'گھنٹی بج رہی ہے...',
  'Bağlanıyor...': 'جڑ رہا ہے...',
  'Cevapla': 'جواب دیں',
  'Reddet': 'مسترد کریں',
  'Sessize al': 'خاموش',
  'Hoparlör': 'اسپیکر',
  'Kamerayı kapat': 'کیمرہ بند کریں',
  'Kamerayı çevir': 'کیمرہ بدلیں',
  'Cevap yok': 'کوئی جواب نہیں',
  'Arama reddedildi': 'کال مسترد کر دی گئی',
  'Meşgul': 'مصروف',
  'Bağlanılamadı': 'رابطہ نہیں ہو سکا',
  'Arama iptal edildi': 'کال منسوخ ہو گئی',
  'Arama geçmişi': 'کال کی تاریخ',
  'Gelen arama': 'آنے والی کال',
  'Giden arama': 'جانے والی کال',
  'Cevapsız arama': 'مِسڈ کال',
  'Arama şu anda kullanılamıyor': 'کالنگ اس وقت دستیاب نہیں',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'ویڈیو کالز فی الحال بند ہیں، آپ وائس کال کر سکتے ہیں',
  'Bu kullanıcıyı arayamazsın': 'آپ اس صارف کو کال نہیں کر سکتے',
  'Aramak için karşılıklı takipleşmelisiniz':
      'کال کرنے کے لیے آپ دونوں کو ایک دوسرے کو فالو کرنا ہوگا',
  'Bu kullanıcı şu anda aranamıyor': 'اس صارف کو ابھی کال نہیں کی جا سکتی',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'بہت زیادہ مِسڈ کالز۔ {} بعد دوبارہ کوشش کریں',
  'Zaten bir aramadasın': 'آپ پہلے ہی ایک کال پر ہیں',
  'Arama için mikrofon izni gerekiyor':
      'کال کے لیے مائیکروفون کی اجازت درکار ہے',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'ویڈیو کال کے لیے کیمرہ اور مائیکروفون کی اجازت درکار ہے',
  'Arama başlatılamadı': 'کال شروع نہیں ہو سکی',
  'Kullanıcı bulunamadı': 'صارف نہیں ملا',
  'Kendini arayamazsın': 'آپ خود کو کال نہیں کر سکتے',
  'Arama artık geçerli değil': 'یہ کال اب درست نہیں رہی',
  'Bu aramanın tarafı değilsin': 'آپ اس کال کا حصہ نہیں ہیں',
  'Arama bulunamadı': 'کال نہیں ملی',
  'Çok fazla istek, biraz bekle': 'بہت زیادہ درخواستیں، تھوڑا انتظار کریں',
  'Bağlantı koptu': 'رابطہ منقطع ہو گیا',
  'Arama süre sınırına ulaştı': 'کال وقت کی حد تک پہنچ گئی',
  'Arama en fazla 4 saat sürebilir':
      'ایک کال زیادہ سے زیادہ 4 گھنٹے چل سکتی ہے',
  'Arama sona erdi': 'کال ختم ہو گئی',
  'Sesli arama': 'وائس کال',
  'Görüntülü arama': 'ویڈیو کال',
  'Gelen aramalar': 'آنے والی کالیں',
  'Sesli ve görüntülü arama bildirimleri': 'وائس اور ویڈیو کال اطلاعات',
  '{} sa': '{} گھنٹے',
  'Sesli ve Görüntülü Aramalar': 'وائس اور ویڈیو کالیں',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'کال کا مواد کبھی ریکارڈ نہیں کیا جاتا۔ آڈیو اور ویڈیو آلات کے درمیان اینڈ ٹو اینڈ خفیہ کاری (DTLS-SRTP) کے ساتھ چلتے ہیں؛ ہمارے سرورز اس ٹریفک کو ڈی کرپٹ، سن یا محفوظ نہیں کر سکتے۔',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'صرف کال میٹا ڈیٹا رکھا جاتا ہے: کس کے ساتھ، کس سمت میں، کب اور کتنی دیر۔ یہ ریکارڈ 90 دن بعد خود بخود حذف ہو جاتے ہیں۔',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'اگر براہِ راست رابطہ نہ بن سکے تو آڈیو اور ویڈیو خفیہ حالت میں ایک ریلے سرور (TURN) سے گزرتے ہیں۔ ریلے سرور بھی مواد کو ڈی کرپٹ یا ریکارڈ نہیں کر سکتا۔',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'مائیکروفون صرف وائس یا ویڈیو کال کے دوران اور کیمرہ صرف ویڈیو کال کے دوران استعمال ہوتا ہے۔ کال ختم ہوتے ہی دونوں بند ہو جاتے ہیں۔',
  'Takip ettiğin {} kişi izledi': 'آپ کے فالو کیے گئے لوگوں میں سے {} نے دیکھا',
  'Yorum yaz...': 'تبصرہ لکھیں...',
  'Sıradaki bölüm': 'اگلی قسط',
  'Doğrulanmış testçi': 'تصدیق شدہ ٹیسٹر',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'فالو، پسند، جواب، پیغام اور ٹیگ کی اطلاعات',
  'Sen': 'آپ',
  'Aradığınız kişide sesli arama devre dışı': 'اس شخص کے لیے صوتی کال بند ہے',
  'Aradığınız kişide görüntülü arama devre dışı':
      'اس شخص کے لیے ویڈیو کال بند ہے',
  'Sesli aramalara izin ver': 'صوتی کالز کی اجازت دیں',
  'Görüntülü aramalara izin ver': 'ویڈیو کالز کی اجازت دیں',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'بند ہونے پر کوئی آپ کو صوتی کال نہیں کر سکتا؛ کال کرنے والے کو اطلاع نظر آتی ہے',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'بند ہونے پر کوئی آپ کو ویڈیو کال نہیں کر سکتا؛ کال کرنے والے کو اطلاع نظر آتی ہے',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'صوتی کال بند ہے۔ اسے ترتیبات > رازداری سے آن کر سکتے ہیں۔',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'ویڈیو کال بند ہے۔ اسے ترتیبات > رازداری سے آن کر سکتے ہیں۔',
  'Sesli ve görüntülü arama': 'صوتی اور ویڈیو کال',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'مہمان اکاؤنٹس کال نہیں کر سکتے۔ اکاؤنٹ بنا لیں تو استعمال کر سکیں گے۔',
  'Misafir hesaplar aranamaz': 'مہمان اکاؤنٹس کو کال نہیں کی جا سکتی',
  'Puan dağılımı': 'ریٹنگ کی تقسیم',
  '{} yıldız': '{} ستارے',
  'Yakında gelecek': 'جلد آ رہا ہے',
  '{} {} yayınlandı': '{} {} آ گئی',
  'Yeni bölüm yayınlandı': 'نئی قسط آ گئی',
  'Yeni bölümler': 'نئی قسطیں',
  'Geri': 'واپس',
  'Karşılamayı kapat': 'خوش آمدید بند کریں',
  'Adım {} / {}': 'مرحلہ {} / {}',
  'Hadi başlayalım': 'چلیں شروع کریں',
  'Kaydet ve devam': 'محفوظ کریں اور جاری رکھیں',
  '{} tanesini ekle': '{} شامل کریں',
  'Şimdilik geç': 'ابھی نہیں',
  'Doğum tarihin ne zaman?': 'آپ کی تاریخِ پیدائش کیا ہے؟',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'یہ اس لیے پوچھتے ہیں تاکہ عمر کے مطابق مواد دکھایا جا سکے اور سالگرہ کی مبارکباد دی جا سکے۔',
  'Gün': 'دن',
  'Ay': 'مہینہ',
  'Yıl': 'سال',
  'Doğum yılımı paylaşmak istemiyorum': 'میرا سالِ پیدائش ظاہر نہ کیا جائے',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'آپ کی تاریخِ پیدائش پروفائل پر سب کو نہیں دکھائی جاتی۔ یہ صرف عمر کے مطابق مواد اور سالگرہ کی مبارکباد کے لیے استعمال ہوتی ہے۔',
  'Ocak': 'جنوری',
  'Şubat': 'فروری',
  'Mart': 'مارچ',
  'Nisan': 'اپریل',
  'Mayıs': 'مئی',
  'Haziran': 'جون',
  'Temmuz': 'جولائی',
  'Ağustos': 'اگست',
  'Eylül': 'ستمبر',
  'Ekim': 'اکتوبر',
  'Kasım': 'نومبر',
  'Aralık': 'دسمبر',
  'Verilerini yanında getir': 'اپنا ڈیٹا ساتھ لے آئیں',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'اگر کسی اور ایپ میں دیکھی ہوئی چیزوں کا ریکارڈ ہے تو اسے یہاں منتقل کر سکتے ہیں۔ صفر سے شروع کرنے کی ضرورت نہیں۔',
  'TV Time, Trakt ve Letterboxd': 'TV Time، Trakt اور Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'وہاں سے برآمد کی ہوئی ZIP فائل منتخب کریں؛ دیکھی ہوئی چیزیں، ریٹنگز اور فہرستیں منتقل ہو جائیں گی۔',
  'Aktarılıyor...': 'منتقل ہو رہا ہے...',
  'ZIP dosyası seç': 'ZIP فائل منتخب کریں',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'جلدی کی ضرورت نہیں: یہ کام بعد میں ترتیبات > میرا ڈیٹا سے بھی کیا جا سکتا ہے۔',
  'Hangi filmleri izledin?': 'کون سی فلمیں دیکھی ہوئی ہیں؟',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'سب سے زیادہ دیکھی جانے والی یہاں ہیں۔ جس پر بھی ٹیپ کریں گے وہ دیکھی ہوئی فہرست میں شامل ہو جائے گی۔',
  'SERİ FİLMLER': 'فلمی سلسلے',
  'Serilerden {} film eklendi': 'سلسلوں سے {} فلمیں شامل ہوئیں',
  'Film listesi yüklenemedi': 'فلموں کی فہرست لوڈ نہیں ہو سکی',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'یہ مرحلہ چھوڑ سکتے ہیں، بعد میں جو چاہیں شامل کر سکتے ہیں۔',
  '{} film izlediklerine eklendi': '{} فلمیں دیکھی ہوئی فہرست میں شامل ہوئیں',
  'Film serileri': 'فلمی سلسلے',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'کوئی سلسلہ شروع سے آخر تک دیکھا ہوا ہو تو ایک ٹیپ سے شامل کریں۔',
  'Seri bulunamadı': 'کوئی سلسلہ نہیں ملا',
  'Daha sonra tekrar deneyebilirsin.': 'بعد میں دوبارہ کوشش کر سکتے ہیں۔',
  '{} film': '{} فلمیں',
  'Eklendi': 'شامل ہو گئی',
  'Tümünü izledim': 'ساری دیکھ لی ہیں',
  'Peki ya diziler?': 'اور سیریز کا کیا؟',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'جو دیکھی ہوئی ہیں انہیں نشان زد کریں؛ جتنا انتخاب ہوگا، اتنی ہی ملتی جلتی تجاویز لائیں گے۔',
  'Dizi listesi yüklenemedi': 'سیریز کی فہرست لوڈ نہیں ہو سکی',
  'Seçtiklerine benzeyenler': 'آپ کے انتخاب سے ملتی جلتی',
  'Her şey hazır': 'سب تیار ہے',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'dizi.jpg میں کیا کچھ کیا جا سکتا ہے، ایک نظر دیکھ لیں۔',
  'Profilini tamamla': 'اپنی پروفائل مکمل کریں',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'ترتیبات سے تعارف، پروفائل تصویر اور کور شامل کر سکتے ہیں۔',
  'Takvimin seni bekliyor': 'کیلنڈر آپ کا منتظر ہے',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'جو سیریز دیکھی جا رہی ہیں ان کی نئی قسطیں کیلنڈر میں آ جاتی ہیں اور ہم اطلاع بھیج دیتے ہیں۔',
  'Puan ver, yorum yaz': 'ریٹنگ دیں، تبصرہ لکھیں',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'قسط در قسط ریٹنگ دیں، اسپائلر پردے کے پیچھے تبصرہ لکھیں، فہرستیں بنائیں۔',
  'Verilerin sende kalır': 'ڈیٹا آپ ہی کا رہتا ہے',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'آپ کا ڈیٹا صرف آپ کے اکاؤنٹ سے جڑا رہتا ہے، بیچا نہیں جاتا۔ ترتیبات سے سب کچھ ڈاؤن لوڈ کر سکتے ہیں یا اکاؤنٹ مکمل طور پر حذف کر سکتے ہیں۔',
  'Engellenen kullanıcılar': 'بلاک کیے گئے صارفین',
  'Engellediğin kişileri gör, engeli kaldır':
      'بلاک کیے گئے لوگ دیکھیں، بلاک ہٹائیں',
  'Engellediğin kimse yok': 'بلاک کی فہرست خالی ہے',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'کسی صارف کو اس کی پروفائل کے تین نقطوں والے مینو سے بلاک کیا جا سکتا ہے۔',
  '@{} engellensin mi?': '@{} کو بلاک کریں؟',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'آپ دونوں ایک دوسرے کی پوسٹس، تبصرے اور پروفائل نہیں دیکھ سکیں گے؛ پیغام اور کال بھی نہیں جا سکے گی۔ اگر آپس میں فالو کا تعلق ہو تو وہ ختم ہو جائے گا اور بلاک ہٹانے پر بھی واپس نہیں آئے گا۔',
  'Bu kullanıcıyı engelledin': 'یہ صارف آپ کی طرف سے بلاک ہے',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'اس شخص کی پوسٹس، تبصرے اور پیغامات آپ کو نظر نہیں آتے؛ اور آپ کے بھی اس شخص کو نظر نہیں آتے۔',
  '{} yeni bir yapımda: {}': '{} ایک نئے کام میں: {}',
  'Favori kişinden yeni yapım': 'پسندیدہ شخص کا نیا کام',
  '{} için bildirimler': '{} کے لیے اطلاعات',
  'Tüm bildirimler': 'تمام اطلاعات',
  'Uygulamada ve telefonda': 'ایپ اور فون دونوں پر',
  'Yalnız uygulama içi': 'صرف ایپ کے اندر',
  'Telefon bildirimi gönderilmez': 'فون پر اطلاع نہیں بھیجی جاتی',
  'Kapalı': 'بند',
  'Bu kişi için bildirim yok': 'اس شخص کے لیے کوئی اطلاع نہیں',
  'Favori kişilerin yeni yapımları': 'پسندیدہ لوگوں کے نئے کام',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'بند ہونے پر کوئی آپ کو صوتی کال نہیں کر سکتا؛ کال کرنے والے کو "بند" ہونے کی اطلاع نظر آتی ہے',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'بند ہونے پر کوئی آپ کو ویڈیو کال نہیں کر سکتا؛ کال کرنے والے کو "بند" ہونے کی اطلاع نظر آتی ہے',
};
