/// Otomatik üretilen çeviri haritası (zh).
const Map<String, String> cevirilerZh = {
  'Hepsini gördün, baştan gösteriyoruz': '您已经看到了这一切，我们从头开始向您展示',
  'Aktarılacak tanınan veri bulunamadı.': '未找到可导入的有效数据。',
  'Arama': '搜索',
  'Aramaya başla': '开始搜索',
  'Son aramalar': '最近搜索',
  'Ayarlar': '设置',
  'Bağla': '绑定',
  'Bio': '简介',
  'Bitirdim': '看完了',
  'Bunları da Beğenebilirsin': '猜你也喜欢',
  'Bölüm': '集',
  'Bıraktım': '弃剧了',
  'Dil': '语言',
  'Dil ara...': '搜索语言...',
  'Dizi': '剧集',
  'Dizi ve filmlerini takip et': '追踪你的剧集和电影',
  'Dizi yorumu': '剧集评论',
  'Dizi, film veya kişi ara...': '搜索剧集、电影或人物...',
  'Dosya en fazla 30MB olabilir': '文件最大 30MB',
  'Dosya en fazla {}MB olabilir': '文件最大 {}MB',
  'E-posta': '邮箱',
  'E-posta veya kullanıcı adı': '邮箱或用户名',
  'En az 2 harf yaz': '至少输入 2 个字符',
  'Film': '电影',
  'Film yorumu': '电影评论',
  'Fotoğraf / video ekle': '添加照片 / 视频',
  'Fotoğraf veya GIF — profil ve kapak resmi': '照片或 GIF — 头像和封面图',
  'Giriş Yap': '登录',
  'Gönder': '发送',
  'Gönderildi': '已发送',
  'Haftanın Dizileri': '本周热门剧集',
  'Haftanın Filmleri': '本周热门电影',
  'Henüz izleme kaydın yok': '还没有观看记录',
  'Henüz listen yok — Profil sekmesinden oluştur.': '还没有片单 — 去个人资料页创建一个吧。',
  'Henüz yorum yok.': '还没有评论。',
  'Hesabın bağlandı!': '账号绑定成功！',
  'Hesabın yok mu? Kayıt ol': '没有账号？注册',
  'Hesabını Bağla': '绑定账号',
  'Hesap Oluştur': '创建账号',
  'Kapak resmi ekle': '添加封面图',
  'Kaydet': '保存',
  'Kendinden bahset...': '介绍一下自己...',
  'Keşfet': '发现',
  'Kimseyi takip etmiyor': '还没有关注任何人',
  'Kişi ara': '搜索人物',
  'Kişi yorumu': '人物评论',
  'Konuk Oyuncular': '特邀演员',
  'Kullanıcı adı (küçük harf)': '用户名（小写）',
  'Kullanıcı adı ara...': '搜索用户名...',
  'Liste adı': '片单名称',
  'Listeye Ekle': '添加到片单',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      '你正在使用游客账号 — 绑定邮箱，别丢了你的数据！',
  'Misafir olarak devam et': '以游客身份继续',
  'Oluştur': '创建',
  'Oyuncular': '演员',
  'Profil': '个人资料',
  'Profil kaydedildi': '资料已保存',
  'Puanla': '评分',
  'Puanı Sil': '删除评分',
  'Puanın': '你的评分',
  'Sezonlar': '季',
  'Sunucu hatası ({})': '服务器错误（{}）',
  'S{} · {}. Bölüm': '第{}季 · 第{}集',
  'S{}B{} yorumu': 'S{}E{} 评论',
  'Takibi Bırak': '取消关注',
  'Takip': '关注',
  'Takip Edilenler': '正在关注',
  'Takip Et': '关注',
  'Takipçi': '粉丝',
  'Takipçi yok': '还没有粉丝',
  'Takipçiler': '粉丝',
  'Takvim': '日历',
  'Tamam': '好的',
  'Tekrar Dene': '重试',
  'Tekrar dene': '重试',
  'Toplam İzleme Süresi': '总观看时长',
  'Tüm Zamanların En İyileri': '史上最佳',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      '将你的全部数据（观看、评分、评论、片单）导出为 TV Time 兼容的 ZIP，或导入来自其他应用的 ZIP。',
  'Tümünü Kaldır': '全部移除',
  'Tümünü İzledim': '全部标记已看',
  'Türk Dizileri': '土耳其剧集',
  'Veri içe aktar (.zip)': '导入数据（.zip）',
  'Verilerim': '我的数据',
  'Verilerimi dışa aktar (e-posta)': '导出我的数据（邮箱）',
  'Verilerini dışa aktar': '导出你的数据',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      '暂无即将播出的剧集。\n在剧集详情页设为"正在追"，即可在这里追踪新剧集。',
  'Yapımları': '参演作品',
  'Yeni Diziler': '新剧上线',
  'Yeni Liste': '新建片单',
  'Yeni kullanıcı adı (isteğe bağlı)': '新用户名（可选）',
  'Yorum': '评论',
  'Yorumunu yaz...': '写下你的评论...',
  'Zaten hesabın var mı? Giriş yap': '已有账号？登录',
  'ort. {}': '平均 {}',
  'takip': '关注',
  'takipçi': '粉丝',
  '{} / {} bölüm': '{} / {} 集',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} 个月',
  '{} ay~tekil': '{} 个月',
  '{} bölüm izlendi': '已看 {} 集',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} 分钟',
  '{} dk~tekil': '{} 分钟',
  '{} gün': '{} 天',
  '{} gün~tekil': '{} 天',
  '{} içerik': '{} 部作品',
  '{} içerik · otomatik': '{} 部作品 · 自动',
  '{} kayıt atlandı (eşleşmedi).': '{} 条记录已跳过（未匹配）。',
  '{} saat': '{} 小时',
  '{} saat~tekil': '{} 小时',
  '{} sezon': '{} 季',
  '{} yıl': '{} 年',
  '{} yıl~tekil': '{} 年',
  '{}. Bölüm': '第{}集',
  '{}. Sezon': '第{}季',
  'Çıkış Yap': '退出登录',
  'Ülke': '国家/地区',
  'Ülke ara...': '搜索国家/地区...',
  'Ülke seç': '选择国家/地区',
  'İlk yorumu sen yaz!': '来写第一条评论吧！',
  'İncelemeler': '影评',
  'İncelemen (isteğe bağlı)': '你的影评（可选）',
  'İptal': '取消',
  'İzlediklerim': '观看记录',
  'İzledim': '看过',
  'İzledin': '你看过',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      '你的观看记录和片单会被保留；现在可以在任何设备上登录了。',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      '你的观看记录、评分、评论和片单将以 ZIP 形式发送到你注册的邮箱。',
  'İzleyeceğim': '想看',
  'İzliyorum': '正在追',
  'İçe aktarım tamamlandı': '导入完成',
  'Şifre': '密码',
  '• profil bilgisi': '• 个人资料',
  '• {} dizi durumu': '• {} 个剧集状态',
  '• {} izleme kaydı': '• {} 条观看记录',
  '• {} liste': '• {} 个片单',
  '• {} puan': '• {} 个评分',
  '• {} yorum': '• {} 条评论',
  '{}+ yapım': '{}+ 部作品',
  'Yorumlar': '评论',
  'Yorumlar ({})': '评论（{}）',
  'Yorumları ({})': 'TA的评论（{}）',
  'Listelerim': '我的片单',
  'Nereden izledin?': '你在哪里看的？',
  'Diziye git': '前往剧集',
  'TV / Kanal': '电视 / 频道',
  'Sinema': '电影院',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': '其他',
  'Akış': '动态',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      '你的动态是空的。\n有人评论你看的剧集和电影时，会显示在这里。',
  'Listeleri ({})': 'TA的片单（{}）',
  'Liste boş.': '这个片单是空的。',
  'Yanıtla': '回复',
  '@{} kullanıcısına yanıt veriyorsun': '正在回复 @{}',
  'İzlediğim Diziler ({})': '我看过的剧集（{}）',
  'İzlediğim Filmler ({})': '我看过的电影（{}）',
  'Tümünü gör': '查看全部',
  'Bildirimler': '通知',
  'Henüz bildirim yok': '还没有通知',
  '@{} yorumuna yanıt verdi': '@{} 回复了你的评论',
  '@{} yorumunu beğendi': '@{} 赞了你的评论',
  '@{} seni takip etti': '@{} 关注了你',
  '@{} sana mesaj gönderdi': '@{} 给你发了消息',
  'Mesajlar': '消息',
  'Mesaj': '私信',
  'Mesaja eklenecek': '将添加到消息中',
  'Mesajını yaz...': '写消息…',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      '还没有会话。\n打开一个主页发送消息吧。',
  'Şifreni mi unuttun?': '忘记密码？',
  'Şifreyi Sıfırla': '重置密码',
  'E-postadaki kod': '邮件中的验证码',
  'Yeni şifre': '新密码',
  'Sana Özel': '为你推荐',
  '{} özetin': '你的 {} 年度回顾',
  'Yıllık izleme istatistiklerin': '你的年度观看统计',
  'Rozetler': '徽章',
  'Verdiğin puan': '打分次数',
  'Ortalama puanın': '平均评分',
  'En çok izlediğin diziler': '看得最多的剧集',
  'İlk Bölüm': '第一集',
  '100 Bölüm': '100 集',
  '1000 Bölüm': '1000 集',
  'İlk Film': '第一部电影',
  '50 Film': '50 部电影',
  'İlk Yorum': '第一条评论',
  '25 Yorum': '25 条评论',
  '10 Puan': '10 次评分',
  'İlk Takipçi': '第一个粉丝',
  '10 Dizi Bitirdin': '看完 10 部剧',
  'İzlemeyi Bıraktım': '不追了',
  'İzlediği Diziler ({})': 'TA看过的剧集（{}）',
  'İzlediği Filmler ({})': 'TA看过的电影（{}）',
  '500 Bölüm': '500 集',
  '5000 Bölüm': '5000 集',
  '10 Film': '10 部电影',
  '100 Film': '100 部电影',
  '100 Yorum': '100 条评论',
  '50 Puan': '50 次评分',
  '100 Puan': '100 次评分',
  '10 Takipçi': '10 个粉丝',
  '50 Takipçi': '50 个粉丝',
  '25 Dizi Bitirdin': '看完 25 部剧',
  '50 Dizi Bitirdin': '看完 50 部剧',
  '10 Beğeni': '10 个赞',
  '100 Beğeni': '100 个赞',
  'yazıyor...': '正在输入…',
  'Profil düzeni': '主页布局',
  'Konumla ve kırp': '调整位置并裁剪',
  'Listeye eklendi': '已加入片单',
  'Listeyi sil?': '删除片单？',
  'Sil': '删除',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      '该作品将被标记为从未观看，并从你的片单中移除。',
  'Gelecek bölüm bugün': '下一集今天播出',
  'Gelecek bölüm {} gün sonra': '下一集 {} 天后播出',
  'Tema': '主题',
  'Sistem': '系统',
  'Koyu': '深色',
  'Açık': '浅色',
  'İzleyenler': '观看用户',
  'Yorumunu yaz... (@ ile etiketle)': '写下你的评论……（@ 来标记）',
  '@{} bir yorumda seni etiketledi': '@{} 在评论中标记了你',
  'Mesajı sil': '删除消息',
  'Mesaj silinemedi': '无法删除消息',
  'Bağlantı geçersiz veya sayfa bulunamadı': '链接无效或页面未找到',
  'Keşfet\'e dön': '返回发现',
  'Düzenle': '编辑',
  'Mesajı düzenle': '编辑消息',
  'Yanıtlanıyor': '正在回复',
  'düzenlendi': '已编辑',
  'Fotoğraf': '照片',
  'Video': '视频',
  'İçerik': '内容',
  'çevrimiçi': '在线',
  'son görülme {} dk önce': '{}分钟前在线',
  'son görülme {} saat önce': '{}小时前在线',
  'son görülme {} gün önce': '{}天前在线',
  'Yorumlar yüklenemedi': '无法加载评论',
  'Favori': '收藏',
  'Listeye ekle': '加入列表',
  'İçerik paylaş': '分享内容',
  'Kapat': '关闭',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      '你标记为已看的内容都会汇总在这里。',
  'Henüz sohbetin yok': '还没有对话',
  'Bir profile girip mesaj gönderebilirsin.': '打开一个资料页并发送消息。',
  'Listeyi sil': '删除列表',
  'Puan kaydedilemedi': '无法保存评分',
  'Nerede İzlenir': '观看渠道',
  'Abonelik': '订阅',
  'Kirala': '租赁',
  'Satın al': '购买',
  'Hoş geldin!': '欢迎！',
  'İzlemek istediğin dizi ve filmleri seç': '选择你想看的剧集和电影',
  'Seçtiklerin "İzleyeceğim" listene eklenir': '你的选择会加入想看列表',
  'Şimdilik atla': '暂时跳过',
  'Devam et': '继续',
  '{} ekle': '添加 {}',
  'Şikayet et': '举报',
  'Engelle': '屏蔽',
  'Engeli kaldır': '取消屏蔽',
  'Kullanıcı engellendi': '已屏蔽用户',
  'Engel kaldırıldı': '已取消屏蔽',
  'Şikayet sebebi': '举报原因',
  'Spam veya yanıltıcı': '垃圾信息或误导',
  'Taciz veya nefret söylemi': '骚扰或仇恨言论',
  'Uygunsuz / cinsel içerik': '不当 / 色情内容',
  'Şiddet veya tehlikeli içerik': '暴力或危险内容',
  'Telif hakkı ihlali': '侵犯版权',
  'Şikayetin alındı, teşekkürler': '已收到你的举报，谢谢',
  'Hesabımı Sil': '删除我的账号',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      '你的账号和所有数据（观看记录、评分、评论、列表、消息）将被永久删除。此操作无法撤销。',
  'Şifreni gir': '输入你的密码',
  'Hesabımı kalıcı sil': '永久删除我的账号',
  'Sesli mesaj': '语音消息',
  'Ses gönderilemedi': '语音消息发送失败',
  'Kaydediliyor…': '录音中…',
  'Ses oynatılamadı': '无法播放语音',
  'Oynat': '播放',
  'Duraklat': '暂停',
  'Liste görünümü': '列表视图',
  'Takvim görünümü': '日历视图',
  'Önceki ay': '上个月',
  'Sonraki ay': '下个月',
  'Bu gün bölüm yok': '这天没有剧集',
  'Gizlilik Politikası': '隐私政策',
  'Son güncelleme: {}': '最近更新：{}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      '本政策说明你在使用 dizi.jpg 应用和 dizijpg.com 网站时，我们收集哪些数据、如何使用这些数据，以及你拥有哪些权利。',
  'Topladığımız Veriler': '我们收集的数据',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      '账号：电子邮箱、用户名和密码。密码以不可逆的哈希形式存储；访客账号可以不绑定邮箱使用。',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      '个人资料：你自行选择添加的信息，例如头像、封面图、简介和国家/地区。',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      '使用数据：你的观看历史、评分、评论、片单、表情反应和收藏。',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      '消息：你的文字、图片和语音消息保存在我们的服务器上。消息未采用端到端加密；仅在被举报时才会出于审核目的查看。',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      '上传的媒体：你添加到个人资料、评论和消息中的照片、GIF、视频和语音录音。',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      '技术数据：IP 地址、大致位置（国家/城市级别）、设备平台、应用版本和错误日志。这些数据用于安全防护和排查故障。',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      '通知：为发送推送通知，我们会保存你的设备令牌和语言偏好。你可以随时在设备设置中关闭通知。',
  'Verileri Nasıl Kullanırız': '我们如何使用你的数据',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      '我们仅将你的数据用于提供服务、保护账号、发送通知、修复错误和防止滥用。我们不会出售你的数据，也不会出于广告目的与任何人共享。',
  'Çerezler ve Yerel Depolama': 'Cookie 与本地存储',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      '本地存储仅用于保持你的登录状态，以及记住语言、主题等偏好。没有任何广告或跟踪 Cookie。',
  'Üçüncü Taraf Hizmetler': '第三方服务',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      '剧集和电影数据来自 TMDB，流媒体平台信息来自 JustWatch。推送通知通过 Google Firebase 送达，网站流量由 Cloudflare 保护。这些服务适用其各自的隐私政策。',
  'Saklama ve Silme': '保存与删除',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      '你的数据在账号存续期间保留。通过设置中的“删除我的账号”可以永久删除账号；数据会立即删除，备份中的副本最迟在 14 天内清除。错误日志在 30 天后自动删除。',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      '你可以在设置中将数据导出为 ZIP；压缩包会发送到你的邮箱。',
  'Güvenlik': '安全',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      '数据通过加密连接（HTTPS）传输，并存储在访问受限的服务器上。',
  'Çocukların Gizliliği': '儿童隐私',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg 不面向 13 岁以下的儿童。',
  'Hakların': '你的权利',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      '根据 KVKK 和 GDPR，你有权访问、更正、删除和迁移自己的数据。如需行使这些权利，请联系我们：{}',
  'Değişiklikler': '变更',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      '如本政策发生变更，新版本将发布在本页面，并更新日期。',
  'Kayıt olarak {} kabul etmiş olursun.': '注册即表示你接受{}。',
  'Kullanıcılar': '用户',
  'Fotoğrafı değiştir': '更换照片',
  'Yeniden konumlandır': '重新调整',
  'Bir şeyler ters gitti': '出了点问题',
  'Sosyal Bağlantılar': '社交链接',
  'Profilinde en fazla 3 bağlantı gösterilir.': '个人资料最多显示 3 个链接。',
  'Platform seç': '选择平台',
  'Kullanıcı adın': '你的用户名',
  'Ekle': '添加',
  'Kaldır': '移除',
  'Kopyalandı: {}': '已复制:{}',
  'Geçersiz kullanıcı adı': '用户名无效',
  'Bağlantı ekle': '添加链接',
  'Spoiler olabilir — dokun ve gör': '可能包含剧透 — 点按查看',
  'Beğeni': '点赞',
  'Beğen': '赞',
  'Görüntülenme': '浏览量',
  'Tam ekran': '全屏',
  'Arama başarısız': '搜索失败',
  'Sonuç bulunamadı': '没有结果',
  'Dizi ve Filmler': '剧集与电影',
  'Kişiler': '人物',
  'Ana Sayfa': '首页',
  'Paylaş': '分享',
  'Yanıtlar': '回复',
  'Yaklaşan Bölümler': '即将播出',
  'Yetişme Listesi': '补看清单',
  'Şunu mu demek istedin': '你是不是想找',
  'Spoiler': '剧透',
  'Spoiler — dokun ve gör': '剧透 — 点按查看',
  'uyum': '契合度',
  'Uyum': '契合度',
  '{} ortak dizi': '{} 部共同剧集',
  '{} ortak film': '{} 部共同电影',
  'Bildirim Tercihleri': '通知偏好',
  'Beğeniler': '点赞',
  'Yeni takipçiler': '新粉丝',
  'Etiketlenmeler': '提及',
  'Yeniden izledim': '重看了',
  '{}. kez izlendi': '看过 {} 次',
  'Gönderi bulunamadı': '未找到帖子',
  'Gözat': '浏览',
  'Diziler': '剧集',
  'Filmler': '电影',
  'Tümü': '全部',
  'Farklı bir tür seç.': '试试其他类型。',
  'Gizlilik': '隐私',
  'İzlediklerimi gizle': '隐藏我看过的内容',
  'Profilinde izlediğin dizi ve filmler görünmez': '你看过的剧集和电影不会显示在你的个人主页上',
  'Yorumlarımı gizle': '隐藏我的评论',
  'Profilinde yorumların görünmez': '你的评论不会显示在你的个人主页上',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      '想隐藏某一部剧或电影，可以在其页面上使用“在我的主页隐藏”标签。',
  'Geri Bildirim': '意见反馈',
  'Uygulama hakkında görüş ve önerini yaz...': '写下你对应用的意见和建议...',
  'Teşekkürler! Geri bildirimin alındı.': '谢谢！已收到你的反馈。',
  'Profilimde gizle': '在我的主页隐藏',
  'Yorumları': 'TA的评论',
  'Bu kullanıcı henüz bir şey izlememiş.': '该用户还没有观看任何内容。',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.': '该用户选择不公开自己的评论。',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': '数据：JustWatch',
  'Web Sitesi': '网站',
  'Diğer uygulamalar': '更多应用',
  'Bağlantıyı kopyala': '复制链接',
  'Henüz kimseyi takip etmiyorsun.': '你还没有关注任何人。',
  'Çevir': '翻译',
  'Çeviri şu an yapılamadı': '目前无法翻译',
  'Bağlantı açılamadı': '无法打开链接',
  'Orijinali göster': '显示原文',
  'Çeviriyi göster': '显示翻译',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      '本月没有已公布播出日期的剧集。日期通常提前几周公布，公布后会显示在这里。',
  'devamı': '更多',
  'Google ile devam et': '通过 Google 继续',
  'Google girişi başarısız': 'Google 登录失败',
  'Veri tasarrufu': '流量节省',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi 下节省流量',
  'Mobil veride veri tasarrufu': '移动数据下节省流量',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      '开启后不会提前下载照片，只加载你正在看的那一张。',
  'Çocuk güvenliği': '儿童安全',
  'Türk Filmleri': '土耳其电影',
  'En Yüksek Puanlı Filmler': '评分最高的电影',
  'En Yüksek Puanlı Diziler': '评分最高的剧集',
  'En Çok İzlenen Filmler': '观看最多的电影',
  'Popüler Diziler': '热门剧集',
  'En Çok Kazanan Filmler': '票房最高的电影',
  'Kült Filmler': '邪典电影',
  'Yeni Filmler': '新电影',
  'Yorum yap': '评论',
  'Henüz yorum yok': '还没有评论',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.': '你对剧集和电影的评论都会汇集在这里。',
  'GIF ekle': '添加 GIF',
  'İlk yorumu sen yaz': '来写第一条评论吧',
  'Video altyazıları': '视频字幕',
  'Videolarda altyazı göster': '在视频上显示字幕',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      '视频中所说的句子写在屏幕上。文本翻译：土耳其语语音英语，其他语言土耳其语。',
  "Güncelleme gerekli": "需要更新",
  "Yeni sürüm var": "有新版本",
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.": "请安装 dizi.jpg 新版本以继续。",
  "Güncelle": "更新",
  "Daha sonra": "稍后",
  'Takvim güncelleniyor': '正在更新日历',
  'Takvim güncellenemedi, eski liste gösteriliyor': '无法更新日历，正在显示旧列表',
  'Bazı diziler yüklenemedi, liste eksik olabilir': '部分剧集加载失败，列表可能不完整',
  'Yenile': '刷新',
  'Devam etmek için giriş yap': '登录后继续',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      '免费账号即可评分、评论并建立你的片库。',
  'Şimdi değil': '暂不',
  'Yorum yazmak için giriş yap': '登录后写评论',
  'Kişilere göndermek için giriş yap': '登录后发送给好友',
  'Beğenenler': '点赞的人',
  'Henüz beğeni yok': '还没有人点赞',
  'Bu gönderiyi ilk beğenen sen ol': '成为第一个点赞的人',
  'Bu gönderiye yanıt': '对这条帖子的回复',
  'Spoiler içeren gönderi': '含剧透的帖子',
  'Görsel gönderi': '图片帖子',
  'Bu yorumu profilimde gizle': '在我的主页隐藏这条评论',
  'Yorum dizi ve film sayfasında durmaya devam eder': '评论仍会保留在剧集和电影页面上',
  'Bu yorumu sil': '删除这条评论',
  'Yorum profilinde gizlendi': '评论已在主页隐藏',
  'Geri al': '撤销',
  'Yorum silinsin mi?': '删除评论？',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      '此评论将在所有地方被永久删除，且无法恢复。',
  'Yorum silindi': '评论已删除',
  'Yorum profilinde tekrar görünüyor': '评论已在你的主页重新显示',
  'Gizlenen yorumun yok': '没有隐藏的评论',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      '在主页的评论标签中长按帖子隐藏后，会显示在这里。',
  'Gizlenen yorumlar': '隐藏的评论',
  'Gönderiye git': '前往帖子',
  'Tekrar göster': '重新显示',
  'Yanıtlarımı gizle': '隐藏我的回复',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      '你在他人帖子下写的回复只有你自己可见',
  'Profilinde gizlediğin yorumları tekrar göster': '重新显示你在主页隐藏的评论',
  'Sıralama': '排序',
  'Önerilen': '推荐',
  'Kronolojik': '按时间',
  'Gelen mesaj istekleri': '收到的消息请求',
  'Mesaj isteğin yok': '没有消息请求',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      '你未关注的人发来的消息会显示在这里。',
  'Çevrimiçi durumumu gizle': '隐藏我的在线状态',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      '其他人将看不到你在消息中的在线状态和最后上线时间',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      '我们最早的用户之一。TA的反馈帮助这款应用成为今天的样子。',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      '你是我们最早的用户之一。你的反馈帮助这款应用成为今天的样子。',
  'İleri': '下一步',
  'Seçilen dosya okunamadı': '无法读取所选文件',
  'Video açılamadı': '无法打开视频',
  'En fazla {} medya seçebilirsin': '最多可以选择 {} 个媒体',
  'Hiçbir medya yüklenemedi': '没有媒体上传成功',
  'Seçimi kaldır': '取消选择',
  'Tek yorumda toplam {} MB medya yükleyebilirsin': '单条评论最多可上传 {} MB 媒体',
  '{} dosya okunamadı': '有 {} 个文件无法读取',
  '{} medya eklendi, {} yüklenemedi': '已添加 {} 个媒体，{} 个失败',
  'Kırp': '裁剪',
  'Çiz': '绘制',
  'Metin': '文字',
  'Emoji': '表情',
  'Yinele': '重做',
  'Daha fazla': '更多',
  'Hazırlanıyor…': '准备中…',
  'Düzenlemeden çık?': '退出编辑？',
  'Yaptığın değişiklikler kaybolacak.': '你所做的更改将会丢失。',
  'Çık': '退出',
  'Serbest çizim': '自由绘制',
  'Ok': '箭头',
  'Dikdörtgen': '矩形',
  'Daire': '圆形',
  'Bulanıklaştır': '模糊',
  'Pikselleştir': '马赛克',
  'Silgi': '橡皮擦',
  'Çizgi kalınlığı': '线条粗细',
  'Saydamlık': '不透明度',
  'Dolgu': '填充',
  'Renk': '颜色',
  'Döndür': '旋转',
  'Yansıt': '翻转',
  'Oran': '比例',
  'Sıfırla': '重置',
  'Serbest': '自由',
  'Metin yaz...': '输入文字...',
  'Hizala': '对齐',
  'Arka plan': '背景',
  'Emoji ara...': '搜索表情...',
  'Son kullanılanlar': '最近使用',
  'İfadeler ve insanlar': '表情与人物',
  'Hayvanlar ve doğa': '动物与自然',
  'Yiyecek ve içecek': '食物与饮料',
  'Etkinlikler': '活动',
  'Seyahat ve yerler': '旅行与地点',
  'Nesneler': '物品',
  'Semboller': '符号',
  'Bayraklar': '旗帜',
  'Görseli düzenle': '编辑图片',
  'Düzenlendi': '已编辑',
  'Düzenlenemedi': '无法编辑',
  'Düzenlenen görsel çok büyük': '编辑后的图片太大',
  'Videoyu düzenle': '编辑视频',
  'Sesi kapat': '静音',
  'Sesi aç': '取消静音',
  'İptal ediliyor…': '正在取消…',
  'Bu biraz sürebilir': '这可能需要一些时间',
  'Video çok büyük': '视频太大',
  'Video hazırlanamadı': '无法准备视频',
  'Başlangıç': '开始',
  'Bitiş': '结束',
  'En çok {} saniye seçebilirsin': '最多可以选择 {} 秒',
  'Dosya en fazla {} MB olabilir': '文件最大 {} MB',
  'Medya ekle': '添加媒体',
  'Seçili medya kalmadı': '未选择媒体',
  'Yorumuna eklemek için fotoğraf veya video seç.': '选择要添加到评论的照片或视频。',
  'Medya seç': '选择媒体',
  'Daha fazla ekle': '添加更多',
  'Medya seçilemedi': '无法选择媒体',
  'Favori oyuncular': '收藏的演员',
  'Henüz favori oyuncun yok': '还没有收藏的演员',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      '打开演员页面，点击右上角的心形图标即可加入这里。',
  '{} yapımdan {} tanesini izledin': '{} 部作品中你看了 {} 部',
  'izledin': '已看',
  'İzlemedin': '未观看',
  'Yapım bulunamadı': '未找到作品',
  'Bu kişinin listelenecek dizi veya filmi yok.': '此人没有可列出的剧集或电影。',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      '观看记录与你的账号绑定，此列表仅属于你。',
  'Hesabın kalıcı olarak askıya alındı': '你的账号已被永久停用',
  'Hesabın geçici olarak askıya alındı': '你的账号已被暂时停用',
  'Hesabın askıya alındı': '你的账号已被停用',
  'Sebep': '原因',
  'Kalan süre': '剩余时间',
  'Süre dolunca hesabın kendiliğinden açılır': '时间结束后账号会自动恢复',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      '在此期间你仍可浏览，但不能发帖、评论或发送消息。',
  'Anladım': '知道了',
  'Ayrıntı': '详情',
  '{} dakika': '{} 分钟',
  'birkaç saniye': '几秒',
  'Karara itiraz et': '对此决定提出申诉',
  'Neden bu cezanın kaldırılması gerektiğini anlat': '说明为什么应该撤销这项处罚',
  'İtirazını gönder': '发送申诉',
  'İtirazın incelemede': '你的申诉正在审核中',
  'İtirazın reddedildi': '你的申诉被驳回',
  'İtirazın alındı, inceleniyor': '已收到你的申诉，正在审核',
  'İtiraz en az 10 karakter olmalı': '申诉至少需要 10 个字符',
  'Yükleniyor...': '加载中...',
  'Bu bölüme puan ver': '给这集评分',
  '{} kişi puanladı': '{} 人评分',
  'Bölüm izlendi olarak işaretlendi': '已将该集标记为已观看',
  'Sesli ara': '语音通话',
  'Görüntülü ara': '视频通话',
  'Çalıyor...': '正在呼叫…',
  'Bağlanıyor...': '正在连接…',
  'Cevapla': '接听',
  'Reddet': '拒接',
  'Sessize al': '静音',
  'Hoparlör': '扬声器',
  'Kamerayı kapat': '关闭摄像头',
  'Kamerayı çevir': '切换摄像头',
  'Cevap yok': '无人接听',
  'Arama reddedildi': '通话被拒接',
  'Meşgul': '忙线中',
  'Bağlanılamadı': '无法连接',
  'Arama iptal edildi': '通话已取消',
  'Arama geçmişi': '通话记录',
  'Gelen arama': '来电',
  'Giden arama': '去电',
  'Cevapsız arama': '未接来电',
  'Arama şu anda kullanılamıyor': '通话功能当前不可用',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin': '视频通话暂时关闭，你可以进行语音通话',
  'Bu kullanıcıyı arayamazsın': '你无法呼叫该用户',
  'Aramak için karşılıklı takipleşmelisiniz': '你们需要互相关注才能通话',
  'Bu kullanıcı şu anda aranamıyor': '暂时无法呼叫该用户',
  'Çok fazla cevapsız arama. {} sonra tekrar dene': '未接来电过多。请在 {} 后重试',
  'Zaten bir aramadasın': '你已经在通话中',
  'Arama için mikrofon izni gerekiyor': '通话需要麦克风权限',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor': '视频通话需要摄像头和麦克风权限',
  'Arama başlatılamadı': '无法发起通话',
  'Kullanıcı bulunamadı': '未找到用户',
  'Kendini arayamazsın': '你不能呼叫自己',
  'Arama artık geçerli değil': '该通话已失效',
  'Bu aramanın tarafı değilsin': '你不是此通话的参与者',
  'Arama bulunamadı': '未找到通话',
  'Çok fazla istek, biraz bekle': '请求过于频繁，请稍候',
  'Bağlantı koptu': '连接已断开',
  'Arama süre sınırına ulaştı': '通话已达到时间上限',
  'Arama en fazla 4 saat sürebilir': '单次通话最长 4 小时',
  'Arama sona erdi': '通话已结束',
  'Sesli arama': '语音通话',
  'Görüntülü arama': '视频通话',
  'Gelen aramalar': '来电',
  'Sesli ve görüntülü arama bildirimleri': '语音和视频通话通知',
  '{} sa': '{} 小时',
  'Sesli ve Görüntülü Aramalar': '语音和视频通话',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      '通话内容不会被录制。音频和视频在设备之间以端到端加密（DTLS-SRTP）方式传输；我们的服务器无法解密、监听或保存这些流量。',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      '仅保留通话元数据：与谁、方向、时间和时长。这些记录将在 90 天后自动删除。',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      '如果无法建立直连，音频和视频会以加密状态经过中继服务器（TURN）。中继服务器同样无法解密或记录内容。',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      '麦克风仅在语音或视频通话期间使用，摄像头仅在视频通话期间使用。通话结束后两者都会关闭。',
  'Takip ettiğin {} kişi izledi': '你关注的 {} 人看过',
  'Yorum yaz...': '写评论…',
  'Sıradaki bölüm': '下一集',
  'Doğrulanmış testçi': '已验证测试员',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri': '关注、点赞、回复、消息和标记通知',
  'Sen': '我',
  'Aradığınız kişide sesli arama devre dışı': '对方已关闭语音通话',
  'Aradığınız kişide görüntülü arama devre dışı': '对方已关闭视频通话',
  'Sesli aramalara izin ver': '允许语音通话',
  'Görüntülü aramalara izin ver': '允许视频通话',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      '关闭后没人能给你打语音电话；来电者会看到提示',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      '关闭后没人能给你打视频电话；来电者会看到提示',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      '语音通话已关闭。可在设置 > 隐私中开启。',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      '视频通话已关闭。可在设置 > 隐私中开启。',
  'Sesli ve görüntülü arama': '语音和视频通话',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      '访客账号无法拨打通话。创建账号后即可使用。',
  'Misafir hesaplar aranamaz': '无法呼叫访客账号',
  'Puan dağılımı': '评分分布',
  '{} yıldız': '{} 星',
  'Yakında gelecek': '即将推出',
  '{} {} yayınlandı': '{} {} 已上线',
  'Yeni bölüm yayınlandı': '新一集已上线',
  'Yeni bölümler': '新剧集',
};
