/// Otomatik üretilen çeviri haritası (nb).
const Map<String, String> cevirilerNb = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Du har sett alt, vi viser deg fra begynnelsen',
  'Aktarılacak tanınan veri bulunamadı.':
      'Fant ingen gjenkjente data å importere.',
  'Arama': 'Søk',
  'Aramaya başla': 'Begynn å søke',
  'Son aramalar': 'Nylige søk',
  'Ayarlar': 'Innstillinger',
  'Bağla': 'Koble til',
  'Bio': 'Biografi',
  'Bitirdim': 'Fullført',
  'Bunları da Beğenebilirsin': 'Disse kan du også like',
  'Bölüm': 'Episode',
  'Bıraktım': 'Droppet',
  'Dil': 'Språk',
  'Dil ara...': 'Søk etter språk...',
  'Dizi': 'Serie',
  'Dizi ve filmlerini takip et': 'Hold oversikt over seriene og filmene dine',
  'Dizi yorumu': 'Seriekommentar',
  'Dizi, film veya kişi ara...': 'Søk etter serie, film eller person...',
  'Dosya en fazla 30MB olabilir': 'Filen kan være maks 30MB',
  'Dosya en fazla {}MB olabilir': 'Filen kan være maks {}MB',
  'E-posta': 'E-post',
  'E-posta veya kullanıcı adı': 'E-post eller brukernavn',
  'En az 2 harf yaz': 'Skriv minst 2 bokstaver',
  'Film': 'Film',
  'Film yorumu': 'Filmkommentar',
  'Fotoğraf / video ekle': 'Legg til foto / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto eller GIF — profil- og forsidebilde',
  'Giriş Yap': 'Logg inn',
  'Gönder': 'Send',
  'Gönderildi': 'Sendt',
  'Haftanın Dizileri': 'Ukens serier',
  'Haftanın Filmleri': 'Ukens filmer',
  'Henüz izleme kaydın yok': 'Du har ingen seerhistorikk ennå',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Du har ingen lister ennå — opprett en fra Profil-fanen.',
  'Henüz yorum yok.': 'Ingen kommentarer ennå.',
  'Hesabın bağlandı!': 'Kontoen din er koblet til!',
  'Hesabın yok mu? Kayıt ol': 'Har du ikke konto? Registrer deg',
  'Hesabını Bağla': 'Koble til kontoen din',
  'Hesap Oluştur': 'Opprett konto',
  'Kapak resmi ekle': 'Legg til forsidebilde',
  'Kaydet': 'Lagre',
  'Kendinden bahset...': 'Fortell om deg selv...',
  'Keşfet': 'Utforsk',
  'Kimseyi takip etmiyor': 'Følger ingen',
  'Kişi ara': 'Søk etter person',
  'Kişi yorumu': 'Personkommentar',
  'Konuk Oyuncular': 'Gjesteskuespillere',
  'Kullanıcı adı (küçük harf)': 'Brukernavn (små bokstaver)',
  'Kullanıcı adı ara...': 'Søk etter brukernavn...',
  'Liste adı': 'Listenavn',
  'Listeye Ekle': 'Legg til i liste',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Du bruker en gjestekonto — koble til e-posten din, så du ikke mister dataene dine!',
  'Misafir olarak devam et': 'Fortsett som gjest',
  'Oluştur': 'Opprett',
  'Oyuncular': 'Skuespillere',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil lagret',
  'Puanla': 'Vurder',
  'Puanı Sil': 'Slett vurdering',
  'Puanın': 'Din vurdering',
  'Sezonlar': 'Sesonger',
  'Sunucu hatası ({})': 'Serverfeil ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Kommentar til S{}E{}',
  'Takibi Bırak': 'Slutt å følge',
  'Takip': 'Følger',
  'Takip Edilenler': 'Følger',
  'Takip Et': 'Følg',
  'Takipçi': 'Følgere',
  'Takipçi yok': 'Ingen følgere',
  'Takipçiler': 'Følgere',
  'Takvim': 'Kalender',
  'Tamam': 'OK',
  'Tekrar Dene': 'Prøv igjen',
  'Tekrar dene': 'Prøv igjen',
  'Toplam İzleme Süresi': 'Total skjermtid',
  'Tüm Zamanların En İyileri': 'Tidenes beste',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Eksporter alle dataene dine (historikk, vurderinger, kommentarer, lister) som en TV Time-kompatibel ZIP, eller importer en ZIP fra en annen app.',
  'Tümünü Kaldır': 'Fjern alle',
  'Tümünü İzledim': 'Har sett alle',
  'Türk Dizileri': 'Tyrkiske serier',
  'Veri içe aktar (.zip)': 'Importer data (.zip)',
  'Verilerim': 'Mine data',
  'Verilerimi dışa aktar (e-posta)': 'Eksporter dataene mine (e-post)',
  'Verilerini dışa aktar': 'Eksporter dataene dine',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Ingen kommende episoder.\nSett en serie til "Ser på" fra seriesiden, og følg nye episoder her.',
  'Yapımları': 'Filmografi',
  'Yeni Diziler': 'Nye serier',
  'Yeni Liste': 'Ny liste',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nytt brukernavn (valgfritt)',
  'Yorum': 'Kommentar',
  'Yorumunu yaz...': 'Skriv kommentaren din...',
  'Zaten hesabın var mı? Giriş yap': 'Har du allerede en konto? Logg inn',
  'ort. {}': 'snitt {}',
  'takip': 'følger',
  'takipçi': 'følgere',
  '{} / {} bölüm': '{} / {} episoder',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} mnd.',
  '{} ay~tekil': '{} mnd.',
  '{} bölüm izlendi': '{} episoder sett',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min.',
  '{} dk~tekil': '{} min.',
  '{} gün': '{} d.',
  '{} gün~tekil': '{} d.',
  '{} içerik': '{} titler',
  '{} içerik · otomatik': '{} titler · automatisk',
  '{} kayıt atlandı (eşleşmedi).': '{} oppføringer hoppet over (ingen match).',
  '{} saat': '{} t.',
  '{} saat~tekil': '{} t.',
  '{} sezon': '{} sesonger',
  '{} yıl': '{} år',
  '{} yıl~tekil': '{} år',
  '{}. Bölüm': 'Episode {}',
  '{}. Sezon': 'Sesong {}',
  'Çıkış Yap': 'Logg ut',
  'Ülke': 'Land',
  'Ülke ara...': 'Søk etter land...',
  'Ülke seç': 'Velg land',
  'İlk yorumu sen yaz!': 'Skriv den første kommentaren!',
  'İncelemeler': 'Anmeldelser',
  'İncelemen (isteğe bağlı)': 'Din anmeldelse (valgfritt)',
  'İptal': 'Avbryt',
  'İzlediklerim': 'Min seerhistorikk',
  'İzledim': 'Sett',
  'İzledin': 'Sett',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Seerhistorikken og listene dine beholdes; nå kan du logge inn fra alle enheter.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Seerhistorikken, vurderingene, kommentarene og listene dine sendes som ZIP til den registrerte e-postadressen din.',
  'İzleyeceğim': 'Vil se',
  'İzliyorum': 'Ser på',
  'İçe aktarım tamamlandı': 'Import fullført',
  'Şifre': 'Passord',
  '• profil bilgisi': '• profilinfo',
  '• {} dizi durumu': '• {} seriestatuser',
  '• {} izleme kaydı': '• {} seeroppføringer',
  '• {} liste': '• {} lister',
  '• {} puan': '• {} vurderinger',
  '• {} yorum': '• {} kommentarer',
  '{}+ yapım': '{}+ titler',
  'Yorumlar': 'Kommentarer',
  'Yorumlar ({})': 'Kommentarer ({})',
  'Yorumları ({})': 'Kommentarer ({})',
  'Listelerim': 'Mine lister',
  'Nereden izledin?': 'Hvor så du den?',
  'Diziye git': 'Gå til serien',
  'TV / Kanal': 'TV / Kanal',
  'Sinema': 'Kino',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Annet',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Feeden din er tom.\nNår noen kommenterer seriene og filmene du ser på, vises det her.',
  'Listeleri ({})': 'Listene deres ({})',
  'Liste boş.': 'Denne listen er tom.',
  'Yanıtla': 'Svar',
  '@{} kullanıcısına yanıt veriyorsun': 'Du svarer @{}',
  'İzlediğim Diziler ({})': 'Serier jeg har sett ({})',
  'İzlediğim Filmler ({})': 'Filmer jeg har sett ({})',
  'Tümünü gör': 'Se alle',
  'Bildirimler': 'Varsler',
  'Henüz bildirim yok': 'Ingen varsler ennå',
  '@{} yorumuna yanıt verdi': '@{} svarte på kommentaren din',
  '@{} yorumunu beğendi': '@{} likte kommentaren din',
  '@{} seni takip etti': '@{} fulgte deg',
  '@{} sana mesaj gönderdi': '@{} sendte deg en melding',
  'Mesajlar': 'Meldinger',
  'Mesaj': 'Melding',
  'Mesaja eklenecek': 'Legges til i meldingen',
  'Mesajını yaz...': 'Skriv en melding...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Ingen samtaler ennå.\nÅpne en profil og send en melding.',
  'Şifreni mi unuttun?': 'Glemt passordet?',
  'Şifreyi Sıfırla': 'Tilbakestill passord',
  'E-postadaki kod': 'Kode fra e-posten',
  'Yeni şifre': 'Nytt passord',
  'Sana Özel': 'For deg',
  '{} özetin': 'Din {}-oppsummering',
  'Yıllık izleme istatistiklerin': 'Din årlige seerstatistikk',
  'Rozetler': 'Merker',
  'Verdiğin puan': 'Vurderinger gitt',
  'Ortalama puanın': 'Din snittvurdering',
  'En çok izlediğin diziler': 'Dine mest sette serier',
  'İlk Bölüm': 'Første episode',
  '100 Bölüm': '100 episoder',
  '1000 Bölüm': '1000 episoder',
  'İlk Film': 'Første film',
  '50 Film': '50 filmer',
  'İlk Yorum': 'Første kommentar',
  '25 Yorum': '25 kommentarer',
  '10 Puan': '10 vurderinger',
  'İlk Takipçi': 'Første følger',
  '10 Dizi Bitirdin': 'Fullførte 10 serier',
  'İzlemeyi Bıraktım': 'Sluttet å se',
  'İzlediği Diziler ({})': 'Serier de har sett ({})',
  'İzlediği Filmler ({})': 'Filmer de har sett ({})',
  '500 Bölüm': '500 episoder',
  '5000 Bölüm': '5000 episoder',
  '10 Film': '10 filmer',
  '100 Film': '100 filmer',
  '100 Yorum': '100 kommentarer',
  '50 Puan': '50 vurderinger',
  '100 Puan': '100 vurderinger',
  '10 Takipçi': '10 følgere',
  '50 Takipçi': '50 følgere',
  '25 Dizi Bitirdin': 'Fullførte 25 serier',
  '50 Dizi Bitirdin': 'Fullførte 50 serier',
  '10 Beğeni': '10 likerklikk',
  '100 Beğeni': '100 likerklikk',
  'yazıyor...': 'skriver...',
  'Profil düzeni': 'Profiloppsett',
  'Konumla ve kırp': 'Plasser og beskjær',
  'Listeye eklendi': 'Lagt til i listen',
  'Listeyi sil?': 'Slette listen?',
  'Sil': 'Slett',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Tittelen merkes som aldri sett og fjernes fra listene dine.',
  'Gelecek bölüm bugün': 'Neste episode i dag',
  'Gelecek bölüm {} gün sonra': 'Neste episode om {} dager',
  'Tema': 'Tema',
  'Sistem': 'System',
  'Koyu': 'Mørk',
  'Açık': 'Lys',
  'İzleyenler': 'Seere',
  'Yorumunu yaz... (@ ile etiketle)':
      'Skriv kommentaren din... (@ for å merke)',
  '@{} bir yorumda seni etiketledi': '@{} nevnte deg i en kommentar',
  'Mesajı sil': 'Slett melding',
  'Mesaj silinemedi': 'Meldingen kunne ikke slettes',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Lenken er ugyldig eller siden ble ikke funnet',
  'Keşfet\'e dön': 'Tilbake til Utforsk',
  'Düzenle': 'Rediger',
  'Mesajı düzenle': 'Rediger melding',
  'Yanıtlanıyor': 'Svarer',
  'düzenlendi': 'redigert',
  'Fotoğraf': 'Foto',
  'Video': 'Video',
  'İçerik': 'Innhold',
  'çevrimiçi': 'pålogget',
  'son görülme {} dk önce': 'sist sett for {} min siden',
  'son görülme {} saat önce': 'sist sett for {} t siden',
  'son görülme {} gün önce': 'sist sett for {} d siden',
  'Yorumlar yüklenemedi': 'Kunne ikke laste kommentarer',
  'Favori': 'Favoritt',
  'Listeye ekle': 'Legg til i liste',
  'İçerik paylaş': 'Del innhold',
  'Kapat': 'Lukk',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Alt du merker som sett samles her.',
  'Henüz sohbetin yok': 'Ingen samtaler ennå',
  'Bir profile girip mesaj gönderebilirsin.':
      'Åpne en profil og send en melding.',
  'Listeyi sil': 'Slett liste',
  'Puan kaydedilemedi': 'Vurderingen kunne ikke lagres',
  'Nerede İzlenir': 'Hvor du kan se',
  'Abonelik': 'Abonnement',
  'Kirala': 'Lei',
  'Satın al': 'Kjøp',
  'Hoş geldin!': 'Velkommen!',
  'İzlemek istediğin dizi ve filmleri seç': 'Velg serier og filmer du vil se',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Valgene dine legges til i listen din',
  'Şimdilik atla': 'Hopp over nå',
  'Devam et': 'Fortsett',
  '{} ekle': 'Legg til {}',
  'Şikayet et': 'Rapporter',
  'Engelle': 'Blokker',
  'Engeli kaldır': 'Fjern blokkering',
  'Kullanıcı engellendi': 'Bruker blokkert',
  'Engel kaldırıldı': 'Blokkering fjernet',
  'Şikayet sebebi': 'Årsak til rapportering',
  'Spam veya yanıltıcı': 'Spam eller villedende',
  'Taciz veya nefret söylemi': 'Trakassering eller hatefulle ytringer',
  'Uygunsuz / cinsel içerik': 'Upassende / seksuelt innhold',
  'Şiddet veya tehlikeli içerik': 'Vold eller farlig innhold',
  'Telif hakkı ihlali': 'Brudd på opphavsrett',
  'Şikayetin alındı, teşekkürler': 'Rapporten din er mottatt, takk',
  'Hesabımı Sil': 'Slett kontoen min',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Kontoen din og alle dataene dine (historikk, vurderinger, kommentarer, lister, meldinger) slettes permanent. Dette kan ikke angres.',
  'Şifreni gir': 'Skriv inn passordet ditt',
  'Hesabımı kalıcı sil': 'Slett kontoen min permanent',
  'Sesli mesaj': 'Talemelding',
  'Ses gönderilemedi': 'Talemeldingen kunne ikke sendes',
  'Kaydediliyor…': 'Tar opp…',
  'Ses oynatılamadı': 'Talemeldingen kunne ikke spilles av',
  'Oynat': 'Spill av',
  'Duraklat': 'Pause',
  'Liste görünümü': 'Listevisning',
  'Takvim görünümü': 'Kalendervisning',
  'Önceki ay': 'Forrige måned',
  'Sonraki ay': 'Neste måned',
  'Bu gün bölüm yok': 'Ingen episoder denne dagen',
  'Gizlilik Politikası': 'Personvernerklæring',
  'Son güncelleme: {}': 'Sist oppdatert: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Denne erklæringen forklarer hvilke data som samles inn når du bruker dizi.jpg-appen og nettstedet dizijpg.com, hvordan de brukes og hvilke rettigheter du har.',
  'Topladığımız Veriler': 'Data vi samler inn',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Konto: e-postadresse, brukernavn og passord. Passord lagres med irreversibel hashing; gjestekontoer kan brukes uten e-post.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profil: informasjon du selv velger å legge til, som avatar, forsidebilde, bio og land.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Bruk: visningshistorikken din, vurderingene, kommentarene, listene, reaksjonene og favorittene dine.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Meldinger: tekst-, bilde- og talemeldingene dine lagres på serverne våre. Meldinger er ikke ende-til-ende-krypterte; de gjennomgås kun for moderering hvis de blir rapportert.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Opplastede medier: bilder, GIF-er, videoer og lydopptak du legger til i profilen, kommentarene og meldingene dine.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Teknisk: IP-adresse, omtrentlig posisjon (land-/bynivå), enhetsplattform, appversjon og feillogger. Disse lagres for sikkerhet og feilsøking.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Varsler: enhetstokenet ditt og språkvalget ditt lagres for push-varsler. Du kan når som helst slå av varsler i innstillingene på enheten din.',
  'Verileri Nasıl Kullanırız': 'Hvordan vi bruker dataene',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Vi bruker dataene dine kun til å levere tjenesten, beskytte kontoen din, sende varsler, rette feil og forhindre misbruk. Vi selger ikke dataene dine og deler dem ikke med noen for reklameformål.',
  'Çerezler ve Yerel Depolama': 'Informasjonskapsler og lokal lagring',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Vi bruker lokal lagring kun for å holde deg innlogget og huske preferansene dine, som språk og tema. Det finnes ingen reklame- eller sporingsinformasjonskapsler.',
  'Üçüncü Taraf Hizmetler': 'Tredjepartstjenester',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'Serie- og filminformasjon hentes fra TMDB, og informasjon om strømmetilbydere fra JustWatch. Push-varsler leveres via Google Firebase, og trafikken til nettstedet beskyttes av Cloudflare. Disse tjenestene har sine egne personvernerklæringer.',
  'Saklama ve Silme': 'Lagring og sletting',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Dataene dine lagres så lenge kontoen din er aktiv. Du kan slette kontoen din permanent med "Slett kontoen min" i Innstillinger; dataene dine slettes umiddelbart, og kopier i sikkerhetskopier slettes senest innen 14 dager. Feillogger slettes automatisk etter 30 dager.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'Du kan eksportere dataene dine som ZIP fra Innstillinger; arkivet sendes til e-postadressen din.',
  'Güvenlik': 'Sikkerhet',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Data overføres via kryptert forbindelse (HTTPS) og lagres på servere med begrenset tilgang.',
  'Çocukların Gizliliği': 'Barns personvern',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg er ikke rettet mot barn under 13 år.',
  'Hakların': 'Rettighetene dine',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'I henhold til KVKK og GDPR har du rett til å få innsyn i, rette, slette og overføre dataene dine. Du kan skrive til oss om disse rettighetene: {}',
  'Değişiklikler': 'Endringer',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Hvis denne erklæringen endres, publiseres den nye versjonen på denne siden, og oppdateringsdatoen fornyes.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Ved å registrere deg godtar du {}.',
  'Kullanıcılar': 'Brukere',
  'Fotoğrafı değiştir': 'Bytt bilde',
  'Yeniden konumlandır': 'Juster på nytt',
  'Bir şeyler ters gitti': 'Noe gikk galt',
  'Sosyal Bağlantılar': 'Sosiale lenker',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Opptil 3 lenker vises på profilen din.',
  'Platform seç': 'Velg plattform',
  'Kullanıcı adın': 'Brukernavnet ditt',
  'Ekle': 'Legg til',
  'Kaldır': 'Fjern',
  'Kopyalandı: {}': 'Kopiert: {}',
  'Geçersiz kullanıcı adı': 'Ugyldig brukernavn',
  'Bağlantı ekle': 'Legg til lenke',
  'Spoiler olabilir — dokun ve gör': 'Kan inneholde spoilere — trykk for å se',
  'Beğeni': 'Likerklikk',
  'Beğen': 'Liker',
  'Görüntülenme': 'Visninger',
  'Tam ekran': 'Fullskjerm',
  'Arama başarısız': 'Søket mislyktes',
  'Sonuç bulunamadı': 'Ingen resultater',
  'Dizi ve Filmler': 'Serier og filmer',
  'Kişiler': 'Personer',
  'Ana Sayfa': 'Hjem',
  'Paylaş': 'Del',
  'Yanıtlar': 'Svar',
  'Yaklaşan Bölümler': 'Kommende episoder',
  'Yetişme Listesi': 'Ta-igjen-liste',
  'Şunu mu demek istedin': 'Mente du',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — trykk for å vise',
  'uyum': 'match',
  'Uyum': 'Match',
  '{} ortak dizi': '{} serier felles',
  '{} ortak film': '{} filmer felles',
  'Bildirim Tercihleri': 'Varselinnstillinger',
  'Beğeniler': 'Likerklikk',
  'Yeni takipçiler': 'Nye følgere',
  'Etiketlenmeler': 'Omtaler',
  'Yeniden izledim': 'Sett igjen',
  '{}. kez izlendi': 'Sett {} ganger',
  'Gönderi bulunamadı': 'Innlegget ble ikke funnet',
  'Gözat': 'Bla',
  'Diziler': 'Serier',
  'Filmler': 'Filmer',
  'Tümü': 'Alle',
  'Farklı bir tür seç.': 'Prøv en annen sjanger.',
  'Gizlilik': 'Personvern',
  'İzlediklerimi gizle': 'Skjul det jeg har sett',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Serier og filmer du har sett, vises ikke på profilen din',
  'Yorumlarımı gizle': 'Skjul kommentarene mine',
  'Profilinde yorumların görünmez':
      'Kommentarene dine vises ikke på profilen din',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Du kan skjule en enkelt serie eller film med brikken «Skjul på profilen min» på siden dens.',
  'Geri Bildirim': 'Tilbakemelding',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Skriv din mening og dine forslag om appen...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Takk! Tilbakemeldingen din er mottatt.',
  'Profilimde gizle': 'Skjul på profilen min',
  'Yorumları': 'Kommentarer',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Denne brukeren har ikke sett noe ennå.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Denne brukeren foretrekker å holde kommentarene sine private.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Data: JustWatch',
  'Web Sitesi': 'Nettsted',
  'Diğer uygulamalar': 'Flere apper',
  'Bağlantıyı kopyala': 'Kopier lenke',
  'Henüz kimseyi takip etmiyorsun.': 'Du følger ingen ennå.',
  'Çevir': 'Oversett',
  'Çeviri şu an yapılamadı': 'Oversettelse er ikke mulig nå',
  'Bağlantı açılamadı': 'Kunne ikke åpne lenken',
  'Orijinali göster': 'Vis original',
  'Çeviriyi göster': 'Vis oversettelse',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Ingen episoder med annonsert sendedato denne måneden. Datoer kunngjøres vanligvis noen uker i forveien og dukker opp her.',
  'devamı': 'mer',
  'Google ile devam et': 'Fortsett med Google',
  'Google girişi başarısız': 'Google-pålogging mislyktes',
  'Veri tasarrufu': 'Datasparing',
  'Wi-Fi ağında veri tasarrufu': 'Datasparing på Wi-Fi',
  'Mobil veride veri tasarrufu': 'Datasparing på mobildata',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Når den er på, lastes ikke bilder ned på forhånd, bare bildet du ser på.',
  'Çocuk güvenliği': 'Barns sikkerhet',
  'Türk Filmleri': 'Tyrkiske filmer',
  'En Yüksek Puanlı Filmler': 'Best vurderte filmer',
  'En Yüksek Puanlı Diziler': 'Best vurderte serier',
  'En Çok İzlenen Filmler': 'Mest sette filmer',
  'Popüler Diziler': 'Populære serier',
  'En Çok Kazanan Filmler': 'Mest innbringende filmer',
  'Kült Filmler': 'Kultfilmer',
  'Yeni Filmler': 'Nye filmer',
  'Yorum yap': 'Kommenter',
  'Henüz yorum yok': 'Ingen kommentarer ennå',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Kommentarene dine om serier og filmer samles her.',
  'GIF ekle': 'Legg til GIF',
  'İlk yorumu sen yaz': 'Vær den første til å kommentere',
  'Video altyazıları': 'Video undertekster',
  'Videolarda altyazı göster': 'Vis undertekster på videoer',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Setningen i videoen er skrevet på skjermen. Teksten er oversettelse: engelsk på tyrkisk tale, tyrkisk på andre språk.',
  "Güncelleme gerekli": "Oppdatering kreves",
  "Yeni sürüm var": "Ny versjon tilgjengelig",
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      "Installer den nye versjonen av dizi.jpg for å fortsette.",
  "Güncelle": "Oppdater",
  "Daha sonra": "Senere",
  'Takvim güncelleniyor': 'Oppdaterer kalenderen',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Kunne ikke oppdatere kalenderen, viser den gamle listen',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Noen serier kunne ikke lastes, listen kan være ufullstendig',
  'Yenile': 'Oppdater',
  'Devam etmek için giriş yap': 'Logg inn for å fortsette',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'En gratis konto er nok til å vurdere, kommentere og bygge biblioteket ditt.',
  'Şimdi değil': 'Ikke nå',
  'Yorum yazmak için giriş yap': 'Logg inn for å skrive en kommentar',
  'Kişilere göndermek için giriş yap': 'Logg inn for å sende til personer',
  'Beğenenler': 'Likerklikk',
  'Henüz beğeni yok': 'Ingen likerklikk enna',
  'Bu gönderiyi ilk beğenen sen ol': 'Bli den forste som liker dette innlegget',
  'Bu gönderiye yanıt': 'Svar pa dette innlegget',
  'Spoiler içeren gönderi': 'Innlegg med spoilere',
  'Görsel gönderi': 'Bildeinnlegg',
  'Bu yorumu profilimde gizle': 'Skjul denne kommentaren på profilen min',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Kommentaren blir værende på serie- og filmsiden',
  'Bu yorumu sil': 'Slett denne kommentaren',
  'Yorum profilinde gizlendi': 'Kommentar skjult på profilen din',
  'Geri al': 'Angre',
  'Yorum silinsin mi?': 'Slette kommentaren?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Denne kommentaren slettes permanent overalt. Det kan ikke angres.',
  'Yorum silindi': 'Kommentar slettet',
  'Yorum profilinde tekrar görünüyor':
      'Kommentaren er synlig på profilen din igjen',
  'Gizlenen yorumun yok': 'Ingen skjulte kommentarer',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Kommentarer du skjuler ved å trykke lenge på et innlegg under fanen Kommentarer på profilen din, samles her.',
  'Gizlenen yorumlar': 'Skjulte kommentarer',
  'Gönderiye git': 'Gå til innlegget',
  'Tekrar göster': 'Vis igjen',
  'Yanıtlarımı gizle': 'Skjul svarene mine',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Svar du skriver på andres innlegg, er bare synlige for deg',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Vis kommentarene du har skjult på profilen din, igjen',
  'Sıralama': 'Sortering',
  'Önerilen': 'Anbefalt',
  'Kronolojik': 'Kronologisk',
  'Gelen mesaj istekleri': 'Innkomne meldingsforespørsler',
  'Mesaj isteğin yok': 'Ingen meldingsforespørsler',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Meldinger fra folk du ikke følger vises her.',
  'Çevrimiçi durumumu gizle': 'Skjul min nettstatus',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Andre ser ikke nettstatusen din eller når du sist var aktiv i meldinger',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'En av våre første brukere. Tilbakemeldingene bidro til å gjøre appen til det den er i dag.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Du er en av våre første brukere. Tilbakemeldingene dine bidro til å gjøre appen til det den er i dag.',
  'İleri': 'Neste',
  'Seçilen dosya okunamadı': 'Den valgte filen kunne ikke leses',
  'Video açılamadı': 'Videoen kunne ikke åpnes',
  'En fazla {} medya seçebilirsin': 'Du kan velge maks {} medier',
  'Hiçbir medya yüklenemedi': 'Ingen medier kunne lastes opp',
  'Seçimi kaldır': 'Fjern fra utvalget',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'I én kommentar kan du laste opp totalt {} MB',
  '{} dosya okunamadı': '{} filer kunne ikke leses',
  '{} medya eklendi, {} yüklenemedi': '{} medier lagt til, {} mislyktes',
  'Kırp': 'Beskjær',
  'Çiz': 'Tegn',
  'Metin': 'Tekst',
  'Emoji': 'Emoji',
  'Yinele': 'Gjør om',
  'Daha fazla': 'Mer',
  'Hazırlanıyor…': 'Forbereder…',
  'Düzenlemeden çık?': 'Avslutte redigering?',
  'Yaptığın değişiklikler kaybolacak.': 'Endringene dine går tapt.',
  'Çık': 'Avslutt',
  'Serbest çizim': 'Frihånd',
  'Ok': 'Pil',
  'Dikdörtgen': 'Rektangel',
  'Daire': 'Sirkel',
  'Bulanıklaştır': 'Uskarphet',
  'Pikselleştir': 'Pikseler',
  'Silgi': 'Viskelær',
  'Çizgi kalınlığı': 'Linjetykkelse',
  'Saydamlık': 'Gjennomsiktighet',
  'Dolgu': 'Fyll',
  'Renk': 'Farge',
  'Döndür': 'Roter',
  'Yansıt': 'Speilvend',
  'Oran': 'Forhold',
  'Sıfırla': 'Tilbakestill',
  'Serbest': 'Fri',
  'Metin yaz...': 'Skriv tekst...',
  'Hizala': 'Juster',
  'Arka plan': 'Bakgrunn',
  'Emoji ara...': 'Søk emoji...',
  'Son kullanılanlar': 'Nylige',
  'İfadeler ve insanlar': 'Smilefjes og personer',
  'Hayvanlar ve doğa': 'Dyr og natur',
  'Yiyecek ve içecek': 'Mat og drikke',
  'Etkinlikler': 'Aktiviteter',
  'Seyahat ve yerler': 'Reiser og steder',
  'Nesneler': 'Objekter',
  'Semboller': 'Symboler',
  'Bayraklar': 'Flagg',
  'Görseli düzenle': 'Rediger bilde',
  'Düzenlendi': 'Redigert',
  'Düzenlenemedi': 'Kunne ikke redigeres',
  'Düzenlenen görsel çok büyük': 'Det redigerte bildet er for stort',
  'Videoyu düzenle': 'Rediger video',
  'Sesi kapat': 'Slå av lyd',
  'Sesi aç': 'Slå på lyd',
  'İptal ediliyor…': 'Avbryter…',
  'Bu biraz sürebilir': 'Dette kan ta litt tid',
  'Video çok büyük': 'Videoen er for stor',
  'Video hazırlanamadı': 'Videoen kunne ikke forberedes',
  'Başlangıç': 'Start',
  'Bitiş': 'Slutt',
  'En çok {} saniye seçebilirsin': 'Du kan velge maks {} sekunder',
  'Dosya en fazla {} MB olabilir': 'Filen kan være maks {} MB',
  'Medya ekle': 'Legg til medier',
  'Seçili medya kalmadı': 'Ingen medier valgt',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Velg et bilde eller en video du vil legge til i kommentaren din.',
  'Medya seç': 'Velg medier',
  'Daha fazla ekle': 'Legg til flere',
  'Medya seçilemedi': 'Kunne ikke velge medier',
  'Favori oyuncular': 'Favorittskuespillere',
  'Henüz favori oyuncun yok': 'Ingen favorittskuespillere ennå',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Apne en skuespillers side og trykk pa hjertet oppe til hoyre.',
  '{} yapımdan {} tanesini izledin': 'Du har sett {} av {} titler',
  'izledin': 'sett',
  'İzlemedin': 'Ikke sett',
  'Yapım bulunamadı': 'Ingen titler funnet',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Denne personen har ingen serier eller filmer a vise.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Historikken din er knyttet til kontoen din; denne listen er bare din.',
  'Hesabın kalıcı olarak askıya alındı': 'Kontoen din er permanent utestengt',
  'Hesabın geçici olarak askıya alındı': 'Kontoen din er midlertidig utestengt',
  'Hesabın askıya alındı': 'Kontoen din er utestengt',
  'Sebep': 'Årsak',
  'Kalan süre': 'Tid igjen',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Kontoen åpnes automatisk igjen når tiden er ute',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'I denne perioden kan du fortsatt lese, men du kan ikke publisere, kommentere eller sende meldinger.',
  'Anladım': 'Forstått',
  'Ayrıntı': 'Detaljer',
  '{} dakika': '{} minutter',
  'birkaç saniye': 'noen sekunder',
  'Karara itiraz et': 'Klag på avgjørelsen',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Forklar hvorfor denne straffen bør oppheves',
  'İtirazını gönder': 'Send klagen din',
  'İtirazın incelemede': 'Klagen din er til behandling',
  'İtirazın reddedildi': 'Klagen din ble avvist',
  'İtirazın alındı, inceleniyor': 'Vi har mottatt klagen din, og den behandles',
  'İtiraz en az 10 karakter olmalı': 'Klagen må være minst 10 tegn',
  'Yükleniyor...': 'Laster...',
  'Bu bölüme puan ver': 'Vurder denne episoden',
  '{} kişi puanladı': '{} personer har vurdert',
  'Bölüm izlendi olarak işaretlendi': 'Episoden er merket som sett',
  'Sesli ara': 'Taleanrop',
  'Görüntülü ara': 'Videoanrop',
  'Çalıyor...': 'Ringer...',
  'Bağlanıyor...': 'Kobler til...',
  'Cevapla': 'Svar',
  'Reddet': 'Avvis',
  'Sessize al': 'Slå av lyd',
  'Hoparlör': 'Høyttaler',
  'Kamerayı kapat': 'Slå av kamera',
  'Kamerayı çevir': 'Bytt kamera',
  'Cevap yok': 'Ingen svar',
  'Arama reddedildi': 'Anropet ble avvist',
  'Meşgul': 'Opptatt',
  'Bağlanılamadı': 'Kunne ikke koble til',
  'Arama iptal edildi': 'Anropet ble avbrutt',
  'Arama geçmişi': 'Anropslogg',
  'Gelen arama': 'Innkommende anrop',
  'Giden arama': 'Utgående anrop',
  'Cevapsız arama': 'Tapt anrop',
  'Arama şu anda kullanılamıyor': 'Anrop er ikke tilgjengelig akkurat nå',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Videoanrop er avslått nå, du kan ringe med tale',
  'Bu kullanıcıyı arayamazsın': 'Du kan ikke ringe denne brukeren',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Dere må følge hverandre for å kunne ringe',
  'Bu kullanıcı şu anda aranamıyor':
      'Denne brukeren kan ikke ringes akkurat nå',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'For mange tapte anrop. Prøv igjen om {}',
  'Zaten bir aramadasın': 'Du er allerede i et anrop',
  'Arama için mikrofon izni gerekiyor': 'Mikrofontillatelse kreves for å ringe',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'Kamera- og mikrofontillatelse kreves for videoanrop',
  'Arama başlatılamadı': 'Anropet kunne ikke startes',
  'Kullanıcı bulunamadı': 'Fant ikke brukeren',
  'Kendini arayamazsın': 'Du kan ikke ringe deg selv',
  'Arama artık geçerli değil': 'Dette anropet er ikke lenger gyldig',
  'Bu aramanın tarafı değilsin': 'Du er ikke part i dette anropet',
  'Arama bulunamadı': 'Fant ikke anropet',
  'Çok fazla istek, biraz bekle': 'For mange forespørsler, vent litt',
  'Bağlantı koptu': 'Tilkoblingen ble brutt',
  'Arama süre sınırına ulaştı': 'Anropet nådde tidsgrensen',
  'Arama en fazla 4 saat sürebilir': 'Et anrop kan vare i maks 4 timer',
  'Arama sona erdi': 'Anropet er avsluttet',
  'Sesli arama': 'Taleanrop',
  'Görüntülü arama': 'Videoanrop',
  'Gelen aramalar': 'Innkommende anrop',
  'Sesli ve görüntülü arama bildirimleri': 'Varsler om tale- og videoanrop',
  '{} sa': '{} t',
  'Sesli ve Görüntülü Aramalar': 'Tale- og videoanrop',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Innholdet i anrop blir aldri tatt opp. Lyd og video går ende-til-ende-kryptert (DTLS-SRTP) mellom enhetene; serverne våre kan verken dekryptere, avlytte eller lagre denne trafikken.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Bare metadata om anropet lagres: med hvem, i hvilken retning, når og hvor lenge. Disse oppføringene slettes automatisk etter 90 dager.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Hvis en direkte tilkobling ikke er mulig, går lyd og video kryptert gjennom en relétjener (TURN). Heller ikke den kan dekryptere eller ta opp innholdet.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Mikrofonen brukes bare under et tale- eller videoanrop, og kameraet bare under et videoanrop. Begge slås av når anropet avsluttes.',
  'Takip ettiğin {} kişi izledi': '{} personer du følger har sett det',
  'Yorum yaz...': 'Skriv en kommentar...',
  'Sıradaki bölüm': 'Neste episode',
  'Doğrulanmış testçi': 'Verifisert tester',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Varsler om følging, likerklikk, svar, meldinger og merkinger',
  'Sen': 'Du',
  'Aradığınız kişide sesli arama devre dışı':
      'Taleanrop er slått av hos denne personen',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Videoanrop er slått av hos denne personen',
  'Sesli aramalara izin ver': 'Tillat taleanrop',
  'Görüntülü aramalara izin ver': 'Tillat videoanrop',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Når det er av, kan ingen ringe deg; den som ringer ser en melding',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Når det er av, kan ingen videoringe deg; den som ringer ser en melding',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Taleanrop er av. Du kan slå dem på i Innstillinger > Personvern.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Videoanrop er av. Du kan slå dem på i Innstillinger > Personvern.',
  'Sesli ve görüntülü arama': 'Tale- og videoanrop',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Gjestekontoer kan ikke ringe. Opprett en konto for å bruke det.',
  'Misafir hesaplar aranamaz': 'Gjestekontoer kan ikke ringes',
};
