/// Otomatik üretilen çeviri haritası (el).
const Map<String, String> cevirilerEl = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Δεν βρέθηκαν αναγνωρίσιμα δεδομένα για εισαγωγή.',
  'Arama': 'Αναζήτηση',
  'Aramaya başla': 'Ξεκίνα την αναζήτηση',
  'Ayarlar': 'Ρυθμίσεις',
  'Bağla': 'Σύνδεσε',
  'Bio': 'Βιογραφικό',
  'Bitirdim': 'Το τελείωσα',
  'Bunları da Beğenebilirsin': 'Μπορεί να σου αρέσουν κι αυτά',
  'Bölüm': 'Επεισόδιο',
  'Bıraktım': 'Το παράτησα',
  'Dil': 'Γλώσσα',
  'Dil ara...': 'Αναζήτηση γλώσσας...',
  'Dizi': 'Σειρά',
  'Dizi ve filmlerini takip et': 'Παρακολούθησε τις σειρές και τις ταινίες σου',
  'Dizi yorumu': 'Σχόλιο σειράς',
  'Dizi, film veya kişi ara...': 'Ψάξε σειρά, ταινία ή πρόσωπο...',
  'Dosya en fazla 30MB olabilir': 'Το αρχείο μπορεί να είναι έως 30MB',
  'Dosya en fazla {}MB olabilir': 'Το αρχείο μπορεί να είναι έως {}MB',
  'E-posta': 'Email',
  'E-posta veya kullanıcı adı': 'Email ή όνομα χρήστη',
  'En az 2 harf yaz': 'Γράψε τουλάχιστον 2 γράμματα',
  'Film': 'Ταινία',
  'Film yorumu': 'Σχόλιο ταινίας',
  'Fotoğraf / video ekle': 'Προσθήκη φωτογραφίας / βίντεο',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Φωτογραφία ή GIF — εικόνα προφίλ και εξωφύλλου',
  'Giriş Yap': 'Σύνδεση',
  'Gönder': 'Αποστολή',
  'Gönderildi': 'Στάλθηκε',
  'Haftanın Dizileri': 'Οι Σειρές της Εβδομάδας',
  'Haftanın Filmleri': 'Οι Ταινίες της Εβδομάδας',
  'Henüz izleme kaydın yok': 'Δεν έχεις ακόμα ιστορικό προβολής',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Δεν έχεις λίστες ακόμα — φτιάξε μία από την καρτέλα Προφίλ.',
  'Henüz yorum yok.': 'Δεν υπάρχουν σχόλια ακόμα.',
  'Hesabın bağlandı!': 'Ο λογαριασμός σου συνδέθηκε!',
  'Hesabın yok mu? Kayıt ol': 'Δεν έχεις λογαριασμό; Κάνε εγγραφή',
  'Hesabını Bağla': 'Σύνδεσε τον λογαριασμό σου',
  'Hesap Oluştur': 'Δημιουργία λογαριασμού',
  'Kapak resmi ekle': 'Προσθήκη εικόνας εξωφύλλου',
  'Kaydet': 'Αποθήκευση',
  'Kendinden bahset...': 'Πες μας για σένα...',
  'Keşfet': 'Ανακάλυψε',
  'Kimseyi takip etmiyor': 'Δεν ακολουθεί κανέναν',
  'Kişi ara': 'Αναζήτηση ατόμων',
  'Kişi yorumu': 'Σχόλιο προσώπου',
  'Konuk Oyuncular': 'Καλεσμένοι Ηθοποιοί',
  'Kullanıcı adı (küçük harf)': 'Όνομα χρήστη (πεζά)',
  'Kullanıcı adı ara...': 'Αναζήτηση ονόματος χρήστη...',
  'Liste adı': 'Όνομα λίστας',
  'Listeye Ekle': 'Προσθήκη σε λίστα',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Είσαι σε λογαριασμό επισκέπτη — σύνδεσε το email σου, μη χάσεις τα δεδομένα σου!',
  'Misafir olarak devam et': 'Συνέχεια ως επισκέπτης',
  'Oluştur': 'Δημιουργία',
  'Oyuncular': 'Ηθοποιοί',
  'Profil': 'Προφίλ',
  'Profil kaydedildi': 'Το προφίλ αποθηκεύτηκε',
  'Puanla': 'Βαθμολόγησε',
  'Puanı Sil': 'Διαγραφή βαθμολογίας',
  'Puanın': 'Η βαθμολογία σου',
  'Sezonlar': 'Σεζόν',
  'Sunucu hatası ({})': 'Σφάλμα διακομιστή ({})',
  'S{} · {}. Bölüm': 'S{} · Επ. {}',
  'S{}B{} yorumu': 'Σχόλιο S{}E{}',
  'Takibi Bırak': 'Άρση ακολούθησης',
  'Takip': 'Ακολουθεί',
  'Takip Edilenler': 'Ακολουθούμενοι',
  'Takip Et': 'Ακολούθησε',
  'Takipçi': 'Ακόλουθος',
  'Takipçi yok': 'Δεν υπάρχουν ακόλουθοι',
  'Takipçiler': 'Ακόλουθοι',
  'Takvim': 'Ημερολόγιο',
  'Tamam': 'Εντάξει',
  'Tekrar Dene': 'Δοκίμασε Ξανά',
  'Tekrar dene': 'Δοκίμασε ξανά',
  'Toplam ekran süresi': 'Συνολικός χρόνος οθόνης',
  'Tüm Zamanların En İyileri': 'Τα Καλύτερα Όλων των Εποχών',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Κατέβασε όλα τα δεδομένα σου (προβολές, βαθμολογίες, σχόλια, λίστες) ως ZIP συμβατό με TV Time ή κάνε εισαγωγή ενός ZIP από άλλη εφαρμογή.',
  'Tümünü Kaldır': 'Κατάργηση όλων',
  'Tümünü İzledim': 'Τα είδα όλα',
  'Türk Dizileri': 'Τουρκικές Σειρές',
  'Veri içe aktar (.zip)': 'Εισαγωγή δεδομένων (.zip)',
  'Verilerim': 'Τα δεδομένα μου',
  'Verilerimi dışa aktar (e-posta)': 'Εξαγωγή δεδομένων (email)',
  'Verilerini dışa aktar': 'Εξαγωγή των δεδομένων σου',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Δεν υπάρχουν επερχόμενα επεισόδια.\nΒάλε μια σειρά σε κατάσταση "Το βλέπω" από τη σελίδα της και παρακολούθησε εδώ τα νέα επεισόδια.',
  'Yapımları': 'Φιλμογραφία',
  'Yeni Diziler': 'Νέες Σειρές',
  'Yeni Liste': 'Νέα Λίστα',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Νέο όνομα χρήστη (προαιρετικό)',
  'Yorum': 'Σχόλιο',
  'Yorumunu yaz...': 'Γράψε το σχόλιό σου...',
  'Zaten hesabın var mı? Giriş yap': 'Έχεις ήδη λογαριασμό; Συνδέσου',
  'ort. {}': 'μ.ό. {}',
  'takip': 'ακολουθεί',
  'takipçi': 'ακόλουθοι',
  '{} / {} bölüm': '{} / {} επεισόδια',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} μήνες',
  '{} bölüm izlendi': '{} επεισόδια παρακολουθήθηκαν',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} λεπ.',
  '{} gün': '{} μέρες',
  '{} içerik': '{} τίτλοι',
  '{} içerik · otomatik': '{} τίτλοι · αυτόματη',
  '{} kayıt atlandı (eşleşmedi).': '{} εγγραφές παραλείφθηκαν (δεν ταίριαξαν).',
  '{} saat': '{} ώρες',
  '{} sezon': '{} σεζόν',
  '{} yıl': '{} χρόνια',
  '{}. Bölüm': 'Επεισόδιο {}',
  '{}. Sezon': 'Σεζόν {}',
  'Çıkış Yap': 'Αποσύνδεση',
  'Ülke': 'Χώρα',
  'Ülke ara...': 'Αναζήτηση χώρας...',
  'Ülke seç': 'Επίλεξε χώρα',
  'İlk yorumu sen yaz!': 'Γράψε εσύ το πρώτο σχόλιο!',
  'İncelemeler': 'Κριτικές',
  'İncelemen (isteğe bağlı)': 'Η κριτική σου (προαιρετικό)',
  'İptal': 'Ακύρωση',
  'İzlediklerim': 'Οι προβολές μου',
  'İzledim': 'Το είδα',
  'İzledin': 'Το είδες',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Το ιστορικό προβολών και οι λίστες σου διατηρούνται· πλέον μπορείς να συνδέεσαι από οποιαδήποτε συσκευή.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Το ιστορικό προβολών, οι βαθμολογίες, τα σχόλια και οι λίστες σου θα σταλούν ως ZIP στο καταχωρημένο email σου.',
  'İzleyeceğim': 'Θα το δω',
  'İzliyorum': 'Το βλέπω',
  'İçe aktarım tamamlandı': 'Η εισαγωγή ολοκληρώθηκε',
  'Şifre': 'Κωδικός',
  '• profil bilgisi': '• στοιχεία προφίλ',
  '• {} dizi durumu': '• {} καταστάσεις σειρών',
  '• {} izleme kaydı': '• {} εγγραφές προβολής',
  '• {} liste': '• {} λίστες',
  '• {} puan': '• {} βαθμολογίες',
  '• {} yorum': '• {} σχόλια',
  '{}+ yapım': '{}+ τίτλοι',
  'Yorumlar': 'Σχόλια',
  'Yorumlar ({})': 'Σχόλια ({})',
  'Yorumları ({})': 'Τα σχόλιά του/της ({})',
  'Listelerim': 'Οι λίστες μου',
  'Nereden izledin?': 'Πού το είδες;',
  'Diziye git': 'Μετάβαση στη σειρά',
  'TV / Kanal': 'TV / Κανάλι',
  'Sinema': 'Σινεμά',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Άλλο',
  'Akış': 'Ροή',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Η ροή σου είναι άδεια.\nΌταν σχολιάσουν τις σειρές και ταινίες που βλέπεις, θα εμφανιστεί εδώ.',
  'Listeleri ({})': 'Οι λίστες του ({})',
  'Liste boş.': 'Αυτή η λίστα είναι άδεια.',
  'Yanıtla': 'Απάντηση',
  '@{} kullanıcısına yanıt veriyorsun': 'Απαντάς στον @{}',
  'İzlediğim Diziler ({})': 'Σειρές που είδα ({})',
  'İzlediğim Filmler ({})': 'Ταινίες που είδα ({})',
  'Tümünü gör': 'Δες όλα',
  'Bildirimler': 'Ειδοποιήσεις',
  'Henüz bildirim yok': 'Καμία ειδοποίηση ακόμα',
  '@{} yorumuna yanıt verdi': 'Ο @{} απάντησε στο σχόλιό σου',
  '@{} yorumunu beğendi': 'Στον @{} άρεσε το σχόλιό σου',
  '@{} seni takip etti': 'Ο @{} σε ακολούθησε',
  '@{} sana mesaj gönderdi': 'Ο @{} σου έστειλε μήνυμα',
  'Mesajlar': 'Μηνύματα',
  'Mesaj': 'Μήνυμα',
  'Mesajını yaz...': 'Γράψε ένα μήνυμα...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Καμία συνομιλία ακόμα.\nΆνοιξε ένα προφίλ και στείλε μήνυμα.',
  'Şifreni mi unuttun?': 'Ξέχασες τον κωδικό;',
  'Şifreyi Sıfırla': 'Επαναφορά κωδικού',
  'E-postadaki kod': 'Κωδικός από το email',
  'Yeni şifre': 'Νέος κωδικός',
  'Sana Özel': 'Για σένα',
  '{} özetin': 'Η ανασκόπησή σου του {}',
  'Yıllık izleme istatistiklerin': 'Ετήσια στατιστικά προβολών',
  'Rozetler': 'Παράσημα',
  'Verdiğin puan': 'Βαθμολογίες που έδωσες',
  'Ortalama puanın': 'Μέση βαθμολογία σου',
  'En çok izlediğin diziler': 'Οι πιο προβεβλημένες σειρές σου',
  'İlk Bölüm': 'Πρώτο επεισόδιο',
  '100 Bölüm': '100 επεισόδια',
  '1000 Bölüm': '1000 επεισόδια',
  'İlk Film': 'Πρώτη ταινία',
  '50 Film': '50 ταινίες',
  'İlk Yorum': 'Πρώτο σχόλιο',
  '25 Yorum': '25 σχόλια',
  '10 Puan': '10 βαθμολογίες',
  'İlk Takipçi': 'Πρώτος ακόλουθος',
  '10 Dizi Bitirdin': 'Ολοκλήρωσες 10 σειρές',
  'İzlemeyi Bıraktım': 'Σταμάτησα να βλέπω',
  'İzlediği Diziler ({})': 'Σειρές που είδε ({})',
  'İzlediği Filmler ({})': 'Ταινίες που είδε ({})',
  '500 Bölüm': '500 επεισόδια',
  '5000 Bölüm': '5000 επεισόδια',
  '10 Film': '10 ταινίες',
  '100 Film': '100 ταινίες',
  '100 Yorum': '100 σχόλια',
  '50 Puan': '50 βαθμολογίες',
  '100 Puan': '100 βαθμολογίες',
  '10 Takipçi': '10 ακόλουθοι',
  '50 Takipçi': '50 ακόλουθοι',
  '25 Dizi Bitirdin': 'Ολοκλήρωσε 25 σειρές',
  '50 Dizi Bitirdin': 'Ολοκλήρωσε 50 σειρές',
  '10 Beğeni': '10 μου αρέσει',
  '100 Beğeni': '100 μου αρέσει',
  'yazıyor...': 'πληκτρολογεί...',
  'Profil düzeni': 'Διάταξη προφίλ',
  'Konumla ve kırp': 'Τοποθέτησε και περίκοψε',
  'Listeye eklendi': 'Προστέθηκε στη λίστα',
  'Listeyi sil?': 'Διαγραφή λίστας;',
  'Sil': 'Διαγραφή',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Θα σημειωθεί ως μη προβεβλημένο και θα αφαιρεθεί από τις λίστες σου.',
  'Gelecek bölüm bugün': 'Επόμενο επεισόδιο σήμερα',
  'Gelecek bölüm {} gün sonra': 'Επόμενο επεισόδιο σε {} μέρες',
  'Tema': 'Θέμα',
  'Sistem': 'Σύστημα',
  'Koyu': 'Σκούρο',
  'Açık': 'Φωτεινό',
  'İzleyenler': 'Θεατές',
  'Yorumunu yaz... (@ ile etiketle)':
      'Γράψε το σχόλιό σου... (@ για επισήμανση)',
  '@{} bir yorumda seni etiketledi': 'Ο/Η @{} σε επισήμανε σε σχόλιο',
  'Mesajı sil': 'Διαγραφή μηνύματος',
  'Mesaj silinemedi': 'Δεν ήταν δυνατή η διαγραφή του μηνύματος',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Ο σύνδεσμος δεν είναι έγκυρος ή η σελίδα δεν βρέθηκε',
  'Keşfet\'e dön': 'Πίσω στην Ανακάλυψη',
};
