/// Otomatik üretilen çeviri haritası (he).
const Map<String, String> cevirilerHe = {
  'Hepsini gördün, baştan gösteriyoruz': 'ראית הכל, אנחנו מראים לך מההתחלה',
  'Aktarılacak tanınan veri bulunamadı.': 'לא נמצאו נתונים מזוהים לייבוא.',
  'Arama': 'חיפוש',
  'Aramaya başla': 'התחל לחפש',
  'Son aramalar': 'חיפושים אחרונים',
  'Ayarlar': 'הגדרות',
  'Bağla': 'קשר',
  'Bio': 'ביו',
  'Bitirdim': 'סיימתי',
  'Bunları da Beğenebilirsin': 'אולי תאהב גם את אלה',
  'Bölüm': 'פרק',
  'Bıraktım': 'נטשתי',
  'Dil': 'שפה',
  'Dil ara...': 'חפש שפה...',
  'Dizi': 'סדרה',
  'Dizi ve filmlerini takip et': 'עקוב אחרי הסדרות והסרטים שלך',
  'Dizi yorumu': 'תגובה על הסדרה',
  'Dizi, film veya kişi ara...': 'חפש סדרה, סרט או אדם...',
  'Dosya en fazla 30MB olabilir': 'גודל הקובץ יכול להיות עד 30MB',
  'Dosya en fazla {}MB olabilir': 'גודל הקובץ יכול להיות עד {}MB',
  'E-posta': 'אימייל',
  'E-posta veya kullanıcı adı': 'אימייל או שם משתמש',
  'En az 2 harf yaz': 'הקלד לפחות 2 אותיות',
  'Film': 'סרט',
  'Film yorumu': 'תגובה על הסרט',
  'Fotoğraf / video ekle': 'הוסף תמונה / וידאו',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'תמונה או GIF — תמונת פרופיל וקאבר',
  'Giriş Yap': 'התחברות',
  'Gönder': 'שלח',
  'Gönderildi': 'נשלח',
  'Haftanın Dizileri': 'סדרות השבוע',
  'Haftanın Filmleri': 'סרטי השבוע',
  'Henüz izleme kaydın yok': 'אין לך עדיין היסטוריית צפייה',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'אין לך עדיין רשימות — צור אחת מלשונית הפרופיל.',
  'Henüz yorum yok.': 'אין תגובות עדיין.',
  'Hesabın bağlandı!': 'החשבון שלך קושר!',
  'Hesabın yok mu? Kayıt ol': 'אין לך חשבון? הירשם',
  'Hesabını Bağla': 'קשר את החשבון שלך',
  'Hesap Oluştur': 'יצירת חשבון',
  'Kapak resmi ekle': 'הוסף תמונת קאבר',
  'Kaydet': 'שמור',
  'Kendinden bahset...': 'ספר על עצמך...',
  'Keşfet': 'גלה',
  'Kimseyi takip etmiyor': 'אין מעקבים',
  'Kişi ara': 'חפש אדם',
  'Kişi yorumu': 'תגובה על האדם',
  'Konuk Oyuncular': 'שחקנים אורחים',
  'Kullanıcı adı (küçük harf)': 'שם משתמש (אותיות קטנות)',
  'Kullanıcı adı ara...': 'חפש שם משתמש...',
  'Liste adı': 'שם הרשימה',
  'Listeye Ekle': 'הוסף לרשימה',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'אתה בחשבון אורח — קשר אותו לאימייל שלך ואל תאבד את הנתונים!',
  'Misafir olarak devam et': 'המשך כאורח',
  'Oluştur': 'צור',
  'Oyuncular': 'שחקנים',
  'Profil': 'פרופיל',
  'Profil kaydedildi': 'הפרופיל נשמר',
  'Puanla': 'דרג',
  'Puanı Sil': 'מחק דירוג',
  'Puanın': 'הדירוג שלך',
  'Sezonlar': 'עונות',
  'Sunucu hatası ({})': 'שגיאת שרת ({})',
  'S{} · {}. Bölüm': 'ע{} · פרק {}',
  'S{}B{} yorumu': 'תגובה על ע{}פ{}',
  'Takibi Bırak': 'הפסק לעקוב',
  'Takip': 'במעקב',
  'Takip Edilenler': 'נעקבים',
  'Takip Et': 'עקוב',
  'Takipçi': 'עוקב',
  'Takipçi yok': 'אין עוקבים',
  'Takipçiler': 'עוקבים',
  'Takvim': 'לוח שנה',
  'Tamam': 'אישור',
  'Tekrar Dene': 'נסה שוב',
  'Tekrar dene': 'נסה שוב',
  'Toplam İzleme Süresi': 'זמן מסך כולל',
  'Tüm Zamanların En İyileri': 'הטובים בכל הזמנים',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'ייצא את כל הנתונים שלך (צפיות, דירוגים, תגובות, רשימות) כקובץ ZIP תואם TV Time, או ייבא ZIP מאפליקציה אחרת.',
  'Tümünü Kaldır': 'הסר הכל',
  'Tümünü İzledim': 'צפיתי בהכל',
  'Türk Dizileri': 'סדרות טורקיות',
  'Veri içe aktar (.zip)': 'ייבוא נתונים (.zip)',
  'Verilerim': 'הנתונים שלי',
  'Verilerimi dışa aktar (e-posta)': 'ייצוא הנתונים שלי (אימייל)',
  'Verilerini dışa aktar': 'ייצא את הנתונים שלך',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'אין פרקים קרובים.\nהעבר סדרה למצב "צופה" מדף הסדרה ועקוב אחרי פרקים חדשים כאן.',
  'Yapımları': 'פילמוגרפיה',
  'Yeni Diziler': 'סדרות חדשות',
  'Yeni Liste': 'רשימה חדשה',
  'Yeni kullanıcı adı (isteğe bağlı)': 'שם משתמש חדש (אופציונלי)',
  'Yorum': 'תגובה',
  'Yorumunu yaz...': 'כתוב את התגובה שלך...',
  'Zaten hesabın var mı? Giriş yap': 'כבר יש לך חשבון? התחבר',
  'ort. {}': 'ממוצע {}',
  'takip': 'במעקב',
  'takipçi': 'עוקבים',
  '{} / {} bölüm': '{} / {} פרקים',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} חודשים',
  '{} ay~tekil': '{} חודש',
  '{} bölüm izlendi': '{} פרקים נצפו',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': "{} דק'",
  '{} dk~tekil': "{} דק'",
  '{} gün': '{} ימים',
  '{} gün~tekil': '{} יום',
  '{} içerik': '{} פריטים',
  '{} içerik · otomatik': '{} פריטים · אוטומטי',
  '{} kayıt atlandı (eşleşmedi).': '{} רשומות דולגו (ללא התאמה).',
  '{} saat': '{} שעות',
  '{} saat~tekil': '{} שעה',
  '{} sezon': '{} עונות',
  '{} yıl': '{} שנים',
  '{} yıl~tekil': '{} שנה',
  '{}. Bölüm': 'פרק {}',
  '{}. Sezon': 'עונה {}',
  'Çıkış Yap': 'התנתקות',
  'Ülke': 'מדינה',
  'Ülke ara...': 'חפש מדינה...',
  'Ülke seç': 'בחר מדינה',
  'İlk yorumu sen yaz!': 'כתוב את התגובה הראשונה!',
  'İncelemeler': 'ביקורות',
  'İncelemen (isteğe bağlı)': 'הביקורת שלך (אופציונלי)',
  'İptal': 'ביטול',
  'İzlediklerim': 'הצפיות שלי',
  'İzledim': 'צפיתי',
  'İzledin': 'צפית',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'היסטוריית הצפייה והרשימות שלך נשמרות; מעכשיו תוכל להתחבר מכל מכשיר.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'היסטוריית הצפייה, הדירוגים, התגובות והרשימות שלך יישלחו כקובץ ZIP לכתובת האימייל הרשומה שלך.',
  'İzleyeceğim': 'אצפה',
  'İzliyorum': 'צופה',
  'İçe aktarım tamamlandı': 'הייבוא הושלם',
  'Şifre': 'סיסמה',
  '• profil bilgisi': '• פרטי פרופיל',
  '• {} dizi durumu': '• {} סטטוסי סדרות',
  '• {} izleme kaydı': '• {} רשומות צפייה',
  '• {} liste': '• {} רשימות',
  '• {} puan': '• {} דירוגים',
  '• {} yorum': '• {} תגובות',
  '{}+ yapım': '{}+ עבודות',
  'Yorumlar': 'תגובות',
  'Yorumlar ({})': 'תגובות ({})',
  'Yorumları ({})': 'התגובות ({})',
  'Listelerim': 'הרשימות שלי',
  'Nereden izledin?': 'איפה צפית?',
  'Diziye git': 'אל הסדרה',
  'TV / Kanal': 'טלוויזיה / ערוץ',
  'Sinema': 'קולנוע',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'אחר',
  'Akış': 'פיד',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'הפיד שלך ריק.\nכשיגיבו על הסדרות והסרטים שאתה צופה בהם, זה יופיע כאן.',
  'Listeleri ({})': 'רשימות ({})',
  'Liste boş.': 'הרשימה הזו ריקה.',
  'Yanıtla': 'השב',
  '@{} kullanıcısına yanıt veriyorsun': 'בתגובה ל-@{}',
  'İzlediğim Diziler ({})': 'סדרות שצפיתי ({})',
  'İzlediğim Filmler ({})': 'סרטים שצפיתי ({})',
  'Tümünü gör': 'הצג הכול',
  'Bildirimler': 'התראות',
  'Henüz bildirim yok': 'אין התראות עדיין',
  '@{} yorumuna yanıt verdi': 'תשובה חדשה לתגובה שלך: @{}',
  '@{} yorumunu beğendi': 'לייק חדש לתגובה שלך: @{}',
  '@{} seni takip etti': 'מעקב חדש: @{}',
  '@{} sana mesaj gönderdi': 'הודעה חדשה מ-@{}',
  'Mesajlar': 'הודעות',
  'Mesaj': 'הודעה',
  'Mesaja eklenecek': 'יתווסף להודעה',
  'Mesajını yaz...': 'כתוב הודעה...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      "אין צ'אטים עדיין.\nפתח פרופיל ושלח הודעה.",
  'Şifreni mi unuttun?': 'שכחת סיסמה?',
  'Şifreyi Sıfırla': 'איפוס סיסמה',
  'E-postadaki kod': 'הקוד מהמייל',
  'Yeni şifre': 'סיסמה חדשה',
  'Sana Özel': 'בשבילך',
  '{} özetin': 'הסיכום שלך ל-{}',
  'Yıllık izleme istatistiklerin': 'סטטיסטיקת הצפייה השנתית',
  'Rozetler': 'תגים',
  'Verdiğin puan': 'דירוגים שנתת',
  'Ortalama puanın': 'הדירוג הממוצע שלך',
  'En çok izlediğin diziler': 'הסדרות שצפית בהן הכי הרבה',
  'İlk Bölüm': 'פרק ראשון',
  '100 Bölüm': '100 פרקים',
  '1000 Bölüm': '1000 פרקים',
  'İlk Film': 'סרט ראשון',
  '50 Film': '50 סרטים',
  'İlk Yorum': 'תגובה ראשונה',
  '25 Yorum': '25 תגובות',
  '10 Puan': '10 דירוגים',
  'İlk Takipçi': 'עוקב ראשון',
  '10 Dizi Bitirdin': 'סיימת 10 סדרות',
  'İzlemeyi Bıraktım': 'הפסקתי לצפות',
  'İzlediği Diziler ({})': 'סדרות שנצפו ({})',
  'İzlediği Filmler ({})': 'סרטים שנצפו ({})',
  '500 Bölüm': '500 פרקים',
  '5000 Bölüm': '5000 פרקים',
  '10 Film': '10 סרטים',
  '100 Film': '100 סרטים',
  '100 Yorum': '100 תגובות',
  '50 Puan': '50 דירוגים',
  '100 Puan': '100 דירוגים',
  '10 Takipçi': '10 עוקבים',
  '50 Takipçi': '50 עוקבים',
  '25 Dizi Bitirdin': 'סיים 25 סדרות',
  '50 Dizi Bitirdin': 'סיים 50 סדרות',
  '10 Beğeni': '10 לייקים',
  '100 Beğeni': '100 לייקים',
  'yazıyor...': 'בהקלדה...',
  'ses kaydediyor...': 'בהקלטת שמע...',
  'Profil düzeni': 'פריסת פרופיל',
  'Konumla ve kırp': 'מקם וחתוך',
  'Listeye eklendi': 'נוסף לרשימה',
  'Listeyi sil?': 'למחוק את הרשימה?',
  'Sil': 'מחק',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'הכותר יסומן כלא נצפה ויוסר מהרשימות שלך.',
  'Gelecek bölüm bugün': 'הפרק הבא היום',
  'Gelecek bölüm {} gün sonra': 'הפרק הבא בעוד {} ימים',
  'Tema': 'ערכת נושא',
  'Sistem': 'מערכת',
  'Koyu': 'כהה',
  'Açık': 'בהיר',
  'İzleyenler': 'צופים',
  'Yorumunu yaz... (@ ile etiketle)': 'כתוב את התגובה שלך... (@ לתיוג)',
  '@{} bir yorumda seni etiketledi': 'תיוג מ-@{} בתגובה',
  'Mesajı sil': 'מחק הודעה',
  'Mesaj silinemedi': 'לא ניתן היה למחוק את ההודעה',
  'Bağlantı geçersiz veya sayfa bulunamadı': 'הקישור אינו תקין או שהדף לא נמצא',
  "Keşfet'e dön": 'חזרה לגילוי',
  'Düzenle': 'ערוך',
  'Mesajı düzenle': 'ערוך הודעה',
  'Yanıtlanıyor': 'משיב',
  'düzenlendi': 'נערך',
  'Fotoğraf': 'תמונה',
  'Video': 'וידאו',
  'İçerik': 'תוכן',
  'çevrimiçi': 'מחובר',
  'son görülme {} dk önce': "פעילות אחרונה לפני {} דק'",
  'son görülme {} saat önce': "פעילות אחרונה לפני {} ש'",
  'son görülme {} gün önce': "פעילות אחרונה לפני {} י'",
  'Yorumlar yüklenemedi': 'לא ניתן היה לטעון תגובות',
  'Favori': 'מועדף',
  'Listeye ekle': 'הוסף לרשימה',
  'İçerik paylaş': 'שתף תוכן',
  'Kapat': 'סגור',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'כל מה שתסמן כנצפה נאסף כאן.',
  'Henüz sohbetin yok': 'אין שיחות עדיין',
  'Bir profile girip mesaj gönderebilirsin.': 'פתח פרופיל ושלח הודעה.',
  'Listeyi sil': 'מחק רשימה',
  'Puan kaydedilemedi': 'לא ניתן היה לשמור את הדירוג',
  'Nerede İzlenir': 'איפה לצפות',
  'Abonelik': 'מנוי',
  'Kirala': 'השכרה',
  'Satın al': 'קנייה',
  'Devam et': 'המשך',
  'Şikayet et': 'דיווח',
  'Engelle': 'חסימה',
  'Engeli kaldır': 'ביטול חסימה',
  'Kullanıcı engellendi': 'המשתמש נחסם',
  'Engel kaldırıldı': 'החסימה הוסרה',
  'Şikayet sebebi': 'סיבת הדיווח',
  'Spam veya yanıltıcı': 'ספאם או מטעה',
  'Taciz veya nefret söylemi': 'הטרדה או דברי שנאה',
  'Uygunsuz / cinsel içerik': 'תוכן לא הולם / מיני',
  'Şiddet veya tehlikeli içerik': 'אלימות או תוכן מסוכן',
  'Telif hakkı ihlali': 'הפרת זכויות יוצרים',
  'Şikayetin alındı, teşekkürler': 'הדיווח שלך התקבל, תודה',
  'Hesabımı Sil': 'מחיקת החשבון שלי',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'החשבון שלך וכל הנתונים שלך (היסטוריה, דירוגים, תגובות, רשימות, הודעות) יימחקו לצמיתות. לא ניתן לבטל זאת.',
  'Şifreni gir': 'הזן את הסיסמה שלך',
  'Hesabımı kalıcı sil': 'מחק את החשבון שלי לצמיתות',
  'Sesli mesaj': 'הודעה קולית',
  'Ses gönderilemedi': 'לא ניתן היה לשלוח את ההודעה הקולית',
  'Kaydediliyor…': 'מקליט…',
  'Ses oynatılamadı': 'לא ניתן להפעיל את ההודעה הקולית',
  'Oynat': 'הפעל',
  'Fragmanı oynat': 'הפעל טריילר',
  'Altyazıyı aç': 'הפעל כתוביות',
  'Altyazıyı kapat': 'כבה כתוביות',
  '10 saniye ileri': 'דלג 10 שניות קדימה',
  '10 saniye geri': 'דלג 10 שניות אחורה',
  'Duraklat': 'השהה',
  'Liste görünümü': 'תצוגת רשימה',
  'Takvim görünümü': 'תצוגת לוח שנה',
  'Önceki ay': 'חודש קודם',
  'Sonraki ay': 'חודש הבא',
  'Bu gün bölüm yok': 'אין פרקים ביום זה',
  'Gizlilik Politikası': 'מדיניות פרטיות',
  'Son güncelleme: {}': 'עדכון אחרון: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'מדיניות זו מסבירה אילו נתונים נאספים, כיצד הם משמשים ומהן הזכויות שלך כשאתה משתמש באפליקציית dizi.jpg ובאתר dizijpg.com.',
  'Topladığımız Veriler': 'אילו נתונים אנחנו אוספים',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'חשבון: כתובת אימייל, שם משתמש וסיסמה. הסיסמאות נשמרות כגיבוב בלתי הפיך; בחשבונות אורח אפשר להשתמש בלי אימייל.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'פרופיל: מידע שאתה בוחר להוסיף, כמו אווטאר, תמונת רקע, ביו ומדינה.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'שימוש: היסטוריית הצפייה, הדירוגים, התגובות, הרשימות, הריאקציות והמועדפים שלך.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'הודעות: הודעות הטקסט, התמונה והקול שלך נשמרות בשרתים שלנו. ההודעות אינן מוצפנות מקצה לקצה; הן נבדקות רק אם הוגש עליהן דיווח, לצורכי פיקוח.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'מדיה שהועלתה: תמונות, קובצי GIF, סרטונים והקלטות קול שאתה מוסיף לפרופיל, לתגובות ולהודעות.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'נתונים טכניים: כתובת IP, מיקום משוער (מדינה/עיר), פלטפורמת המכשיר, גרסת האפליקציה ויומני שגיאות. אלה נשמרים לצורכי אבטחה ותיקון תקלות.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'סטטיסטיקת שימוש: סוג המכשיר, מערכת ההפעלה והדפדפן שדרכם נכנסים נוספים כקטגוריות גסות למונים יומיים כוללים; מזהה הדפדפן עצמו אינו נשמר והמספרים האלה אינם ניתנים לקישור לאנשים.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'התראות: לצורך התראות פוש אנחנו שומרים את אסימון המכשיר ואת שפת ההעדפה שלך. אפשר לכבות התראות בכל עת בהגדרות המכשיר.',
  'Verileri Nasıl Kullanırız': 'איך אנחנו משתמשים בנתונים שלך',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'אנחנו משתמשים בנתונים שלך אך ורק כדי לספק את השירות, להגן על החשבון, לשלוח התראות, לתקן תקלות ולמנוע שימוש לרעה. אנחנו לא מוכרים את הנתונים שלך ולא משתפים אותם עם איש למטרות פרסום.',
  'Çerezler ve Yerel Depolama': 'עוגיות ואחסון מקומי',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'אנחנו משתמשים באחסון מקומי רק כדי לשמור אותך מחובר ולזכור העדפות כמו שפה וערכת נושא. אין עוגיות פרסום או מעקב.',
  'Üçüncü Taraf Hizmetler': 'שירותי צד שלישי',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'נתוני הסדרות והסרטים מגיעים מ-TMDB, ומידע על פלטפורמות סטרימינג מ-JustWatch. התראות פוש נשלחות דרך Google Firebase, ותעבורת האתר מוגנת על ידי Cloudflare. שירותים אלה כפופים למדיניות הפרטיות שלהם.',
  'Saklama ve Silme': 'שמירה ומחיקה',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'הנתונים שלך נשמרים כל עוד החשבון קיים. באמצעות "מחק את החשבון שלי" בהגדרות אפשר למחוק את החשבון לצמיתות; הנתונים נמחקים מיד, והעותקים בגיבויים בתוך 14 יום לכל היותר. יומני שגיאות נמחקים אוטומטית אחרי 30 יום.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'אפשר לייצא את הנתונים שלך כקובץ ZIP מההגדרות; הארכיון נשלח לכתובת האימייל שלך.',
  'Güvenlik': 'אבטחה',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'הנתונים עוברים בחיבורים מוצפנים (HTTPS) ונשמרים בשרתים עם גישה מוגבלת.',
  'Çocukların Gizliliği': 'פרטיות ילדים',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      '‏dizi.jpg אינו מיועד לילדים מתחת לגיל 13.',
  'Hakların': 'הזכויות שלך',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'לפי KVKK ו-GDPR יש לך זכות לגשת לנתונים שלך, לתקן אותם, למחוק אותם ולהעביר אותם. בנושאים אלה כתוב לנו: {}',
  'Değişiklikler': 'שינויים',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'אם המדיניות תשתנה, הגרסה החדשה תפורסם בעמוד זה והתאריך יעודכן.',
  'Kayıt olarak {} kabul etmiş olursun.': 'בהרשמה אתה מקבל את {}.',
  'Kullanıcılar': 'משתמשים',
  'Fotoğrafı değiştir': 'החלפת תמונה',
  'Yeniden konumlandır': 'מיקום מחדש',
  'Bir şeyler ters gitti': 'משהו השתבש',
  'Sosyal Bağlantılar': 'קישורים חברתיים',
  'Profilinde en fazla 3 bağlantı gösterilir.': 'בפרופיל מוצגים עד 3 קישורים.',
  'Platform seç': 'בחר פלטפורמה',
  'Kullanıcı adın': 'שם המשתמש שלך',
  'Ekle': 'הוספה',
  'Kaldır': 'הסרה',
  'Kopyalandı: {}': 'הועתק: {}',
  'Geçersiz kullanıcı adı': 'שם משתמש לא תקין',
  'Bağlantı ekle': 'הוספת קישור',
  'Spoiler olabilir — dokun ve gör': 'עשוי להכיל ספוילרים — הקש כדי לצפות',
  'Beğeni': 'לייקים',
  'beğeni': 'לייקים',
  'Beğen': 'אהבתי',
  'Görüntülenme': 'צפיות',
  'görüntülenme': 'צפיות',
  'Tam ekran': 'מסך מלא',
  'Arama başarısız': 'החיפוש נכשל',
  'Sonuç bulunamadı': 'אין תוצאות',
  'Dizi ve Filmler': 'סדרות וסרטים',
  'Kişiler': 'אנשים',
  'Ana Sayfa': 'בית',
  'Paylaş': 'שיתוף',
  'Yanıtlar': 'תגובות',
  'Yaklaşan Bölümler': 'פרקים קרובים',
  'Yetişme Listesi': 'רשימת השלמות',
  'Şunu mu demek istedin': 'האם התכוונת ל',
  'Spoiler': 'ספוילר',
  'Spoiler — dokun ve gör': 'ספוילר — הקש כדי לראות',
  'uyum': 'התאמה',
  'Uyum': 'התאמה',
  '{} ortak dizi': '{} סדרות משותפות',
  '{} ortak film': '{} סרטים משותפים',
  'Bildirim Tercihleri': 'העדפות התראות',
  'Beğeniler': 'לייקים',
  'Yeni takipçiler': 'עוקבים חדשים',
  'Etiketlenmeler': 'אזכורים',
  'Yeniden izledim': 'נצפה שוב',
  '{}. kez izlendi': 'נצפה {} פעמים',
  'Gönderi bulunamadı': 'הפוסט לא נמצא',
  'Gözat': 'עיון',
  'Diziler': 'סדרות',
  'Filmler': 'סרטים',
  'Tümü': 'הכול',
  'Farklı bir tür seç.': "נסה ז'אנר אחר.",
  'Gizlilik': 'פרטיות',
  'İzlediklerimi gizle': 'להסתיר מה שצפיתי',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'סדרות וסרטים שצפית בהם לא יוצגו בפרופיל שלך',
  'Yorumlarımı gizle': 'להסתיר את התגובות שלי',
  'Profilinde yorumların görünmez': 'התגובות שלך לא יוצגו בפרופיל שלך',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'אפשר להסתיר סדרה או סרט מסוימים עם הצ\'יפ "הסתר בפרופיל שלי" בעמוד התוכן.',
  'Geri Bildirim': 'משוב',
  'Uygulama hakkında görüş ve önerini yaz...':
      'כתוב את דעתך והצעותיך על האפליקציה...',
  'Teşekkürler! Geri bildirimin alındı.': 'תודה! המשוב שלך התקבל.',
  'Profilimde gizle': 'הסתר בפרופיל שלי',
  'Yorumları': 'התגובות',
  'Bu kullanıcı henüz bir şey izlememiş.': 'המשתמש הזה עדיין לא צפה בכלום.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'התגובות של המשתמש הזה מוסתרות.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'נתונים: JustWatch',
  'Web Sitesi': 'אתר אינטרנט',
  'Diğer uygulamalar': 'אפליקציות נוספות',
  'Bağlantıyı kopyala': 'העתק קישור',
  'Henüz kimseyi takip etmiyorsun.': 'עדיין לא עוקב אחרי אף אחד.',
  'Çevir': 'תרגם',
  'Çeviri şu an yapılamadı': 'לא ניתן לתרגם כרגע',
  'Bağlantı açılamadı': 'לא ניתן לפתוח את הקישור',
  'Orijinali göster': 'הצג מקור',
  'Çeviriyi göster': 'הצג תרגום',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'אין פרקים עם תאריך שידור מוכרז החודש. התאריכים מתפרסמים בדרך כלל שבועות ספורים מראש ויופיעו כאן.',
  'devamı': 'עוד',
  'Google ile devam et': 'המשך עם Google',
  'Google girişi başarısız': 'ההתחברות עם Google נכשלה',
  'Veri tasarrufu': 'חיסכון בנתונים',
  'Wi-Fi ağında veri tasarrufu': 'חיסכון בנתונים ב-Wi-Fi',
  'Mobil veride veri tasarrufu': 'חיסכון בנתונים בחבילת גלישה',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'כשהאפשרות פעילה התמונות לא יורדות מראש, נטענת רק התמונה שאתה צופה בה.',
  'Çocuk güvenliği': 'בטיחות ילדים',
  'Türk Filmleri': 'סרטים טורקיים',
  'En Yüksek Puanlı Filmler': 'הסרטים המדורגים ביותר',
  'En Yüksek Puanlı Diziler': 'הסדרות המדורגות ביותר',
  'En Çok İzlenen Filmler': 'הסרטים הנצפים ביותר',
  'Popüler Diziler': 'סדרות פופולריות',
  'En Çok Kazanan Filmler': 'הסרטים המכניסים ביותר',
  'Kült Filmler': 'סרטי פולחן',
  'Yeni Filmler': 'סרטים חדשים',
  'Yorum yap': 'הוסף תגובה',
  'Henüz yorum yok': 'אין עדיין תגובות',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'התגובות שלך על סדרות וסרטים נאספות כאן.',
  'GIF ekle': 'הוספת GIF',
  'İlk yorumu sen yaz': 'היה הראשון להגיב',
  'Video altyazıları': 'כתוביות וידאו',
  'Videolarda altyazı göster': 'הצג כתוביות בסרטונים',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'המשפט הנאמר בסרטון כתוב על המסך. הטקסט הוא תרגום: אנגלית בדיבור טורקי, טורקית בשפות אחרות.',
  'Güncelleme gerekli': 'נדרש עדכון',
  'Yeni sürüm var': 'יש גרסה חדשה',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'התקן את הגרסה החדשה של dizi.jpg כדי להמשיך.',
  'Güncelle': 'עדכן',
  'Daha sonra': 'מאוחר יותר',
  'Takvim güncelleniyor': 'מעדכן את לוח השידורים',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'לא ניתן היה לעדכן את לוח השידורים, מוצגת הרשימה הישנה',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'חלק מהסדרות לא נטענו, ייתכן שהרשימה חלקית',
  'Yenile': 'רענן',
  'Devam etmek için giriş yap': 'התחבר כדי להמשיך',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'חשבון חינמי מספיק כדי לדרג, להגיב ולבנות את הספרייה שלך.',
  'Şimdi değil': 'לא עכשיו',
  'Yorum yazmak için giriş yap': 'התחבר כדי לכתוב תגובה',
  'Kişilere göndermek için giriş yap': 'התחבר כדי לשלוח לאנשים',
  'Beğenenler': 'לייקים',
  'Henüz beğeni yok': 'אין עדיין לייקים',
  'Bu gönderiyi ilk beğenen sen ol': 'סמנו לייק ראשונים לפוסט הזה',
  'Bu gönderiye yanıt': 'תגובה לפוסט הזה',
  'Spoiler içeren gönderi': 'פוסט עם ספוילרים',
  'Görsel gönderi': 'פוסט עם תמונה',
  'Bu yorumu profilimde gizle': 'הסתר את התגובה הזו מהפרופיל שלי',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'התגובה נשארת בדף הסדרה או הסרט',
  'Bu yorumu sil': 'מחק את התגובה הזו',
  'Yorum profilinde gizlendi': 'התגובה הוסתרה מהפרופיל שלך',
  'Geri al': 'בטל',
  'Yorum silinsin mi?': 'למחוק את התגובה?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'תגובה זו תימחק לצמיתות מכל מקום. לא ניתן לבטל פעולה זו.',
  'Yorum silindi': 'התגובה נמחקה',
  'Yorum profilinde tekrar görünüyor': 'התגובה גלויה שוב בפרופיל שלך',
  'Gizlenen yorumun yok': 'אין לך תגובות מוסתרות',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'תגובות שאתה מסתיר בלחיצה ארוכה על פוסט בלשונית התגובות בפרופיל שלך נאספות כאן.',
  'Gizlenen yorumlar': 'תגובות מוסתרות',
  'Gönderiye git': 'עבור לפוסט',
  'Tekrar göster': 'הצג שוב',
  'Yanıtlarımı gizle': 'הסתר את התשובות שלי',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'תשובות שאתה כותב לפוסטים של אחרים גלויות רק לך',
  'Profilinde gizlediğin yorumları tekrar göster':
      'הצג שוב את התגובות שהסתרת בפרופיל שלך',
  'Sıralama': 'מיון',
  'Önerilen': 'מומלץ',
  'Kronolojik': 'כרונולוגי',
  'Gelen mesaj istekleri': 'בקשות הודעה נכנסות',
  'Mesaj isteğin yok': 'אין לך בקשות הודעה',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'הודעות מאנשים שאינך עוקב אחריהם מופיעות כאן.',
  'Çevrimiçi durumumu gizle': 'הסתר את מצב החיבור שלי',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'אחרים לא יראו את מצב החיבור שלך ואת זמן ההופעה האחרון בהודעות',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'מהמשתמשים הראשונים שלנו. המשוב הזה עזר לאפליקציה להיות מה שהיא היום.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'מהמשתמשים הראשונים שלנו. המשוב שלך עזר לאפליקציה להיות מה שהיא היום.',
  'İleri': 'הבא',
  'Önceki': 'הקודם',
  'Sonraki': 'הבא',
  'Seçilen dosya okunamadı': 'לא ניתן לקרוא את הקובץ שנבחר',
  'Video açılamadı': 'לא ניתן לפתוח את הסרטון',
  'En fazla {} medya seçebilirsin': 'אפשר לבחור עד {} פריטים',
  'Hiçbir medya yüklenemedi': 'לא הצלחנו להעלות אף פריט',
  'Seçimi kaldır': 'הסרה מהבחירה',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'בתגובה אחת אפשר להעלות בסך הכול {} MB',
  '{} dosya okunamadı': 'לא ניתן לקרוא {} קבצים',
  '{} medya eklendi, {} yüklenemedi': '{} נוספו, {} נכשלו',
  'Kırp': 'חיתוך',
  'Çiz': 'ציור',
  'Metin': 'טקסט',
  'Emoji': 'אימוג׳י',
  'Yinele': 'בצע שוב',
  'Daha fazla': 'עוד',
  'Hazırlanıyor…': 'מתכונן…',
  'Düzenlemeden çık?': 'לצאת מהעריכה?',
  'Yaptığın değişiklikler kaybolacak.': 'השינויים שלך יאבדו.',
  'Çık': 'יציאה',
  'Serbest çizim': 'ציור חופשי',
  'Ok': 'חץ',
  'Dikdörtgen': 'מלבן',
  'Daire': 'עיגול',
  'Bulanıklaştır': 'טשטוש',
  'Pikselleştir': 'פיקסול',
  'Silgi': 'מחק',
  'Çizgi kalınlığı': 'עובי הקו',
  'Saydamlık': 'שקיפות',
  'Dolgu': 'מילוי',
  'Renk': 'צבע',
  'Döndür': 'סיבוב',
  'Yansıt': 'היפוך',
  'Oran': 'יחס',
  'Sıfırla': 'איפוס',
  'Serbest': 'חופשי',
  'Metin yaz...': 'הקלד טקסט...',
  'Hizala': 'יישור',
  'Arka plan': 'רקע',
  'Emoji ara...': 'חיפוש אימוג׳י...',
  'Son kullanılanlar': 'אחרונים',
  'İfadeler ve insanlar': 'סמיילים ואנשים',
  'Hayvanlar ve doğa': 'חיות וטבע',
  'Yiyecek ve içecek': 'אוכל ושתייה',
  'Etkinlikler': 'פעילויות',
  'Seyahat ve yerler': 'נסיעות ומקומות',
  'Nesneler': 'חפצים',
  'Semboller': 'סמלים',
  'Bayraklar': 'דגלים',
  'Görseli düzenle': 'עריכת התמונה',
  'Düzenlendi': 'נערך',
  'Düzenlenemedi': 'העריכה נכשלה',
  'Düzenlenen görsel çok büyük': 'התמונה שנערכה גדולה מדי',
  'Videoyu düzenle': 'עריכת וידאו',
  'Sesi kapat': 'השתקה',
  'Sesi aç': 'ביטול השתקה',
  'İptal ediliyor…': 'מבטל…',
  'Bu biraz sürebilir': 'זה עשוי לקחת זמן',
  'Video çok büyük': 'הווידאו גדול מדי',
  'Video hazırlanamadı': 'לא ניתן היה להכין את הווידאו',
  'Başlangıç': 'התחלה',
  'Bitiş': 'סיום',
  'En çok {} saniye seçebilirsin': 'אפשר לבחור עד {} שניות',
  'Dosya en fazla {} MB olabilir': 'הקובץ יכול להיות עד {} MB',
  'Medya ekle': 'הוספת מדיה',
  'Seçili medya kalmadı': 'לא נבחרה מדיה',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'בחר תמונה או סרטון להוספה לתגובה שלך.',
  'Medya seç': 'בחירת מדיה',
  'Daha fazla ekle': 'הוספת עוד',
  'Medya seçilemedi': 'לא ניתן היה לבחור מדיה',
  'Favori oyuncular': 'שחקנים מועדפים',
  'Henüz favori oyuncun yok': 'אין עדיין שחקנים מועדפים',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'פתח דף של שחקן והקש על הלב בפינה הימנית העליונה.',
  '{} yapımdan {} tanesini izledin': 'צפית ב-{} מתוך {}',
  'izledin': 'נצפו',
  'İzlemedin': 'לא נצפה',
  'Yapım bulunamadı': 'לא נמצאו כותרים',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'לאדם הזה אין סדרות או סרטים להצגה.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'היסטוריית הצפייה קשורה לחשבון שלך; הרשימה הזו שלך בלבד.',
  'Hesabın kalıcı olarak askıya alındı': 'החשבון שלך הושעה לצמיתות',
  'Hesabın geçici olarak askıya alındı': 'החשבון שלך הושעה זמנית',
  'Hesabın askıya alındı': 'החשבון שלך מושעה',
  'Sebep': 'סיבה',
  'Kalan süre': 'זמן שנותר',
  'Süre dolunca hesabın kendiliğinden açılır': 'בתום התקופה החשבון ייפתח מעצמו',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'בזמן הזה אפשר להמשיך לקרוא, אבל אי אפשר לפרסם, להגיב או לשלוח הודעות.',
  'Anladım': 'הבנתי',
  'Ayrıntı': 'פרטים',
  '{} dakika': '{} דקות',
  'birkaç saniye': 'כמה שניות',
  'Karara itiraz et': 'ערעור על ההחלטה',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'הסבר למה יש לבטל את העונש הזה',
  'İtirazını gönder': 'שליחת הערעור',
  'İtirazın incelemede': 'הערעור שלך בבדיקה',
  'İtirazın reddedildi': 'הערעור שלך נדחה',
  'İtirazın alındı, inceleniyor': 'קיבלנו את הערעור שלך והוא בבדיקה',
  'İtiraz en az 10 karakter olmalı': 'הערעור חייב להיות באורך 10 תווים לפחות',
  'Yükleniyor...': 'טוען...',
  'Bu bölüme puan ver': 'דרגו את הפרק הזה',
  '{} kişi puanladı': '{} אנשים דירגו',
  'Bölüm izlendi olarak işaretlendi': 'הפרק סומן כנצפה',
  'Sesli ara': 'שיחה קולית',
  'Görüntülü ara': 'שיחת וידאו',
  'Çalıyor...': 'מצלצל...',
  'Bağlanıyor...': 'מתחבר...',
  'Cevapla': 'ענה',
  'Reddet': 'דחה',
  'Sessize al': 'השתק',
  'Hoparlör': 'רמקול',
  'Kamerayı kapat': 'כבה מצלמה',
  'Kamerayı çevir': 'החלף מצלמה',
  'Cevap yok': 'אין מענה',
  'Arama reddedildi': 'השיחה נדחתה',
  'Meşgul': 'תפוס',
  'Bağlanılamadı': 'לא ניתן היה להתחבר',
  'Arama iptal edildi': 'השיחה בוטלה',
  'Arama geçmişi': 'היסטוריית שיחות',
  'Gelen arama': 'שיחה נכנסת',
  'Giden arama': 'שיחה יוצאת',
  'Cevapsız arama': 'שיחה שלא נענתה',
  'Arama şu anda kullanılamıyor': 'שיחות אינן זמינות כרגע',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'שיחות וידאו כבויות כרגע, אפשר לבצע שיחה קולית',
  'Bu kullanıcıyı arayamazsın': 'אי אפשר להתקשר למשתמש הזה',
  'Aramak için karşılıklı takipleşmelisiniz':
      'כדי להתקשר עליכם לעקוב זה אחר זה',
  'Bu kullanıcı şu anda aranamıyor': 'לא ניתן להתקשר למשתמש הזה כרגע',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'יותר מדי שיחות שלא נענו. נסה שוב בעוד {}',
  'Zaten bir aramadasın': 'אתה כבר בשיחה',
  'Arama için mikrofon izni gerekiyor': 'נדרשת הרשאת מיקרופון כדי להתקשר',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'לשיחת וידאו נדרשות הרשאות מצלמה ומיקרופון',
  'Arama başlatılamadı': 'לא ניתן היה להתחיל את השיחה',
  'Kullanıcı bulunamadı': 'המשתמש לא נמצא',
  'Kendini arayamazsın': 'אי אפשר להתקשר לעצמך',
  'Arama artık geçerli değil': 'השיחה הזו כבר אינה תקפה',
  'Bu aramanın tarafı değilsin': 'אינך צד בשיחה הזו',
  'Arama bulunamadı': 'השיחה לא נמצאה',
  'Çok fazla istek, biraz bekle': 'יותר מדי בקשות, המתן רגע',
  'Bağlantı koptu': 'החיבור נותק',
  'Arama süre sınırına ulaştı': 'השיחה הגיעה למגבלת הזמן',
  'Arama en fazla 4 saat sürebilir': 'שיחה יכולה להימשך עד 4 שעות',
  'Arama sona erdi': 'השיחה הסתיימה',
  'Sesli arama': 'שיחה קולית',
  'Görüntülü arama': 'שיחת וידאו',
  'Gelen aramalar': 'שיחות נכנסות',
  'Sesli ve görüntülü arama bildirimleri':
      'התראות על שיחות קוליות ושיחות וידאו',
  '{} sa': '{} שע',
  'Sesli ve Görüntülü Aramalar': 'שיחות קוליות ושיחות וידאו',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'תוכן השיחות לעולם אינו מוקלט. האודיו והווידאו זורמים מוצפנים מקצה לקצה (DTLS-SRTP) בין המכשירים; השרתים שלנו אינם יכולים לפענח, להאזין או לאחסן את התעבורה הזו.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'נשמרים רק נתוני העל של השיחה: עם מי, באיזה כיוון, מתי וכמה זמן. רשומות אלה נמחקות אוטומטית לאחר 90 יום.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'אם לא ניתן ליצור חיבור ישיר, האודיו והווידאו עוברים מוצפנים דרך שרת ממסר (TURN). גם הוא אינו יכול לפענח או להקליט את התוכן.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'המיקרופון פועל רק במהלך שיחה קולית או שיחת וידאו, והמצלמה רק במהלך שיחת וידאו. שניהם נכבים בתום השיחה.',
  'Takip ettiğin {} kişi izledi': '{} אנשים במעקב שלך צפו בזה',
  'Yorum yaz...': 'כתוב תגובה...',
  'Sıradaki bölüm': 'הפרק הבא',
  'Doğrulanmış testçi': 'בודק מאומת',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'התראות על מעקב, לייקים, תגובות, הודעות ותיוגים',
  'Sen': 'אני',
  'Aradığınız kişide sesli arama devre dışı':
      'שיחות קוליות מושבתות אצל האדם הזה',
  'Aradığınız kişide görüntülü arama devre dışı':
      'שיחות וידאו מושבתות אצל האדם הזה',
  'Sesli aramalara izin ver': 'אפשר שיחות קוליות',
  'Görüntülü aramalara izin ver': 'אפשר שיחות וידאו',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'כשכבוי, אף אחד לא יכול להתקשר אליך בקול; המתקשר רואה הודעה',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'כשכבוי, אף אחד לא יכול להתקשר אליך בווידאו; המתקשר רואה הודעה',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'שיחות קוליות כבויות. אפשר להפעיל אותן בהגדרות > פרטיות.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'שיחות וידאו כבויות. אפשר להפעיל אותן בהגדרות > פרטיות.',
  'Sesli ve görüntülü arama': 'שיחות קוליות ווידאו',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'חשבונות אורח לא יכולים להתקשר. צור חשבון כדי להשתמש בזה.',
  'Misafir hesaplar aranamaz': 'אי אפשר להתקשר לחשבונות אורח',
  'Puan dağılımı': 'התפלגות הדירוגים',
  '{} yıldız': '{} כוכבים',
  'Yakında gelecek': 'בקרוב',
  '{} {} yayınlandı': '{} {} שוחרר',
  'Yeni bölüm yayınlandı': 'פרק חדש שוחרר',
  'Yeni bölümler': 'פרקים חדשים',
  'Geri': 'חזרה',
  'Karşılamayı kapat': 'סגירת ההיכרות',
  'Adım {} / {}': 'שלב {} / {}',
  'Hadi başlayalım': 'מתחילים',
  'Kaydet ve devam': 'שמירה והמשך',
  '{} tanesini ekle': 'הוספה של {}',
  'Şimdilik geç': 'לא עכשיו',
  'Doğum tarihin ne zaman?': 'מה תאריך הלידה שלך?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'שואלים כדי להציג תוכן שמתאים לגיל שלך וכדי לחגוג את יום ההולדת.',
  'Gün': 'יום',
  'Ay': 'חודש',
  'Yıl': 'שנה',
  'Doğum yılımı paylaşmak istemiyorum': 'אני לא רוצה לשתף את שנת הלידה שלי',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'תאריך הלידה אינו מוצג לכולם בפרופיל שלך. הוא משמש רק לתוכן שמתאים לגיל ולברכת יום הולדת.',
  'Ocak': 'ינואר',
  'Şubat': 'פברואר',
  'Mart': 'מרץ',
  'Nisan': 'אפריל',
  'Mayıs': 'מאי',
  'Haziran': 'יוני',
  'Temmuz': 'יולי',
  'Ağustos': 'אוגוסט',
  'Eylül': 'ספטמבר',
  'Ekim': 'אוקטובר',
  'Kasım': 'נובמבר',
  'Aralık': 'דצמבר',
  'Verilerini yanında getir': 'הנתונים שלך באים איתך',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'אם המעקב אחרי הצפיות שלך מתנהל באפליקציה אחרת, אפשר להעביר אותו לכאן. אין צורך להתחיל מאפס.',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'בחירת קובץ ה-ZIP שיוצא משם; הצפיות, הדירוגים והרשימות שלך יועברו.',
  'Aktarılıyor...': 'בהעברה...',
  'ZIP dosyası seç': 'בחירת קובץ ZIP',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'אין למה למהר: אפשר לעשות את זה גם אחר כך בהגדרות > הנתונים שלי.',
  'Hangi filmleri izledin?': 'באילו סרטים כבר יצא לצפות?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'הכי נצפים נמצאים כאן. כל מה שנבחר נוסף לצפיות שלך.',
  'SERİ FİLMLER': 'סדרות סרטים',
  'Serilerden {} film eklendi': 'מסדרות הסרטים נוספו {} סרטים',
  'Film listesi yüklenemedi': 'לא ניתן לטעון את רשימת הסרטים',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'אפשר לדלג על השלב הזה ולהוסיף אחר כך מה שרוצים.',
  '{} film izlediklerine eklendi': '{} סרטים נוספו לצפיות שלך',
  'Film serileri': 'סדרות סרטים',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'סדרה שנצפתה מתחילתה ועד סופה נוספת בנגיעה אחת.',
  'Seri bulunamadı': 'לא נמצאו סדרות',
  'Daha sonra tekrar deneyebilirsin.': 'אפשר לנסות שוב מאוחר יותר.',
  '{} film': '{} סרטים',
  'Eklendi': 'נוסף',
  'Tümünü izledim': 'צפיתי בכולם',
  'Peki ya diziler?': 'ומה עם הסדרות?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'סימון מה שנצפה; ככל שנבחר יותר, נביא המלצות דומות.',
  'Dizi listesi yüklenemedi': 'לא ניתן לטעון את רשימת הסדרות',
  'Seçtiklerine benzeyenler': 'דומים לבחירות שלך',
  'Her şey hazır': 'הכול מוכן',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'הצצה מהירה למה שאפשר לעשות ב-dizi.jpg.',
  'Profilini tamamla': 'השלמת הפרופיל',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'אפשר להוסיף ביו, תמונת פרופיל ותמונת נושא מההגדרות.',
  'Takvimin seni bekliyor': 'לוח השנה מחכה לך',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'פרקים חדשים של הסדרות שלך נכנסים ללוח השנה, ואנחנו מודיעים בהתראה.',
  'Puan ver, yorum yaz': 'דירוג וכתיבת תגובות',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'דירוג פרק אחרי פרק, תגובות מאחורי מסך ספוילר, ויצירת רשימות.',
  'Verilerin sende kalır': 'הנתונים נשארים שלך',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'הנתונים שלך מקושרים לחשבון שלך בלבד ואינם נמכרים. אפשר להוריד את כולם מההגדרות או למחוק את החשבון לגמרי.',
  'Engellenen kullanıcılar': 'משתמשים חסומים',
  'Engellediğin kişileri gör, engeli kaldır':
      'צפייה ברשימת החסומים וביטול חסימה',
  'Engellediğin kimse yok': 'אין אף אחד חסום',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'אפשר לחסום משתמש מתפריט שלוש הנקודות שבפרופיל.',
  '@{} engellensin mi?': 'לחסום את @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'הפוסטים, התגובות והפרופילים לא יהיו גלויים אחד לשני; גם הודעות ושיחות לא יעברו. אם קיים ביניכם מעקב, הוא ינותק ולא יחזור גם אחרי ביטול החסימה.',
  'Bu kullanıcıyı engelledin': 'המשתמש הזה חסום על ידך',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'הפוסטים, התגובות וההודעות של האדם הזה לא מוצגים לך, וגם שלך לא מוצגים לאדם הזה.',
  '{} yeni bir yapımda: {}': '{} ביצירה חדשה: {}',
  'Favori kişinden yeni yapım': 'יצירה חדשה של אדם מועדף',
  '{} için bildirimler': 'התראות עבור {}',
  'Tüm bildirimler': 'כל ההתראות',
  'Uygulamada ve telefonda': 'באפליקציה ובטלפון',
  'Yalnız uygulama içi': 'באפליקציה בלבד',
  'Telefon bildirimi gönderilmez': 'לא נשלחת התראה לטלפון',
  'Kapalı': 'כבוי',
  'Bu kişi için bildirim yok': 'אין התראות לאדם הזה',
  'Favori kişilerin yeni yapımları': 'יצירות חדשות של אנשים מועדפים',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'כשכבוי, אף אחד לא יכול להתקשר אליך בקול; המתקשר רואה הודעה שהשיחות "מושבתות"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'כשכבוי, אף אחד לא יכול להתקשר אליך בווידאו; המתקשר רואה הודעה שהשיחות "מושבתות"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'הפעילות שלי',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'הלייקים, התגובות והצפיות שלך במקום אחד',
  'Henüz hareketin yok': 'אין עדיין פעילות',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'כל מה שאהבת, הגבת עליו וצפית בו נאסף כאן.',
  'Bu süzgeçte hareket yok': 'אין פעילות בסינון הזה',
  'Başka bir tür seç ya da "Hepsi"ne dön.': 'בחר סוג אחר או חזור אל «הכול».',
  'Hepsi': 'הכול',
  'Puan': 'דירוג',
  'Tepki': 'ריאקציה',
  'İzleme': 'צפייה',
  'Durum': 'סטטוס',
  'Liste': 'רשימה',
  'Yorum yaptın': 'נוספה תגובה',
  'Yorumu beğendin': 'לייק לתגובה',
  '{} puan verdin': 'דירוג {}',
  'Tepki verdin': 'ריאקציה',
  'Listene ekledin': 'נוסף לרשימה',
  'Takip etmeye başladın': 'התחלת מעקב',
  '"İzleyeceğim" işaretledin': 'סומן כ«אצפה»',
  '"İzliyorum" işaretledin': 'סומן כ«צופה»',
  '"Bitirdim" işaretledin': 'סומן כ«סיימתי»',
  '"Bıraktım" işaretledin': 'סומן כ«נטשתי»',
  'Silinmiş içerik': 'תוכן שנמחק',
  'şimdi': 'עכשיו',
  '{} g': "{} ימ'",
  '{} y': "{} שנ'",
  'İstatistiklerim': 'הסטטיסטיקה שלי',
  'Gönderilerinin görüntülenmesi ve beğenisi': 'צפיות ולייקים בפוסטים שלך',
  'Henüz gönderin yok': 'אין לך עדיין פוסטים',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'ברגע שתכתוב תגובה על סדרה או סרט, מספרי הצפיות והלייקים שלך יתחילו להצטבר כאן.',
  'Tüm zamanlar': 'מכל הזמנים',
  'Son {} gün': '{} הימים האחרונים',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'היסטוריית הצפיות עדיין לא התחילה להצטבר; נתוני היום הראשון יופיעו מחר.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'היסטוריית הצפיות מצטברת מאז {} (יש נתונים של {} ימים), ולכן המספר ל-{} ימים עדיין חלקי.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'היסטוריית הלייקים נרשמת מאז {}.',
  'Bu dönemde gösterilecek gönderi yok.': 'אין פוסטים להצגה בתקופה הזו.',
  'eksik veri': 'נתונים חלקיים',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'הסדרות והסרטים שצפית בהם, מוני הצפייה, זמן המסך וכרטיס ההתאמה לא יוצגו לאחרים בפרופיל שלך',
  'Takipçi listemi gizle': 'הסתר את רשימת העוקבים שלי',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'אחרים לא יכולים לראות מי עוקב אחריך; מספר העוקבים שלך נשאר גלוי',
  'Takip ettiklerimi gizle': 'להסתיר את מי שאני עוקב אחריו',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'אחרים לא יכולים לראות אחרי מי אתם עוקבים; מספר הנעקבים שלך נשאר גלוי',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'רשימת העוקבים של המשתמש הזה מוסתרת.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'רשימת הנעקבים של המשתמש הזה מוסתרת.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'סטטיסטיקת הפוסט',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'אפשר לראות סטטיסטיקה רק של הפוסטים שלך.',
  'Erişim': 'טווח הגעה',
  'Görüntüleyen': 'צופים',
  'Kaç farklı kişi gördü (son {} gün)':
      'כמה אנשים שונים ראו (‏{} הימים האחרונים)',
  'Paylaşım': 'שיתופים',
  'Bu gönderiden sonra': 'אחרי הפוסט הזה',
  'Profil ziyareti': 'ביקורים בפרופיל',
  'Yeni takip': 'עוקבים חדשים',
  'İçeriğe tıklama': 'הקשות על התוכן',
  'Spoiler perdesini açan': 'חשפו את הספוילר',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'שיתופים, ביקורים בפרופיל, עוקבים, הקשות על התוכן, פילוח מקורות ומדידות ספוילר נאספים מאז {}; מה שקדם לכך לא נמדד.',
  'Zamana yayılmış görüntülenme': 'צפיות לאורך זמן',
  'Görüntülenme nereden geldi': 'מאיפה הגיעו הצפיות',
  'Kimler gördü': 'מי ראה',
  'Günlük veri henüz birikmeye başlamadı.':
      'הנתונים היומיים עדיין לא התחילו להצטבר.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'לתרשים דרושים נתונים של יומיים לפחות. הנתונים נאספים מאז {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'רוב הצפיות הגיעו ביום ה-{} אחרי הפרסום: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'הצפיות היומיות נאספות מאז {}; מה שקדם לכך לא נמדד.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'פילוח המקורות רק התחיל להימדד; הפוסט הזה עדיין לא קיבל צפייה מתויגת.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'פילוח העוקבים/הגילוי רק התחיל להימדד; אין עדיין נתונים.',
  'Takip edenler': 'עוקבים',
  'Keşiften gelenler': 'מהגילוי',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'עמוד סדרה/סרט',
  'Paylaşılan bağlantı': 'קישור ששותף',
  'yeni ölçülüyor': 'נמדד לאחרונה',
  'Kendi ortalamanla aynı düzeyde': 'ברמת הממוצע שלך',
  'Kendi ortalamanın %{} üstünde': '{}% מעל הממוצע שלך',
  'Kendi ortalamanın %{} altında': '{}% מתחת לממוצע שלך',
  'Etkileşim oranı': 'שיעור מעורבות',
  '(beğeni + yorum) ÷ görüntülenme': '(לייקים + תגובות) ÷ צפיות',
  'Toplam görüntülenme': 'סך הצפיות',
  '{} ile {} arasında toplam {} görüntülenme': 'בין {} ל-{}: {} צפיות בסך הכול',
  'İstatistikleri gör': 'הצג סטטיסטיקה',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'עבור הסטטיסטיקה שמוצגת לבעלי הפוסט נשמרים כמונים מצטברים: כמה פעמים ומאיזה משטח (פיד, פרופיל, פיד במסך מלא, עמוד סדרה/סרט, קישור ששותף) הפוסט נצפה, האם הצופה עקב באותו רגע אחרי בעלי הפוסט, מעבר מהפוסט לפרופיל או לתוכן, מעקבים שנוצרו דרך הפוסט, שיתופים ופתיחת מסך הספוילר. במונים האלה אין מזהה משתמש, כתובת IP או חותמת זמן; לא ניתן לברר מי עשה מה.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'כדי לאפשר לספור כמה אנשים שונים ראו פוסט, נשמר לכל צופה תקציר עם מפתח בלתי הפיך (קיצור קריפטוגרפי הנגזר ממזהה המשתמש או מכתובת ה-IP) למשך 90 יום. לבעלי הפוסט מוצג רק המספר; זהות הצופים אינה משותפת בשום מצב.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'להעביר ל"אצפה"?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'כותר הוא או לצפייה או שכבר נצפה. המשך הפעולה ימחק את סימוני הצפייה שלך בסדרה הזו ({}).',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'כותר הוא או לצפייה או שכבר נצפה. המשך הפעולה יסיר את סימון "צפיתי" שלך בסרט הזה.',
  'Sil ve taşı': 'מחק והעבר',
  'Yapım Ekibi': 'צוות ההפקה',
  'Yaratıcı': 'יצירה',
  'Yönetmen': 'בימוי',
  'Senaryo': 'תסריט',
  'Yapımcı': 'הפקה',
  'Yapım Firmaları': 'חברות הפקה',
  'Yapım Firması': 'חברת הפקה',
  'Firma bulunamadı': 'החברה לא נמצאה',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'לחברה הזו אין כותרים מסוג זה.',
  'Doğum günün kutlu olsun!': 'יום הולדת שמח!',
  'İyi ki doğdun, iyi ki buradasın.': 'טוב שנולדת, טוב שהגעת אלינו.',
  'Bugün {} yaşına girdin': 'היום מלאו לך {} שנים',
  'Teşekkürler': 'תודה',
  'İki Adımlı Doğrulama': 'אימות דו-שלבי',
  'Girişte e-postana kod gönderilir': 'בהתחברות נשלח קוד לאימייל שלך',
  'Kod {} adresine gönderildi': 'הקוד נשלח אל {}',
  '6 haneli kod': 'קוד בן 6 ספרות',
  'Doğrula': 'אימות',
  'Yeniden gönder': 'שליחה מחדש',
  'Vazgeç': 'ביטול',
  'Yeni kod gönderildi': 'קוד חדש נשלח',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'בהתחברות עם Google לא מתבקש קוד; Google מבצעת אימות משלה.',
  'Kapatmak için de kod gerekir.': 'גם הכיבוי דורש קוד.',
  'E-postana erişemezsen hesabına giremezsin.':
      'אובדן הגישה לאימייל פירושו אובדן הגישה לחשבון.',
  'İki adımlı doğrulama açıldı': 'האימות הדו-שלבי הופעל',
  'İki adımlı doğrulama kapatıldı': 'האימות הדו-שלבי כובה',

  // --- md.24 video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': 'כמה מהסרטון נצפה',
  'Videoyu başlatanlar': 'התחילו את הסרטון',
  'videonun %{} noktasına ulaştı': 'הגיעו ל-{}% מהסרטון',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'מחצית מהצופים ראו לפחות {}% מהסרטון.',
  'Sonuna kadar izleyen: %{}': 'צפו עד הסוף: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'לעקומה דרושות לפחות {} צפיות; כרגע יש {} צפיות.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'העקומה מבוססת על {} צפיות ואינה מושפעת מטווח התאריכים שנבחר.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'זמן הצפייה נמדד מאז {}; צפיות ישנות יותר אינן נכללות במספר הזה.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} צפיות. {}% הגיעו לאמצע הסרטון ו-{}% הגיעו לסוף.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'רמה {}',
  'Sonraki seviyeye {} puan kaldı': 'נותרו {} נקודות לרמה הבאה',
  'Gönderilerin': 'הפוסטים שלך',
  '{} gönderi': '{} פוסטים',
  '{} gönderi · {} görüntülenme': '{} פוסטים · {} צפיות',
  'önceki {} güne göre': 'לעומת {} הימים הקודמים',
  'önceki {} güne göre %{} arttı': 'לעומת {} הימים הקודמים: עלייה של {}%',
  'önceki {} güne göre %{} azaldı': 'לעומת {} הימים הקודמים: ירידה של {}%',
  'önceki {} güne göre değişmedi': 'ללא שינוי לעומת {} הימים הקודמים',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'צפיות יומיות: הנמוך ביותר {}, הגבוה ביותר {}',
  'Etkileşim oranı henüz ölçülemedi': 'שיעור המעורבות עדיין לא ניתן למדידה',
  'Oranlar': 'שיעורים',
  'Beğenme oranı': 'שיעור לייקים',
  'Yorum oranı': 'שיעור תגובות',
  'Paylaşma oranı': 'שיעור שיתופים',
  'İçeriğe gitme oranı': 'שיעור הקשות על התוכן',
  'Profile gitme oranı': 'שיעור ביקורים בפרופיל',
  'Ziyaretten takibe dönüşüm': 'מביקור למעקב',
  'beğeni ÷ görüntülenme': 'לייקים ÷ צפיות',
  'yorum ÷ görüntülenme': 'תגובות ÷ צפיות',
  'paylaşım ÷ görüntülenme': 'שיתופים ÷ צפיות',
  'içeriğe tıklama ÷ görüntülenme': 'הקשות על התוכן ÷ צפיות',
  'profil ziyareti ÷ görüntülenme': 'ביקורים בפרופיל ÷ צפיות',
  'yeni takip ÷ profil ziyareti': 'עוקבים חדשים ÷ ביקורים בפרופיל',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'לשיעורים דרושות לפחות {} צפיות; כרגע יש {}.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'השיעורים מבוססים על נתוני הפוסט מכל הזמנים; בחירת הימים שלמטה לא משנה אותם.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'המספרים האלה הם הסך הכול של הפוסט מכל הזמנים (חוץ מתיבות עם הערה משלהן); בחירת הימים שלמטה משנה רק את הגרף.',
  'Ortalama izlenme: videonun %{} kadarı': 'צפייה ממוצעת: {}% מהסרטון',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'הממוצע של 20 המקטעים בעקומת ההחזקה.',
  'Dizi, film, kişi veya şirket ara...': 'חפש סדרה, סרט, אדם או חברה...',
  'Şirketler': 'חברות',
  'Senarist': 'תסריטאי',
  'Bölüm puanları': 'דירוגי פרקים',
  'S{}': 'ע{}',
  'E{}': 'פ{}',
  'Bölüm puanları yüklenemedi': 'לא ניתן לטעון את דירוגי הפרקים',
  'Giriş gerekli': 'נדרשת התחברות',
  'Geçersiz oturum': 'הפעלה לא תקפה',
  'Oturum sonlandı, tekrar giriş yap': 'ההפעלה הסתיימה, התחבר שוב',
  'Çok fazla istek; biraz sonra tekrar dene':
      'יותר מדי בקשות; נסה שוב בעוד מעט',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'אין כרגע מקום בשרת, נסה שוב בעוד רגע',
  'Devam eden yapımlar ({})': 'הפקות פעילות ({})',
  'Diziler ({})': 'סדרות ({})',
  'Filmler ({})': 'סרטים ({})',
  'Tüm yapımlar': 'כל ההפקות',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'אחסון המדיה שלך מלא; מחק העלאות ישנות כדי לפנות מקום',
  'E-posta/kullanıcı adı veya şifre hatalı': 'אימייל/שם משתמש או סיסמה שגויים',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'האימייל או שם המשתמש הזה כבר תפוס',
  'Google doğrulaması başarısız': 'אימות Google נכשל',
  'Kod geçersiz veya süresi dolmuş': 'הקוד לא תקף או שפג תוקפו',
  'Bu kullanıcıyla mesajlaşamazsın': 'אי אפשר לשלוח הודעה למשתמש הזה',
  'Kendini takip edemezsin': 'אי אפשר לעקוב אחרי עצמך',
  'Bu kullanıcıyı takip edemezsin': 'אי אפשר לעקוב אחרי המשתמש הזה',
  'Kendini engelleyemezsin': 'אי אפשר לחסום את עצמך',
  'Yorum 1-1000 karakter olmalı': 'התגובה צריכה להיות 1–1000 תווים',
  'Boş mesaj gönderilemez': 'אי אפשר לשלוח הודעה ריקה',
  'Yorum bulunamadı': 'התגובה לא נמצאה',
  'Şifre hatalı': 'סיסמה שגויה',
  'Şifre en az 6 karakter olmalı': 'הסיסמה חייבת להיות לפחות 6 תווים',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'אפשר להעלות רק GIF, PNG, JPEG או WebP',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'סוגים נתמכים: GIF, PNG, JPEG, WebP, MP4, WebM, שמע',
  'Geçerli bir ZIP dosyası değil': 'זה לא קובץ ZIP תקין',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'כדי לקבל את הנתונים במייל, קשר קודם כתובת',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'יש לך סימוני צפייה. כדי לשים "אשמור לצפייה" צריך למחוק אותם קודם.',
  'Arama şu anda kapalı': 'השיחות כבויות כרגע',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'חשבון אורח לא יכול להפעיל שיחות; צור חשבון',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'השרת מופעל מחדש, נסה שוב בעוד רגע',
  'Puan 1-10 arası olmalı': 'הציון חייב להיות בין 1 ל-10',
  'En fazla 10 medya eklenebilir': 'אפשר להוסיף לכל היותר 10 קבצים',
  'Bu cihazdan yeni hesap açılamıyor': 'אי אפשר ליצור חשבון מהמכשיר הזה',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'נדרשים אימייל תקין, שם משתמש וסיסמה של לפחות 6 תווים',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'נדרשים אימייל תקין וסיסמה של לפחות 6 תווים',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'שם משתמש 3–20 תווים; אותיות קטנות, ספרות, נקודות, מקפים וקווים תחתונים (לא בקצוות)',
  'Bu hesap zaten bağlı': 'החשבון הזה כבר מקושר',
  'Hesap oluşturulamadı': 'לא ניתן ליצור את החשבון',
  'Misafir hesabı oluşturulamadı': 'לא ניתן ליצור חשבון אורח',
  'Hesap bulunamadı': 'החשבון לא נמצא',
  'Bu hesapta e-posta yok': 'לחשבון הזה אין אימייל',
  'İki adımlı doğrulama zaten bu durumda': 'האימות הדו-שלבי כבר במצב הזה',
  'Kod yanlış': 'קוד שגוי',
  'Kodun süresi doldu': 'הקוד פג',
  'Kullanıcının e-postası yok (misafir hesap)':
      'למשתמש הזה אין אימייל (חשבון אורח)',
  'Bio en fazla 300 karakter olabilir': 'הביו יכול להיות לכל היותר 300 תווים',
  'Geçersiz ülke': 'מדינה לא תקפה',
  'Geçersiz sosyal bağlantı': 'קישור חברתי לא תקף',
  'Geçersiz doğum tarihi': 'תאריך לידה לא תקף',
  'Liste adı gerekli': 'נדרש שם לרשימה',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'השם יכול להיות 60 תווים, התיאור 300',
  'Liste bulunamadı': 'הרשימה לא נמצאה',
  'Değiştirilecek tercih yok': 'אין מה לעדכן',
  'İnceleme en fazla 2000 karakter olabilir':
      'הביקורת יכולה להיות לכל היותר 2000 תווים',
  'Önce içeriği "bitirdim" olarak işaretle': 'סמן קודם שהשלמת',
  'Önce kişiyi favorile': 'הוסף קודם את האדם למועדפים',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'לתגובה על פרק נדרשים גם עונה וגם פרק',
  'Yanıtlanan yorum bulunamadı': 'התגובה שעליה אתה מגיב לא נמצאה',
  'Geri bildirim 3-2000 karakter olmalı': 'המשוב חייב להיות 3–2000 תווים',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'נדרשים כותרת וטקסט (לפחות 2 תווים)',
  'Kendine mesaj gönderemezsin': 'אי אפשר לשלוח הודעה לעצמך',
  'Mesaj en fazla 2000 karakter olabilir':
      'ההודעה יכולה להיות לכל היותר 2000 תווים',
  'Mesaj 1-2000 karakter olmalı': 'ההודעה חייבת להיות 1–2000 תווים',
  'Mesaj bulunamadı': 'ההודעה לא נמצאה',
  'Mesaj bulunamadı veya düzenlenemez':
      'ההודעה לא נמצאה או שאי אפשר לערוך אותה',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'אפשר לדווח רק על הודעה שנשלחה אליך',
  'Sebep gerekli': 'נדרשת סיבה',
  'İtiraz edilecek aktif bir ceza yok': 'אין עונש פעיל לערער עליו',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'כבר יש לך ערעור שממתין לבדיקה',
  'Bu ceza için itirazın zaten incelendi': 'הערעור על העונש הזה כבר נבדק',
  'Medya bağlantısının süresi dolmuş': 'קישור המדיה פג',
  'Bu medya için imzalı bağlantı gerekli': 'נדרש קישור חתום למדיה הזאת',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'שירות השיחות מופעל מחדש; נסה שוב עוד מעט',
  'Puan göstergesi': 'מקרא דירוגים',
  'İzleme İstatistiklerim': 'סטטיסטיקת הצפייה שלי',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'ברגע שתסמן פרק או סרט כנצפים, הסטטיסטיקה שלך תתחיל להצטבר כאן.',
  '{} sa {} dk': '{} שע׳ {} דק׳',
  'Yaklaşık ekran süresi': 'זמן מסך משוער',
  'İzleme serisi': 'רצף צפייה',
  'Şu anki seri': 'הרצף הנוכחי',
  'En uzun seri': 'הרצף הארוך ביותר',
  'Haftanın günleri': 'ימות השבוע',
  'En çok izlediklerin': 'הנצפים ביותר',
  'Bu dönemde izleme yok': 'אין צפייה בתקופה הזו',
  'Paz': 'א׳',
  'Pzt': 'ב׳',
  'Sal': 'ג׳',
  'Çar': 'ד׳',
  'Per': 'ה׳',
  'Cum': 'ו׳',
  'Cmt': 'ש׳',
  '{} bölüm': '{} פרקים',
  '{} bölüm~tekil': '{} פרק',
  '{} kez': '{} פעמים',
  '{} kez~tekil': '{} פעם',
  'Son {} gün · günlük': '{} הימים האחרונים · יומי',
  'Son {} gün · haftalık': '{} הימים האחרונים · שבועי',
  'Ekran süren, serin ve en çok izlediklerin':
      'זמן המסך, הרצף והנצפים ביותר שלך',
  'Daralt': 'כווץ',
  'Listeyi düzenle': 'עריכת רשימה',
  'Bitti': 'סיום',
  'Sırala': 'שינוי סדר',
  'Herkese göster': 'הצג לכולם',
  'Başkalarından gizle': 'הסתר מאחרים',
  'Listeden kaldır': 'הסר מהרשימה',
  'Listeden kaldırılsın mı?': 'להסיר מהרשימה?',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'הכותר יוסר מהרשימה. אם ברצונך רק להסתיר אותו, השתמש בסמל העין.',
  'Sıralama kaydedilemedi': 'לא ניתן היה לשמור את הסדר',
  'Değişiklik kaydedilemedi': 'לא ניתן היה לשמור את השינוי',
  'Kaldırılamadı': 'לא ניתן היה להסיר',
  'Popülerlik': 'פופולריות',
  'TMDB puanı': 'דירוג TMDB',
  'Yapım yılı': 'שנת הפקה',
  'dizi.jpg puanı': 'דירוג dizi.jpg',
  'İzlenme': 'צפיות',
  'Yorum sayısı': 'מספר תגובות',
  'Tüm raflara uygulanır': 'חל על כל המדפים',
  'En popüler {} yapım arasında sıralandı':
      'מוין מבין {} הכותרים הפופולריים ביותר',
  'Altyazı görünümü': 'מראה הכתוביות',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık': 'צבע, גופן, גודל, קצה ואטימות',
  'Bu bir örnek altyazıdır.': 'זו כתובית לדוגמה.',
  'Ayar değiştikçe önizleme anında güncellenir.':
      'התצוגה המקדימה מתעדכנת מיד עם כל שינוי.',
  'Yazı biçimi': 'סגנון הטקסט',
  'Yazı rengi': 'צבע הטקסט',
  'Yazı opaklığı': 'אטימות הטקסט',
  'Yazı tipi': 'גופן',
  'Yazı boyutu': 'גודל הטקסט',
  'Karakter ayrıtı': 'קצה התווים',
  'Ayrıt türü': 'סוג הקצה',
  'Ayrıt rengi': 'צבע הקצה',
  'Yok': 'ללא',
  'Dış çizgi': 'מתאר',
  'Gölge': 'צל',
  'Kabartma': 'בולט',
  'Oyma': 'שקוע',
  'Arka plan rengi': 'צבע הרקע',
  'Arka plan opaklığı': 'אטימות הרקע',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      'הרקע הוא המילוי ממש מאחורי הטקסט; החלון הוא המשטח הרחב יותר מאחורי כל בלוק הכתוביות.',
  'Pencere': 'חלון',
  'Pencere rengi': 'צבע החלון',
  'Pencere opaklığı': 'אטימות החלון',
  'Altyazı görünümü sıfırlansın mı?': 'לאפס את מראה הכתוביות?',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      'הגדרות הצבע, הגופן, הגודל, הקצה והאטימות יחזרו לברירת המחדל.',
  'Altyazı görünümü varsayılana döndü': 'מראה הכתוביות אופס לברירת המחדל',
  '{} indiriliyor…': 'מוריד את {}…',
  'Seçince indirilir': 'יורד בעת הבחירה',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      'לא ניתן היה להוריד את הגופן. מוצג בגופן ברירת המחדל.',
  'Beyaz': 'לבן',
  'Siyah': 'שחור',
  'Kırmızı': 'אדום',
  'Yeşil': 'ירוק',
  'Mavi': 'כחול',
  'Sarı': 'צהוב',
  'Camgöbeği': 'טורקיז',
  'Macenta': 'מג\'נטה',
  'Yapım bütçesi': 'תקציב הפקה',
  'Yapım bütçesi ve dünya çapında hasılat': 'תקציב הפקה והכנסות עולמיות',
  'Dizinin yayın durumu': 'סטטוס השידור של הסדרה',
  'Devam ediyor': 'בשידור',
  'Sona erdi': 'הסתיימה',
  'İptal edildi': 'בוטלה',
  'Yapımda': 'בהפקה',
  'Planlandı': 'מתוכננת',
  'Pilot bölüm': 'פרק פיילוט',
  'Ad': 'שם',
  'Adın': 'השם שלך',
  'Kullanıcı adı': 'שם משתמש',
  'Kullanıcı adını değiştir': 'שינוי שם משתמש',
  'Kullanıcı adını 90 günde bir değiştirebilirsin':
      'אפשר לשנות שם משתמש פעם ב-90 יום',
  'Değiştir': 'שינוי',
  '{} gün sonra değiştirebilirsin': 'אפשר יהיה לשנות בעוד {} ימים',
  'Kullanıcı adın: @{}': 'שם המשתמש שלך: @{}',
  'Bu kullanıcı adı zaten alınmış': 'שם המשתמש הזה כבר תפוס',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış':
      'שם המשתמש הזה שמור כרגע לחשבון אחר',
  'Bu zaten senin kullanıcı adın': 'זה כבר שם המשתמש שלך',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      'שם משתמש 3–20 תווים; אותיות קטנות, ספרות, נקודות, מקפים וקווים תחתונים',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      'מופיע בפרופיל מעל שם המשתמש שלך. אפשר להשאיר ריק.',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      'אחרי השינוי לא תוכל לשנות שוב במשך 90 יום. שם המשתמש הישן יישמר עבורך 90 יום — אפשר לחזור אליו, ואף אחד אחר לא יוכל לקחת אותו בזמן הזה. קישורים לשם הישן כבר לא יפתחו את הפרופיל שלך.',
  'Etkinliğim': 'פעילות',
  'Tercihler': 'העדפות',
  'Gizlilik ve güvenlik': 'פרטיות ואבטחה',
  'Destek': 'תמיכה',
  'Hesap': 'חשבון',
  '{} dizileri': 'סדרות של {}',
  '{} filmleri': 'סרטים של {}',
  'En üste taşı': 'העבר לראש הרשימה',
  'Sırayı sıfırla': 'איפוס הסדר',
  'Listede ara': 'חיפוש ברשימה',
  'Elle sıra sıfırlansın mı?': 'לאפס את הסדר הידני?',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      'הרשימה תחזור לסדר ברירת המחדל (מה שסימנת לאחרונה יופיע ראשון).',
  'Sıra sıfırlanamadı': 'לא ניתן היה לאפס את הסדר',
  'Listenin en üstüne taşındı': 'הועבר לראש הרשימה',
  'Adlar yükleniyor…': 'טוען שמות…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      'לחץ ארוכות על הפוסטר כדי לגרור אותו. כדי להקדים כותר רחוק, השתמש ב“העבר לראש הרשימה”.',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      'הגרירה מושבתת בחיפוש; הקדם באמצעות “העבר לראש הרשימה” ({} תוצאות).',
  'Görünüm': 'תצוגה',
  'En çok izlediğin filmler': 'הסרטים שצפית בהם הכי הרבה',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      'הזמנים הם הערכה: פרק נחשב ~{} דק\', סרט ~{} דק\'',
  'Bu kullanıcı adı sistem tarafından ayrılmış':
      'שם המשתמש הזה שמור על ידי המערכת',
  'Ekran süresi': 'זמן מסך',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir":
      'הזמנים הם משכי הפרקים והסרטים האמיתיים מ-TMDB',
  'Tüm zamanlar: {} bölüm · {} film · {}':
      'מאז ומעולם: {} פרקים · {} סרטים · {}',
  'Kabul et': 'אישור',
  'Reddedilenler': 'בקשות שנדחו',
  'İstekler': 'בקשות',
  'Reddettiğin istek yok': 'אין בקשות שנדחו',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      'בקשות שנדחו נשארות כאן; אפשר לאשר אותן שוב בכל עת.',
  'Ne izlesem?': 'מה לצפות?',
  'Karışık': 'מעורב',
  'Çarkı çevir': 'סובב את הגלגל',
  'Tekrar çevir': 'סובב שוב',
  'Bu türde içerik yok': 'אין תוכן מסוג זה',
  'Bütçe': 'תקציב',
  'dizi.jpg AI özeti': 'סיכום בינה מלאכותית של dizi.jpg',
  'Daha fazlasını gör': 'הצגת עוד',
  'Yıldız sistemi': 'מערכת כוכבים',
  '{} yıldız üzerinden': 'מתוך {} כוכבים',
  'Önizleme': 'תצוגה מקדימה',
  'dokununca açılır': 'נפתח בהקשה',
  'Bir azalt': 'הפחת באחד',
  'Bir artır': 'הגדל באחד',
  'Ölçek kaydedilemedi': 'לא ניתן היה לשמור את הסולם',
  'Ölçeği değiştirmek puanlarını silmez; aynı puanlar yeni ölçekte gösterilir.':
      'שינוי הסולם אינו מוחק את הדירוגים שלך; אותם דירוגים מוצגים בסולם החדש.',
  'En aşağıya gönder': 'שלח לתחתית',
  'Listenin en altına taşındı': 'הועבר לתחתית הרשימה',
  'Oturumun sonlandı': 'ההפעלה שלך הסתיימה',
  'Bu hesabın oturumları kapatıldı ya da şifresi değişti. Devam etmek için tekrar giriş yap.':
      'החשבון הזה נותק בכל המכשירים או שהסיסמה שונתה. התחבר שוב כדי להמשיך.',
  'Son izleme: {}': 'נצפה לאחרונה: {}',
  '{} tarihinde izledin': 'נצפה ב-{}',
  'Geri bildirimine yanıt verdik': 'הגבנו למשוב שלך',
  'Bu yanıt artık görüntülenemiyor.': 'לא ניתן עוד להציג את התגובה הזו.',
  'Gönderdiğin geri bildirim': 'המשוב ששלחת',
  'Dizi veya film seç (zorunlu)': 'בחר סדרה או סרט (חובה)',
  'Bölüm seç (isteğe bağlı)': 'בחר פרק (אופציונלי)',
  '{}. sezon {}. bölüm': 'עונה {}, פרק {}',
  'Ne düşünüyorsun?': 'מה דעתך?',
  '{}/{} yükleniyor': 'מעלה {}/{}',
  'Fotoğraf/video ekle': 'הוסף תמונה או וידאו',
  'Paylaşmak için önce bir dizi veya film seç.':
      'בחר תחילה סדרה או סרט כדי לשתף.',
  'Sezon seç': 'בחר עונה',
  '{}. sezon': 'עונה {}',
  'Bölüm seçme (yalnız dizi hakkında)': 'ללא פרק (על הסדרה בלבד)',
  'Sezonlar yüklenemedi.': 'לא ניתן לטעון את העונות.',
  'Bu dizide bölüm bilgisi yok.': 'אין מידע על פרקים לסדרה הזו.',
  'Bu sezonda bölüm yok.': 'אין פרקים בעונה הזו.',
  '{}. bölüm': 'פרק {}',
  'Dizi veya film ara...': 'חפש סדרות וסרטים...',
  'İzlediğin dizi ve film hakkında yorum paylaş': 'שתף תגובה על מה שצפית',
  'Yapım seç (zorunlu)': 'בחר כותר (חובה)',
  'Paylaşmak için önce bir yapım seç.': 'בחר תחילה כותר כדי לשתף.',
  'Kişi': 'אדם',
  'Yapım firması': 'חברת הפקה',
  'Yapım ara...': 'חפש כותרים...',
  'Çarkı çevirmek için sürükle veya dokun': 'גרור או הקש כדי לסובב את הגלגל',
  'Arşiv': 'ארכיון',
  'Yüklediklerim': 'ההעלאות שלי',
  'GIF ara...': 'חיפוש GIF...',
  'GIF yükle': 'העלאת GIF',
  'GIF etiketleri': 'תגיות GIF',
  'Virgülle ayır. Aramada bu kelimelerle bulunur.':
      'הפרד בפסיקים. במילים האלה ימצאו אותו.',
  'gülme, alkış, şaşkın': 'צחוק, מחיאות כפיים, הפתעה',
  'Yükle': 'העלה',
  'Henüz GIF yok': 'עדיין אין GIF',
  'Bu aramaya uyan GIF yok': 'אין GIF שתואם לחיפוש הזה',
  'Arşiv yeni. İlk GIF i sen yükle — sen hemen kullanırsın, onaydan sonra herkes görür.':
      'הארכיון חדש. העלה את ה-GIF הראשון — אפשר להשתמש בו מיד, וכולם יראו אותו לאחר האישור.',
  'GIF yüklendi. Sen hemen kullanabilirsin; herkese açık arşive onaydan sonra girer.':
      'ה-GIF הועלה. אפשר להשתמש בו מיד; לארכיון הציבורי הוא נכנס לאחר האישור.',
  'Onay bekliyor': 'ממתין לאישור',
  'GIF listesi yüklenemedi': 'לא ניתן לטעון את רשימת ה-GIF',
  'GIF yüklenemedi': 'לא ניתן להעלות את ה-GIF',
  'Bu GIF i şikayet et': 'דווח על ה-GIF הזה',
  'Uygunsuz içerik yöneticiye bildirilir ve arşivden kaldırılabilir.':
      'תוכן לא הולם מדווח למנהל ועשוי להיות מוסר מהארכיון.',
  'Şikayetin alındı': 'הדיווח שלך התקבל',
  'Şikayet gönderilemedi': 'לא ניתן לשלוח את הדיווח',
  'Dizinin kendisi': 'הסדרה עצמה',
  'Sezon ya da bölüm seçme': 'בלי עונה או פרק',
  'Tüm {}. sezon': 'כל עונה {}',
  'Bölüm seçme': 'בלי פרק',
  'En fazla {} yapım ekleyebilirsin.': 'אפשר להוסיף עד {} כותרים.',
  'Bu zaten ekli.': 'כבר נוסף.',
  'Dizi, film, oyuncu ya da yönetmen etiketle — gönderin onların sayfasında da görünür.':
      'תייג סדרה, סרט, שחקן או במאי — הפוסט שלך יופיע גם בעמוד שלהם.',
  'Etiket ekle': 'הוספת תגית',
  'Dizi, film, oyuncu ya da yönetmen etiketle': 'תייג סדרה, סרט, שחקן או במאי',
  'Gönderiden vazgeç': 'ביטול הפוסט',
  'Yazdıkların kaydedilmeyecek.': 'מה שכתבת לא יישמר.',
  'Yazmaya devam et': 'להמשיך לכתוב',
  'Bulunamadı. Adın yazılışını değiştirip dene.': 'לא נמצא. נסה איות אחר.',
  'Dizi, film, oyuncu, yönetmen ya da yapım firması ara.':
      'חפש סדרה, סרט, שחקן, במאי או חברת הפקה.',
};
