/// Otomatik üretilen çeviri haritası (sr).
const Map<String, String> cevirilerSr = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Видели сте све, ми вам показујемо од почетка',
  'Aktarılacak tanınan veri bulunamadı.':
      'Није пронађен препознатљив податак за увоз.',
  'Arama': 'Претрага',
  'Aramaya başla': 'Почни да претражујеш',
  'Son aramalar': 'Недавне претраге',
  'Ayarlar': 'Подешавања',
  'Bağla': 'Повежи',
  'Bio': 'Био',
  'Bitirdim': 'Завршено',
  'Bunları da Beğenebilirsin': 'Можда ти се свиде и ови',
  'Bölüm': 'Епизода',
  'Bıraktım': 'Напуштено',
  'Dil': 'Језик',
  'Dil ara...': 'Претражи језике...',
  'Dizi': 'Серија',
  'Dizi ve filmlerini takip et': 'Прати своје серије и филмове',
  'Dizi yorumu': 'Коментар о серији',
  'Dizi, film veya kişi ara...': 'Претражи серије, филмове или особе...',
  'Dosya en fazla 30MB olabilir': 'Фајл може бити највише 30MB',
  'Dosya en fazla {}MB olabilir': 'Фајл може бити највише {}MB',
  'E-posta': 'Имејл',
  'E-posta veya kullanıcı adı': 'Имејл или корисничко име',
  'En az 2 harf yaz': 'Укуцај бар 2 слова',
  'Film': 'Филм',
  'Film yorumu': 'Коментар о филму',
  'Fotoğraf / video ekle': 'Додај фотографију / видео',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Фотографија или GIF — профилна и насловна слика',
  'Giriş Yap': 'Пријави се',
  'Gönder': 'Пошаљи',
  'Gönderildi': 'Послато',
  'Haftanın Dizileri': 'Серије недеље',
  'Haftanın Filmleri': 'Филмови недеље',
  'Henüz izleme kaydın yok': 'Још немаш историју гледања',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Још немаш листу — направи је у картици Профил.',
  'Henüz yorum yok.': 'Још нема коментара.',
  'Hesabın bağlandı!': 'Налог је повезан!',
  'Hesabın yok mu? Kayıt ol': 'Немаш налог? Региструј се',
  'Hesabını Bağla': 'Повежи свој налог',
  'Hesap Oluştur': 'Направи налог',
  'Kapak resmi ekle': 'Додај насловну слику',
  'Kaydet': 'Сачувај',
  'Kendinden bahset...': 'Реци нешто о себи...',
  'Keşfet': 'Откриј',
  'Kimseyi takip etmiyor': 'Не прати никога',
  'Kişi ara': 'Претражи особе',
  'Kişi yorumu': 'Коментар о особи',
  'Konuk Oyuncular': 'Гостујуће улоге',
  'Kullanıcı adı (küçük harf)': 'Корисничко име (мала слова)',
  'Kullanıcı adı ara...': 'Претражи корисничка имена...',
  'Liste adı': 'Назив листе',
  'Listeye Ekle': 'Додај на листу',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Користиш налог за госте — повежи га са имејлом да не изгубиш податке!',
  'Misafir olarak devam et': 'Настави као гост',
  'Oluştur': 'Направи',
  'Oyuncular': 'Глумци',
  'Profil': 'Профил',
  'Profil kaydedildi': 'Профил је сачуван',
  'Puanla': 'Оцени',
  'Puanı Sil': 'Обриши оцену',
  'Puanın': 'Твоја оцена',
  'Sezonlar': 'Сезоне',
  'Sunucu hatası ({})': 'Грешка сервера ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Коментар за S{}E{}',
  'Takibi Bırak': 'Отпрати',
  'Takip': 'Праћење',
  'Takip Edilenler': 'Праћени',
  'Takip Et': 'Запрати',
  'Takipçi': 'Пратилац',
  'Takipçi yok': 'Нема пратилаца',
  'Takipçiler': 'Пратиоци',
  'Takvim': 'Календар',
  'Tamam': 'У реду',
  'Tekrar Dene': 'Покушај поново',
  'Tekrar dene': 'Покушај поново',
  'Toplam İzleme Süresi': 'Укупно време гледања',
  'Tüm Zamanların En İyileri': 'Најбоље свих времена',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'Преузми све своје податке (гледања, оцене, коментаре, листе) као ZIP компатибилан са TV Time или увези ZIP из друге апликације.',
  'Tümünü Kaldır': 'Уклони све',
  'Tümünü İzledim': 'Све одгледано',
  'Türk Dizileri': 'Турске серије',
  'Veri içe aktar (.zip)': 'Увоз података (.zip)',
  'Verilerim': 'Моји подаци',
  'Verilerimi dışa aktar (e-posta)': 'Извези моје податке (имејл)',
  'Verilerini dışa aktar': 'Извези своје податке',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Нема предстојећих епизода.\nУ детаљима серије пребаци је на "Гледам" и прати нове епизоде овде.',
  'Yapımları': 'Филмографија',
  'Yeni Diziler': 'Нове серије',
  'Yeni Liste': 'Нова листа',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Ново корисничко име (опционо)',
  'Yorum': 'Коментар',
  'Yorumunu yaz...': 'Напиши свој коментар...',
  'Zaten hesabın var mı? Giriş yap': 'Већ имаш налог? Пријави се',
  'ort. {}': 'прос. {}',
  'takip': 'праћења',
  'takipçi': 'пратилаца',
  '{} / {} bölüm': '{} / {} епизода',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} мес.',
  '{} ay~tekil': '{} мес.',
  '{} bölüm izlendi': '{} епизода одгледано',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} мин',
  '{} dk~tekil': '{} мин',
  '{} gün': '{} дана',
  '{} gün~tekil': '{} дан',
  '{} içerik': '{} наслова',
  '{} içerik · otomatik': '{} наслова · аутоматски',
  '{} kayıt atlandı (eşleşmedi).': '{} записа прескочено (без поклапања).',
  '{} saat': '{} сати',
  '{} saat~tekil': '{} сат',
  '{} sezon': '{} сезона',
  '{} yıl': '{} година',
  '{} yıl~tekil': '{} година',
  '{}. Bölüm': '{}. епизода',
  '{}. Sezon': '{}. сезона',
  'Çıkış Yap': 'Одјави се',
  'Ülke': 'Земља',
  'Ülke ara...': 'Претражи земље...',
  'Ülke seç': 'Изабери земљу',
  'İlk yorumu sen yaz!': 'Напиши први коментар!',
  'İncelemeler': 'Рецензије',
  'İncelemen (isteğe bağlı)': 'Твоја рецензија (опционо)',
  'İptal': 'Откажи',
  'İzlediklerim': 'Историја гледања',
  'İzledim': 'Одгледано',
  'İzledin': 'Одгледано',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Историја гледања и листе остају сачуване; од сада можеш да се пријавиш са било ког уређаја.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Историја гледања, оцене, коментари и листе биће послати као ZIP на регистровану имејл адресу.',
  'İzleyeceğim': 'Гледаћу',
  'İzliyorum': 'Гледам',
  'İçe aktarım tamamlandı': 'Увоз је завршен',
  'Şifre': 'Лозинка',
  '• profil bilgisi': '• подаци о профилу',
  '• {} dizi durumu': '• {} статуса серија',
  '• {} izleme kaydı': '• {} записа гледања',
  '• {} liste': '• {} листа',
  '• {} puan': '• {} оцена',
  '• {} yorum': '• {} коментара',
  '{}+ yapım': '{}+ наслова',
  'Yorumlar': 'Коментари',
  'Yorumlar ({})': 'Коментари ({})',
  'Yorumları ({})': 'Коментари ({})',
  'Listelerim': 'Моје листе',
  'Nereden izledin?': 'Где је гледано?',
  'Diziye git': 'Иди на серију',
  'TV / Kanal': 'ТВ / канал',
  'Sinema': 'Биоскоп',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Друго',
  'Akış': 'Фид',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Твој фид је празан.\nКад неко коментарише серије и филмове које гледаш, појавиће се овде.',
  'Listeleri ({})': 'Листе ({})',
  'Liste boş.': 'Ова листа је празна.',
  'Yanıtla': 'Одговори',
  '@{} kullanıcısına yanıt veriyorsun': 'Одговор за @{}',
  'İzlediğim Diziler ({})': 'Одгледане серије ({})',
  'İzlediğim Filmler ({})': 'Одгледани филмови ({})',
  'Tümünü gör': 'Прикажи све',
  'Bildirimler': 'Обавештења',
  'Henüz bildirim yok': 'Још нема обавештења',
  '@{} yorumuna yanıt verdi': 'Нови одговор на твој коментар: @{}',
  '@{} yorumunu beğendi': '@{} се свиђа твој коментар',
  '@{} seni takip etti': '@{} те прати',
  '@{} sana mesaj gönderdi': 'Нова порука од @{}',
  'Mesajlar': 'Поруке',
  'Mesaj': 'Порука',
  'Mesaja eklenecek': 'Биће додато поруци',
  'Mesajını yaz...': 'Напиши поруку...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Још нема ћаскања.\nОтвори профил и пошаљи поруку.',
  'Şifreni mi unuttun?': 'Заборављена лозинка?',
  'Şifreyi Sıfırla': 'Ресетуј лозинку',
  'E-postadaki kod': 'Код из мејла',
  'Yeni şifre': 'Нова лозинка',
  'Sana Özel': 'За тебе',
  '{} özetin': 'Твој преглед {}.',
  'Yıllık izleme istatistiklerin': 'Годишња статистика гледања',
  'Rozetler': 'Беџеви',
  'Verdiğin puan': 'Дате оцене',
  'Ortalama puanın': 'Просечна оцена',
  'En çok izlediğin diziler': 'Твоје најгледаније серије',
  'İlk Bölüm': 'Прва епизода',
  '100 Bölüm': '100 епизода',
  '1000 Bölüm': '1000 епизода',
  'İlk Film': 'Први филм',
  '50 Film': '50 филмова',
  'İlk Yorum': 'Први коментар',
  '25 Yorum': '25 коментара',
  '10 Puan': '10 оцена',
  'İlk Takipçi': 'Први пратилац',
  '10 Dizi Bitirdin': 'Завршено 10 серија',
  'İzlemeyi Bıraktım': 'Више не гледам',
  'İzlediği Diziler ({})': 'Одгледане серије ({})',
  'İzlediği Filmler ({})': 'Одгледани филмови ({})',
  '500 Bölüm': '500 епизода',
  '5000 Bölüm': '5000 епизода',
  '10 Film': '10 филмова',
  '100 Film': '100 филмова',
  '100 Yorum': '100 коментара',
  '50 Puan': '50 оцена',
  '100 Puan': '100 оцена',
  '10 Takipçi': '10 пратилаца',
  '50 Takipçi': '50 пратилаца',
  '25 Dizi Bitirdin': 'Завршено 25 серија',
  '50 Dizi Bitirdin': 'Завршено 50 серија',
  '10 Beğeni': '10 лајкова',
  '100 Beğeni': '100 лајкова',
  'yazıyor...': 'куца...',
  'ses kaydediyor...': 'снима аудио...',
  'Profil düzeni': 'Распоред профила',
  'Konumla ve kırp': 'Намести и исеци',
  'Listeye eklendi': 'Додато у листу',
  'Listeyi sil?': 'Обрисати листу?',
  'Sil': 'Обриши',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Биће означено као никад гледано и уклоњено са твојих листа.',
  'Gelecek bölüm bugün': 'Следећа епизода данас',
  'Gelecek bölüm {} gün sonra': 'Следећа епизода за {} дана',
  'Tema': 'Тема',
  'Sistem': 'Систем',
  'Koyu': 'Тамна',
  'Açık': 'Светла',
  'İzleyenler': 'Гледаоци',
  'Yorumunu yaz... (@ ile etiketle)': 'Напиши коментар... (@ за означавање)',
  '@{} bir yorumda seni etiketledi': 'Помињање од @{} у коментару',
  'Mesajı sil': 'Обриши поруку',
  'Mesaj silinemedi': 'Порука није могла бити обрисана',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Веза је неисправна или страница није пронађена',
  "Keşfet'e dön": 'Назад на Откриј',
  'Düzenle': 'Измени',
  'Mesajı düzenle': 'Измени поруку',
  'Yanıtlanıyor': 'Одговара',
  'düzenlendi': 'измењено',
  'Fotoğraf': 'Фотографија',
  'Video': 'Видео',
  'İçerik': 'Садржај',
  'çevrimiçi': 'на вези',
  'son görülme {} dk önce': 'онлајн пре {} мин',
  'son görülme {} saat önce': 'онлајн пре {} ч',
  'son görülme {} gün önce': 'онлајн пре {} д',
  'Yorumlar yüklenemedi': 'Коментари нису могли да се учитају',
  'Favori': 'Омиљено',
  'Listeye ekle': 'Додај на листу',
  'İçerik paylaş': 'Подели садржај',
  'Kapat': 'Затвори',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Све што означиш као погледано скупља се овде.',
  'Henüz sohbetin yok': 'Још нема разговора',
  'Bir profile girip mesaj gönderebilirsin.': 'Отвори профил и пошаљи поруку.',
  'Listeyi sil': 'Обриши листу',
  'Puan kaydedilemedi': 'Оцена није могла да се сачува',
  'Nerede İzlenir': 'Где гледати',
  'Abonelik': 'Претплата',
  'Kirala': 'Изнајми',
  'Satın al': 'Купи',
  'Devam et': 'Настави',
  'Şikayet et': 'Пријави',
  'Engelle': 'Блокирај',
  'Engeli kaldır': 'Одблокирај',
  'Kullanıcı engellendi': 'Корисник је блокиран',
  'Engel kaldırıldı': 'Блокирање уклоњено',
  'Şikayet sebebi': 'Разлог пријаве',
  'Spam veya yanıltıcı': 'Спам или обмањујуће',
  'Taciz veya nefret söylemi': 'Узнемиравање или говор мржње',
  'Uygunsuz / cinsel içerik': 'Неприкладан / сексуални садржај',
  'Şiddet veya tehlikeli içerik': 'Насиље или опасан садржај',
  'Telif hakkı ihlali': 'Кршење ауторских права',
  'Şikayetin alındı, teşekkürler': 'Твоја пријава је примљена, хвала',
  'Hesabımı Sil': 'Обриши налог',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Твој налог и сви подаци (историја, оцене, коментари, листе, поруке) биће трајно обрисани. Ово се не може опозвати.',
  'Şifreni gir': 'Унеси лозинку',
  'Hesabımı kalıcı sil': 'Трајно обриши налог',
  'Sesli mesaj': 'Гласовна порука',
  'Ses gönderilemedi': 'Гласовна порука није послата',
  'Kaydediliyor…': 'Снимање…',
  'Ses oynatılamadı': 'Није могуће репродуковати аудио',
  'Oynat': 'Пусти',
  'Fragmanı oynat': 'Пусти трејлер',
  'Altyazıyı aç': 'Укључи титлове',
  'Altyazıyı kapat': 'Искључи титлове',
  '10 saniye ileri': 'Напред 10 секунди',
  '10 saniye geri': 'Назад 10 секунди',
  'Duraklat': 'Пауза',
  'Liste görünümü': 'Приказ листе',
  'Takvim görünümü': 'Приказ календара',
  'Önceki ay': 'Претходни месец',
  'Sonraki ay': 'Следећи месец',
  'Bu gün bölüm yok': 'Нема епизода овог дана',
  'Gizlilik Politikası': 'Политика приватности',
  'Son güncelleme: {}': 'Последње ажурирање: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Ова политика објашњава који се подаци прикупљају, како се користе и која су твоја права када користиш апликацију dizi.jpg и сајт dizijpg.com.',
  'Topladığımız Veriler': 'Подаци које прикупљамо',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Налог: имејл адреса, корисничко име и лозинка. Лозинке се чувају као неповратни хеш; гостујући налози могу се користити без имејла.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Профил: подаци које сам одлучиш да додаш, попут аватара, насловне слике, биографије и земље.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Коришћење: твоја историја гледања, оцене, коментари, листе, реакције и омиљено.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Поруке: твоје текстуалне, сликовне и гласовне поруке чувају се на нашим серверима. Поруке нису шифроване с краја на крај; прегледају се само ако буду пријављене, ради модерације.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Отпремљени медији: фотографије, GIF-ови, видео-снимци и гласовни снимци које додајеш профилу, коментарима и порукама.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Техничко: IP адреса, приближна локација (на нивоу земље/града), платформа уређаја, верзија апликације и евиденције грешака. Чувају се ради безбедности и отклањања грешака.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Статистика коришћења: тип уређаја, оперативни систем и прегледач са којих се приступа додају се у дневне збирне бројаче као грубе категорије; сам идентификатор прегледача се не чува и ови бројеви се не могу повезати с особама.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Обавештења: за пуш обавештења чувамо токен твог уређаја и изабрани језик. Обавештења можеш било кад искључити у подешавањима уређаја.',
  'Verileri Nasıl Kullanırız': 'Како користимо твоје податке',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Твоје податке користимо искључиво за пружање услуге, заштиту налога, слање обавештења, исправљање грешака и спречавање злоупотребе. Не продајемо твоје податке и не делимо их ни са ким у рекламне сврхе.',
  'Çerezler ve Yerel Depolama': 'Колачићи и локално складиште',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Локално складиште користимо само да останеш пријављен и да запамтимо изборе попут језика и теме. Нема рекламних ни колачића за праћење.',
  'Üçüncü Taraf Hizmetler': 'Услуге трећих страна',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Подаци о серијама и филмовима долазе са TMDB, информације о стриминг платформама са JustWatch. Пуш обавештења испоручује Google Firebase, а саобраћај сајта штити Cloudflare. На ове услуге примењују се њихове сопствене политике приватности.',
  'Saklama ve Silme': 'Чување и брисање',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Твоји подаци се чувају док твој налог постоји. Преко „Обриши мој налог" у подешавањима можеш трајно обрисати налог; подаци се бришу одмах, а њихове копије у резервним копијама најкасније за 14 дана. Евиденције грешака аутоматски се бришу после 30 дана.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'Своје податке можеш извести као ZIP из подешавања; архива се шаље на твоју имејл адресу.',
  'Güvenlik': 'Безбедност',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Подаци путују шифрованим везама (HTTPS) и чувају се на серверима са ограниченим приступом.',
  'Çocukların Gizliliği': 'Приватност деце',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg није намењен деци млађој од 13 година.',
  'Hakların': 'Твоја права',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Према KVKK и GDPR имаш право на приступ својим подацима, исправку, брисање и пренос. За то нам пиши: {}',
  'Değişiklikler': 'Измене',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Ако се ова политика промени, нова верзија биће објављена на овој страници, а датум ажуриран.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Регистрацијом прихваташ {}.',
  'Kullanıcılar': 'Корисници',
  'Fotoğrafı değiştir': 'Промени фотографију',
  'Yeniden konumlandır': 'Поново кадрирај',
  'Bir şeyler ters gitti': 'Нешто је пошло наопако',
  'Sosyal Bağlantılar': 'Друштвене везе',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'На профилу се приказује до 3 везе.',
  'Platform seç': 'Изабери платформу',
  'Kullanıcı adın': 'Твоје корисничко име',
  'Ekle': 'Додај',
  'Kaldır': 'Уклони',
  'Kopyalandı: {}': 'Копирано: {}',
  'Geçersiz kullanıcı adı': 'Неисправно корисничко име',
  'Bağlantı ekle': 'Додај везу',
  'Spoiler olabilir — dokun ve gör':
      'Може садржати спојлере — додирни да видиш',
  'Beğeni': 'Свиђања',
  'beğeni': 'свиђања',
  'Beğen': 'Свиђа ми се',
  'Görüntülenme': 'Прегледи',
  'görüntülenme': 'прегледи',
  'Tam ekran': 'Цео екран',
  'Arama başarısız': 'Претрага није успела',
  'Sonuç bulunamadı': 'Нема резултата',
  'Dizi ve Filmler': 'Серије и филмови',
  'Kişiler': 'Особе',
  'Ana Sayfa': 'Почетна',
  'Paylaş': 'Подели',
  'Yanıtlar': 'Одговори',
  'Yaklaşan Bölümler': 'Предстојеће епизоде',
  'Yetişme Listesi': 'Листа за надокнаду',
  'Şunu mu demek istedin': 'Да ли сте мислили',
  'Spoiler': 'Спојлер',
  'Spoiler — dokun ve gör': 'Спојлер — додирни да видиш',
  'uyum': 'подударања',
  'Uyum': 'Подударање',
  '{} ortak dizi': '{} заједничких серија',
  '{} ortak film': '{} заједничких филмова',
  'Bildirim Tercihleri': 'Подешавања обавештења',
  'Beğeniler': 'Свиђања',
  'Yeni takipçiler': 'Нови пратиоци',
  'Etiketlenmeler': 'Помињања',
  'Yeniden izledim': 'Поново гледано',
  '{}. kez izlendi': 'Гледано {} пута',
  'Gönderi bulunamadı': 'Објава није пронађена',
  'Gözat': 'Прегледај',
  'Diziler': 'Серије',
  'Filmler': 'Филмови',
  'Tümü': 'Све',
  'Farklı bir tür seç.': 'Пробај други жанр.',
  'Gizlilik': 'Приватност',
  'İzlediklerimi gizle': 'Сакриј шта гледам',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Одгледане серије и филмови неће се видети на твом профилу',
  'Yorumlarımı gizle': 'Сакриј моје коментаре',
  'Profilinde yorumların görünmez':
      'Твоји коментари неће се видети на твом профилу',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Појединачну серију или филм можеш сакрити чипом „Сакриј на мом профилу” на њеној страници.',
  'Geri Bildirim': 'Повратне информације',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Напиши своје мишљење и предлоге о апликацији...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Хвала! Твоја повратна информација је примљена.',
  'Profilimde gizle': 'Сакриј на мом профилу',
  'Yorumları': 'Коментари',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Овај корисник још ништа није гледао.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Овај корисник радије држи своје коментаре скривеним.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Подаци: JustWatch',
  'Web Sitesi': 'Веб-сајт',
  'Diğer uygulamalar': 'Друге апликације',
  'Bağlantıyı kopyala': 'Копирај везу',
  'Henüz kimseyi takip etmiyorsun.': 'Још никога не пратиш.',
  'Çevir': 'Преведи',
  'Çeviri şu an yapılamadı': 'Превод тренутно није доступан',
  'Bağlantı açılamadı': 'Веза није могла да се отвори',
  'Orijinali göster': 'Прикажи оригинал',
  'Çeviriyi göster': 'Прикажи превод',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Овог месеца нема епизода са објављеним датумом емитовања. Датуми се обично објављују неколико недеља раније и тада ће се појавити овде.',
  'devamı': 'још',
  'Google ile devam et': 'Настави преко Google-а',
  'Google girişi başarısız': 'Пријава преко Google-а није успела',
  'Veri tasarrufu': 'Уштеда података',
  'Wi-Fi ağında veri tasarrufu': 'Уштеда података на Wi-Fi мрежи',
  'Mobil veride veri tasarrufu': 'Уштеда података на мобилним подацима',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Када је укључено, фотографије се не преузимају унапред — учитава се само кадар који гледаш.',
  'Çocuk güvenliği': 'Безбедност деце',
  'Türk Filmleri': 'Турски филмови',
  'En Yüksek Puanlı Filmler': 'Најбоље оцењени филмови',
  'En Yüksek Puanlı Diziler': 'Најбоље оцењене серије',
  'En Çok İzlenen Filmler': 'Најгледанији филмови',
  'Popüler Diziler': 'Популарне серије',
  'En Çok Kazanan Filmler': 'Најуноснији филмови',
  'Kült Filmler': 'Култни филмови',
  'Yeni Filmler': 'Нови филмови',
  'Yorum yap': 'Коментариши',
  'Henüz yorum yok': 'Још нема коментара',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Твоји коментари о серијама и филмовима скупљају се овде.',
  'GIF ekle': 'Додај GIF',
  'İlk yorumu sen yaz': 'Буди први који коментарише',
  'Video altyazıları': 'Видео титлови',
  'Videolarda altyazı göster': 'Прикажи титлове на видео снимцима',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Реченица изговорена у снимку је исписана на екрану. Текст је превод: енглески у турском говору, турски на другим језицима.',
  'Güncelleme gerekli': 'Потребно је ажурирање',
  'Yeni sürüm var': 'Доступна је нова верзија',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Инсталирај нову верзију dizi.jpg да наставиш.',
  'Güncelle': 'Ажурирај',
  'Daha sonra': 'Касније',
  'Takvim güncelleniyor': 'Календар се ажурира',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Календар није могао да се ажурира, приказује се стара листа',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Неке серије нису учитане, листа може бити непотпуна',
  'Yenile': 'Освежи',
  'Devam etmek için giriş yap': 'Пријавите се да наставите',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Бесплатан налог је довољан за оцењивање, коментарисање и прављење ваше библиотеке.',
  'Şimdi değil': 'Не сада',
  'Yorum yazmak için giriş yap': 'Пријавите се да напишете коментар',
  'Kişilere göndermek için giriş yap': 'Пријавите се да пошаљете људима',
  'Beğenenler': 'Свиђања',
  'Henüz beğeni yok': 'Још нема свиђања',
  'Bu gönderiyi ilk beğenen sen ol': 'Дај прво свиђање овој објави',
  'Bu gönderiye yanıt': 'Одговор на ову објаву',
  'Spoiler içeren gönderi': 'Objava sa spojlerima',
  'Görsel gönderi': 'Objava sa slikom',
  'Bu yorumu profilimde gizle': 'Sakrij ovaj komentar na mom profilu',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Komentar ostaje na stranici serije ili filma',
  'Bu yorumu sil': 'Obriši ovaj komentar',
  'Yorum profilinde gizlendi': 'Komentar je sakriven na tvom profilu',
  'Geri al': 'Opozovi',
  'Yorum silinsin mi?': 'Obrisati komentar?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Ovaj komentar će biti trajno obrisan svuda. Ne može se opozvati.',
  'Yorum silindi': 'Komentar je obrisan',
  'Yorum profilinde tekrar görünüyor':
      'Komentar je ponovo vidljiv na tvom profilu',
  'Gizlenen yorumun yok': 'Nemaš sakrivenih komentara',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Komentari koje sakriješ dugim pritiskom na objavu u kartici Komentari na tvom profilu se skupljaju ovde.',
  'Gizlenen yorumlar': 'Sakriveni komentari',
  'Gönderiye git': 'Idi na objavu',
  'Tekrar göster': 'Prikaži ponovo',
  'Yanıtlarımı gizle': 'Sakrij moje odgovore',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Odgovori koje pišeš na tuđe objave vidljivi su samo tebi',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Ponovo prikaži komentare sakrivene na svom profilu',
  'Sıralama': 'Редослед',
  'Önerilen': 'Препоручено',
  'Kronolojik': 'Хронолошки',
  'Gelen mesaj istekleri': 'Пристигли захтеви за поруку',
  'Mesaj isteğin yok': 'Немаш захтеве за поруку',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Поруке људи које не пратиш појављују се овде.',
  'Çevrimiçi durumumu gizle': 'Сакриј мој статус на мрежи',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Други неће видети твој статус на мрежи ни време последње активности у порукама',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Међу нашим првим корисницима. Те повратне информације помогле су да апликација постане оно што је данас.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Ти си међу нашим првим корисницима. Твоје повратне информације помогле су да апликација постане оно што је данас.',
  'İleri': 'Даље',
  'Önceki': 'Претходно',
  'Sonraki': 'Следеће',
  'Seçilen dosya okunamadı': 'Изабрана датотека не може да се прочита',
  'Video açılamadı': 'Видео није могао да се отвори',
  'En fazla {} medya seçebilirsin': 'Можете изабрати највише {} ставки',
  'Hiçbir medya yüklenemedi': 'Ниједан медиј није отпремљен',
  'Seçimi kaldır': 'Уклони из избора',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'У једном коментару можете отпремити укупно {} MB',
  '{} dosya okunamadı': 'Није могуће прочитати {} датотека',
  '{} medya eklendi, {} yüklenemedi': 'Додато: {}, неуспешно: {}',
  'Kırp': 'Исеци',
  'Çiz': 'Цртај',
  'Metin': 'Текст',
  'Emoji': 'Емоџи',
  'Yinele': 'Понови',
  'Daha fazla': 'Више',
  'Hazırlanıyor…': 'Припрема…',
  'Düzenlemeden çık?': 'Изаћи из уређивања?',
  'Yaptığın değişiklikler kaybolacak.': 'Ваше измене ће бити изгубљене.',
  'Çık': 'Изађи',
  'Serbest çizim': 'Слободном руком',
  'Ok': 'Стрелица',
  'Dikdörtgen': 'Правоугаоник',
  'Daire': 'Круг',
  'Bulanıklaştır': 'Замути',
  'Pikselleştir': 'Пикселизуј',
  'Silgi': 'Гумица',
  'Çizgi kalınlığı': 'Дебљина линије',
  'Saydamlık': 'Непрозирност',
  'Dolgu': 'Испуна',
  'Renk': 'Боја',
  'Döndür': 'Ротирај',
  'Yansıt': 'Обрни',
  'Oran': 'Однос',
  'Sıfırla': 'Ресетуј',
  'Serbest': 'Слободно',
  'Metin yaz...': 'Унесите текст...',
  'Hizala': 'Поравнај',
  'Arka plan': 'Позадина',
  'Emoji ara...': 'Претражи емоџи...',
  'Son kullanılanlar': 'Недавно',
  'İfadeler ve insanlar': 'Смајлији и људи',
  'Hayvanlar ve doğa': 'Животиње и природа',
  'Yiyecek ve içecek': 'Храна и пиће',
  'Etkinlikler': 'Активности',
  'Seyahat ve yerler': 'Путовања и места',
  'Nesneler': 'Предмети',
  'Semboller': 'Симболи',
  'Bayraklar': 'Заставе',
  'Görseli düzenle': 'Уреди слику',
  'Düzenlendi': 'Уређено',
  'Düzenlenemedi': 'Уређивање није успело',
  'Düzenlenen görsel çok büyük': 'Уређена слика је превелика',
  'Videoyu düzenle': 'Uredi video',
  'Sesi kapat': 'Isključi zvuk',
  'Sesi aç': 'Uključi zvuk',
  'İptal ediliyor…': 'Otkazivanje…',
  'Bu biraz sürebilir': 'Ovo može da potraje',
  'Video çok büyük': 'Video je prevelik',
  'Video hazırlanamadı': 'Video nije mogao da se pripremi',
  'Başlangıç': 'Početak',
  'Bitiş': 'Kraj',
  'En çok {} saniye seçebilirsin': 'Možeš da izabereš najviše {} sekundi',
  'Dosya en fazla {} MB olabilir': 'Datoteka može biti najviše {} MB',
  'Medya ekle': 'Додај медије',
  'Seçili medya kalmadı': 'Ниједан медиј није изабран',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Изабери фотографију или видео да их додаш коментару.',
  'Medya seç': 'Изабери медије',
  'Daha fazla ekle': 'Додај још',
  'Medya seçilemedi': 'Медији нису могли бити изабрани',
  'Favori oyuncular': 'Омиљени глумци',
  'Henüz favori oyuncun yok': 'Још нема омиљених глумаца',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Отвори страницу глумца и додирни срце горе десно.',
  '{} yapımdan {} tanesini izledin': 'Погледали сте {} од {}',
  'izledin': 'погледано',
  'İzlemedin': 'Није погледано',
  'Yapım bulunamadı': 'Ништа није пронађено',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Ова особа нема серије ни филмове за приказ.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Историја гледања везана је за твој налог; ова листа је само твоја.',
  'Hesabın kalıcı olarak askıya alındı': 'Ваш налог је трајно суспендован',
  'Hesabın geçici olarak askıya alındı': 'Ваш налог је привремено суспендован',
  'Hesabın askıya alındı': 'Ваш налог је суспендован',
  'Sebep': 'Разлог',
  'Kalan süre': 'Преостало време',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Налог се сам откључава када истекне време',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'У овом периоду можете да читате, али не можете да објављујете, коментаришете нити шаљете поруке.',
  'Anladım': 'Разумем',
  'Ayrıntı': 'Детаљи',
  '{} dakika': '{} минута',
  'birkaç saniye': 'неколико секунди',
  'Karara itiraz et': 'Уложите жалбу на одлуку',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Објасните зашто ову казну треба укинути',
  'İtirazını gönder': 'Пошаљите жалбу',
  'İtirazın incelemede': 'Ваша жалба се разматра',
  'İtirazın reddedildi': 'Ваша жалба је одбијена',
  'İtirazın alındı, inceleniyor': 'Примили смо вашу жалбу и разматрамо је',
  'İtiraz en az 10 karakter olmalı': 'Жалба мора имати најмање 10 знакова',
  'Yükleniyor...': 'Учитавање...',
  'Bu bölüme puan ver': 'Оцените ову епизоду',
  '{} kişi puanladı': 'Оценило {} људи',
  'Bölüm izlendi olarak işaretlendi': 'Епизода означена као одгледана',
  'Sesli ara': 'Гласовни позив',
  'Görüntülü ara': 'Видео позив',
  'Çalıyor...': 'Звони...',
  'Bağlanıyor...': 'Повезивање...',
  'Cevapla': 'Јави се',
  'Reddet': 'Одбиј',
  'Sessize al': 'Искључи звук',
  'Hoparlör': 'Звучник',
  'Kamerayı kapat': 'Искључи камеру',
  'Kamerayı çevir': 'Промени камеру',
  'Cevap yok': 'Нема одговора',
  'Arama reddedildi': 'Позив је одбијен',
  'Meşgul': 'Заузето',
  'Bağlanılamadı': 'Повезивање није успело',
  'Arama iptal edildi': 'Позив је отказан',
  'Arama geçmişi': 'Историја позива',
  'Gelen arama': 'Долазни позив',
  'Giden arama': 'Одлазни позив',
  'Cevapsız arama': 'Пропуштен позив',
  'Arama şu anda kullanılamıyor': 'Позиви тренутно нису доступни',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Видео позиви су тренутно искључени, можеш да упутиш гласовни позив',
  'Bu kullanıcıyı arayamazsın': 'Не можеш да позовеш овог корисника',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Морате да пратите једно друго да бисте се звали',
  'Bu kullanıcı şu anda aranamıyor':
      'Овог корисника тренутно није могуће позвати',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Превише пропуштених позива. Покушај поново за {}',
  'Zaten bir aramadasın': 'Већ си у позиву',
  'Arama için mikrofon izni gerekiyor':
      'За позив је потребна дозвола за микрофон',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'За видео позив су потребне дозволе за камеру и микрофон',
  'Arama başlatılamadı': 'Позив није могао да се започне',
  'Kullanıcı bulunamadı': 'Корисник није пронађен',
  'Kendini arayamazsın': 'Не можеш да позовеш самог себе',
  'Arama artık geçerli değil': 'Овај позив више није важећи',
  'Bu aramanın tarafı değilsin': 'Ниси учесник овог позива',
  'Arama bulunamadı': 'Позив није пронађен',
  'Çok fazla istek, biraz bekle': 'Превише захтева, сачекај мало',
  'Bağlantı koptu': 'Веза је прекинута',
  'Arama süre sınırına ulaştı': 'Позив је достигао временско ограничење',
  'Arama en fazla 4 saat sürebilir': 'Позив може да траје највише 4 сата',
  'Arama sona erdi': 'Позив је завршен',
  'Sesli arama': 'Гласовни позив',
  'Görüntülü arama': 'Видео позив',
  'Gelen aramalar': 'Долазни позиви',
  'Sesli ve görüntülü arama bildirimleri':
      'Обавештења о гласовним и видео позивима',
  '{} sa': '{} ч',
  'Sesli ve Görüntülü Aramalar': 'Гласовни и видео позиви',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Садржај позива се никада не снима. Звук и слика путују између уређаја шифровани с краја на крај (DTLS-SRTP); наши сервери не могу да их дешифрују, прислушкују нити чувају.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Чувају се само метаподаци позива: с ким, у ком смеру, када и колико је трајао. Ови записи се аутоматски бришу после 90 дана.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Ако директна веза није могућа, звук и слика пролазе шифровани кроз релејни сервер (TURN). Ни он не може да дешифрује нити сними садржај.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Микрофон се користи само током гласовног или видео позива, а камера само током видео позива. Оба се искључују када се позив заврши.',
  'Takip ettiğin {} kişi izledi': 'Гледало је {} људи које пратиш',
  'Yorum yaz...': 'Напиши коментар...',
  'Sıradaki bölüm': 'Следећа епизода',
  'Doğrulanmış testçi': 'Верификовани тестер',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Обавештења о праћењима, свиђањима, одговорима, порукама и означавањима',
  'Sen': 'Ти',
  'Aradığınız kişide sesli arama devre dışı':
      'Гласовни позиви су искључени код ове особе',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Видео позиви су искључени код ове особе',
  'Sesli aramalara izin ver': 'Дозволи гласовне позиве',
  'Görüntülü aramalara izin ver': 'Дозволи видео позиве',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Када је искључено, нико не може да те позове гласовно; позивалац види обавештење',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Када је искључено, нико не може да те позове видеом; позивалац види обавештење',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Гласовни позиви су искључени. Можеш их укључити у Подешавања > Приватност.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Видео позиви су искључени. Можеш их укључити у Подешавања > Приватност.',
  'Sesli ve görüntülü arama': 'Гласовни и видео позиви',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Гостујући налози не могу да зову. Направи налог да би користио ово.',
  'Misafir hesaplar aranamaz': 'Гостујућим налозима се не може звати',
  'Puan dağılımı': 'Расподела оцена',
  '{} yıldız': '{} звездица',
  'Yakında gelecek': 'Ускоро',
  '{} {} yayınlandı': '{} {} је изашла',
  'Yeni bölüm yayınlandı': 'Изашла је нова епизода',
  'Yeni bölümler': 'Нове епизоде',
  'Geri': 'Назад',
  'Karşılamayı kapat': 'Затвори добродошлицу',
  'Adım {} / {}': 'Корак {} / {}',
  'Hadi başlayalım': 'Хајде да почнемо',
  'Kaydet ve devam': 'Сачувај и настави',
  '{} tanesini ekle': 'Додај {}',
  'Şimdilik geç': 'Прескочи за сада',
  'Doğum tarihin ne zaman?': 'Који је твој датум рођења?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Питамо да бисмо приказивали садржај примерен узрасту и честитали ти рођендан.',
  'Gün': 'Дан',
  'Ay': 'Месец',
  'Yıl': 'Година',
  'Doğum yılımı paylaşmak istemiyorum': 'Не желим да приказујем годину рођења',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'Датум рођења се не приказује јавно на твом профилу. Користи се само за садржај примерен узрасту и за честитку за рођендан.',
  'Ocak': 'Јануар',
  'Şubat': 'Фебруар',
  'Mart': 'Март',
  'Nisan': 'Април',
  'Mayıs': 'Мај',
  'Haziran': 'Јун',
  'Temmuz': 'Јул',
  'Ağustos': 'Август',
  'Eylül': 'Септембар',
  'Ekim': 'Октобар',
  'Kasım': 'Новембар',
  'Aralık': 'Децембар',
  'Verilerini yanında getir': 'Понеси своје податке са собом',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Ако у другој апликацији пратиш шта гледаш, можеш то пренети овде. Не мораш да почињеш испочетка.',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt и Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Изабери ZIP датотеку из извоза — пренеће се одгледано, оцене и листе.',
  'Aktarılıyor...': 'Преношење...',
  'ZIP dosyası seç': 'Изабери ZIP датотеку',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'Нема журбе: ово можеш урадити и касније у одељку Подешавања > Моји подаци.',
  'Hangi filmleri izledin?': 'Који филмови су већ одгледани?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Овде је најгледаније. Додирни оно што познајеш и додаћемо га у одгледано.',
  'SERİ FİLMLER': 'ФИЛМСКИ СЕРИЈАЛИ',
  'Serilerden {} film eklendi': 'Из серијала додато филмова: {}',
  'Film listesi yüklenemedi': 'Није успело учитавање листе филмова',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Овај корак можеш прескочити и све додати касније.',
  '{} film izlediklerine eklendi': 'У одгледано додато филмова: {}',
  'Film serileri': 'Филмски серијали',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Одгледан цео серијал? Додај га једним додиром.',
  'Seri bulunamadı': 'Серијали нису пронађени',
  'Daha sonra tekrar deneyebilirsin.': 'Можеш покушати поново касније.',
  '{} film': 'Филмова: {}',
  'Eklendi': 'Додато',
  'Tümünü izledim': 'Све одгледано',
  'Peki ya diziler?': 'А шта је са серијама?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Означи одгледано — по твојим ознакама предложићемо слично.',
  'Dizi listesi yüklenemedi': 'Није успело учитавање листе серија',
  'Seçtiklerine benzeyenler': 'Слично твом избору',
  'Her şey hazır': 'Све је спремно',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Баци брз поглед на то шта све можеш у dizi.jpg.',
  'Profilini tamamla': 'Допуни свој профил',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'У одељку Подешавања можеш додати Био, слику профила и насловну слику.',
  'Takvimin seni bekliyor': 'Календар те чека',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'Нове епизоде серија које гледаш стижу у календар, а ми јавимо обавештењем.',
  'Puan ver, yorum yaz': 'Оцени, напиши коментар',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Оцењуј епизоду по епизоду, пиши коментаре иза спојлер завесе, прави листе.',
  'Verilerin sende kalır': 'Твоји подаци остају твоји',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Подаци се чувају само уз твој налог и не продају се. У одељку Подешавања можеш све да их преузмеш или да потпуно обришеш налог.',
  'Engellenen kullanıcılar': 'Блокирани корисници',
  'Engellediğin kişileri gör, engeli kaldır':
      'Преглед блокираних и одблокирање',
  'Engellediğin kimse yok': 'Нема блокираних',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Корисника можеш блокирати преко менија са три тачке на страници профила.',
  '@{} engellensin mi?': 'Блокирати @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'Нећете видети међусобне објаве, коментаре ни профил; ни поруке ни позиви неће пролазити. Ако постоји праћење међу вама, оно се прекида и не враћа се ни ако уклониш блокаду.',
  'Bu kullanıcıyı engelledin': 'Овај корисник је блокиран',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Не видиш објаве, коментаре ни поруке ове особе, а ни та особа не види твоје.',
  '{} yeni bir yapımda: {}': '{} у новом пројекту: {}',
  'Favori kişinden yeni yapım': 'Нови пројекат омиљене особе',
  '{} için bildirimler': 'Обавештења за {}',
  'Tüm bildirimler': 'Сва обавештења',
  'Uygulamada ve telefonda': 'У апликацији и на телефону',
  'Yalnız uygulama içi': 'Само у апликацији',
  'Telefon bildirimi gönderilmez': 'Обавештење на телефон се не шаље',
  'Kapalı': 'Искључено',
  'Bu kişi için bildirim yok': 'Нема обавештења за ову особу',
  'Favori kişilerin yeni yapımları': 'Нови пројекти омиљених особа',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Када је искључено, нико не може да те позове гласовно; позивалац види обавештење "искључено"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Када је искључено, нико не може да те позове видеом; позивалац види обавештење "искључено"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'Моја активност',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'Твоја свиђања, коментари и одгледано на једном месту',
  'Henüz hareketin yok': 'Још нема активности',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Све што ти се свиђа, коментаришеш и гледаш скупља се овде.',
  'Bu süzgeçte hareket yok': 'Нема активности у овом филтеру',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Изабери други тип или се врати на „Све”.',
  'Hepsi': 'Све',
  'Puan': 'Оцена',
  'Tepki': 'Реакција',
  'İzleme': 'Одгледано',
  'Durum': 'Статус',
  'Liste': 'Листа',
  'Yorum yaptın': 'Коментар додат',
  'Yorumu beğendin': 'Свиђање коментара',
  '{} puan verdin': 'Оцена {}',
  'Tepki verdin': 'Реакција',
  'Listene ekledin': 'Додато на листу',
  'Takip etmeye başladın': 'Ново праћење',
  '"İzleyeceğim" işaretledin': 'Означено „Гледаћу”',
  '"İzliyorum" işaretledin': 'Означено „Гледам”',
  '"Bitirdim" işaretledin': 'Означено „Завршено”',
  '"Bıraktım" işaretledin': 'Означено „Напуштено”',
  'Silinmiş içerik': 'Обрисани садржај',
  'şimdi': 'сада',
  '{} g': '{} д',
  '{} y': '{} г',
  'İstatistiklerim': 'Моја статистика',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Прегледи и свиђања твојих објава',
  'Henüz gönderin yok': 'Још немаш објава',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Чим коментаришеш серију или филм, овде почињу да се сакупљају твоји прегледи и свиђања.',
  'Tüm zamanlar': 'Свих времена',
  'Son {} gün': 'Последњих {} дана',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'Историја прегледа још није почела да се сакупља; подаци првог дана појавиће се сутра.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'Историја прегледа се сакупља од {} (постоји {} дана података), па је број за {} дана још непотпун.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'Историја свиђања бележи се од {}.',
  'Bu dönemde gösterilecek gönderi yok.':
      'Нема објава за приказ у овом периоду.',
  'eksik veri': 'непотпуни подаци',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Одгледане серије и филмови, твоји бројачи гледања, време пред екраном и картица подударности неће бити видљиви другима на твом профилу',
  'Takipçi listemi gizle': 'Сакриј листу мојих пратилаца',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Други не могу да виде ко те прати; број твојих пратилаца остаје видљив',
  'Takip ettiklerimi gizle': 'Сакриј кога пратим',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Други не могу да виде кога пратиш; број праћених остаје видљив',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Овај корисник радије држи своје пратиоце скривеним.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Овај корисник радије држи скривеним кога прати.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Статистика објаве',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Статистика је доступна само за твоје сопствене објаве.',
  'Erişim': 'Досег',
  'Görüntüleyen': 'Гледаоци',
  'Kaç farklı kişi gördü (son {} gün)':
      'Колико различитих људи је видело (последњих {} дана)',
  'Paylaşım': 'Дељења',
  'Bu gönderiden sonra': 'После ове објаве',
  'Profil ziyareti': 'Посете профилу',
  'Yeni takip': 'Нова праћења',
  'İçeriğe tıklama': 'Додири на садржај',
  'Spoiler perdesini açan': 'Открили спојлер',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Дељења, посете профилу, праћења, додири на садржај, расподела по изворима и мерења спојлера сакупљају се од {}; старије није мерено.',
  'Zamana yayılmış görüntülenme': 'Прегледи кроз време',
  'Görüntülenme nereden geldi': 'Одакле су дошли прегледи',
  'Kimler gördü': 'Ко је видео',
  'Günlük veri henüz birikmeye başlamadı.':
      'Дневни подаци још нису почели да се сакупљају.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'Графикону су потребни подаци за најмање два дана. Подаци се сакупљају од {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'Највише прегледа стигло је {}. дана након објаве: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Дневни прегледи сакупљају се од {}; старије није мерено.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'Расподела по изворима тек је почела да се мери; ова објава још није добила означени преглед.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'Расподела пратиоци/откривање тек је почела да се мери; података још нема.',
  'Takip edenler': 'Пратиоци',
  'Keşiften gelenler': 'Из откривања',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Страница серије/филма',
  'Paylaşılan bağlantı': 'Подељена веза',
  'yeni ölçülüyor': 'ново мерење',
  'Kendi ortalamanla aynı düzeyde': 'На нивоу твог просека',
  'Kendi ortalamanın %{} üstünde': '{}% изнад твог просека',
  'Kendi ortalamanın %{} altında': '{}% испод твог просека',
  'Etkileşim oranı': 'Стопа интеракције',
  '(beğeni + yorum) ÷ görüntülenme': '(свиђања + коментари) ÷ прегледи',
  'Toplam görüntülenme': 'Укупно прегледа',
  '{} ile {} arasında toplam {} görüntülenme':
      'Између {} и {}: укупно {} прегледа',
  'İstatistikleri gör': 'Погледај статистику',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'За статистику која се приказује власнику објаве чувају се као збирни бројачи: колико пута и са које површине (фид, профил, фид преко целог екрана, страница серије/филма, подељена веза) је објава прегледана, да ли је гледалац у том тренутку пратио власника објаве, прелазак са објаве на профил или садржај, праћења настала преко објаве, дељења и откривање спојлер завесе. Ови бројачи не садрже идентитет корисника, IP адресу нити временску ознаку; не може се утврдити ко је шта урадио.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'Да би се могло избројати колико различитих људи је видело објаву, за сваког гледаоца се 90 дана чува неповратни сажетак са кључем (криптографско скраћење изведено из идентитета корисника или IP адресе). Власнику објаве приказује се само број; идентитет гледалаца се ни под којим условима не дели.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'Преместити у „Гледаћу“?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'Наслов је или за гледање или одгледан. Ако наставиш, твоје ознаке гледања у овој серији ({}) биће обрисане.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'Наслов је или за гледање или одгледан. Ако наставиш, твоја ознака „Одгледано“ за овај филм биће уклоњена.',
  'Sil ve taşı': 'Обриши и премести',

  // --- Yapım ekibi + yapım firmaları ---
  'Yapım Ekibi': 'Екипа',
  'Yaratıcı': 'Творац',
  'Yönetmen': 'Режија',
  'Senaryo': 'Сценарио',
  'Yapımcı': 'Продукција',
  'Yapım Firmaları': 'Продукцијске куће',
  'Yapım Firması': 'Продукцијска кућа',
  'Firma bulunamadı': 'Продукцијска кућа није пронађена',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'Ова кућа нема наслове ове врсте.',
  // --- İzleyici seviyesi ve unvanları (cinsiyetsiz) ---
  // --- Doğum günü kutlama kartı ---
  'Doğum günün kutlu olsun!': 'Срећан рођендан!',
  'İyi ki doğdun, iyi ki buradasın.': 'Како је лепо што постојиш и што си ту.',
  'Bugün {} yaşına girdin': 'Данас пуниш {} година',
  'Teşekkürler': 'Хвала',
  // --- İki adımlı doğrulama (2FA) ---
  'İki Adımlı Doğrulama': 'Потврда у два корака',
  'Girişte e-postana kod gönderilir': 'При пријави се шаље код на имејл',
  'Kod {} adresine gönderildi': 'Код је послат на {}',
  '6 haneli kod': 'Код од 6 цифара',
  'Doğrula': 'Потврди',
  'Yeniden gönder': 'Пошаљи поново',
  'Vazgeç': 'Одустани',
  'Yeni kod gönderildi': 'Нови код је послат',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'При пријави преко Google-а код се не тражи; Google обавља сопствену проверу.',
  'Kapatmak için de kod gerekir.': 'И за искључивање је потребан код.',
  'E-postana erişemezsen hesabına giremezsin.':
      'Без приступа имејлу пријава на налог није могућа.',
  'İki adımlı doğrulama açıldı': 'Потврда у два корака је укључена',
  'İki adımlı doğrulama kapatıldı': 'Потврда у два корака је искључена',
  // --- Video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': 'Колико је видео одгледан',
  'Videoyu başlatanlar': 'почело да гледа видео',
  'videonun %{} noktasına ulaştı': 'стигло до {}% видеа',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'Половина гледалаца одгледала је најмање {}% видеа.',
  'Sonuna kadar izleyen: %{}': 'Одгледано до краја: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'За криву је потребно најмање {} прегледа; тренутно их има {}.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'Крива обухвата све прегледе ({}) и не зависи од изабраног периода.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'Време гледања мери се од {}; старији прегледи се не рачунају.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      'Прегледа: {}. До половине видеа стигло је {}%, до краја {}%.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',

  // --- md.42/26 istatistikler + seviye ---
  'Seviye {}': 'Ниво {}',
  'Sonraki seviyeye {} puan kaldı': 'Поени до следећег нивоа: {}',
  'Gönderilerin': 'Твоје објаве',
  '{} gönderi': 'Објаве: {}',
  '{} gönderi · {} görüntülenme': 'Објаве: {} · Прегледи: {}',
  'önceki {} güne göre': 'у односу на претходних {} дана',
  'önceki {} güne göre %{} arttı': 'у односу на претходних {} дана: раст {}%',
  'önceki {} güne göre %{} azaldı': 'у односу на претходних {} дана: пад {}%',
  'önceki {} güne göre değişmedi': 'без промене у односу на претходних {} дана',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'Дневни прегледи: најмање {}, највише {}',
  'Etkileşim oranı henüz ölçülemedi': 'Стопа интеракције још није измерена',
  'Oranlar': 'Стопе',
  'Beğenme oranı': 'Стопа свиђања',
  'Yorum oranı': 'Стопа коментара',
  'Paylaşma oranı': 'Стопа дељења',
  'İçeriğe gitme oranı': 'Стопа додира на садржај',
  'Profile gitme oranı': 'Стопа посета профилу',
  'Ziyaretten takibe dönüşüm': 'Из посете у праћење',
  'beğeni ÷ görüntülenme': 'свиђања ÷ прегледи',
  'yorum ÷ görüntülenme': 'коментари ÷ прегледи',
  'paylaşım ÷ görüntülenme': 'дељења ÷ прегледи',
  'içeriğe tıklama ÷ görüntülenme': 'додири на садржај ÷ прегледи',
  'profil ziyareti ÷ görüntülenme': 'посете профилу ÷ прегледи',
  'yeni takip ÷ profil ziyareti': 'нова праћења ÷ посете профилу',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'За стопе је потребно најмање {} прегледа; тренутно их има {}.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'Стопе се рачунају из укупних бројева објаве за све време; избор дана испод их не мења.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'Ови бројеви су укупни бројеви објаве за све време (осим поља са сопственом напоменом); избор дана испод мења само графикон.',
  'Ortalama izlenme: videonun %{} kadarı': 'Просечно одгледано: {}% видеа',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'Просек 20 интервала криве задржавања.',
  'Dizi, film, kişi veya şirket ara...':
      'Претражи серије, филмове, особе или компаније...',
  'Şirketler': 'Компаније',
  'Senarist': 'Сценариста',
  'Bölüm puanları': 'Оцене епизода',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'Оцене епизода нису учитане',
  'Giriş gerekli': 'Потребна је пријава',
  'Geçersiz oturum': 'Неважећа сесија',
  'Oturum sonlandı, tekrar giriş yap': 'Сесија је завршена, пријави се поново',
  'Çok fazla istek; biraz sonra tekrar dene':
      'Превише захтева; покушај мало касније',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'Тренутно нема места на серверу, покушај поново за који тренутак',
  'Devam eden yapımlar ({})': 'Актуелне продукције ({})',
  'Diziler ({})': 'Серије ({})',
  'Filmler ({})': 'Филмови ({})',
  'Tüm yapımlar': 'Све продукције',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'Простор за медије је попуњен; обриши старе отпремљене датотеке',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'Погрешан е-маил/корисничко име или лозинка',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'Овај е-маил или корисничко име је већ заузето',
  'Google doğrulaması başarısız': 'Гоогле потврда није успела',
  'Kod geçersiz veya süresi dolmuş': 'Код је неважећи или је истекао',
  'Bu kullanıcıyla mesajlaşamazsın': 'Не можеш да пишеш овом кориснику',
  'Kendini takip edemezsin': 'Не можеш да пратиш самог себе',
  'Bu kullanıcıyı takip edemezsin': 'Не можеш да пратиш овог корисника',
  'Kendini engelleyemezsin': 'Не можеш да блокираш самог себе',
  'Yorum 1-1000 karakter olmalı': 'Коментар мора имати 1–1000 знакова',
  'Boş mesaj gönderilemez': 'Не може се послати празна порука',
  'Yorum bulunamadı': 'Коментар није пронађен',
  'Şifre hatalı': 'Погрешна лозинка',
  'Şifre en az 6 karakter olmalı': 'Лозинка мора имати најмање 6 знакова',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'Може се отпремити само GIF, PNG, JPEG или WebP',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'Подржани типови: GIF, PNG, JPEG, WebP, MP4, WebM, звук',
  'Geçerli bir ZIP dosyası değil': 'Ово није исправна ZIP датотека',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'Да би добио податке е-поштом, прво повежи адресу',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'Имаш ознаке гледања. Да би ставио „Гледаћу“, прво их обриши.',
  'Arama şu anda kapalı': 'Позиви су тренутно искључени',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'Гостујући налози не могу укључити позиве; направи налог',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'Сервер се поново покреће, покушај за који тренутак',
  'Puan 1-10 arası olmalı': 'Оцена мора бити између 1 и 10',
  'En fazla 10 medya eklenebilir': 'Може се додати највише 10 датотека',
  'Bu cihazdan yeni hesap açılamıyor':
      'Са овог уређаја се не може направити налог',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'Потребна је исправна е-пошта, корисничко име и лозинка од најмање 6 знакова',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'Потребна је исправна е-пошта и лозинка од најмање 6 знакова',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'Корисничко име 3–20 знакова; мала слова, цифре, тачке, цртице и доње црте (не на ивицама)',
  'Bu hesap zaten bağlı': 'Овај налог је већ повезан',
  'Hesap oluşturulamadı': 'Налог није направљен',
  'Misafir hesabı oluşturulamadı': 'Гостујући налог није направљен',
  'Hesap bulunamadı': 'Налог није пронађен',
  'Bu hesapta e-posta yok': 'Овај налог нема е-пошту',
  'İki adımlı doğrulama zaten bu durumda':
      'Двостепена потврда је већ у овом стању',
  'Kod yanlış': 'Погрешан код',
  'Kodun süresi doldu': 'Код је истекао',
  'Kullanıcının e-postası yok (misafir hesap)':
      'Овај корисник нема е-пошту (гостујући налог)',
  'Bio en fazla 300 karakter olabilir': 'Био може имати највише 300 знакова',
  'Geçersiz ülke': 'Неважећа земља',
  'Geçersiz sosyal bağlantı': 'Неважећи друштвени линк',
  'Geçersiz doğum tarihi': 'Неважећи датум рођења',
  'Liste adı gerekli': 'Име листе је обавезно',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'Име може имати највише 60, опис 300 знакова',
  'Liste bulunamadı': 'Листа није пронађена',
  'Değiştirilecek tercih yok': 'Нема шта ажурирати',
  'İnceleme en fazla 2000 karakter olabilir':
      'Рецензија може имати највише 2000 знакова',
  'Önce içeriği "bitirdim" olarak işaretle': 'Прво означи наслов као завршен',
  'Önce kişiyi favorile': 'Прво додај особу у омиљене',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'За коментар епизоде потребни су и сезона и епизода',
  'Yanıtlanan yorum bulunamadı': 'Коментар на који одговараш није пронађен',
  'Geri bildirim 3-2000 karakter olmalı':
      'Повратна информација мора имати 3–2000 знакова',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'Наслов и текст су обавезни (најмање 2 знака)',
  'Kendine mesaj gönderemezsin': 'Не можеш себи послати поруку',
  'Mesaj en fazla 2000 karakter olabilir':
      'Порука може имати највише 2000 знакова',
  'Mesaj 1-2000 karakter olmalı': 'Порука мора имати 1–2000 знакова',
  'Mesaj bulunamadı': 'Порука није пронађена',
  'Mesaj bulunamadı veya düzenlenemez':
      'Порука није пронађена или се не може уредити',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'Можеш пријавити само поруку која ти је послата',
  'Sebep gerekli': 'Разлог је обавезан',
  'İtiraz edilecek aktif bir ceza yok': 'Нема активне казне за жалбу',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'Већ имаш жалбу која чека преглед',
  'Bu ceza için itirazın zaten incelendi':
      'Жалба за ову казну је већ прегледана',
  'Medya bağlantısının süresi dolmuş': 'Медијски линк је истекао',
  'Bu medya için imzalı bağlantı gerekli':
      'За овај медиј је потребан потписани линк',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'Услуга позива се поново покреће; покушај ускоро',
  'Puan göstergesi': 'Легенда оцена',
  'İzleme İstatistiklerim': 'Moja statistika gledanja',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'Čim označiš epizodu ili film kao odgledane, tvoja statistika počinje da se skuplja ovde.',
  '{} sa {} dk': '{} č {} min',
  'Yaklaşık ekran süresi': 'Približno vreme pred ekranom',
  'İzleme serisi': 'Niz gledanja',
  'Şu anki seri': 'Trenutni niz',
  'En uzun seri': 'Najduži niz',
  'Haftanın günleri': 'Dani u nedelji',
  'En çok izlediklerin': 'Najviše gledano',
  'Bu dönemde izleme yok': 'Nema gledanja u ovom periodu',
  'Paz': 'ned',
  'Pzt': 'pon',
  'Sal': 'uto',
  'Çar': 'sre',
  'Per': 'čet',
  'Cum': 'pet',
  'Cmt': 'sub',
  '{} bölüm': '{} epizoda',
  '{} bölüm~tekil': '{} epizoda',
  '{} kez': '{} puta',
  '{} kez~tekil': '{} put',
  'Son {} gün · günlük': 'Poslednjih {} dana · dnevno',
  'Son {} gün · haftalık': 'Poslednjih {} dana · nedeljno',
  'Ekran süren, serin ve en çok izlediklerin':
      'Tvoje vreme pred ekranom, niz i najgledanije',
  'Daralt': 'Skupi',
  'Listeyi düzenle': 'Izmeni listu',
  'Bitti': 'Gotovo',
  'Sırala': 'Promeni redosled',
  'Herkese göster': 'Prikaži svima',
  'Başkalarından gizle': 'Sakrij od drugih',
  'Listeden kaldır': 'Ukloni sa liste',
  'Listeden kaldırılsın mı?': 'Ukloniti sa liste?',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'Ovaj naslov će biti uklonjen sa liste. Ako želiš samo da ga sakriješ, koristi ikonicu oka.',
  'Sıralama kaydedilemedi': 'Redosled nije sačuvan',
  'Değişiklik kaydedilemedi': 'Izmena nije sačuvana',
  'Kaldırılamadı': 'Nije moglo da se ukloni',
  'Popülerlik': 'Популарност',
  'TMDB puanı': 'TMDB оцена',
  'Yapım yılı': 'Година продукције',
  'dizi.jpg puanı': 'dizi.jpg оцена',
  'İzlenme': 'Прегледи',
  'Yorum sayısı': 'Број коментара',
  'Tüm raflara uygulanır': 'Примењује се на све полице',
  'En popüler {} yapım arasında sıralandı':
      'Сортирано међу {} најпопуларнијих наслова',
  'Altyazı görünümü': 'Изглед титлова',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık':
      'Боја, фонт, величина, ивица и непрозирност',
  'Bu bir örnek altyazıdır.': 'Ово је пример титла.',
  'Ayar değiştikçe önizleme anında güncellenir.':
      'Преглед се ажурира одмах при свакој промени.',
  'Yazı biçimi': 'Стил текста',
  'Yazı rengi': 'Боја текста',
  'Yazı opaklığı': 'Непрозирност текста',
  'Yazı tipi': 'Фонт',
  'Yazı boyutu': 'Величина текста',
  'Karakter ayrıtı': 'Ивица знакова',
  'Ayrıt türü': 'Тип ивице',
  'Ayrıt rengi': 'Боја ивице',
  'Yok': 'Нема',
  'Dış çizgi': 'Контура',
  'Gölge': 'Сенка',
  'Kabartma': 'Издигнуто',
  'Oyma': 'Удубљено',
  'Arka plan rengi': 'Боја позадине',
  'Arka plan opaklığı': 'Непрозирност позадине',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      'Позадина је испуна одмах иза текста, а прозор је шира површина иза целог блока титлова.',
  'Pencere': 'Прозор',
  'Pencere rengi': 'Боја прозора',
  'Pencere opaklığı': 'Непрозирност прозора',
  'Altyazı görünümü sıfırlansın mı?': 'Ресетовати изглед титлова?',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      'Подешавања боје, фонта, величине, ивице и непрозирности вратиће се на подразумевана.',
  'Altyazı görünümü varsayılana döndü':
      'Изглед титлова враћен на подразумевани',
  '{} indiriliyor…': 'Преузимање {}…',
  'Seçince indirilir': 'Преузима се при избору',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      'Није могуће преузети фонт. Приказује се подразумеваним фонтом.',
  'Beyaz': 'Бела',
  'Siyah': 'Црна',
  'Kırmızı': 'Црвена',
  'Yeşil': 'Зелена',
  'Mavi': 'Плава',
  'Sarı': 'Жута',
  'Camgöbeği': 'Цијан',
  'Macenta': 'Магента',
  'Yapım bütçesi': 'Буџет продукције',
  'Yapım bütçesi ve dünya çapında hasılat': 'Буџет продукције и светска зарада',
  'Dizinin yayın durumu': 'Статус емитовања серије',
  'Devam ediyor': 'У току',
  'Sona erdi': 'Завршена',
  'İptal edildi': 'Отказана',
  'Yapımda': 'У продукцији',
  'Planlandı': 'Планирана',
  'Pilot bölüm': 'Пилот епизода',
  'Ad': 'Име',
  'Adın': 'Твоје име',
  'Kullanıcı adı': 'Корисничко име',
  'Kullanıcı adını değiştir': 'Промени корисничко име',
  'Kullanıcı adını 90 günde bir değiştirebilirsin':
      'Корисничко име можеш да мењаш једном на 90 дана',
  'Değiştir': 'Промени',
  '{} gün sonra değiştirebilirsin': 'Моћи ћеш да промениш за {} дана',
  'Kullanıcı adın: @{}': 'Твоје корисничко име: @{}',
  'Bu kullanıcı adı zaten alınmış': 'Ово корисничко име је већ заузето',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış':
      'Ово корисничко име је тренутно резервисано за други налог',
  'Bu zaten senin kullanıcı adın': 'То је већ твоје корисничко име',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      'Корисничко име 3–20 знакова; мала слова, цифре, тачке, цртице и доње црте',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      'Приказује се на профилу изнад корисничког имена. Можеш оставити празно.',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      'После промене нећеш моћи поново да мењаш 90 дана. Старо корисничко име остаје резервисано за тебе 90 дана — можеш да се вратиш на њега и нико други не може да га узме за то време. Линкови ка старом имену више неће отварати твој профил.',
  'Etkinliğim': 'Активност',
  'Tercihler': 'Поставке',
  'Gizlilik ve güvenlik': 'Приватност и безбедност',
  'Destek': 'Подршка',
  'Hesap': 'Налог',
  '{} dizileri': 'Серије: {}',
  '{} filmleri': 'Филмови: {}',
  'En üste taşı': 'Премести на врх',
  'Sırayı sıfırla': 'Ресетуј редослед',
  'Listede ara': 'Претражи листу',
  'Elle sıra sıfırlansın mı?': 'Ресетовати ручни редослед?',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      'Листа се враћа на подразумевани редослед (најскорије означено прво).',
  'Sıra sıfırlanamadı': 'Редослед није ресетован',
  'Listenin en üstüne taşındı': 'Премештено на врх листе',
  'Adlar yükleniyor…': 'Учитавање наслова…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      'Држи постер да га превучеш. Да удаљени наслов доведеш напред, користи „Премести на врх“.',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      'Превлачење је искључено у претрази; доведи напред помоћу „Премести на врх“ ({} резултата).',
  'Görünüm': 'Приказ',
  'En çok izlediğin filmler': 'Твоји најгледанији филмови',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      'Времена су процена: епизода се рачуна ~{} мин, филм ~{} мин',
  'Bu kullanıcı adı sistem tarafından ayrılmış':
      'Ово корисничко име је резервисано од стране система',
  'Ekran süresi': 'Vreme pred ekranom',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir":
      'Vremena su stvarna trajanja epizoda i filmova sa TMDB-a',
  'Tüm zamanlar: {} bölüm · {} film · {}':
      'Sve vreme: {} epizoda · {} filmova · {}',
  'Kabul et':
      'Прихвати',
  'Reddedilenler':
      'Одбијени',
  'İstekler':
      'Захтеви',
  'Reddettiğin istek yok':
      'Нема одбијених захтева',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      'Одбијени захтеви остају овде; можеш поново да их прихватиш кад год желиш.',
};
