/// Otomatik üretilen çeviri haritası (id).
const Map<String, String> cevirilerId = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Anda telah melihat semuanya, kami tunjukkan dari awal',
  'Aktarılacak tanınan veri bulunamadı.':
      'Tidak ada data yang dikenali untuk diimpor.',
  'Arama': 'Pencarian',
  'Aramaya başla': 'Mulai mencari',
  'Son aramalar': 'Pencarian terbaru',
  'Ayarlar': 'Pengaturan',
  'Bağla': 'Tautkan',
  'Bio': 'Bio',
  'Bitirdim': 'Selesai',
  'Bunları da Beğenebilirsin': 'Mungkin Kamu Juga Suka',
  'Bölüm': 'Episode',
  'Bıraktım': 'Berhenti',
  'Dil': 'Bahasa',
  'Dil ara...': 'Cari bahasa...',
  'Dizi': 'Serial',
  'Dizi ve filmlerini takip et': 'Pantau serial dan filmmu',
  'Dizi yorumu': 'Komentar serial',
  'Dizi, film veya kişi ara...': 'Cari serial, film, atau orang...',
  'Dosya en fazla 30MB olabilir': 'Ukuran file maksimal 30MB',
  'Dosya en fazla {}MB olabilir': 'Ukuran file maksimal {}MB',
  'E-posta': 'Email',
  'E-posta veya kullanıcı adı': 'Email atau nama pengguna',
  'En az 2 harf yaz': 'Ketik minimal 2 huruf',
  'Film': 'Film',
  'Film yorumu': 'Komentar film',
  'Fotoğraf / video ekle': 'Tambah foto / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto atau GIF — foto profil dan sampul',
  'Giriş Yap': 'Masuk',
  'Gönder': 'Kirim',
  'Gönderildi': 'Terkirim',
  'Haftanın Dizileri': 'Serial Minggu Ini',
  'Haftanın Filmleri': 'Film Minggu Ini',
  'Henüz izleme kaydın yok': 'Belum ada riwayat tontonan',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Belum ada daftar — buat dari tab Profil.',
  'Henüz yorum yok.': 'Belum ada komentar.',
  'Hesabın bağlandı!': 'Akunmu sudah tertaut!',
  'Hesabın yok mu? Kayıt ol': 'Belum punya akun? Daftar',
  'Hesabını Bağla': 'Tautkan Akunmu',
  'Hesap Oluştur': 'Buat Akun',
  'Kapak resmi ekle': 'Tambah gambar sampul',
  'Kaydet': 'Simpan',
  'Kendinden bahset...': 'Ceritakan tentang dirimu...',
  'Keşfet': 'Jelajahi',
  'Kimseyi takip etmiyor': 'Tidak mengikuti siapa pun',
  'Kişi ara': 'Cari orang',
  'Kişi yorumu': 'Komentar orang',
  'Konuk Oyuncular': 'Bintang Tamu',
  'Kullanıcı adı (küçük harf)': 'Nama pengguna (huruf kecil)',
  'Kullanıcı adı ara...': 'Cari nama pengguna...',
  'Liste adı': 'Nama daftar',
  'Listeye Ekle': 'Tambah ke Daftar',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Kamu memakai akun tamu — tautkan dengan emailmu, jangan sampai datamu hilang!',
  'Misafir olarak devam et': 'Lanjut sebagai tamu',
  'Oluştur': 'Buat',
  'Oyuncular': 'Pemeran',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil tersimpan',
  'Puanla': 'Beri Rating',
  'Puanı Sil': 'Hapus Rating',
  'Puanın': 'Ratingmu',
  'Sezonlar': 'Musim',
  'Sunucu hatası ({})': 'Kesalahan server ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Komentar S{}E{}',
  'Takibi Bırak': 'Berhenti Ikuti',
  'Takip': 'Mengikuti',
  'Takip Edilenler': 'Yang Diikuti',
  'Takip Et': 'Ikuti',
  'Takipçi': 'Pengikut',
  'Takipçi yok': 'Belum ada pengikut',
  'Takipçiler': 'Pengikut',
  'Takvim': 'Kalender',
  'Tamam': 'Oke',
  'Tekrar Dene': 'Coba Lagi',
  'Tekrar dene': 'Coba lagi',
  'Toplam İzleme Süresi': 'Total waktu nonton',
  'Tüm Zamanların En İyileri': 'Terbaik Sepanjang Masa',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'Ekspor semua datamu (tontonan, nilai, komentar, daftar) sebagai ZIP yang kompatibel dengan TV Time, atau impor ZIP dari aplikasi lain.',
  'Tümünü Kaldır': 'Hapus Semua',
  'Tümünü İzledim': 'Sudah Nonton Semua',
  'Türk Dizileri': 'Serial Turki',
  'Veri içe aktar (.zip)': 'Impor data (.zip)',
  'Verilerim': 'Data Saya',
  'Verilerimi dışa aktar (e-posta)': 'Ekspor data saya (email)',
  'Verilerini dışa aktar': 'Ekspor datamu',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Tidak ada episode mendatang.\nUbah status serial jadi "Sedang Nonton" dari halaman detailnya, lalu pantau episode baru di sini.',
  'Yapımları': 'Filmografi',
  'Yeni Diziler': 'Serial Baru',
  'Yeni Liste': 'Daftar Baru',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nama pengguna baru (opsional)',
  'Yorum': 'Komentar',
  'Yorumunu yaz...': 'Tulis komentarmu...',
  'Zaten hesabın var mı? Giriş yap': 'Sudah punya akun? Masuk',
  'ort. {}': 'rata-rata {}',
  'takip': 'mengikuti',
  'takipçi': 'pengikut',
  '{} / {} bölüm': '{} / {} episode',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} bulan',
  '{} ay~tekil': '{} bulan',
  '{} bölüm izlendi': '{} episode ditonton',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} mnt',
  '{} dk~tekil': '{} mnt',
  '{} gün': '{} hari',
  '{} gün~tekil': '{} hari',
  '{} içerik': '{} judul',
  '{} içerik · otomatik': '{} judul · otomatis',
  '{} kayıt atlandı (eşleşmedi).': '{} entri dilewati (tidak cocok).',
  '{} saat': '{} jam',
  '{} saat~tekil': '{} jam',
  '{} sezon': '{} musim',
  '{} yıl': '{} tahun',
  '{} yıl~tekil': '{} tahun',
  '{}. Bölüm': 'Episode {}',
  '{}. Sezon': 'Musim {}',
  'Çıkış Yap': 'Keluar',
  'Ülke': 'Negara',
  'Ülke ara...': 'Cari negara...',
  'Ülke seç': 'Pilih negara',
  'İlk yorumu sen yaz!': 'Jadilah yang pertama berkomentar!',
  'İncelemeler': 'Ulasan',
  'İncelemen (isteğe bağlı)': 'Ulasanmu (opsional)',
  'İptal': 'Batal',
  'İzlediklerim': 'Riwayat Tontonan',
  'İzledim': 'Sudah Nonton',
  'İzledin': 'Kamu sudah nonton',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Riwayat tontonan dan daftarmu tetap aman; sekarang kamu bisa masuk dari perangkat mana pun.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Riwayat tontonan, nilai, komentar, dan daftarmu akan dikirim sebagai ZIP ke alamat email terdaftar.',
  'İzleyeceğim': 'Mau Nonton',
  'İzliyorum': 'Sedang Nonton',
  'İçe aktarım tamamlandı': 'Impor selesai',
  'Şifre': 'Kata sandi',
  '• profil bilgisi': '• info profil',
  '• {} dizi durumu': '• {} status serial',
  '• {} izleme kaydı': '• {} catatan tontonan',
  '• {} liste': '• {} daftar',
  '• {} puan': '• {} rating',
  '• {} yorum': '• {} komentar',
  '{}+ yapım': '{}+ judul',
  'Yorumlar': 'Komentar',
  'Yorumlar ({})': 'Komentar ({})',
  'Yorumları ({})': 'Komentarnya ({})',
  'Listelerim': 'Daftarku',
  'Nereden izledin?': 'Nonton di mana?',
  'Diziye git': 'Ke serial',
  'TV / Kanal': 'TV / Saluran',
  'Sinema': 'Bioskop',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Lainnya',
  'Akış': 'Beranda',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Berandamu kosong.\nSaat ada yang berkomentar di serial dan film yang kamu tonton, akan muncul di sini.',
  'Listeleri ({})': 'Daftar miliknya ({})',
  'Liste boş.': 'Daftar ini kosong.',
  'Yanıtla': 'Balas',
  '@{} kullanıcısına yanıt veriyorsun': 'Membalas @{}',
  'İzlediğim Diziler ({})': 'Serial yang kutonton ({})',
  'İzlediğim Filmler ({})': 'Film yang kutonton ({})',
  'Tümünü gör': 'Lihat semua',
  'Bildirimler': 'Notifikasi',
  'Henüz bildirim yok': 'Belum ada notifikasi',
  '@{} yorumuna yanıt verdi': '@{} membalas komentarmu',
  '@{} yorumunu beğendi': '@{} menyukai komentarmu',
  '@{} seni takip etti': '@{} mengikutimu',
  '@{} sana mesaj gönderdi': '@{} mengirimimu pesan',
  'Mesajlar': 'Pesan',
  'Mesaj': 'Pesan',
  'Mesaja eklenecek': 'Akan ditambahkan ke pesan',
  'Mesajını yaz...': 'Tulis pesan...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Belum ada obrolan.\nBuka profil dan kirim pesan.',
  'Şifreni mi unuttun?': 'Lupa kata sandi?',
  'Şifreyi Sıfırla': 'Atur Ulang Kata Sandi',
  'E-postadaki kod': 'Kode dari email',
  'Yeni şifre': 'Kata sandi baru',
  'Sana Özel': 'Untukmu',
  '{} özetin': 'Rekap {}-mu',
  'Yıllık izleme istatistiklerin': 'Statistik tontonan tahunanmu',
  'Rozetler': 'Lencana',
  'Verdiğin puan': 'Rating yang kamu beri',
  'Ortalama puanın': 'Rata-rata ratingmu',
  'En çok izlediğin diziler': 'Serial paling sering ditonton',
  'İlk Bölüm': 'Episode Pertama',
  '100 Bölüm': '100 Episode',
  '1000 Bölüm': '1000 Episode',
  'İlk Film': 'Film Pertama',
  '50 Film': '50 Film',
  'İlk Yorum': 'Komentar Pertama',
  '25 Yorum': '25 Komentar',
  '10 Puan': '10 Rating',
  'İlk Takipçi': 'Pengikut Pertama',
  '10 Dizi Bitirdin': 'Menamatkan 10 Serial',
  'İzlemeyi Bıraktım': 'Berhenti Menonton',
  'İzlediği Diziler ({})': 'Serial yang ditonton ({})',
  'İzlediği Filmler ({})': 'Film yang ditonton ({})',
  '500 Bölüm': '500 Episode',
  '5000 Bölüm': '5000 Episode',
  '10 Film': '10 Film',
  '100 Film': '100 Film',
  '100 Yorum': '100 Komentar',
  '50 Puan': '50 Rating',
  '100 Puan': '100 Rating',
  '10 Takipçi': '10 Pengikut',
  '50 Takipçi': '50 Pengikut',
  '25 Dizi Bitirdin': 'Menamatkan 25 Serial',
  '50 Dizi Bitirdin': 'Menamatkan 50 Serial',
  '10 Beğeni': '10 Suka',
  '100 Beğeni': '100 Suka',
  'yazıyor...': 'mengetik...',
  'Profil düzeni': 'Tata letak profil',
  'Konumla ve kırp': 'Atur posisi dan potong',
  'Listeye eklendi': 'Ditambahkan ke daftar',
  'Listeyi sil?': 'Hapus daftar?',
  'Sil': 'Hapus',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Judul ini akan ditandai belum pernah ditonton dan dihapus dari daftarmu.',
  'Gelecek bölüm bugün': 'Episode berikutnya hari ini',
  'Gelecek bölüm {} gün sonra': 'Episode berikutnya {} hari lagi',
  'Tema': 'Tema',
  'Sistem': 'Sistem',
  'Koyu': 'Gelap',
  'Açık': 'Terang',
  'İzleyenler': 'Penonton',
  'Yorumunu yaz... (@ ile etiketle)': 'Tulis komentarmu... (@ untuk menandai)',
  '@{} bir yorumda seni etiketledi': '@{} menandaimu di sebuah komentar',
  'Mesajı sil': 'Hapus pesan',
  'Mesaj silinemedi': 'Pesan tidak dapat dihapus',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Tautan tidak valid atau halaman tidak ditemukan',
  "Keşfet'e dön": 'Kembali ke Jelajahi',
  'Düzenle': 'Edit',
  'Mesajı düzenle': 'Edit pesan',
  'Yanıtlanıyor': 'Membalas',
  'düzenlendi': 'diedit',
  'Fotoğraf': 'Foto',
  'Video': 'Video',
  'İçerik': 'Konten',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': 'terakhir dilihat {} mnt lalu',
  'son görülme {} saat önce': 'terakhir dilihat {} jam lalu',
  'son görülme {} gün önce': 'terakhir dilihat {} hr lalu',
  'Yorumlar yüklenemedi': 'Tidak dapat memuat komentar',
  'Favori': 'Favorit',
  'Listeye ekle': 'Tambah ke daftar',
  'İçerik paylaş': 'Bagikan konten',
  'Kapat': 'Tutup',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Semua yang kamu tandai ditonton terkumpul di sini.',
  'Henüz sohbetin yok': 'Belum ada percakapan',
  'Bir profile girip mesaj gönderebilirsin.': 'Buka profil dan kirim pesan.',
  'Listeyi sil': 'Hapus daftar',
  'Puan kaydedilemedi': 'Rating tidak dapat disimpan',
  'Nerede İzlenir': 'Tempat Menonton',
  'Abonelik': 'Langganan',
  'Kirala': 'Sewa',
  'Satın al': 'Beli',
  'Devam et': 'Lanjutkan',
  'Şikayet et': 'Laporkan',
  'Engelle': 'Blokir',
  'Engeli kaldır': 'Buka blokir',
  'Kullanıcı engellendi': 'Pengguna diblokir',
  'Engel kaldırıldı': 'Blokir dihapus',
  'Şikayet sebebi': 'Alasan laporan',
  'Spam veya yanıltıcı': 'Spam atau menyesatkan',
  'Taciz veya nefret söylemi': 'Pelecehan atau ujaran kebencian',
  'Uygunsuz / cinsel içerik': 'Tidak pantas / konten seksual',
  'Şiddet veya tehlikeli içerik': 'Kekerasan atau konten berbahaya',
  'Telif hakkı ihlali': 'Pelanggaran hak cipta',
  'Şikayetin alındı, teşekkürler': 'Laporanmu sudah diterima, terima kasih',
  'Hesabımı Sil': 'Hapus Akunku',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Akunmu dan semua datamu (riwayat, rating, komentar, daftar, pesan) akan dihapus permanen. Ini tidak bisa dibatalkan.',
  'Şifreni gir': 'Masukkan kata sandimu',
  'Hesabımı kalıcı sil': 'Hapus akunku permanen',
  'Sesli mesaj': 'Pesan suara',
  'Ses gönderilemedi': 'Pesan suara gagal dikirim',
  'Kaydediliyor…': 'Merekam…',
  'Ses oynatılamadı': 'Audio tidak bisa diputar',
  'Oynat': 'Putar',
  'Duraklat': 'Jeda',
  'Liste görünümü': 'Tampilan daftar',
  'Takvim görünümü': 'Tampilan kalender',
  'Önceki ay': 'Bulan sebelumnya',
  'Sonraki ay': 'Bulan berikutnya',
  'Bu gün bölüm yok': 'Tidak ada episode hari ini',
  'Gizlilik Politikası': 'Kebijakan Privasi',
  'Son güncelleme: {}': 'Terakhir diperbarui: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Kebijakan ini menjelaskan data apa yang dikumpulkan, bagaimana digunakan, dan apa saja hakmu saat memakai aplikasi dizi.jpg dan situs dizijpg.com.',
  'Topladığımız Veriler': 'Data yang Kami Kumpulkan',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Akun: alamat email, nama pengguna, dan kata sandi. Kata sandi disimpan sebagai hash yang tidak bisa dibalik; akun tamu bisa dipakai tanpa email.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profil: informasi yang kamu pilih untuk ditambahkan, seperti avatar, gambar sampul, bio, dan negara.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Penggunaan: riwayat tontonan, penilaian, komentar, daftar, reaksi, dan favoritmu.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Pesan: pesan teks, gambar, dan suaramu disimpan di server kami. Pesan tidak terenkripsi end-to-end; hanya ditinjau untuk moderasi jika dilaporkan.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Media yang diunggah: foto, GIF, video, dan rekaman suara yang kamu tambahkan ke profil, komentar, dan pesan.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Teknis: alamat IP, perkiraan lokasi (tingkat negara/kota), platform perangkat, versi aplikasi, dan log kesalahan. Ini disimpan untuk keamanan dan perbaikan masalah.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'Statistik penggunaan: jenis perangkat, sistem operasi, dan peramban yang dipakai untuk masuk ditambahkan ke penghitung total harian dalam kategori kasar; identitas peramban itu sendiri tidak disimpan dan angka-angka ini tidak bisa dikaitkan dengan siapa pun.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'Notifikasi: untuk notifikasi push, kami menyimpan token perangkatmu dan pilihan bahasa. Kamu bisa mematikan notifikasi kapan saja dari pengaturan perangkat.',
  'Verileri Nasıl Kullanırız': 'Cara Kami Menggunakan Data',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Kami memakai datamu hanya untuk menyediakan layanan, melindungi akun, mengirim notifikasi, memperbaiki kesalahan, dan mencegah penyalahgunaan. Kami tidak menjual datamu dan tidak membagikannya kepada siapa pun untuk iklan.',
  'Çerezler ve Yerel Depolama': 'Cookie dan Penyimpanan Lokal',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Penyimpanan lokal hanya dipakai untuk menjagamu tetap masuk dan mengingat preferensi seperti bahasa dan tema. Tidak ada cookie iklan atau pelacakan.',
  'Üçüncü Taraf Hizmetler': 'Layanan Pihak Ketiga',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'Data serial dan film berasal dari TMDB, informasi platform streaming dari JustWatch. Notifikasi push dikirim lewat Google Firebase, dan lalu lintas situs dilindungi Cloudflare. Layanan ini tunduk pada kebijakan privasi masing-masing.',
  'Saklama ve Silme': 'Penyimpanan dan Penghapusan',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Datamu disimpan selama akunmu ada. Lewat "Hapus Akun Saya" di pengaturan, kamu bisa menghapus akun secara permanen; data langsung dihapus, salinan di cadangan paling lambat dalam 14 hari. Log kesalahan otomatis terhapus setelah 30 hari.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'Kamu bisa mengekspor datamu sebagai ZIP dari pengaturan; arsipnya dikirim ke alamat emailmu.',
  'Güvenlik': 'Keamanan',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Data dikirim lewat koneksi terenkripsi (HTTPS) dan disimpan di server dengan akses terbatas.',
  'Çocukların Gizliliği': 'Privasi Anak',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg tidak ditujukan untuk anak di bawah 13 tahun.',
  'Hakların': 'Hakmu',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Berdasarkan KVKK dan GDPR, kamu berhak mengakses, memperbaiki, menghapus, dan memindahkan datamu. Untuk itu, tulis kepada kami: {}',
  'Değişiklikler': 'Perubahan',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Jika kebijakan ini berubah, versi baru akan dipublikasikan di halaman ini dan tanggalnya diperbarui.',
  'Kayıt olarak {} kabul etmiş olursun.': 'Dengan mendaftar, kamu menerima {}.',
  'Kullanıcılar': 'Pengguna',
  'Fotoğrafı değiştir': 'Ganti foto',
  'Yeniden konumlandır': 'Atur ulang posisi',
  'Bir şeyler ters gitti': 'Ada yang salah',
  'Sosyal Bağlantılar': 'Tautan Sosial',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Maksimal 3 tautan tampil di profilmu.',
  'Platform seç': 'Pilih platform',
  'Kullanıcı adın': 'Nama penggunamu',
  'Ekle': 'Tambah',
  'Kaldır': 'Hapus',
  'Kopyalandı: {}': 'Disalin: {}',
  'Geçersiz kullanıcı adı': 'Nama pengguna tidak valid',
  'Bağlantı ekle': 'Tambah tautan',
  'Spoiler olabilir — dokun ve gör':
      'Mungkin mengandung spoiler — ketuk untuk melihat',
  'Beğeni': 'Suka',
  'beğeni': 'suka',
  'Beğen': 'Suka',
  'Görüntülenme': 'Dilihat',
  'görüntülenme': 'dilihat',
  'Tam ekran': 'Layar penuh',
  'Arama başarısız': 'Pencarian gagal',
  'Sonuç bulunamadı': 'Tidak ada hasil',
  'Dizi ve Filmler': 'Serial & Film',
  'Kişiler': 'Orang',
  'Ana Sayfa': 'Beranda',
  'Paylaş': 'Bagikan',
  'Yanıtlar': 'Balasan',
  'Yaklaşan Bölümler': 'Episode Mendatang',
  'Yetişme Listesi': 'Daftar Kejar Tayang',
  'Şunu mu demek istedin': 'Mungkin maksud Anda',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — ketuk untuk lihat',
  'uyum': 'kecocokan',
  'Uyum': 'Kecocokan',
  '{} ortak dizi': '{} serial yang sama',
  '{} ortak film': '{} film yang sama',
  'Bildirim Tercihleri': 'Preferensi notifikasi',
  'Beğeniler': 'Suka',
  'Yeni takipçiler': 'Pengikut baru',
  'Etiketlenmeler': 'Sebutan',
  'Yeniden izledim': 'Ditonton lagi',
  '{}. kez izlendi': 'Ditonton {} kali',
  'Gönderi bulunamadı': 'Postingan tidak ditemukan',
  'Gözat': 'Jelajahi',
  'Diziler': 'Serial',
  'Filmler': 'Film',
  'Tümü': 'Semua',
  'Farklı bir tür seç.': 'Coba genre lain.',
  'Gizlilik': 'Privasi',
  'İzlediklerimi gizle': 'Sembunyikan tontonanku',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Series dan film yang kamu tonton tidak akan tampil di profilmu',
  'Yorumlarımı gizle': 'Sembunyikan komentarku',
  'Profilinde yorumların görünmez': 'Komentarmu tidak akan tampil di profilmu',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Kamu bisa menyembunyikan satu series atau film lewat chip "Sembunyikan di profilku" di halamannya.',
  'Geri Bildirim': 'Masukan',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Tulis pendapat dan saranmu tentang aplikasi...',
  'Teşekkürler! Geri bildirimin alındı.':
      'Terima kasih! Masukanmu sudah diterima.',
  'Profilimde gizle': 'Sembunyikan di profilku',
  'Yorumları': 'Komentarnya',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Pengguna ini belum menonton apa pun.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Pengguna ini memilih menyembunyikan komentarnya.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Data: JustWatch',
  'Web Sitesi': 'Situs web',
  'Diğer uygulamalar': 'Aplikasi lain',
  'Bağlantıyı kopyala': 'Salin tautan',
  'Henüz kimseyi takip etmiyorsun.': 'Kamu belum mengikuti siapa pun.',
  'Çevir': 'Terjemahkan',
  'Çeviri şu an yapılamadı': 'Terjemahan tidak tersedia saat ini',
  'Bağlantı açılamadı': 'Tautan tidak dapat dibuka',
  'Orijinali göster': 'Lihat asli',
  'Çeviriyi göster': 'Tampilkan terjemahan',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Bulan ini belum ada episode dengan tanggal tayang yang diumumkan. Tanggal biasanya diumumkan beberapa minggu sebelumnya dan akan muncul di sini.',
  'devamı': 'selengkapnya',
  'Google ile devam et': 'Lanjutkan dengan Google',
  'Google girişi başarısız': 'Login Google gagal',
  'Veri tasarrufu': 'Hemat data',
  'Wi-Fi ağında veri tasarrufu': 'Hemat data di Wi-Fi',
  'Mobil veride veri tasarrufu': 'Hemat data di data seluler',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Saat aktif, foto tidak diunduh lebih dulu; hanya gambar yang sedang kamu lihat yang dimuat.',
  'Çocuk güvenliği': 'Keselamatan anak',
  'Türk Filmleri': 'Film Turki',
  'En Yüksek Puanlı Filmler': 'Film dengan rating tertinggi',
  'En Yüksek Puanlı Diziler': 'Serial dengan rating tertinggi',
  'En Çok İzlenen Filmler': 'Film paling banyak ditonton',
  'Popüler Diziler': 'Serial populer',
  'En Çok Kazanan Filmler': 'Film berpendapatan tertinggi',
  'Kült Filmler': 'Film kultus',
  'Yeni Filmler': 'Film baru',
  'Yorum yap': 'Komentari',
  'Henüz yorum yok': 'Belum ada komentar',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Komentar yang kamu tulis untuk serial dan film terkumpul di sini.',
  'GIF ekle': 'Tambahkan GIF',
  'İlk yorumu sen yaz': 'Jadilah yang pertama berkomentar',
  'Video altyazıları': 'Subtitle video',
  'Videolarda altyazı göster': 'Tampilkan subtitle pada video',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Kalimat yang diucapkan dalam video tertulis di layar. Teksnya adalah terjemahan: Bahasa Inggris dalam pidato Turki, bahasa Turki dalam bahasa lain.',
  'Güncelleme gerekli': 'Pembaruan diperlukan',
  'Yeni sürüm var': 'Versi baru tersedia',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'Instal versi baru dizi.jpg untuk melanjutkan.',
  'Güncelle': 'Perbarui',
  'Daha sonra': 'Nanti',
  'Takvim güncelleniyor': 'Memperbarui kalender',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'Kalender tidak dapat diperbarui, daftar lama ditampilkan',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'Beberapa serial gagal dimuat, daftar mungkin tidak lengkap',
  'Yenile': 'Segarkan',
  'Devam etmek için giriş yap': 'Masuk untuk melanjutkan',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'Akun gratis sudah cukup untuk memberi nilai, berkomentar, dan membangun pustakamu.',
  'Şimdi değil': 'Nanti saja',
  'Yorum yazmak için giriş yap': 'Masuk untuk menulis komentar',
  'Kişilere göndermek için giriş yap': 'Masuk untuk mengirim ke orang lain',
  'Beğenenler': 'Yang menyukai',
  'Henüz beğeni yok': 'Belum ada yang menyukai',
  'Bu gönderiyi ilk beğenen sen ol':
      'Jadilah yang pertama menyukai kiriman ini',
  'Bu gönderiye yanıt': 'Balasan untuk kiriman ini',
  'Spoiler içeren gönderi': 'Postingan mengandung spoiler',
  'Görsel gönderi': 'Postingan foto',
  'Bu yorumu profilimde gizle': 'Sembunyikan komentar ini di profil saya',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'Komentar tetap ada di halaman serial dan film',
  'Bu yorumu sil': 'Hapus komentar ini',
  'Yorum profilinde gizlendi': 'Komentar disembunyikan di profil kamu',
  'Geri al': 'Urungkan',
  'Yorum silinsin mi?': 'Hapus komentar ini?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'Komentar ini akan dihapus permanen dari semua tempat. Tidak dapat dibatalkan.',
  'Yorum silindi': 'Komentar dihapus',
  'Yorum profilinde tekrar görünüyor': 'Komentar terlihat lagi di profil kamu',
  'Gizlenen yorumun yok': 'Tidak ada komentar yang disembunyikan',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'Komentar yang kamu sembunyikan dengan menekan lama postingan di tab Komentar profil kamu akan terkumpul di sini.',
  'Gizlenen yorumlar': 'Komentar tersembunyi',
  'Gönderiye git': 'Buka postingan',
  'Tekrar göster': 'Tampilkan lagi',
  'Yanıtlarımı gizle': 'Sembunyikan balasan saya',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'Balasan yang kamu tulis di postingan orang lain hanya terlihat oleh kamu',
  'Profilinde gizlediğin yorumları tekrar göster':
      'Tampilkan lagi komentar yang kamu sembunyikan di profil',
  'Sıralama': 'Urutan',
  'Önerilen': 'Direkomendasikan',
  'Kronolojik': 'Kronologis',
  'Gelen mesaj istekleri': 'Permintaan pesan masuk',
  'Mesaj isteğin yok': 'Tidak ada permintaan pesan',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'Pesan dari orang yang tidak kamu ikuti muncul di sini.',
  'Çevrimiçi durumumu gizle': 'Sembunyikan status online saya',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'Orang lain tidak akan melihat status online dan terakhir dilihat kamu di pesan',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'Salah satu pengguna pertama kami. Masukannya membantu aplikasi ini menjadi seperti sekarang.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'Kamu salah satu pengguna pertama kami. Masukanmu membantu aplikasi ini menjadi seperti sekarang.',
  'İleri': 'Berikutnya',
  'Önceki': 'Sebelumnya',
  'Sonraki': 'Berikutnya',
  'Seçilen dosya okunamadı': 'File yang dipilih tidak dapat dibaca',
  'Video açılamadı': 'Video tidak dapat dibuka',
  'En fazla {} medya seçebilirsin': 'Kamu bisa memilih maksimal {} media',
  'Hiçbir medya yüklenemedi': 'Tidak ada media yang berhasil diunggah',
  'Seçimi kaldır': 'Hapus pilihan',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'Dalam satu komentar kamu bisa mengunggah total {} MB media',
  '{} dosya okunamadı': '{} berkas tidak dapat dibaca',
  '{} medya eklendi, {} yüklenemedi': '{} media ditambahkan, {} gagal',
  'Kırp': 'Pangkas',
  'Çiz': 'Gambar',
  'Metin': 'Teks',
  'Emoji': 'Emoji',
  'Yinele': 'Ulangi',
  'Daha fazla': 'Lainnya',
  'Hazırlanıyor…': 'Menyiapkan…',
  'Düzenlemeden çık?': 'Keluar dari pengeditan?',
  'Yaptığın değişiklikler kaybolacak.': 'Perubahan yang kamu buat akan hilang.',
  'Çık': 'Keluar',
  'Serbest çizim': 'Gambar bebas',
  'Ok': 'Panah',
  'Dikdörtgen': 'Persegi panjang',
  'Daire': 'Lingkaran',
  'Bulanıklaştır': 'Buramkan',
  'Pikselleştir': 'Piksel',
  'Silgi': 'Penghapus',
  'Çizgi kalınlığı': 'Ketebalan garis',
  'Saydamlık': 'Opasitas',
  'Dolgu': 'Isi',
  'Renk': 'Warna',
  'Döndür': 'Putar',
  'Yansıt': 'Balik',
  'Oran': 'Rasio',
  'Sıfırla': 'Atur ulang',
  'Serbest': 'Bebas',
  'Metin yaz...': 'Ketik teks...',
  'Hizala': 'Perataan',
  'Arka plan': 'Latar belakang',
  'Emoji ara...': 'Cari emoji...',
  'Son kullanılanlar': 'Terbaru',
  'İfadeler ve insanlar': 'Smiley dan orang',
  'Hayvanlar ve doğa': 'Hewan dan alam',
  'Yiyecek ve içecek': 'Makanan dan minuman',
  'Etkinlikler': 'Aktivitas',
  'Seyahat ve yerler': 'Perjalanan dan tempat',
  'Nesneler': 'Objek',
  'Semboller': 'Simbol',
  'Bayraklar': 'Bendera',
  'Görseli düzenle': 'Edit gambar',
  'Düzenlendi': 'Diedit',
  'Düzenlenemedi': 'Tidak dapat diedit',
  'Düzenlenen görsel çok büyük': 'Gambar yang diedit terlalu besar',
  'Videoyu düzenle': 'Edit video',
  'Sesi kapat': 'Bisukan',
  'Sesi aç': 'Bunyikan',
  'İptal ediliyor…': 'Membatalkan…',
  'Bu biraz sürebilir': 'Ini mungkin butuh waktu',
  'Video çok büyük': 'Video terlalu besar',
  'Video hazırlanamadı': 'Video tidak dapat disiapkan',
  'Başlangıç': 'Mulai',
  'Bitiş': 'Selesai',
  'En çok {} saniye seçebilirsin': 'Kamu bisa memilih maksimal {} detik',
  'Dosya en fazla {} MB olabilir': 'Berkas maksimal {} MB',
  'Medya ekle': 'Tambahkan media',
  'Seçili medya kalmadı': 'Tidak ada media yang dipilih',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'Pilih foto atau video untuk ditambahkan ke komentarmu.',
  'Medya seç': 'Pilih media',
  'Daha fazla ekle': 'Tambah lagi',
  'Medya seçilemedi': 'Media tidak dapat dipilih',
  'Favori oyuncular': 'Aktor favorit',
  'Henüz favori oyuncun yok': 'Belum ada aktor favorit',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'Buka halaman aktor dan ketuk ikon hati di kanan atas untuk menambahkannya di sini.',
  '{} yapımdan {} tanesini izledin': 'Kamu menonton {} dari {} judul',
  'izledin': 'ditonton',
  'İzlemedin': 'Belum ditonton',
  'Yapım bulunamadı': 'Tidak ada judul ditemukan',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'Orang ini tidak punya serial atau film untuk ditampilkan.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'Riwayat tontonanmu terkait akunmu; daftar ini hanya milikmu.',
  'Hesabın kalıcı olarak askıya alındı':
      'Akun kamu ditangguhkan secara permanen',
  'Hesabın geçici olarak askıya alındı': 'Akun kamu ditangguhkan sementara',
  'Hesabın askıya alındı': 'Akun kamu ditangguhkan',
  'Sebep': 'Alasan',
  'Kalan süre': 'Sisa waktu',
  'Süre dolunca hesabın kendiliğinden açılır':
      'Akun kamu terbuka otomatis saat waktunya habis',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'Selama waktu ini kamu masih bisa membaca, tetapi tidak bisa memposting, berkomentar, atau mengirim pesan.',
  'Anladım': 'Mengerti',
  'Ayrıntı': 'Detail',
  '{} dakika': '{} menit',
  'birkaç saniye': 'beberapa detik',
  'Karara itiraz et': 'Ajukan banding',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'Jelaskan kenapa hukuman ini harus dicabut',
  'İtirazını gönder': 'Kirim bandingmu',
  'İtirazın incelemede': 'Bandingmu sedang ditinjau',
  'İtirazın reddedildi': 'Bandingmu ditolak',
  'İtirazın alındı, inceleniyor':
      'Bandingmu sudah diterima dan sedang ditinjau',
  'İtiraz en az 10 karakter olmalı': 'Banding minimal 10 karakter',
  'Yükleniyor...': 'Memuat...',
  'Bu bölüme puan ver': 'Beri nilai episode ini',
  '{} kişi puanladı': '{} orang menilai',
  'Bölüm izlendi olarak işaretlendi': 'Episode ditandai sudah ditonton',
  'Sesli ara': 'Panggilan suara',
  'Görüntülü ara': 'Panggilan video',
  'Çalıyor...': 'Berdering...',
  'Bağlanıyor...': 'Menghubungkan...',
  'Cevapla': 'Jawab',
  'Reddet': 'Tolak',
  'Sessize al': 'Bisukan',
  'Hoparlör': 'Speaker',
  'Kamerayı kapat': 'Matikan kamera',
  'Kamerayı çevir': 'Balik kamera',
  'Cevap yok': 'Tidak dijawab',
  'Arama reddedildi': 'Panggilan ditolak',
  'Meşgul': 'Sibuk',
  'Bağlanılamadı': 'Tidak dapat terhubung',
  'Arama iptal edildi': 'Panggilan dibatalkan',
  'Arama geçmişi': 'Riwayat panggilan',
  'Gelen arama': 'Panggilan masuk',
  'Giden arama': 'Panggilan keluar',
  'Cevapsız arama': 'Panggilan tak terjawab',
  'Arama şu anda kullanılamıyor': 'Panggilan sedang tidak tersedia',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'Panggilan video sedang dimatikan, kamu bisa melakukan panggilan suara',
  'Bu kullanıcıyı arayamazsın': 'Kamu tidak bisa menelepon pengguna ini',
  'Aramak için karşılıklı takipleşmelisiniz':
      'Kalian harus saling mengikuti untuk menelepon',
  'Bu kullanıcı şu anda aranamıyor':
      'Pengguna ini tidak bisa ditelepon sekarang',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'Terlalu banyak panggilan tak terjawab. Coba lagi dalam {}',
  'Zaten bir aramadasın': 'Kamu sudah dalam panggilan',
  'Arama için mikrofon izni gerekiyor':
      'Izin mikrofon diperlukan untuk menelepon',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'Izin kamera dan mikrofon diperlukan untuk panggilan video',
  'Arama başlatılamadı': 'Panggilan tidak dapat dimulai',
  'Kullanıcı bulunamadı': 'Pengguna tidak ditemukan',
  'Kendini arayamazsın': 'Kamu tidak bisa menelepon dirimu sendiri',
  'Arama artık geçerli değil': 'Panggilan ini sudah tidak berlaku',
  'Bu aramanın tarafı değilsin': 'Kamu bukan bagian dari panggilan ini',
  'Arama bulunamadı': 'Panggilan tidak ditemukan',
  'Çok fazla istek, biraz bekle': 'Terlalu banyak permintaan, tunggu sebentar',
  'Bağlantı koptu': 'Koneksi terputus',
  'Arama süre sınırına ulaştı': 'Panggilan mencapai batas waktu',
  'Arama en fazla 4 saat sürebilir':
      'Panggilan dapat berlangsung maksimal 4 jam',
  'Arama sona erdi': 'Panggilan telah berakhir',
  'Sesli arama': 'Panggilan suara',
  'Görüntülü arama': 'Panggilan video',
  'Gelen aramalar': 'Panggilan masuk',
  'Sesli ve görüntülü arama bildirimleri':
      'Notifikasi panggilan suara dan video',
  '{} sa': '{} jam',
  'Sesli ve Görüntülü Aramalar': 'Panggilan Suara dan Video',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'Isi panggilan tidak pernah direkam. Audio dan video mengalir terenkripsi ujung ke ujung (DTLS-SRTP) antar perangkat; server kami tidak dapat mendekripsi, mendengarkan, atau menyimpan lalu lintas ini.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'Hanya metadata panggilan yang disimpan: dengan siapa, ke arah mana, kapan, dan berapa lama. Catatan ini dihapus otomatis setelah 90 hari.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'Jika koneksi langsung tidak dapat dibuat, audio dan video melewati server relai (TURN) dalam keadaan terenkripsi. Server relai juga tidak dapat mendekripsi atau merekam isinya.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'Mikrofon hanya digunakan selama panggilan suara atau video, dan kamera hanya selama panggilan video. Keduanya dimatikan saat panggilan berakhir.',
  'Takip ettiğin {} kişi izledi': '{} orang yang kamu ikuti sudah menontonnya',
  'Yorum yaz...': 'Tulis komentar...',
  'Sıradaki bölüm': 'Episode berikutnya',
  'Doğrulanmış testçi': 'Penguji terverifikasi',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'Notifikasi ikuti, suka, balasan, pesan, dan tag',
  'Sen': 'Kamu',
  'Aradığınız kişide sesli arama devre dışı':
      'Panggilan suara dinonaktifkan pada orang ini',
  'Aradığınız kişide görüntülü arama devre dışı':
      'Panggilan video dinonaktifkan pada orang ini',
  'Sesli aramalara izin ver': 'Izinkan panggilan suara',
  'Görüntülü aramalara izin ver': 'Izinkan panggilan video',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'Saat mati, tidak ada yang bisa menelepon suara kamu; penelepon melihat pemberitahuan',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'Saat mati, tidak ada yang bisa melakukan panggilan video ke kamu; penelepon melihat pemberitahuan',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Panggilan suara mati. Kamu bisa mengaktifkannya di Pengaturan > Privasi.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'Panggilan video mati. Kamu bisa mengaktifkannya di Pengaturan > Privasi.',
  'Sesli ve görüntülü arama': 'Panggilan suara dan video',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'Akun tamu tidak bisa menelepon. Buat akun untuk memakainya.',
  'Misafir hesaplar aranamaz': 'Akun tamu tidak bisa ditelepon',
  'Puan dağılımı': 'Distribusi rating',
  '{} yıldız': '{} bintang',
  'Yakında gelecek': 'Segera hadir',
  '{} {} yayınlandı': '{} {} sudah tayang',
  'Yeni bölüm yayınlandı': 'Episode baru sudah tayang',
  'Yeni bölümler': 'Episode baru',
  'Geri': 'Kembali',
  'Karşılamayı kapat': 'Tutup perkenalan',
  'Adım {} / {}': 'Langkah {} / {}',
  'Hadi başlayalım': 'Ayo mulai',
  'Kaydet ve devam': 'Simpan dan lanjutkan',
  '{} tanesini ekle': 'Tambahkan {} pilihan',
  'Şimdilik geç': 'Lewati dulu',
  'Doğum tarihin ne zaman?': 'Kapan tanggal lahirmu?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'Kami menanyakannya untuk menampilkan konten yang sesuai dengan usiamu dan merayakan ulang tahunmu.',
  'Gün': 'Tanggal',
  'Ay': 'Bulan',
  'Yıl': 'Tahun',
  'Doğum yılımı paylaşmak istemiyorum':
      'Aku tidak ingin membagikan tahun lahirku',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'Tanggal lahirmu tidak ditampilkan secara publik di profilmu. Hanya dipakai untuk konten yang sesuai usia dan ucapan ulang tahun.',
  'Ocak': 'Januari',
  'Şubat': 'Februari',
  'Mart': 'Maret',
  'Nisan': 'April',
  'Mayıs': 'Mei',
  'Haziran': 'Juni',
  'Temmuz': 'Juli',
  'Ağustos': 'Agustus',
  'Eylül': 'September',
  'Ekim': 'Oktober',
  'Kasım': 'November',
  'Aralık': 'Desember',
  'Verilerini yanında getir': 'Bawa datamu ke sini',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'Kalau kamu melacak tontonanmu di aplikasi lain, kamu bisa memindahkannya ke sini. Tidak perlu mulai dari nol.',
  'TV Time, Trakt ve Letterboxd': 'TV Time, Trakt, dan Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'Pilih file ZIP hasil ekspormu; tontonan, rating, dan daftarmu akan dipindahkan.',
  'Aktarılıyor...': 'Mengimpor...',
  'ZIP dosyası seç': 'Pilih file ZIP',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'Tidak perlu buru-buru: kamu juga bisa melakukannya nanti di Pengaturan > Data Saya.',
  'Hangi filmleri izledin?': 'Film apa saja yang sudah kamu tonton?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'Ini yang paling banyak ditonton. Yang kamu ketuk akan kami tambahkan ke tontonanmu.',
  'SERİ FİLMLER': 'SERI FILM',
  'Serilerden {} film eklendi': '{} film ditambahkan dari seri',
  'Film listesi yüklenemedi': 'Daftar film gagal dimuat',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'Kamu bisa melewati langkah ini dan menambahkan yang kamu mau nanti.',
  '{} film izlediklerine eklendi': '{} film ditambahkan ke tontonanmu',
  'Film serileri': 'Seri film',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'Kalau kamu sudah menonton satu seri dari awal sampai akhir, tambahkan dengan sekali ketuk.',
  'Seri bulunamadı': 'Seri tidak ditemukan',
  'Daha sonra tekrar deneyebilirsin.': 'Kamu bisa coba lagi nanti.',
  '{} film': '{} film',
  'Eklendi': 'Ditambahkan',
  'Tümünü izledim': 'Sudah nonton semua',
  'Peki ya diziler?': 'Bagaimana dengan serial?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'Tandai yang sudah kamu tonton; makin banyak yang kamu pilih, makin banyak yang mirip kami tampilkan.',
  'Dizi listesi yüklenemedi': 'Daftar serial gagal dimuat',
  'Seçtiklerine benzeyenler': 'Mirip dengan pilihanmu',
  'Her şey hazır': 'Semuanya siap',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'Lihat sekilas apa saja yang bisa kamu lakukan di dizi.jpg.',
  'Profilini tamamla': 'Lengkapi profilmu',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'Di Pengaturan kamu bisa menambahkan Bio, foto profil, dan sampul.',
  'Takvimin seni bekliyor': 'Kalender sudah menunggumu',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'Episode baru dari serial yang kamu tonton muncul di kalender, dan kami kabari lewat notifikasi.',
  'Puan ver, yorum yaz': 'Beri rating, tulis komentar',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'Beri rating episode demi episode, tulis komentar dengan tirai Spoiler, dan buat daftar.',
  'Verilerin sende kalır': 'Datamu tetap milikmu',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'Datamu hanya terikat pada akunmu dan tidak dijual. Di Pengaturan kamu bisa mengunduh semuanya atau menghapus akunmu sepenuhnya.',
  'Engellenen kullanıcılar': 'Pengguna yang diblokir',
  'Engellediğin kişileri gör, engeli kaldır':
      'Lihat orang yang kamu blokir, buka blokirnya',
  'Engellediğin kimse yok': 'Kamu belum memblokir siapa pun',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'Kamu bisa memblokir pengguna dari menu tiga titik di profilnya.',
  '@{} engellensin mi?': 'Blokir @{}?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'Kalian tidak bisa melihat postingan, komentar, dan profil satu sama lain; pesan dan panggilan juga tidak akan sampai. Ikatan mengikuti yang ada akan putus dan tidak akan kembali meskipun blokir dibuka.',
  'Bu kullanıcıyı engelledin': 'Kamu memblokir pengguna ini',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'Kamu tidak melihat postingan, komentar, dan pesan orang ini; orang ini juga tidak bisa melihat milikmu.',
  '{} yeni bir yapımda: {}': '{} tampil di produksi baru: {}',
  'Favori kişinden yeni yapım': 'Produksi baru dari orang favoritmu',
  '{} için bildirimler': 'Notifikasi untuk {}',
  'Tüm bildirimler': 'Semua notifikasi',
  'Uygulamada ve telefonda': 'Di aplikasi dan di ponsel',
  'Yalnız uygulama içi': 'Hanya di dalam aplikasi',
  'Telefon bildirimi gönderilmez': 'Notifikasi ponsel tidak dikirim',
  'Kapalı': 'Mati',
  'Bu kişi için bildirim yok': 'Tidak ada notifikasi untuk orang ini',
  'Favori kişilerin yeni yapımları': 'Produksi baru dari orang favorit',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'Saat mati, tidak ada yang bisa menelepon suara kamu; penelepon melihat pemberitahuan "dinonaktifkan"',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'Saat mati, tidak ada yang bisa melakukan panggilan video ke kamu; penelepon melihat pemberitahuan "dinonaktifkan"',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'Aktivitasku',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'Suka, komentar, dan tontonanmu dalam satu alur',
  'Henüz hareketin yok': 'Belum ada aktivitas',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'Semua yang kamu suka, komentari, dan tonton terkumpul di sini.',
  'Bu süzgeçte hareket yok': 'Tidak ada aktivitas di filter ini',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'Pilih jenis lain atau kembali ke "Semua".',
  'Hepsi': 'Semua',
  'Puan': 'Rating',
  'Tepki': 'Reaksi',
  'İzleme': 'Tontonan',
  'Durum': 'Status',
  'Liste': 'Daftar',
  'Yorum yaptın': 'Kamu berkomentar',
  'Yorumu beğendin': 'Kamu menyukai komentar',
  '{} puan verdin': 'Kamu memberi nilai {}',
  'Tepki verdin': 'Kamu bereaksi',
  'Listene ekledin': 'Kamu menambahkan ke daftar',
  'Takip etmeye başladın': 'Kamu mulai mengikuti',
  '"İzleyeceğim" işaretledin': 'Ditandai "Mau Nonton"',
  '"İzliyorum" işaretledin': 'Ditandai "Sedang Nonton"',
  '"Bitirdim" işaretledin': 'Ditandai "Selesai"',
  '"Bıraktım" işaretledin': 'Ditandai "Berhenti"',
  'Silinmiş içerik': 'Konten terhapus',
  'şimdi': 'sekarang',
  '{} g': '{} hr',
  '{} y': '{} thn',
  'İstatistiklerim': 'Statistikku',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'Dilihat dan disukai pada postinganmu',
  'Henüz gönderin yok': 'Kamu belum punya postingan',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'Begitu kamu mengomentari serial atau film, jumlah tontonan dan suka mulai terkumpul di sini.',
  'Tüm zamanlar': 'Sepanjang waktu',
  'Son {} gün': '{} hari terakhir',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'Riwayat tontonan belum mulai terkumpul; data hari pertama tampil besok.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'Riwayat tontonan terkumpul sejak {} (ada data {} hari), jadi angka {} hari masih belum lengkap.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'Riwayat suka tercatat sejak {}.',
  'Bu dönemde gösterilecek gönderi yok.':
      'Tidak ada postingan untuk ditampilkan pada periode ini.',
  'eksik veri': 'data belum lengkap',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'Series dan film yang kamu tonton, penghitung tontonan, waktu layar, dan kartu kecocokanmu tidak akan terlihat oleh orang lain di profilmu',
  'Takipçi listemi gizle': 'Sembunyikan daftar pengikut saya',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'Orang lain tidak bisa melihat siapa yang mengikutimu; jumlah pengikutmu tetap terlihat',
  'Takip ettiklerimi gizle': 'Sembunyikan siapa yang saya ikuti',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'Orang lain tidak bisa melihat siapa yang kamu ikuti; jumlah yang kamu ikuti tetap terlihat',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'Pengguna ini memilih menyembunyikan pengikutnya.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'Pengguna ini memilih menyembunyikan siapa yang diikutinya.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'Statistik postingan',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'Kamu hanya bisa melihat statistik postingan sendiri.',
  'Erişim': 'Jangkauan',
  'Görüntüleyen': 'Penonton',
  'Kaç farklı kişi gördü (son {} gün)':
      'Berapa orang berbeda yang melihat ({} hari terakhir)',
  'Paylaşım': 'Dibagikan',
  'Bu gönderiden sonra': 'Setelah postingan ini',
  'Profil ziyareti': 'Kunjungan profil',
  'Yeni takip': 'Pengikut baru',
  'İçeriğe tıklama': 'Ketukan konten',
  'Spoiler perdesini açan': 'Membuka spoiler',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'Dibagikan, kunjungan profil, pengikut, ketukan konten, rincian sumber, dan pengukuran spoiler terkumpul sejak {}; sebelumnya tidak diukur.',
  'Zamana yayılmış görüntülenme': 'Tayangan dari waktu ke waktu',
  'Görüntülenme nereden geldi': 'Dari mana tayangan berasal',
  'Kimler gördü': 'Siapa yang melihat',
  'Günlük veri henüz birikmeye başlamadı.':
      'Data harian belum mulai terkumpul.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'Grafik memerlukan data minimal dua hari. Data terkumpul sejak {}.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'Tayangan terbanyak datang pada hari ke-{} setelah diposting: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'Tayangan harian terkumpul sejak {}; sebelumnya tidak diukur.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'Rincian sumber baru mulai diukur; postingan ini belum menerima tayangan bertanda.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'Rincian pengikut/jelajah baru mulai diukur; belum ada data.',
  'Takip edenler': 'Pengikut',
  'Keşiften gelenler': 'Dari Jelajahi',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'Halaman serial/film',
  'Paylaşılan bağlantı': 'Tautan yang dibagikan',
  'yeni ölçülüyor': 'baru diukur',
  'Kendi ortalamanla aynı düzeyde': 'Setara dengan rata-ratamu',
  'Kendi ortalamanın %{} üstünde': '{}% di atas rata-ratamu',
  'Kendi ortalamanın %{} altında': '{}% di bawah rata-ratamu',
  'Etkileşim oranı': 'Tingkat interaksi',
  '(beğeni + yorum) ÷ görüntülenme': '(suka + komentar) ÷ tayangan',
  'Toplam görüntülenme': 'Total tayangan',
  '{} ile {} arasında toplam {} görüntülenme':
      'Antara {} dan {}: total {} tayangan',
  'İstatistikleri gör': 'Lihat statistik',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'Untuk statistik yang ditampilkan kepada pemilik postingan, disimpan sebagai penghitung agregat: berapa kali dan dari permukaan mana (feed, profil, feed layar penuh, halaman serial/film, tautan yang dibagikan) postingan dilihat, apakah penonton saat itu mengikuti pemilik postingan, perpindahan dari postingan ke profil atau konten, pengikut yang terbentuk lewat postingan, pembagian, dan pembukaan tirai spoiler. Penghitung ini tidak memuat identitas pengguna, alamat IP, atau stempel waktu; siapa melakukan apa tidak dapat ditelusuri.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'Agar dapat menghitung berapa banyak orang berbeda yang melihat sebuah postingan, ringkasan berkunci yang tidak dapat dibalik untuk setiap penonton (pemadatan kriptografis yang diturunkan dari identitas pengguna atau alamat IP) disimpan selama 90 hari. Kepada pemilik postingan hanya ditampilkan angkanya; identitas penonton tidak pernah dibagikan dalam keadaan apa pun.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'Pindahkan ke “Mau Nonton”?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'Sebuah judul itu akan ditonton atau sudah ditonton. Kalau kamu lanjut, {} tanda tontonanmu di serial ini akan dihapus.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'Sebuah judul itu akan ditonton atau sudah ditonton. Kalau kamu lanjut, tanda “Sudah Nonton” kamu di film ini akan dihapus.',
  'Sil ve taşı': 'Hapus dan pindahkan',
  'Yapım Ekibi': 'Kru Produksi',
  'Yaratıcı': 'Kreator',
  'Yönetmen': 'Sutradara',
  'Senaryo': 'Penulis Naskah',
  'Yapımcı': 'Produser',
  'Yapım Firmaları': 'Rumah Produksi',
  'Yapım Firması': 'Rumah Produksi',
  'Firma bulunamadı': 'Perusahaan tidak ditemukan',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'Rumah produksi ini tidak punya judul jenis ini.',
  'Doğum günün kutlu olsun!': 'Selamat ulang tahun!',
  'İyi ki doğdun, iyi ki buradasın.':
      'Syukurlah kamu lahir, syukurlah kamu di sini.',
  'Bugün {} yaşına girdin': 'Hari ini kamu berusia {} tahun',
  'Teşekkürler': 'Terima kasih',
  'İki Adımlı Doğrulama': 'Verifikasi Dua Langkah',
  'Girişte e-postana kod gönderilir': 'Kode dikirim ke emailmu saat masuk',
  'Kod {} adresine gönderildi': 'Kode dikirim ke {}',
  '6 haneli kod': 'Kode 6 digit',
  'Doğrula': 'Verifikasi',
  'Yeniden gönder': 'Kirim ulang',
  'Vazgeç': 'Batal',
  'Yeni kod gönderildi': 'Kode baru dikirim',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'Saat masuk dengan Google, kode tidak diminta; Google melakukan verifikasinya sendiri.',
  'Kapatmak için de kod gerekir.': 'Menonaktifkannya juga butuh kode.',
  'E-postana erişemezsen hesabına giremezsin.':
      'Tanpa akses ke email, kamu tidak bisa masuk ke akunmu.',
  'İki adımlı doğrulama açıldı': 'Verifikasi dua langkah aktif',
  'İki adımlı doğrulama kapatıldı': 'Verifikasi dua langkah nonaktif',

  // --- md.24 video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': 'Seberapa jauh video ditonton',
  'Videoyu başlatanlar': 'Memulai video',
  'videonun %{} noktasına ulaştı': 'mencapai {}% video',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'Separuh penonton menonton setidaknya {}% video.',
  'Sonuna kadar izleyen: %{}': 'Menonton sampai habis: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'Kurva memerlukan minimal {} tayangan; saat ini ada {} tayangan.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'Kurva dihitung dari {} tayangan dan tidak terpengaruh rentang tanggal yang dipilih.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'Durasi tontonan diukur sejak {}; tayangan yang lebih lama tidak termasuk dalam angka ini.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} tayangan. {}% mencapai tengah video, {}% mencapai akhir.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'Level {}',
  'Sonraki seviyeye {} puan kaldı': '{} poin lagi ke level berikutnya',
  'Gönderilerin': 'Postinganmu',
  '{} gönderi': '{} postingan',
  '{} gönderi · {} görüntülenme': '{} postingan · {} tayangan',
  'önceki {} güne göre': 'dibanding {} hari sebelumnya',
  'önceki {} güne göre %{} arttı': 'dibanding {} hari sebelumnya naik {}%',
  'önceki {} güne göre %{} azaldı': 'dibanding {} hari sebelumnya turun {}%',
  'önceki {} güne göre değişmedi': 'tidak berubah dibanding {} hari sebelumnya',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'Tayangan harian: terendah {}, tertinggi {}',
  'Etkileşim oranı henüz ölçülemedi': 'Tingkat interaksi belum bisa diukur',
  'Oranlar': 'Rasio',
  'Beğenme oranı': 'Rasio suka',
  'Yorum oranı': 'Rasio komentar',
  'Paylaşma oranı': 'Rasio berbagi',
  'İçeriğe gitme oranı': 'Rasio ketukan konten',
  'Profile gitme oranı': 'Rasio kunjungan profil',
  'Ziyaretten takibe dönüşüm': 'Kunjungan jadi pengikut',
  'beğeni ÷ görüntülenme': 'suka ÷ tayangan',
  'yorum ÷ görüntülenme': 'komentar ÷ tayangan',
  'paylaşım ÷ görüntülenme': 'dibagikan ÷ tayangan',
  'içeriğe tıklama ÷ görüntülenme': 'ketukan konten ÷ tayangan',
  'profil ziyareti ÷ görüntülenme': 'kunjungan profil ÷ tayangan',
  'yeni takip ÷ profil ziyareti': 'pengikut baru ÷ kunjungan profil',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'Rasio butuh minimal {} tayangan; saat ini ada {}.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'Rasio berasal dari total sepanjang waktu postingan; pilihan hari di bawah tidak mengubahnya.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'Angka-angka ini adalah total sepanjang waktu postingan (kecuali kotak yang punya catatan sendiri); pilihan hari di bawah hanya mengubah grafik.',
  'Ortalama izlenme: videonun %{} kadarı': 'Rata-rata ditonton: {}% dari video',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'Rata-rata dari 20 bagian kurva retensi.',
  'Dizi, film, kişi veya şirket ara...':
      'Cari serial, film, orang, atau perusahaan...',
  'Şirketler': 'Perusahaan',
  'Senarist': 'Penulis naskah',
  'Bölüm puanları': 'Peringkat episode',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'Peringkat episode tidak dapat dimuat',
  'Giriş gerekli': 'Perlu masuk',
  'Geçersiz oturum': 'Sesi tidak valid',
  'Oturum sonlandı, tekrar giriş yap': 'Sesi berakhir, masuk lagi',
  'Çok fazla istek; biraz sonra tekrar dene':
      'Terlalu banyak permintaan; coba lagi sebentar',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'Email/nama pengguna atau kata sandi salah',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'Email atau nama pengguna ini sudah terdaftar',
  'Google doğrulaması başarısız': 'Verifikasi Google gagal',
  'Kod geçersiz veya süresi dolmuş': 'Kode tidak valid atau kedaluwarsa',
  'Bu kullanıcıyla mesajlaşamazsın':
      'Kamu tidak bisa mengirim pesan ke pengguna ini',
  'Kendini takip edemezsin': 'Kamu tidak bisa mengikuti dirimu sendiri',
  'Bu kullanıcıyı takip edemezsin': 'Kamu tidak bisa mengikuti pengguna ini',
  'Kendini engelleyemezsin': 'Kamu tidak bisa memblokir dirimu sendiri',
  'Yorum 1-1000 karakter olmalı': 'Komentar harus 1–1000 karakter',
  'Boş mesaj gönderilemez': 'Pesan kosong tidak bisa dikirim',
  'Yorum bulunamadı': 'Komentar tidak ditemukan',
  'Şifre hatalı': 'Kata sandi salah',
  'Şifre en az 6 karakter olmalı': 'Kata sandi minimal 6 karakter',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'Hanya GIF, PNG, JPEG, atau WebP yang bisa diunggah',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'Jenis yang didukung: GIF, PNG, JPEG, WebP, MP4, WebM, audio',
  'Geçerli bir ZIP dosyası değil': 'Bukan file ZIP yang valid',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'Untuk menerima datamu lewat email, tautkan email dulu',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'Kamu punya riwayat tonton. Untuk "Akan ditonton", hapus tandanya dulu.',
  'Arama şu anda kapalı': 'Panggilan sedang nonaktif',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'Akun tamu tidak bisa menyalakan panggilan; buat akun dulu',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'Server sedang restart, coba lagi sebentar',
  'Puan 1-10 arası olmalı': 'Nilai harus antara 1 dan 10',
  'En fazla 10 medya eklenebilir': 'Paling banyak 10 media',
  'Bu cihazdan yeni hesap açılamıyor':
      'Perangkat ini tidak bisa buat akun baru',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'Perlu email valid, nama pengguna, dan kata sandi minimal 6 karakter',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'Perlu email valid dan kata sandi minimal 6 karakter',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'Nama pengguna 3–20 karakter; huruf kecil, angka, titik, strip, garis bawah (bukan di ujung)',
  'Bu hesap zaten bağlı': 'Akun ini sudah terhubung',
  'Hesap oluşturulamadı': 'Akun tidak bisa dibuat',
  'Misafir hesabı oluşturulamadı': 'Akun tamu tidak bisa dibuat',
  'Hesap bulunamadı': 'Akun tidak ditemukan',
  'Bu hesapta e-posta yok': 'Akun ini tidak punya email',
  'İki adımlı doğrulama zaten bu durumda':
      'Verifikasi dua langkah sudah dalam keadaan ini',
  'Kod yanlış': 'Kode salah',
  'Kodun süresi doldu': 'Kode kedaluwarsa',
  'Kullanıcının e-postası yok (misafir hesap)':
      'Pengguna ini tidak punya email (akun tamu)',
  'Bio en fazla 300 karakter olabilir': 'Bio paling banyak 300 karakter',
  'Geçersiz ülke': 'Negara tidak valid',
  'Geçersiz sosyal bağlantı': 'Tautan sosial tidak valid',
  'Geçersiz doğum tarihi': 'Tanggal lahir tidak valid',
  'Liste adı gerekli': 'Nama daftar wajib',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'Nama paling banyak 60, deskripsi 300 karakter',
  'Liste bulunamadı': 'Daftar tidak ditemukan',
  'Değiştirilecek tercih yok': 'Tidak ada yang diubah',
  'İnceleme en fazla 2000 karakter olabilir':
      'Ulasan paling banyak 2000 karakter',
  'Önce içeriği "bitirdim" olarak işaretle': 'Tandai judulnya selesai dulu',
  'Önce kişiyi favorile': 'Favoritkan orangnya dulu',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'Komentar episode butuh musim dan episode sekaligus',
  'Yanıtlanan yorum bulunamadı': 'Komentar yang dibalas tidak ditemukan',
  'Geri bildirim 3-2000 karakter olmalı': 'Masukan harus 3–2000 karakter',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'Judul dan teks wajib (minimal 2 karakter)',
  'Kendine mesaj gönderemezsin': 'Tidak bisa kirim pesan ke diri sendiri',
  'Mesaj en fazla 2000 karakter olabilir': 'Pesan paling banyak 2000 karakter',
  'Mesaj 1-2000 karakter olmalı': 'Pesan harus 1–2000 karakter',
  'Mesaj bulunamadı': 'Pesan tidak ditemukan',
  'Mesaj bulunamadı veya düzenlenemez':
      'Pesan tidak ditemukan atau tidak bisa diedit',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'Hanya pesan yang dikirim ke kamu yang bisa dilaporkan',
  'Sebep gerekli': 'Alasan wajib',
  'İtiraz edilecek aktif bir ceza yok':
      'Tidak ada hukuman aktif untuk diajukan banding',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'Kamu sudah punya banding yang menunggu tinjauan',
  'Bu ceza için itirazın zaten incelendi': 'Banding hukuman ini sudah ditinjau',
  'Medya bağlantısının süresi dolmuş': 'Tautan media kedaluwarsa',
  'Bu medya için imzalı bağlantı gerekli':
      'Media ini butuh tautan bertanda tangan',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'Layanan panggilan sedang dimulai ulang; coba sebentar lagi',
  'Puan göstergesi': 'Keterangan rating',
};
