/// Otomatik üretilen çeviri haritası (nl).
const Map<String, String> cevirilerNl = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Geen herkende gegevens gevonden om te importeren.',
  'Arama': 'Zoeken',
  'Aramaya başla': 'Begin met zoeken',
  'Ayarlar': 'Instellingen',
  'Bağla': 'Koppelen',
  'Bio': 'Bio',
  'Bitirdim': 'Afgerond',
  'Bunları da Beğenebilirsin': 'Dit vind je misschien ook leuk',
  'Bölüm': 'Aflevering',
  'Bıraktım': 'Gestopt',
  'Dil': 'Taal',
  'Dil ara...': 'Taal zoeken...',
  'Dizi': 'Serie',
  'Dizi ve filmlerini takip et': 'Volg je series en films',
  'Dizi yorumu': 'Reactie op serie',
  'Dizi, film veya kişi ara...': 'Zoek een serie, film of persoon...',
  'Dosya en fazla 30MB olabilir': 'Bestand mag maximaal 30MB zijn',
  'Dosya en fazla {}MB olabilir': 'Bestand mag maximaal {}MB zijn',
  'E-posta': 'E-mail',
  'E-posta veya kullanıcı adı': 'E-mail of gebruikersnaam',
  'En az 2 harf yaz': 'Typ minstens 2 letters',
  'Film': 'Film',
  'Film yorumu': 'Reactie op film',
  'Fotoğraf / video ekle': 'Foto / video toevoegen',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto of GIF — profielfoto en omslagfoto',
  'Giriş Yap': 'Inloggen',
  'Gönder': 'Versturen',
  'Gönderildi': 'Verstuurd',
  'Haftanın Dizileri': 'Series van de week',
  'Haftanın Filmleri': 'Films van de week',
  'Henüz izleme kaydın yok': 'Je hebt nog geen kijkgeschiedenis',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Je hebt nog geen lijsten — maak er een aan via het tabblad Profiel.',
  'Henüz yorum yok.': 'Nog geen reacties.',
  'Hesabın bağlandı!': 'Je account is gekoppeld!',
  'Hesabın yok mu? Kayıt ol': 'Nog geen account? Registreren',
  'Hesabını Bağla': 'Account koppelen',
  'Hesap Oluştur': 'Account aanmaken',
  'Kapak resmi ekle': 'Omslagfoto toevoegen',
  'Kaydet': 'Opslaan',
  'Kendinden bahset...': 'Vertel iets over jezelf...',
  'Keşfet': 'Ontdekken',
  'Kimseyi takip etmiyor': 'Volgt niemand',
  'Kişi ara': 'Persoon zoeken',
  'Kişi yorumu': 'Reactie op persoon',
  'Konuk Oyuncular': 'Gastacteurs',
  'Kullanıcı adı (küçük harf)': 'Gebruikersnaam (kleine letters)',
  'Kullanıcı adı ara...': 'Gebruikersnaam zoeken...',
  'Liste adı': 'Lijstnaam',
  'Listeye Ekle': 'Toevoegen aan lijst',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Je gebruikt een gastaccount — koppel je e-mail en raak je gegevens niet kwijt!',
  'Misafir olarak devam et': 'Doorgaan als gast',
  'Oluştur': 'Aanmaken',
  'Oyuncular': 'Cast',
  'Profil': 'Profiel',
  'Profil kaydedildi': 'Profiel opgeslagen',
  'Puanla': 'Beoordelen',
  'Puanı Sil': 'Beoordeling verwijderen',
  'Puanın': 'Jouw beoordeling',
  'Sezonlar': 'Seizoenen',
  'Sunucu hatası ({})': 'Serverfout ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Reactie op S{}E{}',
  'Takibi Bırak': 'Ontvolgen',
  'Takip': 'Volgend',
  'Takip Edilenler': 'Volgend',
  'Takip Et': 'Volgen',
  'Takipçi': 'Volgers',
  'Takipçi yok': 'Geen volgers',
  'Takipçiler': 'Volgers',
  'Takvim': 'Kalender',
  'Tamam': 'OK',
  'Tekrar Dene': 'Opnieuw proberen',
  'Tekrar dene': 'Opnieuw proberen',
  'Toplam ekran süresi': 'Totale schermtijd',
  'Tüm Zamanların En İyileri': 'De beste aller tijden',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Exporteer al je gegevens (kijkgeschiedenis, beoordelingen, reacties, lijsten) als TV Time-compatibele ZIP of importeer een ZIP uit een andere app.',
  'Tümünü Kaldır': 'Alles verwijderen',
  'Tümünü İzledim': 'Alles gezien',
  'Türk Dizileri': 'Turkse series',
  'Veri içe aktar (.zip)': 'Gegevens importeren (.zip)',
  'Verilerim': 'Mijn gegevens',
  'Verilerimi dışa aktar (e-posta)': 'Mijn gegevens exporteren (e-mail)',
  'Verilerini dışa aktar': 'Exporteer je gegevens',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Geen aankomende afleveringen.\nZet een serie op "Ik kijk" via de seriepagina en volg nieuwe afleveringen hier.',
  'Yapımları': 'Filmografie',
  'Yeni Diziler': 'Nieuwe series',
  'Yeni Liste': 'Nieuwe lijst',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nieuwe gebruikersnaam (optioneel)',
  'Yorum': 'Reactie',
  'Yorumunu yaz...': 'Schrijf je reactie...',
  'Zaten hesabın var mı? Giriş yap': 'Heb je al een account? Inloggen',
  'ort. {}': 'gem. {}',
  'takip': 'volgend',
  'takipçi': 'volgers',
  '{} / {} bölüm': '{} / {} afleveringen',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} mnd',
  '{} bölüm izlendi': '{} afleveringen gezien',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} gün': '{} dg',
  '{} içerik': '{} titels',
  '{} içerik · otomatik': '{} titels · automatisch',
  '{} kayıt atlandı (eşleşmedi).': '{} items overgeslagen (geen match).',
  '{} saat': '{} uur',
  '{} sezon': '{} seizoenen',
  '{} yıl': '{} jaar',
  '{}. Bölüm': 'Aflevering {}',
  '{}. Sezon': 'Seizoen {}',
  'Çıkış Yap': 'Uitloggen',
  'Ülke': 'Land',
  'Ülke ara...': 'Land zoeken...',
  'Ülke seç': 'Kies een land',
  'İlk yorumu sen yaz!': 'Schrijf de eerste reactie!',
  'İncelemeler': 'Recensies',
  'İncelemen (isteğe bağlı)': 'Je recensie (optioneel)',
  'İptal': 'Annuleren',
  'İzlediklerim': 'Mijn kijkgeschiedenis',
  'İzledim': 'Gezien',
  'İzledin': 'Gezien',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Je kijkgeschiedenis en lijsten blijven bewaard; je kunt nu op elk apparaat inloggen.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Je kijkgeschiedenis, beoordelingen, reacties en lijsten worden als ZIP naar je geregistreerde e-mailadres gestuurd.',
  'İzleyeceğim': 'Wil ik zien',
  'İzliyorum': 'Ik kijk',
  'İçe aktarım tamamlandı': 'Import voltooid',
  'Şifre': 'Wachtwoord',
  '• profil bilgisi': '• profielgegevens',
  '• {} dizi durumu': '• {} seriestatussen',
  '• {} izleme kaydı': '• {} kijkregistraties',
  '• {} liste': '• {} lijsten',
  '• {} puan': '• {} beoordelingen',
  '• {} yorum': '• {} reacties',
  '{}+ yapım': '{}+ titels',
  'Yorumlar': 'Reacties',
  'Yorumlar ({})': 'Reacties ({})',
  'Yorumları ({})': 'Reacties ({})',
  'Listelerim': 'Mijn lijsten',
  'Nereden izledin?': 'Waar heb je het gekeken?',
  'Diziye git': 'Naar de serie',
  'TV / Kanal': 'TV / Zender',
  'Sinema': 'Bioscoop',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Overig',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Je feed is leeg.\nZodra er gereageerd wordt op de series en films die je kijkt, verschijnt het hier.',
  'Listeleri ({})': 'Lijsten ({})',
  'Liste boş.': 'Deze lijst is leeg.',
  'Yanıtla': 'Reageren',
  '@{} kullanıcısına yanıt veriyorsun': 'Je reageert op @{}',
  'İzlediğim Diziler ({})': 'Bekeken series ({})',
  'İzlediğim Filmler ({})': 'Bekeken films ({})',
  'Tümünü gör': 'Alles bekijken',
  'Bildirimler': 'Meldingen',
  'Henüz bildirim yok': 'Nog geen meldingen',
  '@{} yorumuna yanıt verdi': '@{} reageerde op je reactie',
  '@{} yorumunu beğendi': '@{} vond je reactie leuk',
  '@{} seni takip etti': '@{} volgt je nu',
  '@{} sana mesaj gönderdi': '@{} stuurde je een bericht',
  'Mesajlar': 'Berichten',
  'Mesaj': 'Bericht',
  'Mesajını yaz...': 'Schrijf een bericht...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Nog geen chats.\nOpen een profiel en stuur een bericht.',
  'Şifreni mi unuttun?': 'Wachtwoord vergeten?',
  'Şifreyi Sıfırla': 'Wachtwoord resetten',
  'E-postadaki kod': 'Code uit de e-mail',
  'Yeni şifre': 'Nieuw wachtwoord',
  'Sana Özel': 'Voor jou',
  '{} özetin': 'Jouw {}-overzicht',
  'Yıllık izleme istatistiklerin': 'Je jaarlijkse kijkstatistieken',
  'Rozetler': 'Badges',
  'Verdiğin puan': 'Gegeven beoordelingen',
  'Ortalama puanın': 'Je gemiddelde score',
  'En çok izlediğin diziler': 'Je meest bekeken series',
  'İlk Bölüm': 'Eerste aflevering',
  '100 Bölüm': '100 afleveringen',
  '1000 Bölüm': '1000 afleveringen',
  'İlk Film': 'Eerste film',
  '50 Film': '50 films',
  'İlk Yorum': 'Eerste reactie',
  '25 Yorum': '25 reacties',
  '10 Puan': '10 beoordelingen',
  'İlk Takipçi': 'Eerste volger',
  '10 Dizi Bitirdin': '10 series uitgekeken',
  'İzlemeyi Bıraktım': 'Gestopt met kijken',
  'İzlediği Diziler ({})': 'Bekeken series ({})',
  'İzlediği Filmler ({})': 'Bekeken films ({})',
  '500 Bölüm': '500 afleveringen',
  '5000 Bölüm': '5000 afleveringen',
  '10 Film': '10 films',
  '100 Film': '100 films',
  '100 Yorum': '100 reacties',
  '50 Puan': '50 beoordelingen',
  '100 Puan': '100 beoordelingen',
  '10 Takipçi': '10 volgers',
  '50 Takipçi': '50 volgers',
  '25 Dizi Bitirdin': '25 series uitgekeken',
  '50 Dizi Bitirdin': '50 series uitgekeken',
  '10 Beğeni': '10 likes',
  '100 Beğeni': '100 likes',
  'yazıyor...': 'typt...',
  'Profil düzeni': 'Profielindeling',
  'Konumla ve kırp': 'Positioneren en bijsnijden',
  'Listeye eklendi': 'Toegevoegd aan lijst',
  'Listeyi sil?': 'Lijst verwijderen?',
  'Sil': 'Verwijderen',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Deze titel wordt gemarkeerd als nooit bekeken en uit je lijsten verwijderd.',
  'Gelecek bölüm bugün': 'Volgende aflevering vandaag',
  'Gelecek bölüm {} gün sonra': 'Volgende aflevering over {} dagen',
  'Tema': 'Thema',
  'Sistem': 'Systeem',
  'Koyu': 'Donker',
  'Açık': 'Licht',
  'İzleyenler': 'Kijkers',
  'Yorumunu yaz... (@ ile etiketle)': 'Schrijf je reactie... (@ om te taggen)',
  '@{} bir yorumda seni etiketledi': '@{} heeft je getagd in een reactie',
  'Mesajı sil': 'Bericht verwijderen',
  'Mesaj silinemedi': 'Bericht kon niet worden verwijderd',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Link is ongeldig of pagina niet gevonden',
  'Keşfet\'e dön': 'Terug naar Ontdekken',
};
