/// Otomatik üretilen çeviri haritası (bg).
const Map<String, String> cevirilerBg = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Не бяха намерени разпознати данни за импортиране.',
  'Arama': 'Търсене',
  'Aramaya başla': 'Започни да търсиш',
  'Son aramalar': 'Скорошни търсения',
  'Ayarlar': 'Настройки',
  'Bağla': 'Свържи',
  'Bio': 'Био',
  'Bitirdim': 'Завършено',
  'Bunları da Beğenebilirsin': 'Може да ти харесат и тези',
  'Bölüm': 'Епизод',
  'Bıraktım': 'Зарязано',
  'Dil': 'Език',
  'Dil ara...': 'Търси език...',
  'Dizi': 'Сериал',
  'Dizi ve filmlerini takip et': 'Следи сериалите и филмите си',
  'Dizi yorumu': 'Коментар за сериал',
  'Dizi, film veya kişi ara...': 'Търси сериал, филм или човек...',
  'Dosya en fazla 30MB olabilir': 'Файлът може да е най-много 30 МБ',
  'Dosya en fazla {}MB olabilir': 'Файлът може да е най-много {} МБ',
  'E-posta': 'Имейл',
  'E-posta veya kullanıcı adı': 'Имейл или потребителско име',
  'En az 2 harf yaz': 'Въведи поне 2 букви',
  'Film': 'Филм',
  'Film yorumu': 'Коментар за филм',
  'Fotoğraf / video ekle': 'Добави снимка / видео',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Снимка или GIF — аватар и корица',
  'Giriş Yap': 'Вход',
  'Gönder': 'Изпрати',
  'Gönderildi': 'Изпратено',
  'Haftanın Dizileri': 'Сериалите на седмицата',
  'Haftanın Filmleri': 'Филмите на седмицата',
  'Henüz izleme kaydın yok': 'Още нямаш история на гледане',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Още нямаш списъци — създай от раздел „Профил“.',
  'Henüz yorum yok.': 'Още няма коментари.',
  'Hesabın bağlandı!': 'Акаунтът ти е свързан!',
  'Hesabın yok mu? Kayıt ol': 'Нямаш акаунт? Регистрирай се',
  'Hesabını Bağla': 'Свържи акаунта си',
  'Hesap Oluştur': 'Създай акаунт',
  'Kapak resmi ekle': 'Добави корица',
  'Kaydet': 'Запази',
  'Kendinden bahset...': 'Разкажи за себе си...',
  'Keşfet': 'Открий',
  'Kimseyi takip etmiyor': 'Не следва никого',
  'Kişi ara': 'Търси хора',
  'Kişi yorumu': 'Коментар за човек',
  'Konuk Oyuncular': 'Гост-актьори',
  'Kullanıcı adı (küçük harf)': 'Потребителско име (малки букви)',
  'Kullanıcı adı ara...': 'Търси потребителско име...',
  'Liste adı': 'Име на списъка',
  'Listeye Ekle': 'Добави в списък',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'В гост акаунт си — свържи го с имейла си, не губи данните си!',
  'Misafir olarak devam et': 'Продължи като гост',
  'Oluştur': 'Създай',
  'Oyuncular': 'Актьори',
  'Profil': 'Профил',
  'Profil kaydedildi': 'Профилът е запазен',
  'Puanla': 'Оцени',
  'Puanı Sil': 'Изтрий оценката',
  'Puanın': 'Твоята оценка',
  'Sezonlar': 'Сезони',
  'Sunucu hatası ({})': 'Сървърна грешка ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Коментар за S{}E{}',
  'Takibi Bırak': 'Спри да следваш',
  'Takip': 'Следвани',
  'Takip Edilenler': 'Следвани',
  'Takip Et': 'Последвай',
  'Takipçi': 'Последователи',
  'Takipçi yok': 'Няма последователи',
  'Takipçiler': 'Последователи',
  'Takvim': 'Календар',
  'Tamam': 'ОК',
  'Tekrar Dene': 'Опитай пак',
  'Tekrar dene': 'Опитай отново',
  'Toplam İzleme Süresi': 'Общо екранно време',
  'Tüm Zamanların En İyileri': 'Най-добрите за всички времена',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Изтегли всичките си данни (гледания, оценки, коментари, списъци) като ZIP, съвместим с TV Time, или импортирай ZIP от друго приложение.',
  'Tümünü Kaldır': 'Премахни всички',
  'Tümünü İzledim': 'Всичко е изгледано',
  'Türk Dizileri': 'Турски сериали',
  'Veri içe aktar (.zip)': 'Импорт на данни (.zip)',
  'Verilerim': 'Моите данни',
  'Verilerimi dışa aktar (e-posta)': 'Експорт на моите данни (имейл)',
  'Verilerini dışa aktar': 'Експортирай данните си',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Няма предстоящи епизоди.\nСложи на сериала статус „Гледам“ от страницата му и следи новите епизоди тук.',
  'Yapımları': 'Филмография',
  'Yeni Diziler': 'Нови сериали',
  'Yeni Liste': 'Нов списък',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Ново потребителско име (по избор)',
  'Yorum': 'Коментар',
  'Yorumunu yaz...': 'Напиши коментар...',
  'Zaten hesabın var mı? Giriş yap': 'Вече имаш акаунт? Влез',
  'ort. {}': 'ср. {}',
  'takip': 'следвани',
  'takipçi': 'последователи',
  '{} / {} bölüm': '{} / {} епизода',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} мес.',
  '{} bölüm izlendi': '{} изгледани епизода',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} мин',
  '{} gün': '{} дни',
  '{} içerik': '{} заглавия',
  '{} içerik · otomatik': '{} заглавия · автоматично',
  '{} kayıt atlandı (eşleşmedi).': '{} записа са пропуснати (няма съвпадение).',
  '{} saat': '{} часа',
  '{} sezon': '{} сезона',
  '{} yıl': '{} години',
  '{}. Bölüm': 'Епизод {}',
  '{}. Sezon': 'Сезон {}',
  'Çıkış Yap': 'Изход',
  'Ülke': 'Държава',
  'Ülke ara...': 'Търси държава...',
  'Ülke seç': 'Избери държава',
  'İlk yorumu sen yaz!': 'Напиши първия коментар!',
  'İncelemeler': 'Ревюта',
  'İncelemen (isteğe bağlı)': 'Твоето ревю (по избор)',
  'İptal': 'Отказ',
  'İzlediklerim': 'История на гледане',
  'İzledim': 'Изгледано',
  'İzledin': 'Изгледано',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Историята на гледане и списъците ти се запазват; вече можеш да влизаш от всяко устройство.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Историята на гледане, оценките, коментарите и списъците ти ще бъдат изпратени като ZIP на регистрирания ти имейл.',
  'İzleyeceğim': 'Ще гледам',
  'İzliyorum': 'Гледам',
  'İçe aktarım tamamlandı': 'Импортът е завършен',
  'Şifre': 'Парола',
  '• profil bilgisi': '• информация за профила',
  '• {} dizi durumu': '• {} статуса на сериали',
  '• {} izleme kaydı': '• {} записа на гледане',
  '• {} liste': '• {} списъка',
  '• {} puan': '• {} оценки',
  '• {} yorum': '• {} коментара',
  '{}+ yapım': '{}+ продукции',
  'Yorumlar': 'Коментари',
  'Yorumlar ({})': 'Коментари ({})',
  'Yorumları ({})': 'Коментари ({})',
  'Listelerim': 'Моите списъци',
  'Nereden izledin?': 'Къде го гледа?',
  'Diziye git': 'Към сериала',
  'TV / Kanal': 'ТВ / канал',
  'Sinema': 'Кино',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Друго',
  'Akış': 'Емисия',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Емисията ти е празна.\nКогато коментират сериалите и филмите, които гледаш, ще се появи тук.',
  'Listeleri ({})': 'Списъци ({})',
  'Liste boş.': 'Този списък е празен.',
  'Yanıtla': 'Отговори',
  '@{} kullanıcısına yanıt veriyorsun': 'Отговаряш на @{}',
  'İzlediğim Diziler ({})': 'Изгледани сериали ({})',
  'İzlediğim Filmler ({})': 'Изгледани филми ({})',
  'Tümünü gör': 'Виж всички',
  'Bildirimler': 'Известия',
  'Henüz bildirim yok': 'Още няма известия',
  '@{} yorumuna yanıt verdi': '@{} отговори на коментара ти',
  '@{} yorumunu beğendi': '@{} хареса коментара ти',
  '@{} seni takip etti': '@{} те последва',
  '@{} sana mesaj gönderdi': '@{} ти изпрати съобщение',
  'Mesajlar': 'Съобщения',
  'Mesaj': 'Съобщение',
  'Mesajını yaz...': 'Напиши съобщение...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Още няма чатове.\nОтвори профил и изпрати съобщение.',
  'Şifreni mi unuttun?': 'Забравена парола?',
  'Şifreyi Sıfırla': 'Нулиране на паролата',
  'E-postadaki kod': 'Кодът от имейла',
  'Yeni şifre': 'Нова парола',
  'Sana Özel': 'За теб',
  '{} özetin': 'Твоето обобщение за {}',
  'Yıllık izleme istatistiklerin': 'Годишна статистика',
  'Rozetler': 'Значки',
  'Verdiğin puan': 'Дадени оценки',
  'Ortalama puanın': 'Средната ти оценка',
  'En çok izlediğin diziler': 'Най-гледаните ти сериали',
  'İlk Bölüm': 'Първи епизод',
  '100 Bölüm': '100 епизода',
  '1000 Bölüm': '1000 епизода',
  'İlk Film': 'Първи филм',
  '50 Film': '50 филма',
  'İlk Yorum': 'Първи коментар',
  '25 Yorum': '25 коментара',
  '10 Puan': '10 оценки',
  'İlk Takipçi': 'Първи последовател',
  '10 Dizi Bitirdin': 'Завърши 10 сериала',
  'İzlemeyi Bıraktım': 'Спрях да гледам',
  'İzlediği Diziler ({})': 'Изгледани сериали ({})',
  'İzlediği Filmler ({})': 'Изгледани филми ({})',
  '500 Bölüm': '500 епизода',
  '5000 Bölüm': '5000 епизода',
  '10 Film': '10 филма',
  '100 Film': '100 филма',
  '100 Yorum': '100 коментара',
  '50 Puan': '50 оценки',
  '100 Puan': '100 оценки',
  '10 Takipçi': '10 последователи',
  '50 Takipçi': '50 последователи',
  '25 Dizi Bitirdin': 'Завърши 25 сериала',
  '50 Dizi Bitirdin': 'Завърши 50 сериала',
  '10 Beğeni': '10 харесвания',
  '100 Beğeni': '100 харесвания',
  'yazıyor...': 'пише...',
  'Profil düzeni': 'Подредба на профила',
  'Konumla ve kırp': 'Позиционирай и изрежи',
  'Listeye eklendi': 'Добавено в списъка',
  'Listeyi sil?': 'Изтриване на списъка?',
  'Sil': 'Изтрий',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Ще бъде отбелязано като негледано и премахнато от списъците ти.',
  'Gelecek bölüm bugün': 'Следващият епизод днес',
  'Gelecek bölüm {} gün sonra': 'Следващият епизод след {} дни',
  'Tema': 'Тема',
  'Sistem': 'Системна',
  'Koyu': 'Тъмна',
  'Açık': 'Светла',
  'İzleyenler': 'Зрители',
  'Yorumunu yaz... (@ ile etiketle)':
      'Напиши коментара си... (@ за отбелязване)',
  '@{} bir yorumda seni etiketledi': '@{} те отбеляза в коментар',
  'Mesajı sil': 'Изтрий съобщението',
  'Mesaj silinemedi': 'Съобщението не можа да бъде изтрито',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Връзката е невалидна или страницата не е намерена',
  'Keşfet\'e dön': 'Обратно към Открий',
  'Düzenle': 'Редакция',
  'Mesajı düzenle': 'Редактирай съобщението',
  'Yanıtlanıyor': 'Отговаряне',
  'düzenlendi': 'редактирано',
  'Fotoğraf': 'Снимка',
  'Video': 'Видео',
  'İçerik': 'Съдържание',
  'çevrimiçi': 'на линия',
  'son görülme {} dk önce': 'видян преди {} мин',
  'son görülme {} saat önce': 'видян преди {} ч',
  'son görülme {} gün önce': 'видян преди {} д',
  'Yorumlar yüklenemedi': 'Коментарите не можаха да се заредят',
  'Favori': 'Любимо',
  'Listeye ekle': 'Добави в списък',
  'İçerik paylaş': 'Сподели',
  'Kapat': 'Затвори',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Всичко, което отбележиш като гледано, се събира тук.',
  'Henüz sohbetin yok': 'Все още няма разговори',
  'Bir profile girip mesaj gönderebilirsin.':
      'Отвори профил и изпрати съобщение.',
  'Listeyi sil': 'Изтрий списъка',
  'Puan kaydedilemedi': 'Оценката не можа да се запази',
  'Nerede İzlenir': 'Къде да гледате',
  'Abonelik': 'Абонамент',
  'Kirala': 'Наем',
  'Satın al': 'Купуване',
  'Hoş geldin!': 'Добре дошъл!',
  'İzlemek istediğin dizi ve filmleri seç':
      'Избери сериали и филми, които искаш да гледаш',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Избраното се добавя към списъка ти „Ще гледам“',
  'Şimdilik atla': 'Пропусни засега',
  'Devam et': 'Продължи',
  '{} ekle': 'Добави {}',
  'Şikayet et': 'Докладвай',
  'Engelle': 'Блокирай',
  'Engeli kaldır': 'Разблокирай',
  'Kullanıcı engellendi': 'Потребителят е блокиран',
  'Engel kaldırıldı': 'Блокирането е премахнато',
  'Şikayet sebebi': 'Причина за доклада',
  'Spam veya yanıltıcı': 'Спам или подвеждащо',
  'Taciz veya nefret söylemi': 'Тормоз или изказвания на омраза',
  'Uygunsuz / cinsel içerik': 'Неподходящо / сексуално съдържание',
  'Şiddet veya tehlikeli içerik': 'Насилие или опасно съдържание',
  'Telif hakkı ihlali': 'Нарушение на авторски права',
  'Şikayetin alındı, teşekkürler': 'Докладът ти е получен, благодарим',
  'Hesabımı Sil': 'Изтрий акаунта ми',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Акаунтът ти и всички данни (история, оценки, коментари, списъци, съобщения) ще бъдат изтрити завинаги. Това не може да бъде отменено.',
  'Şifreni gir': 'Въведи паролата си',
  'Hesabımı kalıcı sil': 'Изтрий акаунта ми завинаги',
  'Sesli mesaj': 'Гласово съобщение',
  'Ses gönderilemedi': 'Гласовото съобщение не можа да бъде изпратено',
  'Kaydediliyor…': 'Записване…',
  'Ses oynatılamadı': 'Аудиото не можа да се възпроизведе',
  'Oynat': 'Възпроизвеждане',
  'Duraklat': 'Пауза',
  'Liste görünümü': 'Изглед списък',
  'Takvim görünümü': 'Изглед календар',
  'Önceki ay': 'Предишен месец',
  'Sonraki ay': 'Следващ месец',
  'Bu gün bölüm yok': 'Няма епизоди този ден',
  'Gizlilik Politikası': 'Политика за поверителност',
  'Son güncelleme: {}': 'Последна актуализация: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Тази политика обяснява какви данни се събират, как се използват и какви права имаш, когато използваш приложението dizi.jpg и сайта dizijpg.com.',
  'Topladığımız Veriler': 'Какви данни събираме',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Акаунт: имейл адрес, потребителско име и парола. Паролите се съхраняват като необратим хеш; гост акаунтите могат да се използват без имейл.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Профил: данните, които сам избираш да добавиш — аватар, корица, био и държава.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Използване: твоята история на гледане, оценки, коментари, списъци, реакции и любими.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Съобщения: твоите текстови, снимкови и гласови съобщения се съхраняват на нашите сървъри. Съобщенията не са криптирани от край до край; преглеждат се само при подаден сигнал, с цел модерация.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Качени файлове: снимки, GIF, видеа и гласови записи, които добавяш към профила, коментарите и съобщенията си.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Технически данни: IP адрес, приблизително местоположение (държава/град), платформа на устройството, версия на приложението и записи за грешки. Пазят се за сигурност и отстраняване на проблеми.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Известия: за push известията пазим токена на устройството ти и избрания език. Можеш да изключиш известията по всяко време от настройките на устройството.',
  'Verileri Nasıl Kullanırız': 'Как използваме данните ти',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Използваме данните ти единствено за да предоставяме услугата, да пазим акаунта ти, да изпращаме известия, да поправяме грешки и да предотвратяваме злоупотреби. Не продаваме данните ти и не ги споделяме с никого с рекламна цел.',
  'Çerezler ve Yerel Depolama': 'Бисквитки и локално хранилище',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Използваме локално хранилище само за да останеш вписан и да помним предпочитания като език и тема. Няма рекламни или проследяващи бисквитки.',
  'Üçüncü Taraf Hizmetler': 'Услуги на трети страни',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'Данните за сериали и филми идват от TMDB, информацията за стрийминг платформите — от JustWatch. Push известията се доставят чрез Google Firebase, а трафикът на сайта се защитава от Cloudflare. За тези услуги важат собствените им политики за поверителност.',
  'Saklama ve Silme': 'Съхранение и изтриване',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Данните ти се пазят, докато акаунтът ти съществува. Чрез „Изтрий акаунта ми" в настройките можеш да изтриеш акаунта завинаги; данните се изтриват веднага, а копията им в резервните копия — най-късно до 14 дни. Записите за грешки се изтриват автоматично след 30 дни.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'Можеш да експортираш данните си като ZIP от настройките; архивът се изпраща на имейл адреса ти.',
  'Güvenlik': 'Сигурност',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Данните се пренасят по криптирани връзки (HTTPS) и се съхраняват на сървъри с ограничен достъп.',
  'Çocukların Gizliliği': 'Поверителност на децата',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg не е предназначен за деца под 13 години.',
  'Hakların': 'Твоите права',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Съгласно KVKK и GDPR имаш право на достъп до данните си, коригиране, изтриване и прехвърляне. За тези въпроси ни пиши: {}',
  'Değişiklikler': 'Промени',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Ако тази политика се промени, новата версия ще бъде публикувана на тази страница и датата ще бъде обновена.',
  'Kayıt olarak {} kabul etmiş olursun.': 'С регистрацията си приемаш {}.',
  'Kullanıcılar': 'Потребители',
  'Fotoğrafı değiştir': 'Смени снимката',
  'Yeniden konumlandır': 'Прекадрирай',
  'Bir şeyler ters gitti': 'Нещо се обърка',
  'Sosyal Bağlantılar': 'Социални връзки',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'В профила се показват до 3 връзки.',
  'Platform seç': 'Избери платформа',
  'Kullanıcı adın': 'Твоето потребителско име',
  'Ekle': 'Добави',
  'Kaldır': 'Премахни',
  'Kopyalandı: {}': 'Копирано: {}',
  'Geçersiz kullanıcı adı': 'Невалидно потребителско име',
  'Bağlantı ekle': 'Добави връзка',
  'Spoiler olabilir — dokun ve gör':
      'Може да съдържа спойлери — докосни, за да видиш',
  'Beğeni': 'Харесвания',
  'Görüntülenme': 'Показвания',
  'Tam ekran': 'Цял екран',
  'Sonuç bulunamadı': 'Няма резултати',
  'Dizi ve Filmler': 'Сериали и филми',
  'Kişiler': 'Хора',
  'Ana Sayfa': 'Начало',
  'Paylaş': 'Сподели',
  'Yanıtlar': 'Отговори',
  'Yaklaşan Bölümler': 'Предстоящи епизоди',
  'Yetişme Listesi': 'Списък за наваксване',
  'Şunu mu demek istedin': 'Може би имахте предвид',
  'Spoiler': 'Спойлер',
  'Spoiler — dokun ve gör': 'Спойлер — докосни, за да видиш',
  'uyum': 'съвпадение',
  'Uyum': 'Съвпадение',
  '{} ortak dizi': '{} общи сериала',
  '{} ortak film': '{} общи филма',
  'Bildirim Tercihleri': 'Настройки за известия',
  'Beğeniler': 'Харесвания',
  'Yeni takipçiler': 'Нови последователи',
  'Etiketlenmeler': 'Споменавания',
  'Yeniden izledim': 'Гледано отново',
  '{}. kez izlendi': 'Гледано {} пъти',
  'Gönderi bulunamadı': 'Публикацията не е намерена',
  'Gözat': 'Разглеждане',
  'Diziler': 'Сериали',
  'Filmler': 'Филми',
  'Tümü': 'Всички',
  'Farklı bir tür seç.': 'Опитай друг жанр.',
  'Gizlilik': 'Поверителност',
  'İzlediklerimi gizle': 'Скрий какво гледам',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Гледаните сериали и филми няма да се виждат в профила ти',
  'Yorumlarımı gizle': 'Скрий коментарите ми',
  'Profilinde yorumların görünmez':
      'Коментарите ти няма да се виждат в профила ти',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Можеш да скриеш отделен сериал или филм с чипа „Скрий в профила ми” на неговата страница.',
  'Geri Bildirim': 'Обратна връзка',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Напиши мнението и предложенията си за приложението...',
  'Teşekkürler! Geri bildirimin alındı.': 'Благодарим! Отзивът ти е получен.',
  'Profilimde gizle': 'Скрий в профила ми',
  'Yorumları': 'Коментари',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Този потребител предпочита да пази коментарите си скрити.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Данни: JustWatch',
  'Web Sitesi': 'Уебсайт',
  'Diğer uygulamalar': 'Други приложения',
  'Bağlantıyı kopyala': 'Копирай връзката',
  'Henüz kimseyi takip etmiyorsun.': 'Още не следваш никого.',
  'Çevir': 'Преведи',
  'Orijinali göster': 'Покажи оригинала',
  'Çeviriyi göster': 'Покажи превода',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Този месец няма епизоди с обявена дата на излъчване. Датите обикновено се съобщават няколко седмици предварително и ще се появят тук.',
  'devamı': 'още',
  'Google ile devam et': 'Продължаване с Google',
  'Google girişi başarısız': 'Входът с Google не бе успешен',
  'Veri tasarrufu': 'Икономия на данни',
  'Wi-Fi ağında veri tasarrufu': 'Икономия на данни при Wi-Fi',
  'Mobil veride veri tasarrufu': 'Икономия на данни при мобилни данни',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'Когато е включено, снимките не се изтеглят предварително — зарежда се само кадърът, който гледаш.',
  'Çocuk güvenliği': 'Безопасност на децата',
  'Türk Filmleri': 'Турски филми',
  'En Yüksek Puanlı Filmler': 'Най-високо оценени филми',
  'En Yüksek Puanlı Diziler': 'Най-високо оценени сериали',
  'En Çok İzlenen Filmler': 'Най-гледани филми',
  'Popüler Diziler': 'Популярни сериали',
  'En Çok Kazanan Filmler': 'Най-касови филми',
  'Kült Filmler': 'Култови филми',
  'Yeni Filmler': 'Нови филми',
  'Yorum yap': 'Коментирай',
  'Henüz yorum yok': 'Още няма коментари',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Коментарите ти за сериали и филми се събират тук.',
};
