/// Otomatik üretilen çeviri haritası (ro).
const Map<String, String> cevirilerRo = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Nu s-au găsit date recunoscute de importat.',
  'Arama': 'Căutare',
  'Aramaya başla': 'Începe să cauți',
  'Ayarlar': 'Setări',
  'Bağla': 'Asociază',
  'Bio': 'Bio',
  'Bitirdim': 'Am terminat',
  'Bunları da Beğenebilirsin': 'S-ar putea să-ți placă și acestea',
  'Bölüm': 'Episod',
  'Bıraktım': 'Am abandonat',
  'Dil': 'Limbă',
  'Dil ara...': 'Caută o limbă...',
  'Dizi': 'Serial',
  'Dizi ve filmlerini takip et': 'Urmărește-ți serialele și filmele',
  'Dizi yorumu': 'Comentariu la serial',
  'Dizi, film veya kişi ara...': 'Caută seriale, filme sau persoane...',
  'Dosya en fazla 30MB olabilir': 'Fișierul poate avea maximum 30MB',
  'Dosya en fazla {}MB olabilir': 'Fișierul poate avea maximum {}MB',
  'E-posta': 'E-mail',
  'E-posta veya kullanıcı adı': 'E-mail sau nume de utilizator',
  'En az 2 harf yaz': 'Scrie cel puțin 2 litere',
  'Film': 'Film',
  'Film yorumu': 'Comentariu la film',
  'Fotoğraf / video ekle': 'Adaugă fotografie / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Fotografie sau GIF — poză de profil și de copertă',
  'Giriş Yap': 'Conectează-te',
  'Gönder': 'Trimite',
  'Gönderildi': 'Trimis',
  'Haftanın Dizileri': 'Serialele săptămânii',
  'Haftanın Filmleri': 'Filmele săptămânii',
  'Henüz izleme kaydın yok': 'Încă nu ai istoric de vizionare',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Încă nu ai liste — creează una din fila Profil.',
  'Henüz yorum yok.': 'Încă nu există comentarii.',
  'Hesabın bağlandı!': 'Contul tău a fost asociat!',
  'Hesabın yok mu? Kayıt ol': 'Nu ai cont? Înregistrează-te',
  'Hesabını Bağla': 'Asociază-ți contul',
  'Hesap Oluştur': 'Creează cont',
  'Kapak resmi ekle': 'Adaugă o copertă',
  'Kaydet': 'Salvează',
  'Kendinden bahset...': 'Spune ceva despre tine...',
  'Keşfet': 'Descoperă',
  'Kimseyi takip etmiyor': 'Nu urmărește pe nimeni',
  'Kişi ara': 'Caută persoane',
  'Kişi yorumu': 'Comentariu la persoană',
  'Konuk Oyuncular': 'Actori invitați',
  'Kullanıcı adı (küçük harf)': 'Nume de utilizator (litere mici)',
  'Kullanıcı adı ara...': 'Caută nume de utilizator...',
  'Liste adı': 'Numele listei',
  'Listeye Ekle': 'Adaugă în listă',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Ești pe un cont de oaspete — asociază-l cu e-mailul tău, nu-ți pierde datele!',
  'Misafir olarak devam et': 'Continuă ca oaspete',
  'Oluştur': 'Creează',
  'Oyuncular': 'Distribuție',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil salvat',
  'Puanla': 'Notează',
  'Puanı Sil': 'Șterge nota',
  'Puanın': 'Nota ta',
  'Sezonlar': 'Sezoane',
  'Sunucu hatası ({})': 'Eroare de server ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Comentariu S{}E{}',
  'Takibi Bırak': 'Nu mai urmări',
  'Takip': 'Urmăriri',
  'Takip Edilenler': 'Urmăriți',
  'Takip Et': 'Urmărește',
  'Takipçi': 'Urmăritori',
  'Takipçi yok': 'Niciun urmăritor',
  'Takipçiler': 'Urmăritori',
  'Takvim': 'Calendar',
  'Tamam': 'OK',
  'Tekrar Dene': 'Încearcă din nou',
  'Tekrar dene': 'Încearcă din nou',
  'Toplam ekran süresi': 'Timp total de vizionare',
  'Tüm Zamanların En İyileri': 'Cele mai bune din toate timpurile',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Descarcă-ți toate datele (vizionări, note, comentarii, liste) ca ZIP compatibil cu TV Time sau importă un ZIP din altă aplicație.',
  'Tümünü Kaldır': 'Elimină tot',
  'Tümünü İzledim': 'Le-am văzut pe toate',
  'Türk Dizileri': 'Seriale turcești',
  'Veri içe aktar (.zip)': 'Importă date (.zip)',
  'Verilerim': 'Datele mele',
  'Verilerimi dışa aktar (e-posta)': 'Exportă-mi datele (e-mail)',
  'Verilerini dışa aktar': 'Exportă-ți datele',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Niciun episod în curând.\nTrece serialul pe „Mă uit acum” din pagina lui de detalii și urmărește episoadele noi aici.',
  'Yapımları': 'Filmografie',
  'Yeni Diziler': 'Seriale noi',
  'Yeni Liste': 'Listă nouă',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nume de utilizator nou (opțional)',
  'Yorum': 'Comentariu',
  'Yorumunu yaz...': 'Scrie-ți comentariul...',
  'Zaten hesabın var mı? Giriş yap': 'Ai deja cont? Conectează-te',
  'ort. {}': 'med. {}',
  'takip': 'urmăriri',
  'takipçi': 'urmăritori',
  '{} / {} bölüm': '{} / {} episoade',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} luni',
  '{} bölüm izlendi': '{} episoade văzute',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} gün': '{} zile',
  '{} içerik': '{} titluri',
  '{} içerik · otomatik': '{} titluri · automat',
  '{} kayıt atlandı (eşleşmedi).': '{} înregistrări sărite (fără potrivire).',
  '{} saat': '{} ore',
  '{} sezon': '{} sezoane',
  '{} yıl': '{} ani',
  '{}. Bölüm': 'Episodul {}',
  '{}. Sezon': 'Sezonul {}',
  'Çıkış Yap': 'Deconectează-te',
  'Ülke': 'Țară',
  'Ülke ara...': 'Caută o țară...',
  'Ülke seç': 'Alege țara',
  'İlk yorumu sen yaz!': 'Scrie tu primul comentariu!',
  'İncelemeler': 'Recenzii',
  'İncelemen (isteğe bağlı)': 'Recenzia ta (opțional)',
  'İptal': 'Anulează',
  'İzlediklerim': 'Vizionările mele',
  'İzledim': 'Am văzut',
  'İzledin': 'Ai văzut',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Istoricul tău de vizionare și listele tale rămân; de acum te poți conecta de pe orice dispozitiv.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Istoricul tău de vizionare, notele, comentariile și listele tale vor fi trimise ca ZIP la adresa de e-mail înregistrată.',
  'İzleyeceğim': 'O să mă uit',
  'İzliyorum': 'Mă uit acum',
  'İçe aktarım tamamlandı': 'Import finalizat',
  'Şifre': 'Parolă',
  '• profil bilgisi': '• informații de profil',
  '• {} dizi durumu': '• {} statusuri de serial',
  '• {} izleme kaydı': '• {} vizionări',
  '• {} liste': '• {} liste',
  '• {} puan': '• {} note',
  '• {} yorum': '• {} comentarii',
  '{}+ yapım': '{}+ producții',
  'Yorumlar': 'Comentarii',
  'Yorumlar ({})': 'Comentarii ({})',
  'Yorumları ({})': 'Comentariile sale ({})',
  'Listelerim': 'Listele mele',
  'Nereden izledin?': 'Unde ai vizionat?',
  'Diziye git': 'Mergi la serial',
  'TV / Kanal': 'TV / Canal',
  'Sinema': 'Cinema',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Altele',
  'Akış': 'Feed',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Feedul tău e gol.\nCând cineva comentează serialele și filmele pe care le vezi, apare aici.',
  'Listeleri ({})': 'Listele sale ({})',
  'Liste boş.': 'Această listă este goală.',
  'Yanıtla': 'Răspunde',
  '@{} kullanıcısına yanıt veriyorsun': 'Îi răspunzi lui @{}',
  'İzlediğim Diziler ({})': 'Seriale vizionate ({})',
  'İzlediğim Filmler ({})': 'Filme vizionate ({})',
  'Tümünü gör': 'Vezi tot',
  'Bildirimler': 'Notificări',
  'Henüz bildirim yok': 'Încă nu ai notificări',
  '@{} yorumuna yanıt verdi': '@{} a răspuns la comentariul tău',
  '@{} yorumunu beğendi': '@{} a apreciat comentariul tău',
  '@{} seni takip etti': '@{} te urmărește',
  '@{} sana mesaj gönderdi': '@{} ți-a trimis un mesaj',
  'Mesajlar': 'Mesaje',
  'Mesaj': 'Mesaj',
  'Mesajını yaz...': 'Scrie un mesaj...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Încă nu ai conversații.\nDeschide un profil și trimite un mesaj.',
  'Şifreni mi unuttun?': 'Ai uitat parola?',
  'Şifreyi Sıfırla': 'Resetează parola',
  'E-postadaki kod': 'Codul din e-mail',
  'Yeni şifre': 'Parolă nouă',
  'Sana Özel': 'Pentru tine',
  '{} özetin': 'Rezumatul tău din {}',
  'Yıllık izleme istatistiklerin': 'Statisticile tale anuale',
  'Rozetler': 'Insigne',
  'Verdiğin puan': 'Note acordate',
  'Ortalama puanın': 'Nota ta medie',
  'En çok izlediğin diziler': 'Serialele tale cele mai vizionate',
  'İlk Bölüm': 'Primul episod',
  '100 Bölüm': '100 de episoade',
  '1000 Bölüm': '1000 de episoade',
  'İlk Film': 'Primul film',
  '50 Film': '50 de filme',
  'İlk Yorum': 'Primul comentariu',
  '25 Yorum': '25 de comentarii',
  '10 Puan': '10 note',
  'İlk Takipçi': 'Primul urmăritor',
  '10 Dizi Bitirdin': '10 seriale terminate',
  'İzlemeyi Bıraktım': 'Am renunțat',
  'İzlediği Diziler ({})': 'Seriale vizionate ({})',
  'İzlediği Filmler ({})': 'Filme vizionate ({})',
  '500 Bölüm': '500 de episoade',
  '5000 Bölüm': '5000 de episoade',
  '10 Film': '10 filme',
  '100 Film': '100 de filme',
  '100 Yorum': '100 de comentarii',
  '50 Puan': '50 de note',
  '100 Puan': '100 de note',
  '10 Takipçi': '10 urmăritori',
  '50 Takipçi': '50 de urmăritori',
  '25 Dizi Bitirdin': '25 de seriale terminate',
  '50 Dizi Bitirdin': '50 de seriale terminate',
  '10 Beğeni': '10 aprecieri',
  '100 Beğeni': '100 de aprecieri',
  'yazıyor...': 'scrie...',
  'Profil düzeni': 'Aspectul profilului',
  'Konumla ve kırp': 'Poziționează și decupează',
  'Listeye eklendi': 'Adăugat în listă',
  'Listeyi sil?': 'Ștergi lista?',
};
