/// Otomatik üretilen çeviri haritası (ko).
const Map<String, String> cevirilerKo = {
  'Hepsini gördün, baştan gösteriyoruz': '당신은 모든 것을 보았습니다. 우리는 처음부터 당신에게 보여줍니다',
  'Aktarılacak tanınan veri bulunamadı.': '가져올 수 있는 데이터를 찾지 못했어요.',
  'Arama': '검색',
  'Aramaya başla': '검색을 시작해 보세요',
  'Son aramalar': '최근 검색',
  'Ayarlar': '설정',
  'Bağla': '연결',
  'Bio': '소개',
  'Bitirdim': '다 봤어요',
  'Bunları da Beğenebilirsin': '이런 작품도 좋아할 거예요',
  'Bölüm': '에피소드',
  'Bıraktım': '하차했어요',
  'Dil': '언어',
  'Dil ara...': '언어 검색...',
  'Dizi': '드라마',
  'Dizi ve filmlerini takip et': '드라마와 영화를 기록해 보세요',
  'Dizi yorumu': '드라마 댓글',
  'Dizi, film veya kişi ara...': '드라마, 영화, 인물 검색...',
  'Dosya en fazla 30MB olabilir': '파일은 최대 30MB까지 가능해요',
  'Dosya en fazla {}MB olabilir': '파일은 최대 {}MB까지 가능해요',
  'E-posta': '이메일',
  'E-posta veya kullanıcı adı': '이메일 또는 사용자 이름',
  'En az 2 harf yaz': '2자 이상 입력하세요',
  'Film': '영화',
  'Film yorumu': '영화 댓글',
  'Fotoğraf / video ekle': '사진 / 동영상 추가',
  'Fotoğraf veya GIF — profil ve kapak resmi': '사진 또는 GIF — 프로필 및 커버 이미지',
  'Giriş Yap': '로그인',
  'Gönder': '보내기',
  'Gönderildi': '전송 완료',
  'Haftanın Dizileri': '이번 주 드라마',
  'Haftanın Filmleri': '이번 주 영화',
  'Henüz izleme kaydın yok': '아직 시청 기록이 없어요',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      '아직 리스트가 없어요 — 프로필 탭에서 만들어 보세요.',
  'Henüz yorum yok.': '아직 댓글이 없어요.',
  'Hesabın bağlandı!': '계정이 연결됐어요!',
  'Hesabın yok mu? Kayıt ol': '계정이 없나요? 회원가입',
  'Hesabını Bağla': '계정 연결',
  'Hesap Oluştur': '계정 만들기',
  'Kapak resmi ekle': '커버 이미지 추가',
  'Kaydet': '저장',
  'Kendinden bahset...': '자기소개를 입력해 보세요...',
  'Keşfet': '둘러보기',
  'Kimseyi takip etmiyor': '아직 아무도 팔로우하지 않아요',
  'Kişi ara': '인물 검색',
  'Kişi yorumu': '인물 댓글',
  'Konuk Oyuncular': '게스트 출연',
  'Kullanıcı adı (küçük harf)': '사용자 이름 (소문자)',
  'Kullanıcı adı ara...': '사용자 이름 검색...',
  'Liste adı': '리스트 이름',
  'Listeye Ekle': '리스트에 추가',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      '게스트 계정을 사용 중이에요 — 이메일을 연결해서 데이터를 지키세요!',
  'Misafir olarak devam et': '게스트로 계속하기',
  'Oluştur': '만들기',
  'Oyuncular': '출연진',
  'Profil': '프로필',
  'Profil kaydedildi': '프로필이 저장됐어요',
  'Puanla': '평가하기',
  'Puanı Sil': '평점 삭제',
  'Puanın': '내 평점',
  'Sezonlar': '시즌',
  'Sunucu hatası ({})': '서버 오류 ({})',
  'S{} · {}. Bölüm': 'S{} · {}화',
  'S{}B{} yorumu': 'S{}E{} 댓글',
  'Takibi Bırak': '팔로우 취소',
  'Takip': '팔로잉',
  'Takip Edilenler': '팔로잉',
  'Takip Et': '팔로우',
  'Takipçi': '팔로워',
  'Takipçi yok': '팔로워가 없어요',
  'Takipçiler': '팔로워',
  'Takvim': '캘린더',
  'Tamam': '확인',
  'Tekrar Dene': '다시 시도',
  'Tekrar dene': '다시 시도',
  'Toplam İzleme Süresi': '총 시청 시간',
  'Tüm Zamanların En İyileri': '역대 최고 작품',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      '모든 데이터(시청, 평점, 댓글, 리스트)를 TV Time 호환 ZIP으로 내보내거나, 다른 앱의 ZIP을 가져올 수 있어요.',
  'Tümünü Kaldır': '전체 해제',
  'Tümünü İzledim': '전체 시청 완료',
  'Türk Dizileri': '터키 드라마',
  'Veri içe aktar (.zip)': '데이터 가져오기 (.zip)',
  'Verilerim': '내 데이터',
  'Verilerimi dışa aktar (e-posta)': '내 데이터 내보내기 (이메일)',
  'Verilerini dışa aktar': '데이터 내보내기',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      '예정된 에피소드가 없어요.\n드라마 상세에서 "보는 중"으로 설정하면 새 에피소드를 여기서 확인할 수 있어요.',
  'Yapımları': '출연 작품',
  'Yeni Diziler': '새로운 드라마',
  'Yeni Liste': '새 리스트',
  'Yeni kullanıcı adı (isteğe bağlı)': '새 사용자 이름 (선택)',
  'Yorum': '댓글',
  'Yorumunu yaz...': '댓글을 입력하세요...',
  'Zaten hesabın var mı? Giriş yap': '이미 계정이 있나요? 로그인',
  'ort. {}': '평균 {}',
  'takip': '팔로잉',
  'takipçi': '팔로워',
  '{} / {} bölüm': '{} / {} 화',
  '{} TMDB': '{} TMDB',
  '{} ay': '{}개월',
  '{} bölüm izlendi': '{}화 시청함',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{}분',
  '{} gün': '{}일',
  '{} içerik': '{}개 작품',
  '{} içerik · otomatik': '{}개 작품 · 자동',
  '{} kayıt atlandı (eşleşmedi).': '{}개 기록을 건너뛰었어요 (일치하지 않음).',
  '{} saat': '{}시간',
  '{} sezon': '시즌 {}개',
  '{} yıl': '{}년',
  '{}. Bölüm': '{}화',
  '{}. Sezon': '시즌 {}',
  'Çıkış Yap': '로그아웃',
  'Ülke': '국가',
  'Ülke ara...': '국가 검색...',
  'Ülke seç': '국가 선택',
  'İlk yorumu sen yaz!': '첫 댓글을 남겨 보세요!',
  'İncelemeler': '리뷰',
  'İncelemen (isteğe bağlı)': '리뷰 (선택)',
  'İptal': '취소',
  'İzlediklerim': '시청 기록',
  'İzledim': '봤어요',
  'İzledin': '봤어요',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      '시청 기록과 리스트는 그대로 유지되고, 이제 어떤 기기에서든 로그인할 수 있어요.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      '시청 기록, 평점, 댓글, 리스트가 ZIP 파일로 등록된 이메일 주소로 전송돼요.',
  'İzleyeceğim': '볼래요',
  'İzliyorum': '보는 중',
  'İçe aktarım tamamlandı': '가져오기 완료',
  'Şifre': '비밀번호',
  '• profil bilgisi': '• 프로필 정보',
  '• {} dizi durumu': '• 드라마 상태 {}개',
  '• {} izleme kaydı': '• 시청 기록 {}개',
  '• {} liste': '• 리스트 {}개',
  '• {} puan': '• 평점 {}개',
  '• {} yorum': '• 댓글 {}개',
  '{}+ yapım': '{}+ 작품',
  'Yorumlar': '댓글',
  'Yorumlar ({})': '댓글 ({})',
  'Yorumları ({})': '남긴 댓글 ({})',
  'Listelerim': '내 리스트',
  'Nereden izledin?': '어디서 봤어?',
  'Diziye git': '작품으로 이동',
  'TV / Kanal': 'TV / 채널',
  'Sinema': '영화관',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': '기타',
  'Akış': '피드',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      '피드가 비어 있어요.\n내가 보는 작품에 댓글이 달리면 여기에 표시돼요.',
  'Listeleri ({})': '리스트 ({})',
  'Liste boş.': '이 리스트는 비어 있어요.',
  'Yanıtla': '답글',
  '@{} kullanıcısına yanıt veriyorsun': '@{}에게 답글 작성 중',
  'İzlediğim Diziler ({})': '시청한 시리즈 ({})',
  'İzlediğim Filmler ({})': '시청한 영화 ({})',
  'Tümünü gör': '전체 보기',
  'Bildirimler': '알림',
  'Henüz bildirim yok': '아직 알림이 없어요',
  '@{} yorumuna yanıt verdi': '@{} 님이 댓글에 답글을 달았어요',
  '@{} yorumunu beğendi': '@{} 님이 댓글을 좋아해요',
  '@{} seni takip etti': '@{} 님이 나를 팔로우했어요',
  '@{} sana mesaj gönderdi': '@{} 님이 메시지를 보냈어요',
  'Mesajlar': '메시지',
  'Mesaj': '메시지',
  'Mesajını yaz...': '메시지를 입력...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      '아직 대화가 없어요.\n프로필에서 메시지를 보내보세요.',
  'Şifreni mi unuttun?': '비밀번호를 잊으셨나요?',
  'Şifreyi Sıfırla': '비밀번호 재설정',
  'E-postadaki kod': '이메일 코드',
  'Yeni şifre': '새 비밀번호',
  'Sana Özel': '맞춤 추천',
  '{} özetin': '{}년 결산',
  'Yıllık izleme istatistiklerin': '연간 시청 통계',
  'Rozetler': '배지',
  'Verdiğin puan': '남긴 평점',
  'Ortalama puanın': '평균 평점',
  'En çok izlediğin diziler': '가장 많이 본 시리즈',
  'İlk Bölüm': '첫 에피소드',
  '100 Bölüm': '100화',
  '1000 Bölüm': '1000화',
  'İlk Film': '첫 영화',
  '50 Film': '영화 50편',
  'İlk Yorum': '첫 댓글',
  '25 Yorum': '댓글 25개',
  '10 Puan': '평점 10개',
  'İlk Takipçi': '첫 팔로워',
  '10 Dizi Bitirdin': '10개 작품 완주',
  'İzlemeyi Bıraktım': '시청 중단',
  'İzlediği Diziler ({})': '시청한 시리즈 ({})',
  'İzlediği Filmler ({})': '시청한 영화 ({})',
  '500 Bölüm': '500화',
  '5000 Bölüm': '5000화',
  '10 Film': '영화 10편',
  '100 Film': '영화 100편',
  '100 Yorum': '댓글 100개',
  '50 Puan': '평점 50개',
  '100 Puan': '평점 100개',
  '10 Takipçi': '팔로워 10명',
  '50 Takipçi': '팔로워 50명',
  '25 Dizi Bitirdin': '25개 작품 완주',
  '50 Dizi Bitirdin': '50개 작품 완주',
  '10 Beğeni': '좋아요 10개',
  '100 Beğeni': '좋아요 100개',
  'yazıyor...': '입력 중...',
  'Profil düzeni': '프로필 배치',
  'Konumla ve kırp': '위치 조정 후 자르기',
  'Listeye eklendi': '리스트에 추가됨',
  'Listeyi sil?': '리스트를 삭제할까요?',
  'Sil': '삭제',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      '이 작품은 시청한 적 없음으로 표시되고 리스트에서 제거됩니다.',
  'Gelecek bölüm bugün': '다음 에피소드 오늘',
  'Gelecek bölüm {} gün sonra': '다음 에피소드 {}일 후',
  'Tema': '테마',
  'Sistem': '시스템',
  'Koyu': '다크',
  'Açık': '라이트',
  'İzleyenler': '시청자',
  'Yorumunu yaz... (@ ile etiketle)': '댓글을 작성하세요... (@ 로 태그)',
  '@{} bir yorumda seni etiketledi': '@{} 님이 댓글에서 나를 태그했어요',
  'Mesajı sil': '메시지 삭제',
  'Mesaj silinemedi': '메시지를 삭제할 수 없어요',
  'Bağlantı geçersiz veya sayfa bulunamadı': '링크가 잘못되었거나 페이지를 찾을 수 없어요',
  'Keşfet\'e dön': '둘러보기로 돌아가기',
  'Düzenle': '편집',
  'Mesajı düzenle': '메시지 편집',
  'Yanıtlanıyor': '답장 중',
  'düzenlendi': '편집됨',
  'Fotoğraf': '사진',
  'Video': '동영상',
  'İçerik': '콘텐츠',
  'çevrimiçi': '온라인',
  'son görülme {} dk önce': '{}분 전 접속',
  'son görülme {} saat önce': '{}시간 전 접속',
  'son görülme {} gün önce': '{}일 전 접속',
  'Yorumlar yüklenemedi': '댓글을 불러오지 못했어요',
  'Favori': '즐겨찾기',
  'Listeye ekle': '목록에 추가',
  'İçerik paylaş': '콘텐츠 공유',
  'Kapat': '닫기',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      '시청함으로 표시한 드라마와 영화가 여기에 모여요.',
  'Henüz sohbetin yok': '아직 대화가 없어요',
  'Bir profile girip mesaj gönderebilirsin.': '프로필에서 메시지를 보내보세요.',
  'Listeyi sil': '목록 삭제',
  'Puan kaydedilemedi': '평점을 저장하지 못했어요',
  'Nerede İzlenir': '시청 가능한 곳',
  'Abonelik': '구독',
  'Kirala': '대여',
  'Satın al': '구매',
  'Hoş geldin!': '환영합니다!',
  'İzlemek istediğin dizi ve filmleri seç': '보고 싶은 시리즈와 영화를 선택하세요',
  'Seçtiklerin "İzleyeceğim" listene eklenir': '선택한 항목이 볼 예정 목록에 추가됩니다',
  'Şimdilik atla': '나중에 하기',
  'Devam et': '계속',
  '{} ekle': '{}개 추가',
  'Şikayet et': '신고',
  'Engelle': '차단',
  'Engeli kaldır': '차단 해제',
  'Kullanıcı engellendi': '사용자를 차단했어요',
  'Engel kaldırıldı': '차단을 해제했어요',
  'Şikayet sebebi': '신고 사유',
  'Spam veya yanıltıcı': '스팸 또는 오해의 소지',
  'Taciz veya nefret söylemi': '괴롭힘 또는 혐오 발언',
  'Uygunsuz / cinsel içerik': '부적절 / 성적인 콘텐츠',
  'Şiddet veya tehlikeli içerik': '폭력 또는 위험한 콘텐츠',
  'Telif hakkı ihlali': '저작권 침해',
  'Şikayetin alındı, teşekkürler': '신고가 접수됐어요, 고마워요',
  'Hesabımı Sil': '내 계정 삭제',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      '네 계정과 모든 데이터(시청 기록, 평점, 댓글, 목록, 메시지)가 영구 삭제돼요. 되돌릴 수 없어요.',
  'Şifreni gir': '비밀번호를 입력해',
  'Hesabımı kalıcı sil': '내 계정 영구 삭제',
  'Sesli mesaj': '음성 메시지',
  'Ses gönderilemedi': '음성 메시지를 보내지 못했어요',
  'Kaydediliyor…': '녹음 중…',
  'Ses oynatılamadı': '음성을 재생할 수 없어요',
  'Oynat': '재생',
  'Duraklat': '일시정지',
  'Liste görünümü': '목록 보기',
  'Takvim görünümü': '캘린더 보기',
  'Önceki ay': '이전 달',
  'Sonraki ay': '다음 달',
  'Bu gün bölüm yok': '이 날에는 에피소드가 없어요',
  'Gizlilik Politikası': '개인정보 처리방침',
  'Son güncelleme: {}': '마지막 업데이트: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      '이 방침은 dizi.jpg 앱과 dizijpg.com 사이트를 사용할 때 어떤 데이터가 수집되고 어떻게 사용되는지, 그리고 어떤 권리가 있는지 알려줘요.',
  'Topladığımız Veriler': '수집하는 데이터',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      '계정: 이메일 주소, 사용자 이름, 비밀번호. 비밀번호는 되돌릴 수 없는 해시 형태로 저장돼요. 게스트 계정은 이메일 없이도 쓸 수 있어요.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      '프로필: 아바타, 커버 이미지, 소개, 국가처럼 직접 추가하기로 선택한 정보.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      '이용 기록: 시청 기록, 평점, 댓글, 리스트, 리액션, 즐겨찾기.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      '메시지: 텍스트·이미지·음성 메시지는 저희 서버에 저장돼요. 메시지는 종단간 암호화되지 않으며, 신고된 경우에만 중재 목적으로 확인해요.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      '업로드한 미디어: 프로필, 댓글, 메시지에 추가한 사진, GIF, 동영상, 음성 녹음.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      '기술 데이터: IP 주소, 대략적인 위치(국가/도시 수준), 기기 플랫폼, 앱 버전, 오류 로그. 보안과 오류 해결을 위해 보관해요.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      '알림: 푸시 알림을 위해 기기 토큰과 언어 설정을 저장해요. 알림은 기기 설정에서 언제든 끌 수 있어요.',
  'Verileri Nasıl Kullanırız': '데이터를 사용하는 방법',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      '데이터는 서비스 제공, 계정 보호, 알림 전송, 오류 수정, 악용 방지를 위해서만 사용해요. 데이터를 판매하지 않고, 광고 목적으로 누구와도 공유하지 않아요.',
  'Çerezler ve Yerel Depolama': '쿠키와 로컬 저장소',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      '로컬 저장소는 로그인 상태 유지와 언어·테마 같은 설정 기억에만 사용해요. 광고용이나 추적용 쿠키는 없어요.',
  'Üçüncü Taraf Hizmetler': '제3자 서비스',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      '드라마와 영화 데이터는 TMDB에서, 스트리밍 플랫폼 정보는 JustWatch에서 가져와요. 푸시 알림은 Google Firebase를 통해 전달되고, 사이트 트래픽은 Cloudflare가 보호해요. 이 서비스들에는 각자의 개인정보 처리방침이 적용돼요.',
  'Saklama ve Silme': '보관과 삭제',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      '데이터는 계정이 있는 동안 보관돼요. 설정의 "내 계정 삭제"로 계정을 영구 삭제할 수 있어요. 데이터는 즉시, 백업 속 사본은 늦어도 14일 안에 삭제돼요. 오류 로그는 30일 후 자동으로 삭제돼요.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      '설정에서 데이터를 ZIP으로 내보낼 수 있어요. 아카이브는 이메일 주소로 전송돼요.',
  'Güvenlik': '보안',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      '데이터는 암호화된 연결(HTTPS)로 전송되고, 접근이 제한된 서버에 저장돼요.',
  'Çocukların Gizliliği': '아동의 개인정보',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg는 13세 미만 어린이를 위한 서비스가 아니에요.',
  'Hakların': '이용자의 권리',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK와 GDPR에 따라 자신의 데이터에 접근하고, 수정하고, 삭제하고, 이전할 권리가 있어요. 필요하면 여기로 연락해줘: {}',
  'Değişiklikler': '변경 사항',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      '이 방침이 바뀌면 새 버전을 이 페이지에 게시하고 날짜를 갱신해요.',
  'Kayıt olarak {} kabul etmiş olursun.': '가입하면 {}에 동의하는 거예요.',
  'Kullanıcılar': '사용자',
  'Fotoğrafı değiştir': '사진 바꾸기',
  'Yeniden konumlandır': '다시 배치',
  'Bir şeyler ters gitti': '문제가 발생했어요',
  'Sosyal Bağlantılar': '소셜 링크',
  'Profilinde en fazla 3 bağlantı gösterilir.': '프로필에는 최대 3개의 링크가 표시돼요.',
  'Platform seç': '플랫폼 선택',
  'Kullanıcı adın': '네 사용자 이름',
  'Ekle': '추가',
  'Kaldır': '제거',
  'Kopyalandı: {}': '복사됨: {}',
  'Geçersiz kullanıcı adı': '올바르지 않은 사용자 이름이에요',
  'Bağlantı ekle': '링크 추가',
  'Spoiler olabilir — dokun ve gör': '스포일러가 있을 수 있어요 — 탭해서 보기',
  'Beğeni': '좋아요',
  'Görüntülenme': '조회수',
  'Tam ekran': '전체 화면',
  'Sonuç bulunamadı': '결과가 없어요',
  'Dizi ve Filmler': '시리즈 & 영화',
  'Kişiler': '인물',
  'Ana Sayfa': '홈',
  'Paylaş': '공유',
  'Yanıtlar': '답글',
  'Yaklaşan Bölümler': '다가오는 에피소드',
  'Yetişme Listesi': '몰아보기 목록',
  'Şunu mu demek istedin': '혹시 이걸 찾으세요',
  'Spoiler': '스포일러',
  'Spoiler — dokun ve gör': '스포일러 — 눌러서 보기',
  'uyum': '일치도',
  'Uyum': '일치도',
  '{} ortak dizi': '공통 시리즈 {}개',
  '{} ortak film': '공통 영화 {}개',
  'Bildirim Tercihleri': '알림 설정',
  'Beğeniler': '좋아요',
  'Yeni takipçiler': '새 팔로워',
  'Etiketlenmeler': '멘션',
  'Yeniden izledim': '다시 봤어요',
  '{}. kez izlendi': '{}번 시청',
  'Gönderi bulunamadı': '게시물을 찾을 수 없음',
  'Gözat': '둘러보기',
  'Diziler': '시리즈',
  'Filmler': '영화',
  'Tümü': '전체',
  'Farklı bir tür seç.': '다른 장르를 시도해 보세요.',
  'Gizlilik': '프라이버시',
  'İzlediklerimi gizle': '시청 기록 숨기기',
  'Profilinde izlediğin dizi ve filmler görünmez': '시청한 시리즈와 영화가 프로필에 표시되지 않아요',
  'Yorumlarımı gizle': '내 댓글 숨기기',
  'Profilinde yorumların görünmez': '내 댓글이 프로필에 표시되지 않아요',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      '특정 시리즈나 영화는 해당 페이지의 "내 프로필에서 숨기기" 칩으로 숨길 수 있어요.',
  'Geri Bildirim': '피드백',
  'Uygulama hakkında görüş ve önerini yaz...': '앱에 대한 의견과 제안을 적어 주세요...',
  'Teşekkürler! Geri bildirimin alındı.': '고마워요! 피드백이 접수됐어요.',
  'Profilimde gizle': '내 프로필에서 숨기기',
  'Yorumları': '남긴 댓글',
  'Bu kullanıcı henüz bir şey izlememiş.': '이 사용자는 아직 아무것도 보지 않았습니다.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      '이 사용자는 댓글을 비공개로 유지하고 있어요.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': '데이터: JustWatch',
  'Web Sitesi': '웹사이트',
  'Diğer uygulamalar': '다른 앱',
  'Bağlantıyı kopyala': '링크 복사',
  'Henüz kimseyi takip etmiyorsun.': '아직 아무도 팔로우하지 않았어요.',
  'Çevir': '번역',
  'Çeviri şu an yapılamadı': '지금은 번역할 수 없습니다',
  'Bağlantı açılamadı': '링크를 열 수 없습니다',
  'Orijinali göster': '원문 보기',
  'Çeviriyi göster': '번역 보기',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      '이번 달에는 방영일이 공개된 에피소드가 없어요. 날짜는 보통 몇 주 전에 공개되며, 공개되면 여기에 표시됩니다.',
  'devamı': '더보기',
  'Google ile devam et': 'Google로 계속하기',
  'Google girişi başarısız': 'Google 로그인에 실패했어요',
  'Veri tasarrufu': '데이터 절약',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi에서 데이터 절약',
  'Mobil veride veri tasarrufu': '모바일 데이터에서 데이터 절약',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      '켜져 있으면 사진을 미리 받지 않고 지금 보는 사진만 불러와요.',
  'Çocuk güvenliği': '아동 안전',
  'Türk Filmleri': '튀르키예 영화',
  'En Yüksek Puanlı Filmler': '평점 높은 영화',
  'En Yüksek Puanlı Diziler': '평점 높은 시리즈',
  'En Çok İzlenen Filmler': '가장 많이 본 영화',
  'Popüler Diziler': '인기 시리즈',
  'En Çok Kazanan Filmler': '흥행 수익 top 영화',
  'Kült Filmler': '컬트 영화',
  'Yeni Filmler': '새 영화',
  'Yorum yap': '댓글 달기',
  'Henüz yorum yok': '아직 댓글이 없어요',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      '시리즈와 영화에 남긴 댓글이 여기에 모여요.',
  'GIF ekle': 'GIF 추가',
  'İlk yorumu sen yaz': '첫 댓글을 남겨보세요',
};
