/// Otomatik üretilen çeviri haritası (hu).
const Map<String, String> cevirilerHu = {
  'Aktarılacak tanınan veri bulunamadı.':
      'Nem található importálható, felismert adat.',
  'Arama': 'Keresés',
  'Aramaya başla': 'Kezdj el keresni',
  'Son aramalar': 'Korábbi keresések',
  'Ayarlar': 'Beállítások',
  'Bağla': 'Összekapcsolás',
  'Bio': 'Bemutatkozás',
  'Bitirdim': 'Befejeztem',
  'Bunları da Beğenebilirsin': 'Ezek is tetszhetnek',
  'Bölüm': 'Epizód',
  'Bıraktım': 'Abbahagytam',
  'Dil': 'Nyelv',
  'Dil ara...': 'Nyelv keresése...',
  'Dizi': 'Sorozat',
  'Dizi ve filmlerini takip et': 'Kövesd a sorozataidat és filmjeidet',
  'Dizi yorumu': 'Hozzászólás a sorozathoz',
  'Dizi, film veya kişi ara...': 'Sorozat, film vagy személy keresése...',
  'Dosya en fazla 30MB olabilir': 'A fájl legfeljebb 30 MB lehet',
  'Dosya en fazla {}MB olabilir': 'A fájl legfeljebb {} MB lehet',
  'E-posta': 'E-mail',
  'E-posta veya kullanıcı adı': 'E-mail vagy felhasználónév',
  'En az 2 harf yaz': 'Írj be legalább 2 betűt',
  'Film': 'Film',
  'Film yorumu': 'Hozzászólás a filmhez',
  'Fotoğraf / video ekle': 'Fotó / videó hozzáadása',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Fotó vagy GIF — profil- és borítókép',
  'Giriş Yap': 'Bejelentkezés',
  'Gönder': 'Küldés',
  'Gönderildi': 'Elküldve',
  'Haftanın Dizileri': 'A hét sorozatai',
  'Haftanın Filmleri': 'A hét filmjei',
  'Henüz izleme kaydın yok': 'Még nincs nézési előzményed',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Még nincs listád — hozz létre egyet a Profil fülön.',
  'Henüz yorum yok.': 'Még nincs hozzászólás.',
  'Hesabın bağlandı!': 'A fiókodat összekapcsoltuk!',
  'Hesabın yok mu? Kayıt ol': 'Nincs még fiókod? Regisztrálj',
  'Hesabını Bağla': 'Kapcsold össze a fiókod',
  'Hesap Oluştur': 'Fiók létrehozása',
  'Kapak resmi ekle': 'Borítókép hozzáadása',
  'Kaydet': 'Mentés',
  'Kendinden bahset...': 'Mesélj magadról...',
  'Keşfet': 'Felfedezés',
  'Kimseyi takip etmiyor': 'Nem követ senkit',
  'Kişi ara': 'Személy keresése',
  'Kişi yorumu': 'Hozzászólás a személyhez',
  'Konuk Oyuncular': 'Vendégszereplők',
  'Kullanıcı adı (küçük harf)': 'Felhasználónév (kisbetűvel)',
  'Kullanıcı adı ara...': 'Felhasználónév keresése...',
  'Liste adı': 'Lista neve',
  'Listeye Ekle': 'Hozzáadás listához',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Vendégfiókot használsz — kapcsold össze az e-mail-címeddel, ne veszítsd el az adataidat!',
  'Misafir olarak devam et': 'Folytatás vendégként',
  'Oluştur': 'Létrehozás',
  'Oyuncular': 'Szereplők',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profil mentve',
  'Puanla': 'Értékelés',
  'Puanı Sil': 'Értékelés törlése',
  'Puanın': 'Az értékelésed',
  'Sezonlar': 'Évadok',
  'Sunucu hatası ({})': 'Szerverhiba ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'S{}E{} hozzászólás',
  'Takibi Bırak': 'Követés leállítása',
  'Takip': 'Követett',
  'Takip Edilenler': 'Követettek',
  'Takip Et': 'Követés',
  'Takipçi': 'Követő',
  'Takipçi yok': 'Nincs követő',
  'Takipçiler': 'Követők',
  'Takvim': 'Naptár',
  'Tamam': 'OK',
  'Tekrar Dene': 'Próbáld újra',
  'Tekrar dene': 'Próbáld újra',
  'Toplam ekran süresi': 'Teljes képernyőidő',
  'Tüm Zamanların En İyileri': 'Minden idők legjobbjai',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Töltsd le az összes adatodat (megtekintések, értékelések, hozzászólások, listák) TV Time-kompatibilis ZIP-ként, vagy importálj ZIP-et egy másik alkalmazásból.',
  'Tümünü Kaldır': 'Összes eltávolítása',
  'Tümünü İzledim': 'Mindet láttam',
  'Türk Dizileri': 'Török sorozatok',
  'Veri içe aktar (.zip)': 'Adatok importálása (.zip)',
  'Verilerim': 'Adataim',
  'Verilerimi dışa aktar (e-posta)': 'Adataim exportálása (e-mail)',
  'Verilerini dışa aktar': 'Exportáld az adataidat',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Nincs közelgő epizód.\nÁllítsd a sorozatot a részleteknél „Most nézem” állapotba, és kövesd itt az új epizódokat.',
  'Yapımları': 'Munkái',
  'Yeni Diziler': 'Új sorozatok',
  'Yeni Liste': 'Új lista',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Új felhasználónév (nem kötelező)',
  'Yorum': 'Hozzászólás',
  'Yorumunu yaz...': 'Írd meg a hozzászólásod...',
  'Zaten hesabın var mı? Giriş yap': 'Van már fiókod? Jelentkezz be',
  'ort. {}': 'átl. {}',
  'takip': 'követett',
  'takipçi': 'követő',
  '{} / {} bölüm': '{} / {} epizód',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} hónap',
  '{} bölüm izlendi': '{} epizód megnézve',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} perc',
  '{} gün': '{} nap',
  '{} içerik': '{} tartalom',
  '{} içerik · otomatik': '{} tartalom · automatikus',
  '{} kayıt atlandı (eşleşmedi).': '{} bejegyzés kihagyva (nem volt találat).',
  '{} saat': '{} óra',
  '{} sezon': '{} évad',
  '{} yıl': '{} év',
  '{}. Bölüm': '{}. epizód',
  '{}. Sezon': '{}. évad',
  'Çıkış Yap': 'Kijelentkezés',
  'Ülke': 'Ország',
  'Ülke ara...': 'Ország keresése...',
  'Ülke seç': 'Válassz országot',
  'İlk yorumu sen yaz!': 'Írd meg az első hozzászólást!',
  'İncelemeler': 'Kritikák',
  'İncelemen (isteğe bağlı)': 'A kritikád (nem kötelező)',
  'İptal': 'Mégse',
  'İzlediklerim': 'Megnézett tartalmak',
  'İzledim': 'Láttam',
  'İzledin': 'Láttad',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'A nézési előzményeid és a listáid megmaradnak; mostantól bármelyik eszközről bejelentkezhetsz.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'A nézési előzményeidet, értékeléseidet, hozzászólásaidat és listáidat ZIP-ként elküldjük a regisztrált e-mail-címedre.',
  'İzleyeceğim': 'Megnézem majd',
  'İzliyorum': 'Most nézem',
  'İçe aktarım tamamlandı': 'Importálás kész',
  'Şifre': 'Jelszó',
  '• profil bilgisi': '• profiladatok',
  '• {} dizi durumu': '• {} sorozatállapot',
  '• {} izleme kaydı': '• {} nézési bejegyzés',
  '• {} liste': '• {} lista',
  '• {} puan': '• {} értékelés',
  '• {} yorum': '• {} hozzászólás',
  '{}+ yapım': '{}+ alkotás',
  'Yorumlar': 'Hozzászólások',
  'Yorumlar ({})': 'Hozzászólások ({})',
  'Yorumları ({})': 'Hozzászólásai ({})',
  'Listelerim': 'Listáim',
  'Nereden izledin?': 'Hol nézted?',
  'Diziye git': 'Ugrás a sorozathoz',
  'TV / Kanal': 'TV / Csatorna',
  'Sinema': 'Mozi',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Egyéb',
  'Akış': 'Hírfolyam',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'A hírfolyamod üres.\nHa kommentelnek az általad nézett sorozatokhoz és filmekhez, itt jelenik meg.',
  'Listeleri ({})': 'Listái ({})',
  'Liste boş.': 'Ez a lista üres.',
  'Yanıtla': 'Válasz',
  '@{} kullanıcısına yanıt veriyorsun': 'Válaszolsz neki: @{}',
  'İzlediğim Diziler ({})': 'Megnézett sorozatok ({})',
  'İzlediğim Filmler ({})': 'Megnézett filmek ({})',
  'Tümünü gör': 'Összes',
  'Bildirimler': 'Értesítések',
  'Henüz bildirim yok': 'Még nincs értesítés',
  '@{} yorumuna yanıt verdi': '@{} válaszolt a kommentedre',
  '@{} yorumunu beğendi': '@{} kedvelte a kommentedet',
  '@{} seni takip etti': '@{} bekövetett',
  '@{} sana mesaj gönderdi': '@{} üzenetet küldött neked',
  'Mesajlar': 'Üzenetek',
  'Mesaj': 'Üzenet',
  'Mesajını yaz...': 'Írj üzenetet...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Még nincs beszélgetés.\nNyiss meg egy profilt és küldj üzenetet.',
  'Şifreni mi unuttun?': 'Elfelejtetted a jelszavad?',
  'Şifreyi Sıfırla': 'Jelszó visszaállítása',
  'E-postadaki kod': 'Kód az e-mailből',
  'Yeni şifre': 'Új jelszó',
  'Sana Özel': 'Neked',
  '{} özetin': '{}. évi összegzésed',
  'Yıllık izleme istatistiklerin': 'Éves nézési statisztikáid',
  'Rozetler': 'Jelvények',
  'Verdiğin puan': 'Adott értékelések',
  'Ortalama puanın': 'Átlagos értékelésed',
  'En çok izlediğin diziler': 'A legtöbbet nézett sorozataid',
  'İlk Bölüm': 'Első epizód',
  '100 Bölüm': '100 epizód',
  '1000 Bölüm': '1000 epizód',
  'İlk Film': 'Első film',
  '50 Film': '50 film',
  'İlk Yorum': 'Első komment',
  '25 Yorum': '25 komment',
  '10 Puan': '10 értékelés',
  'İlk Takipçi': 'Első követő',
  '10 Dizi Bitirdin': '10 sorozat befejezve',
  'İzlemeyi Bıraktım': 'Abbahagytam',
  'İzlediği Diziler ({})': 'Megnézett sorozatai ({})',
  'İzlediği Filmler ({})': 'Megnézett filmjei ({})',
  '500 Bölüm': '500 epizód',
  '5000 Bölüm': '5000 epizód',
  '10 Film': '10 film',
  '100 Film': '100 film',
  '100 Yorum': '100 komment',
  '50 Puan': '50 értékelés',
  '100 Puan': '100 értékelés',
  '10 Takipçi': '10 követő',
  '50 Takipçi': '50 követő',
  '25 Dizi Bitirdin': '25 sorozat befejezve',
  '50 Dizi Bitirdin': '50 sorozat befejezve',
  '10 Beğeni': '10 kedvelés',
  '100 Beğeni': '100 kedvelés',
  'yazıyor...': 'gépel...',
  'Profil düzeni': 'Profil elrendezése',
  'Konumla ve kırp': 'Igazítás és kivágás',
  'Listeye eklendi': 'Hozzáadva a listához',
  'Listeyi sil?': 'Törlöd a listát?',
  'Sil': 'Törlés',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Nem megnézettként lesz megjelölve, és lekerül a listáidról.',
  'Gelecek bölüm bugün': 'Következő epizód ma',
  'Gelecek bölüm {} gün sonra': 'Következő epizód {} nap múlva',
  'Tema': 'Téma',
  'Sistem': 'Rendszer',
  'Koyu': 'Sötét',
  'Açık': 'Világos',
  'İzleyenler': 'Nézők',
  'Yorumunu yaz... (@ ile etiketle)':
      'Írd meg a hozzászólásod... (@ a jelöléshez)',
  '@{} bir yorumda seni etiketledi': '@{} megjelölt egy hozzászólásban',
  'Mesajı sil': 'Üzenet törlése',
  'Mesaj silinemedi': 'Az üzenetet nem sikerült törölni',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'A hivatkozás érvénytelen vagy az oldal nem található',
  'Keşfet\'e dön': 'Vissza a Felfedezéshez',
  'Düzenle': 'Szerkesztés',
  'Mesajı düzenle': 'Üzenet szerkesztése',
  'Yanıtlanıyor': 'Válaszol',
  'düzenlendi': 'szerkesztve',
  'Fotoğraf': 'Fotó',
  'Video': 'Videó',
  'İçerik': 'Tartalom',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': '{} perce látták',
  'son görülme {} saat önce': '{} órája látták',
  'son görülme {} gün önce': '{} napja látták',
  'Yorumlar yüklenemedi': 'A hozzászólások betöltése sikertelen',
  'Favori': 'Kedvenc',
  'Listeye ekle': 'Listához adás',
  'İçerik paylaş': 'Tartalom megosztása',
  'Kapat': 'Bezárás',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Minden, amit megnézettként jelölsz, itt gyűlik.',
  'Henüz sohbetin yok': 'Még nincsenek beszélgetések',
  'Bir profile girip mesaj gönderebilirsin.':
      'Nyiss meg egy profilt és küldj üzenetet.',
  'Listeyi sil': 'Lista törlése',
  'Puan kaydedilemedi': 'Az értékelést nem sikerült menteni',
  'Nerede İzlenir': 'Hol nézhető',
  'Abonelik': 'Előfizetés',
  'Kirala': 'Kölcsönzés',
  'Satın al': 'Vásárlás',
  'Hoş geldin!': 'Üdvözlünk!',
  'İzlemek istediğin dizi ve filmleri seç':
      'Válaszd ki a sorozatokat és filmeket, amiket meg akarsz nézni',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Választásaid a listádra kerülnek',
  'Şimdilik atla': 'Kihagyás most',
  'Devam et': 'Folytatás',
  '{} ekle': '{} hozzáadása',
  'Şikayet et': 'Jelentés',
  'Engelle': 'Letiltás',
  'Engeli kaldır': 'Letiltás feloldása',
  'Kullanıcı engellendi': 'Felhasználó letiltva',
  'Engel kaldırıldı': 'Letiltás feloldva',
  'Şikayet sebebi': 'Jelentés oka',
  'Spam veya yanıltıcı': 'Spam vagy félrevezető',
  'Taciz veya nefret söylemi': 'Zaklatás vagy gyűlöletbeszéd',
  'Uygunsuz / cinsel içerik': 'Nem megfelelő / szexuális tartalom',
  'Şiddet veya tehlikeli içerik': 'Erőszak vagy veszélyes tartalom',
  'Telif hakkı ihlali': 'Szerzői jog megsértése',
  'Şikayetin alındı, teşekkürler': 'A jelentésedet megkaptuk, köszönjük',
  'Hesabımı Sil': 'Fiókom törlése',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'A fiókod és minden adatod (előzmények, értékelések, hozzászólások, listák, üzenetek) véglegesen törlődik. Ez nem vonható vissza.',
  'Şifreni gir': 'Add meg a jelszavad',
  'Hesabımı kalıcı sil': 'Fiókom végleges törlése',
  'Sesli mesaj': 'Hangüzenet',
  'Ses gönderilemedi': 'A hangüzenetet nem sikerült elküldeni',
  'Kaydediliyor…': 'Felvétel…',
  'Ses oynatılamadı': 'A hangüzenetet nem sikerült lejátszani',
  'Oynat': 'Lejátszás',
  'Duraklat': 'Szünet',
  'Liste görünümü': 'Listanézet',
  'Takvim görünümü': 'Naptárnézet',
  'Önceki ay': 'Előző hónap',
  'Sonraki ay': 'Következő hónap',
  'Bu gün bölüm yok': 'Nincs epizód ezen a napon',
  'Gizlilik Politikası': 'Adatvédelmi Szabályzat',
  'Son güncelleme: {}': 'Utolsó frissítés: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Ez a szabályzat elmagyarázza, milyen adatokat gyűjtünk, hogyan használjuk őket, és milyen jogaid vannak, amikor a dizi.jpg alkalmazást és a dizijpg.com oldalt használod.',
  'Topladığımız Veriler': 'Milyen adatokat gyűjtünk',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Fiók: e-mail-cím, felhasználónév és jelszó. A jelszavakat visszafejthetetlen hash formában tároljuk; a vendégfiókok e-mail nélkül is használhatók.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profil: az általad megadott adatok, például avatár, borítókép, bemutatkozás és ország.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Használat: a megtekintési előzményeid, értékeléseid, hozzászólásaid, listáid, reakcióid és kedvenceid.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Üzenetek: a szöveges, képes és hangüzeneteidet a szervereinken tároljuk. Az üzenetek nem végpontok közötti titkosításúak; csak bejelentés esetén, moderálási célból tekintjük meg őket.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Feltöltött média: a profilodhoz, hozzászólásaidhoz és üzeneteidhez adott fotók, GIF-ek, videók és hangfelvételek.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Technikai: IP-cím, hozzávetőleges hely (ország/város szinten), eszközplatform, alkalmazásverzió és hibanaplók. Ezeket biztonsági és hibajavítási célból őrizzük.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Értesítések: a push értesítésekhez tároljuk az eszközöd tokenjét és a nyelvi beállításodat. Az értesítéseket bármikor kikapcsolhatod az eszköz beállításaiban.',
  'Verileri Nasıl Kullanırız': 'Hogyan használjuk az adataidat',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Az adataidat kizárólag a szolgáltatás nyújtására, a fiókod védelmére, értesítések küldésére, hibák javítására és a visszaélések megelőzésére használjuk. Az adataidat nem adjuk el, és reklámcélból senkivel sem osztjuk meg.',
  'Çerezler ve Yerel Depolama': 'Sütik és helyi tárhely',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'A helyi tárhelyet csak arra használjuk, hogy bejelentkezve maradj, és megjegyezzük a beállításaidat, például a nyelvet és a témát. Nincsenek reklám- vagy nyomkövető sütik.',
  'Üçüncü Taraf Hizmetler': 'Harmadik féltől származó szolgáltatások',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'A sorozat- és filmadatok a TMDB-től, a streamingplatform-információk a JustWatch-tól származnak. A push értesítéseket a Google Firebase kézbesíti, az oldal forgalmát a Cloudflare védi. Ezekre a szolgáltatásokra a saját adatvédelmi szabályzataik vonatkoznak.',
  'Saklama ve Silme': 'Tárolás és törlés',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Az adataidat addig tároljuk, amíg a fiókod létezik. A beállításokban a „Fiókom törlése" gombbal véglegesen törölheted a fiókodat; az adataid azonnal, a biztonsági mentésekben lévő másolataik legkésőbb 14 napon belül törlődnek. A hibanaplók 30 nap után automatikusan törlődnek.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'Az adataidat ZIP formátumban exportálhatod a beállításokból; az archívumot az e-mail-címedre küldjük.',
  'Güvenlik': 'Biztonság',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Az adatok titkosított kapcsolaton (HTTPS) keresztül utaznak, és korlátozott hozzáférésű szervereken tároljuk őket.',
  'Çocukların Gizliliği': 'Gyermekek adatvédelme',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'A dizi.jpg nem 13 év alatti gyerekeknek készült.',
  'Hakların': 'A jogaid',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'A KVKK és a GDPR alapján jogod van az adataidhoz hozzáférni, azokat helyesbíteni, törölni és áthelyezni. Ezekben az ügyekben írj nekünk: {}',
  'Değişiklikler': 'Változások',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Ha ez a szabályzat változik, az új verziót ezen az oldalon tesszük közzé, és frissítjük a dátumot.',
  'Kayıt olarak {} kabul etmiş olursun.': 'A regisztrációval elfogadod: {}.',
  'Kullanıcılar': 'Felhasználók',
  'Fotoğrafı değiştir': 'Fotó cseréje',
  'Yeniden konumlandır': 'Újrapozicionálás',
  'Bir şeyler ters gitti': 'Valami hiba történt',
  'Sosyal Bağlantılar': 'Közösségi linkek',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'A profilodon legfeljebb 3 link jelenik meg.',
  'Platform seç': 'Válassz platformot',
  'Kullanıcı adın': 'A felhasználóneved',
  'Ekle': 'Hozzáadás',
  'Kaldır': 'Eltávolítás',
  'Kopyalandı: {}': 'Másolva: {}',
  'Geçersiz kullanıcı adı': 'Érvénytelen felhasználónév',
  'Bağlantı ekle': 'Link hozzáadása',
  'Spoiler olabilir — dokun ve gör':
      'Spoilert tartalmazhat — koppints a megtekintéshez',
  'Beğeni': 'Kedvelések',
  'Görüntülenme': 'Megtekintések',
  'Tam ekran': 'Teljes képernyő',
};
