/// Otomatik üretilen çeviri haritası (fa).
const Map<String, String> cevirilerFa = {
  'Hepsini gördün, baştan gösteriyoruz':
      'شما همه چیز را دیده اید، ما از ابتدا به شما نشان می دهیم',
  'Aktarılacak tanınan veri bulunamadı.':
      'داده‌ی قابل‌شناسایی برای انتقال پیدا نشد.',
  'Arama': 'جستجو',
  'Aramaya başla': 'جستجو را شروع کن',
  'Son aramalar': 'جستجوهای اخیر',
  'Ayarlar': 'تنظیمات',
  'Bağla': 'اتصال',
  'Bio': 'بیو',
  'Bitirdim': 'تمام کردم',
  'Bunları da Beğenebilirsin': 'شاید از این‌ها هم خوشت بیاید',
  'Bölüm': 'قسمت',
  'Bıraktım': 'رها کردم',
  'Dil': 'زبان',
  'Dil ara...': 'جستجوی زبان...',
  'Dizi': 'سریال',
  'Dizi ve filmlerini takip et': 'سریال‌ها و فیلم‌هایت را دنبال کن',
  'Dizi yorumu': 'نظر درباره سریال',
  'Dizi, film veya kişi ara...': 'سریال، فیلم یا شخص جستجو کن...',
  'Dosya en fazla 30MB olabilir': 'حجم فایل حداکثر می‌تواند 30 مگابایت باشد',
  'Dosya en fazla {}MB olabilir': 'حجم فایل حداکثر می‌تواند {} مگابایت باشد',
  'E-posta': 'ایمیل',
  'E-posta veya kullanıcı adı': 'ایمیل یا نام کاربری',
  'En az 2 harf yaz': 'حداقل 2 حرف بنویس',
  'Film': 'فیلم',
  'Film yorumu': 'نظر درباره فیلم',
  'Fotoğraf / video ekle': 'افزودن عکس / ویدیو',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'عکس یا GIF — عکس پروفایل و کاور',
  'Giriş Yap': 'ورود',
  'Gönder': 'ارسال',
  'Gönderildi': 'ارسال شد',
  'Haftanın Dizileri': 'سریال‌های هفته',
  'Haftanın Filmleri': 'فیلم‌های هفته',
  'Henüz izleme kaydın yok': 'هنوز سابقه تماشا نداری',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'هنوز لیستی نداری — از تب پروفایل یکی بساز.',
  'Henüz yorum yok.': 'هنوز نظری نیست.',
  'Hesabın bağlandı!': 'حسابت متصل شد!',
  'Hesabın yok mu? Kayıt ol': 'حساب نداری؟ ثبت‌نام کن',
  'Hesabını Bağla': 'اتصال حساب',
  'Hesap Oluştur': 'ساخت حساب',
  'Kapak resmi ekle': 'افزودن عکس کاور',
  'Kaydet': 'ذخیره',
  'Kendinden bahset...': 'درباره خودت بنویس...',
  'Keşfet': 'کاوش',
  'Kimseyi takip etmiyor': 'کسی را دنبال نمی‌کند',
  'Kişi ara': 'جستجوی شخص',
  'Kişi yorumu': 'نظر درباره شخص',
  'Konuk Oyuncular': 'بازیگران مهمان',
  'Kullanıcı adı (küçük harf)': 'نام کاربری (حروف کوچک)',
  'Kullanıcı adı ara...': 'جستجوی نام کاربری...',
  'Liste adı': 'نام لیست',
  'Listeye Ekle': 'افزودن به لیست',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'در حساب مهمان هستی — با ایمیلت متصل شو تا داده‌هایت را از دست ندهی!',
  'Misafir olarak devam et': 'ادامه به‌عنوان مهمان',
  'Oluştur': 'ساختن',
  'Oyuncular': 'بازیگران',
  'Profil': 'پروفایل',
  'Profil kaydedildi': 'پروفایل ذخیره شد',
  'Puanla': 'امتیاز بده',
  'Puanı Sil': 'حذف امتیاز',
  'Puanın': 'امتیاز تو',
  'Sezonlar': 'فصل‌ها',
  'Sunucu hatası ({})': 'خطای سرور ({})',
  'S{} · {}. Bölüm': 'ف{} · قسمت {}',
  'S{}B{} yorumu': 'نظر ف{}ق{}',
  'Takibi Bırak': 'لغو دنبال کردن',
  'Takip': 'دنبال می‌کند',
  'Takip Edilenler': 'دنبال‌شده‌ها',
  'Takip Et': 'دنبال کن',
  'Takipçi': 'دنبال‌کننده',
  'Takipçi yok': 'دنبال‌کننده‌ای نیست',
  'Takipçiler': 'دنبال‌کننده‌ها',
  'Takvim': 'تقویم',
  'Tamam': 'باشه',
  'Tekrar Dene': 'دوباره تلاش کن',
  'Tekrar dene': 'دوباره تلاش کن',
  'Toplam İzleme Süresi': 'مجموع زمان تماشا',
  'Tüm Zamanların En İyileri': 'بهترین‌های تمام دوران',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP'i içe aktar.":
      'همه داده‌هایت (تماشاها، امتیازها، نظرها، لیست‌ها) را به‌صورت ZIP سازگار با TV Time بگیر یا فایل ZIP آمده از اپ دیگری را وارد کن.',
  'Tümünü Kaldır': 'حذف همه',
  'Tümünü İzledim': 'همه را دیدم',
  'Türk Dizileri': 'سریال‌های ترکی',
  'Veri içe aktar (.zip)': 'وارد کردن داده (.zip)',
  'Verilerim': 'داده‌های من',
  'Verilerimi dışa aktar (e-posta)': 'خروجی داده‌هایم (ایمیل)',
  'Verilerini dışa aktar': 'خروجی گرفتن از داده‌ها',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'قسمت جدیدی در راه نیست.\nاز صفحه سریال آن را در حالت «در حال تماشا» بگذار و قسمت‌های جدید را اینجا دنبال کن.',
  'Yapımları': 'آثار',
  'Yeni Diziler': 'سریال‌های جدید',
  'Yeni Liste': 'لیست جدید',
  'Yeni kullanıcı adı (isteğe bağlı)': 'نام کاربری جدید (اختیاری)',
  'Yorum': 'نظر',
  'Yorumunu yaz...': 'نظرت را بنویس...',
  'Zaten hesabın var mı? Giriş yap': 'قبلاً حساب ساخته‌ای؟ وارد شو',
  'ort. {}': 'میانگین {}',
  'takip': 'دنبال می‌کند',
  'takipçi': 'دنبال‌کننده',
  '{} / {} bölüm': '{} / {} قسمت',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} ماه',
  '{} ay~tekil': '{} ماه',
  '{} bölüm izlendi': '{} قسمت تماشا شد',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} دقیقه',
  '{} dk~tekil': '{} دقیقه',
  '{} gün': '{} روز',
  '{} gün~tekil': '{} روز',
  '{} içerik': '{} عنوان',
  '{} içerik · otomatik': '{} عنوان · خودکار',
  '{} kayıt atlandı (eşleşmedi).': '{} مورد رد شد (مطابقت نداشت).',
  '{} saat': '{} ساعت',
  '{} saat~tekil': '{} ساعت',
  '{} sezon': '{} فصل',
  '{} yıl': '{} سال',
  '{} yıl~tekil': '{} سال',
  '{}. Bölüm': 'قسمت {}',
  '{}. Sezon': 'فصل {}',
  'Çıkış Yap': 'خروج',
  'Ülke': 'کشور',
  'Ülke ara...': 'جستجوی کشور...',
  'Ülke seç': 'انتخاب کشور',
  'İlk yorumu sen yaz!': 'اولین نظر را تو بنویس!',
  'İncelemeler': 'نقد و بررسی‌ها',
  'İncelemen (isteğe bağlı)': 'نقد تو (اختیاری)',
  'İptal': 'لغو',
  'İzlediklerim': 'سابقه تماشا',
  'İzledim': 'دیدم',
  'İzledin': 'دیده‌ای',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'سابقه تماشا و لیست‌هایت حفظ می‌شود؛ از این به بعد می‌توانی از هر دستگاهی وارد شوی.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'سابقه تماشا، امتیازها، نظرها و لیست‌هایت به‌صورت ZIP به ایمیل ثبت‌شده‌ات ارسال خواهد شد.',
  'İzleyeceğim': 'خواهم دید',
  'İzliyorum': 'در حال تماشا',
  'İçe aktarım tamamlandı': 'وارد کردن کامل شد',
  'Şifre': 'رمز عبور',
  '• profil bilgisi': '• اطلاعات پروفایل',
  '• {} dizi durumu': '• {} وضعیت سریال',
  '• {} izleme kaydı': '• {} رکورد تماشا',
  '• {} liste': '• {} لیست',
  '• {} puan': '• {} امتیاز',
  '• {} yorum': '• {} نظر',
  '{}+ yapım': '{}+ اثر',
  'Yorumlar': 'نظرها',
  'Yorumlar ({})': 'نظرها ({})',
  'Yorumları ({})': 'نظرهایش ({})',
  'Listelerim': 'لیست‌های من',
  'Nereden izledin?': 'کجا تماشا کردی؟',
  'Diziye git': 'رفتن به سریال',
  'TV / Kanal': 'تلویزیون / کانال',
  'Sinema': 'سینما',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'سایر',
  'Akış': 'فید',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'فید تو خالی است.\nوقتی روی سریال‌ها و فیلم‌هایی که می‌بینی نظر بدهند، اینجا نمایش داده می‌شود.',
  'Listeleri ({})': 'فهرست‌های او ({})',
  'Liste boş.': 'این فهرست خالی است.',
  'Yanıtla': 'پاسخ',
  '@{} kullanıcısına yanıt veriyorsun': 'در حال پاسخ به @{}',
  'İzlediğim Diziler ({})': 'سریال‌های دیده‌شده ({})',
  'İzlediğim Filmler ({})': 'فیلم‌های دیده‌شده ({})',
  'Tümünü gör': 'مشاهده همه',
  'Bildirimler': 'اعلان‌ها',
  'Henüz bildirim yok': 'هنوز اعلانی نیست',
  '@{} yorumuna yanıt verdi': '@{} به نظرت پاسخ داد',
  '@{} yorumunu beğendi': '@{} نظرت را پسندید',
  '@{} seni takip etti': '@{} تو را دنبال کرد',
  '@{} sana mesaj gönderdi': '@{} برایت پیام فرستاد',
  'Mesajlar': 'پیام‌ها',
  'Mesaj': 'پیام',
  'Mesaja eklenecek': 'به پیام اضافه می‌شود',
  'Mesajını yaz...': 'پیام بنویس...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'هنوز گفتگویی نیست.\nیک پروفایل باز کن و پیام بفرست.',
  'Şifreni mi unuttun?': 'رمز عبور را فراموش کردی؟',
  'Şifreyi Sıfırla': 'بازنشانی رمز عبور',
  'E-postadaki kod': 'کد داخل ایمیل',
  'Yeni şifre': 'رمز عبور جدید',
  'Sana Özel': 'برای تو',
  '{} özetin': 'خلاصه {} تو',
  'Yıllık izleme istatistiklerin': 'آمار تماشای سالانه',
  'Rozetler': 'نشان‌ها',
  'Verdiğin puan': 'امتیازهای داده‌شده',
  'Ortalama puanın': 'میانگین امتیازت',
  'En çok izlediğin diziler': 'پرتماشاترین سریال‌هایت',
  'İlk Bölüm': 'اولین قسمت',
  '100 Bölüm': '۱۰۰ قسمت',
  '1000 Bölüm': '۱۰۰۰ قسمت',
  'İlk Film': 'اولین فیلم',
  '50 Film': '۵۰ فیلم',
  'İlk Yorum': 'اولین نظر',
  '25 Yorum': '۲۵ نظر',
  '10 Puan': '۱۰ امتیاز',
  'İlk Takipçi': 'اولین دنبال‌کننده',
  '10 Dizi Bitirdin': '۱۰ سریال تمام‌شده',
  'İzlemeyi Bıraktım': 'دیگر تماشا نمی‌کنم',
  'İzlediği Diziler ({})': 'سریال‌هایی که دیده ({})',
  'İzlediği Filmler ({})': 'فیلم‌هایی که دیده ({})',
  '500 Bölüm': '۵۰۰ قسمت',
  '5000 Bölüm': '۵۰۰۰ قسمت',
  '10 Film': '۱۰ فیلم',
  '100 Film': '۱۰۰ فیلم',
  '100 Yorum': '۱۰۰ نظر',
  '50 Puan': '۵۰ امتیاز',
  '100 Puan': '۱۰۰ امتیاز',
  '10 Takipçi': '۱۰ دنبال‌کننده',
  '50 Takipçi': '۵۰ دنبال‌کننده',
  '25 Dizi Bitirdin': '۲۵ سریال تمام‌شده',
  '50 Dizi Bitirdin': '۵۰ سریال تمام‌شده',
  '10 Beğeni': '۱۰ پسند',
  '100 Beğeni': '۱۰۰ پسند',
  'yazıyor...': 'در حال نوشتن...',
  'ses kaydediyor...': 'در حال ضبط صدا...',
  'Profil düzeni': 'چیدمان پروفایل',
  'Konumla ve kırp': 'جابه‌جا کن و برش بده',
  'Listeye eklendi': 'به فهرست افزوده شد',
  'Listeyi sil?': 'فهرست حذف شود؟',
  'Sil': 'حذف',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'این عنوان دیده‌نشده علامت می‌خورد و از فهرست‌هایت حذف می‌شود.',
  'Gelecek bölüm bugün': 'قسمت بعدی امروز',
  'Gelecek bölüm {} gün sonra': 'قسمت بعدی {} روز دیگر',
  'Tema': 'پوسته',
  'Sistem': 'سیستم',
  'Koyu': 'تیره',
  'Açık': 'روشن',
  'İzleyenler': 'بینندگان',
  'Yorumunu yaz... (@ ile etiketle)': 'نظرت را بنویس... (@ برای برچسب‌زدن)',
  '@{} bir yorumda seni etiketledi': '‏@{} تو را در یک نظر برچسب زد',
  'Mesajı sil': 'حذف پیام',
  'Mesaj silinemedi': 'پیام حذف نشد',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'پیوند نامعتبر است یا صفحه پیدا نشد',
  "Keşfet'e dön": 'بازگشت به کاوش',
  'Düzenle': 'ویرایش',
  'Mesajı düzenle': 'ویرایش پیام',
  'Yanıtlanıyor': 'در حال پاسخ',
  'düzenlendi': 'ویرایش‌شده',
  'Fotoğraf': 'عکس',
  'Video': 'ویدیو',
  'İçerik': 'محتوا',
  'çevrimiçi': 'آنلاین',
  'son görülme {} dk önce': 'آخرین بازدید {} دقیقه پیش',
  'son görülme {} saat önce': 'آخرین بازدید {} ساعت پیش',
  'son görülme {} gün önce': 'آخرین بازدید {} روز پیش',
  'Yorumlar yüklenemedi': 'نظرات بارگذاری نشد',
  'Favori': 'علاقه‌مندی',
  'Listeye ekle': 'افزودن به فهرست',
  'İçerik paylaş': 'اشتراک محتوا',
  'Kapat': 'بستن',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'هر چه به‌عنوان دیده‌شده علامت بزنی اینجا جمع می‌شود.',
  'Henüz sohbetin yok': 'هنوز گفتگویی نیست',
  'Bir profile girip mesaj gönderebilirsin.': 'یک نمایه باز کن و پیام بفرست.',
  'Listeyi sil': 'حذف فهرست',
  'Puan kaydedilemedi': 'ذخیره امتیاز ممکن نشد',
  'Nerede İzlenir': 'کجا ببینیم',
  'Abonelik': 'اشتراک',
  'Kirala': 'اجاره',
  'Satın al': 'خرید',
  'Devam et': 'ادامه',
  'Şikayet et': 'گزارش',
  'Engelle': 'مسدود کردن',
  'Engeli kaldır': 'رفع مسدودیت',
  'Kullanıcı engellendi': 'کاربر مسدود شد',
  'Engel kaldırıldı': 'مسدودیت برداشته شد',
  'Şikayet sebebi': 'دلیل گزارش',
  'Spam veya yanıltıcı': 'هرزنامه یا گمراه‌کننده',
  'Taciz veya nefret söylemi': 'آزار یا نفرت‌پراکنی',
  'Uygunsuz / cinsel içerik': 'محتوای نامناسب / جنسی',
  'Şiddet veya tehlikeli içerik': 'خشونت یا محتوای خطرناک',
  'Telif hakkı ihlali': 'نقض حق تکثیر',
  'Şikayetin alındı, teşekkürler': 'گزارش تو دریافت شد، ممنون',
  'Hesabımı Sil': 'حذف حساب',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'حساب تو و همه داده‌هایت (تاریخچه، امتیازها، نظرها، فهرست‌ها، پیام‌ها) برای همیشه حذف می‌شود. این کار قابل بازگشت نیست.',
  'Şifreni gir': 'رمز عبورت را وارد کن',
  'Hesabımı kalıcı sil': 'حذف همیشگی حساب',
  'Sesli mesaj': 'پیام صوتی',
  'Ses gönderilemedi': 'پیام صوتی ارسال نشد',
  'Kaydediliyor…': 'در حال ضبط…',
  'Ses oynatılamadı': 'پخش صدا ممکن نشد',
  'Oynat': 'پخش',
  'Fragmanı oynat': 'پخش تریلر',
  'Altyazıyı aç': 'روشن کردن زیرنویس',
  'Altyazıyı kapat': 'خاموش کردن زیرنویس',
  '10 saniye ileri': '۱۰ ثانیه جلو',
  '10 saniye geri': '۱۰ ثانیه عقب',
  'Duraklat': 'مکث',
  'Liste görünümü': 'نمای فهرست',
  'Takvim görünümü': 'نمای تقویم',
  'Önceki ay': 'ماه قبل',
  'Sonraki ay': 'ماه بعد',
  'Bu gün bölüm yok': 'این روز قسمتی نیست',
  'Gizlilik Politikası': 'سیاست حفظ حریم خصوصی',
  'Son güncelleme: {}': 'آخرین به‌روزرسانی: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'این سیاست توضیح می‌دهد هنگام استفاده از اپلیکیشن dizi.jpg و سایت dizijpg.com چه داده‌هایی جمع‌آوری می‌شود، چگونه استفاده می‌شود و چه حقوقی داری.',
  'Topladığımız Veriler': 'داده‌هایی که جمع‌آوری می‌کنیم',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'حساب: نشانی ایمیل، نام کاربری و رمز عبور. رمزهای عبور به‌صورت هش برگشت‌ناپذیر ذخیره می‌شوند؛ حساب‌های مهمان را می‌توان بدون ایمیل استفاده کرد.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'پروفایل: اطلاعاتی که خودت انتخاب می‌کنی اضافه کنی، مانند آواتار، تصویر کاور، بیو و کشور.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'استفاده: تاریخچه تماشا، امتیازها، نظرها، فهرست‌ها، واکنش‌ها و علاقه‌مندی‌هایت.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'پیام‌ها: پیام‌های متنی، تصویری و صوتی تو روی سرورهای ما ذخیره می‌شوند. پیام‌ها رمزگذاری سرتاسری ندارند؛ فقط در صورت گزارش‌شدن و برای نظارت بررسی می‌شوند.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'رسانه‌های بارگذاری‌شده: عکس‌ها، GIFها، ویدیوها و ضبط‌های صوتی که به پروفایل، نظرها و پیام‌هایت اضافه می‌کنی.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'داده‌های فنی: نشانی IP، موقعیت تقریبی (کشور/شهر)، پلتفرم دستگاه، نسخه اپلیکیشن و گزارش‌های خطا. این‌ها برای امنیت و رفع اشکال نگهداری می‌شوند.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'آمار استفاده: نوع دستگاه، سیستم‌عامل و مرورگری که با آن وارد می‌شوید به‌صورت دسته‌های کلی به شمارنده‌های کل روزانه افزوده می‌شود؛ خودِ شناسه مرورگر نگهداری نمی‌شود و این اعداد به هیچ شخصی قابل ربط دادن نیست.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'اعلان‌ها: برای اعلان‌های پوش، توکن دستگاه و زبان انتخابی‌ات را نگه می‌داریم. هر وقت بخواهی می‌توانی اعلان‌ها را از تنظیمات دستگاه خاموش کنی.',
  'Verileri Nasıl Kullanırız': 'چطور از داده‌هایت استفاده می‌کنیم',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'از داده‌هایت فقط برای ارائه سرویس، محافظت از حساب، ارسال اعلان، رفع خطاها و جلوگیری از سوءاستفاده استفاده می‌کنیم. داده‌هایت را نمی‌فروشیم و برای تبلیغات با هیچ‌کس به اشتراک نمی‌گذاریم.',
  'Çerezler ve Yerel Depolama': 'کوکی‌ها و ذخیره‌سازی محلی',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'از ذخیره‌سازی محلی فقط برای باز نگه داشتن نشستت و به‌خاطر سپردن ترجیح‌هایی مانند زبان و پوسته استفاده می‌کنیم. هیچ کوکی تبلیغاتی یا ردیابی وجود ندارد.',
  'Üçüncü Taraf Hizmetler': 'سرویس‌های شخص ثالث',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'اطلاعات سریال‌ها و فیلم‌ها از TMDB و اطلاعات پلتفرم‌های پخش از JustWatch می‌آید. اعلان‌های پوش از طریق Google Firebase ارسال می‌شوند و ترافیک سایت را Cloudflare محافظت می‌کند. این سرویس‌ها تابع سیاست‌های حریم خصوصی خودشان هستند.',
  'Saklama ve Silme': 'نگهداری و حذف',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'داده‌هایت تا زمانی که حسابت فعال است نگهداری می‌شوند. با «حذف حساب من» در تنظیمات می‌توانی حسابت را برای همیشه حذف کنی؛ داده‌هایت بلافاصله و نسخه‌های موجود در پشتیبان‌ها حداکثر تا ۱۴ روز پاک می‌شوند. گزارش‌های خطا پس از ۳۰ روز به‌طور خودکار حذف می‌شوند.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'می‌توانی داده‌هایت را از تنظیمات به‌صورت ZIP خروجی بگیری؛ آرشیو به نشانی ایمیلت فرستاده می‌شود.',
  'Güvenlik': 'امنیت',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'داده‌ها از طریق اتصال‌های رمزگذاری‌شده (HTTPS) منتقل و روی سرورهایی با دسترسی محدود نگهداری می‌شوند.',
  'Çocukların Gizliliği': 'حریم خصوصی کودکان',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      '‏dizi.jpg برای کودکان زیر ۱۳ سال طراحی نشده است.',
  'Hakların': 'حقوق تو',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'طبق KVKK و GDPR حق دسترسی به داده‌هایت، اصلاح، حذف و انتقال آن‌ها را داری. برای این موارد برایمان بنویس: {}',
  'Değişiklikler': 'تغییرات',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'اگر این سیاست تغییر کند، نسخه جدید در همین صفحه منتشر و تاریخ به‌روزرسانی می‌شود.',
  'Kayıt olarak {} kabul etmiş olursun.': 'با ثبت‌نام، {} را می‌پذیری.',
  'Kullanıcılar': 'کاربران',
  'Fotoğrafı değiştir': 'تغییر عکس',
  'Yeniden konumlandır': 'تنظیم دوباره',
  'Bir şeyler ters gitti': 'مشکلی پیش آمد',
  'Sosyal Bağlantılar': 'پیوندهای اجتماعی',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'در پروفایلت حداکثر ۳ پیوند نمایش داده می‌شود.',
  'Platform seç': 'یک پلتفرم انتخاب کن',
  'Kullanıcı adın': 'نام کاربری‌ات',
  'Ekle': 'افزودن',
  'Kaldır': 'حذف',
  'Kopyalandı: {}': 'کپی شد: {}',
  'Geçersiz kullanıcı adı': 'نام کاربری نامعتبر',
  'Bağlantı ekle': 'افزودن پیوند',
  'Spoiler olabilir — dokun ve gör':
      'ممکن است اسپویل داشته باشد — برای دیدن لمس کن',
  'Beğeni': 'پسندها',
  'beğeni': 'پسندها',
  'Beğen': 'پسندیدن',
  'Görüntülenme': 'بازدیدها',
  'görüntülenme': 'بازدیدها',
  'Tam ekran': 'تمام‌صفحه',
  'Arama başarısız': 'جستجو ناموفق بود',
  'Sonuç bulunamadı': 'نتیجه‌ای یافت نشد',
  'Dizi ve Filmler': 'سریال‌ها و فیلم‌ها',
  'Kişiler': 'افراد',
  'Ana Sayfa': 'خانه',
  'Paylaş': 'اشتراک‌گذاری',
  'Yanıtlar': 'پاسخ‌ها',
  'Yaklaşan Bölümler': 'قسمت‌های پیش‌رو',
  'Yetişme Listesi': 'فهرست عقب‌ماندگی',
  'Şunu mu demek istedin': 'منظورت این بود',
  'Spoiler': 'اسپویل',
  'Spoiler — dokun ve gör': 'اسپویل — برای دیدن لمس کن',
  'uyum': 'تطابق',
  'Uyum': 'تطابق',
  '{} ortak dizi': '{} سریال مشترک',
  '{} ortak film': '{} فیلم مشترک',
  'Bildirim Tercihleri': 'تنظیمات اعلان‌ها',
  'Beğeniler': 'پسندها',
  'Yeni takipçiler': 'دنبال‌کننده‌های جدید',
  'Etiketlenmeler': 'اشاره‌ها',
  'Yeniden izledim': 'دوباره دیده شد',
  '{}. kez izlendi': '{} بار دیده شد',
  'Gönderi bulunamadı': 'پست پیدا نشد',
  'Gözat': 'مرور',
  'Diziler': 'سریال‌ها',
  'Filmler': 'فیلم‌ها',
  'Tümü': 'همه',
  'Farklı bir tür seç.': 'ژانر دیگری را امتحان کن.',
  'Gizlilik': 'حریم خصوصی',
  'İzlediklerimi gizle': 'پنهان کردن تماشاهایم',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'سریال‌ها و فیلم‌هایی که دیده‌ای در پروفایلت نمایش داده نمی‌شوند',
  'Yorumlarımı gizle': 'پنهان کردن نظرات من',
  'Profilinde yorumların görünmez': 'نظرات تو در پروفایلت نمایش داده نمی‌شوند',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'می‌توانی یک سریال یا فیلم خاص را با گزینه «در پروفایلم پنهان کن» در صفحه‌اش پنهان کنی.',
  'Geri Bildirim': 'بازخورد',
  'Uygulama hakkında görüş ve önerini yaz...':
      'نظر و پیشنهادت را درباره اپلیکیشن بنویس...',
  'Teşekkürler! Geri bildirimin alındı.': 'ممنون! بازخوردت دریافت شد.',
  'Profilimde gizle': 'در پروفایلم پنهان کن',
  'Yorumları': 'نظرهایش',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'این کاربر هنوز چیزی تماشا نکرده است.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'این کاربر ترجیح می‌دهد نظراتش پنهان بمانند.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'داده‌ها: JustWatch',
  'Web Sitesi': 'وب‌سایت',
  'Diğer uygulamalar': 'برنامه‌های دیگر',
  'Bağlantıyı kopyala': 'کپی لینک',
  'Henüz kimseyi takip etmiyorsun.': 'هنوز کسی را دنبال نمی‌کنی.',
  'Çevir': 'ترجمه',
  'Çeviri şu an yapılamadı': 'ترجمه در حال حاضر ممکن نیست',
  'Bağlantı açılamadı': 'باز کردن پیوند ممکن نشد',
  'Orijinali göster': 'نمایش متن اصلی',
  'Çeviriyi göster': 'نمایش ترجمه',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'این ماه قسمتی با تاریخ پخش اعلام‌شده وجود ندارد. تاریخ‌ها معمولاً چند هفته قبل اعلام می‌شوند و اینجا نمایش داده خواهند شد.',
  'devamı': 'بیشتر',
  'Google ile devam et': 'ادامه با Google',
  'Google girişi başarısız': 'ورود با Google ناموفق بود',
  'Veri tasarrufu': 'صرفه‌جویی داده',
  'Wi-Fi ağında veri tasarrufu': 'صرفه‌جویی داده در Wi-Fi',
  'Mobil veride veri tasarrufu': 'صرفه‌جویی داده در اینترنت همراه',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'وقتی روشن است عکس‌ها از پیش دانلود نمی‌شوند و فقط تصویری که می‌بینی بارگذاری می‌شود.',
  'Çocuk güvenliği': 'ایمنی کودکان',
  'Türk Filmleri': 'فیلم‌های ترکی',
  'En Yüksek Puanlı Filmler': 'فیلم‌های با بالاترین امتیاز',
  'En Yüksek Puanlı Diziler': 'سریال‌های با بالاترین امتیاز',
  'En Çok İzlenen Filmler': 'پربیننده‌ترین فیلم‌ها',
  'Popüler Diziler': 'سریال‌های محبوب',
  'En Çok Kazanan Filmler': 'پرفروش‌ترین فیلم‌ها',
  'Kült Filmler': 'فیلم‌های کالت',
  'Yeni Filmler': 'فیلم‌های جدید',
  'Yorum yap': 'نظر بدهید',
  'Henüz yorum yok': 'هنوز نظری نیست',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'نظرهایی که برای سریال‌ها و فیلم‌ها می‌نویسی اینجا جمع می‌شود.',
  'GIF ekle': 'افزودن GIF',
  'İlk yorumu sen yaz': 'اولین نظر را شما بنویسید',
  'Video altyazıları': 'زیرنویس ویدیو',
  'Videolarda altyazı göster': 'نمایش زیرنویس روی ویدیوها',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'جمله ای که در ویدیو گفته می شود روی صفحه نوشته می شود. متن ترجمه شده است: انگلیسی در گفتار ترکی، ترکی در زبان های دیگر.',
  'Güncelleme gerekli': 'به‌روزرسانی لازم است',
  'Yeni sürüm var': 'نسخه جدید موجود است',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'برای ادامه، نسخه جدید dizi.jpg را نصب کن.',
  'Güncelle': 'به‌روزرسانی',
  'Daha sonra': 'بعداً',
  'Takvim güncelleniyor': 'در حال به‌روزرسانی تقویم',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'تقویم به‌روزرسانی نشد، فهرست قدیمی نمایش داده می‌شود',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'برخی سریال‌ها بارگذاری نشدند، فهرست ممکن است ناقص باشد',
  'Yenile': 'تازه‌سازی',
  'Devam etmek için giriş yap': 'برای ادامه وارد شوید',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'یک حساب رایگان برای امتیاز دادن، نظر نوشتن و ساختن کتابخانه شما کافی است.',
  'Şimdi değil': 'الان نه',
  'Yorum yazmak için giriş yap': 'برای نوشتن نظر وارد شوید',
  'Kişilere göndermek için giriş yap': 'برای ارسال به افراد وارد شوید',
  'Beğenenler': 'پسندیدند',
  'Henüz beğeni yok': 'هنوز پسندی نیست',
  'Bu gönderiyi ilk beğenen sen ol': 'اولین نفری باشید که این پست را می پسندد',
  'Bu gönderiye yanıt': 'پاسخ به این پست',
  'Spoiler içeren gönderi': 'پست دارای اسپویل',
  'Görsel gönderi': 'پست تصویری',
  'Bu yorumu profilimde gizle': 'پنهان کردن این نظر از پروفایلم',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'نظر در صفحه سریال و فیلم باقی می‌ماند',
  'Bu yorumu sil': 'حذف این نظر',
  'Yorum profilinde gizlendi': 'نظر از پروفایل تو پنهان شد',
  'Geri al': 'واگرد',
  'Yorum silinsin mi?': 'نظر حذف شود؟',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'این نظر برای همیشه از همه جا حذف می‌شود. غیرقابل بازگشت است.',
  'Yorum silindi': 'نظر حذف شد',
  'Yorum profilinde tekrar görünüyor':
      'نظر دوباره در پروفایل تو نمایش داده می‌شود',
  'Gizlenen yorumun yok': 'نظر پنهانی نداری',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'نظرهایی که با فشار طولانی روی یک پست در تب نظرات پروفایلت پنهان می‌کنی، اینجا جمع می‌شوند.',
  'Gizlenen yorumlar': 'نظرهای پنهان',
  'Gönderiye git': 'رفتن به پست',
  'Tekrar göster': 'دوباره نمایش بده',
  'Yanıtlarımı gizle': 'پاسخ‌های من را پنهان کن',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'پاسخ‌هایی که به پست‌های دیگران می‌نویسی فقط برای خودت نمایش داده می‌شود',
  'Profilinde gizlediğin yorumları tekrar göster':
      'نظرهایی را که از پروفایلت پنهان کرده‌ای دوباره نشان بده',
  'Sıralama': 'مرتب‌سازی',
  'Önerilen': 'پیشنهادی',
  'Kronolojik': 'بر اساس زمان',
  'Gelen mesaj istekleri': 'درخواست‌های پیام دریافتی',
  'Mesaj isteğin yok': 'درخواست پیامی ندارید',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'پیام‌های افرادی که دنبال نمی‌کنید اینجا نمایش داده می‌شود.',
  'Çevrimiçi durumumu gizle': 'پنهان کردن وضعیت آنلاین من',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'دیگران وضعیت آنلاین و آخرین بازدید شما را در پیام‌ها نمی‌بینند',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'یکی از نخستین کاربران ما. بازخوردهای او کمک کرد تا برنامه به شکل امروزی درآید.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'تو یکی از نخستین کاربران ما هستی. بازخوردهای تو کمک کرد تا برنامه به شکل امروزی درآید.',
  'İleri': 'بعدی',
  'Önceki': 'قبلی',
  'Sonraki': 'بعدی',
  'Seçilen dosya okunamadı': 'فایل انتخاب‌شده خوانده نشد',
  'Video açılamadı': 'ویدیو باز نشد',
  'En fazla {} medya seçebilirsin': 'حداکثر {} رسانه می‌توانید انتخاب کنید',
  'Hiçbir medya yüklenemedi': 'هیچ رسانه‌ای بارگذاری نشد',
  'Seçimi kaldır': 'حذف از انتخاب',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'در هر دیدگاه در مجموع {} مگابایت می‌توانید بارگذاری کنید',
  '{} dosya okunamadı': '{} فایل خوانده نشد',
  '{} medya eklendi, {} yüklenemedi': '{} رسانه افزوده شد، {} ناموفق',
  'Kırp': 'برش',
  'Çiz': 'نقاشی',
  'Metin': 'متن',
  'Emoji': 'ایموجی',
  'Yinele': 'انجام دوباره',
  'Daha fazla': 'بیشتر',
  'Hazırlanıyor…': 'در حال آماده‌سازی…',
  'Düzenlemeden çık?': 'از ویرایش خارج می‌شوید؟',
  'Yaptığın değişiklikler kaybolacak.': 'تغییرات شما از بین می‌رود.',
  'Çık': 'خروج',
  'Serbest çizim': 'نقاشی آزاد',
  'Ok': 'پیکان',
  'Dikdörtgen': 'مستطیل',
  'Daire': 'دایره',
  'Bulanıklaştır': 'محو کردن',
  'Pikselleştir': 'پیکسلی کردن',
  'Silgi': 'پاک‌کن',
  'Çizgi kalınlığı': 'ضخامت خط',
  'Saydamlık': 'شفافیت',
  'Dolgu': 'پرکردن',
  'Renk': 'رنگ',
  'Döndür': 'چرخاندن',
  'Yansıt': 'بازتاب',
  'Oran': 'نسبت',
  'Sıfırla': 'بازنشانی',
  'Serbest': 'آزاد',
  'Metin yaz...': 'متن بنویسید...',
  'Hizala': 'تراز',
  'Arka plan': 'پس‌زمینه',
  'Emoji ara...': 'جستجوی ایموجی...',
  'Son kullanılanlar': 'اخیر',
  'İfadeler ve insanlar': 'شکلک‌ها و افراد',
  'Hayvanlar ve doğa': 'حیوانات و طبیعت',
  'Yiyecek ve içecek': 'غذا و نوشیدنی',
  'Etkinlikler': 'فعالیت‌ها',
  'Seyahat ve yerler': 'سفر و مکان‌ها',
  'Nesneler': 'اشیا',
  'Semboller': 'نمادها',
  'Bayraklar': 'پرچم‌ها',
  'Görseli düzenle': 'ویرایش تصویر',
  'Düzenlendi': 'ویرایش شد',
  'Düzenlenemedi': 'ویرایش انجام نشد',
  'Düzenlenen görsel çok büyük': 'تصویر ویرایش‌شده خیلی بزرگ است',
  'Videoyu düzenle': 'ویرایش ویدیو',
  'Sesi kapat': 'بی‌صدا کردن',
  'Sesi aç': 'باصدا کردن',
  'İptal ediliyor…': 'در حال لغو…',
  'Bu biraz sürebilir': 'ممکن است کمی طول بکشد',
  'Video çok büyük': 'ویدیو خیلی بزرگ است',
  'Video hazırlanamadı': 'ویدیو آماده نشد',
  'Başlangıç': 'شروع',
  'Bitiş': 'پایان',
  'En çok {} saniye seçebilirsin': 'حداکثر {} ثانیه می‌توانید انتخاب کنید',
  'Dosya en fazla {} MB olabilir': 'حجم فایل حداکثر {} مگابایت',
  'Medya ekle': 'افزودن رسانه',
  'Seçili medya kalmadı': 'رسانه‌ای انتخاب نشده است',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'برای افزودن به نظرت یک عکس یا ویدیو انتخاب کن.',
  'Medya seç': 'انتخاب رسانه',
  'Daha fazla ekle': 'افزودن بیشتر',
  'Medya seçilemedi': 'رسانه انتخاب نشد',
  'Favori oyuncular': 'بازیگران مورد علاقه',
  'Henüz favori oyuncun yok': 'هنوز بازیگر مورد علاقه ای ندارید',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'صفحه یک بازیگر را باز کنید و روی قلب بالا سمت راست بزنید تا اینجا اضافه شود.',
  '{} yapımdan {} tanesini izledin': '{} از {} اثر را دیده اید',
  'izledin': 'دیده شده',
  'İzlemedin': 'ندیده اید',
  'Yapım bulunamadı': 'اثری یافت نشد',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'این شخص سریال یا فیلمی برای نمایش ندارد.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'تاریخچه تماشای شما به حسابتان وابسته است؛ این فهرست فقط برای شماست.',
  'Hesabın kalıcı olarak askıya alındı': 'حساب شما برای همیشه تعلیق شده است',
  'Hesabın geçici olarak askıya alındı': 'حساب شما موقتا تعلیق شده است',
  'Hesabın askıya alındı': 'حساب شما تعلیق شده است',
  'Sebep': 'دلیل',
  'Kalan süre': 'زمان باقی مانده',
  'Süre dolunca hesabın kendiliğinden açılır':
      'با پایان مهلت، حساب شما خودبه‌خود باز می‌شود',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'در این مدت می‌توانید بخوانید، اما نمی‌توانید مطلب، دیدگاه یا پیام بفرستید.',
  'Anladım': 'متوجه شدم',
  'Ayrıntı': 'جزئیات',
  '{} dakika': '{} دقیقه',
  'birkaç saniye': 'چند ثانیه',
  'Karara itiraz et': 'اعتراض به این تصمیم',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'توضیح دهید چرا این جریمه باید برداشته شود',
  'İtirazını gönder': 'ارسال اعتراض',
  'İtirazın incelemede': 'اعتراض شما در حال بررسی است',
  'İtirazın reddedildi': 'اعتراض شما رد شد',
  'İtirazın alındı, inceleniyor': 'اعتراض شما دریافت شد و در حال بررسی است',
  'İtiraz en az 10 karakter olmalı': 'اعتراض باید حداقل ۱۰ نویسه باشد',
  'Yükleniyor...': 'در حال بارگذاری...',
  'Bu bölüme puan ver': 'به این قسمت امتیاز دهید',
  '{} kişi puanladı': '{} نفر امتیاز دادند',
  'Bölüm izlendi olarak işaretlendi': 'قسمت به عنوان دیده شده علامت خورد',
  'Sesli ara': 'تماس صوتی',
  'Görüntülü ara': 'تماس تصویری',
  'Çalıyor...': 'در حال زنگ خوردن...',
  'Bağlanıyor...': 'در حال اتصال...',
  'Cevapla': 'پاسخ',
  'Reddet': 'رد کردن',
  'Sessize al': 'بی‌صدا',
  'Hoparlör': 'بلندگو',
  'Kamerayı kapat': 'خاموش کردن دوربین',
  'Kamerayı çevir': 'تعویض دوربین',
  'Cevap yok': 'پاسخی داده نشد',
  'Arama reddedildi': 'تماس رد شد',
  'Meşgul': 'مشغول',
  'Bağlanılamadı': 'اتصال برقرار نشد',
  'Arama iptal edildi': 'تماس لغو شد',
  'Arama geçmişi': 'تاریخچه تماس‌ها',
  'Gelen arama': 'تماس ورودی',
  'Giden arama': 'تماس خروجی',
  'Cevapsız arama': 'تماس بی‌پاسخ',
  'Arama şu anda kullanılamıyor': 'تماس در حال حاضر در دسترس نیست',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'تماس تصویری فعلاً غیرفعال است، می‌توانید تماس صوتی بگیرید',
  'Bu kullanıcıyı arayamazsın': 'نمی‌توانید با این کاربر تماس بگیرید',
  'Aramak için karşılıklı takipleşmelisiniz':
      'برای تماس باید یکدیگر را دنبال کنید',
  'Bu kullanıcı şu anda aranamıyor':
      'در حال حاضر نمی‌توان با این کاربر تماس گرفت',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'تماس‌های بی‌پاسخ زیاد است. {} دیگر دوباره تلاش کنید',
  'Zaten bir aramadasın': 'شما هم‌اکنون در یک تماس هستید',
  'Arama için mikrofon izni gerekiyor':
      'برای تماس، اجازه دسترسی به میکروفون لازم است',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'برای تماس تصویری، اجازه دسترسی به دوربین و میکروفون لازم است',
  'Arama başlatılamadı': 'تماس آغاز نشد',
  'Kullanıcı bulunamadı': 'کاربر پیدا نشد',
  'Kendini arayamazsın': 'نمی‌توانید با خودتان تماس بگیرید',
  'Arama artık geçerli değil': 'این تماس دیگر معتبر نیست',
  'Bu aramanın tarafı değilsin': 'شما بخشی از این تماس نیستید',
  'Arama bulunamadı': 'تماس پیدا نشد',
  'Çok fazla istek, biraz bekle': 'درخواست‌های بیش از حد، کمی صبر کنید',
  'Bağlantı koptu': 'اتصال قطع شد',
  'Arama süre sınırına ulaştı': 'تماس به محدودیت زمانی رسید',
  'Arama en fazla 4 saat sürebilir': 'هر تماس حداکثر ۴ ساعت می‌تواند طول بکشد',
  'Arama sona erdi': 'تماس پایان یافت',
  'Sesli arama': 'تماس صوتی',
  'Görüntülü arama': 'تماس تصویری',
  'Gelen aramalar': 'تماس‌های ورودی',
  'Sesli ve görüntülü arama bildirimleri': 'اعلان تماس‌های صوتی و تصویری',
  '{} sa': '{} ساعت',
  'Sesli ve Görüntülü Aramalar': 'تماس‌های صوتی و تصویری',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'محتوای تماس‌ها هرگز ضبط نمی‌شود. صدا و تصویر با رمزگذاری سرتاسری (DTLS-SRTP) میان دستگاه‌ها جریان می‌یابد؛ سرورهای ما نمی‌توانند این ترافیک را رمزگشایی، شنود یا ذخیره کنند.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'فقط فراداده تماس نگهداری می‌شود: با چه کسی، در چه جهتی، چه زمانی و چه مدت. این سوابق پس از ۹۰ روز به‌طور خودکار حذف می‌شوند.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'اگر اتصال مستقیم ممکن نباشد، صدا و تصویر به‌صورت رمزگذاری‌شده از یک سرور بازپخش (TURN) عبور می‌کنند. آن سرور نیز نمی‌تواند محتوا را رمزگشایی یا ضبط کند.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'میکروفون فقط هنگام تماس صوتی یا تصویری و دوربین فقط هنگام تماس تصویری استفاده می‌شود. با پایان تماس هر دو خاموش می‌شوند.',
  'Takip ettiğin {} kişi izledi':
      '{} نفر از کسانی که دنبال می‌کنی آن را دیده‌اند',
  'Yorum yaz...': 'دیدگاهی بنویس...',
  'Sıradaki bölüm': 'قسمت بعدی',
  'Doğrulanmış testçi': 'آزمایش‌کننده تأییدشده',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'اعلان‌های دنبال کردن، پسند، پاسخ، پیام و برچسب',
  'Sen': 'تو',
  'Aradığınız kişide sesli arama devre dışı':
      'تماس صوتی برای این شخص غیرفعال است',
  'Aradığınız kişide görüntülü arama devre dışı':
      'تماس تصویری برای این شخص غیرفعال است',
  'Sesli aramalara izin ver': 'اجازه تماس صوتی',
  'Görüntülü aramalara izin ver': 'اجازه تماس تصویری',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'وقتی خاموش باشد کسی نمی‌تواند با شما تماس صوتی بگیرد؛ تماس‌گیرنده اعلانی می‌بیند',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'وقتی خاموش باشد کسی نمی‌تواند با شما تماس تصویری بگیرد؛ تماس‌گیرنده اعلانی می‌بیند',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'تماس صوتی خاموش است. می‌توانید از تنظیمات > حریم خصوصی آن را روشن کنید.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'تماس تصویری خاموش است. می‌توانید از تنظیمات > حریم خصوصی آن را روشن کنید.',
  'Sesli ve görüntülü arama': 'تماس صوتی و تصویری',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'حساب‌های مهمان نمی‌توانند تماس بگیرند. برای استفاده، حساب بساز.',
  'Misafir hesaplar aranamaz': 'به حساب‌های مهمان نمی‌توان تماس گرفت',
  'Puan dağılımı': 'توزیع امتیازها',
  '{} yıldız': '{} ستاره',
  'Yakında gelecek': 'به‌زودی',
  '{} {} yayınlandı': '{} {} منتشر شد',
  'Yeni bölüm yayınlandı': 'قسمت جدید منتشر شد',
  'Yeni bölümler': 'قسمت‌های جدید',
  'Geri': 'بازگشت',
  'Karşılamayı kapat': 'بستن خوش‌آمدگویی',
  'Adım {} / {}': 'گام {} / {}',
  'Hadi başlayalım': 'شروع کنیم',
  'Kaydet ve devam': 'ذخیره و ادامه',
  '{} tanesini ekle': 'افزودن {} مورد',
  'Şimdilik geç': 'فعلاً نه',
  'Doğum tarihin ne zaman?': 'تاریخ تولدت کِی است؟',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'می‌پرسیم تا محتوای متناسب با سنت نشان دهیم و تولدت را تبریک بگوییم.',
  'Gün': 'روز',
  'Ay': 'ماه',
  'Yıl': 'سال',
  'Doğum yılımı paylaşmak istemiyorum': 'نمی‌خواهم سال تولدم نشان داده شود',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'تاریخ تولدت در پروفایلت برای همه نمایش داده نمی‌شود. فقط برای محتوای متناسب با سن و تبریک تولد به کار می‌رود.',
  'Ocak': 'ژانویه',
  'Şubat': 'فوریه',
  'Mart': 'مارس',
  'Nisan': 'آوریل',
  'Mayıs': 'مه',
  'Haziran': 'ژوئن',
  'Temmuz': 'ژوئیه',
  'Ağustos': 'اوت',
  'Eylül': 'سپتامبر',
  'Ekim': 'اکتبر',
  'Kasım': 'نوامبر',
  'Aralık': 'دسامبر',
  'Verilerini yanında getir': 'داده‌هایت را با خودت بیاور',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'اگر در برنامه‌ای دیگر تماشاهایت را دنبال می‌کنی، می‌توانی آن‌ها را به اینجا بیاوری. لازم نیست از صفر شروع کنی.',
  'TV Time, Trakt ve Letterboxd': 'TV Time، Trakt و Letterboxd',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'فایل ZIP خروجی‌گرفته را انتخاب کن تا تماشاها، امتیازها و فهرست‌هایت منتقل شوند.',
  'Aktarılıyor...': 'در حال انتقال...',
  'ZIP dosyası seç': 'انتخاب فایل ZIP',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'عجله‌ای نیست: این کار را بعداً هم می‌توانی از تنظیمات > داده‌های من انجام دهی.',
  'Hangi filmleri izledin?': 'چه فیلم‌هایی دیده‌ای؟',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'پرتماشاترین‌ها اینجا هستند. هرکدام را بزنی به تماشاهایت اضافه می‌شود.',
  'SERİ FİLMLER': 'مجموعه‌های فیلم',
  'Serilerden {} film eklendi': '{} فیلم از مجموعه‌ها افزوده شد',
  'Film listesi yüklenemedi': 'فهرست فیلم‌ها بارگذاری نشد',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'می‌توانی این گام را رد کنی و بعداً هرچه خواستی اضافه کنی.',
  '{} film izlediklerine eklendi': '{} فیلم به تماشاهایت افزوده شد',
  'Film serileri': 'مجموعه‌های فیلم',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'اگر مجموعه‌ای را از اول تا آخر دیده‌ای، با یک لمس اضافه‌اش کن.',
  'Seri bulunamadı': 'مجموعه‌ای پیدا نشد',
  'Daha sonra tekrar deneyebilirsin.': 'بعداً دوباره امتحان کن.',
  '{} film': '{} فیلم',
  'Eklendi': 'افزوده شد',
  'Tümünü izledim': 'همه را دیدم',
  'Peki ya diziler?': 'خب، سریال‌ها چطور؟',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'دیده‌هایت را علامت بزن؛ هرچه بیشتر انتخاب کنی، شبیه‌ترها را می‌آوریم.',
  'Dizi listesi yüklenemedi': 'فهرست سریال‌ها بارگذاری نشد',
  'Seçtiklerine benzeyenler': 'شبیه انتخاب‌هایت',
  'Her şey hazır': 'همه‌چیز آماده است',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'نگاهی سریع به کارهایی که در dizi.jpg می‌توانی انجام دهی.',
  'Profilini tamamla': 'پروفایلت را کامل کن',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'از تنظیمات می‌توانی بیو، عکس پروفایل و کاور اضافه کنی.',
  'Takvimin seni bekliyor': 'تقویم منتظرت است',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'قسمت‌های جدید سریال‌هایی که دنبال می‌کنی در تقویم می‌افتد و با اعلان خبرت می‌کنیم.',
  'Puan ver, yorum yaz': 'امتیاز بده، نظر بنویس',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'قسمت‌به‌قسمت امتیاز بده، پشت پردهٔ اسپویل نظر بنویس و فهرست بساز.',
  'Verilerin sende kalır': 'داده‌هایت پیش خودت می‌ماند',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'داده‌هایت فقط به حسابت وصل است و فروخته نمی‌شود. از تنظیمات می‌توانی همه را دانلود کنی یا حسابت را کاملاً حذف کنی.',
  'Engellenen kullanıcılar': 'کاربران مسدودشده',
  'Engellediğin kişileri gör, engeli kaldır':
      'کسانی را که مسدود کرده‌ای ببین و مسدودیت را بردار',
  'Engellediğin kimse yok': 'کسی را مسدود نکرده‌ای',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'هر کاربر را می‌توانی از منوی سه‌نقطه در پروفایلش مسدود کنی.',
  '@{} engellensin mi?': '@{} مسدود شود؟',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'پست‌ها، نظرها و پروفایل یکدیگر را نمی‌بینید؛ پیام و تماس هم رد و بدل نمی‌شود. اگر دنبال‌کردنی میان شما باشد قطع می‌شود و حتی با رفع مسدودیت هم برنمی‌گردد.',
  'Bu kullanıcıyı engelledin': 'این کاربر را مسدود کرده‌ای',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'پست‌ها، نظرها و پیام‌های این شخص را نمی‌بینی؛ این شخص هم مال تو را نمی‌بیند.',
  '{} yeni bir yapımda: {}': '{} در اثری تازه: {}',
  'Favori kişinden yeni yapım': 'اثر تازه از یک چهرهٔ محبوب',
  '{} için bildirimler': 'اعلان‌های {}',
  'Tüm bildirimler': 'همهٔ اعلان‌ها',
  'Uygulamada ve telefonda': 'در برنامه و روی گوشی',
  'Yalnız uygulama içi': 'فقط داخل برنامه',
  'Telefon bildirimi gönderilmez': 'اعلان گوشی فرستاده نمی‌شود',
  'Kapalı': 'خاموش',
  'Bu kişi için bildirim yok': 'برای این شخص اعلانی نیست',
  'Favori kişilerin yeni yapımları': 'آثار تازهٔ چهره‌های محبوبت',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'وقتی خاموش باشد کسی نمی‌تواند با شما تماس صوتی بگیرد؛ تماس‌گیرنده اعلانی می‌بیند که تماس "غیرفعال" است',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'وقتی خاموش باشد کسی نمی‌تواند با شما تماس تصویری بگیرد؛ تماس‌گیرنده اعلانی می‌بیند که تماس "غیرفعال" است',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'فعالیت من',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'پسندها، نظرها و تماشاهایت در یک جریان',
  'Henüz hareketin yok': 'هنوز فعالیتی نیست',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'هر چه بپسندی، نظر بدهی و تماشا کنی اینجا جمع می‌شود.',
  'Bu süzgeçte hareket yok': 'در این فیلتر فعالیتی نیست',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'نوع دیگری انتخاب کن یا به «همه» برگرد.',
  'Hepsi': 'همه',
  'Puan': 'امتیاز',
  'Tepki': 'واکنش',
  'İzleme': 'تماشا',
  'Durum': 'وضعیت',
  'Liste': 'فهرست',
  'Yorum yaptın': 'نظر دادی',
  'Yorumu beğendin': 'نظری را پسندیدی',
  '{} puan verdin': 'امتیاز {} دادی',
  'Tepki verdin': 'واکنش دادی',
  'Listene ekledin': 'به فهرست افزودی',
  'Takip etmeye başladın': 'دنبال کردن را آغاز کردی',
  '"İzleyeceğim" işaretledin': '«خواهم دید» علامت زدی',
  '"İzliyorum" işaretledin': '«در حال تماشا» علامت زدی',
  '"Bitirdim" işaretledin': '«تمام کردم» علامت زدی',
  '"Bıraktım" işaretledin': '«رها کردم» علامت زدی',
  'Silinmiş içerik': 'محتوای حذف‌شده',
  'şimdi': 'هم‌اکنون',
  '{} g': '{} روز',
  '{} y': '{} سال',
  'İstatistiklerim': 'آمار من',
  'Gönderilerinin görüntülenmesi ve beğenisi': 'بازدیدها و پسندهای پست‌هایت',
  'Henüz gönderin yok': 'هنوز پستی نداری',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'وقتی روی سریال یا فیلمی نظر بنویسی، شمار بازدیدها و پسندهایت اینجا جمع می‌شود.',
  'Tüm zamanlar': 'کل زمان',
  'Son {} gün': '{} روز اخیر',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'تاریخچه بازدیدها هنوز شروع به جمع شدن نکرده است؛ داده روز نخست فردا نمایش داده می‌شود.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'تاریخچه بازدیدها از {} در حال جمع شدن است ({} روز داده موجود است)، بنابراین عدد {} روزه هنوز ناقص است.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'تاریخچه پسندها از {} ثبت شده است.',
  'Bu dönemde gösterilecek gönderi yok.': 'برای این بازه پستی برای نمایش نیست.',
  'eksik veri': 'داده ناقص',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'سریال‌ها و فیلم‌هایی که دیده‌ای، شمارنده‌های تماشا، زمان تماشا و کارت تطابق در پروفایلت برای دیگران نمایش داده نمی‌شود',
  'Takipçi listemi gizle': 'پنهان کردن فهرست دنبال‌کنندگانم',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'دیگران نمی‌توانند ببینند چه کسانی دنبالت می‌کنند؛ شمار دنبال‌کنندگانت همچنان دیده می‌شود',
  'Takip ettiklerimi gizle': 'پنهان کردن کسانی که دنبال می‌کنم',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'دیگران نمی‌توانند ببینند چه کسانی را دنبال می‌کنی؛ شمار دنبال‌شده‌هایت همچنان دیده می‌شود',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'این کاربر ترجیح می‌دهد دنبال‌کنندگانش پنهان بمانند.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'این کاربر ترجیح می‌دهد کسانی که دنبال می‌کند پنهان بمانند.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'آمار پست',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'فقط می‌توانی آمار پست‌های خودت را ببینی.',
  'Erişim': 'دسترسی',
  'Görüntüleyen': 'بینندگان',
  'Kaç farklı kişi gördü (son {} gün)':
      'چند نفر متفاوت آن را دیدند ({} روز اخیر)',
  'Paylaşım': 'اشتراک‌گذاری‌ها',
  'Bu gönderiden sonra': 'پس از این پست',
  'Profil ziyareti': 'بازدید پروفایل',
  'Yeni takip': 'دنبال‌کردن‌های جدید',
  'İçeriğe tıklama': 'ضربه روی محتوا',
  'Spoiler perdesini açan': 'اسپویل را باز کردند',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'اشتراک‌گذاری‌ها، بازدید پروفایل، دنبال‌کردن‌ها، ضربه روی محتوا، تفکیک منابع و سنجش اسپویل از {} انباشته می‌شوند؛ پیش از آن سنجیده نشده است.',
  'Zamana yayılmış görüntülenme': 'بازدیدها در طول زمان',
  'Görüntülenme nereden geldi': 'بازدیدها از کجا آمدند',
  'Kimler gördü': 'چه کسانی دیدند',
  'Günlük veri henüz birikmeye başlamadı.':
      'داده‌های روزانه هنوز شروع به انباشته‌شدن نکرده است.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'نمودار دست‌کم به داده‌های دو روز نیاز دارد. داده‌ها از {} انباشته می‌شوند.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'بیشترین بازدید در روز {}اُم پس از انتشار بود: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'بازدیدهای روزانه از {} انباشته می‌شوند؛ پیش از آن سنجیده نشده است.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'تفکیک منابع تازه شروع به سنجش شده است؛ این پست هنوز بازدید برچسب‌خورده‌ای نگرفته است.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'تفکیک دنبال‌کنندگان/کاوش تازه شروع به سنجش شده است؛ هنوز داده‌ای نیست.',
  'Takip edenler': 'دنبال‌کنندگان',
  'Keşiften gelenler': 'از کاوش',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'صفحهٔ سریال/فیلم',
  'Paylaşılan bağlantı': 'پیوند به‌اشتراک‌گذاشته',
  'yeni ölçülüyor': 'سنجش تازه',
  'Kendi ortalamanla aynı düzeyde': 'هم‌سطح میانگین خودت',
  'Kendi ortalamanın %{} üstünde': '{}٪ بالاتر از میانگین خودت',
  'Kendi ortalamanın %{} altında': '{}٪ پایین‌تر از میانگین خودت',
  'Etkileşim oranı': 'نرخ تعامل',
  '(beğeni + yorum) ÷ görüntülenme': '(پسندها + دیدگاه‌ها) ÷ بازدیدها',
  'Toplam görüntülenme': 'کل بازدیدها',
  '{} ile {} arasında toplam {} görüntülenme':
      'بین {} و {}: در مجموع {} بازدید',
  'İstatistikleri gör': 'دیدن آمار',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'برای آماری که به صاحب پست نشان داده می‌شود، به‌صورت شمارنده‌های تجمیعی نگهداری می‌شود: پست چند بار و از کدام سطح (خوراک، پروفایل، خوراک تمام‌صفحه، صفحهٔ سریال/فیلم، پیوند به‌اشتراک‌گذاشته) دیده شده است، آیا بیننده در آن لحظه صاحب پست را دنبال می‌کرده است، رفتن از پست به پروفایل یا محتوا، دنبال‌کردنی که از طریق پست شکل گرفته، اشتراک‌گذاری و باز شدن پردهٔ اسپویل. در این شمارنده‌ها شناسهٔ کاربر، نشانی IP یا مهر زمانی وجود ندارد؛ نمی‌توان پرسید چه کسی چه کاری کرده است.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'برای اینکه بتوان شمرد چند نفر متفاوت یک پست را دیده‌اند، برای هر بیننده یک چکیدهٔ کلیددار برگشت‌ناپذیر (کوتاه‌سازی رمزنگاشتی برگرفته از شناسهٔ کاربر یا نشانی IP) به مدت ۹۰ روز نگهداری می‌شود. به صاحب پست فقط عدد نشان داده می‌شود؛ هویت بینندگان تحت هیچ شرایطی به اشتراک گذاشته نمی‌شود.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': 'به «خواهم دید» منتقل شود؟',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'هر اثری یا دیده می‌شود یا دیده شده است. اگر ادامه بدهی، {} نشانهٔ تماشای تو در این سریال حذف می‌شود.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'هر اثری یا دیده می‌شود یا دیده شده است. اگر ادامه بدهی، نشانهٔ «دیدم» تو در این فیلم برداشته می‌شود.',
  'Sil ve taşı': 'حذف و انتقال',

  // --- Yapım ekibi / firma + seviye unvanları + doğum günü ---
  'Yapım Ekibi': 'عوامل',
  'Yaratıcı': 'سازنده',
  'Yönetmen': 'کارگردان',
  'Senaryo': 'فیلم‌نامه',
  'Yapımcı': 'تهیه‌کننده',
  'Yapım Firmaları': 'شرکت‌های سازنده',
  'Yapım Firması': 'شرکت سازنده',
  'Firma bulunamadı': 'شرکت پیدا نشد',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'این شرکت اثری از این نوع ندارد.',
  'Doğum günün kutlu olsun!': 'تولدت مبارک!',
  'İyi ki doğdun, iyi ki buradasın.':
      'خوب شد که به دنیا آمدی، خوب شد که اینجایی.',
  'Bugün {} yaşına girdin': 'امروز {} ساله شدی',
  'Teşekkürler': 'ممنون',
  'İki Adımlı Doğrulama': 'تأیید دو مرحله‌ای',
  'Girişte e-postana kod gönderilir': 'هنگام ورود، کد به ایمیلت فرستاده می‌شود',
  'Kod {} adresine gönderildi': 'کد به {} ارسال شد',
  '6 haneli kod': 'کد 6 رقمی',
  'Doğrula': 'تأیید',
  'Yeniden gönder': 'ارسال دوباره',
  'Vazgeç': 'انصراف',
  'Yeni kod gönderildi': 'کد جدید ارسال شد',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'هنگام ورود با Google کدی خواسته نمی‌شود؛ Google تأیید خودش را انجام می‌دهد.',
  'Kapatmak için de kod gerekir.': 'برای خاموش کردن هم کد لازم است.',
  'E-postana erişemezsen hesabına giremezsin.':
      'اگر به ایمیلت دسترسی نداشته باشی، نمی‌توانی وارد حسابت شوی.',
  'İki adımlı doğrulama açıldı': 'تأیید دو مرحله‌ای روشن شد',
  'İki adımlı doğrulama kapatıldı': 'تأیید دو مرحله‌ای خاموش شد',
  'Videonun ne kadarı izlendi': 'چه مقدار از ویدیو دیده شد',
  'Videoyu başlatanlar': 'ویدیو را شروع کردند',
  'videonun %{} noktasına ulaştı': 'به {}٪ ویدیو رسیدند',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'نیمی از مخاطبان دست‌کم {}٪ ویدیو را دیده‌اند.',
  'Sonuna kadar izleyen: %{}': 'تا انتها دیدند: {}٪',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'منحنی دست‌کم به {} بازدید نیاز دارد؛ اکنون {} بازدید هست.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'منحنی بر پایه {} بازدید است و به بازه زمانی انتخاب‌شده بستگی ندارد.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'زمان تماشا از {} اندازه‌گیری می‌شود؛ بازدیدهای قدیمی‌تر در این عدد نیستند.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} بازدید. {}٪ به نیمه و {}٪ به پایان رسیدند.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}٪',
  'Seviye {}': 'سطح {}',
  'Sonraki seviyeye {} puan kaldı': '{} امتیاز تا سطح بعدی',
  'Gönderilerin': 'پست‌های تو',
  '{} gönderi': '{} پست',
  '{} gönderi · {} görüntülenme': '{} پست · {} بازدید',
  'önceki {} güne göre': 'نسبت به {} روز پیش',
  'önceki {} güne göre %{} arttı': 'نسبت به {} روز پیش، {}٪ افزایش',
  'önceki {} güne göre %{} azaldı': 'نسبت به {} روز پیش، {}٪ کاهش',
  'önceki {} güne göre değişmedi': 'نسبت به {} روز پیش بدون تغییر',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'بازدید روزانه: کمترین {}، بیشترین {}',
  'Etkileşim oranı henüz ölçülemedi': 'نرخ تعامل هنوز اندازه‌گیری نشده است',
  'Oranlar': 'نرخ‌ها',
  'Beğenme oranı': 'نرخ پسند',
  'Yorum oranı': 'نرخ نظر',
  'Paylaşma oranı': 'نرخ اشتراک‌گذاری',
  'İçeriğe gitme oranı': 'نرخ ضربه روی محتوا',
  'Profile gitme oranı': 'نرخ بازدید پروفایل',
  'Ziyaretten takibe dönüşüm': 'از بازدید تا دنبال‌کردن',
  'beğeni ÷ görüntülenme': 'پسندها ÷ بازدیدها',
  'yorum ÷ görüntülenme': 'نظرها ÷ بازدیدها',
  'paylaşım ÷ görüntülenme': 'اشتراک‌گذاری‌ها ÷ بازدیدها',
  'içeriğe tıklama ÷ görüntülenme': 'ضربه روی محتوا ÷ بازدیدها',
  'profil ziyareti ÷ görüntülenme': 'بازدید پروفایل ÷ بازدیدها',
  'yeni takip ÷ profil ziyareti': 'دنبال‌کردن‌های جدید ÷ بازدید پروفایل',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'نرخ‌ها دست‌کم به {} بازدید نیاز دارند؛ اکنون {} هست.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'نرخ‌ها از عددهای کل عمر پست به دست می‌آید؛ انتخاب روز در پایین آن‌ها را تغییر نمی‌دهد.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'این عددها مجموع کل عمر پست هستند (به‌جز کادرهایی که یادداشت خودشان را دارند)؛ انتخاب روز در پایین فقط نمودار را تغییر می‌دهد.',
  'Ortalama izlenme: videonun %{} kadarı': 'میانگین تماشا: {}٪ از ویدیو',
  'Elde tutma eğrisinin 20 kovasının ortalaması.': 'میانگین 20 بخش منحنی.',
  'Dizi, film, kişi veya şirket ara...': 'سریال، فیلم، شخص یا شرکت جستجو کن...',
  'Şirketler': 'شرکت‌ها',
  'Senarist': 'فیلم‌نامه‌نویس',
  'Bölüm puanları': 'امتیاز قسمت‌ها',
  'S{}': 'ف{}',
  'E{}': 'ق{}',
  'Bölüm puanları yüklenemedi': 'امتیاز قسمت‌ها بارگذاری نشد',
  'Giriş gerekli': 'ورود لازم است',
  'Geçersiz oturum': 'نشست نامعتبر',
  'Oturum sonlandı, tekrar giriş yap': 'نشست تمام شد، دوباره وارد شو',
  'Çok fazla istek; biraz sonra tekrar dene':
      'درخواست‌ها زیاد است؛ کمی بعد دوباره امتحان کن',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'در حال حاضر فضایی روی سرور نیست، کمی بعد دوباره تلاش کن',
  'Devam eden yapımlar ({})': 'آثار در حال پخش ({})',
  'Diziler ({})': 'سریال‌ها ({})',
  'Filmler ({})': 'فیلم‌ها ({})',
  'Tüm yapımlar': 'همه آثار',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'فضای رسانه‌ات پر شده؛ برای باز کردن جا، بارگذاری‌های قدیمی را حذف کن',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'ایمیل/نام کاربری یا رمز عبور اشتباه است',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'این ایمیل یا نام کاربری قبلاً ثبت شده',
  'Google doğrulaması başarısız': 'تأیید گوگل ناموفق بود',
  'Kod geçersiz veya süresi dolmuş': 'کد نامعتبر است یا منقضی شده',
  'Bu kullanıcıyla mesajlaşamazsın': 'نمی‌توانی به این کاربر پیام بدهی',
  'Kendini takip edemezsin': 'نمی‌توانی خودت را دنبال کنی',
  'Bu kullanıcıyı takip edemezsin': 'نمی‌توانی این کاربر را دنبال کنی',
  'Kendini engelleyemezsin': 'نمی‌توانی خودت را مسدود کنی',
  'Yorum 1-1000 karakter olmalı': 'نظر باید ۱ تا ۱۰۰۰ نویسه باشد',
  'Boş mesaj gönderilemez': 'پیام خالی نمی‌توان فرستاد',
  'Yorum bulunamadı': 'نظر پیدا نشد',
  'Şifre hatalı': 'رمز عبور اشتباه است',
  'Şifre en az 6 karakter olmalı': 'رمز عبور باید حداقل ۶ نویسه باشد',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'فقط GIF، PNG، JPEG یا WebP قابل آپلود است',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'انواع مجاز: GIF، PNG، JPEG، WebP، MP4، WebM، صدا',
  'Geçerli bir ZIP dosyası değil': 'فایل ZIP معتبر نیست',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'برای دریافت داده با ایمیل، اول ایمیل را به حساب وصل کن',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'روی این اثر سابقه تماشا داری. برای «می‌خواهم ببینم» اول باید علامت‌ها پاک شوند.',
  'Arama şu anda kapalı': 'تماس‌ها فعلاً خاموش است',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'حساب مهمان نمی‌تواند تماس را روشن کند؛ یک حساب بساز',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'سرور در حال راه‌اندازی دوباره است؛ کمی بعد امتحان کن',
  'Puan 1-10 arası olmalı': 'امتیاز باید بین ۱ و ۱۰ باشد',
  'En fazla 10 medya eklenebilir': 'حداکثر ۱۰ رسانه می‌توان افزود',
  'Bu cihazdan yeni hesap açılamıyor': 'از این دستگاه نمی‌توان حساب ساخت',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'ایمیل معتبر، نام کاربری و رمز حداقل ۶ نویسه لازم است',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'ایمیل معتبر و رمز حداقل ۶ نویسه لازم است',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'نام کاربری ۳–۲۰ نویسه؛ حروف کوچک، رقم، نقطه، خط تیره و زیرخط (نه در دو سر)',
  'Bu hesap zaten bağlı': 'این حساب از قبل متصل است',
  'Hesap oluşturulamadı': 'حساب ساخته نشد',
  'Misafir hesabı oluşturulamadı': 'حساب مهمان ساخته نشد',
  'Hesap bulunamadı': 'حساب پیدا نشد',
  'Bu hesapta e-posta yok': 'این حساب ایمیل ندارد',
  'İki adımlı doğrulama zaten bu durumda':
      'تأیید دو مرحله‌ای از قبل در همین وضعیت است',
  'Kod yanlış': 'کد نادرست است',
  'Kodun süresi doldu': 'اعتبار کد تمام شد',
  'Kullanıcının e-postası yok (misafir hesap)':
      'این کاربر ایمیل ندارد (حساب مهمان)',
  'Bio en fazla 300 karakter olabilir': 'بیو حداکثر ۳۰۰ نویسه',
  'Geçersiz ülke': 'کشور نامعتبر',
  'Geçersiz sosyal bağlantı': 'پیوند اجتماعی نامعتبر',
  'Geçersiz doğum tarihi': 'تاریخ تولد نامعتبر',
  'Liste adı gerekli': 'نام فهرست لازم است',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'نام حداکثر ۶۰، توضیح ۳۰۰ نویسه',
  'Liste bulunamadı': 'فهرست پیدا نشد',
  'Değiştirilecek tercih yok': 'چیزی برای به‌روزرسانی نیست',
  'İnceleme en fazla 2000 karakter olabilir': 'نقد حداکثر ۲۰۰۰ نویسه',
  'Önce içeriği "bitirdim" olarak işaretle':
      'اول آن را به‌عنوان تمام‌شده علامت بزن',
  'Önce kişiyi favorile': 'اول این فرد را به علاقه‌مندی‌ها اضافه کن',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'برای نظر قسمت هم فصل و هم قسمت لازم است',
  'Yanıtlanan yorum bulunamadı': 'نظر پاسخ‌داده‌شده پیدا نشد',
  'Geri bildirim 3-2000 karakter olmalı': 'بازخورد باید ۳–۲۰۰۰ نویسه باشد',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'عنوان و متن لازم است (حداقل ۲ نویسه)',
  'Kendine mesaj gönderemezsin': 'نمی‌توانی به خودت پیام بدهی',
  'Mesaj en fazla 2000 karakter olabilir': 'پیام حداکثر ۲۰۰۰ نویسه',
  'Mesaj 1-2000 karakter olmalı': 'پیام باید ۱–۲۰۰۰ نویسه باشد',
  'Mesaj bulunamadı': 'پیام پیدا نشد',
  'Mesaj bulunamadı veya düzenlenemez': 'پیام پیدا نشد یا ویرایش نمی‌شود',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'فقط پیام‌های ارسال‌شده به تو را می‌توان گزارش کرد',
  'Sebep gerekli': 'دلیل لازم است',
  'İtiraz edilecek aktif bir ceza yok': 'مجازات فعالی برای اعتراض نیست',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'از قبل یک اعتراض در انتظار بررسی داری',
  'Bu ceza için itirazın zaten incelendi': 'اعتراض این مجازات قبلاً بررسی شده',
  'Medya bağlantısının süresi dolmuş': 'لینک رسانه منقضی شد',
  'Bu medya için imzalı bağlantı gerekli':
      'برای این رسانه پیوند امضاشده لازم است',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'سرویس تماس در حال راه‌اندازی دوباره است؛ کمی بعد دوباره امتحان کن',
  'Puan göstergesi': 'راهنمای امتیازها',
  'İzleme İstatistiklerim': 'آمار تماشای من',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'به‌محض اینکه قسمتی یا فیلمی را تماشا‌شده علامت بزنی، آمارت اینجا جمع می‌شود.',
  '{} sa {} dk': '{} ساعت {} دقیقه',
  'Yaklaşık ekran süresi': 'زمان تقریبی تماشا',
  'İzleme serisi': 'زنجیرهٔ تماشا',
  'Şu anki seri': 'زنجیرهٔ فعلی',
  'En uzun seri': 'بلندترین زنجیره',
  'Haftanın günleri': 'روزهای هفته',
  'En çok izlediklerin': 'بیشترین تماشا',
  'Bu dönemde izleme yok': 'در این بازه تماشایی نیست',
  'Paz': 'یک',
  'Pzt': 'دو',
  'Sal': 'سه',
  'Çar': 'چهار',
  'Per': 'پنج',
  'Cum': 'جمعه',
  'Cmt': 'شنبه',
  '{} bölüm': '{} قسمت',
  '{} bölüm~tekil': '{} قسمت',
  '{} kez': '{} بار',
  '{} kez~tekil': '{} بار',
  'Son {} gün · günlük': '{} روز اخیر · روزانه',
  'Son {} gün · haftalık': '{} روز اخیر · هفتگی',
  'Ekran süren, serin ve en çok izlediklerin':
      'زمان تماشا، زنجیره و پرتماشاترین‌هایت',
  'Daralt': 'جمع کردن',
  'Listeyi düzenle': 'ویرایش فهرست',
  'Bitti': 'تمام',
  'Sırala': 'مرتب‌سازی',
  'Herkese göster': 'نمایش به همه',
  'Başkalarından gizle': 'پنهان از دیگران',
  'Listeden kaldır': 'حذف از فهرست',
  'Listeden kaldırılsın mı?': 'از فهرست حذف شود؟',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'این عنوان از فهرست بیرون می‌رود. اگر فقط می‌خواهی پنهانش کنی، از نماد چشم استفاده کن.',
  'Sıralama kaydedilemedi': 'ترتیب ذخیره نشد',
  'Değişiklik kaydedilemedi': 'تغییر ذخیره نشد',
  'Kaldırılamadı': 'حذف نشد',
  'Popülerlik': 'محبوبیت',
  'TMDB puanı': 'امتیاز TMDB',
  'Yapım yılı': 'سال تولید',
  'dizi.jpg puanı': 'امتیاز dizi.jpg',
  'İzlenme': 'بازدیدها',
  'Yorum sayısı': 'تعداد نظرها',
  'Tüm raflara uygulanır': 'برای همه قفسه‌ها اعمال می‌شود',
  'En popüler {} yapım arasında sıralandı': 'میان {} اثر محبوب مرتب شد',
  'Altyazı görünümü': 'ظاهر زیرنویس',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık': 'رنگ، فونت، اندازه، لبه و کدری',
  'Bu bir örnek altyazıdır.': 'این یک زیرنویس نمونه است.',
  'Ayar değiştikçe önizleme anında güncellenir.':
      'با هر تغییر تنظیمات، پیش‌نمایش بی‌درنگ به‌روز می‌شود.',
  'Yazı biçimi': 'سبک متن',
  'Yazı rengi': 'رنگ متن',
  'Yazı opaklığı': 'کدری متن',
  'Yazı tipi': 'فونت',
  'Yazı boyutu': 'اندازه متن',
  'Karakter ayrıtı': 'لبهٔ نویسه‌ها',
  'Ayrıt türü': 'نوع لبه',
  'Ayrıt rengi': 'رنگ لبه',
  'Yok': 'هیچ‌کدام',
  'Dış çizgi': 'خط دور',
  'Gölge': 'سایه',
  'Kabartma': 'برجسته',
  'Oyma': 'فرورفته',
  'Arka plan rengi': 'رنگ پس‌زمینه',
  'Arka plan opaklığı': 'کدری پس‌زمینه',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      'پس‌زمینه همان پُرکنندهٔ درست پشت متن است؛ پنجره سطح گسترده‌تری است پشت کل بلوک زیرنویس.',
  'Pencere': 'پنجره',
  'Pencere rengi': 'رنگ پنجره',
  'Pencere opaklığı': 'کدری پنجره',
  'Altyazı görünümü sıfırlansın mı?': 'ظاهر زیرنویس بازنشانی شود؟',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      'تنظیمات رنگ، فونت، اندازه، لبه و کدری به مقادیر پیش‌فرض برمی‌گردند.',
  'Altyazı görünümü varsayılana döndü': 'ظاهر زیرنویس به پیش‌فرض بازگشت',
  '{} indiriliyor…': 'در حال دانلود {}…',
  'Seçince indirilir': 'با انتخاب دانلود می‌شود',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      'فونت دانلود نشد. با فونت پیش‌فرض نمایش داده می‌شود.',
  'Beyaz': 'سفید',
  'Siyah': 'سیاه',
  'Kırmızı': 'قرمز',
  'Yeşil': 'سبز',
  'Mavi': 'آبی',
  'Sarı': 'زرد',
  'Camgöbeği': 'فیروزه‌ای',
  'Macenta': 'سرخابی',
  'Yapım bütçesi': 'بودجه ساخت',
  'Yapım bütçesi ve dünya çapında hasılat': 'بودجه ساخت و فروش جهانی',
  'Dizinin yayın durumu': 'وضعیت پخش سریال',
  'Devam ediyor': 'در حال پخش',
  'Sona erdi': 'پایان‌یافته',
  'İptal edildi': 'لغو شده',
  'Yapımda': 'در حال ساخت',
  'Planlandı': 'برنامه‌ریزی‌شده',
  'Pilot bölüm': 'قسمت پایلوت',
  'Ad': 'نام',
  'Adın': 'نامت',
  'Kullanıcı adı': 'نام کاربری',
  'Kullanıcı adını değiştir': 'تغییر نام کاربری',
  'Kullanıcı adını 90 günde bir değiştirebilirsin':
      'نام کاربری را هر ۹۰ روز یک بار می‌توانی تغییر دهی',
  'Değiştir': 'تغییر',
  '{} gün sonra değiştirebilirsin': '{} روز دیگر می‌توانی تغییر دهی',
  'Kullanıcı adın: @{}': 'نام کاربری‌ات: @{}',
  'Bu kullanıcı adı zaten alınmış': 'این نام کاربری قبلاً گرفته شده است',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış':
      'این نام کاربری در حال حاضر برای حساب دیگری رزرو شده است',
  'Bu zaten senin kullanıcı adın': 'این همان نام کاربری خودت است',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      'نام کاربری ۳–۲۰ نویسه؛ حروف کوچک، رقم، نقطه، خط تیره و زیرخط',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      'در نمایه بالای نام کاربری‌ات دیده می‌شود. می‌توانی خالی بگذاری.',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      'پس از تغییر تا ۹۰ روز نمی‌توانی دوباره تغییرش دهی. نام کاربری قبلی‌ات ۹۰ روز برایت رزرو می‌ماند — اگر بخواهی می‌توانی برگردی و در این مدت کس دیگری نمی‌تواند آن را بگیرد. پیوندهای نام قدیمی دیگر نمایه‌ات را باز نمی‌کنند.',
  'Etkinliğim': 'فعالیت',
  'Tercihler': 'ترجیحات',
  'Gizlilik ve güvenlik': 'حریم خصوصی و امنیت',
  'Destek': 'پشتیبانی',
  'Hesap': 'حساب',
  '{} dizileri': 'سریال‌های {}',
  '{} filmleri': 'فیلم‌های {}',
  'En üste taşı': 'انتقال به بالا',
  'Sırayı sıfırla': 'بازنشانی ترتیب',
  'Listede ara': 'جستجو در فهرست',
  'Elle sıra sıfırlansın mı?': 'ترتیب دستی بازنشانی شود؟',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      'فهرست به ترتیب پیش‌فرض برمی‌گردد (آخرین موردی که علامت زده‌ای اول).',
  'Sıra sıfırlanamadı': 'ترتیب بازنشانی نشد',
  'Listenin en üstüne taşındı': 'به بالای فهرست منتقل شد',
  'Adlar yükleniyor…': 'در حال بارگذاری نام‌ها…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      'پوستر را نگه دار و بکش. برای جلو آوردن موردی که دور است، از «انتقال به بالا» استفاده کن.',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      'کشیدن در جستجو خاموش است؛ با «انتقال به بالا» جلو بیاور ({} نتیجه).',
  'Görünüm': 'نما',
  'En çok izlediğin filmler': 'پرتماشاترین فیلم‌هایت',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      'زمان‌ها تخمینی‌اند: هر قسمت ~{} دقیقه و هر فیلم ~{} دقیقه حساب می‌شود',
  'Bu kullanıcı adı sistem tarafından ayrılmış':
      'این نام کاربری توسط سیستم رزرو شده است',
  'Ekran süresi': 'زمان تماشا',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir":
      'زمان‌ها مدت‌های واقعی قسمت‌ها و فیلم‌ها از TMDB هستند',
  'Tüm zamanlar: {} bölüm · {} film · {}': 'در کل: {} قسمت · {} فیلم · {}',
  'Kabul et': 'پذیرفتن',
  'Reddedilenler': 'ردشده‌ها',
  'İstekler': 'درخواست‌ها',
  'Reddettiğin istek yok': 'درخواست ردشده‌ای نیست',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      'درخواست‌های ردشده اینجا می‌مانند؛ هر وقت بخواهی می‌توانی دوباره بپذیری.',
  'Ne izlesem?': 'چه تماشا کنم؟',
  'Karışık': 'ترکیبی',
  'Çarkı çevir': 'چرخ را بچرخان',
  'Tekrar çevir': 'دوباره بچرخان',
  'Bu türde içerik yok': 'محتوایی از این نوع نیست',
  'Bütçe': 'بودجه',
  'dizi.jpg AI özeti': 'خلاصه هوش مصنوعی dizi.jpg',
  'Daha fazlasını gör': 'مشاهده بیشتر',
};
