/// Otomatik üretilen çeviri haritası (sv).
const Map<String, String> cevirilerSv = {
  'Hepsini gördün, baştan gösteriyoruz':
      'Du har sett allt, vi visar dig från början',
  'Aktarılacak tanınan veri bulunamadı.':
      'Inga igenkända data att importera hittades.',
  'Arama': 'Sök',
  'Aramaya başla': 'Börja söka',
  'Son aramalar': 'Senaste sökningar',
  'Ayarlar': 'Inställningar',
  'Bağla': 'Koppla',
  'Bio': 'Biografi',
  'Bitirdim': 'Sett klart',
  'Bunları da Beğenebilirsin': 'Du kanske också gillar dessa',
  'Bölüm': 'Avsnitt',
  'Bıraktım': 'Slutat titta',
  'Dil': 'Språk',
  'Dil ara...': 'Sök språk...',
  'Dizi': 'Serie',
  'Dizi ve filmlerini takip et': 'Håll koll på dina serier och filmer',
  'Dizi yorumu': 'Seriekommentar',
  'Dizi, film veya kişi ara...': 'Sök serie, film eller person...',
  'Dosya en fazla 30MB olabilir': 'Filen får vara högst 30MB',
  'Dosya en fazla {}MB olabilir': 'Filen får vara högst {}MB',
  'E-posta': 'E-post',
  'E-posta veya kullanıcı adı': 'E-post eller användarnamn',
  'En az 2 harf yaz': 'Skriv minst 2 bokstäver',
  'Film': 'Film',
  'Film yorumu': 'Filmkommentar',
  'Fotoğraf / video ekle': 'Lägg till foto / video',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'Foto eller GIF — profil- och omslagsbild',
  'Giriş Yap': 'Logga in',
  'Gönder': 'Skicka',
  'Gönderildi': 'Skickat',
  'Haftanın Dizileri': 'Veckans serier',
  'Haftanın Filmleri': 'Veckans filmer',
  'Henüz izleme kaydın yok': 'Du har ingen tittarhistorik än',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'Du har inga listor än — skapa en från Profil-fliken.',
  'Henüz yorum yok.': 'Inga kommentarer än.',
  'Hesabın bağlandı!': 'Ditt konto är kopplat!',
  'Hesabın yok mu? Kayıt ol': 'Har du inget konto? Registrera dig',
  'Hesabını Bağla': 'Koppla ditt konto',
  'Hesap Oluştur': 'Skapa konto',
  'Kapak resmi ekle': 'Lägg till omslagsbild',
  'Kaydet': 'Spara',
  'Kendinden bahset...': 'Berätta om dig själv...',
  'Keşfet': 'Utforska',
  'Kimseyi takip etmiyor': 'Följer ingen',
  'Kişi ara': 'Sök person',
  'Kişi yorumu': 'Personkommentar',
  'Konuk Oyuncular': 'Gästskådespelare',
  'Kullanıcı adı (küçük harf)': 'Användarnamn (små bokstäver)',
  'Kullanıcı adı ara...': 'Sök användarnamn...',
  'Liste adı': 'Listnamn',
  'Listeye Ekle': 'Lägg till i lista',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'Du använder ett gästkonto — koppla din e-post så du inte förlorar dina data!',
  'Misafir olarak devam et': 'Fortsätt som gäst',
  'Oluştur': 'Skapa',
  'Oyuncular': 'Skådespelare',
  'Profil': 'Profil',
  'Profil kaydedildi': 'Profilen sparad',
  'Puanla': 'Betygsätt',
  'Puanı Sil': 'Ta bort betyg',
  'Puanın': 'Ditt betyg',
  'Sezonlar': 'Säsonger',
  'Sunucu hatası ({})': 'Serverfel ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'Kommentar till S{}E{}',
  'Takibi Bırak': 'Sluta följa',
  'Takip': 'Följer',
  'Takip Edilenler': 'Följer',
  'Takip Et': 'Följ',
  'Takipçi': 'Följare',
  'Takipçi yok': 'Inga följare',
  'Takipçiler': 'Följare',
  'Takvim': 'Kalender',
  'Tamam': 'OK',
  'Tekrar Dene': 'Försök igen',
  'Tekrar dene': 'Försök igen',
  'Toplam İzleme Süresi': 'Total skärmtid',
  'Tüm Zamanların En İyileri': 'Bästa genom tiderna',
  'Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da başka uygulamadan gelen ZIP\'i içe aktar.':
      'Exportera alla dina data (historik, betyg, kommentarer, listor) som en TV Time-kompatibel ZIP eller importera en ZIP från en annan app.',
  'Tümünü Kaldır': 'Ta bort alla',
  'Tümünü İzledim': 'Har sett alla',
  'Türk Dizileri': 'Turkiska serier',
  'Veri içe aktar (.zip)': 'Importera data (.zip)',
  'Verilerim': 'Mina data',
  'Verilerimi dışa aktar (e-posta)': 'Exportera mina data (e-post)',
  'Verilerini dışa aktar': 'Exportera dina data',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'Inga kommande avsnitt.\nSätt en serie till "Tittar" från seriesidan och följ nya avsnitt här.',
  'Yapımları': 'Filmografi',
  'Yeni Diziler': 'Nya serier',
  'Yeni Liste': 'Ny lista',
  'Yeni kullanıcı adı (isteğe bağlı)': 'Nytt användarnamn (valfritt)',
  'Yorum': 'Kommentar',
  'Yorumunu yaz...': 'Skriv din kommentar...',
  'Zaten hesabın var mı? Giriş yap': 'Har du redan ett konto? Logga in',
  'ort. {}': 'snitt {}',
  'takip': 'följer',
  'takipçi': 'följare',
  '{} / {} bölüm': '{} / {} avsnitt',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} mån',
  '{} bölüm izlendi': '{} avsnitt sedda',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} min',
  '{} gün': '{} d',
  '{} içerik': '{} titlar',
  '{} içerik · otomatik': '{} titlar · automatisk',
  '{} kayıt atlandı (eşleşmedi).': '{} poster hoppades över (ingen matchning).',
  '{} saat': '{} tim',
  '{} sezon': '{} säsonger',
  '{} yıl': '{} år',
  '{}. Bölüm': 'Avsnitt {}',
  '{}. Sezon': 'Säsong {}',
  'Çıkış Yap': 'Logga ut',
  'Ülke': 'Land',
  'Ülke ara...': 'Sök land...',
  'Ülke seç': 'Välj land',
  'İlk yorumu sen yaz!': 'Skriv den första kommentaren!',
  'İncelemeler': 'Recensioner',
  'İncelemen (isteğe bağlı)': 'Din recension (valfritt)',
  'İptal': 'Avbryt',
  'İzlediklerim': 'Min tittarhistorik',
  'İzledim': 'Sett',
  'İzledin': 'Sett',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'Din tittarhistorik och dina listor sparas; nu kan du logga in från vilken enhet som helst.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'Din tittarhistorik, dina betyg, kommentarer och listor skickas som ZIP till din registrerade e-postadress.',
  'İzleyeceğim': 'Vill se',
  'İzliyorum': 'Tittar',
  'İçe aktarım tamamlandı': 'Importen är klar',
  'Şifre': 'Lösenord',
  '• profil bilgisi': '• profilinfo',
  '• {} dizi durumu': '• {} seriestatusar',
  '• {} izleme kaydı': '• {} tittarposter',
  '• {} liste': '• {} listor',
  '• {} puan': '• {} betyg',
  '• {} yorum': '• {} kommentarer',
  '{}+ yapım': '{}+ titlar',
  'Yorumlar': 'Kommentarer',
  'Yorumlar ({})': 'Kommentarer ({})',
  'Yorumları ({})': 'Kommentarer ({})',
  'Listelerim': 'Mina listor',
  'Nereden izledin?': 'Var såg du den?',
  'Diziye git': 'Gå till serien',
  'TV / Kanal': 'TV / Kanal',
  'Sinema': 'Bio',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'Annat',
  'Akış': 'Flöde',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'Ditt flöde är tomt.\nNär någon kommenterar serierna och filmerna du tittar på visas det här.',
  'Listeleri ({})': 'Deras listor ({})',
  'Liste boş.': 'Den här listan är tom.',
  'Yanıtla': 'Svara',
  '@{} kullanıcısına yanıt veriyorsun': 'Du svarar @{}',
  'İzlediğim Diziler ({})': 'Serier jag sett ({})',
  'İzlediğim Filmler ({})': 'Filmer jag sett ({})',
  'Tümünü gör': 'Visa alla',
  'Bildirimler': 'Aviseringar',
  'Henüz bildirim yok': 'Inga aviseringar än',
  '@{} yorumuna yanıt verdi': '@{} svarade på din kommentar',
  '@{} yorumunu beğendi': '@{} gillade din kommentar',
  '@{} seni takip etti': '@{} följde dig',
  '@{} sana mesaj gönderdi': '@{} skickade ett meddelande',
  'Mesajlar': 'Meddelanden',
  'Mesaj': 'Meddelande',
  'Mesajını yaz...': 'Skriv ett meddelande...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'Inga chattar än.\nÖppna en profil och skicka ett meddelande.',
  'Şifreni mi unuttun?': 'Glömt lösenordet?',
  'Şifreyi Sıfırla': 'Återställ lösenord',
  'E-postadaki kod': 'Kod från mejlet',
  'Yeni şifre': 'Nytt lösenord',
  'Sana Özel': 'För dig',
  '{} özetin': 'Din {}-summering',
  'Yıllık izleme istatistiklerin': 'Din årliga tittarstatistik',
  'Rozetler': 'Utmärkelser',
  'Verdiğin puan': 'Givna betyg',
  'Ortalama puanın': 'Ditt snittbetyg',
  'En çok izlediğin diziler': 'Dina mest sedda serier',
  'İlk Bölüm': 'Första avsnittet',
  '100 Bölüm': '100 avsnitt',
  '1000 Bölüm': '1000 avsnitt',
  'İlk Film': 'Första filmen',
  '50 Film': '50 filmer',
  'İlk Yorum': 'Första kommentaren',
  '25 Yorum': '25 kommentarer',
  '10 Puan': '10 betyg',
  'İlk Takipçi': 'Första följaren',
  '10 Dizi Bitirdin': '10 avklarade serier',
  'İzlemeyi Bıraktım': 'Slutade titta',
  'İzlediği Diziler ({})': 'Serier hen sett ({})',
  'İzlediği Filmler ({})': 'Filmer hen sett ({})',
  '500 Bölüm': '500 avsnitt',
  '5000 Bölüm': '5000 avsnitt',
  '10 Film': '10 filmer',
  '100 Film': '100 filmer',
  '100 Yorum': '100 kommentarer',
  '50 Puan': '50 betyg',
  '100 Puan': '100 betyg',
  '10 Takipçi': '10 följare',
  '50 Takipçi': '50 följare',
  '25 Dizi Bitirdin': '25 avklarade serier',
  '50 Dizi Bitirdin': '50 avklarade serier',
  '10 Beğeni': '10 gillningar',
  '100 Beğeni': '100 gillningar',
  'yazıyor...': 'skriver...',
  'Profil düzeni': 'Profillayout',
  'Konumla ve kırp': 'Justera och beskär',
  'Listeye eklendi': 'Tillagd i listan',
  'Listeyi sil?': 'Ta bort listan?',
  'Sil': 'Ta bort',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'Titeln markeras som aldrig sedd och tas bort från dina listor.',
  'Gelecek bölüm bugün': 'Nästa avsnitt idag',
  'Gelecek bölüm {} gün sonra': 'Nästa avsnitt om {} dagar',
  'Tema': 'Tema',
  'Sistem': 'System',
  'Koyu': 'Mörkt',
  'Açık': 'Ljust',
  'İzleyenler': 'Tittare',
  'Yorumunu yaz... (@ ile etiketle)':
      'Skriv din kommentar... (@ för att tagga)',
  '@{} bir yorumda seni etiketledi': '@{} taggade dig i en kommentar',
  'Mesajı sil': 'Radera meddelande',
  'Mesaj silinemedi': 'Meddelandet kunde inte raderas',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'Länken är ogiltig eller sidan hittades inte',
  'Keşfet\'e dön': 'Tillbaka till Utforska',
  'Düzenle': 'Redigera',
  'Mesajı düzenle': 'Redigera meddelande',
  'Yanıtlanıyor': 'Svarar',
  'düzenlendi': 'redigerat',
  'Fotoğraf': 'Foto',
  'Video': 'Video',
  'İçerik': 'Innehåll',
  'çevrimiçi': 'online',
  'son görülme {} dk önce': 'senast sedd för {} min sedan',
  'son görülme {} saat önce': 'senast sedd för {} tim sedan',
  'son görülme {} gün önce': 'senast sedd för {} d sedan',
  'Yorumlar yüklenemedi': 'Kunde inte läsa in kommentarer',
  'Favori': 'Favorit',
  'Listeye ekle': 'Lägg till i lista',
  'İçerik paylaş': 'Dela innehåll',
  'Kapat': 'Stäng',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'Allt du markerar som sett samlas här.',
  'Henüz sohbetin yok': 'Inga konversationer än',
  'Bir profile girip mesaj gönderebilirsin.':
      'Öppna en profil och skicka ett meddelande.',
  'Listeyi sil': 'Ta bort lista',
  'Puan kaydedilemedi': 'Betyget kunde inte sparas',
  'Nerede İzlenir': 'Var kan man se',
  'Abonelik': 'Prenumeration',
  'Kirala': 'Hyr',
  'Satın al': 'Köp',
  'Hoş geldin!': 'Välkommen!',
  'İzlemek istediğin dizi ve filmleri seç': 'Välj serier och filmer du vill se',
  'Seçtiklerin "İzleyeceğim" listene eklenir':
      'Dina val läggs till i din bevakningslista',
  'Şimdilik atla': 'Hoppa över nu',
  'Devam et': 'Fortsätt',
  '{} ekle': 'Lägg till {}',
  'Şikayet et': 'Anmäl',
  'Engelle': 'Blockera',
  'Engeli kaldır': 'Avblockera',
  'Kullanıcı engellendi': 'Användare blockerad',
  'Engel kaldırıldı': 'Blockering borttagen',
  'Şikayet sebebi': 'Anledning till anmälan',
  'Spam veya yanıltıcı': 'Skräppost eller vilseledande',
  'Taciz veya nefret söylemi': 'Trakasserier eller hatretorik',
  'Uygunsuz / cinsel içerik': 'Olämpligt / sexuellt innehåll',
  'Şiddet veya tehlikeli içerik': 'Våld eller farligt innehåll',
  'Telif hakkı ihlali': 'Upphovsrättsintrång',
  'Şikayetin alındı, teşekkürler': 'Din anmälan har mottagits, tack',
  'Hesabımı Sil': 'Radera mitt konto',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'Ditt konto och all din data (historik, betyg, kommentarer, listor, meddelanden) raderas permanent. Detta kan inte ångras.',
  'Şifreni gir': 'Ange ditt lösenord',
  'Hesabımı kalıcı sil': 'Radera mitt konto permanent',
  'Sesli mesaj': 'Röstmeddelande',
  'Ses gönderilemedi': 'Röstmeddelandet kunde inte skickas',
  'Kaydediliyor…': 'Spelar in…',
  'Ses oynatılamadı': 'Röstmeddelandet kunde inte spelas upp',
  'Oynat': 'Spela upp',
  'Duraklat': 'Pausa',
  'Liste görünümü': 'Listvy',
  'Takvim görünümü': 'Kalendervy',
  'Önceki ay': 'Föregående månad',
  'Sonraki ay': 'Nästa månad',
  'Bu gün bölüm yok': 'Inga avsnitt denna dag',
  'Gizlilik Politikası': 'Integritetspolicy',
  'Son güncelleme: {}': 'Senast uppdaterad: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'Den här policyn förklarar vilka uppgifter som samlas in, hur de används och vilka rättigheter du har när du använder appen dizi.jpg och webbplatsen dizijpg.com.',
  'Topladığımız Veriler': 'Uppgifter vi samlar in',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'Konto: e-postadress, användarnamn och lösenord. Lösenord lagras oåterkalleligt hashade; gästkonton kan användas utan e-post.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'Profil: uppgifter du själv väljer att lägga till, som avatar, omslagsbild, bio och land.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'Användning: din tittarhistorik, dina betyg, kommentarer, listor, reaktioner och favoriter.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'Meddelanden: dina text-, bild- och röstmeddelanden lagras på våra servrar. Meddelanden är inte totalsträckskrypterade; de granskas endast vid en anmälan, i modereringssyfte.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'Uppladdade medier: foton, GIF:ar, videor och röstinspelningar som du lägger till i din profil, dina kommentarer och meddelanden.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'Tekniskt: IP-adress, ungefärlig plats (land/stad), enhetsplattform, appversion och felloggar. Dessa sparas för säkerhet och felsökning.',
  'Bildirimler: push bildirimleri için cihaz token\'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.':
      'Aviseringar: för pushaviseringar sparar vi din enhetstoken och ditt språkval. Du kan när som helst stänga av aviseringar i enhetens inställningar.',
  'Verileri Nasıl Kullanırız': 'Hur vi använder dina uppgifter',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'Vi använder dina uppgifter enbart för att tillhandahålla tjänsten, skydda ditt konto, skicka aviseringar, åtgärda fel och förhindra missbruk. Vi säljer inte dina uppgifter och delar dem inte med någon i reklamsyfte.',
  'Çerezler ve Yerel Depolama': 'Cookies och lokal lagring',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'Vi använder lokal lagring endast för att hålla dig inloggad och komma ihåg val som språk och tema. Det finns inga reklam- eller spårningscookies.',
  'Üçüncü Taraf Hizmetler': 'Tredjepartstjänster',
  'Dizi ve film bilgileri TMDB\'den, izleme sağlayıcı bilgisi JustWatch\'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.':
      'Serie- och filmdata kommer från TMDB, information om streamingtjänster från JustWatch. Pushaviseringar levereras via Google Firebase och webbplatstrafiken skyddas av Cloudflare. För dessa tjänster gäller deras egna integritetspolicyer.',
  'Saklama ve Silme': 'Lagring och radering',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'Dina uppgifter sparas så länge ditt konto finns. Med "Radera mitt konto" i inställningarna kan du radera kontot permanent; dina uppgifter raderas direkt och kopior i säkerhetskopior senast inom 14 dagar. Felloggar raderas automatiskt efter 30 dagar.',
  'Verilerini Ayarlar\'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.':
      'Du kan exportera dina uppgifter som ZIP från inställningarna; arkivet skickas till din e-postadress.',
  'Güvenlik': 'Säkerhet',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'Uppgifter överförs via krypterade anslutningar (HTTPS) och lagras på servrar med begränsad åtkomst.',
  'Çocukların Gizliliği': 'Barns integritet',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg riktar sig inte till barn under 13 år.',
  'Hakların': 'Dina rättigheter',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'Enligt KVKK och GDPR har du rätt att få tillgång till, rätta, radera och flytta dina uppgifter. Skriv till oss om detta: {}',
  'Değişiklikler': 'Ändringar',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'Om policyn ändras publiceras den nya versionen på den här sidan och datumet uppdateras.',
  'Kayıt olarak {} kabul etmiş olursun.':
      'Genom att registrera dig godkänner du {}.',
  'Kullanıcılar': 'Användare',
  'Fotoğrafı değiştir': 'Byt foto',
  'Yeniden konumlandır': 'Justera om',
  'Bir şeyler ters gitti': 'Något gick fel',
  'Sosyal Bağlantılar': 'Sociala länkar',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'Upp till 3 länkar visas på din profil.',
  'Platform seç': 'Välj plattform',
  'Kullanıcı adın': 'Ditt användarnamn',
  'Ekle': 'Lägg till',
  'Kaldır': 'Ta bort',
  'Kopyalandı: {}': 'Kopierat: {}',
  'Geçersiz kullanıcı adı': 'Ogiltigt användarnamn',
  'Bağlantı ekle': 'Lägg till länk',
  'Spoiler olabilir — dokun ve gör':
      'Kan innehålla spoilrar — tryck för att visa',
  'Beğeni': 'Gillanden',
  'Görüntülenme': 'Visningar',
  'Tam ekran': 'Helskärm',
  'Sonuç bulunamadı': 'Inga resultat',
  'Dizi ve Filmler': 'Serier & filmer',
  'Kişiler': 'Personer',
  'Ana Sayfa': 'Hem',
  'Paylaş': 'Dela',
  'Yanıtlar': 'Svar',
  'Yaklaşan Bölümler': 'Kommande avsnitt',
  'Yetişme Listesi': 'Ikapplista',
  'Şunu mu demek istedin': 'Menade du',
  'Spoiler': 'Spoiler',
  'Spoiler — dokun ve gör': 'Spoiler — tryck för att visa',
  'uyum': 'matchning',
  'Uyum': 'Matchning',
  '{} ortak dizi': '{} serier gemensamt',
  '{} ortak film': '{} filmer gemensamt',
  'Bildirim Tercihleri': 'Aviseringsinställningar',
  'Beğeniler': 'Gilla-markeringar',
  'Yeni takipçiler': 'Nya följare',
  'Etiketlenmeler': 'Omnämnanden',
  'Yeniden izledim': 'Sedd igen',
  '{}. kez izlendi': 'Sedd {} gånger',
  'Gönderi bulunamadı': 'Inlägget hittades inte',
  'Gözat': 'Bläddra',
  'Diziler': 'Serier',
  'Filmler': 'Filmer',
  'Tümü': 'Alla',
  'Farklı bir tür seç.': 'Prova en annan genre.',
  'Gizlilik': 'Integritet',
  'İzlediklerimi gizle': 'Dölj vad jag har sett',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'Serier och filmer du har sett visas inte på din profil',
  'Yorumlarımı gizle': 'Dölj mina kommentarer',
  'Profilinde yorumların görünmez': 'Dina kommentarer visas inte på din profil',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'Du kan dölja en enskild serie eller film med chippet "Dölj på min profil" på dess sida.',
  'Geri Bildirim': 'Feedback',
  'Uygulama hakkında görüş ve önerini yaz...':
      'Skriv dina åsikter och förslag om appen...',
  'Teşekkürler! Geri bildirimin alındı.': 'Tack! Din feedback har tagits emot.',
  'Profilimde gizle': 'Dölj på min profil',
  'Yorumları': 'Kommentarer',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'Den här användaren har inte sett något än.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'Den här användaren föredrar att hålla sina kommentarer privata.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'Data: JustWatch',
  'Web Sitesi': 'Webbplats',
  'Diğer uygulamalar': 'Fler appar',
  'Bağlantıyı kopyala': 'Kopiera länk',
  'Henüz kimseyi takip etmiyorsun.': 'Du följer ingen än.',
  'Çevir': 'Översätt',
  'Çeviri şu an yapılamadı': 'Översättning är inte möjlig just nu',
  'Bağlantı açılamadı': 'Länken kunde inte öppnas',
  'Orijinali göster': 'Visa original',
  'Çeviriyi göster': 'Visa översättning',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'Inga avsnitt med annonserat sändningsdatum den här månaden. Datum brukar tillkännages några veckor i förväg och dyker då upp här.',
  'devamı': 'mer',
  'Google ile devam et': 'Fortsätt med Google',
  'Google girişi başarısız': 'Google-inloggningen misslyckades',
  'Veri tasarrufu': 'Datasparläge',
  'Wi-Fi ağında veri tasarrufu': 'Datasparläge på Wi-Fi',
  'Mobil veride veri tasarrufu': 'Datasparläge på mobildata',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'När det är på hämtas inte bilder i förväg, bara den bild du tittar på.',
  'Çocuk güvenliği': 'Barns säkerhet',
  'Türk Filmleri': 'Turkiska filmer',
  'En Yüksek Puanlı Filmler': 'Högst betygsatta filmer',
  'En Yüksek Puanlı Diziler': 'Högst betygsatta serier',
  'En Çok İzlenen Filmler': 'Mest sedda filmer',
  'Popüler Diziler': 'Populära serier',
  'En Çok Kazanan Filmler': 'Mest inkomstbringande filmer',
  'Kült Filmler': 'Kultfilmer',
  'Yeni Filmler': 'Nya filmer',
  'Yorum yap': 'Kommentera',
  'Henüz yorum yok': 'Inga kommentarer än',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'Dina kommentarer om serier och filmer samlas här.',
  'GIF ekle': 'Lägg till GIF',
  'İlk yorumu sen yaz': 'Bli först med att kommentera',
  'Video altyazıları': 'Video undertexter',
  'Videolarda altyazı göster': 'Visa undertexter på videor',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'Meningen som uttalas i videon skrivs på skärmen. Texten är översättning: engelska på turkiskt tal, turkiska på andra språk.',
  "Güncelleme gerekli": "Uppdatering krävs",
  "Yeni sürüm var": "Ny version tillgänglig",
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      "Installera den nya versionen av dizi.jpg för att fortsätta.",
  "Güncelle": "Uppdatera",
  "Daha sonra": "Senare",
};
