/// Otomatik üretilen çeviri haritası (zh).
const Map<String, String> cevirilerZh = {
  'Yorumun bu sayfada görünecek': '你的评论会显示在这个页面上',
  'Hepsini gördün, baştan gösteriyoruz': '您已经看到了这一切，我们从头开始向您展示',
  'Aktarılacak tanınan veri bulunamadı.': '未找到可导入的有效数据。',
  'Arama': '搜索',
  'Aramaya başla': '开始搜索',
  'Son aramalar': '最近搜索',
  'Ayarlar': '设置',
  'Bağla': '绑定',
  'Bio': '简介',
  'Bitirdim': '看完了',
  'Bunları da Beğenebilirsin': '猜你也喜欢',
  'Bölüm': '集',
  'Bıraktım': '弃剧了',
  'Dil': '语言',
  'Dil ara...': '搜索语言...',
  'Dizi': '剧集',
  'Dizi ve filmlerini takip et': '追踪你的剧集和电影',
  'Dizi yorumu': '剧集评论',
  'Dizi, film veya kişi ara...': '搜索剧集、电影或人物...',
  'Dosya en fazla 30MB olabilir': '文件最大 30MB',
  'Dosya en fazla {}MB olabilir': '文件最大 {}MB',
  'E-posta': '邮箱',
  'E-posta veya kullanıcı adı': '邮箱或用户名',
  'En az 2 harf yaz': '至少输入 2 个字符',
  'Film': '电影',
  'Film yorumu': '电影评论',
  'Fotoğraf / video ekle': '添加照片 / 视频',
  'Fotoğraf veya GIF — profil ve kapak resmi': '照片或 GIF — 头像和封面图',
  'Giriş Yap': '登录',
  'Gönder': '发送',
  'Gönderildi': '已发送',
  'Haftanın Dizileri': '本周热门剧集',
  'Haftanın Filmleri': '本周热门电影',
  'Henüz izleme kaydın yok': '还没有观看记录',
  'Henüz listen yok — Profil sekmesinden oluştur.': '还没有片单 — 去个人资料页创建一个吧。',
  'Henüz yorum yok.': '还没有评论。',
  'Hesabın bağlandı!': '账号绑定成功！',
  'Hesabın yok mu? Kayıt ol': '没有账号？注册',
  'Hesabını Bağla': '绑定账号',
  'Hesap Oluştur': '创建账号',
  'Kapak resmi ekle': '添加封面图',
  'Kaydet': '保存',
  'Kendinden bahset...': '介绍一下自己...',
  'Keşfet': '发现',
  'Kimseyi takip etmiyor': '还没有关注任何人',
  'Kişi ara': '搜索人物',
  'Kişi yorumu': '人物评论',
  'Konuk Oyuncular': '特邀演员',
  'Kullanıcı adı (küçük harf)': '用户名（小写）',
  'Kullanıcı adı ara...': '搜索用户名...',
  'Liste adı': '片单名称',
  'Listeye Ekle': '添加到片单',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      '你正在使用游客账号 — 绑定邮箱，别丢了你的数据！',
  'Misafir olarak devam et': '以游客身份继续',
  'Oluştur': '创建',
  'Oyuncular': '演员',
  'Profil': '个人资料',
  'Profil kaydedildi': '资料已保存',
  'Puanla': '评分',
  'Puanı Sil': '删除评分',
  'Puanın': '你的评分',
  'Sezonlar': '季',
  'Sunucu hatası ({})': '服务器错误（{}）',
  'S{} · {}. Bölüm': '第{}季 · 第{}集',
  'S{}B{} yorumu': 'S{}E{} 评论',
  'Takibi Bırak': '取消关注',
  'Takip': '关注',
  'Takip Edilenler': '正在关注',
  'Takip Et': '关注',
  'Takipçi': '粉丝',
  'Takipçi yok': '还没有粉丝',
  'Takipçiler': '粉丝',
  'Takvim': '日历',
  'Tamam': '好的',
  'Tekrar Dene': '重试',
  'Tekrar dene': '重试',
  'Toplam İzleme Süresi': '总观看时长',
  'Tüm Zamanların En İyileri': '史上最佳',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da TV Time / Letterboxd ZIP'ini içe aktar.":
      '将你的全部数据（观看、评分、评论、片单）导出为 TV Time 兼容的 ZIP，或导入 TV Time / Letterboxd 的 ZIP。',
  'Tümünü Kaldır': '全部移除',
  'Tümünü İzledim': '全部标记已看',
  'Türk Dizileri': '土耳其剧集',
  'Veri içe aktar (.zip)': '导入数据（.zip）',
  'Verilerim': '我的数据',
  'Verilerimi dışa aktar (e-posta)': '导出我的数据（邮箱）',
  'Verilerini dışa aktar': '导出你的数据',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      '暂无即将播出的剧集。\n在剧集详情页设为"正在追"，即可在这里追踪新剧集。',
  'Yapımları': '参演作品',
  'Yeni Diziler': '新剧上线',
  'Yeni Liste': '新建片单',
  'Yeni kullanıcı adı (isteğe bağlı)': '新用户名（可选）',
  'Yorum': '评论',
  'Yorumunu yaz...': '写下你的评论...',
  'Zaten hesabın var mı? Giriş yap': '已有账号？登录',
  'ort. {}': '平均 {}',
  'takip': '关注',
  'takipçi': '粉丝',
  '{} / {} bölüm': '{} / {} 集',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} 个月',
  '{} ay~tekil': '{} 个月',
  '{} bölüm izlendi': '已看 {} 集',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} 分钟',
  '{} dk~tekil': '{} 分钟',
  '{} gün': '{} 天',
  '{} gün~tekil': '{} 天',
  '{} içerik': '{} 部作品',
  '{} içerik · otomatik': '{} 部作品 · 自动',
  '{} kayıt atlandı (eşleşmedi).': '{} 条记录已跳过（未匹配）。',
  '{} saat': '{} 小时',
  '{} saat~tekil': '{} 小时',
  '{} sezon': '{} 季',
  '{} yıl': '{} 年',
  '{} yıl~tekil': '{} 年',
  '{}. Bölüm': '第{}集',
  '{}. Sezon': '第{}季',
  'Çıkış Yap': '退出登录',
  'Ülke': '国家/地区',
  'Ülke ara...': '搜索国家/地区...',
  'Ülke seç': '选择国家/地区',
  'İlk yorumu sen yaz!': '来写第一条评论吧！',
  'İncelemeler': '影评',
  'İncelemen (isteğe bağlı)': '你的影评（可选）',
  'İptal': '取消',
  'İzlediklerim': '观看记录',
  'İzledim': '看过',
  'İzledin': '你看过',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      '你的观看记录和片单会被保留；现在可以在任何设备上登录了。',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      '你的观看记录、评分、评论和片单将以 ZIP 形式发送到你注册的邮箱。',
  'İzleyeceğim': '想看',
  'İzliyorum': '正在追',
  'İçe aktarım tamamlandı': '导入完成',
  'Şifre': '密码',
  '• profil bilgisi': '• 个人资料',
  '• {} kitaplık kaydı': '• {} 个片库条目',
  '• {} favori': '• {} 个收藏',
  '• {} izleme kaydı': '• {} 条观看记录',
  '• {} liste': '• {} 个片单',
  '• {} puan': '• {} 个评分',
  '• {} yorum': '• {} 条评论',
  '{}+ yapım': '{}+ 部作品',
  'Yorumlar': '评论',
  'Yorumlar ({})': '评论（{}）',
  'Yorumları ({})': 'TA的评论（{}）',
  'Listelerim': '我的片单',
  'Nereden izledin?': '你在哪里看的？',
  'Diziye git': '前往剧集',
  'TV / Kanal': '电视 / 频道',
  'Sinema': '电影院',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': '其他',
  'Akış': '动态',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      '你的动态是空的。\n有人评论你看的剧集和电影时，会显示在这里。',
  'Listeleri ({})': 'TA的片单（{}）',
  'Liste boş.': '这个片单是空的。',
  'Yanıtla': '回复',
  '@{} kullanıcısına yanıt veriyorsun': '正在回复 @{}',
  'İzlediğim Diziler ({})': '我看过的剧集（{}）',
  'İzlediğim Filmler ({})': '我看过的电影（{}）',
  'Tümünü gör': '查看全部',
  'Bildirimler': '通知',
  'Henüz bildirim yok': '还没有通知',
  '@{} yorumuna yanıt verdi': '@{} 回复了你的评论',
  '@{} yorumunu beğendi': '@{} 赞了你的评论',
  '{} ve {} yorumunu beğendi': '{} 和 {} 赞了你的评论',
  '{} ve {} kişi yorumunu beğendi': '{} 和另外 {} 人赞了你的评论',
  '@{} seni takip etti': '@{} 关注了你',
  '@{} sana mesaj gönderdi': '@{} 给你发了消息',
  'Mesajlar': '消息',
  'Mesaj': '私信',
  'Mesaja eklenecek': '将添加到消息中',
  'Mesajını yaz...': '写消息…',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      '还没有会话。\n打开一个主页发送消息吧。',
  'Şifreni mi unuttun?': '忘记密码？',
  'Şifreyi Sıfırla': '重置密码',
  'E-postadaki kod': '邮件中的验证码',
  'Yeni şifre': '新密码',
  'Sana Özel': '为你推荐',
  '{} özetin': '你的 {} 年度回顾',
  'Yıllık izleme istatistiklerin': '你的年度观看统计',
  'Rozetler': '徽章',
  'Verdiğin puan': '打分次数',
  'Ortalama puanın': '平均评分',
  'En çok izlediğin diziler': '看得最多的剧集',
  'İlk Bölüm': '第一集',
  '100 Bölüm': '100 集',
  '1000 Bölüm': '1000 集',
  'İlk Film': '第一部电影',
  '50 Film': '50 部电影',
  'İlk Yorum': '第一条评论',
  '25 Yorum': '25 条评论',
  '10 Puan': '10 次评分',
  'İlk Takipçi': '第一个粉丝',
  '10 Dizi Bitirdin': '看完 10 部剧',
  'İzlemeyi Bıraktım': '不追了',
  'İzlediği Diziler ({})': 'TA看过的剧集（{}）',
  'İzlediği Filmler ({})': 'TA看过的电影（{}）',
  '500 Bölüm': '500 集',
  '5000 Bölüm': '5000 集',
  '10 Film': '10 部电影',
  '100 Film': '100 部电影',
  '100 Yorum': '100 条评论',
  '50 Puan': '50 次评分',
  '100 Puan': '100 次评分',
  '10 Takipçi': '10 个粉丝',
  '50 Takipçi': '50 个粉丝',
  '25 Dizi Bitirdin': '看完 25 部剧',
  '50 Dizi Bitirdin': '看完 50 部剧',
  '10 Beğeni': '10 个赞',
  '100 Beğeni': '100 个赞',
  'yazıyor...': '正在输入…',
  'ses kaydediyor...': '正在录音…',
  'Profil düzeni': '主页布局',
  'Konumla ve kırp': '调整位置并裁剪',
  'Listeye eklendi': '已加入片单',
  'Listeyi sil?': '删除片单？',
  'Sil': '删除',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      '该作品将被标记为从未观看，并从你的片单中移除。',
  'Gelecek bölüm bugün': '下一集今天播出',
  'Gelecek bölüm {} gün sonra': '下一集 {} 天后播出',
  'Tema': '主题',
  'Sistem': '系统',
  'Koyu': '深色',
  'Açık': '浅色',
  'İzleyenler': '观看用户',
  'Yorumunu yaz... (@ ile etiketle)': '写下你的评论……（@ 来标记）',
  '@{} bir yorumda seni etiketledi': '@{} 在评论中标记了你',
  'Mesajı sil': '删除消息',
  'Mesaj silinemedi': '无法删除消息',
  'Bağlantı geçersiz veya sayfa bulunamadı': '链接无效或页面未找到',
  "Keşfet'e dön": '返回发现',
  'Düzenle': '编辑',
  'Mesajı düzenle': '编辑消息',
  'Yanıtlanıyor': '正在回复',
  'düzenlendi': '已编辑',
  'Fotoğraf': '照片',
  'Video': '视频',
  'İçerik': '内容',
  'çevrimiçi': '在线',
  'son görülme {} dk önce': '{}分钟前在线',
  'son görülme {} saat önce': '{}小时前在线',
  'son görülme {} gün önce': '{}天前在线',
  'Yorumlar yüklenemedi': '无法加载评论',
  'Favori': '收藏',
  'Listeye ekle': '加入列表',
  'İçerik paylaş': '分享内容',
  'Kapat': '关闭',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      '你标记为已看的内容都会汇总在这里。',
  'Henüz sohbetin yok': '还没有对话',
  'Bir profile girip mesaj gönderebilirsin.': '打开一个资料页并发送消息。',
  'Listeyi sil': '删除列表',
  'Puan kaydedilemedi': '无法保存评分',
  'Nerede İzlenir': '观看渠道',
  'Abonelik': '订阅',
  'Kirala': '租赁',
  'Satın al': '购买',
  'Devam et': '继续',
  'Şikayet et': '举报',
  'Engelle': '屏蔽',
  'Engeli kaldır': '取消屏蔽',
  'Kullanıcı engellendi': '已屏蔽用户',
  'Engel kaldırıldı': '已取消屏蔽',
  'Şikayet sebebi': '举报原因',
  'Spam veya yanıltıcı': '垃圾信息或误导',
  'Taciz veya nefret söylemi': '骚扰或仇恨言论',
  'Uygunsuz / cinsel içerik': '不当 / 色情内容',
  'Şiddet veya tehlikeli içerik': '暴力或危险内容',
  'Telif hakkı ihlali': '侵犯版权',
  'Şikayetin alındı, teşekkürler': '已收到你的举报，谢谢',
  'Hesabımı Sil': '删除我的账号',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      '你的账号和所有数据（观看记录、评分、评论、列表、消息）将被永久删除。此操作无法撤销。',
  'Şifreni gir': '输入你的密码',
  'Hesabımı kalıcı sil': '永久删除我的账号',
  'Sesli mesaj': '语音消息',
  'Görüldü': '已读',
  'Gönderi': '帖子',
  'Ses gönderilemedi': '语音消息发送失败',
  'Kaydediliyor…': '录音中…',
  'Ses oynatılamadı': '无法播放语音',
  'Oynat': '播放',
  'Fragmanı oynat': '播放预告片',
  'Altyazıyı aç': '开启字幕',
  'Altyazıyı kapat': '关闭字幕',
  '10 saniye ileri': '快进 10 秒',
  '10 saniye geri': '快退 10 秒',
  'Duraklat': '暂停',
  'Liste görünümü': '列表视图',
  'Takvim görünümü': '日历视图',
  'Önceki ay': '上个月',
  'Sonraki ay': '下个月',
  'Bu gün bölüm yok': '这天没有剧集',
  'Gizlilik Politikası': '隐私政策',
  'Son güncelleme: {}': '最近更新：{}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      '本政策说明你在使用 dizi.jpg 应用和 dizijpg.com 网站时，我们收集哪些数据、如何使用这些数据，以及你拥有哪些权利。',
  'Topladığımız Veriler': '我们收集的数据',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      '账号：电子邮箱、用户名和密码。密码以不可逆的哈希形式存储；访客账号可以不绑定邮箱使用。',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      '个人资料：你自行选择添加的信息，例如头像、封面图、简介和国家/地区。',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      '使用数据：你的观看历史、评分、评论、片单、表情反应和收藏。',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      '消息：你的文字、图片和语音消息保存在我们的服务器上。消息未采用端到端加密；仅在被举报时才会出于审核目的查看。',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      '上传的媒体：你添加到个人资料、评论和消息中的照片、GIF、视频和语音录音。',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      '技术数据：IP 地址、大致位置（国家/城市级别）、设备平台、应用版本和错误日志。这些数据用于安全防护和排查故障。',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      '使用统计：以何种设备类型、操作系统和浏览器访问，会按粗略类别计入每日总计数器；浏览器标识本身不会保存，这些数字也无法关联到具体个人。',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      '通知：为发送推送通知，我们会保存你的设备令牌和语言偏好。你可以随时在设备设置中关闭通知。',
  'Verileri Nasıl Kullanırız': '我们如何使用你的数据',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      '我们仅将你的数据用于提供服务、保护账号、发送通知、修复错误和防止滥用。我们不会出售你的数据，也不会出于广告目的与任何人共享。',
  'Çerezler ve Yerel Depolama': 'Cookie 与本地存储',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      '本地存储仅用于保持你的登录状态，以及记住语言、主题等偏好。没有任何广告或跟踪 Cookie。',
  'Üçüncü Taraf Hizmetler': '第三方服务',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      '剧集和电影数据来自 TMDB，流媒体平台信息来自 JustWatch。推送通知通过 Google Firebase 送达，网站流量由 Cloudflare 保护。这些服务适用其各自的隐私政策。',
  'Saklama ve Silme': '保存与删除',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      '你的数据在账号存续期间保留。通过设置中的“删除我的账号”可以永久删除账号；数据会立即删除，备份中的副本最迟在 14 天内清除。错误日志在 30 天后自动删除。',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      '你可以在设置中将数据导出为 ZIP；压缩包会发送到你的邮箱。',
  'Güvenlik': '安全',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      '数据通过加密连接（HTTPS）传输，并存储在访问受限的服务器上。',
  'Çocukların Gizliliği': '儿童隐私',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg 不面向 13 岁以下的儿童。',
  'Hakların': '你的权利',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      '根据 KVKK 和 GDPR，你有权访问、更正、删除和迁移自己的数据。如需行使这些权利，请联系我们：{}',
  'Değişiklikler': '变更',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      '如本政策发生变更，新版本将发布在本页面，并更新日期。',
  'Kayıt olarak {} kabul etmiş olursun.': '注册即表示你接受{}。',
  'Kullanıcılar': '用户',
  'Fotoğrafı değiştir': '更换照片',
  'Yeniden konumlandır': '重新调整',
  'Bir şeyler ters gitti': '出了点问题',
  'Sosyal Bağlantılar': '社交链接',
  'Profilinde en fazla 3 bağlantı gösterilir.': '个人资料最多显示 3 个链接。',
  'Platform seç': '选择平台',
  'Kullanıcı adın': '你的用户名',
  'Ekle': '添加',
  'Kaldır': '移除',
  'Kopyalandı: {}': '已复制:{}',
  'Geçersiz kullanıcı adı': '用户名无效',
  'Bağlantı ekle': '添加链接',
  'Spoiler olabilir — dokun ve gör': '可能包含剧透 — 点按查看',
  'Beğeni': '点赞',
  'beğeni': '点赞',
  'Beğen': '赞',
  'Görüntülenme': '浏览量',
  'görüntülenme': '浏览量',
  'Tam ekran': '全屏',
  'Arama başarısız': '搜索失败',
  'Sonuç bulunamadı': '没有结果',
  'Dizi ve Filmler': '剧集与电影',
  'Kişiler': '人物',
  'Ana Sayfa': '首页',
  'Paylaş': '分享',
  'Yanıtlar': '回复',
  'Yaklaşan Bölümler': '即将播出',
  'Yetişme Listesi': '补看清单',
  'Şunu mu demek istedin': '你是不是想找',
  'Spoiler': '剧透',
  'Spoiler — dokun ve gör': '剧透 — 点按查看',
  'uyum': '契合度',
  'Uyum': '契合度',
  '{} ortak dizi': '{} 部共同剧集',
  '{} ortak film': '{} 部共同电影',
  'Bildirim Tercihleri': '通知偏好',
  'Beğeniler': '点赞',
  'Yeni takipçiler': '新粉丝',
  'Etiketlenmeler': '提及',
  'Yeniden izledim': '重看了',
  '{}. kez izlendi': '看过 {} 次',
  'Gönderi bulunamadı': '未找到帖子',
  'Gözat': '浏览',
  'Diziler': '剧集',
  'Filmler': '电影',
  'Tümü': '全部',
  'Farklı bir tür seç.': '试试其他类型。',
  'Gizlilik': '隐私',
  'İzlediklerimi gizle': '隐藏我看过的内容',
  'Profilinde izlediğin dizi ve filmler görünmez': '你看过的剧集和电影不会显示在你的个人主页上',
  'Yorumlarımı gizle': '隐藏我的评论',
  'Profilinde yorumların görünmez': '你的评论不会显示在你的个人主页上',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      '想隐藏某一部剧或电影，可以在其页面上使用“在我的主页隐藏”标签。',
  'Geri Bildirim': '意见反馈',
  'Uygulama hakkında görüş ve önerini yaz...': '写下你对应用的意见和建议...',
  'Teşekkürler! Geri bildirimin alındı.': '谢谢！已收到你的反馈。',
  'Profilimde gizle': '在我的主页隐藏',
  'Yorumları': 'TA的评论',
  'Bu kullanıcı henüz bir şey izlememiş.': '该用户还没有观看任何内容。',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.': '该用户选择不公开自己的评论。',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': '数据：JustWatch',
  'Web Sitesi': '网站',
  'Diğer uygulamalar': '更多应用',
  'Bağlantıyı kopyala': '复制链接',
  'Henüz kimseyi takip etmiyorsun.': '你还没有关注任何人。',
  'Çevir': '翻译',
  'Çeviri şu an yapılamadı': '目前无法翻译',
  'Bağlantı açılamadı': '无法打开链接',
  'Orijinali göster': '显示原文',
  'Çeviriyi göster': '显示翻译',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      '本月没有已公布播出日期的剧集。日期通常提前几周公布，公布后会显示在这里。',
  'devamı': '更多',
  'Google ile devam et': '通过 Google 继续',
  'Google girişi başarısız': 'Google 登录失败',
  'Veri tasarrufu': '流量节省',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi 下节省流量',
  'Mobil veride veri tasarrufu': '移动数据下节省流量',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      '开启后不会提前下载照片，只加载你正在看的那一张。',
  'Çocuk güvenliği': '儿童安全',
  'Türk Filmleri': '土耳其电影',
  'En Yüksek Puanlı Filmler': '评分最高的电影',
  'En Yüksek Puanlı Diziler': '评分最高的剧集',
  'En Çok İzlenen Filmler': '观看最多的电影',
  'Popüler Diziler': '热门剧集',
  'En Çok Kazanan Filmler': '票房最高的电影',
  'Kült Filmler': '邪典电影',
  'Yeni Filmler': '新电影',
  'Yorum yap': '评论',
  'Henüz yorum yok': '还没有评论',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.': '你对剧集和电影的评论都会汇集在这里。',
  'GIF ekle': '添加 GIF',
  'İlk yorumu sen yaz': '来写第一条评论吧',
  'Video altyazıları': '视频字幕',
  'Videolarda altyazı göster': '在视频上显示字幕',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      '视频中所说的句子写在屏幕上。文本翻译：土耳其语语音英语，其他语言土耳其语。',
  'Güncelleme gerekli': '需要更新',
  'Yeni sürüm var': '有新版本',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.": '请安装 dizi.jpg 新版本以继续。',
  'Güncelle': '更新',
  'Daha sonra': '稍后',
  'Takvim güncelleniyor': '正在更新日历',
  'Takvim güncellenemedi, eski liste gösteriliyor': '无法更新日历，正在显示旧列表',
  'Bazı diziler yüklenemedi, liste eksik olabilir': '部分剧集加载失败，列表可能不完整',
  'Yenile': '刷新',
  'Devam etmek için giriş yap': '登录后继续',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      '免费账号即可评分、评论并建立你的片库。',
  'Şimdi değil': '暂不',
  'Yorum yazmak için giriş yap': '登录后写评论',
  'Kişilere göndermek için giriş yap': '登录后发送给好友',
  'Beğenenler': '点赞的人',
  'Henüz beğeni yok': '还没有人点赞',
  'Bu gönderiyi ilk beğenen sen ol': '成为第一个点赞的人',
  'Bu gönderiye yanıt': '对这条帖子的回复',
  'Spoiler içeren gönderi': '含剧透的帖子',
  'Görsel gönderi': '图片帖子',
  'Bu yorumu profilimde gizle': '在我的主页隐藏这条评论',
  'Yorum dizi ve film sayfasında durmaya devam eder': '评论仍会保留在剧集和电影页面上',
  'Bu yorumu sil': '删除这条评论',
  'Yorum profilinde gizlendi': '评论已在主页隐藏',
  'Geri al': '撤销',
  'Yorum silinsin mi?': '删除评论？',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      '此评论将在所有地方被永久删除，且无法恢复。',
  'Yorum silindi': '评论已删除',
  'Yorum profilinde tekrar görünüyor': '评论已在你的主页重新显示',
  'Gizlenen yorumun yok': '没有隐藏的评论',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      '在主页的评论标签中长按帖子隐藏后，会显示在这里。',
  'Gizlenen yorumlar': '隐藏的评论',
  'Gönderiye git': '前往帖子',
  'Tekrar göster': '重新显示',
  'Yanıtlarımı gizle': '隐藏我的回复',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      '你在他人帖子下写的回复只有你自己可见',
  'Profilinde gizlediğin yorumları tekrar göster': '重新显示你在主页隐藏的评论',
  'Sıralama': '排序',
  'Önerilen': '推荐',
  'Kronolojik': '按时间',
  'Gelen mesaj istekleri': '收到的消息请求',
  'Mesaj isteğin yok': '没有消息请求',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      '你未关注的人发来的消息会显示在这里。',
  'Çevrimiçi durumumu gizle': '隐藏我的在线状态',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      '其他人将看不到你在消息中的在线状态和最后上线时间',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      '我们最早的用户之一。TA的反馈帮助这款应用成为今天的样子。',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      '你是我们最早的用户之一。你的反馈帮助这款应用成为今天的样子。',
  'İleri': '下一步',
  'Önceki': '上一个',
  'Sonraki': '下一个',
  'Seçilen dosya okunamadı': '无法读取所选文件',
  'Video açılamadı': '无法打开视频',
  'En fazla {} medya seçebilirsin': '最多可以选择 {} 个媒体',
  'Hiçbir medya yüklenemedi': '没有媒体上传成功',
  'Seçimi kaldır': '取消选择',
  'Tek yorumda toplam {} MB medya yükleyebilirsin': '单条评论最多可上传 {} MB 媒体',
  '{} dosya okunamadı': '有 {} 个文件无法读取',
  '{} medya eklendi, {} yüklenemedi': '已添加 {} 个媒体，{} 个失败',
  'Kırp': '裁剪',
  'Çiz': '绘制',
  'Metin': '文字',
  'Emoji': '表情',
  'Yinele': '重做',
  'Daha fazla': '更多',
  'Hazırlanıyor…': '准备中…',
  'Düzenlemeden çık?': '退出编辑？',
  'Yaptığın değişiklikler kaybolacak.': '你所做的更改将会丢失。',
  'Çık': '退出',
  'Serbest çizim': '自由绘制',
  'Ok': '箭头',
  'Dikdörtgen': '矩形',
  'Daire': '圆形',
  'Bulanıklaştır': '模糊',
  'Pikselleştir': '马赛克',
  'Silgi': '橡皮擦',
  'Çizgi kalınlığı': '线条粗细',
  'Saydamlık': '不透明度',
  'Dolgu': '填充',
  'Renk': '颜色',
  'Döndür': '旋转',
  'Yansıt': '翻转',
  'Oran': '比例',
  'Sıfırla': '重置',
  'Serbest': '自由',
  'Metin yaz...': '输入文字...',
  'Hizala': '对齐',
  'Arka plan': '背景',
  'Emoji ara...': '搜索表情...',
  'Son kullanılanlar': '最近使用',
  'İfadeler ve insanlar': '表情与人物',
  'Hayvanlar ve doğa': '动物与自然',
  'Yiyecek ve içecek': '食物与饮料',
  'Etkinlikler': '活动',
  'Seyahat ve yerler': '旅行与地点',
  'Nesneler': '物品',
  'Semboller': '符号',
  'Bayraklar': '旗帜',
  'Görseli düzenle': '编辑图片',
  'Düzenlendi': '已编辑',
  'Düzenlenemedi': '无法编辑',
  'Düzenlenen görsel çok büyük': '编辑后的图片太大',
  'Videoyu düzenle': '编辑视频',
  'Sesi kapat': '静音',
  'Sesi aç': '取消静音',
  'İptal ediliyor…': '正在取消…',
  'Bu biraz sürebilir': '这可能需要一些时间',
  'Video çok büyük': '视频太大',
  'Video hazırlanamadı': '无法准备视频',
  'Başlangıç': '开始',
  'Bitiş': '结束',
  'En çok {} saniye seçebilirsin': '最多可以选择 {} 秒',
  'Dosya en fazla {} MB olabilir': '文件最大 {} MB',
  'Medya ekle': '添加媒体',
  'Seçili medya kalmadı': '未选择媒体',
  'Yorumuna eklemek için fotoğraf veya video seç.': '选择要添加到评论的照片或视频。',
  'Medya seç': '选择媒体',
  'Daha fazla ekle': '添加更多',
  'Medya seçilemedi': '无法选择媒体',
  'Favori oyuncular': '收藏的演员',
  'Henüz favori oyuncun yok': '还没有收藏的演员',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      '打开演员页面，点击右上角的心形图标即可加入这里。',
  '{} yapımdan {} tanesini izledin': '{} 部作品中你看了 {} 部',
  'izledin': '已看',
  'İzlemedin': '未观看',
  'Yapım bulunamadı': '未找到作品',
  'Bu kişinin listelenecek dizi veya filmi yok.': '此人没有可列出的剧集或电影。',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      '观看记录与你的账号绑定，此列表仅属于你。',
  'Hesabın kalıcı olarak askıya alındı': '你的账号已被永久停用',
  'Hesabın geçici olarak askıya alındı': '你的账号已被暂时停用',
  'Hesabın askıya alındı': '你的账号已被停用',
  'Sebep': '原因',
  'Kalan süre': '剩余时间',
  'Süre dolunca hesabın kendiliğinden açılır': '时间结束后账号会自动恢复',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      '在此期间你仍可浏览，但不能发帖、评论或发送消息。',
  'Anladım': '知道了',
  'Ayrıntı': '详情',
  '{} dakika': '{} 分钟',
  'birkaç saniye': '几秒',
  'Karara itiraz et': '对此决定提出申诉',
  'Neden bu cezanın kaldırılması gerektiğini anlat': '说明为什么应该撤销这项处罚',
  'İtirazını gönder': '发送申诉',
  'İtirazın incelemede': '你的申诉正在审核中',
  'İtirazın reddedildi': '你的申诉被驳回',
  'İtirazın alındı, inceleniyor': '已收到你的申诉，正在审核',
  'İtiraz en az 10 karakter olmalı': '申诉至少需要 10 个字符',
  'Yükleniyor...': '加载中...',
  'Bu bölüme puan ver': '给这集评分',
  '{} kişi puanladı': '{} 人评分',
  'Bölüm izlendi olarak işaretlendi': '已将该集标记为已观看',
  'Sesli ara': '语音通话',
  'Görüntülü ara': '视频通话',
  'Çalıyor...': '正在呼叫…',
  'Bağlanıyor...': '正在连接…',
  'Cevapla': '接听',
  // '拒接' yalnız "aramayı reddet" demektir; anahtar artık mesaj isteğini
  // reddetmek için de kullanılıyor — '拒绝' iki bağlamı da karşılar.
  'Reddet': '拒绝',
  'Sessize al': '静音',
  'Hoparlör': '扬声器',
  'Kamerayı kapat': '关闭摄像头',
  'Kamerayı çevir': '切换摄像头',
  'Cevap yok': '无人接听',
  'Arama reddedildi': '通话被拒接',
  'Meşgul': '忙线中',
  'Bağlanılamadı': '无法连接',
  'Arama iptal edildi': '通话已取消',
  'Arama geçmişi': '通话记录',
  'Gelen arama': '来电',
  'Giden arama': '去电',
  'Cevapsız arama': '未接来电',
  'Arama şu anda kullanılamıyor': '通话功能当前不可用',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin': '视频通话暂时关闭，你可以进行语音通话',
  'Bu kullanıcıyı arayamazsın': '你无法呼叫该用户',
  'Aramak için karşılıklı takipleşmelisiniz': '你们需要互相关注才能通话',
  'Bu kullanıcı şu anda aranamıyor': '暂时无法呼叫该用户',
  'Çok fazla cevapsız arama. {} sonra tekrar dene': '未接来电过多。请在 {} 后重试',
  'Zaten bir aramadasın': '你已经在通话中',
  'Arama için mikrofon izni gerekiyor': '通话需要麦克风权限',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor': '视频通话需要摄像头和麦克风权限',
  'Arama başlatılamadı': '无法发起通话',
  'Kullanıcı bulunamadı': '未找到用户',
  'Kendini arayamazsın': '你不能呼叫自己',
  'Arama artık geçerli değil': '该通话已失效',
  'Bu aramanın tarafı değilsin': '你不是此通话的参与者',
  'Arama bulunamadı': '未找到通话',
  'Çok fazla istek, biraz bekle': '请求过于频繁，请稍候',
  'Bağlantı koptu': '连接已断开',
  'Arama süre sınırına ulaştı': '通话已达到时间上限',
  'Arama en fazla 4 saat sürebilir': '单次通话最长 4 小时',
  'Arama sona erdi': '通话已结束',
  'Sesli arama': '语音通话',
  'Görüntülü arama': '视频通话',
  'Gelen aramalar': '来电',
  'Sesli ve görüntülü arama bildirimleri': '语音和视频通话通知',
  '{} sa': '{} 小时',
  'Sesli ve Görüntülü Aramalar': '语音和视频通话',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      '通话内容不会被录制。音频和视频在设备之间以端到端加密（DTLS-SRTP）方式传输；我们的服务器无法解密、监听或保存这些流量。',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      '仅保留通话元数据：与谁、方向、时间和时长。这些记录将在 90 天后自动删除。',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      '如果无法建立直连，音频和视频会以加密状态经过中继服务器（TURN）。中继服务器同样无法解密或记录内容。',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      '麦克风仅在语音或视频通话期间使用，摄像头仅在视频通话期间使用。通话结束后两者都会关闭。',
  'Takip ettiğin {} kişi izledi': '你关注的 {} 人看过',
  'Yorum yaz...': '写评论…',
  'Sıradaki bölüm': '下一集',
  'Doğrulanmış testçi': '已验证测试员',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri': '关注、点赞、回复、消息和标记通知',
  'Sen': '我',
  'Aradığınız kişide sesli arama devre dışı': '对方已关闭语音通话',
  'Aradığınız kişide görüntülü arama devre dışı': '对方已关闭视频通话',
  'Sesli aramalara izin ver': '允许语音通话',
  'Görüntülü aramalara izin ver': '允许视频通话',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      '关闭后没人能给你打语音电话；来电者会看到提示',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      '关闭后没人能给你打视频电话；来电者会看到提示',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      '语音通话已关闭。可在设置 > 隐私中开启。',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      '视频通话已关闭。可在设置 > 隐私中开启。',
  'Sesli ve görüntülü arama': '语音和视频通话',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      '访客账号无法拨打通话。创建账号后即可使用。',
  'Misafir hesaplar aranamaz': '无法呼叫访客账号',
  'Puan dağılımı': '评分分布',
  '{} yıldız': '{} 星',
  'Yakında gelecek': '即将推出',
  '{} {} yayınlandı': '{} {} 已上线',
  'Yeni bölüm yayınlandı': '新一集已上线',
  'Yeni bölümler': '新剧集',
  'Geri': '返回',
  'Karşılamayı kapat': '关闭引导',
  'Adım {} / {}': '第 {} 步 / 共 {} 步',
  'Hadi başlayalım': '开始吧',
  'Kaydet ve devam': '保存并继续',
  '{} tanesini ekle': '添加选中的 {} 部',
  'Şimdilik geç': '暂时跳过',
  'Doğum tarihin ne zaman?': '你的生日是哪天？',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      '我们只是想给你推荐适龄内容，并在生日那天送上祝福。',
  'Gün': '日',
  'Ay': '月',
  'Yıl': '年',
  'Doğum yılımı paylaşmak istemiyorum': '不想公开我的出生年份',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      '你的生日不会公开显示在个人资料上，只用于适龄内容和生日祝福。',
  'Ocak': '1月',
  'Şubat': '2月',
  'Mart': '3月',
  'Nisan': '4月',
  'Mayıs': '5月',
  'Haziran': '6月',
  'Temmuz': '7月',
  'Ağustos': '8月',
  'Eylül': '9月',
  'Ekim': '10月',
  'Kasım': '11月',
  'Aralık': '12月',
  'Verilerini yanında getir': '把你的数据一起带过来',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      '如果你在别的应用里记录过观看，可以搬到这里来，不用从零开始。',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      '选择你导出的 ZIP 文件，把观看记录、评分和片单一起导进来。',
  'Aktarılıyor...': '导入中...',
  'ZIP dosyası seç': '选择 ZIP 文件',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      '不用着急：以后也可以在设置 > 我的数据中完成。',
  'Hangi filmleri izledin?': '你看过哪些电影？',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      '这些是最多人看的。点一下，就加入你的观看记录。',
  'SERİ FİLMLER': '系列电影',
  'Serilerden {} film eklendi': '已从系列中添加 {} 部电影',
  'Film listesi yüklenemedi': '无法加载电影列表',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      '可以先跳过这一步，之后再添加想要的作品。',
  '{} film izlediklerine eklendi': '已将 {} 部电影加入观看记录',
  'Film serileri': '电影系列',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      '如果一个系列你从头看到尾，一键就能全部添加。',
  'Seri bulunamadı': '未找到系列',
  'Daha sonra tekrar deneyebilirsin.': '你可以稍后再试。',
  '{} film': '{} 部电影',
  'Eklendi': '已添加',
  'Tümünü izledim': '全部看过',
  'Peki ya diziler?': '那剧集呢？',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      '标记你看过的；选得越多，我们越能带来相似的作品。',
  'Dizi listesi yüklenemedi': '无法加载剧集列表',
  'Seçtiklerine benzeyenler': '和你的选择相似的作品',
  'Her şey hazır': '一切就绪',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.": '快速看看在 dizi.jpg 你能做些什么。',
  'Profilini tamamla': '完善你的个人资料',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      '你可以在设置里添加简介、头像和封面图。',
  'Takvimin seni bekliyor': '日历在等你',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      '你追的剧有新剧集时会出现在日历里，我们也会发通知提醒你。',
  'Puan ver, yorum yaz': '评分、写评论',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      '一集一集打分，用剧透遮罩写评论，还能创建片单。',
  'Verilerin sende kalır': '数据始终属于你',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      '你的数据只与你的账号绑定，绝不出售。在设置里可以全部下载，也可以彻底删除账号。',
  'Engellenen kullanıcılar': '已屏蔽的用户',
  'Engellediğin kişileri gör, engeli kaldır': '查看你屏蔽的人，或取消屏蔽',
  'Engellediğin kimse yok': '你还没有屏蔽任何人',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      '可以在用户主页的三点菜单中屏蔽对方。',
  '@{} engellensin mi?': '要屏蔽 @{} 吗？',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      '你们将看不到彼此的帖子、评论和主页，消息和通话也无法送达。若你们之间存在关注关系，该关系将被解除；即使日后取消屏蔽，也不会恢复。',
  'Bu kullanıcıyı engelledin': '你已屏蔽该用户',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      '你看不到对方的帖子、评论和消息；对方也看不到你的。',
  '{} yeni bir yapımda: {}': '{} 有新作品：{}',
  'Favori kişinden yeni yapım': '收藏的人有新作品',
  '{} için bildirimler': '{} 的通知',
  'Tüm bildirimler': '全部通知',
  'Uygulamada ve telefonda': '应用内和手机上',
  'Yalnız uygulama içi': '仅应用内',
  'Telefon bildirimi gönderilmez': '不发送手机通知',
  'Kapalı': '关闭',
  'Bu kişi için bildirim yok': '不接收这个人的通知',
  'Favori kişilerin yeni yapımları': '收藏人物的新作品',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      '关闭后没人能给你打语音电话；来电者会看到“已关闭”提示',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      '关闭后没人能给你打视频电话；来电者会看到“已关闭”提示',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': '我的动态',
  'Beğenilerin, yorumların, izlemelerin tek akışta': '你的点赞、评论和观看记录，尽在一处',
  'Henüz hareketin yok': '还没有动态',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      '你点赞、评论和观看过的一切都会汇集在这里。',
  'Bu süzgeçte hareket yok': '此筛选下没有动态',
  'Başka bir tür seç ya da "Hepsi"ne dön.': '选择其他类型，或返回“全部”。',
  'Hepsi': '全部',
  'Puan': '评分',
  'Tepki': '表情回应',
  'İzleme': '观看',
  'Durum': '状态',
  'Liste': '片单',
  'Yorum yaptın': '你发表了评论',
  'Yorumu beğendin': '你点赞了一条评论',
  '{} puan verdin': '你打了 {} 分',
  'Tepki verdin': '你做了回应',
  'Listene ekledin': '你加入了片单',
  'Takip etmeye başladın': '你开始关注',
  '"İzleyeceğim" işaretledin': '标记为“想看”',
  '"İzliyorum" işaretledin': '标记为“正在追”',
  '"Bitirdim" işaretledin': '标记为“看完了”',
  '"Bıraktım" işaretledin': '标记为“弃剧了”',
  'Silinmiş içerik': '内容已删除',
  'şimdi': '刚刚',
  '{} g': '{} 天',
  '{} y': '{} 年',
  'İstatistiklerim': '我的数据',
  'Gönderilerinin görüntülenmesi ve beğenisi': '你的帖子的浏览量和点赞数',
  'Henüz gönderin yok': '你还没有帖子',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      '当你为某部剧集或电影写下评论后，你的浏览量和点赞数就会在这里累积。',
  'Tüm zamanlar': '全部时间',
  'Son {} gün': '最近 {} 天',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      '浏览量历史尚未开始累积；第一天的数据将在明天出现。',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      '浏览量历史自 {} 起开始累积（已有 {} 天数据），因此 {} 天的数字仍不完整。',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.': '点赞历史自 {} 起有记录。',
  'Bu dönemde gösterilecek gönderi yok.': '此期间没有可显示的帖子。',
  'eksik veri': '数据不完整',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      '你在个人主页上看过的剧集和电影、观看计数、观看时长和匹配卡片都不会被他人看到',
  'Takipçi listemi gizle': '隐藏我的粉丝列表',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      '其他人无法看到谁关注了你；你的粉丝数量仍会显示',
  'Takip ettiklerimi gizle': '隐藏我关注的人',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      '其他人无法看到你关注了谁；你的关注数量仍会显示',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.': '该用户选择不公开自己的粉丝。',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      '该用户选择不公开自己关注的人。',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': '帖子数据',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.': '你只能查看自己帖子的数据。',
  'Erişim': '触达',
  'Görüntüleyen': '观看人数',
  'Kaç farklı kişi gördü (son {} gün)': '有多少不同的人看过（最近 {} 天）',
  'Paylaşım': '分享次数',
  'Bu gönderiden sonra': '看完这条帖子后',
  'Profil ziyareti': '主页访问',
  'Yeni takip': '新增关注',
  'İçeriğe tıklama': '内容点击',
  'Spoiler perdesini açan': '揭开剧透遮罩',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      '分享、主页访问、关注、内容点击、来源明细和剧透数据自 {} 起开始累积；更早的数据未被统计。',
  'Zamana yayılmış görüntülenme': '随时间变化的观看',
  'Görüntülenme nereden geldi': '观看来自哪里',
  'Kimler gördü': '谁看到了',
  'Günlük veri henüz birikmeye başlamadı.': '每日数据尚未开始累积。',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      '图表至少需要两天的数据。数据自 {} 起开始累积。',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      '观看最多的是发布后第 {} 天：{}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      '每日观看数据自 {} 起开始累积；更早的数据未被统计。',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      '来源明细刚开始统计；这条帖子还没有收到带标记的观看。',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      '关注者／发现来源明细刚开始统计；目前还没有数据。',
  'Takip edenler': '关注者',
  'Keşiften gelenler': '来自发现',
  'Reels': 'Reels',
  'Dizi/film sayfası': '剧集/电影页面',
  'Paylaşılan bağlantı': '分享的链接',
  'yeni ölçülüyor': '新开始统计',
  'Kendi ortalamanla aynı düzeyde': '与你的平均水平持平',
  'Kendi ortalamanın %{} üstünde': '比你的平均水平高 {}%',
  'Kendi ortalamanın %{} altında': '比你的平均水平低 {}%',
  'Etkileşim oranı': '互动率',
  '(beğeni + yorum) ÷ görüntülenme': '（点赞 + 评论）÷ 观看',
  'Toplam görüntülenme': '总观看次数',
  '{} ile {} arasında toplam {} görüntülenme': '{} 至 {} 期间共 {} 次观看',
  'İstatistikleri gör': '查看数据',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      '为了向帖子作者展示数据，我们以汇总计数器的形式记录：帖子被观看了多少次、来自哪个界面（信息流、个人主页、全屏信息流、剧集/电影页面、分享的链接），观看者当时是否关注了帖子作者，从帖子跳转到主页或内容，通过帖子建立的关注，分享，以及剧透遮罩被揭开的次数。这些计数器不包含用户身份、IP 地址或时间戳；无法查询谁做了什么。',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      '为了统计有多少不同的人看过某条帖子，每位观看者的一个不可逆的带密钥摘要（由用户身份或 IP 地址派生的加密缩略值）会保存 90 天。只向帖子作者展示数字；观看者的身份在任何情况下都不会被分享。',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': '移到“想看”吗？',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      '一个作品要么是待看，要么是看过。继续的话，你在这部剧集中的 {} 条观看记录将被删除。',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      '一个作品要么是待看，要么是看过。继续的话，你在这部电影上的“看过”标记将被移除。',
  'Sil ve taşı': '删除并移动',

  // --- Yapım ekibi + yapım firmaları ---
  'Yapım Ekibi': '制作团队',
  'Yaratıcı': '主创',
  'Yönetmen': '导演',
  'Senaryo': '编剧',
  'Yapımcı': '制片人',
  'Yapım Firmaları': '制作公司',
  'Yapım Firması': '制作公司',
  'Firma bulunamadı': '未找到该公司',
  'Bu firmanın bu türde listelenecek yapımı yok.': '该公司没有此类作品。',
  // --- İzleyici seviyesi ve unvanları (cinsiyetsiz) ---
  // --- Doğum günü kutlama kartı ---
  'Doğum günün kutlu olsun!': '生日快乐！',
  'İyi ki doğdun, iyi ki buradasın.': '很高兴世上有你，也很高兴你在这里。',
  'Bugün {} yaşına girdin': '今天你 {} 岁了',
  'Teşekkürler': '谢谢',
  // --- İki adımlı doğrulama (2FA) ---
  'İki Adımlı Doğrulama': '两步验证',
  'Girişte e-postana kod gönderilir': '登录时会向你的邮箱发送验证码',
  'Kod {} adresine gönderildi': '验证码已发送至 {}',
  '6 haneli kod': '6 位验证码',
  'Doğrula': '验证',
  'Yeniden gönder': '重新发送',
  'Vazgeç': '取消',
  'Yeni kod gönderildi': '新验证码已发送',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      '使用 Google 登录时不会要求输入验证码；Google 会进行自己的验证。',
  'Kapatmak için de kod gerekir.': '关闭时同样需要验证码。',
  'E-postana erişemezsen hesabına giremezsin.': '若无法访问邮箱，将无法登录账号。',
  'İki adımlı doğrulama açıldı': '两步验证已开启',
  'İki adımlı doğrulama kapatıldı': '两步验证已关闭',
  // --- Video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': '观众看到了哪里',
  'Videoyu başlatanlar': '开始观看视频',
  'videonun %{} noktasına ulaştı': '看到了视频的 {}%',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.': '一半观众至少看了视频的 {}%。',
  'Sonuna kadar izleyen: %{}': '看到结尾：{}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      '曲线至少需要 {} 次观看，目前有 {} 次。',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      '曲线基于 {} 次观看，不受所选时间范围影响。',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      '观看时长自 {} 起开始统计，更早的观看不计入。',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} 次观看。{}% 看到视频一半，{}% 看到结尾。',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',

  // --- md.42/26 istatistikler + seviye ---
  'Seviye {}': '等级 {}',
  'Sonraki seviyeye {} puan kaldı': '距离下一等级还差 {} 积分',
  'Gönderilerin': '你的帖子',
  '{} gönderi': '{} 条帖子',
  '{} gönderi · {} görüntülenme': '{} 条帖子 · {} 次浏览',
  'önceki {} güne göre': '与前 {} 天相比',
  'önceki {} güne göre %{} arttı': '与前 {} 天相比增长 {}%',
  'önceki {} güne göre %{} azaldı': '与前 {} 天相比下降 {}%',
  'önceki {} güne göre değişmedi': '与前 {} 天相比没有变化',
  'Günlük görüntülenme: en düşük {}, en yüksek {}': '每日浏览量：最低 {}，最高 {}',
  'Etkileşim oranı henüz ölçülemedi': '暂时无法计算互动率',
  'Oranlar': '各项比率',
  'Beğenme oranı': '点赞率',
  'Yorum oranı': '评论率',
  'Paylaşma oranı': '分享率',
  'İçeriğe gitme oranı': '内容点击率',
  'Profile gitme oranı': '主页访问率',
  'Ziyaretten takibe dönüşüm': '访问转关注率',
  'beğeni ÷ görüntülenme': '点赞 ÷ 浏览量',
  'yorum ÷ görüntülenme': '评论 ÷ 浏览量',
  'paylaşım ÷ görüntülenme': '分享 ÷ 浏览量',
  'içeriğe tıklama ÷ görüntülenme': '内容点击 ÷ 浏览量',
  'profil ziyareti ÷ görüntülenme': '主页访问 ÷ 浏览量',
  'yeni takip ÷ profil ziyareti': '新增关注 ÷ 主页访问',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      '比率至少需要 {} 次浏览，目前有 {} 次。',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      '比率来自帖子的全期总数，下方的天数选择不会改变它们。',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      '这些数字是帖子的全期总数（带有单独说明的方框除外），下方的天数选择只会改变图表。',
  'Ortalama izlenme: videonun %{} kadarı': '平均观看：视频的 {}%',
  'Elde tutma eğrisinin 20 kovasının ortalaması.': '留存曲线 20 个区间的平均值。',
  'Dizi, film, kişi veya şirket ara...': '搜索剧集、电影、人物或公司...',
  'Şirketler': '公司',
  'Senarist': '编剧',
  'Bölüm puanları': '分集评分',
  'S{}': '第{}季',
  'E{}': '第{}集',
  'Bölüm puanları yüklenemedi': '无法加载分集评分',
  'Giriş gerekli': '需要登录',
  'Geçersiz oturum': '会话无效',
  'Oturum sonlandı, tekrar giriş yap': '会话已结束，请重新登录',
  'Çok fazla istek; biraz sonra tekrar dene': '请求过多，稍后再试',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene': '服务器暂时没有空间，请稍后再试',
  'Devam eden yapımlar ({})': '正在播出的作品（{}）',
  'Diziler ({})': '剧集（{}）',
  'Filmler ({})': '电影（{}）',
  'Tüm yapımlar': '全部作品',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      '你的媒体空间已满，请删除旧上传内容以释放空间',
  'E-posta/kullanıcı adı veya şifre hatalı': '邮箱/用户名或密码不正确',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı': '该邮箱或用户名已被注册',
  'Google doğrulaması başarısız': 'Google 验证失败',
  'Kod geçersiz veya süresi dolmuş': '验证码无效或已过期',
  'Bu kullanıcıyla mesajlaşamazsın': '无法向该用户发私信',
  'Kendini takip edemezsin': '不能关注自己',
  'Bu kullanıcıyı takip edemezsin': '无法关注该用户',
  'Kendini engelleyemezsin': '不能拉黑自己',
  'Yorum 1-1000 karakter olmalı': '评论须为 1–1000 个字符',
  'Boş mesaj gönderilemez': '不能发送空消息',
  'Yorum bulunamadı': '找不到评论',
  'Şifre hatalı': '密码错误',
  'Şifre en az 6 karakter olmalı': '密码至少 6 个字符',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir': '仅可上传 GIF、PNG、JPEG 或 WebP',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      '支持的类型：GIF、PNG、JPEG、WebP、MP4、WebM、音频',
  'Geçerli bir ZIP dosyası değil': '不是有效的 ZIP 文件',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      '要邮件收取数据，请先绑定邮箱',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      '该作品已有观看记录。要标为“想看”，须先清除观看标记。',
  'Arama şu anda kapalı': '通话功能目前关闭',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      '访客账号无法开启通话；注册后即可使用',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene': '服务器正在重启，请稍后再试',
  'Puan 1-10 arası olmalı': '评分须为 1 到 10',
  'En fazla 10 medya eklenebilir': '最多可添加 10 个媒体文件',
  'Bu cihazdan yeni hesap açılamıyor': '此设备无法创建新账号',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      '需要有效邮箱、用户名和至少 6 位密码',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli': '需要有效邮箱和至少 6 位密码',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      '用户名须为 3–20 个字符；可用小写字母、数字、点、连字符和下划线（首尾不能是点或连字符）',
  'Bu hesap zaten bağlı': '该账号已绑定',
  'Hesap oluşturulamadı': '无法创建账号',
  'Misafir hesabı oluşturulamadı': '无法创建访客账号',
  'Hesap bulunamadı': '找不到账号',
  'Bu hesapta e-posta yok': '该账号没有邮箱',
  'İki adımlı doğrulama zaten bu durumda': '两步验证已是该状态',
  'Kod yanlış': '验证码错误',
  'Kodun süresi doldu': '验证码已过期',
  'Kullanıcının e-postası yok (misafir hesap)': '该用户没有邮箱（访客账号）',
  'Bio en fazla 300 karakter olabilir': '简介最多 300 个字符',
  'Geçersiz ülke': '国家无效',
  'Geçersiz sosyal bağlantı': '社交链接无效',
  'Geçersiz doğum tarihi': '出生日期无效',
  'Liste adı gerekli': '需要列表名称',
  'Ad en fazla 60, açıklama 300 karakter olabilir': '名称最多 60 字，简介 300 字',
  'Liste bulunamadı': '找不到列表',
  'Değiştirilecek tercih yok': '没有可更新的设置',
  'İnceleme en fazla 2000 karakter olabilir': '评论最多 2000 个字符',
  'Önce içeriği "bitirdim" olarak işaretle': '请先把这部作品标为已看完',
  'Önce kişiyi favorile': '请先把该人物加入收藏',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli': '剧集评论需要同时提供季和集',
  'Yanıtlanan yorum bulunamadı': '找不到被回复的评论',
  'Geri bildirim 3-2000 karakter olmalı': '反馈须为 3–2000 个字符',
  'Başlık ve metin gerekli (en az 2 karakter)': '需要标题和正文（至少 2 个字符）',
  'Kendine mesaj gönderemezsin': '不能给自己发私信',
  'Mesaj en fazla 2000 karakter olabilir': '消息最多 2000 个字符',
  'Mesaj 1-2000 karakter olmalı': '消息须为 1–2000 个字符',
  'Mesaj bulunamadı': '找不到消息',
  'Mesaj bulunamadı veya düzenlenemez': '找不到消息或无法编辑',
  'Yalnız sana gelen mesajı şikayet edebilirsin': '只能举报发给你的消息',
  'Sebep gerekli': '需要原因',
  'İtiraz edilecek aktif bir ceza yok': '没有可申诉的有效处罚',
  'Zaten incelenmeyi bekleyen bir itirazın var': '你已有一条待审申诉',
  'Bu ceza için itirazın zaten incelendi': '对此处罚的申诉已审过',
  'Medya bağlantısının süresi dolmuş': '媒体链接已过期',
  'Bu medya için imzalı bağlantı gerekli': '此媒体需要带签名的链接',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene': '通话服务正在重启，稍后再试',
  'Puan göstergesi': '评分图例',
  'İzleme İstatistiklerim': '我的观看统计',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      '把一集剧或一部电影标记为已观看后，你的统计数据就会在这里累积。',
  '{} sa {} dk': '{} 小时 {} 分钟',
  'Yaklaşık ekran süresi': '大致观看时长',
  'İzleme serisi': '连续观看',
  'Şu anki seri': '当前连续',
  'En uzun seri': '最长连续',
  'Haftanın günleri': '每周各天',
  'En çok izlediklerin': '看得最多',
  'Bu dönemde izleme yok': '此期间没有观看记录',
  'Paz': '周日',
  'Pzt': '周一',
  'Sal': '周二',
  'Çar': '周三',
  'Per': '周四',
  'Cum': '周五',
  'Cmt': '周六',
  '{} bölüm': '{} 集',
  '{} bölüm~tekil': '{} 集',
  '{} kez': '{} 次',
  '{} kez~tekil': '{} 次',
  'Son {} gün · günlük': '最近 {} 天 · 按天',
  'Son {} gün · haftalık': '最近 {} 天 · 按周',
  'Ekran süren, serin ve en çok izlediklerin': '你的观看时长、连续记录和最常看的作品',
  'Daralt': '收起',
  'Listeyi düzenle': '编辑列表',
  'Bitti': '完成',
  'Sırala': '重新排序',
  'Herkese göster': '对所有人显示',
  'Başkalarından gizle': '对他人隐藏',
  'Listeden kaldır': '从列表中移除',
  'Listeden kaldırılsın mı?': '要从列表中移除吗？',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      '该作品将从列表中移除。如果只想隐藏，请使用眼睛图标。',
  'Sıralama kaydedilemedi': '无法保存顺序',
  'Değişiklik kaydedilemedi': '无法保存更改',
  'Kaldırılamadı': '无法移除',
  'Popülerlik': '热门程度',
  'TMDB puanı': 'TMDB 评分',
  'Yapım yılı': '出品年份',
  'dizi.jpg puanı': 'dizi.jpg 评分',
  'İzlenme': '观看数',
  'Yorum sayısı': '评论数',
  'Tüm raflara uygulanır': '适用于所有栏目',
  'En popüler {} yapım arasında sıralandı': '已在最热门的 {} 部作品中排序',
  'Altyazı görünümü': '字幕外观',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık': '颜色、字体、大小、边缘和不透明度',
  'Bu bir örnek altyazıdır.': '这是一条示例字幕。',
  'Ayar değiştikçe önizleme anında güncellenir.': '更改设置时预览会即时更新。',
  'Yazı biçimi': '文字样式',
  'Yazı rengi': '文字颜色',
  'Yazı opaklığı': '文字不透明度',
  'Yazı tipi': '字体',
  'Yazı boyutu': '文字大小',
  'Karakter ayrıtı': '字符边缘',
  'Ayrıt türü': '边缘类型',
  'Ayrıt rengi': '边缘颜色',
  'Yok': '无',
  'Dış çizgi': '轮廓',
  'Gölge': '阴影',
  'Kabartma': '凸起',
  'Oyma': '凹陷',
  'Arka plan rengi': '背景颜色',
  'Arka plan opaklığı': '背景不透明度',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      '背景是紧贴文字后面的填充；窗口则是整个字幕块后面更大的表面。',
  'Pencere': '窗口',
  'Pencere rengi': '窗口颜色',
  'Pencere opaklığı': '窗口不透明度',
  'Altyazı görünümü sıfırlansın mı?': '要重置字幕外观吗？',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      '颜色、字体、大小、边缘和不透明度设置将恢复为默认值。',
  'Altyazı görünümü varsayılana döndü': '字幕外观已恢复默认',
  '{} indiriliyor…': '正在下载 {}…',
  'Seçince indirilir': '选择后下载',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      '无法下载字体。正在使用默认字体显示。',
  'Beyaz': '白色',
  'Siyah': '黑色',
  'Kırmızı': '红色',
  'Yeşil': '绿色',
  'Mavi': '蓝色',
  'Sarı': '黄色',
  'Camgöbeği': '青色',
  'Macenta': '品红',
  'Yapım bütçesi': '制作预算',
  'Yapım bütçesi ve dünya çapında hasılat': '制作预算与全球票房',
  'Dizinin yayın durumu': '剧集播出状态',
  'Devam ediyor': '更新中',
  'Sona erdi': '已完结',
  'İptal edildi': '已取消',
  'Yapımda': '制作中',
  'Planlandı': '已计划',
  'Pilot bölüm': '试播集',
  'Ad': '昵称',
  'Adın': '你的昵称',
  'Kullanıcı adı': '用户名',
  'Kullanıcı adını değiştir': '修改用户名',
  'Kullanıcı adını 90 günde bir değiştirebilirsin': '用户名每 90 天可以修改一次',
  'Değiştir': '修改',
  '{} gün sonra değiştirebilirsin': '{} 天后可以修改',
  'Kullanıcı adın: @{}': '你的用户名：@{}',
  'Bu kullanıcı adı zaten alınmış': '该用户名已被占用',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış': '该用户名目前已保留给其他账号',
  'Bu zaten senin kullanıcı adın': '这已经是你的用户名了',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      '用户名须为 3–20 个字符；可用小写字母、数字、点、连字符和下划线',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      '显示在个人资料中用户名的上方。可以留空。',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      '修改后 90 天内不能再次修改。你的旧用户名会为你保留 90 天——期间你可以改回去，别人也无法占用。指向旧用户名的链接将不再打开你的主页。',
  'Etkinliğim': '我的活动',
  'Tercihler': '偏好设置',
  'Gizlilik ve güvenlik': '隐私与安全',
  'Destek': '帮助与支持',
  'Hesap': '账号',
  '{} dizileri': '{}的剧集',
  '{} filmleri': '{}的电影',
  'En üste taşı': '移到最前',
  'Sırayı sıfırla': '重置顺序',
  'Listede ara': '在列表中搜索',
  'Elle sıra sıfırlansın mı?': '要重置手动排序吗？',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      '列表将恢复默认顺序（最近标记的排在前面）。',
  'Sıra sıfırlanamadı': '无法重置顺序',
  'Listenin en üstüne taşındı': '已移到列表最前',
  'Adlar yükleniyor…': '正在加载名称…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      '长按海报即可拖动。想把靠后的作品提到前面，请用“移到最前”。',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      '搜索时无法拖动；用“移到最前”把它提到前面（{} 个结果）。',
  'Görünüm': '视图',
  'En çok izlediğin filmler': '看得最多的电影',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      '时长为估算：每集约 {} 分钟，每部电影约 {} 分钟',
  'Bu kullanıcı adı sistem tarafından ayrılmış': '该用户名目前已由系统保留',
  'Ekran süresi': '观看时长',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir": '时长为 TMDB 上剧集和电影的真实时长',
  'Tüm zamanlar: {} bölüm · {} film · {}': '历史累计：{} 集 · {} 部电影 · {}',
  'Kabul et': '接受',
  'Reddedilenler': '已拒绝',
  'İstekler': '请求',
  'Reddettiğin istek yok': '没有已拒绝的请求',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      '已拒绝的请求会保留在这里，你可以随时重新接受。',
  'Ne izlesem?': '看什么好？',
  'Karışık': '混合',
  'Çarkı çevir': '转动转盘',
  'Tekrar çevir': '再转一次',
  'Bu türde içerik yok': '没有此类型的内容',
  'Bütçe': '预算',
  'dizi.jpg AI özeti': 'dizi.jpg AI 摘要',
  'Daha fazlasını gör': '查看更多',
  'Yıldız sistemi': '星级制',
  '{} yıldız üzerinden': '满分{}星',
  'Önizleme': '预览',
  'dokununca açılır': '点按打开',
  'Bir azalt': '减一',
  'Bir artır': '加一',
  'Ölçek kaydedilemedi': '无法保存评分制',
  'Ölçeği değiştirmek puanlarını silmez; aynı puanlar yeni ölçekte gösterilir.':
      '更改评分制不会删除你的评分，同样的评分会按新制显示。',
  'En aşağıya gönder': '移到最下方',
  'Listenin en altına taşındı': '已移到列表最下方',
  'Oturumun sonlandı': '你的会话已结束',
  'Bu hesabın oturumları kapatıldı ya da şifresi değişti. Devam etmek için tekrar giriş yap.':
      '此账号已在所有设备退出登录，或密码已更改。请重新登录以继续。',
  'Son izleme: {}': '最近观看：{}',
  '{} tarihinde izledin': '观看于 {}',
  'Geri bildirimine yanıt verdik': '我们回复了你的反馈',
  'Bu yanıt artık görüntülenemiyor.': '此回复已无法显示。',
  'Gönderdiğin geri bildirim': '你发送的反馈',
  'Dizi veya film seç (zorunlu)': '选择剧集或电影（必选）',
  'Bölüm seç (isteğe bağlı)': '选择单集（可选）',
  '{}. sezon {}. bölüm': '第 {} 季第 {} 集',
  'Ne düşünüyorsun?': '你怎么看？',
  '{}/{} yükleniyor': '正在上传 {}/{}',
  'Fotoğraf/video ekle': '添加照片或视频',
  'Paylaşmak için önce bir dizi veya film seç.': '请先选择要分享的剧集或电影。',
  'Sezon seç': '选择季',
  '{}. sezon': '第 {} 季',
  'Bölüm seçme (yalnız dizi hakkında)': '不选单集（仅关于该剧）',
  'Sezonlar yüklenemedi.': '无法加载季信息。',
  'Bu dizide bölüm bilgisi yok.': '该剧没有单集信息。',
  'Bu sezonda bölüm yok.': '本季没有单集。',
  '{}. bölüm': '第 {} 集',
  'Dizi veya film ara...': '搜索剧集和电影...',
  'İzlediğin dizi ve film hakkında yorum paylaş': '分享你看过的剧集或电影的感想',
  'Yapım seç (zorunlu)': '选择作品（必选）',
  'Paylaşmak için önce bir yapım seç.': '请先选择要分享的作品。',
  'Kişi': '人物',
  'Yapım firması': '制作公司',
  'Yapım ara...': '搜索作品...',
  'Çarkı çevirmek için sürükle veya dokun': '拖动或点击转动转盘',
  'Arşiv': '归档',
  'Yüklediklerim': '我的上传',
  'GIF ara...': '搜索 GIF...',
  'GIF yükle': '上传 GIF',
  'GIF etiketleri': 'GIF 标签',
  'Virgülle ayır. Aramada bu kelimelerle bulunur.': '用逗号分隔。搜索时靠这些词找到它。',
  'gülme, alkış, şaşkın': '大笑、鼓掌、惊讶',
  'Yükle': '上传',
  'Henüz GIF yok': '还没有 GIF',
  'Bu aramaya uyan GIF yok': '没有符合此搜索的 GIF',
  'Arşiv yeni. İlk GIF i sen yükle — sen hemen kullanırsın, onaydan sonra herkes görür.':
      '归档是新的。第一个 GIF 由你上传——你可以立刻使用，通过审核后所有人都能看到。',
  'GIF yüklendi. Sen hemen kullanabilirsin; herkese açık arşive onaydan sonra girer.':
      'GIF 已上传。你可以立刻使用；通过审核后才会进入公开归档。',
  'Onay bekliyor': '等待审核',
  'GIF listesi yüklenemedi': '无法加载 GIF 列表',
  'GIF yüklenemedi': '无法上传 GIF',
  'Bu GIF i şikayet et': '举报此 GIF',
  'Uygunsuz içerik yöneticiye bildirilir ve arşivden kaldırılabilir.':
      '不当内容会上报给管理员，并可能从归档中移除。',
  'Şikayetin alındı': '举报已收到',
  'Şikayet gönderilemedi': '举报发送失败',
  'Dizinin kendisi': '剧集本身',
  'Sezon ya da bölüm seçme': '不选季或集',
  'Tüm {}. sezon': '整个第 {} 季',
  'Bölüm seçme': '不选集',
  'En fazla {} yapım ekleyebilirsin.': '最多可以添加 {} 个作品。',
  'Bu zaten ekli.': '已经添加过了。',
  'Dizi, film, oyuncu ya da yönetmen etiketle — gönderin onların sayfasında da görünür.':
      '标记剧集、电影、演员或导演——你的帖子也会出现在他们的页面上。',
  'Etiket ekle': '添加标记',
  'Dizi, film, oyuncu ya da yönetmen etiketle': '标记剧集、电影、演员或导演',
  'Gönderiden vazgeç': '放弃这条帖子',
  'Yazdıkların kaydedilmeyecek.': '你写的内容不会被保存。',
  'Yazmaya devam et': '继续写',
  'Bulunamadı. Adın yazılışını değiştirip dene.': '没找到。换一种写法试试。',
  'Dizi, film, oyuncu, yönetmen ya da yapım firması ara.':
      '搜索剧集、电影、演员、导演或制片公司。',
  'E-posta adresini değiştir': '更改你的邮箱地址',
  'E-posta bağlı değil': '尚未绑定邮箱',
  'Geçerli bir e-posta adresi yaz': '请输入有效的邮箱地址',
  'Bu zaten hesabının e-posta adresi': '这已经是你账号的邮箱地址',
  'Kod gönder': '发送验证码',
  'E-posta adresin güncellendi': '你的邮箱地址已更新',
  'Bu e-posta başka bir hesapta kayıtlı': '该邮箱已注册到另一个账号',
  'Doğrulama kodu YENİ adrese gönderilir; adres ancak kodu girdikten sonra değişir. Şifre sıfırlama ve iki adımlı giriş kodları bundan sonra yeni adrese gider.':
      '验证码会发送到新地址，只有输入验证码后地址才会更改。此后密码重置和两步登录的验证码也会发送到新地址。',
  'Hesabındaki e-posta adresi geçerli değil, bu yüzden e-posta teslim edilemiyor. Doğru adresi bağlamak için destekle iletişime geç.':
      '你账号上的邮箱地址无效，因此无法投递邮件。请联系支持以绑定正确的地址。',
  'Bu adrese kod gönderilemedi, adresi kontrol et': '无法向该地址发送验证码，请检查地址',
  'ya da': '或',
  'Google ile doğrula': '用 Google 验证',
  'Hesabını Google ile açtıysan şifren yoktur; kimliğini Google ile doğrula.':
      '如果你的账号是用 Google 创建的，就没有密码；请用 Google 验证身份。',
  'Google doğrulaması bu hesapla eşleşmedi': 'Google 验证与此账号不匹配',
  'Bu hesap Google ile açıldı; doğrulamak için Google ile giriş yap':
      '此账号是用 Google 创建的；请用 Google 登录以验证',
  // --- 31 Agu 2026: kitaplik paylasimi + reels ceviri + sohbet detayi ---
  'Bu liste gizli': '此列表为私密',
  'Bu kullanıcı izleme listelerini gizli tutmayı tercih ediyor.':
      '该用户选择将其片单设为私密。',
  'Bu listede henüz içerik yok': '此列表暂无作品',
  'Otomatik çeviri': '自动翻译',
  'Otomatik çeviri açıldı': '已开启自动翻译',
  'Otomatik çeviri kapatıldı': '已关闭自动翻译',
  'Sohbet sessize alındı': '聊天已静音',
  'Sessize alma kaldırıldı': '已取消静音',
  'Tema özelleştir': '自定义主题',
  'Sohbette ara': '在聊天中搜索',
  'Mesajlarda ara...': '搜索消息...',
  'Sonuç yok': '无结果',
  'Profili gör': '查看资料',
  'Medya ve dosyalar': '媒体与文件',
  'Henüz medya yok': '暂无媒体',
  'Varsayılan': '默认',
  'Mor': '紫色',
  'Pembe': '粉色',
  'Turuncu': '橙色',
  'Orijinal metin gösteriliyor': '正在显示原文',
  'İnternet bağlantısı yok': '无网络连接',
  'Sunucu yanıt vermedi': '服务器未响应',
  'Güvenli bağlantı kurulamadı': '无法建立安全连接',
  'Sunucudan beklenmeyen bir yanıt geldi': '服务器返回了意外的响应',
  'İzlediğim Diziler': '我看过的剧集',
  'İzlediğim Filmler': '我看过的电影',
  'Satır görünümü': '列表视图',
  'Afiş görünümü': '海报视图',
  'Satır görünümünde sürükleme kapalı; "En üste taşı" ile öne al.':
      '列表视图中无法拖动，请使用“移到最前”移到前面。',
  'Spoiler uyarısını göster': '显示剧透警告',
  'Kapalıyken spoiler işaretli gönderiler perdesiz, doğrudan gösterilir.':
      '关闭后，标记为剧透的帖子将直接显示，不再遮挡。',
  'Etiketler': '标记',
  'dizi.jpg {} yayında': 'dizi.jpg {} 已发布',
  'Yenilikler': '新功能',
  'Bu sürümde neler değişti, aşağıda.': '以下是此版本的变化。',
  'Bildirimler yenilendi': '通知全新改版',
  'Beğeniler artık gönderi başına tek satırda toplanıyor, satırın sağında gönderinin küçük görseli duruyor ve liste arka planla tek parça görünüyor.':
      '点赞现在按帖子合并为一行，右侧显示帖子的小预览图，列表与背景融为一体。',
  'Sarı rozet her yerde': '黄色徽章无处不在',
  'Rozetli kullanıcıların adının yanında artık bildirimlerde, gönderilerde ve beğenenler listesinde sarı onay rozeti görünüyor.':
      '带徽章用户的黄色认证标志现在会显示在通知、帖子和点赞列表中的用户名旁边。',
  'Reels yorumları yarım ekranda': 'Reels 评论半屏显示',
  'Reels izlerken yorumlar ve yazının devamı ekranın yarısından biraz fazlasını kaplayan bir pencerede açılıyor; video üstte oynamaya devam ediyor.':
      '观看 Reels 时，评论和完整文字会在覆盖略超半屏的面板中打开；视频在上方继续播放。',
  'Tek renkli ilerleme çubuğu': '单色进度条',
  'Liste görünümündeki izleme çubuğu artık tek renk: az izlediysen kırmızı, ortalarındaysan sarı, sona yaklaştıysan yeşil.':
      '列表视图中的观看进度条现在是单一颜色：看得少是红色，过半是黄色，接近完成是绿色。',
  'Sohbet düzeltmeleri': '聊天修复',
  'Mesaj yazma kutusu ile istek düğmeleri artık telefonun gezinme tuşlarının altında kalmıyor; sohbete girince alt menü kendiliğinden gizleniyor.':
      '消息输入框和请求按钮不再被手机导航键遮挡；进入聊天时底部菜单会自动隐藏。',
  'Bu sürümün notlarını görmek için uygulamayı güncelle': '更新应用以查看此版本的说明',
  'Galeri': '图库',
  'Kamera': '相机',
  'Dosya': '文件',
  'GIF': 'GIF',
  'Dizi / Film': '剧集 / 电影',
  'Sesli mesaj (basılı tut)': '语音消息（长按）',
  'Kaydetmek için basılı tut': '长按录音',
  'Kaydırarak iptal': '滑动取消',
  'Kamera açılamadı': '无法打开相机',
  'Dosya seçilemedi': '无法选择文件',
  'Dosya gönderilemedi': '无法发送文件',
  'En yeni mesaja in': '跳到最新消息',
  'Gönderilemedi · tekrar dene': '未发送 · 点击重试',
  'Dosya açılamadı': '无法打开文件',
  'Temizle': '清除',
  'Oyuncu': '演员',
  'Böyle bir oda yok': '没有这个房间',
  'Bu oda kapandı': '这个房间已关闭',
  'Bu odaya girmek için davet ya da oda kodu gerekli': '进入需要邀请或房间码',
  'Oda dolu': '房间已满',
  'Bu odaya giremezsin': '你无法进入这个房间',
  'Bu odanın üyesi değilsin': '你不是这个房间的成员',
  'Bunu yalnız oda sahibi yapabilir': '只有房主可以这么做',
  'Oda sahibi odayı kapatmalı': '房间要由房主关闭',
  'Zaten açık bir odan var': '你已经有一个开着的房间',
  'Oda kodu 6 karakter olmalı': '房间码必须是 6 位',
  'Misafir hesaplar izleme odası açamaz. Hesap oluşturursan açabilirsin.':
      '访客账号不能开房间。创建账号后即可开房间。',
  'Yalnız karşılıklı takipleştiğin kişileri davet edebilirsin': '只能邀请互相关注的人',
  'Video en fazla {} GB olabilir': '视频最大 {} GB',
  'Yalnızca MP4 veya WebM izlenebilir': '只能播放 MP4 或 WebM',
  '{} odaya katıldı': '{} 加入了房间',
  '{} odadan ayrıldı': '{} 离开了房间',
  '{} bir video yükledi': '{} 上传了一个视频',
  'bitti': '已结束',
  '{} sn': '{} 秒',
  'Birlikte izle': '一起看',
  'Bir video yükle, arkadaşlarını davet et, aynı anda izleyin.':
      '上传一个视频，邀请朋友，一起同步观看。',
  'Henüz bir odan ya da davetin yok.': '你还没有房间或邀请。',
  'Odaya katıl': '加入房间',
  'Oda kodu': '房间码',
  'Katıl': '加入',
  'Oda oluştur': '创建房间',
  'Odalar 12 saat sonra kendiliğinden kapanır ve video silinir.':
      '房间 12 小时后会自动关闭，视频也会被删除。',
  'Odam': '我的房间',
  '@{} odası': '@{} 的房间',
  'Seni davet etti': '邀请了你',
  '{} kişi': '{} 人',
  'Video yok': '没有视频',
  '{} kaldı': '还剩 {}',
  'Davet': '邀请',
  '@{} davet edildi': '已邀请 @{}',
  'Oda kodu kopyalandı': '房间码已复制',
  'Odayı kapat': '关闭房间',
  'Odadan ayrıl': '离开房间',
  'Oda kapanacak ve video silinecek. Bu geri alınamaz.':
      '房间将被关闭，视频将被删除。此操作无法撤销。',
  'Odadan çıkacaksın. Kodla ya da davetle geri dönebilirsin.':
      '你将离开房间。可以用房间码或邀请再回来。',
  'Ayrıl': '离开',
  'İzleme odası': '观看房间',
  'Odalar 12 saat sonra kendiliğinden kapanır.': '房间 12 小时后会自动关闭。',
  '{} kişi · {} kaldı': '{} 人 · 还剩 {}',
  'Davet et': '邀请',
  'Bir video yükle, izlemeye başlayın': '上传一个视频，开始一起看',
  'Oda sahibi henüz video yüklemedi': '房主还没有上传视频',
  'Video yükle': '上传视频',
  'En fazla {} GB · MP4 veya WebM': '最大 {} GB · MP4 或 WebM',
  'Kaldığı yerden yükleniyor · {}/{} MB': '继续上传 · {}/{} MB',
  'Yükleniyor · {}/{} MB': '上传中 · {}/{} MB',
  'Videoyu değiştir': '更换视频',
  'Oda sahibiyle eşleniyor': '正在与房主同步',
  'Sohbet boş': '聊天是空的',
  'İzlerken buradan konuşabilirsiniz.': '可以边看边在这里聊天。',
  'oda sahibi': '房主',
  'davet bekliyor': '邀请待接受',
  'çevrimdışı': '离线',
  'Mesaj yaz...': '写条消息...',
  'Oda kodunu kopyala': '复制房间码',
  'Oda kodu {} — kopyala': '房间码 {} — 复制',
  'Arkadaşını davet et': '邀请朋友',
  'kullanıcı adı': '用户名',
  'Yalnız karşılıklı takipleştiğin kişileri davet edebilirsin.': '只能邀请互相关注的人。',
  'Oda açılamadı': '无法打开房间',
  'Tam ekrandan çık': '退出全屏',
  'Sohbeti gizle': '隐藏聊天',
  'Sohbeti göster': '显示聊天',
  'Fragman': '预告片',
  'Tekrar oynat': '重新播放',
  '@{} seni izleme odasına davet etti': '@{} 邀请你加入观看房间',
  '{} · {} davet bekliyor': '{} · {} 个邀请待处理',
  'Sırada bekliyor': '排队中',
  'Hazırlanıyor · %{}': '准备中 · {}%',
  'Video, her cihazda oynayacak biçime çevriliyor.': '正在转换视频，让它能在所有设备上播放。',
  'Başka video yükle': '上传其他视频',
  'Bu videoyu tarayıcı oynatamıyor. Telefondan aç.': '浏览器无法播放这个视频，请用手机打开。',
  'Bu videoyu iPhone oynatamıyor.': 'iPhone 无法播放这个视频。',
  'Tarayıcı için hazırla': '为浏览器准备',
  'Başlat': '开始',
  'Bu videonun görüntü biçimi oynatılamıyor. MP4 (H.264) olarak çevirip yeniden dene.':
      '这个视频的格式无法播放。请转换成 MP4（H.264）后重试。',
  'Bu dosyada görüntü yok': '这个文件里没有视频',
  'Video okunamadı, dosya bozuk olabilir': '视频读取失败，文件可能已损坏',
  'Sunucuda yer kalmadı, biraz sonra tekrar dene': '服务器空间不足，请稍后再试',
  'Video bulunamadı': '找不到视频',
  'Yetkili': '管理员',
  'Kontrolü ver': '交出控制权',
  'Kontrolü al': '收回控制权',
  'Videoyu oynatıp durdurabilir ve değiştirebilir.': '可以播放、暂停和更换视频。',
  'Artık videoyu yönetemez.': '不能再管理视频了。',
  'Bunu oda sahibi ve yetki verdiği kişiler yapabilir': '只有房主和他授权的人可以这么做',
  'Kendi yetkini değiştiremezsin': '不能修改自己的权限',
  'Geçersiz yetki': '无效权限',
  '{} artık videoyu yönetebilir': '{} 现在可以管理视频',
  '{} kontrolü bıraktı': '{} 不再有控制权',
};
