/// Otomatik üretilen çeviri haritası (ml).
const Map<String, String> cevirilerMl = {
  'Hepsini gördün, baştan gösteriyoruz':
      'നിങ്ങൾ എല്ലാം കണ്ടു, ഞങ്ങൾ ആദ്യം മുതൽ കാണിക്കുന്നു',
  'Aktarılacak tanınan veri bulunamadı.':
      'ഇറക്കുമതി ചെയ്യാൻ തിരിച്ചറിയാവുന്ന ഡാറ്റയൊന്നും കണ്ടെത്തിയില്ല.',
  'Arama': 'തിരയൽ',
  'Aramaya başla': 'തിരയാൻ തുടങ്ങൂ',
  'Son aramalar': 'സമീപകാല തിരയലുകൾ',
  'Ayarlar': 'സെറ്റിംഗ്സ്',
  'Bağla': 'ലിങ്ക് ചെയ്യൂ',
  'Bio': 'ബയോ',
  'Bitirdim': 'കണ്ടു തീർത്തു',
  'Bunları da Beğenebilirsin': 'ഇവയും ഇഷ്ടപ്പെട്ടേക്കാം',
  'Bölüm': 'എപ്പിസോഡ്',
  'Bıraktım': 'നിർത്തി',
  'Dil': 'ഭാഷ',
  'Dil ara...': 'ഭാഷ തിരയൂ...',
  'Dizi': 'സീരീസ്',
  'Dizi ve filmlerini takip et': 'നിന്റെ സീരീസും സിനിമകളും ട്രാക്ക് ചെയ്യൂ',
  'Dizi yorumu': 'സീരീസ് കമന്റ്',
  'Dizi, film veya kişi ara...': 'സീരീസ്, സിനിമ അല്ലെങ്കിൽ വ്യക്തിയെ തിരയൂ...',
  'Dosya en fazla 30MB olabilir': 'ഫയൽ പരമാവധി 30MB ആകാം',
  'Dosya en fazla {}MB olabilir': 'ഫയൽ പരമാവധി {}MB ആകാം',
  'E-posta': 'ഇമെയിൽ',
  'E-posta veya kullanıcı adı': 'ഇമെയിൽ അല്ലെങ്കിൽ യൂസർനെയിം',
  'En az 2 harf yaz': 'കുറഞ്ഞത് 2 അക്ഷരം ടൈപ്പ് ചെയ്യൂ',
  'Film': 'സിനിമ',
  'Film yorumu': 'സിനിമ കമന്റ്',
  'Fotoğraf / video ekle': 'ഫോട്ടോ / വീഡിയോ ചേർക്കൂ',
  'Fotoğraf veya GIF — profil ve kapak resmi':
      'ഫോട്ടോ അല്ലെങ്കിൽ GIF — പ്രൊഫൈലും കവർ ചിത്രവും',
  'Giriş Yap': 'ലോഗിൻ',
  'Gönder': 'അയയ്ക്കൂ',
  'Gönderildi': 'അയച്ചു',
  'Haftanın Dizileri': 'ഈ ആഴ്ചയിലെ സീരീസ്',
  'Haftanın Filmleri': 'ഈ ആഴ്ചയിലെ സിനിമകൾ',
  'Henüz izleme kaydın yok': 'ഇതുവരെ കണ്ടതിന്റെ രേഖയില്ല',
  'Henüz listen yok — Profil sekmesinden oluştur.':
      'ഇതുവരെ ലിസ്റ്റില്ല — പ്രൊഫൈൽ ടാബിൽ നിന്ന് ഉണ്ടാക്കൂ.',
  'Henüz yorum yok.': 'ഇതുവരെ കമന്റില്ല.',
  'Hesabın bağlandı!': 'നിന്റെ അക്കൗണ്ട് ലിങ്ക് ആയി!',
  'Hesabın yok mu? Kayıt ol': 'അക്കൗണ്ട് ഇല്ലേ? സൈൻ അപ്പ് ചെയ്യൂ',
  'Hesabını Bağla': 'അക്കൗണ്ട് ലിങ്ക് ചെയ്യൂ',
  'Hesap Oluştur': 'അക്കൗണ്ട് ഉണ്ടാക്കൂ',
  'Kapak resmi ekle': 'കവർ ചിത്രം ചേർക്കൂ',
  'Kaydet': 'സേവ് ചെയ്യൂ',
  'Kendinden bahset...': 'നിന്നെക്കുറിച്ച് പറയൂ...',
  'Keşfet': 'കണ്ടെത്തൂ',
  'Kimseyi takip etmiyor': 'ആരെയും ഫോളോ ചെയ്യുന്നില്ല',
  'Kişi ara': 'വ്യക്തിയെ തിരയൂ',
  'Kişi yorumu': 'വ്യക്തി കമന്റ്',
  'Konuk Oyuncular': 'അതിഥി താരങ്ങൾ',
  'Kullanıcı adı (küçük harf)': 'യൂസർനെയിം (ചെറിയക്ഷരം)',
  'Kullanıcı adı ara...': 'യൂസർനെയിം തിരയൂ...',
  'Liste adı': 'ലിസ്റ്റിന്റെ പേര്',
  'Listeye Ekle': 'ലിസ്റ്റിലേക്ക് ചേർക്കൂ',
  'Misafir hesabındasın — e-postanla bağla, verilerini kaybetme!':
      'നീ ഗസ്റ്റ് അക്കൗണ്ടിലാണ് — ഇമെയിലുമായി ലിങ്ക് ചെയ്യൂ, ഡാറ്റ നഷ്ടപ്പെടുത്തരുത്!',
  'Misafir olarak devam et': 'ഗസ്റ്റായി തുടരൂ',
  'Oluştur': 'ഉണ്ടാക്കൂ',
  'Oyuncular': 'അഭിനേതാക്കൾ',
  'Profil': 'പ്രൊഫൈൽ',
  'Profil kaydedildi': 'പ്രൊഫൈൽ സേവ് ആയി',
  'Puanla': 'റേറ്റ് ചെയ്യൂ',
  'Puanı Sil': 'റേറ്റിംഗ് നീക്കം ചെയ്യൂ',
  'Puanın': 'നിന്റെ റേറ്റിംഗ്',
  'Sezonlar': 'സീസണുകൾ',
  'Sunucu hatası ({})': 'സെർവർ പിശക് ({})',
  'S{} · {}. Bölüm': 'S{} · E{}',
  'S{}B{} yorumu': 'S{}E{} കമന്റ്',
  'Takibi Bırak': 'അൺഫോളോ',
  'Takip': 'ഫോളോയിംഗ്',
  'Takip Edilenler': 'ഫോളോ ചെയ്യുന്നു',
  'Takip Et': 'ഫോളോ ചെയ്യൂ',
  'Takipçi': 'ഫോളോവർ',
  'Takipçi yok': 'ഫോളോവേഴ്സ് ഇല്ല',
  'Takipçiler': 'ഫോളോവേഴ്സ്',
  'Takvim': 'കലണ്ടർ',
  'Tamam': 'ശരി',
  'Tekrar Dene': 'വീണ്ടും ശ്രമിക്കൂ',
  'Tekrar dene': 'വീണ്ടും ശ്രമിക്കൂ',
  'Toplam İzleme Süresi': 'ആകെ സ്ക്രീൻ സമയം',
  'Tüm Zamanların En İyileri': 'എക്കാലത്തെയും മികച്ചവ',
  "Tüm verini (izleme, puan, yorum, liste) TV Time uyumlu ZIP olarak al ya da TV Time / Letterboxd ZIP'ini içe aktar.":
      'നിന്റെ എല്ലാ ഡാറ്റയും (കണ്ടവ, റേറ്റിംഗ്, കമന്റ്, ലിസ്റ്റ്) TV Time അനുയോജ്യമായ ZIP ആയി എടുക്കൂ അല്ലെങ്കിൽ TV Time / Letterboxd ZIP ഇറക്കുമതി ചെയ്യൂ.',
  'Tümünü Kaldır': 'എല്ലാം നീക്കം ചെയ്യൂ',
  'Tümünü İzledim': 'എല്ലാം കണ്ടു',
  'Türk Dizileri': 'ടർക്കിഷ് സീരീസ്',
  'Veri içe aktar (.zip)': 'ഡാറ്റ ഇറക്കുമതി (.zip)',
  'Verilerim': 'എന്റെ ഡാറ്റ',
  'Verilerimi dışa aktar (e-posta)': 'എന്റെ ഡാറ്റ എക്സ്പോർട്ട് ചെയ്യൂ (ഇമെയിൽ)',
  'Verilerini dışa aktar': 'നിന്റെ ഡാറ്റ എക്സ്പോർട്ട് ചെയ്യൂ',
  'Yaklaşan bölüm yok.\nDizi detayından "İzliyorum" durumuna al, yeni bölümleri burada takip et.':
      'വരാനിരിക്കുന്ന എപ്പിസോഡില്ല.\nസീരീസ് വിശദാംശത്തിൽ "കണ്ടുകൊണ്ടിരിക്കുന്നു" സ്റ്റാറ്റസിലാക്കൂ, പുതിയ എപ്പിസോഡുകൾ ഇവിടെ ഫോളോ ചെയ്യൂ.',
  'Yapımları': 'ഫിലിമോഗ്രഫി',
  'Yeni Diziler': 'പുതിയ സീരീസ്',
  'Yeni Liste': 'പുതിയ ലിസ്റ്റ്',
  'Yeni kullanıcı adı (isteğe bağlı)': 'പുതിയ യൂസർനെയിം (ഓപ്ഷണൽ)',
  'Yorum': 'കമന്റ്',
  'Yorumunu yaz...': 'നിന്റെ കമന്റ് എഴുതൂ...',
  'Zaten hesabın var mı? Giriş yap': 'അക്കൗണ്ട് ഉണ്ടോ? ലോഗിൻ ചെയ്യൂ',
  'ort. {}': 'ശരാ. {}',
  'takip': 'ഫോളോയിംഗ്',
  'takipçi': 'ഫോളോവേഴ്സ്',
  '{} / {} bölüm': '{} / {} എപ്പിസോഡ്',
  '{} TMDB': '{} TMDB',
  '{} ay': '{} മാസം',
  '{} ay~tekil': '{} മാസം',
  '{} bölüm izlendi': '{} എപ്പിസോഡ് കണ്ടു',
  '{} dizi.jpg': '{} dizi.jpg',
  '{} dk': '{} മിനിറ്റ്',
  '{} dk~tekil': '{} മിനിറ്റ്',
  '{} gün': '{} ദിവസം',
  '{} gün~tekil': '{} ദിവസം',
  '{} içerik': '{} ഉള്ളടക്കം',
  '{} içerik · otomatik': '{} ഉള്ളടക്കം · ഓട്ടോമാറ്റിക്',
  '{} kayıt atlandı (eşleşmedi).': '{} രേഖകൾ ഒഴിവാക്കി (പൊരുത്തപ്പെട്ടില്ല).',
  '{} saat': '{} മണിക്കൂർ',
  '{} saat~tekil': '{} മണിക്കൂർ',
  '{} sezon': '{} സീസൺ',
  '{} yıl': '{} വർഷം',
  '{} yıl~tekil': '{} വർഷം',
  '{}. Bölüm': 'എപ്പിസോഡ് {}',
  '{}. Sezon': 'സീസൺ {}',
  'Çıkış Yap': 'ലോഗ് ഔട്ട്',
  'Ülke': 'രാജ്യം',
  'Ülke ara...': 'രാജ്യം തിരയൂ...',
  'Ülke seç': 'രാജ്യം തിരഞ്ഞെടുക്കൂ',
  'İlk yorumu sen yaz!': 'ആദ്യ കമന്റ് നീ തന്നെ എഴുതൂ!',
  'İncelemeler': 'റിവ്യൂകൾ',
  'İncelemen (isteğe bağlı)': 'നിന്റെ റിവ്യൂ (ഓപ്ഷണൽ)',
  'İptal': 'റദ്ദാക്കൂ',
  'İzlediklerim': 'ഞാൻ കണ്ടവ',
  'İzledim': 'കണ്ടു',
  'İzledin': 'നീ കണ്ടു',
  'İzleme geçmişin ve listelerin korunur; artık her cihazdan girebilirsin.':
      'നിന്റെ കാണൽ ചരിത്രവും ലിസ്റ്റുകളും സുരക്ഷിതമായിരിക്കും; ഇനി ഏത് ഡിവൈസിൽ നിന്നും ലോഗിൻ ചെയ്യാം.',
  'İzleme geçmişin, puanların, yorumların ve listelerin ZIP olarak kayıtlı e-posta adresine gönderilecektir.':
      'നിന്റെ കാണൽ ചരിത്രം, റേറ്റിംഗുകൾ, കമന്റുകൾ, ലിസ്റ്റുകൾ ZIP ആയി രജിസ്റ്റർ ചെയ്ത ഇമെയിൽ വിലാസത്തിലേക്ക് അയയ്ക്കും.',
  'İzleyeceğim': 'കാണാൻ പോകുന്നു',
  'İzliyorum': 'കണ്ടുകൊണ്ടിരിക്കുന്നു',
  'İçe aktarım tamamlandı': 'ഇറക്കുമതി പൂർത്തിയായി',
  'Şifre': 'പാസ്‌വേഡ്',
  '• profil bilgisi': '• പ്രൊഫൈൽ വിവരം',
  '• {} kitaplık kaydı': '• {} ലൈബ്രറി എൻട്രി',
  '• {} favori': '• {} പ്രിയപ്പെട്ടവ',
  '• {} izleme kaydı': '• {} കാണൽ രേഖ',
  '• {} liste': '• {} ലിസ്റ്റ്',
  '• {} puan': '• {} റേറ്റിംഗ്',
  '• {} yorum': '• {} കമന്റ്',
  '{}+ yapım': '{}+ വർക്കുകൾ',
  'Yorumlar': 'കമന്റുകൾ',
  'Yorumlar ({})': 'കമന്റുകൾ ({})',
  'Yorumları ({})': 'കമന്റുകൾ ({})',
  'Listelerim': 'എന്റെ ലിസ്റ്റുകൾ',
  'Nereden izledin?': 'എവിടെ കണ്ടു?',
  'Diziye git': 'ഷോയിലേക്ക് പോകൂ',
  'TV / Kanal': 'ടിവി / ചാനൽ',
  'Sinema': 'തിയേറ്റർ',
  'DVD / Blu-ray': 'DVD / Blu-ray',
  'Diğer': 'മറ്റുള്ളവ',
  'Akış': 'ഫീഡ്',
  'Akışın boş.\nİzlediğin dizi ve filmlere yorum yapılınca burada görünecek.':
      'നിന്റെ ഫീഡ് ശൂന്യമാണ്.\nനീ കാണുന്ന ഷോകളിലും സിനിമകളിലും കമന്റുകൾ വരുമ്പോൾ ഇവിടെ കാണാം.',
  'Listeleri ({})': 'അവരുടെ ലിസ്റ്റുകൾ ({})',
  'Liste boş.': 'ഈ ലിസ്റ്റ് ശൂന്യമാണ്.',
  'Yanıtla': 'മറുപടി',
  '@{} kullanıcısına yanıt veriyorsun': '@{}ന് മറുപടി നൽകുന്നു',
  'İzlediğim Diziler ({})': 'ഞാൻ കണ്ട ഷോകൾ ({})',
  'İzlediğim Filmler ({})': 'ഞാൻ കണ്ട സിനിമകൾ ({})',
  'Tümünü gör': 'എല്ലാം കാണുക',
  'Bildirimler': 'അറിയിപ്പുകൾ',
  'Henüz bildirim yok': 'ഇതുവരെ അറിയിപ്പുകളില്ല',
  '@{} yorumuna yanıt verdi': '@{} നിന്റെ കമന്റിന് മറുപടി നൽകി',
  '@{} yorumunu beğendi': '@{} നിന്റെ കമന്റ് ഇഷ്ടപ്പെട്ടു',
  '@{} seni takip etti': '@{} നിന്നെ ഫോളോ ചെയ്തു',
  '@{} sana mesaj gönderdi': '@{} നിനക്ക് സന്ദേശം അയച്ചു',
  'Mesajlar': 'സന്ദേശങ്ങൾ',
  'Mesaj': 'സന്ദേശം',
  'Mesaja eklenecek': 'സന്ദേശത്തിൽ ചേർക്കും',
  'Mesajını yaz...': 'സന്ദേശം എഴുതൂ...',
  'Henüz sohbetin yok.\nBir profile girip mesaj gönderebilirsin.':
      'ഇതുവരെ ചാറ്റുകളില്ല.\nഒരു പ്രൊഫൈൽ തുറന്ന് സന്ദേശം അയയ്ക്കൂ.',
  'Şifreni mi unuttun?': 'പാസ്‌വേഡ് മറന്നോ?',
  'Şifreyi Sıfırla': 'പാസ്‌വേഡ് റീസെറ്റ്',
  'E-postadaki kod': 'ഇമെയിലിലെ കോഡ്',
  'Yeni şifre': 'പുതിയ പാസ്‌വേഡ്',
  'Sana Özel': 'നിനക്കായി',
  '{} özetin': 'നിന്റെ {} സംഗ്രഹം',
  'Yıllık izleme istatistiklerin': 'വാർഷിക കാഴ്ച സ്ഥിതിവിവരം',
  'Rozetler': 'ബാഡ്ജുകൾ',
  'Verdiğin puan': 'നൽകിയ റേറ്റിംഗുകൾ',
  'Ortalama puanın': 'ശരാശരി റേറ്റിംഗ്',
  'En çok izlediğin diziler': 'നിങ്ങൾ ഏറ്റവും കൂടുതൽ കണ്ട ഷോകൾ',
  'İlk Bölüm': 'ആദ്യ എപ്പിസോഡ്',
  '100 Bölüm': '100 എപ്പിസോഡുകൾ',
  '1000 Bölüm': '1000 എപ്പിസോഡുകൾ',
  'İlk Film': 'ആദ്യ സിനിമ',
  '50 Film': '50 സിനിമകൾ',
  'İlk Yorum': 'ആദ്യ കമന്റ്',
  '25 Yorum': '25 കമന്റുകൾ',
  '10 Puan': '10 റേറ്റിംഗുകൾ',
  'İlk Takipçi': 'ആദ്യ ഫോളോവർ',
  '10 Dizi Bitirdin': '10 ഷോകൾ പൂർത്തിയാക്കി',
  'İzlemeyi Bıraktım': 'കാണുന്നത് നിർത്തി',
  'İzlediği Diziler ({})': 'അവർ കണ്ട ഷോകൾ ({})',
  'İzlediği Filmler ({})': 'അവർ കണ്ട സിനിമകൾ ({})',
  '500 Bölüm': '500 എപ്പിസോഡുകൾ',
  '5000 Bölüm': '5000 എപ്പിസോഡുകൾ',
  '10 Film': '10 സിനിമകൾ',
  '100 Film': '100 സിനിമകൾ',
  '100 Yorum': '100 കമന്റുകൾ',
  '50 Puan': '50 റേറ്റിംഗുകൾ',
  '100 Puan': '100 റേറ്റിംഗുകൾ',
  '10 Takipçi': '10 ഫോളോവർമാർ',
  '50 Takipçi': '50 ഫോളോവർമാർ',
  '25 Dizi Bitirdin': '25 ഷോകൾ പൂർത്തിയാക്കി',
  '50 Dizi Bitirdin': '50 ഷോകൾ പൂർത്തിയാക്കി',
  '10 Beğeni': '10 ലൈക്കുകൾ',
  '100 Beğeni': '100 ലൈക്കുകൾ',
  'yazıyor...': 'ടൈപ്പ് ചെയ്യുന്നു...',
  'ses kaydediyor...': 'ഓഡിയോ റെക്കോർഡ് ചെയ്യുന്നു...',
  'Profil düzeni': 'പ്രൊഫൈൽ ലേഔട്ട്',
  'Konumla ve kırp': 'സ്ഥാനം ക്രമീകരിച്ച് ക്രോപ്പ് ചെയ്യുക',
  'Listeye eklendi': 'ലിസ്റ്റിൽ ചേർത്തു',
  'Listeyi sil?': 'ലിസ്റ്റ് ഇല്ലാതാക്കണോ?',
  'Sil': 'ഇല്ലാതാക്കുക',
  'Bu içerik hiç izlenmemiş olarak işaretlenecek ve listelerinden kaldırılacak.':
      'ഇത് കണ്ടിട്ടില്ലെന്ന് അടയാളപ്പെടുത്തി നിന്റെ ലിസ്റ്റുകളിൽ നിന്ന് നീക്കും.',
  'Gelecek bölüm bugün': 'അടുത്ത എപ്പിസോഡ് ഇന്ന്',
  'Gelecek bölüm {} gün sonra': 'അടുത്ത എപ്പിസോഡ് {} ദിവസത്തിൽ',
  'Tema': 'തീം',
  'Sistem': 'സിസ്റ്റം',
  'Koyu': 'ഡാർക്ക്',
  'Açık': 'ലൈറ്റ്',
  'İzleyenler': 'കാഴ്ചക്കാർ',
  'Yorumunu yaz... (@ ile etiketle)':
      'നിങ്ങളുടെ കമന്റ് എഴുതൂ... (@ ടാഗ് ചെയ്യാൻ)',
  '@{} bir yorumda seni etiketledi': '@{} നിങ്ങളെ ഒരു കമന്റിൽ ടാഗ് ചെയ്തു',
  'Mesajı sil': 'സന്ദേശം ഇല്ലാതാക്കുക',
  'Mesaj silinemedi': 'സന്ദേശം ഇല്ലാതാക്കാനായില്ല',
  'Bağlantı geçersiz veya sayfa bulunamadı':
      'ലിങ്ക് അസാധുവാണ് അല്ലെങ്കിൽ പേജ് കണ്ടെത്തിയില്ല',
  "Keşfet'e dön": 'കണ്ടെത്തലിലേക്ക് മടങ്ങുക',
  'Düzenle': 'എഡിറ്റ്',
  'Mesajı düzenle': 'സന്ദേശം എഡിറ്റ്',
  'Yanıtlanıyor': 'മറുപടി നൽകുന്നു',
  'düzenlendi': 'എഡിറ്റ് ചെയ്തു',
  'Fotoğraf': 'ഫോട്ടോ',
  'Video': 'വീഡിയോ',
  'İçerik': 'ഉള്ളടക്കം',
  'çevrimiçi': 'ഓൺലൈൻ',
  'son görülme {} dk önce': '{} മിനിറ്റ് മുമ്പ് ഓൺലൈനിൽ',
  'son görülme {} saat önce': '{} മണിക്കൂർ മുമ്പ് ഓൺലൈനിൽ',
  'son görülme {} gün önce': '{} ദിവസം മുമ്പ് ഓൺലൈനിൽ',
  'Yorumlar yüklenemedi': 'കമന്റുകൾ ലോഡ് ചെയ്യാനായില്ല',
  'Favori': 'പ്രിയപ്പെട്ടത്',
  'Listeye ekle': 'ലിസ്റ്റിൽ ചേർക്കുക',
  'İçerik paylaş': 'പങ്കിടുക',
  'Kapat': 'അടയ്ക്കുക',
  'İzlediğin dizi ve filmleri işaretledikçe burada toplanır.':
      'കണ്ടതായി അടയാളപ്പെടുത്തുന്നതെല്ലാം ഇവിടെ ശേഖരിക്കും.',
  'Henüz sohbetin yok': 'ഇതുവരെ സംഭാഷണങ്ങളില്ല',
  'Bir profile girip mesaj gönderebilirsin.':
      'ഒരു പ്രൊഫൈൽ തുറന്ന് സന്ദേശം അയയ്ക്കൂ.',
  'Listeyi sil': 'ലിസ്റ്റ് ഇല്ലാതാക്കുക',
  'Puan kaydedilemedi': 'റേറ്റിംഗ് സംരക്ഷിക്കാനായില്ല',
  'Nerede İzlenir': 'എവിടെ കാണാം',
  'Abonelik': 'സബ്‌സ്‌ക്രിപ്ഷൻ',
  'Kirala': 'വാടകയ്‌ക്ക്',
  'Satın al': 'വാങ്ങുക',
  'Devam et': 'തുടരുക',
  'Şikayet et': 'റിപ്പോർട്ട് ചെയ്യുക',
  'Engelle': 'ബ്ലോക്ക് ചെയ്യുക',
  'Engeli kaldır': 'അൺബ്ലോക്ക് ചെയ്യുക',
  'Kullanıcı engellendi': 'ഉപയോക്താവിനെ ബ്ലോക്ക് ചെയ്തു',
  'Engel kaldırıldı': 'ബ്ലോക്ക് നീക്കി',
  'Şikayet sebebi': 'റിപ്പോർട്ടിന്റെ കാരണം',
  'Spam veya yanıltıcı': 'സ്പാം അല്ലെങ്കിൽ തെറ്റിദ്ധരിപ്പിക്കുന്നത്',
  'Taciz veya nefret söylemi': 'ഉപദ്രവം അല്ലെങ്കിൽ വിദ്വേഷ പ്രസംഗം',
  'Uygunsuz / cinsel içerik': 'അനുചിതം / ലൈംഗിക ഉള്ളടക്കം',
  'Şiddet veya tehlikeli içerik': 'അക്രമം അല്ലെങ്കിൽ അപകടകരമായ ഉള്ളടക്കം',
  'Telif hakkı ihlali': 'പകർപ്പവകാശ ലംഘനം',
  'Şikayetin alındı, teşekkürler': 'നിന്റെ റിപ്പോർട്ട് ലഭിച്ചു, നന്ദി',
  'Hesabımı Sil': 'എന്റെ അക്കൗണ്ട് ഇല്ലാതാക്കുക',
  'Hesabın ve tüm verin (izleme, puan, yorum, liste, mesaj) kalıcı olarak silinecek. Bu işlem geri alınamaz.':
      'നിന്റെ അക്കൗണ്ടും എല്ലാ ഡാറ്റയും (ചരിത്രം, റേറ്റിംഗുകൾ, കമന്റുകൾ, ലിസ്റ്റുകൾ, സന്ദേശങ്ങൾ) ശാശ്വതമായി ഇല്ലാതാക്കും. ഇത് പഴയപടിയാക്കാനാവില്ല.',
  'Şifreni gir': 'നിന്റെ പാസ്‌വേഡ് നൽകുക',
  'Hesabımı kalıcı sil': 'എന്റെ അക്കൗണ്ട് ശാശ്വതമായി ഇല്ലാതാക്കുക',
  'Sesli mesaj': 'വോയ്‌സ് സന്ദേശം',
  'Görüldü': 'കണ്ടു',
  'Gönderi': 'പോസ്റ്റ്',
  'Ses gönderilemedi': 'വോയ്‌സ് സന്ദേശം അയയ്‌ക്കാനായില്ല',
  'Kaydediliyor…': 'റെക്കോർഡ് ചെയ്യുന്നു…',
  'Ses oynatılamadı': 'ഓഡിയോ പ്ലേ ചെയ്യാനായില്ല',
  'Oynat': 'പ്ലേ ചെയ്യൂ',
  'Fragmanı oynat': 'ട്രെയ്‌ലർ പ്ലേ ചെയ്യുക',
  'Altyazıyı aç': 'സബ്‌ടൈറ്റിൽ ഓണാക്കുക',
  'Altyazıyı kapat': 'സബ്‌ടൈറ്റിൽ ഓഫാക്കുക',
  '10 saniye ileri': '10 സെക്കൻഡ് മുന്നോട്ട്',
  '10 saniye geri': '10 സെക്കൻഡ് പിന്നോട്ട്',
  'Duraklat': 'താൽക്കാലികമായി നിർത്തൂ',
  'Liste görünümü': 'ലിസ്റ്റ് കാഴ്ച',
  'Takvim görünümü': 'കലണ്ടർ കാഴ്ച',
  'Önceki ay': 'മുൻ മാസം',
  'Sonraki ay': 'അടുത്ത മാസം',
  'Bu gün bölüm yok': 'ഈ ദിവസം എപ്പിസോഡുകളൊന്നുമില്ല',
  'Gizlilik Politikası': 'സ്വകാര്യതാ നയം',
  'Son güncelleme: {}': 'അവസാന അപ്ഡേറ്റ്: {}',
  'Bu politika, dizi.jpg uygulamasını ve dizijpg.com sitesini kullandığında hangi verilerin toplandığını, nasıl kullanıldığını ve haklarının neler olduğunu açıklar.':
      'dizi.jpg ആപ്പും dizijpg.com സൈറ്റും ഉപയോഗിക്കുമ്പോൾ ഏതെല്ലാം ഡാറ്റ ശേഖരിക്കുന്നു, എങ്ങനെ ഉപയോഗിക്കുന്നു, നിന്റെ അവകാശങ്ങൾ എന്തൊക്കെ എന്നിവ ഈ നയം വിശദീകരിക്കുന്നു.',
  'Topladığımız Veriler': 'ഞങ്ങൾ ശേഖരിക്കുന്ന ഡാറ്റ',
  'Hesap: e-posta adresi, kullanıcı adı ve şifre. Şifreler geri döndürülemez şekilde özetlenerek saklanır; misafir hesaplar e-postasız kullanılabilir.':
      'അക്കൗണ്ട്: ഇമെയിൽ വിലാസം, യൂസർനെയിം, പാസ്‌വേഡ്. പാസ്‌വേഡുകൾ തിരിച്ചെടുക്കാനാവാത്ത ഹാഷ് രൂപത്തിലാണ് സൂക്ഷിക്കുന്നത്; ഗസ്റ്റ് അക്കൗണ്ടുകൾ ഇമെയിൽ ഇല്ലാതെയും ഉപയോഗിക്കാം.',
  'Profil: avatar, kapak görseli, bio ve ülke gibi eklemeyi seçtiğin bilgiler.':
      'പ്രൊഫൈൽ: അവതാർ, കവർ ചിത്രം, ബയോ, രാജ്യം എന്നിങ്ങനെ നീ ചേർക്കാൻ തിരഞ്ഞെടുക്കുന്ന വിവരങ്ങൾ.',
  'Kullanım: izleme geçmişin, puanların, yorumların, listelerin, tepkilerin ve favorilerin.':
      'ഉപയോഗം: നിന്റെ കാണൽ ചരിത്രം, റേറ്റിംഗുകൾ, കമന്റുകൾ, ലിസ്റ്റുകൾ, റിയാക്ഷനുകൾ, പ്രിയപ്പെട്ടവ.',
  'Mesajlar: yazılı, görselli ve sesli mesajların sunucularımızda saklanır. Mesajlar uçtan uca şifreli değildir; yalnızca şikayet edilirse moderasyon amacıyla incelenir.':
      'സന്ദേശങ്ങൾ: നിന്റെ ടെക്സ്റ്റ്, ചിത്ര, വോയ്സ് സന്ദേശങ്ങൾ ഞങ്ങളുടെ സെർവറുകളിൽ സൂക്ഷിക്കുന്നു. സന്ദേശങ്ങൾക്ക് എൻഡ്-ടു-എൻഡ് എൻക്രിപ്ഷൻ ഇല്ല; റിപ്പോർട്ട് ചെയ്താൽ മാത്രം മോഡറേഷനായി പരിശോധിക്കും.',
  'Yüklenen medya: profiline, yorumlarına ve mesajlarına eklediğin fotoğraf, GIF, video ve ses kayıtları.':
      'അപ്‌ലോഡ് ചെയ്ത മീഡിയ: പ്രൊഫൈലിലും കമന്റുകളിലും സന്ദേശങ്ങളിലും നീ ചേർക്കുന്ന ഫോട്ടോകൾ, GIF, വീഡിയോകൾ, വോയ്സ് റെക്കോർഡിംഗുകൾ.',
  'Teknik: IP adresi, yaklaşık konum (ülke/şehir düzeyi), cihaz platformu, uygulama sürümü ve hata kayıtları. Bunlar güvenlik ve hata ayıklama için tutulur.':
      'സാങ്കേതികം: IP വിലാസം, ഏകദേശ സ്ഥാനം (രാജ്യം/നഗരം തലത്തിൽ), ഉപകരണ പ്ലാറ്റ്ഫോം, ആപ്പ് പതിപ്പ്, പിശക് ലോഗുകൾ. ഇവ സുരക്ഷയ്ക്കും തകരാർ പരിഹാരത്തിനുമായി സൂക്ഷിക്കുന്നു.',
  'Kullanım istatistikleri: hangi cihaz türü, işletim sistemi ve tarayıcıyla girildiği kaba sınıflar hâlinde günlük toplam sayaçlara eklenir; tarayıcı kimliğinin kendisi saklanmaz ve bu sayılar kişilere bağlanamaz.':
      'ഉപയോഗ സ്ഥിതിവിവരം: ഏത് തരം ഉപകരണം, ഓപ്പറേറ്റിങ് സിസ്റ്റം, ബ്രൗസർ വഴിയാണ് പ്രവേശിച്ചത് എന്നത് പരുക്കൻ വിഭാഗങ്ങളായി ദിവസേനയുള്ള മൊത്തം കൗണ്ടറുകളിൽ ചേർക്കുന്നു; ബ്രൗസറിന്റെ തിരിച്ചറിയൽ വിവരം തന്നെ സൂക്ഷിക്കുന്നില്ല, ഈ എണ്ണങ്ങൾ ഒരു വ്യക്തിയുമായി ബന്ധിപ്പിക്കാനും കഴിയില്ല.',
  "Bildirimler: push bildirimleri için cihaz token'ı ve dil tercihin saklanır. Bildirimleri cihazının ayarlarından istediğin zaman kapatabilirsin.":
      'അറിയിപ്പുകൾ: പുഷ് അറിയിപ്പുകൾക്കായി നിന്റെ ഉപകരണ ടോക്കണും ഭാഷാ തിരഞ്ഞെടുപ്പും സൂക്ഷിക്കുന്നു. ഉപകരണ ക്രമീകരണങ്ങളിൽ നിന്ന് എപ്പോൾ വേണമെങ്കിലും അറിയിപ്പുകൾ ഓഫാക്കാം.',
  'Verileri Nasıl Kullanırız': 'ഡാറ്റ എങ്ങനെ ഉപയോഗിക്കുന്നു',
  'Verilerini yalnızca hizmeti sunmak, hesabını korumak, bildirim göndermek, hataları gidermek ve kötüye kullanımı önlemek için kullanırız. Verilerini satmayız, reklam amacıyla kimseyle paylaşmayız.':
      'സേവനം നൽകാനും അക്കൗണ്ട് സംരക്ഷിക്കാനും അറിയിപ്പുകൾ അയയ്ക്കാനും പിശകുകൾ പരിഹരിക്കാനും ദുരുപയോഗം തടയാനും മാത്രമാണ് നിന്റെ ഡാറ്റ ഉപയോഗിക്കുന്നത്. നിന്റെ ഡാറ്റ വിൽക്കുന്നില്ല; പരസ്യത്തിനായി ആരുമായും പങ്കിടുന്നില്ല.',
  'Çerezler ve Yerel Depolama': 'കുക്കികളും ലോക്കൽ സ്റ്റോറേജും',
  'Yalnızca oturumunu açık tutmak ve dil/tema gibi tercihlerini hatırlamak için yerel depolama kullanırız. Reklam veya izleme çerezi yoktur.':
      'നിന്നെ ലോഗിൻ ആയി നിലനിർത്താനും ഭാഷ/തീം പോലുള്ള മുൻഗണനകൾ ഓർക്കാനും മാത്രമാണ് ലോക്കൽ സ്റ്റോറേജ് ഉപയോഗിക്കുന്നത്. പരസ്യ അല്ലെങ്കിൽ ട്രാക്കിംഗ് കുക്കികൾ ഇല്ല.',
  'Üçüncü Taraf Hizmetler': 'മൂന്നാം കക്ഷി സേവനങ്ങൾ',
  "Dizi ve film bilgileri TMDB'den, izleme sağlayıcı bilgisi JustWatch'tan alınır. Push bildirimleri Google Firebase üzerinden iletilir, site trafiği Cloudflare tarafından korunur. Bu hizmetler kendi gizlilik politikalarına tabidir.":
      'സീരീസുകളുടെയും സിനിമകളുടെയും ഡാറ്റ TMDB-യിൽ നിന്നും സ്ട്രീമിംഗ് പ്ലാറ്റ്ഫോം വിവരങ്ങൾ JustWatch-ൽ നിന്നും വരുന്നു. പുഷ് അറിയിപ്പുകൾ Google Firebase വഴി എത്തുന്നു; സൈറ്റ് ട്രാഫിക്ക് Cloudflare സംരക്ഷിക്കുന്നു. ഈ സേവനങ്ങൾക്ക് അവയുടെ സ്വന്തം സ്വകാര്യതാ നയങ്ങൾ ബാധകമാണ്.',
  'Saklama ve Silme': 'സൂക്ഷിക്കലും നീക്കം ചെയ്യലും',
  'Verilerin hesabın açık olduğu sürece saklanır. Ayarlar\'daki "Hesabımı Sil" ile hesabını kalıcı olarak silebilirsin; verilerin anında, yedeklerdeki kopyaları en geç 14 gün içinde silinir. Hata kayıtları 30 gün sonra otomatik silinir.':
      'നിന്റെ അക്കൗണ്ട് ഉള്ളിടത്തോളം ഡാറ്റയും ഉണ്ടാകും. ക്രമീകരണങ്ങളിലെ "എന്റെ അക്കൗണ്ട് ഇല്ലാതാക്കുക" വഴി അക്കൗണ്ട് ശാശ്വതമായി ഇല്ലാതാക്കാം; ഡാറ്റ ഉടനെയും ബാക്കപ്പുകളിലെ പകർപ്പുകൾ പരമാവധി 14 ദിവസത്തിനുള്ളിലും മായ്ക്കപ്പെടും. പിശക് ലോഗുകൾ 30 ദിവസത്തിന് ശേഷം സ്വയമേവ മായ്ക്കപ്പെടും.',
  "Verilerini Ayarlar'dan ZIP olarak dışa aktarabilirsin; arşiv e-posta adresine gönderilir.":
      'ക്രമീകരണങ്ങളിൽ നിന്ന് നിന്റെ ഡാറ്റ ZIP ആയി എക്സ്പോർട്ട് ചെയ്യാം; ആർക്കൈവ് നിന്റെ ഇമെയിൽ വിലാസത്തിലേക്ക് അയയ്ക്കും.',
  'Güvenlik': 'സുരക്ഷ',
  'Veriler şifreli bağlantı (HTTPS) üzerinden taşınır ve erişimi sınırlı sunucularda saklanır.':
      'ഡാറ്റ എൻക്രിപ്റ്റഡ് കണക്ഷനുകൾ (HTTPS) വഴി സഞ്ചരിക്കുന്നു; പരിമിത ആക്സസ് ഉള്ള സെർവറുകളിൽ സൂക്ഷിക്കുന്നു.',
  'Çocukların Gizliliği': 'കുട്ടികളുടെ സ്വകാര്യത',
  'dizi.jpg 13 yaşından küçük çocuklara yönelik değildir.':
      'dizi.jpg 13 വയസ്സിന് താഴെയുള്ള കുട്ടികൾക്കുള്ളതല്ല.',
  'Hakların': 'നിന്റെ അവകാശങ്ങൾ',
  'KVKK ve GDPR kapsamında verilerine erişme, düzeltme, silme ve taşıma hakkına sahipsin. Bu haklar için bize yazabilirsin: {}':
      'KVKK, GDPR പ്രകാരം നിന്റെ ഡാറ്റ ആക്സസ് ചെയ്യാനും തിരുത്താനും ഇല്ലാതാക്കാനും മാറ്റാനും നിനക്ക് അവകാശമുണ്ട്. ഇതിനായി ഞങ്ങൾക്ക് എഴുതൂ: {}',
  'Değişiklikler': 'മാറ്റങ്ങൾ',
  'Bu politika değişirse yeni sürümü bu sayfada yayımlanır ve güncelleme tarihi yenilenir.':
      'ഈ നയം മാറിയാൽ പുതിയ പതിപ്പ് ഇതേ പേജിൽ പ്രസിദ്ധീകരിച്ച് തീയതി പുതുക്കും.',
  'Kayıt olarak {} kabul etmiş olursun.':
      'രജിസ്റ്റർ ചെയ്യുന്നതിലൂടെ നീ {} അംഗീകരിക്കുന്നു.',
  'Kullanıcılar': 'ഉപയോക്താക്കൾ',
  'Fotoğrafı değiştir': 'ഫോട്ടോ മാറ്റുക',
  'Yeniden konumlandır': 'വീണ്ടും ക്രമീകരിക്കുക',
  'Bir şeyler ters gitti': 'എന്തോ പിഴവ് സംഭവിച്ചു',
  'Sosyal Bağlantılar': 'സോഷ്യൽ ലിങ്കുകൾ',
  'Profilinde en fazla 3 bağlantı gösterilir.':
      'നിന്റെ പ്രൊഫൈലിൽ പരമാവധി 3 ലിങ്കുകൾ കാണിക്കും.',
  'Platform seç': 'പ്ലാറ്റ്ഫോം തിരഞ്ഞെടുക്കൂ',
  'Kullanıcı adın': 'നിന്റെ യൂസർനെയിം',
  'Ekle': 'ചേർക്കുക',
  'Kaldır': 'നീക്കുക',
  'Kopyalandı: {}': 'കോപ്പി ചെയ്തു: {}',
  'Geçersiz kullanıcı adı': 'തെറ്റായ യൂസർനെയിം',
  'Bağlantı ekle': 'ലിങ്ക് ചേർക്കുക',
  'Spoiler olabilir — dokun ve gör': 'സ്പോയിലർ ഉണ്ടാകാം — കാണാൻ ടാപ്പ് ചെയ്യൂ',
  'Beğeni': 'ലൈക്കുകൾ',
  'beğeni': 'ലൈക്കുകൾ',
  'Beğen': 'ലൈക്ക്',
  'Görüntülenme': 'കാഴ്ചകൾ',
  'görüntülenme': 'കാഴ്ചകൾ',
  'Tam ekran': 'ഫുൾസ്ക്രീൻ',
  'Arama başarısız': 'തിരയൽ പരാജയപ്പെട്ടു',
  'Sonuç bulunamadı': 'ഫലങ്ങളൊന്നുമില്ല',
  'Dizi ve Filmler': 'സീരീസും സിനിമകളും',
  'Kişiler': 'വ്യക്തികൾ',
  'Ana Sayfa': 'ഹോം',
  'Paylaş': 'പങ്കിടുക',
  'Yanıtlar': 'മറുപടികൾ',
  'Yaklaşan Bölümler': 'വരാനിരിക്കുന്ന എപ്പിസോഡുകൾ',
  'Yetişme Listesi': 'ക്യാച്ച്-അപ്പ് ലിസ്റ്റ്',
  'Şunu mu demek istedin': 'നിങ്ങൾ ഉദ്ദേശിച്ചത്',
  'Spoiler': 'സ്പോയിലർ',
  'Spoiler — dokun ve gör': 'സ്പോയിലർ — കാണാൻ ടാപ്പ് ചെയ്യുക',
  'uyum': 'പൊരുത്തം',
  'Uyum': 'പൊരുത്തം',
  '{} ortak dizi': '{} പൊതു പരമ്പരകൾ',
  '{} ortak film': '{} പൊതു സിനിമകൾ',
  'Bildirim Tercihleri': 'അറിയിപ്പ് മുൻഗണനകൾ',
  'Beğeniler': 'ലൈക്കുകൾ',
  'Yeni takipçiler': 'പുതിയ ഫോളോവേഴ്സ്',
  'Etiketlenmeler': 'പരാമർശങ്ങൾ',
  'Yeniden izledim': 'വീണ്ടും കണ്ടു',
  '{}. kez izlendi': '{} തവണ കണ്ടു',
  'Gönderi bulunamadı': 'പോസ്റ്റ് കണ്ടെത്തിയില്ല',
  'Gözat': 'ബ്രൗസ്',
  'Diziler': 'പരമ്പരകൾ',
  'Filmler': 'സിനിമകൾ',
  'Tümü': 'എല്ലാം',
  'Farklı bir tür seç.': 'മറ്റൊരു വിഭാഗം പരീക്ഷിക്കൂ.',
  'Gizlilik': 'സ്വകാര്യത',
  'İzlediklerimi gizle': 'ഞാൻ കണ്ടവ മറയ്ക്കുക',
  'Profilinde izlediğin dizi ve filmler görünmez':
      'നീ കണ്ട സീരീസുകളും സിനിമകളും നിന്റെ പ്രൊഫൈലിൽ കാണില്ല',
  'Yorumlarımı gizle': 'എന്റെ കമന്റുകൾ മറയ്ക്കുക',
  'Profilinde yorumların görünmez': 'നിന്റെ കമന്റുകൾ നിന്റെ പ്രൊഫൈലിൽ കാണില്ല',
  'Tek bir dizi veya filmi, içeriğin sayfasındaki "Profilimde gizle" çipiyle gizleyebilirsin.':
      'ഏതെങ്കിലും ഒരു സീരീസോ സിനിമയോ അതിന്റെ പേജിലെ "എന്റെ പ്രൊഫൈലിൽ മറയ്ക്കുക" ചിപ്പ് ഉപയോഗിച്ച് മറയ്ക്കാം.',
  'Geri Bildirim': 'ഫീഡ്‌ബാക്ക്',
  'Uygulama hakkında görüş ve önerini yaz...':
      'ആപ്പിനെക്കുറിച്ചുള്ള നിന്റെ അഭിപ്രായവും നിർദ്ദേശങ്ങളും എഴുതൂ...',
  'Teşekkürler! Geri bildirimin alındı.': 'നന്ദി! നിന്റെ ഫീഡ്‌ബാക്ക് ലഭിച്ചു.',
  'Profilimde gizle': 'എന്റെ പ്രൊഫൈലിൽ മറയ്ക്കുക',
  'Yorumları': 'കമന്റുകൾ',
  'Bu kullanıcı henüz bir şey izlememiş.':
      'ഈ ഉപയോക്താവ് ഇതുവരെ ഒന്നും കണ്ടിട്ടില്ല.',
  'Bu kullanıcı yorumlarını gizli tutmayı tercih ediyor.':
      'ഈ ഉപയോക്താവ് കമന്റുകൾ സ്വകാര്യമായി സൂക്ഷിക്കാൻ ഇഷ്ടപ്പെടുന്നു.',
  'S{}B{}': 'S{}E{}',
  'Veri: JustWatch': 'ഡാറ്റ: JustWatch',
  'Web Sitesi': 'വെബ്സൈറ്റ്',
  'Diğer uygulamalar': 'മറ്റ് ആപ്പുകൾ',
  'Bağlantıyı kopyala': 'ലിങ്ക് പകർത്തുക',
  'Henüz kimseyi takip etmiyorsun.': 'നീ ഇതുവരെ ആരെയും ഫോളോ ചെയ്യുന്നില്ല.',
  'Çevir': 'വിവർത്തനം',
  'Çeviri şu an yapılamadı': 'ഇപ്പോൾ വിവർത്തനം സാധ്യമല്ല',
  'Bağlantı açılamadı': 'ലിങ്ക് തുറക്കാനായില്ല',
  'Orijinali göster': 'ഒറിജിനൽ കാണിക്കുക',
  'Çeviriyi göster': 'വിവർത്തനം കാണിക്കൂ',
  'Bu ay için yayın tarihi açıklanmış bölüm yok. Tarihler genelde birkaç hafta önceden duyurulur; açıklandıkça burada görünür.':
      'ഈ മാസം സംപ്രേഷണ തീയതി പ്രഖ്യാപിച്ച എപ്പിസോഡുകളില്ല. തീയതികൾ സാധാരണ ഏതാനും ആഴ്ച മുൻപ് അറിയിക്കും, അപ്പോൾ ഇവിടെ കാണാം.',
  'devamı': 'കൂടുതൽ',
  'Google ile devam et': 'Google ഉപയോഗിച്ച് തുടരുക',
  'Google girişi başarısız': 'Google സൈൻ ഇൻ പരാജയപ്പെട്ടു',
  'Veri tasarrufu': 'ഡാറ്റ ലാഭം',
  'Wi-Fi ağında veri tasarrufu': 'Wi-Fi യിൽ ഡാറ്റ ലാഭം',
  'Mobil veride veri tasarrufu': 'മൊബൈൽ ഡാറ്റയിൽ ഡാറ്റ ലാഭം',
  'Açıkken fotoğraflar önceden indirilmez, yalnızca baktığın kare yüklenir.':
      'ഓൺ ആയിരിക്കുമ്പോൾ ഫോട്ടോകൾ മുൻകൂട്ടി ഡൗൺലോഡ് ചെയ്യില്ല, നീ കാണുന്ന ചിത്രം മാത്രം ലോഡ് ആകും.',
  'Çocuk güvenliği': 'കുട്ടികളുടെ സുരക്ഷ',
  'Türk Filmleri': 'തുർക്കി സിനിമകൾ',
  'En Yüksek Puanlı Filmler': 'ഏറ്റവും ഉയർന്ന റേറ്റിംഗുള്ള സിനിമകൾ',
  'En Yüksek Puanlı Diziler': 'ഏറ്റവും ഉയർന്ന റേറ്റിംഗുള്ള പരമ്പരകൾ',
  'En Çok İzlenen Filmler': 'ഏറ്റവും കൂടുതൽ കണ്ട സിനിമകൾ',
  'Popüler Diziler': 'ജനപ്രിയ പരമ്പരകൾ',
  'En Çok Kazanan Filmler': 'ഏറ്റവും കൂടുതൽ വരുമാനം നേടിയ സിനിമകൾ',
  'Kült Filmler': 'കൾട്ട് സിനിമകൾ',
  'Yeni Filmler': 'പുതിയ സിനിമകൾ',
  'Yorum yap': 'അഭിപ്രായം ഇടുക',
  'Henüz yorum yok': 'ഇതുവരെ അഭിപ്രായങ്ങളില്ല',
  'Dizi ve filmlere yazdığın yorumlar burada toplanır.':
      'പരമ്പരകൾക്കും സിനിമകൾക്കും നീ എഴുതുന്ന അഭിപ്രായങ്ങൾ ഇവിടെ ചേരും.',
  'GIF ekle': 'GIF ചേർക്കുക',
  'İlk yorumu sen yaz': 'ആദ്യ അഭിപ്രായം നിങ്ങൾ എഴുതൂ',
  'Video altyazıları': 'വീഡിയോ സബ്ടൈറ്റിലുകൾ',
  'Videolarda altyazı göster': 'വീഡിയോകളിൽ സബ്‌ടൈറ്റിലുകൾ കാണിക്കുക',
  'Videoda konuşulan cümle ekranda yazılır. Metin çeviridir: Türkçe konuşmada İngilizce, diğer dillerde Türkçe.':
      'വീഡിയോയിൽ പറയുന്ന വാചകം സ്ക്രീനിൽ എഴുതിയിരിക്കുന്നു. വാചകം വിവർത്തനം ആണ്: ടർക്കിഷ് ഭാഷയിൽ ഇംഗ്ലീഷ്, മറ്റ് ഭാഷകളിൽ ടർക്കിഷ്.',
  'Güncelleme gerekli': 'അപ്ഡേറ്റ് ആവശ്യമാണ്',
  'Yeni sürüm var': 'പുതിയ പതിപ്പ് ലഭ്യമാണ്',
  "Devam etmek için dizi.jpg'in yeni sürümünü yükle.":
      'തുടരാൻ dizi.jpg ന്റെ പുതിയ പതിപ്പ് ഇൻസ്റ്റാൾ ചെയ്യുക.',
  'Güncelle': 'അപ്ഡേറ്റ് ചെയ്യുക',
  'Daha sonra': 'പിന്നീട്',
  'Takvim güncelleniyor': 'കലണ്ടർ അപ്ഡേറ്റ് ചെയ്യുന്നു',
  'Takvim güncellenemedi, eski liste gösteriliyor':
      'കലണ്ടർ അപ്ഡേറ്റ് ചെയ്യാനായില്ല, പഴയ പട്ടിക കാണിക്കുന്നു',
  'Bazı diziler yüklenemedi, liste eksik olabilir':
      'ചില പരമ്പരകൾ ലോഡ് ചെയ്യാനായില്ല, പട്ടിക അപൂർണ്ണമാകാം',
  'Yenile': 'പുതുക്കുക',
  'Devam etmek için giriş yap': 'തുടരാൻ ലോഗിൻ ചെയ്യുക',
  'Puan vermek, yorum yazmak ve kitaplığını oluşturmak için ücretsiz bir hesap yeterli.':
      'റേറ്റിംഗ് നൽകാനും അഭിപ്രായം എഴുതാനും നിങ്ങളുടെ ലൈബ്രറി ഉണ്ടാക്കാനും ഒരു സൗജന്യ അക്കൗണ്ട് മതി.',
  'Şimdi değil': 'ഇപ്പോൾ വേണ്ട',
  'Yorum yazmak için giriş yap': 'അഭിപ്രായം എഴുതാൻ ലോഗിൻ ചെയ്യുക',
  'Kişilere göndermek için giriş yap': 'ആളുകൾക്ക് അയക്കാൻ ലോഗിൻ ചെയ്യുക',
  'Beğenenler': 'ഇഷ്ടപ്പെട്ടവർ',
  'Henüz beğeni yok': 'ഇതുവരെ ലൈക്കുകൾ ഇല്ല',
  'Bu gönderiyi ilk beğenen sen ol': 'ഈ പോസ്റ്റ് ആദ്യം ഇഷ്ടപ്പെടൂ',
  'Bu gönderiye yanıt': 'ഈ പോസ്റ്റിനുള്ള മറുപടി',
  'Spoiler içeren gönderi': 'സ്പോയിലർ അടങ്ങിയ പോസ്റ്റ്',
  'Görsel gönderi': 'ഫോട്ടോ പോസ്റ്റ്',
  'Bu yorumu profilimde gizle': 'ഈ കമന്റ് എന്റെ പ്രൊഫൈലിൽ മറയ്ക്കുക',
  'Yorum dizi ve film sayfasında durmaya devam eder':
      'കമന്റ് സീരീസ്, സിനിമ പേജിൽ അതേപടി തുടരും',
  'Bu yorumu sil': 'ഈ കമന്റ് ഇല്ലാതാക്കുക',
  'Yorum profilinde gizlendi': 'കമന്റ് നിങ്ങളുടെ പ്രൊഫൈലിൽ മറച്ചു',
  'Geri al': 'പഴയപടിയാക്കുക',
  'Yorum silinsin mi?': 'കമന്റ് ഇല്ലാതാക്കണോ?',
  'Bu yorum her yerden kalıcı olarak silinir. Geri alınamaz.':
      'ഈ കമന്റ് എല്ലായിടത്തുനിന്നും ശാശ്വതമായി ഇല്ലാതാകും. തിരികെ എടുക്കാൻ കഴിയില്ല.',
  'Yorum silindi': 'കമന്റ് ഇല്ലാതാക്കി',
  'Yorum profilinde tekrar görünüyor':
      'കമന്റ് നിങ്ങളുടെ പ്രൊഫൈലിൽ വീണ്ടും കാണാം',
  'Gizlenen yorumun yok': 'മറച്ചുവെച്ച കമന്റുകൾ ഇല്ല',
  'Profilindeki Yorumlar sekmesinde bir gönderiye basılı tutup gizlediklerin burada birikir.':
      'നിങ്ങളുടെ പ്രൊഫൈലിലെ കമന്റുകൾ ടാബിൽ ഒരു പോസ്റ്റ് അമർത്തിപ്പിടിച്ച് മറച്ചവ ഇവിടെ ശേഖരിക്കപ്പെടും.',
  'Gizlenen yorumlar': 'മറച്ചുവെച്ച കമന്റുകൾ',
  'Gönderiye git': 'പോസ്റ്റിലേക്ക് പോകുക',
  'Tekrar göster': 'വീണ്ടും കാണിക്കുക',
  'Yanıtlarımı gizle': 'എന്റെ മറുപടികൾ മറയ്ക്കുക',
  'Başkalarının gönderilerine yazdığın yanıtlar yalnız sana görünür':
      'മറ്റുള്ളവരുടെ പോസ്റ്റുകൾക്ക് നിങ്ങൾ എഴുതിയ മറുപടികൾ നിങ്ങൾക്ക് മാത്രമേ കാണാനാകൂ',
  'Profilinde gizlediğin yorumları tekrar göster':
      'നിങ്ങളുടെ പ്രൊഫൈലിൽ മറച്ച കമന്റുകൾ വീണ്ടും കാണിക്കുക',
  'Sıralama': 'ക്രമം',
  'Önerilen': 'ശുപാർശ ചെയ്തത്',
  'Kronolojik': 'കാലക്രമം',
  'Gelen mesaj istekleri': 'വന്ന സന്ദേശ അഭ്യർത്ഥനകൾ',
  'Mesaj isteğin yok': 'സന്ദേശ അഭ്യർത്ഥനകളൊന്നുമില്ല',
  'Takip etmediğin kişilerden gelen mesajlar burada görünür.':
      'നിങ്ങൾ പിന്തുടരാത്തവരുടെ സന്ദേശങ്ങൾ ഇവിടെ കാണാം.',
  'Çevrimiçi durumumu gizle': 'എന്റെ ഓൺലൈൻ നില മറയ്ക്കുക',
  'Mesajlarda çevrimiçi olduğun ve son görülme zamanın başkalarına görünmez':
      'മറ്റുള്ളവർക്ക് സന്ദേശങ്ങളിൽ നിങ്ങളുടെ ഓൺലൈൻ നിലയും അവസാനം കണ്ട സമയവും കാണാനാകില്ല',
  'İlk kullanıcılarımızdan biri. Geri bildirimleriyle uygulamanın bugün olduğu hale gelmesine katkı sağladı.':
      'ഞങ്ങളുടെ ആദ്യ ഉപയോക്താക്കളിൽ ഒരാൾ. അവരുടെ അഭിപ്രായങ്ങൾ ആപ്പ് ഇന്നത്തെ രൂപത്തിലാകാൻ സഹായിച്ചു.',
  'İlk kullanıcılarımızdan birisin. Geri bildirimlerinle uygulamanın bugün olduğu hale gelmesine katkı sağladın.':
      'നീ ഞങ്ങളുടെ ആദ്യ ഉപയോക്താക്കളിൽ ഒരാളാണ്. നിന്റെ അഭിപ്രായങ്ങൾ ആപ്പ് ഇന്നത്തെ രൂപത്തിലാകാൻ സഹായിച്ചു.',
  'İleri': 'അടുത്തത്',
  'Önceki': 'മുമ്പത്തെ',
  'Sonraki': 'അടുത്തത്',
  'Seçilen dosya okunamadı': 'തിരഞ്ഞെടുത്ത ഫയൽ വായിക്കാനായില്ല',
  'Video açılamadı': 'വീഡിയോ തുറക്കാനായില്ല',
  'En fazla {} medya seçebilirsin': 'പരമാവധി {} മീഡിയ തിരഞ്ഞെടുക്കാം',
  'Hiçbir medya yüklenemedi': 'ഒരു മീഡിയയും അപ്‌ലോഡ് ചെയ്യാനായില്ല',
  'Seçimi kaldır': 'തിരഞ്ഞെടുപ്പ് നീക്കുക',
  'Tek yorumda toplam {} MB medya yükleyebilirsin':
      'ഒരു അഭിപ്രായത്തിൽ ആകെ {} MB അപ്‌ലോഡ് ചെയ്യാം',
  '{} dosya okunamadı': '{} ഫയലുകൾ വായിക്കാനായില്ല',
  '{} medya eklendi, {} yüklenemedi': '{} മീഡിയ ചേർത്തു, {} പരാജയപ്പെട്ടു',
  'Kırp': 'ക്രോപ്പ്',
  'Çiz': 'വരയ്ക്കുക',
  'Metin': 'ടെക്സ്റ്റ്',
  'Emoji': 'ഇമോജി',
  'Yinele': 'വീണ്ടും ചെയ്യുക',
  'Daha fazla': 'കൂടുതൽ',
  'Hazırlanıyor…': 'തയ്യാറാക്കുന്നു…',
  'Düzenlemeden çık?': 'എഡിറ്റിംഗ് അവസാനിപ്പിക്കണോ?',
  'Yaptığın değişiklikler kaybolacak.':
      'നിങ്ങൾ വരുത്തിയ മാറ്റങ്ങൾ നഷ്ടപ്പെടും.',
  'Çık': 'പുറത്തുകടക്കുക',
  'Serbest çizim': 'ഫ്രീഹാൻഡ്',
  'Ok': 'അമ്പ്',
  'Dikdörtgen': 'ദീർഘചതുരം',
  'Daire': 'വൃത്തം',
  'Bulanıklaştır': 'മങ്ങിക്കുക',
  'Pikselleştir': 'പിക്സലേറ്റ്',
  'Silgi': 'ഇറേസർ',
  'Çizgi kalınlığı': 'വരയുടെ കനം',
  'Saydamlık': 'അതാര്യത',
  'Dolgu': 'നിറയ്ക്കുക',
  'Renk': 'നിറം',
  'Döndür': 'തിരിക്കുക',
  'Yansıt': 'മറിക്കുക',
  'Oran': 'അനുപാതം',
  'Sıfırla': 'പുനഃസജ്ജമാക്കുക',
  'Serbest': 'സ്വതന്ത്രം',
  'Metin yaz...': 'ടെക്സ്റ്റ് ടൈപ്പ് ചെയ്യുക...',
  'Hizala': 'വിന്യസിക്കുക',
  'Arka plan': 'പശ്ചാത്തലം',
  'Emoji ara...': 'ഇമോജി തിരയുക...',
  'Son kullanılanlar': 'അടുത്തിടെ',
  'İfadeler ve insanlar': 'സ്മൈലികളും ആളുകളും',
  'Hayvanlar ve doğa': 'മൃഗങ്ങളും പ്രകൃതിയും',
  'Yiyecek ve içecek': 'ഭക്ഷണവും പാനീയവും',
  'Etkinlikler': 'പ്രവർത്തനങ്ങൾ',
  'Seyahat ve yerler': 'യാത്രയും സ്ഥലങ്ങളും',
  'Nesneler': 'വസ്തുക്കൾ',
  'Semboller': 'ചിഹ്നങ്ങൾ',
  'Bayraklar': 'പതാകകൾ',
  'Görseli düzenle': 'ചിത്രം എഡിറ്റ് ചെയ്യുക',
  'Düzenlendi': 'എഡിറ്റ് ചെയ്തു',
  'Düzenlenemedi': 'എഡിറ്റ് ചെയ്യാനായില്ല',
  'Düzenlenen görsel çok büyük': 'എഡിറ്റ് ചെയ്ത ചിത്രം വളരെ വലുതാണ്',
  'Videoyu düzenle': 'വീഡിയോ എഡിറ്റ് ചെയ്യുക',
  'Sesi kapat': 'ശബ്ദം ഓഫാക്കുക',
  'Sesi aç': 'ശബ്ദം ഓണാക്കുക',
  'İptal ediliyor…': 'റദ്ദാക്കുന്നു…',
  'Bu biraz sürebilir': 'ഇതിന് കുറച്ച് സമയമെടുത്തേക്കാം',
  'Video çok büyük': 'വീഡിയോ വളരെ വലുതാണ്',
  'Video hazırlanamadı': 'വീഡിയോ തയ്യാറാക്കാനായില്ല',
  'Başlangıç': 'തുടക്കം',
  'Bitiş': 'അവസാനം',
  'En çok {} saniye seçebilirsin': 'പരമാവധി {} സെക്കൻഡ് തിരഞ്ഞെടുക്കാം',
  'Dosya en fazla {} MB olabilir': 'ഫയൽ പരമാവധി {} MB ആകാം',
  'Medya ekle': 'മീഡിയ ചേർക്കുക',
  'Seçili medya kalmadı': 'മീഡിയ ഒന്നും തിരഞ്ഞെടുത്തിട്ടില്ല',
  'Yorumuna eklemek için fotoğraf veya video seç.':
      'നിങ്ങളുടെ കമന്റിൽ ചേർക്കാൻ ഒരു ഫോട്ടോ അല്ലെങ്കിൽ വീഡിയോ തിരഞ്ഞെടുക്കുക.',
  'Medya seç': 'മീഡിയ തിരഞ്ഞെടുക്കുക',
  'Daha fazla ekle': 'കൂടുതൽ ചേർക്കുക',
  'Medya seçilemedi': 'മീഡിയ തിരഞ്ഞെടുക്കാനായില്ല',
  'Favori oyuncular': 'പ്രിയപ്പെട്ട നടന്മാർ',
  'Henüz favori oyuncun yok': 'ഇതുവരെ പ്രിയപ്പെട്ട നടന്മാരില്ല',
  'Bir oyuncunun sayfasını aç ve sağ üstteki kalbe dokun; buraya eklensin.':
      'ഒരു നടന്റെ പേജ് തുറന്ന് വലതു മുകളിലെ ഹൃദയത്തിൽ ടാപ്പ് ചെയ്യുക.',
  '{} yapımdan {} tanesini izledin': '{} ൽ {} കണ്ടു',
  'izledin': 'കണ്ടു',
  'İzlemedin': 'കണ്ടിട്ടില്ല',
  'Yapım bulunamadı': 'ഒന്നും കണ്ടെത്തിയില്ല',
  'Bu kişinin listelenecek dizi veya filmi yok.':
      'ഈ വ്യക്തിക്ക് കാണിക്കാൻ പരമ്പരകളോ സിനിമകളോ ഇല്ല.',
  'İzlediklerin hesabına bağlı; bu liste yalnız sana özel.':
      'നിങ്ങളുടെ ചരിത്രം അക്കൗണ്ടുമായി ബന്ധപ്പെട്ടതാണ്; ഈ പട്ടിക നിങ്ങളുടേത് മാത്രം.',
  'Hesabın kalıcı olarak askıya alındı':
      'നിങ്ങളുടെ അക്കൗണ്ട് ശാശ്വതമായി താൽക്കാലികമായി നിർത്തി',
  'Hesabın geçici olarak askıya alındı':
      'നിങ്ങളുടെ അക്കൗണ്ട് താൽക്കാലികമായി നിർത്തി',
  'Hesabın askıya alındı': 'നിങ്ങളുടെ അക്കൗണ്ട് നിർത്തിവച്ചിരിക്കുന്നു',
  'Sebep': 'കാരണം',
  'Kalan süre': 'ബാക്കി സമയം',
  'Süre dolunca hesabın kendiliğinden açılır':
      'സമയം കഴിയുമ്പോൾ അക്കൗണ്ട് സ്വയം തുറക്കും',
  'Bu süre boyunca okumaya devam edebilirsin; gönderi, yorum ve mesaj gönderemezsin.':
      'ഈ സമയത്ത് വായിക്കാം, പക്ഷേ പോസ്റ്റ്, കമന്റ് അല്ലെങ്കിൽ സന്ദേശം അയക്കാൻ കഴിയില്ല.',
  'Anladım': 'മനസ്സിലായി',
  'Ayrıntı': 'വിശദാംശം',
  '{} dakika': '{} മിനിറ്റ്',
  'birkaç saniye': 'ഏതാനും സെക്കൻഡ്',
  'Karara itiraz et': 'ഈ തീരുമാനത്തിനെതിരെ അപ്പീൽ നൽകുക',
  'Neden bu cezanın kaldırılması gerektiğini anlat':
      'ഈ ശിക്ഷ എന്തുകൊണ്ട് നീക്കണമെന്ന് വിശദീകരിക്കുക',
  'İtirazını gönder': 'നിങ്ങളുടെ അപ്പീൽ അയയ്ക്കുക',
  'İtirazın incelemede': 'നിങ്ങളുടെ അപ്പീൽ പരിശോധനയിലാണ്',
  'İtirazın reddedildi': 'നിങ്ങളുടെ അപ്പീൽ നിരസിച്ചു',
  'İtirazın alındı, inceleniyor': 'നിങ്ങളുടെ അപ്പീൽ ലഭിച്ചു, പരിശോധനയിലാണ്',
  'İtiraz en az 10 karakter olmalı': 'അപ്പീൽ കുറഞ്ഞത് 10 അക്ഷരം വേണം',
  'Yükleniyor...': 'ലോഡ് ചെയ്യുന്നു...',
  'Bu bölüme puan ver': 'ഈ എപ്പിസോഡ് റേറ്റ് ചെയ്യുക',
  '{} kişi puanladı': '{} പേർ റേറ്റ് ചെയ്തു',
  'Bölüm izlendi olarak işaretlendi': 'എപ്പിസോഡ് കണ്ടതായി അടയാളപ്പെടുത്തി',
  'Sesli ara': 'വോയ്‌സ് കോൾ',
  'Görüntülü ara': 'വീഡിയോ കോൾ',
  'Çalıyor...': 'റിംഗ് ചെയ്യുന്നു...',
  'Bağlanıyor...': 'കണക്റ്റ് ചെയ്യുന്നു...',
  'Cevapla': 'മറുപടി നൽകുക',
  'Reddet': 'നിരസിക്കുക',
  'Sessize al': 'മ്യൂട്ട്',
  'Hoparlör': 'സ്പീക്കർ',
  'Kamerayı kapat': 'ക്യാമറ ഓഫാക്കുക',
  'Kamerayı çevir': 'ക്യാമറ മാറ്റുക',
  'Cevap yok': 'മറുപടിയില്ല',
  'Arama reddedildi': 'കോൾ നിരസിച്ചു',
  'Meşgul': 'തിരക്കിലാണ്',
  'Bağlanılamadı': 'കണക്റ്റ് ചെയ്യാനായില്ല',
  'Arama iptal edildi': 'കോൾ റദ്ദാക്കി',
  'Arama geçmişi': 'കോൾ ചരിത്രം',
  'Gelen arama': 'ഇൻകമിംഗ് കോൾ',
  'Giden arama': 'ഔട്ട്‌ഗോയിംഗ് കോൾ',
  'Cevapsız arama': 'മിസ്ഡ് കോൾ',
  'Arama şu anda kullanılamıyor': 'കോൾ ഇപ്പോൾ ലഭ്യമല്ല',
  'Görüntülü arama şu anda kapalı, sesli arayabilirsin':
      'വീഡിയോ കോൾ ഇപ്പോൾ ഓഫാണ്, നിങ്ങൾക്ക് വോയ്‌സ് കോൾ ചെയ്യാം',
  'Bu kullanıcıyı arayamazsın': 'ഈ ഉപയോക്താവിനെ വിളിക്കാനാവില്ല',
  'Aramak için karşılıklı takipleşmelisiniz':
      'വിളിക്കാൻ നിങ്ങൾ പരസ്പരം ഫോളോ ചെയ്യണം',
  'Bu kullanıcı şu anda aranamıyor': 'ഈ ഉപയോക്താവിനെ ഇപ്പോൾ വിളിക്കാനാവില്ല',
  'Çok fazla cevapsız arama. {} sonra tekrar dene':
      'വളരെയധികം മിസ്ഡ് കോളുകൾ. {} കഴിഞ്ഞ് വീണ്ടും ശ്രമിക്കുക',
  'Zaten bir aramadasın': 'നിങ്ങൾ ഇതിനകം ഒരു കോളിലാണ്',
  'Arama için mikrofon izni gerekiyor': 'വിളിക്കാൻ മൈക്രോഫോൺ അനുമതി വേണം',
  'Görüntülü arama için kamera ve mikrofon izni gerekiyor':
      'വീഡിയോ കോളിന് ക്യാമറയും മൈക്രോഫോണും അനുമതി വേണം',
  'Arama başlatılamadı': 'കോൾ ആരംഭിക്കാനായില്ല',
  'Kullanıcı bulunamadı': 'ഉപയോക്താവിനെ കണ്ടെത്തിയില്ല',
  'Kendini arayamazsın': 'സ്വയം വിളിക്കാനാവില്ല',
  'Arama artık geçerli değil': 'ഈ കോൾ ഇനി സാധുവല്ല',
  'Bu aramanın tarafı değilsin': 'നിങ്ങൾ ഈ കോളിന്റെ ഭാഗമല്ല',
  'Arama bulunamadı': 'കോൾ കണ്ടെത്തിയില്ല',
  'Çok fazla istek, biraz bekle':
      'അഭ്യർത്ഥനകൾ വളരെ കൂടുതൽ, അൽപ്പം കാത്തിരിക്കുക',
  'Bağlantı koptu': 'കണക്ഷൻ നഷ്ടപ്പെട്ടു',
  'Arama süre sınırına ulaştı': 'കോൾ സമയപരിധിയിലെത്തി',
  'Arama en fazla 4 saat sürebilir': 'ഒരു കോൾ പരമാവധി 4 മണിക്കൂർ നീളാം',
  'Arama sona erdi': 'കോൾ അവസാനിച്ചു',
  'Sesli arama': 'വോയ്‌സ് കോൾ',
  'Görüntülü arama': 'വീഡിയോ കോൾ',
  'Gelen aramalar': 'ഇൻകമിംഗ് കോളുകൾ',
  'Sesli ve görüntülü arama bildirimleri': 'വോയ്‌സ്, വീഡിയോ കോൾ അറിയിപ്പുകൾ',
  '{} sa': '{} മ',
  'Sesli ve Görüntülü Aramalar': 'വോയ്‌സ്, വീഡിയോ കോളുകൾ',
  'Aramaların içeriği kaydedilmez. Ses ve görüntü, cihazlar arasında uçtan uca şifreli (DTLS-SRTP) akar; sunucularımız bu trafiği çözemez, dinleyemez ve saklayamaz.':
      'കോളിന്റെ ഉള്ളടക്കം ഒരിക്കലും റെക്കോർഡ് ചെയ്യുന്നില്ല. ഓഡിയോയും വീഡിയോയും ഉപകരണങ്ങൾക്കിടയിൽ എൻഡ്-ടു-എൻഡ് എൻക്രിപ്റ്റ് ചെയ്ത് (DTLS-SRTP) ഒഴുകുന്നു; ഞങ്ങളുടെ സെർവറുകൾക്ക് ഇത് ഡീക്രിപ്റ്റ് ചെയ്യാനോ കേൾക്കാനോ സൂക്ഷിക്കാനോ കഴിയില്ല.',
  'Yalnızca arama üstverisi tutulur: kiminle, hangi yönde, ne zaman ve ne kadar sürdüğü. Bu kayıtlar 90 gün sonra otomatik silinir.':
      'കോൾ മെറ്റാഡേറ്റ മാത്രമേ സൂക്ഷിക്കുന്നുള്ളൂ: ആരുമായി, ഏത് ദിശയിൽ, എപ്പോൾ, എത്ര നേരം. ഈ രേഖകൾ 90 ദിവസത്തിനു ശേഷം സ്വയമേവ ഇല്ലാതാകും.',
  'Doğrudan bağlantı kurulamazsa ses ve görüntü şifreli hâlde bir aktarma sunucusundan (TURN) geçer. Aktarma sunucusu da içeriği çözemez ve kaydetmez.':
      'നേരിട്ടുള്ള കണക്ഷൻ സാധ്യമല്ലെങ്കിൽ ഓഡിയോയും വീഡിയോയും എൻക്രിപ്റ്റ് ചെയ്ത നിലയിൽ ഒരു റിലേ സെർവർ (TURN) വഴി കടന്നുപോകും. റിലേ സെർവറിനും ഉള്ളടക്കം ഡീക്രിപ്റ്റ് ചെയ്യാനോ റെക്കോർഡ് ചെയ്യാനോ കഴിയില്ല.',
  'Mikrofon yalnızca sesli veya görüntülü arama sırasında, kamera ise yalnızca görüntülü arama sırasında kullanılır. Arama bitince ikisi de kapatılır.':
      'മൈക്രോഫോൺ വോയ്‌സ് അല്ലെങ്കിൽ വീഡിയോ കോൾ സമയത്തും ക്യാമറ വീഡിയോ കോൾ സമയത്തും മാത്രമേ ഉപയോഗിക്കൂ. കോൾ കഴിഞ്ഞാൽ രണ്ടും ഓഫാകും.',
  'Takip ettiğin {} kişi izledi': 'നിങ്ങൾ പിന്തുടരുന്ന {} പേർ കണ്ടു',
  'Yorum yaz...': 'അഭിപ്രായം എഴുതൂ...',
  'Sıradaki bölüm': 'അടുത്ത എപ്പിസോഡ്',
  'Doğrulanmış testçi': 'സ്ഥിരീകരിച്ച ടെസ്റ്റർ',
  'Takip, beğeni, yanıt, mesaj ve etiket bildirimleri':
      'ഫോളോ, ലൈക്ക്, മറുപടി, സന്ദേശം, ടാഗ് അറിയിപ്പുകൾ',
  'Sen': 'നിങ്ങൾ',
  'Aradığınız kişide sesli arama devre dışı':
      'ഈ വ്യക്തിക്ക് വോയ്‌സ് കോൾ പ്രവർത്തനരഹിതമാണ്',
  'Aradığınız kişide görüntülü arama devre dışı':
      'ഈ വ്യക്തിക്ക് വീഡിയോ കോൾ പ്രവർത്തനരഹിതമാണ്',
  'Sesli aramalara izin ver': 'വോയ്‌സ് കോളുകൾ അനുവദിക്കുക',
  'Görüntülü aramalara izin ver': 'വീഡിയോ കോളുകൾ അനുവദിക്കുക',
  'Kapalıyken kimse seni sesli arayamaz; arayan uyarı görür':
      'ഓഫ് ആയിരിക്കുമ്പോൾ ആർക്കും നിങ്ങളെ വോയ്‌സ് കോൾ ചെയ്യാനാവില്ല; വിളിക്കുന്നയാൾ അറിയിപ്പ് കാണും',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan uyarı görür':
      'ഓഫ് ആയിരിക്കുമ്പോൾ ആർക്കും നിങ്ങളെ വീഡിയോ കോൾ ചെയ്യാനാവില്ല; വിളിക്കുന്നയാൾ അറിയിപ്പ് കാണും',
  'Sesli arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'വോയ്‌സ് കോൾ ഓഫാണ്. ക്രമീകരണങ്ങൾ > സ്വകാര്യത എന്നതിൽ നിന്ന് ഓണാക്കാം.',
  'Görüntülü arama kapalı. Ayarlar > Gizlilik bölümünden açabilirsin.':
      'വീഡിയോ കോൾ ഓഫാണ്. ക്രമീകരണങ്ങൾ > സ്വകാര്യത എന്നതിൽ നിന്ന് ഓണാക്കാം.',
  'Sesli ve görüntülü arama': 'വോയ്‌സ്, വീഡിയോ കോൾ',
  'Misafir hesaplar arama yapamaz. Hesap oluşturursan kullanabilirsin.':
      'അതിഥി അക്കൗണ്ടുകൾക്ക് വിളിക്കാനാകില്ല. അക്കൗണ്ട് ഉണ്ടാക്കിയാൽ ഉപയോഗിക്കാം.',
  'Misafir hesaplar aranamaz': 'അതിഥി അക്കൗണ്ടുകളെ വിളിക്കാനാകില്ല',
  'Puan dağılımı': 'റേറ്റിംഗ് വിതരണം',
  '{} yıldız': '{} സ്റ്റാർ',
  'Yakında gelecek': 'ഉടൻ വരുന്നു',
  '{} {} yayınlandı': '{} {} പുറത്തിറങ്ങി',
  'Yeni bölüm yayınlandı': 'പുതിയ എപ്പിസോഡ് പുറത്തിറങ്ങി',
  'Yeni bölümler': 'പുതിയ എപ്പിസോഡുകൾ',
  'Geri': 'പിന്നോട്ട്',
  'Karşılamayı kapat': 'സ്വാഗതം അടയ്ക്കുക',
  'Adım {} / {}': 'ഘട്ടം {} / {}',
  'Hadi başlayalım': 'നമുക്ക് തുടങ്ങാം',
  'Kaydet ve devam': 'സേവ് ചെയ്ത് തുടരുക',
  '{} tanesini ekle': '{} എണ്ണം ചേർക്കൂ',
  'Şimdilik geç': 'തൽക്കാലം ഒഴിവാക്കൂ',
  'Doğum tarihin ne zaman?': 'നിങ്ങളുടെ ജനനത്തീയതി എപ്പോഴാണ്?',
  'Yaşına uygun içerik göstermek ve doğum gününü kutlamak için soruyoruz.':
      'പ്രായത്തിനു ചേരുന്ന ഉള്ളടക്കം കാണിക്കാനും പിറന്നാൾ ആശംസിക്കാനുമാണ് ഞങ്ങൾ ചോദിക്കുന്നത്.',
  'Gün': 'ദിവസം',
  'Ay': 'മാസം',
  'Yıl': 'വർഷം',
  'Doğum yılımı paylaşmak istemiyorum': 'ജനന വർഷം കാണിക്കേണ്ട',
  'Doğum tarihin profilinde herkese açık gösterilmez. Yalnız yaşa uygun içerik ve doğum günü kutlaması için kullanılır.':
      'നിങ്ങളുടെ ജനനത്തീയതി പ്രൊഫൈലിൽ പരസ്യമായി കാണിക്കില്ല. പ്രായത്തിനു ചേരുന്ന ഉള്ളടക്കത്തിനും പിറന്നാൾ ആശംസയ്ക്കും മാത്രമേ ഉപയോഗിക്കൂ.',
  'Ocak': 'ജനുവരി',
  'Şubat': 'ഫെബ്രുവരി',
  'Mart': 'മാർച്ച്',
  'Nisan': 'ഏപ്രിൽ',
  'Mayıs': 'മേയ്',
  'Haziran': 'ജൂൺ',
  'Temmuz': 'ജൂലൈ',
  'Ağustos': 'ഓഗസ്റ്റ്',
  'Eylül': 'സെപ്റ്റംബർ',
  'Ekim': 'ഒക്ടോബർ',
  'Kasım': 'നവംബർ',
  'Aralık': 'ഡിസംബർ',
  'Verilerini yanında getir': 'നിങ്ങളുടെ ഡാറ്റ ഒപ്പം കൊണ്ടുവരൂ',
  'Başka bir uygulamada izlediklerini takip ediyorsan buraya taşıyabilirsin. Sıfırdan başlamana gerek yok.':
      'മറ്റൊരു ആപ്പിൽ കണ്ടവ ട്രാക്ക് ചെയ്യുന്നുണ്ടെങ്കിൽ അവ ഇവിടേക്ക് കൊണ്ടുവരാം. പൂജ്യത്തിൽ നിന്ന് തുടങ്ങേണ്ട.',
  'Dışa aktardığın ZIP dosyasını seç; izlediklerin, puanların ve listelerin aktarılsın.':
      'എക്സ്പോർട്ട് ചെയ്ത ZIP ഫയൽ തിരഞ്ഞെടുക്കൂ; കണ്ടവയും റേറ്റിംഗുകളും ലിസ്റ്റുകളും എത്തിക്കോളും.',
  'Aktarılıyor...': 'ഇമ്പോർട്ട് ചെയ്യുന്നു...',
  'ZIP dosyası seç': 'ZIP ഫയൽ തിരഞ്ഞെടുക്കൂ',
  'Aceleye gerek yok: bunu sonra Ayarlar > Verilerim bölümünden de yapabilirsin.':
      'തിടുക്കമില്ല: ഇത് പിന്നീട് സെറ്റിംഗ്സ് > എന്റെ ഡാറ്റ എന്നതിൽ നിന്നും ചെയ്യാം.',
  'Hangi filmleri izledin?': 'ഏതൊക്കെ സിനിമകൾ കണ്ടിട്ടുണ്ട്?',
  'En çok izlenenler burada. Dokunduklarını izlediklerine ekleyelim.':
      'ഏറ്റവും കൂടുതൽ കണ്ടവ ഇവിടെയുണ്ട്. ടാപ്പ് ചെയ്യുന്നവ കണ്ടവയിലേക്ക് ചേർക്കാം.',
  'SERİ FİLMLER': 'സിനിമാ പരമ്പരകൾ',
  'Serilerden {} film eklendi': 'പരമ്പരകളിൽ നിന്ന് {} സിനിമ ചേർത്തു',
  'Film listesi yüklenemedi': 'സിനിമകളുടെ പട്ടിക ലോഡ് ചെയ്യാനായില്ല',
  'Bu adımı geçebilirsin, sonra istediğini ekleyebilirsin.':
      'ഈ ഘട്ടം ഒഴിവാക്കാം, പിന്നീട് വേണ്ടത് ചേർക്കാം.',
  '{} film izlediklerine eklendi': '{} സിനിമ കണ്ടവയിലേക്ക് ചേർത്തു',
  'Film serileri': 'സിനിമാ പരമ്പരകൾ',
  'Bir seriyi baştan sona izlediysen tek dokunuşla ekle.':
      'ഒരു പരമ്പര തുടക്കം മുതൽ അവസാനം വരെ കണ്ടിട്ടുണ്ടെങ്കിൽ ഒറ്റ ടാപ്പിൽ ചേർക്കൂ.',
  'Seri bulunamadı': 'പരമ്പരയൊന്നും കണ്ടെത്തിയില്ല',
  'Daha sonra tekrar deneyebilirsin.': 'പിന്നീട് വീണ്ടും ശ്രമിക്കാം.',
  '{} film': '{} സിനിമ',
  'Eklendi': 'ചേർത്തു',
  'Tümünü izledim': 'എല്ലാം കണ്ടു',
  'Peki ya diziler?': 'സീരീസുകളോ?',
  'İzlediklerini işaretle; seçtikçe sana benzeyenleri getireceğiz.':
      'കണ്ടവ അടയാളപ്പെടുത്തൂ; തിരഞ്ഞെടുക്കുന്തോറും സമാനമായവ എത്തിക്കാം.',
  'Dizi listesi yüklenemedi': 'സീരീസുകളുടെ പട്ടിക ലോഡ് ചെയ്യാനായില്ല',
  'Seçtiklerine benzeyenler': 'തിരഞ്ഞെടുത്തവയോട് സമാനമായവ',
  'Her şey hazır': 'എല്ലാം തയ്യാർ',
  "dizi.jpg'de neler yapabileceğine hızlıca göz at.":
      'dizi.jpg-യിൽ എന്തൊക്കെ ചെയ്യാമെന്ന് പെട്ടെന്ന് ഒന്നു നോക്കൂ.',
  'Profilini tamamla': 'പ്രൊഫൈൽ പൂർത്തിയാക്കൂ',
  "Ayarlar'dan bir bio, profil fotoğrafı ve kapak ekleyebilirsin.":
      'സെറ്റിംഗ്സിൽ നിന്ന് ബയോ, പ്രൊഫൈൽ ചിത്രം, കവർ എന്നിവ ചേർക്കാം.',
  'Takvimin seni bekliyor': 'കലണ്ടർ നിങ്ങളെ കാത്തിരിക്കുന്നു',
  'İzlediğin dizilerin yeni bölümleri takvime düşer, bildirimle haber veririz.':
      'കാണുന്ന സീരീസുകളുടെ പുതിയ എപ്പിസോഡുകൾ കലണ്ടറിൽ വരും, അറിയിപ്പായി അറിയിക്കാം.',
  'Puan ver, yorum yaz': 'റേറ്റ് ചെയ്യൂ, കമന്റ് എഴുതൂ',
  'Bölüm bölüm puanla, spoiler perdesiyle yorum yaz, listeler oluştur.':
      'എപ്പിസോഡ് തോറും റേറ്റ് ചെയ്യൂ, സ്പോയിലർ മറയോടെ കമന്റ് എഴുതൂ, ലിസ്റ്റുകൾ ഉണ്ടാക്കൂ.',
  'Verilerin sende kalır': 'ഡാറ്റ നിങ്ങളുടേതായി തന്നെ നിൽക്കും',
  "Verilerin yalnız hesabına bağlı tutulur, satılmaz. Ayarlar'dan hepsini indirebilir ya da hesabını tamamen silebilirsin.":
      'നിങ്ങളുടെ ഡാറ്റ അക്കൗണ്ടിനോട് മാത്രം ചേർത്താണ് സൂക്ഷിക്കുന്നത്, വിൽക്കുന്നില്ല. സെറ്റിംഗ്സിൽ നിന്ന് എല്ലാം ഡൗൺലോഡ് ചെയ്യാം അല്ലെങ്കിൽ അക്കൗണ്ട് പൂർണമായി ഇല്ലാതാക്കാം.',
  'Engellenen kullanıcılar': 'ബ്ലോക്ക് ചെയ്ത ഉപയോക്താക്കൾ',
  'Engellediğin kişileri gör, engeli kaldır':
      'ബ്ലോക്ക് ചെയ്തവരെ കാണൂ, ബ്ലോക്ക് നീക്കൂ',
  'Engellediğin kimse yok': 'ആരെയും ബ്ലോക്ക് ചെയ്തിട്ടില്ല',
  'Bir kullanıcıyı profilindeki üç nokta menüsünden engelleyebilirsin.':
      'ഒരു ഉപയോക്താവിനെ അവരുടെ പ്രൊഫൈലിലെ മൂന്ന് കുത്തുകളുള്ള മെനുവിൽ നിന്ന് ബ്ലോക്ക് ചെയ്യാം.',
  '@{} engellensin mi?': '@{} എന്നയാളെ ബ്ലോക്ക് ചെയ്യണോ?',
  'Birbirinizin gönderilerini, yorumlarını ve profilini göremezsiniz; mesaj ve arama da gidemez. Varsa takip bağınız kopar ve engeli kaldırsan bile geri gelmez.':
      'നിങ്ങൾക്ക് പരസ്പരം പോസ്റ്റുകളും കമന്റുകളും പ്രൊഫൈലും കാണാനാവില്ല; സന്ദേശങ്ങളും കോളുകളും എത്തുകയുമില്ല. ഇടയിൽ ഫോളോ ഉണ്ടെങ്കിൽ അത് വിച്ഛേദിക്കപ്പെടും, ബ്ലോക്ക് നീക്കിയാലും തിരികെ വരില്ല.',
  'Bu kullanıcıyı engelledin': 'ഈ ഉപയോക്താവിനെ ബ്ലോക്ക് ചെയ്തിരിക്കുന്നു',
  'Gönderilerini, yorumlarını ve mesajlarını görmüyorsun; o da seninkileri göremiyor.':
      'ആ വ്യക്തിയുടെ പോസ്റ്റുകളും കമന്റുകളും സന്ദേശങ്ങളും നിങ്ങൾ കാണുന്നില്ല; ആ വ്യക്തിക്കും നിങ്ങളുടേത് കാണാനാവില്ല.',
  '{} yeni bir yapımda: {}': '{} പുതിയൊരു സൃഷ്ടിയിൽ: {}',
  'Favori kişinden yeni yapım': 'പ്രിയപ്പെട്ട വ്യക്തിയുടെ പുതിയ സൃഷ്ടി',
  '{} için bildirimler': '{} എന്നയാൾക്കുള്ള അറിയിപ്പുകൾ',
  'Tüm bildirimler': 'എല്ലാ അറിയിപ്പുകളും',
  'Uygulamada ve telefonda': 'ആപ്പിലും ഫോണിലും',
  'Yalnız uygulama içi': 'ആപ്പിൽ മാത്രം',
  'Telefon bildirimi gönderilmez': 'ഫോൺ അറിയിപ്പ് അയയ്ക്കില്ല',
  'Kapalı': 'ഓഫ്',
  'Bu kişi için bildirim yok': 'ഈ വ്യക്തിക്ക് അറിയിപ്പില്ല',
  'Favori kişilerin yeni yapımları': 'പ്രിയപ്പെട്ട വ്യക്തികളുടെ പുതിയ സൃഷ്ടികൾ',
  'Kapalıyken kimse seni sesli arayamaz; arayan "devre dışı" uyarısı görür':
      'ഓഫ് ആയിരിക്കുമ്പോൾ ആർക്കും നിങ്ങളെ വോയ്‌സ് കോൾ ചെയ്യാനാവില്ല; വിളിക്കുന്നയാൾ "പ്രവർത്തനരഹിതം" എന്ന അറിയിപ്പ് കാണും',
  'Kapalıyken kimse seni görüntülü arayamaz; arayan "devre dışı" uyarısı görür':
      'ഓഫ് ആയിരിക്കുമ്പോൾ ആർക്കും നിങ്ങളെ വീഡിയോ കോൾ ചെയ്യാനാവില്ല; വിളിക്കുന്നയാൾ "പ്രവർത്തനരഹിതം" എന്ന അറിയിപ്പ് കാണും',

  // --- Hareketlerim / İstatistiklerim / gizlilik ---
  'Hareketlerim': 'എന്റെ പ്രവർത്തനം',
  'Beğenilerin, yorumların, izlemelerin tek akışta':
      'നിന്റെ ലൈക്കുകൾ, കമന്റുകൾ, കണ്ടവ ഒരിടത്ത്',
  'Henüz hareketin yok': 'ഇതുവരെ പ്രവർത്തനമില്ല',
  'Beğendiğin, yorumladığın, izlediğin her şey burada birikir.':
      'നീ ലൈക്ക് ചെയ്യുന്നതും കമന്റ് ചെയ്യുന്നതും കാണുന്നതും ഇവിടെ കൂടും.',
  'Bu süzgeçte hareket yok': 'ഈ ഫിൽട്ടറിൽ പ്രവർത്തനമില്ല',
  'Başka bir tür seç ya da "Hepsi"ne dön.':
      'മറ്റൊരു തരം തിരഞ്ഞെടുക്കുക അല്ലെങ്കിൽ "എല്ലാം" എന്നതിലേക്ക് മടങ്ങുക.',
  'Hepsi': 'എല്ലാം',
  'Puan': 'റേറ്റിംഗ്',
  'Tepki': 'പ്രതികരണം',
  'İzleme': 'കണ്ടത്',
  'Durum': 'നില',
  'Liste': 'ലിസ്റ്റ്',
  'Yorum yaptın': 'കമന്റ് ചെയ്തു',
  'Yorumu beğendin': 'ഒരു കമന്റ് ലൈക്ക് ചെയ്തു',
  '{} puan verdin': '{} റേറ്റിംഗ് നൽകി',
  'Tepki verdin': 'പ്രതികരിച്ചു',
  'Listene ekledin': 'ലിസ്റ്റിൽ ചേർത്തു',
  'Takip etmeye başladın': 'ഫോളോ ചെയ്യാൻ തുടങ്ങി',
  '"İzleyeceğim" işaretledin': '"കാണാൻ പോകുന്നു" എന്ന് അടയാളപ്പെടുത്തി',
  '"İzliyorum" işaretledin': '"കണ്ടുകൊണ്ടിരിക്കുന്നു" എന്ന് അടയാളപ്പെടുത്തി',
  '"Bitirdim" işaretledin': '"കണ്ടു തീർത്തു" എന്ന് അടയാളപ്പെടുത്തി',
  '"Bıraktım" işaretledin': '"നിർത്തി" എന്ന് അടയാളപ്പെടുത്തി',
  'Silinmiş içerik': 'ഇല്ലാതാക്കിയ ഉള്ളടക്കം',
  'şimdi': 'ഇപ്പോൾ',
  '{} g': '{} ദി',
  '{} y': '{} വ',
  'İstatistiklerim': 'എന്റെ സ്ഥിതിവിവരം',
  'Gönderilerinin görüntülenmesi ve beğenisi':
      'നിന്റെ പോസ്റ്റുകളുടെ കാഴ്ചകളും ലൈക്കുകളും',
  'Henüz gönderin yok': 'നിനക്ക് ഇതുവരെ പോസ്റ്റുകളില്ല',
  'Bir dizi ya da filme yorum yazdığında görüntülenme ve beğeni sayıların burada birikmeye başlar.':
      'ഒരു സീരീസിനോ സിനിമയ്ക്കോ കമന്റ് എഴുതിയാൽ, നിന്റെ കാഴ്ചകളുടെയും ലൈക്കുകളുടെയും എണ്ണം ഇവിടെ കൂടിത്തുടങ്ങും.',
  'Tüm zamanlar': 'എക്കാലവും',
  'Son {} gün': 'കഴിഞ്ഞ {} ദിവസം',
  'Görüntülenme geçmişi henüz birikmeye başlamadı; ilk gün verisi yarın görünür.':
      'കാഴ്ചകളുടെ ചരിത്രം ഇനിയും കൂടിത്തുടങ്ങിയിട്ടില്ല; ആദ്യ ദിവസത്തെ വിവരം നാളെ കാണാം.',
  'Görüntülenme geçmişi {} tarihinden beri birikiyor ({} günlük veri var), bu yüzden {} günlük sayı henüz eksik.':
      'കാഴ്ചകളുടെ ചരിത്രം {} മുതൽ കൂടിവരുന്നു ({} ദിവസത്തെ വിവരമുണ്ട്), അതിനാൽ {} ദിവസത്തെ എണ്ണം ഇനിയും അപൂർണമാണ്.',
  'Beğeni geçmişi {} tarihinden beri kayıtlı.':
      'ലൈക്കുകളുടെ ചരിത്രം {} മുതൽ രേഖപ്പെടുത്തുന്നു.',
  'Bu dönemde gösterilecek gönderi yok.':
      'ഈ കാലയളവിൽ കാണിക്കാൻ പോസ്റ്റുകളില്ല.',
  'eksik veri': 'അപൂർണ വിവരം',
  'Profilinde izlediğin dizi ve filmler, izleme sayaçların, ekran süren ve uyum kartın başkalarına görünmez':
      'നിന്റെ പ്രൊഫൈലിലെ കണ്ട സീരീസുകളും സിനിമകളും, കാഴ്ചാ കൗണ്ടറുകൾ, സ്ക്രീൻ സമയം, പൊരുത്ത കാർഡ് എന്നിവ മറ്റുള്ളവർക്ക് കാണില്ല',
  'Takipçi listemi gizle': 'എന്റെ ഫോളോവർ ലിസ്റ്റ് മറയ്ക്കുക',
  'Seni kimlerin takip ettiğini başkaları göremez; takipçi sayın görünmeye devam eder':
      'നിന്നെ ആരൊക്കെ ഫോളോ ചെയ്യുന്നു എന്ന് മറ്റുള്ളവർക്ക് കാണാനാകില്ല; നിന്റെ ഫോളോവർ എണ്ണം കാണാം',
  'Takip ettiklerimi gizle': 'ഞാൻ ഫോളോ ചെയ്യുന്നവരെ മറയ്ക്കുക',
  'Kimleri takip ettiğini başkaları göremez; takip sayın görünmeye devam eder':
      'നീ ആരെയൊക്കെ ഫോളോ ചെയ്യുന്നു എന്ന് മറ്റുള്ളവർക്ക് കാണാനാകില്ല; നിന്റെ ഫോളോയിംഗ് എണ്ണം കാണാം',
  'Bu kullanıcı takipçilerini gizli tutmayı tercih ediyor.':
      'ഈ ഉപയോക്താവ് ഫോളോവർമാരെ സ്വകാര്യമായി സൂക്ഷിക്കാൻ ഇഷ്ടപ്പെടുന്നു.',
  'Bu kullanıcı takip ettiklerini gizli tutmayı tercih ediyor.':
      'ഈ ഉപയോക്താവ് താൻ ഫോളോ ചെയ്യുന്നവരെ സ്വകാര്യമായി സൂക്ഷിക്കാൻ ഇഷ്ടപ്പെടുന്നു.',

  // --- md.23 gönderi istatistikleri ---
  'Gönderi istatistikleri': 'പോസ്റ്റ് സ്ഥിതിവിവരക്കണക്കുകൾ',
  'Yalnız kendi gönderilerinin istatistiklerini görebilirsin.':
      'നിങ്ങളുടെ സ്വന്തം പോസ്റ്റുകളുടെ സ്ഥിതിവിവരക്കണക്കുകൾ മാത്രമേ കാണാനാകൂ.',
  'Erişim': 'എത്തിച്ചേരൽ',
  'Görüntüleyen': 'കണ്ടവർ',
  'Kaç farklı kişi gördü (son {} gün)':
      'എത്ര വ്യത്യസ്ത ആളുകൾ കണ്ടു (കഴിഞ്ഞ {} ദിവസം)',
  'Paylaşım': 'പങ്കിടലുകൾ',
  'Bu gönderiden sonra': 'ഈ പോസ്റ്റിന് ശേഷം',
  'Profil ziyareti': 'പ്രൊഫൈൽ സന്ദർശനങ്ങൾ',
  'Yeni takip': 'പുതിയ ഫോളോകൾ',
  'İçeriğe tıklama': 'ഉള്ളടക്ക ടാപ്പുകൾ',
  'Spoiler perdesini açan': 'സ്പോയിലർ തുറന്നവർ',
  'Paylaşım, profil ziyareti, takip, içeriğe tıklama, kaynak kırılımı ve spoiler ölçüleri {} tarihinden beri birikiyor; daha eskisi ölçülmedi.':
      'പങ്കിടലുകൾ, പ്രൊഫൈൽ സന്ദർശനങ്ങൾ, ഫോളോകൾ, ഉള്ളടക്ക ടാപ്പുകൾ, ഉറവിട വിഭജനം, സ്പോയിലർ അളവുകൾ എന്നിവ {} മുതൽ ശേഖരിക്കപ്പെടുന്നു; അതിനു മുൻപുള്ളത് അളന്നിട്ടില്ല.',
  'Zamana yayılmış görüntülenme': 'കാലക്രമേണയുള്ള കാഴ്ചകൾ',
  'Görüntülenme nereden geldi': 'കാഴ്ചകൾ എവിടെ നിന്നു വന്നു',
  'Kimler gördü': 'ആരു കണ്ടു',
  'Günlük veri henüz birikmeye başlamadı.':
      'ദൈനംദിന ഡാറ്റ ഇതുവരെ ശേഖരിക്കപ്പെടാൻ തുടങ്ങിയിട്ടില്ല.',
  'Grafik için en az iki günlük veri gerekiyor. Veri {} tarihinden beri birikiyor.':
      'ഗ്രാഫിന് കുറഞ്ഞത് രണ്ട് ദിവസത്തെ ഡാറ്റ വേണം. ഡാറ്റ {} മുതൽ ശേഖരിക്കപ്പെടുന്നു.',
  'En çok görüntülenme paylaşımdan sonraki {}. gün geldi: {}':
      'ഏറ്റവും കൂടുതൽ കാഴ്ചകൾ പോസ്റ്റ് ചെയ്ത് {}-ാം ദിവസം വന്നു: {}',
  'Günlük görüntülenme {} tarihinden beri birikiyor; öncesi ölçülmedi.':
      'ദൈനംദിന കാഴ്ചകൾ {} മുതൽ ശേഖരിക്കപ്പെടുന്നു; അതിനു മുൻപുള്ളത് അളന്നിട്ടില്ല.',
  'Kaynak kırılımı yeni ölçülmeye başladı; bu gönderi henüz etiketli bir görüntülenme almadı.':
      'ഉറവിട വിഭജനം അളക്കാൻ ഇപ്പോൾ മാത്രമാണ് തുടങ്ങിയത്; ഈ പോസ്റ്റിന് ഇതുവരെ ടാഗ് ചെയ്ത കാഴ്ച ലഭിച്ചിട്ടില്ല.',
  'Takipçi/keşif kırılımı yeni ölçülmeye başladı; henüz veri yok.':
      'ഫോളോവർ/കണ്ടെത്തൽ വിഭജനം അളക്കാൻ ഇപ്പോൾ മാത്രമാണ് തുടങ്ങിയത്; ഇതുവരെ ഡാറ്റ ഇല്ല.',
  'Takip edenler': 'ഫോളോവർമാർ',
  'Keşiften gelenler': 'കണ്ടെത്തലിൽ നിന്ന്',
  'Reels': 'Reels',
  'Dizi/film sayfası': 'സീരീസ്/സിനിമ പേജ്',
  'Paylaşılan bağlantı': 'പങ്കിട്ട ലിങ്ക്',
  'yeni ölçülüyor': 'പുതുതായി അളക്കുന്നു',
  'Kendi ortalamanla aynı düzeyde': 'നിങ്ങളുടെ ശരാശരിക്ക് ഒപ്പം',
  'Kendi ortalamanın %{} üstünde': 'നിങ്ങളുടെ ശരാശരിയെക്കാൾ {}% കൂടുതൽ',
  'Kendi ortalamanın %{} altında': 'നിങ്ങളുടെ ശരാശരിയെക്കാൾ {}% കുറവ്',
  'Etkileşim oranı': 'ഇടപഴകൽ നിരക്ക്',
  '(beğeni + yorum) ÷ görüntülenme': '(ലൈക്കുകൾ + കമന്റുകൾ) ÷ കാഴ്ചകൾ',
  'Toplam görüntülenme': 'ആകെ കാഴ്ചകൾ',
  '{} ile {} arasında toplam {} görüntülenme': '{} മുതൽ {} വരെ ആകെ {} കാഴ്ചകൾ',
  'İstatistikleri gör': 'സ്ഥിതിവിവരക്കണക്ക് കാണുക',

  // --- md.23 gizlilik politikası ---
  'Gönderi sahibine gösterilen istatistikler için, gönderinin kaç kez ve hangi yüzeyden (akış, profil, tam ekran akış, dizi/film sayfası, paylaşılan bağlantı) görüntülendiği, görüntüleyenin o an gönderi sahibini takip edip etmediği, gönderiden profile/içeriğe geçiş, gönderi üzerinden kurulan takip, paylaşım ve spoiler perdesi açılması toplu sayaçlar olarak tutulur. Bu sayaçlarda kullanıcı kimliği, IP adresi veya zaman damgası bulunmaz; kimin ne yaptığı sorgulanamaz.':
      'പോസ്റ്റിന്റെ ഉടമയ്ക്ക് കാണിക്കുന്ന സ്ഥിതിവിവരക്കണക്കുകൾക്കായി സമാഹൃത കൗണ്ടറുകളായി സൂക്ഷിക്കുന്നു: പോസ്റ്റ് എത്ര തവണ, ഏത് പ്രതലത്തിൽ നിന്ന് (ഫീഡ്, പ്രൊഫൈൽ, പൂർണ്ണസ്ക്രീൻ ഫീഡ്, സീരീസ്/സിനിമ പേജ്, പങ്കിട്ട ലിങ്ക്) കണ്ടു, കണ്ടയാൾ അപ്പോൾ പോസ്റ്റിന്റെ ഉടമയെ ഫോളോ ചെയ്തിരുന്നോ, പോസ്റ്റിൽ നിന്ന് പ്രൊഫൈലിലേക്കോ ഉള്ളടക്കത്തിലേക്കോ പോകൽ, പോസ്റ്റ് വഴി ഉണ്ടായ ഫോളോ, പങ്കിടൽ, സ്പോയിലർ മറ തുറക്കൽ. ഈ കൗണ്ടറുകളിൽ ഉപയോക്തൃ ഐഡന്റിറ്റിയോ IP വിലാസമോ ടൈംസ്റ്റാമ്പോ ഇല്ല; ആരു എന്തു ചെയ്തു എന്ന് ചോദിക്കാനാവില്ല.',
  'Bir gönderiyi kaç farklı kişinin gördüğünü sayabilmek için, görüntüleyen başına geri çevrilemez bir anahtarlı özet (kullanıcı kimliğinden veya IP adresinden türetilen kriptografik kısaltma) 90 gün saklanır. Gönderi sahibine yalnız sayı gösterilir; görüntüleyenlerin kimliği hiçbir koşulda paylaşılmaz.':
      'ഒരു പോസ്റ്റ് എത്ര വ്യത്യസ്ത ആളുകൾ കണ്ടു എന്ന് എണ്ണാൻ കഴിയാൻ, ഓരോ കാഴ്ചക്കാരനും ഒരു തിരിച്ചെടുക്കാനാവാത്ത കീ അധിഷ്ഠിത സംഗ്രഹം (ഉപയോക്തൃ ഐഡന്റിറ്റിയിൽ നിന്നോ IP വിലാസത്തിൽ നിന്നോ ഉരുത്തിരിഞ്ഞ ക്രിപ്റ്റോഗ്രാഫിക് ചുരുക്കം) 90 ദിവസം സൂക്ഷിക്കുന്നു. പോസ്റ്റിന്റെ ഉടമയ്ക്ക് എണ്ണം മാത്രമേ കാണിക്കൂ; കാഴ്ചക്കാരുടെ ഐഡന്റിറ്റി ഒരു സാഹചര്യത്തിലും പങ്കിടില്ല.',

  // --- İzleyeceğim tekilliği (izleme silme onayı) ---
  'İzleyeceklerine taşınsın mı?': '“കാണാൻ പോകുന്നു”-ലേക്ക് മാറ്റണോ?',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu dizideki {} izleme işaretin silinecek.':
      'ഒരു ടൈറ്റിൽ ഒന്നുകിൽ കാണാനുള്ളതാണ്, അല്ലെങ്കിൽ കണ്ടതാണ്. തുടർന്നാൽ ഈ സീരീസിലെ നിന്റെ {} കണ്ട അടയാളങ്ങൾ മായ്ക്കപ്പെടും.',
  'Bir içerik ya izlenecektir ya izlenmiştir. Devam edersen bu filmdeki "izledim" işaretin kaldırılacak.':
      'ഒരു ടൈറ്റിൽ ഒന്നുകിൽ കാണാനുള്ളതാണ്, അല്ലെങ്കിൽ കണ്ടതാണ്. തുടർന്നാൽ ഈ സിനിമയിലെ നിന്റെ “കണ്ടു” അടയാളം നീങ്ങും.',
  'Sil ve taşı': 'മായ്ച്ച് മാറ്റുക',
  'Yapım Ekibi': 'അണിയറ പ്രവർത്തകർ',
  'Yaratıcı': 'സൃഷ്ടി',
  'Yönetmen': 'സംവിധാനം',
  'Senaryo': 'തിരക്കഥ',
  'Yapımcı': 'നിർമ്മാണം',
  'Yapım Firmaları': 'നിർമ്മാണ കമ്പനികൾ',
  'Yapım Firması': 'നിർമ്മാണ കമ്പനി',
  'Firma bulunamadı': 'കമ്പനി കണ്ടെത്തിയില്ല',
  'Bu firmanın bu türde listelenecek yapımı yok.':
      'ഈ കമ്പനിക്ക് ഈ തരത്തിലുള്ള സൃഷ്ടികളൊന്നുമില്ല.',
  'Doğum günün kutlu olsun!': 'ജന്മദിനാശംസകൾ!',
  'İyi ki doğdun, iyi ki buradasın.':
      'നിങ്ങൾ ജനിച്ചത് നന്നായി, ഇവിടെ ഉള്ളതും നന്നായി.',
  'Bugün {} yaşına girdin': 'ഇന്ന് നിങ്ങൾക്ക് {} വയസ്സ് തികഞ്ഞു',
  'Teşekkürler': 'നന്ദി',
  'İki Adımlı Doğrulama': 'രണ്ട് ഘട്ട പരിശോധന',
  'Girişte e-postana kod gönderilir':
      'ലോഗിൻ ചെയ്യുമ്പോൾ ഇമെയിലിലേക്ക് കോഡ് അയയ്ക്കും',
  'Kod {} adresine gönderildi': 'കോഡ് {} എന്ന വിലാസത്തിലേക്ക് അയച്ചു',
  '6 haneli kod': '6 അക്ക കോഡ്',
  'Doğrula': 'പരിശോധിക്കൂ',
  'Yeniden gönder': 'വീണ്ടും അയയ്ക്കൂ',
  'Vazgeç': 'റദ്ദാക്കൂ',
  'Yeni kod gönderildi': 'പുതിയ കോഡ് അയച്ചു',
  'Google ile girişte kod sorulmaz; Google kendi doğrulamasını yapar.':
      'Google ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുമ്പോൾ കോഡ് ചോദിക്കില്ല; പരിശോധന Google സ്വയം നടത്തും.',
  'Kapatmak için de kod gerekir.': 'ഓഫ് ചെയ്യാനും കോഡ് വേണം.',
  'E-postana erişemezsen hesabına giremezsin.':
      'ഇമെയിൽ ലഭ്യമല്ലെങ്കിൽ അക്കൗണ്ടിൽ ലോഗിൻ ചെയ്യാൻ കഴിയില്ല.',
  'İki adımlı doğrulama açıldı': 'രണ്ട് ഘട്ട പരിശോധന ഓണാക്കി',
  'İki adımlı doğrulama kapatıldı': 'രണ്ട് ഘട്ട പരിശോധന ഓഫാക്കി',

  // --- md.24 video elde tutma eğrisi ---
  'Videonun ne kadarı izlendi': 'വീഡിയോ എത്ര കണ്ടു',
  'Videoyu başlatanlar': 'വീഡിയോ തുടങ്ങിയവർ',
  'videonun %{} noktasına ulaştı': 'വീഡിയോയുടെ {}% വരെ എത്തി',
  'İzleyenlerin yarısı videonun en az %{} kadarını gördü.':
      'കണ്ടവരിൽ പകുതി പേർ വീഡിയോയുടെ കുറഞ്ഞത് {}% കണ്ടു.',
  'Sonuna kadar izleyen: %{}': 'അവസാനം വരെ കണ്ടവർ: {}%',
  'Eğri için en az {} izlenme gerekiyor; şu an {} izlenme var.':
      'വക്രരേഖയ്ക്ക് കുറഞ്ഞത് {} കാഴ്ചകൾ വേണം; ഇപ്പോൾ {} കാഴ്ചകളുണ്ട്.',
  'Eğri {} izlenmeden çıkarıldı ve seçili zaman aralığından etkilenmez.':
      'വക്രരേഖ {} കാഴ്ചകളിൽ നിന്നുള്ളതാണ്; തിരഞ്ഞെടുത്ത കാലയളവ് ഇതിനെ മാറ്റില്ല.',
  'İzlenme süresi {} tarihinden beri ölçülüyor; daha eski görüntülenmeler bu sayıya girmez.':
      'കാഴ്ചാസമയം {} മുതൽ അളക്കുന്നു; അതിനു മുൻപുള്ള കാഴ്ചകൾ ഈ എണ്ണത്തിൽ വരില്ല.',
  '{} izlenme. Videonun yarısına ulaşan %{}, sonuna ulaşan %{}.':
      '{} കാഴ്ചകൾ. വീഡിയോയുടെ പകുതി വരെ {}%, അവസാനം വരെ {}% എത്തി.',
  // Yüzde işaretinin YERİ dile göre değişir; sayı tek başına
  // basılamaz (bkz. gonderi_istatistik.dart). Kalıp bu dosyanın
  // kendi mevcut yüzde çevirilerinden çıkarıldı.
  '%{}': '{}%',
  'Seviye {}': 'ലെവൽ {}',
  'Sonraki seviyeye {} puan kaldı': 'അടുത്ത ലെവലിലേക്ക് {} പോയിന്റ് ബാക്കി',
  'Gönderilerin': 'നിന്റെ പോസ്റ്റുകൾ',
  '{} gönderi': '{} പോസ്റ്റ്',
  '{} gönderi · {} görüntülenme': '{} പോസ്റ്റ് · {} കാഴ്ച',
  'önceki {} güne göre': 'മുൻ {} ദിവസവുമായി താരതമ്യം',
  'önceki {} güne göre %{} arttı': 'മുൻ {} ദിവസത്തെക്കാൾ {}% കൂടി',
  'önceki {} güne göre %{} azaldı': 'മുൻ {} ദിവസത്തെക്കാൾ {}% കുറഞ്ഞു',
  'önceki {} güne göre değişmedi': 'മുൻ {} ദിവസത്തിൽ നിന്ന് മാറ്റമില്ല',
  'Günlük görüntülenme: en düşük {}, en yüksek {}':
      'ദിവസേനയുള്ള കാഴ്ചകൾ: കുറഞ്ഞത് {}, കൂടിയത് {}',
  'Etkileşim oranı henüz ölçülemedi': 'ഇടപഴകൽ നിരക്ക് ഇതുവരെ അളക്കാനായില്ല',
  'Oranlar': 'നിരക്കുകൾ',
  'Beğenme oranı': 'ലൈക്ക് നിരക്ക്',
  'Yorum oranı': 'കമന്റ് നിരക്ക്',
  'Paylaşma oranı': 'പങ്കിടൽ നിരക്ക്',
  'İçeriğe gitme oranı': 'ഉള്ളടക്ക ടാപ്പ് നിരക്ക്',
  'Profile gitme oranı': 'പ്രൊഫൈൽ സന്ദർശന നിരക്ക്',
  'Ziyaretten takibe dönüşüm': 'സന്ദർശനത്തിൽ നിന്ന് ഫോളോ',
  'beğeni ÷ görüntülenme': 'ലൈക്കുകൾ ÷ കാഴ്ചകൾ',
  'yorum ÷ görüntülenme': 'കമന്റുകൾ ÷ കാഴ്ചകൾ',
  'paylaşım ÷ görüntülenme': 'പങ്കിടലുകൾ ÷ കാഴ്ചകൾ',
  'içeriğe tıklama ÷ görüntülenme': 'ഉള്ളടക്ക ടാപ്പുകൾ ÷ കാഴ്ചകൾ',
  'profil ziyareti ÷ görüntülenme': 'പ്രൊഫൈൽ സന്ദർശനങ്ങൾ ÷ കാഴ്ചകൾ',
  'yeni takip ÷ profil ziyareti': 'പുതിയ ഫോളോകൾ ÷ പ്രൊഫൈൽ സന്ദർശനങ്ങൾ',
  'Oran için en az {} görüntülenme gerekiyor; şu an {} var.':
      'നിരക്കിന് കുറഞ്ഞത് {} കാഴ്ച വേണം; ഇപ്പോൾ {} ഉണ്ട്.',
  'Oranlar gönderinin ömür boyu sayılarından çıkar; aşağıdaki gün seçimi bunları değiştirmez.':
      'നിരക്കുകൾ പോസ്റ്റിന്റെ എക്കാലത്തെയും കണക്കുകളിൽ നിന്നാണ്; താഴെയുള്ള ദിവസ തിരഞ്ഞെടുപ്പ് അവയെ മാറ്റില്ല.',
  'Bu sayılar gönderinin ömür boyu toplamıdır (kendi notu olan kutular hariç); aşağıdaki gün seçimi yalnız grafiği değiştirir.':
      'ഈ സംഖ്യകൾ പോസ്റ്റിന്റെ എക്കാലത്തെയും ആകെത്തുകയാണ് (സ്വന്തം കുറിപ്പുള്ള ബോക്സുകൾ ഒഴികെ); താഴെയുള്ള ദിവസ തിരഞ്ഞെടുപ്പ് ഗ്രാഫ് മാത്രം മാറ്റുന്നു.',
  'Ortalama izlenme: videonun %{} kadarı': 'ശരാശരി കാഴ്ച: വീഡിയോയുടെ {}%',
  'Elde tutma eğrisinin 20 kovasının ortalaması.':
      'നിലനിർത്തൽ വക്രത്തിലെ 20 ഭാഗങ്ങളുടെ ശരാശരി.',
  'Dizi, film, kişi veya şirket ara...':
      'സീരീസ്, സിനിമ, വ്യക്തി അല്ലെങ്കിൽ കമ്പനി തിരയൂ...',
  'Şirketler': 'കമ്പനികൾ',
  'Senarist': 'തിരക്കഥാകൃത്ത്',
  'Bölüm puanları': 'എപ്പിസോഡ് റേറ്റിംഗ്',
  'S{}': 'S{}',
  'E{}': 'E{}',
  'Bölüm puanları yüklenemedi': 'എപ്പിസോഡ് റേറ്റിംഗ് ലോഡ് ചെയ്യാനായില്ല',
  'Giriş gerekli': 'സൈൻ ഇൻ ആവശ്യമാണ്',
  'Geçersiz oturum': 'അസാധുവായ സെഷൻ',
  'Oturum sonlandı, tekrar giriş yap': 'സെഷൻ അവസാനിച്ചു, വീണ്ടും സൈൻ ഇൻ ചെയ്യൂ',
  'Çok fazla istek; biraz sonra tekrar dene':
      'അമിതമായ അഭ്യർത്ഥനകൾ; അല്പസമയം കഴിഞ്ഞ് വീണ്ടും ശ്രമിക്കൂ',
  'Sunucuda geçici olarak yer yok, birazdan tekrar dene':
      'സെർവറിൽ ഇപ്പോൾ സ്ഥലമില്ല, അൽപ്പം കഴിഞ്ഞ് വീണ്ടും ശ്രമിക്കുക',
  'Devam eden yapımlar ({})': 'നടന്നുകൊണ്ടിരിക്കുന്ന നിർമ്മാണങ്ങൾ ({})',
  'Diziler ({})': 'സീരീസ് ({})',
  'Filmler ({})': 'സിനിമകൾ ({})',
  'Tüm yapımlar': 'എല്ലാ നിർമ്മാണങ്ങളും',
  'Medya alanın doldu; yer açmak için eski yüklemelerini sil':
      'നിങ്ങളുടെ മീഡിയ സംഭരണം നിറഞ്ഞു; സ്ഥലം ലഭിക്കാൻ പഴയ അപ്‌ലോഡുകൾ മായ്ക്കുക',
  'E-posta/kullanıcı adı veya şifre hatalı':
      'ഇമെയിൽ/ഉപയോക്തൃനാമം അല്ലെങ്കിൽ പാസ്‌വേഡ് തെറ്റാണ്',
  'Bu e-posta veya kullanıcı adı zaten kayıtlı':
      'ഈ ഇമെയിൽ അല്ലെങ്കിൽ ഉപയോക്തൃനാമം നേരത്തെ എടുത്തതാണ്',
  'Google doğrulaması başarısız': 'Google പരിശോധന പരാജയപ്പെട്ടു',
  'Kod geçersiz veya süresi dolmuş': 'കോഡ് അസാധുവാണ് അല്ലെങ്കിൽ കാലഹരണപ്പെട്ടു',
  'Bu kullanıcıyla mesajlaşamazsın':
      'ഈ ഉപയോക്താവിന് സന്ദേശം അയയ്ക്കാൻ കഴിയില്ല',
  'Kendini takip edemezsin': 'നിന്നെത്തന്നെ ഫോളോ ചെയ്യാൻ കഴിയില്ല',
  'Bu kullanıcıyı takip edemezsin': 'ഈ ഉപയോക്താവിനെ ഫോളോ ചെയ്യാൻ കഴിയില്ല',
  'Kendini engelleyemezsin': 'നിന്നെത്തന്നെ ബ്ലോക്ക് ചെയ്യാൻ കഴിയില്ല',
  'Yorum 1-1000 karakter olmalı': 'അഭിപ്രായം 1–1000 അക്ഷരം ആയിരിക്കണം',
  'Boş mesaj gönderilemez': 'ശൂന്യമായ സന്ദേശം അയയ്ക്കാൻ കഴിയില്ല',
  'Yorum bulunamadı': 'അഭിപ്രായം കണ്ടെത്തിയില്ല',
  'Şifre hatalı': 'പാസ്‌വേഡ് തെറ്റാണ്',
  'Şifre en az 6 karakter olmalı': 'പാസ്‌വേഡ് കുറഞ്ഞത് 6 അക്ഷരം ആയിരിക്കണം',
  'Yalnızca GIF, PNG, JPEG veya WebP yüklenebilir':
      'GIF, PNG, JPEG അല്ലെങ്കിൽ WebP മാത്രം അപ്‌ലോഡ് ചെയ്യാം',
  'Desteklenen türler: GIF, PNG, JPEG, WebP, MP4, WebM, ses':
      'പിന്തുണയുള്ള തരം: GIF, PNG, JPEG, WebP, MP4, WebM, ഓഡിയോ',
  'Geçerli bir ZIP dosyası değil': 'സാധുവായ ZIP ഫയൽ അല്ല',
  'Verilerini e-postayla almak için önce hesabına e-posta bağlamalısın':
      'ഡാറ്റ ഇമെയിലിൽ ലഭിക്കാൻ ആദ്യം ഇമെയിൽ ബന്ധിപ്പിക്കൂ',
  'Bu içerikte izleme kaydın var. "İzleyeceğim" demek için önce izleme işaretlerin silinmeli.':
      'ഇതിൽ കണ്ട രേഖയുണ്ട്. "കാണും" എന്നു പറയാൻ ആദ്യം അടയാളം മാറ്റണം.',
  'Arama şu anda kapalı': 'കോളിംഗ് ഇപ്പോൾ ഓഫാണ്',
  'Misafir hesaplar arama ayarlarını açamaz; hesap oluşturunca kullanabilirsin':
      'അതിഥി അക്കൗണ്ടിന് കോളിംഗ് ഓൺ ചെയ്യാൻ കഴിയില്ല; അക്കൗണ്ട് ഉണ്ടാക്കൂ',
  'Sunucu yeniden başlatılıyor, birazdan tekrar dene':
      'സെർവർ റീസ്റ്റാർട്ട് ചെയ്യുന്നു, അല്പസമയം കഴിഞ്ഞ് ശ്രമിക്കൂ',
  'Puan 1-10 arası olmalı': 'റേറ്റിംഗ് 1 മുതൽ 10 വരെ ആയിരിക്കണം',
  'En fazla 10 medya eklenebilir': 'പരമാവധി 10 മീഡിയ ചേർക്കാം',
  'Bu cihazdan yeni hesap açılamıyor':
      'ഈ ഉപകരണത്തിൽ നിന്ന് പുതിയ അക്കൗണ്ട് തുറക്കാനാവില്ല',
  'Geçerli e-posta, kullanıcı adı ve en az 6 karakter şifre gerekli':
      'സാധുവായ ഇമെയിൽ, ഉപയോക്തൃനാമം, കുറഞ്ഞത് 6 അക്ഷരമുള്ള പാസ്‌വേഡ് വേണം',
  'Geçerli e-posta ve en az 6 karakter şifre gerekli':
      'സാധുവായ ഇമെയിലും കുറഞ്ഞത് 6 അക്ഷരമുള്ള പാസ്‌വേഡും വേണം',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir (başta/sonda nokta-tire olamaz)':
      'ഉപയോക്തൃനാമം 3–20; ചെറിയക്ഷരം, അക്കം, ഡോട്ട്, ഹൈഫൻ, അണ്ടർസ്കോർ (അറ്റത്ത് വേണ്ട)',
  'Bu hesap zaten bağlı': 'ഈ അക്കൗണ്ട് ഇതിനകം ബന്ധിപ്പിച്ചിരിക്കുന്നു',
  'Hesap oluşturulamadı': 'അക്കൗണ്ട് ഉണ്ടാക്കാനായില്ല',
  'Misafir hesabı oluşturulamadı': 'അതിഥി അക്കൗണ്ട് ഉണ്ടാക്കാനായില്ല',
  'Hesap bulunamadı': 'അക്കൗണ്ട് കണ്ടെത്തിയില്ല',
  'Bu hesapta e-posta yok': 'ഈ അക്കൗണ്ടിന് ഇമെയിൽ ഇല്ല',
  'İki adımlı doğrulama zaten bu durumda':
      'രണ്ട്-ഘട്ട പരിശോധന ഇതിനകം ഈ അവസ്ഥയിലാണ്',
  'Kod yanlış': 'കോഡ് തെറ്റാണ്',
  'Kodun süresi doldu': 'കോഡ് കാലഹരണപ്പെട്ടു',
  'Kullanıcının e-postası yok (misafir hesap)':
      'ഈ ഉപയോക്താവിന് ഇമെയിൽ ഇല്ല (അതിഥി അക്കൗണ്ട്)',
  'Bio en fazla 300 karakter olabilir': 'ബയോ പരമാവധി 300 അക്ഷരം',
  'Geçersiz ülke': 'അസാധുവായ രാജ്യം',
  'Geçersiz sosyal bağlantı': 'അസാധുവായ സോഷ്യൽ ലിങ്ക്',
  'Geçersiz doğum tarihi': 'അസാധുവായ ജനനത്തീയതി',
  'Liste adı gerekli': 'ലിസ്റ്റ് പേര് ആവശ്യമാണ്',
  'Ad en fazla 60, açıklama 300 karakter olabilir':
      'പേര് പരമാവധി 60, വിവരണം 300 അക്ഷരം',
  'Liste bulunamadı': 'ലിസ്റ്റ് കണ്ടെത്തിയില്ല',
  'Değiştirilecek tercih yok': 'അപ്‌ഡേറ്റ് ചെയ്യാൻ ഒന്നുമില്ല',
  'İnceleme en fazla 2000 karakter olabilir': 'അവലോകനം പരമാവധി 2000 അക്ഷരം',
  'Önce içeriği "bitirdim" olarak işaretle':
      'ആദ്യം ഇത് കണ്ടുതീർത്തതായി അടയാളപ്പെടുത്തൂ',
  'Önce kişiyi favorile': 'ആദ്യം ഈ വ്യക്തിയെ പ്രിയപ്പെട്ടതാക്കൂ',
  'Bölüm yorumu için sezon ve bolum birlikte gerekli':
      'എപ്പിസോഡ് അഭിപ്രായത്തിന് സീസണും എപ്പിസോഡും വേണം',
  'Yanıtlanan yorum bulunamadı': 'മറുപടി നൽകിയ അഭിപ്രായം കണ്ടെത്തിയില്ല',
  'Geri bildirim 3-2000 karakter olmalı': 'ഫീഡ്ബാക്ക് 3–2000 അക്ഷരമായിരിക്കണം',
  'Başlık ve metin gerekli (en az 2 karakter)':
      'തലക്കെട്ടും വാചകവും ആവശ്യം (കുറഞ്ഞത് 2 അക്ഷരം)',
  'Kendine mesaj gönderemezsin': 'നിനക്ക് നീ തന്നെ സന്ദേശം അയയ്ക്കാനാവില്ല',
  'Mesaj en fazla 2000 karakter olabilir': 'സന്ദേശം പരമാവധി 2000 അക്ഷരം',
  'Mesaj 1-2000 karakter olmalı': 'സന്ദേശം 1–2000 അക്ഷരമായിരിക്കണം',
  'Mesaj bulunamadı': 'സന്ദേശം കണ്ടെത്തിയില്ല',
  'Mesaj bulunamadı veya düzenlenemez':
      'സന്ദേശം കണ്ടെത്തിയില്ല അല്ലെങ്കിൽ തിരുത്താനാവില്ല',
  'Yalnız sana gelen mesajı şikayet edebilirsin':
      'നിനക്ക് വന്ന സന്ദേശം മാത്രമേ റിപ്പോർട്ട് ചെയ്യാവൂ',
  'Sebep gerekli': 'കാരണം ആവശ്യമാണ്',
  'İtiraz edilecek aktif bir ceza yok': 'അപ്പീൽ ചെയ്യാൻ സജീവ ശിക്ഷയില്ല',
  'Zaten incelenmeyi bekleyen bir itirazın var':
      'ഇതിനകം അവലോകനത്തിനായി കാത്തിരിക്കുന്ന അപ്പീൽ ഉണ്ട്',
  'Bu ceza için itirazın zaten incelendi':
      'ഈ ശിക്ഷയുടെ അപ്പീൽ ഇതിനകം അവലോകനം ചെയ്തു',
  'Medya bağlantısının süresi dolmuş': 'മീഡിയ ലിങ്ക് കാലഹരണപ്പെട്ടു',
  'Bu medya için imzalı bağlantı gerekli':
      'ഈ മീഡിയയ്ക്ക് ഒപ്പിട്ട ലിങ്ക് ആവശ്യമാണ്',
  'Arama hizmeti yeniden başlatılıyor, birazdan tekrar dene':
      'കോളിംഗ് സേവനം വീണ്ടും ആരംഭിക്കുന്നു; അൽപ്പം കഴിഞ്ഞ് ശ്രമിക്കൂ',
  'Puan göstergesi': 'റേറ്റിംഗ് ലെജൻഡ്',
  'İzleme İstatistiklerim': 'എന്റെ കാഴ്ച സ്ഥിതിവിവരങ്ങൾ',
  'Bir bölümü ya da filmi izlendi olarak işaretlediğinde istatistiklerin burada birikmeye başlar.':
      'ഒരു എപ്പിസോഡോ സിനിമയോ കണ്ടതായി അടയാളപ്പെടുത്തിയാൽ ഉടൻ നിങ്ങളുടെ സ്ഥിതിവിവരങ്ങൾ ഇവിടെ ശേഖരിക്കാൻ തുടങ്ങും.',
  '{} sa {} dk': '{} മ {} മി',
  'Yaklaşık ekran süresi': 'ഏകദേശ സ്ക്രീൻ സമയം',
  'İzleme serisi': 'കാഴ്ച പരമ്പര',
  'Şu anki seri': 'നിലവിലെ പരമ്പര',
  'En uzun seri': 'ഏറ്റവും നീണ്ട പരമ്പര',
  'Haftanın günleri': 'ആഴ്ചയിലെ ദിവസങ്ങൾ',
  'En çok izlediklerin': 'ഏറ്റവും കൂടുതൽ കണ്ടവ',
  'Bu dönemde izleme yok': 'ഈ കാലയളവിൽ കാഴ്ചയില്ല',
  'Paz': 'ഞായ',
  'Pzt': 'തിങ്ക',
  'Sal': 'ചൊവ്വ',
  'Çar': 'ബുധ',
  'Per': 'വ്യാഴ',
  'Cum': 'വെള്ളി',
  'Cmt': 'ശനി',
  '{} bölüm': '{} എപ്പിസോഡുകൾ',
  '{} bölüm~tekil': '{} എപ്പിസോഡ്',
  '{} kez': '{} തവണ',
  '{} kez~tekil': '{} തവണ',
  'Son {} gün · günlük': 'അവസാന {} ദിവസം · ദിവസേന',
  'Son {} gün · haftalık': 'അവസാന {} ദിവസം · പ്രതിവാരം',
  'Ekran süren, serin ve en çok izlediklerin':
      'നിങ്ങളുടെ സ്ക്രീൻ സമയം, പരമ്പര, ഏറ്റവും കൂടുതൽ കണ്ടവ',
  'Daralt': 'ചുരുക്കുക',
  'Listeyi düzenle': 'പട്ടിക തിരുത്തുക',
  'Bitti': 'കഴിഞ്ഞു',
  'Sırala': 'ക്രമം മാറ്റുക',
  'Herkese göster': 'എല്ലാവർക്കും കാണിക്കുക',
  'Başkalarından gizle': 'മറ്റുള്ളവരിൽ നിന്ന് മറയ്ക്കുക',
  'Listeden kaldır': 'പട്ടികയിൽ നിന്ന് നീക്കുക',
  'Listeden kaldırılsın mı?': 'പട്ടികയിൽ നിന്ന് നീക്കണോ?',
  'Bu yapım listeden çıkarılacak. Gizlemek istersen göz simgesini kullanabilirsin.':
      'ഈ ശീർഷകം പട്ടികയിൽ നിന്ന് നീക്കപ്പെടും. മറയ്ക്കാൻ മാത്രമാണെങ്കിൽ കണ്ണിന്റെ ചിഹ്നം ഉപയോഗിക്കുക.',
  'Sıralama kaydedilemedi': 'ക്രമം സേവ് ചെയ്യാനായില്ല',
  'Değişiklik kaydedilemedi': 'മാറ്റം സേവ് ചെയ്യാനായില്ല',
  'Kaldırılamadı': 'നീക്കാനായില്ല',
  'Popülerlik': 'ജനപ്രീതി',
  'TMDB puanı': 'TMDB റേറ്റിംഗ്',
  'Yapım yılı': 'നിർമ്മാണ വർഷം',
  'dizi.jpg puanı': 'dizi.jpg റേറ്റിംഗ്',
  'İzlenme': 'കാഴ്ചകൾ',
  'Yorum sayısı': 'അഭിപ്രായങ്ങളുടെ എണ്ണം',
  'Tüm raflara uygulanır': 'എല്ലാ ഷെൽഫുകൾക്കും ബാധകം',
  'En popüler {} yapım arasında sıralandı':
      'ഏറ്റവും ജനപ്രിയമായ {} ശീർഷകങ്ങൾക്കിടയിൽ അടുക്കി',
  'Altyazı görünümü': 'സബ്ടൈറ്റിലിന്റെ രൂപം',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık':
      'നിറം, ഫോണ്ട്, വലുപ്പം, അരിക്, അതാര്യത',
  'Bu bir örnek altyazıdır.': 'ഇത് ഒരു സാമ്പിൾ സബ്ടൈറ്റിൽ ആണ്.',
  'Ayar değiştikçe önizleme anında güncellenir.':
      'ക്രമീകരണം മാറുമ്പോൾ പ്രിവ്യൂ ഉടനെ പുതുക്കും.',
  'Yazı biçimi': 'ടെക്സ്റ്റ് ശൈലി',
  'Yazı rengi': 'ടെക്സ്റ്റിന്റെ നിറം',
  'Yazı opaklığı': 'ടെക്സ്റ്റിന്റെ അതാര്യത',
  'Yazı tipi': 'ഫോണ്ട്',
  'Yazı boyutu': 'ടെക്സ്റ്റിന്റെ വലുപ്പം',
  'Karakter ayrıtı': 'അക്ഷരത്തിന്റെ അരിക്',
  'Ayrıt türü': 'അരികിന്റെ തരം',
  'Ayrıt rengi': 'അരികിന്റെ നിറം',
  'Yok': 'ഒന്നുമില്ല',
  'Dış çizgi': 'ഔട്ട്‌ലൈൻ',
  'Gölge': 'നിഴൽ',
  'Kabartma': 'ഉയർന്നത്',
  'Oyma': 'താഴ്ന്നത്',
  'Arka plan rengi': 'പശ്ചാത്തല നിറം',
  'Arka plan opaklığı': 'പശ്ചാത്തലത്തിന്റെ അതാര്യത',
  'Arka plan yazının hemen arkasındaki dolgudur; pencere ise tüm altyazı bloğunun arkasındaki daha geniş yüzey.':
      'പശ്ചാത്തലം എന്നത് ടെക്സ്റ്റിന് തൊട്ടുപിന്നിലെ നിറമുള്ള ഭാഗമാണ്; വിൻഡോ എന്നത് സബ്ടൈറ്റിൽ ബ്ലോക്കിന് മുഴുവനായി പിന്നിലുള്ള വിശാലമായ പ്രതലമാണ്.',
  'Pencere': 'വിൻഡോ',
  'Pencere rengi': 'വിൻഡോയുടെ നിറം',
  'Pencere opaklığı': 'വിൻഡോയുടെ അതാര്യത',
  'Altyazı görünümü sıfırlansın mı?': 'സബ്ടൈറ്റിലിന്റെ രൂപം പുനഃസജ്ജമാക്കണോ?',
  'Renk, yazı tipi, boyut, ayrıt ve opaklık ayarları varsayılana döner.':
      'നിറം, ഫോണ്ട്, വലുപ്പം, അരിക്, അതാര്യത എന്നിവയുടെ ക്രമീകരണങ്ങൾ ഡിഫോൾട്ടിലേക്ക് മടങ്ങും.',
  'Altyazı görünümü varsayılana döndü':
      'സബ്ടൈറ്റിലിന്റെ രൂപം ഡിഫോൾട്ടിലേക്ക് മടങ്ങി',
  '{} indiriliyor…': '{} ഡൗൺലോഡ് ചെയ്യുന്നു…',
  'Seçince indirilir': 'തിരഞ്ഞെടുക്കുമ്പോൾ ഡൗൺലോഡ് ചെയ്യും',
  'Yazı tipi indirilemedi. Varsayılan yazı tipiyle gösteriliyor.':
      'ഫോണ്ട് ഡൗൺലോഡ് ചെയ്യാനായില്ല. ഡിഫോൾട്ട് ഫോണ്ടിൽ കാണിക്കുന്നു.',
  'Beyaz': 'വെള്ള',
  'Siyah': 'കറുപ്പ്',
  'Kırmızı': 'ചുവപ്പ്',
  'Yeşil': 'പച്ച',
  'Mavi': 'നീല',
  'Sarı': 'മഞ്ഞ',
  'Camgöbeği': 'സയാൻ',
  'Macenta': 'മജന്ത',
  'Yapım bütçesi': 'നിർമ്മാണ ബജറ്റ്',
  'Yapım bütçesi ve dünya çapında hasılat':
      'നിർമ്മാണ ബജറ്റും ലോകവ്യാപക കളക്ഷനും',
  'Dizinin yayın durumu': 'പരമ്പരയുടെ സംപ്രേഷണ നില',
  'Devam ediyor': 'തുടരുന്നു',
  'Sona erdi': 'അവസാനിച്ചു',
  'İptal edildi': 'റദ്ദാക്കി',
  'Yapımda': 'നിർമ്മാണത്തിലാണ്',
  'Planlandı': 'ആസൂത്രണം ചെയ്തു',
  'Pilot bölüm': 'പൈലറ്റ് എപ്പിസോഡ്',
  'Ad': 'പേര്',
  'Adın': 'നിന്റെ പേര്',
  'Kullanıcı adı': 'യൂസർനെയിം',
  'Kullanıcı adını değiştir': 'യൂസർനെയിം മാറ്റൂ',
  'Kullanıcı adını 90 günde bir değiştirebilirsin':
      'യൂസർനെയിം 90 ദിവസത്തിലൊരിക്കൽ മാറ്റാം',
  'Değiştir': 'മാറ്റൂ',
  '{} gün sonra değiştirebilirsin': '{} ദിവസം കഴിഞ്ഞ് മാറ്റാം',
  'Kullanıcı adın: @{}': 'നിന്റെ യൂസർനെയിം: @{}',
  'Bu kullanıcı adı zaten alınmış': 'ഈ യൂസർനെയിം ഇതിനകം എടുത്തുകഴിഞ്ഞു',
  'Bu kullanıcı adı şu an başka bir hesaba ayrılmış':
      'ഈ യൂസർനെയിം ഇപ്പോൾ മറ്റൊരു അക്കൗണ്ടിനായി കരുതിവച്ചിരിക്കുന്നു',
  'Bu zaten senin kullanıcı adın': 'ഇത് ഇപ്പോൾ തന്നെ നിന്റെ യൂസർനെയിം ആണ്',
  'Kullanıcı adı 3-20 karakter; küçük harf, rakam, nokta, tire ve alt çizgi kullanılabilir':
      'ഉപയോക്തൃനാമം 3–20; ചെറിയക്ഷരം, അക്കം, ഡോട്ട്, ഹൈഫൻ, അണ്ടർസ്കോർ',
  'Profilinde kullanıcı adının üstünde görünür. Boş bırakabilirsin.':
      'പ്രൊഫൈലിൽ നിന്റെ യൂസർനെയിമിനു മുകളിൽ കാണാം. ഒഴിച്ചിടാം.',
  'Değiştirdikten sonra 90 gün boyunca tekrar değiştiremezsin. Eski kullanıcı adın 90 gün boyunca sana ayrılır — istersen geri dönebilirsin, o sürede başkası alamaz. Eski adına giden bağlantılar artık profilini açmaz.':
      'മാറ്റിയ ശേഷം 90 ദിവസത്തേക്ക് വീണ്ടും മാറ്റാനാവില്ല. പഴയ യൂസർനെയിം 90 ദിവസം നിനക്കായി കരുതിവയ്ക്കും — വേണമെങ്കിൽ തിരികെ പോകാം, ആ സമയത്ത് മറ്റാർക്കും എടുക്കാനാവില്ല. പഴയ പേരിലേക്കുള്ള ലിങ്കുകൾ ഇനി നിന്റെ പ്രൊഫൈൽ തുറക്കില്ല.',
  'Etkinliğim': 'പ്രവർത്തനം',
  'Tercihler': 'മുൻഗണനകൾ',
  'Gizlilik ve güvenlik': 'സ്വകാര്യതയും സുരക്ഷയും',
  'Destek': 'പിന്തുണ',
  'Hesap': 'അക്കൗണ്ട്',
  '{} dizileri': '{} പരമ്പരകൾ',
  '{} filmleri': '{} സിനിമകൾ',
  'En üste taşı': 'ഏറ്റവും മുകളിലേക്ക് മാറ്റുക',
  'Sırayı sıfırla': 'ക്രമം പുനഃസജ്ജമാക്കുക',
  'Listede ara': 'ലിസ്റ്റിൽ തിരയുക',
  'Elle sıra sıfırlansın mı?': 'സ്വയം ക്രമീകരിച്ച ക്രമം പുനഃസജ്ജമാക്കണോ?',
  'Liste varsayılan sırasına (en son işaretlediğin önce) döner.':
      'ലിസ്റ്റ് സ്ഥിരസ്ഥിതി ക്രമത്തിലേക്ക് മടങ്ങും (ഏറ്റവും ഒടുവിൽ അടയാളപ്പെടുത്തിയത് ആദ്യം).',
  'Sıra sıfırlanamadı': 'ക്രമം പുനഃസജ്ജമാക്കാനായില്ല',
  'Listenin en üstüne taşındı': 'ലിസ്റ്റിന്റെ ഏറ്റവും മുകളിലേക്ക് മാറ്റി',
  'Adlar yükleniyor…': 'പേരുകൾ ലോഡ് ചെയ്യുന്നു…',
  'Afişe basılı tutup sürükle. Uzaktaki bir yapımı öne almak için "En üste taşı"yı kullan.':
      'പോസ്റ്റർ അമർത്തിപ്പിടിച്ച് വലിക്കുക. അകലെയുള്ള ഒന്ന് മുന്നിലെത്തിക്കാൻ “ഏറ്റവും മുകളിലേക്ക് മാറ്റുക” ഉപയോഗിക്കുക.',
  'Aramada sürükleme kapalı; "En üste taşı" ile öne al ({} sonuç).':
      'തിരയലിൽ വലിക്കൽ ഓഫാണ്; “ഏറ്റവും മുകളിലേക്ക് മാറ്റുക” വഴി മുന്നിലെത്തിക്കുക ({} ഫലം).',
  'Görünüm': 'കാഴ്ച',
  'En çok izlediğin filmler': 'നിങ്ങൾ ഏറ്റവും കൂടുതൽ കണ്ട സിനിമകൾ',
  'Süreler tahmindir: bölüm ~{} dk, film ~{} dk sayılır':
      'സമയം ഏകദേശമാണ്: എപ്പിസോഡ് ~{} മിനിറ്റ്, സിനിമ ~{} മിനിറ്റ് എന്ന കണക്കിൽ',
  'Bu kullanıcı adı sistem tarafından ayrılmış':
      'ഈ യൂസർനെയിം സിസ്റ്റം കരുതിവച്ചിരിക്കുന്നു',
  'Ekran süresi': 'സ്ക്രീൻ സമയം',
  "Süreler TMDB'deki gerçek bölüm ve film süreleridir":
      'സമയങ്ങൾ TMDB-യിലെ എപ്പിസോഡുകളുടെയും സിനിമകളുടെയും യഥാർത്ഥ ദൈർഘ്യങ്ങളാണ്',
  'Tüm zamanlar: {} bölüm · {} film · {}':
      'എക്കാലവും: {} എപ്പിസോഡുകൾ · {} സിനിമകൾ · {}',
  'Kabul et': 'സ്വീകരിക്കുക',
  'Reddedilenler': 'നിരസിച്ചവ',
  'İstekler': 'അഭ്യർത്ഥനകൾ',
  'Reddettiğin istek yok': 'നിരസിച്ച അഭ്യർത്ഥനകളില്ല',
  'Reddettiğin istekler burada durur; dilersen geri kabul edebilirsin.':
      'നിരസിച്ച അഭ്യർത്ഥനകൾ ഇവിടെ നിലനിൽക്കും; വേണമെങ്കിൽ വീണ്ടും സ്വീകരിക്കാം.',
  'Ne izlesem?': 'എന്ത് കാണണം?',
  'Karışık': 'മിശ്രം',
  'Çarkı çevir': 'ചക്രം കറക്കുക',
  'Tekrar çevir': 'വീണ്ടും കറക്കുക',
  'Bu türde içerik yok': 'ഈ തരത്തിലുള്ള ഉള്ളടക്കമില്ല',
  'Bütçe': 'ബജറ്റ്',
  'dizi.jpg AI özeti': 'dizi.jpg AI സംഗ്രഹം',
  'Daha fazlasını gör': 'കൂടുതൽ കാണുക',
  'Yıldız sistemi': 'സ്റ്റാർ സിസ്റ്റം',
  '{} yıldız üzerinden': '{} നക്ഷത്രങ്ങളിൽ',
  'Önizleme': 'പ്രിവ്യൂ',
  'dokununca açılır': 'ടാപ്പുചെയ്യുമ്പോൾ തുറക്കുന്നു',
  'Bir azalt': 'ഒന്ന് കുറയ്ക്കുക',
  'Bir artır': 'ഒന്ന് കൂട്ടുക',
  'Ölçek kaydedilemedi': 'സ്കെയിൽ സംരക്ഷിക്കാനായില്ല',
  'Ölçeği değiştirmek puanlarını silmez; aynı puanlar yeni ölçekte gösterilir.':
      'സ്കെയിൽ മാറ്റുന്നത് നിങ്ങളുടെ റേറ്റിംഗുകൾ ഇല്ലാതാക്കില്ല; അതേ റേറ്റിംഗുകൾ പുതിയ സ്കെയിലിൽ കാണിക്കും.',
  'En aşağıya gönder': 'ഏറ്റവും താഴേക്ക്',
  'Listenin en altına taşındı': 'പട്ടികയുടെ അവസാനത്തേക്ക് മാറ്റി',
  'Oturumun sonlandı': 'നിങ്ങളുടെ സെഷൻ അവസാനിച്ചു',
  'Bu hesabın oturumları kapatıldı ya da şifresi değişti. Devam etmek için tekrar giriş yap.':
      'ഈ അക്കൗണ്ട് എല്ലായിടത്തും സൈൻ ഔട്ട് ചെയ്തു അല്ലെങ്കിൽ പാസ്‌വേഡ് മാറി. തുടരാൻ വീണ്ടും സൈൻ ഇൻ ചെയ്യുക.',
  'Son izleme: {}': 'അവസാനം കണ്ടത്: {}',
  '{} tarihinde izledin': '{} ന് കണ്ടു',
  'Geri bildirimine yanıt verdik': 'നിങ്ങളുടെ ഫീഡ്‌ബാക്കിന് ഞങ്ങൾ മറുപടി നൽകി',
  'Bu yanıt artık görüntülenemiyor.': 'ഈ മറുപടി ഇനി കാണാനാകില്ല.',
  'Gönderdiğin geri bildirim': 'നിങ്ങൾ അയച്ച ഫീഡ്‌ബാക്ക്',
  'Dizi veya film seç (zorunlu)': 'പരമ്പരയോ സിനിമയോ തിരഞ്ഞെടുക്കുക (നിർബന്ധം)',
  'Bölüm seç (isteğe bağlı)': 'എപ്പിസോഡ് തിരഞ്ഞെടുക്കുക (ഐച്ഛികം)',
  '{}. sezon {}. bölüm': 'സീസൺ {}, എപ്പിസോഡ് {}',
  'Ne düşünüyorsun?': 'നിങ്ങൾ എന്ത് കരുതുന്നു?',
  '{}/{} yükleniyor': '{}/{} അപ്‌ലോഡ് ചെയ്യുന്നു',
  'Fotoğraf/video ekle': 'ഫോട്ടോയോ വീഡിയോയോ ചേർക്കുക',
  'Paylaşmak için önce bir dizi veya film seç.':
      'പങ്കിടാൻ ആദ്യം ഒരു പരമ്പരയോ സിനിമയോ തിരഞ്ഞെടുക്കുക.',
  'Sezon seç': 'സീസൺ തിരഞ്ഞെടുക്കുക',
  '{}. sezon': 'സീസൺ {}',
  'Bölüm seçme (yalnız dizi hakkında)':
      'എപ്പിസോഡ് ഇല്ല (പരമ്പരയെക്കുറിച്ച് മാത്രം)',
  'Sezonlar yüklenemedi.': 'സീസണുകൾ ലോഡ് ചെയ്യാനായില്ല.',
  'Bu dizide bölüm bilgisi yok.': 'ഈ പരമ്പരയ്ക്ക് എപ്പിസോഡ് വിവരമില്ല.',
  'Bu sezonda bölüm yok.': 'ഈ സീസണിൽ എപ്പിസോഡുകളില്ല.',
  '{}. bölüm': 'എപ്പിസോഡ് {}',
  'Dizi veya film ara...': 'പരമ്പരകളും സിനിമകളും തിരയുക...',
  'İzlediğin dizi ve film hakkında yorum paylaş':
      'നിങ്ങൾ കണ്ടതിനെക്കുറിച്ച് അഭിപ്രായം പങ്കിടുക',
  'Yapım seç (zorunlu)': 'ഒരു ശീർഷകം തിരഞ്ഞെടുക്കുക (നിർബന്ധം)',
  'Paylaşmak için önce bir yapım seç.':
      'പങ്കിടാൻ ആദ്യം ഒരു ശീർഷകം തിരഞ്ഞെടുക്കുക.',
  'Kişi': 'വ്യക്തി',
  'Yapım firması': 'നിർമ്മാണ കമ്പനി',
  'Yapım ara...': 'ശീർഷകങ്ങൾ തിരയുക...',
  'Çarkı çevirmek için sürükle veya dokun':
      'ചക്രം കറക്കാൻ വലിക്കുക അല്ലെങ്കിൽ ടാപ്പ് ചെയ്യുക',
  'Arşiv': 'ശേഖരം',
  'Yüklediklerim': 'എന്റെ അപ്‌ലോഡുകൾ',
  'GIF ara...': 'GIF തിരയുക...',
  'GIF yükle': 'GIF അപ്‌ലോഡ് ചെയ്യുക',
  'GIF etiketleri': 'GIF ടാഗുകൾ',
  'Virgülle ayır. Aramada bu kelimelerle bulunur.':
      'കോമ ഉപയോഗിച്ച് വേർതിരിക്കുക. ഈ വാക്കുകളിലൂടെയാണ് ഇത് കണ്ടെത്തുക.',
  'gülme, alkış, şaşkın': 'ചിരി, കൈയ്യടി, അമ്പരപ്പ്',
  'Yükle': 'അപ്‌ലോഡ് ചെയ്യുക',
  'Henüz GIF yok': 'ഇതുവരെ GIF ഇല്ല',
  'Bu aramaya uyan GIF yok': 'ഈ തിരയലുമായി യോജിക്കുന്ന GIF ഇല്ല',
  'Arşiv yeni. İlk GIF i sen yükle — sen hemen kullanırsın, onaydan sonra herkes görür.':
      'ശേഖരം പുതിയതാണ്. ആദ്യ GIF നിങ്ങൾ അപ്‌ലോഡ് ചെയ്യൂ — ഉടൻ ഉപയോഗിക്കാം, അംഗീകാരത്തിനു ശേഷം എല്ലാവരും കാണും.',
  'GIF yüklendi. Sen hemen kullanabilirsin; herkese açık arşive onaydan sonra girer.':
      'GIF അപ്‌ലോഡ് ചെയ്തു. ഉടൻ ഉപയോഗിക്കാം; അംഗീകാരത്തിനു ശേഷം പൊതു ശേഖരത്തിൽ ചേരും.',
  'Onay bekliyor': 'അംഗീകാരം കാത്തിരിക്കുന്നു',
  'GIF listesi yüklenemedi': 'GIF പട്ടിക ലോഡ് ചെയ്യാനായില്ല',
  'GIF yüklenemedi': 'GIF അപ്‌ലോഡ് ചെയ്യാനായില്ല',
  'Bu GIF i şikayet et': 'ഈ GIF റിപ്പോർട്ട് ചെയ്യുക',
  'Uygunsuz içerik yöneticiye bildirilir ve arşivden kaldırılabilir.':
      'അനുചിതമായ ഉള്ളടക്കം മോഡറേറ്ററെ അറിയിക്കുകയും ശേഖരത്തിൽ നിന്ന് നീക്കം ചെയ്യപ്പെടുകയും ചെയ്യാം.',
  'Şikayetin alındı': 'നിങ്ങളുടെ റിപ്പോർട്ട് ലഭിച്ചു',
  'Şikayet gönderilemedi': 'റിപ്പോർട്ട് അയയ്ക്കാനായില്ല',
  'Dizinin kendisi': 'പരമ്പര തന്നെ',
  'Sezon ya da bölüm seçme': 'സീസണോ എപ്പിസോഡോ ഇല്ല',
  'Tüm {}. sezon': 'മുഴുവൻ സീസൺ {}',
  'Bölüm seçme': 'എപ്പിസോഡ് ഇല്ല',
  'En fazla {} yapım ekleyebilirsin.': 'നിനക്ക് പരമാവധി {} ശീർഷകങ്ങൾ ചേർക്കാം.',
  'Bu zaten ekli.': 'ഇതിനകം ചേർത്തിട്ടുണ്ട്.',
  'Dizi, film, oyuncu ya da yönetmen etiketle — gönderin onların sayfasında da görünür.':
      'ഒരു പരമ്പര, സിനിമ, നടൻ അല്ലെങ്കിൽ സംവിധായകനെ ടാഗ് ചെയ്യൂ — നിന്റെ പോസ്റ്റ് അവരുടെ പേജിലും കാണാം.',
  'Etiket ekle': 'ടാഗ് ചേർക്കുക',
  'Dizi, film, oyuncu ya da yönetmen etiketle':
      'പരമ്പര, സിനിമ, നടൻ അല്ലെങ്കിൽ സംവിധായകനെ ടാഗ് ചെയ്യൂ',
  'Gönderiden vazgeç': 'പോസ്റ്റ് ഉപേക്ഷിക്കുക',
  'Yazdıkların kaydedilmeyecek.': 'നീ എഴുതിയത് സംരക്ഷിക്കില്ല.',
  'Yazmaya devam et': 'എഴുത്ത് തുടരുക',
  'Bulunamadı. Adın yazılışını değiştirip dene.':
      'കണ്ടെത്തിയില്ല. മറ്റൊരു അക്ഷരവിന്യാസം പരീക്ഷിക്കൂ.',
  'Dizi, film, oyuncu, yönetmen ya da yapım firması ara.':
      'പരമ്പര, സിനിമ, നടൻ, സംവിധായകൻ അല്ലെങ്കിൽ നിർമ്മാണ കമ്പനി തിരയൂ.',
  'E-posta adresini değiştir': 'നിന്റെ ഇമെയിൽ വിലാസം മാറ്റുക',
  'E-posta bağlı değil': 'ഇമെയിൽ ബന്ധിപ്പിച്ചിട്ടില്ല',
  'Geçerli bir e-posta adresi yaz': 'സാധുവായ ഒരു ഇമെയിൽ വിലാസം എഴുതുക',
  'Bu zaten hesabının e-posta adresi':
      'ഇത് ഇപ്പോൾതന്നെ നിന്റെ അക്കൗണ്ടിന്റെ ഇമെയിൽ വിലാസമാണ്',
  'Kod gönder': 'കോഡ് അയയ്ക്കുക',
  'E-posta adresin güncellendi': 'നിന്റെ ഇമെയിൽ വിലാസം പുതുക്കി',
  'Bu e-posta başka bir hesapta kayıtlı':
      'ഈ ഇമെയിൽ മറ്റൊരു അക്കൗണ്ടിൽ രജിസ്റ്റർ ചെയ്തിട്ടുണ്ട്',
  'Doğrulama kodu YENİ adrese gönderilir; adres ancak kodu girdikten sonra değişir. Şifre sıfırlama ve iki adımlı giriş kodları bundan sonra yeni adrese gider.':
      'സ്ഥിരീകരണ കോഡ് പുതിയ വിലാസത്തിലേക്കാണ് പോകുന്നത്; കോഡ് നൽകിയ ശേഷമേ വിലാസം മാറൂ. പാസ്‌വേഡ് പുനഃസജ്ജീകരണവും രണ്ടു ഘട്ട ലോഗിൻ കോഡുകളും പിന്നീട് പുതിയ വിലാസത്തിലേക്കു പോകും.',
  'Hesabındaki e-posta adresi geçerli değil, bu yüzden e-posta teslim edilemiyor. Doğru adresi bağlamak için destekle iletişime geç.':
      'നിന്റെ അക്കൗണ്ടിലെ ഇമെയിൽ വിലാസം സാധുവല്ല, അതിനാൽ ഇമെയിൽ എത്തിക്കാനാകുന്നില്ല. ശരിയായ വിലാസം ബന്ധിപ്പിക്കാൻ പിന്തുണയുമായി ബന്ധപ്പെടുക.',
  'Bu adrese kod gönderilemedi, adresi kontrol et':
      'ഈ വിലാസത്തിലേക്ക് കോഡ് അയയ്ക്കാനായില്ല, വിലാസം പരിശോധിക്കുക',
  'ya da': 'അല്ലെങ്കിൽ',
  'Google ile doğrula': 'Google ഉപയോഗിച്ച് പരിശോധിക്കുക',
  'Hesabını Google ile açtıysan şifren yoktur; kimliğini Google ile doğrula.':
      'അക്കൗണ്ട് Google വഴി തുറന്നതെങ്കിൽ നിനക്ക് പാസ്‌വേഡ് ഇല്ല; ഐഡന്റിറ്റി Google വഴി പരിശോധിക്കുക.',
  'Google doğrulaması bu hesapla eşleşmedi':
      'Google പരിശോധന ഈ അക്കൗണ്ടുമായി പൊരുത്തപ്പെട്ടില്ല',
  'Bu hesap Google ile açıldı; doğrulamak için Google ile giriş yap':
      'ഈ അക്കൗണ്ട് Google വഴി തുറന്നതാണ്; പരിശോധിക്കാൻ Google വഴി സൈൻ ഇൻ ചെയ്യുക',
  // --- 31 Agu 2026: kitaplik paylasimi + reels ceviri + sohbet detayi ---
  'Bu liste gizli': 'ഈ ലിസ്റ്റ് സ്വകാര്യമാണ്',
  'Bu kullanıcı izleme listelerini gizli tutmayı tercih ediyor.':
      'ഈ ഉപയോക്താവ് തന്റെ ലിസ്റ്റുകൾ സ്വകാര്യമായി സൂക്ഷിക്കാൻ ഇഷ്ടപ്പെടുന്നു.',
  'Bu listede henüz içerik yok': 'ഈ ലിസ്റ്റിൽ ഇതുവരെ ടൈറ്റിലുകളില്ല',
  'Otomatik çeviri': 'ഓട്ടോമാറ്റിക് വിവർത്തനം',
  'Otomatik çeviri açıldı': 'ഓട്ടോമാറ്റിക് വിവർത്തനം ഓണാക്കി',
  'Otomatik çeviri kapatıldı': 'ഓട്ടോമാറ്റിക് വിവർത്തനം ഓഫാക്കി',
  'Sohbet sessize alındı': 'ചാറ്റ് മ്യൂട്ട് ചെയ്തു',
  'Sessize alma kaldırıldı': 'മ്യൂട്ട് നീക്കി',
  'Tema özelleştir': 'തീം ഇഷ്ടാനുസൃതമാക്കുക',
  'Sohbette ara': 'ചാറ്റിൽ തിരയുക',
  'Mesajlarda ara...': 'സന്ദേശങ്ങളിൽ തിരയുക...',
  'Sonuç yok': 'ഫലങ്ങളില്ല',
  'Profili gör': 'പ്രൊഫൈൽ കാണുക',
  'Medya ve dosyalar': 'മീഡിയയും ഫയലുകളും',
  'Henüz medya yok': 'ഇതുവരെ മീഡിയയില്ല',
  'Varsayılan': 'സ്ഥിരം',
  'Mor': 'പർപ്പിൾ',
  'Pembe': 'പിങ്ക്',
  'Turuncu': 'ഓറഞ്ച്',
  'Orijinal metin gösteriliyor': 'യഥാർത്ഥ വാചകം കാണിക്കുന്നു',
  'İnternet bağlantısı yok': 'ഇന്റർനെറ്റ് കണക്ഷൻ ഇല്ല',
  'Sunucu yanıt vermedi': 'സെർവർ പ്രതികരിച്ചില്ല',
  'Güvenli bağlantı kurulamadı': 'സുരക്ഷിത കണക്ഷൻ സ്ഥാപിക്കാനായില്ല',
  'Sunucudan beklenmeyen bir yanıt geldi':
      'സെർവറിൽ നിന്ന് അപ്രതീക്ഷിത പ്രതികരണം ലഭിച്ചു',
};
